### PR TITLE
AP_Motors: Heli: Single: rework tail rotor handling

### PR DESCRIPTION
**Pull request by IamPete1**
This is a none-functional change to re-work tail rotor handling into what is hopefully easier to understand. This moves the tail types to be a enum class and uses switch statements where possible. 

Helper functions have been added to check if DDFP and direct drive var pitch.

Yaw offset had been moved to its own function. 

As usual the motors example has been updated to allow testing of different tail types, it shows no difference before vs after. 

```
Single_Heli H3 Servo_only:
        Inputs max change:
                Roll: 0.000000
                Pitch: 0.000000
                Yaw: 0.000000
                Thr: 0.000000
        Outputs max change:
                Mot1: 0.000000
                Mot2: 0.000000
                Mot3: 0.000000
                Mot4: 0.000000
                Mot5: 0.000000
                Mot6: 0.000000
                Mot7: 0.000000
                Mot8: 0.000000
        Limits max change:
                LimR: 0.000000
                LimP: 0.000000
                LimY: 0.000000
                LimThD: 0.000000
                LimThU: 0.000000


Single_Heli H3 Servo_with_ExtGyro:
        Inputs max change:
                Roll: 0.000000
                Pitch: 0.000000
                Yaw: 0.000000
                Thr: 0.000000
        Outputs max change:
                Mot1: 0.000000
                Mot2: 0.000000
                Mot3: 0.000000
                Mot4: 0.000000
                Mot5: 0.000000
                Mot6: 0.000000
                Mot7: 0.000000
                Mot8: 0.000000
        Limits max change:
                LimR: 0.000000
                LimP: 0.000000
                LimY: 0.000000
                LimThD: 0.000000
                LimThU: 0.000000


Single_Heli H3 DirectDrive_VarPitch:
        Inputs max change:
                Roll: 0.000000
                Pitch: 0.000000
                Yaw: 0.000000
                Thr: 0.000000
        Outputs max change:
                Mot1: 0.000000
                Mot2: 0.000000
                Mot3: 0.000000
                Mot4: 0.000000
                Mot5: 0.000000
                Mot6: 0.000000
                Mot7: 0.000000
                Mot8: 0.000000
        Limits max change:
                LimR: 0.000000
                LimP: 0.000000
                LimY: 0.000000
                LimThD: 0.000000
                LimThU: 0.000000


Single_Heli H3 DirectDrive_FixedPitch_CW:
        Inputs max change:
                Roll: 0.000000
                Pitch: 0.000000
                Yaw: 0.000000
                Thr: 0.000000
        Outputs max change:
                Mot1: 0.000000
                Mot2: 0.000000
                Mot3: 0.000000
                Mot4: 0.000000
                Mot5: 0.000000
                Mot6: 0.000000
                Mot7: 0.000000
                Mot8: 0.000000
        Limits max change:
                LimR: 0.000000
                LimP: 0.000000
                LimY: 0.000000
                LimThD: 0.000000
                LimThU: 0.000000


Single_Heli H3 DirectDrive_FixedPitch_CCW:
        Inputs max change:
                Roll: 0.000000
                Pitch: 0.000000
                Yaw: 0.000000
                Thr: 0.000000
        Outputs max change:
                Mot1: 0.000000
                Mot2: 0.000000
                Mot3: 0.000000
                Mot4: 0.000000
                Mot5: 0.000000
                Mot6: 0.000000
                Mot7: 0.000000
                Mot8: 0.000000
        Limits max change:
                LimR: 0.000000
                LimP: 0.000000
                LimY: 0.000000
                LimThD: 0.000000
                LimThU: 0.000000


Single_Heli H3 DDVP_with_external_governor:
        Inputs max change:
                Roll: 0.000000
                Pitch: 0.000000
                Yaw: 0.000000
                Thr: 0.000000
        Outputs max change:
                Mot1: 0.000000
                Mot2: 0.000000
                Mot3: 0.000000
                Mot4: 0.000000
                Mot5: 0.000000
                Mot6: 0.000000
                Mot7: 0.000000
                Mot8: 0.000000
        Limits max change:
                LimR: 0.000000
                LimP: 0.000000
                LimY: 0.000000
                LimThD: 0.000000
                LimThU: 0.000000
```

### CODE REVIEW

**Comment by Gone4Dirt** [comment]
Are you thinking of this as a starting PR and doing more later as incremental changes?

The reason I ask is because IMHO it would be nice if we moved tail into it's own class much like RSC and swashplate.  If we used a a backend and front end style we could sperate out the different tail types quite cleanly.  This way we could handle the params for the different tail types separately with enables (i think we have 1 level of params left which would be enough to do this>)  We could also move all of the switch case statements out of Heli_Single and into "TailRotor.cpp".

In any case, I like this rework, as it can just be a stepping stone to what I mentioned above, if others feel there is value in that?

**Comment by IamPete1** [comment]
> Are you thinking of this as a starting PR and doing more later as incremental changes?

I started off doing a class, however its not as clean as the swash stuff. Firstly because its only used for single heli there is no duplicated code. Secondly it uses params and values from motors so we would have to add hooks to get the data we need. 

On the whole I think the bigger re-work will cost a bunch of flash and have little benefit. Especially if we have to move around params.

However there are certainly tidy ups that could follow this PR.

**Comment by IamPete1** [comment]
I have added the ability to set the `COL2YAW` param and the autorotation flag from the test. I re-ran the testes with no  `COL2YAW` and no autorotation,  `COL2YAW` only and  `COL2YAW` with autorotation. As before, no change in output.

**Comment by bnsgeyer** [comment]
@IamPete1 Thanks for including COL2YAW in your tests.  Did you use a non-zero value for the COL2YAW parameter?  if so what was the value?

**Comment by IamPete1** [comment]
> @IamPete1 Thanks for including COL2YAW in your tests. Did you use a non-zero value for the COL2YAW parameter? if so what was the value?

I used 1, I figured so long as the value was not 0 any number would prove equivalence before vs after this change.

**Review by bnsgeyer — APPROVED** [review]
LGTM

**Pull request merged**
