### PR TITLE
Copter: Describing the comment to a variable that does not use the program.

### PR DESCRIPTION
**Pull request by muramura**
**cppcheck** tool message is "(style) struct or union member 'Anonymous7::value' is never used.".
However,
This variable can obtain the status of **CH12 from CH6** at a time.
Thus,
Describing the comment.

In addition, this variable is sufficient in **16-bit**.
And therefore
To change to **uint16_t** from **uint32_t**.

### CODE REVIEW

**Comment by OXINARF** [comment]
The tool is correct, it isn't used. My though is that it should be removed, but let's have @rmackay9 decide that.

**Comment by muramura** [comment]
@OXINARF Comment Thanks.
@rmackay9 
I think.
Debugging, etc., there is an advantage that you can get the state of CH12 from CH6 at a time.
Therefore, add and resize the comment.

**Comment by rmackay9** [comment]
Yes, let's remove the union and value.  Thanks for finding this!

**Comment by muramura** [comment]
@randy, Thank you for comment.
I will remove.

**Comment by muramura** [comment]
I failed to rebase.
Again, and PR.

**Pull request closed without merging**
