### PR TITLE
AP_Compass:Fixed the QMC5883 identification,add check ID

### PR DESCRIPTION
**Pull request by ljwang1102**
Before the ID identification error problem may come up,Add new check ID now.
testing in pixhawk,pixracer.Use HMC5983 and QMC5883,there is no course deflection problem.
@rmackay9 You can test about #6633 issues

### CODE REVIEW

**Comment by OXINARF** [comment]
@tridge Is it a problem that the driver does a register write operation before detection?

**Comment by OXINARF** [comment]
@ljwang1102 Do you have any documentation for registers above 0x0D? The only datasheet I can find doesn't list any register above that.

**Comment by ljwang1102** [comment]
[QMC5883 datasheet](https://www.dropbox.com/s/y74w3d4sfipps7k/QMC5883L%20Datasheet%201.0.pdf?dl=0),the 9.2.6 is chip ID register,and Manufacturer Engineer tell me that also can check ID 0x21.
If you don't write a register to reset,the chip can't communication,this is bug,and if the fisrt start QMC5883,it can start ok,Don't need to write a register.I have already feedback to the manufacturer
@OXINARF

**Comment by tridge** [comment]
@ljwang1102 did you try reading from the registers multiple times? Or dumping all registers from the device without doing the write?
we're quite worried that the write will disturb other devices if it isn't a qmc5883l
otherwise I think we will need to use COMPASS_TYPEMASK to disable the QMC5883L by default and get users to enable it if they have it. That will be inconvenient for users

**Comment by ljwang1102** [comment]
if i  do dumping all registers from the device without doing the write,it's all ok. @tridge

**Comment by tridge** [comment]
> if i do dumping all registers from the device without doing the write,it's all ok

so you can read the ID registers reliably then? Can you develop a version of the PR that does a reliable ID of the device with the write?

**Comment by ljwang1102** [comment]
@tridge @rmackay9  now start without doing the write,and add check ID 0x0C,this is a read only register.I have been in the pixhawk, pixracer tested, and tested the internal bus

**Comment by tridge** [comment]
this looks much better, thanks!

**Pull request merged**
