### PR TITLE
Handle "Reset Mission" param in DO_SET_MISSION_CURRENT command

### PR DESCRIPTION
**Pull request by nexton-winjeel**
This PR adds handling for `param2` ("Reset Mission") in the [`DO_SET_MISSION_CURRENT`](https://mavlink.io/en/messages/common.html#MAV_CMD_DO_SET_MISSION_CURRENT) command.

### CODE REVIEW

**Comment by nexton-winjeel** [comment]
Our use case for this is being able to restart a completed mission without having to exit and re-enter `AUTO` mode.

**Review by peterbarker — COMMENTED** [review]
Autotest?

This PR seems to do more than the title would imply.

**Comment by nexton-winjeel** [comment]
> Autotest?
> 
> This PR seems to do more than the title would imply.

@peterbarker: I've added some autotests to test the chaned behaviour.

**Comment by nexton-winjeel** [comment]
@peterbarker: The changes to `AP_Mission` also partially address #18561.

**Comment by nexton-winjeel** [comment]
Fixed `flake8` compliance.

**Review by tridge — APPROVED** [review]

**Pull request merged**
