### PR TITLE
modules: fix DroneCAN/libcanard to point back at its master

### PR DESCRIPTION
**Pull request by magicrub**
This fixes a git hash submodule remote mixup.

PR https://github.com/dronecan/libcanard/pull/10 was merged and then https://github.com/ArduPilot/ardupilot/pull/21459 merged but it was pointing at the PR author's branch repo, not master.
This moved the head back to dronecan/libcanard:master which is a non-functional change for DroneCAN but will now be correctly found by repo owners who don't have the author's repo as a remote.

Before this fix, this is is what a ```git submodule update recursive force``` would show. Somehow, a fresh checkout of ardupilot/ardupilot doesn't show that submodule error.
image

### CODE REVIEW

**Comment by magicrub** [comment]
Any releases that have forked after PR https://github.com/ArduPilot/ardupilot/pull/21459 was merged on August 15, 2022 need this PR backported.

**Comment by tridge** [comment]
@magicrub this isn't a non-functional change, but I think it is correct. This PR has the effect of adding this commit:
https://github.com/dronecan/libcanard/commit/f646cdd9345c79b2d144056dcce0fd342a3da12f
which fixes the sign of some error returns. Looks like Sids PR reverted that change?

**Review by tridge — APPROVED** [review]

**Comment by magicrub** [comment]
ahh dang, you're right! Not sure how I didn't see that. This does add two additional commits that merged into master while that other PR was pending.
image

**Comment by magicrub** [comment]
@tridge and I talked about the backport and a more simple solution is to just bring those commits from the other PR into a branch on the DroneCAN repo. SO, now we have this branch https://github.com/dronecan/libcanard/tree/git-ref-fix so at least there wont' be any reference problems and thus don't need to backport to 4.3.x releases.

**Pull request merged**
