### PR TITLE
AP_RangeFinder: Delete unused definitions

### PR DESCRIPTION
**Pull request by muramura**
I have very undefined definitions, so I would like to delete them.

### CODE REVIEW

**Comment by WickedShell** [comment]
I'd rather we kept these. It can be useful when someone else tries to extend the driver in the future, and by having them listed it's less likely that someone will try and assign the same value to a different name in the future.

**Comment by muramura** [comment]
agree with not deleting it for the future.
I would like to indicate that it is invalid by commenting out in this case.
This is one of the ways that we are doing business software development.
I processed the commented out, but the edia changes color. For example, eclipse, VSC and so on. .

ddd

**Comment by magicrub** [comment]
These should stay in. It's best to document the driver as much as possible

**Comment by muramura** [comment]
@WickedShell san, @magicrub san...
I understand. Thank you.

**Pull request closed without merging**
