### PR TITLE
APMrover2: AP_MotorsUGV: Add support for H-Bridge with 2 relay pins f…

### PR DESCRIPTION
**Pull request by juvinski**
AP_MotorsUGV: Add a new PWM type: Add support for H-Bridge with 2 relay pins for direction
                         Logic to apply a reverse value on the next relay pin.
			 There is support for 3 motors in this version.

I will create a discuss in how to setup this to use it.
I tested with L298 and TB6612 on a skid sterring with 2 motors.

The motor1 will use relay pins 1 and 2 to control
the direction. 
The motor 2 will use relay pins 3 and 4 to control the direction.
The motor 3 will use relay pins 5 and 6 to control the direction.

I create a mechanism to brake the motors while the
speed are between 10 and -10 - even in the idle position of the stick the motors keep running, so via code I made this stop mechanism.

I don't know what to do in case of vehicles with 4 motors because we
just have 6 relay pins on pixhawk - I think a method to count the number of aux relay pins are needed to avoid setting a value to an nonexistent relay pin.

There are a strange behavior steering I detected during my tests and if someone can help will be welcome. 
If the throttle are in the maximum forward and I tried to steering to left, everithing is fine, the right motor decrease and the vehicle turn. If I tried to steering to the right, the right motor keep the throttle and the vehicle don't turn. If I decrease the throttle a little (25%) the sterring work fine.
If I'm in the backward, everything works fine.
I tested only in manual mode.

### CODE REVIEW

**Comment by amilcarlucas** [comment]
Please squash both commits

**Comment by khancyr** [comment]
Hello,

Thanks for the contribution.
I am not sure that we need to merge this for numerous reason : 
- L298 clones that we can buy aren't reliable nor good controlers ... there are numerous better choice with better control for 1-2$ more.
- This change bring only a special case and not the full control of the H-drive. We still miss active breaking and freewheel mode but that would be a pain to manage with our architecture.
- This use 2 relay for one command, one relay beeing the opposite of the other. A better change would be to have a mirror option on AP_Relay, that would allow for simplier controler. The same behavior can also be acheived with some sub $ logic chips (XOR gate)

About the second change on low throttle, it need to be on another commit but I think the solution shouldn't be here in order to not bypass the control loop: see some explanation here https://github.com/ArduPilot/ardupilot/pull/7249

**Comment by juvinski** [comment]
> Please squash both commits

I think I made something wrong because tryting to squash I was forced to merge the 2 commits.
:(

**Comment by juvinski** [comment]
Hi @khancyr 

I agree with you abour the L298 - is not the best option, the concepts and power consuption is from another age, but the TB6612 is a good option. What controller do you know I can use ?
My first try before changing the code was a simpler inverter (cd4066) and everything was fine except there are no zero throttle ( even with the stick in the middle position) the motors was spinning, to I had to implement by code this "zero throttle".
I was studing the code and the breaking and freewheel mode is really a problem because the logical involved, as I can see, will require a lot of work to be done.

**Comment by peterbarker** [comment]
@juvinski are you still interested in pushing this in?  @khancyr identifed several things that would need to be fixed for this to go in - most notably full h-bridge control.

@khancyr full h-bridge control might allow people to convert their random rovers to using ArduPilot, which would be nice.  There are probably a lot of L298N-based things out there.

**Comment by juvinski** [comment]
Hi @peterbarker 
I don't know if this is a specific development for my case or there are more people interested in this feature.

**Comment by juvinski** [comment]
> @juvinski are you still interested in pushing this in? @khancyr identifed several things that would need to be fixed for this to go in - most notably full h-bridge control.
> 
> @khancyr full h-bridge control might allow people to convert their random rovers to using ArduPilot, which would be nice. There are probably a lot of L298N-based things out there.

I’m very interested on the comments I tried the same code with tb6612 and this is a better choice than lm and is working as is.

**Comment by heeplr** [comment]
Hi! 
I'm pretty new to ardupilot and was quite surprised that [H-Bridge](https://en.wikipedia.org/wiki/H-bridge) circuits are not already supported. They are omnipresent and almost all arduino projects use them to control bi-directional brushed or stepper motors.

> There are a strange behavior steering I detected during my tests

Can't confirm that. Turning at full throttle with skid steering works for me. (The only thing I noticed, full throttle turns will only block one track, not reverse it. Thusly, turn radius is larger than it needs to be but I guess that's not an issue of this PR and probably a configuration problem).

> L298 clones that we can buy aren't reliable nor good controlers

I can't confirm that. Although they're dated, they're still widely used and rock solid when used within specs. Not being controllers but just simple drivers also eliminates a ton of complexity which is nice when you don't need the features of a modern ESC.

> This change bring only a special case and not the full control of the H-drive. We still miss active breaking and freewheel mode but that would be a pain to manage with our architecture.

Maybe the active breaking and freewheel mode could be controlled by the [ATC_BRAKE](https://ardupilot.org/rover/docs/parameters.html#atc-brake-speed-control-brake-enable-disable) parameter? The current hardcoded "always brake when throttle < abs(10)" mode is not desired when someone needs their wheels to run free when idle.

I'd love to see support for this in master.

**Comment by DroneMang** [comment]
Is https://github.com/juvinski/ardupilot/tree/RoverBridgeDualRelayPins or this version on this page supported yet in master or the beta firmwares? I want to use the L298N driver with rover and 2 12v motors. Thanks!

**Comment by DroneMang** [comment]
> > @juvinski are you still interested in pushing this in? @khancyr identifed several things that would need to be fixed for this to go in - most notably full h-bridge control.
> > @khancyr full h-bridge control might allow people to convert their random rovers to using ArduPilot, which would be nice. There are probably a lot of L298N-based things out there.
> 
> I’m very interested on the comments I tried the same code with tb6612 and this is a better choice than lm and is working as is.

I'm trying to get ardurover working with the tb6612, @juvinski seems like you got it working.  How did you get it to work?  It seems to me from the pinout to require just as many pins for the relay as the L298.  Thanks!

**Comment by juvinski** [comment]
hi @DroneMang 

The basic principle for this is, you need 2 relay pins per motor - to control the direction and a forced break when throttle gimbal is in the middle position.

**Pull request closed without merging**
