### PR TITLE
Use script to setup custom copter tailsitter frame

### PR DESCRIPTION
**Pull request by kd0aij**
@rmackay9 LUA bindings seem to work correctly
Still need to define a custom frame type

### CODE REVIEW

**Comment by rmackay9** [comment]
This is looking pretty interesting and I'm happy with the approach.

A few small things that you may already have thought of:

- I think the get and set functions should affect the roll, pitch and yaw factors all at once.  And the setter should return a boolean (true if successful)
- I think the scripts should only be able to update the factors if the FRAME_TYPE has been set to "Custom" (a new frame) and then we should ensure that a pre-arm check fails if the frame-type is set to "Custom" and no factors have been set yet.

**Comment by kd0aij** [comment]
Thanks Randy. I changed the approach to use add_motors_raw instead of directly accessing the RPY factors, and was able to write a script which sets up a quad with contra-rotating boost motors.
The script checks frame_type, but there is no other checking yet.

This only works for the QUAD frame class right now, I modified setup_motors to indicate success if the frame_type is CUSTOM and exit without adding any motors, on the assumption that the script would do that. The script only adds motors if it sees frame_class==quad and frame_type==custom.

What do you think of restricting this custom frame script option to AP_MotorsMatrix? 
It doesn't seem to make much sense for the other AP_Motors subclasses.

**Comment by kd0aij** [comment]
The rover build is failing because it doesn't link AP_Motors, and lua_generated_bindings.cpp now references the AP_Motors and AP_MotorsMatrix singletons...

**Comment by kd0aij** [comment]
AP_Motors isn't part of the common_vehicle_library, and adding it to the antennatracker build increases the binary text/total size by over 300,000 bytes

**Comment by davidbuzz** [comment]
i was reviewing this PR and i was thinking about vehicles with tilting arms, such as tri-copters where one of the motor/s can have variable yaw, and other more complicated vehicles where multiple arms might be setup that way.... does this script support that sort of configuration.?

**Comment by kd0aij** [comment]
AP_Motors doesn't know about tilting motors, that is handled for quadplanes in Plane/tiltrotor.cpp 
It uses AP_MotorsMatrix for motor control in VTOL modes, but AP_MotorsMatrix doesn't support tricopters. 
Tricopters are handled by AP_MotorsTri, which is hardwired for the standard tricopter frame. So I think you would have to generalize it if you wanted more general support for yaw tilt servos.  But that kind of generalization would probably best be done by extending AP_MotorsMatrix to include the concept of tilting motor(s) for yaw control.  
So no, there aren't currently any knobs for a script to turn in order to specify a frame type with arbitrary "yaw tilt servos" for motors.
How much incentive is there for this kind of frame?

**Comment by davidbuzz** [comment]
> How much incentive is there for this kind of frame?

 I'm sitting in an office now with quite a number of large multirotors with tilting arms (between 4-8 of them actually), and for now, they run customised ardupilot because MotorsMatrix can't do what they do... and of course if the MotorsMatrix supported this out-of-the-box then the custom Tricopter tweaks could be removed as well as it could then use MotorsMatrix.   So there's certainly at least 2 use-cases for having 'tilt' support, possibly more.

**Comment by kd0aij** [comment]
> for now, they run customised ardupilot

Where is that branch?  Sounds like all you need to do is generate a PR from it.

**Comment by kd0aij** [comment]
@davidbuzz What's the weight penalty for the tilting mechanisms used to generate yaw torque?
What percentage of hover thrust does it represent?

**Comment by davidbuzz** [comment]
The vehicles we r flying use tilt instead of reversing  the engine rotation,  and are a pretty unique configuration, but its basically the weight of a large servo and relevant aluminium mounts

**Comment by kd0aij** [comment]
@WickedShell Have you decided yet how to handle the issue that some vehicles don't link AP_Motors?
Is there anything I can do to help?

**Comment by kd0aij** [comment]
@davidbuzz I guess the issue you raised about rotating motor arms for yaw control should become an enhancement request for AP_MotorsMatrix. Can you point me at the code that supports that?

**Comment by kd0aij** [comment]
@WickedShell  ping

**Comment by IamPete1** [comment]
Maybe I should pull the binding gen changes out to a different PR

**Comment by kd0aij** [comment]
I guess that depends on whether this PR is worth saving.

**Comment by IamPete1** [comment]
I was just thinking it would make it easier to get one or other of them in

**Comment by kd0aij** [comment]
Stale

**Pull request closed without merging**
