### PR TITLE
solution to TECS height rate demand spikes due to setting target altitude to soon

### PR DESCRIPTION
**Pull request by kniuk**
This is solution to bug described in #19189.

### CODE REVIEW

**Comment by kniuk** [comment]
Here is a plot ilustrating that spikes are gone.
landing_dhdem_spikes_corrected

**Comment by kniuk** [comment]
It is worth noting that spikes might not be so clearly visible in actual AP code, because it applies much more filtering to demanded height than I am using on my builds.

**Comment by samuelctabor** [comment]
Interesting @kniuk . Certainly looks like an improvement although in the sim I don't see the TECS.dhdem spikes you originally identified. 

These results are from the landing phase of the "MainFlight" autotest.

Old - 

image

New - 
image

Old - 
image

New - 
image

**Comment by kniuk** [comment]
@samuelctabor dhdem is calcuated from hdem, actually in AP_TECS::_update_height_demand it look like this:
_hgt_rate_dem = (_hgt_dem_adj - _hgt_dem_adj_last) / 0.1f;
You won't be able to see those spikes which huge averaging applied to hgt_dem earlier in that method (actually twice!). I noted that in my post scriptum.

**Comment by samuelctabor** [comment]
@kniuk yes makes sense. Removing the spikes in TEC2.hdem1 is a good improvement.

**Review by tridge — APPROVED** [review]

**Comment by tridge** [comment]
nice work, thanks!

**Pull request merged**
