### PR TITLE
Tools: add blue and bbbmini to firmware server

### PR DESCRIPTION
**Pull request by khancyr**
request from https://github.com/ArduPilot/ardupilot/pull/19600

### CODE REVIEW

**Comment by drtrigon** [comment]
Can I help with something in order to get this one merged soon?

**Comment by drtrigon** [comment]
As noted in the inital pull request: `[...] meanwhile we had the opportunity to test them and they do work for us as expected!`

**Review by hendjoshsr71 — APPROVED** [review]
LGTM

**Comment by nkruzan** [comment]
I'd also like to see this get merged.

**Review by nkruzan — APPROVED** [review]
tested blue and bbbmini on my local instance of custom build server. works (blue output below)
custombuild-blue

**Review by tridge — APPROVED** [review]

**Comment by drtrigon** [comment]
This is great! Thanks a lot to everybody involved!

**Pull request merged**
