### PR TITLE
WIP: AP_Airspeed: Blending of several sensors V2

### PR DESCRIPTION
**Pull request by EShamaev**
Second version based on issues raised by @WickedShell 

Main changes are:
- minimum EKF speed to enable health determination
- good/bad delay to prevent erratic behaviour

### CODE REVIEW

**Comment by EShamaev** [comment]
image

Takeoff and flight with 15 m/s wind, changing wind 15->5->15, changing directions 0->180->0, turbulence up to 5.

[00000041.zip](https://github.com/ArduPilot/ardupilot/files/1799376/00000041.zip)

**Comment by EShamaev** [comment]
@priseborough Can you please clarify why wind fusion (and airspeed from sensors as well) is disabled while we are on the ground?
`NavEKF2_core::setWindMagStateLearningMode()` in control.cpp

**Comment by priseborough** [comment]
Because air speed measurements on ground are highly unreliable  due to unknown orientation wrt wind. Also zero sideslip assumption cannot be used.

**Comment by OXINARF** [comment]
Needs to be rebased on master and have submodule changes removed.

**Comment by EShamaev** [comment]
Not only rebased. Due to "recent" changes, I will update this completely.

**Comment by IamPete1** [comment]
@EShamaev We now have EKF affinity for airspeed, is this PR something you would still like to take forward?

**Comment by davidbuzz** [comment]
superceded by ekf lanes

**Pull request closed without merging**
