### PR TITLE
Frame_params: Solo dynamic and static notch filter parameters

### PR DESCRIPTION
**Pull request by Pedals2Paddles**
Adds the dynamic harmonic notch filter and static notch filter to the Solo's default parameters.  Tested with the stock Pixhawk 2 cube and a CubeOrange with the same functional results.  The results therefor should functionally be the same regardless of stock, CubeBlack, CubeGreen, CubeOrange, etc.

This also allows the PID tuning to be significantly tightened up. So new PID parameters are included as well.

This makes a very dramatic difference in flight stability.  Well done Andy, Leonard, and everyone that made these notch filters possible.

### CODE REVIEW

**Comment by Pedals2Paddles** [comment]
This is ready for merge and should be backported to Copter 4.0 for R3

**Comment by rmackay9** [comment]
Merged, thanks!  I'll backport this to Copter for the next release candidate.  I suspect that will be late next week

**Comment by Pedals2Paddles** [comment]
Thanks!

**Comment by Saijin-Naib** [comment]
**F***** **yes!** I've been watching this going into BetaFlight with the 4.x release and thinking how much ArduPilot would benefit from this type of filtering.

Do you guys have any thoughts/eyes-on the bi-directional DSHOT for ArduPilot to help even further?
Still very young/WIP for BetaFlight, but looks insanely promising.
https://jflight.net/index.php?route=information/information&language=en-gb&information_id=8

**Comment by Saijin-Naib** [comment]
Matt,

Any difference in resonances with/without gimbal attached, or was that part of your Solo1/Solo2 A-B testing you cited above?

**Comment by andyp1per** [comment]
@Saijin-Naib bi-dir dshot is on the list. However, we already support BLHeli telemetry which a surprising number of small copter ESC's support.

**Comment by Pedals2Paddles** [comment]
All my testing was with the gimbal.  At some point I will try it with the fixed mount, but I'm not anticipating a difference that will impact the filters.

**Comment by rmackay9** [comment]
@andyp1per, I've been thinking that we should restructure all the drivers for ESCs that provide feedback (KDECAN, ToshibaCAN, UAVCAN, BLHeli) so that the vehicle code can just ask for rpm (or something) and get it regardless of which is being used.  This isn't exactly on my to-do list yet but I'm thinking about it.

P.S. this is probably the wrong place to discuss but .. what the heck..

**Comment by andyp1per** [comment]
@rmackay9 - yes, I was wondering when you would ask something like that. I saw you working on the Toshiba ESC's incl telemetry and was thinking "that's not going to work with the notch" :)

Yes I agree.

**Comment by AndKe** [comment]
I can imagine this improving a lot on our bigger planes with IC propulsion (5m wingspan).

**Comment by rmackay9** [comment]
this has been added to Copter-4.0.0-rc3

**Comment by jkohfel** [comment]
Hi.  

1.  I updated to Open Solo 4-dev and tried to install RC2, but it failed.  (Should I do a factory reset?) 
2.  How do I update my Solo to this RC3 code?

Thank you!

**Comment by Pedals2Paddles** [comment]
> Hi.
> 
> 1. I updated to Open Solo 4-dev and tried to install RC2, but it failed.  (Should I do a factory reset?)
> 2. How do I update my Solo to this RC3 code?
> 
> Thank you!

Please post support questions in the various forums and facebook group for the Solo.

**Pull request merged**
