### PR TITLE
AP_Baro_KellerLD : update pressure offset value based on sensor mode

### PR DESCRIPTION
**Pull request by shiv-tyagi**
This fixes the issue #18968. 
Earlier we were directly setting the _p_mode_offset property based on sensor mode, which is wrong. When in PR-mode, the offset needs to be regularly updated with the value of pressure inside the vent.
Now, we first set a property `_p_mode` with the mode we were getting from the device (we now have an enum for sensor modes) and then set or update the `_p_mode_offset` as required.

### CODE REVIEW

**Comment by hendjoshsr71** [comment]
Those (-1bar) and  (0bar) are the minimum possible pressure readings, not
the offsets. If you look under Section 4.2 you can see that.

Yes, the sensor is a differential sensor so it reads the pressure
difference between the outside (AKA underwater for sub) and its reference
pressure. The reference pressure is either: vacuum [0bar] (an absolute
sensor), 1 atmosphere (gauge), or the current internal pressure (vented).

But we need to return to the system the actual pressure outside AKA
referenced to vacuum. So we need to add the offsets.

**Comment by shiv-tyagi** [comment]
> Those (-1bar) and (0bar) are the minimum possible pressure readings, not the offsets. If you look under Section 4.2 you can see that. Yes, the sensor is a differential sensor so it reads the pressure difference between the outside (AKA underwater for sub) and its reference pressure. The reference pressure is either: vacuum [0bar] (an absolute sensor), 1 atmosphere (gauge), or the current internal pressure (vented). But we need to return to the system the actual pressure outside AKA referenced to vacuum. So we need to add the offsets.
> […](#)

Yes, thanks for correcting me. I got it.

**Comment by peterbarker** [comment]
> Note there is another PR [here](https://github.com/ArduPilot/ardupilot/pull/18126) that will likely conflict with these changes.

Sadly that one already conflicts in a confusing way when rebasing against master :-(

We really need a simulator for this device.

**Comment by hendjoshsr71** [comment]
> > Note there is another PR [here](https://github.com/ArduPilot/ardupilot/pull/18126) that will likely conflict with these changes.
> 
> Sadly that one already conflicts in a confusing way when rebasing against master :-(
> 
> We really need a simulator for this device.
Yes... but probably isn't the device for the top of the list ... for that 

I think i already had a hand at rebasing that PR of yours [here](https://github.com/hendjoshsr71/ardupilot/tree/rev/keller_init_cleanup).  But... it seems I accidentally deleted it from everywhere mehhh

**Review by Williangalvani — APPROVED** [review]
Lgtm.

Just tested on a Bar100 (PA-L7D) and it works the same, as expected.

**Pull request merged**
