### PR TITLE
fix bebop rangefinder

### PR DESCRIPTION
**Pull request by jberaud**
Still a solution needs to be found for reliably linking against libiio with the appropriate toolchain and libc

### CODE REVIEW

**Comment by rmackay9** [comment]
I'm not qualified to judge the waf change so I've left it but merged the range finder fix.  Maybe this PR could be rebased on master?  Sorry to only pull in half but I figured that was better than risking the fix getting stuck.

**Comment by khancyr** [comment]
Static linking should have been fixed on master now ! Could you rebase ?

**Comment by jberaud** [comment]
This is not related to static linking but to linking against external shared libraries.

**Comment by khancyr** [comment]
I have the recent fix for bebop rangefinder in https://github.com/ArduPilot/ardupilot/pull/11365 .
could you redo the PR with only the modification for the waf ?

**Comment by lucasdemarchi** [comment]
@jberaud sorry for the delay. Merged, thanks.

**Pull request closed without merging**
