### PR TITLE
Map flight modes to their mavlink representations

### PR DESCRIPTION
**Pull request by WickedShell**
This is intended to allow ground control stations to have a direct enum to use when interpreting the `custom_mode` of heartbeat, as well as when requesting the vehicle change to a given flight mode. This could be done as pure MAVLink without changing the headers, however by forcing the `defines.h` to all match we ensure a consistent representation (and hint to people to update the mavlink xml files when they add new flight modes)

Loosely implements #3788 and is probably as good as we can ever get on that without breaking backwards compatibility with GCS's which is not worth it.

### CODE REVIEW

**Comment by amilcarlucas** [comment]
I like this, It removes hardcoded values from the GCS source code.

**Comment by WickedShell** [comment]
I'm less pigheaded on this side but the MAVLink commit needs to happen. Currently GCS's are expected to look up the define.h file in the ArduPilot source if they want to understand the modes. It makes new GCS creation extremely challenging, and means that a GCS must self maintain a table we should be providing. The remapping our enum to that one was just meant to be an error checking/enabler. (This is why I tagged it as dev call though so it can have more/proper discussion)

**Comment by amilcarlucas** [comment]
We have our own mavlink fork. I'm fine with having to change the mavlink xml file.

**Comment by WickedShell** [comment]
Chasing just the MAVLink XML changes and closing this part.

**Pull request closed without merging**
