### PR TITLE
AP_VideoTX:add additional freq bands(RushFPV 3.3GHz)

### PR DESCRIPTION
**Pull request by zvldz**
Add additional freq bands(RushFPV 3.3GHz)

### CODE REVIEW

**Comment by zvldz** [comment]
@andyp1per 
Please approve

**Review by andyp1per — APPROVED** [review]

**Comment by Hwurzburg** [comment]
which product uses this?

**Comment by andyp1per** [comment]
> which product uses this?

I assume its the one in the title?

**Comment by zvldz** [comment]
> which product uses this?

https://rushfpv.net/products/3-3g-2w-vtx-transmitter-module-%E5%A4%8D%E5%88%B6?variant=46120333246634

**Comment by zvldz** [comment]
@andyp1per 
Can this PR be added to the 4.5 branch ?

**Pull request merged**
