### PR TITLE
AP_Compass: fix example

### PR DESCRIPTION
**Pull request by kwikius**
Update example with BoardConfig

### CODE REVIEW

**Comment by magicrub** [comment]
Closed accidentally when 2-3 days had passed and not merged. This is still a valid PR.

**Comment by magicrub** [comment]
Branch was also deleted so I'm unable to reopen.

**Comment by OXINARF** [comment]
Just to clarify that @kwikius has said multiple times in Gitter that he closed this (and multiple other PRs) intentionally (because he didn't get an answer in two days...).

**Comment by kwikius** [comment]
These files are all merged on this branch now.
https://github.com/kwikius/ardupilot/tree/aerflite
They are also available to read in this PR FWIW. 2 files 2 lines

**Pull request closed without merging**
