### PR TITLE
Tools: Change MOT_THST_HOVER params to 0.5

### PR DESCRIPTION
**Pull request by patrickelectric**
The ROVs are mainly neutrally buoyant, 0.5 represents an accurate value for real live vehicles
Tested with BlueROV2 and BlueROV2-heavy 
@Williangalvani can confirm this tests

### CODE REVIEW

**Comment by jaxxzer** [comment]
I believe the ideal solution is for this parameter to have no effect on Sub, as it was in the past.

@Williangalvani There appears to be some regression because you will find that on 3.5, the value of this parameter has no effect.

**Comment by patrickelectric** [comment]
Why not use it correctly instead ? Such particularities are hard to track and maintain, also make ArduSub more singular in ArduPilot code base. I'm not a big fan of such approach.

**Comment by jaxxzer** [comment]
0.5 does makes sense when the vehicle is neutral. How much does changing the buoyancy change the response of the vehicle when the parameter is applied like this?

We shouldn't assume the buoyancy of the vehicle, and I do not want the user to have to change the parameter or ask why their vehicle behaves differently each time they adjust the buoyancy.

We have had stable consistent behavior since the first release. When the parameter takes effect, you will see crazy undesirable and confusing results (as @patrickelectric and @Williangalvani have observed). 

This parameter is not helpful to us like it is for copter, so my opinion has always been that it is better if the parameter did not exist for sub at all. Since that is not an option at the moment, it is better if it has no effect.

If we do apply this, we will also need to consider people's old parameters who are upgrading, and the default value for the firmware. (this patch only affects sitl).

**Comment by patrickelectric** [comment]
@jaxxzer since it's not used, I'm removing the parameter from our files.

**Comment by tridge** [comment]
i'm not sure what the conclusion is? should the lines be removed?

**Comment by jaxxzer** [comment]
@Williangalvani let's review this together.

**Comment by jaxxzer** [comment]
These files are automatically generated. They should not be manuallly edited.

It's not broken, there's nothing to fix.

**Comment by jaxxzer** [comment]
@patrickelectric try here: https://github.com/ArduPilot/ardupilot/blob/master/ArduSub/Parameters.cpp#L702

**Pull request closed without merging**
