### PR TITLE
modify NavEKF2 for AHRS Test

### PR DESCRIPTION
**Pull request by jinchengde**
AHRS_Test: Modify to NavEKF2 for AHRS Example

### CODE REVIEW

**Comment by magicrub** [comment]
I'm not really sure what the AHRS_Test thing does. Anyone have any insight on it?

**Comment by jinchengde** [comment]
@priseborough 
could you help to provide some EKF2 test code for ARHS Test?

**Comment by magicrub** [comment]
What purpose does it serve?

**Comment by priseborough** [comment]
If I want to test the EKF, I use SITL and check the EKF log data. I also use replay of sensor data from a flight. I have never used this AHRS test harness before.

**Comment by magicrub** [comment]
I'm not a fan of committing dead code so @jinchengde please tell us how you use this. Otherwise I'll close this.

**Comment by jinchengde** [comment]
@magicrub 
Here is a project that we used pixhawk to provide AHRS reference to another flight control with navigation function through serial port.

**Comment by magicrub** [comment]
Link?

**Comment by jinchengde** [comment]
yes, serial port, pixhawk provide the AHRS reference in 10Hz

**Comment by magicrub** [comment]
.....?

**Comment by OXINARF** [comment]
This isn't a test, this is an example - an old one though. I don't like the changes very much, it inserts a dummy vehicle that looks unnecessary. It also changes the baro variable name without any reason I can see. On the other hand, it shouldn't hurt to bring this in.

In any case the commit message doesn't follow our format and needs to be changed.

**Pull request merged**
