### PR TITLE
Cope with negative ESC rpms in notch filter

### PR DESCRIPTION
**Pull request by andyp1per**

### CODE REVIEW

**Comment by RickReeser** [comment]
@andyp1per The test flight that caused me to open the issue was done on Copter 4.5.6. Master has a different behavior: the logged filter frequency is negative for notches that are tracking negative RPM. I haven't read through the code enough yet to know what the filter is actually doing in this case. This is what it looks like on master:
image

With your changes:
image

**Comment by andyp1per** [comment]
It doesn't look quite right, does it. We have made some effort to properly log what values are actually being used.

**Comment by andyp1per** [comment]
Actually, maybe it does look right. I'm just a little thrown by the weird symmetry of the ESC values - I wonder if there is something else going on there. Unless this is just split yaw.

**Comment by RickReeser** [comment]
Yeah I think it is fine. The symmetry is because the drone was yawing at the time (uncommanded; bad tune because this was default tuning params).
image

Here are the logs from the above screenshots.
[negative rpm test flights.zip](https://github.com/user-attachments/files/17267598/negative.rpm.test.flights.zip)

**Comment by andyp1per** [comment]
great!

**Comment by IamPete1** [comment]
My preference would be to just apply the abs in the ESC RPM method. Just so that -1 for a static notch still results in off rather than 1hz. -1 makes no sense for many of the sources.

**Comment by andyp1per** [comment]
IDK, this feels safer preventing negative numbers ever reaching the notches

**Review by tridge — APPROVED** [review]

**Comment by tridge** [comment]
@IamPete1 i'm OK with this change, but will delay merge for you to expand on your comment

**Comment by tridge** [comment]
discussed on the EU dev call, decided this is good for now

**Pull request merged**
