### PR TITLE
autotest : Update receive

### PR DESCRIPTION
**Pull request by RuffaloLavoisier**
recieve -> receive

### CODE REVIEW

**Review by nkruzan — APPROVED** [review]
LGTM

**Review by peterbarker — APPROVED** [review]
Could do better on the descriptions in the commit message e.g. `autotest: correct spelling on receive`

**Comment by peterbarker** [comment]
Merged, thanks!

**Comment by RuffaloLavoisier** [comment]
> Could do better on the descriptions in the commit message e.g. `autotest: correct spelling on receive`
@peterbarker 
I will reflect it in the next Pull request commit. Thank you for your opinion.

**Pull request merged**
