### PR TITLE
Tools: add set -x to install-prereqs scripts

### PR DESCRIPTION
**Pull request by peterbarker**
Add additional verbose output to scripts

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
> If someone is running these scripts than they won't be scared by
> the amount of output

humn... the reasoning here seems to be the opposite of what this commit is accomplishing?

**Comment by OXINARF** [comment]
I agree with Lucas, this will output more output, not less. And for this script I think less output is the best. We may have to do a better job at reporting when something goes wrong.

**Comment by khancyr** [comment]
and adding a simple DEBUG parameter that do set -x , that way the script stay as usual but when people got problem it output all ?

**Comment by peterbarker** [comment]
@lucasdemarchi I've reread my comment a few times now.  It *is* increasing the output, and I'm stating that that won't scare users.  I disagree with @OXINARF here - I think more output is better.

I'm saying that if someone is wanting to develop for ArduPilot then they *won't* be scared by the amount of output that adding `-x` accomplishes.  And when someone has issues (like they did last night) when the script stops outputting anything then it makes support much easier.

But then, there's a reason I made a PR for this rather than just pushing the change in - because I thought other people might have a different opinion on the matter.

Do people really think that the "-x" output is going to scare people off?!

**Comment by magicrub** [comment]
how much more? This should be an easy A-B test on Travis raw output.

**Comment by lucasdemarchi** [comment]
I actually don't mind adding -x. But I still think you need to rephrase your commit message :) I read it again and again and it still looks bad.... It looks like you are saying, in a short version.... "add -x so people are not scared by the amount of output"

**Comment by magicrub** [comment]
I think Peter needs to apply this PR to every PR he submits, he could use a little more verbose PR descriptions :)

I updated his initial PR message, but the commit message should also change to be something more useful. If we all agree that the code is OK then someone just change the commit message and shove this into PR and get on with it.

**Comment by OXINARF** [comment]
The reason I don't like is this: by default waf runs with as many parallel jobs as CPU cores you have and that means that often when you have an error it is hidden by the next compilations. 90% of the times people post the waf error where it says what task failed and not the real error. Even after I say to scroll up to find the real error, about 20% can't find it.

The most people using this script are people without much experience so I don't think that adding more output is going to help them. Like I said, I think that a better error handling would be better than increasing output.

**Comment by peterbarker** [comment]
On Thu, 3 Nov 2016, Tom Pittenger wrote:

> I think Peter needs to apply this PR to every PR he submits, he could use a
> little more verbose PR descriptions :)
> 
> I updated his initial PR message, but the commit message should also change
> to be something more useful. If we all agree that the code is OK then
> someone just change the commit message and shove this into PR and get on
> with it.

Ah, well... I went the other way and removed the extra gumpf in the commit 
message which was causing confusion :-)

**Comment by peterbarker** [comment]
@OXINARF I'm not sure how this relates to waf.  AFAIK these scripts aren't run by waf, but by a user trying to get a dev environment on their Ubuntu or arch machines. 

Since we're running with `set -e`, the error will almost certainly be at the bottom :-)

**Comment by lucasdemarchi** [comment]
Agreed. We either need to fix it properly as suggested or add-x. We could have the later as an interim solution

**Comment by OXINARF** [comment]
@peterbarker I know this isn't run by waf, but my description was about the inexperienced users that use this script. It is true that with `-e` set it is more likely the error will be at the end, but not guaranteed.

Anyway, since I'm the only one opposing this then go ahead and merge it.

**Comment by peterbarker** [comment]
Merged.  We can always take it out again if it does cause grief, but I think saving on the round-trips to the user when doing support will be rather beneficial.

**Pull request merged**
