### PR TITLE
AP_Motors: Don't pass servos into AP_MotorsHeli_Single

### PR DESCRIPTION
**Pull request by fhedberg**
AP_Motors: Don't pass servos into AP_MotorsHeli_Single

### CODE REVIEW

**Comment by tridge** [comment]
we need to check that external gyro function still works properly with this change, that is what servo_aux is for

**Comment by tridge** [comment]
I've just checked, and this patch does change the value output to an external gyro. The range going to the external gyro in master depends on RC7_MIN and RC7_MAX. With this patch those limits are hard-coded to the default for RC_Channel, which is 1100 to 1900. So it will break existing users and remove the ability to control the full range of an external gyro.

**Comment by rmackay9** [comment]
ok, Thanks for checking that @tridge.

**Comment by fhedberg** [comment]
@rmackay9 @tridge Updated the PR.

**Comment by fhedberg** [comment]
@rmackay9 @tridge Ping

**Comment by tridge** [comment]
@fhedberg sorry for the slow response. Thanks for pinging me on gitter.

The patch still doesn't look right to me. It is still declaring a new RC_Channel instead of using a reference to an existing channel. That means it gets a new copy of the min, max, rev and other channel variables. It also means that if a user changes RC7_MIN/RC7_MAX then it won't have an effect on the behaviour of the channel.
I think what we need to do is what was done for the RSC output, which is to use RCn_FUNCTION. We'll add a function for k_heli_gyro and then default it to use channel 7 on heli_single. If you have a look at what is done with default_channel in AP_MotorsHeli_RSC I think you'll see what I mean.
That will retain compatibility with existing setups, plus add the ability to move the gyro output to any channel.
If that sounds OK I could code it up, or you could if you have the time.

**Comment by fhedberg** [comment]
@tridge I think that's a feature not a bug ;) Just as with the other helicopter output channels, the RCX_MIN/MAX in my mind should not affect the output channels, hence the addition of a new RC_Channel object. Thoughts?

Adding an AUX function, I'm all for!

**Comment by lvale** [comment]
@tridge Isn't the purpose of this PR been deprecated with the Channel Mask PR ?

**Comment by R-Lefebvre** [comment]
What effect would this change have on the operation of the direct drive tail motor output function?  I'm currently using that.

**Comment by fhedberg** [comment]
@R-Lefebvre Shouldn't affect the tail.

**Comment by davidbuzz** [comment]
No action on this PR for over a year, possibly superceeded according to lvale's comment.

**Pull request closed without merging**
