### PR TITLE
Feature/ci cache restore

### PR DESCRIPTION
**Pull request by khancyr**
Fix some CI variable name leading to wrong cache usage.
fix macos caching
when doing SITL autotest we don't need to lose time to save build cache again as it was already done in build phase

### CODE REVIEW

**Comment by peterbarker** [comment]
What does this save us?

**Comment by khancyr** [comment]
around 16s per autotest
macos some minutes per test as cache will working
test size some minutes per test as cache will working (mean save should be 10-20min)

**Comment by magicrub** [comment]
@peterbarker How do you feel about this? Ready to merge?

**Comment by peterbarker** [comment]
Merged, thanks!

**Pull request merged**
