### PR TITLE
AP_Arming: Use arming helper

### PR DESCRIPTION
**Pull request by IamPete1**
Uses the helper to ~~save flash~~ and reduce code.  No change in behavior.

Edit: seems not to save flash, maybe we need to inline the `check_enabled` method.

### CODE REVIEW

**Comment by peterbarker** [comment]
In case the size thing becomes a problem, I'll note something I've wanted to do for a while.  What I'd like to do is remove these clauses entirely, replacing them with setting state variables indicating which tests have failed.  We can then log that state, so when we're looking at crash logs we might be able to see what wasn't working when the user armed. The prearm check, then, became running the update-prearm-flags followed by checking the bitmask.

I did have a branch which accomplished that working for a while - but it's gone now...  I'm not sure if this will have gotten easier or harder since I wrote it.

**Review by rmackay9 — APPROVED** [review]

**Comment by peterbarker** [comment]
> Uses the helper to ~save flash~ and reduce code. No change in behavior.
> 
> Edit: seems not to save flash, maybe we need to inline the `check_enabled` method.

In-lining doesn't help - I checked.

Is this *all* the bytes we lose to become uniform across the code-base?

One thing we *could* do is change the method to be a macro.... but I'm pretty sure I'd rather just remove the calls (see previous comment)

**Comment by IamPete1** [comment]
> Is this _all_ the bytes we lose to become uniform across the code-base?

There is https://github.com/ArduPilot/ardupilot/pull/22707 too. Less than 100 bytes added total. The main reason for this was to prevent what is in https://github.com/ArduPilot/ardupilot/pull/22707 which I think is quite nasty.

**Review by peterbarker — APPROVED** [review]
LGTM.  It would be nice to be able to merge this today so we can discuss the other PR after it has been rebased.

**Comment by rmackay9** [comment]
Let's merge it then!

**Pull request merged**
