### PR TITLE
EKF: Fix height jump in copter when GPS checks pass in flight

### PR DESCRIPTION
**Pull request by priseborough**
Addresses https://github.com/ArduPilot/ardupilot/issues/6594

Plots show local vertical position before and after change.

**Before**
before

**After**
after

### CODE REVIEW

**Comment by tridge** [comment]
tested in SITL and works nicely
thanks Paul!

**Comment by OXINARF** [comment]
@priseborough Although there is nothing wrong with changing the default value, I don't understand how this fixes the problem. If someone changes the parameter to 4 they will get the issue we have in master now - and that looks just like some bad initialization, because if origin isn't set, both EKF_origin and ekfGpsRefHgt should be 0.

**Comment by priseborough** [comment]
It fixes the problem immediately for the default parameter case.

For the case where origin changes are applied to the reported local position, the underlying problem is that the origin height is set to the copters position at the time that GPS checks pass. Changing this to GPS height - local height should solve that problem.

**Comment by priseborough** [comment]
I'll push some additional patches for the non-default case.

**Comment by OXINARF** [comment]
Thanks @priseborough. I should know that, but for some reason I assumed that it already did that and just home would be set at whatever height the vehicle would be.

**Comment by priseborough** [comment]
I have tested these on SITL with both EK2_OGN_HGT_MASK and EK3_OGN_HGT_MASK set to 4 and vertified no jump in reported local vertical position from EKF2 and EKF3 when they start using GPS.
screen shot 2017-07-17 at 9 16 08 am

**Comment by OXINARF** [comment]
Thanks, as soon as CI passes the tests I'll merge it.

Just throwing an idea here: when optical flow is available, would using the local position to set the true origin GPS position be something doable?

**Comment by priseborough** [comment]
Yes it would.  I can see how it would be useful for RTL.

**Comment by OXINARF** [comment]
@priseborough I'm not sure for RTL (as it should return home), but we certainly have some mix between home (which is settable at any time) and EKF origin, so it would be nice if when possible the EKF origin was set to its true location.

Merged, thanks!

**Comment by priseborough** [comment]
Yes, I was thinking having the origin as close as possible to the starting point would enable it to be used to set the home position in the case of copters or other vehicles which start operation without a GPS lock and then acquire GPS later.

**Pull request merged**
