### PR TITLE
AP_RangeFinder: add get_temp() and implement for NMEA driver

### PR DESCRIPTION
**Pull request by rmackay9**
This PR makes two changes:

- adds support for reading the MWT (Mean Water Temperature) NMEA message from NMEA rangefinders.  The Rover/Boat firmware then logs this in the DPTH message.
- logs the DPTH message even if the vehicle does not have a position estimate (lat,lon are logged as zero). Resolves issue  https://github.com/ArduPilot/ardupilot/issues/17190

Th water temperature has been requested by at least two users although it is not in the issues list (it probably should be).

The MTW message format can be found here: https://gpsd.gitlab.io/gpsd/NMEA.html#_mtw_mean_temperature_of_water

This has been tested on real hardware and the results are below:
image

Below is a test of what happens when the GPS_TYPE is set to 0 to disable the position estimate and we see the message keeps logging with the last known lat,lon.  If the vehicle has never had a good position estimate the lat,lon fields are zero.
image

### CODE REVIEW

**Comment by IamPete1** [comment]
If you have MATLAB this I wrote a script for testing the MTW and VHW via Airspeed, https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Airspeed/models/NMEA_Sensor.m

**Comment by khancyr** [comment]
As the data comes from NMEA, can't we just instanciate a temperature sensor with nmea input?

**Comment by rmackay9** [comment]
@khancyr, can you provide some more detail on how we'd do that?  I'm not aware of a NMEA temp sensor but we've got a big code base these days so I could easily be missing something.

**Review by khancyr — COMMENTED** [review]
Yep, we don't have it here, so this is fine like this.

**Comment by khancyr** [comment]
What I was referring is having an AP_NMEA base class like Mavlink and having some handle_nmea() function on other lib to access the nmea stream

**Comment by rmackay9** [comment]
@khancyr, txs.  Yes, it would be great if we had a NMEA base class.. we've talked about it but we just don't have one yet.

**Review by tridge — APPROVED** [review]

**Pull request merged**
