### PR TITLE
AP_Arming: Parameter check is not unused

### PR DESCRIPTION
**Pull request by AndKe**
Fix for https://github.com/ArduPilot/ardupilot_wiki/issues/3111#issuecomment-719772864

### CODE REVIEW

**Review by khancyr — APPROVED** [review]
LGTM

**Comment by peterbarker** [comment]
I'm confused.

https://github.com/ardupilot/ardupilot/blob//ArduPlane/AP_Arming.cpp#L89

**Comment by rmackay9** [comment]
@peterbarker the link you've provided doesn't work for some reason so here is a replacement.

https://github.com/ArduPilot/ardupilot/blob/master/ArduPlane/AP_Arming.cpp#L89

**Comment by rmackay9** [comment]
@peterbarker I've had another look at this PR. This PR is **removing** "(unused)" from the parameter description.

**Comment by peterbarker** [comment]
Merged, thanks!

**Pull request merged**
