### PR TITLE
Fix home location set/get

### PR DESCRIPTION
**Pull request by lucasdemarchi**

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
@guiccbr does this fix the issue for you?

**Comment by guiccbr** [comment]
@lucasdemarchi , yes, it solves the problem. Thanks.

**Comment by OXINARF** [comment]
Does this require GCS changes?

I'm sure Tom would prefer to multiply to 0.1 instead of the division, isn't it so @magicrub? :smile:

**Comment by lucasdemarchi** [comment]
@OXINARF it's integer operation

**Comment by lucasdemarchi** [comment]
@OXINARF for set_home, I've seen them using the other MAV_DO_SET_HOME instead of this one. I checked QGC and this actually fixes the value for them.  Mavproxy was already displaying "as is". I didn't check others.

**Comment by OXINARF** [comment]
> @OXINARF it's integer operation

I'm just kidding with Tom, he's in "every" PR asking for that change.

> @OXINARF for set_home, I've seen them using the other MAV_DO_SET_HOME instead of this one. I checked QGC and this actually fixes the value for them. Mavproxy was already displaying "as is". I didn't check others.

Ok, thanks. There shouldn't be a need to notify them then.

**Comment by rmackay9** [comment]
I'm happy for this to go in in case you're waiting on me.

**Comment by magicrub** [comment]
:)

**Comment by magicrub** [comment]
I can tolerate an integer divide over a float divide especially if there's a penalty for converting to float like in this case.

**Comment by tridge** [comment]
applied, thanks Lucas!

**Pull request closed without merging**
