### PR TITLE
Add bus thread to AuxiliaryBus

### PR DESCRIPTION
**Pull request by lucasdemarchi**
See https://github.com/ArduPilot/ardupilot/pull/6705#issuecomment-319636961

UNTESTED YET. Should be tested at least on navio/navio2 and minlure that make use of AuxiliaryBus with AK8963 and HMC5883.

### CODE REVIEW

**Comment by tridge** [comment]
nice! I do hope this works

**Comment by staroselskii** [comment]
We'll give it a try later this week.

**Comment by khancyr** [comment]
@staroselskii ping !

**Comment by staroselskii** [comment]
Sorry, guys!

It somehow slipped through. We'll test it in the beginning of the next week. Sorry for the delay.

**Comment by staroselskii** [comment]
We've tested it on Navio/Navio2 and everything seems to be okay. Thanks for your work, Lucas!

**Comment by lucasdemarchi** [comment]
Applied, thanks.

**Pull request closed without merging**
