### PR TITLE
Copter: Heli: correct use of swash when landing as part of mission RTL

### PR DESCRIPTION
**Pull request by peterbarker**
Also correct dynamic-flight when landing as part of mission RTL

The critical logic missing from the current master code is that when your mission ends with an RTL then we are in ModeAuto byut we our submode is not Auto_Land.

We have a method used to indicate if we're currently doing what mode land does - we should use it.

### CODE REVIEW

**Comment by peterbarker** [comment]
@bnsgeyer At the moment this doesn't.  That should change.

Problem here is that that original list of modes a very mixed bag.  `SPORT` and `DRIFT` aren't direct throttle control (drift is close).  `SPORT` actually allows for going through automated takeoffs, and it seems to use the same z-controller in the same way as loiter and poshold, for example.  `is_taking_off` would also be relevant.

Enumerating the modes is problematic.  As modes get added any switch statements like this - with a `default:` down the bottom - will naturally become out of date.  Doubly so when there are sub-modes involved!  Calling back onto the vehicle to determine the information you're after is far better.  Having a `limit_swash_movement()` call on the vehicles seems a little heavy-handed, however.

Currently the only relevant call we on the mode is `has_manual_throttle`, which is only true for `ACRO and `STABILIZE`.

I guess one issue here is that the function is misnamed.  We're not *just* limiting swash movement for landing, are we?  So `use_landing_swash` might be accurate but also misleading?  We use this any time you're not in dynamic flight in modes like loiter - so if you've no rangefinder you can enter this regime by hovering (ground-relative) for a couple of seconds.

What is it that should really be checked for about the mode for us to say, "should we ever limit swash movement?"  Direct equivalence with this code would be something which returns true for everything byt `STABILIZE`, `ACRO`, `DRIFT` and `SPORT` - but I don't think that's a great list.  Perhaps we could just go off `manual_throttle` and just get `STABILIZE` and `ACRO`?

**Comment by bnsgeyer** [comment]
@peterbarker we have to limit the downward movement of the collective because once landed, pushing the collective too low will cause bad vibrations and potentially ground resonance.  So we have to keep the autopilot from setting collective too low while landed.  So in the early days, collective is limited while below a speed over ground to cover all cases when in a non-manual throttle mode.  Do you have any suggestions how better to address this?

**Comment by peterbarker** [comment]
@bnsgeyer Ideally we change this to never limit if `flightmode->is_manual_throttle()`. 

That is a behaviour change.

Less than ideally we special-case the other two modes to preserve existing behaviour.

**Comment by bnsgeyer** [comment]
@peterbarker I rebased on master and made some changes.  I still need to test this.

**Comment by peterbarker** [comment]
@bnsgeyer I've moved the contents into the other PR as requested.  Thanks!

**Pull request closed without merging**
