### PR TITLE
Copter/Plane/Rover/Tracker: 4.5.7-beta1 release

### PR DESCRIPTION
**Pull request by rmackay9**
This is the Copter, Plane, Rover and Tracker 4.5.7-beta1 release.

The full list of PRs included can be seen in the 4.5.7-beta1 column of [this project](https://github.com/orgs/ArduPilot/projects/8/views/8?layout=board).

After discussions with @peterbarker and @tridge these three have also been added

- [x] https://github.com/ArduPilot/ardupilot/pull/28213
- [x] https://github.com/ArduPilot/ardupilot/pull/27799
- [x] https://github.com/ArduPilot/ardupilot/pull/28219

Any and all feedback is very welcome!

### CODE REVIEW

**Comment by peterbarker** [comment]
> I think we could also include the PRs below but I'd like it if @peterbarker or someone else could put an approved on the first one. I'm less sure who should put an approved on the 2nd one.

I've approved the first one.

**Comment by peterbarker** [comment]
> I think we could also include the PRs below but I'd like it if @peterbarker or someone else could put an approved on the first one. I'm less sure who should put an approved on the 2nd one.
> 
>     * [AP_GPS: Backport correct satellite count for SBF DNU NrSv value #27799](https://github.com/ArduPilot/ardupilot/pull/27799)

This one is also fine to include.

**Comment by tridge** [comment]
@rmackay9 I think this should be included:
https://github.com/ArduPilot/ardupilot/pull/28219

**Review by andyp1per — DISMISSED** [review]
Needs https://github.com/ArduPilot/ardupilot/pull/28219/commits/3615bf392b2715258455a991e127fdc7b8d9f8db I think

**Review by tridge — APPROVED** [review]

**Pull request merged**
