### PR TITLE
AP_OpticalFlow: fix for msp opflow sensor alignment

### PR DESCRIPTION
**Pull request by yaapu**
This fixes a bug in the MSP opflow driver.

It has been tested by @tenten8401, waiting for more testers to confirm the issue is solved.

### CODE REVIEW

**Comment by rmackay9** [comment]
Txs for this. So there are no changes to the flow rates (the changes to these lines is just cosmetic) but the body rates are reversed?  Seems OK to me.

**Comment by yaapu** [comment]
@rmackay9 yes, the bug was reversing only the flow, by basically installing the sensor as suggested by matek one could align body and flow but imu was reversed and had to apply a flow orient of 180°, by inverting both flow and body before applying flow orient you get aligned flow, body and imu with flow_orient = 0 as expected

**Comment by yaapu** [comment]
@rmackay9 now I got it right, but I think there's a bug in the mavlink opflow driver I used as a reference when writing the MSP one, the state.bodyRate vector comes from the gyros and we should not apply the FLOW_ORIENT_YAW compensation since gyro info comes from ahrs and not from onboard the flow sensor, what do you think?

mavlink opflow bugged code is here
 https://github.com/ArduPilot/ardupilot/blob/b0fa5fadcd53ba9a28a29ec435347ffa260a0d28/libraries/AP_OpticalFlow/AP_OpticalFlow_MAV.cpp#L68-L69

I tested the MSP code against a Matek 3901
FLOW_TYPE = 7
OPFLOW_FXSCALER = -800
OPFLOW_FYSCALER = -800

sensor pointing forwards
FLOW_ORIENT_YAW = 0
image

sensor pointing right
FLOW_ORIENT_YAW = 9000
image

sensor pointing left
FLOW_ORIENT_YAW = -9000
image

sensor pointing backwards
FLOW_ORIENT_YAW = 18000
image

**Comment by rmackay9** [comment]
@yaapu, yes, you're probably right.  The issue exists in the CXOF driver as well.  This would mean that these drivers wouldn't work correctly unless the sensor was placed in it's default position (i.e. FLOW_ORIENT_YAW = 0).

Maybe create a separate PR to fix the other drivers too?  We will have a bit of an issue because we will need to find someone to test them probably.

**Comment by yaapu** [comment]
@rmackay9 ok, I might have a CXOF sensor somewhere and should be able to test by myself but we'll need help for the mavlink one, thanks

**Comment by yaapu** [comment]
related PR https://github.com/ArduPilot/ardupilot/pull/16226 for MAVLink and CXOF

**Comment by rmackay9** [comment]
Merged, thanks!

**Pull request merged**
