### PR TITLE
Use MAV_RESULT to tighten return types

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by magicrub** [comment]
../../ArduPlane/GCS_Mavlink.cpp: In member function 'virtual void GCS_MAVLINK_Plane::handleMessage(mavlink_message_t*)':
../../ArduPlane/GCS_Mavlink.cpp:1398:179: error: invalid conversion from 'uint8_t {aka unsigned char}' to 'MAV_RESULT' [-fpermissive]
             result = plane.quadplane.mavlink_motor_test_start(chan, (uint8_t)packet.param1, (uint8_t)packet.param2, (uint16_t)packet.param3, packet.param4, (uint8_t)packet.param5);

**Comment by peterbarker** [comment]
On Mon, 27 Nov 2017, Tom Pittenger wrote:

> ../../ArduPlane/GCS_Mavlink.cpp: In member function 'virtual void
> GCS_MAVLINK_Plane::handleMessage(mavlink_message_t*)':
> ../../ArduPlane/GCS_Mavlink.cpp:1398:179: error: invalid conversion from
> 'uint8_t {aka unsigned char}' to 'MAV_RESULT' [-fpermissive]
> result = plane.quadplane.mavlink_motor_test_start(chan,
> (uint8_t)packet.param1, (uint8_t)packet.param2, (uint16_t)packet.param3,
> packet.param4, (uint8_t)packet.param5);

Fixed

**Comment by khancyr** [comment]
LGTM

**Comment by OXINARF** [comment]
Merged, thanks!

**Pull request merged**
