### PR TITLE
Frame_params: Add DJI AGRAS MG-1

### PR DESCRIPTION
**Pull request by muramura**
Axel Weckschmied uploaded a video of the DJI AGRAS MG-1 flight on Facebook "CubePilot.org".
This MG-1 replaced the FC with CubeOrange.
This CubeOrange is using AC4.1.3.
I PR'd this config parameter on behalf of Axel Weckschmied.

Axel Weckschmied has agreed to PR it.

Thank you, Axel Weckschmied.

### CODE REVIEW

**Comment by rmackay9** [comment]
Thanks for this but really we need to reduce the parameter list to just the essentials:

- remove the RC and compass calibration values
- remove any parameter values that are already the defaults
- remove anything that could be very specific to a single frame.  For example AHRS_ORIENTATION = 4 doesn't seem like a common way that users would install the autopilot.   failsafe and battery monitor params should probably also be removed.

**Review by rmackay9 — CHANGES_REQUESTED** [review]
some changes requested above, also let's squash the commits if possible.

**Comment by muramura** [comment]
@rmackay9 san

Thank you for your review.  
I will change.
I have one commit.

**Comment by muramura** [comment]
@rmackay9 san
I've changed it.

**Comment by rmackay9** [comment]
@muramura,

Great thanks.  There still seem to be 3 commits.  Also these changes which I don't think should be included:

- COMPASS_xxx parameters
- SERIAL2_PROTOCOL
- SERVO9_FUNCTION
- SERVO13_FUNCTION
- BRD_IMU_TARGTEMP
- CAM_DURATION
- CAM_SERVO_ON

**Comment by muramura** [comment]
@rmackay9  san
Thanks for the review.
I have reflected the review comments.

**Comment by rmackay9** [comment]
Hi @muramura,

Sorry, can you also remove the CAN_ parameters?

**Comment by muramura** [comment]
@rmackay9 san
Thank you for the review.
I have reflected the review comments.

**Comment by rmackay9** [comment]
Merged, thanks!

**Pull request merged**
