### PR TITLE
Relocate mission 0.1

### PR DESCRIPTION
**Pull request by WillyZehnder**
Extension of using a MISSION by temporary Translation and Rotation of the Waypoints.
Explanation in Wiki: https://github.com/ArduPilot/ardupilot_wiki/pull/4486

### CODE REVIEW

**Review by amilcarlucas — APPROVED** [review]
I thought you re-did this in lua.
@tridge how much of these things does your acrobatics scripts do? There is surely some overlap.

**Comment by WillyZehnder** [comment]
Yes, I programmed and tested nearly the same functionality in lua.
But for all the 1MB FCs with no lua it would be helpful to have that small code as an option - e.g. for 'Custom Firmware Builder' or DIY-builders.

**Comment by amilcarlucas** [comment]
At the speed that Peter Barker is adding switches, I bet that all 1MB boards can now do lua. :)

**Comment by WillyZehnder** [comment]
> I bet that all 1MB boards can now do lua
That sounds great! Do you have a link where to get more info about the current state and the strategy?

**Comment by WillyZehnder** [comment]
Unfortunately Lua on e.g. F405 will not be possible: https://discuss.ardupilot.org/t/plane-4-2-stable-release/84979/120
So that PR still makes sense as a build-option.

**Comment by Hwurzburg** [comment]
What is the size of this for a MatekF405-Wing if it was enabled?

**Comment by WillyZehnder** [comment]
BUILD SUMMARY
Build directory: /home/willy/ardupilot/build/sitl
           Target         Text     Data    BSS     Total  
-----------------------------------------------
bin/arduplane  3477167  165245  167688  3810100 -> with
bin/arduplane  3475863  165213  167624  3808700 -> without
diff                         1304          32          64        1400

**Comment by tridge** [comment]
we discussed on the dev call and decided not to bring this into master

**Pull request closed without merging**
