### PR TITLE
HAL_F4light: Fixed build after api changes

### PR DESCRIPTION
**Pull request by night-ghost**
when BetterStream lost a lots of methods

### CODE REVIEW

**Comment by tridge** [comment]
looks good, but I'd like to do a quick test of the change to DataFlash, just to make sure it is ok for all boards

**Comment by night-ghost** [comment]
>you seem to still have vestiges of the CLI code in here

sorry but I don't understand you

>tridge is talking about resurrecting the DataFlash backend, DataFlash_Block

I want to drop support of raw block device in favor of FAT-formatted volume. It works much better now.

>there are lots and lots and lots of new defines to get rid of features and flight modes

yes I know, so just added a refusal of a most useless features

> I'd like to do a quick test of the change to DataFlash

changes was only to adopt to changes in API

**Comment by night-ghost** [comment]
Thanks, now things becomes clear.  But I don't know which functions are used only for CLI and not for MAVlink, so can't do this before that PR will be in master

**Comment by peterbarker** [comment]
On Mon, 9 Apr 2018, night-ghost wrote:

> Thanks, now things becomes clear. But I don't know which functions are
> used only for CLI and not for MAVlink, so can't do this before that PR
> will be in master

I've updated the PR now.  The only place the functions are used is in the 
tests for the library, and I'd need to sort those out before we could 
merge the PR.

It even Compiles For Me.

If this conflicts horribly with your PR, get that one in first.  This one 
wasn't problematic.

**Comment by amilcarlucas** [comment]
I think there are a couple of more stuff that you can disable, like sprayer, or winch ...

**Comment by tridge** [comment]
@night-ghost the DataFlash change breaks logging for HAL_ChibiOS, as it doesn't set HAL_OS_POSIX_IO (it sets HAL_OS_FATFS_IO instead)
I will push to your PR branch to fix this

**Comment by tridge** [comment]
I've pushed the changes and tested on fmuv4 chibios build and px4-v4. It works now. I'll push this to master once CI passes

**Pull request merged**
