### PR TITLE
Tidy EKF-related #include lists

### PR DESCRIPTION
**Pull request by peterbarker**
Reduces pointless coupling between libraries and transitive include issues.

### CODE REVIEW

**Comment by khancyr** [comment]
any tools used to do that ?

**Comment by peterbarker** [comment]
@khancyr emacs? :-)

All done manually.

**Comment by tridge** [comment]
check for same size binary for a couple of builds

**Comment by peterbarker** [comment]
Tested some binary sizes; minimal changes.

**Pull request merged**
