### PR TITLE
AP_Joypad: Added base library (part1)

### PR DESCRIPTION
**Pull request by hiro2233**
Multipurpose Joypad library, right now the library support 3 targets and already working.

**Working as bridge:**
- atmega16u2 (fully working with DFU)
- atmega32u2 (in development on the DFU bootloader)

**Working as remote:**
- atmega328p (fully working with the joypad_remote tool)
- atmega2560 (fully working with the joypad_remote tool)

**Not tested (this should work with the joypad remote tool)**
- Raspberry Pi
- STM32F4 series.

These AVR microcontrollers are supported right now with the master on fusioned library with URUS SHAL: https://github.com/UrusTeam/urus_modules

**What we can do with it?**
With this one, we can make and use a legacy board (APM 2.x) like a joystick with your companion computer, or interface your RC controller to use on your computer or do anything that you can imagine for profesional or hobby use.

The joypad_remote tool is buildable with WAF like other examples and buildable with precompiled GCC toolchain that come with Urus Studio IDE, you can find it here https://github.com/UrusTeam/urusstudio_installer

The AVR microcontroller is only buildable with Urus Studio and you can build for other platforms too. Urus Studio was developed and focussed to work only with Ardupilot Libraries-HALs and with URUS SHAL.

You need also the dfu programmer and avrdude to upload the firmware to the target respectively.
I hope to make it friendly on the next step, because this is our way to work and develop right now with Ardupilot URUS ecosystem.

Greetings,
Hiroshi.

### CODE REVIEW

**Comment by WickedShell** [comment]
I'm not sure that this really belongs in the ArduPilot repo. As far as I can tell it's only allowing unsupported boards to be used as HID's which are not really the focus or use case for ArduPilot. I think allowing the boards to be useful is valid and worthwhile, but I don't think this really belongs in the main ArduPilot repo.

**Comment by hiro2233** [comment]
To confirm your insecurity, it's is already supported. The library is like than other ones into the master, and you can add more drivers separately without breaking to others, this enhance capabilities to the Ardupilot too. HID is one a method for companion computers too, so this is native APM API running and working with HID on 8 bits and 32 bits boards.

This is my proposal, if it's doesn't pass to master, no problem, the project continue, with or without your agree.

**Comment by khancyr** [comment]
Hello, I didn't understand all. This allow some avr board to be use a joystick, isn't it? But how to send command ? 
 That doesn't need any ardupilot stuff ? Just a standalone lib should be better... 
Moreover the current proposed implementation is only available for urus so it is not usable on ardupilot board

**Comment by hiro2233** [comment]
Hello @khancyr ,

> This allow some avr board to be use a joystick, isn't it?
Yes, with APM 2.x boards and URUS ones, not only AVR, it will be done with STM32FX series, and linux boards too, but right now only AVR.

 you can send the command with the tool on "Tools/joypad_remote/" and you can use that on any board, right now UART is only supported, i hope to expand it on the next steps.

The ap_joypad has one synchronous protocol that match with the USB GamePad descriptors. I hope to add an user-space virtual gamepad to support linux boards on ap_joypad natively.

**Comment by tridge** [comment]
How would this be used with the flight boards we support in master? I don't understand why you would want to connect a joypad to a flight controller?

**Comment by tridge** [comment]
I don't think the ArduPilot/ardupilot repo is the right place for this code

**Comment by davidbuzz** [comment]
This is not directly part of an autopilot, it's code for a custom joystick.

**Comment by WickedShell** [comment]
Discussed on the Dev call today. Given that it is a generic HID device it's just out of scope of the project. You are of course welcome to maintain the feature elsewhere, but it isn't a feature we are looking to bring into the core project at the moment.

**Comment by hiro2233** [comment]
> How would this be used with the flight boards we support in master? I don't understand why you would want to connect a joypad to a flight controller?

I will demonstrate it with a video on next week, right now i'm integrating it in a realtime simlulator.

> This is not directly part of an autopilot, it's code for a custom joystick.

Of course, if you say it.

> Discussed on the Dev call today. Given that it is a generic HID device it's just out of scope of the project. You are of course welcome to maintain the feature elsewhere, but it isn't a feature we are looking to bring into the core project at the moment.

Well.

**Pull request closed without merging**
