### PR TITLE
AP_CustomControl:Update README.md

### PR DESCRIPTION
**Pull request by DisCoLabIITK**
Changes needs to be done in the AC_CustomControl_config.h file to prevent error while compilation.

### CODE REVIEW

**Comment by rmackay9** [comment]
Hi @DisCoLabIITK,

Thanks for this, could you update the commit so that it is prefixed with "AP_CustomControl: "?  In general we ask that all commits are prefixed with the folder or subsystem that is changed because it makes it much easier for us to backport items to the stable releases.

**Comment by DisCoLabIITK** [comment]
Hi Randy, 
I have made the changes. This is my first pull request anywhere, so sorry for any mistakes.
Regards,

**Comment by khancyr** [comment]
@DisCoLabIITK that change should be done on the commit message (using git) not the github title !

**Comment by DisCoLabIITK** [comment]
I dont know how to do that. I created the PR from GUI. So closing this for now. Thanks!

**Comment by DisCoLabIITK** [comment]
> @DisCoLabIITK that change should be done on the commit message (using git) not the github title !

I dont know how to do that. I created the PR from GUI. So closing this for now. Thanks!

**Comment by khancyr** [comment]
No need to close. You can force push the update.

Try to look for something called Commit Ament on your gui, that should allow to update the commit message

**Comment by DisCoLabIITK** [comment]
> No need to close. You can force push the update.
> 
> Try to look for something called Commit Ament on your gui, that should allow to update the commit message

@khancyr I meant from the web browser. I new to git and i am not a SW developer. Im afraid I might break something. I tried git amend from terminal but it did something else I suppose as the comment didnt change.

**Pull request closed without merging**
