### PR TITLE
Support for reverse thrust with DShot

### PR DESCRIPTION
**Pull request by tridge**
This is an initial implementation of reverse thrust for planes using DShot.

To use, do the following:

- remove propellers
- setup your BLHeli32 ESCs for 3D throttle using pass-thru support
- set param SERVO_BLH_MASK to the mast of outputs that use DShot
- set param SERVO_BLH_REMASK to the mask of outputs that support reverse thrust
- set param THR_MIN to a negative number (maximum amount of reverse thrust you want, -100 means 100%)
- set RCn_OPTION to 64 for a RC input channel that has a switch on it. Option 64 is "reverse throttle" and is used to test reverse thrust in MANUAL or to command reverse thrust while flying in a manual throttle mode. For example, if you have a switch on RC channel 7 then set RC7_OPTION=64. When that channel goes high (above 1800) then reverse thrust is enabled.

For example, if your motor is on AUX1 on a CubeBlack then you will need to set:

 - SERVO_BLH_MASK=256
 - SERVO_BLH_REMASK=256

after that follow the normal plane reverse thrust landing instructions

To make testing easier I've put some binary builds here:

http://uav.tridgell.net/RevThrust/

if you want me to build some more boards then please let me know.

### CODE REVIEW

**Comment by Naterater** [comment]
Thank you for the quick tutorial for testing. Is reverse thrust only activated by another channel, or can a self-centering transmitter stick be used (if that stick's min, max, and trim are set correctly)? Don't intend to distract from the point of this PR.

**Comment by tridge** [comment]
@Naterater you have a choice. If you setup a RCx_OPTION=63 then you should use a non-centered throttle. If you don't setup a RCx_OPTION=63 then a sprung throttle works

**Comment by tridge** [comment]
this has been flight tested by Alex, merging

**Comment by pompecukor** [comment]
> 
> 
> this has been flight tested by Alex, merging

Yes we did, works like a dream. Thank you for the fast work!!

**Comment by pompecukor** [comment]
> 
> 
> @Naterater you have a choice. If you setup a RCx_OPTION=63 then you should use a non-centered throttle. If you don't setup a RCx_OPTION=63 then a sprung throttle works

You may wanna edit, it is option 64. not 63.

**Comment by Naterater** [comment]
This really needs to make it into the stable releases. Test flew yesterday and all works well.

**Pull request merged**
