### PR TITLE
AP_HAL_ChibiOS: JFB100 gets custom firmware string

### PR DESCRIPTION
**Pull request by jfbblue0922**
Apply custom firmware strings for JFB100.

### CODE REVIEW

**Comment by rmackay9** [comment]
@jfbblue0922,

Txs for the PR.  

I'm wondering why you'd want to replace the ArduPilot firmware string with the board name.  Perhaps I'm misunderstanding but below is how "master" appears with the JFB100 board.  Both the ArduPilot firmware version and the board type are displayed.
image


By the way, commits should normally be prefixed with the subsystem.  So for example this PR's commit should really be, "AP_HAL_ChibiOS: JFB100 gets custom firmware string" (or similar).

**Comment by jfbblue0922** [comment]
@rmackay9 

Our purpose is to let users know JFB hwdef version easily.
I thought it would be easier if it was displayed on the title bar of MissionPlanner.
Please let me know if there is an easy way for users to know this information.

Thank you.

fig

**Comment by rmackay9** [comment]
@jfbblue0922,

OK thanks.  The hwdef is tied to the AP version though so I'm not sure that most users really need to know this level of detail.  In general because AP is GPLv3 most users tend to use an official version of AP or something very close to it.  We don't have the massive fracturing of firmware versions that appear with non-GPL code.  Without the fracturing and accompanying confusion firmware versions I'm not sure there's much value in showing users the version of the hardware definition file.

I think users need to be able to check the hardware they're using (e.g. they might forget whether a particular drone has a JFB100 or JFB110) but this is visible in the messages tab I posted above.

**Comment by rmackay9** [comment]
@jfbblue0922,

Sorry to be annoying but just want to be sure you saw my comment about the commit message formatting.  Commits should be prefixed with the subsystem. So for example this PR's commit should really be, "AP_HAL_ChibiOS: JFB100 gets custom firmware string".

**Comment by jfbblue0922** [comment]
@rmackay9 

thank you.I understand your point of view.

By the way, if "AP_CUSTOM_FIRMWARE_STRING" is set in hwdef.dat, where is it displayed?
(In a previous PR, @tridge suggested us using "AP_CUSTOM_FIRMWARE_STRING")

https://github.com/ArduPilot/ardupilot/pull/22154#discussion_r1017509005

**Comment by rmackay9** [comment]
@jfbblue0922,

AP_CUSTOM_FIRMWARE_STRING overwrites the ArduPilot firmware version (e.g. "ArduCopter V4.5.0-dev (943d9a01)" and is recorded in the onboard logs (see "MSG" messages) and appears in the GCS's Messages tab (see the orange box in the screen shot above).

@tridge,

It's unusual to have a hardware definition overwrite the ArduPilot firmware version isn't it?

**Comment by rmackay9** [comment]
@jfbblue0922,

I'm going to go ahead and close this PR but if you're unhappy with this decision we can re-open.

The screenshot below (copied from my earlier comment) shows how the board name and ArduPilot version are displayed in the messages tab as part of the "banner" ([see code here](https://github.com/ArduPilot/ardupilot/blob/master/libraries/GCS_MAVLink/GCS_Common.cpp#L4164) and [here](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_HAL_ChibiOS/Util.cpp#L384)).
image

I can certainly imagine that you might like a different string rather than "JFB100" displayed but I don't think the way this PR does it (by overwriting the ArduPilot firmware version) is the way this should be done.

Anyway, txs again for the PR.

**Pull request closed without merging**
