### PR TITLE
Copter: add EKF failsafe notify tones

### PR DESCRIPTION
**Pull request by tatsuy**
When EKF failsafe was triggered, some users were unaware that it was switched to LAND.
They feel that the copter suddenly become unstable and descend.
I think ToneAlarm makes the user aware the failsafe easily.

I tested this in Copter using CubeBlack without propellers.
If EKF failsafe is triggered, activates buzzer.
After disarmed, stop the buzzer.

If we need same functionality in other vehicles, I can add it.

### CODE REVIEW

**Comment by tatsuy** [comment]
I added the message to make a user easier to find that the mode has changed due to EKF Failsafe.
When EKF failsafe is triggered
image

When EKF failsafe is cleared
image

**Comment by tatsuy** [comment]
Bad EKF has Tone-alarm in Copter-3.2.1.
https://www.youtube.com/watch?v=j-CMLrAwlco&feature=player_detailpage#t=60
It was deleted in Copter-3.3.
https://github.com/ArduPilot/ardupilot/commit/3dfcdde6be73f5c91763f9e7709004c267087763#diff-24ea2f7db716ad1bcd3be133d58431c3L138

In this PR, I added failsafe_ekf flag instead of ekf_bad flag because ekf_bad is also flagged when using manual flight modes that do not require GPS.
I don't want to activate Tone Alarm when EKF failsafe action isn't triggered. 
@rmackay9 please review if you have a time.

**Review by khancyr — APPROVED** [review]
Even if most won't heard the tone in flight, I think that have a good value !

The impact is minimal.
And yes we should extend this for other vehicle in the future ! Thanks !

**Comment by rmackay9** [comment]
We discussed this on the dev call and the only issue is that in Copter at the moment the EKF failsafe will trigger a few seconds after arming if the user arms before the EKF has a position estimate (i.e. arms in Stabilize or Acro soon after startup).  Most users don't notice this at the moment but really we should change the EKF failsafe so that it only triggers if the vehicle has ever had a good position estimate.

I hate to scope creep but I think we should fix this EKF failsafe issue before we merge this PR otherwise we will end up with users complaining about the new tone.

**Comment by tatsuy** [comment]
@rmackay9 
Thank you for the discussion.
> Most users don't notice this at the moment but really we should change the EKF failsafe so that it only triggers if the vehicle has ever had a good position estimate.

I agree with the change.
After that, this PR could be more simpler.

**Comment by tatsuy** [comment]
@rmackay9 Are there any progress about EKF failsafe issue?
> the only issue is that in Copter at the moment the EKF failsafe will trigger a few seconds after arming if the user arms before the EKF has a position estimate (i.e. arms in Stabilize or Acro soon after startup).

This PR makes activates buzzer only when EKF failsafe action is triggered.
So this means that users will not hear the new tone over and over, including arming in Stabilize soon after startup.
> we will end up with users complaining about the new tone.

**Comment by tatsuy** [comment]
@rmackay9 
I confirmed EKF failsafe issue is fixed by #16594.
And it doesn't conflict this PR.

**Comment by rmackay9** [comment]
Great. I've added this for discussion at the EU Dev call this afternoon.

So we have "bad_ekf" and "failsafe_ekf".  I think this is OK but I'd like to hear what other devs think.

As a small side note, it might be good to change the message from "EKF Failsafe - LAND Mode" to "EKF Failsafe: changed to Land" or something like that.  Not a big deal of course.

**Review by tridge — APPROVED** [review]

**Comment by tatsuy** [comment]
Thank you.
I fixed it about the message.

about the reason of adding "failsafe_ekf",
I wanted to notify the EKF failsafe alert only when the flight mode was changed.

If I use "bad_ekf", the alert will sound even in Althold mode.

**Comment by rmackay9** [comment]
Merged, thanks!

**Pull request merged**
