### PR TITLE
uavcan: use recursive submodule

### PR DESCRIPTION
**Pull request by guludo**
Hi all,

This PR removes the submodule at `modules/uavcan` and enable using the recursive submodule instead (i.e. the one inside `modules/PX4Firmware`).

In PX4Firmware submodule, I cherry picked the commit that sets the uavcan's HEAD to the same as the one used on `modules/uavcan`.

I still had to keep the path to the new submodule in the build systems because of `Tools/scripts/add_git_hashes.py`. @tridge Do you think it still makes sense to have `--uavcan` option?

Best regards,
Gustavo Sousa

### CODE REVIEW

**Comment by guludo** [comment]
Oh, forgot to mention that this depends on https://github.com/ArduPilot/PX4Firmware/pull/55 .

**Comment by magicrub** [comment]
I was thinking about this same thing the other day. Could submodule MAVLink
also be recursive?

**Comment by guludo** [comment]
@magicrub Hm, I think the problem would be for non px4 boards. They would depend on PX4 just because of MAVLink.

**Comment by magicrub** [comment]
Same argument goes for UAVCan, doesn't it? Besides, regardless of your
target build you still sync/update all the modules so the source is always
available.

**Comment by guludo** [comment]
> Same argument goes for UAVCan, doesn't it?

Hm, really? I thought the only boards that depended on uavcan were the ones that depend on PX4Firmware.

**Comment by guludo** [comment]
I might be missing something...

**Comment by OXINARF** [comment]
I believe @guludo is right that only PX4 boards support UAVCAN.

**Comment by OXINARF** [comment]
I think that what we can/should do for MAVLink is to use the upstream repo instead of our own.

**Comment by magicrub** [comment]
There's this expert guy on mumble, who we should be talking to about this, who gives this a thumbs-up but wants to check the hashes first

**Comment by lucasdemarchi** [comment]
In theory Linux boards could support by using the libuavcan in this submodule. Apparently the Linux implementation using socketcan is in:
`libuavcan_drivers/linux/include/uavcan_linux`

When/if we support it we can use this implementation as a collaboration effort with the other projects.

**Comment by lucasdemarchi** [comment]
I'll leave this for @tridge

**Comment by magicrub** [comment]
Last i heard from tridge, a few hours ago, he was ok with uavcan and nuttx
submodules consolidation, not with MAVLink. Would be nice if he would come
in.
On May 18, 2016 7:04 PM, "Lucas De Marchi" <notifications@github.com> wrote:

I'll leave this for @tridge <https://github.com/tridge>

—
You are receiving this because you were mentioned.

Reply to this email directly or view it on GitHub
<https://github.com/ArduPilot/ardupilot/pull/4159#issuecomment-220209076>

**Comment by OXINARF** [comment]
With NuttX we need to be careful because we have commits that aren't upstream.

**Comment by lucasdemarchi** [comment]
We talked about this during the dev call and I talked in person with @guludo. Decision was to leave it as is for now.

**Pull request closed without merging**
