### PR TITLE
AC_WPNav: Change the minimum radius of WP to 1cm

### PR DESCRIPTION
**Pull request by muramura**
I can get the position with the accuracy of centimeter by RTK.
I want a minimum value of 1 centimeter.

### CODE REVIEW

**Comment by rmackay9** [comment]
@muramura,

The concern though is that users will make a mistake between cm and meters and input very small values and then vehicle may get stuck at waypoints.

What's the advantage of having it so small?  I think in a real flight that users won't notice a difference.

**Comment by muramura** [comment]
@rmackay9 san.
The minimum value for config parameter range specification is 5 cm.
The minimum value of 5 cm is displayed in the range description of the configuration parameter.
The rover can move the specified distance by the wheel encoder.
Therefore, I don't think it is necessary to modify the minimum value to 5 cm in ArduPilot's internal processing.

**Comment by rmackay9** [comment]
yes, I see your point that the parameter limits for the user input is different.

.. this change affects copter not rover though .. I agree that we probably can change this to 1cm but I also worry that these seemingly innocuous changes could cause problem and offer no real advantage.  I haven't heard of a case where I user really needed the radius to be this small for good performance.  On the other hand I have definitely seen users set the parameter to too small a value and then they raised support calls complaining that the vehicle was stuck at waypoints.

Sorry, but there just isn't enough evidence that this is solving more problems than it's creating.

**Comment by muramura** [comment]
@rmackay9 san. So, being able to set it up causes problems, right? I understood.

**Pull request closed without merging**
