### PR TITLE
Copter: Add a redefinition decision

### PR DESCRIPTION
**Pull request by muramura**
#16170 recommit.

I know that I can enable and disable the optional features of the copter in APM_Config.h.
I enabled the definition of OSD_ENABLED, since I do not need the OSD feature.
I got a build error.
I learned that I have defined it in config.h.
I will add the definition presence/absence check.

I think only one option function specification file is needed.

[687/748] Compiling ArduCopter/navigation.cpp
In file included from ... /... /ArduCopter/config.h:29:0,
From ... /. /... /ArduCopter/Copter.h:72,
from ... /... /ArduCopter/mode_zigzag.cpp:1:
... /... /ArduCopter/APM_Config.h:47:0: error: "OSD_ENABLED" redefined [-Werror].
#define OSD_ENABLED DISABLED // disable on-screen-display support

### CODE REVIEW

**Comment by peterbarker** [comment]
The definition of `OSD_ENABLED` that matters is the one coming in from the hwdef for the ChibiOS-based boards.

```
libraries/AP_HAL_ChibiOS/hwdef/BeastH7/hwdef.dat:define OSD_ENABLED 1
libraries/AP_HAL_ChibiOS/hwdef/F35Lightning/hwdef.dat:define OSD_ENABLED 1
libraries/AP_HAL_ChibiOS/hwdef/KakuteF4/hwdef.dat:define OSD_ENABLED 1
```

This error won't happen in SITL.

This is probably only the first of many options in these configuration files that will sprout this bug - so I'll bring it up at the devcall.  We might want to solve this in a more general way, I don't know.

**Comment by khancyr** [comment]
I don't think this is a right fix as it will just hid the definition into the hwdef...
Here the compiler is right.
I don't have a good solution for now to define feature both for vehicle and boards. Maybe the hwdef parser could or waf could fix the conflict between both or we need another file that would allow customisation for both sides.

**Review by rmackay9 — CHANGES_REQUESTED** [review]
as discussed on the dev call, we think the solution is to remove the OSD_ENABLED option in APM_Config.h and add a comment which points users towards the hwdef for system level options.

**Comment by khancyr** [comment]
I will close this for now as it need deeper change. Feels free to open another PR with the resquested changes. thanks

**Pull request closed without merging**
