### PR TITLE
AP_Compass: enable AK09916 inside a ICM20948

### PR DESCRIPTION
**Pull request by tridge**
the ICM20948 has an AK09916 which can be accessed via I2C bypass

### CODE REVIEW

**Comment by khancyr** [comment]
Dear git/github, this is Tridge work not mine. Thanks!

**Comment by WickedShell** [comment]
@khancyr Tridge is just trying to shift blame for anything that goes wrong on you! It's his new way of assigning maintainership!

**Comment by tridge** [comment]
@khancyr sorry about that! It was a rebase error. fixed now

**Comment by proficnc** [comment]
We will be adding this IMU as an IMU later, but the urgent priority was the mag.

Thanks all! Glad to have this in!

**Comment by tridge** [comment]
we can add it as an IMU later, and indeed it will need to change a bit in driver setup for that

**Comment by tridge** [comment]
@proficnc we need to get the right default orientation setup. Let me know when you have time for that

**Pull request merged**
