### PR TITLE
Rover: added optional AdvancedFailsafe

### PR DESCRIPTION
**Pull request by khancyr**
Following https://github.com/ArduPilot/ardupilot/pull/4714

### CODE REVIEW

**Comment by khancyr** [comment]
not tested .

**Comment by gmorph** [comment]
@khancyr - did you want to rebase this on master and update it and we will pull it in?

**Comment by khancyr** [comment]
@gmorph, yes I was waiting for the cleanup before rework that !

**Comment by khancyr** [comment]
close for https://github.com/ArduPilot/ardupilot/pull/5644

**Pull request closed without merging**
