### PR TITLE
SITL: add code to add, remove or corrupt bytes in SITL::SerialDevice …

### PR DESCRIPTION
**Pull request by peterbarker**
…xfrs

### CODE REVIEW

**Review by magicrub — COMMENTED** [review]
Why aren't all simulators enabled in SITL? Shouldn't this all be behind params to enable and/or control more/less corruption?

**Review by khancyr — APPROVED** [review]
LGTM, SITL + behind a define zeroed by default so that is fine

**Review by peterbarker — COMMENTED** [review]
So this isn't quite right in terms of when it applies the corruption (need persistent state to corrupt a percentage of bytes, probably), but I found this quite useful as-is, and it's not active by default.

**Comment by peterbarker** [comment]
> Why aren't all simulators enabled in SITL? 

This isn't a simulator?

> Shouldn't this all be behind params to enable and/or control more/less corruption?

Possibly?  But I used this patch in a bit of a hacky manner on two PRs recently and found it quite useful, and thought it better to have it in behind a `#ifndef` than not in at all.

The current formulation is actually a bit problematic in that it corrupts the data going to the simulator - and most simulators are *very* strict about the data they're receiving from the autopilot - on purpose, because we're supposed to be validating the autopilot output!

I agree that it might be interesting to see what happens when we throw corrupted data at all device drivers in the autotest suite - but not something I plan on doing right now.

Also, apologies for merging without reading your comment - didn't refresh the page before merging....

**Pull request merged**
