### PR TITLE
MatekH743 VSW controlled by relay and automatically enabled

### PR DESCRIPTION
**Pull request by andyp1per**
Pin gets no power by default without this and the pad has to be soldered as well

### CODE REVIEW

**Comment by andyp1per** [comment]
@Hwurzburg 

image

pad needs to be soldered for vsw to have power and also GPIO needs to be high

**Comment by Hwurzburg** [comment]
@andyp1per there are many H743s that use this software....only the Slim has the need to solder a pad, fyi...and that really has nothing to do with ArduPilot....but I am curious as to why the the change to the logic...for all the H743s with Vsw, there are defaults to setup the GPIO and have it turned on such that Vsw is on....perhaps not in the bootloader....is this why this PR is needed? this function has been in many H743 versions previously and seemed to work ....

**Comment by andyp1per** [comment]
In my setup the pad is unpowered by default, even if the pad is soldered.

**Comment by Hwurzburg** [comment]
I have many H743 /H765....some use the Vsw  I beleive...some do not..instead of digging thru all of them, I have a NIB H743Wing that I will setup and check with current code to verify that Vsw works, or not as default...

**Comment by Hwurzburg** [comment]
just pin populated a new MatekH743Wing, and it powers up Vsw by default.....programming RELAY to  81, allows me to turn it off from MP...admittedly the logic seems inverted....RELAY set high turns it off, set low turns on, toggle winds up with power on....

I imagine the other FCs like the F765/405-wse all behave the same....strange that the SLIM is the only one that does not power Vsw by default (Assuming the pad is soldered)...why would they change the electrical logic for that board?.....in any case, this PR would reverse that RELAY high/low logic? if so thats a behaviour change for the other H743s  correct? unless I misunderstand

**Comment by andyp1per** [comment]
@Hwurzburg you are right, something is off here - I will have to dig a bit deeper on my board

**Pull request closed without merging**
