### PR TITLE
AP_GPS: Do not set the bit decision.

### PR DESCRIPTION
**Pull request by muramura**
To change the bit field.
To change from multiple ignore bit to multiple have bit.
Using this have bit on the condition of the if statement.
It becomes even more simple.

### CODE REVIEW

**Comment by magicrub** [comment]
Ok, this is certainly a good improvement and is easy to read. However, it now requires the struct declaration to match the packet definition so the struct def can't hide in the function like this. It needs to be somewhere else for easier maintenance.

**Comment by muramura** [comment]
@magicrub Comments Thanks.
I thinks.
Bit fields structure defined "GCS_MAVLink/include/mavlink/v2.0/common/common.h"

**Comment by magicrub** [comment]
does MAVLink 2.0 offer bit fields? I'm pretty sure <= 1.0 does not

**Comment by muramura** [comment]
@magicrub Comment Thank you.

Checked Version of MAVLink you are using is V2.0.
Ahead to try to PR in version 2.0.

ex.
ardupilot/build/sitl/libraries/GCS_MAVLink/include/mavlink/v2.0/common/common.h

**Comment by magicrub** [comment]
Please link to where bitwise operations are defined and/or used in MAVLink

**Comment by muramura** [comment]
To change the thinking in the bit sequence from the structure.
To close this PR.

**Pull request closed without merging**
