### PR TITLE
Module DroneCAN: fix Jon's name - non-functional change. Just proper respect!

### PR DESCRIPTION
**Pull request by magicrub**
fixes Jon Challinger's spelling in the Copyright stuff. Non-functional change.

Depends on https://github.com/dronecan/dronecan_dsdlc/pull/3

### CODE REVIEW

**Review by tridge — APPROVED** [review]

**Review by tridge — CHANGES_REQUESTED** [review]
needs rebase, wrong git hash
also spelling of "spilling" is interesting

**Comment by magicrub** [comment]
Oh come on.. the spelling was intentional :)

**Comment by rmackay9** [comment]
@magicrub i'm sure you're busy but you can fix this up soon right?  Just trying to get our outstanding PRs below 500..

**Comment by magicrub** [comment]
rebased and git hash fixed

**Pull request merged**
