### PR TITLE
AP_CanManager: use milliseconds for timeout

### PR DESCRIPTION
**Pull request by peterbarker**
The use of PRIu64 was breaking people's builds

### CODE REVIEW

**Comment by peterbarker** [comment]
@bugobliterator was there a reason this was using micros?

**Comment by bugobliterator** [comment]
> The use of PRIu64 was breaking people's builds

This was added by @OXINARF . But yeah I don't see a reason for this.

**Comment by OXINARF** [comment]
I don't remember anymore why I used micros there. However, I think this isn't going to fix it since there are other PRI* macros in there. In my opinion, the fix should be to include the cinttypes header as my original code does.

**Comment by peterbarker** [comment]
> I don't remember anymore why I used micros there. However, I think this isn't going to fix it since there are other PRI* macros in there. In my opinion, the fix should be to include the cinttypes header as my original code does.

Nuked the extra uses of PRI* - thanks.

I *am* tempted to just make the include as least-possible-fix, mind you.

This current PR will save 4 bytes per ESC.... 

Hmmm.

**Review by tridge — APPROVED** [review]

**Comment by tridge** [comment]
using PRIu64 is correct, but hard to read. Discussed on the call, decided to approve

**Pull request merged**
