### PR TITLE
Mavlink: Update to HEAD from master branch and add upstream updates f…

### PR DESCRIPTION
**Pull request by amilcarlucas**
…rom 20200129

This is to test if the upstream mavlink changes break the code

### CODE REVIEW

**Comment by amilcarlucas** [comment]
All checks passed, this can be merged after https://github.com/ArduPilot/mavlink/pull/127

**Comment by tridge** [comment]
I've merged the mavlink changes, but I'd like @peterbarker to have a look at the GENERATOR_STATUS change to make sure it doesn't impact on his use case

**Comment by peterbarker** [comment]
On Tue, 28 Jul 2020, Andrew Tridgell wrote:

> I've merged the mavlink changes, but I'd like @peterbarker to have a look at the GENERATOR_STATUS change to make sure it doesn't impact on his use case

There's an outstanding PR to use the newly-shaped message.  Should be 
merged in the next day or so.

**Comment by amilcarlucas** [comment]
@peterbarker can this go in now then? I would like to rebase and prepare the other mavlink PR

**Comment by peterbarker** [comment]
I'll resolve the generator conflicts in the PR.

Thanks, merged!

**Pull request merged**
