### PR TITLE
AP_Param:  fix parsing for lines >100 characters

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by peterbarker** [comment]
Tested in SITL using this patch:
```
diff --git a/libraries/AP_Param/AP_Param.cpp b/libraries/AP_Param/AP_Param.cpp
index 1eb7b3fb29c..440f2cfd45d 100644
--- a/libraries/AP_Param/AP_Param.cpp
+++ b/libraries/AP_Param/AP_Param.cpp
@@ -117,7 +117,19 @@ const AP_Param::param_defaults_struct AP_Param::param_defaults_data = {
     "PARMDEF",
     { 0x55, 0x37, 0xf4, 0xa0, 0x38, 0x5d, 0x48, 0x5b },
     AP_PARAM_MAX_EMBEDDED_PARAM,
+#if CONFIG_HAL_BOARD == HAL_BOARD_SITL && !defined(HAL_BUILD_AP_PERIPH)
+    308,
+    "AHRS_EKF_TYPE 0 # this is a comment\n"
+"#another comment\n"
+"# yet another comment\n"
+"SERIAL5_PROTOCOL 13\n"
+"  SERIAL5_BAUD 5678\n"
+"# ------------------------------------------------------------------------------------------------------------------------------------------------------\n"
+"    SERIAL4_BAUD 1234\n"
+"SERIAL3_BAUD 2345\n"
+#else
     0
+#endif
 };
 #endif
 
```

**Comment by peterbarker** [comment]
Also tested on CubeOrange with this patch:
```diff --git a/libraries/AP_HAL_ChibiOS/hwdef/CubeOrange/defaults.parm b/libraries/AP_HAL_ChibiOS/hwdef/CubeOrange/defaults.parm
index 05d30c8e6f1..5ffe5132f01 100644
--- a/libraries/AP_HAL_ChibiOS/hwdef/CubeOrange/defaults.parm
+++ b/libraries/AP_HAL_ChibiOS/hwdef/CubeOrange/defaults.parm
@@ -9,3 +9,5 @@ BATT2_VOLT_MULT 12.02
 ADSB_TYPE 1
 SERIAL5_BAUD 57
 SERIAL5_PROTOCOL 1
+------------------------------------------------------------------------------------------------------------------------------------------------------
+SERIAL5_BAUD 4567
```

SERIAL5_BAUD was set and ADSB_TYPE was correct too.

**Comment by tridge** [comment]
@peterbarker my change is a lot smaller and more obvious. I want this in 4.3.0, so I want a simple patch that is very obvious

**Comment by peterbarker** [comment]
My PR here adds 52 bytes - for no real advantage.  Closed.

**Pull request closed without merging**
