### PR TITLE
Copter support for MAV_CMD_NAV_DELAY

### PR DESCRIPTION
**Pull request by rmackay9**
This replaces the PR raised by nititrohilla which adds support for the MAV_CMD_NAV_DELAY.
https://github.com/ArduPilot/ardupilot/pull/3922

I haven't tested it in the simulator yet but I think it's fairly close to being able to go into master.
One additional thing I've noticed is the four additional test missions is probably a bit much (one is more than enough or better yet let's just add it to one of the existing test missions that gets run automatically).

Anyway, all comments welcome.

### CODE REVIEW

**Comment by rmackay9** [comment]
ok, so looks like we have some kind of small issue perhaps with the mavlink submodule update.

**Comment by OXINARF** [comment]
@rmackay9 Yep, the commit referenced in the submodule update doesn't exist in our repo. You need to pick that into our mavlink repo and use that commit.

**Comment by rmackay9** [comment]
merged.  Hopefully the updates to ardupilot/mavlink have also worked.

**Comment by nitirohilla** [comment]
Thanks @rmackay9

**Pull request closed without merging**
