### PR TITLE
Correct nanf() usage

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by tridge** [comment]
why don't we just use NaN?

**Comment by peterbarker** [comment]
Original nan PR and discussion on nanf is here: https://github.com/ArduPilot/ardupilot/pull/6607

**Comment by OXINARF** [comment]
I'm not against this, but what is the reason for this change? The argument to nanf should be able to have characters, doesn't need to be a number.

**Comment by WickedShell** [comment]
@peterbarker more PR comments that way just the people you talked to offline are tracking!

@OXINARF Peter did some testing which we were chatting about offline, the compiler appears to be converting the passed string to a integer internally and then using that for the tag. So tagging it as "ARDUPILOT" didn't actually add anything to the emitted NAN, while sending "1" would set the value to 1 intenrall. This patch gets us back to a useful value of NAN from the compiler.

I can't recall if this was clang vs gcc that Peter tested on, but we'd like to be able to use both of them anyways, so its worth going with a behaviour that works on both.

**Comment by OXINARF** [comment]
@WickedShell Ok, that was what I was thinking, but I wasn't sure if it was tested. Was some test done in a PX4 board? I'm asking because after I did my comment I search and:

- Clang expects the string to be an integer
- Glibc uses *strtoull*, so again, it should be an integer
- GCC built-in parses it like _strtol_, so integer too
- newlib ignores the string completely (our PX4 toolchain has newlib included hence my doubt)

**Comment by OXINARF** [comment]
@peterbarker @WickedShell Has either of you tested this in PX4? I guess it doesn't hurt to merge it, but it would be good to know what it does there.

**Comment by WickedShell** [comment]
@OXINARF I have not yet done so.

**Comment by WickedShell** [comment]
Tested against SITL where it at least does the right behavior. I'd nominate we should just get this merged, it's worth a second pass later to test PX4 (my card readers are misbehaving at the moment, but SITL at least results in the expected result, which is a good indicator that the other linux boards will as well which is worth the change alone.

**Comment by peterbarker** [comment]
OK was given to merge this on the call today.

**Pull request merged**
