### PR TITLE
Copter:added new attitude re-initialization mode

### PR DESCRIPTION
**Pull request by SwiftGust**
it's actually extended application of flip mode and it works since AC has good navigation/control system
this might help preventing accidental vehicle loss from pilot's mistake or else
done/tested with own quad last july using AC 3.3 rc 7(?) version so some function would not work 
tested out with own code of launch / free-fall detection 
and found out it also works even from inverted attitude to up-right within a sec

### CODE REVIEW

**Comment by magicrub** [comment]
If I'm not mistaken, as of this PR this is dead code and therefore will not be accepted.

- There is no change to the make file to compile it
- No other existing code was changed to utilize this
- All files must have the GPLv3 license at the top, this one does not
- The file has lots of whitespace problems, namely a blank line on every other line. It looks suspiciously like a copy/paste from another project. If so, then there may be a licensing issue.

**Comment by magicrub** [comment]
@rmackay9 can you take a look and close if you agree

**Comment by R-Lefebvre** [comment]
For sure there are formatting problems, but I think that, and the lack of license, is not an indication it was copy/paste.  It uses too much existing Ardcopter-specific syntax.

I do not understand what the point of the mode is, instead of just switching to one of the existing modes like Stabilize?

**Comment by magicrub** [comment]
FIRST!
He also has this as a PR in his own fork :)
https://github.com/SwiftGust/ardupilot/pull/1

**Comment by SwiftGust** [comment]
thank you for replies
it's my first time committing code and found out to be lack in a lot of things.
this mode is for attitude re-initialization(to upright) even copter is inverted 
like roll or pitch at 180 degrees 
for example copter pilot practices acro mode but fail to control it's attitude
if you turn this mode on then copter will automatically re-initialize it's attitude to upright(hover)
and this code has been proven by replacing existing flight mode since i lack in skill

**Comment by magicrub** [comment]
How did you test this?

**Comment by R-Lefebvre** [comment]
But flipping to Stabilize mode, will also right the copter.

**Comment by SwiftGust** [comment]
replaced control_sport mode code that i don't use with this
and tested in SITL and in real
R-Lefebvre/ I didn't know that

**Comment by rmackay9** [comment]
It's great to see someone working on new flight modes.  Not that many people actually give it a try.

I agree with Rob though that any of the existing flight modes like Stabilize, AltHold, Loiter, RTL should right the copter so I don't think we need a specific recovery flight mode.

It's great to see this work and I hope you'll keep at it!

**Comment by SwiftGust** [comment]
thank you for reply
I didn't know those stabilize mode based attitude control mode has such function
it would be better to let everyone know about that

**Pull request closed without merging**
