### PR TITLE
EKF3: Covariance stability improvement

### PR DESCRIPTION
**Pull request by priseborough**
This PR eliminated the incorrect state variances that a user encountered during a fixed wing flight without a magnetometer that resulted in multiple height and vertical velocity variance resets when that log was replayed using single precision. Replaying the log using master with double precision also eliminated the issue.

The symptons are a collapse of the vertical velocity and position variances and a resulting failure of the EKF to correct vertical velocity and position to the sensor values.

Although default use of EKF3 is new to the ArduPilot community, PX4 have been using the same mathematics in their ekf2 module estimator since 2016 and collapse of variances associated with the vertical velocity and Z axis delta velocity bias have been detected in a small number of logs with a number of mitigations introduced over the years. This potential fix to the mathematics was uncovered by Mathieu Bresciani during investigation of one such occurrence. 

Whilst replay and SITL testing indicate a benefit, wider flight testing with LOG_DISARMED=1 and LOG_REPLAY=1 is required.

Here are the vertical position innovations for the original and replay using master with the --ekf-single processing option:

master - single

Here they are with replay using master with the default double precision processing - the behaviour is eliminated:

master - double

Here they are with replay using this PR with the --ekf-single precessing option:

derivation-single

If we look more closely at the original and replayed state variances for the original and replayed log using this PR with --ekf-single, we can see how the state variances for the vertical velocity (index 6) and position (index 9) collapse for the original log:

Screen Shot 2021-07-13 at 8 19 35 am

The current hypothesis for why this minor change to the prediction equations in the derivation improve stability is that it eliminates the presence of the qx quaternion in the rotation matrix x,x, qy in the y,y and qz in the z,z diagonals. Given that qx, qy and qz represent the cosines of a rotation vector along their respective axes, this intuitively makes sense. A rotation about Z for example should not change the projection of the Z earth axis along the Z body axis.

Even though the old and new equations are mathematically identical for a unit length quaternion, when the partial derivatives for the state transition matrix are calculated and used in the covariance prediction equation, the old equations may be resulting in higher order terms that lead to accumulation of unwanted numerical errors when single precision processing is used.

### CODE REVIEW

**Comment by priseborough** [comment]
This is a candidate for backport to 4.1 beta

**Comment by tridge** [comment]
@giacomo892 we'd appreciate you testing this on your Dart, thanks!

**Comment by priseborough** [comment]
Checking the GPS velocity innovations from the log shows that on replay the patch does reduce the size of the innovations when the vehicle switches to RTL, performs a turn and the yaw error becomes observable, eg:

image

**Comment by priseborough** [comment]
@tridge the CI build is failing due to frame size on the lowest spec boards. Is there a way to work around that?

**Comment by tridge** [comment]
@priseborough I've run the failing test.Copter.PrecisionLoiterCompanion test with replay, and get this:
image
the replay log built with master is here:
http://uav.tridgell.net/EKF/3-precloiter-replay.bin

**Comment by tridge** [comment]
new formulation matches SIM2 state more closely for PN and PE:
image
image
a bit worse for PD. PD is a surprisingly long way from the sim state:
image

**Comment by tridge** [comment]
VN and VE are improved (lane 0 is master, lane 100 is this PR):
image
image
VD goes both ways:
image

**Comment by priseborough** [comment]
> a bit worse for PD. PD is a surprisingly long way from the sim state:

It's actually tracking baro alt better than before see:

image

The error is in the simulated baro alt sensor:
image

**Comment by priseborough** [comment]
Overview of single precision replay logs with updated tune at commit https://github.com/ArduPilot/ardupilot/pull/18008/commits/e11a2c67968c0b3d25aade28ba943c6526047fd8

The new tune gives equivalent to silightly better tracking of GPS velociities (lower innovations) so the weighting of IMU vs GPS is approximately the same:
image

Bias esitimates estimates are smooth but do respond to changes in offfset when IMU temperature changes:

image

image

image

**Review by tridge — APPROVED** [review]

**Comment by priseborough** [comment]
The PrecisionLoiterCompanion test was failing due to a tight tolerance of 0.1m radially in the final position. Inspection of the log shows that this is due to a bias in the horizontal velocity innovation of 6 cm/s at the end of flight that offsets the position controller by 6 cm in esch axis. 

image

Retuning the filter to handle a faster changing gyro bias (EK3_GBIAS_P_NSE 0.0001 -> 0.001) reduced this to 1 cm/s and the corresponding position controller offset to 1cm in each axis 

image

However this gave a noisy gyro bias esitmate on replay of real flight logs, so a compromise tuning of 0.0003 will be adopted.

**Comment by giacomo892** [comment]
Replayed a log I had from another plane using MPU6000 (Omnibus F4 Pro) on which I had similar issues with EK3, and guess what:
image

**Comment by tridge** [comment]
@priseborough here is the new log from @giacomo892 https://uav.tridgell.net/EKF/z84red%20ahrs%20issues.BIN

**Comment by priseborough** [comment]
The autotests failing currently are:

1) Plane.FlyEachFrame where after landing, the autotester does not get the 'throttle disarmed' text it is looking for. The log shows that the vehicle does disarm. 

2) Copter.VibrationFailsafe where the changed filter tuning appears to have reduced the effectiveness of the current vibration compensation settings. These will need to be re-tuned.

**Comment by priseborough** [comment]
I'm still working on getting the Copter vibration failsafe working again. Changes made in the process are being pushed to https://github.com/ArduPilot/ardupilot/pull/18008

@rmackay9 I would be grateful for some assistance with this. The current stats when running 

'./Tools/autotest/autotest.py --no-clean --replay build.Copter test.CopterTests1c.VibrationFailsafe'

is that the "Vibration compensation ON" message is received, but it doesn't go into land mode.

**Comment by rmackay9** [comment]
@priseborough,

OK, the issue then is that the EKF is not losing its horizontal or vertical position estimate so the EKF failsafe isn't triggering.  The purpose of this test is not actually to test the EKF failsafe so I can imagine two changes that would resolve the failing test:

1. increase the vibration levels even higher so that it does lose its position fix
2. we could modify the test so that it ensure the vehicle altitude stays within some range (using real numbers, not EKF numbers).

The 2nd choice is probably the better one.

**Comment by tridge** [comment]
@priseborough please also note this PR:
https://github.com/ArduPilot/ardupilot/pull/18032

**Comment by priseborough** [comment]
The wind estimation when not using an airspeed sensor has been modified and the process noise and initial uncertainty retuned to give  a better result for the Plane test.Plane.DeadreckoningNoAirSpeed test with equivalent wind estimation for the two estimators:

Screen Shot 2021-07-17 at 4 58 06 pm

A number of factors were contributing to the poor EKF3 wind estimation performance in the test.Plane.DeadreckoningNoAirSpeed test:

1) Fusion of the default airspeed in EKF3 that is a average of ARSPD_ASPD_MAX  and ARSPD_ASPD_MIN combined with a TRIM_THROTTLE  that was too high caused the plane to exceed ARSPD_ASPD_MAX which degraded the airspeed estimate between turns. 

2) EKF started wind speed estimation earlier in flight, whereas EKF2 started much later after the  turn in guided mode had already started which gave EKF2 a better initialisation of the wind states. However this means the estimated airspeed derived from the EKF2 will be unavailable until then. 

3) The process noise on for the wind states on EKF3 require larger values due to the revised covariance prediction.

4) The wind estimation for the no airspeed behaviour was tuned originally for hand launches with an into wind throw assumption whereas the test is for a downwind runway takeoff. 

The wind estimation for a real flight log with airspeed sensor has also been checked on replay to check that we get acceptable state noise:

Screen Shot 2021-07-17 at 4 52 36 pm

**Comment by priseborough** [comment]
@rmackay9 I've reworked the copter vibration failsafe to resolve an issue encountered when running './Tools/autotest/autotest.py --no-clean --replay build.Copter test.CopterTests1c.VibrationFailsafe' 

After having modified the EKF to be more resistant to the type of large constant accel bias error in the auto-test the first problem was that the innovations were not large enough to set vibration_check.high_vibes to true, but were large enough to cause the height to progressively ratchet up each EKF reset cycle. This was fixed by exposing the EKF's internal badIMUstatus to the copter code - https://github.com/ArduPilot/ardupilot/pull/18008/commits/bed3c15fa2c188cda9aa6b0c590c45d8d36f99b8

The second issue was that even when vibration_check.high_vibe was triggering, the innovations were not large enough to trigger then land response which causes the autotest to fail. This was resolved by adding vibration_check.high_vibe as a LAND mode failsafe initiator - https://github.com/ArduPilot/ardupilot/pull/18008/commits/fce517fef45d1de95b6cb8d5f79ddd6c374f8482

As separate PR I want to include the INS clipping counter as a requirement in the EKF's internal bad IMU check and rework the CopterTests1c.VibrationFailsafe test to use a simulation of  IMU clipping in SITL.

**Comment by andyp1per** [comment]
Hey @priseborough I'm not sure how you plan to use the clipping information, but looking at the absolute count would be wrong - I have several copters that all clip in acro at high speed, but don't clip at all at low speed. It's quite common to fly around in manual dynamic flight and then to slow down and hit RTL. It's important not to prevent this.

**Comment by priseborough** [comment]
> Hey @priseborough I'm not sure how you plan to use the clipping information, but looking at the absolute count would be wrong - I have several copters that all clip in acro at high speed, but don't clip at all at low speed. It's quite common to fly around in manual dynamic flight and then to slow down and hit RTL. It's important not to prevent this.

@andyp1per I would AND the clipping and bad innovations within the EKF before it reports itself as vibration affected which would reduce the likelihood of a false positive. We could also disable the copters use of the EKF's reported vibration affected status to go into LAND mode via a failsafe option.

**Comment by giacomo892** [comment]
I've just flown the PR on my Dart. Everything looks good. No more EK3/DCM switching mid flight, and wind estimation is much much better. Thanks @priseborough !

**Comment by priseborough** [comment]
> I've just flown the PR on my Dart. Everything looks good. No more EK3/DCM switching mid flight, and wind estimation is much much better. Thanks @priseborough !

@giacomo892 are you able to share the log for the flight?

**Comment by giacomo892** [comment]
@priseborough https://mega.nz/file/dk4XyCwJ#4sqR4Jb6Q5KZ4IWR-T_9AlB5A-PDwwuOHetKVx1WJy8 short flight and poor GPS but might be worth checking

**Comment by priseborough** [comment]
@giacomo892 Thanks for that log. The EKF behaviour is as expected, but something to be aware of when operating without a compass is that the speed inaccuracy GPA.SAcc reported by the receiver was high enough during parts of flight that the GSF-EKF yaw estimator stopped using GPS and stopped the yaw calculation. 

The following plot shows the GPS reported speed accuracy, the GSF yaw estimate, the GSF yaw estimated 1-sigma accuracy and the EKF yaw. We can see that when the GPS reported error spikes, the GSF stops estimating yaw and restarts its yaw estimate which takes several seconds to converge again.

Screen Shot 2021-07-18 at 9 31 58 pm

Fortunately this happened after the EKF had aligned the yaw and started using GPS. If it had happened earlier, the yaw alignment and commencement of GPS navigation would have been delayed by several seconds.

In separate PR I will improve this behaviour by keeping the yaw prediction from the GSF running when the GPS error spikes, but not correct it using the GPS velocity. The reported 1-sigma uncertainty will grow when this is happening, but it will provide an estimate if one is required in an emergency.

**Comment by giacomo892** [comment]
Cool, also consider that the GPS was very weak cause by a combination of noise and low quality GPS unit. Have to address that.
Still nice if you improve the behaviour

**Comment by priseborough** [comment]
Conflict fixed and rebased on master. 

The tuning param changes to the IMU noise, biases and wind velocity states have been reverted. This gives noisier state estimates, but is required until the EKF can discriminate between boards using the following information:

- Lower sampling rate IMU's that are more susceptible to vibration.
- Only one sensor so there is no backup IMU and EKF  to fall back on if the IMU develops a rapid bias  change.
- The IMU's are temeprature calibrated so the likelihood of a rapdi change is bias is reduced.

**Pull request merged**
