### PR TITLE
Global: Change to is_positive and is_negative

### PR DESCRIPTION
**Pull request by muramura**
Change the floating value 0.0 to large and small to IS_POSITIVE and IS_NEGATIVE.

Unify the decisions.

### CODE REVIEW

**Comment by peterbarker** [comment]
This is remarkably expensive:
```
Board,plane
Pixhawk1-1M-bdshot,248
```

**Comment by tpwrules** [comment]
It appears the `is_negative` and `is_positive` functions have a somewhat strange definition of greater than/less than zero (i.e. abs(n) > ~1e-7), but non-denormal floats can be as small as 1e-38. It's unclear if this was intended by the functions' original author.

This would (very slightly) change behavior and explains the size delta.

**Comment by khancyr** [comment]
even if mathematically more correct, it is unnecessary in most of those case. I would vote to close this and not try to check each case one by one to see if that usefull or not.

**Review by tridge — CHANGES_REQUESTED** [review]
is_positive() is used when we will be doing operations like division to avoid an overflow
it is not correct for a boolean decision, such as to use speed_up vs speed_down, as otherwise values less than FLT_EPSILON and greater than 0 will go through the wrong if path

**Comment by tridge** [comment]
@muramura we discussed on the EU dev call, decided nearly all cases were incorrect, so closing

**Pull request closed without merging**
