### PR TITLE
Blimp: Add Blimp vehicle support

### PR DESCRIPTION
**Pull request by MichelleRos**
This pull request adds support for finned blimps to ArduPilot. It is implemented as a new vehicle-type.

It has had quite a few flight tests to test the main functions although there are still a few (mostly) cosmetic things that are not working (for example, vehicle & mode names on ground stations).

It supports a single frame type which has four fins arranged as per the video below.

Currently it has two modes: Manual and Land. Manual simply gives direct control over the blimp and land stops all fin movement. 

This video demonstrates the flight in manual mode:
https://www.youtube.com/watch?v=_aHBc4lBdKQ
Note that the silver balloon was painted black to allow the blimp to be used with Vicon, although currently it is only used as a location/attitude source in logging as autonomous modes haven't been implemented yet.

### CODE REVIEW

**Comment by magicrub** [comment]
>as autonomous modes haven't been implemented yet

making this it's own vehicle target seems totally overkill. Why doesn't copter work as-is? I have a feeling just a tiny tweak in copter would suffice.. if that.

**Comment by MichelleRos** [comment]
> > as autonomous modes haven't been implemented yet
> 
> making this it's own vehicle target seems totally overkill. Why doesn't copter work as-is? I have a feeling just a tiny tweak in copter would suffice.. if that.

For the manual control that I currently have, perhaps. But  I am going to be adding the autonomous functions to it next - full autonomous flight is the aim of my master's degree - so once I start implementing that, I think it will get a bit messy to try to fit it into Copter.

**Comment by IamPete1** [comment]
I'm fairly sure you could use the new copter 6DoF attitude control backend and add a new AP_Motors backend to do the flapping. I think all existing copter functionally should work without change.

**Comment by MichelleRos** [comment]
> I'm fairly sure you could use the new copter 6DoF attitude control backend and add a new AP_Motors backend to do the flapping. I think all existing copter functionally should work without change.

When @tridge and I originally spoke about how to add Blimp support, we considered adding it to Copter. We also thought about adding it to Sub given that Sub has neutral buoyancy and other similarities, but we ended up deciding that there are still enough differences to make it a separate vehicle.

**Comment by tridge** [comment]
rebased and commits cleaned up

**Comment by tridge** [comment]
> making this it's own vehicle target seems totally overkill. Why doesn't copter work as-is? I

it really doesn't behave like a copter, and trying to get the changes into a mature vehicle like copter would be a nightmare in terms of release management. I think we are much better off as a separate vehicle type

**Review by tridge — APPROVED** [review]

**Comment by tridge** [comment]
there are things that could be cleaned up in this PR, but I think we should get the base vehicle support in then work on followup PRs
@rmackay9 are you ok with that approach?

**Comment by tridge** [comment]
after discussion with @rmackay9 we are happy to merge now 
@MichelleRos congrats on introducing a new vehicle type to ArduPilot !

**Comment by MichelleRos** [comment]
> @MichelleRos congrats on introducing a new vehicle type to ArduPilot !
Thanks. 😀
And thank you so much for all your help in this!

**Pull request merged**
