### PR TITLE
Add a function so Lua can control RC inputs

### PR DESCRIPTION
**Pull request by FrederickBoisvert394**
I apologize in advance if there are any errors, this is my first time writing in a .desc file.

### CODE REVIEW

**Comment by IamPete1** [comment]
What is the use case? This is a very big hammer to give to lua.

**Comment by FrederickBoisvert394** [comment]
I would like to control a tilting canard with dual linear actuators.

**Comment by IamPete1** [comment]
@FrederickBoisvert394 Why do you need RC input for that? The go to to method would be to read out the exiting tilt output function do whatever to it and then output to a scripting servo function. Maybe if you share your script I can help. I'm sure overwriting RC input is not the right way to do it.

**Comment by FrederickBoisvert394** [comment]
@IamPete1 , I am pretty sure it has something to do with the equipment we are using (I am working for a company). I will relay your question to my team and get back to you.

**Comment by FrederickBoisvert394** [comment]
I have consulted my team and I can give you the following details: The targeted canards are actually moved by a linear actuator. Said actuators are controlled by a microchip, to which we can only communicate via RC Channel, which is why we need Lua to be able to override said channel. If you know a function that could work better, please let me know, I am open to suggestions.

**Comment by IamPete1** [comment]
@FrederickBoisvert394 It sounds like you want to output the RC channel from ArduPilot to the linear actuator? See this example of setting a PWM ouptut:
https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Scripting/examples/servo_scan.lua

Its very hard to give useful advice with so little to go on.

**Comment by FrederickBoisvert394** [comment]
@IamPete1 Sorry if my descriptions aren't clear, I'm still new to the world of aircrafts. The linear actuator will be controlled by a Jrk G2 motor controller. [https://www.pololu.com/product/3147](url) The electric and mechanic teams want ardupilot to communicate with it via RC Channel.

**Comment by IamPete1** [comment]
I'm sure we can already do what you need, a RC output, as in the example script I linked.

This PR would allow scripting to control a RC input. That would give scripting huge power to override commands from the pilot, something that we should not do with out careful thought and a clear use case.

**Comment by FrederickBoisvert394** [comment]
Forgive me if this question is silly, but I just want to make sure: Will I be able to change the output of a RC channel with this function despite it being a servo channel function?

**Pull request closed without merging**
