### PR TITLE
Copter/GCS_MAVLink:  Change the component ID to be able to set it.

### PR DESCRIPTION
**Pull request by muramura**
I'm considering implementing two or more FCs on a 1 airframe.
Component IDs from 25 to 75 can be defined by the user.
I have ArduPilot pegging the component ID to 1.
When I connect two FCs with UART, they get mixed up.
Therefore, I will allow you to specify the component ID.

IMG-7519

### CODE REVIEW

**Comment by peterbarker** [comment]
I've rebased this.

**Comment by peterbarker** [comment]
OK, so this works as advertised; it will change your component ID.

However, without something like https://github.com/ArduPilot/ardupilot/pull/10527 - this doesn't really accomplish anything as both autopilots will respond to any component ID they don't have a mavlink route for.

Does this patchset make sense to merge before we have something like the PR I mentioned?

**Comment by khancyr** [comment]
I think this is a safe addition as it doesn't change the default behavior, however, I would like this change to be done on all vehicles at once. And that is needed to compile !
@muramura could you make it done for all vehicle ?

**Comment by peterbarker** [comment]
This has had NeedAnswer and NeedRework on for 4 years.

There might be something here, but we've seen redundant systems now and they use different system IDs, not different component IDs.

We'd need a fresh PR to discuss now, so I'm closing this now.

**Pull request closed without merging**
