### PR TITLE
GPS: Remove MTK binary drivers, divert them to NMEA backends

### LINKED ISSUE #7081: broken support for MTK GPSes
this commit (https://github.com/ArduPilot/ardupilot/commit/2f8f2ffd2dec1d85546cc9b8f2e875d9b77fb4c9) removed initialization for NMEA GPS. But binary protocols for MTK is under "#if !HAL_MINIMIZE_FEATURES" so don't present in precompiled binaries. In result, GPS based on MTK chipsets, even on world's best MT3333, now don't works correctly without recompiling or tuning GPS via special tool.

### PR DESCRIPTION
**Pull request by WickedShell**
Resolves #7081 by piping all MTK support to the NMEA backends. They share the same capabilities so this should be acceptable unless there is an old board that doesn't support NMEA for some reason. This also effectively restores MTK support across all boards regardless of flash space without needing to save configuration.

@night-ghost can you test this? I don't have any of the relevant hardware unfortunately.

### CODE REVIEW

**Comment by WickedShell** [comment]
@night-ghost can you verify that this works with a MTK GPS? I'm afraid I don't have any hardware to test with for this.

**Comment by tridge** [comment]
needs testing, I have one of the original 3DR MTK GPS modules to try

**Comment by tridge** [comment]
I tested current master with an original 3DR MTK GPS and it works fine, and detects the MTK binary protocol
 - APM: GPS 2: detected as MTK19 at 38400 baud

**Comment by WickedShell** [comment]
@tridge right, that is expected if it's not a minimized board, but on any board with minimize features it is reported as broken/maybe broken? (For use in nmea as the fallback). The real question is can you use this PR which forces it into nmea mode and have that GPS work.

**Comment by tridge** [comment]
I tested this build and it didn't work on my MTK GPS with GPS_TYPE=1

**Comment by WickedShell** [comment]
That's actually expected, what about GPS_TYPE 3 (or 4)

**Comment by khancyr** [comment]
@WickedShell do you want to pursuit this or we can close this ?

**Comment by WickedShell** [comment]
Yes, I'm still stuck on someone testing the hardware though.

**Pull request closed without merging**
