### PR TITLE
SITL: use a thread to create sockets for RealFlight

### PR DESCRIPTION
**Pull request by tridge**
this reduces the cost of the socket creation on each frame, resulting
in higher frame rates. Typical improvement is around 30%

### CODE REVIEW

**Comment by IamPete1** [comment]
For me on WSL1 this is slightly slower and on Cygwin it is about the same average frame rate but a little more inconsistent.

**Comment by tridge** [comment]
> For me on WSL1 this is slightly slower and on Cygwin it is about the same average frame rate but a little more inconsistent.

how are you measuring it? Note that the frame rate displayed in the widget on RealFlight is not the one to look at. That is the RF9 graphics rate. The one to look at is displayed on ArduPilot terminal, like this:
image
what was happening was that ArduPilot wasn't getting the full frame rate that RF9 achieved. So the number displayed in RF9 was considerably higher than the number in the first column that ArduPilot actually gets.

**Comment by tridge** [comment]
this is my result on cygwin:
image

**Comment by IamPete1** [comment]
Cygwin with average of 479 and standard deviation of 58
image

without average of 452 and standard deviation of 77
image

So a definite improvement on local Cygwin now random RealFlight physics level bottleneck is removed.

**Comment by IamPete1** [comment]
WSL1 with average of 625  standard deviation of 63

image

WSL1 without average of 493 standard deviation of 46
image

Very nice improvement!

**Comment by IamPete1** [comment]
WSL2 is still un-usable.

**Review by IamPete1 — APPROVED** [review]
A Nice improvement, picks up almost exactly 14% on both WSL1 and Cygwin. 

We also learned to only use the "Realistic" physics setting. ;)

**Pull request merged**
