### PR TITLE
AP_Frsky_Telem: fix compilation when frsky bidir is disabled

### PR DESCRIPTION
**Pull request by tatsuy**
This allows to build with "define HAL_WITH_FRSKY_TELEM_BIDIRECTIONAL 0".

### CODE REVIEW

**Comment by tatsuy** [comment]
@yaapu Thank you for your advice!
```
CubeOrange
Target          Text (B)  Data (B)  BSS (B)  Total Flash Used (B)  Free Flash (B)
---------------------------------------------------------------------------------
bin/arducopter   1780540      3492   258876               1784032          182040 // AP_FRSKY_TELEM_ENABLED=0
bin/arducopter   1801888      3492   258872               1805380          160696 // HAL_WITH_FRSKY_TELEM_BIDIRECTIONAL=0
bin/arducopter   1805496      3492   258872               1808988          157088 // master(c69e90be)
```

**Comment by peterbarker** [comment]
Rebased this.  Also added it to build_options.py

This define is pretty poorly named; modern style would be something like `AP_FRSKY_BIDIRECTIONAL_TELEMETRY_ENABLED`

@tatsuy this doesn't currently compile for me with this command-line:
```
./Tools/scripts/size_compare_branches.py --board=CubeOrange --vehicle=copter --extra-hwdef=/tmp/extra.hwdef
```

```
pbarker@fx:~/rc/ardupilot((HEAD detached at 1e001fa0174))$ cat /tmp/extra.hwdef 
define HAL_WITH_FRSKY_TELEM_BIDIRECTIONAL 0
pbarker@fx:~/rc/ardupilot((HEAD detached at 1e001fa0174))$ 
```

Needs to :-)

**Review by peterbarker — CHANGES_REQUESTED** [review]
Needs to compile with feature disabled

**Review by peterbarker — APPROVED** [review]
Bleh.

Never mind.  size_compare_branches.py was failing on *master* as it should!

**Comment by tatsuy** [comment]
@peterbarker Thank you for rebasing and updating!

**Comment by peterbarker** [comment]
Merged, thanks!

**Pull request merged**
