### PR TITLE
Yet more zero throttle and relax

### PR DESCRIPTION
**Pull request by peterbarker**
This is based on top of https://github.com/ArduPilot/ardupilot/pull/7462

These are the problem bits which are related to zero-throttle-and-relax and need staring at.

### CODE REVIEW

**Comment by OXINARF** [comment]
@peterbarker Feel free to rebase, first two commits are now in master.

Just to be clear for anyone reviewing this: the issue in the last commit is that it changes code for Heli and we aren't sure it is correct or not. More specifically, in Land, it looks to me (and @R-Lefebvre) that Heli is doing the right thing and Multi is doing the wrong - comparing it to AltHold supports that idea.

**Comment by peterbarker** [comment]
@ChristopherOlson In terms of having throw "enter the build" - at some stage it would be nice not to have separate builds for Heli and multicopter, so adding more `#ifdef`'s isn't great IMO.  Not allowing the vehicle to enter the mode is where we should be there - like we do for throw.

The reason this PR exists is that it does actually change behaviour for existing modes.
I think any change to autotune is fine as we're very unlikely to support autotune on a heli :-)

Drift mode seems to be allowed on Copter, and behaviour is changing here.  As it currently stands, if you bring your helicopter to the ground and reduce the throttle (or engage the interlock, or do whatever else meaning we're probably sitting on the ground) then we will NOT do what we do in other modes like `ALT_HOLD` where zero the desired attitude rates.  I *think* that means that you might end up with a desired rate but we'll never update that desired rate.... there's also the desired spool setting - no idea what effect that will have on a helicopter....

The same is true of position hold.

Land is a bit more contentious - it is specifying rates rather than zeroing them, and I'm not sure anybody quite knows why :-)  My patch zeroes them.

So there are actually some significant behavioural changes.  For the better IMO, but they do need to be studied by someone who actually knows helicopters! :-)

**Comment by rmackay9** [comment]
Merged except for the change to land mode.  I'm not completely sure but I think that the helicopters should try to stabilize the vehicle's attitude while landed (i.e. ap.land_complete = true) in modes where the pilot has control of the roll-pitch angles.

This is a good thing to do because land-complete false positives do occasionally happen especially with helicopters with their big propellers which can get a lot of lift from an updraft.  So the pilot keeps lean angle control in these bad cases.  With Peter's change it wouldn't be terrible though, the vehicle would just flatten out I think.  Remember that helicopters can keep controlling their attitude even when the throttle is zero because their propeller may still be spinning.  For multicopters there's no point in trying to control attitude while the throttle is zero.

In autonomous modes (including Loiter, Auto, etc) we definitely *do not* want the autopilot to try and control roll and pitch because more often than not, it will want to make them non-zero to try and correct some horizontal position error it sees due to the position moving around a bit.   So these roll-pitch inputs are more likely to cause the vehicle to flip.

**Comment by rmackay9** [comment]
Thinking about this more though, I suspect that multicopters could send the pilot's target-roll and target-pitch into the attitude controllers because it does no harm.  Once the follow-up call to set_throttle_out_unstabilized is made, the attitude controller will not do anything with the pilot's roll and pitch input.   This would remove one more difference from multicopters and helicopters.

**Comment by ChristopherOlson** [comment]
> Once the follow-up call to set_throttle_out_unstabilized is made, the attitude controller will not do anything with the pilot's roll and pitch input. This would remove one more difference from multicopters and helicopters.

I would tend to agree. Attitude control with helicopters, rotors turning, is always a good thing except if the helicopter is on the ground and the autopilot would try to move it to a different spot because the position estimate drifts, which is more likely to happen on the ground than in flight. But this would not make a difference with multicopters and will not harm anything for them, so there's no sense to having special treatment in that respect.

**Pull request closed without merging**
