### PR TITLE
Copter/Blimp: Allows the tune channel to be specified

### PR DESCRIPTION
**Pull request by muramura**
RC6 can be assigned functions in addition to tuning.
I will allow tuning channels to be specified in RCMAP.

ex Mission Planner
Screenshot from 2022-03-13 23-42-47

### CODE REVIEW

**Review by IamPete1 — CHANGES_REQUESTED** [review]
Better to add a new RCx_OPTION

**Comment by amilcarlucas** [comment]
I also vote for RCx_OPTION

**Comment by rmackay9** [comment]
Yes, definitely an RCx_OPTION value these days..

**Comment by muramura** [comment]
The PR was re-promoted again.

**Pull request closed without merging**
