### PR TITLE
AP_Scripting: added AEROM_PATH_SCALE

### PR DESCRIPTION
**Pull request by tridge**
This allows a sequence to be scaled up or down as needed, and mirrored by using a negative scale

and add some docs on parameters

### CODE REVIEW

**Comment by andypnz** [comment]
This works very nicely indeed! Tested in SITL. 

For center maneuvers they of course only remain on center if the maneuver construction starts 'on center'. So when constructing say a Cuban eight, the maneuver path should start 'on center' with a length of straight flight before pulling into the first part loop. 

For other maneuvers this is not possible eg the barrel roll.  Here, it would be great to create an (optional) 'center distance' construct within the maneuver definition, so the center position could be maintained with schedule scaling.

**Review by andypnz — APPROVED** [review]

**Comment by tridge** [comment]
> Negative (reverse direction) scaling values not working for me.....

we better fix that

**Comment by tridge** [comment]
@andypnz mirroring should work now. It only worked for my first version when the path was nearly north. Now works for any path orientation

**Comment by andypnz** [comment]
Yep, now all good including mirroring :-)

**Review by andypnz — APPROVED** [review]

**Pull request merged**
