### PR TITLE
AP_NMEA_Output: correct 10Hz rate limiting

### PR DESCRIPTION
**Pull request by peterbarker**
integer promotion issue

### CODE REVIEW

**Comment by magicrub** [comment]
why is this 16bit?

**Comment by peterbarker** [comment]
On Wed, 27 Nov 2019, Tom Pittenger wrote:

> why is this 16bit?

To cause bugs, as it turns out.

16-bits has all the range we need for a 10Hz rate at ms precision.

It's a 2 byte saving for the retirement fund.

**Comment by rmackay9** [comment]
oh, I was just about to do this with the uint32_t..

**Comment by SMenne** [comment]
i wrote the new firmware on the cube and its working very stabil.
with the Here+ RTK do i get the RTK Data out or are just the Data from the Ublox handed through?

**Comment by rmackay9** [comment]
@SMenne,

Thanks for testing this out.  The nmea out data is not actually from the GPS directly but rather from the EKF which is mixing the GPS with accelerometers, etc..  This means if an RTK GPS is being used that the output will be more accurate.  This nmea output feature doesn't output any RTK related info though.

**Comment by SMenne** [comment]
im gonna test the accuracy soon when i got the chance to have a land surveyor with me. but when i see the accuracy of flying these days im very optimistic that it should fit

**Comment by rmackay9** [comment]
this has been included in Copter-4.0.0-rc3

**Comment by SMenne** [comment]
dear all,
today i change the software from 4.0.0.dev to 4.0.0. rc3.
unfortunately my receiver didnt recognize anymore the NMEA Protokoll. When I changed it back to the dev software everything was fine again.
The developer of my "Reciver" which is a Magnetometer  also told me that the best would be if the Protokoll wich is coming out is the NMEA-ZDA . That has got something to do with the Timecode. If you need more Informations I have to ask him again.
Thanks
screensho_dev
screenshot_RC3

**Comment by SMenne** [comment]
the top / 1st foto is the dev firmware wich is working, the second one is the rc3

**Comment by rmackay9** [comment]
@SMenne, ah, OK.  we've missed a commit.  Sorry but thanks for the report!  This may go into 4.0.1 instead of 4.0.0 I'm afraid but we shall see.

**Comment by SMenne** [comment]
@rmackay9, no problem and thanks. Question: is it so difficult to get this issue back to the 4.0.0._dev level. Because that was working very good, not perfekt, but very good. Then I could go on flying and testing the rc3 which I really would apriciate

**Comment by peterbarker** [comment]
Current 4.0 beta looks fine to me:

```
pbarker@bluebottle:~/rc/ardupilot((HEAD detached at ardupilot/Copter-4.0))$ telnet localhost 5765
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
$GPGGA,003058.785,3521.79573,S,14909.91425,E,1,06,02.0,0584.02,M,0.0,M,,*4E
$GPRMC,003058.785,A,3521.79573,S,14909.91425,E,0.04,320.73,201219,,*16
$GPGGA,003058.885,3521.79573,S,14909.91425,E,1,06,02.0,0584.02,M,0.0,M,,*41
$GPRMC,003058.885,A,3521.79573,S,14909.91425,E,0.04,320.38,201219,,*16
$GPGGA,003058.985,3521.79573,S,14909.91425,E,1,06,02.0,0584.02,M,0.0,M,,*40
$GPRMC,003058.985,A,3521.79573,S,14909.91425,E,0.04,320.50,201219,,*19
$GPGGA,003059.085,3521.79573,S,14909.91425,E,1,06,02.0,0584.02,M,0.0,M,,*48
$GPRMC,003059.085,A,3521.79573,S,14909.91425,E,0.04,320.38,201219,,*1F
$GPGGA,003059.185,3521.79573,S,14909.91425,E,1,06,02.0,0584.02,M,0.0,M,,*49
$GPRMC,003059.185,A,3521.79573,S,14909.91425,E,0.04,320.47,201219,,*16
$GPGGA,003059.285,3521.79573,S,14909.91425,E,1,06,02.0,0584.02,M,0.0,M,,*4A
$GPRMC,003059.285,A,3521.79573,S,14909.91425,E,0.04,320.11,201219,,*16
$GPGGA,003059.385,3521.79573,S,14909.91425,E,1,06,02.0,0584.02,M,0.0,M,,*4B
$GPRMC,003059.385,A,3521.79573,S,14909.91425,E,0.04,320.09,201219,,*1E
$GPGGA,003059.485,3521.79573,S,14909.91425,E,1,06,02.0,0584.02,M,0.0,M,,*4C
$GPRMC,003059.485,A,3521.79573,S,14909.91425,E,0.04,319.96,201219,,*15
$GPGGA,003059.585,3521.79573,S,14909.91425,E,1,06,02.0,0584.02,M,0.0,M,,*4D
$GPRMC,003059.585,A,3521.79573,S,14909.91425,E,0.04,320.04,201219,,*15
$GPGGA,003059.685,3521.79573,S,14909.91425,E,1,06,02.0,0584.02,M,0.0,M,,*4E
$GPRMC,003059.685,A,3521.79573,S,14909.91425,E,0.04,320.18,201219,,*1B
```

```
pbarker@bluebottle:~/rc/ardupilot((HEAD detached at ardupilot/Copter-4.0))$ git show
commit 2e0323f75aba352135f40b2307b97f15eab168a6 (HEAD, tag: ArduCopter-beta-heli, tag: ArduCopter-beta, ardupilot/Copter-4.0)
Author: Randy Mackay <rmackay9@yahoo.com>
```

**Comment by rmackay9** [comment]
@SMenne, as @peterbarker mentions above, we've re-checked Copter-4.0.0-rc3/-rc4 and it seems to include all the changes in master (i.e. Copter-4.0.0-dev).  I wonder if perhaps the Copter-4.0.0-dev that you're using is quite old and so we are comparing apples and oranges.  Could you re-test with "latest" (Copter-4.0.0-dev downloaded from MP's insteall firmware screen after pressing Ctrl-Q).

**Comment by SMenne** [comment]
@rmackay9 ; @peterbarker , 
when I found out that the 4-0-0_rc3 was not compatible with my "Reciver" I went straight away to the 
https://firmware.ardupilot.org/Copter/latest/CubeBlack/
directory and downloaded the firmware I found theire. I was happy, when I found out that that one was working because I thought that that one was changed also. In my worries I thought about my download folder, and thought that maybe some older versions I find in theire.  But that one was working. I attache that one i use.
Lucky as I am Im gonna fly to Australia in some days (@peterbarker: so happy!) and spend their the whole January. The Magnetometer stays here, so I cant test anymore for that Time.
Of cause i´m in Contact with the developer of that tool.


[arducopter.zip](https://github.com/ArduPilot/ardupilot/files/3990463/arducopter.zip)

**Comment by rmackay9** [comment]
@SMenne, ok, well, maybe when you're back you can re-test with the stable version of Copter-4.0.0 because it should be out by then.  For now we don't have any other reports of it not working and I think we need a non-working setup to get to the bottom of it... anyway.. when you're back let's continue the investigation.

**Pull request merged**
