### PR TITLE
AP_NavEKF: Correct the setting process of variable dAngBiasSigma.

### PR DESCRIPTION
**Pull request by muramura**
L977 and L980 are doing the same processing.
Therefore,
Delete L977.

Other 
Correct the tab code to spaces.
 Delete the space or tab code at the end of the line.

### CODE REVIEW

**Comment by OXINARF** [comment]
@muramura Please split the commit in two: one with just style changes (tab to spaces, etc.) and the other with the code change.

**Comment by muramura** [comment]
@OXINARF Comment thank you.
I understand.
I commit the following.
1. style changes (tab to spaces, etc.)
2. code change.

**Comment by OXINARF** [comment]
@priseborough Do you approve the second commit?

**Comment by priseborough** [comment]
Approved

**Pull request merged**
