### PR TITLE
Add 4 More User Params to Scripting

### PR DESCRIPTION
**Pull request by Gone4Dirt**
This PR adds 4 more user params to scripting.

This PR is a precursor to a larger scripting PR (will be PR-ing in the next few days).

### CODE REVIEW

**Comment by rmackay9** [comment]
I agree that we need more than 4.  On a recent project I really needed 5 or 6.

**Comment by IamPete1** [comment]
I should have another go at https://github.com/ArduPilot/ardupilot/pull/16198

**Comment by TunaLobster** [comment]
Was this closed by #19715?

**Comment by Gone4Dirt** [comment]
It is made unneeded by that pr yes.  Will close now.

**Pull request closed without merging**
