### PR TITLE
Rover: balancebot pitch control feedforward uses current pitch angle

### PR DESCRIPTION
**Pull request by rmackay9**
This PR improves the balance bot pitch control with these enhancements:

1. The feedforward is based on the sin of the vehicle's current pitch angle instead of its speed (see below for more details)
2. Pitch limit protection reduces the maximum desired pitch angle if the throttle output climbs over 60%.  This limit is configurable using the new ATC_BAL_LIM_THR and ATC_BAL_LIM_TC parameters
3. The default pitch angle max is increased from 2 to 10deg.  This is more representative of most frames.

These drive-by fixes are also included

- SITL's balancebot's tuning is adjusted so that it can also lean at 10deg
- Minor improvements to the BalanceBot Pitch angle tuning parameters

Re the feed forward change, this new method naturally increases the throttle as the vehicle leans over.  This immediate response reduces the amount of error that is left to the P, I and D terms and seems to greatly improve stability.  I've used the sin of the current pitch angle but this is a bit of a guess.

The old feedforward was added by me in PR https://github.com/ArduPilot/ardupilot/pull/9173 with the intention of improving the bots ability to travel at higher speeds.  The pitch limit protection accomplishes this much more successfully

This has been tested in SITL and on a real vehicle.

See video here https://www.youtube.com/watch?v=8EATOJRzBqs

### CODE REVIEW

**Comment by rmackay9** [comment]
FYI @EbinPhilip

**Comment by EbinPhilip** [comment]
@rmackay9 I think the idea is good, but I have a couple of doubts:

1) Sine of pitch, because the torque generated by the motors should be proportional to it, in order to achieve balance. Is that the reasoning behind your guess? 

2) The stability you observed is with Manual and Hold Mode, is it? Previously these modes were very unstable and uncontrollable. So this could be a big improvement.

3) Correct me if I'm wrong. At any non zero pitch, the ff term will add some compensation. I think this will always try to force the robot to correct and achieve zero pitch, like a P controller with setpoint as zero, right? Perhaps this is the cause for the stability that has been observed? Given the pitch controller is intended to achieve a **desired** pitch, can this become a hinderance for other modes, is what I'm wondering.

4) It can possibly impact speed control, since it depends on pitch control (cascaded PID). I believe it would be prudent to check how Acro, Guided and Auto modes are impacted by this change. Perhaps it may not be fatal, but speed controller performance may have been adversely impacted?

Anyway, even if the modes using speed control are impacted, it may not be a big problem. Since this is all tunable, I guess the user will have to choose what they require: good Manual mode performance or speed control, but not both?

I did not personally find the old way of applying ff to be helpful and therefore had recommended setting it to zero: https://ardupilot.org/rover/docs/balance_bot-tuning.html. We must change this in the documentation after the current change is proven, I guess.

I wish I could help with testing this, but sadly my balance bot is broken.

**Comment by rmackay9** [comment]
@EbinPhilip,

Thanks very much for the feedback.

1. My reasoning behind using the sin of pitch is that I think the amount of torque required to stop the rotation increases with lean angle of the vehicle.  In the simple cases this is easy to imagine but I'm actually not sure if we should use sin(pitch) or something else.
   - When fully upright gravity acting on the body is straight down and does not cause any extra rotational force.
   - At 90 degrees the rotational force is at its maximum
2. I have tested in Manual (which is really the same as Hold) and Acro and both appeared to perform better
3. If the feedforward gain is set too high then it could overcompensate and become higher than the actual rotational force caused by gravity.  I've tested setting the gain too high and the performance gets worse as the PID needs to fight more to lean the vehicle. over.
4. I think this change improves all modes because it improves the pitch control and the speed controller's output feeds into the pitch control.

No problem with testing, thanks again for the feedback and queries.

**Comment by rmackay9** [comment]
rebased on master to pickup the lastest fixes to autotest.

**Review by tridge — APPROVED** [review]

**Pull request merged**
