### PR TITLE
Move GPS instance parameters to a sub-object

### PR DESCRIPTION
**Pull request by peterbarker**
The new tool confirms correct transformation:
```
OK: GPS_TYPE=17.0 converted  to GPS_TYPE=17.0
OK: GPS_TYPE2=37.0 converted  to GPS2_TYPE=37.0
OK: GPS_GNSS_MODE=21.0 converted  to GPS_GNSS_MODE=21.0
OK: GPS_GNSS_MODE2=45.0 converted  to GPS2_GNSS_MODE=45.0
OK: GPS_RATE_MS=186.0 converted  to GPS_RATE_MS=186.0
OK: GPS_RATE_MS2=123.0 converted  to GPS2_RATE_MS=123.0
OK: GPS_POS1_X=3.75 converted  to GPS_POS_X=3.75
OK: GPS_POS2_X=6.9 converted  to GPS2_POS_X=6.9
OK: GPS_POS1_Y=2.75 converted  to GPS_POS_Y=2.75
OK: GPS_POS2_Y=5.9 converted  to GPS2_POS_Y=5.9
OK: GPS_POS1_Z=12.1 converted  to GPS_POS_Z=12.1
OK: GPS_POS2_Z=-6.9 converted  to GPS2_POS_Z=-6.9
OK: GPS_DELAY_MS=987.0 converted  to GPS_DELAY_MS=987.0
OK: GPS_DELAY_MS2=2345.0 converted  to GPS2_DELAY_MS=2345.0
OK: GPS_COM_PORT=19.0 converted  to GPS_COM_PORT=19.0
OK: GPS_COM_PORT2=100.0 converted  to GPS2_COM_PORT=100.0
OK: GPS_CAN_NODEID1=109.0 converted  to GPS_CAN_NODEID=109.0
OK: GPS_CAN_NODEID2=102.0 converted  to GPS2_CAN_NODEID=102.0
OK: GPS1_CAN_OVRIDE=34.0 converted  to GPS_CAN_OVRIDE=34.0
OK: GPS2_CAN_OVRIDE=67.0 converted  to GPS2_CAN_OVRIDE=67.0
OK: GPS_MB1_TYPE=1.0 converted  to GPS_MB_TYPE=1.0
OK: GPS_MB1_OFS_X=3.14 converted  to GPS_MB_OFS_X=3.14
OK: GPS_MB1_OFS_Y=2.18 converted  to GPS_MB_OFS_Y=2.18
OK: GPS_MB1_OFS_Z=17.6 converted  to GPS_MB_OFS_Z=17.6
OK: GPS_MB2_TYPE=1.0 converted  to GPS2_MB_TYPE=1.0
OK: GPS_MB2_OFS_X=17.14 converted  to GPS2_MB_OFS_X=17.14
OK: GPS_MB2_OFS_Y=12.18 converted  to GPS2_MB_OFS_Y=12.18
OK: GPS_MB2_OFS_Z=27.6 converted  to GPS2_MB_OFS_Z=27.6
```

I've tested AP_Periph parameter upgrade on a handful of parameters, including the MovingBaseline parameters.  And both instances.

I've gone with `GPS_` and `GPS2_` rather than `GPS1_` and `GPS2_` as that's our usual pattern.  We could change that.....

Yet to put this on real hardware.

### CODE REVIEW

**Comment by IamPete1** [comment]
I wonder if we should take the opportunity to change some of the params to be per instance, `_SAVE_CFG`, `_SBP_LOGMASK`, `_SBAS_MODE`, `_MIN_ELEV`, `_RAW_DATA`, `_AUTO_CONFIG` could all be per instance.

**Comment by peterbarker** [comment]
> I wonder if we should take the opportunity to change some of the params to be per instance, `_SAVE_CFG`, `_SBP_LOGMASK`, `_SBAS_MODE`, `_MIN_ELEV`, `_RAW_DATA`, `_AUTO_CONFIG` could all be per instance.

Yep, I'd wondered about that, but then figured maybe keep the change-in-functionality for future PRs would be better.  There's also the question for some of those parameters as to whether to go with magic per-backend parameter sets like we do the the Wasp rangefinder.

Incidentally, my goal here is to allow for >2 instances, and *that* requires a bunch of thinking around RTK base/rover pairing.

**Comment by tridge** [comment]
@peterbarker nice new tool!
did you test the tool by deliberately getting a param idx wrong and seeing it fails?

**Comment by peterbarker** [comment]
> @peterbarker nice new tool! did you test the tool by deliberately getting a param idx wrong and seeing it fails?

Oh yes.  On purpose some of the time ;-)

**Comment by tridge** [comment]
we've decided on GPS1_xxx

**Comment by peterbarker** [comment]
- GPS1_
 - need to fix the code which sets the type on the periph
 - need periph to consider an attempt to set GPS_TYPE as an attempt to set GPS1_TYPE
 -

**Comment by peterbarker** [comment]
I've done the rename from GPS_TYPE -> GPS1_TYPE.

I've tested new firmware with old AP_Periph, new Periph with old Firmware and new firmware with new periph.  The magic GPS_TYPE/GPS1_TYPE setting works in each case.

**Comment by peterbarker** [comment]
I've tested this on my edu650 with a pair of moving-baseline GPS units (Mosaic-H and C-RTK 2)

Everything works as it does on master.

**Review by tridge — APPROVED** [review]

**Pull request merged**
