### PR TITLE
Disable Solo Gimbal except on CubeSolo and CubeGreen-solo

### PR DESCRIPTION
**Pull request by peterbarker**
`Pixhawk1`:

image

Pixhawk1-1M isn't affected because it's already excluded.

CubeSolo is still the same - well, 12 bytes off...

I'd note that this means gimbal will stop working for users with a gimbal on CubeOrange.  I'm just copying the broken-ness because they'll also be missing OreoLED support....

### CODE REVIEW

**Review by amilcarlucas — APPROVED** [review]

**Comment by khancyr** [comment]
Lgtm, there won't be a lot of solo gimbal outside solo anyway, so that is manageable

**Review by khancyr — APPROVED** [review]

**Comment by peterbarker** [comment]
```
 Binary Name      Text [B]           Data [B]     BSS (B)       Total Flash Change [B] (%)      Flash Free After PR (B)
---------------  -----------------  -----------  ------------  ----------------------------  -------------------------
antennatracker   -808 (-0.0599%)    0 (0.0000%)  0 (0.0000%)   -808 (-0.0598%)                                  616768
blimp            -808 (-0.0626%)    0 (0.0000%)  0 (0.0000%)   -808 (-0.0626%)                                  675336
ardurover        -17848 (-1.1234%)  0 (0.0000%)  0 (0.0000%)   -17848 (-1.1221%)                                393360
arducopter-heli  -17736 (-0.9916%)  0 (0.0000%)  0 (0.0000%)   -17736 (-0.9898%)                                191940
ardusub          -17836 (-1.1373%)  0 (0.0000%)  4 (+0.0015%)  -17836 (-1.1360%)                                413800
arduplane        -17836 (-1.0136%)  0 (0.0000%)  4 (+0.0015%)  -17836 (-1.0119%)                                221232
arducopter       -17424 (-0.9801%)  0 (0.0000%)  0 (0.0000%)   -17424 (-0.9784%)                                202612
```

**Comment by peterbarker** [comment]
Tracker and Blimp don't do Mount but they do do camera:
image

**Comment by tridge** [comment]
needs CubeOrange and fmuv3

**Comment by peterbarker** [comment]
> needs CubeOrange and fmuv3

Done

**Review by IamPete1 — APPROVED** [review]

**Pull request merged**
