### PR TITLE
SITL: allow to pass extra parameter by cmdline

### PR DESCRIPTION
**Pull request by khancyr**

### CODE REVIEW

**Comment by khancyr** [comment]
correct stupid mistake and rebase

**Comment by peterbarker** [comment]
SITL supports passing in a comma-separated list of configuration files.

I think using that facility would actually neaten this patch vs using the extra_parameters keyword.  It keeps all parameters together in the `default_files` directory, which is a distinct advantage.

**Comment by khancyr** [comment]
Hello,
This use the multi config file support to work. Indeed, it just generate an exta config file with param pass with  "-P" . Don't you think this is a good idea ? Or should we just remove the -P support

About the modification for vehicule default file, the problem I see is that we got multiple file for the same type of vehicle, but generaly only the copter.parm is modified. So hexa, octo etc don't got the new default. Using the -P thing allow to always have the good default and the good vehicle type. And solve the extra_mavlink_cmds that was working

**Comment by OXINARF** [comment]
I don't really like this approach, writing a temporary file just to get the parameters from the command-line looks very hackish. I have a commit I need to rework (it has a bug somewhere I don't remember anymore) where I basically fixed the *-P* option with another approach (it basically parses parameter changes at a later time): https://github.com/OXINARF/ardupilot/commit/d499deb491e11833312d2a96edb09cebebd60456

**Comment by khancyr** [comment]
@OXINARF your approach is better ! I close this one !

**Comment by peterbarker** [comment]
On Mon, 24 Apr 2017, khancyr wrote:

> This use the multi config file support to work. Indeed, it just generate an exta config file with param pass with "-P" . Don't you think this is a good
> idea ? Or should we just remove the -P support
> 
> About the modification for vehicule default file, the problem I see is that we got multiple file for the same type of vehicle, but generaly only the
> copter.parm is modified. So hexa, octo etc don't got the new default. Using the -P thing allow to always have the good default and the good vehicle type.
> And solve the extra_mavlink_cmds that was working

https://github.com/ardupilot/ardupilot/blob/master/Tools/autotest/sim_vehicle.py#L740

sim_vehicle.py has support for passing in multiple parameter files to the 
ArduPilot binary to take advantage of the fact we can parse multiple files 
within ArduPilot.  Last-file-in wins in terms of parameter values.  So to 
get the effect we're after, a small file with just the differences 
required for Hexa could be created - then set "default_params_filename": 
["copter.parm","hexa.parm"] in the Hexa block and it is All Good.  AFAIK 
the multiple-file stuff works just fine - we just haven't created these 
tiny "hexa.param" files!

**Pull request closed without merging**
