### PR TITLE
Copter: If fast_loop method executed time is over MAIN_LOOP_MICROS, when time_available variable value is large MAIN_LOOP_MICROS.

### PR DESCRIPTION
**Pull request by muramura**
fast_loop excecuted time must under MAIN_LOOP_MICROS(2500us) time.
If fast_loop excecuted time over MAIN_LOOP_MICROS, time_available value is over MAIN_LOOP_MICROS by uint32_t.
If over MAIN_LOOP_MICROS time, when many tasks executed.
fast_loop method can not regularly run.

uint32_t time_available = (timer + MAIN_LOOP_MICROS) - micros();

Change 

If fast_loop excecuted time over MAIN_LOOP_MICROS, set time_available value is 0.
If time_available value is 0, when not task executed.

uint32_t now = micros();  // Current time
uint32_t limit_time = timer + MAIN_LOOP_MICROS;  // limit of time
uint32_t time_available = (limit_time <= now) ? 0u : limit_time - now;

### CODE REVIEW

**Comment by magicrub** [comment]
This PR contains unrelated changes

On Tue, Jul 26, 2016 at 9:44 AM, murata,katsutoshi <notifications@github.com

**Comment by OXINARF** [comment]
@muramura This is your second PR and you have already been advised that you need to rebase instead of merging - it was done for you in the first one but you need to start doing it yourself.

**Comment by rmackay9** [comment]
@muramura, one thing that might help you a bit is always do your development in a new branch in your repo (i.e. use "git checkout -b new-branch-name").  Then you can always keep your repo's master branch exactly the same as the ardupilot/master branch (i..e use "git remote add trunk https://github.com/ArduPilot/ardupilot.git" and "git checkout my-new-branch", "git fetch trunk", "git reset --hard trunk/master").
To get your branch rebased on master then you can do "git rebase origin/master" or "git rebase trunk/master".
I know git is a bit hard to get use to when you first start.  Thanks for contributing to ardupilot!

**Comment by magicrub** [comment]
git workflow:
switch to master branch
pull master (now you're up to date)
make new branch with whatever name you like (feature_xyz)
commit
commit
commit
...
switch to master
pull master (now you're up to date but your feature_xyz branch has diverged
from a previous master commit)
switch branch feature_xyz
rebase feature_xyz onto master.
push feature_xyz to github
submit PR


note, there are no merges and the history is clean

**Comment by OXINARF** [comment]
Superseded by #4620

**Pull request closed without merging**
