### PR TITLE
CAN: added CANSensor class for easy CAN sensors

### PR DESCRIPTION
**Pull request by tridge**
This adds a CANSensor class which makes writing drivers for simple CAN protocols very easy.
This also adds two such drivers:
 - an EFI CAN driver, based on a driver originally written by @WickedShell 
 - a CAN driver for the USD1 radar

### CODE REVIEW

**Comment by auturgy** [comment]
@magicrub this might be of interest re https://github.com/ArduPilot/ardupilot/pull/15780

**Comment by bugobliterator** [comment]
Really like the overall structure! Only thing is the naming part. I am thinking this could be used by Non-Sensor CAN devices as well. So, better name might be AP_CANBackend or something else that's generic.

**Review by bugobliterator — APPROVED** [review]
Other than the naming thing, looks good.

**Comment by magicrub** [comment]
I'll take a closer look at this tomorrow. Meanwhile let me ask: I plan to convert my MPPT and KDECAN drivers to be used on Ap_periph. How does this come into play on that? Easier I hope?

**Comment by tridge** [comment]
> How does this come into play on that? Easier I hope?

I think so, but I haven't tried

**Comment by tridge** [comment]
> Only thing is the naming part. I am thinking this could be used by Non-Sensor CAN devices as well. So, better name might be AP_CANBackend or something else that's generic.

I don't really like AP_CANBackend .... I'll leave it as CANSensor and then we can rename when we are inspired

**Pull request merged**
