### PR TITLE
HAL_ChibiOS: cleanup cube IMUs and compasses

### PR DESCRIPTION
**Pull request by tridge**
don't probe for old sensor set

### CODE REVIEW

**Comment by Pedals2Paddles** [comment]
I did the same with this but kept the sensors for the alpha units.
https://github.com/ArduPilot/ardupilot/pull/12953

**Comment by tridge** [comment]
> I did the same with this but kept the sensors for the alpha units.
> #12953

ahh, sorry, I hadn't noticed your PR
I'll leave it up to @bugobliterator which way he wants to go. I did this PR in response to someone asking why they get a probing lsm303d message. Your PR would fix that too as it would find the correct IMUs and top probing

**Comment by khancyr** [comment]
@bugobliterator do you want to continue this or we close it ?

**Comment by khancyr** [comment]
@tridge @bugobliterator Still interested in this cleanup ?

**Comment by tridge** [comment]
@bugobliterator please let me know if you'd like to move fwd with this, may be better for you to do a new PR

**Comment by peterbarker** [comment]
Ping @bugobliterator - this one's now conflicting and is waiting on your answer...

**Comment by peterbarker** [comment]
We merged the rebased-and-pushed-into-separate-branch PR.

**Pull request closed without merging**
