### PR TITLE
Add clone information to BUILD.md

### PR DESCRIPTION
**Pull request by bdemers**
Adds git clone step to BUILD.md, to ensure that the submodule step is not missed

### CODE REVIEW

**Comment by bdemers** [comment]
**NOTE:* There are a few locations that do point out the sub modules, but not all.  For example coming into the project from the "build on a Mac" path there is no mention of cloning the repo. 
(This isn't necessarily bad, but missing submodule step may be a common issue for folks that don't typically deal with them)

**Comment by auturgy** [comment]
Thanks Brian: useful feedback. 
Would it be better to find a way to define the entry point into the wiki a bit better for new devs, rather than increase duplication (for maintainability)?
Also, as you’ve likely observed build.md needs a bit of a general refresh :)

**Comment by bdemers** [comment]
@peterbarker done!

**Comment by Hwurzburg** [comment]
@peterbarker  why do we recommend repeatedly elsewhere to use git submodule update --init --recursive after a normal clone...instead of --recursive or --recurse-submodules during the clone?

**Comment by peterbarker** [comment]
On Sun, 9 Aug 2020, Henry Wurzburg wrote:

> @peterbarker why do we recommend repeatedly elsewhere to use git submodule update --init --recursive after a normal clone...instead of --recursive or
> --recurse-submodules during the clone?

The only reason I can think of is that the separate operation is useful 
after you've got a clone, when you're trying to bring everything 
up-to-date.  Perhaps a long-term sort of a hint.

**Comment by peterbarker** [comment]
Merged, thanks!

**Pull request merged**
