### PR TITLE
Tools: Mavlink Pascal Unit

### PR DESCRIPTION
**Pull request by hiro2233**
MAVLink Pascal Unit for APM communication.

There is an example in ./example path to test te unit, it's tested with Embarcadero RAD Studio Berlin in multidevice mode with windows and android.
I think the unit will work with LAZARUS with little modifications.

NOTICED

AS you see the code has no implemeted all helpers, but with this code you have all basic protocols to comunicate with APM.
 
I stopped development to here, because i discovered a new way to transport telemetry data side by side, and it's will be release when URUS System development finish.
You will be updated about this if you want following the development.
 
All URUS System and new URUS Protocol will be a member project and a part of Ardupilot Development.

### CODE REVIEW

**Comment by OXINARF** [comment]
This belongs in the MAVLink repository, not here. Also, you should have made a generator instead of manually adding the messages and enums. MAVLink adds and changes messages all the time, so the generator is the way to go, not something fixed.

**Comment by hiro2233** [comment]
@OXINARF you have the reason always. :-)
Thanks to clarify.

**Comment by OXINARF** [comment]
Not always :smiley: By the way, I hope you don't get the impression that this isn't wanted. I think that the more language bindings MAVLink has the better, but they belong in the MAVLink repository in the form of a generator, so that everybody can use it instead of it being constrained to ArduPilot.

**Comment by hiro2233** [comment]
@OXINARF Ok, thanks. No problem, i understand, i like the APM Team and i will do everything as possible that project can grow up, following the good practice.

**Pull request closed without merging**
