### PR TITLE
GCS_Common: refactor try_send_mission_message

### PR DESCRIPTION
**Pull request by chobitsfan**
`bool ret` only be assigned `true` here, maybe we can just remove it?

### CODE REVIEW

**Review by peterbarker — APPROVED** [review]
LGTM.

This function can only return false if we're out-of-space-to-send, and that's amply handled by `CHECK_PAYLOAD_SIZE`.

**Comment by chobitsfan** [comment]
Hi @peterbarker thank you for reviewing and information.  I have updated comments. I think `bool ret` may be unnecessary because it is only assigned `true`

**Comment by rmackay9** [comment]
@chobitsfan,

Thanks for this, can you rebase on master?

**Review by magicrub — APPROVED** [review]
needs a rebase but otherwise LGTM

**Comment by peterbarker** [comment]
Merged, thanks!

**Pull request merged**
