### PR TITLE
Remove ahrs.get_gps()

### PR DESCRIPTION
**Pull request by peterbarker**
We now have a GPS singleton, so places where libraries were using the AHRS object to get a-hold of the GPS singleton can now do so directly.

AHRS no longer requires the GPS singleton be passed in in the constructor.

### CODE REVIEW

**Comment by magicrub** [comment]
Shouldn't we really be moving more things into the AHRS where we ask the EKF what our lat/lng is (for example) instead of the GSP driver? Same goes with the IMU, should we be asking it what our x-axis acel currently is? no, that's silly. We want the EKF result. I don't see why GPS is any different.

**Comment by peterbarker** [comment]
On Sun, 3 Dec 2017, Tom Pittenger wrote:

> Shouldn't we really be moving more things into the AHRS where we ask the EKF what our lat/lng is (for example) instead of the
> GSP driver? Same goes with the IMU, should we be asking it what our x-axis acel currently is? no, that's silly. We want the
> EKF result. I don't see why GPS is any different.

I think that's correct, but a subject for a different PR.  Those changes 
are likely to have subtle side-effects.

I find the code checking we have at least a 3D lock particularly irksome. 
3D lock with a 100 HDOP... great.

**Comment by magicrub** [comment]
> with a 100 HDOP

Any I know someone who will be irked by that statement :)

**Comment by peterbarker** [comment]
@OXINARF Rebased.

**Comment by OXINARF** [comment]
Merged, thanks!

**Pull request merged**
