### PR TITLE
Fix sample rates for ICM45686

### PR DESCRIPTION
**Pull request by bugobliterator**
* based on https://github.com/ArduPilot/ardupilot/pull/22144

### CODE REVIEW

**Comment by andyp1per** [comment]
@bugobliterator on my CubeOrangePlus this now shows up as a ICM42688 which seems wrong. As far as I can tell the sampling rate support is all good - just the naming that is a bit off

**Comment by bugobliterator** [comment]
@andyp1per I have swapped INS_ICM20649 and ICM45686 order, that is why you are not seeing it anymore. To test you either need to disable ICM20649 or swap order in hwdef.dat for CubeOrangePlus

**Comment by andyp1per** [comment]
Ok disabled 20649 and got this:
```
20/02/2023 09:22:04 : IMU2: fast sampling enabled 12.8kHz
20/02/2023 09:22:04 : IMU1: fast sampling enabled 4.0kHz
20/02/2023 09:22:04 : IMU0: fast sampling enabled 4.0kHz
```
So something not quite right 😆

**Comment by andyp1per** [comment]
@bugobliterator I put back https://github.com/ArduPilot/ardupilot/pull/22144/commits/4504cfab2dbb548a0b79273d3eaedb6936ff8e33 and its working for me - what was the issue you were seeing?

**Review by andyp1per — CHANGES_REQUESTED** [review]
Needs low sample rate fixing, currently using the wrong backend rate

**Pull request closed without merging**
