### PR TITLE
AP_Scripting: bump SCRIPTING_HEAP_SIZE for large RAM (>=1MB) devices

### PR DESCRIPTION
**Pull request by magicrub**
I've found that 100k just isn't enough to run multiple scripts on SITL. If there's plenty of RAM available, lets go ahead and allocate it by default.

Bump up the default SCRIPTING_HEAP_SIZE from 100k to 300k on systems with >= 1MB RAM. The existing HAL_MEM_CLASS_500 systems are unchanged and remain at 100k

### CODE REVIEW

**Comment by IamPete1** [comment]
It could mean that scripting stops working for some users if they had enough free memory for the original defeat value but not enough for this new default. 

Happy to change in SITL, but its probably reasonable that you have to turn it up in SITL if you need to run multiple scripts.

**Comment by magicrub** [comment]
The bar only gets raised on systems with more memory.

**Comment by magicrub** [comment]
Systems with 1MB RAM have lots of idle RAM.. We're pushing more and more features to scripts and that means running multiple scripts are becoming not only normal, but required and/or expected - as designed. The default heap will need to be raised at some point. What if I changed it to 200k?

**Comment by magicrub** [comment]
@IamPete1 I changed it to 200k

**Comment by magicrub** [comment]
Perhaps this is better to go in after 4.4 beta so there's plenty of variety of people using it on master for a 4.5 release?

**Review by tridge — APPROVED** [review]

**Pull request merged**
