### PR TITLE
add install-prereqs-mac.sh

### PR DESCRIPTION
**Pull request by Huibean**
add a script to install dependencies for mac to compile ardupilot code

### CODE REVIEW

**Comment by bugobliterator** [comment]
@Huibean I am creating a travis build for mac, will include your patch into that and check.

**Comment by Huibean** [comment]
@bugobliterator ok

**Comment by davidbuzz** [comment]
LGTM.

**Comment by lucasdemarchi** [comment]
I haven't really looked into this, just applied as others already reviewed.

**Pull request merged**
