### PR TITLE
SITL: add correct battery estimator from vehicle type #10050

### PR DESCRIPTION
**Pull request by ongspxm**
#10050 

```
Currently, for SITL, the battery consumption of the different models is
defined inside the `AP_HAL`. This overloads the `SITL_State` object as
a "god" class with all the battery consumption model.

Let's shift the calculation for the servo output voltage and current to
the individual SITL models instead. Meanwhile, the battery object is
created in the SITL to allow for extension in the future when these
consumption model rely on different information, e.g. battery types.
```

### CODE REVIEW

**Comment by ongspxm** [comment]
@khancyr it seems like `SITL_State` only creates an `Aircraft` object as `sitl_model`.

Should we keep the implementation of the different motor outputs in sitl state?

If we want to let each subclass of `Aircraft` implements its own servo output function, then we might need to move the `SITL_State::_simulator_servos` somewhere else, or have some way to pass the subclass model in.

How do we proceed?

**Comment by khancyr** [comment]
Hello,
you can put the battery update inside vehicle->update() like update_external_payload() does

**Comment by ongspxm** [comment]
oh, so we just add a servo voltage and current output into SITL, update it
from the vehicle, then use it in SITL_State?

I think i got it, let me implement it, i will pdate you again.

**Comment by ongspxm** [comment]
```
AUTOTEST: Failing tests:
  BatteryFailsafe (Fly Battery Failsafe) (Did not change mode) (see /home/travis/build/ArduPilot/buildlogs/ArduCopter-BatteryFailsafe.txt)
Had to force-reset SITL 1 times
```
I implemented it as you advised, but there is this battery failsafe auto test that I am failing. Can you point to where I can start searching for the error?

**Comment by ongspxm** [comment]
@khancyr I traced one of it to [a failure to change mode](https://github.com/ArduPilot/ardupilot/blob/master/Tools/autotest/arducopter.py#L523).

It seems like the copter should change into `LAND` mode but is not doing so. Can you point me to the part where is the relevant?

I am looking through `AP_Motors/AP_MotorsMulticopter`, the part where they set the low and high bound for the voltage, but doesnt seem like my changes would affect.

Can help point me to a right direction?

**Comment by ongspxm** [comment]
@khancyr I have redid the implementation, but it doesn't seem like the test is running, the travis-ci logs seems to keep having this "no link" messages. Any guidance on how to proceed?

**Comment by ongspxm** [comment]
@khancyr ready for review. The appveyor fails due to some easy_install issue, i will merge master when its fixed

**Comment by ongspxm** [comment]
@khancyr ready for review, merged with master to resolve the appveyor problem

**Comment by ongspxm** [comment]
merged master, ready for review

**Comment by peterbarker** [comment]
I think tridge's SITL PR https://github.com/ArduPilot/ardupilot/pull/15613 has overtaken this one.  Bits of that look like this.

Always makes me a bit sad when I see work like this go to waste - sorry!

**Comment by khancyr** [comment]
Yep Tridge work override this, so better start with what he did to extend it to all vehicles.

This was on my todo list but I never found the time to finish it...

**Pull request closed without merging**
