### PR TITLE
Learning branching and patching

### PR DESCRIPTION
**Pull request by d-v**
Added another location to locations.txt. (This is my first ever pull request!)

### CODE REVIEW

**Comment by d-v** [comment]
Sorry about the mess of commits -- still learning to use Git properly!

**Comment by jaxxzer** [comment]
Good job! Try this tutorial about squashing commits. The result of this PR is good, but the path to get there.. in the commit history.. can be cleaned up. 

https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

**Comment by khancyr** [comment]
or http://ardupilot.org/dev/docs/git-interactive-rebase.html ^^

**Comment by d-v** [comment]
@jaxxzer thanks for the input! I'll create a new PR in a little
@khancyr thanks!

**Comment by jaxxzer** [comment]
noooo! you can use the same pr! just (force) push to the same branch on github, and the pr will be updated here

**Comment by jaxxzer** [comment]
Too late now, it looks like you have deleted your repository.

**Pull request closed without merging**
