### PR TITLE
Closing #15851

### PR DESCRIPTION
**Pull request by maksimdrachov**
Need help with squashing the commits into 1

### CODE REVIEW

**Comment by maksimdrachov** [comment]
I'm trying to squash all the commits into 1 by doing the following steps:
1) git clone git@github.com:maksimdrachov/ardupilot.git (to get a clean start)
2) git branch
-> here I expect to see 2 branches "master" and "develop", but I only see 1, why is that?

**Comment by amilcarlucas** [comment]
You need to do:
> git fetch develop
> git checkout develop
> git rebase -i master

then select that you want to squash the commits.
After that:

> git push -f

**Comment by maksimdrachov** [comment]
Ok, if i try `git fetch develop`, i get the following:
Screenshot 2020-11-26 at 13 44 31

Meanwhile I can see the branch is there:
Screenshot 2020-11-26 at 13 45 04

Btw my .git/config:
Screenshot 2020-11-26 at 13 47 22

**Comment by maksimdrachov** [comment]
Hi,
Is this finished or is there anything else i need to do?

**Comment by amilcarlucas** [comment]
I updated the commands now. Please push the commit in. We have no commits on this branch now

**Comment by maksimdrachov** [comment]
I haven't been able to resolve this issue completely so I started over fresh with a new branch and pull request :/
https://github.com/ArduPilot/ardupilot/pull/15907

New at this, so sorry :)

**Pull request closed without merging**
