### PR TITLE
Ported the precision landing/IR-LOCK system into Quadplane V3

### PR DESCRIPTION
**Pull request by Rouniy**
Ported the precision landing/IR-LOCK system into Quadplane.
This commit based on the 
https://github.com/ArduPilot/ardupilot/pull/11339
With the conflict solving.

### CODE REVIEW

**Review by Rouniy — COMMENTED** [review]
Seems fine

**Comment by markcfong561** [comment]
Any updates on this?

**Comment by Rouniy** [comment]
> Any updates on this?

No time to work with this feature. TerroRussia killing my friends. Need to help them.

**Comment by rmackay9** [comment]
@Rouniy I'm sorry, I mistakenly deleted a comment on this PR.

**Comment by tridge** [comment]
i've decided to implement this in scripting for flexibility: https://github.com/ArduPilot/ardupilot/pull/26380

**Pull request closed without merging**
