### PR TITLE
restore fly.ArduCopter as running all tests

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by andyp1per** [comment]
Ahh I thought about naming this way, but it didn't see very sexy - I guess it's more obvious 👍 
Thanks @peterbarker for cleaning this up.
There is much more time on the unit test run but it is clang. I do wonder though whether having one suite run on clang is actually a good idea?

**Comment by khancyr** [comment]
I would prefer to keep the test suite on the same toolchain to really validate correctly the code.

**Comment by peterbarker** [comment]
On Sat, 22 Feb 2020, Andy Piper wrote:

> There is much more time on the unit test run but it is clang. I do wonder though whether having one suite run on clang is actually a good idea?

Well... we do run tracker under clang, it seems :-)

**Comment by andyp1per** [comment]
@khancyr I kind of agree, but I have also found that clang catches some issues that gcc does not (i.e. actual bugs), so you could argue that mixing the toolchain is validating the code more.

**Comment by khancyr** [comment]
hum, are we speaking of compilation test or autotest ? for autotest it is better to continue with GCC as we are shipping binary build with GCC so at least we ensure that on GCC we got some coverage.
Ideally we should do the same for both compiler to maximize the coverage ... but we don't have enough CI time...

**Comment by andyp1per** [comment]
But are we really - sitl GCC is not the same as Arm GCC, and still is what we are testing here.

**Pull request merged**
