### PR TITLE
Global: Change strcmp to strncmp

### PR DESCRIPTION
**Pull request by muramura**
For a fixed string, I specify the length of the string, including the null character.
I thought this would be a fail safe.
For example, when NULL becomes a non-NULL code due to memory error.

### CODE REVIEW

**Comment by muramura** [comment]
@WickedShell san..
I know that memory is not perfect.
I want to avoid a lot of processing time.
I designed a lifeline embedded hardware that works for a long time and added a parity memory to detect memory anomalies.
This hard design was effective.

**Comment by peterbarker** [comment]
> I know that memory is not perfect.

If you think we need protection against flash corruption, that's good - but there are better fixes for that.  If you think we need to protect against the trailing nulls in the stack variable being corrupted - well, the parameter for string length you're passing through could be corrupted in just the same way :-)  (in fact, depending on just how that number gets corrupted you may be *more* likely to hit a hard fault!)

> I want to avoid a lot of processing time.

I'm not sure how this makes things shorter; if anything it may be longer as not only will the null-termination checks be done but also a comparison against the length parameter being passed through.

> I think that this kind of processing is unnecessary if memory anomalies are detected on such hardware.
> However, if there is no such function, I think that it is better to do it with software.

Some mechanisms to determine corruption - checksumming the flash, for example - are probably worthwhile.  Software solutions to check our own core memory for validity - the number of vehicles lost due to problems in implementation would probably outweigh those saved by those checks.  None of the embedded flight controllers we run on have ECC - that would be a *far* superior (obviously HW) solution for those that cared about this.

**Comment by WickedShell** [comment]
Closing, as peter mentioned this isn't the correct way to try and fix the flash use case, and isn't helping us in the general case.

**Comment by muramura** [comment]
@peterbarker san, @WickedShell san.  Comments thanks.

I think the idea to make sure that the flash memory was written successfully is good. I remembered that the verification check was done by writing to rom. Thank you.

**Pull request closed without merging**
