### PR TITLE
AP_Baro: tidy probing of external i2c baros

### PR DESCRIPTION
**Pull request by peterbarker**
This is a single commit built on top of https://github.com/ArduPilot/ardupilot/pull/19897/files - it will be rebased after that's merged.

Seems to save ~1300 bytes on Plane on MatekF405-Wing

```
 after neaten: bin/arduplane    961312      2020   129136                963332           19700
before neaten: bin/arduplane    962648      2020   129136                964668           18364
```

### CODE REVIEW

**Comment by tridge** [comment]
tested successfully on striver mini with cube orange and cuavv5mini with MSP and CAN baro

**Comment by peterbarker** [comment]
This still needs some explaining:
image

**Comment by peterbarker** [comment]
I did a small test to see if these savings are plausible.  I believe they are.

With this patch:
```
--- a/libraries/AP_Baro/AP_Baro.cpp
+++ b/libraries/AP_Baro/AP_Baro.cpp
@@ -765,8 +765,6 @@ void AP_Baro::_probe_i2c_barometers(void)
         FOREACH_I2C_MASK(i,mask) {
             ADD_BACKEND(AP_Baro_BMP280::probe(*this,
                                               std::move(GET_I2C_DEVICE(i, HAL_BARO_BMP280_I2C_ADDR))));
-            ADD_BACKEND(AP_Baro_BMP280::probe(*this,
-                                              std::move(GET_I2C_DEVICE(i, HAL_BARO_BMP280_I2C_ADDR2))));
         }
     }
 #endif
```

The binary is 116 bytes smaller.  We're eliminating a *lot* of these calls to `ADD_BACKEND`.

**Review by tridge — APPROVED** [review]

**Review by hendjoshsr71 — APPROVED** [review]
Tested and works with both a  CubeOrange conencted to the external baro or to a matek-L431-periph node using an external BMP388

image

**Pull request merged**
