### PR TITLE
Move handling of parachute mission commands into AP_Mission_Commands

### PR DESCRIPTION
**Pull request by peterbarker**
Note that Copter logs will not get Event entries.

### CODE REVIEW

**Comment by rmackay9** [comment]
Thanks for this, makes a lot of sense.

For support purposes though it's important that we know when the parachute has been deployed.  I suspect this means that we need to move events into the dataflash log library?

**Comment by peterbarker** [comment]
On Thu, 31 Jan 2019, Randy Mackay wrote:

> For support purposes though it's important that we know when the parachute has been deployed. I suspect this means that we need to move events into the
> dataflash log library?

tridge has already OK'd that IIRC.

**Comment by peterbarker** [comment]
@rmackay9 I've created a PR to move event logging up.

**Comment by peterbarker** [comment]
Marked devcalltopic for attention

**Comment by peterbarker** [comment]
redo - link in parachute instead

**Comment by peterbarker** [comment]
After discussion on the call I moved the text-message-sending into the library itself, and didn't log the parachute event if it's not enabled.

**Comment by rmackay9** [comment]
Merged, thanks!

**Pull request merged**
