### PR TITLE
AP_Compass: not only PIXHAWK2 probe QMC5883L on internal

### PR DESCRIPTION
**Pull request by JIMWAR**
there is not only PIXHAWK2 probe QMC5883L on internal,but also other px4 board(e.g., radiolink PIXHAWK)

### CODE REVIEW

**Comment by tridge** [comment]
the reason we probe on internal for pixhawk2 is it exposes an 'internal' i2c on an external connector.
I don't think any other boards do this? If the radiolink pixhawk does then please send me a tlog from connecting after applying this patch

**Comment by tridge** [comment]
I just noticed your account name is radiolink. Can you tell me what the radiolink pixhawk does? Perhaps you've replaced the HMC5883L with a QMC5883L ?

**Comment by JIMWAR** [comment]
We don't have an external interface to connect internal I2C, we just replace LSM303D with QMC5883L internally.the tlog files are linked below.
[http://www.radiolink.com.cn/firmware/wiki/2020-01-02%2009-39-09.tlog](url)

**Comment by JIMWAR** [comment]
The correct link is below.
[http://www.radiolink.com.cn/firmware/wiki/2020-01-02 09-39-09.tlog.tlog](url)

**Comment by JIMWAR** [comment]
The correct link is below.
[http://www.radiolink.com.cn/firmware/wiki/PIXHAWK.tlog](url)

**Comment by tridge** [comment]
> We don't have an external interface to connect internal I2C, we just replace LSM303D with QMC5883L internally.the tlog files are linked below.
> [http://www.radiolink.com.cn/firmware/wiki/2020-01-02%2009-39-09.tlog](url)

that means you must have replaced the 2nd IMU too, as the accel is on the LSM303D.
Perhaps we should just make this a new hwdef.dat and a new board type? It would also be better if we didn't call it "Pixhawk", as that has a particular meaning, plus it is a trademark held by Lorenz Meier.
maybe you can submit a PR for this board under a new name?

**Comment by JIMWAR** [comment]
Our Pixhawk is the same as the previous board, only QMC5883L  is used to replace LSM303D and deleted the 2nd IMU.

**Comment by JIMWAR** [comment]
But now the firmware can be used normally, just need to probe QMC5883 on internal.

**Comment by JIMWAR** [comment]
Butnow  we don't have time to make a new hwdef.dat and a new board type,although it would also be better to make a a new hwdef.dat.Maybe later.

**Comment by tridge** [comment]
> Our Pixhawk is the same as the previous board, only QMC5883L is used to replace LSM303D and deleted the 2nd IMU.

it really isn't a pixhawk then. In ArduPilot a "Pixhawk" is defined by the sensors, peripherals and pinout.

**Comment by tridge** [comment]
you should be able to make a derived hwdef.dat, using include lines

**Comment by khancyr** [comment]
it is pretty staled.
The solution we ask it to add a new hwdef to take this into account. Please bring a new PR with the change if you are still interested in bringing this. thanks

**Pull request closed without merging**
