### PR TITLE
Improve bug_report issue template

### PR DESCRIPTION
**Pull request by wucke13**
Now the boxes for **Platform** look way better IMO.

### CODE REVIEW

**Comment by rmackay9** [comment]
So to make it easier to see the difference here is the before after.  I think it's an improvement.  I suspect the original intention was to make the boxes check boxes.

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Platform**
+ [ ] All
+ [ ] AntennaTracker
+ [ ] Copter
+ [ ] Plane
+ [ ] Rover
+ [ ] Submarine

**Review by rmackay9 — APPROVED** [review]

**Comment by peterbarker** [comment]
@wucke13 could you change the wording on the commit, please?  Should be `.github: improve bu_report issue template`

If you don't know how to do that, let me know and I'll do it for you.

Incidentally - you ought to be using git `topic` branches rather than your master branch for making pull requests.... google for more info :-)

**Comment by WickedShell** [comment]
The reason they were not checkboxes originally was because that changed the
GitHub interface to show the progress on the issue tab, which was
misleading and more annoying.

**Comment by wucke13** [comment]
@WickedShell so is it desired at all?

**Comment by tridge** [comment]
this is how github treats it:
image
see how it is "6 of 13", so it assumes that all the boxes need ticking for completion
so this doesn't work unfortunately

**Comment by wucke13** [comment]
Just as a reference point, we do the thing with boxes over at [nixos/nixpkgs](https://github.com/nixos/nixpkgs). Our workflow does almost never involve ticking of all boxes. So just because github offers us to use this for a metric does not mean we can not use it. Of course I respect whatever this projects decision ends up being, this was just a suggestion :)

**Pull request closed without merging**
