### PR TITLE
travis: Move from Ubuntu 14.04 to 16.04

### PR DESCRIPTION
**Pull request by patrickelectric**
14.04 end of life is near
https://wiki.ubuntu.com/Releases

Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

### CODE REVIEW

**Comment by patrickelectric** [comment]
@magicrub 	AFAIK travis does not provide it.

**Comment by peterbarker** [comment]
OTOH, we wouldn't know we've got issues on trusty64 if we weren't running it on travis.

**Comment by peterbarker** [comment]
Merged, thanks!

**Comment by peterbarker** [comment]
@jaxxzer To try to unconfuse you...

The problem we found was that trusty's development environment was reliably failing a test where everything else was passing.

The thing is that on the face of it trusty was correct.

I've yet to find the carve-out for `pow(...)` which says that anything which looks like integer arithmetic can be considered floating point arithmetic - but that's what seems to happen!  (it's probably a macro/template change or similar which is doing it somewhere in the deep dark depths of the compiler suite, I reckon).

By moving away from trusty64 we will no longer catch these bugs - and it *IS* a bug since different compilers will give you different results (unless, as I say, there's a carve-out somewhere for `pow(...)`).

**Comment by patrickelectric** [comment]
@peterbarker should we add https://gcc.gnu.org/wiki/NewWconversion in ArduPilot flags ?

**Comment by peterbarker** [comment]
On Wed, 3 Apr 2019, Patrick José Pereira wrote:

> @peterbarker should we add https://gcc.gnu.org/wiki/NewWconversion in
> ArduPilot flags ?

Let's find out :-)

https://github.com/ArduPilot/ardupilot/pull/10983

Peter

**Pull request merged**
