### PR TITLE
autotest: Move soaring into plane suite

### PR DESCRIPTION
**Pull request by samuelctabor**
As recommended by @peterbarker 

Based on #14011

### CODE REVIEW

**Comment by peterbarker** [comment]
@samuelctabor so it's not passing the soaring test.  Seems to be making all the right noises, but is hitting the ground.

Is it possible the simulated thermals aren't actually active, despite the indications I'm seeing?

**Comment by samuelctabor** [comment]
@peterbarker there was a key error in `start_sitl` preventing default parameters being overridden with `customise_SITL_commandline` - it may affect `test_skid_steer` too

**Comment by peterbarker** [comment]
@samuelctabor I've rebased this on top of master (again).  Let's see how *this* goes...

**Comment by samuelctabor** [comment]
@peterbarker I'm not sure why this failed the accelerometer calibration arming check on CI - it passes locally for me in a clean repo.

**Comment by peterbarker** [comment]
OK, there's some weird stuff going on in here.

I can reliably reproduce the accel failure, but there seems to be a bug in the suite as I can only do that if I also do a `build.Plane` first.

... after that there's some even weirder stuff:

image

Check the text on the RHS of that image.

I'm going to focus on the accel problem.

**Comment by samuelctabor** [comment]
Interesting - I had the same plot at one stage, when the wrong parameters were applied (before I fixed the defaults_filepath issue)

**Comment by peterbarker** [comment]
OK, fixed the problem.  Corrected path to defaults file and SITL now panics if you provide a bad one.

**Comment by peterbarker** [comment]
Well, this one finally went in - thanks!.  That graph still disturbs me, 'though.

**Comment by samuelctabor** [comment]
Thanks for all your help Peter.

Using the BIN log from autotest.ardupilot.org, the graph now looks better:

Figure_2

I'm not sure if the wrapping of NKF5.HAGL is expected?

Also it seems like the map generated from the tLog and shown on the autotest server is incorrect or stale - the .BIN file gives the expected map.

From .tLog, image from autotest.ardupilot.org:

Map-fromTLog

From .BIN downloaded from autotest.ardupilot.org:

Map-fromBIN

**Comment by peterbarker** [comment]
Might want to check that map periodically - possible hadn't finished the run when you looked.

The HAGL wrap is a logging artifact; we take a perfectly good float, multiply it by 100 and shove it into a 16-bit-signed-integer, yielding that maximum upper value of 32767cm (32.8-ish metres).

We do save 2 bytes per message that way....

**Comment by samuelctabor** [comment]
Ok it does show the soaring test as part of the main Arduplane flight. I guess now that soaring is part of the main plane suite it shouldn't be showing it as a separate plot, so that is maybe a hangover from before this change.

**Pull request merged**
