### PR TITLE
Swarmly/prec landing

### PR DESCRIPTION
**Pull request by aralce**
Ported the precision landing/IR-LOCK system into Quadplane.
This commit is a rebase of the Pull-request 19377 to current Plane-4.1 commits.

From pull-request 19377:
"[Rouniy](https://github.com/Rouniy) commented [on Nov 27, 2021](https://github.com/ArduPilot/ardupilot/pull/19377#issue-1065115716)

Ported the precision landing/IR-LOCK system into Quadplane.
This commit based on the
https://github.com/ArduPilot/ardupilot/pull/11339
With the conflict solving."

### CODE REVIEW

**Comment by Autonomost** [comment]
@aralce have you done any hardware testing on this? want some? This is going to be awesome!

**Comment by aralce** [comment]
> u done any hardware testing on this? want some? This is going to be awesome!

Hi @Autonomost.  @Rouniy was in charge of the development of this feature, he could tell you more details.

**Comment by Rouniy** [comment]
This one comment not fully tested. Previous one - yes tested and it works.
Waiting for the some investigation and proper solving issues with the pull request.

**Comment by tridge** [comment]
i've decided to implement this in scripting for flexibility: https://github.com/ArduPilot/ardupilot/pull/26380

**Pull request closed without merging**
