### PR TITLE
CBU-H7-Stamp Information Update and Baro Change

### PR DESCRIPTION
**Pull request by CBUnmanned**
Removal of outdated information and update the hardware to BMP280 from the DPS310

### CODE REVIEW

**Comment by andyp1per** [comment]
@CBUnmanned do you plan to do a new README?

**Comment by CBUnmanned** [comment]
@andyp1per Yes, should I close & redo the PR with the new one or put in another PR for the readme changes?

**Comment by andyp1per** [comment]
Just put the full set of changes in this PR. I'm just anticipating what @Hwurzburg might say.
You will need to squash the changes with the appropriate log message

**Comment by Hwurzburg** [comment]
should be a single commit  hwdef: Update CBU-H7-Stamp

**Comment by CBUnmanned** [comment]
Sorry, Think that is now all squashed into a single commit

**Review by Hwurzburg — APPROVED** [review]

**Review by andyp1per — APPROVED** [review]

**Comment by peterbarker** [comment]
@CBUnmanned did you ever ship products with the old baro?  This PR will break ArduPilot on any boards manufactured with the old one.

**Comment by peterbarker** [comment]
Merged, thanks!

**Pull request merged**
