### PR TITLE
AP_HAL_ChibiOS: Remove fmuv2(unused)

### PR DESCRIPTION
**Pull request by Hwurzburg**
Not sure if this is allowed, but the MatekH743 board folder and firmware build name is incorrect..Matek will introduce many more H7 boards in the future....I think we need to match the board name to the firmware correctly...

also, the fmuv2 is not used in any board definition, so why is it being built?

there may be impacts I am not aware of, but, presently these just add to the board name to firmware matching confusion that now exists...

### CODE REVIEW

**Comment by kd0aij** [comment]
I guess fmuv2 may be redundant to Pixhawk1-1M, but that's not completely obvious, since they're one is based on fmuv3 and the other is based on Pixhawk1.

**Comment by MATEKSYS** [comment]
We use MATEKH743 instead of MATEKH743-WING in purpose.   We will release more H743 boards in future, they will use the same MCU pin definitions as they on H743-WING.  No necessity to add individual name for each board.

**Comment by Hwurzburg** [comment]
Sampson, thanks! removed that part of this PR....just wanted to make sure we do not create any  confusion  regarding board name vs firmware build names..

**Comment by peterbarker** [comment]
For once CI has actually caught a bug rather than spewing spurious errors.

So fmuv2 isn't the same as Pixhawk1-1M.

I'm not sure the distinction is important.

```
fmuv2
  bin/arduplane  960184  1204  195616  1157004

Pixhawk1-1M
  bin/arduplane  954080  1204  195616  1150900
```

**Comment by tridge** [comment]
fmuv2 is for 1M boards with non-Pixhawk1 sensors

**Pull request closed without merging**
