### PR TITLE
MatekF405-Wing: Add HAL_MINIMIZE_FEATURES to hwdef.dat

### PR DESCRIPTION
**Pull request by Davidsastresas**
This board is low on flash, should have this enabled. It is blocking the PR #13263

### CODE REVIEW

**Comment by davidbuzz** [comment]
LGTM, looks good, fixes 405 build etc.

**Comment by davidbuzz** [comment]
@andyp1per  - sorry i duin't see your earlier PR, I only stumbled on this one as it was linked to 13263, I really don't think it matters which is merged at this point, but well done on being the first. :-)

**Comment by Davidsastresas** [comment]
@andyp1per I wasn't aware of your PR, I just came across this because of my PR #13263. I rebased it to master as it seems some recent commit was affecting that file.

**Comment by tridge** [comment]
I've pushed in a change which reduces flash usage on this board. I much prefer to disable little used features for boards like this instead of removing lots of features at once

**Comment by tridge** [comment]
if anyone is finding the MatekF405-Wing isn't building for you then please check you are using the right compiler. The old 4.9 compiler produces larger binaries. We now use the 6.3 compiler:
https://firmware.ardupilot.org/Tools/STM32-tools/

**Comment by Davidsastresas** [comment]
@tridge I am using gcc 7.4.0 and still it doesn't compile #13263. Please take a look there and let me know how to proceed with it. Build for matekf405-wing is the only thing hoding back that PR apparently.

**Pull request closed without merging**
