### PR TITLE
AP_Vehicle: add singleton

### PR DESCRIPTION
**Pull request by peterbarker**
Marked this as WIP as there is no current user of it in the ArduPilot codebase, but @yaapu wants access to it.

### CODE REVIEW

**Comment by yaapu** [comment]
@peterbarker I already feel the burden on my shoulders. Thanks Peter.
I can move the osd navigation structure to ap_vehicle now and expose it to all libraries :)
@wickedshell this was something you asked too, correct?

**Comment by yaapu** [comment]
OK, I did a couple tests and I think a good compromise would be:
- create pure virtual functions in Ap_Vehicle.h
```
   virtual float get_wp_distance() = 0;
   virtual int32_t get_wp_bearing() = 0;
   virtual uint16_t get_wp_number() = 0;
   virtual float get_xtrack_error() = 0;
```
- add same functions as public overrides in each vehicle class
```
    // AP_Vehicle public overrides
    float get_wp_distance() override;
    int32_t get_wp_bearing() override;
    uint16_t get_wp_number() override;
    float get_xtrack_error() override;
```
have each vehicle maintainer implement them since each vehicle has a different "approach" .
for plane something like (I included the current plane OSD code as a reference)

```
#if OSD_ENABLED == ENABLED
void Plane::publish_osd_info()
{
    AP_OSD::NavInfo nav_info;
    nav_info.wp_distance = auto_state.wp_distance;
    nav_info.wp_bearing = nav_controller->target_bearing_cd();
    nav_info.wp_xtrack_error = nav_controller->crosstrack_error();
    nav_info.wp_number = mission.get_current_nav_index();
    osd.set_nav_info(nav_info);
}
#endif

float Plane::get_wp_distance() {
    return auto_state.wp_distance;
}

int32_t Plane::get_wp_bearing() {
    return nav_controller->target_bearing_cd();
}

uint16_t Plane::get_wp_number() {
    return mission.get_current_nav_index();
}

float Plane::get_xtrack_error() {
    return nav_controller->crosstrack_error();
}
```

From library code one would call AP::vehicle()->get_wp_distance()

This would also get rid of the OSD thread, what do you think @peterbarker ?

**Comment by peterbarker** [comment]
@yaapu Seems reasonable on the face of it.  A couple of questions/musings:
 - can we get the mission number from AP_Mission by default (i.e. make it not pure virtual, perhaps not even virtual, depending...
 - I'm not sure about "waypoint distance" - for example, for Plane that might the centre of a circle you're going around sometimes, I think.  I wonder if it could/should be "distance to target" or something
 - all of these methods should be const
 - there's no way to indicate "no current waypoint" with these calls
 - it's not clear what "distance_to_waypoint" should return if you're in e.g. Plane manual mode.  Plane does have persistent target, but that doesn't mean it will go there if you flip into auto mode - it might currently be a guided-mode waypoint.  This might be nit-picking a bit.

Perhaps the current model of taking semaphores and publishing information up *may* be better - but don't abandon your current approach based on that musing :-)

I guess we could also look at what information we send via GCS MAVLink which could fetch from this pool, too.

@tridge ?

@WickedShell  ?

**Comment by yaapu** [comment]
@peterbarker 
> - can we get the mission number from AP_Mission by default (i.e. make it not pure virtual, perhaps not even virtual, depending...

sure, you know the code base much better than me

> - I'm not sure about "waypoint distance" - for example, for Plane that might the centre of a circle you're going around sometimes, I think. I wonder if it could/should be "distance to target" or something

we have the same abiguity in the current OSD code

> - all of these methods should be const

ok

> - there's no way to indicate "no current waypoint" with these calls

neither in the current OSD code

> - it's not clear what "distance_to_waypoint" should return if you're in e.g. Plane manual mode. Plane does have persistent target, but that doesn't mean it will go there if you flip into auto mode - it might currently be a guided-mode waypoint. This might be nit-picking a bit.

same as above, current solution has the same issue

> Perhaps the current model of taking semaphores and publishing information up may be better - but don't abandon your current approach based on that musing :-)

Well, the real difference is that since the information right now is only used by the OSD code nobody really ever questioned wheter it was correct/proper, if we move it outside the OSD scope than current info quality will not suffice unless we find a way to mark that info as "telemetry" and delegate the consumer to get context info

> I guess we could also look at what information we send via GCS MAVLink which could fetch from this pool, too.

this would really be nice, I think somebody already did mention a potential AP_Telemetry class for this very purpose

**Comment by davidbuzz** [comment]
fyi, I reviewed the new AP_Vehicle stuff yesterday, and was like 'why doesn't it have a singleton'... so i went and wrote one, and opened a pr, and then discovered @peterbarker was 12 or more hrs ahead of me.    fyi, I wanted the singleton it AP_Vehicle so that LUA scripting would get a simplified interface to a 'vehicle' ...    in short, i think this PR should be accepted and then expanded on as per the above discussions in a new pr.

**Comment by davidbuzz** [comment]
Also an alternative suggestion to make AP_Vehicle less in-your-face with regard to requiring all derived vehicles to explicitly implement all 'pure virtual' interfaces in this class...  instead do this..

`    // vehicles should 'override' over any of these that they use, as these as they are essentially unimplemented in AP_Vehicle`
`    // these are 'virtual' but not 'pure virtual' =0, as we don't want AP_Vehicle to be made 'abstract' by the compiler`
`    // and we also provide {minimal} to each so that if anyone inheriting doesn't implement them because they dont *use* them, it's not a linker error`
`   virtual float get_wp_distance() { hal.console->printf("ERROR: get_wp_distance() NOT IMPL somewhere");return 0.0;}`
`   virtual int32_t get_wp_bearing(){hal.console->printf("ERROR: get_wp_bearing() NOT IMPL somewhere");return -1;}`
`   virtual uint16_t get_wp_number(){hal.console->printf("ERROR: get_wp_number() NOT IMPL somewhere");return 0;}`
`   virtual float get_xtrack_error(){hal.console->printf("ERROR: get_xtrack_error() NOT IMPL somewhere");return 0.0;}`

**Comment by tridge** [comment]
> @yaapu This would also get rid of the OSD thread

why does it get rid of the OSD thread? The thread is there as the bus ops on the OSD are quite slow and we don't want to stop flying the vehicle while doing them. We could do it in the SPI bus thread instead for systems where the OSD is on a SPI bus (all real boards at this stage). Doing the bus operations from the main thread definitely would be bad.

**Comment by yaapu** [comment]
@tridge I didn't express myself properly, I should have said
'This would also get rid of the vehicles OSD scheduled tasks..
https://github.com/ArduPilot/ardupilot/blob/d6e17b0c2b953ef49fc500013829a932e1073c8c/ArduPlane/ArduPlane.cpp#L103-L105

**Comment by yaapu** [comment]
@davidbuzz I agree pure virtual is a bit aggressive but virtual wouldn't let end user distinguish between a real value and a not implemented one.
We might come up with some kind of test at build time that would validate those methods that we "require" each vehicle to implement even vehicle specific ones.
This way we might have the best of both worlds?

**Comment by peterbarker** [comment]
We agreed to merge this today, even though it's currently dead code.

**Pull request merged**
