### PR TITLE
Copter: Fix guided yaw bug.

### PR DESCRIPTION
**Pull request by lthall**
This is a small bug fix to enable full guided mode yaw capability.

### CODE REVIEW

**Review by khancyr — APPROVED** [review]
Nice one.
Not blocking change : use * 0,001 instead of / 1000.0 as it is faster 
using setyaw 180 5 1 show that master don't respect the input and the yaw change is at full speed.

**Comment by khancyr** [comment]
That is annoying as the change on AUTO_YAW_ANGLE_RATE is definitively right, but tests on master weren't failing on yaw rate targetting (https://github.com/ArduPilot/ardupilot/blob/master/Tools/autotest/common.py#L8004 and https://github.com/ArduPilot/ardupilot/blob/master/Tools/autotest/common.py#L8236). Anyone got an idea to improve the tests ?

**Comment by lthall** [comment]
> use * 0,001 instead of / 1000.0 as it is faster

I have added this.

**Review by rmackay9 — APPROVED** [review]

**Comment by rmackay9** [comment]
Merged, thanks!

**Pull request merged**
