### PR TITLE
Add option to compile OpticalFlow out of the code

### PR DESCRIPTION
**Pull request by peterbarker**
This allows the OpticalFlow library to be compiled out of ArduPilot.

I've only tested this for compilation on CubeBlack.  Each backend can be compiled out separately.

```

No-flow:
bin/arducopter   1661856      3304   193504               1665160          415604
flow:
bin/arducopter   1680220      3312   193508               1683532          397220

no-hereflow:
bin/arducopter   1678392      3304   193504               1681696          399068
```

### CODE REVIEW

**Comment by peterbarker** [comment]
Durandal:
```
 Binary Name      Text [B]          Data [B]     BSS (B)        Total Flash Change [B] (%)      Flash Free After PR (B)
---------------  ----------------  -----------  -------------  ----------------------------  -------------------------
arducopter-heli  0 (0.0000%)       0 (0.0000%)  0 (0.0000%)    0 (0.0000%)                                      229408
blimp            0 (0.0000%)       0 (0.0000%)  0 (0.0000%)    0 (0.0000%)                                      689620
antennatracker   0 (0.0000%)       0 (0.0000%)  0 (0.0000%)    0 (0.0000%)                                      620508
ardusub          12716 (+0.8224%)  0 (0.0000%)  -4 (-0.0015%)  12716 (+0.8213%)                                 405164
arducopter       0 (0.0000%)       0 (0.0000%)  0 (0.0000%)    0 (0.0000%)                                      207016
arduplane        0 (0.0000%)       0 (0.0000%)  0 (0.0000%)    0 (0.0000%)                                      205292
ardurover        0 (0.0000%)       0 (0.0000%)  0 (0.0000%)    0 (0.0000%)                                      381316
```

**Review by tridge — APPROVED** [review]

**Comment by Hwurzburg** [comment]
@peterbarker, @tridge :
1. does this change if optical flow was being built in some vehicles by default but no longer is? ie plane/sub
2. what about 1MB boards, any changes?
3. has the build server options been updated?

**Comment by peterbarker** [comment]
On Wed, 29 Dec 2021, Henry Wurzburg wrote:

>  1. does this change if optical flow was being built in some vehicles by default but no longer is? ie plane/sub

Now built on Sub where it wasn't previously.

>  2. what about 1MB boards, any changes?

No.

>  3. has the build server options been updated?

No.

**Comment by Hwurzburg** [comment]
so were you going to submit a PR for #3 as a consequence of this PR? or do you wish for me to do it?

**Comment by peterbarker** [comment]
On Thu, 30 Dec 2021, Henry Wurzburg wrote:

> so were you going to submit a PR for #3 as a consequence of this PR? or do you wish for me to do it?

I had no plans to.

I did look at it, but the format for specifying the dependencies was 
somewhat opaque.  As in flat array with no comments that I spotted which 
made it easy.

There's basically the master option AP_OPTICALFLOW_ENABLED and an option 
for each of the backends (e.g. AP_OPTICALFLOW_HEREFLOW_ENABLED).  It 
should be much like the MSP block - I copy/pasted it and started poking 
the results - but quickly shrugged and moved on.

**Pull request merged**
