### PR TITLE
ADSB over UAVCAN

### PR DESCRIPTION
**Pull request by tridge**
This adds support for AP_Periph providing a UAVCAN ADSB adapter. It works by plugging a Ping ADSB receiver into a f103 AP_Periph node from mRobotics.
It also adds support for ArduPilot receiving ADSB data over UAVCAN, so that it can do avoidance and logging of traffic in the ArduPilot logs.
Note that this uses a Matternet DSDL structure for the UAVCAN message format. I'm in two minds whether we should keep this or create an ardupilot specific one
The DSDL came from work done by @jschall

### CODE REVIEW

**Comment by jschall** [comment]
Let's change the message name so that it is not "com.matternet."
Perhaps "org.ardupilot."

**Comment by tridge** [comment]
@jschall yeah, I wondered if I should. It changes the signature though, so I need to check how hard it is for matternet to rebuild with the new name

**Comment by jschall** [comment]
Or make them a special version that uses their name.

**Comment by tridge** [comment]
@jschall true, I could just carry a patch for them

**Comment by tridge** [comment]
i've changed it to be ardupilot/equipment namespace. Matternet will carry a patch to use their namespace

**Pull request merged**
