### PR TITLE
AP_HAL_ChibiOS: fix fast_channel_mask

### PR DESCRIPTION
**Pull request by kd0aij**
This makes param SERVO_RATE functional for IO and FMU channels.

### CODE REVIEW

**Comment by kd0aij** [comment]
the IOMCU changes need testing: works on mRoX21 with normal PWM output

**Comment by tridge** [comment]
@kd0aij I've added one more commit to this to use the IOMCU masks to only ask IOMCU to set the right channels, which also means that io_fast_channel_mask is maintained correctly

**Comment by kd0aij** [comment]
@tridge Thanks, this looks good to me now. 

I eliminated the redundant masks array in AP_IOMCU::set_freq and deleted the unused update_masks variable in RCOutput::set_freq and retested on the X21. 
If you agree with those changes, I think it's ready for squash and merge.
I'll also change the commit message prefixes from AP_HAL... to HAL...

**Comment by tridge** [comment]
@kd0aij looks good, thanks!

**Comment by kd0aij** [comment]
squashed; no changes to source

**Pull request merged**
