### PR TITLE
PID - Replacement by AC_PID

### PR DESCRIPTION
**Pull request by dgrat**
I just wondered, whether PID is still needed? Ideas? 
Currently untested.

### CODE REVIEW

**Comment by khancyr** [comment]
@dgrat Nice one ! 
Here are some clues : https://github.com/ArduPilot/ardupilot/pull/6852 
But as your pass test, the position may be revised !

**Comment by dgrat** [comment]
I wonder why you commit failed the test. I guess the only explanation is either the claculation of <code>dt</code> or the start settings of the PID.  I used the settings of the old PID, but they should be anyway overridden by AP_Param ...

**Comment by Linjieqiang** [comment]
I think the ardupilot project maybe need to remove some unused code form the master branch.

**Comment by dgrat** [comment]
Well, lets wait for @tridge opinion.

**Comment by dgrat** [comment]
I also made a branch where I changed dt calculation. Seems to works a well (as it should).

https://github.com/dgrat/ardupilot/commit/8059ee5e7f657b9f0288d1acdb79e54656ca7e71

**Comment by WickedShell** [comment]
Overall I'd still rather not do this. It doesn't come with param conversion code, and will require users of the feature to retune. As it doesn't actually provide new features or address a bug in the deepstall landing library, I'd strongly prefer to leave the PID library alone at this point.

**Comment by dgrat** [comment]
Understand, it would be really a great tragedy if users have to redo PID configuration. Shall I close?

**Comment by WickedShell** [comment]
Closing for now, for much the same reason as before, sorry @dgrat

**Pull request closed without merging**
