### PR TITLE
Dual imu and tone alarm

### PR DESCRIPTION
**Pull request by pritamghanghas**

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
@pritamghanghas I took the first commit doing the rename while applying the ADC changes to pxf (otherwise you'd get yet another conflict). I'll try to review the rest soon. Thanks.

**Comment by lucasdemarchi** [comment]
We never merges. So the right thing to do would be a rebase.

As for losing comments, this is a github problem. We actually don't lose them, but we lose the reference to the commits they were in. In this case what I generally do is to close the PR and open another one with (v2) in the title. It's a pain, but at least we don't lose the comments.

**Comment by lucasdemarchi** [comment]
@pritamghanghas updates on this?  I will probably take this PR on top of mine (#3544) and do some rework on top. Are you ok with this?

**Comment by pritamghanghas** [comment]
I am waiting for new raspilot board. Have doubts about the current board
that I have. Have been sitting on it because I didn't want to give the
impression with these commits that everything is working as currently its
not working. MPU9250 gives "Bad WHOAMI" and LSM isn't calibrating anymore.
I would start once again once the new boards arrives. Till then I have no
problem about where you take it. I will just start working on top of your
work once I have reliable hardware with me.

On Thu, Jan 28, 2016 at 8:18 PM, Lucas De Marchi <notifications@github.com>
wrote:

> @pritamghanghas <https://github.com/pritamghanghas> updates on this? I
> will probably take this PR on top of mine (#3544
> <https://github.com/diydrones/ardupilot/pull/3544>) and do some rework on
> top. Are you ok with this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/diydrones/ardupilot/pull/3467#issuecomment-176219746>.
>



-- 
Regards,
pritam

**Comment by lucasdemarchi** [comment]
@pritamghanghas ok, no problem. Btw, my raspilot with MPU9250 is working fine on my branch. I didn't test LSM on it yet.  Are the raspilot boards still being sold?

**Comment by pritamghanghas** [comment]
I have convinced Jerry to do more batches on promise that I will maintain
the port. With sciencebeer leaving the project, there was no one to
maintain the code and Jerrry was no longer sure about viability without
somebody supporting the APM port. If this works and there are no major
board design issues, I guess we can make it work as a completely community
driven board. If you have any feedback about the board or modification
needed, you can contact me or jerry so that it gets incorporated.

The current small batch will be the same layout and design as v1.1 and
v1.2. Once its working again and new batch is verified, I would like to
give a go on adjustable pwm frequency and more pwm outputs as their are
additional ports available on IO STM  and timers can be reallocated in a
way that atleast one group can have lower frequency. That will probably be
v1.3, I think in that revision Jerry can incorporate design changes if you
suggest any.

On Sat, Jan 30, 2016 at 12:34 AM, Lucas De Marchi <notifications@github.com>
wrote:

> @pritamghanghas <https://github.com/pritamghanghas> ok, no problem. Btw,
> my raspilot with MPU9250 is working fine on my branch. I didn't test LSM on
> it yet. Are the raspilot boards still being sold?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/diydrones/ardupilot/pull/3467#issuecomment-176914546>.
>



-- 
Regards,
pritam

**Comment by lucasdemarchi** [comment]
new version on #3730

**Pull request closed without merging**
