### PR TITLE
Copter: 4.4.1-beta2 release

### PR DESCRIPTION
**Pull request by rmackay9**
This is the Copter-4.4.1-beta2 release which includes just 3 extra PRs which can be seen in the "4.4.1-beta2" column of [this project](https://github.com/ArduPilot/ardupilot/projects/27).

Rover's 4.4.0-beta7 will be identical to this PR.

I've taken a small leap and added the release notes and version change for Plane as well.

### CODE REVIEW

**Review by tridge — APPROVED** [review]

**Comment by tridge** [comment]
> I've taken a small leap and added the release notes and version change for Plane as well.

thanks!
I notice you use BETA+2 for beta2, whereas I always did BETA+1 for beta2 (ie. BETA+0 is beta1)
probably doesn't matter

**Comment by rmackay9** [comment]
@tridge,

Re the beta+0 vs beta+1. it makes sense to do one or the other... I'm happy for it to be zero based from now on.

**Comment by andyp1per** [comment]
Doesn’t this include the chibios changes as well?Andy Sent from my iPhoneOn 12 Sep 2023, at 09:25, Randy Mackay ***@***.***> wrote:﻿This is the Copter-4.4.1-beta2 release which includes just 3 extra PRs which can be seen in the "4.4.1-beta2" column of this project.
Rover's 4.4.0-beta7 will be identical to this PR.
I've taken a small leap and added the release notes and version change for Plane as well.



You can view, comment on, or merge this pull request online at:
  https://github.com/ArduPilot/ardupilot/pull/24959

Commit Summary

  e8a8711  hwdef: get airbotf4 building with 4.4
  5577489  Plane: 4.4.1-beta2 release notes
  fe78ce0  Plane: version to 4.4.1-beta2
  2af1b5a  Rover: 4.4.0-beta7 release notes
  c73c9ad  Rover: version to 4.4.0-beta7
  3282d9a  Copter: 4.4.1-beta2 release notes
  9c47541  Copter: version to 4.4.1-beta2


File Changes  (7 files)

  
    M
    ArduCopter/ReleaseNotes.txt
    (9)
  
  
    M
    ArduCopter/version.h
    (4)
  
  
    M
    ArduPlane/ReleaseNotes.txt
    (10)
  
  
    M
    ArduPlane/version.h
    (4)
  
  
    M
    Rover/release-notes.txt
    (9)
  
  
    M
    Rover/version.h
    (4)
  
  
    M
    libraries/AP_HAL_ChibiOS/hwdef/airbotf4/hwdef.dat
    (2)
  


Patch Links:

  https://github.com/ArduPilot/ardupilot/pull/24959.patch
  https://github.com/ArduPilot/ardupilot/pull/24959.diff

**Comment by andyp1per** [comment]
@rmackay9 - @mluessi will be keen for https://github.com/ArduPilot/ardupilot/pull/24959 to make it in as well since most of the changes are geared to enabling that!

**Comment by rmackay9** [comment]
Hi @andyp1per, OK, thanks.  That link points back to this PR.. maybe I can find the correct one in a bit..

**Comment by rmackay9** [comment]
This has been updated to:

1. include https://github.com/ArduPilot/ardupilot/pull/24897
2. BETA now uses 0 indexing
3. release notes slight updated

I'll merge this after it passes CI

**Comment by rmackay9** [comment]
Despite the risk of delaying the release further, I've added two more changes requested by @andyp1per and @HefnySco respectively.  I figure they've just arrived in time and maybe this will generate more interest in beta testing :-).

- https://github.com/ArduPilot/ardupilot/pull/23245
- https://github.com/ArduPilot/ardupilot/pull/23943

I'll merge as soon as it passes CI.

**Pull request merged**
