### PR TITLE
AP_GPS: add AP_GPS_FEMTO driver for Femtomes GPS

### PR DESCRIPTION
**Pull request by Femtomes**
1.Add AP_GPS_FEMTO driver for Femtomes gps device
2.Add femtomes driver in AP_GPS class

### CODE REVIEW

**Comment by Femtomes** [comment]
Note ：This driver only supports Femtomes gps devices. We have our own protocol, which is fundamentally different from Novatel. Novatel does not support such messages. If mixed into Novatel driver code, it will cause confusion to other Novatel users.

**Comment by WickedShell** [comment]
> Note ：We have our own protocol, which is fundamentally different from Novatel. Novatel does not support such messages. If mixed into Novatel driver code, it will cause confusion to other Novatel users.

I'm sorry but that's not true. You have the same protocol with some new functions (indeed the driver you have PR'd here is almost a perfect copy of our Novatel driver, with some slight function renaming, but the same source code). The new messages would need to be isolated I agree, but that's best done with a type parameter that gets passed to the GPS driver. This will not lead to any user confusion as you still select a different type for the GPS parameter, but saves us a massive amount of flash...

**Comment by peterbarker** [comment]
Structure-wise, if it really is just the initialisation blob and a few new messages, perhaps make this new driver inherit from the NOVA driver.  `process_msg` can be made `virtual`, and a callback created to get the initialisation blob.  I don't think `switch`ing on a passed-in `type` is better than that.

**Comment by Femtomes** [comment]
Dear WickedShell and PeterBraker. both your comments have good points. However, let me explain more about why we see these two drivers are essentially different. Typically, a binary message protocol constitute a preamble, a message payload, and encoding check (e.g. parity or CRC). Our choice of preamable is same with novatel as for the convenience of the current user practice and CRC32 is indeed common knowledge. We see the PAYLOAD FORMAT is the essence of a protocol which we put a lot of effort to optimize which parameter is best for APM applications and how to organize them. As for protocol decoder, we do have our own codes for syncing the preamble and checking CRC32 ,but I personally copy those code from novatel driver simply because I thought those code are well checked and well reviewed by you guys. why not reuse them. In my personal opinion, I think peter barker 's suggestion on inherit from NOVA driver make sense in some level. However it still brings some misconception on the code structure. Allow me to give a maybe-inproper analogy: there are two class to describe a car, one is trunk and another is sport car, the common thing of these two are all have four wheels and the difference is payload capacity. It is odd for sport car class to derive from the trunk class. Maybe it is better to have common parser base and both NOVA driver and femtomes driver can inherit from the common base. I thought it is not my place to change NOVA driver, but if you guys consider it is the best solution I can contribute on that with no-doubt.

**Comment by peterbarker** [comment]
> Maybe it is better to have common parser base and both NOVA driver and femtomes driver can inherit from the common base.

That would also be acceptable.  My suggestion was made that way to minimise changes to the existing NOVA driver.

When the work's done, the first commit should be a clean split of the nova driver into the parser and the message handler (/initialisation-blob-supplier).  The next commit would add femto as another message handler subclass of the parser.

**Pull request closed without merging**
