### PR TITLE
AHRS: pre_arm_check accepts requires_position argument to allow disabling some checks

### PR DESCRIPTION
**Pull request by rmackay9**
This PR allows vehicles to skip the EKF3 source parameter checks for horizontal and vertical position and velocity checks.  In particular this allows Copters to arm in Stabilize, Acro, AltHold and Sport even if EK3_SRCx_POSXY, VELXY, VELZ or POSZ are set to GPS but no GPS if found (can be caused by GPS being disconnected or GPS_TYPE = 0).

This has been lightly tested in SITL for Copter and appears to work.  Below are before and after screens shots when attempting to arm in Stabilize mode with GPS_TYPE = 0.

ekf3-arming-checks

This resolves issue: https://github.com/ArduPilot/ardupilot/issues/16017

FYI @tridge @andyp1per

### CODE REVIEW

**Comment by Hwurzburg** [comment]
can this be extended to ALTHOLD and SPORT?....it does not require GPS, although if baro fails one would need to switch to ACRO/STAB...

**Review by khancyr — APPROVED** [review]
LGTM

**Comment by rmackay9** [comment]
@Hwurzburg, thanks for the comment.  This actually applies to AltHold and Sport as well so I've updated the description. txs!

**Comment by joneseym** [comment]
FYI, using the latest dev build my copter will now arm in stabilize mode and other non-GPS modes  when there is no GPS fix, even though GPS fix is explicitly enabled as one of the pre-arm checks and a GPS is present and enabled (just no fix, e.g. indoors).

I am guessing this is not intended behaviour but I suspect it may have been intorduced by this PR.

**Comment by peterbarker** [comment]
On Mon, 8 Feb 2021, joneseym wrote:

> FYI, using the latest dev build my copter will now arm in stabilize mode and other non-GPS modes when there is no GPS fix, even though GPS fix is
> explicitly enabled as one of the pre-arm checks and a GPS is present and enabled (just no fix, e.g. indoors).
> 
> I am guessing this is not intended behaviour but I suspect it may have been intorduced by this PR.

That's actually always been the intended behaviour for Copter.

**Pull request merged**
