### PR TITLE
Update Kakute F4 Wing board_types.txt

### PR DESCRIPTION
**Pull request by vincentpoont2**
Change AP_HW ID to 5406 due to conflict with another product.  The [Holybro DroneCAN airspeed sensor uses 5405](https://github.com/ArduPilot/ardupilot/pull/27631/files#diff-a720bbf01b6a94de212cea3cb69c06eb00dfb6255f75e4cca8fdba17a43dfa69R357) and the FW has already been flashed onto actual products.

### CODE REVIEW

**Comment by vincentpoont2** [comment]
@andyp1per Can you review and merge?

**Comment by peterbarker** [comment]
> Change AP_HW ID to 5406 due to conflict with another product. The [Holybro DroneCAN airspeed sensor uses 5405](https://github.com/ArduPilot/ardupilot/pull/27631/files#diff-a720bbf01b6a94de212cea3cb69c06eb00dfb6255f75e4cca8fdba17a43dfa69R357) and the FW has already been flashed onto actual products.

Any reason to not put 5405 in here too?  Will stop this happening again.

**Comment by andyp1per** [comment]
@vincentpoont2 we need to rebuild the bootloaders as well with this change. Sorry I did not spot this!

**Review by andyp1per — APPROVED** [review]

**Review by peterbarker — APPROVED** [review]
Fixed the commit messages and marking as MergeOnCIPass

**Pull request merged**
