### PR TITLE
Plane: fix divide by zero in transition time

### PR DESCRIPTION
**Pull request by Hwurzburg**
can remove minimum if we want to save a few bytes of flash....but I would prevent the possible divide by zero myself...

### CODE REVIEW

**Review by IamPete1 — APPROVED** [review]
Range change is good. 

I could leave or take the addition of the max, it seems to not add any flash in this case because of the mysterious ways of the compiler.

**Comment by magicrub** [comment]
The docs don't say anything but is zero ( or 0.000001) give any other useful behavior?

**Comment by WickedShell** [comment]
Considering a NaN get's passed to `_throttle_rpy_mix_desired` directly it's probably worth ensuring it doesn't happen. A value down to about 0.1 seems quite plausible though instead of just forcing 1 there...

**Comment by Hwurzburg** [comment]
> The docs don't say anything but is zero ( or 0.000001) give any other useful behavior?

no...no special behavior except divide by zero error

@WickedShell this is in ms so 1 seems plenty low to me...no need for 100uS as an option....to complete the transition IMO...even a value of 100 min....doesnt matter, just not zero

**Comment by WickedShell** [comment]
> @WickedShell this is in ms so 1 seems plenty low to me...no need for 100uS as an option....to complete the transition IMO...even a value of 100 min....doesnt matter, just not zero

Okay, yeah 1's fine then. I had forgotten it was in milliseconds, sorry.

**Comment by IamPete1** [comment]
The throttle mix being nan is safe, it is constrained. It will slew down towards 0.1, it will only be a single loop in any case as it will advance onto the next transtion stage. 

https://github.com/ArduPilot/ardupilot/blob/83d3aace444fa53c9f10c0b425eda3c1a49024b2/libraries/AC_AttitudeControl/AC_AttitudeControl_Multi.cpp#L315-L327

**Pull request merged**
