### PR TITLE
ArduPlane: An experiment in tighter integration of  horizontal and vertical tracking navigation loops

### PR DESCRIPTION
**Pull request by priseborough**
As bank angles increase, the effect of changes to  pitch angle demanded by TECS is to generate a change in turn radius due to the variation in pitch rate and therefore normal load factor. The horizontal navigation them adjusts the bank angle which in turn causes the normal g vector to rotate and vary vertical lift. This can result in an out of phase roll and pitch limit cycle during high bank turns depending on how the AP_TECS and AP_L1_Control libraries have been tuned.  This branch experiments with methods to reduce this interaction.

The first attempt was via a correction to the nav_roll_cd that took into account the predicted change in normal load factor. 
See https://github.com/ArduPilot/ardupilot/commit/231b2ca53d2e90f4a6014b9f576d6855aeaa34aa and https://github.com/ArduPilot/ardupilot/commit/839c5ed004509ad489c7bea25613de84f4ef0cdd. However this was going to be difficult to tune as the decoupling gain would vary depending on the relative speed of the TECS, pitch and and roll control loops so was discarded.

The second approach was to add a user selectable via NAV_TYPE_ACC control mode that combines a horizontal acceleration demand (calculated from the AP_L1_Control  calculated nav_roll_cd) and a vertical acceleration demand calculated by AP_TECS that has been modified to calculate a vertical acceleration in addition to a pitch angle. These acceleration demands are then converted to a bank angle and pitch rate demand. Exisiting pitch angle limits are respected as is the normal load factor limit set by a new LOAD_FACTOR_MAX parameter. This approach has a number of benefits:

- Pitch angle errors do not directly affect height tracking performance.
- Height keeping at steep bank angles should be better.
- Tuning of the pitch controller I gain becomes more important so that good rate tracking is achieved. 

The control loop used by TECS to calculate the flight path angle demand has also been re-worked to move the integrator down one level in the loop cascade so that it works on the height rate error not height error. This reduces overshoot when levelling off following a climb or descent. A block diagram sketch of the of vs new calculation is shown below:

Screen Shot 2021-03-22 at 6 50 52 pm

The TECS changes could be split out into a separate PR to the acceleration vector nav.

**TODO**

For the acceleration vector control option enabled by LOAD_FACTOR_CTL (which is off by default):

Make it work when flying upside down.

**SITL TESTING**

ArduPlane SITL with CMAC_grid plan loaded and NAV_TYPE_ACC = 1.  

Screen Shot 2020-09-28 at 3 01 01 pm

** FLIGHT TESTING**

See comments for test results obtained using a Strix Nano Goblin and other airframes. To date the optional acceleration vector control has only been tested on the Nano Goblin.

### CODE REVIEW

**Comment by tridge** [comment]
exciting stuff! This should really help with height in turns!

**Comment by priseborough** [comment]
Good test on a nano Goblin today with tight height tracking with significant convection up/down air movement and up to 60 deg bank angle.

Screen Shot 2021-03-20 at 6 16 03 pm

Screen Shot 2021-03-20 at 6 16 18 pm

**Comment by tridge** [comment]
needs a rebase for new rate controllers

**Comment by davidbuzz** [comment]
appears to have been rebased by @priseborough  , appears to need another lookover by @tridge  ?

**Comment by davidbuzz** [comment]
hey @priseborough  - how far away do u think this is to being mergable..?  :-)

**Comment by priseborough** [comment]
Not much to go. I need to spend some time going through the changes with @tridge and get some testing on other vehicles so that the default parameters settings can be validated.

**Comment by priseborough** [comment]
Results from testing on a MakeFlyEasy Believer airframe with airspeed sensor is presented below.

The takeoff was done with the legacy defaults.
 
Screen Shot 2022-10-16 at 1 47 18 pm

Tuning parameters were then adjusted at the following times (note the time stamps in the figures are shown in AEST not AEDT, hence the 1 hour offset)

2022-10-16 11:42:55.201 TECS_INTEG_GAIN 0.100000 -> 0.200000
2022-10-16 11:43:30.121 TECS_HDEM_TCONST 2.000000 -> 3.000000
2022-10-16 11:43:44.163 TECS_PTCH_DAMP 0.000000 -> 0.300000
2022-10-16 11:46:43.463 TECS_RLL2THR 10.000000 -> 7.000000
2022-10-16 11:50:41.701 TECS_INTEG_GAIN 0.200000 -> 0.300000
2022-10-16 11:51:42.940 TECS_INTEG_GAIN 0.300000 -> 0.400000
2022-10-16 11:52:44.302 TECS_INTEG_GAIN 0.400000 -> 0.500000
2022-10-16 11:53:42.540 TECS_INTEG_GAIN 0.500000 -> 0.300000

Screen Shot 2022-10-16 at 1 52 07 pm

The height and speed control was acceptable for all combinations. Increasing TECS_PTCH_DAMP from 0 to 0.3 at 11:43:44 did reduce height variation.

Screen Shot 2022-10-16 at 1 57 07 pm

The effect of other changes was more subtle.  The value of TECS_RLL2THR was reduced slightly because. the aircraft was increasing airspeed slightly during turns.

The integrator was increased in steps of 0.2 from 0.2 up to 0.5 and the height tracking for a single climb and descent  was tested for each value of 0.3, 0.4 and 0.5, eg:

Screen Shot 2022-10-16 at 2 00 14 pm

Based on this limited sample, TECS_INTEG_GAIN = 0.3 was chosen.

This aircraft does not exhibit significant speedup during descent with throttle closed. Future testing with the pitch angle and descent limits opened up is recommended.

**Comment by priseborough** [comment]
Another log from flight of a Ranger 1600 using the legacy TECS gain default values flown using changes up to commit aa0b8ff

Screen Shot 2022-10-16 at 2 23 33 pm 

Speed and height control was acceptable with minimal overshoot on climb completion or undershoot on descent completion.

**Comment by priseborough** [comment]
Here are test results on a Striver VTOL. The following TECS gains were evaluated.

2022-10-16 11:04:34.481 TECS_INTEG_GAIN 0.100000 -> 0.200000
2022-10-16 11:04:56.679 TECS_HDEM_TCONST 2.000000 -> 3.000000
2022-10-16 11:06:56.393 TECS_INTEG_GAIN 0.200000 -> 0.400000
2022-10-16 11:07:07.782 TECS_INTEG_GAIN 0.400000 -> 0.500000
2022-10-16 11:07:46.765 TECS_PTCH_DAMP 0.000000 -> 0.300000
2022-10-16 11:11:58.034 TECS_INTEG_GAIN 0.500000 -> 0.200000

The time stamps for the following figure are in AEST not AEDT. This figure starts at the section of flight where we have set

TECS_HDEM_TCONST = 3.0
TECS_INTEG_GAIN = 0.5
TECS_PTCH_DAMP = 0.3

At 11:11:58 AEDT the TECS_INTEG_GAIN was reduced from 0.5 to 0.2

Screen Shot 2022-10-16 at 2 53 37 pm

The larger value for integrator gain did not produce overshoot. Based on this and data from testing on other vehicles, we shoulf be able to increase the default value of TECS_INTEG_GAIN with this  new controller architecture.

**Comment by priseborough** [comment]
Thank you [@pompecukor](https://github.com/pompecukor) for testing these patches rebased on Plane stable 4.3.1.

The height and speed control is improved from an flight using legacy TECS in similar 6 m/s wind conditions:

Legacy TECS:

Height Control
Screen Shot 2022-11-11 at 9 55 06 am

Speed Control
Screen Shot 2022-11-11 at 9 56 07 am

New TECS

Height Control
Screen Shot 2022-11-11 at 9 57 51 am

Speed Control
Screen Shot 2022-11-11 at 9 58 44 am

**Comment by priseborough** [comment]
This PR has been replaced with https://github.com/ArduPilot/ardupilot/pull/22191 which implements the TECs changes that  will benefit all users.

The optionally enabled more advanced  acceleration vector control will be implemented in a separate PR.

Thank you to everyone who contributed to flight testing these changes.

**Pull request closed without merging**
