### PR TITLE
Fix bodycentric attitude

### PR DESCRIPTION
**Pull request by PeterQFR**
Addresses #20444
This PR checks if the user wants to use attitude quaternion but also specifies yaw rate but not pitch or roll rates for attitude control. 
This then enables control in body centric pitch and roll, yaw is ignored from the quaternion. Yaw is specified by yaw rate.

### CODE REVIEW

**Comment by rmackay9** [comment]
@PeterQFR,

Thanks for this.  One small thing is that our commits are normally prefixed with the subsystem (i.e. vehicle name or library name) in order to make backporting easier.  So for example these commits should be prefixed with "Copter:".  So it might become something like, "Copter: add body frame attitude setting" although something more specific might better.  E.g. "Copter: guided mode body frame attitude setting".

**Comment by PeterQFR** [comment]
@rmackay9 Do you not squash commits when the PR is done? That way you could put all detail in a single commit and call it what you want.

**Comment by lthall** [comment]
I literally sent this to Randy Yesterday. "I had a thought about the problem where people want to command roll and pitch attitude and yaw rate. Currently we need the quaternion or no quaternion, and we need all 3 rates or none. The thought I had was that we could use the enable bits to detect if only yaw rate has been provided and in that case interoperate the input as attitude and yaw rate. I am not sure how I feel about it but I wanted to get it down to have a chat with you at some point."

**Comment by PeterQFR** [comment]
Yeah, I'd had a specific fix for this last year on a local copy of mine and forgot about it. But then I went to try my code against an upstream firmware binary it started rotating on the spot! 
So I figured I should do this properly and make a PR

**Comment by Ryanf55** [comment]
> I literally sent this to Randy Yesterday. "I had a thought about the problem where people want to command roll and pitch attitude and yaw rate. Currently we need the quaternion or no quaternion, and we need all 3 rates or none. The thought I had was that we could use the enable bits to detect if only yaw rate has been provided and in that case interoperate the input as attitude and yaw rate. I am not sure how I feel about it but I wanted to get it down to have a chat with you at some point."

We're facing the same questions in #23363. Randy and I came to similar conclusions for that interface.

**Comment by PeterQFR** [comment]
This PR checks that:
Yaw rate enabled
Pitch and Roll disabled/ignored
Attitude is enabled,
before assuming that you want to command pitch and roll in body frame and use rate for yaw. Its documented in the code might want to document it in the non-gps documentation as its a common use case.

**Comment by PeterQFR** [comment]
I did a flight test using this code and it works as per patch in #20444.

**Comment by ajshank** [comment]
I'm a little bit confused by the discussion here. Over a year ago, #20444 was _strongly_ opposed to (cf also #22865) -- has something changed?
I've proposed and maintained a local patch that makes this feature available through a bit in `GUID_OPTIONS` which makes this choice quite explicit -- how is making an extra assumption using user's ignore/no-ignore settings any better?

**Comment by PeterQFR** [comment]
#22865 is a very similar implementation, only missing a check is on the validity of the attitude quaternion. I like the direct calculation of the boolean for this mode in that system too, will make a change here. Otherwise its almost verbatim the same implementation.
Prefer either with the assumption method because I'm already using that implementation. 

@lthall  I don't really consider this a corruption of the original message as stated in #22865. The yaw component of the quaternion is essentially undefined if using in non-gps environments. And at best, a lot of the mavlink messages are only defined by convention (such as the NED frame).

**Comment by lthall** [comment]
I have two main problems with this.

1. The current message can't be applied without ignoring the yaw component of the quaternion. This is a "corruption of the original message" and the only argument to the contrary is the one where we say that heading is unknown and therefore we must ignore it. Discussions about needing GPS to know heading (false) or conventions aren't important are just a distraction.
2. The dev team seemed to prefer defining a new message to handle this form of control.

Using a strict interpretation of this message we have three options:

https://mavlink.io/en/messages/common.html#ATTITUDE_TARGET_TYPEMASK

1. Quaternion control (ignore body roll, pitch and yaw rates),
2. Rotation vector control (ignore attitude),
3. Quaternion and rotation rate control (don't ignore attitude and at least one body roll, pitch or yaw rate).

Where this approach could break somebody else's implementation is if they are using this message as it is designed to be used but ignoring any rate input that they are currently setting to zero. This could be easily fixed by setting these rates to zero and not ignoring them.  I find this unlikely but we have a lot of users...

We could decide that, to be valid, this message must use all three rates, OR ignore all three rates. Then we could also decide that ignoring roll and pitch rate but accepting yaw rate is a clear and unambiguous indication that we want to interpret the quaternion as roll and pitch attitude only.

However, this change could cause somebody to crash their aircraft if they are using the message as it is specified and ignoring any rate input that is set to zero.

Given we now have three attempts to provide PR's to support this feature and two (this and #22865) that use this approach I am starting to think the risk maybe acceptable. We would also need to make a PR to the wiki to clearly describe how we handle this message.

**Comment by PeterQFR** [comment]
There is also the GUID options which would also make it unambiguous.

**Comment by lthall** [comment]
> There is also the GUID options which would also make it unambiguous.

This is really just making a new message but not going to the effort of making a new message.

The best option is to make a new message that is properly defined. The problem here is I don't see anybody willing to make the effort to do that.

That leaves two options from what I can see:
1. Let the current message be distorted to support a useful input combination. Deal with the support load forever or the large influx of complaints when we removing it when we get to (2)
2. Let people make changes in their own branch until someone cares enough to do the job properly.

My personal opinion is if people don't care enough to get together and do (2) then why should we expect the developer team to take on the larger and more prolonged burden of (1).

**Comment by PeterQFR** [comment]
What I mean is, if you're worried people will inadvertantly trigger this condition, the worst outcome will be controllable yaw possibly leading to crash, so they need and will often have a backup mode. Setting GUID_OPTIONS bit will force people to proactively select this mode of interpretation of the ATTITUDE_CMD. 
```
This is really just making a new message but not going to the effort of making a new message.
```

I don't understand the new message bit.

**Comment by lthall** [comment]
> I don't understand the requirement for a new message.

The message you are using does not describe what you are doing. The Quaternion discribes the full attitude, including the heading. There is nothing in the message to say you want to ignore the heading component of the quaternion. Using this message is just a short cut and hacky.

The message you want would provide roll, pitch and yaw angles, and roll, pitch and yaw rates, with the ability to ignore yaw angle. Or something like that. Maybe a climb rate / thrust level.

Nobody seems to care enough to even specify what they want, much less define a message.

> I would like to see at least this functionality incorporated, so I don't get caught out again.

Then get together with the other two people that want to use this and put together a message specification. Start an issue where you can discuss and build the specification. Tridge seems confident that a new message isn't to hard to do once the specification is done. This is really the only option that doesn't leave the developers with an additional support load for the foreseeable future.

**Comment by PeterQFR** [comment]
Do you really think that is the gold standard solution, we have two solutions here that are the same and another that uses GUID_OPTIONS? No one has proposed a new message format as being the solution to this problem. 

If defining a new message is the only "Correct" way then that effectively is saying that guided_no_gps, which inherits from guided_mode does not need this mode of control.  But that's not the case because we are using roll, pitch and yawrate methods that are part of guided_no_gps. I think introducing a new message is unnecessary.. all we need is to have a mechanism to determine that we are using the attitude_cmd in this way.. that is all.

The mechanism is already there.. use the bitmask which already ignores certain parts of the message, it has values that can enable it to set they system in the mode we are after. Adjusting [ATTITUDE_TARGET_TYPEMASK ](https://mavlink.io/en/messages/common.html#ATTITUDE_TARGET_TYPEMASK) is probably the "correct" way. The message itself provides a mechanism to ignore certain parts... your argument that the attitude yaw cannot be ignored does not align with the mechanics of the message. 

Add an additional flag to IGNORE_QUATERNION_YAW_USE_YAWRATE will be an explicit solution, and be self documenting.

**Comment by lthall** [comment]
> No one has proposed a new message format as being the solution to this problem.

So the developers don't count then? If you don't want to include the developers discussions into the picture then you are back to making PR's to your own code.

> The message itself provides a mechanism to ignore certain parts...

But it doesn't provide the ability to ignore part of the Quaternion attitude, only all of it.

> then that effectively is saying that guided_no_gps, which inherits from guided_mode does not need this mode of control.

I don't see what GPS has to do with heading. You can define the attitude, including the heading without knowing your position.

> But that's not the case because we are using roll, pitch and yawrate methods that are part of guided_no_gps.

I think you are referring to your own code here, not master. guided_nogps gives you only the same angle control as normal guided. There is no reason you shouldn't have a heading (or altitude) when flying guided_no_gps.


Again, I have not seen anybody be willing to take the time to clearly articulate the problem or discuss other, perhaps more appropriate, solutions. Everybody just wants to add their quick hack and make it somebody else's problem.

**Comment by PeterQFR** [comment]
>    No one has proposed a new message format as being the solution to this problem.

> So the developers don't count then? If you don't want to include the developers discussions into the picture then you are back to > making PR's to your own code.

No I mean the people who have taken the time to raise a PR @ajshank #20444 @lmark1 #22865. Your input is important, but you don't seem to understand the need for this feature, and haven't provided as worked up solution for it.  

This feature is needed because, in some use cases we don't want to use or trust Ardupilot's estimate for yaw. (for example due to drift, mag interference, no position updates, arbitary alignment). The control loop for yaw is offboard and we only need attitude control for pitch and roll to control the aircraft as our velocity control loops are also offboard. We just want Ardupilot to interface with the hardware and controll roll, pitch and yawrate.

I will add a PR in Mavlink to add the required bitfield to the ATTITUDE_TARGET_TYPEMASK, and then the message will be complete, and allow ignoring of Yaw and use of yawrate.

**Comment by PeterQFR** [comment]
@ajshank @lmark1 @rmackay9 What do you think about adjusting the SET_ATTITUDE_TYPEMASK to explicity include a mode to ignore quaternion yaw and use yawrate?

**Comment by PeterQFR** [comment]
https://github.com/mavlink/mavlink/pull/2013

**Comment by lthall** [comment]
> This feature is needed because, in some use cases we don't want to use or trust Ardupilot's estimate for yaw.

You don't have a choice. ArduPilot is always using it's estimate of heading. If you send a yaw rate of zero ArduPilot is working to maintain a constant heading, not a yaw rate of zero. If you send a yaw rate of 10 degrees per second, ArduCopter is rotating the target heading at 10 degrees per second. If the estimate of heading changes due to estimation problems the aircraft will rotate even if you are commanding zero yaw rate.

There is very little difference between providing a Quaternion attitude where you increase or decrease the heading component vs command a yaw rate. The difference only becomes apparent if you are trying to follow a moving yaw target.

> The control loop for yaw is offboard and we only need attitude control for pitch and roll to control the aircraft as our velocity control loops are also offboard.

What I said above means this is not the case for yaw control. You are still using the full attitude controller. Yaw control is being done exactly the same way as it always is. Heading is being specified and held. 

> We just want Ardupilot to interface with the hardware and control roll, pitch and yaw rate.

And that is what you are getting here. What you seem to misunderstand is you are also getting roll and pitch rates, and yaw angle. Nothing you have done here changes that. The controllers take your attitude command and create a rotation vector to move to that attitude. If you command a rate the aircraft will update the target attitude by that rotation rate until it receives the next message or the last message times out.

> Your input is important, but you don't seem to understand the need for this feature, and haven't provided as worked up solution for it.

I don't think you understand that you don't need this feature at all. You literally get exactly what you want if you simply integrate your heading rate into the quaternion so it includes the heading, and provide it as a rate. The only difference is you also know exactly what the aircraft target heading is because you specified it in the last message. You literally don't need this message at all!

**Comment by PeterQFR** [comment]
Okay, my starting estimate for yaw is 2.0 radians. I want zero yaw-rate initially. I construct the quaternion using a yaw of 2.0. What is ardupilot going to do?

**Comment by lthall** [comment]
Assuming you got your starting estimate of the aircraft heading from the ATTITUDE_TARGET message:

https://mavlink.io/en/messages/common.html#ATTITUDE_TARGET

Then it will hold that heading with zero yaw rate.

I feel pretty confident you know that so I suspect what you are saying is your heading estimate is different to the aircraft's current heading estimate but you don't want it to move because your heading estimate is correct and the aircraft heading estimate is wrong. I am sure we both can see this is a problem easily solved by accounting for the difference between the two.

**Comment by PeterQFR** [comment]
> Assuming you got your starting estimate of the aircraft heading from the ATTITUDE_TARGET message:

Not a good assumption, it isn't.

**Comment by lthall** [comment]
> Not a good assumption, it isn't.

Sorry, given you obviously didn't understand what I said after that shown here:

> I feel pretty confident you know that so I suspect what you are saying is your heading estimate is different to the aircraft's current heading estimate but you don't want it to move because your heading estimate is correct and the aircraft heading estimate is wrong. I am sure we both can see this is a problem easily solved by accounting for the difference between the two.

Perhaps I have assumed you had a better understanding of how this worked than perhaps you do.

The aircraft has an internal estimation of it's heading. It does not know you have a different estimation of heading. The aircraft also has an internal estimation of heading rate of change, just as you will have your own estimation of heading rate of change. So when you command zero yaw rate the aircraft is working to keep it's own estimation of heading constant, not your estimation of heading.

Now there is a really easy way of calculating the difference between your heading estimation (Yaw_P for payload) and the aircraft heading estimation (Yaw_A for aircraft). The yaw offset between the two, Yaw_O,  can be calculated using this formulae:
Yaw_O = Yaw_A - Yaw_P 

So you can calculate the expected aircraft yaw component using the following formulae:
Yaw_A = Yaw_P + Yaw_O 

The problem is the Yaw offset changes over time because both heading estimates also have different heading rate estimates.

The other thing you are probably not aware of is the roll and pitch of the aircraft are defined relative to the current target heading, not the current heading estimate (and definatly not your heading estimate). Mind blown, I know. This control stuff gets complicated when you use real systems! Don't worry, given your current approach your navigation performance requirements are very low and don't include any need to account for significant disturbances much less loss of yaw control. So you don't have to worry about these issues as they only impact systems trying to achieve higher levels of performance.

**Comment by auturgy** [comment]
I've approved the mavlink pr (https://github.com/mavlink/mavlink/pull/2013), but it'll need to be pulled down to ardupilot/mavlink when it goes in.  @PeterQFR @lthall I suspect you two will end up in screaming agreement if you get on a call to talk this through - you're both in Aus.

**Comment by timtuxworth** [comment]
> > Not a good assumption, it isn't.
> 
> Sorry, given you obviously didn't understand what I said after that shown here:
> 
> > I feel pretty confident you know that so I suspect what you are saying is your heading estimate is different to the aircraft's current heading estimate but you don't want it to move because your heading estimate is correct and the aircraft heading estimate is wrong. I am sure we both can see this is a problem easily solved by accounting for the difference between the two.
> 
> Perhaps I have assumed you had a better understanding of how this worked than perhaps you do.
> 
> The aircraft has an internal estimation of it's heading. It does not know you have a different estimation of heading. The aircraft also has an internal estimation of heading rate of change, just as you will have your own estimation of heading rate of change. So when you command zero yaw rate the aircraft is working to keep it's own estimation of heading constant, not your estimation of heading.
> 
> Now there is a really easy way of calculating the difference between your heading estimation (Yaw_P for payload) and the aircraft heading estimation (Yaw_A for aircraft). The yaw offset between the two, Yaw_O, can be calculated using this formulae: Yaw_O = Yaw_A - Yaw_P
> 
> So you can calculate the expected aircraft yaw component using the following formulae: Yaw_A = Yaw_P + Yaw_O
> 
> The problem is the Yaw offset changes over time because both heading estimates also have different heading rate estimates.
> 
> The other thing you are probably not aware of is the roll and pitch of the aircraft are defined relative to the current target heading, not the current heading estimate (and definatly not your heading estimate). Mind blown, I know. This control stuff gets complicated when you use real systems! Don't worry, given your current approach your navigation performance requirements are very low and don't include any need to account for significant disturbances much less loss of yaw control. So you don't have to worry about these issues as they only impact systems trying to achieve higher levels of performance.

This is an incredibly valuable explanation of how this works. Thanks @lthall ! @Hwurzburg any chance we could get this in the wiki somewhere? Not sure where, but it would be a shame to lose it.

**Comment by lthall** [comment]
I have discussed this with Randy we both feel that the only way forward is a new message that caters specifically to this use case. 

A positive outcome of the discussions around this PR is it has highlighted a problem with our existing interpretation of this message when we accept both an attitude and rotation rate where we have should be using a body frame rate. Fixing this problem will further clarify that the rate message is body frame yaw rate, not the euler yaw rate or heading rate as used in this PR.

I will leave this PR open as it is a capability we would like to support if the interested parties can get together to propose a new mavlink message.

**Review by lthall — COMMENTED** [review]
This is not a change I will support.

**Comment by lthall** [comment]
I had a great chat with @Jaeyoung-Lim and he suggested that the desired behaviour could be achieved using the POSITION_TARGET_LOCAL_NED if we added support for MAV_FRAME_LOCAL_FRD frame.

https://mavlink.io/en/messages/common.html#POSITION_TARGET_LOCAL_NED
https://mavlink.io/en/messages/common.html#MAV_FRAME_LOCAL_FRD
https://mavlink.io/en/messages/common.html#POSITION_TARGET_TYPEMASK

We could support the input where only X and Y acceleration are not ignored. Then Alt_Hold could be controlled with rate and/or position. Yaw can be controlled with rate and/or angle.

This is a much more elegant and appropriate solution to this problem. 

I am closing this PR in preference for https://github.com/ArduPilot/ardupilot/issues/24375

**Pull request closed without merging**
