### PR TITLE
HAL_ChibiOS: initial F103 board file

### PR DESCRIPTION
**Pull request by jpkh**
Adding F103 based boards to autobuild/waf

### CODE REVIEW

**Comment by OXINARF** [comment]
Is this superseded by #10020?

**Comment by jpkh** [comment]
it adds more details of the STM32F103 mcus that were missing from initial script file by @tridge

**Comment by WickedShell** [comment]
Is this still relevant?

**Comment by tridge** [comment]
this has been obsoleted by later work, closing

**Pull request closed without merging**
