### PR TITLE
Add support for the Parrot Rolling Spider

### PR DESCRIPTION
**Pull request by lopsided98**
This builds off of #9142, adding support for a different Parrot minidrone, the Rolling Spider. This drone uses a nearly identical airframe and flight controller to the other Parrot minidrones such as the Mambo or Airborne Cargo, so this PR could easily be adapted to work on those drones.

This PR provides basic support for all the hardware on the drone except for the camera (I don't think it would be hard to get working, but I haven't tried and it is somewhat out of scope for ArduPilot). The ultrasonic sensor also still needs some more work to be useful, which I will explain in more detail below.

All the Parrot minidrones are based around the Parrot SIP6 SoC (Parrot's code refers to it as the P6I), which uses an 800MHz ARMv5TEJ ARM926EJ-S CPU, which does not have an FPU. The lack of an FPU somewhat reduces the potential of the drone, as it uses most of the available CPU time performing software floating point operations. There is little CPU time left over to perform other processing, such as optical flow using the vertical camera.

It looks like #9142 ran into the same issue, as it disables many tasks in order to reduce CPU usage. I tried this as well, but found it did not have much of an impact. I had to reduce the IMU sample rate from 1000Hz to 500Hz in order to prevent measurements from being dropped and to allow stable Bluetooth communication. I would be interested to know if there are other ways that I could reduce ArduPilot's CPU usage.

By far the most difficult sensor to get working was the ultrasonic rangefinder. It consists of an unknown ultrasonic pulse generation chip that communicates over SPI, and an audio ADC that records the echo. The recorded waveform then needs to be processed to find the echo and calculate the distance. This is identical to how the Parrot Bebop's rangefinder works, except it uses different interfaces to communicate with the hardware.

There are huge number of parameters than can be adjusted, and it is very frustrating to try to get good results out of the sensor across different conditions. Right now, the sensor gives good readings at some altitudes, but has difficulty switching between modes and sometimes gives spurious results.

### CODE REVIEW

**Comment by lopsided98** [comment]
A few things I forgot to mention:

Here is an example of the echo waveform at a low altitude:
image
The yellow line shows the shape of the threshold for low altitude mode.

I included the commit that fixes the build with musl because I used [Nix](https://nixos.org/nix/)'s `pkgsCross.sheevaplug.pkgsStatic` toolchain, which uses musl.

**Comment by lucasdemarchi** [comment]
> ultrasonic pulse generation chip that communicates over SPI, and an audio ADC that records the echo.

This sounds a lot like the bebop. I'd bet it's the same thing, just moving from IIO to a device-specific-driver with its ioctls.

**Comment by lopsided98** [comment]
Yes, my driver started out as a copy of the Bebop driver. There are definitely some differences: the RS seems to have a lower resolution ADC and the Bebop's threshold curve and pulse patterns do not work well for it (even if the thresholds are scaled down by a factor of 4).

The original flight software produces much louder audible "chirps", so it seems to be using more pulses and/or a different pattern. I tried using more pulses, but I couldn't get it to work well.

**Comment by patrickelectric** [comment]
@lopsided98 I just saw your PR now, I did a couple of corrections for musl in #14761 and it appears to be closer to what you come up in 0815a32.

**Comment by tridge** [comment]
@lucasdemarchi can you decide if we continue with this PR? It is very old and is the vehicle still sold? Do we want to carry this support fwd?
@lopsided98 are you still using this?

**Comment by lucasdemarchi** [comment]
Unless we have some changes done here, no. Also this has several conflicts now. It's up to @lopsided98  to update this PR or create another one.

**Comment by lopsided98** [comment]
I'm haven't done anything with it recently. It's not really all that practical due to the lack of an FPU.

**Pull request closed without merging**
