### PR TITLE
Copter: Added feature to change the angular velocity of circle mode

### PR DESCRIPTION
**Pull request by jmachuca77**
Rebased on Master, tested on SITL

### CODE REVIEW

**Comment by jmachuca77** [comment]
implements part #386

**Comment by rmackay9** [comment]
@jmachuca77, do you have any testing evidence that this works?  Sorry, but otherwise I need to spend a fair bit of time testing it myself to be sure it works..

**Comment by jmachuca77** [comment]
Understood, what sort of evidence do you need? I tested it in SITL, took off, put the copter in circle mode. It started circling, then modified rc 1 to 1000, and watched speed increase gradually, then rc 1 to 2000, speed slowed down and then switched directions, and kept increasing until rc 1 is back to 1500. I can test fly it but not until the weekend.

**Comment by jmachuca77** [comment]
screen shot 2018-07-18 at 11 14 45 am

This graph shows how this change works.

**Comment by jmachuca77** [comment]
Withdrawing since it seems no one is interested in merging this

**Comment by rmackay9** [comment]
@jmachuca77, it's hard for us to get through all the existing PRs.  We all suffer from not getting enough reviews.  The best way to escalate a change is to tag it with the DevCallTopic and then show up at the weekly meetings over and over until it's merged.

**Pull request closed without merging**
