### PR TITLE
AP_BLHeli: fixed critical errors caused by BLHeli code

### LINKED ISSUE #12542: Copter: significant issues with BLHeli on 4.0
I am seeing a number of issues with BLHeli support in 4.0

### Bug report

 - If I enable BLHeli Passthrough and connect with BLHeli, after I disconnect I start seeing the error " internal error (0x8000)"
- If I enable ESC testing I get (*UPDATE: caused by auto telemetry*)
```
APM: ESC: Running test on channel 0
APM: ESC: BL_ConnectEx 0/4 at 0
APM: Initialising APM
APM: ESC: BL_ReadBuf 8 -> 9
APM: ESC: Interface type imARM_BLB
APM: ESC: BL_SendCMDSetAddress 0x7C00
APM: ESC: BL_ReadBuf 256 -> 259
APM: ESC: BL_SendCMDSetAddress 0xEB00
APM: ESC: BL_ReadBuf 16 -> 19
APM: ESC: Prot 5 Good 151338 Bad 0 0 0 0 x0

APM: ESC: Test PASSED
Critical failure
```
 - If I enable ESC telemetry I lose logging (*UPDATE: caused by DMA on the RX pin*)

If I had to guess I would say the BLHeli support is pegging the CPU somehow

**Version**
4.0
BLHeli version 32.7 with auto telemetry enabled (I'll try switching this off next)

**Platform**
[  ] All
[  ] AntennaTracker
[X ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Quad 3"

**Hardware type**
KakuteF7 Mini

**Logs**

### PR DESCRIPTION
**Pull request by tridge**
fixes #12542

### CODE REVIEW

**Comment by andyp1per** [comment]
So all just a timing issue!

**Comment by vierfuffzig** [comment]
@tridge i don't get the critical error message anymore, but on doing a BLH test on copter still makes the EKF unhappy and reset, plus BLH_DEBUG doesn't seem to work on copter. don't know if related, but these features do work on plane without known issues.

**Comment by tridge** [comment]
@vierfuffzig the EKF getting unhappy is expected as it doesn't like pauses
BLH_DEBUG should work, I'll need to look at that

**Comment by rmackay9** [comment]
@tridge, I'm thinking about releasing Copter-4.0.0-rc2 for beta testing.  Shall we merge this one and then deal with the EKF unhappiness as a follow-up PR at some point?

**Comment by tridge** [comment]
@rmackay9 yes

**Pull request merged**
