### PR TITLE
Change sensor health check to prevent false positive

### PR DESCRIPTION
**Pull request by floaledm**
Corresponds to this update in Mission Planner: https://github.com/ArduPilot/MissionPlanner/commit/1b91ae21e240f20739dfeaa88172961338838621

### CODE REVIEW

**Comment by magicrub** [comment]
are you sure it's supposed to be & instead of &&?

**Comment by floaledm** [comment]
Each control_sensors_vars is a uint32 bitfield so bitwise operators seem appropriate... By contrast, in Mission Planner, the way I understand it is that the operation is done on the individual bits, so there it's the logical AND that's used on booleans...

**Comment by floaledm** [comment]
I saw you reassigned to yourself (and by the way, thanks again for all your time helping out!). Should I not assign tridge to those pull requests? If not, should I assign anyone? He had asked us to assign him to our pull requests during one of the dev calls...

**Comment by magicrub** [comment]
assigning him is fine. I was just helping out.

**Comment by magicrub** [comment]
merged, thanks!

**Pull request merged**
