### PR TITLE
AP_GPS Prevent using uninitialized variables

### PR DESCRIPTION
**Pull request by amilcarlucas**

### CODE REVIEW

**Comment by EShamaev** [comment]
I thought that all new data is initialized to zero due to this overloaded new method. Is this correct?

**Comment by amilcarlucas** [comment]
I do not know, but I did the PR just in case.

**Comment by rmackay9** [comment]
We initialise all static variables to zero but not the dynamic ones I think.  My understanding was that the curly braces initialise everything to zero so I don't think this change is required.

**Comment by tridge** [comment]
the overload of new only works when you allocate dynamically, so it doesn't apply here
but the patch also does nothing, as C++11 initialisation with {} already guarantees zero, and works for all data types, not just scalars. So the patch is unnecessary. I'll close the PR

**Pull request closed without merging**
