### PR TITLE
hwdef: remove MatekL431-Periph

### PR DESCRIPTION
**Pull request by peterbarker**
this was a kitchen-sink AP_Periph build.  We're moving away from these.

This board does not currently build.  We could make it build, but it will die again and again.

### CODE REVIEW

**Comment by tpwrules** [comment]
I will miss it dearly (and had gotten it to build) 😭

Why is a speedybee change mixed in?

**Comment by IamPete1** [comment]
That is for this board:
https://www.mateksys.com/?portfolio=can-l431#tab-id-1

This build is recommended on there page?

I have used these a lot. Typically as a base with extra stuff added on, relay temp sensors ect. 

I think we should fix it rather than removing. Maybe remove GPS, I think remote GPS via a external node is not common.

**Comment by andyp1per** [comment]
> Maybe remove GPS, I think remote GPS via a external node is not common.

Yes, agreed

**Comment by tpwrules** [comment]
I looked and it does seem GPS changes are what pushed it over the edge. Can we just remove some of the rarer GPS types? It does have a GPS plug and a GPS is a suggested application. But maybe we could push users to the GPS-specific build for that.

**Comment by tpwrules** [comment]
https://github.com/ArduPilot/ardupilot/pull/27685 will bring this board back from the dead without any hwdef changes.

**Comment by joshanne** [comment]
+1 for keeping this build around. As Pete mentioned, that board is a kitchen sink board. I tend to rely on the base hwdef to customise this board.

**Comment by Ryanf55** [comment]
You can drop GSOF from periph on this board as long as we still check GSOF on Periph.

**Comment by peterbarker** [comment]
OK, obviously a lot of love for the MatekL431-Periph build.  Lesson learnt :-)

**Pull request closed without merging**
