### PR TITLE
Frsky FPort2 fixes

### PR DESCRIPTION
**Pull request by yaapu**
fixed 24ch support but had to disable telemetry
fixed 16ch telemetry (status text corruption)

added a test for 24ch fport2

Tested on Archer M+ (FW-Archer-2.1.5) + Taranis X9D 2019 Plus (FW-X9DP2019-ISRM-v2.1.0)

### CODE REVIEW

**Comment by yaapu** [comment]
@tridge would be nice if you could test this as well, thanks

**Comment by kniuk** [comment]
Does this also affect FPort v1 ?
I wonder if this will solve my issues.
I am getting critical messages "no RC receiver" during arming followed by endless beeping. It happens every second arm or so. Disarming and arming again usually fixes it.
Also Yaapu LUA GCS script for Horus (T16 in my case) has a low chance of succeeding with changing params (1 in 10 tries or even lower) I am using Matek F765Wing, R9mm Rx and Plane firmware 4.10dev from 23 November

**Comment by yaapu** [comment]
@kniuk no this has nothing to do with your fport issue, fport2 is a totally different protocol.
For support you can either open an issue on fport or ask on discuss servers. Since many have fport working it might be an issue specific to your setup.

**Comment by tridge** [comment]
@yaapu I tested and it works well, thanks!

**Review by tridge — APPROVED** [review]

**Pull request merged**
