### PR TITLE
Copter: use iterators in parameter conversion

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by peterbarker** [comment]
This is an old branch rebased.

I can't recall if I tested going across an upgrade, so needs testing there again.

**Comment by rmackay9** [comment]
I can't say I'm a fan.  For me, because I'm not very familiar with "auto" I find this harder to understand what's going on.

**Review by amilcarlucas — APPROVED** [review]

**Review by khancyr — APPROVED** [review]
Looks good, but could you do a size check ? Sometime the range based loop are fater

**Review by tridge — APPROVED** [review]
i like it, but up to Randy

**Comment by tridge** [comment]
> I can't say I'm a fan. For me, because I'm not very familiar with "auto" I find this harder to understand what's going on.

I've starting to use auto a lot. Now I'm used to it I find it very nice. The iterators are nice as they remove a pointless integer counter

**Comment by rmackay9** [comment]
I don't think I'll merge it actually.  We don't have other code like this .. sorry!

**Comment by tridge** [comment]
@rmackay9 we do have code like that. Look at this PR:
https://github.com/ArduPilot/ardupilot/pull/16205
moving to the iterator fixed a bug

**Comment by rmackay9** [comment]
ok, merged thanks.

**Pull request merged**
