### PR TITLE
Fix for NAV_LOITER_TO_ALT -- now verifies heading when param 1 is set nonzero

### PR DESCRIPTION
**Pull request by mday299**
NAV_LOITER_TO_ALT should verify that the aircraft is heading towards the next waypoint when param 1 of the mavlink message is not zero.  This patch fixes a bug where that was not happening.

### CODE REVIEW

**Comment by magicrub** [comment]
I think you've made a mistake, how did you test this?

Your PR title and description is claiming to fix a problem which is enforced for all loiter types without mission param via the line directly under your code change "result = verify_loiter_heading()".

However, your submitted code only tells the system you've instantly already orbited a little but a non-zero orbit degree count is checked just 3 lines above so your code change has no effect.

What am I missing?

**Comment by mday299** [comment]
@magicrub This one is a bit tough to understand and to explain.  I'll attach an example to illustrate and then attempt to explain.

The expected behavior in the attached mission is for the plane to wait to leave loiter in waypoint 2 until the plane is heading towards waypoint 3 (due to the 1 setting on param 1 of waypoint 2).  This doesn't happen in master.

Looks like what's happening is rooted in commands_logic.cpp, verify_loiter_heading_method:

```
if (labs(heading_err_cd) <= 1000  ||
            loiter.sum_cd > loiter.total_cd) {

```
So the check for the heading requires that we also have a number of times loitered checked at the same time (to ensure we don't loiter forever if we never happen to get a "YES, we're heading in the right direction result").  

Hope that makes sense.  Happy to discuss further.


[loiter_to_alt_example.wp.zip](https://github.com/ArduPilot/ardupilot/files/669428/loiter_to_alt_example.wp.zip)

**Comment by mday299** [comment]
To answer your question about testing -- I used the attached example and NAV_LOITER_TO_ALT works (again -- it used to work a long time ago) for my branch I'm requested to be pulled.

**Comment by magicrub** [comment]
Sorry for the slow responses. I've been traveling and now it is Xmas. I definitely plan on testing and fixing this in the next couple days. I have a feeling the fix will go down in the verify loiter exit instead, we'llll see.

**Comment by magicrub** [comment]
I'm testing this with the first param as 1 or zero, same effect - loiter waits to be lined up before exit. Your code is change is redundant, this feature is enforced for all loiter types at all times. The P1 label on Mission planner should be removed, has no effect (always treated as 1)

**Comment by magicrub** [comment]
This feature works for me without this PR so I'm closing this. However, the label in MissionPlanner is still there implying LOITER_TO_ALT p1=1 is needed with this code but about a year ago I changed it so this is now always enforced (always treated as 1). I'll talk to @mday299 offline further

**Comment by magicrub** [comment]
Here's the PR to move the "Heading req" label for the loiter commands: https://github.com/ArduPilot/MissionPlanner/pull/1448

**Pull request closed without merging**
