### PR TITLE
geotag.sh - an advanced geotagging tool.

### PR DESCRIPTION
**Pull request by AndKe**
It can do all, tag by time, with offset, by CAM messages, detect and
help correct problems, and process multiple logs(flights) at once.
Initial commit. I've used this tool for years.

### CODE REVIEW

**Comment by peterbarker** [comment]
Yowsers.  That's definitely a shell script.

I'm hesitant to add this without documentation or regression tests.  Regression tests  because this is the sort of thing people suddenly think "I can use X to do this", and discover it's bitrotted a year ago.  Documentation because without that nobody will know about it!  Something on the Wiki is what I'm thinking there.

**Comment by AndKe** [comment]
It's current :)  works with current, and older arduplane/copter, we use it often. - had it for some 5 years i guess, it evolved now and then.
As for documentation; most is described in help, but yes, some more tips and tricks could/should be described.  It's really useful, and can help find out/correct crazy bad datasets which we sometime see in forums as "MP wont geotag this" 
Further documentation or code beautifying is not done as it was an internal tool, so publishing it is kind of hen/egg problem :)  - unless people get to use it, it's no point of making more docs.  If you make a wiki page, so it'll be published later,  I'll surely take some time to describe it there.  :)

**Comment by peterbarker** [comment]
I'm going to merge this on the basis that it's not going to kill anything, and despite my reservations.  Let's see if people use it.

**Comment by AndKe** [comment]
how should I proceed to create a page with some documentation/extra info ?
, or can you create the page, and I'll edit it before publishing ?

**Pull request merged**
