### PR TITLE
Update GPS_AUTO_test.cpp

### PR DESCRIPTION
**Pull request by sona-19**

### CODE REVIEW

**Comment by OXINARF** [comment]
Hi @sona-19, thank you for your first contribution! Have you read our contribution guidelines (http://http://ardupilot.org/dev/docs/submitting-patches-back-to-master.html)? Specifically the part about commit message format.

**Comment by sona-19** [comment]
> Hi @sona-19, thank you for your first contribution! Have you read our contribution guidelines (http://http://ardupilot.org/dev/docs/submitting-patches-back-to-master.html)? Specifically the part about commit message format.

Hi
Sorry, I missed that part.
Should I create another Pull request?

**Comment by khancyr** [comment]
@sona-19 hello, no you can just for push on this pr !

**Comment by khancyr** [comment]
@sona-19 ping !

**Comment by WickedShell** [comment]
Closing as abandoned, and it's just adding a comment.

**Pull request closed without merging**
