### PR TITLE
Global: Aggregate the same definitions.

### PR DESCRIPTION
**Pull request by muramura**
LOCATION_SCALING_FACTOR, LOCATION_SCALING_FACTOR_INV is defined in location.cpp of AP_Math and Location.cpp of AP_Common.
Therefore,
It is defined in AP_Common.h.

### CODE REVIEW

**Comment by OXINARF** [comment]
I like to have only one place to these definitions, but it should be at location.h inside the AP_Math library. The Location.cpp already includes AP_Math (through the Location.h).

**Comment by muramura** [comment]
@OXINARF Comment Thanks.
I understand.
location.h inside the AP_Math library. The Location.cpp already includes AP_Math (through the Location.h).
Therefore,
Move the definition from AP_Common.h to location.h.

**Comment by OXINARF** [comment]
@muramura One skill you need to acquire is how to squash and force push commits. This PR is a good example where that should be done - there's no need to have two commits for this. Feel free to talk to us in Gitter if you ever need help.
For this one, I'll let whoever merges it to do it.

**Comment by muramura** [comment]
@OXINARF comment thanks.
I want to learn how to commit and push next in a pushed environment.
Gitter, I am unfamiliar.
Nice to meet you.
I will take action at Midnight time in Japan.

**Comment by rmackay9** [comment]
For squashing commits I use **_git rebase -i "HEAD~5"_**.  The I change the first column to "s" for each commit that I want to squash into the one above.

**Comment by muramura** [comment]
@rmackay9 Comment thanks.
I will do it in the way of this message.
thank you.

**Comment by muramura** [comment]
@OXINARF
Based on the advice of @rmackay9 , pushed together.

**Comment by OXINARF** [comment]
@muramura Great! It looks like an empty line change was left in AP_Common.h, if you want to practice more you can get try to amend the commit and remove that change - but only if you want, that's not needed!

**Comment by muramura** [comment]
@OXINARF Comment Thanks.
if you want to practice more you can get try to amend the commit and remove that change 

I think.
I can restore the AP_Common.h file using the following procedure (checked in the Commit file list).
From now on, make PR file compact.
Thank you for giving me a chance.
＝＝＝
> git checkout 152edf7 libraries/AP_Common/AP_Common.h
> git commit
> git log --oneline
57a6ac8 AP_Common.h discard
b8105c7 Global: Aggregate the same definitions.
:
rebase process...

**Comment by OXINARF** [comment]
@muramura With those commands you would have two commits which you would then need to squash. A better method would be that your commit line was something like `git commit --amend`. That replaces the last commit by merging it with the current changes you have.

Anyway, Lucas already merged this so it is all good!

**Pull request merged**
