### PR TITLE
AP_Scripting: allow optional param name in Parameter userdata

### PR DESCRIPTION
**Pull request by IamPete1**
Adds optional param name in `Parameter()`

So:
```
local user_param = Parameter('SCR_USER1')
```
is equivalent to:
```
local user_param = Parameter()
assert(user_param:init('SCR_USER1'), 'No parameter: SCR_USER1')
```
Old method still works, and is useful if none fatal init is needed.

This also changes all the examples to the new method, this does mean they will no longer work on stable (of course the stable branch examples will still work). We could leave examples as they are and just use the new method going forward.

### CODE REVIEW

**Comment by IamPete1** [comment]
I have not tested all the changed examples still work. Except the param set/get example which is included in the first commit. Second commit is optional.

**Comment by tridge** [comment]
I really like this, much nicer.
we do need to test at least the applets like VTOL-quicktune.lua. Changes look fine, but should test

**Comment by IamPete1** [comment]
I have tested the three applets this changes.

**Comment by timtuxworth** [comment]
OMG this is absolutely brilliant! Thank you!

**Comment by IamPete1** [comment]
@tridge How would you feel about also making `param:add_table` and `param:add_param` fatal? We don't have single user of those not in a assert in the examples/applets. If they needed to be none fatal for some reason they could be pcalled-ed.

**Review by tridge — CHANGES_REQUESTED** [review]
i think VTOL-quicktune should use old logging syntax and old param syntax

**Comment by IamPete1** [comment]
Re-based, dropped the applet changes, moved ship landing to applets and then reverted the logger changes from last week on all the applets.

**Review by tridge — APPROVED** [review]

**Pull request merged**
