### PR TITLE
AP_HAL_ChibiOS: MatekF405-Wing really needs to be HAL_MINIMIZE_FEATURES

### PR DESCRIPTION
**Pull request by andyp1per**
Please, please can we do this to unbreak all of CI!

### CODE REVIEW

**Comment by tridge** [comment]
i'll be submitting a PR tomorrow that should shrink matekf405-wing quite a lot by disabling SMBUS battery backends

**Comment by peterbarker** [comment]
@andyp1per I believe I unbroke CI yesterday with a series of commits that reduced code size overall.

It only *just* saved us; a margin of kilobytes is really wanted.

Minimizing features is an awfully big hammer to wield, and we don't really want to field bug reports from people running MatekF405-Wing who are using an older version because they're using a feature we nuked in later versions.

OTOH - piecemeal disabling of features may also lead to support issues :-/

**Comment by auturgy** [comment]
There’s some surprising stuff behind HAL_MINIMIZE. We really need to look at it a lot deeper to get it right: I don’t think applying it to another board before hand would serve us well (as annoying as the limitation is).

Regards,

James

**Comment by andyp1per** [comment]
I just rebased on the latest master and Matek Wing is still overflowing by 436 bytes even though my feature is disabled. This seems way to fragile. Any other obvious things that could be switched off to make this board less picky? Note that building locally does not overflow for me. What version of gcc are we using for travis?

**Comment by peterbarker** [comment]
On Fri, 6 Dec 2019, Andy Piper wrote:

> I just rebased on the latest master and Matek Wing is still overflowing by 436 bytes even though my feature is disabled. This seems way to fragile. Any
> other obvious things that could be switched off to make this board less picky? Note that building locally does not overflow for me. What version of gcc
> are we using for travis?

Link to branch?

**Comment by andyp1per** [comment]
@peterbarker https://github.com/ArduPilot/ardupilot/pull/11886

**Comment by amilcarlucas** [comment]
Would #12997 help solve this one? It will save a lot of memory.

**Comment by andyp1per** [comment]
Moving to gcc 6.3.1 makes this irrelevant. Closing

**Pull request closed without merging**
