### PR TITLE
Copter: advance towards proximity obstacles and maintain distance

### PR DESCRIPTION
**Pull request by IamPete1**
This is a rebase of some work I did based on my original active avoidance PR. I have reworked it on top of the velocity based method from @rishabsingh3003 

A companion to https://github.com/ArduPilot/ardupilot/pull/14855 for inspection.

This adds a switch to enable and disable, if enabled the vehicle should move towards a obstacles once it is within 1.5 x the avoidance margin, it will then hold at the margin distance and advance or retreat with it. Pilot inputs should work as normal.

I need to test this rebase in AirSim and ideally also a real vehicle.

### CODE REVIEW

**Comment by IamPete1** [comment]
@rishabsingh3003 another one for you to have a look at. 

I think the dead-zone added here should be a improvement to the current avoidance. It allows you to stay in the more intuitive to control velocity limiting when bumping against at proximity limit. This matters for where your trying to prosperously fly along a obstacles such as a wall. Of course for backing away from obstacles moving towards the copter it has less effect. 

Currently its hard coded to 25cm either way, maybe we should add a pram, or use 10% of the set margin.

**Comment by rmackay9** [comment]
It would be good if @rishabsingh3003 could have a peek at this..

**Review by rishabsingh3003 — COMMENTED** [review]
Sorry I took this much time to review this! 
The changes are simple, and I can see why it works. Hijacking the backaway code for this is smart!
But at the same time I am a little worried about the avoidance library having the power to advance towards obstacles...
Back in June, Simple Avoidance only had the capability to reduce Velocity in one direction, never add anything, in any direction.
We stepped back from that, and put in the bacakaway code, which had the power to alter the velocity direction, magnitude and everything, but it was always away from the obstacle.

Now this PR will give the avoidance library more power to come closer to the obstacle, which is another step back to what this library initially wanted to do.. But thats just my personal opnion.  

If @rmackay9 feels this is a good change, i'll be happy to test it out on a real vehicle when I go out to test some of my related work...

Another issue is, this will heavily conflict with my PR here: https://github.com/ArduPilot/ardupilot/pull/15553
But, the changes to avoidnace lib are actually pretty easy, and can be easily encorporated.

**Comment by IamPete1** [comment]
@rishabsingh3003 thanks for taking a look, I think even if we decide the advancing towards obstacles is better done some other way the dead zone added here should make normal avoidance 'feel' better to the pilot. The dead zone will make the switch from velocity limiting to back way avoidance a lot less common.

**Comment by IamPete1** [comment]
@rishabsingh3003 has been playing with the deadzone stuff, I think was the only reaming useful thing in this PR, rest should be a script.

**Comment by rishabsingh3003** [comment]
Its added in this commit, as part of a larger PR:
https://github.com/ArduPilot/ardupilot/pull/15553/commits/836924e16fee0566e7629b7e175d8d0f753ef6d9
Thanks again!

**Pull request closed without merging**
