### PR TITLE
Plane: prevent bad vtol state and very close QPOS_APPROACH

### PR DESCRIPTION
**Pull request by tridge**
master version of this PR #19053

### CODE REVIEW

**Comment by robustini** [comment]
@tridge @IamPete1 I think you need to do something else, here the SITL crashes.

[00000001.ZIP](https://github.com/ArduPilot/ardupilot/files/7453444/00000001.ZIP)

immagine

**Comment by IamPete1** [comment]
I cannot replicate on master.

**Comment by robustini** [comment]
> 
> 
> I cannot replicate on master.

Try with Q_ANGLE_MAX to 9000.

**Comment by IamPete1** [comment]
Yep, that will do it, but that is unrelated to this PR. You get a divide by zero in the pos controller init IRRC. Copter will crash too if you set angle max to 9000.

**Comment by robustini** [comment]
> 
> 
> Yep, that will do it, but that is unrelated to this PR. You get a divide by zero in the pos controller init IRRC. Copter will crash too if you set angle max to 9000.

Well, it is not related but it is still to be solved.
I don't know if there are any open issues about that.

**Pull request merged**
