### PR TITLE
Added Gazebo SITL IRLock and Gazebo Zephyr Elevon simulations

### PR DESCRIPTION
**Pull request by hsu**
you'll need

[gazebo_models aero_testing_john branch](https://bitbucket.org/osrf/gazebo_models/pull-requests/177/aerodynamics-models/activity)

[gazebo aero_apm_irlock_john branch](https://bitbucket.org/osrf/gazebo/branches/compare/aero_apm_irlock_john%0Ddefault#diff)

please also see [intermediate pr](https://bitbucket.org/osrf/gazebo/pull-requests/2264/aerodynamic-updates/activity)

[instructions on running this simulation](https://bitbucket.org/osrf/gazebo/src/31cb2d9da593fe0e8f89848c71ff956d64b34e6c/worlds/iris_irlock_demo.world?at=aero_apm_irlock_john&fileviewer=file-view-default#iris_irlock_demo.world-5)

end result - https://youtu.be/sgEkG8iekLY

### CODE REVIEW

**Comment by hsu** [comment]
https://youtu.be/sgEkG8iekLY

**Comment by squilter** [comment]
Nice work! ardupilot/ardupilot_wiki#480 has instructions for setting up the simulation in Gazebo (minus the new IRLock part). Also, could you clean up the history a bit? [This](https://github.com/ArduPilot/ardupilot/commits/master) is how it usually looks.

**Comment by magicrub** [comment]
Thanks Sebastian for the history mention. Yes, please clean up the history
and remove the merges, they are not allowed.

**Comment by hsu** [comment]
thanks, will do a rebase and force push.

**Comment by hsu** [comment]
history cleaned up.

**Comment by hsu** [comment]
@tfoote @gerkey

**Comment by hsu** [comment]
major change as sim_vehicles.sh has been removed, replaced by sim_vehicles.py. I added frames "GazeboIris" and "GazeboZephyr"

**Comment by squilter** [comment]
@hsu I am still very excited about getting this PR in, but the history is still not clean enough. Take a look at some [recently closed pull requests](https://github.com/ArduPilot/ardupilot/pulls?q=is%3Apr+is%3Aclosed) and the [contributing doc](http://ardupilot.org/dev/docs/submitting-patches-back-to-master.html). The PR should also be rebased on master, not on 3-4

**Comment by tridge** [comment]
@hsu, I'm also keen to see this get in. If you are having trouble with the git cleanup then let me know and I'll put together a fixed branch.

**Comment by hsu** [comment]
@tridge @squilter thanks for the tips and help. I am working on my git rebase and squash skills :)  Will try to clean up history some more today.

**Comment by hsu** [comment]
Meanwhile, got a question about testing with the same interface for ArduPlane SITL. In my example, on ArduPlane startup, I always get a blip of throttle input (input.servos[3] = 0), which leads to a brief motor spin up to 50% given that I assumed that throttle input ranges [-1, 1]. Almost immediately after a second or less, input.servos[3] goes back down to -1 as expected. Is this an expected behavior or do I have improper setup in my parameters (see added gazebo-elevon.parm)? Please excuse my ArduPlane novice-ness. Thanks in advance for any pointers.

**Comment by hsu** [comment]
I'll start from scratch and submit a new pr with clean history.

**Pull request closed without merging**
