### PR TITLE
Spell in comments

### PR DESCRIPTION
**Pull request by amilcarlucas**

### CODE REVIEW

**Comment by magicrub** [comment]
These all look good to me. I'm sure there will be a fight between meter vs metre so we'd better merge it in before anyone complains :)

**Comment by amilcarlucas** [comment]
Thanks Tom.

**Comment by khancyr** [comment]
it is meter in english no ? ( I am french so in french it is metre but I was teach that in english it is meter)

**Comment by magicrub** [comment]
English is meter.

**Comment by peterbarker** [comment]
On Fri, 6 Jan 2017, Tom Pittenger wrote:

> English is meter.

No.  English is "metre" 
(https://en.oxforddictionaries.com/definition/metre)

American English is "meter" 
(https://www.merriam-webster.com/dictionary/metre), and that's what we use 
in ArduPilot (based on my previous experience).

**Comment by magicrub** [comment]
Who pays attention to English English....

**Pull request merged**
