### PR TITLE
fix: Missing comma

### PR DESCRIPTION
**Pull request by mrshu**
* Add missing comma in `sim_vehicle.py`.

### CODE REVIEW

**Comment by rmackay9** [comment]
@mrshu,

Thanks for this.  Could you rename the commit to, "Tools: add missing comma to sim_vehicle.py" or something similar?  Normally we prefix the commit with the subsytem to allow easier backporting

**Comment by mrshu** [comment]
@rmackay9 sure thing, I just did that!

**Review by peterbarker — APPROVED** [review]
LGTM - thanks!

**Comment by rmackay9** [comment]
Merged, thanks!

**Pull request merged**
