### PR TITLE
AP_Frsky_Telem: sport/fport bidirectional telemetry support

### PR DESCRIPTION
**Pull request by yaapu**
Note: original PR https://github.com/ArduPilot/ardupilot/pull/12200 was getting too long, this is part 2.

This adds two way mavlink style (mavlite) messages on top of sport/fport bidirectional telemetry.

A brief note:

it is not an alternative to a fast and light downlink protocol but rather a way to interact with the FC from LUA
the intention is to fill the "gaps" of the current passtrough protocol
Sport packets are the "transport" and mavlink like messages, that I called mavlite, are transferred in chunks of 6 bytes.
Maximum payload is 256 bytes.

It handles the following messages:

- PARAM_REQUEST_READ
- PARAM_VALUE
- PARAM_SET
- COMMAND_LONG (fence, ground cal, reboot, mode)

The companion LUA GCS script is [here](https://github.com/yaapu/FrskyLuaGCS)
Blog on ardupilot discuss is [here](https://discuss.ardupilot.org/t/frsky-bidirectional-telemetry-implementation/46513)

Related PR:
https://github.com/ArduPilot/ardupilot/pull/12200

Related issues:
#5725
#4812

### CODE REVIEW

**Comment by Hwurzburg** [comment]
@peterbarker @yaapu tested today: pulled the PR, rebased to master, loaded onto a flying wing...on the ground changed params , rebooted, and recal'd via GCS script...flight tested in normal modes, changed mode via the script while flying, changed a param while flying....all good...maybe needs rebasing here to pass CI...damn copter tests again, no?

**Comment by peterbarker** [comment]
On Tue, 13 Oct 2020, Henry Wurzburg wrote:

> @peterbarker @yaapu tested today: pulled the PR, rebased to master, loaded onto a flying wing...on the ground changed params , rebooted, and recal'd via
> GCS script...flight tested in normal modes, changed mode via the script while flying, changed a param while flying....all good...maybe needs rebasing here
> to pass CI...damn copter tests again, no?

This is a new intermittent test failure which has cropped up.  I've 
created a PR to address.

**Comment by Hwurzburg** [comment]
@peterbarker  should we kick the test again? and put a DEVCALL label on it....time this puppy gets merged,no?

**Comment by peterbarker** [comment]
For DevCall:
 - structure of packing
    - e.g. command-long could be better
 - can only transport 8-bit mavlink message IDs
   -  @yaapu has a desire to keep the mavlite message IDs 1-1 with mavlink message IDs.
 - is it OK to break existing clients if we change the on-wire protocol for e.g. command_long?
   - @Hwurzburg  thinks so...

**Comment by yaapu** [comment]
@peterbarker @Hwurzburg 
A better packed command long is just fine, my objections were only against using custom command IDs.
But I can sure change my mind, my fear is that if we'll ever find a nice way to have full access to incoming/outgoing/routed mavlink messages it would be hard to control gimbals and cameras from OpenTX and would require adding custom code to ardupilot instead of leveraging a transparent passthrough.

**Pull request merged**
