### PR TITLE
GCS_MAVLink: add warnings if older messages used

### PR DESCRIPTION
**Pull request by peterbarker**
Hopefully we can remove the older code in a future release.

### CODE REVIEW

**Comment by amilcarlucas** [comment]
It would be great if these messages where marked as deprecated in the mavlink xml files. Are they?

**Comment by peterbarker** [comment]
> It would be great if these messages where marked as deprecated in the mavlink xml files. Are they?

Yes, they are both marked deprecated

**Comment by peterbarker** [comment]
Tested in SITL:

```
STABILIZE> set wp_use_mission_int 0
STABILIZE> wp load Tools/autotest/Generic_Missions/CMAC-circuit.txt
STABILIZE> Loaded 8 waypoints from Tools/autotest/Generic_Missions/CMAC-circuit.txt
Got MISSION_ACK: TYPE_MISSION: ACCEPTED
AP: got MISSION_ITEM; GCS should send MISSION_ITEM_INT
Loaded 8 waypoint in 0.04s
Sent all 8 waypoints
Got MISSION_ACK: TYPE_MISSION: ACCEPTED
AP: Flight plan received

STABILIZE> wp load Tools/autotest/Generic_Missions/CMAC-circuit.txt
STABILIZE> Loaded 8 waypoints from Tools/autotest/Generic_Missions/CMAC-circuit.txt
Got MISSION_ACK: TYPE_MISSION: ACCEPTED
AP: got MISSION_ITEM; GCS should send MISSION_ITEM_INT
Loaded 8 waypoint in 0.04s
Sent all 8 waypoints
Got MISSION_ACK: TYPE_MISSION: ACCEPTED
AP: Flight plan received

STABILIZE> set wp_use_mission_int 1
STABILIZE> wp load Tools/autotest/Generic_Missions/CMAC-circuit.txt
STABILIZE> Loaded 8 waypoints from Tools/autotest/Generic_Missions/CMAC-circuit.txt
Got MISSION_ACK: TYPE_MISSION: ACCEPTED
Loaded 8 waypoint in 0.04s
Sent all 8 waypoints
Got MISSION_ACK: TYPE_MISSION: ACCEPTED
AP: Flight plan received
Flight battery 100 percent
```

**Review by tridge — APPROVED** [review]
for 4.4.x we could remove the old msg support completely

**Comment by rmackay9** [comment]
To help GCS developers move to the new messages we should fill out this wiki page https://ardupilot.org/dev/docs/mavlink-mission-upload-download.html

**Pull request merged**
