### PR TITLE
Copter: tidy handling of DO_FLIGHT_TERMINATION

### PR DESCRIPTION
**Pull request by muramura**
I found that the processing was interrupted by the same preprocessor.
I found it to finish in the preprocessor.
I reviewed the processing.

### CODE REVIEW

**Comment by peterbarker** [comment]
I think this could be a nice cleanup - 'though I haven't looked at it thoroughly.

Does this fix any actual issue or is it just neater?

**Comment by peterbarker** [comment]
For https://github.com/ArduPilot/ardupilot/issues/13773

**Comment by rmackay9** [comment]
.. and everything needs to be tested and testing evidence provided as well please.  Sorry to be annoying but we've had a number of supposedly NFCs cause real issues.

**Comment by peterbarker** [comment]
I've tested this thoroughly in SITL now, both with-AFS-enabled and without.

It does not change behaviour.

The new code is *much* better than the existing code.

I've adjusted the commit message and fixed an introduced whitespace error.

I suggest we merge this.

**Comment by khancyr** [comment]
Shouldn't we copy this on other vehicles?

**Comment by peterbarker** [comment]
On Sun, 3 Jan 2021, Pierre Kancir wrote:

> Shouldn't we copy this on other vehicles?

There is no equivalent on other vehicles.

**Comment by tridge** [comment]
restarted CI

**Review by rmackay9 — APPROVED** [review]
Looking good, let's merge after it passes CI

**Comment by peterbarker** [comment]
Merged, thanks!

**Pull request merged**
