### PR TITLE
Reduce memory used by DDS client 

### PR DESCRIPTION
**Pull request by srmainwaring**
Remove unused TFMessage variable and reduce size of pre-allocate arrays in XRCE DDS message types.

### Dependencies

Requires upstream change:
- https://github.com/eProsima/Micro-XRCE-DDS-Gen/issues/68
- https://github.com/eProsima/Micro-XRCE-DDS-Gen/pull/74

Which are applied to the ArduPilot forks in:
- https://github.com/ArduPilot/OMG-IDL-Parser/pull/1
- https://github.com/ArduPilot/Micro-XRCE-DDS-Gen/pull/2

### Tasks

- [x] Require a submodule update in this PR before merging.

### Testing

Before

```bash
AP: DDS: ********** DDS message sizes **********
AP: DDS: ardupilot_msgs_srv_ArmMotors_Request:   1
AP: DDS: ardupilot_msgs_srv_ArmMotors_Response:  1
AP: DDS: builtin_interfaces_msg_Time:            8
AP: DDS: geographic_msgs_msg_GeoPoseStamped:     320
AP: DDS: geometry_msgs_msg_PoseStamped:          320
AP: DDS: geometry_msgs_msg_TwistStamped:         312
AP: DDS: sensor_msgs_msg_Joy:                    1072
AP: DDS: sensor_msgs_msg_NavSatFix:              376
AP: DDS: rosgraph_msgs_msg_Clock:                8
AP: DDS: tf2_msgs_msg_TFMessage:                 57608
AP: DDS: AP_DDS_Client:                          119768
AP: DDS: ********** DDS message sizes **********
```

After

```bash
AP: DDS: ********** DDS message sizes **********
AP: DDS: ardupilot_msgs_srv_ArmMotors_Request:   1
AP: DDS: ardupilot_msgs_srv_ArmMotors_Response:  1
AP: DDS: builtin_interfaces_msg_Time:            8
AP: DDS: geographic_msgs_msg_GeoPoseStamped:     320
AP: DDS: geometry_msgs_msg_PoseStamped:          320
AP: DDS: geometry_msgs_msg_TwistStamped:         312
AP: DDS: sensor_msgs_msg_BatteryState:           920
AP: DDS: sensor_msgs_msg_Joy:                    336
AP: DDS: sensor_msgs_msg_NavSatFix:              376
AP: DDS: rosgraph_msgs_msg_Clock:                8
AP: DDS: tf2_msgs_msg_TFMessage:                 4616
AP: DDS: AP_DDS_Client:                          9168
AP: DDS: ********** DDS message sizes **********
```

Run on SITL and on MatekH743 / plane.

### CODE REVIEW

**Review by Ryanf55 — APPROVED** [review]
LGTM. Hopefully upstream merges the dependencies soon with our endorsement. Once that's done, this can go in.

**Comment by tridge** [comment]
Nice memory reduction!

**Comment by Ryanf55** [comment]
Can you squash the commits together?  Each one looks good.

**Comment by srmainwaring** [comment]
> Can you squash the commits together? Each one looks good.

Could do, though I kept them separate on purpose to make it clear what was changing: 1. removal of unused variable, 2. change in upstream dep, and 3. an unrelated bug fix.

**Comment by Ryanf55** [comment]
> > Can you squash the commits together? Each one looks good.
> 
> Could do, though I kept them separate on purpose to make it clear what was changing: 1. removal of unused variable, 2. change in upstream dep, and 3. an unrelated bug fix.
Alright, I'll request a merge in dev call as-is.

**Review by tridge — APPROVED** [review]

**Comment by Ryanf55** [comment]
We agreed in dev call a final test on hardware would be a good idea before merging. The plan is this can be backported to 4.5 with the testing complete. I'll test on CubeRed.

**Comment by srmainwaring** [comment]
> I'll test on Pixhawk 6X with serial.

Ok. I'm running on a MatekH743-WING using `MatekH743-bdshot` with DDS and PPP enabled and it's working well.

**Comment by Ryanf55** [comment]
I think the testing Rhys has done is sufficient. Are we ok to merge this so it can be part of 4.5?

**Pull request merged**
