### PR TITLE
Rover: implement NAV_DELAY (attempt 2)

### PR DESCRIPTION
**Pull request by rmackay9**
This builds upon this existing PR: https://github.com/ArduPilot/ardupilot/pull/11999 but creates a new Auto submode called "Stop" which I think is more robust than trying to use the existing SpeedAndHeading submode which is meant for a very different purpose.

### CODE REVIEW

**Comment by magicrub** [comment]
Your solution doesn't pass the test you proposed on https://github.com/ArduPilot/ardupilot/pull/11999

created a mission with 4 commands
wp1
rtl
nav_delay of 10 sec
wp2
switched the vehicle to auto, let it drive to wp1 and then start rtling
"wp set 3" to move the mission command to command 3 (nav-delay), the vehicle kept driving towards home for 10 seconds and then began driving towards wp2

**Comment by magicrub** [comment]
I've I initially tested this using mission ID 94 (which was wrong) since that was a comment in AP_Mission. Naturally it didn't work. I updated the comment and tested and it works fine. Thanks @rmackay9

**Comment by magicrub** [comment]
closes https://github.com/ArduPilot/ardupilot/issues/8506

**Comment by rmackay9** [comment]
Thanks!

**Pull request merged**
