### PR TITLE
[Quadplane/Tailsitter] Fix transition FW->VTOL in AUTO mode - New parameters VELZ_MAX_UP and VELZ_MAX_DOWN

### PR DESCRIPTION
**Pull request by robustini**
This solves the problem I reported in [#16322](https://github.com/ArduPilot/ardupilot/issues/16322).
Also added the new parameters VELZ_MAX_UP and VELZ_MAX_DOWN instead of VELZ_MAX, very useful since the two speeds normally want to be calibrated differently, uphill there are never problems so you can go fast, while in the descent it is often useful to go slower (as in the Copter).
Tested everything in Realflight successfully, but require review of @IamPete1 and @tridge, certainly there are conflicts that need to be resolved.

### CODE REVIEW

**Review by IamPete1 — CHANGES_REQUESTED** [review]
This needs a re-base and removal of white space and unrelated changed. Then a squash and fixup of the commit messages. After that I think its work splitting into two PRs, one for the addition of the up and down params and the second for the transition changes.

**Comment by robustini** [comment]
100% agree @IamPete1, @rekomerio must provide for this.

**Comment by rekomerio** [comment]
I am a bit of a noob with git features I need to use to achieve this. I will look into this on the weekend

**Comment by IamPete1** [comment]
Maybe we would be better closing this and letting @rekomerio open his own PR when he thinks its ready. @rekomerio Please don't feel pressured into doing anything, obviously if you have time to get to it that's great, if not that is fine too. If you need any git or general AP advice head over over the discord https://discord.gg/YwZE6byy.

**Comment by rekomerio** [comment]
Sorry guys, I've been quite busy this weekend and couldnt do this yet, but it is on my mind, dont worry

**Comment by robustini** [comment]
> 
> 
> Sorry guys, I've been quite busy this weekend and couldnt do this yet, but it is on my mind, dont worry

Take your time for this, nobody is in a hurry.
In the meantime I'm experimenting on PX4 for comparison.

**Pull request closed without merging**
