### PR TITLE
OpticalFlow: BBBmini remove onboard OpticalFlow support

### PR DESCRIPTION
**Pull request by mirkix**
After some discussion with BBBmini users I decide to skip the onboard (USB Webcam) OpticalFlow support for BBBmini. 

The reason to skip the support:
* USB Webcam data transfer rise CPU load >35%
* onboard OpticalFlow seems not to work now
* OpticalFlow sensor is hardcoded can can not be changed by parameter
* most BBBmini users are using PX4FLOW

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
LGTM. I also think we should leave only bebop there, to make it easier to refactor this for proper opticalflow integration

**Comment by lucasdemarchi** [comment]
Let's wait for CI and then we can merge.

**Comment by lucasdemarchi** [comment]
@OXINARF 
```
The job exceeded the maximum time limit for jobs, and has been terminated.
```

Are we having problems with travis?

**Comment by OXINARF** [comment]
@lucasdemarchi Kind of, they have now limited jobs to a maximum of 50 minutes (it was documented but not applied in practice). When a PR has more changes the ccache doesn't help it pass, but relaunching has, so far, always make it pass. I have relaunched this one, let me know if it doesn't pass.

**Comment by lucasdemarchi** [comment]
Applied, thanks.

**Pull request closed without merging**
