### PR TITLE
Copter: Changed if statements to switch statement.

### PR DESCRIPTION
**Pull request by muramura**
Multiple modes are judged by if statement.
Replace with switch statement.
Mode becomes easy to find.

### CODE REVIEW

**Comment by muramura** [comment]
> make px4-clean
> make px4-v3
Compiling and building are successful.
===
LINK:    /home/murata/work/ardupilot/modules/PX4Firmware/Build/px4fmu-v3_APM.build/firmware.elf
BIN:     /home/murata/work/ardupilot/modules/PX4Firmware/Build/px4fmu-v3_APM.build/firmware.bin
%% Generating /home/murata/work/ardupilot/modules/PX4Firmware/Build/px4fmu-v3_APM.build/firmware.px4
make[2]: Leaving directory '/home/murata/work/ardupilot/modules/PX4Firmware/Build/px4fmu-v3_APM.build'
%% Copying /home/murata/work/ardupilot/modules/PX4Firmware/Images/px4fmu-v3_APM.px4
make[1]: Leaving directory '/home/murata/work/ardupilot'
   text	   data	    bss	    dec	    hex	filename
1035996	   2832	  57700	1096528	 10bb50	/home/murata/work/ardupilot/modules/PX4Firmware/Build/px4fmu-v3_APM.build/firmware.elf
PX4 ArduCopter Firmware is in ArduCopter-v3.px4
murata@ubuntu:~/work/ardupilot/ArduCopter$

**Comment by muramura** [comment]
@magicrub Thank you Comment.
Changed missing.
to correct.

**Comment by OXINARF** [comment]
This is more unreadable to me. @rmackay9 what's your opinion?

**Comment by rmackay9** [comment]
I kind of like the switch statements so I'm going to merge this, thanks for doing the reviews and catching the issues!

**Comment by muramura** [comment]
@OXINARF , @rmackay9 san, Check and Comments thank you.
I thought that automatic testing was wrong.
I noticed the mistake in the check comment by @magicrub.
Thank you very much.

**Pull request merged**
