### PR TITLE
Copter: To remove a return after the Switch statement.

### PR DESCRIPTION
**Pull request by muramura**
To return in the default of a switch statement.
In this return, the next process is meaningless.

Therefore,

To change the return to break.

### CODE REVIEW

**Comment by OXINARF** [comment]
I understand your point, but I think having the default return false is more appropriate. Maybe what should be removed is the last line returning false (I'm just not sure if the compiler will issue a warning or not).

**Comment by muramura** [comment]
@OXINARF Comments Thanks.
This method is a switch statement only.
return has been completed in this switch statement.

Therefore,
To remove a return after the Switch statement.
===
Checked.
 To remove a return after the Switch statement.
And
make clean
make px4-v2 1> bbb.log 2>&1

Result
Only The message of the compiled results
CXX:     /home/murata/work/ardupilot/ArduCopter/flight_mode.cpp

**Comment by khancyr** [comment]
@OXINARF yes it trigger an unreachable code warning with some compiler or tools. 
This problem is recurrent in many place. Sometimes break are use, sometimes only return are use, and sometimes both are used. Could be useful to have a guideline about that!

**Comment by OXINARF** [comment]
@khancyr Do you know what compiler still throws that warning? Our GCC 4.9 versions aren't throwing a warning.

**Comment by khancyr** [comment]
@oxinarf I am not sure that g++ >5.4 trigger a warning. I got a warning when using Clion Ide (sure), and cpplint. I will check tomorrow with g++ 5.4 & 6.x but I am not sure that current flags will trigger a warning.

**Comment by magicrub** [comment]
unreachable code should throw a warning. If we are masking that on g++ right now then we should fix that. It is very useful to detect warnings in Travis when compiling for all the platforms.

**Comment by OXINARF** [comment]
@magicrub I have to confess I didn't read the warning @khancyr was referring to was an unreachable code. Anyway, Travis isn't showing any warning, either with current code or with this PR.

@khancyr What I was saying about warning was if removing the last if (like @muramura has done now) would throw a warning. Is that what you are talking about? I don't see how it could throw an unreachable code warning in that case.

**Comment by muramura** [comment]
@magicrub, @OXINARF Comments Thanks.
 **cppcheck** tool, can not be detected for this invalid return.
But,
This **cppcheck** tool detects an invalid break that can not be detected in the GCC.
ex. ArduCopter/events.cpp and ArduCopter/control_auto.cpp
this message is,
[ArduCopter/control_auto.cpp:583]: (style) Consecutive return, break, continue, goto or throw statements are unnecessary.
＝＝＝
I from the file of **control_auto.cpp** and **events.cpp**, to remove this multiple break.
This source to new PR.

**Comment by rmackay9** [comment]
Merged, thanks!

**Pull request closed without merging**
