### PR TITLE
INS: Update comment AP_InertialSensor.cpp

### PR DESCRIPTION
**Pull request by hdtechk**
Fix typo in comments should be NFC

### CODE REVIEW

**Comment by rmackay9** [comment]
Looks good but the commit should have "INS:" prefixed

**Comment by rmackay9** [comment]
Interactive rebase is the key and it's on the wiki [here](http://ardupilot.org/dev/docs/git-interactive-rebase.html).  It's also possible to change a commit using Git Gui (it has a "Latest Commit" button on the bottom right) and then you'll need to do a forced push.

In any case, it's not the end of the world, I can do it .. it just adds a few min to the process.

**Comment by hdtechk** [comment]
Randy I had to download to my computer to fix it. hope that is what you needed

**Comment by rmackay9** [comment]
yes, looking good, thanks!  I'll merge shortly.

**Comment by magicrub** [comment]
Thanks Kurt! @hdtechk

**Comment by magicrub** [comment]
@proficnc seems like we'll need another PR from @hdtechk

**Comment by hdtechk** [comment]
@magicrub @proficnc #10817

**Pull request merged**
