### PR TITLE
Rover: add ATC_DECEL_MAX parameter for deceleration limits

### PR DESCRIPTION
**Pull request by Ammarf**
This PR fixes [this issue](https://github.com/ArduPilot/ardupilot/issues/8422) found in [this discussion](https://discuss.ardupilot.org/t/skid-steer-mower-overshooting-pivot-turns/28910).

### CODE REVIEW

**Comment by rmackay9** [comment]
Txs for this.  one issue that's come to mind is we need to use this in the mode.cpp's Mode::calc_reduced_speed_for_turn_or_distance(). 

This little section should be using the deceleration value so perhaps add a new accessor called "get_decel_max()" and have it return the deceleration max if set, otherwise return the accel max.

**Comment by rmackay9** [comment]
I think it's probably good to remove the AR_ATTCONTROL_THR_DECEL_MAX definition as well and just set the parameter default to 0 directly in the .cpp file.

**Comment by rmackay9** [comment]
I've tested this and it does what is expected.  See pic below including yellow arrows in the AFTER image which slows the vehicle decelerates more slowly when ATC_DECEL_MAX is set to 1m/s/s (default is 5m/s/s)
ammarf-testing

I will merge this after including a couple of small changes.

**Comment by rmackay9** [comment]
@khancyr, yes, while testing I've uncovered a whole bunch of acceleration/decelertion issues and [listed them here](https://github.com/ArduPilot/ardupilot/issues/8448).  This PR isn't the cause of those issues though, they're pre-existing.

**Comment by rmackay9** [comment]
Merged!

**Comment by tonymills** [comment]
Hi All,

Is this atc_decel_max still a valid value in rover 4.0? i am wanting my boat to decel before it gets to the waypoint

Thanks in advance

**Comment by rmackay9** [comment]
Hi @tonymills,

Yes, it should be included in Rover-4.0

**Pull request closed without merging**
