### PR TITLE
This allows user to set the surface positions for the aeroterminate

### PR DESCRIPTION
**Pull request by QuPsi**
functionality.

Continued from:

https://github.com/ArduPilot/ardupilot/pull/15413

### CODE REVIEW

**Comment by magicrub** [comment]
please don't close and re-open new PRs for code changes. Just push to your same branch. the PR will update.

**Comment by QuPsi** [comment]
I understand and I tried to do just that but I thoroughly screwed up my
repositories and managed to delete the branch upstream. My apologies.

**Comment by QuPsi** [comment]
So I'm seeing that the build failed for the Rover. Can someone guide me as to how I can address this? I'm not exactly sure what failed and/or why?

**Comment by mday299** [comment]
@magicrub I cannot recreate the Rover problem on my machine.  Why is Rover failing?

**Comment by magicrub** [comment]
@mday299 that Travis error smells like a timing problem. I've restarted the test. We've ben having a lot of problems with Travis and are currently implementing GitHub Actions which will help.

**Comment by magicrub** [comment]
Travis is passing. 

@QuPsi @mday299 since this is a (int * int/int) have you guys tested this with values 1-99? I runs the risk of being truncated to zero since there's no obvious promotion happen. I'd be more comfortable if we changed that ```100``` to ```100.0```

Otherwise looks fine to me and I'd otherwise be happy to merge it if there wasn't already an unresolved discussion in #15413 that was lost with this new PR's discussion.

**Comment by magicrub** [comment]
Conversation from #15413 
> @tridge: we need some good justification for why these parameters are needed
> @QuPsi: In some aircraft, because of channel reversal, the aircraft will pitch up instead of down during aeroterminate. This allows the user to set the positions for the aeroterminate.

I think that's a valid justification for specific percent but I think the intent is to not have control and a max is OK as long as it's in the correct direction so a change to this is probably what we're looking for:
```
SRV_Channels::set_output_scaled(SRV_Channel::k_aileron, channel_roll->get_reverse() ? -SERVO_MAX : SERVO_MAX);
SRV_Channels::set_output_scaled(SRV_Channel::k_elevator, channel_pitch->get_reverse() ? -SERVO_MAX : SERVO_MAX);
SRV_Channels::set_output_scaled(SRV_Channel::k_rudder, channel_rudder->get_reverse() ? -SERVO_MAX : SERVO_MAX);
```

**Comment by QuPsi** [comment]
@magicrub again, this is my fault for the new pull request. You can blame my inexperience with git for that, so my apologies. 

I understand your point about the direction, but I still feel that the user should be able to set this. Reason being is because depending on the type of aircraft and configuration, even with the reverse, the deflections may not yield the fastest descent. For example, right aileron and left rudder. Depending on the aircraft, this may not yield a spin as intended. 

Also, depending on the surface control hardware configuration, full servo deflection may not yield full surface deflection. I think for most applications this is fine, but I think it would good to have a bit more granular control.

**Comment by QuPsi** [comment]
Resubmitted changing the 100 to 100.0. 

Although it worked just fine for values 1-99, I changed it to be on the safe side.

**Comment by magicrub** [comment]
@QuPsi thanks. We'll discuss at the Dev call on Monday.

**Comment by tridge** [comment]
@QuPsi can you please show a photo of an aircraft where the existing code won't cause it to crash quickly

**Comment by QuPsi** [comment]
Unfortunately, I am unable as it is a DOD vehicle.

**Comment by mday299** [comment]
@tridge 
https://www.dualrc.com/elanus-duo/rtf

**Comment by tridge** [comment]
@mday299 thanks, it seems surprising to me that you'd want down elevator. Normally the aim is to lose airspeed and stall (max rudder and aileron to roll over)
If there is a legitimate reason for this then it can go in, I just want to be sure that there is a real reason for terminating with other than up elevator

**Comment by QuPsi** [comment]
Depending on the aircraft, full up elevator causes a graceful stall before entering in a spin. The allows the aircraft to travel a bit before really spinning. Also, depending on the aircraft, full deflection of elevator, aileron, and rudder is not enough to completely stall it but rather make the aircraft enter in a spiral descent vs a spin. 

I understand the concern, but is there any harm in giving the user control over this, especially since it already has a default?

**Comment by tridge** [comment]
> I understand the concern, but is there any harm in giving the user control over this, especially since it already has a default?

the harm is more parameters. We try and not add parameters when they are not needed.



> Depending on the aircraft, full up elevator causes a graceful stall before entering in a spin. The allows the aircraft to travel a bit before really spinning. Also, depending on the aircraft, full deflection of elevator, aileron, and rudder is not enough to completely stall it but rather make the aircraft enter in a spiral descent vs a spin.

so what settings are better than full up elevator, full aileron and full rudder?

**Comment by QuPsi** [comment]
This would depend on the aircraft. For example, a canard, by its very nature stalls gracefully. The canard will stall before the main wing. As a result, the nose will drop lowering the AoA of the main wing further preventing a full on stall. In this configuration, nose down would probably be better.

**Comment by tridge** [comment]
> This would depend on the aircraft. For example, a canard, by its very nature stalls gracefully. The canard will stall before the main wing. As a result, the nose will drop lowering the AoA of the main wing further preventing a full on stall. In this configuration, nose down would probably be better.

that seems to be ignoring the roll and rudder aspects of the termination. A canard plane roll lose speed and roll over. So I still don't see why putting elevator down is useful. It will just increase the energy of the impact.

**Comment by QuPsi** [comment]
No longer necessary.

**Pull request closed without merging**
