### PR TITLE
some init msg

### PR DESCRIPTION
**Pull request by ObeidHaidar**

### CODE REVIEW

**Comment by rmackay9** [comment]
Hi @ObeidHaidar,

It looks like the whole Git_Success.txt file has been zapped in this PR.  Maybe update it so that only your name is added at the end?  Also if possible change the commit to be something like, "Tools: add name to Git_Success".

**Review by rmackay9 — CHANGES_REQUESTED** [review]
points to fix listed above, txs!

**Review by amilcarlucas — CHANGES_REQUESTED** [review]
Nope, you can not remove the name of the other persons!

**Comment by peterbarker** [comment]
I'm going to close this now.  @ObeidHaidar feel free to have another go at adding yourself, 'though!

**Pull request closed without merging**
