### PR TITLE
AC_Fence: Change the default fence specification

### PR DESCRIPTION
**Pull request by muramura**
The default values for fences are altitude and radius.
Since the polygon fence has not been set, an error occurs if the fence is allowed.
I basically assume a fence with default values.
I think fences without default values are optional.

### CODE REVIEW

**Comment by rishabsingh3003** [comment]
@muramura there was some discussion on this a while back.
https://github.com/ArduPilot/ardupilot/issues/11486

**Comment by rmackay9** [comment]
I'm afraid we can't merge this if this leads to users having to define a polygon fence when they enable the regular fence.

Try this test:

- leave fence parameters as their defaults
- set FENCE_ENABLE = 1
- try to arm vehicle

if this PR means that the user is hit with a pre-arm check requiring them to setup a fence then we can't merge this.

**Comment by peterbarker** [comment]
@muramura do you have a solution for Randy's problem there?

**Comment by joshanne** [comment]
I would posit the changes made in #15288 address and correct the `FENCE_STATUS` message. Previously, a fence was only present if `_poly_loader.total_fence_count() == 0`. There are also autotests to test the breaches of each of these individual items.

**Comment by peterbarker** [comment]
Closing this as no answer in 4 years.  @joshanne thinks this is already addressed, and there's been  a lot of rework in fence since this PR was created.

Please PR against master if you think there's still work to be done here.

**Pull request closed without merging**
