### PR TITLE
AP_HAL_ChibiOS: add HEEWING-F405 hwdef

### PR DESCRIPTION
**Pull request by HelloLeFei**
hi
  This is my first time submitting a request to ardupilot, and the content submitted this time includes HEEWING F405 hwdef.

### CODE REVIEW

**Comment by rmackay9** [comment]
Hi @HelloLeFei,

Thanks for the contribution.

One small thing is that we always prefix our commits with the directory name or subsystem name.  So it would be good if you could squash the commits together and rename it to something like, "AP_HAL_ChibiOS: add hwdef for heewingf405".

**Comment by HelloLeFei** [comment]
> Hi @HelloLeFei,
> 
> Thanks for the contribution.
> 
> One small thing is that we always prefix our commits with the directory name or subsystem name. So it would be good if you could squash the commits together and rename it to something like, "AP_HAL_ChibiOS: add hwdef for heewingf405".

Okay, I will pay attention next time. Thank you！

**Comment by rmackay9** [comment]
@HelloLeFei,

OK thanks.  So can you squash these two commits together?

I've changed the PR title but I haven't fixed the commits.

**Comment by HelloLeFei** [comment]
> @HelloLeFei,
> 
> OK thanks. So can you squash these two commits together?
> 
> I've changed the PR title but I haven't fixed the commits.

hello, can you tell me how to squash commits after i have pull request,thankyou

**Comment by andyp1per** [comment]
@HelloLeFei - I put together a PR with your changes - https://github.com/ArduPilot/ardupilot/pull/24164 - it is probably easier to drive it from there as I have a board I can test. Put happy to push to this PR if you would prefer.

**Comment by HelloLeFei** [comment]
> @HelloLeFei - I put together a PR with your changes - #24164 - it is probably easier to drive it from there as I have a board I can test. Put happy to push to this PR if you would prefer.

OK .thankyou, i will also test

**Comment by rmackay9** [comment]
OK, well, looking forward to you @HelloLeFei next time.

I'll close this PR, thanks again!

**Pull request closed without merging**
