### PR TITLE
hwdef: SkyViper doesn't need proximity sensors

### PR DESCRIPTION
**Pull request by peterbarker**
```
Board               AP_Periph  blimp  bootloader  copter  heli  iofirmware  plane  rover  sub
Durandal                       *      *           *       *                 *      *      *
HerePro             *                                                                     
Hitec-Airspeed      *                                                                     
KakuteH7-bdshot                *      *           -24     -24               *      -16    *
MatekF405                      *      *           *       *                 *      *      *
Pixhawk1-1M-bdshot             *                  *       *                 *      *      *
f103-QiotekPeriph   *                                                                     
f303-Universal      *                                                                     
iomcu                                                           *                         
revo-mini                      *      *           *       *                 *      *      *
skyviper-v2450                                    -7576                                   
```

SkyViper retains mavlink proximity sensor here.

### CODE REVIEW

**Comment by peterbarker** [comment]
Should we keep mavlink?

**Review by tridge — APPROVED** [review]

**Comment by peterbarker** [comment]
I've gone ahead and made defines for all of the backends.  So if someone wants to use a mavlink-based backend on SkyViper - great!

**Comment by khancyr** [comment]
ha , it seems I didn't follow enough on latest devcall. I though you were speaking about disabling MAVlink proximity by default but for all... not only for skyviper 
I think that disabling it on skyviper by default is fine too

**Comment by peterbarker** [comment]
I ran this through the build_options.py script far enough to try disabling each of the backends in turn.

**Comment by peterbarker** [comment]
@rmackay9 this PR contains another instance of voiding the variable.  This is the patch required to fix it here:
```
index 3ef0db827e7..06442b85bb6 100644
--- a/libraries/AP_Proximity/AP_Proximity.cpp
+++ b/libraries/AP_Proximity/AP_Proximity.cpp
@@ -120,8 +120,10 @@ void AP_Proximity::init()
     }
 
     // instantiate backends
+#if AP_PROXIMITY_RPLIDARA2_ENABLED || AP_PROXIMITY_TERARANGERTOWER_ENABLED || AP_PROXIMITY_TERARANGERTOWEREVO_ENABLED || AP_PROXIMITY_LIGHTWARE_SF40C_ENABLED || AP_PROXIMITY_LIGHTWARE_SF45B_ENABLED || AP_PROXIMITY_CYGBOT_ENABLED
     uint8_t serial_instance = 0;
-    (void)serial_instance;  // in case no serial backends are compiled in
+#endif
+
     for (uint8_t instance=0; instance<PROXIMITY_MAX_INSTANCES; instance++) {
         switch (get_type(instance)) {
         case Type::None:
```

... I don't think that's a good trade-off myself :-)

**Review by tridge — APPROVED** [review]

**Pull request merged**
