### PR TITLE
Rover: auto stops vehicle if RTK fix lost

### PR DESCRIPTION
**Pull request by mehsyeda01**
added autoresume if rtk fix is there or stop if rtk fix is lost. It will be a really helpful feature.

### CODE REVIEW

**Comment by amilcarlucas** [comment]
This needs to be configurable using a parameter.
The indentation needs to be improved, and the original if needs to be taken into consideration.

**Comment by IamPete1** [comment]
Perfect lua scripting use case.

**Comment by amilcarlucas** [comment]
like Pete said this is better done in a lua script.

**Comment by khancyr** [comment]
As said by other , this belong more for LUA script. In case we would like such feature, it would be need a broader integration to really restrict moving when RTK is working. But that will be a bigger task and I don't think that is necessary.

I will close this PR for now. Open a new one with the LUA script and we should be able to merge it fast hopefully

**Pull request closed without merging**
