### PR TITLE
OREOLED update

### PR DESCRIPTION
**Pull request by jschall**
Depends on: https://github.com/diydrones/PX4Firmware/pull/47

### CODE REVIEW

**Comment by tridge** [comment]
the approach looks good. Let me know when you have tested that this works on Solo

**Comment by lucasdemarchi** [comment]
@jschall news on that?

**Comment by magicrub** [comment]
@jschall is this still valid?

**Comment by jschall** [comment]
Honestly don't know. OREOLED is purely a Solo thing. Whatever is in solo-rebase works fine - don't know if this is up to date.

**Comment by jmachuca77** [comment]
This is probably no longer relevant.

**Comment by WickedShell** [comment]
SMBus stuff is no longer relevant, I suspect this can be closed.

**Comment by magicrub** [comment]
replaced with https://github.com/ArduPilot/ardupilot/pull/6092

**Comment by OXINARF** [comment]
How does #6092 replace this? This has an updated oreoled binary for example...

**Comment by magicrub** [comment]
Ok, not a replacement but still depends on another PR which is bitrotting. Reopening

**Comment by Pedals2Paddles** [comment]
Closing as this is quite old and has been superceeded.

**Pull request closed without merging**
