### PR TITLE
AP_HAL: Added RCOutput interactive example with Menu

### PR DESCRIPTION
**Pull request by hiro2233**
Added a version RCOuput example working with AP_Menu.
Servo and Esc types can select and set freq in menu.

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
I think this functionality is reasonable to have in the RCOutput example actually. Any reason to duplicate this code?

**Comment by hiro2233** [comment]
Because adding menu library make different and basically it's for Junior APM developers first impression and compare with v1 example. Because i think v1 it's better maintain and more examples is better too, thinking in the teaching side.

**Comment by guludo** [comment]
Some comments:
 - This is missing a `wscript` file.
 - The code doesn't conform with http://ardupilot.org/dev/docs/style-guide.html (just a few lines actually).  Consider running `astyle --options=Tools/CodeStyle/astylerc libraries/AP_HAL/examples/RCOutput2/RCOutput.cpp`.

**Comment by hiro2233** [comment]
@lucasdemarchi @guludo, please check, reworked and fixed APM codestyle dev.

Thanks, @guludo .

**Comment by lucasdemarchi** [comment]
Applied. I squashed the fixes that were on top and added some more coding style fixes.

**Pull request closed without merging**
