### PR TITLE
Save Waypoints in Copter 4.0

### PR DESCRIPTION
**Pull request by norimboo**
"Save Waypoint" function doesn't work. It can be chosen from Auxiliary Function Switch RCx_OPTION (7/Save WP). When "Save Waypoint" is selected and triggered nothing happens. So there is no possibility to manual plan an auto mission. 

That will be also useful to add new parameters to RCx_OPTION which will give possibility to add waypoints, skip to next waypoint, select delay on waypoint, give possibility to save waypoint with yaw angle an without yaw.

### CODE REVIEW

**Comment by amilcarlucas** [comment]
Please use "git rebase" to put your changes on top of either master or Copter-4.0 branch

**Comment by peterbarker** [comment]
We do autotest the toggle-waypoint-in functionality.  that test is here: https://github.com/ardupilot/ardupilot/blob/master/Tools/autotest/arducopter.py#L300

It's passing on master....

Could you describe minimum steps to reproduce, please?

**Comment by rmackay9** [comment]
This looks like an issue raised as a PR so closing.  Issues belong here: https://github.com/ArduPilot/ardupilot/issues but support should really go into the forums first before being raised as an issue

**Comment by norimboo** [comment]
@rmackay9 What I did wrong. Is it known problem and raised earlier ?

**Pull request closed without merging**
