### PR TITLE
AP_EFI: avoid requesting data too often

### PR DESCRIPTION
**Pull request by peterbarker**
Similar to 4585c9fdc1f5b2e6a962cc9d2be02bff5c347073

### CODE REVIEW

**Review by WickedShell — CHANGES_REQUESTED** [review]
I think this would be a regression. The driver ideally wants data at 10Hz. In an ideal situation we parse a full message, and have no extra bytes pending (because the protocol is request/response driven), in which case we should request the data again so we can have it in 100 ms. If there was data, but not the right amount of data it might still be coming in (or got lost), so we don't spam the request out, and this should be the less common situation.

The effect of your proposed change would be to only send a request for data at 5Hz instead of 10Hz, which would hurt everything that is dependent upon this data.

**Comment by peterbarker** [comment]
> I think this would be a regression. The driver ideally wants data at 10Hz. In an ideal situation we parse a full message, and have no extra bytes pending (because the protocol is request/response driven), in which case we should request the data again so we can have it in 100 ms. If there was data, but not the right amount of data it might still be coming in (or got lost), so we don't spam the request out, and this should be the less common situation.
> 
> The effect of your proposed change would be to only send a request for data at 5Hz instead of 10Hz, which would hurt everything that is dependent upon this data.

We can request at 10Hz.  Or 20Hz.  Let's do so deliberately.

Right now in master we're polling at ~50Hz - by accident...

**Comment by WickedShell** [comment]
> > I think this would be a regression. The driver ideally wants data at 10Hz. In an ideal situation we parse a full message, and have no extra bytes pending (because the protocol is request/response driven), in which case we should request the data again so we can have it in 100 ms. If there was data, but not the right amount of data it might still be coming in (or got lost), so we don't spam the request out, and this should be the less common situation.
> > The effect of your proposed change would be to only send a request for data at 5Hz instead of 10Hz, which would hurt everything that is dependent upon this data.
> 
> We can request at 10Hz. Or 20Hz. Let's do so deliberately.
> 
> Right now in master we're polling at ~50Hz - by accident...

To be fair that's actually a better way then going the opposite direction down to 5Hz (as long as the ECU doesn't die/has the bandwidth), because this is a source of RPM data for the notch filters on quadplanes :)

**Comment by peterbarker** [comment]
> > > I think this would be a regression. The driver ideally wants data at 10Hz. In an ideal situation we parse a full message, and have no extra bytes pending (because the protocol is request/response driven), in which case we should request the data again so we can have it in 100 ms. If there was data, but not the right amount of data it might still be coming in (or got lost), so we don't spam the request out, and this should be the less common situation.
> > > The effect of your proposed change would be to only send a request for data at 5Hz instead of 10Hz, which would hurt everything that is dependent upon this data.
> > 
> > 
> > We can request at 10Hz. Or 20Hz. Let's do so deliberately.
> > Right now in master we're polling at ~50Hz - by accident...
> 
> To be fair that's actually a better way then going the opposite direction down to 5Hz (as long as the ECU doesn't die/has the bandwidth), because this is a source of RPM data for the notch filters on quadplanes :)

Yep, I understand your concerns, so DevCall time.

If I'm reading the Lutan driver correctly then it requests at 5Hz - so perhaps that one should be bumped up as well.

**Comment by WickedShell** [comment]
> > To be fair that's actually a better way then going the opposite direction down to 5Hz (as long as the ECU doesn't die/has the bandwidth), because this is a source of RPM data for the notch filters on quadplanes :)
> 
> Yep, I understand your concerns, so DevCall time.
> 
> If I'm reading the Lutan driver correctly then it requests at 5Hz - so perhaps that one should be bumped up as well.

So I was thinking about this a bit more, and the parser is *rough*. A large part of the problem here is that the protocol has no header, which means once we lose sync the only real way to recover is to either shift the entire input buffer by 1 byte and test again (a rapidly painful experience with the CRC being the validation approach), or to simply wait until a dead line is detected (as shown by both having decoded the previous packet, and having no pending data, and not having asked for a new one.

While the change limits us spamming requests out, I think the minimum to make this better would be to:
  - Upon parsing a response correctly drain the input
  - Upon parsing a response correctly issue a request for the data we need
  - Then only issue an additional request if we haven't sent one within 200 ms
  - Make send request itself rate limit to only request an update at at most every 75 milliseconds (this could be a constant in the header, or a define so a hwdef can change it).

This makes it a larger patch, but I think at least keeps us in a generally well behaved space, without messing up our rate at which we get vital engine information.

**Comment by peterbarker** [comment]
@WickedShell are you OK with merging this if we change it to 10Hz?

**Comment by WickedShell** [comment]
As long as we are still getting data/issuing requests at 10Hz or more after the change I'm good with it.

**Comment by peterbarker** [comment]
> As long as we are still getting data/issuing requests at 10Hz or more after the change I'm good with it.

Done!

**Pull request merged**
