### PR TITLE
Change default storage paths for Navio boards 

### PR DESCRIPTION
**Pull request by staroselskii**
This is a minor change that only affects Navio boards. This is mainly done for consistency.
AFAIK, `APM` is an old name. So, I also suggest trying to remove it from the codebase one piece at a time.

It'd be also nice to keep logs in vehicle-dependent directories (I know of the `--log-directory` switch, but I was thinking about a compile time dependency here). I would like to hear out any suggestions on that matter. I'm also eager to hear why that might be a bad idea.

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
Hi @staroselskii 

This the proposed solution and never implemented: https://docs.google.com/document/d/1Bqf1CcJkgWZBokmNKRm2sqZukezHVZRnGWdiV1sYfN4/edit

I don't see a reason to add a directory for each board. I agree wrt vehicle type.

**Comment by staroselskii** [comment]
@lucasdemarchi 

There's a scenario that I'd like to avoid. Here it goes:
1) one launches an ArduCopter (for the sake of the example) binary on one board
2) switches the board to another one
3) logs are written to the same directory (```/var/lib/ardupilot/logs```)

After that there's no way for a user to determine which of the logs were written on which board.

I'm going to force push the changes according to the doc. Maybe other maintainers will keep up and will get rid of ```#ifdef``` eventually.

**Comment by lucasdemarchi** [comment]
> There's a scenario that I'd like to avoid. Here it goes:
> 1) one launches an ArduCopter (for the sake of the example) binary on one board
> 2) switches the board to another one
> 3) logs are written to the same directory (/var/lib/ardupilot/logs)

I'd actually advise against sharing the sdcard with each board. But it's your call.

> After that there's no way for a user to determine which of the logs were written on which board.

Maybe we could also write the board name to the log?

**Comment by staroselskii** [comment]
> I'd actually advise against sharing the sdcard with each board. But it's your call.

Yeah, sure. I'm chasing ghosts here.

**Comment by magicrub** [comment]
I'm definitely in favor of writing the board type to the log on boot. We write many things on boot such as the firmware number with git hash ect ect. Adding board type would be a very welcome addition

**Comment by dgrat** [comment]
Is there a way to solve this via the input parameters? 
Additionally, it might be nice to extend the command line parameters to refer to a *.ini file with settings.
Beside to this, I would maybe add a time-stamp into the name of the directory or the log file name.

**Comment by staroselskii** [comment]
> Is there a way to solve this via the input parameters? 

Sure. That is the default approach. This doesn't mean that we should have a compile time dependency on old name.

> Additionally, it might be nice to extend the command line parameters to refer to a *.ini file with settings.
Beside to this, I would maybe add a time-stamp into the name of the directory or the log file name.

I'm totally up to both of these.

**Comment by dgrat** [comment]
@staroselskii 
Agree.

**Comment by rmackay9** [comment]
I've assigned this to Lucas, not sure if that's the right thing to do but..

**Comment by staroselskii** [comment]
I'm closing this one. I'll reopen when merge conflicts are fixed.

**Pull request closed without merging**
