### PR TITLE
AP_Compass: simplify optional backends

### PR DESCRIPTION
**Pull request by lucasdemarchi**
@LanderU  this may help with your boards.

### CODE REVIEW

**Comment by LanderU** [comment]
@lucasdemarchi , okay I will try it. Thanks.

**Comment by LanderU** [comment]
@lucasdemarchi ,after trying with all vehicles, these changes, not work for me. Only recognize the internal compass.

Why not, select the compass like below?

```
#elif CONFIG_HAL_BOARD_SUBTYPE == HAL_BOARD_SUBTYPE_LINUX_PXF || CONFIG_HAL_BOARD_SUBTYPE == HAL_BOARD_SUBTYPE_LINUX_ERLEBRAIN2 || \
      CONFIG_HAL_BOARD_SUBTYPE == HAL_BOARD_SUBTYPE_LINUX_PXFMINI

       AP_Compass_Backend *backend = AP_Compass_HMC5843::probe(*this, hal.i2c_mgr->get_device(HAL_COMPASS_HMC5843_I2C_BUS, HAL_COMPASS_HMC5843_I2C_ADDR));
    if (backend) {
        _add_backend(backend);
    } else {
        _add_backend(AP_Compass_AK8963::probe_mpu9250(*this, 0));
    }
```

Works well.

**Comment by lucasdemarchi** [comment]
@LanderU why do you want to force only 1 compass?  You could just try to add both (preferably with the internal one first)

**Comment by LanderU** [comment]
Ok for me @lucasdemarchi.

**Comment by lucasdemarchi** [comment]
Applied, thanks for reviewing.

**Pull request closed without merging**
