### PR TITLE
AHRS: fixed earth frame accel with significant AHRS trim

### PR DESCRIPTION
**Pull request by tridge**
thanks to @lthall for finding this
this bug does not affect EKF2

### CODE REVIEW

**Review by andyp1per — APPROVED** [review]

**Comment by rmackay9** [comment]
fantastic!

**Comment by lthall** [comment]
I think this is one for the 4.3 backport :)

**Comment by andrefreitas97** [comment]
Can someone explain what possible problems this solves? Thanks in advance

**Comment by rmackay9** [comment]
@andrefreitas97,

We found that the multicopter landing detector was not working if AHRS_TRIM_X/Y was greater than 0.1.

**Pull request merged**
