### PR TITLE
Copter: Grouping judgment conditions

### PR DESCRIPTION
**Pull request by muramura**
Multiple IF statements contain the same decision condition.
I have grouped the judgment conditions.

### CODE REVIEW

**Review by F11ff — APPROVED** [review]

**Review by lthall — CHANGES_REQUESTED** [review]
I like it but I would like to see the following line split out by removing the internal decision statement.
auto_yaw.set_yaw_angle_rate(yaw_cd * 0.01f, use_yaw_rate ? yaw_rate_cds * 0.01f : 0.0f);

**Comment by muramura** [comment]
@lthall san.
Thanks for the review.
I have made the changes.

**Review by lthall — APPROVED** [review]

**Comment by lthall** [comment]
Sorry for the delay. Do you want to do a quick rebase and I will try to get it approved at the next dev call.

**Comment by peterbarker** [comment]
I'm not a great fan of this, but marking I've rebased it and I'm marking for DevCall.

**Review by lthall — APPROVED** [review]
Looks correct to me

**Comment by rmackay9** [comment]
It's correct but I think it's less easy to understand after the change.  I think with two of us not liking the change I think I'll close it

**Pull request closed without merging**
