### PR TITLE
Add support for Baro/Vario in CRSF

### PR DESCRIPTION
**Pull request by andyp1per**
Fixes the CRSF part of https://github.com/ArduPilot/ardupilot/issues/26699

### CODE REVIEW

**Comment by Merga189** [comment]
Is it possible for me to do some test?

Hardware Kakute F7 Mini and SpeedyBee F405 Wing Mini.

br Karl

**Comment by Merga189** [comment]
Could not resist, as after a discussion with Yuri 
https://discuss.ardupilot.org/t/2-linux-versions-needed-to-build-different-ap-versions/115237/1
have a environment here under Debian 12 and build for both my FCs here successfully.

I'll flash and come back.

**Comment by Merga189** [comment]
If it is OK!?

I build for the SpeedyBee F405 WING

parameter list version: 4.6.0 dev

[Speedy_Test.params.txt](https://github.com/ArduPilot/ardupilot/files/15107924/Speedy_Test.params.txt)

FW

[bin.zip](https://github.com/ArduPilot/ardupilot/files/15107938/bin.zip)

Karl

**Comment by Merga189** [comment]
**No** baro values on SpeedyBee F405 WING mini with FW 4.6.0 dev.

FrSky X10S Express,  EdgeTX 2.9.4, HiYounger TX module + BETAFPV 2.4GHz Nano RX ELRS 3.3.2, SppedyBee F405 Wing mini only with BT slave on Serial 6 for communication. No GPS connected.

[xxx.params.txt](https://github.com/ArduPilot/ardupilot/files/15109309/xxx.params.txt)

**Comment by andyp1per** [comment]
Do you get any extra sensors if you search for them? I only did ID 9, not ID 7 (Baro only)

**Comment by Target0815** [comment]
@andyp1per Can you please provide a firmware for SpeedyBee F405 Wing?

**Comment by Merga189** [comment]
Deleted all sensor and searched again.

That is, what I have here on the table

Screenshot_2024-04-25_20-55-31

It is just a F405 WING Mini with RX and BT module, nothing else. The parameter list with your Version: 4.6.0 dev I posted before. No changes made.

Here the radio telemetry screen and the companion telemetry screen -fresh-




No id 9

br Karl

**Comment by Merga189** [comment]
@andyp1per 

I think, there is an error on my side.

I cloned your fork `~$ git clone --recurse-submodules https://github.com/andyp1per/ardupilot.git` and just build the firmware.

But checking, if your modifications like

Screenshot_2024-04-26_08-50-52

are actually in the code I did build here I see that

Screenshot_2024-04-26_08-47-00

My apologize for the confusion

Best you provide a firmware for the SpeedyBee F405 Wing

Karl

**Comment by andyp1per** [comment]
[arduplane.apj.zip](https://github.com/ArduPilot/ardupilot/files/15126821/arduplane.apj.zip)

**Comment by Merga189** [comment]
ID 9 shows up! Wrong value, but it is there .....

screen-2024-04-26-093844
screen-2024-04-26-093854

**Comment by andyp1per** [comment]
[arduplane.apj.zip](https://github.com/ArduPilot/ardupilot/files/15127523/arduplane.apj.zip)

Try this one, I think I need to invert the sign since AP deals in down rather than up

**Comment by Merga189** [comment]
GPS attached. FW changed. Have the FC here on the window sill

Untitled

**Comment by Target0815** [comment]
With Ethos 1.5.6

screenshot-2024-04-26-41102

I still have to test whether the values are correct ...

**Comment by Target0815** [comment]
Ethos can evaluate the frame CRSF_FRAMETYPE_BARO_ALTITUDE with ID9 (Alt and VSpd). EdgeTX only evaluates CRSF_FRAMETYPE_VARIO with ID7 (VSpd).

It would be an advantage for Ardupilot if you could use both. Possibly switchable with a flag in RC_OPTIONS or similar. This would cover all transmitter systems.  

As for the values themselves, the calculations used for the S.Port protocol can be found in AP_Frsky_Telem. Presumably you can see there which sign is used and adopt this in part for CRSF.

**Comment by andyp1per** [comment]
This includes ID 7 - please try it
[arduplane.zip](https://github.com/ArduPilot/ardupilot/files/15138418/arduplane.zip)

**Comment by Merga189** [comment]
Alt and VSpd show up, but irregular values.

50' YT video showing first baro values on QGroundcontrol and then values on my radio.

https://youtu.be/iiIft0VpIOk

**Comment by andyp1per** [comment]
So there was a bug in the new code where it was using absolute alt instead of relative. Should be fixed now.

[arduplane.zip](https://github.com/ArduPilot/ardupilot/files/15139634/arduplane.zip)

I think the errors in vspd are actually quantization errors since this is only an 8-bit int. We might have to special-case 0 to return 0;

**Comment by Merga189** [comment]
VSpd id 7.   moving up down in between +1xx.x m/s and -9x.x m/s

ALT id 9.     -1000.0 m fix, not moving at all

ELRS

**Comment by andyp1per** [comment]
[arduplane.zip](https://github.com/ArduPilot/ardupilot/files/15139781/arduplane.zip) - think there was a sign conversion issue.

Can you send me a disarmed log of your vehicle? There is not a lot going on in these calculations, but there is some weird conversion.

**Comment by Merga189** [comment]
> [arduplane.zip](https://github.com/ArduPilot/ardupilot/files/15139781/arduplane.zip) - think there was a sign conversion issue.
> 
> Can you send me a disarmed log of your vehicle? There is not a lot going on in these calculations, but there is some weird conversion.

I am just a user and at the moment there is no vehicle. It is just the SpeedBee in the window sill. 
MP or QG?
But I'll flash now and come back ....

**Comment by Merga189** [comment]
VSpd  - varying between -/+ xxx m/s
Alt      -  crazy numbers -/+ xxxxx m 

What is that "disarmed log"?? MP or QG

**Comment by Merga189** [comment]
I think, 'data log' in MP. I am on Linux here with QG, but I have a WIN with MP in a Vbox. So I'll try ....

**Comment by Target0815** [comment]
[Andy_log.zip](https://github.com/ArduPilot/ardupilot/files/15139942/Andy_log.zip)

Log 1: original 4.6.0 with ER8GV **Vario** RX
Log 4: Andy 4.6.0 with Standard ELRS RX

You should be able to make a good comparison.

**Comment by Merga189** [comment]
[2024-04-27 22-56-34.tlog.zip](https://github.com/ArduPilot/ardupilot/files/15139954/2024-04-27.22-56-34.tlog.zip)

Hope, that is the right one.

Good night, shut down now ;-)

**Comment by andyp1per** [comment]
Ok, pretty sure this is correct now:

[arduplane.zip](https://github.com/ArduPilot/ardupilot/files/15142807/arduplane.zip)

Constant 10000 is expected - that's 0m above home or 10000dm above the minimum altitude which is 1000m below home.
The switching between -1/+1 etc for vpsd is also expected - this is in cm/s for ID7 and is a log scale for ID9 so represents something like +-0.05ms which is perfectly reasonable. So my guess is that the decoding on your TX side that is the problem.

**Comment by Merga189** [comment]
Set RATIO for VSpd and Alt to 0.1 on the radio here. ELRS. Alt  and VSpd values now in region +/- x.x m/s and x.x m.

Put the FC in a blown up plastic shopping bag and compress the bag with my hand. Alt value static, VSpd moving, but in my eyes not making seens.

**Comment by andyp1per** [comment]
Alt value is relative height above home which will not change unless you arm.

**Comment by Merga189** [comment]
I see on MP, that the FC is ARMED (ARM/DISARM on toggle switch) Alt here with me rock solid -4.5m. Putting a plastic bag over the FC and putting hand pressure on the bag, in MP see - 30 ... -40m, but value is 9 rock solid. For VSpd same. a little variation, but not a measurement as expected ... ELRS

**Comment by andyp1per** [comment]
> I see on MP, that the FC is ARMED (ARM/DISARM on toggle switch) Alt here with me rock solid -4.5m. Putting a plastic bag over the FC and putting hand pressure on the bag, in MP see - 30 ... -40m, but value is 9 rock solid. For VSpd same. a little variation, but not a measurement as expected ... ELRS

Do you have a GPS? Its the same code as FPort, will only work with GPS

**Comment by Merga189** [comment]
Then the fault is on my side. I removed the GPS for the bag testing.
So it need ARMING and GPS! GPS has to have a lock?
Repeat the test and report.

So, ARMED, GPS has fix. Ratio VSpd 0.1, Alt Ratio 0.1 
VSpd +/- 0.3 m/s, Alt -3.3 to -3.4 m. Looks good!

But how to verify those values?

I used this here to simulate altitude changes with baro sensors some years ago, but this is to small to take it all inside. 



Or I need a plane and record, but I don't have that at the moment.

**Comment by andyp1per** [comment]
Pete showed me perhaps a better way to determine the altitude which will not require GPS. I'll chat to Alex about using this.

**Comment by Merga189** [comment]
The good thing is, ID 7 and ID 9 are on the radio and we do have values.

**Comment by Target0815** [comment]
> I'll chat to Alex about using this.

Do this ... Alex has conjured up a quick Vario / VSpd for S.Port. I actually wanted to test your current solution against F.Port, but I should probably wait a little longer?

**Comment by andyp1per** [comment]
Can you try this? This adds better support for relative home, so baro on its own should work.
[arduplane.zip](https://github.com/ArduPilot/ardupilot/files/15170342/arduplane.zip)

**Comment by Target0815** [comment]
Looks the best so far. However, I still have to test it tomorrow outdoors with a GPS fix.

**Comment by Merga189** [comment]
Works here without arming and without GPS.

RATIO to 0.2 for quite reasonable values VSpd and Alt. x.x m/s and x.x m.

But how to verify?

**Comment by Target0815** [comment]
> RATIO to 0.2 for quite reasonable values VSpd and Alt. x.x m/s and x.x m.

So only 20% of the respective value would be displayed? Because according to the EdgeTX manual:

Ratio: Specifies the ratio value to multiply with the sensor value as needed by some sensors.

> But how to verify?

I will compare with another Vario sensor. oXs would be a candidate or like here a Radiomaster ER8GV.

**Comment by andyp1per** [comment]
> Works here without arming and without GPS.
> 
> RATIO to 0.2 for quite reasonable values VSpd and Alt. x.x m/s and x.x m.
> 
> But how to verify?

vspd is an exponential value, so simple multiplication will not give you correct values. You really need EdgeTX to decode this properly.

image

**Comment by Target0815** [comment]
Alt (ID 9) is still strange here. Immediately after resetting the telemetry, -380 m is displayed here. Mostly values in the minus range.

There is another Alt value (ID 2/4) which is approximately at the height of the location (27 m).

**Review by tridge — APPROVED** [review]

**Comment by tridge** [comment]
can be merged once testing passes

**Comment by andyp1per** [comment]
> Alt (ID 9) is still strange here. Immediately after resetting the telemetry, -380 m is displayed here. Mostly values in the minus range.
> 
> There is another Alt value (ID 2/4) which is approximately at the height of the location (27 m).

For ID9 to be displayed correctly your TX needs to know how to decode it

**Comment by andyp1per** [comment]
Tested ok. Can be merged now.

**Comment by Matvey546436** [comment]
I flashed my speedy bee and the 405 wing is a test firmware. and Vspd shows random values, although mission planner displays correctly in the status window
photo_5449693189838597147_y
photo_5449693189838597146_y
photo_5449693189838597145_y
photo_5449693189838597144_y

**Comment by Frank0587** [comment]
I think there is still a little/big endian issue in the code. 
A Ratio of 0.1 means in OpenTx  a factor of 1/255 (and not 10%). Therfore this ratio acts like a 8bit right shift, so the upper bytes is used as lower byte. For values <255 (altitude = 25.5m) this "workaround" is ok. But a code fix will be better... #28478

**Pull request merged**
