### PR TITLE
Nav_EKF3: varInnovBodyVel assigned the innovation covariance, rather …

### LINKED ISSUE #12702: In EKF3 body odometry, the inverse innovation covariance is used in Chi2 test
In the body frame velocity update, varInnovBodyVel is assigned the inverse innovation covariance (CPCt + R)^-1, but then used as if it were (CPCt + R) in the Chi2 test

**Version**
a08443ff19

**Platform**
[ x] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
all

**Hardware type**
all

### PR DESCRIPTION
**Pull request by dmagree**
…than inverse

fixes #12702. Affects the Chi2 test only

### CODE REVIEW

**Comment by rmackay9** [comment]
@dmagree, very nice to see you digging this deeply into the EKF!

**Comment by rmackay9** [comment]
@dmagree, do you have any test results that show the before and after?  I think that could make it easier to review if we can see the problem and the fix.

**Comment by dmagree** [comment]
I don't right now. I may be able to produce some simulation results, but not sure when.

**Comment by peterbarker** [comment]
Merged, thanks!

**Comment by rmackay9** [comment]
This is marked for backporting to Copter-4.0.x but I think it only affects wheel encoders which are only used on Rover so I think I'll leave it out of Copter-4.0.4.  If anyone disagrees please tell me.

**Pull request merged**
