### PR TITLE
AP_VisualOdom: NoopLoop driver (WIP)

### PR DESCRIPTION
**Pull request by rmackay9**
This PR adds an AP_VisualOdom library backend for the NoopLoop (https://www.nooploop.com/) indoor positioning system.

Setup:

- The NoopLoop beacons must be setup so that the system's X-axis aligns with physical North-South because the system cannot provide a yaw attitude meaning we must use the autopilot's built-in compass.  Note that indoors this compass is very likely to suffer from interference from metal objects nearby.
- Connect the NoopLoop tag's 4-pin UART to one of the autopilot's serial ports (i.e. Telem2/Serial2)
- SERIAL2_PROTOCOL = 29
- SERIAL2_BAUD = 921
- VISO_TYPE = 3 (For NoopLoop)
- GPS_TYPE = 0
- EK2_GPS_TYPE or EK3_GPS_TYPE = 3 (do not use GPS)

Optically enable EKF3:
- AHRS_EKF_TYPE = 3
- EK2_ENABLE = 0
- EK3_ENABLE = 1

It may be helpful to adjust these parameters based on the noisiness of the system (we don't know what values are best yet)

- VISO_POS_M_NSE = reduce from 0.2 to 0.1?
- VISO_VEL_M_NSE = increase from 0.2 to 0.3 of 0.5?

So far this has only been lightly bench tested.

### CODE REVIEW

**Comment by rmackay9** [comment]
Rebased on master.

**Comment by peterbarker** [comment]
Not sure this rebase went well; AP_VisualOdom is now down in AP_Vehicle.

**Comment by rmackay9** [comment]
@peterbarker, txs for the feedback, I've moved the visual_odom.update call to AP_vehicle.

**Comment by rmackay9** [comment]
It looks like the Z-axis position report from the sensor is +ve upwards so we've got to fix this driver.

**Comment by rmackay9** [comment]
Peter Barker has provided a simulated backend and this now works, thanks!

**Comment by chobitsfan** [comment]
Hi @rmackay9 Thank you
I made a little changes and tested flying it in PosHold mode. Would you mind if I create a PR based on your branch to describe my changes?

**Comment by rmackay9** [comment]
@chobitsfan, that sounds great, thanks!

**Comment by rmackay9** [comment]
Closing in favour of @chobitsfan's PR, thanks!

**Pull request closed without merging**
