### PR TITLE
Plane: combine trigger for VTOL/GLideSlope land abort between MAVLink and SW

### PR DESCRIPTION
**Pull request by magicrub**
This is option two, where option 1 is to just make an additional AUX SW via PR https://github.com/ArduPilot/ardupilot/pull/23199

### CODE REVIEW

**Comment by tridge** [comment]
looks good to me. What testing has it had?

**Comment by magicrub** [comment]
No testing. Looking for volunteers!

**Comment by Hwurzburg** [comment]
I have SILT tested:
continuing after PAYLOAD_PLACE lands
aborting PAYLOAD_PLACE during its descent phase
aborting a QRTL (does nothing...correctly)
aborting a glide slope FW landing....aborts and goes around as expected
anything else need testing? I assume the MAV CMD works since nothing was changed

**Review by Hwurzburg — APPROVED** [review]
approved...

**Comment by magicrub** [comment]
@Hwurzburg Thanks for testing!

**Pull request merged**
