### PR TITLE
move to using tool instead of tools program group

### PR DESCRIPTION
**Pull request by bugobliterator**
Some file system formats are case insensitive, like macOS where the system is case aware but case insensitive. This creates an issue when building tools, as we have a directory where the Tools objects are placed under `Tools/CPUInfo` directory and when time comes to generate binary `tools\CPUInfo` things don't go well as the binary name conflicts with directory name.

### CODE REVIEW

**Comment by peterbarker** [comment]
Sorry, still not understanding what the conflict is.

What's the binary name and what's the directory name which is conflicting?

**Comment by bugobliterator** [comment]
> What's the binary name and what's the directory name which is conflicting?

`Tools\CPUInfo` directory where compiled objects are placed conflicts with `tools\CPUInfo` executable. Same would happen with Replay, but currently not built in macos.

**Comment by andyp1per** [comment]
100% this change!

**Comment by peterbarker** [comment]
What's creating the little-l directory?

```
pbarker@bluebottle:~/rc/ardupilot(master)$ ls build/linux/
ap_config.h  ap_version.h  gen-bindings  lib  libraries  tools  Tools
```

Coz yeah, that sucks.

**Comment by bugobliterator** [comment]
> What's creating the little-l directory?

You mean little "T" directory, that's the directory for program group, generated binaries was being placed in "tools" directory, we want to move that to "tool"

**Comment by peterbarker** [comment]
> > What's creating the little-l directory?
> 
> You mean little "T" directory, that's the directory for program group, generated binaries was being placed in "tools" directory, we want to move that to "tool"

Shouldn't the tools end up in the `bin` directory like the normal binaries?

**Comment by bugobliterator** [comment]
> > > What's creating the little-l directory?
> > 
> > 
> > You mean little "T" directory, that's the directory for program group, generated binaries was being placed in "tools" directory, we want to move that to "tool"
> 
> Shouldn't the tools end up in the `bin` directory like the normal binaries?

Yes, the final .apj, .bin and .hex does, but ELF file is always generated inside the program_group directory, for instance `bootloader` ELF is put in `bootloader/` directory same for AP_Periph and examples group. Only `bin` program_group gets ELF put in bin directory.

**Review by tridge — CHANGES_REQUESTED** [review]
git grep /tools still shows some matches, for example:
```
Tools/Replay/check_replay_branch.py:        subprocess.check_call(["./build/sitl/tools/Replay", logfile_path])
Tools/autotest/arducopter.py:        util.run_cmd(['build/sitl/tools/Replay', current_log_filepath],
```

**Comment by tridge** [comment]
alternatively we could consistently use Tools with a capital, might be simpler

**Comment by bugobliterator** [comment]
> alternatively we could consistently use Tools with a capital, might be simpler

Sorry, don't understand how that will help. the collision is between `Tools/CPUInfo` directory and `tools/CPUInfo` executable. Using Tools, will only make this an issue on other Filesystems as well, wouldn't it?

**Comment by bugobliterator** [comment]
> Tools/Replay/check_replay_branch.py

Fixed

**Comment by bugobliterator** [comment]
@peterbarker @tridge I have also added following notification to developers which is displayed if they use `tools` instead of `tool` in target name. So as to not leave any confusion on developers side.

`"tools" name has been replaced with "tool" for build please use that!`

**Comment by khancyr** [comment]
how could you have a collision ? one is marked as executable and not the other so it is weird that you got and error on this ?

**Comment by bugobliterator** [comment]
> how could you have a collision ? one is marked as executable and not the other so it is weird that you got an error on this ?

you can't have files and/or folders of exact same name in the same directory. You can easily test this by creating a directory of the same name besides and executable, you will get an error.

**Review by tridge — APPROVED** [review]

**Pull request merged**
