### PR TITLE
use zero length flexible arrays in unions

### PR DESCRIPTION
**Pull request by tridge**
this works with gcc 6.1 and with asan. 
Using a length of 1 makes coverity unhappy and breaks with asan

### CODE REVIEW

**Comment by magicrub** [comment]
oh geez, that feels worse

**Comment by WickedShell** [comment]
Yeah... How does that actually fix things?

**Comment by lucasdemarchi** [comment]
It's a GCC extension. But I'm not sure this works in clang. Need to check.

**Comment by OXINARF** [comment]
@lucasdemarchi It passed the clang builds without even a warning

**Comment by tridge** [comment]
the reason it works is an array of length 1 is treated as having exactly length 1 by tools like coverity and asan. An array of length zero is treated as having any length, which is what we want.
In gcc prior to version 6 you could use flexible arrays in unions, which are the "bytes[]" syntax. In gcc6 support for those was removed from unions. So now the only option left for the semantics we want is zero length arrays.

**Comment by tridge** [comment]
pushed

**Pull request closed without merging**
