### PR TITLE
add two new horizon31.com boards

### PR DESCRIPTION
**Pull request by climr**
PixC4-Pi and PixC4-Jetson

### CODE REVIEW

**Review by khancyr — COMMENTED** [review]
Commit message would gain some love

**Review by peterbarker — CHANGES_REQUESTED** [review]
@khancyr is correct - commit message should be `AP_HAL_Chibios: add two new horizon31.com boards`

@climr let me know if you'd like me to fix that up for you.,

**Comment by climr** [comment]
@peterbarker yes please. Thank you!!

**Review by tridge — APPROVED** [review]

**Comment by peterbarker** [comment]
Merging.

**Comment by peterbarker** [comment]
@climr apologies - had to change the allocated IDs as the Kakute board got in ahead of yours.

**Pull request merged**
