### PR TITLE
Autotest: new autotest implementation

### PR DESCRIPTION
**Pull request by khancyr**
rebase from https://github.com/ArduPilot/ardupilot/pull/6284

It create a base abstract class Autotest that should implement what can be shared between vehicle.
It will permit to develop more test, specially for mavlink feature !

### CODE REVIEW

**Comment by khancyr** [comment]
this overseed https://github.com/ArduPilot/ardupilot/pull/7343

**Comment by peterbarker** [comment]
Hmmm.

I think we need to compare your efforts here with my PR.  I can see several cleanups in mine which aren't in here, and I'm sure there must be cleanups in yours that aren't in mine.

 - self.home handling is neater
 - self.options isn't present in mine
 - self.progress in mine (I've customised/overridden this in various branches here to provide timing information)

If we were to pull my PR in, what would we then need to do to get whatever cleanups/functionality you've added in this PR?

**Comment by khancyr** [comment]
@peterbarker I did : 
- base and abstract class for more common code and force implentation on each vehicle
- implement a first set of common tests
- correct some test due to the new structure
- add more tests

But we can go directly on you version, let's merge it. I will redo my change on top of it

**Comment by khancyr** [comment]
rebased and little pep8 clean

@peterbarker I didn't find much differences with what you had done on yours.

**Comment by khancyr** [comment]
rebased and remove new test, just keep the structure change!

**Comment by peterbarker** [comment]
Currently breaks both Plane and Sub.

Plane is a trivial fix.  Sub less so.

**Comment by khancyr** [comment]
problem solved, I miss that sub was disabling GCS FS, so I readd it

**Comment by khancyr** [comment]
@peterbarker ready !

**Comment by khancyr** [comment]
rebased on master

**Comment by khancyr** [comment]
closed by https://github.com/ArduPilot/ardupilot/pull/7928

**Pull request closed without merging**
