### PR TITLE
Copter: pre-arm check that rally points are within fence

### PR DESCRIPTION
**Pull request by rmackay9**
During Copter-3.4 beta testing we found that the vehicle would attempt to fly to a Rally point even if it was outside the fence.  Worse yet, if it was 100m outside the circular fence the vehicle would switch to land before reaching the rally point.  This pre-arm check stops the vehicle from arming if the rally points are outside the circular and/or pollygon fences (if the fences are enabled).

### CODE REVIEW

**Comment by OXINARF** [comment]
I would like to have an arming check for this but I think we are out of bits? I'm not sure if we can change the size of the parameter without a problem or not.

The reason I would like that is because I imagine people could have rally points they don't want to delete and still want the fence to be enabled. For example, you have rally points set for the place where you normally fly but you go fly at a different place and want to have a fence - it would be normal you didn't want to delete the rally points (and possibly they would be excluded from RTL thanks to the RALLY_LIMIT_KM param).

I think another way to go at this would be to add the check in AP_Rally to also check the fence beside RALLY_LIMIT_KM, but that would need Plane and Copter to subclass AP_Rally since their fences are different.

@rmackay9 do you know how Plane handles this problem?

**Comment by rmackay9** [comment]
@OXINARF, you're right that we don't have enough bits in the arming-check.  That could be handled as part of the move of copter to the ap-arming library but I just can't get it high enough on my to-do list.

My guess is that plane doesn't check this issue so it will likely try to fly to the rally point but then hit the fence and return to the polygon fence's return point.

You raise a very good point about the rally-limit-km parameter although the problem is the rally-limit-km is a distance from the vehicle so to check it properly we would need to find the closest point on the fence's edge to the rally-point and then exclude the rally-point from the check if it's farther than rally-limit-km.  Doing this would perhaps resolve your concern because far-away rally points (perhaps at the user's other flying field) wouldn't be checked.

**Comment by OXINARF** [comment]
@rmackay9 that would, at least, make it much better.
My last idea in the previous post was to make the AP_Rally ignore rally points outside the fence, that way we wouldn't need the pre-arm check (maybe just have it as a warning).

**Comment by rmackay9** [comment]
@OXINARF, I've merged this but added an issue regarding how the pre-arm check is too strict.  https://github.com/ArduPilot/ardupilot/issues/4421

Sorry, for going ahead with it but I didn't want the "perfect to be the enemy of the good".  Basically the check is a bit too strict but it's better than having no check at all.  The maths are a bit complex to calculate how far outside the polygon fence is.. at least it's more complex than I can immediately figure out.  Perhaps @dricketts and @lthall can come up with a function that we can add to AC_Polygon_loader that calculates the distance to the closes edge and then we can relax the check.  https://github.com/ArduPilot/ardupilot/blob/master/libraries/AC_Fence/AC_PolyFence_loader.h

**Comment by OXINARF** [comment]
No problem. What do you think about the idea to just ignore rally points outside the fences (and removing the pre-check then)?

**Comment by rmackay9** [comment]
@OXINARF, as discussed on the dev call today, I think we will go with your suggestion to just ignore rally points outside the fence (for copter) and remove the pre-arm check (except maybe in cases where the RALLY_INCL_HOME is zero?).

**Comment by OXINARF** [comment]
@rmackay9 When you don't have any rally point you will go home even if RALLY_INCL_HOME is zero. So I think that if rally points are outside the fence they are out no matter what.

**Comment by dricketts** [comment]
I'm not sure if this is still useful, but the following function computes the closest point on a line segment to a given point:

https://github.com/ArduPilot/ardupilot/blob/master/libraries/AC_Avoidance/AC_Avoid.cpp#L211

It would be easy to iterate over all edges in the fence to find the closest point on the fence.

**Pull request merged**
