### PR TITLE
Copter: set_range on motor interlock channel

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by peterbarker** [comment]
I introduced a regression when the default parameters were used on a Heli; channel 8 is used as a range channel on Helicopters for the interlock.  Kind of.

The fix here will also mean the interlock will work if you put it on channels other than 5,6,7,8 - those were "magic" range-value channels which my previous patch removed.

**Comment by bnsgeyer** [comment]
We will have to rework this once my motor interlock fix pr goes in as this logic is moved.

**Comment by peterbarker** [comment]
@bnsgeyer I'll do the rebase if you like when it comes to it.

**Comment by peterbarker** [comment]
Rebased this.

**Comment by peterbarker** [comment]
Nudge @bnsgeyer Heli on master is kind of broken without this.  You can run the autotest suite yourself to verify this.

```
time ./Tools/autotest/autotest.py build.Helicopter fly.CopterAVC.AVCMission
```

**Comment by bnsgeyer** [comment]
Sorry, I did look at this the other night.  It appears to work fine. Is this getting backported to 4.0?

**Comment by peterbarker** [comment]
@bnsgeyer Only a problem in master, thankfully.

**Comment by rmackay9** [comment]
TBH, I'm not a huge fan of where this is placed inside of a get_ function.  I wouldn't normally expect a get_ function to have side effects.  I'm surprised this doesn't cause problem for a const function actually.

**Pull request merged**
