### PR TITLE
AP_OSD: Switch screens basing on ARM state

### PR DESCRIPTION
**Pull request by SergeyBokhantsev**
This is alternative implementation for OSD screen switching basing on discussion in https://github.com/ArduPilot/ardupilot/pull/10679

### CODE REVIEW

**Comment by SergeyBokhantsev** [comment]
3 settngs added:
- ARM_SCREEN, DSARM_SCREEN: If set, then screen will be shown on arm/disarm screen correspondingly
- FS_SCREEN: if set then screen will be shown on failsafe event (radio/battery). After/if FS will be cleared then the screen that was displayed before FS event will be shown again.
User still can use any of OSD_SW_METHOD to switch screens.
@sh83

**Comment by sh83** [comment]
Thank you. I do not see any problem with this pr.

**Comment by tridge** [comment]
unfortunately due to a recent github change this needs a rebase before it can be merged

**Comment by SergeyBokhantsev** [comment]
@tridge rebase done

**Pull request merged**
