### PR TITLE
new board - GEPRC_TAKER_H743

### PR DESCRIPTION
**Pull request by YI-BOYANG**
Add a new board from GEPRC_TAKER_H743
image

### CODE REVIEW

**Review by andyp1per — APPROVED** [review]
LGTM

**Comment by Hwurzburg** [comment]
@YI-BOYANG when you are finished making changes to this PR (ie stop pushing new commits), let me know and I will review

**Comment by YI-BOYANG** [comment]
> @YI-BOYANG when you are finished making changes to this PR (ie stop pushing new commits), let me know and I will review

The modifications are now complete.

**Review by Hwurzburg — CHANGES_REQUESTED** [review]
You will also need to squash the commits into two commits...one titled Tools: add GEPRC_TAKER_H743 containing files changed in the Tools library
and another
hwdef: add GEPRC_TAKER_H743 for all the other files in that library

**Comment by YI-BOYANG** [comment]
> You will also need to squash the commits into two commits...one titled Tools: add GEPRC_TAKER_H743 containing files changed in the Tools library and another hwdef: add GEPRC_TAKER_H743 for all the other files in that library

I have modified it according to your suggestion, but I am not familiar with the operation of rebase, is there any developer who can help me complete rebase?

**Comment by Hwurzburg** [comment]
@YI-BOYANG I have squashed and split into the two library commits required for you....if this has been tested, I will mark for DEVCALL review

**Comment by YI-BOYANG** [comment]
> @YI-BOYANG I have squashed and split into the two library commits required for you....if this has been tested, I will mark for DEVCALL review
The test has been completed before, this modification is not big, I think maybe the previous test results will not be affected.

**Review by Hwurzburg — APPROVED** [review]

**Pull request merged**
