### PR TITLE
Add option to allow arming on centered throttle controllers when using a switch or mav command

### PR DESCRIPTION
**Pull request by Hwurzburg**
makes arming HWing a lot easier....rudder arming is still allowed at low throttle

### CODE REVIEW

**Comment by Hwurzburg** [comment]
I would like to constrain this to auto-throttle modes in Plane and in Copter, but will need some pointers...Rover would not use this as it arms already at center, I think due to reversing

**Comment by IamPete1** [comment]
I'm not that keen, as you say at the least it needs to be auto throttle modes only.

**Comment by WickedShell** [comment]
> I'm not that keen, as you say at the least it needs to be auto throttle modes only.

And once it's automodes only it just makes the interaction of remembering the rules for each mode just a bit more complicated. I'd skip it personally...

**Comment by peterbarker** [comment]
On Mon, 16 Aug 2021, Peter Hall wrote:

> I'm not that keen, as you say at the least it needs to be auto throttle modes only.

This is not an intractable problem; we've had sprung throttles in Copter 
for a long time.  Of course, I think it's currently broken on Solo, for 
example...

**Pull request closed without merging**
