### PR TITLE
WIP: add support for quadmotor tailsitters

### PR DESCRIPTION
**Pull request by kd0aij**
adds 2 new motor functions, k_throttleTop and k_throttleBot
and implements them in tailsitter.cpp, along with reductions in control surface gains when in VTOL mode at high roll or pitch angles (assuming that means high airspeed)

Tested in RF8 with this model: Stryker_quad_APM_AV.RFX in the SITL_Models repo here:
https://github.com/ArduPilot/SITL_Models/tree/master/RealFlight/markw/Tailsitters/DuoMotorTailsitters

RF8 screen capture: https://youtu.be/dDfmZhdMK2w

### CODE REVIEW

**Comment by kd0aij** [comment]
motors 1-4 when pitched 90 degrees in VTOL modeL
90deg_pitch_vtol

**Comment by sh83** [comment]
There is two different quadmotor tailsitter configuration.
The first one with left/right/updown motor.
The second one with two motors above wing and two motors below wing.
Which configuration is supported here?

**Comment by sh83** [comment]
I see, thanks. Just to shutdown motors is inefficient solution, should be better way to deal with ff.

**Comment by kd0aij** [comment]
simulated forward transition with hover at 75% throttle, top/bot motors shut down when the forward transition is complete (must add throttle at that point to maintain altitude):
https://youtu.be/58r7yQ1W1T4

**Comment by kd0aij** [comment]
@tridge Based on our conversation yesterday, I conditioned hover throttle learning on is_tailsitter()

**Comment by OXINARF** [comment]
@kd0aij It's Plane autotest that is failing (quadplane is passing though). I would say that Plane SITL is dying right after boot. Have you tried it on your end? The command running in Travis is `"/home/travis/build/ArduPilot/ardupilot/build/sitl/bin/arduplane" "-w" "-S" "--home" "-35.362938,149.165085,585,354" "--model" "plane-elevrev" "--speedup" "10" "--defaults" "/home/travis/build/ArduPilot/ardupilot/Tools/autotest/default_params/plane-jsbsim.parm"`

**Comment by kd0aij** [comment]
@OXINARF  Thanks, that showed a segfault caused by my changes.

**Pull request closed without merging**
