### PR TITLE
AP_HAL_Linux: Support parrot mambo minidrone

### PR DESCRIPTION
**Pull request by chobitsfan**
some barometer and motors control code are copied from [paparazzi](https://github.com/paparazzi/paparazzi)

fly in altitude hold mode [video](https://youtu.be/4NtlH5p-2fw)
fly in guided mode [video](https://youtu.be/AHmkaYnrFpY)

Please be careful because I am still testing it

1. download [toolchain](https://sourcery.mentor.com/GNUToolchain/package12813/public/arm-none-linux-gnueabi/arm-2014.05-29-arm-none-linux-gnueabi-i686-pc-linux-gnu.tar.bz2). it lacks arm-none-linux-gnueabi-pkg-config, you can copy it from [toolchain in parrot-developer](https://github.com/Parrot-Developers/toolchains/blob/master/parrot-tools-linuxgnutools-2012.03_1.0.0-1_i386.deb). or you can just comment out 
`cfg.find_toolchain_program('pkg-config',` var='PKGCONFIG')`
in boards.py
2. flash mambo with education firmware from [parrot-developer](https://github.com/Parrot-Developers/MinidronesEdu).  you need this for bluetooth PAN connection
3. ./waf configure --board mambo --static
4. ./waf copter
5. power on mambo, connect it to Linux PC through USB. mambo will be 192.168.2.1. telnet it and mkdir /data/edu/ardupilot. use ftp to copy arducopter binary (do not forget to strip it) and Tools/Frame_params/Parrot_Mambo.param to /data/edu/ardupilot/. rename Parrot_Mambo.param to mambo.parm
6. (in mambo) kk; pstop delosd; pstop ledd
7. (in mambo) pstart bleproxy; ifconfig bnep 192.168.3.1 netmask 255.255.255.0 up
8. follow instructions from [parrot](https://github.com/Parrot-Developers/MinidronesEdu/blob/master/mambo-2.6.11/README.bluetooth.md) or [mathworks](https://www.mathworks.com/help/supportpkg/parrot/ug/connect-parrot-mambo-minidrone-to-computer-using-bluetooth.html) to connect mambo to PC through bluetooth. You may need to manual config IP (for example, 192.168.3.2) and netmask of your PC
9.  (in mambo) arducopter -A udp:192.168.3.2:14550. You can launch Mission Planner to control it now.

Issues:
1. compass is not supported
2. both optical flow and sonar are not supported
3. most features are disabled. I am still testing loiter mode with external motion capture system

### CODE REVIEW

**Comment by tridge** [comment]
thanks!
I've ordered one as well so I can have a play

**Comment by chobitsfan** [comment]
hi @tridge thank you
These code are still experimental. I am still testing it. Please be careful

**Comment by lucasdemarchi** [comment]
@chobitsfan first comment is to not add ifdef in the Copter's task table. Even if you don't have that in your drone, it should cope well with that without the need to ifdef it out.

**Comment by chobitsfan** [comment]
@lucasdemarchi  I got it. You are right, thank you.
I disable many task because otherwise arducopter too much CPU time (50%+). I am still investigate the cause.

**Comment by lucasantoro** [comment]
is it possible to have a tutorial to implement ardupilot? There are some steps that are not very clear due to my limited experience.
Thank you very much for your attention

**Pull request closed without merging**
