### PR TITLE
WIP: Add support for 6 DShot outputs to the IOMCU

### PR DESCRIPTION
**Pull request by mirkix**
**WIP do not merge**

This PR adds 6 additional DShot outputs to the IOMCU. As the result we can use up to 12 DShot outputs with i.e. a CubeBlack or other autopilots that use an IOMCU.

What will work:
* Up to 6 DShot outputs with DSHOT150 and DSHOT 300
* To timer and dma dependencies output 1,2,5,6,7,8 can be used for DShot
* DShot telemetry requests 

What will not work:
* DSHOT600 and DSHOT 1200, padding must be checked
* BlHeli pass through because of the hardware that is used (only output signals are possible)

### CODE REVIEW

**Comment by tridge** [comment]
really nice work! Just need to solve the extra pulses puzzle

**Comment by tridge** [comment]
I've rebased this and been doing some testing. I'm getting some quite strange results. With no RC input connected it did work a few times, but when I have RC in connected I get quite a few resets of the IOMCU. I suspect it is running out of memory.
I'll do some more testing soon

**Comment by dkemxr** [comment]
I have tried a version of this on a Pixhawk (fmuv3) but I'm not seeing Dshot from the outputs. I configured a Hexa with outputs on Main 1,2,5,6,7,8 set MOT_PWM_TYPE to Dshot150, selected those channels in the BLH Mask and set Dshot150 with the Otype parameter. I'm scoping the outpurts, no ESC connected and I see standaed PWM.

**Comment by mirkix** [comment]
@dkemxr Did you execute `Tools/scripts/build_iofirmware.py` before you compile the PR for fmuv3?

**Comment by dkemxr** [comment]
Mirko-I used a version compiled by Mark Whitehorn as I can't do that. I'll be happy to try any compiled version, I have a bench setup to test it on.

**Pull request closed without merging**
