### PR TITLE
Copter: correct ACRO_RP_EXPO constraint range

### PR DESCRIPTION
**Pull request by Hwurzburg**

### CODE REVIEW

**Review by rmackay9 — APPROVED** [review]
This looks correct to me but I'd like a second opinion from @lthall

**Comment by lthall** [comment]
The parameter definition is correct it is the constraint that is wrong:
https://github.com/ArduPilot/ardupilot/blob/master/ArduCopter/mode_acro.cpp#L114

**Review by rmackay9 — CHANGES_REQUESTED** [review]
Oops, I guess we need to fix the constraint to match this -0.5 to 1.0 range.

**Comment by rmackay9** [comment]
Unfortunately I think that now we need to test it.  I'm hoping to do that soon-ish..

**Pull request merged**
