### PR TITLE
AP_Param: always use set method, remove `=`

### PR DESCRIPTION
**Pull request by IamPete1**
This removes the inline `=` methods for params replacing with `set()`. Mainly because I was trying to track down where we should be setting the default along with the value. 

I do think this is a improvement, makes it clear if a value is a param. Should be no change in bahavour.

Note that this omits the ones converted to `set_and_default` in https://github.com/ArduPilot/ardupilot/pull/20972 so won't build yet.

### CODE REVIEW

**Comment by magicrub** [comment]
How does this effect size?

**Comment by IamPete1** [comment]
Also removed vector params. Moved param template functions to cpp for nice flash saving.

**Review by andyp1per — CHANGES_REQUESTED** [review]
I'm dead against this. I think this makes the code less readable and does not provide any tangible benefit. The operator overloads exist specifically to make the code more user-friendly and I believe this takes it in the opposite direction. The removal of inlining for a big flash gain is a huge win though!

**Comment by IamPete1** [comment]
The param template messing was causing periph to overflow, this PR is getting big, so I have pulled that out for a future PR.  https://github.com/IamPete1/ardupilot/commit/c004647220fb604d05e2d487b0fc94df5fb9b3ca It saves 5K on 2M boards, 1.4K on 1M boards but costs 220 bytes on periph.

**Comment by IamPete1** [comment]
No flash cost on 1M boards, 
```
Binary Name      Text [B]     Data [B]     BSS (B)      Total Flash Change [B] (%)      Flash Free After PR (B)
---------------  -----------  -----------  -----------  ----------------------------  -------------------------
antennatracker   0 (0.0000%)  0 (0.0000%)  0 (0.0000%)  0 (0.0000%)                                      603232
arducopter-heli  0 (0.0000%)  0 (0.0000%)  0 (0.0000%)  0 (0.0000%)                                      178016
ardurover        0 (0.0000%)  0 (0.0000%)  0 (0.0000%)  0 (0.0000%)                                      361128
arducopter       0 (0.0000%)  0 (0.0000%)  0 (0.0000%)  0 (0.0000%)                                      185736
ardusub          0 (0.0000%)  0 (0.0000%)  0 (0.0000%)  0 (0.0000%)                                      400300
blimp            0 (0.0000%)  0 (0.0000%)  0 (0.0000%)  0 (0.0000%)                                      662180
arduplane        0 (0.0000%)  0 (0.0000%)  0 (0.0000%)  0 (0.0000%)                                      203416
```
A little on f405
```
Binary Name      Text [B]       Data [B]     BSS (B)        Total Flash Change [B] (%)      Flash Free After PR (B)
---------------  -------------  -----------  -------------  ----------------------------  -------------------------
antennatracker   28 (+0.0042%)  0 (0.0000%)  4 (+0.0031%)   28 (+0.0042%)                                    319456
arducopter-heli  24 (+0.0025%)  0 (0.0000%)  0 (0.0000%)    24 (+0.0025%)                                     36712
ardurover        28 (+0.0033%)  0 (0.0000%)  -4 (-0.0031%)  28 (+0.0033%)                                    129752
arducopter       24 (+0.0026%)  0 (0.0000%)  0 (0.0000%)    24 (+0.0026%)                                     47056
ardusub          28 (+0.0034%)  0 (0.0000%)  4 (+0.0031%)   28 (+0.0034%)                                    169020
blimp            28 (+0.0041%)  0 (0.0000%)  -4 (-0.0031%)  28 (+0.0041%)                                    301428
arduplane        24 (+0.0025%)  0 (0.0000%)  0 (0.0000%)    24 (+0.0025%)                                      7760
```
No cost on periph

**Review by tridge — APPROVED** [review]

**Comment by tridge** [comment]
needs a rebase first, thanks @IamPete1 !

**Comment by IamPete1** [comment]
rebased.

**Pull request merged**
