### PR TITLE
Morse:Made changes to add vehicle following camera

### PR DESCRIPTION
**Pull request by arshPratap**
This PR tries to add a vehicle following camera ,a feature that has been missing from the morse simulations (and also stated [here](https://ardupilot.org/dev/docs/gsoc-ideas-list.html#improve-morse-simulator-integration-including-supporting-boats-rovs)).
Added a blend file so instead of running the simulation from the .py file we can run it from the .blend file.
Here I have added some ss of this feature in action

Screenshot from 2021-02-28 06-59-55
Screenshot from 2021-02-28 07-00-15

### CODE REVIEW

**Comment by magicrub** [comment]
So, does this give it a default view? What needs to change on the wiki?

**Comment by arshPratap** [comment]
> So, does this give it a default view? What needs to change on the wiki?

yes @magicrub  sir,the quadcopter gets a default vehicle-following view.Although I just realized there are some potential issues that might come up with this commit,if you dont mind sir ,can I work on this commit a little while longer.Thanks again

**Comment by rishabsingh3003** [comment]
This is awesome! I actually tried doing this a while back and I couldn't figure out how to do it. So really awesome that you found a way.
A query though:

- I see you're directly running this off blender, and not using the Python API. Does this mean that the map is permanently fixed? Currently I can change maps, make custom maps very easily and all I have to do is provide the path to the python script. So does this mean if I have to simulate a new environment, I must tweak its blender file?
 
Also can you give a brief description on how to run this ? Thanks!

**Comment by arshPratap** [comment]
@magicrub ,@rishabsingh3003 I have submitted a new PR(#16779) that serves as a modification to this one and also I have answered all the queries there.Please do take a look .Thanks !

**Pull request closed without merging**
