### PR TITLE
AP_FENCE: adjusted AP_GROUPINFO so that rover has not altitude fence …

### PR DESCRIPTION
**Pull request by amilcarlucas**
…anymore

Min and max altitude fences make no sense for the rover/boat  vehicles

### CODE REVIEW

**Comment by khancyr** [comment]
LGTM !

**Comment by rmackay9** [comment]
AC_Fence isn't included in anything but Copter and perhaps sub of course.. so a bit of a non-op for the moment I think..

**Comment by khancyr** [comment]
Well, if we can get rid of inertialnav, fence will be in rover, so for me it works !

**Comment by OXINARF** [comment]
Like @rmackay9 I don't understand this PR, AC_Fence isn't a parameter group in Rover...

**Comment by khancyr** [comment]
Can be close. I add this in https://github.com/ArduPilot/ardupilot/pull/6775

**Comment by rmackay9** [comment]
Merged, thanks!

By the way I made the following changes while merging:

- removed Plane from the ALT_MAX parameter because Plane doesn't use AC_Fence
- removed changes to the ALT_MIN parmeter because Copter does not support a minimum fence yet

**Pull request closed without merging**
