### PR TITLE
COPTER: Fix MOUNT_CONTROL command yaw response

### PR DESCRIPTION
**Pull request by Pedals2Paddles**
In response to MAV_CMD_DO_MOUNT_CONTROL or MSG_MOUNT_CONTROL in guided mode, or DO_MOUNT_CONTROL in missions.... If the mount instance doesn't support camera panning, the copter is supposed to yaw instead.  For some reason, this was missing from the GCS and Mission commands handling.  So in both guided and missions, the gimbal would tilt correctly, but copter yaw never moved.  I'm surprised nobody noticed this bug, but MOUNT_CONTROL probably has a fairly limited set of users.

These two patches implement the copter yaw when the mount instance does not have panning support.  It does so by calling the same yaw controller that CONDITION_YAW uses.  I've tested this repeatedly, and it worked as intended.

This will close https://github.com/ArduPilot/ardupilot/issues/6272

### CODE REVIEW

**Comment by Pedals2Paddles** [comment]
@rmackay9, this is pretty important bug fix for co-computers and the smart shots on Solo.  Can this get into master and backported to 3.5.5?

**Comment by lvale** [comment]
@Pedals2Paddles @rmackay9 
Shouldn't the yaw limits for the mount be checked? If you try to yaw beyond the limits of the gimbal yaw, what should be done? Yaw gimbal to the limit (usually gimbals don't like that) and the rest vehicle yaw ?

**Comment by Pedals2Paddles** [comment]
That sounds logical. But wouldn't that be for the mount library to handle? This is just the copter yaw where a gimbal has no pan control.

In fact it doesn't appear the mount libraries have any means to do what your suggesting. And in fact it looks like all of them indicate they have no pan control. How are people with pan controllable gimbals even using them?

**Comment by githubtd01** [comment]
I think this fix has something to do with a problem I'm having with do_mount_control:
https://discuss.ardupilot.org/t/mission-do-mount-control-impacts-yaw-of-copter-bug-or-feature/37497

**Comment by Pedals2Paddles** [comment]
I responded in the discuss thread.

**Pull request merged**
