### PR TITLE
HAL_ChibiOS: enable MatekF765 LED pin

### PR DESCRIPTION
**Pull request by tridge**
waiting on testing by Matek

### CODE REVIEW

**Comment by MATEKSYS** [comment]
Tonealarm with Active buzzer and Passive buzzer. both work.  Tone of passive buzzer is better.
2812LED,  seems it works. only the first LED works on 8xLED strip
BMP388 on I2C2, it works while the builtin BMP280 is desoldered.  BMP388 and BMP280 can't share same I2C.
MS5611 on I2C2, it works whether BMP280 is connected or desoldered.  GND_PRIMARY = 0 //BMP280,   GND_PRIMARY = 1 //MS5611

**Comment by MATEKSYS** [comment]
Tonealarm with Active buzzer and Passive buzzer. both work. Tone of passive buzzer is better.
2812LED, seems it works. only the first LED works on 8xLED strip
BMP388 on I2C2, it works while the builtin BMP280 is desoldered. BMP388 and BMP280 can't share same I2C.
MS5611 on I2C2, it works whether BMP280 is connected or desoldered.

**Comment by tridge** [comment]
> Tonealarm with Active buzzer and Passive buzzer. both work. Tone of passive buzzer is better.

great

> 2812LED, seems it works. only the first LED works on 8xLED strip

Support for Lua scripting with up to 32 LEDs on one pin is pending in #12716

> BMP388 on I2C2, it works while the builtin BMP280 is desoldered. BMP388 and BMP280 can't share same I2C.
> MS5611 on I2C2, it works whether BMP280 is connected or desoldered.

ok, thanks for testing, I'll merge

**Comment by rmackay9** [comment]
this has been added to Copter-4.0.0-rc3

**Pull request merged**
