### PR TITLE
AP_Compass: add LIS3MDL probe for Pixracer

### PR DESCRIPTION
**Pull request by kd0aij**
depends on https://github.com/ArduPilot/PX4Firmware/pull/83

### CODE REVIEW

**Comment by tridge** [comment]
looks good! just need to confirm the orientation

**Comment by kd0aij** [comment]
orientation of LIS3MDL verified to be ROTATION_NONE by inspection of board

also, plots of x/y/z values for both compasses shows the same behavior as board orientation is changed

**Comment by kd0aij** [comment]
updated and corrected comments here and in https://github.com/ArduPilot/PX4Firmware/pull/83
I think this is ready to merge now

**Comment by tridge** [comment]
looks good, thanks!

**Comment by kd0aij** [comment]
Copter build of master for px4-v4 on PixRacer R15:

compass_compare

**Pull request merged**
