### PR TITLE
Allow Vagrant VM to run autotest

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by WickedShell** [comment]
@peterbarker I don't see any handling of the buildlog directory constants in the Tools/autotest/arducopter.py for example. (And that extends to the other vehicle scripts as well I think)

**Comment by khancyr** [comment]
why not use ardupilot install script ?

**Comment by peterbarker** [comment]
@khancyr This is handy during development, and for getting people a quick-development environment.  I'm not sure what it's got to do with an "installed" ardupilot...

**Comment by peterbarker** [comment]
On Wed, 30 Aug 2017, WickedShell wrote:

> @peterbarker I don't see any handling of the buildlog directory constants in
> the Tools/autotest/arducopter.py for example. (And that extends to the other
> vehicle scripts as well I think)

OK... so given I tested Plane to the point that it segfaulted.... I guess 
at some stage we should look at our error handling...

I've pushed up changes for each of the vehicle tests.

**Comment by khancyr** [comment]
@peterbarker I was speaking about https://github.com/ArduPilot/ardupilot/blob/master/Tools/scripts/install-prereqs-ubuntu.sh ! Sorry about the confusion

**Comment by peterbarker** [comment]
Merged it, thanks all.

**Pull request closed without merging**
