### PR TITLE
AP_Motors: fix regression for tiltrotors

### PR DESCRIPTION
**Pull request by kd0aij**
fix suggested by @IamPete1 
tested in SITL with Tridge's tri-motor "Big Stik TiltRotorTri"
Restores original behavior in manual and fbwa modes.

### CODE REVIEW

**Comment by Pedals2Paddles** [comment]
In bypassing the shutdown spool mode, this bypasses the esc shutdown while disarmed (0 PWM). There doesn't appear to be any other functional change since everything after that is the same. Are you sure you want that safety function defeated permanently?

Also, what other vehicles uses this instance of motor output? Because this is likely Changing the function for more than just a tilt rotor.

**Comment by IamPete1** [comment]
this function is only used by tilt rotors currently, will also be tail sitters soon. It is used in forward slight modes so it makes sense to have the copter code spooled down and handle the safety with the plane code

**Comment by kd0aij** [comment]
@Pedals2Paddles Two questions: don't some ESCs complain or behave erratically when receiving no PWM pulses? 
And did ouput_motor_mask originally check the spool mode, or does this "fix" actually restore the original behavior?

**Comment by WickedShell** [comment]
> don't some ESCs complain or behave erratically when receiving no PWM pulses? 

That depends upon the ESC, and can be critical for safety reasons during some interactions with the vehicle (booting, physically connecting PWM lines after powered on). It's definitely something I'm reliant on with quadplanes.

**Comment by kd0aij** [comment]
also look at ARMING_REQUIRE

**Comment by rmackay9** [comment]
Merged, thanks!

**Pull request merged**
