### PR TITLE
AP_Motors: eliminate flags structure

### PR DESCRIPTION
**Pull request by peterbarker**
Saves about 44 bytes of flash at the expense of 2 bytes of RAM.

Subclasses use the accessors.

### CODE REVIEW

**Comment by WickedShell** [comment]
FWIW it's 4 bytes of RAM, AP_Motors goes from 104 bytes to 108 bytes due to alignment reasons. You can however rearrange the class if you want to maintain the 104 byte count, the following patch will result  in no increase in RAM usage from before this PR, and saves a further 64 bytes of flash:

``` diff
diff --git a/libraries/AP_Motors/AP_Motors_Class.h b/libraries/AP_Motors/AP_Motors_Class.h
index 3e4920505e..473e74bbc4 100644
--- a/libraries/AP_Motors/AP_Motors_Class.h
+++ b/libraries/AP_Motors/AP_Motors_Class.h
@@ -200,6 +200,12 @@ public:
                     PWM_TYPE_DSHOT1200  = 7};
     pwm_type            get_pwm_type(void) const { return (pwm_type)_pwm_type.get(); }
     
+private:
+
+    bool _armed;             // 0 if disarmed, 1 if armed
+    bool _interlock;         // 1 if the motor interlock is enabled (i.e. motors run), 0 if disabled (motors don't run)
+    bool _initialised_ok;    // 1 if initialisation was successful
+
 protected:
     // output functions that should be overloaded by child classes
     virtual void        output_armed_stabilizing() = 0;
@@ -256,10 +262,6 @@ protected:
 
 private:
 
-    bool _armed;             // 0 if disarmed, 1 if armed
-    bool _interlock;         // 1 if the motor interlock is enabled (i.e. motors run), 0 if disabled (motors don't run)
-    bool _initialised_ok;    // 1 if initialisation was successful
-
     static AP_Motors *_singleton;
 };

```

CubeOrange results for plane, with some dirty submodules.

|Version|Target       |  Text |    Data|  BSS  |   Total  |
|----|--------------|--------|--------|--------|-------|
|PR|bin/arduplane | 1480708 | 1516 | 129764 | 1611988 |
|With above diff |bin/arduplane | 1480644 |  1516 | 129764 | 1611924 |

**Comment by rmackay9** [comment]
Thanks @WickedShell for the detailed analysis and suggestion.  I'm not actually a fan of the suggested re-ordering to save a few bytes because of the readability cost (in my mind anyway).  I think "private" should always be after "protected" otherwise we end up with developers searching around and getting confused.

**Comment by WickedShell** [comment]
@rmackay9 it's worth noting that it's actually flash size as well. If we move the entire private section up I don't think that's unreasonable. A key note here is that you can't actually assume you are in a private or protected region of a class file based on how far down, you actually have to find the label above it either way. (I do agree that having multiple private sections does make things harder for people)

**Review by rmackay9 — APPROVED** [review]
Looks ok to me.

**Comment by peterbarker** [comment]
We eventually did not create the extra section to save the 100 bytes in here.  Deemed too ugly.

**Pull request merged**
