### PR TITLE
Emit size savings from test_build_options.py script

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by peterbarker** [comment]
```
Disabling EKF3(HAL_NAVEKF3_AVAILABLE) on copter saves 148200 bytes
Disabling EKF2(HAL_NAVEKF2_AVAILABLE) on copter saves 111080 bytes
Disabling DSP(HAL_WITH_DSP) on copter saves 37460 bytes
Disabling MSP(HAL_MSP_ENABLED) on copter saves 30856 bytes
Disabling MOUNT(HAL_MOUNT_ENABLED) on copter saves 26836 bytes
Disabling OSD(OSD_ENABLED) on copter saves 26088 bytes
Disabling OPTICALFLOW(AP_OPTICALFLOW_ENABLED) on copter saves 21064 bytes
Disabling PROXIMITY(HAL_PROXIMITY_ENABLED) on copter saves 19704 bytes
Disabling MSP_DISPLAYPORT(HAL_WITH_MSP_DISPLAYPORT) on copter saves 18496 bytes
Disabling SOLOGIMBAL(HAL_SOLO_GIMBAL_ENABLED) on copter saves 17408 bytes
Disabling ADSB(HAL_ADSB_ENABLED) on copter saves 16528 bytes
Disabling AC_OAPATHPLANNER(AC_OAPATHPLANNER_ENABLED) on copter saves 16504 bytes
Disabling AIRSPEED(AP_AIRSPEED_ENABLED) on copter saves 16480 bytes
Disabling OSD_PARAM(OSD_PARAM_ENABLED) on copter saves 11976 bytes
Disabling VISUALODOM(HAL_VISUALODOM_ENABLED) on copter saves 10392 bytes
Disabling CRSF(HAL_CRSF_TELEM_ENABLED) on copter saves 9168 bytes
Disabling AHRS_EXT(HAL_EXTERNAL_AHRS_ENABLED) on copter saves 9088 bytes
Disabling PICCOLOCAN(HAL_PICCOLO_CAN_ENABLE) on copter saves 7992 bytes
Disabling TEMPCAL(HAL_INS_TEMPERATURE_CAL_ENABLE) on copter saves 7376 bytes
Disabling OPTICALFLOW_PIXART(AP_OPTICALFLOW_PIXART_ENABLED) on copter saves 5600 bytes
Disabling GENERATOR(HAL_GENERATOR_ENABLED) on copter saves 5136 bytes
Disabling GPS_MOVING_BASELINE(GPS_MOVING_BASELINE) on copter saves 5128 bytes
Disabling MODE_ZIGZAG(MODE_ZIGZAG_ENABLED) on copter saves 4576 bytes
Disabling BATTMON_SMBUS(AP_BATTMON_SMBUS_ENABLE) on copter saves 4508 bytes
Disabling SPEKTRUM(HAL_SPEKTRUM_TELEM_ENABLED) on copter saves 4256 bytes
Disabling BEACON(BEACON_ENABLED) on copter saves 4168 bytes
Disabling SBF(AP_GPS_SBF_ENABLED) on copter saves 3992 bytes
Disabling DISPLAY(HAL_DISPLAY_ENABLED) on copter saves 3992 bytes
Disabling NMEA(AP_GPS_NMEA_ENABLED) on copter saves 3976 bytes
Disabling EFI(HAL_EFI_ENABLED) on copter saves 3888 bytes
Disabling RUNCAM(HAL_RUNCAM_ENABLED) on copter saves 3324 bytes
Disabling MODE_SYSTEMID(MODE_SYSTEMID_ENABLED) on copter saves 3048 bytes
Disabling SBP2(AP_GPS_SBP2_ENABLED) on copter saves 2936 bytes
Disabling SBP(AP_GPS_SBP_ENABLED) on copter saves 2744 bytes
Disabling ADSB_SAGETECH(HAL_ADSB_SAGETECH_ENABLED) on copter saves 2728 bytes
Disabling MODE_FOLLOW(MODE_FOLLOW_ENABLED) on copter saves 2704 bytes
Disabling WINCH(WINCH_ENABLED) on copter saves 2528 bytes
Disabling LANDING_GEAR(LANDING_GEAR_ENABLED) on copter saves 2416 bytes
Disabling MSP_SENSORS(HAL_MSP_SENSORS_ENABLED) on copter saves 2376 bytes
Disabling HOTT(HAL_HOTT_TELEM_ENABLED) on copter saves 2336 bytes
Disabling HIGHLAT2(HAL_HIGH_LATENCY2_ENABLED) on copter saves 1936 bytes
Disabling RPM(RPM_ENABLED) on copter saves 1904 bytes
Disabling OPTICALFLOW_HEREFLOW(AP_OPTICALFLOW_HEREFLOW_ENABLED) on copter saves 1896 bytes
Disabling PARACHUTE(HAL_PARACHUTE_ENABLED) on copter saves 1824 bytes
Disabling GSOF(AP_GPS_GSOF_ENABLED) on copter saves 1792 bytes
Disabling MODE_TURTLE(MODE_TURTLE_ENABLED) on copter saves 1760 bytes
Disabling NOVA(AP_GPS_NOVA_ENABLED) on copter saves 1600 bytes
Disabling SMARTAUDIO(HAL_SMARTAUDIO_ENABLED) on copter saves 1528 bytes
Disabling ERB(AP_GPS_ERB_ENABLED) on copter saves 1512 bytes
Disabling QUAD(AP_MOTORS_FRAME_QUAD_ENABLED) on copter saves 1304 bytes
Disabling ADSB_UAVIONIX(HAL_ADSB_UAVIONIX_MAVLINK_ENABLED) on copter saves 1272 bytes
Disabling OCTA(AP_MOTORS_FRAME_OCTA_ENABLED) on copter saves 1256 bytes
Disabling SPRAYER(HAL_SPRAYER_ENABLED) on copter saves 1248 bytes
Disabling BATTMON_INA2XX(HAL_BATTMON_INA2XX_ENABLED) on copter saves 1248 bytes
Disabling CRSFText(HAL_CRSF_TELEM_TEXT_SELECTION_ENABLED) on copter saves 1184 bytes
Disabling MAV(AP_GPS_MAV_ENABLED) on copter saves 1112 bytes
Disabling BATTMON_FUEL(AP_BATTMON_FUEL_ENABLE) on copter saves 1032 bytes
Disabling SIRF(AP_GPS_SIRF_ENABLED) on copter saves 992 bytes
Disabling PLUSCODE(HAL_PLUSCODE_ENABLE) on copter saves 960 bytes
Disabling OPTICALFLOW_PX4FLOW(AP_OPTICALFLOW_PX4FLOW_ENABLED) on copter saves 856 bytes
Disabling OPTICALFLOW_CXOF(AP_OPTICALFLOW_CXOF_ENABLED) on copter saves 832 bytes
Disabling OSD_SIDEBARS(HAL_OSD_SIDEBAR_ENABLE) on copter saves 800 bytes
Disabling EFI_NMPWU(HAL_EFI_NWPWU_ENABLED) on copter saves 792 bytes
Disabling GRIPPER(GRIPPER_ENABLED) on copter saves 752 bytes
Disabling OPTICALFLOW_UPFLOW(AP_OPTICALFLOW_UPFLOW_ENABLED) on copter saves 744 bytes
Disabling MSP_GPS(HAL_MSP_GPS_ENABLED) on copter saves 720 bytes
Disabling MSP_OPTICALFLOW(HAL_MSP_OPTICALFLOW_ENABLED) on copter saves 648 bytes
Disabling HEXA(AP_MOTORS_FRAME_HEXA_ENABLED) on copter saves 616 bytes
Disabling Y6(AP_MOTORS_FRAME_Y6_ENABLED) on copter saves 608 bytes
Disabling MSP_AIRSPEED(HAL_MSP_AIRSPEED_ENABLED) on copter saves 600 bytes
Disabling OPTICALFLOW_MAV(AP_OPTICALFLOW_MAV_ENABLED) on copter saves 576 bytes
Disabling TORQEEDO(HAL_TORQEEDO_ENABLED) on copter saves 568 bytes
Disabling NMEA_OUTPUT(HAL_NMEA_OUTPUT_ENABLED) on copter saves 568 bytes
Disabling OCTAQUAD(AP_MOTORS_FRAME_OCTAQUAD_ENABLED) on copter saves 560 bytes
Disabling MSP_BARO(HAL_MSP_BARO_ENABLED) on copter saves 528 bytes
Disabling MSP_RANGEFINDER(HAL_MSP_RANGEFINDER_ENABLED) on copter saves 488 bytes
Disabling MSP_COMPASS(HAL_MSP_COMPASS_ENABLED) on copter saves 456 bytes
Disabling DODECAHEXA(AP_MOTORS_FRAME_DODECAHEXA_ENABLED) on copter saves 288 bytes
Disabling DECA(AP_MOTORS_FRAME_DECA_ENABLED) on copter saves 264 bytes
Disabling MODE_GUIDED_NOGPS(MODE_GUIDED_NOGPS_ENABLED) on copter saves 200 bytes
Disabling SOARING(HAL_SOARING_ENABLED) on copter saves -8 bytes
Disabling AIS(HAL_AIS_ENABLED) on copter saves -8 bytes
Disabling QUADPLANE(HAL_QUADPLANE_ENABLED) on copter saves -16 bytes
Disabling OPTICALFLOW_ONBOARD(AP_OPTICALFLOW_ONBOARD_ENABLED) on copter saves -16 bytes
Disabling MODE_SPORT(MODE_SPORT_ENABLED) on copter saves -16 bytes
Disabling DEEPSTALL(HAL_LANDING_DEEPSTALL_ENABLED) on copter saves -16 bytes
Disabling BARO_WIND_COMP(HAL_BARO_WIND_COMP_ENABLED) on copter saves -576 bytes
```

**Comment by timtuxworth** [comment]
This is VERY interesting. The biggest bang for the buck is to disable either EKF2 (111K) or EKF3 (140K).  Disabling either of these gives you almost enough space for everything else!
Does it make sense to make EKF2 vs EKF3 an option for small boards?

**Comment by timtuxworth** [comment]
@peterbarker  could this be output in csv format so it's easier to import it into a spreadsheet?

**Comment by peterbarker** [comment]
> Does it make sense to make EKF2 vs EKF3 (pick one - either this or that?) an option for small boards?

Yes, we stopped including EKF2 on small boards a year or so ago.  It didn't take us long to eat that space up!

> Another way of looking at this is, that the best place to focus any further attention on might be the EKF2 and EKF3 code.

Yes, tridge made a start on that with `AP_NavEKF3_feature.h`.  OpticalFlow is a really big chunk that could be made optional in 
EK3 - but it is closely tied with "use rangefinder as EKF alt source", which makes it painful to remove.  Additionally - we're not even giving people the option of excluding EKF3 features on the build server at the moment; you will note that they are not in the output that's been pasted in.

> Its also noteworthy that disabling some of the options at the end of the list actually costs space.

Yes, I'd noted that - that's truly weird.

**Comment by peterbarker** [comment]
> @peterbarker could this be output in csv format so it's easier to import it into a spreadsheet?

Yes - maybe on the next lap around if it's left to me.  Probably a `--output-size-delta-csv-filepath=` command-line option and code changes to spit stuff out to that.

**Pull request merged**
