### PR TITLE
AP_Networking: make connector loopback test priority to be PRIORITY_IO-1

### PR DESCRIPTION
**Pull request by bugobliterator**

### CODE REVIEW

**Comment by magicrub** [comment]
This thread is faster so it makes sense but I'm not sure amount will change. Do you have any metrics to show that this makes any difference?

**Comment by bugobliterator** [comment]
> This thread is faster so it makes sense but I'm not sure amount will change. Do you have any metrics to show that this makes any difference?

We need this for Testing the modules. Lua scripts don't run properly until we set priority higher than loopback test thread.

**Comment by tridge** [comment]
Maybe just set lua thread priority higher with the parameter for that?

**Comment by bugobliterator** [comment]
> Maybe just set lua thread priority higher with the parameter for that?

I think the loopback test needs to be lower than IO anyways. It completely chokes out all the remaining threads. As with loopback its just pushing and receiving data at a really high rate.

**Review by tridge — APPROVED** [review]

**Pull request merged**
