### PR TITLE
Correct OmnibusNanov6 build

### PR DESCRIPTION
**Pull request by andyp1per**
This adds the OmnibusNanov6 HAL subtype to the list of boards to avoid compilation warnings

### CODE REVIEW

**Comment by andyp1per** [comment]
Need @1wick to confirm that the DMA change is necessary

**Comment by 1wick** [comment]
I got busy w/ work, and tomorrow am home alone w/ my 4 year old, so probably won't be able to do any testing..  Maybe Sunday.  
I have had several flights using the ESC Telemetry based notch w/ the official 4.0rc2 release, and have had no problems at all.  So w/ this release, the noDMA mod doesn't seem necessary.  

But, I'll put your firmware w/ the FFT back on it and do the same things I was doing a few days ago to see if I get all those prearm errors again.  And then either way, I'll put the noDMA version on it and take a few flights and report back.

**Comment by 1wick** [comment]
OK, 
The issue is repeatable w/ even the default 4.0rc2.  And even on a new FC w/ nothing installed, fresh of the bag.  

Calibrate level, and I get 0x8000 error and cannot arm.  3.6 doesn't cause the error.  
The no DMA version made no difference.  

Doing a 'soft reboot' doesn't fix it.. that's when I start getting the 0x4000 errors as well.  (by soft reboot I mean in MP, Actions, preflight_reboot_shutdown, DO Action)

It's ok after a complete power off.

**Comment by tridge** [comment]
the cal level error is easily fixed, and I've opened a PR for it here: #13043 
The one I'd really like to reproduce is the SPI timeout. My omnibusnanov6 has now arrived but I don't see the SPI timeout. If anyone can give me exact instructions for reproducing that from a bare board it would be appreciated

**Comment by andyp1per** [comment]
@tridge I've not been able to reproduce. I guess we can see if the cal level fix makes the other one go away?

**Comment by tridge** [comment]
@andyp1per they should be unrelated. I'd really like to find the SPI issue ...

**Comment by 1wick** [comment]
@tridge, For me, I got the SPI timeout if I hot reboot after doing a level calibration.  That's the only time I got it.  
So, calibrate level.  It causes error.  I thought a quick reboot would fix it, so I tried rebooting from in MP, actions, preflight_reboot_shutdown, then I got the SPI error.

**Comment by andyp1per** [comment]
@tridge, this simply adds the board id now so is completely safe

**Comment by peterbarker** [comment]
Closes #13678

**Comment by tridge** [comment]
please instead remove this line:
https://github.com/peterbarker/ardupilot/blob/master/libraries/AP_HAL_ChibiOS/hwdef/OmnibusNanoV6/hwdef.dat#L99

**Comment by andyp1per** [comment]
@tridge @peterbarker done.

**Pull request merged**
