### PR TITLE
AP_AHRS: provide interfaces for autopilot body frame rotations

### PR DESCRIPTION
**Pull request by jschall**
We have not been careful to maintain the distinction between autopilot body frame and vehicle body frame. These patches rectify that situation.

### CODE REVIEW

**Comment by OXINARF** [comment]
@jschall You wrote _get__**vehicle_rotation**_\_body_to_ned_ instead of _get__**rotation_vehicle**_\_body_to_ned_ in two places, that is why it is failing checks.

Also, you removed the trim from `getEulerAngles` in the EKFs and, as far as I can see, these are now only used in `getSecondaryAttitude` (which I think is only used to log). Is that not a problem? I mean, we will be logging different values than before.

**Comment by jschall** [comment]
@OXINARF oops, I should've build all targets on my machine before pushing it.

You are correct that this changes values that are logged. I don't think it will be an issue. It does break (*for some definition of break*) replay on older logs.

**Comment by jschall** [comment]
Force pushed some fixes. We'll see how travis goes now.

**Comment by jschall** [comment]
Made a simplified (baby steps) version: #4550 

Hopefully that one is less scary and can go in.

**Comment by jschall** [comment]
Closing this one for now.

**Pull request closed without merging**
