### PR TITLE
Plane: Flexible loiter exit options

### PR DESCRIPTION
**Pull request by magicrub**
When exiting a loiter it is sometimes nice to have flexible exit options. This PR adds a flag to the mission item that allows either:
- follow the path from center of waypoint to next waypoint (default)
- follow the path from tangent exit point to next waypoint

loiter_exit_xtrack

### CODE REVIEW

**Comment by iskess** [comment]
This is great, thank you!
See #3694 and #1906

**Comment by magicrub** [comment]
This still needs a mavlink packet and GCS PRs

**Comment by WickedShell** [comment]
Why does this need a mavlink packet? Or just an indicator on the current LOITER cmd's that we expect fields there?

**Comment by magicrub** [comment]
it would be a non-functional description change on mavlink and GCS

**Comment by DonLakeFlyer** [comment]
Not sure if you meant this by mavlink packet.Can you update the mavlink spec to include this so it's not a one-off for ardupilot?

**Comment by magicrub** [comment]
@DonLakeFlyer That's what I meant by mavlink needs t be updated

**Comment by magicrub** [comment]
pending PR: https://github.com/mavlink/mavlink/pull/531

**Comment by magicrub** [comment]
mavlink PR has been merged: https://github.com/mavlink/mavlink/pull/531

**Comment by magicrub** [comment]
Any final comments on this? I plan to merge it tomorrow and add the field in mission planner. I'd like it in v3.6.0

**Comment by proficnc** [comment]
LGTM

**Comment by OXINARF** [comment]
@magicrub The only thing I would recommend is to rebase it and let all tests run before merging.

**Comment by magicrub** [comment]
Sure thing.

**Comment by magicrub** [comment]
merged

**Comment by magicrub** [comment]
Mission Planner label PR: https://github.com/ArduPilot/MissionPlanner/pull/1251

**Pull request closed without merging**
