### PR TITLE
First commit: adding my name to GIT_Success.txt

### PR DESCRIPTION
**Pull request by mounalbaccouch**
Testing PR in Ardupilot project.

### CODE REVIEW

**Comment by rmackay9** [comment]
Looking good, except could you change the title of the commit to be something like "Tools: adding my name to GIT_Success"?  Note that I mean the commit title not the PR title.

**Comment by mounalbaccouch** [comment]
Done.
I don't know why there is some failed actions. Could you check please ?

**Comment by khancyr** [comment]
the CI failure is unrelated, don't worry. 
We don't use merge commit, could you do a rebase on our master branch, you should have only one commit for your change. see https://ardupilot.org/dev/docs/git-interactive-rebase.html for some help.

**Comment by mounalbaccouch** [comment]
Done

**Comment by rmackay9** [comment]
ok great merged.  This PR appears "closed" but the commit has been merged to master. txs!

**Pull request closed without merging**
