### PR TITLE
RC_Channel: Add AUX Functions: CompassNorthCal & AccelCalSimple

### PR DESCRIPTION
**Pull request by Jaaaky**
Add 2 extra AUX functions:

109 To Calibrate All compasses to the NORTH
110 To run simple INS calibration `accelcalsimple`, should assume vehicle is level too so no need for `ahrstrim` (level calibration)

Those helps a lot with large frames that lost proper compass calibration some how or the autopilot has been remounted for example.

### CODE REVIEW

**Comment by Hwurzburg** [comment]
why are these needed? they are available already by simple MAVLink commands from the ground station?

**Comment by Jaaaky** [comment]
> why are these needed? they are available already by simple MAVLink commands from the ground station?

Most if not all on AUX can be done through mavlink commands.. or can be aliased to short mavproxy commands..

It's just easier when you do not need to to type commands, or a single person handling RC and holding the vehicle..
Also accelcalsimple is not available on MissionPlanner so make it easier for non mavproxy geeks.

**Comment by Hwurzburg** [comment]
Given our 1MB be code crunch, we should not be consuming Aux functions and adding code for ground based operations... If the function is missing from MP,then it should be added there..not in firmware

**Comment by Jaaaky** [comment]
> Given our 1MB bd code crunch, we should not be consuming Aux functions and adding code for ground based operations... If the function is missing from MP,then it should be added there..not in firmware

I've added `#if !HAL_MINIMIZE_FEATURES` now to avoid the 1M issue.

**Comment by Hwurzburg** [comment]
unfortunately we do not use HAL_MINIMIZE_FEATURES any more....it can be a specific define, like RC_CHANNEL_GND_CAL_SW_ENABLE with it enabled in the .h for not defined && BOARD_FLASH_SIZE>1024....
but I still do not think ground only AUX switches should be in the firmware, but rather the GCS

**Comment by Hwurzburg** [comment]
I asked Micheal OBorne to add the simplecal button in MP

**Pull request closed without merging**
