### PR TITLE
Tools: add sensor_status_change.py

### PR DESCRIPTION
**Pull request by peterbarker**
```
2022-10-27 07:24:16.61:  health-SENSOR_RC_RECEIVER
2022-10-27 07:24:17.35:  health+SENSOR_RC_RECEIVER
2022-10-27 07:24:27.00:  health-SENSOR_RC_RECEIVER
2022-10-27 07:24:27.74:  health+SENSOR_RC_RECEIVER
2022-10-27 07:24:28.61:  health+SENSOR_YAW_POSITION health+SENSOR_Z_ALTITUDE_CONTROL health+SENSOR_XY_POSITION_CONTROL
2022-10-27 07:24:31.89:  health-SENSOR_RC_RECEIVER
2022-10-27 07:24:32.62:  health+SENSOR_RC_RECEIVER
2022-10-27 07:24:34.35:  health-SENSOR_RC_RECEIVER
2022-10-27 07:24:34.86:  health+SENSOR_RC_RECEIVER
2022-10-27 07:24:42.02:  health-SENSOR_RC_RECEIVER
```

### CODE REVIEW

**Review by khancyr — APPROVED** [review]
it doesn't impact on the rest and is compliant with the checkers, so let's merge this

**Comment by peterbarker** [comment]
> it doesn't impact on the rest and is compliant with the checkers, so let's merge this

When I discussed this with tridge he suggested it be moved to the MAVProxy repository instead.  It could then be easily added to MAVExplorer as a command.  That all seemed reasonable.

What are your thoughts on that?

**Comment by khancyr** [comment]
That would be indeed a place with more usage.
I don't mind where we place this as that isn't critical and seems already working

**Comment by peterbarker** [comment]
I think I'll merge this on the basis that it puts it next to `powr_change.py` `du32_change.py` and `solution_status_change.py`  all of which are equivalent in terms of where they sit in the ecosystem

**Pull request merged**
