### PR TITLE
mavlink: update submodule with upstream changes up-to 2021-02-20

### PR DESCRIPTION
**Pull request by amilcarlucas**
This is required before implementing CMD_DO_SPRAY in ground control stations

### CODE REVIEW

**Comment by peterbarker** [comment]
Why did this change IDs?

This is not how this should be working, of course, it probably should have gone upstream first.  But why did it change IDs?  We probably already have users actively using this now.

**Comment by amilcarlucas** [comment]
Because it is now in the common.xml segment.
It uses ID 199 on both upstream mavlink and downstream mavlink.
I told Two users on the forum that this was WIP and should not be used yet.
The tests pass, once this get merged the users can start using this.

**Comment by peterbarker** [comment]
On Mon, 22 Feb 2021, Amilcar Lucas wrote:

> Because it is now in the common.xml segment.
> It uses ID 199 on both upstream mavlink and downstream mavlink.
> I told Two users on the forum that this was WIP and should not be used yet.
> The tests pass, once this get merged the users can start using this.

Thing is that this is NOT a good precedent.  We've moved messages between 
the two files without changing IDs - gripper, autotune and inverted flight 
for example.

What made this one different that it warranted breaking existing users of 
ardupilotmega.xml?  It certainly makes me less enthusiastic about moving 
things up to common.xml!

**Comment by amilcarlucas** [comment]
Those features had a userbase, this one had none. It is not implemented in any GCS yet, or is it?

**Comment by davidbuzz** [comment]
On the dev call, it seems to be the general consensus that changing the ID when moving between xml's is poor form and we should keep the id's the same.... ( this particular one is low-risk, so might be able to go in anyway ..?)

**Comment by davidbuzz** [comment]
The other expectation is that unless there is another implementation that's using  (or going to use) the xml , it should stay in ardupilot.xml

**Comment by amilcarlucas** [comment]
closed in favor of #16717

**Pull request closed without merging**
