### PR TITLE
hwdef: add hwdef for CubeOrange-SimOnHardware

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Review by tridge — APPROVED** [review]

**Comment by tridge** [comment]
should we build it in CI ?

**Comment by radiohound** [comment]
Thank you for your work on this! I tested this on the CubeOrange on a few flights with no issues. Also tested the code on the NucleoH755 with no issues.

Is there a way to make this an firmware compile for all viable hardware? Simulation On Hardware seems more useful than SITL, since it's the real hardware doing the calculations and controlling the virtual craft.

(To get it to compile on my NucleoH755 hardware I had to change the define INS_MAX_INSTANCES to 1)

**Comment by peterbarker** [comment]
Wow, thanks for the feedback, @radiohound - it's always nice to get feedback like this on PRs.

> Thank you for your work on this! I tested this on the CubeOrange on a few flights with no issues. Also tested the code on the NucleoH755 with no issues.

Great!

> Is there a way to make this an firmware compile for all viable hardware? Simulation On Hardware seems more useful than SITL, since it's the real hardware doing the calculations and controlling the virtual craft.

I'm not sure we can justify the flash cost for most of our builds.  It's only the very beta boards (SPRacing) with qspi flash that could reasonably just throw everything like this in.  Otherwise we'd need to limit flight features.

In terms of utiltity, this-vs-normal-SITL.... both have their place, I think.  It's certainly a lot easier to step through flight code in SITL than it is when running on real hardware, but it's also very satisfying to see your physical parachute *actually* pop while flying a virtual flight.

> (To get it to compile on my NucleoH755 hardware I had to change the define INS_MAX_INSTANCES to 1)

Cool.  This sort of thing probably belongs in the documentation: https://github.com/ArduPilot/ardupilot_wiki/pull/4241 - which I really ought to go back and address Henry's comments....

Hopefully we'll be able to push this further - allowing you to switch between "real" and "virtual" parameters nicely somehow, for example, and finding a safe way to allow actuator outputs without making people hack the code (it is assumed if users are *that* keen they will also take appropriate precautions!).

**Comment by peterbarker** [comment]
Merged on the basis of @radiohound 's testing.  I don't actually *have* a CubeOrange on my bench ATM :-)

**Pull request merged**
