### PR TITLE
AP_NavEKF3: correct ext nav for sensor offset after recall

### PR DESCRIPTION
**Pull request by chobitsfan**
Currently, ext nav data need to corrected for sensor offset in ResetPosition(), while ext nav vel do not need to do so in ResetVelocity() (it is corrected after it is recalled). Maybe we could do it in a coherent way? Always corrected it after it is recalled from buffer.

### CODE REVIEW

**Comment by rmackay9** [comment]
I agree this is probably the best way to do it

**Comment by rmackay9** [comment]
Probably need to do some kind of testing (SITL at least) to show that the values before and after are unchanged.

**Comment by chobitsfan** [comment]
Thank you @rmackay9 
I do a SITL with master and this PR (SIM_VICON_POS_Z =5, VISO_POS_Z = 5)
[pr15027.zip](https://github.com/ArduPilot/ardupilot/files/5055768/pr15027.zip)

I also do a flight test with kakute f7 mini quad
[1 2020-8-11 03-37-32.zip](https://github.com/ArduPilot/ardupilot/files/5055777/1.2020-8-11.03-37-32.zip)

**Comment by peterbarker** [comment]
It looks like @rmackay9 may have forgotten about this PR and gone ahead and fixed his himself in a16de76f571349585ec8c02e439e0313621d72a2 (https://github.com/ArduPilot/ardupilot/pull/15614)

Thanks for this - it really ought to have been merged.

**Comment by chobitsfan** [comment]
Hi @peterbarker  and @rmackay9 
Thank you for taking care of this issue.

**Pull request closed without merging**
