### PR TITLE
Rover: Added reversing loiter_type parameter

### PR DESCRIPTION
**Pull request by IamPete1**
This is https://github.com/ArduPilot/ardupilot/pull/12737 from @sahith22 , I atmepted to squash and broke his PR, sorry @sahith22, this is his PR from my backup

### CODE REVIEW

**Comment by rmackay9** [comment]
Great, it's been tested of course?  if "yes" I'll merge after it passes travis.

**Comment by IamPete1** [comment]
@rmackay9 I'll try it on SITL now, interestingly it actually has passed Travis if you click details, not sure why it had updated here

**Comment by IamPete1** [comment]
@rmackay9 Now tested, works as It should

**Comment by rmackay9** [comment]
Great, merged, thanks!

**Comment by IamPete1** [comment]
@sahith22 Congratulations on your first contribution

**Pull request merged**
