### PR TITLE
added support for marking parameters as frame specific

### PR DESCRIPTION
**Pull request by tridge**
This allows us to hide parameters that don't match the current frame type

### CODE REVIEW

**Comment by amilcarlucas** [comment]
How does this get extrected by the tools/autotest/param_metadate/para_parse.py scripts ?

**Comment by tridge** [comment]
@amilcarlucas it doesn't relate to the param parse scripts. Those put in all params, but the GCS should only display params that it gets from the board at runtime

**Comment by jaxxzer** [comment]
Works well with Sub, I added this to the specific_gravity param in Baro, and the forward/lateral channels in RCMapper.

I also built QGC with new parameter xmls generated after this patch and can confirm both QGC and the autopilot seem content.

**Comment by lucasdemarchi** [comment]
> @amilcarlucas it doesn't relate to the param parse scripts. Those put in all params, but the GCS should only display params that it gets from the board at runtime

@tridge humn... but I think it should parse the different parameters to upload to our site. I've just been bitten by this while trying to use ARMING_REQUIRE, which is not implemented by copter.

**Comment by OXINARF** [comment]
@lucasdemarchi That is a current issue, not related to this PR. What we need to do is add a vehicle field to the documentation.

**Comment by tridge** [comment]
@lucasdemarchi, @OXINARF A vehicle field shouldn't be needed. The GCS should only display parameters that it has received when it enumerated the parameters. It then uses those names to lookup the generated xml files to get documentation on the parameter. It should not be listing parameters just because they are in the XML. 
Trying to get a XML file that only contains parameters that exist on the board would be extremely hard and is also pointless. There are so many factors that contribute to what parameters are available - it isn't just vehicle type, it is also board type and the current values of other parameters. The number of combinations would be far too high.

**Comment by OXINARF** [comment]
@tridge We are talking about the wiki, it will list all parameters even the ones not compiled in (or the ones that will be marked with this flag).

**Comment by jaxxzer** [comment]
Would it make sense to add an "@Frame" tag to these types of parameters, that will make a note of applicable frames for the documentation when passed through param_parse.py?

**Comment by OXINARF** [comment]
@jaxxzer I would call it Vehicle instead. I doubt we will split it in frames any time soon, that's a big change.
Regarding your experiment with it, I think it would be more worth it if we exclude it when building documentation for a vehicle, having a parameter show up in Copter documentation saying it is only for Rover and Plane is a bit weird. @peterbarker can probably help with this.

**Comment by tridge** [comment]
I think we can do the doc markup in a future PR, I'd like this in master now for the sub merge
pushed to master

**Pull request closed without merging**
