### PR TITLE
add NMEA Input library

### PR DESCRIPTION
**Pull request by IamPete1**
This adds a new NMEA input library and uses it for WindVane, GPS and Rangefinder. I have only tested a with windvane. It is hoped this will make it easier to add new NMEA inputs in the future (AIS). Hopefully it also removes a bit of duplicated code.

This is getting to the limit of my C++ so apology's if i have done it in a odd way.

### CODE REVIEW

**Comment by rmackay9** [comment]
From a practical point of view, this would be much easier to get into master if the GPS parts were removed.  Touching the NMEA GPS is such a critical part of the code that it will require a much higher level of review and testing vs the changes for the windvane and range finder which are rarely used.  If it were me I'd take it in steps, get the range finder and windvane changes in, then put the NMEA GPS changes in a follow-up PR.

**Comment by IamPete1** [comment]
rebased and dropped the GPS bit

**Comment by IamPete1** [comment]
rebased

**Comment by IamPete1** [comment]
fixed bad rebase

**Comment by IamPete1** [comment]
I'm going to close this, there is no saving in code without the GPS drivers and its a big job to re-test the rangefinders (and I don't have any) let alone the GPS stuff if that were to be included.

**Pull request closed without merging**
