### PR TITLE
Tools: autotest: add test for short failsafe triggering via low-throttle

### PR DESCRIPTION
**Pull request by peterbarker**
Currently this fails but should probably pass.

@Jaaaky - does this  new test look like your scenario?

### CODE REVIEW

**Comment by Jaaaky** [comment]
Yeah, Does this test pass on master now?
Have you tried it with my proposed pr fix?

**Comment by peterbarker** [comment]
@Jaaaky You can see the travis test results by clicking through the github interface (URL is in the notification you're receiving, I assume....).

Nope, this doesn't pass on master now :-)  (I mentioned that in my description, presumably not clearly enough!)

I have not tried this on top of your PR.

If we're agreed that this test should pass but currently fails I can add a patch to disable it in a normal run and merge this PR into master.

**Comment by Jaaaky** [comment]
How can I run this specific test locally on my machine?

**Comment by peterbarker** [comment]
On Fri, 23 Aug 2019, Jaaaky wrote:

> How can I run this specific test locally on my machine?

Roughly speaking:

# create and fetch a remote for my github repository
git remote add peterbarker https://github.com/peterbarker/ardupilot
git fetch peterbarker

# create a temporary branch to test on:
git checkout -b test-low-throttle https://github.com/Jaaaky/ardupilot/tree/pr-fix_failsafe_short_act_disabled

# grab the test I added:
git cherry-pick remotes/peterbarker/pr/autotest-add-short-failsafe-disabled-test

# run the test
./Tools/autotest/autotest.py --gdb --debug build.ArduPlane fly.ArduPlane.ThrottleFailsafe

# when you are done, delete the test branch:
git checkout master
git branch -D test-low-throttle

**Comment by Jaaaky** [comment]
Thanks a lot,
I just needed this command `./Tools/autotest/autotest.py --gdb --debug build.ArduPlane fly.ArduPlane.ThrottleFailsafe`

For pr fetch I found that something like
`git fetch origin pull/12095/head:autotest-add-short-failsafe-disabled-test` would be faster.

Any way, I've run the test on master and with my pr. On master it fails, with my pr it passes.

**Comment by tridge** [comment]
@peterbarker needs rebase for new fix

**Comment by peterbarker** [comment]
@tridge this passes after rebase (cool!), so I'm merging.

**Pull request merged**
