### PR TITLE
AP_Periph: restructure

### PR DESCRIPTION
**Pull request by tridge**
Restructure to have separate cpp files for most functions, and avoid static functions

based on https://github.com/ArduPilot/ardupilot/pull/24779 and 
https://github.com/ArduPilot/ardupilot/pull/24768

### CODE REVIEW

**Comment by andyp1per** [comment]
Move out of Tools if you are going to do this?

**Comment by tridge** [comment]
> Move out of Tools if you are going to do this?

that is a separate discussion, certainly possible, but not as important as the internal restructure I think

**Comment by andyp1per** [comment]
> that is a separate discussion, certainly possible, but not as important as the internal restructure I think

Not sure I agree - the restructure makes any merges from other branches or PR's impossible to all intents and purposes - if you are going to make this level of breaking change you should do anything else as disruptive at the same time. I think what you are proposing is a good change - just think you should take it all the way 😄

**Review by peterbarker — APPROVED** [review]
It's better.

My review comments would make it better still, but this one could bitrot very rapidly.

**Comment by peterbarker** [comment]
Costs:

```
Board                    AP_Periph
f103-Airspeed            136
CubePilot-CANMod         152
f103-ADSB                152
f103-QiotekPeriph        152
f103-HWESC               160
f103-Trigger             160
Hitec-Airspeed           160
AeroFox-Airspeed         176
AeroFox-Airspeed-DLVR    176
f103-RangeFinder         176
MatekL431-BattMon        176
MatekL431-Airspeed       184
f303-HWESC               192
MatekL431-HWTelem        192
MatekL431-Proximity      192
mRo-M10095               192
mRo-M10095               192
MatekL431-EFI            200
MatekL431-Rangefinder    200
Sierra-TrueNorth         200
Sierra-TrueSpeed         200
f303-PWM                 208
HolybroG4_Compass        208
Nucleo-G491              208
Sierra-L431              208
AR-F407SmartBat          216
CubeOrange-periph-heavy  224
CubeOrange-periph        232
f103-GPS                 232
HerePro                  232
mRoCANPWM-M10126         232
mRoCANPWM-M10126         232
f303-MatekGPS            240
f303-TempSensor          240
G4-ESC                   240
HitecMosaic              240
MatekH743-periph         240
AeroFox-PMU              256
MatekL431-GPS            256
C-RTK2-HP                264
f303-GPS                 264
f303-M10025              264
f303-M10070              264
Here4AP                  264
Nucleo-L476              264
Nucleo-L496              264
f303-Universal           272
MatekL431-bdshot         272
MatekL431-DShot          272
ZubaxGNSS                272
MatekL431-RC             280
BirdCANdy                296
CarbonixL496             304
Sierra-TrueNavPro        304
CarbonixF405             312
CubeBlack-periph         312
Sierra-PrecisionPoint    312
AeroFox-GNSS_F9P         328
f405-MatekAirspeed       328
f405-MatekGPS            328
HolybroG4_GPS            328
rGNSS                    328
rGNSS                    328
Sierra-F9P               328
MatekL431-Periph         336
Sierra-F405              336
Sierra-F412              336
HolybroGPS               344
Pixracer-periph          344
CUAV_GPS                 360
ARK_GPS                  368
ARK_RTK_GPS              376
FreeflyRTK               376
kha_eth                  416
```

**Pull request merged**
