### PR TITLE
AP_HAL_CHIBIOS: Change RCIN Prio

### PR DESCRIPTION
**Pull request by tsubashchandar**
Add provision to change Rcin thread priority
-needed to increase priority for some low speed cpu

### CODE REVIEW

**Comment by tsubashchandar** [comment]
@tridge , can you review it.

**Review by andyp1per — APPROVED** [review]

**Comment by tsubashchandar** [comment]
@tridge can you review this and merge

**Review by peterbarker — APPROVED** [review]

**Comment by peterbarker** [comment]
@tsubashchandar thanks - I've updated the commit message to better reflect the change, I hope you don't mind!

I've marked this as MergeOnCIPass.

**Comment by tsubashchandar** [comment]
@peterbarker thanks

**Pull request merged**
