### PR TITLE
Use GPS_AUTO_SWITCH parameter to choose exacly which GPS to use

### PR DESCRIPTION
**Pull request by amilcarlucas**

### CODE REVIEW

**Comment by rmackay9** [comment]
so this change uses the gps-auto-switch parameter as a selector for the primary GPS.  It makes some sense I think.

**Comment by amilcarlucas** [comment]
yes, exactly

**Comment by rmackay9** [comment]
a tiny thing I forgot to mention is the commit should start with "GPS:"..

**Comment by amilcarlucas** [comment]
@rmackay9 Fixed the commit message, sorry for that

**Comment by Kiwa21** [comment]
@amilcarlucas 
If I understand correctly, if set to 0, selected GPS will always be GPS1 and if set to 3 it will always use GPS2.
Why not create a new param to select the instance we want to use ? 
Something like "GPS_USE" = 1 for GPS1 or = 2 for GPS2  = 3 for GPS3 so it can handle more than 2 GPS..

**Comment by Kiwa21** [comment]
By the way, if you disabled the GPS auto switch does it still handle the loss of the selected GPS ? When no signal, not healthy or a GPS glitch it automatically switch to another instance ?

**Comment by amilcarlucas** [comment]
I did not create a new parameter because:
- we already have too many parameters
- Not it will not autoswitch to another GPS if the selected one fails. By having it in a single parameter it is very explicit that it does not autoswitch.

**Comment by WickedShell** [comment]
I brought this in, it's a bit dirty since it's normally fairly easy to rearrange ports to avoid the situation, but I can see some situations where it isn't possible (usually do to either flow control constraints or dedicated carrier board routing).

At some point soon we should do a follow PR that uses an enum to replace the magic values of 0/1/2/3, but I didn't want to hold this up for it.

**Pull request merged**
