### PR TITLE
APMrover2: Issue #11583 move contents of APMrover2.cpp to Rover.cpp

### PR DESCRIPTION
**Pull request by lyuyangh**
Addresses Issue #11583. APMrover2 builds successfully after the patch. SITL runs successfully.

### CODE REVIEW

**Comment by rmackay9** [comment]
@lyuyangh, thanks for this.  One problem is that all the history is lost as part of this move.  I've made the change in a slightly different way [in this repo](https://github.com/rmackay9/rmackay9-ardupilot/commits/master).

@peterbarker, does this change (in my repo) look OK?  If yes I'll merge it.

**Comment by peterbarker** [comment]
On Wed, 10 Jul 2019, Randy Mackay wrote:

> @lyuyangh, thanks for this. One problem is that all the history is lost as part of this move. I've made the change in a slightly different way in this
> repo.

@lyuyangh the trick to preserving the commit history is to make sure that 
git sees file renames - it can track history across those, and that's what 
Randy has done in his branch.

> @peterbarker, does this change (in my repo) look OK? If yes I'll merge it.

Change looks correct, but the first commit message should read "Rover: 
move contents of Rover.cpp to APMrover2.cpp"

**Comment by rmackay9** [comment]
txs, i'll merge once it passes travis again

**Comment by rmackay9** [comment]
updated and merged, thanks!

**Comment by lyuyangh** [comment]
Thank you! @rmackay9 @peterbarker  Will keep that in mind next time.

**Pull request closed without merging**
