### PR TITLE
Tools: Add css formatting and red colour

### PR DESCRIPTION
**Pull request by MichelleRos**
Add link to use css from main firmware page.
Add return to top link after each table (to make navigating between tables easier).

Make text red for for boards that have less than 5kB flash free or haven't built in the past 3 days. 
Sort by flash free for the group that have low flash free, and by date built for the second group.

image

### CODE REVIEW

**Comment by hendjoshsr71** [comment]
Awesome!  

If I understand the code correctly, if the velocity of commits to master get less than 1 commit per 3 days you are going to have a lot of "red" boards.  I guess we have to hit merge enough to keep pace :)

My thought would be to look for the most prevalent githash, grab that date, and any board not matching within some tolerance isn't building? (Assumes most boards build.)

**Comment by MichelleRos** [comment]
Good point. I've changed it to use the most recent build time instead. This does mean we assume the firmware server is always running correctly...
I've also added the filtering option - can search through any of the columns (eg "copter" to only see the Copter builds or "Matek" to see only the Matek boards).

image

**Comment by peterbarker** [comment]
Maybe yellow for low and red for dead?

**Comment by MichelleRos** [comment]
Bit difficult to find a yellow that works well on white/grey, but:
image

**Review by peterbarker — APPROVED** [review]
LGTM

**Pull request merged**
