### PR TITLE
AP_HAL_ChibiOS: restrict F405-WING BL to listen only on OTG1 port

### PR DESCRIPTION
**Pull request by giacomo892**
In the hope to fix the board remaining stuck in the bootloader (sometimes) when powering it up.
Continuing to test this in the next days if it actually fixes the issue.

### CODE REVIEW

**Comment by tridge** [comment]
thanks! will be interesting to hear the result

**Comment by vierfuffzig** [comment]
@giacomo892 when exactly do you see your board get stuck in BL?
iirc we were at that point of checking BL UART handling already https://github.com/ArduPilot/ardupilot/pull/9646 and fixed serial ports' signal handling in BL respectively. having UARTS available in BL is not a bad idea on that board type, as the 90° USB connector easily breaking off has been an issue for a couple of users.

**Comment by giacomo892** [comment]
@vierfuffzig The green light remains on and the board gets stuck in BL. That's it
There is no need to keep the UARTS available. You can still flash the board with stm32flash via UART when in bootloader  (stm32) mode.

**Comment by vierfuffzig** [comment]
i just wonder what the root cause of your actual issue is. does that happen with ot without USB connected? i’m not seeing any BL stuck  issues on any one of my boards.

does default stm32 dfu uart handling allow firmware updates while keeping your parameters?

**Comment by giacomo892** [comment]
@vierfuffzig yeah. board powered up via USB, but it happens also when on battery.
The GPS powers up when powering from USB from instance and it might send data that fools the BL.

stm32flash should allow to flash without erase I guess.
If you don't have mavlink enabled on an UART (beside the USB port) I guess it will be hard getting the params from the board, just keep a backup.

No, haven't seen the PR, link?

**Comment by vierfuffzig** [comment]
https://github.com/ArduPilot/ardupilot/pull/12993
https://github.com/tridge/ardupilot/commit/5c9b3842e6bda887354b1a9d5e5807e9d4340ce3#diff-f548aecf272d44c22e5b842c6d6fcf3a

please don't get me wrong, it's just that we've had a respective bootloader line noise issue that had been safely fixed over 1 y ago (see links above). it's kind of surprising to see this come up again now. afaik there's quite a lot of matekf405-wings around running ardupilot, i myself got 7 of those boards in frequent use, all running master with current bootloaders, and i'm seeing no issues here. so i just wonder if this is a new issue or something that is related to your indiviual hardware.

can you reliably un-freeze BL when stuck by disconnecting your GPSes TX line form your board? on a sidenote, this board's periphereal 5V pins are not powered by USB.

**Comment by tridge** [comment]
@vierfuffzig thanks for helping with this!
I suggested that @giacomo892 try disabling the uarts in the bl in case the issue isn't completely fixed already. I suspect it is fully fixed and the bl uarts isn't the issue, but the change should allow us to show it one way or the other
assuming it isn't the bl uart issue then we'll need to go hunting for another cause. If @vierfuffzig or someone else can reproduce that that would be great.
I tried to reproduce on my matek f405-wing with no luck, but I also don't have a GPS attached on mine (its a bench test board)

**Comment by giacomo892** [comment]
@vierfuffzig I can confirm it is an issue not only for me but also for people that I know directly. My GPS is powered from the 4.5V rail, so the MAG inside it gets powered also when I power the board via USB.
To reproduce, I connected the mag on UART4, UBLOX, 10Hz, auto config and auto save enabled. Then powercycle the board and eventually sooner or later it will get stuck in BL.

Being stuck in BL is one of the issues we have, another one is the board hanging during initialization, nominally OSD gets initialized but the board hangs before showing the battery voltage (shows 0V) and initializing the IMU. 
We have such issues on all our ChibiOS boards. (Matek, iFlight (succex) and OmnibusF4Pro).

**Comment by vierfuffzig** [comment]
i myself run 8 matek boards in all kinds of setups indcluding GPS, external I2C (baro) and other periphereals on a frequent basis and i haven't seen any stuck or hang issues in the past year. no issue reports on our local forum with BL hangs on ChibiOS boards, and i can't really see issue reports of that sort cumulating on RCG or discuss too, so i wonder if this is something more specific?
maybe we should take a look at power issues too, using the 4,5V rail to power periphereals other than the RCRx likely isn't something commonly done on that board.

@giacomo892 can you point me to the exact BL / main FW file you're seeing this issue on? and does unplugging the respective serial TX -> board RX wire get the board out of being stuck?

**Comment by giacomo892** [comment]
Hi, as I told you I have reports of these series of issues coming from different friends. Not very frequent, but there.
Powering the GPS from the 4.5V rail shouldn't cause any harm at least when the board is powered on via battery. The only difference between the other 5V lines is the presence of a little diode.

I am having such issues on every master version of AP (plane and copter) since I started exploring with AP, at least 1 years ago.
I'll check if I can unplug the GPS when it happens again, since it might be soldered to the board.

**Comment by tridge** [comment]
@giacomo892 have you determined if the change in this PR solves the problem for you?

**Comment by giacomo892** [comment]
> @giacomo892 have you determined if the change in this PR solves the problem for you?

It needs a bit of time to test :) I guess for the next week I should have an answer

**Comment by giacomo892** [comment]
The issue was related to DSHOT output being initialised too early. Fixed in #16501 .
Closing this

**Pull request closed without merging**
