### PR TITLE
AP_GPS: fix dataflash logging of blended GPS instance

### PR DESCRIPTION
**Pull request by amilcarlucas**
It needs testing

### CODE REVIEW

**Comment by amilcarlucas** [comment]
I tested it, it works and fixes a regression of all vehicles against the previous stable version. i.e. Arducopter 3.6 is fine Arducopter >= 4.0 is broken.

**Comment by peterbarker** [comment]
> I tested it, it works and fixes a regression of all vehicles against the previous stable version. i.e. Arducopter 3.6 is fine Arducopter >= 4.0 is broken.

... and without regression tests, it will break again :-)

**Comment by amilcarlucas** [comment]
Can this on go in without a CI test? It has been tested in hardware.

**Comment by rmackay9** [comment]
We normally don't insist on an autotest for bug fixes so it's not a requirement I think.

**Comment by peterbarker** [comment]
I've cherry-picked and fixed up these changes in master now.


Thanks for this!

**Pull request closed without merging**
