### PR TITLE
RC_Channel: adds Generator to metadata

### PR DESCRIPTION
**Pull request by Hwurzburg**
Fixes mistakes in recent commits that we made...

### CODE REVIEW

**Comment by rmackay9** [comment]
Looks like the generator is only supported in Copter and Plane at the moment.  I think it will eventually be added to Rover but not quite yet.

**Comment by Hwurzburg** [comment]
then the ,AP_PARAM_FRAME_COPTER|AP_PARAM_FRAME_ROVER|AP_PARAM_FRAME_PLANE) should be changed, right?

**Comment by rmackay9** [comment]
@Hwurzburg, I think we just need to remove the change to the line that starts with "// @Values{Rover}"

**Comment by Hwurzburg** [comment]
@rmackay9 removed it from Rover

**Comment by rmackay9** [comment]
Thanks!  Plane is not my baby but hopefully it's OK that I merge this.

**Comment by Hwurzburg** [comment]
shouldn't be an issue since it was there before I accidentally removed it in a commit that got merged!

**Pull request merged**
