### PR TITLE
Tools: vagrant: update path to CMAC-circuit.txt

### PR DESCRIPTION
**Pull request by nkruzan**
path is no longer valid. not tested.

### CODE REVIEW

**Review by khancyr — CHANGES_REQUESTED** [review]
hello,

Thanks for this. The change is good, it just need correction on the commit message. It should be :

`Tools: vagrant: update path to CMAC-circuit.txt`

Could you make the change ?

**Comment by nkruzan** [comment]
I think I have changed commit message correctly. Please advise. Thank you.

**Review by peterbarker — APPROVED** [review]
LGTM

**Comment by peterbarker** [comment]
Merged, thanks!

**Pull request merged**
