### PR TITLE
CI: test ubuntu 22.04 for github actions

### PR DESCRIPTION
**Pull request by tridge**

### CODE REVIEW

**Comment by RuffaloLavoisier** [comment]
Hi, @tridge !
Why don't you use `Ubuntu-latest`? Is there a difference?

**Comment by tridge** [comment]
> Why don't you use `Ubuntu-latest`? As a result, is there a difference?

we want to control what version is used. latest may change in future to something that doesn't work - we want to test first

**Comment by khancyr** [comment]
That doesn't change the ubuntu version we are using for tests. Those change are for the github machine but we are using docker container, so we need to change the dockers containers.

Not a big deal, I can do it fast. 
But what is the motivation behind this change ? Just pushing to the latest LTS ?

**Comment by tridge** [comment]
> But what is the motivation behind this change ? Just pushing to the latest LTS ?

I want to take advantage of ubsan to check for undefined behaviour. That doesn't seem to work with 20.04.
See https://github.com/ArduPilot/ardupilot/pull/21163

> Not a big deal, I can do it fast.

thanks!

**Comment by khancyr** [comment]
This was resolved. closing

**Pull request closed without merging**
