### PR TITLE
AP_Arming: running and reporting all individual prearm checks over Mavlink

### PR DESCRIPTION
**Pull request by blandry**
This is a rebase of some work @rmackay9 had started. I have modified it so that we can report every individual check that is failing/passing. Obviously do not merge this directly as it contains a submodule update to [a copy of Mavlink that has the arming_check_report message](https://github.com/blandry/mavlink/commit/8ed30599b9ca200b1056f62d1f64189af52fd106).

A few notes:
- Let's minimize the amount of "grouping" we do with the checks. different UI's might want to group things differently. It should be their responsibility, not APM's.
- Let's not be too greedy with message size. I actually think we could make those fields even bigger. The checks are sent at 1Hz. This is far from a bandwidth hog.
- It's a big change. It will require substantial testing. If you have suggestions to have a more progressive transition toward a system like that please pitch in!

[Here is a drone-discuss thread on this topic.
](https://groups.google.com/forum/#!searchin/drones-discuss/proposal$20for$20pre-arm$20check$20mavlink$20messages/drones-discuss/yjOwXjZCnCo/UrDb1GmMDwAJ)

Cheers!

### CODE REVIEW

**Comment by OXINARF** [comment]
I have only looked superficially to the PR but some comments for now:

- commits which add generated MAVLink headers shouldn't be here. MAVLink headers are automatically generated
- this is missing waf integration
- I don't understand the point of having a common message for arm checks if then each autopilot has their own definitions for it. I think it is much worse that GCS would then need to go to each autopilot repository to find the definitions for what each code means. Since it is difficult to agree to a common specification it seems better to me if each autopilot had its own message (or if possible maintain the common message with the enum in each autopilot) - at least that way a GCS only needs the MAVLink repository.

**Comment by magicrub** [comment]
is this something that would go in after 3.4?

**Comment by amilcarlucas** [comment]
We are on the road to 3.5 now. Can you rebase ???

**Comment by amilcarlucas** [comment]
No feedback for more than 2,5 years. The PR is huge and so are the merge conflicts, should this be further perused?

**Comment by blandry** [comment]
I will not be pursuing this any further so I'm happy to close it. Any objection?

**Comment by rmackay9** [comment]
... the need to finish this actually came up in a discussion at the recent Canberra developers conference.. closing is OK I guess although I'll keep a link and hopefully we will resuscitate this effort at some point.

**Pull request closed without merging**
