### PR TITLE
DataFlash: extract common labels and formats into defines

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by WickedShell** [comment]
Can I be picky? Primarily can we have this be a macro that checks the input string length for you? I'd love it if the compiler would just hit me with the clue stick when I make my strings to long... (Or does it and I've just been counting the hardway for no good reason?)

**Comment by WickedShell** [comment]
Is this just a prototype of what this would look like? (Since not all of them were done?)

**Comment by peterbarker** [comment]
@WickedShell No, this just pulls every common format string and label string out into defines.  So people (not naming any names... ;-) ) don't forget to update them all.

And SITL will just die now if you get things wrong  (patch already merged).

**Comment by tridge** [comment]
makes sense, thanks Peter!

**Comment by OXINARF** [comment]
Excellent patch @peterbarker!

**Pull request merged**
