### PR TITLE
Have sub and copter use the same RC checks

### PR DESCRIPTION
**Pull request by peterbarker**
Currently Sub uses a version of the Copter RC checks from a year ago.

### CODE REVIEW

**Comment by peterbarker** [comment]
@jaxxzer this will cause pre-arm RC checks to fail for users who upgrade and have never done an RC calibration.  These checks are stricter than what was previously there.

**Comment by OXINARF** [comment]
I'm a bit surprised to see Sub using RC checks given that, as far as I know, it doesn't work with RC input, but just with MAVLink overrides.
Otherwise looks good to me.

@peterbarker third commit needs to be split, there a param file change there 🙂

**Comment by peterbarker** [comment]
@OXINARF Commit split.  Damnit :-)

**Comment by rmackay9** [comment]
Merged, thanks!

**Pull request merged**
