### PR TITLE
Rover: Add manual mode to MIS_DONE_BEHAVIOR

### PR DESCRIPTION
**Pull request by Shadowru**
Add manual mode to MIS_DONE_BEHAVIOR for Rover

### CODE REVIEW

**Comment by rmackay9** [comment]
@Shadowru,

Looking pretty good, thanks!  One small thing, can you add "Rover:" to the front of the commit subject line?  Sorry to be picky but we normally do this ([have a peek at our commit history here](https://github.com/ArduPilot/ardupilot/commits/master)) because it helps us when it comes time to merging things.  If you're not sure how to do this with git (it involves an interactive rebase) then I can do it as part of the merge.

**Comment by IamPete1** [comment]
also add it to the param description https://github.com/ArduPilot/ardupilot/blob/1c77df9169a3cd7d58e79d0ab678305de91bcd5c/APMrover2/Parameters.cpp#L572

Thanks

**Comment by Shadowru** [comment]
> @Shadowru,
> can you add "Rover:" to the front of the commit subject line?
I'll do

**Comment by peterbarker** [comment]
@Shadowru you need to squash all of this down into a single commit, then force-push that commit up.

Did you want help doing that?

**Comment by khancyr** [comment]
Redone in  #16443

**Pull request closed without merging**
