### PR TITLE
Validate built Navigator firmware using firmware_version_decoder.py

### PR DESCRIPTION
**Pull request by Williangalvani**
depends on:
 - [x] #20047
 - [x] https://github.com/ArduPilot/ardupilot_dev_docker/pull/11

### CODE REVIEW

**Comment by Williangalvani** [comment]
> We probably need to wait a little while for the docker stuff to work?

yes! I think we'll need a new tag/release in there

**Comment by Williangalvani** [comment]
> yes! I think we'll need a new tag/release in there

nope! we're using latest there, so I guess I just need to wait for the action to finish and update this pr.

**Comment by Williangalvani** [comment]
@peterbarker maybe I was right after all. it looks like latest is the latest tag tagged. so I think we need a v0.0.21 in there

**Review by patrickelectric — APPROVED** [review]
LGTM
image

**Review by peterbarker — APPROVED** [review]

**Review by tridge — APPROVED** [review]

**Pull request merged**
