### PR TITLE
AP_Compass:Add QMC5883L driver for GPS compass module

### PR DESCRIPTION
**Pull request by ljwang1102**
#6445 has been added into master,but I think it add into Copter-3.5 is better,that can use as soon as possible

### CODE REVIEW

**Comment by OXINARF** [comment]
This is different than #6445. We usually don't accept PRs against branches other than master, unless they are bug-fixes. When you want something in a release branch, you do a PR adding it to master and write in the PR that you think it would be a good addition for release X - then the vehicle maintainer decides if it is backported or not.

Is there any board using this driver already? It shouldn't be a big problem to backport it, just trying to understand it's usefulness.

@rmackay9 What do you think? If we put it in 3.5, it should be the commits that were merged into master and not this.

**Comment by ljwang1102** [comment]
Sorry,I don't kown that can not be added in a release branch directly,I have some GPS+compass module use this driver.Comparison of HMC5983 test, log compass data show that the difference is not obvious, and QMC5883L use InvenSense licensing technology, you can not modify the circuit instead of HMC5983,Then HMC5983 will be discontinued,Lis3mdl production is also uncertain，So I think this is the best choice，I can provided for you to test @rmackay9. @OXINARF @tridge

**Comment by ljwang1102** [comment]
@rmackay9 here are some test log,[QMC5883L](https://www.dropbox.com/s/0fp11nfds0p8evy/2017-07-10%2017-34-28.bin?dl=0)and[HMC5983](https://www.dropbox.com/s/gzs20eckg4y5itu/2017-07-10%2017-45-06.bin?dl=0),

**Comment by OXINARF** [comment]
All the commits related to this driver are now in the Copter 3.5 Backports project (https://github.com/ArduPilot/ardupilot/projects/4#card-3721465) so I'm closing this. Hopefully it will make it to 3.5.1

I should also note that this was adding the device with ID 0x0B, which is different from master (0x0D) and that is wrong, IDs need to be the same in master and release branches.

**Comment by ljwang1102** [comment]
@OXINARF Sorry, this didn't notice, thank you for reminding me

**Comment by rmackay9** [comment]
@ljwang1102, I guess you've seen this related issue?  I don't think I'll be able to include this in AC3.5.1 until this is resolved because it sporadically causes the vehicle's attitude to be off by 90 degrees.
https://github.com/ArduPilot/ardupilot/issues/6633

By the way, I know it was discussed previously but personally I think it might have been better to make the orientation consistent with the original HMC compass.  It's a hardware vendor thing but I would have though that if any orientation could be chosen, and this chip is pin compatible with the original, it would have made sense to make it easy for hardware vendors to switch over by keeping the same orientation.  This is just my personal opinion.

**Comment by ljwang1102** [comment]
@rmackay9 It has the same orientation consistent with the original HMC compass，so Later I submit changes direction [Change direction](https://github.com/ArduPilot/ardupilot/commit/603e903ccdd8748f8a6a7783e97f451fdd2e3121)

**Pull request closed without merging**
