### PR TITLE
EKF3: Preflight health check: always update height innov. filtered estimate

### PR DESCRIPTION
**Pull request by Giruad**
This PR aims to have a stricter EKF height health check while on the ground before arming. Presently, the only check on altitude in the EKF health checks is on the attribute `hgtInnovFiltState`. However, it is not updated if the height estimate is **unhealthy** (barometer data not fused anymore, unit variance >1) and the vehicle is already in the aiding mode **AID_ABSOLUTE** or **AID_RELATIVE**, which can lead to deceptively think the filter is healthy while in fact it is not. 

What I propose is to always estimate `hgtInnovFiltState`, the difference between the estimated altitude and the baro height, while on the ground. This is done to detect a constant bias.

### CODE REVIEW

**Comment by khancyr** [comment]
you need to modify the heathy() function too, otherwise the calculated innovation isn't use when you are in aiding mode : https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_NavEKF3/AP_NavEKF3_Outputs.cpp#L30

**Comment by peterbarker** [comment]
@Giruad are you still interested in pursuing this?

**Comment by Giruad** [comment]
I have been using code with this PR for a year and a half with success, however, I don't have the means or the time to provide an autotest to prove the success here. So if you want to drop this, feel free to do so !  

The problem here was a loophole in the EKF safety net which could allow arming while baro height data rejected & not fused.

**Comment by davidbuzz** [comment]
pr appears abandoned by original author, needs rebase, and will need @priseborough  to do this testing if he chooses to ( as original author clearly isn't going to), otherwise this pr can be closed.

**Comment by rmackay9** [comment]
I think this was resolved for Copter at least (perhaps not Plane) with this PR to add a pre-arm check of the EKF's altitude estimate https://github.com/ArduPilot/ardupilot/pull/15092

**Comment by davidbuzz** [comment]
see randys comment.

**Pull request closed without merging**
