### PR TITLE
Plane: Use AHRS for heading in mode loiter

### PR DESCRIPTION
**Pull request by rishabsingh3003**
This is a fix for #14018.
@WickedShell is this fine? Please let me know if there is something wrong here! Thanks.

### CODE REVIEW

**Comment by WickedShell** [comment]
@rishabsingh3003 So what we want is the course over ground rather then the current yaw of the aircraft. So with a plane a common situation is where you are crabbing (turning slightly into the wind) to correct for getting pushed side ways. This means the yaw is pointed a bit sideways from the way the vehicle is actually traveling. What you need to do is ask the AHRS for the ground speed vector, and then convert this to a single angular heading. (Look up `AP_AHRS::groundspeed_vector`)

**Comment by rishabsingh3003** [comment]
@WickedShell yes I understand. Thanks for the clarification. While fixing my PR, I realized the angle is completely wrong when ground speed is zero. What should be done in that case? Should normal yaw be used if the ground speed is zero (or close to)?

**Comment by WickedShell** [comment]
So I have a slight problem that I think this is the correct type of change, but in testing validating the math I'm surprised at how off the groundspeed vector from AHRS is relative to the GPS data.

Following data is from SITL (AHRS_EKF_TYPE 2), with a wind set at 5 m/s on a quadplane, while in a loiter turns and attempting to breakout. `GPS` is the GPS course over ground, `Vec` is the math shown in this PR, and `Yaw` being the aircrafts current yaw. The AHRS estimate clearly attempts to be close to the GPS data, but I'm surprised at how often it seems to be splitting the middle ground.

```
GPS: 2.59 Vec: 6.84 Yaw 7.01
GPS: 2.59 Vec: 8.59 Yaw 9.14    
GPS: 6.13 Vec: 10.34 Yaw 11.29    
GPS: 6.13 Vec: 12.08 Yaw 13.40    
GPS: 9.67 Vec: 13.83 Yaw 15.56    
GPS: 9.67 Vec: 15.60 Yaw 17.74    
GPS: 13.16 Vec: 17.40 Yaw 19.95    
GPS: 13.16 Vec: 19.22 Yaw 22.18    
GPS: 16.68 Vec: 21.04 Yaw 24.40    
GPS: 16.68 Vec: 22.84 Yaw 26.59    
GPS: 20.30 Vec: 24.63 Yaw 28.75    
GPS: 20.30 Vec: 26.40 Yaw 30.85    
GPS: 23.93 Vec: 28.18 Yaw 33.01    
GPS: 23.93 Vec: 29.94 Yaw 35.09    
GPS: 27.50 Vec: 31.68 Yaw 37.16    
GPS: 27.50 Vec: 33.43 Yaw 39.27    
GPS: 31.05 Vec: 35.18 Yaw 41.35    
GPS: 31.05 Vec: 36.89 Yaw 43.37    
GPS: 34.54 Vec: 38.57 Yaw 45.37    
GPS: 34.54 Vec: 40.25 Yaw 47.34    
GPS: 37.99 Vec: 41.90 Yaw 49.26    
GPS: 37.99 Vec: 43.55 Yaw 51.20    
GPS: 41.35 Vec: 45.22 Yaw 53.16    
GPS: 41.35 Vec: 46.87 Yaw 55.04    
GPS: 44.63 Vec: 48.45 Yaw 56.90    
GPS: 44.63 Vec: 50.05 Yaw 58.77    
GPS: 47.94 Vec: 51.64 Yaw 60.60    
GPS: 47.94 Vec: 53.24 Yaw 62.43    
GPS: 51.11 Vec: 54.82 Yaw 64.25    
GPS: 51.11 Vec: 56.41 Yaw 66.09    
GPS: 54.26 Vec: 57.98 Yaw 67.88    
GPS: 54.26 Vec: 59.60 Yaw 69.71    
GPS: 57.42 Vec: 61.23 Yaw 71.55    
GPS: 57.42 Vec: 62.86 Yaw 73.36    
GPS: 60.60 Vec: 64.48 Yaw 75.11    
GPS: 60.60 Vec: 66.08 Yaw 76.84    
GPS: 63.86 Vec: 67.63 Yaw 78.52    
GPS: 63.86 Vec: 69.16 Yaw 80.21    
GPS: 67.06 Vec: 70.68 Yaw 81.87    
GPS: 67.06 Vec: 72.20 Yaw 83.53    
GPS: 70.13 Vec: 73.74 Yaw 85.24    
GPS: 70.13 Vec: 75.30 Yaw 86.92    
GPS: 73.15 Vec: 76.85 Yaw 88.61    
GPS: 73.15 Vec: 78.42 Yaw 90.26    
GPS: 76.24 Vec: 79.97 Yaw 91.87    
GPS: 76.24 Vec: 81.50 Yaw 93.43    
GPS: 79.35 Vec: 83.02 Yaw 94.97    
GPS: 79.35 Vec: 84.50 Yaw 96.49    
GPS: 82.41 Vec: 85.94 Yaw 97.98    
GPS: 82.41 Vec: 87.37 Yaw 99.43    
GPS: 85.39 Vec: 88.77 Yaw 100.88    
GPS: 85.39 Vec: 90.17 Yaw 102.31    
GPS: 88.24 Vec: 91.57 Yaw 103.72    
GPS: 88.24 Vec: 92.98 Yaw 105.12    
GPS: 91.03 Vec: 94.36 Yaw 106.48    
GPS: 91.03 Vec: 95.75 Yaw 107.91    
GPS: 93.82 Vec: 97.18 Yaw 109.33    
GPS: 93.82 Vec: 98.61 Yaw 110.71    
GPS: 96.59 Vec: 100.03 Yaw 112.07    
GPS: 96.59 Vec: 101.42 Yaw 113.36    
GPS: 99.43 Vec: 102.78 Yaw 114.61    
GPS: 99.43 Vec: 104.12 Yaw 115.89    
GPS: 102.21 Vec: 105.46 Yaw 117.20    
GPS: 102.21 Vec: 106.79 Yaw 118.48    
GPS: 104.89 Vec: 108.15 Yaw 119.79    
GPS: 104.89 Vec: 109.51 Yaw 121.07    
GPS: 107.55 Vec: 110.88 Yaw 122.29    
GPS: 107.55 Vec: 112.21 Yaw 123.43    
GPS: 110.24 Vec: 113.49 Yaw 124.58    
GPS: 110.24 Vec: 114.77 Yaw 125.76    
GPS: 112.92 Vec: 116.02 Yaw 126.92    
GPS: 112.92 Vec: 117.27 Yaw 128.04    
GPS: 115.45 Vec: 118.50 Yaw 129.14    
GPS: 115.45 Vec: 119.15 Yaw 129.71    
GPS: 117.93 Vec: 120.37 Yaw 130.76    
GPS: 117.93 Vec: 121.56 Yaw 131.80    
GPS: 120.36 Vec: 122.75 Yaw 132.87    
GPS: 120.36 Vec: 123.98 Yaw 133.99    
GPS: 122.73 Vec: 125.22 Yaw 135.08    
GPS: 122.73 Vec: 126.48 Yaw 136.13    
GPS: 125.14 Vec: 127.70 Yaw 137.11    
GPS: 125.14 Vec: 128.88 Yaw 138.09    
GPS: 127.61 Vec: 130.05 Yaw 139.10    
GPS: 127.61 Vec: 131.25 Yaw 140.12    
GPS: 129.94 Vec: 132.44 Yaw 141.10    
GPS: 129.94 Vec: 133.60 Yaw 142.10    
GPS: 132.29 Vec: 134.76 Yaw 143.06    
GPS: 132.29 Vec: 135.92 Yaw 143.99    
GPS: 134.59 Vec: 137.07 Yaw 144.94    
GPS: 134.59 Vec: 138.23 Yaw 145.91    
GPS: 136.87 Vec: 139.38 Yaw 146.86    
GPS: 136.87 Vec: 140.51 Yaw 147.82    
GPS: 139.16 Vec: 141.63 Yaw 148.74    
GPS: 139.16 Vec: 142.76 Yaw 149.63    
GPS: 141.40 Vec: 143.87 Yaw 150.51    
GPS: 141.40 Vec: 144.98 Yaw 151.40    
GPS: 143.62 Vec: 146.07 Yaw 152.26    
GPS: 143.62 Vec: 147.13 Yaw 153.12    
GPS: 145.80 Vec: 148.18 Yaw 154.00    
GPS: 145.80 Vec: 149.21 Yaw 154.82    
GPS: 147.91 Vec: 150.27 Yaw 155.65    
GPS: 147.91 Vec: 151.36 Yaw 156.53    
GPS: 149.96 Vec: 152.47 Yaw 157.42    
GPS: 149.96 Vec: 153.60 Yaw 158.29    
GPS: 152.11 Vec: 154.72 Yaw 159.18    
GPS: 152.11 Vec: 155.83 Yaw 160.03    
GPS: 154.34 Vec: 156.94 Yaw 160.85    
GPS: 154.34 Vec: 158.04 Yaw 161.71    
GPS: 156.54 Vec: 159.14 Yaw 162.58    
GPS: 156.54 Vec: 160.24 Yaw 163.47    
GPS: 158.73 Vec: 161.34 Yaw 164.30    
GPS: 158.73 Vec: 162.40 Yaw 165.12    
GPS: 160.91 Vec: 163.46 Yaw 165.94    
GPS: 160.91 Vec: 164.49 Yaw 166.74    
GPS: 163.03 Vec: 165.49 Yaw 167.51
```

``` c++
    gcs().send_text(MAV_SEVERITY_INFO, "GPS: %.2f Vec: %.2f Yaw %.2f", heading_cd * 1e-2f, wrap_360(degrees(plane.ahrs.groundspeed_vector().angle())), degrees(plane.ahrs.yaw));
```

**Comment by WickedShell** [comment]
`SIM_GPS_DELAY` was screwing up my testing above :) All good.

**Pull request merged**
