### PR TITLE
GitHub: update issue template

### PR DESCRIPTION
**Pull request by OXINARF**
Change template so that Platform doesn't turn into a task list

### CODE REVIEW

**Comment by WickedShell** [comment]
Yeah the list was bothering me wasn't sure how to fix it.

 #### Platform
 [  ] All
 [  ] AntennaTracker
 [  ] Copter
 [  ] Plane
 [  ] Rover

**Comment by OXINARF** [comment]
> So the goal of the change is just show the brackets, there isn't a way to get a visual checkbox without having it as a task list? Darn!

I would prefer that too but I searched and didn't find a way to do it.

**Comment by WickedShell** [comment]
If we can't have the checkbox maybe just go with asking them to select the right one instead of having them all in that list? (Always thought All weirdly overlapped with the others, and it's hard to think of an issue that would be only true for copter + rover for example without also affecting plane (and maybe tracker).

Anyways I'm fine with the change as proposed

**Comment by OXINARF** [comment]
I'm fine either way. I have a slight preference for this way just because we get a consistent text - I believe if we ask people to write which one it affects we will get _plane_, _Plane_, _ArduPlane_, _arduplane_, etc.

I guess _All_ can be removed, but it is a simple way to mark it affects all vehicles.

**Comment by WickedShell** [comment]
Thats a very valid point for consistency. (All can stay or go, I have a sick desire to check all, then go check everything below it everytime...)

**Comment by lucasdemarchi** [comment]
LGTM. Applied.

**Pull request closed without merging**
