### PR TITLE
Copter: Delete a comparison that does not become a true forever.

### PR DESCRIPTION
**Pull request by muramura**
Already against Checked code, again, it is checked.

### CODE REVIEW

**Comment by rmackay9** [comment]
@muramura, I'm not sure why we should remove the 0x63?  I think 0x63 is the character, "c".  So if a user pushes "c" it means "cancel".

**Comment by OXINARF** [comment]
@rmackay9 'c' is checked in the if before, so this is actually unreachable code.

**Comment by muramura** [comment]
@OXINARF Comment, Thanks.

Before This statement, c Variable value checked 'c'(small c character).
This variable value is equal 'c', then loop out by break.
By loop-out, this statement is not executed.

I think 'c' and 0x63 is equal.

**Comment by rmackay9** [comment]
Ah, I see.  Thanks, merged!

**Pull request closed without merging**
