### PR TITLE
AP_BattMonitor: extend build options to backend modules

### PR DESCRIPTION
**Pull request by Hwurzburg**
Can save 5.6k....completes all options that save space in AP_BattMonitor

### CODE REVIEW

**Review by magicrub — CHANGES_REQUESTED** [review]
As @hendjoshsr71 said, need to remove the defines in the main header.

**Comment by Hwurzburg** [comment]
Actually, since the defines already exist at a higher layer that is included lower, I should just remove the ifndefs from the lower layer .h files rather than the higher .h, I think....done

**Comment by hendjoshsr71** [comment]
> Actually, since the defines already exist at a higher layer that is included lower, I should just remove the ifndefs from the lower layer .h files rather than the higher .h, I think....done

I think the pattern is to generally have those in the file they effect.  (so like you had it)??

**Comment by tridge** [comment]
we need to work out why this makes any difference, it shouldn't

**Comment by hendjoshsr71** [comment]
OK trying this again and I don't see any size difference not sure what happened before for me. Probably, just had built the wrong thing.... when looking at sizes which makes more sense to what I thought would be the case.

**Pull request closed without merging**
