### PR TITLE
Remove tri yaw servo from motor mask

### PR DESCRIPTION
**Pull request by andyp1per**
This allows MOT_PWM_TYPE to be used

### CODE REVIEW

**Comment by IamPete1** [comment]
I wonder if we should move away from using a function called motors. This same issue exists for the singe and coax copters along with all the heli frames. Tailsitter is the only one that uses none - motors outputs already.

But I think this change is a good one.

It is possible to do this now (not that I have tested recently) by using the `BLH` prams rather than `MOT_PWM_TPYE`. I have a tri running dshot.

**Comment by andyp1per** [comment]
> It is possible to do this now (not that I have tested recently) by using the `BLH` prams rather than `MOT_PWM_TPYE`. I have a tri running dshot.

Right - this just makes it easier for users to get going and not screw it up

**Review by IamPete1 — APPROVED** [review]
Tested on my Tricopter. I was able to turn off all the `SERVO_BLH_*` over rides.

**Comment by rmackay9** [comment]
Merged, thanks!

**Comment by rmackay9** [comment]
I've created an issue to capture the similar problem for SingleCopter and CoaxCopter https://github.com/ArduPilot/ardupilot/issues/18201

**Pull request merged**
