### PR TITLE
Add battery failsafe reset capability

### PR DESCRIPTION
**Pull request by khancyr**
Usefull battery swap or charging. It use the BATT_ARM_VOLT value to clear the failsafe.
Test as been added, the default behavior is not changed.
Currently it clear the failsafe on all battery. We could rework later to select which failsafe should be cleared by adding a parameter for each battery.
This is used by AzurDrones solution

### CODE REVIEW

**Comment by WickedShell** [comment]
@khancyr I'm surprised you went down this road. On the one hand I get it for the way you guys do battery charging. On the other hand it relies upon actually seeing current flow back into the battery to reset the remaining capacity such that a failsafe is not immediately retriggered. If you used this with a battery which you swapped in and out of the aircraft, the arming voltage may cause you to reset the failsafe, but unless I've missed something a low (or critical) capacity failsafe would be immediately triggered on the next battery update. So the solution you've given here works reasonably well for in-situ charging (assuming no significant integration error of the battery capacity), but doesn't work well with swapping the actual batteries.

**Comment by khancyr** [comment]
Yep, I mention that it should work on all case. But now that you are saying it, it should reset the current count and all other counter ... I will change that

**Comment by WickedShell** [comment]
@khancyr Yeah, we need to be able to reset the capacity counters. Unfortunately that doesn't work well for your use case, and in general makes large assumptions about the battery behaviour. Automatically resetting capacity based on arming voltage is very dangerous, as if you set a lowish arming voltage, and it fluctuates back and forth you would destroy the capacity based failsafes.

I suspect we need to actually let this be MAVLink based to be a general solution. With your specific use case the PR makes sense as is (although you'd still benefit from a MAVLink message to reset the capacities once you know the system is fully charged)

**Comment by khancyr** [comment]
yes, I think that the mavlink message is the best solution for all use case. In fact, in our case, we have the mavlink message, but I cannot share this part nor the battery management logic.

**Comment by khancyr** [comment]
Closing for now, as I don't have more time to work on this

**Pull request closed without merging**
