### PR TITLE
Copter: disable precland by default.

### PR DESCRIPTION
**Pull request by khancyr**
The precland state machine is introducing more than 4s delay  (around 10s on RTL) and precland failsafe message in all case.
It shouldn't happen for normal user.

### CODE REVIEW

**Comment by rmackay9** [comment]
Before we disable it let's ask @rishabsingh3003 to investigate.  the precision landing state machine stuff just went in a few hours ago..

**Comment by khancyr** [comment]
even worse : 
set PLD_STRICT to 2 and disable precland and your copter will never land ...

**Comment by khancyr** [comment]
@rmackay9 okay whatever.

**Comment by rishabsingh3003** [comment]
I have fixed the issue https://github.com/ArduPilot/ardupilot/pull/18424
It was really trivial and should not have happened in the first place, really sorry. 

PLD_STRICT = 2 is for users who do not want to land at all, unless its prec land, so the functionality is intended.. but only when its enabled (which was the bug)

**Pull request closed without merging**
