### PR TITLE
Fix for Trad heli DDVP tail for Copter 3.5.4

### PR DESCRIPTION
**Pull request by bnsgeyer**
Here is the fix for the trad heli DDVP tail.  This feature was broken when code went from 3.3 to 3.4.

### CODE REVIEW

**Comment by rmackay9** [comment]
@tridge and I did a quick review and we think there are a few issues (hopefully I can transcribe them correctly here):

- only getting the min/max/rev at startup is probably not best because it means changes to these values won't take effect until the next reboot.
- REV is not quite the same as the new SRV_Channel library's REVERSED parameter.  In fact, it might be the opposite (REV=-1 means reversed which is equivalent to REVERSED=1)
- @tridge suggested we should switch to use one of the SRV_Channel lib's new functions to output to the tail servos.  I'm not sure which one but one of them allows outputting to multiple channels.  Personally I don't see any changes in this PR to how the output is done so perhaps this comment is out of scope for this PR and can be handled in a future PR.

**Comment by bnsgeyer** [comment]
@rmackay9  as far as only receiving the min, max and rev at startup, do you think I should have it query the servo library every time it writes to the servo (i.e. put it in the write_rsc method).  I understand that having it as a parameter allowed the user to change the values and then it caught the changes without having to reboot.  Having a servo function that does what write_rsc does would be nice and would keep from having to requery the servo library every time the write_rsc method is used.  
I welcome your comments/suggestions on this.

**Comment by ChristopherOlson** [comment]
> @tridge suggested we should switch to use one of the SRV_Channel lib's new functions to output to the tail servos

This would have to be one of the SRV_Channel functions for HeliRSC. It does not drive an actual servo - it drives the ESC for the DDVP tail rotor motor, similar to the RSC system that drives the ESC for the main rotor motor. I tested Bill's code in a real heli (not the sim) and it works with all the main rotor RSC modes. This has been broken since AC3.4 (no output to the HeliTailRSC), leaving a number of users stranded on AC3.3.3, which was the last version of Copter that it worked in, as per this thread on the Dev section of the forum
https://discuss.ardupilot.org/t/need-help-tradheli-direct-drive-variable-pitch-tailrotor/22795/25

**Comment by bnsgeyer** [comment]
@rmackay9 and @tridge  I completed my rework of this PR.  I have the servo reverse interpretation corrected and moved the call for servo min, max and rev to the write_rsc function.  I tested it in the SITL and the servo responds correctly to the settings with the servo set to normal and reverse.  Submitting this for inclusion in master.
Regards,
Bill

**Comment by ChristopherOlson** [comment]
If I reverse the servo with this new change it doesn't work. Is that intended? The tail ESC has to have a 1000 pwm signal on power-up or it goes into programming/calibration mode

**Comment by bnsgeyer** [comment]
@rmackay9 and @tridge. I see Chris' point on this. I looked back at the function in AC3.3.3 and it does not account for the servo being reversed (unless I'm missing something behind the scenes. I want to make it behave like it did in AC 3.3 but I need your approval on this path in order to get it merged.

**Comment by ChristopherOlson** [comment]
@rmackay9 and @tridge there's a couple issues here. It is a HeliRSC drive. Heli power drives are expected to operate from 0 to 100% torque (or power). So min/max needs to be hard-wired to 1000 and 2000 because that is what ESC's expect to initialize properly and make the power setting.

The second issue is, you cannot reverse a power drive. The tail ESC simply goes into programming mode and beeps. It will never start the tail rotor. If the user does not mess with the REV setting, it will work. But that is not how it worked in AC3.3.3.

Being a HeliRSC certain defaults need to be set and not adjustable. If it was a normal servo then all this makes sense. But it is not a normal servo.

We have a number of users waiting to get this function working. We can code it to work the way it should and implement that in ArduHeli master so our users can test it and make sure it works the way it did in AC3.3.3. Then port the code to Copter master for a PR. But we need to make sure min/max defaults apply to a HeliRSC, and REV function does not reverse the output and put the tail ESC into programming mode. DDVP tail heli's use a governor like the main rotor does, and that programming is done in the ESC with the manufacturer's software prior to installation in the heli. The HeliTailRSC can be driven with the main_rotor RSC with a y-cable. But that does not allow independent adjustment of the tail rotor speed.

**Comment by tridge** [comment]
not discussion here in reversal behaviour:
https://discuss.ardupilot.org/t/need-help-tradheli-direct-drive-variable-pitch-tailrotor/22795/52?u=tridge

**Comment by ChristopherOlson** [comment]
> only getting the min/max/rev at startup is probably not best because it means changes to these values won't take effect until the next reboot.

@rmackay9 I tested this particular concern and it does not require a reboot with the FC in unarmed state for the SERVO min/max/rev settings to take effect (flying the code with the call in the init() method).

**Comment by ChristopherOlson** [comment]
@bnsgeyer I cloned your repo and built from that for testing. Have you checked to see if this merges cleanly with 3.6-dev?

**Comment by bnsgeyer** [comment]
@tridge  please review and let me know if any other changes are necessary. @rmackay, please let me know if I need to squash the commits and force an update to my branch for this pull request. I would like to get this merged. Thx!

**Comment by bnsgeyer** [comment]
@rmackay9  please let me know if I need to squash the commits and force an update to my branch for this pull request. I would like to get this merged. Thx!

**Comment by OXINARF** [comment]
This should definitely be merged against master first. We don't want to go back into situations where fixes were done in release branches and never went to master.

**Comment by bnsgeyer** [comment]
@oxinarf Do you want me to close this PR and open a new one against master? I can clean it up as well.

**Comment by rmackay9** [comment]
@bnsgeyer, yes, I think opening against master would be best.  Normally stuff goes into master first then we backport it to a release branch.

**Comment by OXINARF** [comment]
@bnsgeyer My suggestion: close this one and open a new PR against master. When it is merged to master, re-open this one backporting whatever was merged into master.

**Comment by bnsgeyer** [comment]
opened new pull request to merge into master

**Pull request closed without merging**
