### PR TITLE
Various little correction for precland and place

### PR DESCRIPTION
**Pull request by khancyr**
taken from https://github.com/ArduPilot/ardupilot/pull/8932

### CODE REVIEW

**Comment by rmackay9** [comment]
any testing evidence?  This touches a few critical functions including precision landing and package place.. have both these features been tested at least in the simulator?

the #undef is a bit weird.. why is this required?

**Comment by khancyr** [comment]
The first two are just clean up.
The undef is just a security I think as the macros is really generic
The last on is the real corretion. I has been tested with the autotest in #8932

**Comment by khancyr** [comment]
Tested on SITL with the new autotest in https://github.com/khancyr/ardupilot/tree/precland-autotest

**Comment by rmackay9** [comment]
Merged, thanks!

**Pull request merged**
