### PR TITLE
Copter: update sensor status error flags independently of sending a sys_status message

### PR DESCRIPTION
**Pull request by floaledm**
Currently, an active MAVLink connection with extended_status1 messages must be active for the control_sensors_... vars (i.e., sensor status error flags) to be updated and in turn make the update to the flags in the Frsky lib.
This removes the limitation (a number of users of the FrSky link don't use a MAVLink GCS at the same time).

- update_sensor_status_flags() is called from the 1Hz loop but could be placed somewhere else.
- I placed Copter::update_sensor_status_flags() in sensors.cpp, but could be somewhere else (for fence, it's in its own file).

### CODE REVIEW

**Comment by floaledm** [comment]
@magicrub Do you know if there's anything holding up this PR? tridge and I had discussed and had agreed in principle on this PR (see last line here: https://github.com/ArduPilot/ardupilot/pull/3434#issuecomment-242251911)

**Comment by magicrub** [comment]
Only @rmackay9 , and sometimes @tridge, are allowed to commit to copter.

**Comment by floaledm** [comment]
Thanks for letting me know! I'm referencing this commit a14ff8ac7757e72fae7b0acb0dcca95aff274da8 which enabled the functionality (getting sensor status error flags) but which has the limitations that this PR would correct.

**Comment by floaledm** [comment]
Just resolved conflicts on this PR. I would appreciate if @rmackay9 or @tridge could merge soon or let me know what needs to be fixed...

**Comment by tridge** [comment]
applied with fix to update flags on mavlink send too
thanks Florent!

**Comment by lucasdemarchi** [comment]
This brought back the bug fixed by this commit:

```
commit b24d850695b6e044a1af4f6bf9c0a946c7198c39
Author: Lucas De Marchi <lucas.demarchi@intel.com>
Date:   Thu Sep 29 08:49:47 2016 -0300

    ArduCopter: Fix use of logical op instead of bitwise op
```

Same comment applies to other vehicles.

**Comment by floaledm** [comment]
My bad. Thanks Lucas for catching that. I'll put those corrections with the Plane PR as that one has not been merged yet (rover and copter have been)...

**Pull request closed without merging**
