### PR TITLE
GPS: added RC switch for disabling GPS

### PR DESCRIPTION
**Pull request by tridge**
This is for testing GPS failure. The PR includes the patches to fix dead-reckoning support

### CODE REVIEW

**Comment by Pedals2Paddles** [comment]
This is useful beyond just GPS failure testing. If you're indoors without editing parameters, or fly into an area of tree cover or under obstructions, disabling the GPS so it can't use it no matter what are realistic use cases.

**Comment by peterbarker** [comment]
Needs a rebase

**Comment by Raviu8** [comment]
I've a comment with my real flight results in #9349 using this PR.

**Comment by magicrub** [comment]
needs a rebase, the GPS dead-reckoning patch has been merged

**Comment by tridge** [comment]
rebased

**Pull request merged**
