### PR TITLE
AP_Proximity: Support LD robot STL27L lidar

### PR DESCRIPTION
**Pull request by ajarx**
image

### CODE REVIEW

**Comment by geofrancis** [comment]
does this use the same protocol as the LD19?

**Comment by ajarx** [comment]
> does this use the same protocol as the LD19?

From follow manual, they share same protocol.
https://manuals.plus/dfrobot/lidar-ld19-laser-sensor-kit-manual#data_protocol
#define PO/NT_PER_PACK 12
#define HEADER 0x54
typedef struct _attribute_((packed))
{ uint16_t distance;
uint8_t intensity; } LidarPointStructDef;
typedef struct _attribute_((packed)) {

uint8_t:  header;
uint8 t:  ver_len;
uint16_t:  speed;
uint16 t: start_ angle;
LidarPointStructDef point[POINT_PER_PACK};
uint16 t: end_angle;
uint16_t: timestamp;
uint8 t: crc8;
}LiDARFrameTypeDef;

**Comment by geofrancis** [comment]
the Ld19 can be picked up for about £60 so I look forward to this getting merged.

**Comment by lvale** [comment]
see

https://github.com/ArduPilot/ardupilot/pull/20138

same basic lidar

**Comment by lvale** [comment]
can this be closed ? Same generic lidar has been merged

**Pull request closed without merging**
