### PR TITLE
Make MTK enable defines in place of relying on AP_Periph

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by WickedShell** [comment]
Just remove the driver! I have a PR for it! Since no one has the hardware
to test let's remove it and wait till it's encountered before resolving at
this point. The attempt to remove it is several years old, and stalled on
having hardware that it appears no dev has....

**Comment by peterbarker** [comment]
> Just remove the driver! I have a PR for it! Since no one has the hardware to test let's remove it and wait till it's encountered before resolving at this point. The attempt to remove it is several years old, and stalled on having hardware that it appears no dev 

Is the same true for both MTK and MTK19?

**Comment by WickedShell** [comment]
> Is the same true for both MTK and MTK19?

The PR removes both and asks you to use the NMEA output from the GPS instead. I don't see anything that is in the MTK protocol that is superior to the NMEA implementation. (It's missing the same fields, and doesn't have any jitter handling). But the NMEA drivers receive more maintenance and are much more likely to gain these features.

As far as I can tell with the slight exception of units 3DR may have sold directly (back in the APM1/APM2 days, and well gone before the APM2 days ended), is the only unit that might not be able to do NMEA, but I'm skeptical that A: any of those units are still used, B: I've heard so many terrible things about them. I think every other MTK chip out there should actually speak the full set of NMEA we need, but that's the thing I was looking to see tested.

**Comment by peterbarker** [comment]
For reference during the call, here is @WickedShell 's ridiculously conflicting PR which we should probably have merged years ago: https://github.com/ArduPilot/ardupilot/pull/8364

**Comment by peterbarker** [comment]
Closing in favour of https://github.com/ArduPilot/ardupilot/pull/18785

**Pull request closed without merging**
