### PR TITLE
AC_WPNav: Fix Terrain Following with Obstacle Avoidance On

### PR DESCRIPTION
**Pull request by hendjoshsr71**
This attempts to address terrain following not working with Object Avoidance. Issue #16479 

@Huibean in #15223 identified the location of where the `_terrain_alt` flag was being set to false. This causes `_terrain_alt` to be set false, for the duration of each waypoint, after the following the code executes.
https://github.com/ArduPilot/ardupilot/blob/b450740fb0e5cfb814636704a15e8ae19497a24a/libraries/AC_WPNav/AC_WPNav.cpp#L248

To fix this `get_wp_stopping_point(stopping_point)` should set the altitude in the terrain frame. Without doing this an extra `origin_terrain_offset` would be added to commands.

Issue found with OABR log messages incorrectly logging altitudes due to wrong format specifier. PR #16750

Below are SITL Testing Logs:
**Master Terrain Following ON: OA OFF** (Terrains following works)
master_OA_off_terrain_follow

**Master Terrain Following ON: OA Bendy ON** (Terrain following fails)
master_OA_on_terrain_follow

**PR Terrain Following On: OA Bendy ON**
modifications_to_master_with_stopping_adaptation3_no_speed_graph

### CODE REVIEW

**Comment by Huibean** [comment]
looks better 👍

**Comment by rishabsingh3003** [comment]
Hi @hendjoshsr71. I understand what you're trying to do in this PR but I am not sure if the problem is this simple. 
BendyRuler does a sweep for "safe-paths" around the vehicle, by projecting distances in a **straight line**. And currently, it uses alt-above-origin for it. So this means that while calculating the safe (obstacle free) path,  it does not take into account the terrain. Now if BendyRuler spits out a particular path, and terrain following asks the vehicle to climb up/down, we might hit an obstacle somewhere because BendyRuler never asked the vehicle to go in that direction, and hence we have no clue if that path is safe.
I might be misunderstanding the situation though, in which case feel to provide an explanation. Thanks!

**Comment by hendjoshsr71** [comment]
@rishabsingh3003 
You are correct about the differing altitude frames being input/output from `oa_ptr->mission_avoidance(..)`

Currently, in master, if terrain is active `current_loc` & `origin_loc` are being set as relative to EKF origin even though they are actually relative to terrain. The output is relative to EKF origin, but later could be used as relative to terrain. I've added additional logic to ensure that the frames are correctly set for inputs and that on output.

The main reason to get this in is that if a user has OA on and terrain following on they could easily hit a slopping hill. For a 40m tall hill and 30m terrain_altitude offset you will hit the hill eventually!

Still to solve issues: Vertical bendy: Gains altitude between waypoints where there are no obstacles. Upon reaching the next waypoint it descends to the correct  terrain_altitude.

**Comment by rmackay9** [comment]
I think I've got an alternative fix now in PR: https://github.com/ArduPilot/ardupilot/pull/16901.

All feedback and testing welcome but no pressure of course.

**Comment by rmackay9** [comment]
I'm going to close this PR because I've merged the alternative.  Thanks very much for looking into this in any case!

**Comment by hendjoshsr71** [comment]
@rmackay9 No problem yours is far simpler! 

I do think the altitude frames should be set for `orign_loc` and `desitnation_loc` as currently they could be terrain referenced but currently are being assumed to always be absolute referenced.

Thoughts? 

```cpp
        // convert origin and destination to Locations and pass into oa
        Location origin_loc(_origin_oabak);
        Location destination_loc(_destination_oabak);

        if(_terrain_alt) {
            origin_loc.set_alt_cm(_origin_oabak.z, Location::AltFrame::ABOVE_TERRAIN);
            destination_loc.set_alt_cm(_destination_oabak.z, Location::AltFrame::ABOVE_TERRAIN);
        }
```

**Comment by rmackay9** [comment]
@hendjoshsr71,

yes, I totally agree.  I also think that the current_loc that is passed into the path planners also needs to be in the same frame as the origin and destination.  The path planners then needs to be smart enough to return a Location with a usable altitude.

I think these mistakes (still in master) are a result from us having started with only 2D path planners.  Now we have at least one 3D path planner so we should sort this out.

Some of this on the critical path for 4.1 because we need to keep the path planners working after introducing SCurves. My WIP branch is here in case that is of any interest: https://github.com/rmackay9/rmackay9-ardupilot/commits/lthall-scurve4-spline-oa3

**Comment by hendjoshsr71** [comment]
I will checkout your branch tomorrow.

On current_loc : I think getting things to the same frame is definitively important. I wonder if it is best to change frame where altitude is needed instead of enforcing it on the inputs and outputs all over the place? 

My thought is that the Location(Vector3f NEU) constructor can be a bit dangerous since it assumes the altitude frame. Possibly, requiring the altitude frame in this constructor could help prevent hidden frame errors.

 Location(Vector3f NEU, AltFrame frame)

**Comment by rmackay9** [comment]
@hendjoshsr71,

I think I agree about the Location constructor although I was thinking of only have a boolean to signify above-terrain or above-ekf-origin but perhaps it makes sense to have a full alt-frame..

**Pull request closed without merging**
