### PR TITLE
STIL: delete unused parameter 'Vector3f &body_accel' in Plane::calculate_forces()

### PR DESCRIPTION
**Pull request by oneWayOut**
The Parameter 'Vector3f &body_accel' in method Plane::calculate_forces() is not used, so need to be deleted.

### CODE REVIEW

**Review by khancyr — CHANGES_REQUESTED** [review]
This is interesting ! Indeed, body_accel isn't used here as accel_body from Aircraft class is directly used.
I don't mind merging that.
We can oppose the other vehicle are pass the accel_body reference on their update() function instead of directly access it from the other functions.
@peterbarker any opinion ?

Anyways, the commit message need to be change to : 
```SITL:  delete unused parameter 'Vector3f &body_accel' in Plane```

Thanks

**Review by magicrub — COMMENTED** [review]
This is one of those "if it compiles it's probably ok" but I'm looking at it on mobile right now. I'll check it again from the desktop

**Review by rmackay9 — CHANGES_REQUESTED** [review]
txs for this.  It would be good to change the commit description to start with "SITL:".  To be clear I mean the **commit** description not the PR description.

**Comment by peterbarker** [comment]
@oneWayOut let me know if you need help adjusting the commit message.  Keywords you're looking for are "git amend" and "git force push"

**Comment by oneWayOut** [comment]
@peterbarker Thanks for your reminder, just amended the commit message and force pushed.

 @khancyr    I noticed that Sim_Submarine.cpp, Sim_Frame.cpp are passing  the accel_body reference to function calculate_forces(), in which case that the parameter could also be deleted since accel_body is always accessible.  But I don't know whether this kind of change is compliant to the Ardupliot coding convention.

**Comment by khancyr** [comment]
@oneWayOut Yes, we just need to decide which usage we want and unify each target.

**Comment by tridge** [comment]
can be merged when passes CI

**Review by tridge — APPROVED** [review]

**Comment by peterbarker** [comment]
Merged, thanks!

**Comment by khancyr** [comment]
@peterbarker ok so we unify that way ?

**Pull request merged**
