### PR TITLE
AP_Scripting: add mount bindings and example script

### PR DESCRIPTION
**Pull request by rmackay9**
This adds Lua bindings to control a gimbal (aka mount).  Every method's first argument is the gimbal number which should normally be left at zero.

- get_mode
- set_mode
- set_angle_target: accepts roll, pitch and yaw degrees along with a final boolean to indicate earth-frame (false = body-frame)
- set_angle_target: accepts roll, pitch and yaw rates in deg/s along with a final boolean to indicate earth-frame (false = body-frame)
- set_roi_target accepts a Location

All methods have been tested in RealFlight and on a real vehicle

### CODE REVIEW

**Comment by olliw42** [comment]
great!

one comment: When I did things like shown here, https://youtu.be/yUPlOLXbImw, I found it very important to add a means to make a script overriding commands from other sources like missions or mavlink, a kind of mutex. 

I called them take_control, give_control

https://github.com/olliw42/BetaPilot/blob/qshotscript/libraries/AP_Scripting/generator/description/bindings.desc#L293-L302
https://github.com/olliw42/BetaPilot/blob/qshotscript/libraries/AP_Mount/AP_Mount.h#L163-L170
https://github.com/olliw42/BetaPilot/blob/qshotscript/libraries/AP_Mount/AP_Mount.cpp#L787-L840
https://github.com/olliw42/BetaPilot/blob/qshotscript/libraries/AP_Mount/AP_Mount_Backend.h#L93-L100
https://github.com/olliw42/BetaPilot/blob/qshotscript/libraries/AP_Mount/BP_Mount_STorM32_MAVLink.cpp#L628-L655
https://github.com/olliw42/BetaPilot/blob/qshotscript/libraries/AP_Mount/BP_Mount_STorM32_MAVLink.cpp#L598-L602

very simple, and there sure might be much better approaches, and one maybe may want mavlink means too, e.g this mutex might indeed be a mav mode, and so on, but the point is something like this is needed. IMHO.

you may want to have also some of the other functions I've added, like getting angles, etc

**Comment by olliw42** [comment]
BTW, I actually wonder since a while, and was thinking over it, if one shouldn't implement a pretty generic driver, which has lua bindings to even crucial functionality. That is, the main logic would be implemented in a lua script, and there would be a lua script for each gimbal. The C code would "just" provide a good API. Having the main logic in the lua, that way one could get around 
1) having to have a AP driver for each and every gimbals
2) wouldn't have to change AP code whenever there is a change in a gimbal behavior, i.e., get around the slow cycle of getting changes into AP
3) limitations to implementers as now they just need to modify a lua script and upload instead reworking the C code

I just have not yet seen how this would be possible. Just to have shared the idea LOL.

**Comment by IamPete1** [comment]
Needs lua docs, re-gen with `./waf copter --scripting-docs`. That will give all new docs then only keep your new ones and remove all the changes to the ones was have manually updated. Bonus points for updating the descriptions and param values.

**Comment by IamPete1** [comment]
@rmackay9 Looks like it was just broken, I have opened a PR that should fix.

**Comment by rmackay9** [comment]
I've updated the docs and rebased on master, thanks!

**Comment by rmackay9** [comment]
@IamPete1 no pressure of course but you don't want to drop and approved on this PR do you?

**Review by IamPete1 — APPROVED** [review]
LGTM

**Comment by rmackay9** [comment]
Merged, thanks!

**Pull request merged**
