### PR TITLE
Threaded I2C and SPI (v3)

### PR DESCRIPTION
**Pull request by lucasdemarchi**
v3 of #4540

Changes:
  - Implement threaded SPI and move changes to MS5611 to be after that
  - Split commit adding PollerThread and changes to I2CDevice: this way it's easy to see the changes to SPIDevice is very similar
  - Rename thread to `ap-i2c-%d` and `ap-spi-%d` - that's because on some kernels the spi/i2c buses may have a dedicated worker thread and we don't want a confused user looking for our thread
  - Shuffle some commits around
  - Tested on minlure (MS5611 on I2C) and erlebrain2 (MS5611 on SPI)

### CODE REVIEW

**Comment by staroselskii** [comment]
Awesome! I just bench-tested it Navio 2 and Navio+ and everything seems to work fine.

**Comment by lucasdemarchi** [comment]
@staroselskii while monitoring the cpu load with and without these patches, I noticed a huge workload on rcin thread on navio (and erlebrain2 and others): 15+%. Looking at the implementation, we are waking up the thread every 500usec. Is that really needed?

**Comment by lucasdemarchi** [comment]
@staroselskii wouldn't it work the same if we just called _timer_tick() less frequently but processed more bytes in a batch, increasing the buffer size?  Ideally we should call it much less frequently than that

**Comment by lucasdemarchi** [comment]
Applied.

**Comment by staroselskii** [comment]
@lucasdemarchi 
Sorry it took me so long to get back to you.

This is indeed extremely big CPU overhead. I was told that this was needed in order to achieve the wanted accuracy. I doubt that too. We had a team member working on reimplementing this in the kernel space. IMHO, it's the place for such low-level stuff to be. Unfortunately, he couldn't get around to finishing it but I'll ping him and ask if we can fix it ASAP.

**Pull request closed without merging**
