### PR TITLE
Change "AHRS unhealthy" message to "no EKFn cores" if no cores exist

### PR DESCRIPTION
**Pull request by kd0aij**
If AHRS_EKF_TYPE=2/3 but the respective EK2/3_enable is 0, the prearm check reports
"AHRS unhealthy" without providing any clue to the cause of the problem.
This PR adds code which reports the issue .

### CODE REVIEW

**Comment by rmackay9** [comment]
I like that we are thinking of a fix for this because it's confusing to (advanced) users.  Another alternative would be to add a pre-arm check and then spit out a text message as to what the problem is.

**Comment by kd0aij** [comment]
Changed to only report that no cores exist.

**Comment by tridge** [comment]
needs description on commits

**Comment by rmackay9** [comment]
As a side note, I think the message might be easier to understand if it was "EKF2 not initialised".

**Comment by kd0aij** [comment]
@rmackay9 Thanks,  I chose "no cores" because that is the only information available by that point in the code (as far as I understand). I guess the original author thought "unhealthy" made it perfectly clear what was wrong :)

To be more useful, the message should obviously tell the user how to fix the problem, but  I don't think either "no cores" or "not initialized" does that; though the latter is IMO even more vague.

But if the only reason the core pointer might be null is a lack of memory (or EKn_enable not set) then the message could change to indicate that.  I assume it's not that simple, though.

**Comment by rmackay9** [comment]
@kd0aij, ok great.  I think we should probably update the wiki page so that we list all the possible failures and possible solutions.  I'm going to go ahead and merge this now. thanks!

**Comment by kd0aij** [comment]
OK, I'll look for relevant info in the wiki.
Are these the only pages discussing EKF configuration?
http://ardupilot.org/plane/docs/common-apm-navigation-extended-kalman-filter-overview.html?highlight=ekf
http://ardupilot.org/dev/docs/extended-kalman-filter.html#extended-kalman-filter

**Comment by rmackay9** [comment]
@kd0aij, this is the pre-arm failure message so the new messages should go here I think: http://ardupilot.org/copter/docs/common-prearm-safety-checks.html#common-prearm-safety-checks

**Pull request merged**
