### PR TITLE
AP_IOMCU: Revert breaking changes to SBUS output

### PR DESCRIPTION
**Pull request by asfishman**
SBUS output to servos was going through a cycle of working, and then not working. SBUS output would stop for 2 seconds, then resume, then stop again.

This PR essentially reverts key portions of this commit: https://github.com/ArduPilot/ardupilot/commit/bdd7094d17d5cd5d88254e68bf26c3759f758f73.

I am not sure of the goals of the commit, so it is likely that I broke the goals, however, reverting does fix the problem.

Looking for comment on the "right" way to fix this.

### Update More Information

I am using a CubeOrange and some SBUS servos. I am using no RC controller.

_Copter 4.0.3_
The system works as expected. As I move my heli around (angular rotation), the swash plate continuously maintains its level orientation. If I rotate the heli continuously, then the swash servos are also continuously rotating.

_Copter 4.0.4_
As I rotate the heli, the swash plate servos function nominally for 2 seconds. Then, despite my continuing to move the aircraft, the servos stop moving for 2 seconds. This cycle repeats.

# Analysis
I connected an oscilloscope to the SBUS outline for the servos, and noted that there was no output during the two seconds of failed servo motion.

I ran a git bisect and identified the commit above https://github.com/ArduPilot/ardupilot/commit/bdd7094d17d5cd5d88254e68bf26c3759f758f73 as the breaking commit. 

This is due to there being no RC controller connected, so the rc.cpp file thinks there is a failure and swaps the `sd3_config` flag after 2 seconds. We can see that the SBUS output is only conditionally enabled:

```
void sbus_out_write(uint16_t *channels, uint8_t nchannels)
{
    if (sd3_config == 0) {
        uint8_t buffer[25];
        AP_SBusOut::sbus_format_frame(channels, nchannels, buffer);
        chnWrite(&SD3, buffer, sizeof(buffer));
    }
}
```

### CODE REVIEW

**Comment by rmackay9** [comment]
@asfishman,

Thanks for this, a couple of questions:

- are you saying that SBUS output doesn't work for any version of Copter-4.0.x or did the troubles start happening sometime after 4.0.0 was released?
- have you reported this in discuss anywhere?  I'd like to hear more details if possible of the setup

**Comment by asfishman** [comment]
I have updated the PR comment with more information. There is not discuss post for this.

**Comment by joshanne** [comment]
Looks like Plane has reports of this too.
https://github.com/ArduPilot/ardupilot/issues/15516

**Comment by tridge** [comment]
@asfishman thanks very much for the detailed analysis. I don't want to just revert the change, as that will introduce another bug. 
The basic problem is that the same uart is used for SBUS output and SBUS input on the IOMCU. Until recently this was OK as we always ran that uart at 100kbaud. When we added support for FPort that changed, as FPort uses a inverted RC protocol at 115200. 
The f103 used for the IOMCU can't invert uarts in software, so it relies on the hardware inverter on that uart. So when we're probing for FPort we have to reconfigure the uart as 115200, which breaks SBUS output.

**Comment by tridge** [comment]
What I'd like to do is use the new RC_PROTOCOLS parameter to allow users to select the RC protocols they want to probe, and make it that if FPort isn't selected then we don't do the baudrate change
Also note that you can make it work now by setting up another UART for SBUS output, using SERIALn_PROTOCOL

**Comment by tridge** [comment]
I've done a better fix in #15523 
In that fix we disable the baudrate switching when SBUS output is enabled
we will include this fix in the next 4.0 releases

**Pull request closed without merging**
