### PR TITLE
Copter: Safe RTL / Smart RTL

### PR DESCRIPTION
**Pull request by rmackay9**
This replaces @squilter's earlier PR (#6682) and follow up PRs (#6792, #6868) by adding support for "Safe RTL" (aka "SmartRTL"):

Improvements over the previous PR (#6868) include:

- CPU load is reduced because:
  - detect_simplify is run after 50 points have been added to the path and the path is then simplified (i.e. simplify-able points removed using remove_points_by_simplify_bitmask).  detect_simplify never runs on these points again (except for the very last point which can't be simplified without knowing the point after it).
  - detect_loops runs next on the simplified path and using the same number of points as simplify used.  the segment comparison logic has been changed so we do not compare segments that have already been compared in the past (outer loop goes from top-to-bottom, inner loop goes from bottom-to-top).
  - points are removed from the path by directly using the simplify.bitmask and prune.loops array instead of going through an intermediate stage in which path points were set to zero.
- Pruning of loops is improved in cases where there are overlapping loops:
  - logical error is fixed - previously it could fly in places where it had never flown before
  - add_loop method added which checks new loops against existing loops and keeps the longest.  This requires storing the loop length which consumes an additional 150 to 500 bytes (depending upon number of points)
- Bitmask usage is reduced mostly because we simply don't need it with the modified simplify and prune method.

Description:

- AC_SafeRTL library does the following:
  - creates and maintains a "path" which is an array of Vector3f objects (position offsets from the EKF origin) which can lead the vehicle from its current position to the take-off location.
  - SRTL_ACCURACY parameter holds the minimum distance between points
  - SRTL_PATH_LEN holds the maximum number of points that can be recorded to the path (defaults to 150, maximum is 500)
  - the update function is called from the main vehicle class at 3.3hz and records the vehicle's position at the end of the array (if necessary)
  - the run_background_cleanup runs in the IO thread and does the following:
    - "detect_simplifications" looks for points in a straight line that can be simplified.  These are recorded in the _simplification_bitmask and then removed by the "remove_points_by_simplify_bitmask" method.
    - "detect_loops" works off the simplified path, looking for loops in the path.  Loops are recorded to the _prune.loops array using the "add_loop" method which performs some checks for overlap with previously detected loops (only the longest loop is kept)
    - "routine_cleanup" is called regularly and kicks off simplify and pruning after each 50 points are added to the path and when the path array has only 10 empty slots left.
    - "thorough_cleanup" is initiated when the vehicle code calls the "request_thorough_cleanup" method.  The "thorough_cleanup" ensures all possible simplification and pruning is complete so the vehicle can begin its journey home.
 - a new SafeRTL flight mode has been added which, when initiated, stops the vehicle then returns the vehicle to the take-off location by using the lib's "pop_point" method to retrieve points from the path.
- the vehicle eventually stops 2 meters above the take-off location and uses regular RTL's Land or Descend feature.

Items potential issues that we might need to address in follow-up PRs:

- at 200 points, SafeRTL consumes about 4k of memory (2.4k for the path itself, 0.8k for each of the simplification-stack and prunable-loops arrays). Increasing the number of points consumes more memory but also more CPU for the simplification. We need to test more to find what number of points works best in practice. Same goes for the ACCURACY parameter.
- the EKF must be reporting a good position at take-off for SafeRTL to be available
- SafeRTL becomes unusable for that flight if the EKF's position estimate goes bad for >15seconds.
- SafeRTL should be made available as a failsafe option.

Some relevant links:

- Sebastian's blog post: https://discuss.ardupilot.org/t/safertl-mode-for-copter/20486
- sitl test: https://www.youtube.com/watch?v=7YsTC6vd2jE
- sitl test2: https://www.youtube.com/watch?v=1TDO8rDbm48
- actual flight test: https://www.youtube.com/watch?v=Ju0tL-nmQpo

### CODE REVIEW

**Comment by squilter** [comment]
Loop pruning wasn't working properly in sitl on some pretty simple paths. I first flew a path that had two loops, one after the other. Only the first loops was pruned out. Then I tried two loops, one inside the other. Only the inside loop was pruned out. If you can't recreate, I can put a video on youtube.

Regarding the simplification, it is still making the same mistake by splitting the path into chunks and only simplifying that chunk. Problem is this line:
```
_simplify.stack[0].start = (_simplify.path_points_completed > 0) ? _simplify.path_points_completed - 1 : 0;
```
Maybe the best thing to do here is to always set the start to zero, but every single comparison where both the start and end are `< _simplify.path_points_completed` will immediately return. This gets most of the advantage of using less CPU, and it is more correct. Once all this is fixed, we need to get the example working again.

Looks a lot cleaner, I appreciate all the effort you are putting into this.

**Comment by lvale** [comment]
Something else that should be added is the yaw behaviour when SmartRTL engages. 

I would suggest to maintain the existing parameters, and the drone should adjust it's yaw according to that, so it should change yaw between each flight segment.

**Comment by magicrub** [comment]
LOLz, you you a skype message in that video!

**Comment by magicrub** [comment]
Isn't there a setting for that? To have yaw fixed or to face mission/ground vector?

**Comment by lvale** [comment]
@magicrub yes, on "standard" RTL, not defined yet for smartRTL :)

**Comment by magicrub** [comment]
from a user's perspective, I don't see the difference. Everything should be exactly the same, only the path is different

**Comment by lvale** [comment]
@magicrub That's what I was saying above. Current behaviour is that returns always maintaining the yaw it had when smartRTL is engaged.

**Comment by squilter** [comment]
Yaw is working as expected when I just tested it, based on `WP_YAW_BEHAVIOR`.

**Comment by rmackay9** [comment]
I've just just a forced update to -rtl10.  I think this resolves the issue with overlapping loops by improving the checks within add_loop so that the length of the new loop is compared with the sum of all the length of overlapping loops and only if the new loop is longer is it added.  I think this is better than the previous method which compared the new loop individually to the existing loops.  This meant there was a number of unlikely cases where adding the new loop would actually make the vehicle take a longer path home.  The previous logic also had a bug where it wasn't checking if the new loop completely surrounded the old loop which lead to duplicate loops and a nasty index overflow and freeze-up.

There is I'm afraid still one remaining issue.  If the user aborts the return-to-home we can end up with _simplify.path_points_completed and _prune.path_points_completed being greater than _path_point_count.  This can lead to the simplify and path pruning not running on these points.  I think the solution is probably just to reduce the _simplify.path_points_completed and _prune.path_points_completed when we pop a point.  ideally the main thread wouldn't touch these variables which are really owned by the background thread but I think it's safe because the background thread shouldn't be running when the front-end.pop is being called.

**Comment by Pedals2Paddles** [comment]
What will it do if the home position changes?  If the operator uses a GCS Return to Me function, the home position is updated to the GCS device location every few seconds.  Or if the operator otherwise manually changes the home location.

I'm guessing doing this would completely torpedo everything SmartRTL has done since there would no longer be a known reliable path to that new location.  In such a case, would SmartRTL be inhibited and failover to regular dumbRTL just as it would if the EKF goes bad or it didn't have a home location at all?

**Comment by squilter** [comment]
@Pedals2Paddles Currently, it will pretend that the home position was never changed, and go back to where it was armed.

**Comment by Pedals2Paddles** [comment]
hmm.  If that is going to be the case, that will need to be heavily documented and warned.  People who are using return to me functionality, or otherwise change the home position, usually do so because having it return to the launch location would be dangerous or destructive.  Such as being on a boat or traveling long distances or ground hazards.  The operator will expect it to go where they're telling it to go.  We also shouldn't expect the operator to remember to turn off SmartRTL parameters in such cases. They won't.

- If the current design is maintained, where it ignores home position changes and returns to the launch location regardless:
  - The GCS applications need to lock out return to me and home location changing functionality if SmartRTL is enabled. At least for those GCS apps that still have active developers.
  - There should be a mavlink warning message sent from the copter to the GCS if the home location changes while SmartRTL is enabled, informing the operator that the home location change is being ignored.  Something like "WARNING: Home Location Change Ignored in SmartRTL. Vehicle will return to launch."
  - Overstate this in the documentation / wiki / etc.  Also make note of it in the boat mode section of the wiki, since people using boat mode usually also use return to me.

- If the design changes and SmartRTL is disabled by home position changes:
  - There should be a mavlink message from the copter to the GCS informing the operator that home position changed and SmartRTL is now disabled.

**Comment by lvale** [comment]
@Pedals2Paddles 
Return to Me is different than Return to Launch, and different than to Return to Home. And I won't even go to the actions when you add Rally points.....

Launch Point should not be "artificially" changed. So the action enabled by SmartRTL should be just that. A breadcrumb optimized Return To Launch. 

If you change the Launch Point "artificially" the system has no way of guessing that the specific point is Safe to use, unless you use all the collision avoidance methods available, but that is way of scope of this, and unless something radical occurs on the path planning, octomaps realm occurs, the standalone STM32 family of cpu's won't be capable to handle the requirements AND fly the vehicle efficiently.
just my 2c

**Comment by lvale** [comment]
@rmackay9 
today flight test with rc11 translated to a mission, default parameters
[way.txt](https://github.com/ArduPilot/ardupilot/files/1278966/way.txt)

**Comment by Pedals2Paddles** [comment]
@lvale , unfortunately that isn't the case. Every GCS that has a return to me function does so by continuously updating the home position in ArduCopter.  And therefore, that is continuously updated home position is what RTL mode would return to when RTL mode is activated, either by mode change or failsafe.

So, IMO, smartRTL needs to take this into account somehow. Either by disabling itself when the home location changes and notifying the operator... or by rejecting the home location change and notifying the operator... or something.  I don't think it would be prudent to ignore this use case, especially since the use case has serious safety implications.  The first person that uses a return to me function and has their vehicle land a mile away from their boat will not be pleased.

**Comment by proficnc** [comment]
Yes, notifying the GCS that SafeRTL is in play, and preventing Return to me, or visa versa makes sense, as long as the GCS is super clear about the intention.

**Comment by lvale** [comment]
@Pedals2Paddles 
From what you are saying (I didn't check any of the existing sources) GCS's that implement a Return to Me are hacking the Launch location, which IMHO is wrong but was perhaps the easiest way to implement that feature. This doesn't make it correct, and I don't think that we should bow to a wrong principle.

Would be useful to check the code base of the GCS's you say implement that Return to Me feature.

If required a modification of the current RTL would be more future proof and safe, something like Return to This Point/Return to Here.

I was chatting with @rmackay9 about this, and he might have some useful insights regarding the Home, Launch location

**Comment by rmackay9** [comment]
From my point of view, I think this is all done now.  I've asked @peterbarker if he can have a final look at it and come up with anything else we should fix.  Any other feedback is also more than welcome!

@squilter, the example sketches do produce a failure but I think it's not actually an error but rather that we should update the test_path_after_pruning and test_path_complete.  do you agree?

**Comment by rmackay9** [comment]
@squilter, I'm looking more closely at the example sketches and I'll see if I can fix them.  One issue is that the new method only runs the pruning on points that have been simplified so this definitely breaks one of the tests.  The more complex issue is the "both" test coming up with different results, i haven't gotten to the bottom of that yet.

**Comment by Pedals2Paddles** [comment]
@lvale I agree it is a hackish method. But it's what they do and what they have done for very long time, and therefore what the operators will expect it to do. So this can't be ignored to make a point on principle. 

We know there are common use cases where the home location will change. So smartRTL needs to do something when that happens. The two choices I see are ignore it, always return to launch location, and warn the operator it won't go to the new location? Disable itself, fall back to normal RTL mode, and warn the operator that safeRTL is disabled?

**Comment by peterbarker** [comment]
On Wed, 6 Sep 2017, Matt wrote:

> We know there are common use cases where the home location will change. So
> smartRTL needs to do something when that happens. The two choices I see are

Well, now we're talking about "SafeReturnToHome", not safe RTL.

SafeReturnToHome would probably grow the list at both ends....

**Comment by Pedals2Paddles** [comment]
The average operator doesn't distinguish the terms home, launch, and origin. And they have no reason to today, and would never know there is a difference.

The behavior today that an average operator sees and expects is that RTL mode and the fail-safes that use it returns the copter to the home position. And when using a GCS return to me function, that home location changes with them, and that's where the copter is expected to go.

There may be more to it than that in the background. There may be different proper technical terms in the background. But that is what operators see and anticipate today. We can't ignore this reality, change the expected behavior, not tell anyone, and call it safe.

If we're going to change what the copter does to something else, and that something else will completely change an expected common use case, we need to do something with it. Ignoring it on the principal of technical wording is asking for highly undesirable and unsafe results.

**Comment by squilter** [comment]
@rmackay9 Your changes fixed the issue of bad loop pruning that I noticed last time. Nice job.

Yes, the different cleanup strategy might make it hard to fix the "both" section of the example script. I wouldn't have a problem if you just removed that part. And it's totally fine to change the `test_path_after_pruning` since the algorithm produces a slightly different result now.

**Comment by rmackay9** [comment]
I've rebased on master, fixed the example sketch, rename to "SmartRTL".  Once Travis confirms it's ok I plan to push to master.

**Comment by Pedals2Paddles** [comment]
Just in time for the weekend!  Nice work everyone.

**Pull request merged**
