### PR TITLE
Tracker: add auto opts param

### PR DESCRIPTION
**Pull request by IamPete1**
This adds a bitmask who's first bit can be used to allow scanning before a vehicle has been found in auto mode.

Tested in SITL

### CODE REVIEW

**Comment by rmackay9** [comment]
Not passing travis for some reason.  I tried to restart the build but was unable to for some reason.

**Comment by IamPete1** [comment]
rebased in an attempt to get this passing checks

**Comment by IamPete1** [comment]
@peterbarker rebased this

**Comment by IamPete1** [comment]
@peterbarker now mended the bad rebase ;)

**Comment by peterbarker** [comment]
Rebased this.

**Comment by peterbarker** [comment]
Merged, thanks!

**Comment by IamPete1** [comment]
@peterbarker Thanks

**Pull request merged**
