### PR TITLE
libraries: Change the word(NFC)

### PR DESCRIPTION
**Pull request by muramura**
I think mili is a typo.
I'll change it to milli.

### CODE REVIEW

**Review by peterbarker — CHANGES_REQUESTED** [review]
Looks good, but could we change the commit message to:

`something: correct spelling mili -> milli`

**Comment by muramura** [comment]
@peterbarker san
I agree. I will change the title.

**Comment by muramura** [comment]
I have changed the commit title.

**Comment by rmackay9** [comment]
Merged, thanks!

**Pull request merged**
