### PR TITLE
Simplify our Stream stuff

### PR DESCRIPTION
**Pull request by peterbarker**
Eliminate a couple of layers, leaving us with just BetterStream.

The BIG point of contention here will probably be the lambda (since C++11 ;-) )

### CODE REVIEW

**Comment by magicrub** [comment]
I'm glad you like doing this stuff... Because I sure don't!

**Comment by tridge** [comment]
thanks!
I haven't actually used that functional stuff before. Any gotchas with it with compiler versions? It seems to have broken the fmuv3 chibios build for some reason.
Apart from that it looks good!

**Comment by peterbarker** [comment]
On Thu, 22 Mar 2018, Andrew Tridgell wrote:

> I haven't actually used that functional stuff before. Any gotchas with it
> with compiler versions? It seems to have broken the fmuv3 chibios build for
> some reason.

Yeah, I'm giving up on <functional> for the time being.  I blame ChibiOS 
:-)  Note that we already <functional> in non-flight code :-)

I tried replacing the lamda with the age-old function pointer/void* cruft. 
That was ugly.  I considered using functors, and decided they'd be almost 
as ugly as the void* cruft

I'm going to force-push something up that retains the bodgy BufferPrinter 
thing, inheritting from BetterStream.  Not my fight, at least not for 
today.

**Comment by lucasdemarchi** [comment]
@peterbarker you'd need to take care with functional and lambda as they allocate memory from heap. Functor we have is exactly the same except the syntax sugar for lambda, but you can have it statically allocated and initialized, which means that on stm32 it ends up on flash.

**Comment by lucasdemarchi** [comment]
That said, I don't see a lambda in this code, nor the possible place in which it would be in the previous version. I would still get rid of the vprintf() implementation.

**Comment by peterbarker** [comment]
@lucasdemarchi I wonder what those stack overheads are... some experimentation required, thanks!

Getting rid of the `vfprintf` would be beyond the scope of this issue.

I assume you're suggesting we use the standard library's version?

I still haven't nutted out what the ChibiOS HAL is doing implementing these string functions itself..

**Comment by amilcarlucas** [comment]
WTF Peter you just removed over 300 lines of code!!!
Don't do that, we will end up with a small and clean codebase, nobody wants that !!!
;-)

**Comment by lucasdemarchi** [comment]
> I assume you're suggesting we use the standard library's version?

yep

**Comment by tridge** [comment]
> I assume you're suggesting we use the standard library's version?

I'd prefer to keep our version. We've had too many troubles in the past with libc vprintf, and having our own means we know we behave the same on all boards

**Comment by lucasdemarchi** [comment]
@tridge, isn't that long ago in the Arduino era? Can we try and revert back in case it goes south?

**Comment by tridge** [comment]
> @tridge, isn't that long ago in the Arduino era? Can we try and revert back in case it goes south?

not just arduino. If we use libc then we get a different printf based on toolchain. We get double support even if we don't want it. We get a boatload of helper string functions we don't really want. 
I'm really happy with our printf system - it means when I run in SITL we get as close as we can to a real system.

**Pull request merged**
