### PR TITLE
Remove gcs console

### PR DESCRIPTION
**Pull request by peterbarker**
Closes https://github.com/ArduPilot/ardupilot/issues/1899 (in a somewhat extreme fashion).

### CODE REVIEW

**Comment by Pedals2Paddles** [comment]
Simplification by elimination.

**Comment by magicrub** [comment]
Does this make the binary size smaller?

**Comment by Pedals2Paddles** [comment]
By at least 2,000,000 microbytes.

**Comment by OXINARF** [comment]
Merged, thanks!

**Comment by peterbarker** [comment]
On Tue, 9 Jan 2018, Tom Pittenger wrote:

> Does this make the binary size smaller?

No.  Apparently the optimisation works :-)

**Pull request merged**
