### PR TITLE
HAL_ChibiOS: fixed DMA disable on contention

### PR DESCRIPTION
**Pull request by tridge**
this fixes a problem with the automatic DMA disable on DMA contention
in UARTs. This fixes issue #14581

the problem was that while tx_dma_enabled was correctly set to false,
it would keep looping inside write_pending_bytes_DMA() if the data
arrived in the write buffer at a faster rate than it could be sent
out, which did happen with a mavlink stream rate of 4Hz. This means it
kept using DMA even with tx_dma_enabled set to false. The result was
that the automatic flow control code never got a chance to run and we
didn't switch back to non-DMA for these low baudrate contended UARTs

### CODE REVIEW

**Comment by rmackay9** [comment]
this looks important.. I wonder if this could improve GPS-for-yaw?

**Comment by peterbarker** [comment]
autotest failure is a new one on me; vehicle said it was OK to arm but it wasn't - and the arming failure didn't produce any diagnostic string.

**Comment by tridge** [comment]
> autotest failure is a new one on me; vehicle said it was OK to arm but it wasn't - and the arming failure didn't produce any diagnostic string.

only changes are in HAL_ChibiOS, so this PR cannot cause an autotest failure

**Review by andyp1per — APPROVED** [review]
I think this is ok but it would be worth running with assertions enabled to verify the lock ordering

**Comment by tridge** [comment]
> I think this is ok but it would be worth running with assertions enabled to verify the lock ordering

I've tested with assertions enabled on a CubeOrange, running UART2 and UART2 with mavlink

**Pull request merged**
