### PR TITLE
Tools: added name to GIT_Success.txt

### PR DESCRIPTION
**Pull request by Biswajitghosh98**
This PR adds my name to GIT_Success.txt file

### CODE REVIEW

**Comment by rmackay9** [comment]
@Biswajitghosh98, you're going to rebase on master?

**Comment by Biswajitghosh98** [comment]
@rmackay9 Yes. Please correct me if I am wrong. I'll send a second pull request accordingly.

**Comment by rmackay9** [comment]
@Biswajitghosh98, yes, rebasing on master and resending would be good.  I've just merged another commit to the same file so you'll need to rebase on latest master.

**Comment by Biswajitghosh98** [comment]
@rmackay9 Thank You for replying. Another PR on it's way. By the way if you have some time to spare, can you please check out the video I sent on the gitter channel ArduPilot/GSoc. Andrew tagged you for a review too. It'll be great to see if it matches your expectations for the same.

**Pull request closed without merging**
