### PR TITLE
ChibiOS tonealarm

### PR DESCRIPTION
**Pull request by kd0aij**
- [x] tested on PixRacer and AUAVX2.1
- [x] add support for MindPX
- [x] is the separate toneAlarm thread optimal?
- [x] determine necessary stack size for new toneAlarm_thread 
- [ ] is thread priority OK?
- [ ] move the tune definitions from ToneAlarm.cpp to hwdef.dat

notes:
- changed chibios_hwdef.py to add separate config for alarm pwm output
- stack size of 256 seemed sufficient; set to 512 to be conservative
- tick frequency is currently 100Hz; this provides 10 msec precision for note duration
       I can't tell what precision is in the Linux version... timeslice?
- there is a lot of code duplication...

### CODE REVIEW

**Comment by tridge** [comment]
hi Mark, we need #ifdefs around the creation of the thread and the building of the code based on HAL_PWM_ALARM (or another define that is only there if hwdef.dat does define an alarm pin). We don't want to pay for this in cpu, ram or flash if there is no alarm pin

**Comment by Pedals2Paddles** [comment]
I just built this and loaded on my Solo (Pixhawk 2).  We have beeping!  The beeps appear to be slow with longer spacing between them compared to the old PX4 tones.  Not a complaint, just noting the difference.

**Comment by kd0aij** [comment]
@tridge That saves a fair amount of flash space. I hope "#ifdef HAL_PWM_ALARM" is OK

with HAL_PWM_ALARM undefined:
   text	   data	    bss	    dec	    hex	filename
 857712	   3244	 193904	1054860	 10188c	build/fmuv4/bin/arduplane

with HAL_PWM_ALARM defined:
   text	   data	    bss	    dec	    hex	filename
 859360	   3376	 193776	1056512	 101f00	build/fmuv4/bin/arduplane

**Comment by kd0aij** [comment]
@Pedals2Paddles Glad to *hear* it.  This uses a different driver for playing the tunes, and the syntax for defining tunes is different.  I'm not sure whether the two sets of tunes are supposed to be identical, but I did check that the note durations of this implementation are as specified.

**Comment by tridge** [comment]
thanks for this Mark!
I know there are a few more things we can do, but lets do them as a separate PR

**Pull request merged**
