### PR TITLE
AP_UAVCAN: use fixed-size memory pool

### PR DESCRIPTION
**Pull request by jschall**
Avoids heap allocation in flight

### CODE REVIEW

**Comment by jschall** [comment]
64 is the recommended block size from Pavel.
pyuavcan (and by extension the GUI tool) with my recent patches keeps up
much better

On Jul 12, 2018 3:28 PM, "Andrew Tridgell" <notifications@github.com> wrote:

note that the firmware in libraries/AP_UAVCAN/examples/UAVCAN_sniffer is
good for testing the msg rates. The Linux based tools can't keep up

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ArduPilot/ardupilot/pull/8878#issuecomment-404670307>,
or mute the thread

**Comment by magicrub** [comment]
I'll test this change on top of https://github.com/ArduPilot/ardupilot/pull/8972/files

**Comment by jschall** [comment]
@tridge ping on this one... currently AP_UAVCAN will allow dynamic allocation of up to 8192 256-byte blocks, using up to 2 MB of RAM - very very broken.

**Comment by tridge** [comment]
tested this with various options, works well. It does cost us about 3k of ram in practice, but prevents ram usage in pathological situations

**Pull request merged**
