### PR TITLE
Add filter reset when vehicle is idle for too long

### PR DESCRIPTION
**Pull request by andyp1per**
Potentially a fix for #16094 which is already in EK2

### CODE REVIEW

**Comment by andyp1per** [comment]
I think this has fixed it for me - thanks @tridge ! You can see I am getting the forced reset message but I can still consistently arm and get off the ground:

image

**Comment by tridge** [comment]
@andyp1per great, glad it worked! I'd like @priseborough to look at this as well though. There may be some extra things we need for this on EK3 that we don't have in EK2

**Review by priseborough — APPROVED** [review]
This is a harmless change that will reduce user frustration. I would still like to get  a replayable log for one of these instances.

**Comment by tridge** [comment]
thanks Paul

**Pull request merged**
