### PR TITLE
Be consistent across our vehicles in terms of VFR_HUD.alt

### PR DESCRIPTION
**Pull request by peterbarker**
Sub and Copter were erroneously (according to spec) sending height-above-home in this field.

This PR makes all of our vehicles consistent, sending height above (below...) MSL.

@night-ghost - there's some confusion about MinimOSD's handling of this field.  At least we'll be consistent after this PR.

### CODE REVIEW

**Comment by rmackay9** [comment]
I'm sure we're going to get support calls but I think we can deal with that by showing people how to get the relative altitude in MP (and perhaps other ground stations).

**Comment by peterbarker** [comment]
Tagging GCS authors I can think of:
@meee1 @billbonney @WickedShell @DonLakeFlyer

**Comment by auturgy** [comment]
@MishkaRogachev (jagcs) and @episarenko (ugcs) too

Regards,

James

**Comment by amilcarlucas** [comment]
Is this not supposed to be relative to home ???

**Comment by peterbarker** [comment]
@amilcarlucas Nope - https://github.com/ArduPilot/mavlink/blob//message_definitions/v1.0/common.xml#L3210

**Comment by amilcarlucas** [comment]
@peterbarker  the link you sent is for LOCAL_POSITION_NED_COV.

Yes, that was the point that I talked in the meeting last night and a couple of weeks ago. PX4 code is using alt relative to home. So it makes more sense to change the standard and keep the current code.

Or did I misunderstood something ?

**Comment by peterbarker** [comment]
On Tue, 29 May 2018, Amilcar Lucas wrote:

> Yes, that was the point that I talked in the meeting last night and a couple
> of weeks ago. PX4 code is using alt relative to home. So it makes more sense
> to change the standard and keep the current code.
> 
> Or did I misunderstood something ?

I believe that was GLOBAL_POSITION_INT - where relative_alt is in the spec 
as above-ground but both ArduPilot and PX4Firmware are above-home.

I don't think anybody will be fussed on which way we change it in AP - the 
point of this PR is to be consistent across AP vehicles!

Please verify what PX4 Firmware send in VFR_HUD.alt - I just had a quick 
peek and I see the phrase "global" being thrown around a bit in there.

**Comment by amilcarlucas** [comment]
@WickedShell Sorry I missed those links at the meeting.
@peterbarker yes, I confused it with GLOBAL_POSITION_INT.

@DonLakeFlyer Does PX4 Firmware send in MLS altitude in VFR_HUD.alt message? According to the links in the comments above it looks like it does. But we want to make sure.

**Comment by DonLakeFlyer** [comment]
> Does PX4 Firmware send in MLS altitude in VFR_HUD.alt message?

Don't know. I switched QGC away from VFH_HUD for altitude because of all the differences. It now use GPS messages, or if no GPS it uses the ALTITUDE message for altitude.,

**Pull request merged**
