### PR TITLE
Plane/SpdHgtCtrl/TECS: we should never talk directly to TECS

### PR DESCRIPTION
**Pull request by samuelctabor**
Removes some (all?) remaining instances of directly interacting with TECS.

### CODE REVIEW

**Comment by IamPete1** [comment]
I actually would be tempted to go the other way and remove the `SpdHgt_Controller` indirection all together. I guess you might be working on a alternate so we could actually switch. I do think we should at least shove them all in one place.

**Comment by samuelctabor** [comment]
> i'd be happy to remove the intermediate layer, it doesn't really add anything

Okay doky. It would be good to define up front - 

 - what the pointer/reference should be called - SpdHgt_Controller is more descriptive than TECS but less specific;
 - what to do with other objects that currently cache a pointer to SpdHgt_Controller (Soaring, L1_Controller, Landing) - e.g. TECS singleton?

**Comment by samuelctabor** [comment]
@tridge see above, what's your preference on this?

**Comment by tridge** [comment]
> @tridge see above, what's your preference on this?

I think it is fine to call it TECS, but if you prefer to keep it as SpdHgt_Controller to keep the diff small that is fine too.

> what to do with other objects that currently cache a pointer to SpdHgt_Controller (Soaring, L1_Controller, Landing) - e.g. TECS singleton?

we could add a TECS singleton

**Pull request closed without merging**
