### PR TITLE
ACRO_TRAINER_DIRECT acro variant

### PR DESCRIPTION
**Pull request by tridge**
This adds a new ACRO_TRAINER=3 option which uses the quaternion acro mode from Jon which is independent of the EKF attitude solution. This makes it a great recovery mode, especially for helicopters. 
I have done several flights with this on a 250 sized quad with good results

### CODE REVIEW

**Comment by tridge** [comment]
hi Randy, I know you're not keen on the change to always allow ACRO mode with this setting. What about if that only applied to heli? In fact, it doesn't really make sense to ever disallow acro for a heli, as there is no safety issue (going to acro makes no difference to the throttle speed so poses no safety issue)

**Comment by tridge** [comment]
I've updated the PR to make the failure to enter acro not happen for helis

**Comment by tridge** [comment]
added needs-rework as I'm discussing some changes with Jon

**Comment by R-Lefebvre** [comment]
Tridge, I see a lot of changes exclusively to control_acro file, but I think you've missed heli_control_acro.  There's a heli_control_stabilize as well.  Those are the only two modes with their own files.  At the time these were created, it made sense due to complexity, but maybe it doesn't anymore.  We'll have to look at that issue separately.

Anyway, I suspect there's a chance you haven't actually tested this new mode on a helicopter yet, as you haven't made changes to heli_control_acro yet.

**Comment by rmackay9** [comment]
Perhaps Tridge's comment to add "Need-rework" is because the acro quaternion controller changes will conflict with Jon's PR: https://github.com/diydrones/ardupilot/pull/3229

It looks like the ACRO_TRAINER param is being used to set the type of attitude controller used but that parameter's intention was to control the strength of the "trainer" which helps keep the vehicle level for beginner acro pilots.

**Comment by tridge** [comment]
Rob, you're right, thanks!!

**Comment by tridge** [comment]
Randy, would you prefer a new parameter? Any suggestions on a name if so?

**Comment by jschall** [comment]
Ideally I'd get input shaper/attitude controller split done and then figure out how this fits in with the attitude controller interface. However, I can also do that after this goes in.

**Comment by tridge** [comment]
I've updated the PR with the other patches from Jon and with heli support. It is not flying correctly in the sim though. Yaw control is quite different from ACRO_TRAINER=0, with much less yaw rate available, and an oscillation in yaw rate. I can provide logs if needed

**Comment by jschall** [comment]
I flew this in SITL and did not experience what you experienced. Can you provide reproduction steps?

**Comment by tridge** [comment]
hi Jon, to reproduce do this (assumes current PR code, updated today)
1) rm eeprom.bin
2) run SITL like this:
sim_vehicle.sh -j6 -D -G -f heli
3) disable float exceptions (there is a problem in the nav library in acro, I'll do a separate PR for that)
param set SIM_FLOAT_EXCEPT 0
4) load standard heli parms
param load ../Tools/autotest/Helicopter.parm
5) set ACRO_TRAINER to 0
6) set unlimited accel on yaw
param set ATC_ACCEL_Y_MAX 0
(otherwise the low default limits hide the issue)
7) graph rc4 in and servo4 out
graph RC_CHANNELS_RAW.chan4_raw SERVO_OUTPUT_RAW.servo4_raw
8) change yaw input to 1000 then 2000
rc 4 1000
rc 4 1000
9) try with ACRO_TRAINER=0 and ACRO_TRAINER=3
You get about 1/3 of the movement of tail servo with ACRO_TRAINER=3

**Comment by lucasdemarchi** [comment]
@tridge any update on this?

**Comment by jschall** [comment]
@lucasdemarchi I intend to implement this on the upcoming new AC_AttitudeControl architecture.

**Comment by lucasdemarchi** [comment]
@jschall thanks

**Comment by tridge** [comment]
this has been obsoleted by recent work by Leonard. Closing

**Pull request closed without merging**
