### PR TITLE
FFT watchdog

### PR DESCRIPTION
**Pull request by andyp1per**
Fixes https://github.com/ArduPilot/ardupilot/issues/20884

### CODE REVIEW

**Comment by andyp1per** [comment]
@Jaaaky should fix this issue

**Comment by rmackay9** [comment]
Txs for finding and fixing this.

I think it might be better if we can move the "fft->prepare_for_arming();" to be in AP_Arming::arm().

I think where it is (even now) is muddying the waters because it's not an arming check, it's something that needs to be done at arming similar to starting logging or setting the terrain reference altitude.

**Review by rmackay9 — DISMISSED** [review]
see comment above

**Comment by andyp1per** [comment]
Thx, fixed

**Comment by andyp1per** [comment]
Thx, fixed

**Comment by Jaaaky** [comment]
Looks fine

**Review by tridge — APPROVED** [review]

**Pull request merged**
