### PR TITLE
Copter: Change the description(NFC)

### PR DESCRIPTION
**Pull request by muramura**
Include the methods for LUA scripts within the range of the preprocessor.

### CODE REVIEW

**Review by IamPete1 — CHANGES_REQUESTED** [review]
I don't think this is correct, these methods are used by DroneCAN.

https://github.com/ArduPilot/ardupilot/blob/eb8eeba8516f5fc3a83b82a7f03235c2ca6578ae/libraries/AP_DroneCAN/AP_DroneCAN.cpp#L1033-L1041

**Comment by muramura** [comment]
@IamPete1 san.
Thank you for the review. I will revert the changes and remove the phrase "script only."

**Comment by muramura** [comment]
@IamPete1 san.
I changed the title.
I changed the description.

**Comment by peterbarker** [comment]
Corrected commit message, marking for merge

**Pull request merged**
