### PR TITLE
HAL_ChibiOS: lower speed of mpu9250

### PR DESCRIPTION
**Pull request by tridge**
it isn't handling the full speed well on the CubeBlack+, getting some SPI transfer errors

### CODE REVIEW

**Comment by amilcarlucas** [comment]
Is this only on CubeBlack+ or also in the original CubeBlack ?

**Comment by tridge** [comment]
@amilcarlucas the change affects both. I only saw the error on a CubeBlack+, but I'd prefer to change on all boards as there is no actual difference in FMU between CubeBlack and the +

**Comment by magicrub** [comment]
does 6 MHz work?

**Comment by tridge** [comment]
I've now reverted this as on another CubeBlack it caused issues with the first IMU
This warrants some more investigation

**Pull request merged**
