### PR TITLE
AP_RangeFinder: To define the OK status to LEDDARONE status.

### PR DESCRIPTION
**Pull request by muramura**
The return value of send_request method is 0.
Detailed error in the status definitions are defined.
OK defining the status is not defined.

Therefore, to define the OK status to LEDDARONE status.

### CODE REVIEW

**Comment by ShingoMatsuura** [comment]
I think it is readable.

**Comment by magicrub** [comment]
I like that much better. What about making all these statuses an enum?

**Comment by ShingoMatsuura** [comment]
Enum is good. Im going to change to enum.

**Comment by muramura** [comment]
@magicrub, @ShingoMatsuura  Thanks Comments.
Original developer @ ShingoMatsuura, enum change, thank you.

**Comment by magicrub** [comment]
merged, thanks! Also, define != enum but this is close enough (for now)
PROTIP: branches with names that describe the changes are helpful to reviewers!

**Pull request closed without merging**
