### PR TITLE
AP_BoardConfig: Increase the number of digits in the board serial number

### PR DESCRIPTION
**Pull request by muramura**
I use numbers to represent the unique aircraft number.
I use an 8-digit number.
I want to use INT16 to INT32.
INT32 can represent a 10-digit number.

### CODE REVIEW

**Comment by magicrub** [comment]
This is my fault, I always regret not making it 32. Unless there's a new development that I'm not aware of, it's too late to change now. We can't change the size of an existing param because it will corrupt the param table. :(

**Comment by hendjoshsr71** [comment]
> This is my fault, I always regret not making it 32. Unless there's a new development that I'm not aware of, it's too late to change now. We can't change the size of an existing param because it will corrupt the param table. :(

Not true see this function in AP_Param a usage example is here,

https://github.com/ArduPilot/ardupilot/blob/b7bd8cd6be3b062e3ccd12f16e157f270567ab7b/ArduCopter/Parameters.cpp#L1231-L1233

Converting widths like that would need to be done in this PR. 

To do this I think you would need to add the following in at the top of `AP_BoardConfig::init()`

`vehicleSerialNumber.convert_parameter_width(AP_PARAM_INT16);`

**Comment by muramura** [comment]
@hendjoshsr71 san.
Thanks for the comment.
I have added a local serial number parameter to an older version.
I want to use the standard parameter.
I want to address in the review comments.

**Comment by WickedShell** [comment]
It's worth noting you will only gain 7 effective bits with the float transport of params. (After that it becomes hit or miss if you can get the value you requested).

**Comment by hendjoshsr71** [comment]
> @hendjoshsr71 san. Thanks for the comment. I have added a local serial number parameter to an older version. I want to use the standard parameter. I will respond with a review comment.

@muramura san Ping on this one to add the  Parameter width conversion

**Review by tridge — APPROVED** [review]

**Review by tridge — APPROVED** [review]

**Comment by muramura** [comment]
ardupilot is suppressing stm32 exceptions and will continue processing.

**Pull request merged**
