### PR TITLE
Add a ChibiOS based bootloader

### PR DESCRIPTION
**Pull request by tridge**
This adds a bootloader based on ChibiOS, that uses the hwdef.dat system for configuration. It has been tested on:

-  stm32f405
-  stm32f745
-  stm32f765
-  stm32f777

The bootloader protocol is based on the old bootloader, and is compatible with it (so same upload tools)
The main downside of this new bootloader is that is produces a larger bootloader binary than the old one (which is based on libopencm3). For STM32F7 that isn't an issue, as the first sector is 32k and the bootloader ends up well under that. For STM32F4 it is a problem as the bootloader ends up as about 20k, but the first sector is 16k on F4. That means it works if we reserve two sectors for the bootloader, which we do on some boards, but won't work for boards like fmuv3 or fmuv4.
Trimming this bootloader down below 16k would make it much more useful

Update: the bootloader is now well below 16k for all boards, thanks to some great work by @sh83

ping @bugobliterator, @mirkix and @sh83 

To use this bootloader do this (example for cube-orange):

 ./waf configure --board cube-orange --bootloader
 ./waf bootloader

then load build/cube-orange/bootloader/AP_Bootloader.bin with DFU

### CODE REVIEW

**Comment by proficnc** [comment]
Thanks Tridge!

**Comment by Linjieqiang** [comment]
Nice work.But I have some questions about your code.
1. Why not use "rtc signature" to determine whether an update is needed?
2. Is CAN_BUS interface supported?

**Comment by vooon** [comment]
Maybe you can use nil rtos (alternative kernel in chibios) to shrink down binary size.

**Comment by mirkix** [comment]
@tridge Thanks! Can you check the location of `build/cube-orange-bootloader/AP_Bootloader.bin` I found that file at `build/cube-orange-bootloader/tools/AP_Bootloader.bin`

**Comment by tridge** [comment]
@mirkix yes, I've been updating that. It is now "./waf bootloader" and the file ends up in 
build/cube-orange-bootloader/bootloader/AP_Bootloader.bin

**Comment by tridge** [comment]
@vooon possibly, but we need USB support, and later UART. I haven't tried nil yet, so I don't know if we'd get the features we need

**Comment by tridge** [comment]
@Linjieqiang I haven't looked at using the RTC to determine boot mode yet, but there is a general problem with the "boot immediately unless fw asked to stay in bootloader" approach. The problem is that if there is a crash bug in the current fw, then it will never stay long enough in the bootloader to load a new fw that fixes the bug.

>     Is CAN_BUS interface supported?

not yet

**Comment by mirkix** [comment]
@tridge LGT, just get it working on my NUCLEO-F767ZI dev board. Would like to create a bootloader PR for this board. Could you please assign me a APJ_BOARD_ID for this board.

**Comment by tridge** [comment]
@mirkix I've opened a PR against the px4 bootloader for managing boards IDs here:
https://github.com/PX4/Bootloader/pull/104
once that is accepted we can add board IDs there, giving us a common ID location for both bootloaders

**Comment by tridge** [comment]
meanwhile, you can PR against github.com/ArduPilot/Bootloader by editing board_types.txt

**Comment by mirkix** [comment]
@tridge Done. https://github.com/ArduPilot/Bootloader/pull/3

**Comment by Linjieqiang** [comment]
@tridge https://github.com/PX4/Bootloader/blob/e6e7539b20d9367cf6210c0d78bd725bee3a59d3/main_f4.c#L723-L740
https://github.com/PX4/Bootloader/blob/e6e7539b20d9367cf6210c0d78bd725bee3a59d3/main_f4.c#L814-L829

**Comment by tridge** [comment]
@Linjieqiang ahh, ok, yes, we could implement that in the same way

**Comment by peterbarker** [comment]
Building for cube-orange-bootloader doesn't work unless you've previous configured for cube-orange.

Steps to reproduce:
```
rm -rf build
./waf configure --board=cube-orange --bootloader
./waf bootloader
```

```
Waf: Entering directory `/home/pbarker/rc/ardupilot/build/cube-orange-bootloader'
Checking for env.py
No env.py found
[3/7] Processing modules/mavlink/message_definitions/v1.0/ardupilotmega.xml
[4/7] Creating build/cube-orange-bootloader/ap_version.h
[5/7] Creating build/cube-orange-bootloader/hwdef.h
[6/7] Creating build/cube-orange-bootloader/modules/ChibiOS/include_dirs
Setup for MCU STM32F777xx
Writing hwdef setup in /home/pbarker/rc/ardupilot/build/cube-orange/hwdef.h

Traceback (most recent call last):
  File "/home/pbarker/rc/ardupilot/libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py", line 1193, in <module>
    write_hwdef_header(os.path.join(outdir, "hwdef.h"))
  File "/home/pbarker/rc/ardupilot/libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py", line 942, in write_hwdef_header
    f = open(outfilename, 'w')
IOError: [Errno 2] No such file or directory: '/home/pbarker/rc/ardupilot/build/cube-orange/hwdef.h'
```

```
pbarker@bluebottle:~/rc/ardupilot((HEAD detached at tridge/pr-ap-bootloader))$ ls /home/pbarker/rc/ardupilot/build/
c4che       cube-orange-bootloader  fmuv2-bootloader  fmuv4  revo-mini
config.log  fmuv2                   fmuv3             linux  sitl
pbarker@bluebottle:~/rc/ardupilot((HEAD detached at tridge/pr-ap-bootloader))$ 
pbarker@bluebottle:~/rc/ardupilot((HEAD detached at tridge/pr-ap-bootloader))$ 
```

Also falls over building:
```
../../libraries/AP_HAL_ChibiOS/hwdef/common/chibios_common.mk:230: recipe for target 'modules/ChibiOS/obj/fatfs_diskio.o' failed

../../modules/ChibiOS/os/various/fatfs_bindings/fatfs_diskio.c:21:2: error: #error "MMC_SPI or SDC driver must be specified"
 #error "MMC_SPI or SDC driver must be specified"
  ^~~~~
In file included from ../../modules/ChibiOS/os/hal/include/hal.h:120:0,
                 from ../../modules/ChibiOS/os/various/fatfs_bindings/fatfs_diskio.c:8:
../../modules/ChibiOS/os/various/fatfs_bindings/fatfs_diskio.c: In function 'disk_initialize':
```

**Comment by tridge** [comment]
@peterbarker fixed, thanks!

**Comment by vooon** [comment]
@tridge previously i done SD bootloader which takes [ofw][1] file and write (F373, SD on SPI, FATFS).
As i remember with ch kernel i have to reserve 32k, when i switch to nil - 28k. Most space used for HAL and zlib compatible decompressor.

**Comment by sh83** [comment]
@tridge I was able to reduce bl size by about 1.5kb just reducing .ALIGN(16) to .ALIGN(4) for .text section inside common.ld

**Comment by proficnc** [comment]
does this have the 2x 32K reserved flash included?

**Comment by magicrub** [comment]
@vooon I would be very happy to see either your SD bootloader or the one from Traxxas get into master. With the opportunity of new chips like this I'd say let's reserve room for a huge bootloader to handle sdMicro, Serial, AND USB bootloaders all at the same time. This could also give a big incentive to upgrade to the Orange!

**Comment by vooon** [comment]
@magicrub it's a bit hard to extract from my old project (which i don't want to publish), also it is very quick and dirty.
I can make a zip, but don't think that it is really helpful, since it parses CBOR based file.
Apj (or .px4) - JSON based. So only helpful findings is inflate library - [tinf][1], because that library works ok with small ram buffers, while zlib require 32k (can't fit in f373).

[1]: http://dfrank.ru/prog/c/tinf

**Comment by sh83** [comment]
@tridge  I have reduced revo-mini bl to 14320b. Also this fixes reduce main fw size by about 35kb. Please take a look https://github.com/tridge/ardupilot/pull/18

**Pull request merged**
