### PR TITLE
Copter: automatically yaw towards closest proximity obstacle

### PR DESCRIPTION
**Pull request by IamPete1**
Use case is for inspection where the operator might be using the onboard camera only and not be able to see obstacles behind, the copter will now yaw to face them once they are closer than some threshold. 

Demo with bad audio, Sorry

https://youtu.be/cjzeUmeFvVc

Should work quite well with https://github.com/ArduPilot/ardupilot/pull/14186

Might be better off implementing this completely in copter rather than adding functions in AP_Proximity.

@rishabsingh3003

### CODE REVIEW

**Comment by rmackay9** [comment]
Very interesting!  I wonder if perhaps we should do this as a lua script at least for now?  Then if it becomes popular and users struggle with the burden of using the scripts or the integration is messy we can move it to C++?

**Comment by IamPete1** [comment]
@rmackay9 Currently the implementation doesn't lend its self to lua because it calls a different attitude controller. Unless you have any ides in that direction?

**Comment by rmackay9** [comment]
@IamPete1,

It would fit better into our existing structure if the controller part was pulled out of the sensor library.  We don't do terrain following from inside the AP_RangeFinder library for example.

I think it would be better to instead expose the proximity data to lua scripts and then lua scripts could use a vehicle level set_attitude_target or set_yaw_target() method to point the vehicle in the correct direction.

Allowing an external system to control the vehicle's yaw in Loiter mode is also a step we need to be careful of.  In some ways we've already made this step with precision loiter but in any case, it's a step towards mixing autonomous and pilot controls and we risk further complicating this already complex flight mode and having situations where the pilot can't control the vehicle because an external controller is misbehaving.

**Comment by rmackay9** [comment]
.. to be clear, despite my worries above, I'm not against this change I think.  Inspection is an important use-case that many users are interested in.  I think adding this new point-towards-closest-object is a good one to add to AutoYaw so that it can be used in many modes.  The we can also extend Loiter to support AutoYaw... but make sure that if the user moves the yaw stick around Loiter stays in pilot controlled yaw.

**Comment by rishabsingh3003** [comment]
Really interesting! I always wanted to implement this feature and one where we can possibly have a servo mounted with a 1-D lidar which can point towards the closest object. The second one should be pretty easy to do in lua IG.
Anyhow, since my primary driver is a benewake Tfmini (1-D lidar) and I use it daily, I will test this out on a real vehicle when ever its ready.
Also, let me know if you want me to build a Morse blender environment to test this...  One can very easily make any sort of environment with various range's of 1-D lidar

**Comment by IamPete1** [comment]
Rebased and moved all up into copter

**Comment by IamPete1** [comment]
@rishabsingh3003 would be great if you could have a look over this, I can't 'officially' request your review for some reason.

**Comment by IamPete1** [comment]
this should be a lua script, although it would be nice to add bindings for some functions to allow guided via scripting to behave in a more loiter like way.

**Pull request closed without merging**
