### PR TITLE
Frame_params: fix param names

### PR DESCRIPTION
**Pull request by jberaud**
Broken by AP_Motors refactoring

This can be split by frame if someone prefers.

### CODE REVIEW

**Comment by rmackay9** [comment]
I've merged the bebop ones for now.  The others I think should wait until Copter-3.4 goes out (or at least until beta testing starts) because most users of those param files (and I'm unsure how many use them) will most likely be on the official release which still uses the old names.

**Comment by jberaud** [comment]
@rmackay9 thanks for merging for the Bebops. Regarding the other frames, it's up to you but IMHO it is bad to have on the same repository params that don't currently work on master. One of the key points of having those param files is so that they correspond to the current master. If the users of 3.4 need the old params, then the old params should be on branch 3-4 but not on master.

**Comment by rmackay9** [comment]
Yeah, the thing is that the GCSs don't currently go to the branches to get the frame parameters, they go straight to master.  So I guess we should get the GCSs sorted out so we can handle it properly.

**Comment by jberaud** [comment]
@rmackay9 It makes sense. Thanks for the explanation and yes I think we need to get the GCSs sorted out.

**Pull request closed without merging**
