### PR TITLE
AP_Periph: fixed GPS dropout on F4 and L4 GPS nodes

### PR DESCRIPTION
**Pull request by tridge**
we need more time for other threads on these nodes or we will end up dropping GPS frames

### CODE REVIEW

**Review by peterbarker — APPROVED** [review]
LGTM.

A note on tests, 'though - if the script were structured as a library it would allow easier reuse, so you could end up with a single script you could run against a node to check many things out at the same time.    Might be handy when coming up on release time to avoid regressions.

**Comment by tridge** [comment]
> if the script were structured as a library it would allow easier reuse, so you could end up with a single script you could run against a node to check many things out at the same time.

i'd be happy for the script to evolve in that direction, but for now the simple script works, and demonstrates nicely how to use pydronecan for this sort of task

**Review by bugobliterator — APPROVED** [review]

**Comment by MallikarjunSE** [comment]
Tested on F405 node. Works without dropout.
image

**Comment by MallikarjunSE** [comment]
Tested on F412 nodes. No GPS dropout.
image

**Pull request merged**
