### PR TITLE
Quat Tests and new *(Vector3f) operator

### PR DESCRIPTION
**Pull request by peterbarker**
Extracted from https://github.com/ArduPilot/ardupilot/pull/17209

The tests here are worth a separate PR, and the new function will be used soon-enough.

### CODE REVIEW

**Comment by peterbarker** [comment]
A commit message was also fixed.

**Comment by peterbarker** [comment]
Merging, thanks @Hs293Go 

(@lthall for visibility)

**Comment by Hs293Go** [comment]
Lol just realized I messed up the message. Thanks!!! I'm enormously grateful to lthall for essentially walking me through all of this. Will keep on trying to contribute!

**Comment by peterbarker** [comment]
On Mon, 19 Apr 2021, H S Helson Go wrote:

> Lol just realized I messed up the message. Thanks!!! I'm enormously grateful to lthall for essentially walking me through all of this. Will keep on trying to contribute!

If this is your area of interest, try looking for things tagged for 
Leonard in the issues list.

**Pull request merged**
