### PR TITLE
Global: Correct the tab code to spaces.

### PR DESCRIPTION
**Pull request by muramura**
1. The tab code is used.
2. At the end of the line there is space code, tab code.
Therefore,
1. Change tab code to spaces code.
2. Delete the last space code or tab code of the line.

### CODE REVIEW

**Comment by magicrub** [comment]
/w ?w=1 there are zero changes so that's good-ish. Also of note it's a 35k line change. You have a merge conflict but that is going to happen if there is *ANY* commit that gets in before this does because you're hanging almost every line.

**Comment by muramura** [comment]
@magicrub Comments Thanks.
I will fix the conflict.

**Comment by rmackay9** [comment]
My feeling is that we should haven't one single commit.. but rather many many smaller commits... one for each vehicle and each library.  so there might be 50 commits.
The problem with one big commit is it will make a wall in the code history and it will be very painful to merge things across the wall.

**Comment by rrr6399** [comment]
Given the potential for merge conflicts, is this really value added? Tabs are easier to work with anyway.

**Comment by muramura** [comment]
@rrr6399 Comment Thank you.
I understand.
The tab code changes with 2, 4, 8 ... ... column specification by editor.
If the tab code is 2 columns(ex. Ruby langage), you need 2 tab codes to make it 4 columns.
It is set to 4 spaces for indentation not dependent on the editor.

**Comment by magicrub** [comment]
I agree that the value-add for this PR is low - "the git wall" will be a pain to overcome. I vote to do this in baby steps over time.

**Comment by muramura** [comment]
@rmackay9 , magicrub Comments Thanks.
It divides it into AntennaTracker, APMrover2, ArduCopter, ArduPlane, libraries, tests, and Tools separately and PR.
Therefore,
This PR will be closed.

**Pull request closed without merging**
