### PR TITLE
AP_SerialManager: Add missing option for XRCE DDS

### PR DESCRIPTION
**Pull request by Ryanf55**
This was missing from the wiki:
https://ardupilot.org/copter/docs/parameters.html#serial1-protocol-telem1-protocol-selection

### CODE REVIEW

**Comment by amilcarlucas** [comment]
This needs to ba added to ALL SERIALx_PROTOCOL, not just 1

**Comment by Ryanf55** [comment]
> This needs to ba added to ALL SERIALx_PROTOCOL, not just 1

The others inherit the docs. It's not necessary.

**Comment by rmackay9** [comment]
@Ryanf55 you're happy with me merging this now?  I see it has the 4.5 label on it.. I'm not actually sure what we use that for because everything going into master will end up in 4.5.

**Comment by Ryanf55** [comment]
> @Ryanf55 you're happy with me merging this now? I see it has the 4.5 label on it.. I'm not actually sure what we use that for because everything going into master will end up in 4.5.

Yep, please do! 

I put the 4.5 label on things I would love merged in time for 4.5, including some issues that are priority to be resolved by next release.

**Pull request merged**
