### PR TITLE
Copter: Add smart rtl or land to the fence action

### PR DESCRIPTION
**Pull request by muramura**
The copter's fence action 3 will try to return with RTL if it has a missing Smart RTL record.
However, in this case, it will go straight back, which defeats the purpose of choosing Smart RTL.
What seems to be missing in this action is, if the smart RTL is missing a record, it will transition to LAND.

### CODE REVIEW

**Comment by rmackay9** [comment]
Looking good, could you make the define, "AC_FENCE_ACTION_SMART_RTL_OR_LAND"?

**Comment by muramura** [comment]
@rmackay9 san. Testing in SITL.

**Review by peterbarker — APPROVED** [review]
We could potentially rename `AC_FENCE_ACTION_SMART_RTL` to `AC_FENCE_ACTION_SMART_RTL_OR_RTL_OR_LAND` - it was presumably the original and we've gotten rather more nuanced.

But LGTM.

@muramura your testing is complete on this PR?

**Comment by rmackay9** [comment]
I think "Testing in SITL" probably meant "Tested in SITL" so merged!

**Pull request merged**
