### PR TITLE
Plane: correct bug that prevents QACRO rudder disarm

### PR DESCRIPTION
**Pull request by Hwurzburg**

### CODE REVIEW

**Comment by Hwurzburg** [comment]
tested in SITL...verified that it does not impact AIRMODE options and that they still work for QACRO

**Comment by kd0aij** [comment]
This would allow disarming in-flight with full left rudder and zero throttle if airmode is off.
I believe the original idea (probably undocumented) was that rudder disarm is unsafe in any acro mode.
Since we now have AIRMODE, perhaps it makes sense to allow rudder disarming in this case, but I have always switched to QSTABILIZE prior to disarming, (not to mention usually landing in QSTAB anyway).

**Comment by kd0aij** [comment]
Also, is seems that is_vtol_man_mode is poorly named, perhaps it should be something like "enable_rudder_disarm" ???

**Comment by Hwurzburg** [comment]
Actually, the is_flying check prevents the disarm in all modes while flying...I cant disarm in QACRO while flying with or without this change

**Comment by kd0aij** [comment]
Is that the check for isFlyingProbability >= 0.1f ? I was assuming we didn't want to trust that one, but I'll defer to you, Pete H. and Tridge on that one. Perhaps airmode should default to ON for QACRO mode?

**Comment by IamPete1** [comment]
I dont use Qacro, but i think we should do whatever copter does since that is what users will expect.

I guess you could argue that planes can glide in Qacro and so 0 throttle is more valid than it might be on copter.

**Comment by Hwurzburg** [comment]
Copter disarms with rudder in all non-auto modes: acro,stab,loiter,poshold,althold,etc.

**Comment by peterbarker** [comment]
Why isn't the check against manual-throttle rather than manual-mode?

**Comment by kd0aij** [comment]
Somewhat confusing:
is_vtol_man_mode is true for modes qstabilize, qacro, qhover, qloiter and qautotune
is_vtol_man_throttle is true for modes qstabilize and qacro

is_vtol_man_mode is used only in is_flying_vtol()

is_vtol_man_throttle is used there and also in
get_pilot_input_yaw_rate_cds() and 
get_desired_yaw_rate_cds() and 
update_throttle_suppression() and 
update_throttle_mix()

**Comment by Hwurzburg** [comment]
apparently, the difference is vtol_man_throttle is for modes the pilot directly controls the throttle..
whereas, vtol_man_mode is not a mode that AP controls the position independently of the pilot, like QRTL and QLAND (although I think you can push the vehicle around in the final stage of QLAND)
anyway subject of another discussion perhaps...
based on Tridge's, Marks', and Pete's comments, I think this can be merged now

**Pull request merged**
