### PR TITLE
quieten vagrant/virtualbox window

### PR DESCRIPTION
**Pull request by drnic**
see https://discuss.ardupilot.org/t/tutorial-for-running-sitl-simulator-on-macos-with-vagrant-xquartz/38383/11\?u\=drnic

/cc @peterbarker

### CODE REVIEW

**Comment by peterbarker** [comment]
@davidbuzz We didn't ever doing anything `vb.gui` - should we leave it in there as aspirational?

**Comment by drnic** [comment]
If it helps, it is still aspirationally at the top of Vagrantfile (commented out) https://github.com/ArduPilot/ardupilot/blob/13608474dd99822ff98a41a556cb4161444e5544/Vagrantfile#L26-L27

**Comment by peterbarker** [comment]
@drnic The commit message needs help; the subsystem should be included in the message (vehicle or library).  Vagrant is a bit tricky; perhaps, "Vagrant: quieten vagrant/virtualbox window"?

I think we might pull this in.  Hopefully at some stage I (or someone else) will come back and put in full desktop variants of these; as mentioned somewhere else I couldn't get auto-login functionality to work for that, pretty much a prereq.

**Comment by peterbarker** [comment]
I've fixed the commit message and pushed this in.

**Comment by peterbarker** [comment]
thanks!

**Pull request closed without merging**
