### PR TITLE
HAL_ChibiOS: fixed build with alarm and no PWM channels

### PR DESCRIPTION
**Pull request by tridge**
this fixes a build error due to conditional always being false when
NUM_GROUPS==0 by using a C++ iterator. It also makes the code neater

### CODE REVIEW

**Comment by ukmook** [comment]
Tested this pr on a node with alarm but no other pwm pin, gps (m8q), baro, mag and ncp5623 are all working perfectly.

**Comment by magicrub** [comment]
I've used this method in C# and java a lot, I didn't know C++ had this!

**Review by magicrub — APPROVED** [review]
approved pending test on targets WITH and WITHOUT pwms

**Comment by tridge** [comment]
> I've used this method in C# and java a lot, I didn't know C++ had this!

we use it in a few places in ArduPilot. I rarely use it mostly because of my habits as a C coder. In this case it works around the annoyance that the compiler doesn't like an index loop with a upper limit of zero due to NUM_GROUPS being zero.
I think we should start using this loop pattern more in ArduPilot. It is actually very readable.

**Comment by ukmook** [comment]
> approved pending test on targets WITH and WITHOUT pwms

Have tested with Pixracer-periph and Neopixels are working.

**Pull request merged**
