### PR TITLE
AP_GPS: add AP_GPS_FEMTO driver for Femtomes GPS

### PR DESCRIPTION
**Pull request by Femtomes**
1.Add AP_GPS_FEMTO driver for Femtomes gps device
2.Add femtomes driver in AP_GPS class

### CODE REVIEW

**Comment by amilcarlucas** [comment]
I advise you to squash all commits together into a single commit, and after that use ./Tools/gittools/git-subsystems-split script to break your commits down according to ardupilot code guidelines

**Comment by Femtomes** [comment]
> I advise you to squash all commits together into a single commit, and after that use ./Tools/gittools/git-subsystems-split script to break your commits down according to ardupilot code guidelines

What should I do after run ./Tools/gittools/git-subsystems-split script ?

**Comment by amilcarlucas** [comment]
git push -f

**Comment by Femtomes** [comment]
> git push -f

Thanks!

**Comment by amilcarlucas** [comment]
You do not need to close this. just
git push -f

**Pull request closed without merging**
