### PR TITLE
Copter: Introduce WP_YAW_DEADBAND parameter

### PR DESCRIPTION
**Pull request by amilcarlucas**

### CODE REVIEW

**Comment by rmackay9** [comment]
I'm really not sure about this change.  If the nose of the copter is wagging or something then it's more likely a tuning issue.  This deadband will lead to slightly odd behaviour in that the vehicle will likely make little steps.  I.e. turn 10deg, then not turn for a while, then turn another.  I'm really not sure that's good behaviour.

**Comment by amilcarlucas** [comment]
@rmackay9 The original code has an hardcoded 200 cdeg. On my tests, the copter pointed at ROI with an error of no less than 2 deg. By changing this parameter I got that error reduced. However it seams to only be reduceable down to 1,4 °, Hence WIP.... I need to find what else can I do to further reduce this yaw error down.

**Comment by amilcarlucas** [comment]
I will rebase this once the YAW cleanup PR from Peter gets merged.

**Comment by OXINARF** [comment]
@amilcarlucas Rebase?

**Comment by amilcarlucas** [comment]
No, need for a rebase, there were no conflicts. But I did rebased it now anyways.

It is still WIP because this only improves the problem slightly. It needs more work in order to fully fix the issue :(
Increasing  WPNAV_ACCEL seams to help... but it needs more tests.

**Comment by khancyr** [comment]
@amilcarlucas do you still need to continue this work ? I never encounter this kind of yaw issue, so I don't know if it is worth continuing this ?

**Comment by rmackay9** [comment]
I think I will close this because it shouldn't actually affect the accuracy of the yaw.  What this will change is the moment at which the condition-yaw command will complete and move onto the next do command.  The target remains exactly what the mission command requested and the vehicle will attempt to hold that exact target.

**Pull request closed without merging**
