### PR TITLE
adding turbulance to SITL

### PR DESCRIPTION
**Pull request by orig74**
I have added support for turbulence in SITL the effect can observe in this Demonstration video:
https://youtu.be/IjzDwZ5OKxU

### CODE REVIEW

**Comment by magicrub** [comment]
I thought we had this already? I'll check when I get back to my computer. Meanwhile, this PR needs work because there's no way to disable it. There's always turbulence no matter what and that's not good for a sim. Needs a parameter.

**Comment by orig74** [comment]
Hi,
if the Turbulence variable SIM_WIND_TURB is equal to zero It has no effect,
since the speed of the turbulence is 0.
The video I've uploaded shows the effect of turbulence in the SITL with
SIM_WIND_TURB=5.0
https://youtu.be/IjzDwZ5OKxU

**Comment by magicrub** [comment]
problems:
- Turbulence would be higher than normal when using JSBsim... unless update_wind() doesn't get called when JSBsim is running?
- the extra "+= cosf(radians(.." call is inefficient, simply adding to the existing "wind_ef = " line is better.
- doing all that work when _speed == 0 is silly. Might as well check for that before going though all that work

**Comment by orig74** [comment]
Hi, 
I have changed the code a bit.
1. JSBsim: update_wind() is not called when JSBsim running (I double checked the function update in SIM_JSBSim.cpp).
2,3. Now I am doing all the work only when   input.wind.turbulence>0

**Comment by tridge** [comment]
wow, you have it running with unreal engine? how do I try that?

**Comment by orig74** [comment]
Hi,
fist I've created a plug-in for UE4 https://github.com/orig74/UE4PyServer
second created this project  https://github.com/orig74/DroneLab
I tried to document everything in the README.md file in both projects.
If anything is missing or not working, please let me know.

**Comment by orig74** [comment]
regarding points 1,2,3 I think I can do something about them with small modifications to the code.
Regarding Dryden / MIL-STD-1797A I will look into that.

**Comment by orig74** [comment]
Updated version. 
- I added IIR filter to reduce high frequencies.
- disabled turbulence when on the ground
- Regarding scaling the turbulence, I think we should let the user decide and not hide the fact that the turbulence parameter (SIM_WIND_TURB) is dependent on  SIM_WIND_SPD, but I am not sure. For me, it's more clear that way. I left the other option (line 514)  remarked. 
- still looking into JSBsim,  but for now, I think that this is a simple solution that for me and hopefully for others is very useful to imitate quad dynamics.

This is a Test with SIM_WIND_TURB=5 and SIM_WIND_SPD=5
https://youtu.be/AkJraybF6HA

**Comment by orig74** [comment]
Some Testing:
Take-off to 20 meters in LOITER mode and land.
Doing it four times with different turbulence parameter:
SIM_WIND_SPD=5  SIM_WIND_TURB=0,5,10,15
links for images:
[full test](https://github.com/orig74/tmp/blob/master/turb_test.png?raw=true)
[zoom-in](https://github.com/orig74/tmp/blob/master/turb_test_zoom.png?raw=true)

**Comment by magicrub** [comment]
Thank you! There are some minor white space changes needed but I can handle that for you afterward. Please take a look at the guidelines when you have a chance.

**Comment by priseborough** [comment]
This will give misleading results. The user should be warned that this model does not follow any aerospace standard.

**Comment by magicrub** [comment]
As far as i can see, the jsbsim turbulence model is here https://github.com/tridge/jsbsim/tree/master/src/models/atmosphere but it is extremely complex.

I believe that what we have here is certainly better than not having one at all.

**Comment by magicrub** [comment]
whitespace change is here: https://github.com/ArduPilot/ardupilot/commit/11229d258825279af5096958f8c3a78185ed022d

**Comment by priseborough** [comment]
If it is being used to make the visuals look more realistic, then yes I agree. However it should not be used to for control loop tuning on fixed wing.

**Comment by magicrub** [comment]
well, lets hope no one does that on a non-JSBsim SITL any time soon.

**Pull request merged**
