### PR TITLE
AP_Param: disable debug

### PR DESCRIPTION
**Pull request by khancyr**
Pretty sure we don't want that

### CODE REVIEW

**Comment by OXINARF** [comment]
What do you mean infinite loop?

**Comment by khancyr** [comment]
oups it is while(0) not while(1)

**Comment by OXINARF** [comment]
Ok, so no infinite loop. But it may be worthwhile to have it disabled anyway. I'll ask in dev call today.

**Comment by khancyr** [comment]
in fact it make the rover code crash in this PR : https://github.com/ArduPilot/ardupilot/pull/5455 . There must be another error in param or rover code. But I didn't find it...

**Comment by rmackay9** [comment]
@khancyr, thanks for finding this!  If it helps me get my PR in, I'm super happy :-).

**Comment by OXINARF** [comment]
@khancyr We discussed it in the dev call and it is useful for doing development so I'm closing this as we want to leave it enabled by default.

**Comment by khancyr** [comment]
Ok then I will try to look why it may rover crash ! (and maybe other vehicle)

**Pull request closed without merging**
