### PR TITLE
GPS: add enum GPS_AUTO_SWITCH=4 choose WORST receiver

### PR DESCRIPTION
**Pull request by magicrub**
add enum GPS_AUTO_SWITCH=4 choose WORST receiver. That includes status=0.

This is useful when you want to be able "disable" the gps in-flight and feed that inferior, or absent, value into the system but still want to log true gps values for later analysis. Helpful to show behavior of actual aircraft gps loss during flight and easier to see improvements when adding additional sensors like airspeed, flow and SLAM.

This should give a similar effect as SIM_GPS_DISABLE but with the added benefit that it will also work on real vehicles. To test in SITL:

SIM_GPS2_ENABLE 1
GPS_TYPE2 1
AUTO_SWITCH 4

(arm, takeoff, fly around)

SIM_GPS2_ENABLE 0

(things go nuts)

SIM_GPS2_ENABLE 1

(aircraft resumes whatever it was doing)

### CODE REVIEW

**Comment by magicrub** [comment]
added DevCallTopic per request by @WickedShell

**Comment by khancyr** [comment]
I am not opposed to this, but wouldn't it be simplier to use the disabling gps feature that is on switch to do test ?

**Comment by magicrub** [comment]
@khancyr the problem is the gps data stops and is not able to be logged. The major problem is simply saying "disabled" doesn't effect the other zillion modules that pull from the gps singleton directly.

**Comment by rmackay9** [comment]
It seems like this might be just a one-time developer style option.  I'm not sure we really need this long term in master.

**Comment by magicrub** [comment]
@rmackay9 I'm happy to make it a stand-alone param. If I did that I'd like to make it a counter that decrements down to zero and then turns the GPS back on.

**Comment by magicrub** [comment]
Closing, the same can be accomplished by using AUTO_SWITCH = 3 (use Second). Also, the inspiration for this was that many places in the code we aren't checking gps.status before using the data from it. I have created an issue to track that

https://github.com/ArduPilot/ardupilot/issues/14213

**Pull request closed without merging**
