### PR TITLE
Plane: tail sitter pull Q mode control outputs from copter

### PR DESCRIPTION
**Pull request by IamPete1**
This changes tailsitter to pull control surface outputs from AP_Motors, this tidy's AP_Motors_tailsitter and allows tailsitters to support any motors backend without modification.

### CODE REVIEW

**Comment by IamPete1** [comment]
@kd0aij I think this is a neater again way of allowing 'copter' tail sitters. Now tail sitters should be able to use any motor matrix back-end without modification. So we get them all for free in addition to any custom quad motor tail sitter back-ends we add.

**Comment by kd0aij** [comment]
AP_MotorsTailsitter would need to inherit from MotorsMatrix too, wouldn't it?
That's where I was going with https://github.com/kd0aij/ardupilot/pull/4
but I think instead of a subclass per frame AP_MotorsMatrixTS could implement (a subset of) existing frame_classes/types. I'd leave AP_MotorsTailsitter alone to avoid breaking things like the AddictionX.

**Comment by IamPete1** [comment]
we would still need the tilt mask stuff to get copter tailsitters. But this should allow them without any modification to any motors back ends. Although as you say we can probably get improvements with custom stuff.  This should be no functional change as it is, haven't tested AddictionX but work fine with my tvbs.

**Comment by kd0aij** [comment]
OK, I thought this was to make AP_MotorsTailsitter support copter tailsitters. We should probably clarify that it supports only single and twin engine configurations and that AP_MotorsMatrix handles the others.

**Comment by kd0aij** [comment]
BTW: I had made a similar change to tailsitter.cpp in https://github.com/ArduPilot/ardupilot/pull/10324

**Comment by IamPete1** [comment]
Ah, I completely missed that you had done it there, great minds think alike , I think it makes sense to move to that method for the tail sitters mixer too, does a better job of separating copter and plane as the tail sitter mixer is now also used by bi-copters

**Comment by rmackay9** [comment]
This looks good to me.. are @IamPete1 and @kd0aij happy with this change?

**Comment by tridge** [comment]
thanks Pete!

**Pull request merged**
