### PR TITLE
Tools: align ci gcc with environment gcc on arm

### PR DESCRIPTION
**Pull request by andyp1per**
Saves 8k on plane, 9.3k on copter

### CODE REVIEW

**Comment by andyp1per** [comment]
Before:
```
BUILD SUMMARY
Build directory: /home/runner/ardupilot/build/MatekF405-Wing
Target                       Text    Data  BSS     Total  
----------------------------------------------------------
bin/ardurover                860016  1268  129872   991156
bin/antennatracker           685412  1256  129892   816560
bin/arducopter               978652  1276  129876  1109804
bin/arducopter-heli          964148  1276  129876  1095300
bin/arduplane                975652  1272  129876  1106800
bin/ardusub                  816860  1296  129852   948008
bin/ardurover                860016  1268  129872   991156
bin/antennatracker           685412  1256  129892   816560
bin/arducopter               978652  1276  129876  1109804
bin/arducopter-heli          964148  1276  129876  1095300
bin/arduplane                975652  1272  129876  1106800
bin/ardusub                  816860  1296  129852   948008
```
After:
```
BUILD SUMMARY
Build directory: /home/runner/ardupilot/build/MatekF405-Wing
Target                       Text    Data  BSS     Total  
----------------------------------------------------------
bin/ardurover                851636  1336  129812   982784
bin/antennatracker           676556  1324  129828   807708
bin/arducopter               969352  1344  129808  1100504
bin/arducopter-heli          954868  1344  129812  1086024
bin/arduplane                967580  1340  129812  1098732
bin/ardusub                  808168  1364  129784   939316
bin/ardurover                851636  1336  129812   982784
bin/antennatracker           676556  1324  129828   807708
bin/arducopter               969352  1344  129808  1100504
bin/arducopter-heli          954868  1344  129812  1086024
bin/arduplane                967580  1340  129812  1098732
bin/ardusub                  808168  1364  129784   939316
```
Saves 8k on plane, 9.3k on copter

**Comment by khancyr** [comment]
Interesting.
The build server should also be checked if we make gcc6 the new toolchain

**Comment by rmackay9** [comment]
@jaxxzer, merging this means that we can't do stable releases that rely on NuttX anymore because (our version of) NuttX doesn't build with version 6 of the compiler.

**Comment by jaxxzer** [comment]
Ok I think that will be fine. We are closing in on a 4.0, and I don't expect any more releases based on 3.5.

**Pull request merged**
