### PR TITLE
AP_Generator: apply -Os to all cpp files

### PR DESCRIPTION
**Pull request by peterbarker**
```
Board                    AP_Periph  blimp  bootloader  copter  heli  iofirmware  plane  rover  sub
CubeBlack                           -656   *           -664    -656              -664   -664   -656
CubeOrange-periph-heavy  *                                                                     
CubeOrangePlus                      -672   *           -664    -672              -672   -672   -664
CubeRedPrimary                      -32    *           -40     -40               -40    -40    -32
Durandal                            -664   *           -672    -664              -672   -672   -664
Hitec-Airspeed           *                                                                     
KakuteH7-bdshot                     -40    *           -32     -40               -40    -32    -32
MatekF405                           *      *           *       *                 *      *      *
Pixhawk1-1M-bdshot                  *                  *       *                 *      *      *
f103-QiotekPeriph        *                                                                     
f303-Universal           *                                                                     
iomcu                                                                *                         
revo-mini                           *      *           *       *                 *      *      *
skyviper-journey                                       -32                                     
skyviper-v2450                                         *                                       
111

### CODE REVIEW

**Comment by amilcarlucas** [comment]
Aren't all generators disabled on 1MB boards?
Also, this is just for 2MB boards, right?

Nice space saving!

**Comment by tpwrules** [comment]
I think we should pull the trigger on `-Os` to all 2MB boards. It's already enabled for all 1MB boards.

**Comment by andyp1per** [comment]
> I think we should pull the trigger on `-Os` to all 2MB boards. It's already enabled for all 1MB boards.

Nah, the performance boost is quite substantial - if we don't need to we shouldn't. There are many 2Mb boards that can easily accommodate -O2

**Comment by peterbarker** [comment]
> Aren't all generators disabled on 1MB boards? 

Yes.

> Also, this is just for 2MB boards, right?

No - this means that if you choose to enable a generator on a 1MB board locally or on custom.ardupilot.org the feature will come in -Os

> Nice space saving!

Considering it is essentially free, yes.  tridge pointed out we should be doing this in virtually every new .cpp file - the majority of code is not timing sensitive.

**Review by tridge — APPROVED** [review]

**Pull request merged**
