### PR TITLE
Copter: make fwver static

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by peterbarker** [comment]
To be clear, this is just here as a discussion point for #6883 ATM, but if this is the way to go I'm happy to do it for all vehicles.

**Comment by lucasdemarchi** [comment]
The entire object is static and has only ever one instance. There's no point in making a member of that object static, too... What you are doing here is exactly what I did on that PR minus the place where the object is initialized.

**Comment by peterbarker** [comment]
@lucasdemarchi Yes, but this is far less ugly IMNSHO :-)

AFAICS there's no reason for us to initialise this object in the header.

**Comment by OXINARF** [comment]
Although I understand @lucasdemarchi's point, I like this, for two reasons:

- I really like the separate version.cpp file to initialize the structure
- if one day we have a multi-vehicle binary, it's possible the vehicle object stops being static, but each vehicle version being static would still make sense

**Comment by lucasdemarchi** [comment]
> if one day we have a multi-vehicle binary, it's possible the vehicle object stops being static, but each vehicle version being static would still make sense

Then the whole struct shouldn't be inside the vehicle class. If that day arrives we should have a single object, which probably means moving it to libraries/ rather than being on the vehicle.

**Comment by OXINARF** [comment]
@lucasdemarchi It depends on how it is done. In my mind, each vehicle would continue to be independent and so have its own version.

**Comment by lucasdemarchi** [comment]
> @lucasdemarchi It depends on how it is done. In my mind, each vehicle would continue to be independent and so have its own version.

Then the vehicle will continue to be static so I don't get the point here.  And even if it isn't, this seems to be looking way ahead in a future that may not arrive. At the time it does we could revisit this and whatever else is needed.

**Comment by OXINARF** [comment]
@lucasdemarchi Yeah, let's not get into details here. My point was that having it static doesn't make any harm and from a logical perspective it even makes sense - if two objects of the same vehicle were created they would still have the same version, hence making it static.

**Comment by lucasdemarchi** [comment]
This has been done on #6883

**Pull request closed without merging**
