### PR TITLE
Update mavlink and pymavlink submodules upto 2019-02-25

### PR DESCRIPTION
**Pull request by amilcarlucas**
can go in after ardupilot/mavlink#90

### CODE REVIEW

**Comment by amilcarlucas** [comment]
Only one test Fails: Rover rally points.
Is this a quirck, or a real fail ?

**Comment by amilcarlucas** [comment]
Updated again with the latest pymavlink changes, let's see if the rover rally points test now pass.

**Comment by amilcarlucas** [comment]
All tests pass, this can be merged after ArduPilot/mavlink#90

**Comment by amilcarlucas** [comment]
The mavlink PR has gone in, this one can be merged now

**Comment by peterbarker** [comment]
Commit message needs help.

tradition seems to be: `mavlink: submodule update`

**Comment by amilcarlucas** [comment]
rebased and corrected the commit message

**Comment by amilcarlucas** [comment]
The appveyor test failed because it expired the 60 minutes build time.

**Comment by peterbarker** [comment]
On Wed, 13 Mar 2019, Amilcar Lucas wrote:

> The appveyor test failed because it expired the 60 minutes build time.

There's a lot of that going on.  I tend to ignore these failures...

Rebase and try again?  I want that message-request patch! :-)

**Comment by amilcarlucas** [comment]
@peterbarker All tests passed now  :)

**Comment by amilcarlucas** [comment]
@peterbarker this allows the that message-request patch! :-)

**Comment by peterbarker** [comment]
Merged, thanks!

**Pull request merged**
