### PR TITLE
 Copter: support changing vertical speed in DO_CHANGE_SPEED

### PR DESCRIPTION
**Pull request by chobitsfan**
for  #5618 

It allows users to change vertical speed in auto mission using DO_CHANGE_SPEED. set param1 to 2 for changing climb speed. set param1 to 3 for changing descent speed.

Tested on both SITL and my quadcopter (pixhawk 2 on dji f450 frame)

According to [doc](http://ardupilot.org/copter/docs/common-mavlink-mission-command-messages-mav_cmd.html#mav-cmd-do-change-speed). param1 means speed type (0=Airspeed, 1=Ground Speed)

### CODE REVIEW

**Comment by khancyr** [comment]
Hello, 
This will need a change in mavlink!

**Comment by chobitsfan** [comment]
hi @khancyr Maybe change description of param 1 is enough? I test this PR with current version of mavproxy and mission planner, it works fine

**Comment by amilcarlucas** [comment]
This requires a mavlink change, and to be on the safe side the introduction of an enum, and that enum should be used here.

**Comment by rmackay9** [comment]
I love this change!  I agree with @khancyr and @amilcarlucas that we should update mavlink so that this appears in the official documents.  Still, I'm going to pull this in as-is if it passes travis because we often get into this little chicken-vs-egg issue with the mavlink changes.

**Comment by rmackay9** [comment]
Merged, thanks!  I'll leave it to @chobitsfan to hopefully make the follow-up mavlink changes.  @chobitsfan if you have troubles making the mavlink changes one of us (i.e. me) can help you or just do the change for you.

**Comment by chobitsfan** [comment]
Thank you @rmackay9 
I have create https://github.com/mavlink/mavlink/pull/1003

Hi @amilcarlucas thank you for commenting. Because it already states (0=Airspeed, 1=Ground Speed) in DO_CHANGE_SPEED, maybe we just add more type following current description? The changes would be  minimum.

**Pull request merged**
