### PR TITLE
Global: To nullptr from NULL.

### PR DESCRIPTION
**Pull request by muramura**
C++11 is to provide a nullptr for NULL pointer.
Therefore,
To change to nullptr.

### CODE REVIEW

**Comment by magicrub** [comment]
This pr is a good idea but must be looked at carefully

**Comment by muramura** [comment]
@OXINARF , @magicrub Comments Thank you.
I understand.
Extension C is NULL.
Below, to modify the 3 files.

1. libraries/AP_Param/tools/eedump.c
2. libraries/AP_Param/tools/eedump_apparam.c
3. Tools/ArduPPM/ATMega32U2/Bootloaders/arduino-usbdfu/Descriptors.c

**Comment by lucasdemarchi** [comment]
Reviewed with:

```
git show -U0 --color-words
```

Apparently everything is correct now. Applied, thanks. I also squashed the 2 commits since they are doing the same thing.

**Comment by muramura** [comment]
@lucasdemarchi Thanks.
Thank you for checking the very, very many files.
Applied Thank you.

**Pull request closed without merging**
