### PR TITLE
Fix Plane Forward Throttle Battery Voltage Scaling

### PR DESCRIPTION
**Pull request by priseborough**
Scaling as implemented previously does not adjust upper and lower throttle limits. This has the undesired effect that as battery voltage drops off towards end of discharge, the maximum climb performance continues to reduce which is unsafe when flying without an airspeed sensor.

Consistent climb and reverse thrust descent operation without an airspeed sensor requires that 

THR_MAX <= FWD_THR_BATT_VOLT_MIN / FWD_THR_BATT_VOLT_MAX 

and 

THR_MAX >= -FWD_THR_BATT_VOLT_MIN / FWD_THR_BATT_VOLT_MAX

There has been limited SITL testing with 

ARSPD_USE = 0
THR_MAX = 70
FWD_THR_BATT_VOLT_MAX = 12.6
FWD_THR_BATT_VOLT_MIN = 9.9

I will be testing this on a Strix Nano Goblin with Matek F765 Wing board.

### CODE REVIEW

**Comment by IamPete1** [comment]
This is my understanding of the patch. Currently THR_MIN and MAX are based on the unscaled throttle, this apply the scaling to MIN and MAX also. I think this makes sense. Without this you could have set THR_MAX to cruse throttle + a little bit thus negating the scaling. Of course if your THR_MAX was already 100 this makes no difference. The new advice suggest setting throttle max such that it would be 100 (or less) at min voltage, this would constrains you to the low battery performance at all times. I guess if you want a completely consistent vehicle independent of voltage that is a good idea.

**Comment by priseborough** [comment]
Here is the battery voltage and EKF estimated airspeed from the Nano Goblin flying without an airspeed sensor in CRUISE mode using these parameters

THR_MAX = 72
TECS_RLL2THR = 3
TRIM_THROTTLE = 45
FWD_BAT_VOLT_MAX = 8.3
FWD_BAT_VOLT_MIN = 6.0

Screen Shot 2020-06-13 at 7 59 22 pm

Airspeed remain relatively constant throughout the CRUISE flight segment despite falling voltage.

Another flight with TRIM_THROTTLE = 55 and a larger value of TECS_RLL2THR = 10 to push the throttle into clipping shows the expected effect of the rising throttle limit with falling voltage.

Screen Shot 2020-06-13 at 8 09 38 pm

**Comment by CraigElder** [comment]
@Hwurzburg

**Comment by FPVREVIEWS** [comment]
This have any relation to an issue I'm having getting BAD BATTERY warning in RED on HUD in Mission Planner? 
I understand the code calculates internal resistance of the battery and is generating a warning. I see no parameters to disable it, as I am using LION batteries, and it's normal for there to be voltage sag..    Found a Mavlink parameter called MAV_BATTERY_TYPE , but am unfamiliar with how to edit mavlink parameters in Mission planner..  Is it via Terminal?  or is there another way?  I'm sure lots of users will be having this issue towards end of flight now, as the warning did not seem to exist in previous versions of mission planner. 
Any help is appreciated.  Thanks, and sorry for my ignorance in advance.    Thanks!

**Comment by IamPete1** [comment]
@FPVREVIEWS  your issue is unrelated, please post a log on the support forum https://discuss.ardupilot.org/

**Pull request merged**
