### PR TITLE
Fixed blheli passthru on H7 boards

### PR DESCRIPTION
**Pull request by tridge**
This improves the matching of pulse rates for DShot, NeoPixel and for blheli pass-thru
ping @IamPete1 
marked WIP. Even if this passes testing I would like to look at this some more before merging.

### CODE REVIEW

**Comment by IamPete1** [comment]
This fixes it for me, tried internal test and BLHeli suite on AUX 1, both working, thanks

**Comment by rmackay9** [comment]
By the way, we have a new report that the BLHeli pass through is also not working on a PixhawkMini: https://discuss.ardupilot.org/t/orange-cube-4-0-and-blh-passthrough/51296/26.  It may be unrelated of course, users seem to struggle with the setup.

**Comment by tridge** [comment]
I've done more testing and I'm happy with this now

**Comment by davidbitton** [comment]
@tridge @rmackay9 This is currently an issue with my Matek H743-SLIM. I'm running master. To confirm hardware, I loaded Betaflight on to the board, and was able to successfully make use of BLHeli Suite to flash firmware and update settings. Back in ArduCopter, BLHeli Suite connects, but not ESC configs.

**Comment by rmackay9** [comment]
@davidbitton,

I'm not a big user of BLHeli so I'd better leave feedback to the likes of Tridge and @andyp1per.

**Comment by andyp1per** [comment]
@davidbitton can you post your params?

**Comment by davidbitton** [comment]
@andyp1per here:

https://drive.google.com/file/d/1vok5EVsVCUlNv4OZKnHZrbIC59s-pkO7/view?usp=sharing

**Pull request merged**
