### PR TITLE
Cubes Define EKx_IMU_MASK and Change INS_USE check to apply for all Cubes

### PR DESCRIPTION
**Pull request by hendjoshsr71**
This PR sets the default `EKF_IMU_MASK` to use all three IMUs and changes the `INS_USEx` check to apply to all cubes.  This was discussed on discord with @proficnc. [Here](https://discord.com/channels/674039678562861068/780728024756781056/914278885804355625)
It also sets the `INS_USE` check that was for only cubeblack to be for all cubes.

Should this be set as the default via the hwdef? 
"The answer from Cubepilot is ABSOLUTELY YES!  But the pull request for this was rejected."

I couldn't find the PR discussed. 

My one thought is  that enabling this for F4s in this manner  might cause a bunch of support issues on updating. The user would need to go in and switch back to `EK3_IMU_MASK 3` on an update if there resources are constrained.

### CODE REVIEW

**Comment by IamPete1** [comment]
I don't think this is a good idea for CubeBlack's there quite CPU/memory limited on 4.1, I have seen scheduler overruns with defaults on copter if you turn on harmonic notches.

**Comment by hendjoshsr71** [comment]
Ok. I've removed the IMU_MASK default for Black, Purple, and Solo since they have the same limitations.

I left it in for Yellow though?

Testing:  I did desktop test on my orange going from Copter Stable to this PR from IMU_MASK 3.  And it came up after update correctly and with reasonable data for EKF[0-2] logs.

I also tried setting `INS_USE3 0` and comes back up on reboot to `INS_USE3 1`

**Review by tridge — APPROVED** [review]

**Comment by proficnc** [comment]
This is absolutely critical for cube black. I'd rather see other features taken out than people flying without using this as advised on our Service Bulletin.

**Comment by hendjoshsr71** [comment]
> This is absolutely critical for cube black. I'd rather see other features taken out than people flying without using this as advised on our Service Bulletin.

@IamPete1 @andyp1per Thoughts on the above? 

IMU_MASK 7: Users who are already resource constrained will need to go in and change this back. But will do so after being very unhappy and confused. It would need another campaign to let users know. (Yes, they should be doing so but .... safety vs use is up to the user)

An option could be defaulting to using say `IMU_MASK` 5 or 6 be to provide for some safety for the case where the vibe isolated IMUs fail.  This would not take additional computational resources? But this then compromises the EKF solution for one lane somewhat?

**Pull request merged**
