### PR TITLE
Remove class specifier prefixing Location in function declarations

### PR DESCRIPTION
**Pull request by srmainwaring**
Remove  occurrences of `class` prefixing `Location` in function declarations:

- See comment in: https://github.com/ArduPilot/ardupilot/pull/26328#discussion_r1522653270

### CODE REVIEW

**Comment by rmackay9** [comment]
I'm happy with this but 3 of the 4 commits are outside my area so I've marked for next week's dev call.  I suspect @peterbarker knows well if there's any difference in having the "class" in the front or not.

**Comment by nexton-winjeel** [comment]
> if there's any difference in having the "class" in the front or not.

AFAIK having the `class` there makes it a forward declaration.

**Review by peterbarker — CHANGES_REQUESTED** [review]
These header files are not including `AP_Common/Location.h`

That means they know this thing is a class only because they're getting that information transitively, and that's bad.

We do not want to include `Location.h` if we don't need to as it just slows things down unnecessarily.

I don't think this PR is a good idea.

Stripping them out where not required in e.g. .cpp files is a good idea, but not in headers if we then need to get the `class` aspect from elsewhere

**Comment by rmackay9** [comment]
OK, thanks very much for the education on this issue!  Sorry @srmainwaring for the extra work but we all learned something perhaps :-)

**Comment by srmainwaring** [comment]
> Stripping them out where not required in e.g. .cpp files is a good idea, but not in headers if we then need to get the `class` aspect from elsewhere

How about we forward declare `class Location` at the top of the file after the include directives rather than inline in function declarations? That makes the intent clearer. This started out as a request to clean up a function declaration in a different PR, so there is some confusion.

The code base does not seem to generally apply forward declaration rules for compilation efficiency (as per J. Lakos, Large-scale C++ Software Design). Is that something we'd want to move to (or is that largely outdated now with the current round of compilers)?

**Pull request closed without merging**
