### PR TITLE
Allow for much larger compass offsets in calibrator

### PR DESCRIPTION
**Pull request by tridge**
This fixes two problems with the compass calibrator on airframes with large offsets.
The first is that the integer scaling to int16_t could overflow with some samples. The scaling factor has been reduced by 2x to fix that issue.
The second is that the fitting algorithm could fail with large offsets. To fix that the average sample in the first sphere fit is subtracted from the samples.
This fixes compass cal on the Disco with its hatch magnet

### CODE REVIEW

**Comment by jschall** [comment]
Please test https://github.com/jschall/ardupilot/commits/compass-calibrator-large-offset-fix

**Comment by jschall** [comment]
Can I use more memory for the sample buffer and just use floats?

**Comment by tridge** [comment]
@jschall thanks Jon!
I tried your branch and it fails for the disco (and SITL) because of the offset limits in fit_acceptable(). If those limits are raised then it works. I've pushed an update for this PR that uses your changes but uses a board specific offset limit.
btw, you can test the calibrator in SITL by using "--model calibration"  and then "servo set 5 1250". That starts the model doing the compass dance. You can set SITL mag offsets with SIM_MAG_OFS_{X,Y,Z}

**Comment by tridge** [comment]
applied with Jons changes

**Pull request closed without merging**
