### PR TITLE
HAL_ChibiOS: enable heater on Pix32v5

### PR DESCRIPTION
**Pull request by tridge**
tested and working
mag interference is 20 mGauss on X axis, so not very strong

### CODE REVIEW

**Comment by rmackay9** [comment]
OK, the parameter default for BRD_IMU_TARGTEMP doesn't seem to be correct.  For me at least it is appearing as 0 for both CubeBlack and CubeOrange on both Copter-4.0.7 and latest and this PR.  So this is probably an existing issue but I bumped into it while testing this PR.

**Comment by rmackay9** [comment]
Another issue I noticed was setting the BRD_IMU_TARGTEMP to -1 turned on the heater permanently (it seemed) as the temp kept climbing.  Setting the temp to zero caused the temp to start falling but the param descriptions say -1 is a valid value for the parameter.

**Comment by tridge** [comment]
> OK, the parameter default for BRD_IMU_TARGTEMP doesn't seem to be correct. For me at least it is appearing as 0 for both CubeBlack and CubeOrange on both Copter-4.0.7 and latest and this PR.

please check again. I just loaded this PR on an orange and set FORMAT_VERSION to 0 to reset params, then I rebooted and fetched params. The value is 45.

**Comment by tridge** [comment]
> Another issue I noticed was setting the BRD_IMU_TARGTEMP to -1 turned on the heater permanently (it seemed) as the temp kept climbing.

again, I can't reproduce on an orange. Setting to -1 turns off the heater for me

**Comment by tridge** [comment]
i've checked both on CubeBlack too. Behaviour is correct. Default is 45 and -1 disables heater

**Comment by rmackay9** [comment]
ok, I've retested and the defaulting seems ok on the cubes.  I couldn't re-test the defaulting on the Pix32v5 because that would lead to a bunch of re-calibration or extra work to avoid the re-calibration and I think Tridge's re-test is sufficient.

We've discussed a possible (existing) issue in that if a user sets the BRD_IMU_TARGTEMP to -1 it may (or may not) leave the pin on which could cook the board.  As a minimum we should add a warning to the param docs that if users set the value to -1 they should reboot the autopilot.

**Review by rmackay9 — APPROVED** [review]
I'm not an expert in this area but I've tested and it seems ok, thanks!

**Pull request merged**
