### PR TITLE
Copter: Add a "RC not found" message

### PR DESCRIPTION
**Pull request by muramura**
I have tested the radio receiver not connecting to FC.
The "Throttle below failsafe" message is incorrect.
I added the message "Radio signal not received".

AFTER
Screenshot from 2022-08-27 16-57-59

BEFORE
Screenshot from 2022-08-27 16-30-05

### CODE REVIEW

**Comment by Hwurzburg** [comment]
will need this fixed to pass CI: https://github.com/ArduPilot/ardupilot/blob/5fd98918803ce028b5d7d200124155593d2c7188/Tools/autotest/arducopter.py#L8693

**Comment by Hwurzburg** [comment]
btw,I dont get that message....clean install of Stable on CubeOrange, no rc:
8/27/2022 8:09:43 AM : PreArm: Compass not calibrated
8/27/2022 8:09:43 AM : PreArm: 3D Accel calibration needed
8/27/2022 8:09:43 AM : PreArm: Hardware safety switch
8/27/2022 8:09:31 AM : EKF3 IMU0 MAG0 initial yaw alignment complete
8/27/2022 8:09:31 AM : EKF3 IMU1 MAG0 initial yaw alignment complete
8/27/2022 8:09:31 AM : EKF3 IMU2 MAG0 initial yaw alignment complete
8/27/2022 8:09:31 AM : EKF3 IMU2 tilt alignment complete
8/27/2022 8:09:31 AM : EKF3 IMU0 tilt alignment complete
8/27/2022 8:09:31 AM : EKF3 IMU1 tilt alignment complete
8/27/2022 8:09:30 AM : AHRS: EKF3 active
8/27/2022 8:09:30 AM : EKF3 IMU2 initialised
8/27/2022 8:09:30 AM : EKF3 IMU1 initialised
8/27/2022 8:09:30 AM : EKF3 IMU0 initialised
8/27/2022 8:09:28 AM : RCOut: PWM:1-14
8/27/2022 8:09:28 AM : AHRS: DCM active
8/27/2022 8:09:28 AM : ArduPilot Ready
8/27/2022 8:09:27 AM : Initialising ArduPilot
8/27/2022 8:09:27 AM : Barometer 2 calibration complete
8/27/2022 8:09:27 AM : Barometer 1 calibration complete
8/27/2022 8:09:27 AM : Frame: QUAD/X
8/27/2022 8:09:27 AM : RCOut: Initialising
8/27/2022 8:09:27 AM : CubeOrange 001C002E 3131510E 31363832
8/27/2022 8:09:27 AM : ChibiOS: 93e6e03d
8/27/2022 8:09:27 AM : ArduCopter V4.2.2 (4fcfa4b2)
8/27/2022 8:09:27 AM : Frame: QUAD/X
8/27/2022 8:09:27 AM : RCOut: Initialising
8/27/2022 8:09:27 AM : CubeOrange 001C002E 3131510E 31363832
8/27/2022 8:09:27 AM : ChibiOS: 93e6e03d
8/27/2022 8:09:27 AM : ArduCopter V4.2.2 (4fcfa4b2)
8/27/2022 8:09:26 AM : Frame: QUAD/X
8/27/2022 8:09:26 AM : RCOut: Initialising
8/27/2022 8:09:26 AM : CubeOrange 001C002E 3131510E 31363832
8/27/2022 8:09:26 AM : ChibiOS: 93e6e03d
8/27/2022 8:09:26 AM : ArduCopter V4.2.2 (4fcfa4b2)
8/27/2022 8:09:25 AM : Calibrating barometer

**Review by Hwurzburg — CHANGES_REQUESTED** [review]
see comments above

**Comment by IamPete1** [comment]
I think this is a good idea, and should be the default, but we need away to bypass for those who don't use RC.

In my case I was using a H16 Pro and either by design or miss configuration it does not output any RC signal if the transmitter is turned off. Currently it is possible to arm in that state. Once the receiver has seen the transmitter once it worked as normal triggering failsafes.

**Comment by rmackay9** [comment]
I think we should modify the message to replace "Radio" with "RC".  So perhaps, change "Radio signal not received" with "RC not found"?

@Hwurzburg, I don't think this change should flood the GCS with messages because it uses the existing mechanism .. I could be wrong of course.

**Comment by Hwurzburg** [comment]
@rmackay9 Look at the messages above....I have the same prearm flooding of this vs the other prearms

**Comment by muramura** [comment]
I agree to change Randy's message, rc not found.  The reason why the error detection message is sent periodically is that the radio check is selected in the pre-arm check.  A radio check on arm signals a different message.

**Comment by muramura** [comment]
I set the message notification to a 30 second cycle.
I have changed the message.

Screenshot from 2022-08-30 22-38-38

**Review by Hwurzburg — APPROVED** [review]

**Review by rmackay9 — CHANGES_REQUESTED** [review]
This is failing the autotests with this message, "NoRCOnBootPreArmFailure".  I think that the autotests are probably looking for the previous failure string.  so we will need to resolve this before we can merge it.

**Comment by muramura** [comment]
@rmackay9 san
I added the "RC not found" test.

**Comment by peterbarker** [comment]
Randy just wanted the test fixed - merging., thanks

**Comment by rmackay9** [comment]
It turns out that this includes a bug so we should revert it I think unless we can think of a better solution.  Details are in this issue https://github.com/ArduPilot/ardupilot/issues/21921

**Comment by muramura** [comment]
#21924
I was a nuisance. I am sorry.
I PR'd this PR revert.

I will consider the joystick as well.

**Pull request merged**
