### PR TITLE
AP_Landing: phase 1 - port Plane/landing.cpp to new library

### PR DESCRIPTION
**Pull request by magicrub**
This is a mostly non-functional change and a port of ArduPlane/landing.cpp to a new library/AP_Landing class. This is the first phase to help us move along to a new module based landing scheme for Plane

### CODE REVIEW

**Comment by magicrub** [comment]
This has only been tested on SITL but it produced indistinguishable log files wen comparing a flight from this branch vs master on the same auto mission. Basically, the behavior is unchanged.

**Comment by WickedShell** [comment]
Overall LGTM. Lots of changes needed after this step, but as a pure port I have no major complaints. (Long term we will want to try and fix some of the function signatures like verify_land() to not need *so* many arguments, but we can wait on that one. As well as creating a more generic interface).

Only thing that needs to be fixed is the comment in ArduPlance.cpp:528 about how "this should never be reached" needs to be removed as that is now behavior this is depending upon

**Comment by magicrub** [comment]
Thanks @WickedShell, I updated the comment.

**Comment by magicrub** [comment]
Closing in favor of a single phase 3 PR https://github.com/ArduPilot/ardupilot/pull/5269

**Pull request closed without merging**
