### PR TITLE
AC_PosControl: expose _thr_out via get_throttle()

### PR DESCRIPTION
**Pull request by Williangalvani**
This will allow reading the throttle output from the position controller

### CODE REVIEW

**Comment by rmackay9** [comment]
@Williangalvani,

Are we using this new accessor anywhere?  Normally we don't add code and state unless it will be used.

**Comment by IamPete1** [comment]
Why not just ask attitude control? It should be the same value.

https://github.com/ArduPilot/ardupilot/blob/b450740fb0e5cfb814636704a15e8ae19497a24a/libraries/AC_AttitudeControl/AC_AttitudeControl.h#L257

**Comment by Williangalvani** [comment]
> Are we using this new accessor anywhere? Normally we don't add code and state unless it will be used.

This is used in https://github.com/ArduPilot/ardupilot/pull/15247

 > Why not just ask attitude control? It should be the same value.
 
 That works fine, but doesn't feel right.

**Comment by rmackay9** [comment]
I agree with @IamPete1 actually.  In the other PR you've removed the passthrough of the throttle through the attitude controller.  So it's directly pos-control->motors.  that's quite a fundamental change from Copter and I really think it's a bad ideal unless there's a good reason for it.  The extra layering is there to allow change in thrust based on attitude.

There are many ways to do stuff but I think more effort should be spent keep Sub consistent with the other vehicles.  I'm totally happy to help you with that but just need some more communication I think.

**Pull request closed without merging**
