### PR TITLE
Check configured AHRS type last in order to provide a more meaningful error to the user

### PR DESCRIPTION
**Pull request by andyp1per**
Currently EKF issues before arming result in the message:
```
PreArm: AHRS: not using configured AHRS type
```
Because DCM fallback causes the configured type not to match the actual type. This PR moves the check so that the EKF check is hit first and results in 
```
AHRS: Not healthy
```
Which is slightly more meaningful

### CODE REVIEW

**Comment by Hwurzburg** [comment]
so that message now is never shown, correct? or will the prearm get issued repeatedly after the AHRS not healty first message?

**Comment by timtuxworth** [comment]
Slightly more meaningful? That's a pretty low bar. 
When helping others panicking because "something serious is wrong" - I just tell them this message really means "Initializing - please wait"  - how about that?

**Comment by andyp1per** [comment]
> so that message now is never shown, correct? or will the prearm get issued repeatedly after the AHRS not healty first message?

I'm not sure under what circumstances it would now be shown. Generally the problem is the EKF.

**Comment by Hwurzburg** [comment]
one would hope its sent when you have a good EKF3 and AHRS_EKF_TYPE is set to EKF2 and its disabled...a common situation for someone upgrading from an older firmware and being told to disable EKF2 and enable EKF3 for a new feature that requires EKF3....you should not get an AHRS unhealthy, but rather that not using message

**Review by peterbarker — CHANGES_REQUESTED** [review]
I think someone might have done a `commit -a` :-)

Need to remove the submodule commits.

**Comment by andyp1per** [comment]
@peterbarker done

**Comment by IamPete1** [comment]
`AHRS: Not healthy` is a DCM pre-arm message? I would have expected that we would get correct EK3 pre-arm? 

The pre-arm switch is on configured type not using type I think?

"Not healthy" is not really much of a improvement, if we can get correct EK3 message then it would be.

**Comment by andyp1per** [comment]
Not interested enough to spend more time on this

**Comment by peterbarker** [comment]
> Not interested enough to spend more time on this

That's a shame, as I think the code as it currently is is flawed - I think we will fail to retrieve a meaningful message from the EKF where we could.

I think a future PR of mine actually calls pre_arm_check on the configured backend as well as doing the AHRS-healthy  check, so I think this will get better over timne.

**Pull request closed without merging**
