### PR TITLE
Disable airspeed autocal if airspeed is disabled

### PR DESCRIPTION
**Pull request by peterbarker**
This code: https://github.com/ardupilot/ardupilot/blob/master/ArduPlane/ArduPlane.cpp#L360 expects AP_Airspeed to be available... so gating autocal on airspeed actually being enabled seems entirely reasonable.....

### CODE REVIEW

**Comment by hendjoshsr71** [comment]
Makes sense. And reminds me I still need to put in the PR to remove Airspeed from Plane fully...

**Review by hendjoshsr71 — APPROVED** [review]

**Comment by peterbarker** [comment]
> Makes sense. And reminds me I still need to put in the PR to remove Airspeed from Plane fully...

I have a patch for that here - this was a precursor patch....

**Comment by hendjoshsr71** [comment]
> > Makes sense. And reminds me I still need to put in the PR to remove Airspeed from Plane fully...
> 
> I have a patch for that here - this was a precursor patch....

Sweet!

**Comment by peterbarker** [comment]
> > > Makes sense. And reminds me I still need to put in the PR to remove Airspeed from Plane fully...
> > 
> > 
> > I have a patch for that here - this was a precursor patch....
> 
> Sweet!

https://github.com/ArduPilot/ardupilot/pull/20308

**Pull request merged**
