### PR TITLE
Add Gripper support to Rover

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by rmackay9** [comment]
I actually already thought we had gripper support and I had even added it to the release notes. https://github.com/ArduPilot/ardupilot/blob/master/APMrover2/release-notes.txt#L52

**Comment by rmackay9** [comment]
It refuses to pass the rover test for some reason..

**Comment by peterbarker** [comment]
@rmackay9 I think I found that problem.  New test left the vehicle armed, and the protection I put into autotest.py which is supposed to protect against that happening appears to be broken (at least on Rover).

Since you can't arm when armed, a subsequent, unrelated test, was failing.

**Comment by rmackay9** [comment]
Merged, thanks!

**Comment by rmackay9** [comment]
This was on the list to backport to Rover-3.5 but it's not merging cleaning so I'll probably leave it out

**Pull request merged**
