### PR TITLE
Update build scripts

### PR DESCRIPTION
**Pull request by lucasdemarchi**

### CODE REVIEW

**Comment by OXINARF** [comment]
LGTM

**Comment by lucasdemarchi** [comment]
Applied, thanks.

**Comment by magicrub** [comment]
Lucas, You said "Applied, thanks" to your own pull request :)

**Comment by lucasdemarchi** [comment]
Thanks for the review :)
Em 8 de mai de 2016 12:48 AM, "Tom Pittenger" <notifications@github.com>
escreveu:

**Pull request closed without merging**
