### PR TITLE
AP_Logger: avoid logging duplicate FMT/UNIT/FMTU/MULT messages

### PR DESCRIPTION
**Pull request by peterbarker**
Failing due to being out of time meant we wouldn't incremement the counter, even though we'd emitted the item.

it is important we try to send something, so move this check to be after we increment whichever counter we are using.

Tested in SITL with the following patch:
```
--- a/libraries/AP_Logger/LoggerMessageWriter.cpp
+++ b/libraries/AP_Logger/LoggerMessageWriter.cpp
@@ -81,6 +81,10 @@ bool LoggerMessageWriter_DFLogStart::check_process_limit(uint32_t start_us)
     if (AP_HAL::micros() - start_us > limit_us) {
         return true;
     }
+    static uint32_t counter;
+    if (counter++ % 10 == 0) {
+        return true;
+    }
     return false;
 }
```

### CODE REVIEW

**Comment by peterbarker** [comment]
Closes https://github.com/ArduPilot/ardupilot/issues/22662

**Comment by peterbarker** [comment]
```
Board              AP_Periph  blimp  copter  heli  plane  rover  sub
Durandal                      -48    -56     -56   -56    -56    -56
Hitec-Airspeed     0                                             
KakuteH7-bdshot               0      0       -8    0      0      -8
MatekF405                     0      -8      -8    0      -8     -8
Pixhawk1-1M                   0      0       -8    -8     0      0
f103-QiotekPeriph  0                                             
f303-Universal     0                                             
revo-mini                     -8     -8      -8    -8     -8     -8
skyviper-v2450                       0                           
```


image

**Comment by rmackay9** [comment]
Thanks very much for this!

**Review by tridge — APPROVED** [review]

**Comment by rmackay9** [comment]
This is included in Copter-4.3.4-rc1

**Pull request merged**
