### PR TITLE
Move MAVLink fence-message handling up

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by rmackay9** [comment]
Travis looks unhappy with this one but I suspect you're on top of it..

**Comment by peterbarker** [comment]
@rmackay9 It's happy now.

**Comment by peterbarker** [comment]
marked devcalltopic for attention

**Comment by rmackay9** [comment]
Devcall action was for me to test this and then merge.

**Comment by rmackay9** [comment]
lightly tested and then merged, thanks!

**Pull request merged**
