### PR TITLE
Disable EK2 by default on all 1M boards

### PR DESCRIPTION
**Pull request by tridge**
This is in response to Pixhawk1-1M not building any more with EK2

### CODE REVIEW

**Comment by peterbarker** [comment]
Can we kill HAL_MEM_CLASS now? :-)

**Comment by tridge** [comment]
> Can we kill HAL_MEM_CLASS now? :-)

it is used in 2 places

**Comment by stephendade** [comment]
Is it worth putting this into the list of features disabled by HAL_MINIMIZE_FEATURES instead?

It'd be simpler having all the disabled features under the one define, but I'm not 100% the same boards are covered.

**Comment by tridge** [comment]
> It'd be simpler having all the disabled features under the one define, but I'm not 100% the same boards are covered.

we don't want the same list of features disabled for all boards

**Pull request merged**
