### PR TITLE
AP_HAL_ChibiOS: correct clearing of UART drivers

### PR DESCRIPTION
**Pull request by peterbarker**
fixed Hott telem

### CODE REVIEW

**Comment by rmackay9** [comment]
I think we didn't need to include this in Copter-4.0.4-rc2.  The issue with Hott Telemetry was actually something else.

**Comment by andyp1per** [comment]
Anecdotally my SRXL2 issues in master seem much better now. So something in the UART stack was broken and now is not. Not sure whether this bug fix was responsible however.

**Comment by peterbarker** [comment]
On Sat, 13 Jun 2020, Andy Piper wrote:

> Anecdotally my SRXL2 issues in master seem much better now. So something in the UART stack was broken and now is not. Not sure whether this bug fix was
> responsible however.

If it makes you feel better, sure :-)

The dud call was discard_input(), however, which doesn't seem to be 
present in AP_RCProtocol_SRXL2

Peter

**Comment by peterbarker** [comment]
On Fri, 12 Jun 2020, Randy Mackay wrote:

> I think we didn't need to include this in Copter-4.0.4-rc2. The issue with Hott Telemetry was actually something else.

That is also my understanding.

**Pull request merged**
