### PR TITLE
Tidy heli autotune a little

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Review by khancyr — APPROVED** [review]
Nice one.
changes are correct and will have some gain. 
LGTM.

**Review by bnsgeyer — APPROVED** [review]
LGTM

**Comment by rmackay9** [comment]
Merged, txs!

**Comment by rmackay9** [comment]
This PR is included in Copter-4.2.0-beta3 because of merge conflicts with this PR https://github.com/ArduPilot/ardupilot/pull/20238

**Pull request merged**
