### PR TITLE
Rover lqr

### PR DESCRIPTION
**Pull request by Akshath-Singhal**
Added LQR control support to Rover. Changes have been made to maintain similarity with the ArduPlane codebase. Allows easier integration of new Navigation libraries.

### CODE REVIEW

**Comment by rmackay9** [comment]
I'm wonder what testing has been done.. any evidence of it?  Can the vehicle get around a course?  Is it closer or further from the line?  Definitely more testing evidence would be good to see.

**Comment by Akshath-Singhal** [comment]
> I'm wonder what testing has been done.. any evidence of it? Can the vehicle get around a course? Is it closer or further from the line? Definitely more testing evidence would be good to see.

Can you provide any suggestions for the kind of testing required? The library was developed for use in Plane. The major reason for raising this PR was to enable easily switching between navigation controllers and enable support for new navigation controllers. I will be doing testing with a ROVER next week. Suggested missions would be highly appreciated.

**Comment by rmackay9** [comment]
@Akshath-Singhal, a mission that includes corners of various angles would be good.  For example straight line, 45 degrees, 90degrees, 180degrees.  I'd also like to see what happens we a DO_REVERSE is included which should make the vehicle drive in reverse.

Using SITL to test is a good way as well but it's up to you of course.

**Comment by davidbuzz** [comment]
pr was not reworked after randys review in 2019, appears abandoned by orig author.

**Pull request closed without merging**
