### PR TITLE
AP_Mission: PLANE to refuse NAV_SPLINE_WAYPOINT missions items

### PR DESCRIPTION
**Pull request by magicrub**
PLANE to refuse NAV_SPLINE_WAYPOINT missions items. This replaces https://github.com/ArduPilot/ardupilot/pull/19234

### CODE REVIEW

**Comment by samuelctabor** [comment]
Seems to work correctly in simulation.

**Review by peterbarker — APPROVED** [review]
LGTM

**Comment by peterbarker** [comment]
I will point out that there's the corner case of a quadplane doing an entire mission in VTOL mode - which should be capable of running these spline waypoints.  Pretty damned sure that's not tested in autotest, and probably not tested *at all, by anyone*.

**Comment by magicrub** [comment]
Spline waypoints are not handled at all my Plane. We can revisit this if/when it gets added to https://github.com/ArduPilot/ardupilot/blob/master/ArduPlane/commands_logic.cpp

Meanwhile, it's a safety risk.

**Review by tridge — APPROVED** [review]

**Pull request merged**
