### PR TITLE
Copter : LAND continues on FS_BATT

### PR DESCRIPTION
**Pull request by Kiwa21**
If Coper is already landing and the FS_BATT kicks in, do not change mode to RTL and let the land continue.

### CODE REVIEW

**Comment by magicrub** [comment]
@Kiwa21 for next time, instead of closing an old PR and creating a new one please just force push to the same branch. The existing PR updates.

**Comment by Pedals2Paddles** [comment]
I'm happy work this into my existing PR regarding land mode and failsafes if it would keep things cleaner.

**Comment by magicrub** [comment]
@Pedals2Paddles we have two conflicting PRs, this one and yours (https://github.com/ArduPilot/ardupilot/pull/6406). Does anyone have a preference which is the better method?

**Comment by Pedals2Paddles** [comment]
Well I naturally favor mine :)

**Comment by Kiwa21** [comment]
Well, I didn't see the FS_BATT was also taken into account the Matt PR, I tought it was only for RADIO_FS.
I don't mind using his PR, either way the feature will be in ! :)

**Comment by Pedals2Paddles** [comment]
I hadn't thought of that when I was doing it. I will add the battery portion and tag you in it. Good thinking.

**Comment by OXINARF** [comment]
This PR is targeting 3.5 branch instead of master, which is a no-go until this is merged in master.

In any case, I have the same objection I had for #6406 - there we agreed on using a parameter and it looks like @Pedals2Paddles will be incorporating this with that option.

For these reasons, I'm closing this.

**Pull request closed without merging**
