### PR TITLE
HAL_ChibiOS: adjust Swan-K1 tuning

### PR DESCRIPTION
**Pull request by tridge**
raise priority of attitude control in fixed wing flight

### CODE REVIEW

**Comment by Hwurzburg** [comment]
I think that PTCH2SRV_TCONST also needs lowering....maybe we should look at some of my logs?

**Comment by tridge** [comment]
> I think that PTCH2SRV_TCONST also needs lowering...and the FW->VTOL transition rates may need lowering.....maybe we should look at some of my logs?

yes, very likely. Maybe raising Q_A_ACCEL_Y_MAX too. We really need new values to be tested, but I'm in lockdown for at least the next 2 weeks

**Comment by Hwurzburg** [comment]
I can test Thur..

**Review by IamPete1 — APPROVED** [review]
These seem like sensible changes, would be good to flight test of course.....

**Comment by Hwurzburg** [comment]
logs of test flights: https://www.dropbox.com/s/wp29qo4zb3ea90x/2021-08-19%2013-28-48.bin?dl=0
https://www.dropbox.com/s/em0cpw0v9wivjcs/2021-08-19%2013-16-40.bin?dl=0

**Comment by peterbarker** [comment]
Rebased on MacOSX CI fixes

**Pull request merged**
