### PR TITLE
AP_GPS: Only inject RTCM data to the selected GPS device defined in G…

### PR DESCRIPTION
**Pull request by amilcarlucas**
…PS_INJECT_TO parameter

### CODE REVIEW

**Comment by proficnc** [comment]
This will still allow dual RTK yes? 

Please update the Here+ wiki for any user changes needed to have dual RTK

**Comment by WickedShell** [comment]
@proficnc default GPS_INJECT_TO of 127 means inject to all GPS's. As long as someone hasn't edited that parameter from the default value it will work. (And if they edited it, they were probably trying to lock out one GPS anyways)

**Comment by amilcarlucas** [comment]
Good catch OXINARF, I removed it, thanks

**Comment by OXINARF** [comment]
Merged, thanks!

**Pull request merged**
