### PR TITLE
Lua script starts/stops video recording on arm/disarm

### PR DESCRIPTION
**Pull request by arikrupnik**
I use this script in real life. I thought I'd add it to the examples directory to demonstrate use of aux functions from a script without T configuration and also as an example of simple, useful automation Lua scripting can bring to ArduPilot.

### CODE REVIEW

**Comment by rmackay9** [comment]
Looking pretty good.  A couple of small things:

1. best to prefix the commit with "AP_Scripting: ".
2. consider moving it to the applets directory if you think it would be useful to others users as-is.  If you do this though you'll also need to make a small .md file with setup instructions.

**Comment by arikrupnik** [comment]
I always forget the directory prefix! Would you like me to force-push with a new message? I'll take your advice on leaving this script here or moving to applets. It's useful as-is (it depends only on the value of standard parameters), but it's also quite small.

**Comment by rmackay9** [comment]
@arikrupnik,

If you could force push it that would be great.

Maybe @andyp1per should weigh in on whether it should be an applet or an example.  I think it's more of an applet.

**Comment by arikrupnik** [comment]
> If you could force push it that would be great.

done

> Maybe @andyp1per should weigh in on whether it should be an applet or an example. I think it's more of an applet.

I think he wants it in C++ :=)

**Comment by rmackay9** [comment]
Re using C++ instead, I was also thinking of adding a CAM_OPTIONS parameter to allow turning on regular video recording (using a Siyi gimbal/camera) at arming.

**Comment by arikrupnik** [comment]
> Re using C++ instead, I was also thinking of adding a CAM_OPTIONS parameter to allow turning on regular video recording (using a Siyi gimbal/camera) at arming.

Can it have a bit to use the target's armed state instead of your own if the mount is following another vehicle?

**Comment by andyp1per** [comment]
Looks good - I agree with @rmackay9 probably should be an applet as it is useful as-is

**Comment by arikrupnik** [comment]
Wow, the .md came out longer than the code. Let me know if this works for y'all or if I can make any additional changes.

**Comment by arikrupnik** [comment]
@rmackay9 @andyp1per do I need to do anything else to merge this?

**Comment by tridge** [comment]
squashed commits

**Review by tridge — APPROVED** [review]

**Comment by arikrupnik** [comment]
Thank you @tridge @rmackay9  and @andyp1per

**Review by davidbuzz — COMMENTED** [review]
looks good to me.

**Pull request merged**
