### PR TITLE
AP_SerialManager: allow for protocol GPS2

### PR DESCRIPTION
**Pull request by tridge**
if you specify protocol as GPS2 then it will only match the 2nd instance
This was requested by @priseborough

### CODE REVIEW

**Comment by priseborough** [comment]
I tested this on a pixracer with the second GPS connected to TELEM1 with SERIAL1_PROTOCOL = 6. The primary GPS is connected to the GPS port with SERIAL3_PROTOCOL = 5. Telemetry is via wifi module. It goes into an indefinite series of GPS1 detection events:

screen shot 2017-09-09 at 1 25 12 pm

**Comment by tridge** [comment]
ok, thanks Paul, I'll see if I can reproduce and fix

**Comment by tridge** [comment]
I've reproduced the issue and pushed a fix (I hope!). Only tested in SITL

**Comment by priseborough** [comment]
It works thanks.

**Comment by tridge** [comment]
great, thanks Paul

**Comment by OXINARF** [comment]
I understand why Paul wants this and I don't have a problem with this code but I think it shouldn't be publicized in the parameter's value documentation. We had this and got away from it. Besides other protocols not having the same (and the same argument could be used for them), It will be a problem when we have more GPS instances.

**Comment by WickedShell** [comment]
I get why being able to specify which GPS is primary, however I think this is the wrong easy to do it.

The problem is that this doesn't scale as Francisco observed, it breaks existing dual GPS users, and is a more complicated approach them just letting the primary GPS be a parameter that the gcs can set and have any auto switching just be a soft set that is overridden on reboot.

Is there a reason to user the protocol for this?

**Comment by WickedShell** [comment]
s/easy/wrong

I apologize for phone typing problems.

**Comment by magicrub** [comment]
Feels like a bad hack to me

**Comment by magicrub** [comment]
-1

**Comment by priseborough** [comment]
@magicrub OK, so how do we ensure that when a user plugs a GPs receiver into a port they can guarantee that it will always be GPS1 or GPS2? Not knowing is unacceptable when we have Antenna offset parameters per GPs instance. At the moment i have no choice but to do custom cross-over wiring looms so that when i plug a second receiver into the pixracer it will be seen as GPS2 and can be used as ride-along only.

**Comment by olliw42** [comment]
I have a user, and a general concern

u: as much as I understand 'GPS' is what it was before, a "auto-numerated" assignement. Calling the two options 'GPS' and 'GPS2' is then most unfortunate because following all other sensor parameter naming one would think that 'GPS' means GPS unit 1 and 'GPS2' GPS unit 2 ... one always can of course argue RTFM, but some consistency can be helpful
(in that line of logic the "correct" thing would be to actually rename 'GPS' ;))

g: this is obviously a quick hack to quickly achieve something. My concern: it might end up in a release and lateron may become a annoyance. I can't see a concept. Which would survive also other GPS types - such as e.g. UAVCAN GPS units ;), or "future". As food for thought: Conceptually, as regards multi-type/multi-instance handling, I can't see what a GPS would distinguish from e.g. a magnetometer. Both are sensors with properties, and one may have several of them. It's surprising how massively differently they are handled in AP. :)

**Comment by tridge** [comment]
> it breaks existing dual GPS users,

why does it break them? It doesn't change existing behaviour

**Comment by tridge** [comment]
please note, this patch does not require that users change their dual-GPS setup. It works exactly as before if they just leave both at 5 (ie. GPS). It only changes behaviour if the user really cares and wants to know exactly which GPS is on what port (like Paul does)

**Comment by tridge** [comment]
> We had this and got away from it.

no, we never had this functionality. Previously users had to set GPS and GPS2 if they wanted dual-GPS. That was too hard for most users. This approach preserves the simplicity we have now, but allows advanced users to control the order.

**Comment by robustini** [comment]
+1

**Comment by tridge** [comment]
addressing some of the other concerns raised:

- The GPS is different from sensors like the baro, as the consumer of the GPS data does care which one they are consuming. Failover of things like the baro is handled within the sensor library, so the only consumer of the data that cares about multiple sensors outside of AP_Baro is the logging system. For the GPS, the EKF does care about multiple sensors. We don't have any other sensor library other than GPS where this is needed at the moment.
- The idea that this system is not scalable to more than 2 GPS modules is incorrect. In fact, the "_PRIMARY" method is the one that is not scalable. If we had support for 4 GPS modules, would we have GPS_PRIMARY, GPS_SECONDARY, GPS_THIRD, GPS_FOUTH? And how does the user relate those back to the serial ports so they can control which is which? What would the API look like for the EKF to then access the primary, secondary, third etc? By putting the tag in the SERIALn_ name space it is much clearer as the tag is directly associated with the serial port and the log numbers will align with the API used by the EKF. We could have SERIALn_PROTOCOL=GPS3 and GPS4 if we wanted to then use the same logic I've put in for this patch to make it work with either all protocols set to GPS, or allowing a user to specify the exact order if they want to.

I think the key complaint is that this is not how we've done things in the past, but that neglects to take into account that we've never had to deal with this problem before. The problem that XXX_PRIMARY solves is a quite different problem from what this solves. The XXX_PRIMARY method is about failover order within the sensor library. The GPS, GPS2 approach is about giving a clear way to control order for an external consumer of the sensor (and for logging).

It is much closer to the problem we solved with the SERVOn_FUNCTION approach than it is to the XXX_PRIMARY approach.

**Comment by magicrub** [comment]
The concept of "primary goal" should go away when possible. Maybe now? It's no longer a back up, we can blend and should always blend. Naturally, the thing doing the blending would need to know where the sensor is located some that is more critical for good, especially with rtk. So, not primary, but there is still gps1 and gps2...

**Comment by OXINARF** [comment]
@tridge 

> Previously users had to set GPS and GPS2 if they wanted dual-GPS. That was too hard for most users. This approach preserves the simplicity we have now, but allows advanced users to control the order.

Yes and publicizing a GPS2 option will once again confuse users. Like I said, I don't have a problem with the code itself, I just don't like publicizing the option.
By the way, when I said that it doesn't scale it wasn't only about more GPS instances, but also that other libraries could want the same - for example, the rangefinder library.

> The GPS is different from sensors like the baro, as the consumer of the GPS data does care which one they are consuming. Failover of things like the baro is handled within the sensor library, so the only consumer of the data that cares about multiple sensors outside of AP_Baro is the logging system. For the GPS, the EKF does care about multiple sensors. We don't have any other sensor library other than GPS where this is needed at the moment.

I think it's completely the opposite. The EKF does not care about multiple GPS, it always reads the primary GPS - actually only recently, when the blend work was done, did the EKF got aware of GPS primary changing (that was the main reason we didn't recommend the auto switching before, the EKF wasn't aware of that change and would only see a jump in position).
You used the example of baro, which is the other one where unfortunately the EKF doesn't care about multiple being available and always relies on the library changing the primary. But the compass or inertial sensor libraries, EKF does care about sensor index in those and will change which sensor it reads from them.

> The GPS, GPS2 approach is about giving a clear way to control order for an external consumer of the sensor (and for logging).

As I said above, besides logging, I think no GPS data consumer cares about the GPS sensor order - but more important than that, that's not Paul's problem. Paul's problem is that when he adds or removes a GPS it will change in what order they are detected in the GPS library and so parameters like the POSition need to be changed accordingly - this is inside the library, nothing to do with external users.
I understand the issue so I'm fine with the code, but I'll add that exactly the same argument can be done for compass, for example.

A more correct change would be the libraries having parameters saying which serial port should be used instead of the serial port having a protocol assigned - this could lead to bad configurations where a serial port would be used in two places but we could easily put a warning in that case and forbid that to happen.
Think of this example: you set SERIAL0/1/2_PROTOCOL to MAVLink and accordingly set SR0/1/2 parameters to what you want. Later on, you change SERIAL1_PROTOCOL to NONE. Your SR1 parameters are now wrong and you have to manually copy your SR2 values to SR1. If the serial port was configured in a SR2_PORT parameter then it would continue to work, only SR1_PORT set to NONE would be needed to disable that MAVLink port.

**Comment by amilcarlucas** [comment]
@OXINARF +1

**Comment by priseborough** [comment]
@OXINARF When post processing GPS log data it is necessary to know which receiver is GPS1 or GPS2

**Comment by proficnc** [comment]
+1 Paul
It's critical to know which GPS is which...

And I would love to go further... (off topic)

I hate that plugging in an additional compass changes which one is which! 

I would much prefer to see all the compasses that exist, and to be able to choose exactly which one I want to use.. and if it disappears... to know.. not just have new data dumped from another random compass

**Comment by tridge** [comment]
@proficnc that would indeed be nice, but we need to make it simple for most users, and need a way of expressing the layout in terms of a flat space of parameter names

**Comment by geofrancis** [comment]
How does this relate to geotagging in mission planner as it selects GPS or GPS2 from the log?

It is absolutely critical that it selects the correct GPS as one is RTK and directly over the camera and the other is at the back of the plane. 

How does ardupilot currently Handle dual GPS assignment? Is there no way to ensure what GPS is assigned other than this patch?

**Comment by magicrub** [comment]
any ideas on this one?

**Comment by WickedShell** [comment]
Needed a different approach was outlined on the dev call and tridge was going to approach it, however it has not been done yet. (What is outlined here did not play well with UAVCAN for example)

The primary thing this was attempting to correct was not the level issue it was originally perceived to be. (GPS detection order doesn't matter, the only time the GPS's could be remapped surprisingly was if you changed a `SERIALx_PROTOCOL` to GPS that was earlier then either of your existing GPS mapped serial ports.

**Comment by WickedShell** [comment]
Closing as it was determined this was not the way we wanted to move forward with the overall feature, and it seems unlikely that this branch would be used on the selected solution moving forward (in part because no effort has been made on it recently).

**Pull request closed without merging**
