### PR TITLE
.github: add GH cache cleanup on PR close. Taken from https://docs.gi…

### PR DESCRIPTION
**Pull request by khancyr**
…thub.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#force-deleting-cache-entries

### CODE REVIEW

**Review by peterbarker — CHANGES_REQUESTED** [review]
Commit message needs fixing.

Please put the URL in the body of the commit message rather than the first line

Is this the right thing to do?  If someone force-pushes on the same merge base with a minor change somewhere then a lot of the files will be identical and we'll at least get secondary cache hits.

Maybe I'm misunderstanding what's in this cache we're manipulating here?

**Comment by khancyr** [comment]
The current issue is that we are far over our cache limit, so github randomly remove old cache, most generally the oldest first. We speak about Github Cache. 

With this PR, we ask github to remove the PR cache when we merge the PR. So the cache cleanup will happens faster and we remove normally useless PR cache first, and not master branch cache.

The only issue it bring is if somebody reopen the PR and put another commit on it. it will then need to recreate a cache. But as we merge the PR into master, the master cache will be used as base and shouldn't be far from the PR anyway. So we won't lose much in this special case.

The second case that is impacted, is if somebody close the PR and open it again. Then it will need to rebuild the cache. As previously, it will use master cache as basis.

Considering, how low those two case are, I prefer to have the cache cleanup on PR close and retain interesting PR cache longer, like the master branch one's.

**Comment by peterbarker** [comment]
> merge commit should get rid of its cache, so looking here : https://github.com/ArduPilot/ardupilot/actions/caches should give us less usage after merge.

It's not really the cache size that matters, 'though - it's the build times, right?  That's what we *actually* care about :-)

**Comment by khancyr** [comment]
well on chibios the cache is around 30-40mb so that 2-3s to dl and unzip and 6s to zip and upload.
On unitest, cache is 280MB, that 6s to dl and unzip and 13s to zip and upload. 

So it gives us a bit of time. But yes, nothing compared to some other improvement. But that is a bit greener so worth it for me.

**Comment by peterbarker** [comment]
Merged, thanks!

**Pull request merged**
