### PR TITLE
AP_BoardConfig: rename BRD_TEMPMGN_LOW to BRD_HEAT_LOWMGN

### PR DESCRIPTION
**Pull request by rmackay9**
This attempts to make the board heater parameter names more consistent so that users have an easier time understanding what parameters are used to control this feature.

The current parameter names are:

- BRD_IMU_TARGTEMP
- BRD_IMUHEAT_P/I/IMAX
- BRD_TEMPMGN_LOW

The new proposal is:

- BRD_HEAT_TARG
- BRD_HEAT_P/I/IMAX
- BRD_HEAT_LOWMGN

I'm not hugely locked into these names, I just want them to be consistent.

This a follow-up to https://github.com/ArduPilot/ardupilot/pull/18640

### CODE REVIEW

**Comment by IamPete1** [comment]
My original PR was `BRD_IMU_ARM_TEMP`, the change to `BRD_TEMPMGN_LOW` was from dev call. The though was that if we changes to a margin we have to be a clear that it is a low margin only. It does not apply on the high side. 

I still prefer having a absolute temp rather than a margin, by that was voted down. 

But I just want the functionality, I'm don't have any strong feeling on the name. So if someone does that we can change to that.

**Comment by rmackay9** [comment]
@IamPete1, OK thanks.  I've changed the parameter names in this PR to start with BRD_HEAT_xxx

**Comment by davidbuzz** [comment]
lgtm. :-)

**Comment by rmackay9** [comment]
Great, merged!

**Pull request merged**
