### PR TITLE
Touchdown yaw correction with altitude or weight on wheels

### PR DESCRIPTION
**Pull request by EShamaev**
Side wind 15 m/s

Without:
image
[00000006.zip](https://github.com/ArduPilot/ardupilot/files/1800773/00000006.zip)

With:
image
[00000007.zip](https://github.com/ArduPilot/ardupilot/files/1800775/00000007.zip)

### CODE REVIEW

**Comment by EShamaev** [comment]
Depends on: https://github.com/ArduPilot/ardupilot/pull/7893

Adresses: https://github.com/ArduPilot/ardupilot/issues/7867

**Comment by EShamaev** [comment]
@magicrub For sure I missed some special things in AP_Landing, please review and give comments.

**Comment by magicrub** [comment]
Ooooo thank you! GaryM will be very happy

**Comment by EShamaev** [comment]
Would be perfect if https://github.com/ArduPilot/ardupilot/pull/7890 gets reviewed and hopefully merged in for full tests. Now the wind near the ground is rather limited for adequate testing of this.
Also the steering in SITL is not perfect either.

**Comment by magicrub** [comment]
@EShamaev I've rebased it and optimized a few things. Ready to merge when the other dependency gets merged

**Comment by EShamaev** [comment]
Superseded with https://github.com/ArduPilot/ardupilot/pull/9736

**Pull request closed without merging**
