### PR TITLE
AC_FENCE:correct prearm message

### PR DESCRIPTION
**Pull request by Hwurzburg**
NFC....can be inside or outside a fence to be in breach

### CODE REVIEW

**Comment by rmackay9** [comment]
Thanks, let's get @andyp1per to approve to be sure it doesn't interfere with his fence-min-alt PR

**Review by peterbarker — APPROVED** [review]

**Comment by peterbarker** [comment]
> Thanks, let's get @andyp1per to approve to be sure it doesn't interfere with his fence-min-alt PR

We've already merged that one.  Sorry, perhaps that was ahead of time?!

Merging this one.

**Review by peterbarker — CHANGES_REQUESTED** [review]
Not really NFC - even changing a string like this is functional - as the autotests failing show.

Autotests must pass

**Comment by peterbarker** [comment]
... commit message should also be `AC_Fence` rather than `AC_FENCE`

**Review by andyp1per — COMMENTED** [review]
Sorry, I did see this Henry but didn't have time to check where it was being changed. I am ok with this if the tests are fixed to match.

**Pull request merged**
