### PR TITLE
APM_Control: remove unused variables

### PR DESCRIPTION
**Pull request by peterbarker**
recent refactoring made these unused IIUC.

### CODE REVIEW

**Review by khancyr — APPROVED** [review]
That is too bad that they aren't reported as unused

**Comment by peterbarker** [comment]
> That is too bad that they aren't reported as unused

They are by clang++ :-)

**Comment by khancyr** [comment]
Yep, they are by static analyzer too. But on our default gcc they aren't reported. That is annoying

**Review by IamPete1 — APPROVED** [review]
must be correct as it is still building.

**Comment by rmackay9** [comment]
Not my baby but it must be safe and correct and we can save 2 min on the dev call.

**Pull request merged**
