### PR TITLE
Set get mode reason

### PR DESCRIPTION
**Pull request by WillyZehnder**
Making mode_change_reason available for lua and for other libraries.

### CODE REVIEW

**Review by rmackay9 — CHANGES_REQUESTED** [review]
Thanks for this.

I don't think it makes sense to store the mode reason within the Mission class.  It looks like it is already stored in each vehicle (see Copter.h ModeReason control_mode_reason) so a better method might be to add an accessor to the vehicle class.

**Comment by peterbarker** [comment]
Agree with @rmackay9

Amusingly the ModeReason is constant across all vehicles so notionally we can hold it in AP_Vehicle rather than each vehicle separately.  If we're not storing it on some vehicles we might want to do that.  pure-virtual is the obvious other choice (but has a flash cost).

**Comment by peterbarker** [comment]
I've trimmed all commits but the add-lua-binding patch.  I intend to merge it once CI passes.

**Comment by WillyZehnder** [comment]
@peterbarker That's the old/first PR. In the meantime I worked on the successor #16463 we lately discussed.

Btw I asked for syntax of enumeration type on Discord # scripting and Peter Hall told me to use the base-typ like used for get_mode https://discord.com/channels/674039678562861068/719466647710072832/804345362643025941
But if you could give me an answer I would be happy to learn.

**Pull request closed without merging**
