### PR TITLE
Tools: Parameter file for enRouteLAB 's quad copter "LAB445".

### PR DESCRIPTION
**Pull request by muramura**
enRouteLAB has released Quad Cotter LAB445 for consumers. It is that parameter file.

This quad Copter LAB445 video:
https://youtu.be/V4NShzpTQP8

### CODE REVIEW

**Comment by rmackay9** [comment]
Hi @muramura,
thanks for this file.  One thing though is we should only save the non-default values and we shouldn't put any sensor calibration numbers in there.  You can imagine that if someone loaded this file they would get the compass offsets for some vehicle.. but it wouldn't match their own.

**Comment by muramura** [comment]
@rmackay9 san Check thank you.
I understand. I will change.

**Comment by rmackay9** [comment]
Merged, thanks!

**Comment by muramura** [comment]
@rmackay9 san Checked and Merged Thank you.

**Pull request closed without merging**
