### PR TITLE
Add WARN_IF_UNUSED to RingBuffer methods

### PR DESCRIPTION
**Pull request by peterbarker**
... and fix some places where we weren't checking.

### CODE REVIEW

**Comment by khancyr** [comment]
Test build on my machine for Cube Orange and SITL with DEBUG. I didn't notice any new warnings so that is fine.
Test that warning is correctly triggered OK !

I don't have CAN hardware so I haven't test the changes.
Those on CANSerialRouter.cpp seems correct as but lead to something strange : we have data available but cannot retreive them.
Changes on AP_UAVCAN_SLCAN.cpp are correctly handle by the current usage : we always check that the return from the receive() function is 1 for success, 0 is failure.

Question : shouldn't the push method also have its return checked ?

**Comment by peterbarker** [comment]
On Tue, 7 Jul 2020, Pierre Kancir wrote:

> I don't have CAN hardware so I haven't test the changes.
> Those on CANSerialRouter.cpp seems correct as but lead to something strange : we have data available but cannot retreive them.

Yes - but if there was another reader that can happen.  These loops could 
just be written to try the peek() directly rather than checking 
available().

> Question : shouldn't the push method also have its return checked ?

Probably.

**Comment by khancyr** [comment]
@peterbarker Do you need anything else or we can merge this ?

**Comment by peterbarker** [comment]
@khancyr no reviewer has approved this PR.

**Comment by rmackay9** [comment]
I think @bnsgeyer can comment on the helicopter sitl change.  I've added @tridge and @bugobliterator to the reviewer list for the CAN level changes.

**Comment by peterbarker** [comment]
On Sat, 18 Jul 2020, Bill Geyer wrote:

> @bnsgeyer commented on this pull request.
> 
> I ran the Helicopter SITL. There were no issues which I'm sure was determined using the autotest. So if this was to actually happen while the SITL was
> running, does user receive a warning on the GCS? Do I need to add code to handle this if it does happen? I am just using the ring buffer to add time delay
> to the aircraft response.

No, this is all compile-time checking.

Adding WARN_IF_UNUSED means that the caller *must* deal with the result 
value in some way.

It's a cheap win for reducing bugs.

In this case I've simply returned if there's nothing in the buffer (so pop 
fails).  If it is the case that the flow through the code means you will 
*always* have something to pop then the appropriate thing is to put an 
AP_HAL::panic() in place as the author believes it's a "can't happen". 
When it does happen you get a clear error rather than starting to use 
uninitialised data!

**Comment by rmackay9** [comment]
Merged, hope that's OK.  Perhaps the conversation hasn't quite finished but I think we've agreed that this is safe (and a good change)

**Pull request merged**
