### PR TITLE
define out scripting specific vehicle functions when no scripting. 

### PR DESCRIPTION
**Pull request by IamPete1**
Easy win, saving 600 bytes on copter F405 Wing

```
Binary           text             data         bss            total
---------------  ---------------  -----------  -------------  ---------------
antennatracker   -84 (-0.0127%)   0 (0.0000%)  4 (+0.0031%)   -80 (-0.0101%)
arducopter       -600 (-0.0643%)  0 (0.0000%)  0 (0.0000%)    -600 (-0.0564%)
arducopter-heli  -600 (-0.0654%)  0 (0.0000%)  0 (0.0000%)    -600 (-0.0572%)
ardurover        -576 (-0.0694%)  0 (0.0000%)  0 (0.0000%)    -576 (-0.0599%)
arduplane        -228 (-0.0235%)  0 (0.0000%)  -4 (-0.0031%)  -232 (-0.0211%)
blimp            -84 (-0.0124%)   0 (0.0000%)  4 (+0.0031%)   -80 (-0.0099%)
ardusub          -84 (-0.0104%)   0 (0.0000%)  4 (+0.0031%)   -80 (-0.0085%)

```

### CODE REVIEW

**Comment by davidbuzz** [comment]
lgtm

**Review by davidbuzz — APPROVED** [review]

**Review by tridge — CHANGES_REQUESTED** [review]
I'd like to know why the linker isn't doing this for us

**Comment by IamPete1** [comment]
Looks like the linker cant deal with virtual functions, for `set_steering_and_throttle` that is not used in copter we still get:
```
[ardupilot/build/MatekF405-Wing/libraries/AP_Vehicle/AP_Vehicle.cpp.3.o]
00000001 W AP_Vehicle::set_steering_and_throttle(float, float)

[ardupilot/build/MatekF405-Wing/ArduCopter/Copter.cpp.39.o]
00000001 W AP_Vehicle::set_steering_and_throttle(float, float)
```

Had a poke about and cant find anything very useful, possibly there is a compiler flag, but I'm well out of my depth.

This cant be the only case, we might be able to save quite abit of flash....

**Comment by andyp1per** [comment]
By definition the linker can't eliminate virtuals unless they are not called. If they are called then the target callee is determined at runtime so the linker can't tell whether it's used or not. The only way to avoid this is to ifdef out virtuals in subclasses if known not to be used.

**Review by tridge — APPROVED** [review]

**Comment by rmackay9** [comment]
This was included in Copter-4.1 (and other vehicles) because it resolved merge conflicts

**Pull request merged**
