### PR TITLE
Copter: fix options to disable MOUNT/ADSB

### PR DESCRIPTION
**Pull request by tatsuy**
This PR makes options to disable MOUNT / ADSB in APM_Config.h work.

MOUNT/ADSB ENABLED
```
Build directory: /home/drone/github/ardupilot/build/CubeBlack
Target          Text     Data  BSS     Total  
----------------------------------------------
bin/arducopter  1529464  2484  194344  1726292
```

#define MOUNT_ENABLED         DISABLED
```
Build directory: /home/drone/github/ardupilot/build/CubeBlack
Target          Text     Data  BSS     Total  
----------------------------------------------
bin/arducopter  1504288  2464  194360  1701112
```

#define ADSB_ENABLED          DISABLED
```
Build directory: /home/drone/github/ardupilot/build/CubeBlack
Target          Text     Data  BSS     Total  
----------------------------------------------
bin/arducopter  1522436  2484  194348  1719268
```

### CODE REVIEW

**Review by khancyr — APPROVED** [review]
Hello,

That is interesting. 
The blocking point I saw is if we got both hal_mount_enable and mount_enable defined. But either the compilation will failed or the linker will get ride of unused lib so it should be fine

**Comment by tatsuy** [comment]
Thank you for the comment.

If both are set, the setting (mount_enable) in APM_Config.h works and ignore hal_mount_enable.
This is the same method as HAL_SPRAYER_ENABLED and I think it works correctly.
https://github.com/ArduPilot/ardupilot/blob/37fb7a52e06985aae819e035d63231725319f8dd/ArduCopter/config.h#L211

**Review by khancyr — APPROVED** [review]
LGTM

**Comment by rmackay9** [comment]
We discussed this on the dev call and the issue raised by Tridge, MichaelDB and PeterB is that because we now use singletons the APM_Config.h method will only affect the vehicle code and may or may not end up saving flash space.  This PR does save some flash but the library may or may not still be linked in.

I brought up the general complaint that the move to singletons has progressed and broken Copter's ability to disable features easily using the APM_Config.h.

The action from the call was for @tridge and @rmackay9 to clarify how the hwdef can be modified to disable a feature and get this on the developer wiki.

After the call I brought up in the chat that we probably need a replacement for the APM_Config.h.  This could probably be a single file included by all hwdef files that includes a full list of features that can be enabled/disabled.

I think it's unlikely that we will merge this PR as-is unfortunately so I'm going to close it sorry!

**Pull request closed without merging**
