### PR TITLE
Rover: cycle through rangefinders when sending WATER_DEPTH

### PR DESCRIPTION
**Pull request by peterbarker**
Requested in https://github.com/ArduPilot/ardupilot/pull/28875

### CODE REVIEW

**Comment by peterbarker** [comment]
New autotest fails before the patch, passes after:
```
    DepthFinder (Test mulitple depthfinders for boats) (Did not get expected rate (want=12.000000 got=24.000000)) (see /home/pbarker/rc/buildlogs/Rover-DepthFinder.txt) (duration 10.057545185089111 s)
```

**Review by IamPete1 — APPROVED** [review]
LGTM

**Comment by rmackay9** [comment]
Merged, thanks!

**Comment by rmackay9** [comment]
I was unable to immediately include this in 4.6.0-beta5 due to merge conflicts

**Pull request merged**
