### PR TITLE
AP_Terrain: Update spacing param description in line with firmware us…

### PR DESCRIPTION
**Pull request by Hwurzburg**
…eage

### CODE REVIEW

**Comment by rmackay9** [comment]
Is this true that there is no point in setting the grid spacing to less than 100?  I very regularly set this to 30m.

**Comment by Hwurzburg** [comment]
I was told that by @tridge that the code does not use anything closer than 30m,,,he had me remove that from the PR for updating the wiki on terrain sourcing  https://github.com/ArduPilot/ardupilot_wiki/pull/2856

**Comment by tridge** [comment]
> I was told that by @tridge that the code does not use anything closer than 100m,,,he had me remove that from the PR for updating the wiki on terrain sourcing 

The protocol supports less than 100m, and if the user had setup their own terrain source in the GCS (which I believe is possible with MissionPlanner) then it could use better than 30m.
What I was trying to say with regards to the wiki is the ArduPilot SRTM server will only server the 100m grids. So maybe we should say "Values less than 100m will only be useful if the GCS is setup to service higher resolution tiles than the standard SRTM server can provide. With the default GCS setup a value below 100 will just waste space on the sdcard"

**Comment by tridge** [comment]
we should also check if MissionPlanner does automatically use a different higher resolution SRTM server if 30m is requested. It is possible that it does as those servers do exist, they just aren't mirrored on the ArduPilot server

**Comment by rmackay9** [comment]
@meee1, can MP actually provide SRTM data at 30m resolution?  I think it can but ..

**Comment by meee1** [comment]
by default i use the 90m (3 arc second), i do have support for srtm(1 arc second) but its not auto downloaded, MP supports down to cm level though via custom geotiff etc.

**Comment by aaaaaaudrey** [comment]
Is there any kind of existing guide or resource to get 30m SRTM data into mission planner? Seems like a good thing to add to the wiki. If there's even base level documentation I'll do the wiki page.

**Comment by Hwurzburg** [comment]
Modified description after conversation with @tridge

**Comment by meee1** [comment]
@aaaaaaudrey 
 > Is there any kind of existing guide or resource to get 30m SRTM data into mission planner? Seems like a good thing to add to the wiki. If there's even base level documentation I'll do the wiki page.

are you in the US? as thats the only place 1 arc second srtm data exists.
if you in australia you can use elvis https://elevation.fsdf.org.au/ but again, manual added

**Comment by aaaaaaudrey** [comment]
@meee1 

> are you in the US? as thats the only place 1 arc second srtm data exists.


Nope, there is 1 arc second SRTM data for the entire planet as of recently under SRTMGL1v003. It's even void filled. https://earthdata.nasa.gov/learn/articles/nasa-shuttle-radar-topography-mission-srtm-version-3-0-global-1-arc-second-data-released-over-asia-and-australia

Tiles can easily be downloaded [here](https://search.earthdata.nasa.gov/search/granules?p=C1000000240-LPDAAC_ECS&q=SRTMGL1&tl=1577113052!4!!)

**Comment by sangwoomoon** [comment]
@meee1 

> by default i use the 90m (3 arc second), i do have support for srtm(1 arc second) but its not auto downloaded, MP supports down to cm level though via custom geotiff etc.

How can we mount custom terrain data into MP? I have a GeoTIFF file with 10-meter resolution but cannot proceed further.

**Pull request merged**
