### PR TITLE
Moved from using new to new(std::nothrow)

### PR DESCRIPTION
**Pull request by tridge**
Unfortunately clang++ accepts -fcheck-new on the command line but does not implement it, which means our strategy of relying on -fcheck-new to avoid the problem of elided code for nullptr checks does not work on any build using clang++.

This switches us to use a NEW_NOTHROW macro instead for new, and adds link checks to ensure we don't miss any cases

See also https://github.com/ArduPilot/ardupilot/pull/22614 and #22615 

Note that we could avoid the NEW_NOTHROW macro and use new(std::nothrow) directly, it is largely a matter of taste.
One advantage of directly using new(std::nothrow) is it may display better in C++ editors

UPDATE: this now maps NEW_NOTHROW to new on ChibiOS, and maps it to new(std::nothrow) on other HALs. This avoids the extra flash on ChibiOS where -fcheck-new works

### CODE REVIEW

**Comment by amilcarlucas** [comment]
```
Binary Name      Text [B]         Data [B]     BSS (B)        Total Flash Change [B] (%)      Flash Free After PR (B)
---------------  ---------------  -----------  -------------  ----------------------------  -------------------------
ardusub          1908 (+0.1210%)  0 (0.0000%)  -4 (-0.0015%)  1908 (+0.1208%)                                  384556
antennatracker   1404 (+0.1057%)  0 (0.0000%)  -4 (-0.0015%)  1404 (+0.1055%)                                  633752
ardurover        2012 (+0.1228%)  0 (0.0000%)  4 (+0.0015%)   2012 (+0.1226%)                                  322784
arduplane        1984 (+0.1113%)  0 (0.0000%)  0 (0.0000%)    1984 (+0.1111%)                                  178004
arducopter-heli  2032 (+0.1134%)  0 (0.0000%)  0 (0.0000%)    2032 (+0.1132%)                                  168884
blimp            1424 (+0.1053%)  0 (0.0000%)  0 (0.0000%)    1424 (+0.1052%)                                  610532
arducopter       2028 (+0.1136%)  0 (0.0000%)  -4 (-0.0015%)  2028 (+0.1134%)                                  175276
```

Is the size change expected?

**Comment by tridge** [comment]
> Is the size change expected?

no, I'll look into it

**Comment by tridge** [comment]
@amilcarlucas it seems the compiler does a better job optimising when we use new(std::nothrow). I don't know why. The result is the same regardless of whether we use -fcheck-new or not

**Comment by tridge** [comment]
@amilcarlucas it is weird, the CI test shows the PR costing flash, but when I run the same builds locally (eg. for Durandal) I get a significant reduction in flash usage.
Here is master (hash a1971bb5b7) on Durandal:
```
Build directory: /data/APM/build/Durandal
Target          Text (B)  Data (B)  BSS (B)  Total Flash Used (B)  Free Flash (B)  External Flash Used (B)
----------------------------------------------------------------------------------------------------------
bin/arducopter   1790040      4008   258280               1794048          172020  Not Applicable
```
and here is this PR:
```
Build directory: /data/APM.36/build/Durandal
Target          Text (B)  Data (B)  BSS (B)  Total Flash Used (B)  Free Flash (B)  External Flash Used (B)
----------------------------------------------------------------------------------------------------------
bin/arducopter   1786836      4008   258284               1790844          175220  Not Applicable
```

**Comment by tridge** [comment]
in CI, I see this for master: ```
BUILD SUMMARY
Build directory: /__w/ardupilot/ardupilot/base_branch/build/Durandal
Target               Text (B)  Data (B)  BSS (B)  Total Flash Used (B)  Free Flash (B)  External Flash Used (B)
---------------------------------------------------------------------------------------------------------------
bin/antennatracker    1328732      2180   260100               1330912          635152  Not Applicable         
bin/arducopter        1784756      4008   258284               1788764          177300  Not Applicable         
bin/arducopter-heli   1791144      4008   258280               1795152          170916  Not Applicable         
bin/arduplane         1782156      3920   258356               1786076          179988  Not Applicable         
bin/ardusub           1576980      2628   259652               1579608          386460  Not Applicable         
bin/blimp             1351928      2196   260072               1354124          611956  Not Applicable         
bin/ardurover         1638640      2628   259648               1641268          324800  Not Applicable         
```
and this for the PR:
```
BUILD SUMMARY
Build directory: /__w/ardupilot/ardupilot/pr/build/Durandal
Target               Text (B)  Data (B)  BSS (B)  Total Flash Used (B)  Free Flash (B)  External Flash Used (B)
---------------------------------------------------------------------------------------------------------------
bin/antennatracker    1330136      2180   260096               1332316          633752  Not Applicable         
bin/arducopter        1786784      4008   258280               1790792          175276  Not Applicable         
bin/arducopter-heli   1793176      4008   258280               1797184          168884  Not Applicable         
bin/arduplane         1784140      3920   258356               1788060          178004  Not Applicable         
bin/ardusub           1578888      2628   259648               1581516          384556  Not Applicable         
bin/blimp             1353352      2196   260072               1355548          610532  Not Applicable         
bin/ardurover         1640652      2628   259652               1643280          322784  Not Applicable         
```

Looking at copter, the size for the PR matches my local build, but the size for master doesn't. 
ahh, it depends on what directory I build in. Starting in a new directory I match the CI test

**Comment by tpwrules** [comment]
According to the GCC docs it should be sufficient to mark the `new` operator implementation as `noexcept`?

**Comment by tpwrules** [comment]
Is it time to make our own named malloc/new functions if we are having to use a macro here? Placement new could be used to place in allocated storage; delete would need to be changed.

There are a few other problems which could come back to bite us I've observed:
* `malloc`'s contents are defined to be unspecified, not 0. The compiler could do funky things with reads to data returned from malloc. Allegedly clang does this.
* It's undefined to allocate with new and pass to free, or allocate with malloc and pass to delete. But the existing code does this.

**Comment by tpwrules** [comment]
Added at the top of `AP_GPS.cpp` and replaced the functions within appropriately:
```c++
#define CONSTRUCT(T, ...) \
    ({ T* t = (T*)malloc(sizeof(T)); if (t) { new (t) T(__VA_ARGS__); }; t; })

template<class T> void DESTRUCT(T* p) { if(p) { p->~T(); } free(p); }
```

Using just `CONSTRUCT` adds 0 bytes on CubeOrangePlus, using DESTRUCT adds 8 bytes. This compares to 40 additional bytes using `new (std::nothrow)`.

The syntax is even uglier but it reinforces that something is going on and lets us safely do stuff like zero the underlying memory.

**Comment by tridge** [comment]
this has been updated to make NEW_NOTHROW map to new on ChibiOS by default. You can make it map to NEW_NOTHROW by configuring with --enable-new-checking, which allows CI to check for new violations

**Comment by tridge** [comment]
@tpwrules I can see how CONSTRUCT would work, but I decided to go with just leaving NEW_NOTHROW as new on ChibiOS, relying on gcc support for -fcheck-new, and using the C++ standard of new(std::nothrow) elsewhere

**Review by peterbarker — APPROVED** [review]
LGTM

**Pull request merged**
