### PR TITLE
Port SITL to OpenBSD

### PR DESCRIPTION
**Pull request by rsaxvc**

### CODE REVIEW

**Comment by Ryanf55** [comment]
Neat! Do you know if there is an OpenBSD docker image that we could use to test these changes in CI with?

**Comment by rsaxvc** [comment]
I don't know. There is a docker image that contains qemu(https://containerlab.dev/manual/kinds/openbsd/) that contains OpenBSD. Though if I'm the only person using it, I'd be ok without a CI build.

**Comment by rsaxvc** [comment]
SITL runs on OpenBSD.

**Review by peterbarker — APPROVED** [review]
LGTM.

**Comment by peterbarker** [comment]
Merged, thanks!

**Comment by rsaxvc** [comment]
Thanks Peter!

**Pull request merged**
