### PR TITLE
FETtecOneWire support on top of AP_ESC_Telem backend

### PR DESCRIPTION
**Pull request by amilcarlucas**
This one is based on top of #16725 with https://github.com/andyp1per/ardupilot/pull/14 on top of it.

requires #16725

It uses a very different approach from my other FETtec PR (#14678) . #14678 has been flight tested, this one is still wip.

- [x] feature complete:
- control motor speed
- copy ESC telemetry data into MAVLink telemetry
- save ESC telemetry data in Dataflash logs
- use RPM telemetry for dynamic notch filter frequencies
- sum the current telemetry info from all ESCs and use it as virtual battery current monitor sensor
- average the voltage telemetry info and use it as virtual battery voltage monitor sensor
- [x] passes CI
- [x] [addressed all TODOs](https://ardupilot.org/dev/docs/editing-prs.html) in the code:
- https://github.com/ArduPilot/ardupilot/pull/16850/files#diff-e4e0df6b1a14c8042ee98aa009d835584310eb2b116051b83a8c6813fa756a5eR69
- https://github.com/ArduPilot/ardupilot/pull/16850/files#diff-224165226fc822e0d28dc499f19997946ec00db384651687ed5f4e4cc0f2d8d3R144
- [ ] flight tested with a Hex frame using the last 6 channels (FETtec ID 7 to 12) 1 to 6 are unused/unassigned
- [ ] mavlink telemetry works (analyzed a TLOG to see that [ESC_TELEMETRY_1_TO_4](https://mavlink.io/en/messages/ardupilotmega.html#ESC_TELEMETRY_1_TO_4) and [ESC_TELEMETRY_5_TO_8](https://mavlink.io/en/messages/ardupilotmega.html#ESC_TELEMETRY_5_TO_8) messages are present or that [ESC_TELEMETRY_5_TO_8](https://mavlink.io/en/messages/ardupilotmega.html#ESC_TELEMETRY_5_TO_8) and [ESC_TELEMETRY_9_TO_12](https://mavlink.io/en/messages/ardupilotmega.html#ESC_TELEMETRY_9_TO_12) messages are present and their contents correct)
- [ ] dataflash logs have ESC telemetry data in ESC7..12
- [x] flight tested with a Hex frame using the first 6 channels (FETtec ID 1 to 6)
- [ ] mavlink telemetry works (analyzed a TLOG to see that [ESC_TELEMETRY_1_TO_4](https://mavlink.io/en/messages/ardupilotmega.html#ESC_TELEMETRY_1_TO_4) and [ESC_TELEMETRY_5_TO_8](https://mavlink.io/en/messages/ardupilotmega.html#ESC_TELEMETRY_5_TO_8) messages are present and their contents correct)
- [x] dataflash logs have ESC telemetry data in ESC1..6
- [ ] six independent [notch filters](https://ardupilot.org/copter/docs/common-imu-notch-filtering.html) work (used a hex for testing) 
- INS_HNTCH_ENABLE = 1,
- [INS_HNTCH_MODE](https://ardupilot.org/copter/docs/parameters.html#ins-hntch-mode-harmonic-notch-filter-dynamic-frequency-tracking-mode) = 3 (ESC telemetry),
- [INS_HNTCH_OPTS](https://ardupilot.org/copter/docs/parameters.html#ins-hntch-opts-harmonic-notch-filter-options) = 2 (dynamic notch)
- [INS_HNTCH_REF](https://ardupilot.org/copter/docs/parameters.html#ins-hntch-ref) = 1
- [ ] [IMU noise levels](https://ardupilot.org/copter/docs/common-imu-fft.html) measured before [notch filtering](https://ardupilot.org/copter/docs/common-imu-notch-filtering.html)
- [INS_LOG_BAT_MASK](https://ardupilot.org/copter/docs/parameters.html#ins-log-bat-mask) = 1
- [INS_LOG_BAT_OPT](https://ardupilot.org/copter/docs/parameters.html#ins-log-bat-opt-batch-logging-options-mask) = 0
- @teezeefpv please add a  [MissionPlanner FFT picture](https://ardupilot.org/planner/docs/common-measuring-vibration.html) here like described in the [noise analysis page](https://ardupilot.org/copter/docs/common-imu-batchsampling.html)
- [ ] [IMU noise levels](https://ardupilot.org/copter/docs/common-imu-fft.html) measured after [notch filtering](https://ardupilot.org/copter/docs/common-imu-notch-filtering.html)
- [INS_LOG_BAT_OPT](https://ardupilot.org/copter/docs/parameters.html#ins-log-bat-opt-batch-logging-options-mask) = 2
- @teezeefpv please add a [MissionPlanner FFT picture](https://ardupilot.org/planner/docs/common-measuring-vibration.html) here like described in the [noise analysis page](https://ardupilot.org/copter/docs/common-imu-batchsampling.html)
- [x] voltage and current measurements replace the need for power monitoring hardware:
- [BATT_MONITOR](https://ardupilot.org/copter/docs/parameters.html#batt-monitor-battery-monitoring) = 9 (BLHeli ESC)
- [ ] protocol is documented in the README.md file in the same location as the .cpp implementation file
- [ ] [configuration instructions](/ArduPilot/ardupilot_wiki/pull/3335) are on the ardupilot wiki

@khancyr @Linjieqiang can you help us test this?

Compared to master this PR needs just 480 bytes for ArduCopter on a Durandal flight controller :)

I also [backported most of this to ArduCopter-4.0.7](https://github.com/ArduPilot/ardupilot/pull/16874)

### CODE REVIEW

**Comment by Linjieqiang** [comment]
Nice. I will continue to follow this PR. 
@amilcarlucas

**Comment by amilcarlucas** [comment]
Test flown today. The logs are https://drive.google.com/drive/folders/1SqI3lxSBH7zLx__rvviwBe3Lg6_uzKX0

**Comment by andyp1per** [comment]
@amilcarlucas - nice - I can see the RPM clearly, although 300rpm seems way too low unless this was an enormous copter? Also the notch wasn't active because the configured frequency (80Hz) was way above the rotor frequency (5Hz!)

**Comment by amilcarlucas** [comment]
@andyp1per This was a small Hexa :( 

On the .bin file:
1. I guess the number of poles is not set correctly. SERVO_BLH_POLES = 14
2. Looking closely there are some 60V voltage spikes that do not belong there
3. the average current per motor is 2,5A, seams a bit low
4. the temperature needs to be multiplied by 100
5. cTot is missing units

The .log files are useless, they should have been .tlog files, so I can not test mavlink telemetry.
@teezeefpv please upload .tlog files.

**Comment by amilcarlucas** [comment]
@andyp1per can you take a look at why the CI test is failing?

**Comment by andyp1per** [comment]
@amilcarlucas you must have broken harmonic notch support since that test is now failing

**Comment by amilcarlucas** [comment]
commit 34cdc84 reduced the FW size from 488 bytes to 416 bytes

**Comment by amilcarlucas** [comment]
Test flown today. The logs are https://drive.google.com/drive/folders/1SqI3lxSBH7zLx__rvviwBe3Lg6_uzKX0 in the 18-Mach folder
But the .log file does not seam to be from the correct day and contains no flight, just sitting on the ground :(
The .bin file shows that the temperature is now correct

**Pull request closed without merging**
