### PR TITLE
Rename RangeFinder.h to AP_RangeFinder.h (and friends)

### PR DESCRIPTION
**Pull request by peterbarker**
I always end up opening `AP_RangeFinder/AP_RangeFinder.h`, get annoyed and open the correct one...

### CODE REVIEW

**Comment by WickedShell** [comment]
+1 I get bitten by this a lot.

**Comment by lucasdemarchi** [comment]
+1

Now can you also take care of `s/Compass/AP_Compass/` please? :)

**Comment by rmackay9** [comment]
Merged, thanks!

**Comment by peterbarker** [comment]
On Mon, 11 Nov 2019, Lucas De Marchi wrote:

> Now can you also take care of s/Compass/AP_Compass/ please? :)

That's actually a different problem, and one that I haven't actually 
addressed for RangeFinder in this PR!

Changing our compass stuff from "class Compass" to "class AP_Compass", 
and "class RangeFinder" to "class AP_RangeFinder" would make these 
consistent with most of our libraries (but there's still SRV_Channel!).

OTOH, it's previously been suggested we could move to a proper C++ 
namespace, so AP_Barometer becomes AP::Barometer instead.

It might not be the best of changes to fix Compass and RangeFinder if 
we'll go with AP:: at some stage anyway.

**Comment by lucasdemarchi** [comment]
> That's actually a different problem, and one that I haven't actually addressed for RangeFinder in this PR!

I know, just trying to give you ideas for improvements :)

>  Changing our compass stuff from "class Compass" to "class AP_Compass", and "class RangeFinder" to "class AP_RangeFinder" would make these consistent with most of our libraries (but there's still SRV_Channel!). OTOH, it's previously been suggested we could move to a proper C++ namespace, so AP_Barometer becomes AP::Barometer instead. It might not be the best of changes to fix Compass and RangeFinder if we'll go with AP:: at some stage anyway.

Indeed. I don't mind much either way... I would slightly prefer AP::, but it's a very intrusive change. What bothers me the most is the inconsistency.

**Pull request merged**
