### PR TITLE
OpenPilot Revo Mini HAL v3

### PR DESCRIPTION
**Pull request by night-ghost**
new version of (#3834), including last work of scenkov (not in https://github.com/scenkov/ardurevo):

```
2 i2c buses
better analog layer
samples and tests for HAL
```

added build targets

```
revomini-upload
revomini-debug
revomini-jtag-program
revomini-clean
```

added support of CCM memory (not tested)

build flags changed to ones from px4*.mk

it successfully compiles in https://github.com/ArduPilot/ardupilot/tree/cc24f323d25439661429d9afe52cc41ab46741d1 for targets revomini and px4-v2 with gcc-arm-none-eabi-5_2-2015q4

from ld:
Final Size:
text data bss dec hex filename
597900 11768 18164 627832 99478 /tmp/ArduCopter.build/ArduCopter.elf

It has not yet been tested in flight

PS. OpenPilot Revomini costs near $25 when the cheapest Pixhawk (lite) around $60, this is a significant difference, especially for some countries

### CODE REVIEW

**Comment by kwikius** [comment]
Thought this might be of interest

http://www.rcgroups.com/forums/showthread.php?t=2634785

regards
Andy

**Comment by night-ghost** [comment]
RevoMini weight is 6g with case and stm32f4 works on full speed and uses well-tested MPU6000. Not to mention the fact that the RevoMini is much cheaper and it sold almost everywhere :)

**Comment by lolorc** [comment]
Hi, I own a revo mini and several quanton, I'm very happy to see this PR and I'm looking forward to try it.
Thanks a lot for doing this !

**Comment by night-ghost** [comment]
To compile this at f579c3e6ebc3531e8fa778cba44eefe02db13dec commit should be used small patch, which also fixes some internal issues and change HAL from 'uintXX' types to conventional  'uintXX_t' types

[build.patch.zip](https://github.com/ArduPilot/ardupilot/files/363489/build.patch.zip)

**Comment by anbello** [comment]
Once completed will also be possible to use it with openpilot revo "normal" (non mini)?

**Comment by night-ghost** [comment]
> will also be possible to use it with openpilot revo "normal" (non mini)?

Yes of course! Mini differs only in the absence of the RF module.

**Comment by anbello** [comment]
@night-ghost 
Thanks. Will also be possible to use the oplink RF module for telemetry?

**Comment by night-ghost** [comment]
Sorry but no, support for the  native RF module is not planned. Use small 3dr modem like [this](https://ru.aliexpress.com/item/3DRobotics-3DR-Radio-433-Ground-Module-Telemtry-Mini-433Mhz-433-Telemetry-Air-Module-Kit-for-APM2/32518223634.html)

**Comment by lolorc** [comment]
Hi there, 

What is the current status of this PR ?
I'd love to help and try this port.
TIA

**Comment by night-ghost** [comment]
> What is the current status of this PR ?

active debugging for recent version of Ardupilot

**Comment by night-ghost** [comment]
Now it works on ground - can successfully connect to MP, test motors, calibrate radio and sensors. 

But to do that I had to rewrite a half of the code. So now works even USB, which was not worked in the original version.

Also fixed a lot of bad complicated decisions in favor to be simple and understandable.

Known issues:
1. when you restart Fc with connected USB port MP gives an error, you need to remove and insert the connector.
2. No support for Oneshot mode

Unfortunately, now I can't check it in the air.

If anyone interested I can do a PR with the result.

**Comment by night-ghost** [comment]
Also ported and slightly altered bootloader to support flashing and start firmware automatically at addresses 8010000 and 8020000 (2 low 16k flash pages are used to emulate EEPROM).

**Comment by tridge** [comment]
if I wanted to buy one of these boards for testing the port, where would you recommend I get one? I'd like it to be the same as the one you have for maximum reproducibility

**Comment by night-ghost** [comment]
I use [Revolution Mini](https://ru.aliexpress.com/item/F17008-Openpilot-CC3D-DIY-FPV-Drone-Nano/32671154881.html) because of its weight of 4 grams but it is too small and inconvenient for debugging and installation. so I would recommend the usual [Revoluton](https://ru.aliexpress.com/item/Openpilot-New-version-CC3D-Revolution-Flight-Controller-Upgrade-Version-Integrating-OPLinK-Revo/32462718293.html), it is more convenient, and all the difference is only in the absence of the radiomodem on board. It also has SWD port already. By reviews Betaflight works on them the same way.

**Comment by night-ghost** [comment]
latest news: 
* external I2C bus moved out from FlexiPort by Soft_I2C driver so we always has 3 UARTs
* added 1 full-functional UART (only for quads) and 1 RX-only UART for satellite receiver on OpLink connector
* added buzzer support
* stack now in CCM memory
* a lot of minor enhancements

**Comment by anbello** [comment]
@night-ghost I bought an openpilot revo mini and I would like to try this version of arducopter, is it possible to try it without the need to recompile it by myself? Have you ever tried it in flight?
Thanks

**Comment by night-ghost** [comment]
Please wait for some time, now I got the receiver for it so can to continue debugging. Feel free to ask questions [here](https://www.rcgroups.com/forums/showthread.php?2784349-Ardupilot-on-OpenPilot-Revolution#post36312107)

**Comment by night-ghost** [comment]
Wow! Now it flies! binaries are [here](https://github.com/night-ghost/ardupilot/blob/master/latest.zip)

**Comment by rmackay9** [comment]
Congrats @night-ghost!

**Comment by night-ghost** [comment]
Thanks! BTW, it fits to 1MByte even with EKF3 and -Og optimization

**Comment by anbello** [comment]
Thanks @night-ghost 
Flashed on my RevoMini and it's all OK on APM Planner 2 Flight Display, compass, accelerometer and RC calibration. I have not yet found the time to test it in flight. I will do asap.

**Comment by peterbarker** [comment]
@night-ghost Do you have a branch which can be checked out?  Somehow I'm getting "unknown repository" on this pull request.

**Comment by night-ghost** [comment]
>Do you have a branch which can be checked out?

Yes, [of course!](https://github.com/night-ghost/ardupilot)

**Comment by night-ghost** [comment]
Seems to be rather good now. There is one still not catched yet bug which requires to turn off optimization in some parts of code but now it's done by #pragmas

**Comment by night-ghost** [comment]
latest news:

* micros() call uses 32-bit hardware timer instead of systick_micros()
* added translation layer between system PWM_MODES and board's PWM_MODES
* added initial support for DMA
* added support for all timers
* supported reboot to DFU mode (via "reboot to PX4 bootloader" in MP)
* after any Fault or Panic() automatically reboots to DFU mode
* diversity on RC_Input
* unified exception handling
* added ability to bind Spectrum satellite without managed 3.3 DC-DC (requires short power off)
* added support for Arduino32 reset sequence - negative DTR edge on 1200 baud or '1eaf' packet with high DTR
* fixed hang on dataflash malfunction
* fixed USB characters loss *without* hangup if disconnected
* added failsafe on receiver's hangup - if no one channel changes in 60 seconds
* changed to simplify support of slightly different boards - eg. AirbotF4

**Comment by auturgy** [comment]
Is this progressing?  Could be an awesome way to open ArduPilot up to new users.

**Comment by night-ghost** [comment]
Watch the news [here](https://www.rcgroups.com/forums/showthread.php?2784349-Ardupilot-on-OpenPilot-Revolution/page50#post38059447) and full info in 1st post

**Comment by lucasdemarchi** [comment]
And will you update this PR with the latest version you have?

**Comment by auturgy** [comment]
Thanks NG.
That's a huge amount of work: you should blog it on discuss.ardupilot.org or do a wiki page!

**Comment by tridge** [comment]
@night-ghost just wanted to let you know that James Pattison just dropped into my place and gave me a RevoMini to play with!
I've been trying to build your branch. No luck yet, but I'll have another go

**Comment by tridge** [comment]
using the pre-build 3.8.1-dev plane binaries, I set SCHED_DEBUG=1 and noticed a lot of large scheduling errors. This is with plane at 400Hz:
APM: PERF: 168/2000 Dt=969240/1214 Log=0
APM: PERF: 158/2000 Dt=961884/1597 Log=0
APM: PERF: 179/2000 Dt=22139/1392 Log=0
APM: PERF: 169/2000 Dt=26592/1543 Log=0
APM: PERF: 178/2000 Dt=26584/1427 Log=0
APM: PERF: 199/2004 Dt=38687/1042 Log=0
APM: PERF: 159/2000 Dt=24391/1440 Log=0

that shows loops sometimes taking nearly a second. Longest I've seen is 4.8s for one loop (should be under 3ms).

Any idea where the scheduling jitter is coming from? Maybe it only happens on USB?

**Comment by night-ghost** [comment]
There is a bug comes with latest commit which cause no RC input. I'll fix it next week. And will try to fix scheduler issue

**Comment by magicrub** [comment]
Thanks @night-ghost !

**Comment by anbello** [comment]
@tridge I was able to build the @night-ghost fork using his instructions (on the RC Groups thread)

> download code from original Ardupilot

```
git clone https://github.com/ArduPilot/ardupilot.git
cd ardupilot
git submodule update --init --recursive
```

> go to Arduplane folder and say:

```
make px4-v2
```

> after successful build download my sources and then move ".git" and "modules" folders from official to my sources. Then go to Arduplane folder in my sources and say:

`make revomini`

I did the same for ArduCopter and worked.

**Comment by auturgy** [comment]
Can someone post a link to target with an SD card?

Regards,

James

**Comment by tridge** [comment]
I suspect it depends on an exact compiler version. @night-ghost, what compiler version are you using?

**Comment by anbello** [comment]
I don't know which version use @night-ghost anyway I used this:
gcc version 4.9.3 20150529 (release) [ARM/embedded-4_9-branch revision 227977] (GNU Tools for ARM Embedded Processors)
I obtained some error messages here and there, but with a little knowledge of C / C++ (I am not an expert) can be fixed and I obtained a working bin.

**Comment by night-ghost** [comment]
> I suspect it depends on an exact compiler version

wrong, it works with both GCC 4.9.3 and GCC 5.4.1 which I use. And sometimes I check how it works if built by GCC 4.8.3 and 5.2

>I obtained some error messages here and there

what and where? I tried to remove all compilation warnings, not only errors!

>Can someone post a link to target with an SD card?

AirbotV2

PS. RC_input is reverted to working state

**Comment by auturgy** [comment]
@night-ghost can you confirm that this is the one:
https://store.myairbot.com/flight-controller/omnibus-f4-pro-v2.html

Regards,

James

**Comment by night-ghost** [comment]
>can you confirm that this is the one

yes AirbotV2 target is for this board.

**Comment by anbello** [comment]
> > I obtained some error messages here and there

> what and where? I tried to remove all compilation warnings, not only errors!

Little error related to things that gcc 5.4 can do and 4.9 cannot like declaring var in for loop, easy solvable.

**Comment by night-ghost** [comment]
>Little error related to things that gcc 5.4 can do and 4.9 cannot

thanks, fixed. Now successfully compiles with 4.8.3

**Comment by tridge** [comment]
btw, supporting the oplink may be possible. I have implemented cyrf6936 support in ArduPilot here:
https://github.com/tridge/ardupilot/tree/skyviper-wip/libraries/AP_Radio
I don't know what chipset oplink uses, but supporting a different chipset may not be a lot of work

**Comment by tridge** [comment]
got the build working now - just a couple of minor fixes needed (like AP_WayBack being a symlink)
next step, working out how to get a revomini into dfu mode - I guess I need to add "reboot to bootloader" command in mavproxy

**Comment by anbello** [comment]
First time to get DFU mode you have to short BL pads while plugging USB, next times you can use Mavproxy:

$ mavproxy.py --master=/dev/ttyACM0 --baud=115200 --console

then:
STABILIZE> long MAV_CMD_PREFLIGHT_REBOOT_SHUTDOWN 3 0 0 0 0 0 0

then you see:
STABILIZE> Device /dev/ttyACM0 is dead

then you can use dfu-util to flash the revolution

**Comment by tridge** [comment]
@anbello thanks!
got dfu to flash it ok:
```
dfuIDLE, continuing
DFU mode device DFU version 011a
Device returned transfer size 2048
DfuSe interface name: "Internal Flash  "
Downloading to address = 0x08010000, size = 840092
Download        [=========================] 100%       840092 bytes
Download done.
File downloaded successfully
```
unfortunately after flashing it doesn't come up on USB. I guess I will need the bl pads. Do you have a link to the pinout showing where the bl pads are?

**Comment by tridge** [comment]
looks like this is it:
http://drone.hjns.net/wp-content/uploads/2016/11/cc3d-mini-revo-sbl.png

**Comment by tridge** [comment]
yep, with the above SBL pins shorted DFU works. Still no luck loading a working fw though. What the recommended debug setup for this board? Are there jtag pins? Or a debug console somewhere?

**Comment by anbello** [comment]
For debug info better ask to @night_ghost but if you flash last bin with dfu then at next reboot (without BL shorted) you should see a tty device (on linux /dev/ttyACM0) and use MissionPlanner or APM Planner (I use this on linux) to see the Revo and configure it.

**Comment by night-ghost** [comment]
it's too early, I have not yet catch an incomprehensible issue of scheduler

**Comment by night-ghost** [comment]
> What the recommended debug setup for this board? Are there jtag pins? Or a debug console somewhere?

I use SWD debug via st-link and there is debug console on main port (mixed with MAVlink)

**Comment by anbello** [comment]
> it's too early, I have not yet catch an incomprehensible issue of scheduler

Is this true for all the target or only for revomini?
I ask because yesterday I flight with my AirbotF4 and last commit and seemed all OK: AltHold, PosHold and Circle.

**Comment by night-ghost** [comment]
for all targets. Sometimes delay_us(100) cause delay for ~4000uS because task switcher for some unknown reason executes other tasks. But this bug does not lead to any negative consequences, page erase took 0.3s but don't spoil flight

**Comment by night-ghost** [comment]
seems that I catch it

**Comment by anbello** [comment]
> seems that I catch it

Good!

On other front: I had to comment the line `if(usart_is_used(_usart_device)) return;` in file "libraries/AP_HAL_REVOMINI/UARTDriver.cpp" from commit 3152214 otherwise telemetry on UART1 does not works, but it's OK only for me because I don't use SBUS.
```
#ifdef BOARD_SBUS_UART1
//    if(_initialized && _usart_device==_USART1 && hal_param_helper->_uart1_sbus) return; //already used as SBUS
//    if(usart_is_used(_usart_device)) return;
#endif
```

**Comment by night-ghost** [comment]
"usart_is_used" is deleted now because it is NORMAL to Ardupilot to open one USART many times. So only manual check for confilct with SBUS

**Comment by anbello** [comment]
I don't understand fully, what you say mean that the line I commented out is anyway unneeded?

**Comment by night-ghost** [comment]
yes bug catched. I2C reads from external compass tooks a lot of time so there is calls to yield() for byte time, but yield() with low times (<5uS) don't cause task switch - so ALL registers reads in one timeslice which took ~2500uS. Now any calls to yield() from IO tasks cause task switch

**Comment by night-ghost** [comment]
>what you say mean that the line I commented out is anyway unneeded?
because soft creates many drivers for one USART so begin() called many times

**Comment by tridge** [comment]
@night-ghost I'm curious what results you can get with SCHED_DEBUG=1 now that you've added the yield calls on io?
I also wanted to mention a separate effort which should result in a port to the revo mini, based around ChibiOS. @bugobliterator has been working on a ChibiOS port of ArduPilot, initially targetting the STM32F412 and the STM32F427. It is going really well, and we got a first flight done yesterday. See:
https://discuss.ardupilot.org/t/chibios-port-of-apm/20491
chibios is extremely light weight, but also very efficient. We're getting firmwares about half the size of the current NuttX based firmware, and the cpu load is about 50% of the nuttx CPU load for the same board. The scheduling consistency is also excellent. Here is the SCHED_DEBUG=1 output on a PH2.1 board with 3 IMUs, 2 baros and 2 compasses:
APM: PERF: 0/4000 max=2829 min=2171 avg=2500 sd=91
APM: PERF: 0/4000 max=2830 min=2171 avg=2499 sd=90
APM: PERF: 0/4000 max=2836 min=2164 avg=2499 sd=90
APM: PERF: 0/4000 max=2840 min=2121 avg=2500 sd=92
as you can see, zero scheduling misses and extremely low standard deviation in timing. It is early days, but if you are interested in helping with the chibios port to the revo mini then you would be welcome.

**Comment by night-ghost** [comment]
Yes that issue is almost solved, it was caused by EEPROM emulation driver which requires to search in 16KB array to read one byte. Unfortunately, this can not be avoided on such boards, and we can only reduce the impact of this time on other tasks, but not on the cycle time.

Yes, I have already seen that project, but still prefer to do without any OS, because forced context switch is about 50 times more expensive than voluntary one. My digits:

delay times: in main 72.05% including in semaphore  0.11%  in timer  0.00%
max delay() error= 378
MPU overflows: 0 restarts 0

so my cooperative scheduler works with quant ~400uS and takes ~0.1 uS to switch tasks, and full CPU load is only ~28%. With only one onboard IMU, yes :)

If I ever change my mind and will start to use an OS, then it will be a FreeRTOS, not Chibi

And yes, it flies :) https://vimeo.com/232566937

**Comment by tridge** [comment]
> Unfortunately, this can not be avoided on such boards, and we can only reduce the impact of this time on other tasks, but not on the cycle time.

the impact can be avoided. For the ChibiOS port we use two sectors, and a low priority IO thread that uses a log structure in those sectors to give reliable storage. See the AP_FlashStorage library in master. It uses two sectors so that it can swap sectors without any race conditiion that could cause data loss when it has to erase a sector. Sector erase can take a long time, so it defers it till you are disarmed.

> delay times: in main 72.05% including in semaphore 0.11% in timer 0.00%
> max delay() error= 378

can you try arducopter master with SCHED_DEBUG=1 and get the console output? That will allow direct comparison at 400Hz loop rates.

**Comment by night-ghost** [comment]
>the impact can be avoided

that solution leads to data loss in case of unexpected power failure, for example, when crash with battery disconnect. Page erase time is near 0.3 second and not cause any problems indeed even on 250 copter. Moreover 427 stone has 2 banks and can write upper one while program works in lower so Pixhawk family isn't affected.

btw, I now don't use buggy MPU's FIFO an read data by DataReady interrupt so it don't loose any gyro's data portion.

logs for SCHED_DEBUG=1 will be some time later

**Comment by tridge** [comment]
> that solution leads to data loss in case of unexpected power failure, for example, when crash with battery disconnect.

It deals with power off at any time and doesn't corrupt the data on power loss. I tested that case rather extensively. Did you read through AP_FlashStorage, or are you basing that on some other system?

> I now don't use buggy MPU's FIFO

what FIFO bug are you referring to?

> logs for SCHED_DEBUG=1 will be some time later

thanks!

**Comment by night-ghost** [comment]
deferred data in RAM will be lost, isn't it? :) Yes I read AP_FlashStorage but my EEPROM driver was written much earlier, it uses 2 pages too and don't corrupt data even in case of arbitrary power offs, tested on stand with arduino's controlled power relay. More interesting would be a solution that allows you to use an arbitrary number of pages, but so far this has not come across.

>what FIFO bug are you referring to?

the bug which requires co check validity of data by temperature, see AP_InertialSensor_Invensense.cpp  lines 619 and 700. I often seen "temp reset" in console before, when ALL content of FIFO discarded, loosing valuable gyro's data

**Comment by night-ghost** [comment]
Caching of emulated EEPROM data greatly improved performance:

delay times: in main 79.07% including in semaphore  0.03%  in timer  0.00%
max delay() error= 392uS

sleep time 75.23350%
task 0 (0x80AAED5) times: full  37966.7ms (  12.25%) mean      8.7uS max 2492uS at 80AAE21 error 0
task 1 (0x80AAEE920004A94) times: full      0.0ms (   0.00%) mean      1.5uS max 2uS at 80ABE91 error 89
task 2 (0x80AC60320004B08) times: full   1458.4ms (   0.47%) mean      3.3uS max 93uS at 80ABD65 error 255
task 3 (0x804A21D20007D60) times: full    673.6ms (   0.21%) mean      1.9uS max 87uS at 80ABE91 error 250
task 4 (0x80ABDAD) times: full   9798.8ms (   3.16%) mean      2.2uS max 106uS at 80ABE91 error 0
task 5 (0x8054BB920007F50) times: full  17504.9ms (   5.65% - [!!was 24%] mean      4.9uS max 114uS at 80AAE49 error 42

so now CPU load is only 21%

**Comment by tridge** [comment]
>  I often seen "temp reset" in console before, when ALL content of FIFO discarded, loosing valuable gyro's data

did you check the timing when that happened? It should only happen if the FIFO read is delayed by 20ms, allowing the FIFO to fill. Perhaps there were some long running operations that prevented the 1kHz reads from happening?

**Comment by night-ghost** [comment]
>did you check the timing when that happened?

reads was in rather high-priority timer's interrupt so nothing could prevent reads, but resets occures periodically (not often), sometimes even at 1st item - I rewrote this as "debug("temp reset %d %d i=%d", _raw_temp, t2, i);" to see the point when it happens. 

This was on AirbotV1 board which has common 3.3 power for STM and MPU so it may be a sort of interference.

Reads in ISR without FIFO fixed it.

**Comment by night-ghost** [comment]
logs for SCHED_DEBUG=1

PERF: 155/4000 max=5684 min=678 avg=2514 sd=264
PERF: 160/4000 max=4528 min=877 avg=2511 sd=238

Yes there is no preemption between tasks so long period between calls to HAL still spoils loop time

**Comment by tridge** [comment]
> PERF: 155/4000 max=5684 min=678 avg=2514 sd=264
> PERF: 160/4000 max=4528 min=877 avg=2511 sd=238
> Yes there is no preemption between tasks so long period between calls to HAL still spoils loop time

yep, I thought that might be the case. It would work OK for most fixed wing aircraft, but would fly badly in a quadcopter. It would fly (I've certainly seen plenty of logs for quads with worse scheduling than that), but it won't be as smooth and won't have the same level of disturbance rejection as you get with good consistent scheduling.

> but resets occures periodically (not often), sometimes even at 1st item

it happening as the first item isn't really surprising as the FIFO isn't in sync yet and there can be a delay between the sensor being initialised and the first read. If that pause is 20ms or more then you expect to get exactly this message. 

If it is happening regularly then that means the scheduling is not accurate enough. 

> Reads in ISR without FIFO fixed it.

well, for some value of "fixed" :-)

reading in the ISR prevents us from doing bus parallelism, so you can't overlap the i2c read of a compass with the read of an IMU, and doesn't scale to more than one IMU. It also only works well on boards with a hardware data-ready line (which many boards don't have), and doesn't work at all once you use a more modern IMU that can read the gyro data at 8kHz (such as MPU9250).

This is why we use an RTOS and a thread-per-bus model. It really does give much better performance, and a great deal of flexibility. The context switch overhead of a RTOS like ChibiOS is really small. I don't know if FreeRTOS would achieve the same level of performance, but it may well be able to as well.

On the APM2 we used the approach you're using, with IMU reads in an ISR and no threads, so we lived with it for many years, but I think it would be a backwards step to go back to that model, especially when we will be able to support the same flight boards with great scheduling by using a light weight RTOS.

**Comment by night-ghost** [comment]
>but it won't be as smooth and won't have the same level of disturbance rejection as you get with good consistent scheduling.

I have 250-size copter with Revo and 350-size with PixLite, but I can't confirm this 

>reading in the ISR prevents us from doing bus parallelism, so you can't overlap the i2c read of a compass with the read of an IMU

You must be joking! How reads on independent SPI bus can disturb I2C reads from compass? Do you see a diagram of OpenPilot Revolution board? I don't say about any badly designed boards around.

>I don't know if FreeRTOS would achieve the same level of performance, but it may well be able to as well.

Yes these OSes uses very similar approach.


>I think it would be a backwards step to go back to that model

no-OS  approach is used also in Cleanflight family which has up to 32kHz loop so can to has some advantages too, especially in comparison with fatty and complex nuttx

**Comment by night-ghost** [comment]
> I have 250-size copter with Revo and 350-size with PixLite

PS. But both behaves much better than 350 copter on APM

**Comment by tridge** [comment]
> I have 250-size copter with Revo and 350-size with PixLite, but I can't confirm this

we've noticed a pretty strong correlation between good consistent scheduling and good flight performance. You can still fly OK with the sorts of scheduling results you posted, but if you can get much better scheduling on the same hw then why not do it?

> You must be joking! How reads on independent SPI bus can disturb I2C reads from compass? Do you see a diagram of OpenPilot Revolution board? I don't say about any badly designed boards around.

maybe I explained it badly. I mean that if you do sensor reads in an ISR, then while reading from the sensor you can't start a read from another sensor at the same time. I'm assuming that the ISR waits for completion of the sensor read, and that you don't allow for nested interrupts.
So while you're waiting for the MPU6000 to respond you can get the I2C peripheral to start working on a compass read (or an airspeed read, or lidar etc). 
The amount this affects a board with a single i2c and single SPI sensor isn't large, as typically the i2c read would not be done from an ISR, so while you are reading from the compass you could still service interrupts to read from the IMU. The reverse isn't true though.
Where this really starts to matter is where you have lots of sensors. Being able to run all your buses in parallel starts to become a really big win. Even on a little board like the Revo mini you ideally want bus parallelism for UART, I2C and SPI. You can get away without it for simpler cases, but it still does disturb the scheduling.

What I'm trying to point out with the ChibiOS option for the revo mini is that we can get great scheduling results and also fit on tiny boards. So we can keep all the richness of ArduPilot on bigger boards, but on cheaper hardware.

> no-OS approach is used also in Cleanflight family which has up to 32kHz loop so can to has some advantages too, especially in comparison with fatty and complex nuttx

we haven't tried for more than 8kHz yet, but I expect we could sample at 32kHz on the gyros if that turned out to be worthwhile. What betaflight and cleanflight are achieving is certainly very impressive (I especially like the dynamic notch filter option in betaflight), but that doesn't mean we should go the no-OS route.

When you go the no-OS route you can really only support extremely simple setups, and background processing like to do for logging, telemetry, terrain calculations, safertl etc starts to become extremely difficult.

We are looking at supporting much higher loop rates in ArduPilot, probably going to 1kHz rate loops first, then maybe 4kHz after that. 

Meanwhile, think about that 5ms loop time you got when you ran with SCHED_DEBUG=1. Now translate that to a 32kHz gyro read. That is 150 gyro samples. Yes, you can fly with 5ms loops times, but not as well as you can fly with 2.5ms loop times, and when we start pushing towards 1kHz, 4kHz, 8kHz etc then the approach taking in this port will just get worse.

**Comment by tridge** [comment]
btw, with the 5ms loop times, it's worth checking if it could be something that only happens when disarmed. For example, the pre-arm checks for RC calibration can really throw out the loop times, as it involves a scan of the parameter tables. 
Try changing this line to "return true;"
https://github.com/ArduPilot/ardupilot/blob/master/libraries/RC_Channel/RC_Channel.h#L102
and see if that makes some of your long loops go away.

**Comment by night-ghost** [comment]
>maybe I explained it badly. I mean that if you do sensor reads in an ISR, then while reading from the sensor you can't start a read from another sensor at the same time. I'm assuming that the ISR waits for completion of the sensor read, and that you don't allow for nested interrupts.

Just wrong assumption: there is only DMA configure in ISR, and 2nd interrupt when DMA transfer completes. Time in both ISR is much less than "tick" of preemptive scheduler and near the time of one context switch (~800ns in ChibiOs on 180mHz ARM). Moreover, threads NEVER works on one CPU simulteniously but CPU switches between threads by timer's tick so sensors are never reads at the same moment - only next tick in the best case, what gives us jitter to all measured times. What tick time are used in port to ChibiOs? I don't have any ISR which runs longer than 90uS, and there is only one ISR which takes so much: calculation of Gyro&Accel samples, all another ISR times are less than 10uS.

>When you go the no-OS route you can really only support extremely simple setups, and background processing like to do for logging, telemetry, terrain calculations, safertl etc starts to become extremely difficult.

2nd wrong assumption: there is simple cooperative multitask when tasks are switched on each call to HAL functions, especially in various delay(), I showed the statistics of tasks a little earlier. Scheduler measures how much time requires each task and (almost) not executes them if we have less time, so error of delay_us() usually not more than 200uS.  It can't give guaranteed time to high-priority tasks like Gyro&Accel processing but works rather well for slow compass and baro drivers. So logging and so on is not difficult. The only problem - no Posix compatibility so all code that uses FS can't works, but ChibiOs port should has this problem too

>Meanwhile, think about that 5ms loop time you got when you ran with SCHED_DEBUG=1. Now translate that to a 32kHz gyro read. That is 150 gyro samples.

if propeller does 10000RPM then it rotates near 0,5 revolutions per 5ms. And yes, this board has MPU6000 which can produce only 5 samples per 5ms

Loop time can easily be improved by inserting call to yield() to all slow functions but I don't want to disturb any code outside HAL

**Comment by tridge** [comment]
> ust wrong assumption: there is only DMA configure in ISR, and 2nd interrupt when DMA transfer completes. 

ok, interesting.  Which branch do I see that on? The PR isn't showing the branch at the moment (perhaps you renamed the branch?)

> Moreover, threads NEVER works on one CPU simulteniously but CPU switches between threads by timer's tick so sensors are never reads at the same moment - only next tick in the best case, what gives us jitter to all measured times.

wrong assumption :-)

We really do have sensor parallelism in ArduPilot master. The DMA happens on multiple buses at once, as you can see with a logic analyser if you look at the various buses at the same time. The thread that is associated with a bus starts a DMA request then yields the CPU until the DMA completes. Meanwhile the other bus threads run. That is how we run so many sensors in parallel with no scheduling issues.

On something like a PH2.1 we typically run 6 bus threads (3x SPI, 2x I2C and one for UARTs), and on systems with canbus run more. The buses all run in parallel.

You can end up getting some memory bandwidth contention as they all share the same memory interface, but the sensors definitely run in parallel and it is a huge win. We roughly halved our average CPU load when we switched to thread-per-bus early this year.

> 2nd wrong assumption: there is simple cooperative multitask when tasks are switched on each call to HAL functions, especially in various delay(), I showed the statistics of tasks a little earlier.

I don't remember seeing that. It seems quite strange to me - we don't call delay() from the main code while flying, and actually disallow delay() in other tasks. So what delay() calls are triggering this? 

> What tick time are used in port to ChibiOs? 

we're using 100us at the moment. That is working well.

> no Posix compatibility so all code that uses FS can't works, but ChibiOs port should has this problem too

Sid added microSD and FAT filesystem support to HAL_ChibiOS last week

**Comment by night-ghost** [comment]
>ok, interesting. Which branch do I see that on? 

https://github.com/night-ghost/ardupilot , sure :)

>We really do have sensor parallelism

yes, but STARTING of transfer will be on next tick. My HAL also does all transfers in DMA so in parallel

>we don't call delay() from the main code while flying

but calls delay_microseconds() from the delay..() family

>we're using 100us at the moment.

so any task can be paused for 100uS at any time. And what is better than a ISR for 90us?

>Sid added microSD and FAT filesystem support to HAL_ChibiOS last week

My HAL works with FatFs for about 6 months already

**Comment by night-ghost** [comment]
BTW, it needs a small change in AP_Hal::Device API:

/*
        allows to set callback that will be called after DMA transfer complete.
        if this callback is set then any read/write operation will return directly after transfer setup and
        bus semaphore must not be released until register_completion_callback(0) called from callback itself
    */
    virtual void register_completion_callback(AP_HAL::MemberProc proc) {}
    virtual void register_completion_callback(AP_HAL::Proc proc) {}

**Comment by night-ghost** [comment]
almost forget: thread per bus requires a lot of memory for thread's stack, ISR approach with completion callbacks don't

**Comment by night-ghost** [comment]
OK, Tridge, you wanted preemptive multitask - I did it! Without any OS, sure. Test results will be some later

**Comment by night-ghost** [comment]
results. Task sheduling by HAL has maximal time error 30uS, and bad loop times are not caused by HAL

> Scheduler overrun task[21-one_hz_loop] (6874/100)
> 
>  huge loop time=7609!

and lots of another overruns as I see if sched_debug set to 5  but this is largest

**Comment by night-ghost** [comment]
Most of the time - in AP_Arming::rc_checks_copter_sub()

**Comment by night-ghost** [comment]
PERF: 10/4000 max=3791 min=1830 avg=2501 sd=50
PERF: 9/4000 max=3545 min=1753 avg=2501 sd=47
PERF: 6/4000 max=3548 min=1494 avg=2500 sd=62

**Comment by night-ghost** [comment]
Well, now my HAL can run ArduCopter with 1KHz loop :)

PERF: 0/10000 max=1112 min=883 avg=1000 sd=9
PERF: 0/10000 max=1150 min=889 avg=999 sd=10
PERF: 0/10000 max=1112 min=890 avg=1000 sd=10
PERF: 0/10000 max=1151 min=882 avg=1000 sd=9
PERF: 0/10000 max=1105 min=892 avg=999 sd=8
PERF: 0/10000 max=1121 min=877 avg=999 sd=10
PERF: 0/10000 max=1129 min=869 avg=1000 sd=9
PERF: 0/10000 max=1151 min=889 avg=1000 sd=9
PERF: 0/10000 max=1112 min=880 avg=1000 sd=10
PERF: 0/10000 max=1121 min=875 avg=1000 sd=9
PERF: 0/10000 max=1148 min=878 avg=999 sd=11
PERF: 0/10000 max=1149 min=883 avg=999 sd=9
PERF: 0/10000 max=1132 min=865 avg=1000 sd=10
PERF: 0/10000 max=1424 min=892 avg=1000 sd=11
PERF: 0/10000 max=1108 min=892 avg=1000 sd=9
PERF: 0/10000 max=1113 min=884 avg=1000 sd=9
PERF: 0/10000 max=1108 min=889 avg=1000 sd=10
PERF: 0/10000 max=1148 min=884 avg=1000 sd=10

**Comment by magicrub** [comment]
That's really good news!

Would be great to get this branch cleaned up so we can review it. Needs a big rebase because it has diverged from master a lot in it's current form. We'd love to have this into master.

Number of files changed: 563
Number of Lines of Code changed: +251790 and −3
git merge conflicts exist

**Comment by night-ghost** [comment]
code is [here](https://github.com/night-ghost/ardupilot), this PR is only a history

**Comment by magicrub** [comment]
It's win-win to get them merged into master. Everyone benefits and it's less maintenance on your end to rebase your branch onto ArduPilot master. We have standards that are strongly enforced (http://ardupilot.org/dev/docs/contributing.html). It's all about risk. Millions of drones fly ArduPilot with many developers so we're a bit particular. If you're able to break up the improvements into smaller pieces then we can more easily evaluate them to be merged. General rule is PRs that are small and "obviously correct" go in fast, large "need to be confirmed/tested" changes take longer.

**Comment by night-ghost** [comment]
>We have standards that are strongly enforced

The problem is those standards are required for all but your team.The team allowed to [break working code](https://github.com/ArduPilot/ardupilot/issues/7081), use [goto](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Scheduler/AP_Scheduler.cpp#L159), [kill drones in air](https://github.com/ArduPilot/ardupilot/blob/master/ArduCopter/failsafe.cpp#L63) et cetera.

Moreover your standards are not cover an OS that your use, sure? 

> It's all about risk. Millions of drones fly ArduPilot

but zero of that drones uses hardware this HAL intended to.

So I don't interested to change something  in working state-of-the-art HAL code, and changes to other parts are negligible and straightforward.

**Comment by hiro2233** [comment]
👀

**Pull request closed without merging**
