### PR TITLE
Copter : Added altitude check for guided takeoff (will be at least 1m)

### PR DESCRIPTION
**Pull request by ClementChristomanos**
Following comment from @rmackay9, added altitude check that is present in AUTO takeoff and that wasn't in guided takeoff (Closed PR #5683).

### CODE REVIEW

**Comment by OXINARF** [comment]
@rmackay9 What's the reason behind this? It has downsides and I don't see any advantage (checking that it is above current altitude would be good though).

**Comment by GunMan-fr** [comment]
@OXINARF Auto takeoff code says in a comment that "if taking off from below home this could cause a climb to an unexpectedly high altitude". That behavior is mitigated by that check. I don't know how the arbitrary 100cm value was chosen, however what I'm willing to do with that PR is to maintain Guided_takeoff code as similar as possible as auto_takeoff code.

In general, I would say you wouldn't want to takeoff to less than 100cm on a multirotor. Ground effect makes height readings very unprecise especially for users without rangefinders - that's why I wouldn't so much trust the altitude values under 1m.

**Comment by ClementChristomanos** [comment]
@OXINARF Auto takeoff code says in a comment that "if taking off from below home this could cause a climb to an unexpectedly high altitude". That behavior is mitigated by that check. I don't know how the arbitrary 100cm value was chosen, however what I'm willing to do with that PR is to maintain Guided_takeoff code as similar as possible as auto_takeoff code.

In general, I would say you wouldn't want to takeoff to less than 100cm on a multirotor. Ground effect makes height readings very unprecise especially for users without rangefinders - that's why I wouldn't so much trust the altitude values under 1m.

**Comment by OXINARF** [comment]
> Auto takeoff code says in a comment that "if taking off from below home this could cause a climb to an unexpectedly high altitude". That behavior is mitigated by that check.

It's exactly the opposite. This code you are adding causes that behaviour. Let's say you have the copter 100m below home and you send a takeoff with takeoff altitude (above home) set to -80m. That should cause the vehicle to climb to 20m above current location, but with this check in place it will actually go to 101m above current location.

> In general, I would say you wouldn't want to takeoff to less than 100cm on a multirotor. Ground effect makes height readings very unprecise especially for users without rangefinders - that's why I wouldn't so much trust the altitude values under 1m.

Exactly, you are inhibiting anyone with a rangefinder to takeoff to less than 1m.

Like I said, checking that the takeoff altitude is higher than current altitude is good, but more than that seems to me like an unnecessary restriction.

**Comment by ClementChristomanos** [comment]
@OXINARF I agree with your point, however as said earlier, I've done this PR just to fix a discrepancy between AUTO takeoff and GUIDED takeoff procedures. I'm not adding a check, just making sure Auto and Guided perform the same checks.

You're probably right on the principle - then what should be done is remove this check from auto takeoff ! @rmackay9 ?

**Comment by OXINARF** [comment]
@ClementChristomanos Yes, I know, that's why I directed my first comment at @rmackay9 :smiley: 

We can also check if we have a rangefinder available (and healthy) to decide on whether to impose a minimum altitude lift or not. Even then, it should be a minimum from current altitude and not from home - and 1m is probably more than needed.

**Comment by rmackay9** [comment]
Ok, so the idea behind this PR is to make guided and auto equivalent which is a good thing in general.

I don't think we should change the interpretation of the NAV_TAKEOFF command's altitude field away from alt-above-home a check that the target altitude is at least as high as the current altitude would be good - for both guided and auto.

Sorry @ClementChristomanos for leading you astray.

**Comment by ClementChristomanos** [comment]
No problem @rmackay9 ! Thanks for your inputs @OXINARF. I will close this PR and open another one in the next few days for the "check if target alt is > to current alt" for both auto and guided takeoffs.

**Pull request closed without merging**
