### PR TITLE
GCS_MAVLink: Allow the user to specify private channels

### PR DESCRIPTION
**Pull request by WickedShell**
This allows you to mark a serial channel via the `SERIALx_OPTIONS` bitmask as a channel that the MAVLink data shouldn't be forwarded to or from. The motivating reason for this is an embedded device which has misunderstood some of the implementation details of `MESSAGE_INTERVAL` and is sending out messages that don't help any GCS, and we don't want to forward any of the debug messages onto the telemetry link to the GCS as it's consuming the bandwidth.

There is a behaviour change here in that this extends the concept of private channels to mean "no data from this channel is sent to the GCS" where before it was simply "no data gets forwarded to a private channel". Before this patch the only thing that could be a private channel was a Solo gimbal. As I understand it, this was done because the gimbal was getting confused by MAVLink messages from the GCS. This change would mean you can't receive messages from the gimbal on the GCS with this patch set, but in an inital conversation with @Pedals2Paddles it was believed this was okay. This does need to be tested before we bring this in so it doesn't break anything for the solo gimbal support. If that doesn't work I can add a new bitmask in parallel to `is_private()` but I didn't want to add that if it wasn't needed.

I've locally tested that this suppresses the data I didn't want to see from the GCS, however I don't have a solo to test if this breaks anything there.

### CODE REVIEW

**Comment by rmackay9** [comment]
As mentioned on the dev call this will resolve the top issue on our T265 issues list: https://github.com/ArduPilot/ardupilot/issues/13903

**Comment by Pedals2Paddles** [comment]
Loaded on my solo.  Nothing is on fire.  All systems working as intended.  LGTM.

**Comment by peterbarker** [comment]
Thanks @Pedals2Paddles !

Merged, thanks.

**Comment by lthall** [comment]
I have opened an issue with this PR here:
https://github.com/ArduPilot/ardupilot/issues/20723

**Pull request merged**
