### PR TITLE
Matek F405 TE/VTOL bdshot

### PR DESCRIPTION
**Pull request by andyp1per**
Specific Matek F405 TE/VTOL firmware based on Matek F405 TE, but including bdshot on channels 1,2 and 4 for tri-tilt (e.g. Ranger T1)

### CODE REVIEW

**Comment by peterbarker** [comment]
Is there some reason we're moving away from the `-bdhost` convention?

Why not `MatekF405-TE-bdshot?  I could certainly see people running a `MatekF405-Wing` wanting to do VTOL jumping at this firmware rather than the `MatekF405-Wing-bdshot` variant, for example.

**Comment by andyp1per** [comment]
> Is there some reason we're moving away from the `-bdhost` convention?

Not moving away - just suggesting it in this instance. The pinout of the board means that channel 3 cannot be used for bdshot - that's a problem for quads but not really for wings, hence my suggestion of doing it this way

**Comment by andyp1per** [comment]
ok @MATEKSYS you are the vendor 👍

**Review by tridge — APPROVED** [review]

**Comment by rmackay9** [comment]
This is included in Copter-4.4.0-beta1

**Pull request merged**
