### PR TITLE
AP_Beacon: Add a method to determine if the device is not ready.

### PR DESCRIPTION
**Pull request by muramura**
It is judged whether a device or type is not supported by multiple methods.
Therefore,
Create a common method.

### CODE REVIEW

**Comment by magicrub** [comment]
LGTM

**Comment by OXINARF** [comment]
I don't like the name very much as it doesn't check for an unsupported device, it checks for the presence of a beacon device.
Anyway, I'll leave this one to @rmackay9 to decide

**Comment by muramura** [comment]
@OXINARF Comment thank you.
method name , etc no good, OK.
In @rmackay9  comment, I will correspond.

**Comment by magicrub** [comment]
A function like this should start with is_ such as is_ready

**Comment by muramura** [comment]
Sorry. Miss UP.

**Comment by muramura** [comment]
@magicrub Comment Thank you.
Changed "unsuport_device_or_type" to "is_device_not_ready".

**Comment by rmackay9** [comment]
Changed slightly and merged! thank!

**Pull request closed without merging**
