### PR TITLE
DataFlash: add debug for io thread failure

### PR DESCRIPTION
**Pull request by peterbarker**
I'm quite sure this will show write() is never returning

### CODE REVIEW

**Comment by WickedShell** [comment]
Have you used this to show wat happens with the onboard compass cal?

**Comment by peterbarker** [comment]
On Fri, 28 Jul 2017, WickedShell wrote:

> Have you used this to show wat happens with the onboard compass cal?

Nope!

**Comment by OXINARF** [comment]
I don't quite like to get debug in messages shown to users, but this will at least show us where the issue is happening. Merged, thanks!

**Comment by peterbarker** [comment]
On Fri, 28 Jul 2017, Francisco Ferreira wrote:

> I don't quite like to get debug in messages shown to users, but this will at least show us where the issue is happening. Merged, thanks!

Well I *would* have liked to log it, but... :-)

**Pull request merged**
