### PR TITLE
Tools: added board IDs for GreenSight boards

### PR DESCRIPTION
**Pull request by sionv**

### CODE REVIEW

**Comment by magicrub** [comment]
is there something more coming or is this it? How about a hwdef?

**Comment by sionv** [comment]
This is it for now. A pull request for two hwdef files will be made in the near future after an internal review and additional flight testing. The board IDs are needed to update those hwdef files.

**Comment by magicrub** [comment]
I don't think we usually reserve IDs to board_types without a hwdef, so the devs will chat internally to see if that's something we'll allow here. The outcome will be we either:
1. merge this and cross our fingers you follow-up in the future with a hwdef PR
2. close this and you include it in your PR /w the hwdef

**Comment by magicrub** [comment]
I marked this for the devcall but if there's a precedent I'm missing then I'm happy to approve it.

**Review by tridge — APPROVED** [review]

**Comment by tridge** [comment]
@magicrub reserving IDs is a good idea, we do this quite a lot

**Pull request merged**
