### PR TITLE
AP_Beacon: Added Marvelmind beacon example.

### PR DESCRIPTION
**Pull request by ptsneves**
This commit includes an example program to
run the code of AP_Marvelmind class.
It also includes a dump from the marvelmind
serial as well as a script that injects
this dump into the example for demonstration.

### CODE REVIEW

**Comment by rmackay9** [comment]
The AP_Beacon examples stuff looks fine.  I'm not sure if we have any rules about what we put in the Tools/scripts directory.  Maybe @peterbarker or @OXINARF has an opinion?

**Comment by OXINARF** [comment]
I don't think we have rules. I'm not sure if the script is valuable to have though. I think that a README in the example folder explaining how you launch it would be more valuable.

**Comment by peterbarker** [comment]
I'd suggest putting the script in the example's directory.  That way nobody has to go looking.

**Comment by ptsneves** [comment]
@OXINARF Very sorry. I need to fix my vimrc.

Regarding where the scripts should be, I also agree that maybe it is better for it to stay in the example directory. Just instructions, makes things more complicated.

**Comment by ptsneves** [comment]
Pull request updated with inputs from the thread and review.

**Comment by rmackay9** [comment]
I think this is looking OK so mergine!

**Pull request merged**
