### PR TITLE
AP_NavEKF3: added EK3_MAG_EF_LIM parameter

### PR DESCRIPTION
**Pull request by Jaaaky**
Adapted from EKF2 implementation as of commits
3835d2613, e9ed3540f and df4fc0fff
this sets a limit on the difference between the earth field from the
WMM tables and the learned earth field inside the EKF. Setting it to
zero disables the feature. A positive value sets the limit in mGauss.

### CODE REVIEW

**Comment by tridge** [comment]
Great, thanks! We just need to do some testing of this and wait for Paul to review

**Comment by khancyr** [comment]
I fly this on EKF3 since you made it on EKF2 and it was working great at reducing compass perturbations

**Comment by tridge** [comment]
testing in SITL with large (incorrect) compass offsets looks good
normalised innovations with master:
image
normalised innovations with EF limit enabled in this PR:
image

**Comment by Jaaaky** [comment]
@priseborough Can you review please? In order to do real flight test.

**Comment by tridge** [comment]
@Jaaaky I can do a test flight of this on the weekend

**Comment by Jaaaky** [comment]
Thanks @tridge , waiting the results

**Comment by tridge** [comment]
@priseborough flight log:
http://uav.tridgell.net/Paul/ek3-ef-lim.bin

**Comment by tridge** [comment]
rebased. The flight log was good, so I will merge this when it passes CI

**Comment by Jaaaky** [comment]
Passed?

**Pull request merged**
