### PR TITLE
.github: add chibios test with GCC 9

### PR DESCRIPTION
**Pull request by khancyr**

### CODE REVIEW

**Comment by tridge** [comment]
thanks for this! failing CI at the moment, once passing this will be very useful

**Comment by tridge** [comment]
thanks @khancyr !
note that we expect this to fail until https://github.com/ArduPilot/ardupilot/pull/15786 is merged

**Comment by peterbarker** [comment]
I've rebased this on top of the gcc-9-fixes PR.

**Comment by peterbarker** [comment]
CI is failing here because the VM doesn't have the Python serial module

**Pull request merged**
