### PR TITLE
 AR_AttitudeControl: cutoff low speed value

### PR DESCRIPTION
**Pull request by khancyr**
@rmackay9 this should give smother direction switching and in respect of max acc/deceleration

### CODE REVIEW

**Comment by rmackay9** [comment]
@khancyr,
So I think the idea behind this PR is that we should force the vehicle to slow and stop as the user changes the desired-speed from positive to negative (or negative to positive).  I think this is a good idea.

My concern though is that the speed may not be perfectly accurate or may temporarily become negative in cases where the user isn't transitioning from forward to reverse.  This could happen for example if the vehicle was stopped or travelling very slowly.  Say for example the vehicle was stopped but the EKF was reporting a slightly backwards movement, wouldn't this change stop the vehicle from ever moving forwad?

**Comment by khancyr** [comment]
@rmackay9 yep, you had add it but, I think it is better not to bypass the pid and use it to control the slowdown on foward-backward request.

I think it was pretty safe, if the EKF was miscalculating the current speed, then going to stop momentary will allow it to converge to the real speed (that is 0), wouldn't it ?

Anyway, I change to use the throttle calculated instead of the speed !

**Comment by rmackay9** [comment]
@khancyr, have you tested this in the simulator and/or a real vehicle?
It definitely seems to me that the vehicle could get stuck.  If the vehicle is stopped so throttle-out is zero, won't the desired-speed be stuck at zero?  How can it become non-zero?

**Comment by khancyr** [comment]
yes, you are right, it append sometime, we need to correct that.

**Comment by khancyr** [comment]
@rmackay9 
Setting cutoff value for getting rid of impression and mecanical limits solve plenty things ! I don't think value under 1% throttle are valuable neither those < 0.01 rad/s .
I am not sure about some change I made .. I will try to discuss them with you

**Comment by rmackay9** [comment]
I've merged the "fix servo-out" commit to master and also the fix to the MOT_SLEWRATE parameter description (perhaps from another PR).

**Comment by khancyr** [comment]
I don't know how I didn't saw that that what I was doing wasn't at all usefull...
So I just left low speed value cuteoff . I have tested with SITL in velocity control in guided and it works well. The controler works very well, maybe the accel limit is too hight but the effect of lowering it can be see on speedup and slowdown so controler output doesn't as intended even in transition from forward to backward !

**Pull request closed without merging**
