### PR TITLE
LSM9DS1 magnetometer support

### PR DESCRIPTION
**Pull request by staroselskii**
- support for compass inside LSM9DS1
- enable it for Linux boards that don't have a default compass
- enable support for multiple compasses on Navio 2

This PR has been bench-tested as follows:
- Set compass#2 (i.e. LSM9DS1 for Navio 2) in GCS to external and applied ```ROTATION_ROLL_180```.
- Attached a HMC5883L  and applied a rotation
- Calibrate
- Compare magnetometer data in the logs

And the test has yielded the same results on the three compasses.

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
> Set compass#2 (i.e. LSM9DS1 for Navio 2) in GCS to external and applied ROTATION_ROLL_180.

Isn't LSM9DS1 onboard? Why would you set it to external? We may want to check https://github.com/ArduPilot/ardupilot/pull/3792

I want to bring that in this week which will bring 3 changes:

 - Internal mag we know so we can set the orientation
 - External mag can be set to external automatically, no need for the user to set the param
 - External mag should use the orientation relative to vehicle, not the board.

What do you think?

**Comment by staroselskii** [comment]
> Internal mag we know so we can set the orientation

I would've set if I had known where to set it. I didn't want to hardcode, so I figured that *external* should get me going, so I tested it as I described but I would like to play along! So would you be so kind to help me figure out where do I need to set the proper orientation for the internal magnetometer. 

> External mag can be set to external automatically, no need for the user to set the param

That is awesome!

So I guess I'll wait until those changes are merged into. Do we have an estimate time? Is there anything that stops from merging? 

This PR will be updated accordingly. The PX4 build will also of course will have been fixed by that time.

**Comment by staroselskii** [comment]
@lucasdemarchi 

Have you had a chance to discuss this PR on the [devcall](https://groups.google.com/forum/#!topic/drones-discuss/drzly_Nendo)? 

By the way, the code had been already flight-tested and I've updated the PR to eliminate the conflicts as well.

**Comment by lucasdemarchi** [comment]
@staroselskii briefly only...

I'm just curious on the following points:
  - LSM9DS1 is an accel + gyro + mag. Why don't we have something similar to the LSM9DS0 code?
  - Couldn't LSM9DS0 driver be tweaked to support both LSM9DS0 and LSM9DS1?  LSM9DS0 driver provides accel + gyro + mag for LSM9DS0 and the combo LSM303D + L3G20.

**Comment by staroselskii** [comment]
@lucasdemarchi 

These sensors do share a lot in common (register map is identical from the brief look), so I suppose your questions are valid indeed. But they differ in the way the are used. That is LSM9DS1 is a gyroscope/accelerometer and magnetometer (they use different CS lines).

That's why I'd decided not to make my life more difficult and hadn't implemented the former yet. I kept it as simple as possible for now.

> Couldn't LSM9DS0 driver be tweaked to support both LSM9DS0 and LSM9DS1? LSM9DS0 driver provides accel + gyro + mag for LSM9DS0 and the combo LSM303D + L3G20.

I guess so! But I'd prefer to keep both devices on my desk when I implement the merge. I'm sure we'll implement the accelerometer and gyro part on the LSM9DS1 in the future and make use of the awesome framework you'd created (```AuxillaryBus``` and friends) if needed. 

But a separate LSM9DS1 driver for accelerometer and gyro would also more trivial for us to implement because the way ```InertialSensor``` library is used. It's used for accels + gyros. That is where LSM9DS1 shines and sure makes our lives easier because it has a designated CS line for these. It differs from LSM9DS0 where it has line for gyro and another for accel/magnetometer.

**Comment by lucasdemarchi** [comment]
Got it. Thanks.

Another question before going deeper in the code:  are you guys ok with this: https://github.com/ArduPilot/ardupilot/pull/3792 ? Particularly the fact that after applying it, external sensors would have the orientation set relative to the vehicle and not the board.

**Comment by staroselskii** [comment]
@lucasdemarchi 

Sure. I have a question, though.

> external sensors would have the orientation set relative to the vehicle and not the board.

I cannot wrap my head around one simple fact. How do I make APM know that I do have two internal compasses with different rotations that are needed to be applied without introducing an ```#ifdef``` in the driver code? Or I can pass an extra rotation to the constructor.

Either way, I feel that's a hack I'd prefer not making. Maybe the problem is deeper? Like ```MAG_BOARD_ORIENTATION``` seems to be caring exclusively about one compass rotation.

This driver requires one extra action from our users before a flight - setting second compass as external and selecting ```ROTATION_ROLL_180```. I don't really like it this way. So I'd be glad to hear the idea anyone could pitch in.

**Comment by lucasdemarchi** [comment]
@staroselskii 

The idea is that we provide the rotation automatically for internal mags. However as you noticed, we have some problems in the codebase right now:
  - we only support 1 internal mag orientation
  - the orientation is set via an ifdef

I think I'd prefer an ifdef now for a second internal mag. For a long time we plan to add a config parser to ardupilot, and then these kind of things would be moved from an ifdef to an entry in the config file (to be stored in /etc/ardupilot. Unfortunately we didn't have that yet :-/.

If you add it as an external compass you are forcing your users to go and tweak one more parameter to do something we could have done for them.

**Comment by staroselskii** [comment]
> - we only support 1 internal mag orientation
- the orientation is set via an ifdef

That can be fixed, though. I mean we could add several mag orientations to the codebase. I'm not sure if that's worth the endeavour, though. What do you think? 

I'm totally into the config idea we'd been discussing some time ago. Has there been any news on the topic? I'd like to contribute to that in any way possible. These issues (#3562 and #3571) are also of great interest. It'd be great to discuss them once more.

But I digress. This thread is about the compass at hand.

> If you add it as an external compass you are forcing your users to go and tweak one more parameter to do something we could have done for them.

Yes. You're absolutely right. I'm going to add the rotation with an ```ifdef``` for now, then. After that's done, are we good to start merging?

**Comment by lucasdemarchi** [comment]
> That can be fixed, though. I mean we could add several mag orientations to the codebase. I'm not sure if that's worth the endeavour, though. What do you think?

I think it's worth it since it will be easier to translate the ifdefs to the config files

> I'm totally into the config idea we'd been discussing some time ago. Has there been any news on the topic? I'd like to contribute to that in any way possible. These issues (#3562 and #3571) are also of great interest. It'd be great to discuss them once more.

No news

> Yes. You're absolutely right. I'm going to add the rotation with an ifdef for now, then. After that's done, are we good to start merging?

yes, thanks

**Comment by lucasdemarchi** [comment]
Applied, thanks.

**Pull request closed without merging**
