### PR TITLE
AP_GPS: Fixes GPS auto baud failing to send out configuration string

### PR DESCRIPTION
**Pull request by joshanne**
We found that GPS configuration string sent before the baud was reconfigured (GPS_TYPE is set to SBF, GSOF or NOVA) resulted in the configuration string not being sent out. This is due to the serial port being reconfigured almost immediately after the configuration string is sent, and not having time to write to the port.

By ensuring auto baud occurs before the check for these GPS, the data is output on the port at the appropriate baud rates (user defined first, then iterates the baudrates array).

To the best of my knowledge, this looks like it's been present since as early as Copter 4.0.0 (??)

Required Configuration:
Hardware: `mRo Pixracer Pro`
`GPS_TYPE` : 10, 11, 15
`GPS_AUTO_CONIG`: 0
`SERIALx_PROTOCOL`: 5
`SERIALx_BAUD`: 230 (realistically, this can be anything, it just allows to test the user specified serial port baud occurs BEFORE the auto-baud starts)

### CODE REVIEW

**Review by tridge — APPROVED** [review]
looks good to me, but I'd like @WickedShell to have a look too

**Review by WickedShell — CHANGES_REQUESTED** [review]
I'm not seeing how this is a benefit. The drivers up here all strongly want to not participate in the config string stuff. If anything we should be strengthening it to ensure *no* bytes of the config string are sent, not just trusting timing.  None of these drivers have any data in the blob that I'm aware of, and for some of hem (IE SBF) sending the init blob at all will only make the drivers actual job harder, and take longer to configure.

Can you elaborate as to why you want to send the config string to these units?

**Comment by joshanne** [comment]
> The drivers up here all strongly want to not participate in the config string stuff
> Can you elaborate as to why you want to send the config string to these units?

The problem was that if you have a driver that creates a new GPS and in doing so sends out its own config string in the constructor (as is the case for GSOF and NOVA) that config string is never being sent out because autobaud pulls the serial port out from under it.

Those drivers also should never be participating in the auto configuration strings because GPS_TYPE will be set, and ideally, `GPS_AUTO_CONFIG` will be `0`.

We had a custom driver that was in that block, and by moving the auto baud, above, the serial port could `begin` and have those drivers send out their own specific config message.

**Comment by WickedShell** [comment]
> in doing so sends out its own config string in the constructor

This isn't a safe way of getting a config to a GPS unit. You need to actually look for an ack back, as it could be lost on the wire. You also might have an overly full buffer stopping you from fitting the whole string in the buffer, which can result in oddities as well. (Buffer sizes are a bit better these days, so it's less common, but it is a real problem I've seen in the past).

> Those drivers also should never be participating in the auto configuration strings because `GPS_TYPE` will be set, and ideally, `GPS_AUTO_CONFIG` will be 0.

You can't count on auto config being 0, as we only have one parameter for that. You might have SBF for one unit and UBX for the second. Even more importantly though the SBF driver does use `GPS_AUTO_CONFIG` internally, it's just that it knows what to do much better then the core driver.

> We had a custom driver that was in that block, and by moving the auto baud, above, the serial port could begin and have those drivers send out their own specific config message.

While this doesn't sound unreasonable on the one hand, the current structure is already attempting that. I guess it's a symptom of not having a detection routine you trust (which is not unreasonable honestly).

I'll need to look a bit more carefully. I think I can see why you want to do it this way, but I strongly caution you that relying upon anything being transmitted in the constructor is incredibly brittle, and is pretty risky for working reliably.

**Pull request closed without merging**
