### PR TITLE
Rover: Add param FS_THR_TIMEOUT for tighter control of RC loss

### PR DESCRIPTION
**Pull request by magicrub**
Rover: Add param FS_THR_TIMEOUT for tighter control of RC loss

### CODE REVIEW

**Comment by rmackay9** [comment]
Txs for this although I think if you test this you'll find that the radio failsafe does not actually trigger in the time specified in the new parameter.  Instead it will trigger after FS_THR_TIMEOUT + FS_TIMEOUT.  This cascaded timeout is confusing for users so I'm not keen on this change as-is.

What we need to do I think is separate the failsafes.  I thought there was an issue on the issues list that covers this but I couldn't immediately find it.

**Comment by magicrub** [comment]
> Txs for this although I think if you test this you'll find that the radio failsafe does not actually trigger in the time specified in the new parameter. Instead it will trigger after FS_THR_TIMEOUT + FS_TIMEOUT. This cascaded timeout is confusing for users so I'm not keen on this change as-is.


I've updated the description to help clarify:
    // @Description: The throttle failsafe timeout time in seconds. If no RC update occurs for this amount of time then throttle and steering demands are set to zero but no other action is taken. If this condition continues for another FS_TIMEOUT then a throttle failsafe will occur. This is useful for system failures where the RC input disappears or your are controlled only by MAVLink commands.

**Comment by rmackay9** [comment]
The cascaded timeouts is a bit silly though right?  If we're going to fix it, let's fix it properly..

**Comment by NickNunno** [comment]
Hello @rmackay9 

Please forgive the vague description of this PR. 

I also agree our FS structure can and should be greatly improved over the long run. It's also understood a FS does not trigger during the first timer. 

ArduPilot latches last received packet for the currently hard coded 500ms. (To my understanding this is the fastest timer we have) 

In other words:
FS_THR_TIMOUT - forces last received control msg to zero upon X time in MS 
FS_TIMEOUT - starts after FS_THR_TIMEOUT period and executes FS_TYPE action.

Correct? 

If yes, consider the following: 

**Example Configuration 1:** 
Control Type: GCS sending MANUAL_CONTROL messages 
Connection: WiFi, p2p etc.
FS_TYPE: 2 (HOLD)
FS_TIMEOUT: 1 second 
FS_THR_TIMEOUT: (Hard coded 500ms)
Net Behavior: ArduPilot will latch last known packet for 1.5 seconds. 

In Example 1, ArduPilot will latch the last received packet for 500ms + FS_TIMEOUT which puts us into HOLD. In the case of a manually controlled vehicle operating in a tight environment, a 1.5 second delay means we very likely caused a crash/injury before stopping. Whats more, we _will_ latch full throttle for this period if that was the last packet received. 

**Example Configuration 2:** 
Control Type: GCS sending MANUAL_CONTROL messages 
Connection: WiFi, p2p etc.
FS_TYPE: 2 (HOLD)
FS_TIMEOUT:   2 Seconds
FS_THR_TIMEOUT: 250ms (User adjustable) 
Net Behavior: ArduPilot will only latch controls for 250ms before cutting to zero, then go into failsafe (HOLD) after another 2 seconds. 

In Example 2, we're using HOLD for its intended purpose. (loss of connection with the GCS) While we're also resetting last received packets to zero as quickly as possible, avoiding an immediate crash. 

With an adjustable FS_THR_TIMEOUT, we're improving safety until we have time to rewrite the FS structure in a more permanent way.  

Unfortunately, we can't simply hard code a shorter interval due to variance between users wireless links/systems etc. 

- If set too high, the user feels latching "Sticking" in the controls.
- If set too low, the vehicle will twitch as it goes 0 during packet loss events. 

For best performance, you simply adjust FS_THR_TIMEOUT as low as your link allows. (Until you see twitching from packet loss) 

In our testing across a variety of devices, the sweet spot in terms of reliable packet transmission VS latching causing noticeable lag to the user seems to be around 100-400ms.

**Comment by rmackay9** [comment]
@NickNunno,

Thanks for explaining the issue.  I can see the need for a two stage failsafe, and that's essentially what's being implemented here but in a very specific way and it ends up being confusing for users.

Compared to the time we will spend testing, documenting and supporting users, the extra effort to implement it properly is really not very large.

**Comment by NickNunno** [comment]
@rmackay9 

Thank you. Just to make sure we're on the same page. Its understood, that we have not changed ArduPilot behavior, simply allowed the user to adjust this arbitrary 500ms value, correct? 

Without this adjustability, features such as touch screen sticks on QGC or GCS joysticks cause vehicles to stutter or controls to stick for 500ms. 

We're simply ok with this behavior? 

The parameter can easily be defaulted to 500ms as to not effect legacy users. 

The description would simply be:
"Adjust for manually controlling a vehicle over lossy wireless links. A setting too low will cause twitchy behavior, a setting too high will cause a delay in controls. A lower setting is preferred." 

Thanks for your consideration.

**Comment by rmackay9** [comment]
@NickNunno, @magicrub,

Feel free to bring it up at the dev call and we can get input from other developers.  I'm inclined not to include it because it's confusing.  If a two stage RC failsafe is really required (and it sounds like it is) then I think a solution similar to what MichaelDB did for the battery failsafe would be a better solution.

**Comment by rmackay9** [comment]
As discussed on the dev call, there is an existing parameter called RC_OVERRIDE_TIME that has a very similar purpose ([code](https://github.com/ArduPilot/ardupilot/blob/master/libraries/RC_Channel/RC_Channels_VarInfo.h#L77)) so instead of creating a new parameter this existing parameter's behaviour should be tested and if any issue crop up, they should be resolved.

**Pull request closed without merging**
