### PR TITLE
AP_Motors: reserve parameter index 38

### PR DESCRIPTION
**Pull request by jschall**

### CODE REVIEW

**Comment by jschall** [comment]
Copter already has a max current parameter in the motors library.

**Comment by rmackay9** [comment]
In general I don't mind merging this because it's a non-functional change and I'm sure you know what you're doing.  I'm wondering though, how is this different from the BATT_CURR_MAX?  I guess the difference is when the batter voltage drops?  It just seems very close so I worry having both parameters will be confusing.

**Comment by jschall** [comment]
Yes, it results in consistent behavior as the voltage drops.

**Comment by IamPete1** [comment]
We still have this reserved, but no sign of anything using it yet. Is there a PR somewhere?

**Comment by hendjoshsr71** [comment]
The primary electrical limit a battery needs to respect is the current limit. You could also add a power limit check to account for other device's power limits ESC, power distribution, etc. But the battery's P_max_limit =  C_max_limit * V in most cases. 

Of course the BattMon library has other device types other than batteries ESCs, MPPTs, generators and fuel flows where power limits are important. So could be good addition that could be made.

**Pull request merged**
