### PR TITLE
HAL/AP_RSSI - SBUS Rssi - ArduPilot - Resubmit #1

### LINKED ISSUE #2721: SBUS receiver signal quality by FrameLost status
Hello,

The idea here is to use the FrameLost status contained in the SBUS protocol to give an indication of the signal quality of the RC receiver, and use it instead of the analog based RSSI in all the APM system (telemetry, auto RTL,...).

I'm thinking about a sliding average of the last received FrameLost statuses. The length of the average could be 1 second or something, so 70 samples. This will give an indication of the signal quality for the last second.

Best,

Nicolas

### PR DESCRIPTION
**Pull request by StewLG**
(This is a resbumit of https://github.com/diydrones/ardupilot/pull/2798. The conversation there is still relevant to this and should be consulted for more background.)

This counts recent (about 0.7 seconds worth) of SBUS frames to see how many have been dropped, and calculates a Link Quality metric as a percentage of the possible total. This allows any SBUS radio receiver to offer an RSSI-type value to ArduPilot without resorting to additional channels or FrSky style telemetry wiring.

AP_HAL has had one function added to the interface. It has been stubbed out everywhere except PX4, although there are other platforms that could likely support it - the Linux boards for example. I would be happy to pursue at least some of those once this initial patch is accepted.

Here's an example of performance. In this log the transmitter has been walked away from my house, around my block, and back:

sbusrxrssi_smoothwalk

This was done using a 9XR Pro transmitter with a FrSky DJT module, and a FrSky X8R receiver, connected via single-cable SBUS to a Pixhawk. No other cables were used.

I believe it clearly provides a useful, non-binary value as the signal degrades.

Closes #2721.
Relies on https://github.com/diydrones/PX4Firmware/pull/45, so this will fail Travis integration checks until https://github.com/diydrones/PX4Firmware/pull/45 is accepted .

### CODE REVIEW

**Comment by lbarreiro** [comment]
I like this option and it will be great to see it in the next upgrade

**Comment by magicrub** [comment]
+1

**Comment by magicrub** [comment]
This is not compiling:
/home/travis/build/diydrones/ardupilot/libraries/AP_HAL_Empty/RCInput.cpp:19:7: error: 'EmptyRCInput' has not been declared
 float EmptyRCInput::link_quality() {
       ^

Please fix and re-test. Would be great to see this in Plane v3.5.0 but you'll need to do it soon!

**Comment by StewLG** [comment]
Tom, have you also included the relevant PX4 patch in your compile?

"Relies on diydrones/PX4Firmware#45, so this will fail Travis integration checks until diydrones/PX4Firmware#45 is accepted ."

**Comment by magicrub** [comment]
No, I had missed that. Sorry!

**Comment by StewLG** [comment]
I was hoping this would make it to Plane 3.5.1, but despite getting the 3.5.1 Milestone tag I evidently missed the beta.

Please let me know if there is anything I need to do to get this accepted. Again, it will not compile without the corresponding PX4 patch noted above.

**Comment by magicrub** [comment]
The beta is 3.5.0. The URL is labeled incorrectly and changing it had
unknown side effects. This is still on track for 3.5.1

**Comment by cliffoco** [comment]
@StewLG Have you compiled your patch into the most recent update 3.5.0, if so I would love to use it!

**Comment by nicbk117** [comment]
Please don't forget Copter :D

**Comment by magicrub** [comment]
@tridge please take a look at this for the v3.5.1 release

**Comment by nicbk117** [comment]
Hi All,

When do you thing this feature will be pulled to master?

Best regards,

Nicolas

**Comment by StewLG** [comment]
Nicolas:

I tried merging this PR again, and discovered that I think it needs a rebase. I apologize for not catching this earlier - since it relies on the PX4 patch this PR will _always_ fail Travis integration checks, and so I didn't know this PR had fallen out of alignment with trunk.

I hope to get to it soon - I very much want to see this released.

**Comment by nicbk117** [comment]
@StewLG : No problem :-)

I'm looking forward seeing this released...

**Comment by nicbk117** [comment]
Hi,

Any chance to see this included in Copter 3.4?

Best,
Nicolas

**Comment by StewLG** [comment]
I'm trying to re-open this PR rather than start yet another -- I apologize again for my Git ineptitude.

**Comment by magicrub** [comment]
Anything that touches PX4Firmware needs to be run by @tridge because he's doing a huge refactor. This is a very old PR, thank you for hanging in there! I'll remind him take a look.

**Comment by lvale** [comment]
@tridge With the refactoring of the RC, any way we could get this PR functionality ?

**Comment by tridge** [comment]
@lvale yes, we should revisit this. It would be a good time to work on it

**Comment by StewLG** [comment]
I have been trying to rebase this - which it may not even need - but in the short term I've only made a mess. My apologies, and bear with me.

**Comment by StewLG** [comment]
I wasn't trying to close this just yet. I am still working on it

**Comment by StewLG** [comment]
I have re-done the changes, my apologies.

**Comment by StewLG** [comment]
I have re-based this, but I think it was fine & ready for merge beforehand. I would love to see this merged, just let me know if there are any issues.

**Comment by robustini** [comment]
I really wait the @tridge supervision, would now integrate this feature into the master.
Having the opportunity to log on the RSSI would be crucial, considering that Taranis and X8R are the most used system in the world with Ardupilot.

**Comment by nicbk117** [comment]
Any chance this will be integrated on/before the final release of Copter 3.5?

**Comment by lvale** [comment]
@OXINARF can you please have a look at this ?

**Comment by lvale** [comment]
@StewLG Sorry. I flagged it for discussion but then I forgot it. It's 2AM here :)

**Comment by tridge** [comment]
@StewLG apologies again for slow response on this, and thanks for the reminder on the dev call today.
After looking at this I thought we could do it a bit more generally, so it works for SUMD and ST24 which have RSSI builtin to the protocol. So I have pushed a branch here that implements using the existing rssi from rc_input:
https://github.com/ArduPilot/PX4Firmware/commit/2634c74b25aaa07f0f4cfb4e7335fb75cb85673c
it is based on your patch, but instead of a new field in rc_input it just fixes the existing rssi field to work. That means it also gives us RSSI for ST24 and SUMD.
Then I added a new RSSI_TYPE=3 for "ReceiverProtocol". That works for SBUS, SUMD and ST24
https://github.com/ArduPilot/ardupilot/pull/6467
I tested it with a X6R and Taranis and it works nicely for me. What do you think?

**Comment by StewLG** [comment]
My initial impression is this is a big improvement over my more targeted PR. What I don't know is if SUMD and ST24 will actually give us a useful/valid value. I don't think it will do much harm if they don't, I just can't vouch for it working as I can with SBUS. I confess I never even considered the possibility that they would, I only knew SBUS would work and focused on that. So thank you for this big boost to potential reach.

I was afraid to touch the RSSI parameter that was pre-existing in PX4 - I wasn't confident about what it did and was just being cautious. It's better if we can use it, it certainly makes things simpler.

I said this in a comment near the relevant code, but I do think the range parameters for RSSI are super important. This is the part where many Flight Controller implementations of RSSI fall down - I can't tell you how many times I've had to say to myself while flying "Oh, right, 30% means total loss. And 85% is full signal." I in fact had to do it today while flying another system.

So I think we need RECEIVER_PROTOCOL_LOW/RECEIVER_PROTOCOL_HIGH to cover that.

I have to get to bed, but I will try compiling it up tomorrow and trying it out, maybe doing a walk test again and make sure everything is still functional under SBUS.

Thanks again for your help!

**Comment by tridge** [comment]
ok, lets discuss on the new PR. I'll close this one.
sleep well :-)

**Pull request closed without merging**
