### PR TITLE
Plane: Updated MANUAL_RCMASK description for safety

### PR DESCRIPTION
**Pull request by Naterater**
Noted that MANUAL_RCMASK can bypass arming. Condensed description.

### CODE REVIEW

**Comment by OXINARF** [comment]
@Naterater Commit message should be prefixed with `Plane: `

**Comment by rmackay9** [comment]
Also strangely I cannot see which repo this commit is coming from.  there must be something unusual about @Naterater's repo.

**Comment by OXINARF** [comment]
@rmackay9 That's because @Naterater created a branch in ArduPilot's repo.

@Naterater Please be careful with that, you should create a branch in your repo and then do a PR, don't create branches in ArduPilot's repo. Using GitHub interface is bad for this unfortunately, so it's best to use a Git GUI on your PC.

**Comment by rmackay9** [comment]
Oh right, that's not good.  @Naterater, forking, cloning etc is described [here on the developer wiki](http://ardupilot.org/dev/docs/git-fork.html).

**Comment by Naterater** [comment]
Many apologies as I did this from the web interface. I'll re-do this properly from my PC.

**Pull request closed without merging**
