### PR TITLE
HAL_ChibiOS: added YJUAV_A6SE support

### PR DESCRIPTION
**Pull request by yunjiuav**

### CODE REVIEW

**Comment by yunjiuav** [comment]
> how will you test this? since ArdduPilot bootloader will not work with this chip to boot firmware? are you doing a custom bootloader to ship with board that will boot ArduPilot firmware from the SD card?

We did not use a custom bootloader, just started it from the external Flash of the flight control, and the bootloader worked normally.
We directly tested the bootloader on the new flight control circuit board, and the ardupilot firmware started successfully.

**Comment by Hwurzburg** [comment]
okay, thought you might be loading from SD...
you need to create the bootloader files for Tools/bootloaders also

as to the A6 already merged (without bootloader files also) will it be produced at all or is this taking its place? I see neither on your website...will do a review of the README.md at little later....

**Comment by yunjiuav** [comment]
No, A6SE is a new hardware definition that does not replace A6. We have added a new bootloader ID in the "board_types. txt" file.
https://github.com/ArduPilot/ardupilot/pull/24546

**Comment by Hwurzburg** [comment]
I pushed a PR that adds the bootloader for the _A6 board so that firmware has it included..
do you provide a boot pin or button to allow DFU on these boards?

**Comment by yunjiuav** [comment]
> I pushed a PR #24565 that adds the bootloader for the _A6 board so that firmware has it included.. do you provide a boot pin or button to allow customer DFU on these boards?

Yes, we have provided the boot pin.
image

**Review by Hwurzburg — CHANGES_REQUESTED** [review]
needs bootloader binary added to Tools/bootloaders

**Comment by yunjiuav** [comment]
> needs bootloader binary added to Tools/bootloaders

OK，the bootloader binary has been pushed up.https://github.com/ArduPilot/ardupilot/pull/24631

**Review by Hwurzburg — APPROVED** [review]

**Review by tridge — APPROVED** [review]

**Pull request merged**
