### PR TITLE
Provide access to EKF status report

### PR DESCRIPTION
**Pull request by floaledm**
This will be used by the Frsky lib in a separate pull request.

### CODE REVIEW

**Comment by magicrub** [comment]
Thansk @floaledm . We typically don't merge in dead code. Let us know when your other PR is ready. It's OK to have a PR branch based on a PR branch.

**Comment by floaledm** [comment]
@OXINARF Thanks for the suggestion. I picked option 2. Definitely an improvement!

**Comment by floaledm** [comment]
Thanks for letting me know. Not sure I understand the concept but do I do that by adding override after const (i.e., `bool get_variances(float &velVar, float &posVar, float &hgtVar, Vector3f &magVar, float &tasVar, Vector2f &offset) const override;`)?

**Comment by OXINARF** [comment]
Yes. You should learn about virtual and override methods in C++.

**Comment by floaledm** [comment]
Thanks. Will do!

**Comment by floaledm** [comment]
@magicrub Do you know if there's anything holding up this PR?

**Comment by magicrub** [comment]
Seems ok, @OXINARF what about you?

**Comment by OXINARF** [comment]
Yep, I approved already :+1:

**Comment by magicrub** [comment]
Merged!

**Pull request merged**
