### PR TITLE
AP_Scripting: rename TRIK to TRIKR for sport_aerobatics

### PR DESCRIPTION
**Pull request by Hwurzburg**
to avoid trick param conflicts when swtiching between sport and trajectory aerobatics

this is most consistent with how we renamed AEROM to AEROR

### CODE REVIEW

**Comment by timtuxworth** [comment]
If I understand correctly, the params for sport aerobatics are "TRK", whereas the params for plane aerobatics will be "TRIK", this is very confusing and will cause ongoing problems.

Perhaps something like SPTRK and PLTRK or TRKS vs TRKP (since I think you you have used sport_aerobatics and plane_aerobatics for the different scripts)?

**Comment by Hwurzburg** [comment]
actually leaving the new sport_aerobatics as TRIK cause problems....if you switch scripts (which I do in the 3D XL depending on wind, since trajectory script cant handle now on this plane, to rate based for wind) the tricks become screwed up because the same params are being used for a different script....we changed the AERO params to stay AEROM for trajectory and AEROR for the new sport, but forgot about the TRIK group....and there are already people using the trajectory stuff and updating the script often, so param name changes for it are not on the table...

**Comment by timtuxworth** [comment]
> and there are already people using the trajectory stuff and updating the script often, so param name changes for it are not on the table.
A minor problem for a small number of people now vs ... 
I didn't suggest leaving anything. At least make it consistent with AERO - TRIKM, TRIKR ?

**Comment by Hwurzburg** [comment]
TRIKR was my first suggestion, but Tridge thought TRK was better....just needs to NOT be TRIK and TRIKx prefixes

**Comment by timtuxworth** [comment]
TRK vs TRIK will _totally_ cause confusion, maybe not in the software, but definitely in the wetware.

**Comment by timtuxworth** [comment]
Does it really need to be so aggressively abbreviated? I think I heard parameters can be up to 16 characters? It would be much easier for human beings to get the association from sport_aerobatics.lua to maybe "SPORT_TRICK##" as parameter and would never get confused with "TRIK" - they won't even show up near each other in the full parameter list.

**Comment by Hwurzburg** [comment]
after flying and setting up with script switcher, I find renaming to TRIKR is the best IMO...revised to that

**Review by tridge — APPROVED** [review]

**Pull request merged**
