### PR TITLE
Copter: fix RTL to rally point 

### PR DESCRIPTION
**Pull request by OXINARF**
I looked at the logs in http://discuss.ardupilot.org/t/copter-3-4rc1-rtl-to-rally-point-issue/9659 and the issue is that when we go to a rally point we were adding an RTL altitude to the rally point instead of flying at the rally point altitude.

Although the AP_Rally library says the altitude is absolute it shouldn't be, since by looking at the _rally_location_to_location_ function we can see that the home altitude was added, so it is in fact an altitude above home. This fix retains that the altitude at the rally point will be above home. The travel between current location and rally point behaves the same as if going home: follow terrain if active, follow altitude above home if not.

@rmackay9 I tried to think of all scenarios (terrain/no terrain, home/rally point, fence/no fence, etc), but I might have missed something so this should be reviewed carefully.

This also fixes a bug where terrain was being checked for origin twice and not checked for the return target.

### CODE REVIEW

**Comment by rmackay9** [comment]
Ok, I've reviewed this and I think it was missing one important feature which was that the vehicle could still climb above the fence if the rally point's altitude was set to an altitude higher than the fence.  I think the commit in my branch (built on @OXINARF's) resolves this.
https://github.com/rmackay9/rmackay9-ardupilot/commits/oxinarf-rtl

@OXINARF could you have a peek and see if you think this looks ok?

By the way, why was this added?
#if AC_RALLY == ENABLED
    if (!use_home) {
        ret = rallyLoc.alt * 100.0f;
    }
#endif

**Comment by OXINARF** [comment]
@rmackay9 Do you have a log that shows the problem you are mentioning? I just tried to reproduce it in SITL and it did respect the fence.

> By the way, why was this added?

That is added to set the rally point altitude. If you are going to a rally point (maybe the variable should be named *goto_rallypoint*  - and its value would be `!use_home`) the altitude you are going to travel at isn't the RTL_ALT or the one determined by the cone, it is the rally point altitude.

I've looked at your branch and I don't see where you are using the rally point altitude.
Like I've explained to you in Skype the initial altitude is always the home altitude. Then it calculates how much it has to climb above home and adds it to the home altitude.
If you want the rally point altitude to be above terrain, if available (and TERRAIN_FOLLOW is enabled), that would be adding 3-5 lines in the beginning. I can do it, just tell me if that is desired.

**Comment by rmackay9** [comment]
@OXINARF, I did a bunch more tests today and I think I fixed up the issues you found with my modifications on top of your stuff. https://github.com/rmackay9/rmackay9-ardupilot/commits/oxinarf-rtl

There's just one thing that bothers me which is that when applying the fence (which is alt-above-home) to the return target (which can be an alt-above-terrain), it can cause the vehicle to not climb at all (because the climb_target's alt is copied from the return_target's alt.

Anyway, i think it's much better than what we had before.

**Comment by OXINARF** [comment]
Ok, I've looked at it and it seems good but I have a couple of notes:

- `curr_alt` is set at the beginning as an above-home or above-terrain and it is used latter to make calculations. If the if at https://github.com/ArduPilot/ardupilot/compare/master...rmackay9:oxinarf-rtl#diff-318f021c8be097b591a37a25a6dfa40fR499 is true, then we should get curr_alt from current_loc as an above-home altitude (if false, it is certain `curr_alt` is already in terrain alt). Also we should set `rtl_path.terrain_used` to false.
- the check for negative altitudes (https://github.com/ArduPilot/ardupilot/compare/master...rmackay9:oxinarf-rtl#diff-318f021c8be097b591a37a25a6dfa40fR509) is not needed because the next checks will always, at least, get RTL_ALT_MIN.
- we need to make sure to alert our users that rally point has changed its meaning: it is now used as another minimum altitude but RTL cone also applies to it (meaning that if we are close to the rally point we won't climb to the rally point altitude)

> There's just one thing that bothers me which is that when applying the fence (which is alt-above-home) to the return target (which can be an alt-above-terrain), it can cause the vehicle to not climb at all (because the climb_target's alt is copied from the return_target's alt.

I see that you are making sure that the fence altitude is used as an above-home altitude. There are two problems with that:

- fence checking doesn't account for that, it just checks current altitude, not caring if it is above-home or above-terrain
- if you are following terrain you can go above that above-home-altitude anyway

My opinion is that we should have two new parameters: RTL_ALT_TERR and FENCE_ALT_MAX_TERR, which would be the altitudes used for RTL and FENCE when using terrain following, and leaving the old ones to be used as above-home altitudes when we don't use terrain.
And I would leave the rally point altitude to be an above-home target altitude instead of a minimum (that's what the docs say too by the way: https://github.com/mavlink/mavlink/blob/master/message_definitions/v1.0/ardupilotmega.xml#L1302).

Anyway, this is complex and you are the one that decides what to do.

**Comment by rmackay9** [comment]
I'm closing this PR because I've created a new one.  https://github.com/ArduPilot/ardupilot/pull/4623

I wanted to see it pass travis and semaphore before committing.

**Pull request closed without merging**
