### PR TITLE
AP_Scripting: greatly reduce memory in aerobatic scripting

### PR DESCRIPTION
**Pull request by tridge**
rework aerobatics script to make objects fall out of scope to allow gc to do its job on low memory

### CODE REVIEW

**Comment by IamPete1** [comment]
Interesting, What is the before and after memory usage? Presumably the extra collection takes a noticeable amount of run time? We could default to more aggressive collection....

**Comment by tridge** [comment]
> What is the before and after memory usage?

without this change aerobatics with a large schedule (eg. F3A) takes about 350k, and increases proportional to the length of the schedule, making large schedules impossible on real hw
with this change it is fixed 200k, with any length schedule

**Comment by tridge** [comment]
one thing we could do is auto gc when we fail an allocation

**Comment by tridge** [comment]
@IamPete1 turns out the gc does correctly run on oom conditions, so the collectgarbage() isn't needed, just need to arrange the script to ensure objects drop out of scope at the right time

**Pull request merged**
