### PR TITLE
AP_MotorsUGV: Fix application of MOT_SLEWRATE to achieve full range.

### PR DESCRIPTION
**Pull request by jimovonz**
The actual slew rate achievable using the MOT_SLEWRATE parameter does not seem to correspond with stated range of 0-1000 percent throttle per second. The current code limits the minimum delta to 1 percent of throttle per loop cycle. For the Rover default of 50Hz, this equates to 50% throttle per second - any parameter values less than 50 results in the same slew rate of 50. For faster loop rates the minimum possible slew rate is higher - for instance, at 400Hz the minimum achievable rate is 400% throttle per second. The proposed change results in slew rates that cover the whole of the intended range.

### CODE REVIEW

**Comment by IamPete1** [comment]
We could take the opportunity to remove the loop rate dependency,  I actually think the range check is unnecessary.

**Comment by jimovonz** [comment]
The range limit imposed was loop rate dependant, my fix removes this
dependency and allows the parameter to behave as expected regardless of
loop rate

**Comment by khancyr** [comment]
Hello,
What improvement does this bring ?
On the current implementation change lower than 1% throttle are just noise and won't be taken into account.. so what does thing bring beside of more calculus?

**Comment by jimovonz** [comment]
@khancyr As the title suggests, this is a 'Fix' that does not offer any additional features other than restoring the functionality that is advertised.

**Comment by khancyr** [comment]
Ok I understand what the issue is ... my bad, I wasn't looking at the right place.
the function `MAX(1.0f, (float)_slew_rate * dt);` doesn't work as dt is 1/50s so under 50% slew rate we are always under 1 and thus we are always asking for a change of 1% throttle  ...

So the current fix is OK, and it fix the slew behavior.
But what I don't understand is why we are using G_Dt (50Hz) for the timing while the servo loop is running at 400Hz ?

**Comment by peterbarker** [comment]
I've rebased this on top of some CI fixes.

**Comment by khancyr** [comment]
@rmackay9 I have made https://github.com/ArduPilot/ardupilot/pull/14890 that show the issue and show that the proposed fix is correct.
About the removal from MIN/MAX, it works without.

**Comment by khancyr** [comment]
@jimovonz sorry for beeing a little pedantic on commits, but we don't use the merge commit. Could you rebase on ArduPilot master branch to get rid of the merge commit ? thanks !

**Comment by peterbarker** [comment]
@jimovonz nudge!

**Comment by khancyr** [comment]
I have rebase and correct in https://github.com/ArduPilot/ardupilot/pull/14890. thanks

**Pull request closed without merging**
