### PR TITLE
AP_HAL_PX4: fix UAVCAN armed state to depend on safety switch

### PR DESCRIPTION
**Pull request by OXINARF**
This commit was originally in #6070, but I removed it so that PR can go in and discussion can continue here.

### CODE REVIEW

**Comment by EShamaev** [comment]
Hopefully I will have CAN ESC soon to fully tests it.
For now, after considering your answers, I agree with this version.
However none of the known CAN ESCs have the arm/disarm capability at the moment, so we should use the old method of not sending the data to it when disarmed.

**Comment by OXINARF** [comment]
I'm sorry, looking at too many things at once. I was completely convinced that the `rco_arm_actuators` method would send a message to CAN ESCs to arm/disarm. Apparently it just enables or disables the sending of Actuator Command and Esc Raw messages, which is exactly what we want.
Given this, I think this PR is perfect and all we need. Do you agree? Is it OK to merge?

**Comment by EShamaev** [comment]
Yes, I agree and will be good to have this merged!

**Comment by OXINARF** [comment]
Merged, thanks!

**Pull request merged**
