### PR TITLE
mavlink local position now uses origin instead of home

### PR DESCRIPTION
**Pull request by sharvashish**
This PR closes https://github.com/ArduPilot/ardupilot/issues/6830

### CODE REVIEW

**Comment by amilcarlucas** [comment]
This breaks the sitltest :(

**Comment by sharvashish** [comment]
Log of CI states:

AUTOPILOT_VERSION not received
FAILED: None
>>>> FAILED STEP: drive.APMrover2 at Mon Sep  4 10:53:20 2017
FAILED 1 tests: ['drive.APMrover2']

But I cannot understand when and how it failed?

**Comment by khancyr** [comment]
I relaunched it as it was looking like a sync problem... it happends

**Comment by OXINARF** [comment]
@sharvashish Since this is your first contribution we'll fix it for you, but please read our contribution guidelines (http://ardupilot.org/dev/docs/submitting-patches-back-to-master.html), specially the part about commit messages.

**Comment by WickedShell** [comment]
The conclusion from the dev call was that home is controlled by the ground station and doesn't just move, while origin can drift on altitude over time through the EKF.

**Comment by tridge** [comment]
I think I'd prefer to add extra fields to the HOME_POSITION message using MAVLink2 extensions, so that HOME_POSITION can also contain the origin

**Comment by OXINARF** [comment]
@WickedShell I'm sorry I wasn't in that dev call as those conclusions aren't correct. As I explained in the issue, origin doesn't move any more and it's way more likely for home to actually be moved by the user - home was designed to be moved, origin wasn't.
When people keep saying we want ArduPilot to work better with ROS I'm sure this goes against that, there is no way for a ROS node to have a stable local position of the vehicle.

**Comment by WickedShell** [comment]
@OXINARF Origin should be considered the EKF's option to do what it wants to. The recent additions of gps baro drift compensation for long flights still shift the EKF origin. Target pos NED is still considered to be relative to home rather then origin (at least for altitude) already.

If you want to use ROS in a stable manner then don't move the home location? Home moves only under a specific set of very controllable circumstances, and if set from a GCS won't automatically move again, while the origin can be slowly drifted by a number of locations in the code. If EKF origin must never shift in flight/after power on that limits Paul's ability to compensate over time.

**Comment by OXINARF** [comment]
> The recent additions of gps baro drift compensation for long flights still shift the EKF origin.

That's turned off by default... No EKF origin shifting happens now by default. And GPS baro drift compensation wasn't added now, it was already there (and not just for long flights), it just was changed to be disabled by default and an option added to correct reported altitude instead of the origin. Still, a slight shift in EKF origin altitude (only!) is much better than home jumping around!

> Target pos NED is still considered to be relative to home rather then origin (at least for altitude) already.

Yes, it is and I'll argue that's wrong any day of the week 😉 

> If you want to use ROS in a stable manner then don't move the home location? 

Really?

> Home moves only under a specific set of very controllable circumstances, and if set from a GCS won't automatically move again

Well if a GCS changing it without user intervention isn't automatic then I don't know what is...

> If EKF origin must never shift in flight/after power on that limits Paul's ability to compensate over time.

And why does the EKF origin need to be shifted over time? I'll say again, it doesn't with master (or at least it's not supposed to).

**Comment by WickedShell** [comment]
> (or at least it's not supposed to).
This is my biggest worry, is last time I pointed at it shifting it was a surprise to people that it was, in general no one looks at what the EKF origin does except when things go wrong (or in my case when I was reviewing the original changeset), so it's quite easy to have this changing and have no one notice for a long time.

> Well if a GCS changing it without user intervention isn't automatic then I don't know what is...
The same comments apply here though, the GCS doesn't update home by default or have any good reason to ever do so. You have to opt into this behavior. I'd argue quite happily though that the EKF features of drifting the origin hold far more value then the GCS ones.

> Yes, it is and I'll argue that's wrong any day of the week :wink:
Can we agree that changing one without the other is actually worse, because now you have a situation where setting a target of {1, 2, 3} can result in the aircraft reporting it's at {0, 2, 5} with 0 meters of error which is even worse for the GCS.

**Comment by OXINARF** [comment]
> This is my biggest worry, is last time I pointed at it shifting it was a surprise to people that it was, in general no one looks at what the EKF origin does except when things go wrong (or in my case when I was reviewing the original changeset), so it's quite easy to have this changing and have no one notice for a long time.

It was a surprise, but EKF maintainer knew about it. What you are talking about now would be either a bug or a hidden change, both of which are not only unlikely to happen but also completely different than what happened before - Paul did the drift correction with good intention, it was just people weren't aware of it (which happens frequently unfortunately - as just happened on Gitter - but that's normal when people don't look at all code).

> The same comments apply here though, the GCS doesn't update home by default or have any good reason to ever do so. You have to opt into this behavior. I'd argue quite happily though that the EKF features of drifting the origin hold far more value then the GCS ones.

Yes, you do have to opt-in in both cases. But a home change will likely have several meters of difference, while the EKF origin drift won't - and the EKF origin only changes altitude, while home changes the location.
I still don't see why you need EKF origin drifting though, it makes way more sense to use a corrected altitude report - if the baro drifts over time what ends up being incorrect is the current altitude, not the altitude that was set on boot.

> Can we agree that changing one without the other is actually worse, because now you have a situation where setting a target of {1, 2, 3} can result in the aircraft reporting it's at {0, 2, 5} with 0 meters of error which is even worse for the GCS.

No, I don't think it's worse because the position taken in target pos NED is relative to origin, not to home. So if someone uses the current reported local position it will be wrong if home isn't close to origin. Yes, altitude will still be wrong, but I think that's better than having a location being entirely wrong. I'll also mention this was a change from previous ArduPilot versions, it did report the local position according to origin.
By the way, the altitude issue is much larger than just this. We use altitude above home in many code places and that's a very bad idea given how volatile home is.

**Comment by sharvashish** [comment]
Hi,

@OXINARF, I will make sure to abide by the commit rules next time.

@WickedShell, I am sorry if my understanding is wrong, but I think home not only moves via GCS but also when copter arms. Is this wrong? So if a vehicle does a flight, then disarms and arms again, there is a jump in local position. Moreover, even in the logic of local position wrt home, it is dead wrong.  In my observation, when vehicle disarms and arms again, new lpos should be (0,0) but its value becomes double of what it was before disarming.

Also, in my little understanding of the code, position controller also uses position estimate wrt origin. So if the controller can use position data wrt origin, why can it not be sent via mavlink.

**Comment by chobitsfan** [comment]
I think it would be helpful that LOCAL_POSITION_NED use EKF origin as ref
Hi @WickedShell Would you mind reconsidering it? Thank you very much

**Comment by WickedShell** [comment]
I'm still very opposed to this, don't forget that the origin isn't even currently the same between all your EKF cores, which would lead to sudden/surprising shifts.

**Comment by rmackay9** [comment]
@WickedShell, I think the EKF cores all use the same origin now don't they?  I think they must or we have a larger problem with Copter navigation which is based on using the ekf origin.

**Comment by WickedShell** [comment]
@rmackay9 ah it did get fixed in 742ae0b750aa008e9adc99fcfb273e0faa3ef27a I'd forgotten that had actually made it in. I came across #11527 the otherday which was still open and that's why I'd thought we hadn't fixed it yet.

**Comment by rmackay9** [comment]
My feeling on this change is that what's reported should be consistent to how we consume the [SET_POSITION_TARGET_LOCAL_NED](https://mavlink.io/en/messages/common.html#SET_POSITION_TARGET_LOCAL_NED) message.

Plane only seems to use the Z-axis.  Copter uses all three but strangely seems to interpret x and y as offset from the EKF origin but Z offset from home which just can't be right.  https://github.com/ArduPilot/ardupilot/blob/master/ArduCopter/GCS_Mavlink.cpp#L1062

My guess is that what's in this PR is correct and it should all be done off the ekf origin.  This makes sense for people flying in a non-GPS environment which are probably the most common users of this message and the SET_POSITION_TARGET_LOCAL_NED.  If we use the home position then the values will change every time the Copter or Rover is armed.

I think there are a few ways to move forward:

1. We can talk it out on a dev call and try and come to an agreement
2. We can add a bit to the DEV_OPTIONS parameter to allow the user to get the behaviour they want
3. We can make plane act differently than Copter and Rover.

**Comment by chobitsfan** [comment]
Thank you @WickedShell and @rmackay9 

> home is controlled by the ground station and doesn't just move, while origin can drift on altitude over time through the EKF.
home is where you actually armed the aircraft and relative to it will be consistent through out a flight.

In `get_relative_position_NED_home()`. It calls `get_relative_position_NED_origin()`  to get current location relative to origin
https://github.com/ArduPilot/ardupilot/blob/d0d7a46492e56dcc4d8f66d037f9d9ee53658650/libraries/AP_AHRS/AP_AHRS_NavEKF.cpp#L1000
So relative to home is not consistent if ekf origin drift

**Comment by rmackay9** [comment]
In general I think the EKF origin does **not** move while home moves regularly either as part of arming or because the user moves it.

There are theoretically some cases where the EKF will drift the origin as it struggles with the inconsistent baro altitude vs GPS altitude but in practice this doesn't happen as far as I know.  There was a bug in the EKF for many years that meant in copter it never happened.  That bug has been fixed now but I think in practice is still can't happen at least in Copter perhaps because by default at least, it's configured so that it doesn't happen.  Sorry to be so vague but it's been at least a year since I've thought about this.

**Comment by chobitsfan** [comment]
Thank you @rmackay9 

In https://github.com/ArduPilot/ardupilot/pull/6893#issuecomment-327354316 and https://github.com/ArduPilot/ardupilot/issues/6830#issuecomment-326693372. @WickedShell mentioned that relative to home is more consistent (than relative to origin). I'm afraid that's not quite true because `get_relative_position_NED_home()` use `get_relative_position_NED_origin()`

**Comment by peterbarker** [comment]
On Fri, 31 Jul 2020, WickedShell wrote:

> I'm still very opposed to this, don't forget that the origin isn't even
> currently the same between all your EKF cores, which would lead to
> sudden/surprising shifts.

I believe that's been fixed - at least on each EKF version.

I have a branch around here somewhere which attempts to give us a single 
global origin - including for DCM.

**Comment by rmackay9** [comment]
With the growing number of people doing non-GPS navigation I've had this issue come up twice this week amazingly.  Once in the vision projects discord channel and then once more from my main sponsor.  As soon as I can get someone to confirm it resolves their issue I'll fix the commit description and merge I think... so last chance for any objections!

**Comment by rmackay9** [comment]
I've created a new PR with this fix and I plan to merge it after it passes Travis.  The new PR is the exact same change and attribution is still to @sharvashish.   I've simply fixed the commit message.

Thanks again for this fix and sorry it took so long!

**Pull request closed without merging**
