### PR TITLE
Return failure in pre_arm_check if unhealthy

### PR DESCRIPTION
**Pull request by peterbarker**
Fixes compilation with no EKFs compiled in ... ret is unused otherwise.

### CODE REVIEW

**Comment by tridge** [comment]
needs testing with:
 - plane takeoff without mag
 - compass_learn=3

**Comment by rmackay9** [comment]
I think we should check on Rover and Copter that we can arm in Manual or Stabilize with no position estimate.

**Comment by tridge** [comment]
i think this will cause stabilize and alt_hold mode failing to arm indoors when you have poor gps lock, due to EK3 healthy() logic

**Comment by peterbarker** [comment]
.... I've just looked again at this.

The `switch` statement this code is in is your *configured* EKF type.  The changes here to check `ret` *only* affect you if your *configured EKF type* is DCM or ExternalAHRS - AFAICS this does *absolutely nothing* if your configured type is EKF2/EKF3 (Copter also never allows a configured EKF type of DCM, squashing it to an EKF).

DCM *already* includes "healthy" in its prearm check (in AP_AHRS_DCM::pre_arm_check), so it is unaffected.

Both the LORD and VectorNAV backends already call `healthy()` - so this is also a no-op there.

So this should be a no-op in terms of how our pre-arms work.

**Comment by peterbarker** [comment]
... also, it means tridge's thinking on not being able to arm in alt_hold with a bad position is actually a problem in master if it is a problem as we already use `ret` for the EKFs...

**Comment by rmackay9** [comment]
Great, I guess just to get it in it would still be good to test those items Tridge mentioned but it seems clear they won't be a problem.

**Review by tridge — APPROVED** [review]

**Pull request merged**
