### PR TITLE
Plane: use dead zone in stick mixing

### PR DESCRIPTION
**Pull request by tridge**
prevent small stick offsets causing navigation errors

### CODE REVIEW

**Review by IamPete1 — COMMENTED** [review]
Good idea. Will need testing in every mode, I would be un-surprised to find other cases were were not updating them.

We might need to cache old values for MAVLink to report?

**Comment by tridge** [comment]
> We might need to cache old values for MAVLink to report?

I think the mavlink output will always happen after the mode up, but if mavlink moved to its own thread we could be in trouble.
I'm more concerned about possible access to these variables in scripting and things like FrSky telem. I haven't traced through any possible issues there yet

**Comment by tridge** [comment]
@IamPete1 maybe we need a set_nav_roll() and set_nav_pitch() call, which set a boolean to say they have been updated, and if false when we output then zero?

**Comment by tridge** [comment]
check rudder for dz usage

**Pull request merged**
