### PR TITLE
Frame_params: add standard bluerov2 parameter file

### PR DESCRIPTION
**Pull request by jaxxzer**

### CODE REVIEW

**Comment by rmackay9** [comment]
@jaxxzer, I think we should remove all the default parameters and parameters that are board specific (like compass calibration parameters).

**Comment by jaxxzer** [comment]
Hi @rmackay9, thanks for taking a look. You're right, I meant to omit the calibration parameters but grabbed the wrong file.

I want the defaults here in order to provide a clean slate in fewer steps for the user (and me, when I'm helping someone troubleshoot).

**Comment by jaxxzer** [comment]
I'm ready for this if it won't break anything.

**Comment by rmackay9** [comment]
@jaxxzer, definitely better.

There are many other parameters which are still set to their defaults though.  For example COMPASS_CAL_FIT and MOT_BATT_CURR_MAX.  The user always has the option to revert to the factory defaults easily (http://ardupilot.org/copter/docs/common-parameter-reset.html).  So for me, the "nuclear option" for the user would be to do the factory reset, re-apply the standard param file and then re-do the calibration (accel, compass, rc, failsafe, flight mode setup).  I guess others (you and Matt, the solo maintainer) perhaps prescribe to the method that many of the defaults appear again in the file so if the user has perhaps changed them, they are reverted to the factory defaults.  The issue I see with this is:

- float parameters could be overwritten with just slightly different-from-default values due to rounding errors and we could fill up the eeprom (unlikely but it could happen if we attempted to save a non-default value for every parameter)
- requires extra maintenance because each time we change a default in the code we need to remember to also change the default parameter files.

In the end, you're the maintainer so it's really up to you of course.  If you're happy with the parameter file, I'm happy to merge it.  .. or you can even merge it yourself.

**Comment by jaxxzer** [comment]
Thanks Randy,
At the moment we do not support compass calibration and current limiting, so I want these to always be the default. Great point about floats, I don't think this is happening, but I will look into it and fix it up if it is. The maintenance is no problem, this will make things easier for me already :)

-Jacob

**Pull request merged**
