### PR TITLE
Added RC option to force disable GPS yaw

### PR DESCRIPTION
**Pull request by tridge**
This is very useful when testing impact of loss of GPS yaw in flight

### CODE REVIEW

**Comment by rmackay9** [comment]
I wonder what the logic is for the RC auxiliary switch numbering.  It seems like the KillIMU options were purposely put at 100.. but then RunCamMode took 102 instead of a number in the 80s.  and now this GPS Disable Yaw has taken 105 leaving 103 and 104 unused.

It's not a big deal but not following any pattern seems odd to me.

**Comment by rmackay9** [comment]
sadly it looks like the CAM_MODE_TOGGLE got out in the Copter-4.0 release so now it's locked in forever :-(.

**Comment by peterbarker** [comment]
Randy and I just discussed this.  We agree CAM_MODE_TOGGLE was a goof, but this PR didn't do anything wrong.

I've created https://github.com/ArduPilot/ardupilot/pull/14635 to try to avoid another `CAM_MODE_TOGGLE`

**Comment by andyp1per** [comment]
Phew, thought it was me - pretty sure the runcam values are in the 70's

**Comment by rmackay9** [comment]
@andyp1per, yes, you are off the hook.  Not that it matters that much but it was [this PR](https://github.com/ArduPilot/ardupilot/pull/13528).

**Pull request merged**
