### PR TITLE
EKF: update is-flying check for non fly-forward vehicle types

### PR DESCRIPTION
**Pull request by priseborough**
These changes enable the is-flying checks to pass for low flying  non fly forward vehicle types (eg copters).

### CODE REVIEW

**Comment by magicrub** [comment]
Would be nice to unify the is flying stuff... We have 3 we are maintaining. Ekf3, ekf2, and isflying.cpp.

**Comment by tridge** [comment]
I just realised this change won't work well with helicopters, as they often sit on the ground armed for quite a while

**Comment by priseborough** [comment]
My preference would be to pull the isFlying and onGround logic out of the EKF and use what the platform code provides.

**Comment by priseborough** [comment]
We should revert these patches and work on a longer term fix.

**Comment by tridge** [comment]
I've submitted https://github.com/ArduPilot/ardupilot/pull/6458 to use vehicle is_flying state in EKF

**Pull request merged**
