### PR TITLE
Rename HAL_GPIO_A_LED_PIN to AP_NOTIFY_GPIO_LED_1_PIN

### PR DESCRIPTION
**Pull request by peterbarker**
... and correct the hwdefs to use the new define.

Based on discussions with @Hwurzburg

### CODE REVIEW

**Comment by Hwurzburg** [comment]
I like it....but are you doing the same for 2 and 3 led?

**Review by Hwurzburg — APPROVED** [review]

**Comment by peterbarker** [comment]
> I like it....but are you doing the same for 2 and 3 led?

What do you think they should be named?

**Comment by Hwurzburg** [comment]
same pattern
define AP_NOTIFY_GPIO_LED_1_PIN x
define AP_NOTIFY_GPIO_LED_2_PIN y
define AP_NOTIFY_GPIO_LED_3_PIN z

**Comment by peterbarker** [comment]
> same pattern define AP_NOTIFY_GPIO_LED_1_PIN x define AP_NOTIFY_GPIO_LED_2_PIN y define AP_NOTIFY_GPIO_LED_3_PIN z

The _1 refers to the fact it's the pin for the LED_1 driver, 'though.

Could be this:
```
define AP_NOTIFY_GPIO_LED_2_A_PIN x
define AP_NOTIFY_GPIO_LED_2_B_PIN y
```

and
```
define AP_NOTIFY_GPIO_LED_3_A_PIN x
define AP_NOTIFY_GPIO_LED_3_B_PIN y
define AP_NOTIFY_GPIO_LED_3_C_PIN x
```

>

**Pull request merged**
