### PR TITLE
FMUv2: re-add uavcan for FMUv2

### PR DESCRIPTION
**Pull request by tridge**
this re-adds uavcan and instead drops some esoteric GPS drivers and compass drivers for FMUv2, allowing uavcan to be used on older pixhawk1 boards

### CODE REVIEW

**Comment by magicrub** [comment]
Will removing oreoled effect solo on master?

**Comment by tridge** [comment]
no, the oreoled.bin is for upgrading the firmware of the i2c oreoled devices
apparently that doesn't work at the moment anyway

**Comment by OXINARF** [comment]
LGTM

**Comment by proficnc** [comment]
Oreoled is for Solo only, so v3, it needn't be in v2

**Comment by proficnc** [comment]
Speaking of which... where is the source kept for the oreoled.bin that's in the GPLv3 master?

**Comment by OXINARF** [comment]
@proficnc Nowhere, we only have the binary.

**Pull request merged**
