### PR TITLE
UARTDriver: add option to create uart connection to file

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by peterbarker** [comment]
Can be useful for testing serial parsers with real data.

**Comment by tridge** [comment]
the problem is the pacing of the data, it would be better to have a small py script that reads a file at a given rate and sends to a tcp port

**Comment by peterbarker** [comment]
@tridge true enough.  What I'd like is to finish up my write-pcap-file and feed that into such a script.  

The protocol I was working with here was a time-independent capture which provided useful exercise for the parser.

It's nothing that can't be done with socat and a tcp port - it's just more hassle.

It also occurs to me that file could probably be a pipe, 'though....

Kill this or keep it?

**Comment by tridge** [comment]
I needs a NMEA capture as input tonight, and did this:
https://github.com/tridge/junkcode/blob/master/python/file_to_tcp.py
it assumes a line based protocol. It allowed me to find the issue for this report v quickly:
https://discuss.ardupilot.org/t/how-to-pass-it-on/53832/16

**Comment by peterbarker** [comment]
No appetite for this in master.

**Pull request closed without merging**
