### PR TITLE
fixing wxpython package name

### PR DESCRIPTION
**Pull request by imriss**

### CODE REVIEW

**Comment by WickedShell** [comment]
Looks reasonable to me. I have wxpython installed, wxpython2.8 isn't a valid target. Not sure why we need wxpython per se, but I have installed it and the current package is not correct so this is definitely better then the current script.

**Comment by WickedShell** [comment]
(For the record this script doesn't work as of when I installed my arch system, but I didn't even try and debug it, just installed packages as I needed them).

**Comment by OXINARF** [comment]
Ubuntu had the same name change of this package. Looking in Arch website this looks correct - they don't keep old versions so it's all good.

@imriss We'll fix it for you since this is your first contribution, but please read our contribution rules for a next time (mainly the commit message spec): ardupilot.org/dev/docs/submitting-patches-back-to-master.html

**Comment by imriss** [comment]
Thanks. I will follow the rules from now.

I also use Arch Linux with the latest packages. There is another change need for this script that I will commit as soon as possible.

**Comment by magicrub** [comment]
needs a squash, but otherwise LGTM

**Comment by WickedShell** [comment]
Why is lib32-glibc installed that way?

**Comment by imriss** [comment]
lib32-glibc is from the Multilib repo. That way of installation does not need that the Multilib repo is enabled.

**Comment by WickedShell** [comment]
Why not just install lib32-glibc through pacman?

**Comment by imriss** [comment]
If multibib repo is not enabled, pacman cannot install it. I prefer to keep the multibib repo disabled.

**Comment by OXINARF** [comment]
@WickedShell I've never used Arch so I'm going by your advice here. From what I could gather multilib is disabled by default, which means that trying to install a 32-bit library with pacman is going to fail. I don't quite like to do a direct download though. Should we instead check for the availability of the multilib repo and warn the user if it isn't enabled? It already asks the user to install yaourt.

**Comment by WickedShell** [comment]
Ah, okay I had forgotten that...

I suspect requiring multilib is still better however. If we require a 32bit lib to work with ArduPilot, then fundamentally we are a multilib project, and I think reflecting that in the enable list is worthwhile.

@OXINARF Honestly the best approach for a Arch would be if we maintained our own AUR package. That's a more work however, and not something I can stick my hand up for. Installing yaourt is a bit poor IMO. There are a large number of AUR tools that exist out there, yaourt is just one of them (it is one of the more popular ones, I personally use it) and it feels a bit weird to just force the dependency on top for a user. But by the same token, the user has selected to run this script so maybe it's fine.

**Comment by OXINARF** [comment]
@WickedShell @imriss What do you guys think of https://github.com/ArduPilot/ardupilot/compare/master...OXINARF:review/5873?

**Comment by imriss** [comment]
@OXINARF It looks good for the green field cases. However, if a package from multilib has been already installed (by any means) and then the multilib repo is disabled, the condition will not notice it.

**Comment by lucasdemarchi** [comment]
Just require multilib to be present. 2 line entries in the conf that's probably useful for more things.

The good question is actually why we actually need these 32-bit libraries :)

**Comment by lucasdemarchi** [comment]
First commit with name change cherry-picked. For the way it's installing the 32bits version of glibc I don't think is a good idea.  `--needed` would just not reinstall packages, so I think it's fine not passing it.  Let's close this for now since it supposedly fix that the PR proposes to.

**Comment by OXINARF** [comment]
> The good question is actually why we actually need these 32-bit libraries :)

PX4 compiler is only available in 32-bit...

> For the way it's installing the 32bits version of glibc I don't think is a good idea

Why?

> --needed would just not reinstall packages, so I think it's fine not passing it.

I'm not fussed about it, but it is nice to not reinstall unneeded packages - specially if you have a version installed you don't want replaced.

**Pull request closed without merging**
