### PR TITLE
Frsky: improve capabilies and compatibility of Smart Port implementation

### PR DESCRIPTION
**Pull request by hsteinhaus**
With the introduction of the Smart Port protocol, FrSky has extended the width of the data fields from 16 to 32bits. The current Smart Port code runs in a kind of a compatibility mode, using only 16 bits of 32 and filling the rest with zeros. Larger values are split into multiple frames, effectively doubling the bandwidth required.

This PR adds some marginal extensions to the transfer code, that allows to send true Smart Port datagrams. I have also added Smart port versions of datagram functions, while trying to keep the impact on existing hub frame code minimal. The over-all update rate of most information has significantly improved. Additionally some information about attitude, climb rate and GPS HDOP are now sent, as the changes freed up lots of link bandwidth. 

Together with OpenTx 2.1, almost all data fields are auto-detected with their correct units, as they use reasonable FrSky sensor ids.

### CODE REVIEW

**Comment by mirkix** [comment]
@hsteinhaus Hi Holger, I tried your PR with my BBBmini, X8R, X9D+ with OpenTX 2.1.7 When I discover new sensors I get multible instances of senors with different IDs until I get `All telemetry slots full`. Do you have any ideas?
 
rp

**Comment by hsteinhaus** [comment]
@mirkix Tnx for the report. Never seen this problem before. Could you try to clear all sensors and start over again? What kind of interface circuitry do you use?

**Comment by mirkix** [comment]
@hsteinhaus Hi Holger. That does not help. When all sensors are cleared and I start discover again, I get some thing after a short time. The X8R is connected via SPC and FrUSB-3 (FUC-3) to the BeagleBone USB Port.

**Comment by mirkix** [comment]
@hsteinhaus Do you know where the sensor ID is set?

**Comment by hsteinhaus** [comment]
Closing this old PR - 32bits telemetry data went into master in between.

**Pull request closed without merging**
