### PR TITLE
EKF: Match handling of MAV_CMD_EXTERNAL_POSITION_ESTIMATE to common MAVLink dialect

### PR DESCRIPTION
**Pull request by Maarrk**
This is a minor follow up to #23903. The feature works great, thanks a lot! I ran into some minor surprises when implementing support for it in our GCS. I initially wrote the code based on the [MAVLink docs for MAV_CMD_EXTERNAL_POSITION_ESTIMATE](https://mavlink.io/en/messages/common.html#MAV_CMD_EXTERNAL_POSITION_ESTIMATE), and found that frame and accuracy weren't handled as I expected.

Accuracy is explicitly advised to be set to NaN if unknown:
> estimated one standard deviation accuracy of the measurement. Set to NaN if not known. [source](https://github.com/mavlink/mavlink/blob/bcdbeb7f07906490fbc945fb5e2db29bad1196d7/message_definitions/v1.0/common.xml#L2489)

But I found that it was stopping the whole autopilot when I tried that in SITL (`Connection reset or closed by peer on TCP socket`)

---

I assume that [MAV_FRAME](https://mavlink.io/en/messages/common.html#MAV_FRAME) sent in COMMAND_INT should behave the same way for [MAV_FRAME_GLOBAL](https://mavlink.io/en/messages/common.html#MAV_FRAME_GLOBAL) and [MAV_FRAME_GLOBAL_INT](https://mavlink.io/en/messages/common.html#MAV_FRAME_GLOBAL_INT) ([a search of the repo](https://github.com/search?q=repo%3AArduPilot%2Fardupilot%20MAV_FRAME_GLOBAL_INT&type=code) shows them together), but only the first one was accepted in the check.

*(Contribution on behalf of @FlyfocusUAV)*

### CODE REVIEW

**Comment by rmackay9** [comment]
Hi @Maarrk,

Could you update the commit title so that it starts with "AP_NavEKF3:"?  Adding the prefix makes backporting easier because we can immediately see what subsystem is affected by a change.  To be clear, I'm talking about the commit title not the PR title.

**Comment by rmackay9** [comment]
@Maarrk,

Could you also tell us what testing has been done?  Knowing this will give us more confidence that merging is safe.

**Comment by Maarrk** [comment]
Hello @rmackay9,
thanks for the quick reply. I rebased onto `master` and changed the commit message as requested.

I have tested the code in SITL with ArduPlane. During flight, I disabled GPS with MAV_CMD_DO_AUX_FUNCTION, and then sent the command through GCS.

Didn't change interacting through MAVProxy "Set Position" (sending MAV_FRAME_GLOBAL and accuracy 50), and worked as expected with our custom QGroundControl (sending MAV_FRAME_GLOBAL_INT and accuracy NaN).

At the moment it's hard for me to give you a precise date when I'd have a chance to fly this code on real hardware. Do let me know if you'd like me to change one of the calls in autotest to use these newly supported values, for example here:

https://github.com/ArduPilot/ardupilot/blob/2d5e6a5f98d95f50af76f72ff3862fe6c78e63da/Tools/autotest/arduplane.py#L703-L713

**Review by tridge — APPROVED** [review]

**Comment by peterbarker** [comment]
I've fixed up the commit list and marked this as MergeOnCIPass.  Thanks!

**Pull request merged**
