### PR TITLE
AC_Fence: able to use polygon fence as stay-out zone

### PR DESCRIPTION
**Pull request by chobitsfan**
A simple but not complete solution for #391 and #1056. I need no-fly zone/stay-out zone for my current project. So I make a quick solution.

It use geofence code to implement stay-out zone.  By setting FENCE_ENABLE = 2.  It makes polygon fence become stay-out zone. Setup procedure is identical to polygon geofence using mission planner.  It is possible to use circle/altitude geofence along with polygon stay-out zone.

Current limit:
1. Only polygon stay-out zone is supported
2. Only one stay-out zone is support

### CODE REVIEW

**Comment by chobitsfan** [comment]
SITL video https://youtu.be/MNRz7ivJNzY

**Comment by chobitsfan** [comment]
Hi @OXINARF Thank you for your feedback.

I found there is no need to modify AC_Avoidance code. just modify AC_Fence is enough. Because only AC_Fence code is modified. Users only need to set FENCE_ENABLE.

**Comment by chobitsfan** [comment]
I found it is possible to use circle/altitude geofence along with polygon stay-out zone. We can have both circle/altitude geofence and polygon stay-out zone in the same time. Although still not complete, I think it should meet most case need.

**Comment by rmackay9** [comment]
By the way, I think we will add stay-out zones soon-ish.  The first step is going to be getting the zones into AP from the ground stations and then getting that integrated in AC_Avoid.  There may be some bits we can steal from this PR for that.

**Comment by reidaruss** [comment]
@rmackay9 You wouldn't happen to have a timeline for this implementation would you?

**Comment by rmackay9** [comment]
@reidaruss, @peterbarker has [this in-progress PR](https://github.com/ArduPilot/ardupilot/pull/10409) that is the core bit we need to get done as a first step to getting stay-out zones supported.

**Pull request closed without merging**
