### PR TITLE
Merge branch 'ArduPilot:master' into master

### PR DESCRIPTION
**Pull request by AlfredBaum**
v0.1

### CODE REVIEW

**Comment by AlfredBaum** [comment]
v0.1

**Comment by khancyr** [comment]
Hello  
What are you trying to do ?
Here you are pushing your change to ArduPilot main repository. To have your change accepted you need to provide some description of what you change and follow our contribution rules. 
Please see https://ardupilot.org/dev/docs/contributing.html

If you need help, please ask on discord or discuss.

**Comment by AlfredBaum** [comment]
v0.1

**Comment by khancyr** [comment]
No answer. Closing then. Please don't push a pull request on ArduPilot but only on your own repository for development. Thank you

**Pull request closed without merging**
