### PR TITLE
ChibiOS: STM32H7 support

### PR DESCRIPTION
**Pull request by tridge**
This is a work in progress branch for supporting STM32H7 MCUs. I am starting with a STM32H743, using the Nucleo board. This involves a rebase of ChibiOS on upstream master to get H7 support. The first steps are fixing the build on F1, F4 and F7 MCUs for the changes in the ChibiOS API

Many thanks to Holybro for sponsoring this work!

Steps:
 - [x] build F4 MCUs with ChibiOS master
 - [x] build F1 and F7 MCUs with ChibiOS master
 - [x] build H743 bootloader
 - [x] build minimal hello world firmware for H743
 - [x] port main firmware to H743
 - [x] full 1Mbyte of memory

This has been successfully flight tested by Holybro.

Issues:
 - CAN not working
 - SDMMC not building

I believe this is ready for merging into master now. I will add SDMMC and CAN support as a separate PR

### CODE REVIEW

**Comment by proficnc** [comment]
Thanks Tridge! 
Somewhere on your desk is an Orange cube with H7 written on the top :)

we will send you an actual production version very soon!

**Comment by tridge** [comment]
thanks @proficnc, I've found it
I'm targetting the Nucleo H743 initially, as bringup on a new MCU is much easier on the nucleo boards due to easy pin access and debugging.

**Comment by proficnc** [comment]
Very good, it’s the same chip, so hopefully that helps

**Comment by rmackay9** [comment]
I flew this branch on my ancient IRIS and it flew a-ok.  I didn't notice any differences from it's regular behaviour.

**Pull request merged**
