### PR TITLE
Update Parameters.cpp

### PR DESCRIPTION
**Pull request by proficnc**
the value for the skip arming voltage was set to 127, which is actually the value for All.....
I believe it should be -128
Please confirm.

### CODE REVIEW

**Comment by magicrub** [comment]
Wow, I never realized how unintuitive those values are for copter.

**Comment by OXINARF** [comment]
I would rather prefer to change the description to positive values for the ones that people want to enable.

Plus, does this even work? I mean, isn't -3 represented as 11111101 in virtually all boards? Or does the parameter system use a 1's complement?

**Comment by rmackay9** [comment]
Ah, I think we want 126 instead of 127.  127 is 01111111 which is almost what we want except the first bit "all" is checked.  We need the first bit and last bit as zero.

I have a PR coming some day which switches copter over to use the AP_Arming lib which has a much larger field to hold the bitmask and allows us to remove the negative numbers.

Thanks @proficnc

**Comment by rmackay9** [comment]
Of course, this now makes me think that we have them all wrong!  My guess is that mission planner uses the Bit values so we haven't noticed the mistakes.

**Comment by DonLakeFlyer** [comment]
QGC expects these to be bits. Check a box and QGC will "or" in the value, uncheck and it will and out ~value.

```
            onClicked: {
                if (checked) {
                    fact.value |= fact.bitmaskValues[index]
                } else {
                    fact.value &= ~fact.bitmaskValues[index]
                }
            }
```

screen shot 2016-04-13 at 2 05 38 pm

**Comment by rmackay9** [comment]
Ok, I tested this and the existing values (i.e. current master with no fixes) should all work fine.
Internally before it runs the check for any subsystem, it checks ((ARMING_CHECK == 1) || (ARMING_CHECK & <bitmask> > 0)).  So either 126 or 127 works.  -128 doesn't work, it actually sets the last bit which means only the voltage check is run instead of being skipped.

**Comment by lucasdemarchi** [comment]
@rmackay9 when moving to the library would be nice to get the values corrected. "All" should be an OR of all the options. Actually should be "~0" so it's future proof. This would allow the GCS to be smart and provide a different behavior for "All", because: what would mean to select "RC + Voltage + All"?

**Comment by rmackay9** [comment]
@lucasdemarchi, my feeling is that RC + Voltage + All would be the same as just "All".  At the moment it would be RC+Voltage which I think is weird.

**Comment by lucasdemarchi** [comment]
@rmackay9 that's why I think "All" should be a logic OR, so we make sure "All" would mean "All" regardless the other options

**Comment by lucasdemarchi** [comment]
and a logic or of all the bits is just "~0U"

**Pull request closed without merging**
