### PR TITLE
SITL: Webots2021b Compatible

### PR DESCRIPTION
**Pull request by HefnySco**
Webots 2021 is not compatible with current SIM_WEBOTS.
This is an update for the new version.
webots_two_quadX_1

### CODE REVIEW

**Comment by HefnySco** [comment]
@khancyr Kindly adivse.
Current SITL_WEBOTS is not longer compatible with current webots.
This is the new update.

**Comment by HefnySco** [comment]
**Do people still use the old Webots, or should we support just the new protocol?** 
The old Webots is replaced by the new one.
**Do we need a wiki update to go along with this?**
Yes very minor, and once this is merged I will publish the updates. However I already changed the [ReadMe](https://github.com/ArduPilot/ardupilot/pull/18337/files#diff-422460152f15f56c93445326c1589a875b7c271dad7c880b484450fad25a6a48) as part of this PR.

**Comment by tridge** [comment]
@HefnySco I've merged, and sent you an invite to join the github group so you can label PRs to ensure they get attention (eg. SITL or DevCall labels)
thanks for keeping us up to date with WeBots!

**Comment by halil93ibrahim** [comment]
Hi @HefnySco, do you have any plan to make it compatible with webots 2022a? Now, when I try to run it takes off but cannot keep the altitude but increase forever. If you could easily identify what should be done, I am open to helping with the implementation.

**Comment by HefnySco** [comment]
> Hi @HefnySco, do you have any plan to make it compatible with webots 2022a? Now, when I try to run it takes off but cannot keep the altitude but increase forever. If you could easily identify what should be done, I am open to helping with the implementation.

I already have the  upgraded code [here](https://github.com/HefnySco/ardupilot/tree/pr_SITL_webots_2022a) 

please check  ./libraries/SITL/examples/Webots/webots_2022/droneX_2022.sh   and run the Quadcopter sample at [./libraries/SITL/examples/Webots/webots_2022/worlds/webots_sitl_simple.wbt](https://github.com/HefnySco/ardupilot/tree/pr_SITL_webots_2022a/libraries/SITL/examples/Webots/webots_2022).

I tuned the Quadfcopter but not the TRICopter.

Thanks

**Comment by halil93ibrahim** [comment]
Thanks a lot!
I got `FCU: PreArm: Check mag field:    0, max 875, min 185` error when I try to takeoff. Should I disable some parameter?

**Pull request merged**
