### PR TITLE
AP_PolyFence - move plane's polyfence code into a library

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by tridge** [comment]
we'll need an update to the table in parameters.cpp to automatically upgrade users fence parameters

**Comment by rmackay9** [comment]
As a side note a number of users are keen for the polygon fence in copter so having it as a library (like this PR does) will probably make that easier.

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (407/400 (101%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o6.sgmail.github.com ([192.254.113.101]:31824)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-8f06-yann.dupuy=zyapps.com@sgmail.github.com>)
	id 1b8IXN-002DBm-TQ
	for yann.dupuy@zyapps.com; Thu, 02 Jun 2016 04:39:16 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=BucJE1+w+lqHBkblHUjyLw2gBnk=; b=wf9qS6MXrfQ/Gc0+
	sXSoM9CsYxpVhxQm8LjoIWsspzukytODisCHWN5cW/CEHiSDat71BA5du58Wscke
	mIS3lOQz6xA9Ui4Am8QSAw1kRr1hiY35VycA0C4YHzQuogDo3zvHin/HAhgz/JTS
	VvIv0Gme/YFMeVHXd5ykKWzLt+w=
Received: by filter0576p1mdw1.sendgrid.net with SMTP id filter0576p1mdw1.7773.574F9C1F40
        2016-06-02 02:38:23.565610927 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0003p1iad1.sendgrid.net (SG) with ESMTP id UwGy6YnvQz2hoPnZX_Wg6A
	for <yann.dupuy@zyapps.com>; Thu, 02 Jun 2016 02:38:23.564 +0000 (UTC)
Date: Wed, 01 Jun 2016 19:38:23 -0700

**Comment by peterbarker** [comment]
@rmackay9 @tridge I'm tempted to make the parameters namespace "FNC" rather than "FENCE_"; this will not conflict with Copter's existing namespace, which I think will make the transition easier.  Does that sound reasonable?

@rmackay9 "drickets" asked about PolyFence for copter recently on gitter, thus me pulling out this branch for a PR :-)

**Comment by tridge** [comment]
@peterbarker, the namespace is set by the caller in the vehicle code, so we can leave it as FENCE_* in plane and Randy could use FNC_ in copter if he would like to. I prefer not to change names of parameters unless there is a good reason.

**Comment by tridge** [comment]
how much testing of this have you done in SITL? Have you tested all the parameters and how it interacts with the AFS_* code?

**Comment by peterbarker** [comment]
I tested all parameters in SITL.  I have not tested interaction with AFS_* code.  Will do so now.

**Comment by peterbarker** [comment]
Seems to play nicely with AFS.

**Comment by peterbarker** [comment]
Commit added to copy parameter values from old locations.

**Comment by rmackay9** [comment]
Maybe we should put the new class into a directory called AP_Fence instead of AP_PolyFence and then I'll eventually merge AC_Fence into AP_Fence.

**Comment by magicrub** [comment]
Sounds good

**Comment by tridge** [comment]
I don't mind it being AP_Fence

**Comment by peterbarker** [comment]
Pushed up changes to make this move into AP_Fence/ rather than AP_PolyFence/ directory in libraries.

**Comment by OXINARF** [comment]
@peterbarker This failed Travis because path to the library class is now wrong: https://travis-ci.org/ArduPilot/ardupilot/jobs/135187227#L733

**Comment by peterbarker** [comment]
On Fri, 3 Jun 2016, Francisco Ferreira wrote:

> @peterbarker This failed Travis because path to the library class is now wrong: https://travis-ci.org/ArduPilot/ardupilot/jobs/135187227#L733

Fixed, thanks!  Adding build.Parameters to my mental checklist...

**Comment by rmackay9** [comment]
I've had a short look at this and I worry that there are some vehicle specific things in the AP_PolyFence class which will make it harder to integrate with Copter:
- ACTION - Copter has a small set of options.  Just Report-Only or RTL.  https://github.com/ArduPilot/ardupilot/blob/master/libraries/AC_Fence/AC_Fence.cpp#L27
- CHANNEL - Copter uses auxiliary switches and there are good arguments on each side as to whether the plane method (assign a channel to the function) or the copter way (assign a function to the channel) is best but being inconsistent within a vehicle is probably the worst thing to do so ideally we would move this out of the main lib. 
- _RETALT, _RET_RALLY parameters, like _ACTION, customise the response to a breach and this response is quite different in copter.
- update_pwm_enabled_state, should_revert_flight_mode, guided_destinations_match, oldSwitchPosition, vehicle_in_mode_guided, vehicle_in_mode_rtl, revert_mode, do_breach_action_guided seem very closely tied to how the pilot input or failsafe response to the breach is handled.

Conversely I wonder if we could move handling of the mavlink messages, MAVLINK_MSG_ID_FENCE_POINT and MAVLINK_MSG_ID_FENCE_FETCH_POINT into the AP_PolyFence library.  the send_status is already in the library so handling both input and output to mavlink makes sense to me.

As a side note, I guess we can delete, "geofence_check_maxalt" and "geofence_check_minalt"?

**Comment by rmackay9** [comment]
To be clear though, it's good work on a difficult problem!

**Comment by peterbarker** [comment]
Thanks Randy!

I'll preface my comments by saying that after recent debacles with complicated patches I try to keep things as simple as possible.  In this case I didn't want to change the way the program flow worked, so (e.g.) leaving the fence-disable-check in the top of check() was intentional.  This dragged some code in - like the "channel" stuff - that will move back into AP_PolyFence_Plane.  This patch was only supposed to be about changing the location of the code, not the way it functioned.

ACTION: Copter can simply support a subset of the enumeration.  Some of the plane options even make sense for Copter, really - "return to centre of fenced area" would be good for training purposes, I'd think.  Also, the new "stop at fence" code would give Copter something that Plane didn't in terms of actions (ignoring QuadPlane anomalies).  Having the handling in here means that we get a consistent interface between the vehicle types, with no confusingly-similar variables.  It's the fact that fences have actions that puts the variable in the library, the fact that the vehicle actions only overlap is  an unfortunate facet of reality leaking in.  IMO :-)

CHANNEL: Fair point, but AP_Param fence_channel belongs in the fence code I reckon :-)  On adapting this for Copter g.fence_channel would probably change to a user_enabled() or perhaps user_disabled_by_rc() pure virtual method.  Plane would look at fence_channel, Copter would... not...  This has the disadvantage that the parameter would appear for Copter but the comments would indicate "*Plane only*"..  (Distracting aside: using x_channel allows libraries to be self-contained.  channel_func ensures that/limits you to having one function per channel.  x_channel would theoretically allow you to divide the range for additional functionality).  We should have a conversation about _channel vs rcx_function, anyway.

RETALT, _RET_RALLY parameters: I thought those variables *would* be applicable for Copter?  retalt certainly, but also RET_RALLY if return-to-rally-point functionality was added.  For normal multicopters there's not much point, but for big helis, having it return to somewhere that isn't the launch point would be a good idea IMO!

On the variety of functions (update_pwm_state etc).  Many of those are candidates for moving into Plane.  Not done to try to keep the patch simple ATM, and in the hope that when doing the Copter update we can share as much code as possible.  For example, the "should revert flight mode" isn't relevant for Copter ATM - if you RTL, you land disarm.  If we started to support "move back to centre", we would have to start supporting revert-flight-mode.

The mavlink message parsing should be moved into the library, yes.

And the (preexisting!) variable typing can also be fixed :-)

Well spotted on the geofence_check_maxalt/minalt!

It does sound like we might end up with an "handle_breach" callback which has the vehicle-specific fence code take care of all of that.  It would be nice if we could share code and behaviour as much as possible, 'though.

**Comment by peterbarker** [comment]
Randy has put PolyFence support into Copter already.

**Comment by magicrub** [comment]
This old Fence PR is closed and marked as Plane but no mention if it went in for Plane. The fence stuff is currently Copter only, right?

**Comment by rmackay9** [comment]
So you've already got the polygon fence in Plane so I don't think this PR went in eventually.  The only thing I'd add is that we did create a class called a polygon loader that Plane could adopt.  Currently Plane's polygon loading is all within the plane vehicle code.
https://github.com/ArduPilot/ardupilot/tree/master/libraries/AC_Fence

**Pull request closed without merging**
