### PR TITLE
Parameters consistent explicit si units

### PR DESCRIPTION
**Pull request by amilcarlucas**

### CODE REVIEW

**Comment by WickedShell** [comment]
Why did you open all the individual PR's as well? They were all encompassed here, it's much easier to review this type of change here in a lump PR of multiple commits.

I admit I'm a bit ticked to wake up to about 40 e-mails of PR's that were then nicely lumped into a single PR here. In this case it's a lot more effort to review and merge each individual one, and you clearly got the collective PR done here.

**Comment by OXINARF** [comment]
@WickedShell There weren't individual PRs, but all commits mention us.

@amilcarlucas Next time you do so many commits don't put the @ in the commit message or that person will get spammed with an e-mail for every commit. Same for the issue number, just write "issue X" - if you go there now there is a huge list of commits where it was referenced.

I'd also like to make clear that we didn't exactly asked for these changes, we said that shortening the units wasn't a good idea.

You'll want to bring this to a dev call, it touches everywhere.

**Comment by WickedShell** [comment]
@OXINARF okay that makes sense, was writing the response from e-mail when I first woke up, hadn't actually pulled the issue open yet.

**Comment by amilcarlucas** [comment]
Sorry for the spam, I had no idea.

**Comment by magicrub** [comment]
I'd say we may want a @UnitLong: for this because many of those won't fit on the screen of a GCS that is trying to list them.

**Comment by amilcarlucas** [comment]
@magicrub The idea is to either have small and compact text that can be direcly displayed in the GUI of any GCS without having to hardcode anything in the GCS code #5517 

or

Have full fleadged complete SI unit names that people can better understand, and let the GCS have a small (40 entry or so) look-up-table that converts those in whatever unit they want, even imperial units is possible.

I do not think that the added complexity of adding @UnitsLong would be a feasable step.

**Comment by DonLakeFlyer** [comment]
QGC is coded to understand the following units designations (the first column in each):
```
// Built in translations for all Facts
const FactMetaData::BuiltInTranslation_s FactMetaData::_rgBuiltInTranslations[] = {
    { "centi-degrees",  "deg",  FactMetaData::_centiDegreesToDegrees,   FactMetaData::_degreesToCentiDegrees },
    { "radians",        "deg",  FactMetaData::_radiansToDegrees,        FactMetaData::_degreesToRadians },
    { "norm",           "%",    FactMetaData::_normToPercent,           FactMetaData::_percentToNorm },
};

// Translations driven by app settings
const FactMetaData::AppSettingsTranslation_s FactMetaData::_rgAppSettingsTranslations[] = {
    { "m",      "m",        false,  UnitsSettings::DistanceUnitsMeters,         FactMetaData::_defaultTranslator,                   FactMetaData::_defaultTranslator },
    { "meters", "meters",   false,  UnitsSettings::DistanceUnitsMeters,         FactMetaData::_defaultTranslator,                   FactMetaData::_defaultTranslator },
    { "cm/px",  "cm/px",    false,  UnitsSettings::DistanceUnitsMeters,         FactMetaData::_defaultTranslator,                   FactMetaData::_defaultTranslator },
    { "m/s",    "m/s",      true,   UnitsSettings::SpeedUnitsMetersPerSecond,   FactMetaData::_defaultTranslator,                   FactMetaData::_defaultTranslator },
    { "m^2",    "m^2",      false,  UnitsSettings::AreaUnitsSquareMeters,       FactMetaData::_defaultTranslator,                   FactMetaData::_defaultTranslator },
    { "m",      "ft",       false,  UnitsSettings::DistanceUnitsFeet,           FactMetaData::_metersToFeet,                        FactMetaData::_feetToMeters },
    { "meters", "ft",       false,  UnitsSettings::DistanceUnitsFeet,           FactMetaData::_metersToFeet,                        FactMetaData::_feetToMeters },
    { "cm/px",  "in/px",    false,  UnitsSettings::DistanceUnitsFeet,           FactMetaData::_centimetersToInches,                 FactMetaData::_inchesToCentimeters },
    { "m^2",    "km^2",     false,  UnitsSettings::AreaUnitsSquareKilometers,   FactMetaData::_squareMetersToSquareKilometers,      FactMetaData::_squareKilometersToSquareMeters },
    { "m^2",    "ha",       false,  UnitsSettings::AreaUnitsHectares,           FactMetaData::_squareMetersToHectares,              FactMetaData::_hectaresToSquareMeters },
    { "m^2",    "ft^2",     false,  UnitsSettings::AreaUnitsSquareFeet,         FactMetaData::_squareMetersToSquareFeet,            FactMetaData::_squareFeetToSquareMeters },
    { "m^2",    "ac",       false,  UnitsSettings::AreaUnitsAcres,              FactMetaData::_squareMetersToAcres,                 FactMetaData::_acresToSquareMeters },
    { "m^2",    "mi^2",     false,  UnitsSettings::AreaUnitsSquareMiles,        FactMetaData::_squareMetersToSquareMiles,           FactMetaData::_squareMilesToSquareMeters },
    { "m/s",    "ft/s",     true,   UnitsSettings::SpeedUnitsFeetPerSecond,     FactMetaData::_metersToFeet,                        FactMetaData::_feetToMeters },
    { "m/s",    "mph",      true,   UnitsSettings::SpeedUnitsMilesPerHour,      FactMetaData::_metersPerSecondToMilesPerHour,       FactMetaData::_milesPerHourToMetersPerSecond },
    { "m/s",    "km/h",     true,   UnitsSettings::SpeedUnitsKilometersPerHour, FactMetaData::_metersPerSecondToKilometersPerHour,  FactMetaData::_kilometersPerHourToMetersPerSecond },
    { "m/s",    "kn",       true,   UnitsSettings::SpeedUnitsKnots,             FactMetaData::_metersPerSecondToKnots,              FactMetaData::_knotsToMetersPerSecond },
};
```

Changing parameter units from the current ones above to different naming will completely break QGC's unit conversion capabilities for those parameters. Sure I can update this table to convert from the new names, but that doesn't help anyone running older builds of QGC. I would guess the same would be true for Mission Planner.

For most of these changes I don't see how making them wordier/longer really makes them any clearer.

**Comment by amilcarlucas** [comment]
The current units are not consistent:
https://github.com/ArduPilot/ardupilot/pull/5538#issuecomment-271818989

That means that the current code does not work in QGCS anyway.

**Comment by tridge** [comment]
Thanks for this work!
minor tweaks: I'd prefer "volts" to "volt", as other units are plural (eg. meters)
Like Randy, I also prefer the shorter names

**Comment by rmackay9** [comment]
As discussed on the dev call, could we switch to the shorter names?

**Comment by amilcarlucas** [comment]
This was voted against in the dev meeting, and #6182 (short SI units) was choosen instead.
All issues raised here have been addressed to the best of my knowladge in the #6182 

@DonLakeFlyer centi-degrees is the only unit that gets broken in that PR, but it was broken anyways because it was spelled in three different ways troughtout the code.

**Pull request closed without merging**
