### PR TITLE
Global: change from NULL to nullptr

### PR DESCRIPTION
**Pull request by muramura**
For NULL pointers, nullptr is more appropriate for C++.

### CODE REVIEW

**Comment by muramura** [comment]
@WickedShell san. Comments Thanks.
I change the generator file.

**Comment by WickedShell** [comment]
@muramura I'm not actually fully sure it's the correct change for the Lua code either way though, as the structure is getting passed to C code, and the sentinel is supposed to just be `{NULL, NULL}`. I'm not upto date enough with `nullptr` to speak to the value of that.

**Comment by muramura** [comment]
I think it is better to use nullptr defined in C ++ source to solve the NULL problem.

**Comment by rmackay9** [comment]
I've removed the dev-call-topic.

I suspect this hasn't been tested.  I'm afraid that all changes need to be tested so we can be sure they don't break anything.  Even NFC.  If that's not possible, let's close this.

**Comment by khancyr** [comment]
a flight test should be enough to validate this.
The change from NULL to nullptr ensure us that the compiler will do the right thing with pointer and not  use the value 0.
The analysis is already done by the compiler since nullptr is a pointer type and cannot be used with other litteral type such as int or float. Therefore, this change are checked at compile time and unsure that we are trully speaking of pointer and not need the 0 value ! I will provide a flight log next week

**Comment by peterbarker** [comment]
A flight test isn't enough to validate this.  We don't cross all of the relevant codepaths in a single flight.

This is now conflicting *horribly*, and it will probably be easier to redo from scratch.  However, I suggest a better way forward would be to just stay vigilant about eliminating `NULL` from the code in new PRs; since this was last rebased about 12% of the NULLs have died a natural death (rough grepping done).

I'm going to close this one as a lost cause.

I'm not convinced a similar PR will gain much traction - it doesn't buy us *that* much.  That being said, I'll look at any against `AP_Logger` and replay - they're some of the main offenders.

**Pull request closed without merging**
