### PR TITLE
standard spelling of "variant"

### PR DESCRIPTION
**Pull request by arikrupnik**
For some odd reason, the repository contains 22 instances of an unusual spelling of "variant" in comments. This PR replaces them with the standard spelling.

### CODE REVIEW

**Comment by peterbarker** [comment]
One commit per directory (sometimes we make exceptions for changes like this).

Commit message needs to prepend the directory.

The script `Tools/gittools/git-subsystems-split` will do both of these things for you - just run it and force-push the branch.

**Comment by arikrupnik** [comment]
Thank you for the guidance, @peterbarker I'm not sure the commit messages came out how you wanted them--the prefix is there but not the commit message. Did I run it with the wrong arguments? Do you want me to fix the messages by hand?

**Comment by peterbarker** [comment]
@arikrupnik Huh.  I've never seen the tool do *that* before!

I would hazard a guess that it got really confused by the quotes in your commit message - shell scripts and all that...

If you could fix them by hand that would be good.

**Comment by arikrupnik** [comment]
Here they are, fixed up by hand, and without quotes.

**Review by peterbarker — APPROVED** [review]
LGTM

**Comment by peterbarker** [comment]
Merged, thanks!

**Pull request merged**
