### PR TITLE
Extend use of AP_BATTERY_ENABLED

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by amilcarlucas** [comment]
Nice and modular, but what is the use case?
A vehicle without voltage measurement is a strange one :)

**Comment by peterbarker** [comment]
> Nice and modular, but what is the use case? A vehicle without voltage measurement is a strange one :)

Sid brought a PR to DevCall tonight which had to play games in the AP_Notify library because.... AP_Periph which can have a Notify device but not a battery monitor.

There are definitely many libraries we don't want on Periph (motors!), but I figured may as well get things working with our current boards.

This doesn't allow you to build anything but peripherals with the define disabled (AFAIK)!

It also helps point out where things should be grouped a bit, I think.

My goal with this PR is no-compiler-output-change-except-on-Periph-where-it-stops-nullptr-dereference

**Comment by peterbarker** [comment]
```
------------------------  ---------  --------------  -----  ------  ----  -----  -----  ---
Board                     AP_Periph  antennatracker  blimp  copter  heli  plane  rover  sub
ARK_CANNODE               -216
ARK_GPS                   -216
ARK_RTK_GPS               -216
AeroFox-GNSS_F9P          -208
FreeflyRTK                -208
Here4AP                   -200
HerePro                   -360
HolybroG4_GPS             -216
HolybroGPS                -208
MatekL431-DShot           -208
MatekL431-GPS             0
MatekL431-RC              -208
MatekL431-bdshot          -208
SITL_arm_linux_gnueabihf             0               0      0       0     0      0      0
SITL_x86_64_linux_gnu                0               0      0       0     0      0      0
Sierra-F405               -208
Sierra-F412               -216
Sierra-F9P                -208
Sierra-PrecisionPoint     -208
Sierra-TrueNavPro         -208
f303-MatekGPS             0
rGNSS                     -208
sw-nav-f405               -208
------------------------  ---------  --------------  -----  ------  ----  -----  -----  ---
```

**Comment by peterbarker** [comment]
I've run this through size_compare_branches.py.

Changes are limited to several periph which include code which contained a nullptr dereference:
image

Other periphs have minor changes to their linking.

**Review by tridge — APPROVED** [review]

**Pull request merged**
