### PR TITLE
ArduCopter, ArduPlane, ArduSub, Rover: fix long booting

### PR DESCRIPTION
**Pull request by wiktor-m**
Booting was 25 seconds took longer. Tested at ESP32, Copter

### CODE REVIEW

**Review by peterbarker — DISMISSED** [review]
We need everything squashed into a single commit, then broken out into a per-vehicle commit.

You can do this using an interactive rebase, followed by running the script `Tools/gittools/git-subsystems-split`.  Let me know if you would like me to do this for you.  More information here: https://ardupilot.org/dev/docs/git-interactive-rebase.html

People are going to ask on the DevCall "what testing has this had?" - it's inevitable.  We'll need answers to that question - in particular, does the parameter conversion still actually work, doing its job as you move between two different versions of the firmware?

**Comment by wiktor-m** [comment]
Peter I did it but, I am not sure. After squash (git rebase -i "HEAD~7") and split (per vehicle by script "git-subsystems-split") in my copy I saw only 4 commits (splitted per vehicle) but I coud't do "git push", so I did git pull and git push and now I see too much commits. I don't understan where I did mistake.

**Comment by wiktor-m** [comment]
I rolled back some commits, is it ok now?

**Comment by rmackay9** [comment]
@wiktor-m,

Thanks for this. In your testing could you test if the parameter conversion code was still working?  I think it should but it would be good to confirm.

**Comment by wiktor-m** [comment]
@rmackay9
@peterbarker

For few days I tried understand (source code for parameters is not simple) how I can generate parameter in old way for next conversion. Maybe do you know? I tried generate parameter (debuging, printf etc), but in new firmware maybe is it not possible, maybe I need old firmware, but old firmware I need for ESP32 CPU. I think changing the code by me for this PR is not so big as to risk merges :)

**Comment by rmackay9** [comment]
@wiktor-m,

Great, thanks for testing.  Normally when testing parameter conversion I do it in SITL and when I need to clear the parameters I delete the eeprom.bin file.  On a real board the parameters can be [reset using MP](https://ardupilot.org/copter/docs/common-parameter-reset.html).

**Comment by rmackay9** [comment]
So the reason this speeds things up must be that it avoids repeatedly calling [flush()](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Param/AP_Param.cpp#L1960)

**Review by rmackay9 — APPROVED** [review]

**Review by peterbarker — APPROVED** [review]
LGTM

**Comment by rmackay9** [comment]
OK, merged!

**Pull request merged**
