### PR TITLE
Tools: added name to GIT_Success.txt

### PR DESCRIPTION
**Pull request by GiovanniRaseraF**
This PR adds my name to Git_Success.txt file

### CODE REVIEW

**Review by hendjoshsr71 — APPROVED** [review]
Great looks much better!

By the way there is no need to open a new PR to fix commits.
Instead upon amending the commit message what you needed to do was the "force push" your branch.

`git push -f origin`  

Though do be careful with force push when others are working the branch too. (Not the case for a pull request like yours.)

**Comment by GiovanniRaseraF** [comment]
Hi, if the test fails what i need to do ?

**Comment by rmackay9** [comment]
I've re-run the failed job.  Let's hope it passes this time.

**Comment by peterbarker** [comment]
Merged, thanks!

**Pull request merged**
