### PR TITLE
MAVLink: merge in upstream mavlink changes

### PR DESCRIPTION
**Pull request by tridge**

### CODE REVIEW

**Comment by rmackay9** [comment]
I had a look at this and it seems fine to me except maybe MAVProxy also needs to be updated to handle the mavlink message changes as well?  The copter SITL test seems to be failing when it tries to save the mission to a file:

> '/home/travis/build/ArduPilot/ardupilot/Tools/autotest/ch7_mission.txt']: mission_request_list_send() takes at least 4 arguments (3 given)

**Comment by tridge** [comment]
i've now added the changes needed to fix the problems with mission loading, and in fact with any new extensions added. It adds backwards compatibility to pymavlink scripts that aren't aware of extensions added to mavlink messages
Once this passes travis we should push it in

**Comment by rmackay9** [comment]
Yes, I vote for pushing it in as well.

**Comment by OXINARF** [comment]
Merged, thanks!

**Pull request merged**
