### PR TITLE
AC_PosControl: log PSC data in metres in place of centimetres

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by WickedShell** [comment]
Please rearrange that so that the multiplication is done before casting to
double. As written it's casting then doing software double precision
multiplication. This log call is already expensive, let's try to not make
it to much worse.

**Comment by khancyr** [comment]
good point

**Comment by peterbarker** [comment]
@WickedShell fair enough.  I'd decided I didn't care enough about it at the rate we put these out :-)

**Comment by peterbarker** [comment]
@WickedShell Done.

**Comment by WickedShell** [comment]
@peterbarker used to be 300 Hz.... I think I fixed that, but it was more
common then expected.

**Comment by tridge** [comment]
already merged, closing

**Pull request closed without merging**
