### PR TITLE
Camera: Report number of feedback events over MAVLink

### PR DESCRIPTION
**Pull request by WickedShell**
Implements #3903. For a mapping mission you routinely want to know both how many times you've tried to trigger the camera (which we already report) and how many times you succeeded in triggering the camera (what this PR adds). Otherwise it's quite difficult to assess if the camera is meeting an acceptable level of performance.

*CAUTION* Do not merge as is, https://github.com/ArduPilot/mavlink/pull/65 must be merged first, then the MAVLink commit here needs to be updated before merging.

### CODE REVIEW

**Comment by WickedShell** [comment]
Fixed the spelling (I think, I am really bad at spelling) on the MAVLink PR, didn't bother rebasing this since that will need to happen anyways once the MAVLink one is merged and doesn't affect the rest of the review.

**Comment by OXINARF** [comment]
@WickedShell Actually, as long as the MAVLink commit is directly on top of master, it shouldn't be needed to re-do the submodule commit here, as we can just point MAVLink master to your commit. Now, I know that usually doesn't happen, but it's possible.

I think this is fine, but as it involves a MAVLink change, I'd like to put it through the dev call, I'll add the label.

**Comment by WickedShell** [comment]
@OXINARF rebased upon an updated mavlink branch.

I considered trying to push it into the last Dev call, but decided I already had enough topics on it, and should give people a chance to actually look at it here first :)

**Comment by OXINARF** [comment]
Merged, thanks!

**Pull request merged**
