### PR TITLE
New Lua script example

### PR DESCRIPTION
**Pull request by Buenobarbie**
Introducing a new Lua script example that instructs the drone to move forward and backward over a specified distance and number of repetitions. Additionally, there's an accompanying .md file that provides an explanation of the code's functionality, along with fundamental Lua functions and libraries related to drone control. This code has been  tested in both simulation and on an actual drone.

### CODE REVIEW

**Comment by rmackay9** [comment]
Hi @Buenobarbie,

Thanks for the contribution!

One small thing is that we normally prefix our commits with the subsystem or directory affected.  This helps us more easily identify what a commit affects which makes backporting easier.  So could you prefix the commit name is "AP_Scripting: "?

It might also be a good idea to rename the lua script from pingpong.lua to copter_pingpong.lua to make it easier for users to quickly know what vehicle it is meant for.

**Comment by Buenobarbie** [comment]
Okay, i've made the changes

**Comment by rmackay9** [comment]
@Buenobarbie,

Great, thanks.  Eventually it would be good to squash the two commits together as well.

**Review by khancyr — APPROVED** [review]
not the best as need to arm into stabilize. We could improve the logic to switch to guided and arm from guided directly.

But it works. Can merge.
Tested on SITL

**Comment by peterbarker** [comment]
Merged, thanks!

**Pull request merged**
