### PR TITLE
Remove URUS

### PR DESCRIPTION
**Pull request by OXINARF**
It has been a month and two weeks since @hiro2233 was notified that we would remove URUS (given that after more than 1 year it doesn't have any functioning code). He requested one month to send everything in, but nothing happened.

@lucasdemarchi I need to know if you want the macro board number sequence to change or keeping it as is (which is what I've done).

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
Applied, thanks.

**Comment by hiro2233** [comment]
Dear Ardupilot owner project @OXINARF,
i pushed this https://github.com/ArduPilot/ardupilot/pull/5552 pr ineed in January.

I don't know whats is wrong?

**Comment by magicrub** [comment]
@hiro2233 ArduPilot is a flight controller. I have no idea what URUS is, but it doesn't seem to resemble a flight controller.

**Comment by hiro2233** [comment]
@magicrub I know that Ardupilot project makes a flight controller, for that reason i pushed the urus project to ardupilot indeed, i'm sorry if you doesn't understand it.

Anyway, urus project is moving to their hal structure. When it become commercial and make a lot money, maybe you are interested in urus, i think. :P

I still believeing that ardupilot project have good people.

**Comment by magicrub** [comment]
>i'm sorry if you doesn't understand it

Care to explain it?

**Comment by hiro2233** [comment]
Remember when you ask me about if Ardupilot is running on Android? Well, i reply to you with yes.

I think that people here is confused with the problem with Pixhawk and Dronecode members and you are thinking that the others supporting board are evil, so, the situation isn't inverse?

FYI, i have nothing to do with any PX4 and any mRO teams, but i'm thinking to go there to know the people, i'm alone on this. What is your fear?

If you don't want that some projects use your name, only tell to the people that, i could remove the Ardupilot name without any problem. But i don't know if that will be good for the project.

At this point i don't know in who believe.

**Comment by magicrub** [comment]
reminding us of the 9 month old PR would have been helpful. We see a lot of pull requests. We have contacted you a few times to explain what it is. Ok, so you're porting ArduPilot to Android. That's AMAZING!!! Are you actually running ArduPilot? Because what we've seen in your videos is ArduPilot acting as your GPIO manager and that is not interesting to us. If you're controlling vehicles with Android then that is worthwhile to look at closer. Do you have any examples of it controlling vehicles?

**Comment by lucasdemarchi** [comment]
@hiro2233 as we talked earlier, I think this is receiving more attention than it should really.  It's not a ban on anything.  It's simply that we are trying to cleanup the repository from what's not ready so we can remove the burden to maintain it and help evolve the project faster.  This is not exclusive to your board... I have a pending PR to remove one and gave a NACK on more being added that were not at least close to complete.

I'm sorry it needs to be that way. I'd be glad to add it back again when it's ready.

**Comment by lucasdemarchi** [comment]
I'm locking this conversation for 2 days so it gives time for people to think through before commenting.

**Pull request closed without merging**
