### PR TITLE
SITL: Added quadcopter morse example with laser scanner

### PR DESCRIPTION
**Pull request by rishabsingh3003**
This PR is an attempt to make things simpler and more convinent for some people who might want to use Morse with a laser scanner enabled quad. 

An odd thing about this script:
I have placed the laser scanner 1 meter above the quad, and not a few cm's below because on startup the scanner tends to send false readings due to it detecting the ground. Also I have turned off `fastmode` to make obstacle visualization easier. 
Any suggestion for parameter changes are welcome. Thanks :)

To use: run these two commands in two separate terminals 

- `morse run libraries/SITL/examples/Morse/quad_scanner.py`

- `Tools/autotest/sim_vehicle.py -v ArduCopter --model morse-quad --add-param-file=libraries/SITL/examples/Morse/quad_scanner.parm --console --map`

Ill update Morse documentation too if this is merged.

### CODE REVIEW

**Comment by peterbarker** [comment]
Are those false readings a problem in the data coming from Morse?

There's no way we can tweak the rangefinder parameters to use a within-minimum-distance state?

**Comment by rishabsingh3003** [comment]
> Are those false readings a problem in the data coming from Morse?
> 
> There's no way we can tweak the rangefinder parameters to use a within-minimum-distance state?

@peterbarker I'll mess around with the parameters a bit more and see if a solution is possible.

**Comment by peterbarker** [comment]
OK, so I can't get Morse to run with the instructions on ArduPilot.org - even with a whole bunch of hacking.

trusty fails because the QuadRotorDynamics class doesn't exit.

bionic fails because `local_data["engines"]` goes away with an exception in the Morse libraries in the motors actuator (and is replaced with steer/thrust/something).

focal fails because Blender's 2.80 API has changed sufficiently to break Morse's use of it.

How are people actually using Morse with ArduPilot?

**Comment by auturgy** [comment]
Not with ubuntu 20!

https://github.com/ArduPilot/ardupilot_wiki/issues/2782

**Comment by rishabsingh3003** [comment]
Hi @peterbarker . I have been using Morse + SITL everyday since the past three months on Ubuntu 16/18. It works very nicely with SITL( except rover skid steering, which is a little broken and I mean to fix it soon)
The key is:
Do not use blender version above 2.79.0
Rest everything written on the documentation works and you can use this PR's script for lidar on quadcopter!

**Comment by peterbarker** [comment]
I've rebased this on top of changes to the way `OBSTACLE_DISTANCE` is sent in Morse.

I've also changed the range of the rangefinder to match the Rover one.  Ideally we request the rangefinder config from the simulation and use that, but we do need to know what the max range is.

Will merge this once it passes CI.

**Comment by rishabsingh3003** [comment]
LGTM. Thanks!

**Comment by peterbarker** [comment]
Merged, thanks!

**Pull request merged**
