### PR TITLE
AP_NavEKF2 : Adding EXTNAV_ALTSC parameter to choose altitude source.

### PR DESCRIPTION
**Pull request by KiloNovemberDelta**
This parameter lets the user choose for altitude between external navigation z, or the ALT_SOURCE selected like baro or rangefinder. Useful for SLAM robots, which are subject of drift.

### CODE REVIEW

**Comment by rmackay9** [comment]
very nice!  What do you think about trying to save a parameter by combining this with the EK2_ALT_SOURCE?  I'm not sure if it's a good idea or not.. it just seems at the moment when using external navigation we completely ignore the EK2_ALT_SOURCE parameter.  One possible way to make this work would be to change EK2_ALT_SOURCE = 0 to be "Default" (normally baro but when using SLAM this would be the Z-axis value from the SLAM system) and then we would add a new option to allow explicitly set Baro.  when not doing SLAM this would functionally be the same as "Default" but when doing SLAM it would really use the barometer.  Just a thought..

**Comment by KiloNovemberDelta** [comment]
Yes, I had the same idea too. 
It can be looks like : 

EK2_ALT_SOURCE : 

OLD : 

0 	Use Baro
1 	Use Range Finder
2 	Use GPS
3 	Use Range Beacon

NEW : 

0	Use Baro or EXTNAV_Z 
1	Use Range Finder
2	Use GPS
3	Use Range Beacon
4	Use Baro instead of EXTNAV_Z

OR NEW 2 : 

0 	Use Baro
1 	Use Range Finder
2 	Use GPS
3 	Use Range Beacon
4	Use EXTNAV_Z

What do you think ?

**Comment by amilcarlucas** [comment]
New 2 is cleaner

**Comment by khancyr** [comment]
I think new 2 is better too, if you want to use extnav_z do like for rangefinder : use it explicitly !

**Comment by KiloNovemberDelta** [comment]
I agree, 
if @rmackay9  is ok with NEW 2, do not accept this PR, I will make another soon

**Comment by khancyr** [comment]
could you do the same with EKF3 too ?

**Comment by KiloNovemberDelta** [comment]
@khancyr I'm not using EKF3 for now, but I suppose the code for the altitude choice is the same as EKF2, so yes :)

**Comment by KiloNovemberDelta** [comment]
@khancyr I just saw the code for EKF3, I will need more time for the EKF3 because the EXTNAV not seems to be implemented at all yet.

**Comment by rmackay9** [comment]
That's right, external position estimates aren't supported in the EKF3 yet so that will have to wait until [this other PR goes in](https://github.com/ArduPilot/ardupilot/pull/10374).  there are some serious hold-ups on the other PR I'm afraid.

**Comment by rmackay9** [comment]
Re New vs New2.. is New2 really better?  this would mean that by default external SLAM would **not** provide the Z-axis position.  Not so sure about that..

**Comment by khancyr** [comment]
we could auto set the parameter when first seting external nav.
Why I prefer option 2 : it because it won't break what it done on other sensors. On GPS and beacon, we backup on baro is z is not good (I think I remember it is like that) so on external nav it should be the same

**Comment by rmackay9** [comment]
@priseborough, what do you think?

**Comment by priseborough** [comment]
I think that if the user specifies an altitude source, the EKF should not align until that data is present. 

From a user facing perspective I would want to be able to specify the primary and backup source, rather than assume that Baro was always the backup as there are situations where baro is unusable. otherwise we stay with Baro as the default backup sensor and go with option 2.

**Comment by KiloNovemberDelta** [comment]
I like the idea to be able to choose the backup source. When I will have time, I will try to implement it on a new PR. 

@rmackay9  : We go for option 2 ?

**Comment by rmackay9** [comment]
I think we can close this PR because this new PR is available right? https://github.com/ArduPilot/ardupilot/pull/11812

**Comment by rmackay9** [comment]
I'm going to close this for now because we have a newer PR but I'll be monitoring comments so we can re-open if I've made a mistake.

**Pull request closed without merging**
