### PR TITLE
AC_Avoid: fix issue with acute angles in polygon fence

### PR DESCRIPTION
**Pull request by dricketts**
This fixes https://github.com/ArduPilot/ardupilot/issues/4429, which could allow the vehicle to escape the polygon fence at acute angles. The behavior of the vehicle should be identical to the previous behavior in almost all cases. However, it should now be safe in situations where more than one fence edge must be considered.

The main downside to this patch is that the runtime is now quadratic in the number of edges (previously it was linear). However, this is only in the worst case. A more precise runtime is O(k*n) where k is the number of fence edges that must be adjusted for. In most cases, I expect k <= 1. If there is concern about the runtime, we can parameterize this code by a maximum value of k. After the velocity has been adjusted k times, the code will only adjust the magnitude of velocity, not the direction. This will not be optimal, but will at least have a guaranteed linear runtime.

This patch also refactors the velocity adjustment code into two parts:
1. Generation of linear constraints on velocity.
2. Computation of closest velocity subject to linear constraints from (1). This is implemented with adjust_velocity_constraints.

This refactoring will make the avoidance code easily extensible. The idea is that there are many different sources of velocity constraints (polygon fence, no-fly zones, obstacles, etc.). In the future, we can generate all such constraints and then pass them to adjust_velocity_constraints. This guarantees that the velocity satisfies all constraints, without having to worry about weird interactions between, e.g. the polygon fence and obstacle avoidance.

### CODE REVIEW

**Comment by dricketts** [comment]
This pull request is now subsumed be another: https://github.com/ArduPilot/ardupilot/pull/4829. It might be easier to just close this pull request and only consider the newer one, but I'll leave this one open for now.

**Comment by amilcarlucas** [comment]
@peterbarker does this still make sense after the fence changes that you did ?

**Comment by peterbarker** [comment]
On Mon, 21 Oct 2019, Amilcar Lucas wrote:

> @peterbarker does this still make sense after the fence changes that you did ?

Almost certainly.  If someone were to write an autotest we'd know for sure 
:-)

**Comment by davidbuzz** [comment]
see #4829

**Pull request closed without merging**
