### PR TITLE
AP_HAL_Linux: support PWM input for BH hat

### PR DESCRIPTION
**Pull request by lucasdemarchi**
Continuing https://github.com/ArduPilot/ardupilot/pull/6755 - I have no idea what github did, but that PR is closed and doesn't allow me to reopen it.

@onceme let's continue here.

### CODE REVIEW

**Comment by onceme** [comment]
@lucasdemarchi Hi, in case you didn't see [my comment](https://github.com/ArduPilot/ardupilot/pull/6755#issuecomment-406452377) in https://github.com/ArduPilot/ardupilot/pull/6755?

Now it has been around 21 hours, the navio binary is still running on BH. Would you mind to test the patch for me? Thank you!

:)

**Comment by lucasdemarchi** [comment]
Tested on a navio+ here and it's working.

Now if you want to continue on this, something to cut down the cpu utilization on this RCInput would be good. On this RPI the thread ap-rcin is on ~12.6% which is huge for such a simple task. Do you have any idea how that could be done?

**Comment by staroselskii** [comment]
@onceme @lucasdemarchi 

What kind of tests were that? Did you make sure that the decoding actually works?

Actually the more I look at this code, the more I think we need to move it to the kernel. This code is ridiculously unreadable. But as far as I remember at the time of implementing it the PCM and DMA interfaces on Raspberry Pi were lacking.

**Comment by onceme** [comment]
@staroselskii

Did you meet problem on RCInput_RPI?

This PR was moved from here: https://github.com/ArduPilot/ardupilot/pull/6755#issue-135283861, in there first comment, those were the tests I did. Can't say sufficient tests, at least it is working in my real flight for 8 PWM and 1 PPM.

Basically this PR is an improvement of original RCInput_RPI, with 8 PWM support and less memory consumption. If you met problems, please let me know.

**Comment by lucasdemarchi** [comment]
> What kind of tests were that? Did you make sure that the decoding actually works?

Test if it decoded correctly were done by @onceme.

I only made sure it was not crashing with the latest linux image + ardupilot master for a navio+ board. If it worked as PPM for his board, it should work properly on yours too.

It didn't work well for me on a erlebrain but I realized it was actually the linux distro there that a problem... it was crashing even without this patch.

> 
> Actually the more I look at this code, the more I think we need to move it to the kernel. This code is ridiculously unreadable. But as far as I remember at the time of implementing it the PCM and DMA interfaces on Raspberry Pi were lacking.

I agree. Either a separate HW (as navio2 / edge do) or at least doing the bitbang using real interrupts would alleviate the overhead a little bit. See my complaint about the cpu waste.

On a board that lacks HW for doing PPM, I'd much rather dedicate a UART and support only DSM/Sbus (with proper inverter). But I'm not the one doing the boards :)

**Pull request merged**
