### PR TITLE
hwdef: CubeRedPrimary: ICM45686 as ICM20649 alternative

### PR DESCRIPTION
**Pull request by tpwrules**
Empirically what is present on Cube Reds built on/after 2024-04-14 (that is the marking on mine). Fixes board configuration failure.

Not sure if there are any other hardware changes. Bench tested the orientation.

Please confirm @bugobliterator .

### CODE REVIEW

**Comment by rmackay9** [comment]
Thanks for this, I've marked this for the dev call so that it is not forgotten

**Comment by bugobliterator** [comment]
This has been tested on CubeRed with ICM20649 as well.

**Review by bugobliterator — APPROVED** [review]

**Comment by bugobliterator** [comment]
We probably need to backport this to 4.5

**Comment by tpwrules** [comment]
The sensors on CubeRedSecondary seem to be okay.

**Review by rmackay9 — APPROVED** [review]

**Pull request merged**
