### PR TITLE
Tools: set mavlink log backend for Intel Aero RTF

### PR DESCRIPTION
**Pull request by lucasdemarchi**
This needs to wait for an update of the Linux side so shouldn't be applied just yet. For tests this can be accomplished by adding the following entry to `/etc/mavlink-router/main.conf`:

```
MavlinkDialect = ardupilotmega
```

Or install master branch of mavlink-router (https://github.com/01org/mavlink-router) which chooses the dialect automatically.

### CODE REVIEW

**Comment by rmackay9** [comment]
Oops, didn't read the message before merging!

**Comment by lucasdemarchi** [comment]
:(

**Comment by magicrub** [comment]
:(

**Comment by lucasdemarchi** [comment]
Latest BSP can now be downloaded:
https://downloadcenter.intel.com/download/26748/Intel-Aero-Platform-for-UAVs-Installation-Files

**Pull request merged**
