### PR TITLE
EKF2 Updates

### PR DESCRIPTION
**Pull request by priseborough**
This has been submitted as a work in progress to try and gather test data for the tuning which is not yet complete.

Fixes error in derivation use of IMU noise parameters.
This required the tuning to be redone. The retune provides a better compromise between susceptibility to different sensor errors and is closer to the EKF1 tune. This results in some increase in sensitivity to IMU errors, but improves resistance to magnetometer and GPS errors.
Improved magnetic anomaly handling logic.
Fixes a bug that caused the filter to be vulnerable to loss of attitude reference immediately after GPS lock was gained.
Improves resistance to loss of heading accuracy during prolonged fast yaw spins
Miscellaneous bug-fixes.

This has had limited testing on Copters, but requires testing on Rovers and Planes. When testing it would be appreciated if with the following parameters  settings are used and links to the logs posted here so that a back to back comparison between the two observers can be made.

AHRS_EKF_TYPE = 1 (use EKF1 to de-risk flight testing)
EKF_ENABLE = 1
EK2_ENABLE = 1
EK2_IMU_MASK = 1
INS_USE = 1
INS_USE2 = 0
INS_USE3 = 0

Until the log replay facility is upgraded we are reliant on feedback from flight testing. Additional tuning work is required to improve the following areas:

1) Improve heading accuracy during fast yaw spins
2) Prevent flight until initial bias estimates have converged
3) gyro bias estimates in flight are too noisy
4) mag field estimates in flight are too noisy
5) gyro scale factors learn too slowly

### CODE REVIEW

**Comment by tridge** [comment]
I've put some logs here:
http://uav.tridgell.net/Paul/ekf-test-apr-25-2016/
3.BIN is with mag enabled, 4.BIN with mag disabled
This is the following branch:
https://github.com/tridge/ardupilot/tree/paul-ekf-test2
it includes both your pending PRs
flights went fine!

**Comment by priseborough** [comment]
@tridge can you please check the 3.BIN file. It looks like it never left the ground.

**Comment by priseborough** [comment]
The last three patches to improve robustness to fast yaw spins worked well on SITL with up to 3% scale factor errors applied to gyro data, but were not successful when test flown. The position reset logic worked well and the filter recovered rapidly each time, but it is not known at this stage what caused the inertia solution to depart from the GPS when it experienced sustained rapid yaw rotations. Thsi problem did nto affect EKF1 and the EKF2 and EKF1 yaw angles were in close agreement.

The log from this flight is attached.

[iris_yaw_spin_fail.bin.zip](https://github.com/ArduPilot/ardupilot/files/233850/iris_yaw_spin_fail.bin.zip)

**Comment by tridge** [comment]
i've fixed the log, it was a partial upload on a dodgy link from the club wifi

**Comment by priseborough** [comment]
i tried another flight after reverting back to ff47dd1. The same behaviour exhibited. EKF1 and EKF2 had equivalent attitude estimates, but EKF2 built up velocity and position errors during the spin that recovered afterwards. It could be an issue with time alignment of sensor data given that it doesn't occur in SITL.

[iris_yaw_spin_fail_2.bin.zip](https://github.com/ArduPilot/ardupilot/files/233953/iris_yaw_spin_fail_2.bin.zip)

**Comment by priseborough** [comment]
I've been able to reproduce the position and velocity error in SITL with the following steps:

Add a scale error of +3% to gyro X and  -3% to gyro Y to the IMU inputs
Start SITL and perform the following steps:
enter 'param set SIM_WIND_SPD 5'
wait for GPS
enter 'arm throttle'
enter 'rc 3 1500'
wait for height to increase to 20m
enter 'loiter'
 enter 'rc 4 2000' to start spin
wait until EKF goes unhealthy
enter 'rc 4 1500' to stop spin
wait for EKF to reset position to GPS and settle, then quit SITL

**Comment by priseborough** [comment]
Reverting back to commit 8eeef6c removes the fast yaw spin sensitivity. The EKF2 estimator from the PX4/ecl library on the same copter does not experience the fast yaw dizziness and it in theory uses the same derivations as the EKF2 in this PR, but with modified parameters.

It looks likely that this is due to a bug introduced by this PR after commit 8eeef6c

**Comment by OXINARF** [comment]
@priseborough I think the fastest way to find the bug is to use git bisect

**Comment by jschall** [comment]
Paul, I am getting it to fail without adding the scale factor to the IMU inputs.

**Comment by jschall** [comment]
Result of bisect: e48ca01fe03314c501b06f901dd24c3c5ad1fcbe is the first bad commit

This suggests a tuning problem, I think.

**Comment by tridge** [comment]
Replay now works again in master, which should help test of of these patches

**Comment by priseborough** [comment]
I have a fix that works in the ecl version of EKF2, but it does negate the sale factor learning https://github.com/PX4/ecl/pull/110. Jon and I are working to to see if a modification to the derivation will enable us to keep the scale factor estimation, however if no better solution turns up in the next week, we have a backup.

**Comment by priseborough** [comment]
Obsoleted by https://github.com/ArduPilot/ardupilot/pull/4133. Some of the patches for data logging and interface compatibility may be submitted in future PR's.

**Pull request closed without merging**
