### PR TITLE
Baro: proble for MS5611 on I2C address 0x76

### PR DESCRIPTION
**Pull request by rmackay9**
This small PR does the following:

1. probes for the MS5611 barometer on I2C address 0x76 when external barometers are enabled ([wiki](http://ardupilot.org/copter/docs/common-baro-external.html))
2. adds parameter Values for PROBE_EXT to make it easier to setup the external baro for users of GCSs that don't display the bitmasks well

This has been tested to work on a Pixhawk1 with a Drotek MS5611 external barometer.

### CODE REVIEW

**Comment by tridge** [comment]
I've extended this to probe both i2c buses on the CubeBlack

**Comment by WickedShell** [comment]
This needs a warning to not be used with a MS5525 airspeed sensor as they will conflict. The overloading of values and bitmask are really poor. It makes it much harder for a GCS to select which one to use. GCS's should have checkboxes generated from the bitmask, so I'd really prefer to not see the Values as well.

**Comment by tridge** [comment]
I've added a commit to use GND_EXT_BUS to specify what bus to probe. That will at least allow users who know what they are doing to avoid conflicts with a MS5525.
What we really need is a way to detect duplicate devices at the HAL level.

**Comment by rmackay9** [comment]
@tridge, we should probably update the @Values so that "-1" is "All Buses"...

**Pull request merged**
