### PR TITLE
Add log download tests

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by WickedShell** [comment]
Can this remove the normal `LogDownLoad` test that the vehicles already run? This seems like a much more thorough version of the same thing, and given that the exsisting LogDownload test was very much a non trivial portion of the autotest time last time I benchmarked it it's probably worth not adding to much time here.

**Comment by peterbarker** [comment]
@WickedShell I was planning on moving the test-log-download component of LogDownload, yes.  The moving and uploading will stay.

**Comment by peterbarker** [comment]
@WickedShell well... there is the issue that we won't be  testing MAVProxy's log download.  May need to re-add a test for that - with a small logfile :-)

**Comment by WickedShell** [comment]
> @WickedShell well... there is the issue that we won't be testing MAVProxy's log download. May need to re-add a test for that - with a small logfile :-)

I've said it before, and I'll say it again: this is not the MAVProxy test suite, it's the ArduPilot one. If MAVProxy want's a separate test that's fine :)

**Comment by peterbarker** [comment]
On Thu, 14 May 2020, WickedShell wrote:

> I've said it before, and I'll say it again: this is not the MAVProxy test suite, it's the ArduPilot one. If MAVProxy want's a separate test that's fine :)

It's nice if SITL still works.  That requires MAVProxy to continue to 
work.

**Comment by peterbarker** [comment]
@WickedShell I've now got just QuadPlane doing the log download test.

**Pull request merged**
