### PR TITLE
AP_Math: Convert MatrixN to header only.

### PR DESCRIPTION
**Pull request by samuelctabor**
Reduces binary size slightly for CubeOrange.

### CODE REVIEW

**Comment by magicrub** [comment]
I see that this no longer includes #pragma GCC optimize("O2"), is that intentional?

**Comment by samuelctabor** [comment]
Nope, must've got lost in the copying-across process . . .

**Comment by magicrub** [comment]
is this just for code-size improvements or for something else?

**Comment by samuelctabor** [comment]
I'm planning to add some more uses of matrixN, this just avoids having to instantiate the different matrix sizes in matrixN.cpp.

**Comment by magicrub** [comment]
It's failing Travis:

```
In file included from ../../libraries/AP_Math/AP_Math.h:9:0,
                 from ../../Tools/AP_Periph/can.cpp:19:
../../libraries/AP_Param/AP_Param.h: In instantiation of 'void AP_ParamT<T, PT>::set_and_save_ifchanged(const T&) [with T = float; ap_var_type PT = (ap_var_type)4u]':
../../Tools/AP_Periph/can.cpp:221:74:   required from here
../../libraries/AP_Param/AP_Param.h:772:15: warning: comparing floating point with == or != is unsafe [-Wfloat-equal]
         if (v == _value) {
             ~~^~~~~~~~~
cc1plus: warning: unrecognized command line option '-Wno-expansion-to-defined'

```

Also, it says it's not fitting in another platform.

**Comment by rmackay9** [comment]
This isn't really my area but I think we probably need to seem some real advantage to merge this.  Perhaps a bunch of testing to show that it has some benefit in terms of CPU load or firmware size.

**Comment by samuelctabor** [comment]
After putting the optimisation pragma back in there doesn't seem to be any code size advantage. After removing the include of matrixN from vectorN the binary size is unchanged from master for AP_Periph (which was failing due to size) but it is slightly increased for ArduPlane by 152bytes..

I ran the Quadplane.GyroFFT test that is failing CI locally a bunch of times. I was able to get passes and fails without changing code.

I'll just follow the advice of @rmackay9 and close this unless someone else sees a benefit to it.

**Comment by rmackay9** [comment]
@samuelctabor, thanks for the investigation.  Moving on sounds good to me.

**Comment by tridge** [comment]
This is not a good idea, it slows down the build and as we add more users of the calls it increases binary sizes. closing

**Pull request closed without merging**
