### PR TITLE
Plane: added TKOFF_THR_MAX_T for non-airspeed takeoff

### LINKED ISSUE #22572: Not using full throttle in non-airspeed takeoff
With ARSPD_USE=0 fixed wing takeoff doesn't reach full throttle in AUTO takeoff. This is particularly a problem for catapult or bungee launches where full throttle may be needed to achieve reliable takeoff
See https://discuss.ardupilot.org/t/takeoff-throttle-is-not-at-maximum-when-airspeed-not-used-for-throttle-control/94359

With ARSPD_USE=1 we have a override in AP_TECS to give full throttle until the target airspeed is reached:
https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_TECS/AP_TECS.cpp#L748
there is no equivalent check in AP_TECS::_update_throttle_without_airspeed()

@priseborough any suggestions on the right approach? Overspeed can happen without an airspeed sensor of course, so just forcing full throttle for the entire takeoff isn't ideal

### PR DESCRIPTION
**Pull request by tridge**
This adds TKOFF_THR_MAX_T which is the time to force maximum throttle on fixed wing takeoff without airspeed

fixes #22572

### CODE REVIEW

**Review by priseborough — COMMENTED** [review]
Have you tested this in SITL with a strong headwind and verified that it doesn't cause the pitch angle to drop due to synthetic airspeed being equal to ground speed until the first turn?

**Comment by tridge** [comment]
> Have you tested this in SITL with a strong headwind and verified that it doesn't cause the pitch angle to drop due to synthetic airspeed being equal to ground speed until the first turn?

when we don't have an airspeed sensor we override the pitch based on the pitch from the takeoff mission item, with a minimum of 5 degrees. See Plane::takeoff_calc_pitch()
I just tried it with a 20knot headwind in SITL and it worked fine

**Comment by priseborough** [comment]
Looking at the code the TECS total energy error to throttle control loop will engage with a speed weight of 2 during takeoff when _flags.reached_speed_takeoff goes true. For setups without an airspeed sensor, this will be the only time in flight that the TECS total energy loop is engaged and when we make this change this will happen on their first takeoff after they flash a new FW . Users that don't run airspeed sensors may not have the min, max and trim airspeed configured correctly. Is it possible that this could result in throttle being pulled back excessively? I'll discuss this further on Discord.

**Comment by tridge** [comment]
> Users that don't run airspeed sensors may not have the min, max and trim airspeed configured correctly. Is it possible that this could result in throttle being pulled back excessively?

that could happen, yes. The airspeeds are used for speed scaling and for the roll limit (stall protection), so they can't be massively off, but yes it is a risk.

**Comment by timtuxworth** [comment]
> > Users that don't run airspeed sensors may not have the min, max and trim airspeed configured correctly. Is it possible that this could result in throttle being pulled back excessively?
> 
> that could happen, yes. The airspeeds are used for speed scaling and for the roll limit (stall protection), so they can't be massively off, but yes it is a risk.

This could be mitigated by updating the docs/wiki with appropriate warnings.

**Comment by priseborough** [comment]
This does change behaviour for existing setups and a higher wing loading faster setup will fly happily at the moment on default airspeed values. My preference with a no airspeed sensor setup is that the combination of fixed takeoff throttle and pitch angle is used to provide a consistent and safe takeoff and climbout, rather than rely on the setting of airspeed values which will give a different throttle response depending on headwind.

**Comment by tridge** [comment]
@priseborough I'll need some help to implement that, I don't see how we combine pitch and throttle

**Comment by priseborough** [comment]
OK, I'll discuss on Discord.

**Comment by tridge** [comment]
@priseborough PR updated as discussed

**Review by priseborough — APPROVED** [review]

**Comment by magicrub** [comment]
These sort of params really need to live in the mode takeoff class.

**Pull request merged**
