### PR TITLE
Defined SIM_ENGINE_FAIL to simulate an engine failure

### PR DESCRIPTION
**Pull request by GuilhermeGSousa**
Hi everyone this is my first PR, besides adding me to GIT_SUCESS I created a new parameter SIM_ENGINE_FAIL (0-7) to define the motor affected by SIM_ENGINE_MUL. Simple enough for a first time!

### CODE REVIEW

**Comment by magicrub** [comment]
Hi there, and welcome!

Using an index 0 -7 means only a single engine failure is possible. I think offering multiple failures would be more interesting via bitmask so a 32 Param would be better.

**Comment by GuilhermeGSousa** [comment]
Definitely more interesting, I hadn't thought of that I'll add a commit with a bitmask then!

**Comment by magicrub** [comment]
While you're at it, please take a look at the commit guidelines on the wiki. Namely, no merges are allowed in the branch. Please rebase on the current master and force push.

**Comment by rmackay9** [comment]
by the way we have SIM_ENGINE_MUL which allows reducing the power that is output to the first motor.

**Comment by tridge** [comment]
pretty good for a first PR. It does need some work though. Please cleanup the commits - should be one commit per directory (so 4 commits I think). You should squash the fixup commits, and add directory prefix to the commit first lines

**Comment by tridge** [comment]
you might like to read up on git interactive rebase for fixing the commits

**Comment by GuilhermeGSousa** [comment]
Ok I see I have some cleanup to do thanks for the help, @rmackay9 my idea was to still use SIM_ENGINE_MUL, just to add a parameter to define which motor it affects (for copters)

**Comment by OXINARF** [comment]
@GuilhermeGSousa Regarding our rules, you should read http://ardupilot.org/dev/docs/submitting-patches-back-to-master.html

**Pull request closed without merging**
