### PR TITLE
Move logging of RPM, Beacon and Proximity into relevant libraries

### PR DESCRIPTION
**Pull request by peterbarker**
I've added some tests to ensure these get logged.

It would be nice to move responsibility for logging into these libraries and out of the vehicle code.  This will require the whole `set_log_bitmask_bit()` pattern on the libraries (which we use on a few libraries line `AP_InertialSensor`).

### CODE REVIEW

**Comment by rmackay9** [comment]
I'm happy with this change in a general sense and it looks mostly like a move of code.  I haven't checked line by line though.

**Review by hendjoshsr71 — APPROVED** [review]
lgtm

**Comment by tridge** [comment]
@rishabsingh3003 can you test?

**Comment by rishabsingh3003** [comment]
Sure. I will test this out tomorrow

**Comment by rishabsingh3003** [comment]
filter prob

Proximity logging works as normal! Thanks :)

**Comment by peterbarker** [comment]
Thanks @rishabsingh3003

**Comment by peterbarker** [comment]
I had another look at the logs produced by the autotest suite and the RPM and beacon data also looks reasonable.

**Pull request merged**
