### PR TITLE
AC_AutoTune: correct incorrect min raw rate value

### PR DESCRIPTION
**Pull request by andyp1per**
An obvious error

### CODE REVIEW

**Review by rmackay9 — APPROVED** [review]

**Comment by rmackay9** [comment]
Thanks! 

Maybe I should have left this a little longer for @lthall to review but I think, as AndyP says, this is a pretty obvious fix.  We will include this in the next 4.4 beta as well.

**Comment by andyp1per** [comment]
@rmackay9 it's fine - I already talked with Leonard about it and he agrees its correct

**Review by lthall — COMMENTED** [review]
All good

**Comment by rmackay9** [comment]
this is included in Copter-4.4.0-beta3

**Pull request merged**
