### PR TITLE
AP_NavEKF : remove the space around the operator

### PR DESCRIPTION
**Pull request by RuffaloLavoisier**

### CODE REVIEW

**Review by khancyr — APPROVED** [review]
LGTM

**Review by hendjoshsr71 — COMMENTED** [review]
This is the correct style of course. But I think it should be closed?

We generally do not accept code churn PRs such as whitespace only changes that muddy up the waters of the gitblame.

If there functional changes or even variables renames that help other developers, those do get accepted. Or if you are already changing the lines and fix up the style that is cool and actually preferred.

**Comment by rmackay9** [comment]
I like tidy code so I'd probably merge it.  Let's have a 2min chat on the dev call..

**Comment by rmackay9** [comment]
Merged.  To be clear though, let's not have a massive number of PRs to fix white space issues..

**Comment by RuffaloLavoisier** [comment]
@rmackay9 
Thanks, if I have to keep making these requests according to the style guide, should I request them in a large unit (small request and many modifications)?

**Pull request merged**
