### PR TITLE
AHRS: switch to EKF3 by default

### PR DESCRIPTION
**Pull request by rmackay9**
Switch EKF3 on by default, disable EKF2

### CODE REVIEW

**Comment by magicrub** [comment]
Whenever I fly, it's on EKF3. no problems. I approve!

**Comment by Pedals2Paddles** [comment]
This is great to see coming. I recently switched my Solo (cube 2.1 / Copter 3.5) over to EKF3, disabling EKF2 entirely.  When this goes out, it would be great if someone could make a list of things that make EKF3 an improvement over EKF2, what it does differently, etc.  I'm using because I trust that it's the new improved better way to go. But I actually have no clue how or why.

**Comment by rmackay9** [comment]
The travis failure seems to be somewhat of a real problem re the EKF3 failing it's pre-arm checks.. so requires some more investigation.

**Comment by ThorstenDP** [comment]
Hi all,
I had some incident with EKF3 (Copter V3.5.0) enabled:
https://discuss.ardupilot.org/t/ekf3-uncommanded-periodic-high-throttle-out-in-poshold
I don't think this is a setup issue - except some problems with the baro foam. Not sure if some "fix" went in since then.
Let me know if should make some further tests with this specific copter and EKF3 enabled.
Kind regards,
Thorsten

**Comment by rmackay9** [comment]
@ThorstenDP, thanks for the feedback.  To me that looks like an EKF3 problem.  All the more reason to get the EKF3 out there for testing, so that we can uncover issues like this even before we start beta testing.

**Comment by OXINARF** [comment]
@rmackay9 I see you caught more places where a change was needed, great! I knew I was forgetting something (as I remembered when Tridge changed it to EKF2 it was a bigger change), but I wasn't seeing what it was.

Regarding the Travis failure, I already wrote above what the issue is. We need to figure out what we should do, I hope we get @WickedShell's opinion soon.

**Comment by WickedShell** [comment]
I guess since it's hanging on confirmation of the GPS model does this indicate that EKF3 has never been sitl tested?

We need to either just broadcast a NAV_SVINFO message that we can use to handle the version stuff at a regular interval (and ignore the requests to stop sending it), or need to teach the GPS simulation to actual parse data from the aircraft (as currently all data from the aircraft is dropped).

I guess you could also use a #ifdef to work around the detection in SITL, but I think this is the worst solution and not one we should embrace.

Of the two I'm more inclined to just spam at say 10 second intervals the NAV_SVINFO as it's the minimum patch set, and I don't currently have the time to write a proper u-blox simulation, although if someone wants to take that on that would be great.

**Comment by OXINARF** [comment]
> I guess since it's hanging on confirmation of the GPS model does this indicate that EKF3 has never been sitl tested?

Maybe not since we changed the lag response? @priseborough would be the one to answer that really.

> Of the two I'm more inclined to just spam at say 10 second intervals the NAV_SVINFO as it's the minimum patch set

Looks good to me (although I'd prefer to have a SITL GPS driver instead of all the driver simulations). Do you have time to do it?

**Comment by WickedShell** [comment]
#7521 takes the quick approach and should resolve the SITL issues (fixed it for me at least).

**Comment by rmackay9** [comment]
Rebase on master.

I had a chat with @priseborough and he suggested that we should perhaps enable one instance of EKF3 (to be used by default) and another instance of EKF2 to be used as the backup.  I'm not quite sure how we can do this, I suspect it will require some small code changes..

**Comment by Pedals2Paddles** [comment]
As it is setup now, enabling an instance of EKF2 and an instance of EKF3 provides no redundancy, correct? Since the ability to switch from one IMU to another requires both to be using the same EKF.  Are the two even similar enough to make handoffs from one to another if the code was changed to allow it?  Will that adversely affect the amount of memory or drag the loop rate down?

**Comment by OXINARF** [comment]
@rmackay9 That's an interesting idea from Paul. It does require doing more code at the AP_AHRS_NavEKF level to compare the estimator scores. I guess the idea is to run different IMUs, right?

@priseborough is really the best person to say, but I think that we'll be adding unnecessary code, there are people already flying with EKF3 and, after all, we are putting this in master, it's not even guaranteed to be alpha quality code.

**Comment by rmackay9** [comment]
It's not clear to me that we ever want to make EKF3 the default so closing for now anyway.

**Pull request closed without merging**
