### PR TITLE
AP_NavEKF3: don't accept ExtNavVelData until initialised

### PR DESCRIPTION
**Pull request by peterbarker**
This same code is in the other write methods for external data.

### CODE REVIEW

**Comment by rmackay9** [comment]
This may be correct but I don't see this check in other write methods.  What problem is it solving?

**Comment by peterbarker** [comment]
> This may be correct but I don't see this check in other write methods. What problem is it solving?

https://github.com/ardupilot/ardupilot/blob/master/libraries/AP_NavEKF3/AP_NavEKF3_Measurements.cpp#L123

https://github.com/ardupilot/ardupilot/blob/master/libraries/AP_NavEKF3/AP_NavEKF3_Measurements.cpp#L153

https://github.com/ardupilot/ardupilot/blob/master/libraries/AP_NavEKF3/AP_NavEKF3_Measurements.cpp#L954

https://github.com/ardupilot/ardupilot/blob/master/libraries/AP_NavEKF3/AP_NavEKF3_Measurements.cpp#L987

I'm not actually sure why we care whether the data goes into the time horizon buffers - so long as we're not munging it based on other EKF state, AFAICS we ought to rely on the code consuming data from the buffers to accept, reject or purge the data.

My guess is that this was essentially an optimisation - the history buffers are cleared as part of InitialiseVariables ( called here https://github.com/ardupilot/ardupilot/blob/master/libraries/AP_NavEKF3/AP_NavEKF3_core.cpp#L499 before `statesInitialised` is set to true) so pushing anything into the time horizon buffers is pointless before then.

I was just after consistency here... I'd be just as happy to not check the `statesInitialised` flag - we don't for MAG, GPS or BARO data, for example.  Removing those checks saves us bytes, simplifies the code and offers a marginal performance increase in the general case (where we are initialised).

**Comment by rmackay9** [comment]
I appreciate the desire for consistency!

I agree that we should probably move in the other direction and remove the statesInitialised check.  One thing that makes me think this is that inside of InitialiseFilterBootstrap() we have calls to  to ResetVelocity() and ResetPosition() which can rely on the delayed data (see the line for ExternalNav in ResetPosition).  Who knows what the Delayed value is going to be if we are not always filling the buffers.

Sorry if I rant a bit but this kind of cascading logic in the EKF is terrible.  One logic check in one part of the code relying on another boolean in a completely different part of the code.  It makes it nearly impossible to be sure that the code is correct in all situations.

**Comment by peterbarker** [comment]
I think I'll close this; it might be inconsistent, but it is tested.

Randy and I both seem to agree we should probably remove the `statesInitialised` test from the other input methods rather than adding it here, relying on the `InitialiseVariables` call to nuke things as required.

@priseborough for visibility

**Pull request closed without merging**
