### PR TITLE
Corrected pincount values for J and K

### PR DESCRIPTION
**Pull request by ptoku**
The STM32F777xx.py  script does not have all the pins on the J and K port. This leads to an when you use one of those pins and try to create hwdef.h using ./libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py

### CODE REVIEW

**Review by peterbarker — CHANGES_REQUESTED** [review]
Commit message can be better `AP_HAL_ChibiOS: STM32F777xx.py: correct pincount for J and K`

**Comment by tridge** [comment]
well spotted, thanks!

**Review by tridge — APPROVED** [review]

**Review by peterbarker — APPROVED** [review]
I've fixed the commit message

**Comment by peterbarker** [comment]
Merged, thanks @ptoku !

**Comment by ptoku** [comment]
That was fast. Thank you!

**Pull request merged**
