### PR TITLE
RC_Channel: rearrange RCx_OPTION's @Values order

### PR DESCRIPTION
**Pull request by tatsuy**
I modified the order of "34:Relay2 On/Off".

### CODE REVIEW

**Comment by rishabsingh3003** [comment]
@peterbarker we already check if the _values_ field has any duplicated in the param metadata autotest (https://github.com/ArduPilot/ardupilot/pull/13867). This can easily be extended to check if values are in increasing order or not. Do you think that this is a good idea, and hence we fix this issue throughout the codebase?

**Comment by peterbarker** [comment]
On Sat, 2 May 2020, Rishabh Singh wrote:

> @peterbarker we already check if the values field has any duplicated in the param metadata autotest (#13867). This can easily be extended to check if
> values are in increasing order or not. Do you think that this is a good idea, and hence we fix this issue throughout the codebase?

Sounds good to me :-)

**Comment by tatsuy** [comment]
rebased

**Comment by tatsuy** [comment]
@peterbarker 
I'm sorry for taking your time.
I made a review request because it was left unattended for a long time.

**Comment by peterbarker** [comment]
Merged, thanks!

**Comment by tatsuy** [comment]
Thank you!

**Pull request merged**
