### PR TITLE
AP_HAL_SITL: reorder setting of reuseaddr and bind for SITL RC port

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by khancyr** [comment]
Should we set option like SO_REUSEADDR before binding ? and the SO_REUSEPORT seems to be a good improvement on recent kernel (on swarm perspective)

**Comment by peterbarker** [comment]
@khancyr I don't have a test setup here for cygwin, so I'm shooting blind...

**Comment by khancyr** [comment]
even on linux, most usage of SO_REUSEADDR said it should be before binding ... I am not expert on this, but it doesn't seems to hurt much.

about cygwin, I will try to make a pass on Francisco PR on azure CI, it should help !

**Comment by peterbarker** [comment]
@khancyr That SO_REUSEADDR vs bind ordering thing was actually the problem on cygwin!  @meee1 changed the ordering and the problem went away.

If it's actually ineffective on Linux it would explain our periodic rebind problems, too!

I've force-pushed up the reordering over what was here previously.

**Comment by OXINARF** [comment]
Merged, thanks!

**Comment by aercamti** [comment]
Things are working again as expected - Thanks!

**Comment by peterbarker** [comment]
@aercamti What error does mavproxy give?  How is MAVProxy getting its data from the SITL instance?

**Comment by aercamti** [comment]
Following issuing the reboot command:
MAVProxy: Link1 down; no link (but console status "icons" remain green)
MP: Popup: "Error: no responce from MAV"

(MAVProxy is started like so:
"C:\Program Files (x86)\MAVProxy\mavproxy.exe" --master=tcp:127.0.0.1:5762 --console --map

**Comment by peterbarker** [comment]
On Wed, 19 Dec 2018, aercamti wrote:

> Following issuing the reboot command:
> MAVProxy: Link1 down; no link (but console status "icons" remain green)
> MP: Popup: "Error: no responce from MAV"

That's interesting.  It should be detecting that the tcp link is dead and 
restarting it.  Hmmm.

**Pull request merged**
