### PR TITLE
AP_BLHeli: Remove duplicated code, use existing AP_Math CRC function

### PR DESCRIPTION
**Pull request by amilcarlucas**
This saves 24 bytes

### CODE REVIEW

**Review by andyp1per — APPROVED** [review]
Looks right to me but needs verifying on hardware

**Comment by amilcarlucas** [comment]
Can you test this? I have no BLHeli hardware to test this with :(

**Comment by andyp1per** [comment]
Looks like it works

**Comment by amilcarlucas** [comment]
This has been tested in hardware, and passes CI.

**Review by tridge — APPROVED** [review]

**Pull request merged**
