### PR TITLE
Remove unused AP_ADC

### PR DESCRIPTION
**Pull request by WickedShell**
This removes the unused AP_ADC class (this is orphaned class at the moment that is never instantiated), it leaves the AP_ADC_ADS1115 which is needed for some Linux boards, and potentially useful elsewhere, and is currently directly instantiated as needed.

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
there are more uses of AP_ADC. AP_ADC_ADS1115 can be moved to libraries/AP_HAL_Linux or better yet folded into AnalogIn_ADS1115

**Comment by WickedShell** [comment]
@lucasdemarchi I'm actually looking at either doing a quick and dirty pass with AP_ADC_ADS1115 for a short term project here on a Cube build, or if I think of a reasonable/sane way might look at adding it as a generic set of extra ADC inputs.

For now I wanted to hold off on moving the actual driver until after I do my dirty hack, or if I find a reasonable way to add extra ADC's to all the HAL's. Do you have any issues with what's outlined here?

**Comment by lucasdemarchi** [comment]
If you are going to use it, then you can leave where it is. But then maybe AP_ADC should remain as the ADC abstraction.

Right now each HAL has a AnalogIn which is already what AP_ADC would be. And on Linux there's a double abstraction AnalogIn_ADS1115 -> AP_ADC_1115 that desn't make much sense.

**Comment by WickedShell** [comment]
The reason I thought it was worth removing the AP_ADC class at the moment is because it is completely unimplemented, and has an API that doesn't make a lot of sense. I think we do need to land on a more unified ADC interface.

And yes, the Linux side seems to have an unneeded abstraction layer, I'm a bit hesitant to poke at it though, as I don't have any hardware setup to actually test it on.

**Comment by tridge** [comment]
maybe we should go the other way and remove hal.analogin, and instead use AP_ADC  with backends for the HAL specific stuff?

**Comment by WickedShell** [comment]
@tridge Long term I think that's probably better. A lot of the HAL's do stuff very very similarly, although there might be just enough variation in behaviour to make lifting it up and out problematic/minimal win. I haven't given a lot of thought to what a proper API should look like yet, so it might be a lot less problematic then I'm anticipating.

**Comment by tridge** [comment]
the biggest advantage would be allowing multiple backends (for things like i2c expanders), and being able to configure it with parameters.
We should probably move other parts of the HAL out too

**Comment by lucasdemarchi** [comment]
@tridge yes, I agree. But looking at the implementation of this AP_ADC, it has nothing we really want in a new implementation and would need to be rewritten. As such, I'm not against of removing it and then doing a proper implementation with backends like in other sensors.

**Pull request merged**
