### PR TITLE
Copter: calculate wp bearing and distance on demand

### PR DESCRIPTION
**Pull request by peterbarker**
Move responsibility for calculating wp bearing/distance
into the FlightMode object doing the navigation

Calculating these variables was being done at 50Hz where they
were used at 10Hz max.

### CODE REVIEW

**Comment by rmackay9** [comment]
Merged, thanks!
As a side note, I think we should probably call these functions "get_distance_to_destination" and "get_heading_to_target" to be consistent with Rover but the change is still good so merged.

**Comment by peterbarker** [comment]
On Sat, 9 Dec 2017, Luis Vale Gonçalves wrote:

> Shouldn't thishttps://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Frsky_Tele
> m/AP_Frsky_Telem.cpp#L699
> 
> be removed and use this PR ?
> @peterbarker

Yes, I think that would work.

**Comment by lvale** [comment]
@floaledm Should verify this change as the "blame" says he was the author of that part of the code

**Comment by floaledm** [comment]
@lvale Thanks for including me and flagging this as a potential problem.
I'd be happy to do whatever is needed but for the moment not sure what may be broken... As far as I can tell, nothing in the referenced part of the FrSky lib is affected by changes in this commit, but I haven't studies the implications of this commit in detail.
Should the bearing, distance, and altitude between the vehicle and the home location be calculated/retrieved in a specific way now? If so, please let me know how and I'll gladly make a PR to address that in the FrSky lib...

**Pull request merged**
