### PR TITLE
pixracer R15 LIS3 magnetometer support

### PR DESCRIPTION
**Pull request by kd0aij**
PixRacers from mRobotics will soon be shipping with LIS3 in place of the HMC magnetometer.
This PR adds a probe for the new device and has been flight tested on a small FPV quad.

### CODE REVIEW

**Comment by kd0aij** [comment]
@OXINARF That was just an attempt to get Travis to pass, and it didn't work anyway. Should I just remove it?

**Comment by OXINARF** [comment]
@kd0aij Yes, better to remove it. I'll try to fix Travis in 3.5 branch this weekend.

**Comment by kd0aij** [comment]
Thank, I removed the unrelated commit.

**Comment by rmackay9** [comment]
@CraigElder will add this to the dev call agenda for Tue.  Releases eat a day or two of my time so I'd like to release this change along with others.  I think @tridge and @proficnc have an issue they are looking at related to the Here GPS's orientation so maybe this change and that one can be released together.

**Comment by kd0aij** [comment]
@rmackay9 With Copter-3.5.4 (284349c) flashed on my PixRacer R15, the HMC5843 is (of course) not found (no external compass was connected for this test):
```
SPI device hmc5843 on 1:5 at speed 11000000 mode 3                                                  
SPI device hmc5843 on 1:5 closed                                                                    
SPI device icm20608 on 1:6 at speed 500000 mode 3                                                   
SPI device mpu9250 on 1:4 at speed 1000000 mode 3                                                   
```
but the 8963 in the MPU9250 is recognized properly:
```
STABILIZE> param show COMPASS_DEV_ID*
COMPASS_DEV_ID   263178.000000
COMPASS_DEV_ID2  0.000000
COMPASS_DEV_ID3  0.000000

Tools/scripts/decode_devid.py 263178
bus_type:2  bus:1 address:4 devtype:4(0x4)
```
I noted that on initial bootup, both dev_id and dev_id2 were 263178
I manually zeroed COMPASS_DEV_ID2, rebooted and it remained zero
I noticed no warnings that compass calibration was necessary, but heading was off by 90 degrees until I recalibrated.

**But magnetic heading is accurate after recal, so there should be no (additional) internal compass problems using 3.5.4 on PixRacer R15 prior to addition of support for the LIS3.**

**Comment by rmackay9** [comment]
Merged (actually I re-cherry-picked the commits from master but should be the same result).  Thanks!

**Pull request closed without merging**
