### PR TITLE
Create and use RangeFiner backend data accesors

### PR DESCRIPTION
**Pull request by peterbarker**
This includes a previous PR, #6733

### CODE REVIEW

**Comment by OXINARF** [comment]
I didn't thought this was what you were doing when we talked about get_backend yesterday. I have to say I'm a bit torn on this, although it is growing on me.
On one hand, I think this library interface should be really about orientation and not about instance number (although that may still be needed for logging and reporting). On the other hand, this means some places need to know the backend interface and I'm not too fond of that.
I'll probably let it stay for a day or two and then merge it if no one else has comments.

**Comment by peterbarker** [comment]
@OXINARF I was thinking a better interface might be `bool get_distance_cm_orient(ORIENTATION orientation, &uint16_t retvalue_cm)` which returns you the distance this sensor measures in a particular orientation, if possible.  This would allow a sensor mounted at 45 degrees to give you a reading.  But I haven't looked at the proximity sensor stuff yet, so I'm probably crossing into its territory.  Spinning devices would be able to give you a reading for any orientation in their plane.

As I said, I haven't looked at proximity, but I think it is possible that AP_RangeFinder is redundant.

**Comment by OXINARF** [comment]
> I was thinking a better interface might be bool get_distance_cm_orient(ORIENTATION orientation, &uint16_t retvalue_cm) which returns you the distance this sensor measures in a particular orientation, if possible.

@peterbarker Yeah, that's basically what the current *_orient* methods do but without returning a boolean telling the validity of the data - which makes most API users having the use *has_data* first to check if the information exists and is valid. Changing to your proposal would be much better, I believe.

As I've said in Gitter, one issue we need to fix is what to do with multiple sensors pointing in the same direction. Right now we just return the first one we find, but that's not very useful - and that is the main reason why EKF kept looping through the sensors instead of getting just one downwards sensor.
Fixing this should also reduce the users that need to iterate over the rangefinder instances, making me appreciate this PR more.

Regarding AP_Proximity, I agree there is an overlap, specially on the desired APIs side, but I'm not sure we can merge them in a good way. AP_Rangefinder deals with single direction hardware/instances, while the AP_Proximity deals with multiple direction hardware/instances.

I don't quite understand why this PR has conflicts, but it needs a rebase.

**Comment by peterbarker** [comment]
@OXINARF Rebased.  It didn't conflict for me when I rebased, either... hmmmm...

**Comment by OXINARF** [comment]
Rebased, aligned code comments in last commit and merged. Thanks!

**Pull request closed without merging**
