### PR TITLE
SITL: adding GPS_TYPE_MAV

### PR DESCRIPTION
**Pull request by HefnySco**
This PR I added GPS_TYPE_MAV to SITL.
Now you can test  **msg_gps_input** with simulator.
GPS_TYPE = 14 "MAV"
SIM_GPS_TYPE = 14

### CODE REVIEW

**Comment by tridge** [comment]
I don't understand what this is trying to do. We can already use GPS_TYPE=14 by doing "module load fakegps" in mavproxy. 
How is this proposed change used?

**Comment by HefnySco** [comment]
> I don't understand what this is trying to do. We can already use GPS_TYPE=14 by doing "module load fakegps" in mavproxy.
> How is this proposed change used?
GPS_MAV is defined already in AP_GPS as a true GPS option. Adding it to SITL this way enabled SITL to simulate it exactly as in "true" pixhawk. I believe this makes the SITL more like real boards with no extra initialization. I mean this is the way we simulate other GPS modules without using load modules.

**Comment by tridge** [comment]
> GPS_MAV is defined already in AP_GPS as a true GPS option. Adding it to SITL this way enabled SITL to simulate it exactly as in "true" pixhawk

I still don't understand what you're talking about. You haven't added a new backend to AP_HAL_SITL/sitl_gps.cpp, you just added an empty function, so this seems to do nothing.
When you set GPS_TYPE=14 you need to provide mavlink packets of type GPS_INPUT which have the GPS data. Your PR doesn't do that.

**Comment by tridge** [comment]
closing as the PR doesn't do anything, it is an empty implementation

**Comment by HefnySco** [comment]
> I still don't understand what you're talking about. You haven't added a new backend to AP_HAL_SITL/sitl_gps.cpp, you just added an empty function, so this seems to do nothing.
> When you set GPS_TYPE=14 you need to provide mavlink packets of type GPS_INPUT which have the GPS data. Your PR doesn't do that.

Thank you for the feedback. 
Now I set GPS_TYPE = 14 and SITL_GPS_TYPE = 14 or any value not in SITL::SITL::GPS_TYPE_* so that no GPS simulation data is sent using _update_gps_*
and yes this worked well.

Guys your valued time is much appreciated.

Thanks

**Pull request closed without merging**
