### PR TITLE
Fixed bug in EKF compass switching

### PR DESCRIPTION
**Pull request by tridge**
This fixes a critical bug in EKF compass switching that happens when you have exactly 3 healthy compasses. The lack of the break in the loop resulted in the EKF always switching back to the compass that has been rejected due to high innovations immediately, which means compass failover due to innovations did not work.
If you had 2 compasses then it worked correctly

### CODE REVIEW

**Comment by peterbarker** [comment]
Quadplane is failing with:
```
APM: PreArm: Compass not calibrated

Got MAVLink msg: COMMAND_ACK {command : 400, result : 4}
```

Sounds related.  Do we need more parameter values added to defaults files?

**Comment by rmackay9** [comment]
this looks great!

**Comment by tridge** [comment]
@peterbarker thanks, fixed

**Comment by peterbarker** [comment]
@tridge well, now the more interesting question is why all the other vehicles passed if their third compass wasn't configured....

**Pull request merged**
