### PR TITLE
Respect servo channel min/max output configuration

### PR DESCRIPTION
**Pull request by jaxxzer**
The min/max configuration is not actually applied to the servo channels before writing the output pwm.

### CODE REVIEW

**Comment by khancyr** [comment]
It doesn't looks good to me. Using RC Passthrough mean that you want to copy input to output, so your output must only be limited by the limits you set on input. 
Some places in the codebase can bypass the limit : see comments in https://github.com/ArduPilot/ardupilot/pull/5819

**Comment by jaxxzer** [comment]
> so your output must only be limited by the limits you set on input.

I don't agree. The solution is to configure your min/max correctly on input and output.

**Comment by jaxxzer** [comment]
Is deepstall the only thing this will break?

**Comment by WickedShell** [comment]
@khancyr there is `MANUAL_RCMASK` on plane at least ( http://ardupilot.org/plane/docs/parameters.html#manual-rcmask-manual-r-c-pass-through-mask ) that copies the inputs to outputs directly when in manual.

@jaxxzer The things I know would break are deepstall, and possibly MANUAL_RCMASK'd channels. (I'd have to go look at how they are copied)

**Comment by OXINARF** [comment]
@jaxxzer Although I agree with you - min and max should really be min and max -, this has been discussed before and it was rejected based on some needed uses from Plane. Of course, you are welcome to bring this to a dev call again.

**Comment by amilcarlucas** [comment]
Maybe a better solution is to add two exceptions: `Plane pitch` and `manual_passthru` ?

**Comment by peterbarker** [comment]
Marked DevCall - we should make a decision on this.

Do we need a mask of channels not to apply this check to or something to make everyone happy?

**Comment by tridge** [comment]
this was discussed and rejected in april last year, closing

**Pull request closed without merging**
