### PR TITLE
Inertialnav removal part1

### PR DESCRIPTION
**Pull request by khancyr**

### CODE REVIEW

**Comment by khancyr** [comment]
Rebased and add simplification for get_origin... having an object to keep ekf_origin between loop simplify a little!

**Comment by khancyr** [comment]
correct shadowing

**Comment by rmackay9** [comment]
I think we can close this one, because we have a more updated PR here: https://github.com/ArduPilot/ardupilot/pull/6720

**Comment by khancyr** [comment]
that was for easier review, and this part can be merge without impact !

**Pull request closed without merging**
