### PR TITLE
Use defaults HAL_BOARD_LOG_DIRECTORY and HAL_BOARD_TERRAIN_DIRECTORY

### PR DESCRIPTION
**Pull request by peterbarker**
Removes these lines from all of the hwdefs which included them.  We now set the defaults in chibios_hwdef.py.

For the most part this was done with search/replace of the offending lines.

I used this regexp to convince myself the patch was good:
```
git diff master | grep '^-' | grep -v 'a/libraries' | grep -v '^-$' | grep -v 'define HAL_BOARD_LOG_DIRECTORY "/APM/LOGS"' | grep -v 'define HAL_BOARD_TERRAIN_DIRECTORY "/APM/TERRAIN"' | grep -v 'some defines'
```

### CODE REVIEW

**Comment by andyp1per** [comment]
Why not put these in the logging header and make them dependent on sd card logging?

**Comment by peterbarker** [comment]
```
Board,AP_Periph,blimp,bootloader,copter,heli,iofirmware,plane,rover,sub
AIRLink,,-32,*,-32,-32,,-32,-32,-32
ARKV6X,,-32,*,-32,-32,,-32,-32,-32
ARK_GPS,*,,,,,,,,
ARK_RTK_GPS,*,,,,,,,,
AeroFox-Airspeed,*,,,,,,,,
AeroFox-Airspeed-DLVR,*,,,,,,,,
AeroFox-GNSS_F9P,*,,,,,,,,
AeroFox-PMU,*,,,,,,,,
AtomRCF405NAVI,,-32,*,-32,-40,,-32,-32,-40
BeastF7,,*,*,*,*,,*,*,*
BeastF7v2,,*,*,*,*,,*,*,*
BeastH7,,*,*,*,*,,*,*,*
BeastH7v2,,*,*,*,*,,*,*,*
BirdCANdy,*,,,,,,,,
BlitzF745AIO,,,*,*,,,,,
C-RTK2-HP,*,,,,,,,,
CUAV-Nora,,-32,*,-32,-32,,-32,-32,-32
CUAV-Nora-bdshot,,-40,*,-32,-32,,-32,-40,-40
CUAV-X7,,-40,*,-40,-32,,-40,-32,-32
CUAV-X7-bdshot,,-40,*,-32,-32,,-32,-32,-40
CUAV_GPS,*,,,,,,,,
CUAVv5,,-32,*,-40,-40,,-40,-40,-32
CUAVv5-bdshot,,-40,*,-32,-40,,-32,-40,-32
CUAVv5Nano,,-40,*,-40,-40,,-40,-40,-32
CUAVv5Nano-bdshot,,-40,*,-32,-40,,-32,-40,-40
CarbonixF405,*,,,,,,,,
CarbonixL496,*,,,,,,,,
CubeBlack,,-32,*,-32,-32,,-32,-32,-32
CubeBlack+,,-32,*,-32,-32,,-32,-32,-32
CubeBlack-periph,*,,,,,,,,
CubeGreen-solo,,,*,-32,,,,,
CubeOrange,,-32,*,-32,-32,,-32,-32,-32
CubeOrange-ODID,,-32,*,-32,-32,,-32,-32,-32
CubeOrange-SimOnHardWare,,,,-32,,,,,
CubeOrange-bdshot,,-32,*,-32,-32,,-32,-32,-32
CubeOrange-joey,,-32,*,-40,-32,,-32,-32,-32
CubeOrange-periph,*,,,,,,,,
CubeOrange-periph-heavy,*,,,,,,,,
CubeOrangePlus,,-32,*,-32,-32,,-32,-32,-32
CubeOrangePlus-SimOnHardWare,,,,-32,,,,,
CubeOrangePlus-bdshot,,-32,*,-32,-32,,-32,-32,-32
CubePilot-CANMod,*,,,,,,,,
CubePurple,,-32,*,-32,-32,,-32,-32,-32
CubeRedPrimary,,0,*,0,0,,0,0,0
CubeRedSecondary,,*,*,*,*,,*,*,*
CubeSolo,,,*,-32,,,,,
CubeYellow,,-32,*,-32,-32,,-32,-32,-32
CubeYellow-bdshot,,-32,*,-32,-32,,-32,-32,-32
DevEBoxH7v2,,-32,*,-32,-32,,-32,-32,-32
DrotekP3Pro,,-32,*,-32,-32,,-32,-32,-32
Durandal,,-40,*,-32,-40,,-32,-32,-32
Durandal-bdshot,,-32,*,-32,-32,,-32,-32,-32
F35Lightning,,*,*,*,*,,*,*,*
F4BY,,-32,*,-32,-32,,-32,-32,-32
FlyingMoonF407,,-40,*,-32,-40,,-32,-32,-32
FlyingMoonF427,,-40,*,-32,-40,,-32,-40,-32
FlyingMoonH743,,-32,*,-32,-32,,-32,-40,-40
FlywooF405S-AIO,,*,*,*,*,,*,*,*
FlywooF745,,*,*,*,*,,*,*,*
FlywooF745Nano,,*,*,*,*,,*,*,*
FoxeerH743v1,,*,*,*,*,,*,*,*
FreeflyRTK,*,,,,,,,,
G4-ESC,*,,,,,,,,
H757I_EVAL,,,*,,,,,,
H757I_EVAL_intf,,,*,,,,,,
HEEWING-F405,,,*,,,,*,,
HerePro,*,,,,,,,,
Hitec-Airspeed,*,,,,,,,,
HitecMosaic,*,,,,,,,,
HolybroG4_Compass,*,,,,,,,,
HolybroG4_GPS,*,,,,,,,,
HolybroGPS,*,,,,,,,,
KakuteF4,,*,*,*,*,,*,*,*
KakuteF4Mini,,*,*,*,*,,*,*,*
KakuteF7,,-40,*,-40,-40,,-32,-40,-32
KakuteF7-bdshot,,-32,*,-32,-32,,-32,-32,-32
KakuteF7Mini,,*,*,*,*,,*,*,*
KakuteH7,,-32,*,-32,-32,,-32,-32,-32
KakuteH7-Wing,,-32,*,-32,-40,,-40,-40,-32
KakuteH7-bdshot,,-32,*,-32,-32,,-32,-32,-32
KakuteH7Mini,,*,*,*,*,,*,*,*
KakuteH7Mini-Nand,,*,*,*,*,,*,*,*
KakuteH7v2,,-48,*,-48,-48,,-40,-48,-40
MambaF405-2022,,*,*,*,*,,*,*,*
MambaF405US-I2C,,*,*,*,*,,*,*,*
MambaF405v2,,*,*,*,*,,*,*,*
MambaH743v4,,*,*,*,*,,*,*,*
MatekF405,,-32,*,-40,-32,,-32,-40,-40
MatekF405-CAN,,-40,*,-40,-32,,-32,-40,-40
MatekF405-STD,,-32,*,-32,-32,,-32,-32,-32
MatekF405-TE,,-32,*,-32,-32,,-32,-32,-32
MatekF405-TE-bdshot,,-32,*,-32,-32,,-32,-32,-32
MatekF405-Wing,,-32,*,-32,-32,,-32,-32,-32
MatekF405-Wing-bdshot,,-32,*,-32,-32,,-32,-32,-32
MatekF405-bdshot,,-32,*,-24,-32,,-32,-32,-24
MatekF765-SE,,-32,*,-32,-32,,-32,-32,-32
MatekF765-Wing,,-32,*,-32,-32,,-32,-32,-32
MatekF765-Wing-bdshot,,-32,*,-32,-32,,-32,-32,-32
MatekH743,,-32,*,-32,-32,,-32,-32,-32
MatekH743-bdshot,,-32,*,-40,-32,,-40,-32,-32
MatekH743-periph,*,,,,,,,,
MatekL431-Airspeed,*,,,,,,,,
MatekL431-BattMon,*,,,,,,,,
MatekL431-DShot,*,,,,,,,,
MatekL431-EFI,*,,,,,,,,
MatekL431-GPS,*,,,,,,,,
MatekL431-HWTelem,*,,,,,,,,
MatekL431-Periph,*,,,,,,,,
MatekL431-Proximity,*,,,,,,,,
MatekL431-Rangefinder,*,,,,,,,,
MatekL431-bdshot,*,,,,,,,,
MazzyStarDrone,,-40,*,-32,-40,,-32,-40,-32
Nucleo-G491,*,,,,,,,,
Nucleo-L476,*,,,,,,,,
Nucleo-L496,*,,,,,,,,
NucleoH743,,,*,,,,,,
NucleoH755,,,*,,,,,,
OMNIBUSF7V2,,-40,*,-32,-32,,-32,-40,-32
OmnibusNanoV6,,*,*,*,*,,*,*,*
OmnibusNanoV6-bdshot,,*,*,*,*,,*,*,*
PH4-mini,,-40,*,-40,-40,,-40,-40,-40
PH4-mini-bdshot,,-32,*,-40,-32,,-40,-32,-32
Pix32v5,,-40,*,-40,-40,,-40,-40,-32
PixC4-Jetson,,-32,*,-32,-32,,-40,-32,-32
PixFlamingo,,-32,*,-40,-32,,-40,-32,-32
PixPilot-V3,,-32,*,-32,-32,,-32,-32,-32
PixPilot-V6,,-40,*,-40,-32,,-40,-32,-40
PixSurveyA1,,-32,*,-32,-32,,-32,-32,-32
PixSurveyA1-IND,,-32,*,-32,-32,,-32,-32,-32
PixSurveyA2,,-32,*,-32,-40,,-32,-40,-32
Pixhawk1,,-32,*,-32,-32,,-32,-32,-32
Pixhawk1-1M,,-32,*,-32,-32,,-32,-32,-32
Pixhawk1-1M-bdshot,,-32,,-32,-32,,-32,-32,-32
Pixhawk1-bdshot,,-40,,-40,-40,,-40,-40,-32
Pixhawk4,,-32,*,-40,-40,,-40,-40,-32
Pixhawk4-bdshot,,-40,*,-32,-40,,-32,-40,-32
Pixhawk5X,,-32,*,-32,-32,,-32,-32,-40
Pixhawk6C,,-32,*,-32,-32,,-32,-32,-32
Pixhawk6C-bdshot,,-32,*,-32,-32,,-32,-32,-32
Pixhawk6X,,-40,*,-32,-40,,-32,-40,-40
Pixhawk6X-ODID,,-32,*,-40,-32,,-32,-40,-32
Pixhawk6X-bdshot,,-32,*,-32,-32,,-32,-32,-32
Pixracer,,-32,*,-32,-40,,-40,-40,-32
Pixracer-bdshot,,-32,*,-32,-32,,-32,-32,-32
Pixracer-periph,*,,,,,,,,
QioTekZealotF427,,-32,*,-40,-32,,-40,-40,-40
QioTekZealotH743,,-32,*,-40,-32,,-40,-40,-40
QioTekZealotH743-bdshot,,-32,*,-32,-32,,-32,-40,-32
R9Pilot,,-32,*,-32,-32,,-32,-32,-32
airbotf4,,*,*,*,*,,*,*,*
bbbmini,,*,,*,*,,*,*,*
blue,,*,,*,*,,*,*,*
crazyflie2,,*,*,*,*,,*,*,*
edge,,*,,*,*,,*,*,*
erlebrain2,,*,,*,*,,*,*,*
f103-ADSB,*,,,,,,,,
f103-Airspeed,*,,,,,,,,
f103-GPS,*,,,,,,,,
f103-HWESC,*,,,,,,,,
f103-QiotekPeriph,*,,,,,,,,
f103-RangeFinder,*,,,,,,,,
f103-Trigger,*,,,,,,,,
f303-GPS,*,,,,,,,,
f303-HWESC,*,,,,,,,,
f303-M10025,*,,,,,,,,
f303-M10070,*,,,,,,,,
f303-MatekGPS,*,,,,,,,,
f303-PWM,*,,,,,,,,
f303-TempSensor,*,,,,,,,,
f303-Universal,*,,,,,,,,
f405-MatekAirspeed,*,,,,,,,,
f405-MatekGPS,*,,,,,,,,
fmuv2,,-32,,-32,-32,,-32,-32,-32
fmuv3,,-32,*,-32,-32,,-32,-32,-32
fmuv3-bdshot,,-32,,-40,-32,,-32,-32,-40
fmuv5,,-32,*,-32,-32,,-32,-32,-32
iomcu,,,,,,*,,,
iomcu_f103_8MHz,,,,,,*,,,
luminousbee4,,-40,,-32,-32,,-32,-40,-32
luminousbee5,,-40,*,-40,-32,,-40,-32,-40
mRo-M10095,*,,,,,,,,
mRoCANPWM-M10126,*,,,,,,,,
mRoControlZeroClassic,,-32,*,-32,-32,,-32,-32,-32
mRoControlZeroF7,,-32,*,-32,-32,,-32,-32,-32
mRoControlZeroH7,,-32,*,-32,-32,,-32,-32,-32
mRoControlZeroH7-bdshot,,-32,*,-32,-32,,-32,-32,-32
mRoControlZeroOEMH7,,-32,*,-32,-32,,-32,-40,-32
mRoNexus,,-32,*,-40,-32,,-32,-40,-32
mRoPixracerPro,,-32,*,-32,-32,,-32,-32,-32
mRoPixracerPro-bdshot,,-32,*,-32,-40,,-32,-40,-32
mRoX21,,-32,*,-40,-32,,-32,-32,-40
mRoX21-777,,-32,*,-32,-32,,-32,-32,-32
mindpx-v2,,-32,*,-32,-32,,-32,-32,-32
mini-pix,,-32,*,-32,-32,,-32,-32,-32
modalai_fc-v1,,-32,*,-32,-32,,-32,-40,-32
navigator,,*,,*,*,,*,*,*
navio,,*,,*,*,,*,*,*
navio2,,*,,*,*,,*,*,*
obal,,*,,*,*,,*,*,*
omnibusf4,,-32,*,-32,-32,,-32,-32,-32
omnibusf4pro,,-32,*,-32,-32,,-32,-32,-32
omnibusf4pro-bdshot,,-24,*,-32,-32,,-24,-32,-24
omnibusf4pro-one,,-32,*,-32,-32,,-32,-32,-32
omnibusf4v6,,*,*,*,*,,*,*,*
pxf,,*,,*,*,,*,*,*
pxfmini,,*,,*,*,,*,*,*
```

**Comment by peterbarker** [comment]
> Why not put these in the logging header and make them dependent on sd card logging?

They could be, and I did consider that.  However, the other HALs are specifying these defines in their own weird and wonderful ways, so I decided to retain that symmetry.

Defaulting in chibios_hwdef.py is the way we've done a lot of other similar cleanups....doing it this way retricts everything to being in just the ChibiOS parts of the code for now.

I think we *can* do more cleanups here, as you describe - but it does require more thought than I've given it.  Those cleanups should be rather smaller than this patch, I hope!

**Comment by peterbarker** [comment]
I've checked that SD card still works on CubeOrangePlus.

**Pull request merged**
