### PR TITLE
[GCS MAVLink] Fix build for builds with GPS_MAX_RECEIVERS = 1

### PR DESCRIPTION
**Pull request by giacomo892**

### CODE REVIEW

**Review by peterbarker — CHANGES_REQUESTED** [review]
Commit message should be `GCS_MAVLink:`, not `[GCS_MAVLink]`

**Comment by giacomo892** [comment]
> Commit message should be `GCS_MAVLink:`, not `[GCS_MAVLink]`

Addressed. Idk what I was thinking about :P

**Review by peterbarker — APPROVED** [review]
LGTM

**Review by tridge — APPROVED** [review]

**Comment by peterbarker** [comment]
Thanks @giacomo892

**Pull request merged**
