### PR TITLE
SITL: adding Tricopter model in Webots

### PR DESCRIPTION
**Pull request by HefnySco**
This PR contains a Tricopter model.
It is control signals are all correct and it is flying ok. PID params can be enhanced better.

### CODE REVIEW

**Comment by HefnySco** [comment]
@OXINARF could you kindly proceed with this PR.

**Comment by OXINARF** [comment]
Given this only affects Webots and @HefnySco is the original developer (and so maintainer) of it, I've merged it (I took a quick look at code too obviously). Thank you @HefnySco!

**Comment by peterbarker** [comment]
We don't ordinarily carry compiled binaries in our tree.

Was it intentional to do so as part of this PR?

**Comment by OXINARF** [comment]
> We don't ordinarily carry compiled binaries in our tree.

@peterbarker With Webots we do, so I just followed the same procedure of accepting it.

**Comment by HefnySco** [comment]
Guys @OXINARF @peterbarker ,
I am sorry I dont get it. I only uploaded .c & .h files in example folder which are necessary for Webots to compile controllers for vehicles.
other files are world files that is used by webots and they are in JSON format.
Files like  ".so or lib or exe" should not be uploaded.
Please let me know if I violated any thing so that I can correct it.
Thanks,
M.Hefny

**Comment by OXINARF** [comment]
@HefnySco You have committed (now and before) binary files: https://github.com/ArduPilot/ardupilot/pull/12281/files#diff-b72b3a79c118b4b41fd5c35e60acef74 I thought this was intentional, if it isn't, can you do a PR removing them?

**Comment by HefnySco** [comment]
Thank you Guys for informing me.
I implemented the PR [here](https://github.com/ArduPilot/ardupilot/pull/12442).

**Pull request merged**
