### PR TITLE
Rover: move AP_Mission object into ModeAuto class

### PR DESCRIPTION
**Pull request by peterbarker**
This mirrors what we did for Copter

### CODE REVIEW

**Comment by rmackay9** [comment]
great.  as a follow up we should actually move the implementation into mode_auto.cpp

**Comment by rmackay9** [comment]
it looks like this may be failing SITL for a real reason..

**Comment by peterbarker** [comment]
@rmackay9 @lvale @tridge This is failing to compile for the same reason things aren't working on Mac for Luis :-)  It's unrelated to this PR.

It *is* a real bug which tridge and I are looking at at the moment; object initialisation order seems to be wonky.

Nice to see CI is now catching it - sometimes...

**Comment by rmackay9** [comment]
Merged, thanks!

**Pull request merged**
