### PR TITLE
Plane: Move soaring functions to mode_thermal.

### PR DESCRIPTION
**Pull request by samuelctabor**
Copy-paste of thermalling logic and helper functions from `soaring.cpp` to `mode_thermal.cpp`.

### CODE REVIEW

**Review by magicrub — APPROVED** [review]

**Comment by peterbarker** [comment]
Doesn't this change mean a whole heap more code in here will be running at the main loop rate rather than 50Hz?

Perhaps instead of moving just this chunk of code, `update_soaring` could be moved into the mode itself - you can call a method on a class in the scheduler table with `SCHED_TASK_CLASS`.  Or perhaps just factor this code into a separate function in the mode?  The call could be left in the current location where the code's being removed from or put in some sort of decimated call within Soaring's `update`.

**Comment by samuelctabor** [comment]
> Doesn't this change mean a whole heap more code in here will be running at the main loop rate rather than 50Hz?
> 
> Perhaps instead of moving just this chunk of code, `update_soaring` could be moved into the mode itself - you can call a method on a class in the scheduler table with `SCHED_TASK_CLASS`. Or perhaps just factor this code into a separate function in the mode? The call could be left in the current location where the code's being removed from or put in some sort of decimated call within Soaring's `update`.

Hmm, yes I guess I'm running the default main loop rate of 50Hz, which is the same rate as `update_soaring`, so I didn't see any difference in flight.

**Comment by samuelctabor** [comment]
@peterbarker  as you suggested I've factored the moved code into a separate method on mode_thermal, called from the original task.

The CI failure is unrelated (rover/sub test).

**Review by peterbarker — APPROVED** [review]
This LGTM - 'though I am assuming you've moved the code across essentially verbatim.

It does occur to me that we should probably run the themal update logic immediately when we `             set_mode(mode_thermal, ModeReason::SOARING_THERMAL_DETECTED);` - but that's a pre-existing problem.  That'd best be done with a "switch if required" followed by early-return-if-we're-not-in-thermalling followed by making the thermal update call.  IOW the "mode-thermal" case would be removed from the switch.

**Comment by samuelctabor** [comment]
> This LGTM - 'though I am assuming you've moved the code across essentially verbatim.
> 
> It does occur to me that we should probably run the themal update logic immediately when we ` set_mode(mode_thermal, ModeReason::SOARING_THERMAL_DETECTED);` - but that's a pre-existing problem. That'd best be done with a "switch if required" followed by early-return-if-we're-not-in-thermalling followed by making the thermal update call. IOW the "mode-thermal" case would be removed from the switch.

Not sure I fully understand . . . there is certainly some further cleanup that I'm planning for follow-up PRs.

The EU dev call would be a much better time for me.

**Review by tridge — APPROVED** [review]

**Pull request merged**
