### PR TITLE
AP_GPS: remove blended GPS from small boards

### PR DESCRIPTION
**Pull request by peterbarker**
those boards which are not including all backends will lose blended after this
```
Board                    AP_Periph  blimp  bootloader  copter  heli   iofirmware  plane  rover  sub
CubeOrange-periph-heavy  *
Durandal                            *      *           *       *                  *      *      *
Hitec-Airspeed           *
KakuteH7-bdshot                     *      *           *       *                  *      *      *
MatekF405                           -2688  *           -2656   -2680              -2792  -2680  -2688
Pixhawk1-1M-bdshot                  -2624              -2664   -2656              -2624  -2672  -2624
f103-QiotekPeriph        *
f303-Universal           *
iomcu                                                                 *
revo-mini                           -2648  *           -2752   -2680              -2552  -2680  -2664
skyviper-v2450                                         *
```

### CODE REVIEW

**Comment by peterbarker** [comment]
This is the full list of boards affected:
```
pbarker@threads:/tmp$ ~/rc/ardupilot/Tools/scripts/filter_size_compare_branches_csv.py /tmp/some.csv  --hide-bin 
------------------------  ---------  -----  ----------  ------  -----  -----  -----  -----
Board                     AP_Periph  blimp  bootloader  copter  heli   plane  rover  sub
ACNS-CM4Pilot                        -2720  *           -2648   -2616  -2568  -2696  -2648
ACNS-F405AIO                         -2640  *           -2608   -2688  -2632  -2640  -2632
AtomRCF405NAVI                       -2680  *           -2664   -2672  -2792  -2680  -2688
BETAFPV-F405                                *           -2752
BeastF7                              -2696  *           -2752   -2744  -2736  -2736  -2704
BeastF7v2                            -2696  *           -2752   -2744  -2736  -2736  -2712
BlitzF745AIO                                *           -2664
CarbonixF405              -3080
CarbonixL496              -3080
F35Lightning                         -2696  *           -2752   -2744  -2736  -2736  -2704
F4BY                                 -2632  *           -2664   -2672  -2616  -2552  -2680
FlyingMoonF407                       -2632  *           -2664   -2672  -2616  -2552  -2680
FlywooF405Pro                               *           -2752
FlywooF405S-AIO                             *           -2304
FlywooF745                           -2664  *           -2624   -2608  -2656  -2664  -2592
FlywooF745Nano                       -2656  *           -2624   -2608  -2656  -2664  -2600
HEEWING-F405                                *                          -2736
HEEWING-F405v2                              *                          -2736
JHEM_JHEF405                                *           -2696
KakuteF4                             -2696  *           -2752   -2744  -2736  -2736  -2712
KakuteF4Mini                         -2696  *           -2760   -2744  -2776  -2744  -2712
KakuteF7                             -2680  *           -2664   -2672  -2792  -2680  -2688
KakuteF7-bdshot                      -2680  *           -2656   -2680  -2792  -2680  -2688
KakuteF7Mini                         -2696  *           -2760   -2744  -2768  -2736  -2712
MambaF405-2022                       -2648  *           -2304   -2408  -2560  -2648  -2632
MambaF405US-I2C                      -2696  *           -2752   -2744  -2736  -2744  -2712
MambaF405v2                          -2648  *           -2304   -2408  -2560  -2648  -2632
MatekF405                            -2688  *           -2656   -2680  -2792  -2680  -2688
MatekF405-CAN                        -2720  *           -2648   -2632  -2648  -2696  -2656
MatekF405-STD                        -2680  *           -2664   -2672  -2792  -2680  -2696
MatekF405-TE                         -2616  *           -2600   -2600  -2680  -2632  -2624
MatekF405-TE-bdshot                  -2616  *           -2600   -2608  -2680  -2632  -2624
MatekF405-Wing                       -2704  *           -2704   -2760  -2880  -2728  -2712
MatekF405-Wing-bdshot                -2712  *           -2704   -2760  -2880  -2728  -2720
MatekF405-bdshot                     -2688  *           -2664   -2672  -2792  -2680  -2688
MazzyStarDrone                       -2696  *           -2728   -2680  -2736  -2680  -2728
Nucleo-L476               -3080
Nucleo-L496               -3168
OMNIBUSF7V2                          -2640  *           -2736   -2656  -2848  -2592  -2648
OmnibusNanoV6                        -2696  *           -2752   -2744  -2736  -2744  -2704
OmnibusNanoV6-bdshot                 -2696  *           -2752   -2744  -2736  -2744  -2712
OrqaF405Pro                          -2696  *           -2752   -2744  -2736  -2736  -2704
Pixhawk1-1M                          -2624  *           -2664   -2656  -2616  -2664  -2624
Pixhawk1-1M-bdshot                   -2624              -2664   -2656  -2624  -2672  -2624
QioTekAdeptF407                      -2648  *           -2680   -2728  -2760  -2728  -2664
ReaperF745                           -2696  *           -2672   -2720  -2448  -2680  -2776
SITL_arm_linux_gnueabihf             0                  0       0      0      0      0
SITL_x86_64_linux_gnu                0                  0       0      0      0      0
SpeedyBeeF405Mini                           *           -2752
SpeedyBeeF405WING                    -2688  *           -2680   -2664  -2664  -2664  -2680
SuccexF4                                    *           -2336
VRBrain-v51                          -2680  *           -2952   -2936  -2712  -2648  -2736
VRBrain-v52                          -2688  *           -2952   -2936  -2720  -2640  -2744
VRCore-v10                           -2680  *           -2952   -2936  -2712  -2648  -2736
VRUBrain-v51                         -2680  *           -2480   -2424  -2752  -2656  -2704
ZubaxGNSS                 -3280
airbotf4                             -2680  *           -2704   -2728  -2696  -2656  -2736
crazyflie2                                  *           -2672
fmuv2                                -2680              -2624   -2600  -2608  -2696  -2664
mini-pix                             -2648  *           -2672   -2592  -2536  -2696  -2664
omnibusf4                            -2576  *           -2560   -2624  -1848  -2592  -2552
omnibusf4pro                         -2576  *           -2560   -2624  -1856  -2592  -2552
omnibusf4pro-bdshot                  -2576  *           -2560   -2624  -1856  -2592  -2552
omnibusf4v6                          -2696  *           -2752   -2744  -2736  -2744  -2704
revo-mini                            -2648  *           -2752   -2680  -2552  -2680  -2664
revo-mini-bdshot                     -2648  *           -2752   -2680  -2552  -2680  -2664
revo-mini-i2c                        -2696  *           -2752   -2744  -2736  -2736  -2704
revo-mini-i2c-bdshot                 -2696  *           -2752   -2744  -2736  -2736  -2712
sparky2                              -2656  *           -2672   -2592  -2624  -2568  -2688
speedybeef4                          -2696  *           -2752   -2744  -2736  -2744  -2704
speedybeef4v3                        -2680  *           -2656   -2672  -2720  -2680  -2696
speedybeef4v4                        -2680  *           -2656   -2672  -2728  -2680  -2688
------------------------  ---------  -----  ----------  ------  -----  -----  -----  -----
pbarker@threads:/tmp$ 
```

@andyp1per - do these boards need to be able to blend GPSs?

**Comment by andyp1per** [comment]
> do these boards need to be able to blend GPSs?

I have no idea. Maybe some of them - e.g. some of the more pro boards

**Comment by peterbarker** [comment]
> > do these boards need to be able to blend GPSs?
> 
> I have no idea. Maybe some of them - e.g. some of the more pro boards

So the way some of these boards are getting to this point is including `minimal_gps.inc`:

```
libraries/AP_HAL_ChibiOS/hwdef/MatekF405-CAN/hwdef.dat:include ../include/minimal_GPS.inc
libraries/AP_HAL_ChibiOS/hwdef/MatekF405-bdshot/hwdef.dat:include ../include/minimal_GPS.inc
libraries/AP_HAL_ChibiOS/hwdef/Pixhawk1-1M/hwdef.dat:include ../include/minimal_GPS.inc
libraries/AP_HAL_ChibiOS/hwdef/Sierra-TrueNavPro/hwdef.dat:include ../include/minimal_GPS.inc
libraries/AP_HAL_ChibiOS/hwdef/omnibusf4pro-bdshot/hwdef.dat:include ../include/minimal_GPS.inc
```

Most of them get it from including `minimize_common.inc` via `minimize_fpv_osd.inc`, however, which is why I poked you :-)

**Comment by peterbarker** [comment]
I flew this on a Mini-Pix without issue

**Review by tridge — APPROVED** [review]

**Pull request merged**
