### PR TITLE
Added mag and dataflash logging support to AnyLeaf H7

### PR DESCRIPTION
**Pull request by David-OConnor**
https://github.com/ArduPilot/ardupilot/pull/26999

### CODE REVIEW

**Comment by andyp1per** [comment]
Now you need to modify the commit message to start with "AP_HAL_ChibiOS: "

```
git rebase -i HEAD~
```
The use "r" for reword, edit the message and finish

**Comment by David-OConnor** [comment]
Hmm... Just tried that and...

**Comment by David-OConnor** [comment]
Now the squash process is passing, but adds 2 commits each time.

**Comment by David-OConnor** [comment]
I'm going to pause on troubleshooting, as each thing I try increases the commit log size.

**Comment by David-OConnor** [comment]
Now I get this:

```
PS C:\Users\the_a\Desktop\t7\ardupilot> git rebase -i HEAD~7

Auto-merging ArduCopter/compassmot.cpp
CONFLICT (content): Merge conflict in ArduCopter/compassmot.cpp
error: could not apply d198c3e13d... Copter: emit system time during compassmot on SITL
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply d198c3e13d... Copter: emit system time during compassmot on SITL
PS C:\Users\the_a\Desktop\t7\ardupilot>
```

Somehow this file is still conflicting with unrelated code when I go to squash the commits.

**Comment by andyp1per** [comment]
I've fixed it for you

**Comment by David-OConnor** [comment]
Thank you!

**Comment by peterbarker** [comment]
Merged it, thanks!

**Pull request merged**
