### PR TITLE
Stop using HAL_BUILD_AP_PERIPH to gate GPS backends

### PR DESCRIPTION
**Pull request by peterbarker**
.... instead, use explicit backend defines in the relevant hwdef files

### CODE REVIEW

**Review by khancyr — APPROVED** [review]
LGTM

**Comment by peterbarker** [comment]
Pixhawk1-1M and Matek-F405 are unchanged size-wise

f103-GPS saves 
```
ap_periph      -216 (-0.2109%)  0 (0.0000%)  0 (0.0000%)  -216 (-0.2106%)                                    3104
```

because we weren't gating everything out correctly.

**Comment by tridge** [comment]
need to check build size not changing for HitecMosaic and f303-GPS and f303-Universal

**Comment by peterbarker** [comment]
I put this firmware onto an mRo v1 with an f103 on it using f103-GPS and I got a UAVCAN GPS out of it - including an actual fix indoors...

**Review by tridge — APPROVED** [review]

**Pull request merged**
