### PR TITLE
Separate words with spaces in a help message

### PR DESCRIPTION
**Pull request by Boreas7**

### CODE REVIEW

**Comment by rmackay9** [comment]
Looks good, one small thing is the commit message should be prefixed with the subsystem (or directory) name.  so in this case "Tools: ".

**Comment by Boreas7** [comment]
Thanks, Randy. I'll do that for the future changes. Do you want me to correct this commit?

**Comment by rmackay9** [comment]
@Boreas7, if you can that would be good..  Just force push it to the branch.  If it's gets too hard or complicated I can do it as part of the merge it just takes a couple extra steps for me to do that.

**Comment by Boreas7** [comment]
Randy, that seemed to work. Let me know if anything else needs to be done.

**Comment by rmackay9** [comment]
Merged, thanks!

**Pull request merged**
