### PR TITLE
autotest: large outliers in sub terrain test have low sq

### PR DESCRIPTION
**Pull request by clydemcqueen**
The current test.Sub.SimTerrainSurftrak noise configuration is causing ~more~ test failures ~than we'd like~.

This PR adds `outlier_good_sq_limit` to the configuration. If the error exceeds `outlier_good_sq_limit` then the signal quality drops from 100 (best) to 50 (bad). `Sub::read_rangefinder()` tests for this, so large outliers are rejected. This should ~minimize~ eliminate test failures, and it also exercises the sq test in `Sub::read_rangefinder()`.

Edit: I also fixed some test names and a few typos

### CODE REVIEW

**Comment by clydemcqueen** [comment]
@ptrmu Please take a look

**Comment by peterbarker** [comment]
Just a note.  No test failures are acceptable - the test must be 100% (as-designed ;-) ), even in the face of adding random noise.

People seem to have this thing against flapping tests :-)

**Comment by clydemcqueen** [comment]
@peterbarker got it!

I pushed another commit (I'll squash later), this should eliminate all test failures:
* all outliers > 1m have low signal quality, so they will be dropped
* the rf target is explicitly set

**Comment by ptrmu** [comment]
Looks great!

**Review by peterbarker — APPROVED** [review]
Anything which reduces false positives is good in my book :-)

**Review by Williangalvani — APPROVED** [review]
Looks good!

**Comment by peterbarker** [comment]
Merged, thanks!

**Pull request merged**
