### PR TITLE
Copter: fix typo from https://github.com/ArduPilot/ardupilot/pull/4714

### PR DESCRIPTION
**Pull request by khancyr**

### CODE REVIEW

**Comment by rmackay9** [comment]
Merged, thanks!

**Comment by R-Lefebvre** [comment]
Woah, nice catch.

**Comment by rmackay9** [comment]
Actually we #define ENABLE/DISABLE to be the same as ENABLED/DISABLED so functionally it doesn't make a difference (I think).  We did have real bugs like this many years ago which is why we added the additional #defines.

**Comment by R-Lefebvre** [comment]
Ah, OK.  I remember mis-spelling FRAME_CONFIG or something once and that caused problems.

**Comment by peterbarker** [comment]
I'd like to know why -Wundef didn't pick it up....

**Comment by khancyr** [comment]
The fact is when doing advance failsafe for rover, I copy-paste copter version with ENABLE. But on Rover it was failling to compile. So look at copter and see that it was ENABLE and not ENABLED but it was working... a little grep conform me that it was a type error.

**Pull request closed without merging**
