### PR TITLE
AP_Arming: Allow disarming to force the safety switch

### PR DESCRIPTION
**Pull request by WickedShell**
I should have made this a long time ago, as this is a continual confusion/pain point for users. The overall principle is that when the vehicle autolands and disarms it self to be safe on the ground we should take this as far as possible and also force the safety switch state to the disarmed position. It also fixes a number of problems with users forgetting to use the button to help make the vehicle safe again/bumping outputs, and general handling/confusion.

(This also helps make it easier to treat the button as a pre arm only step)

### CODE REVIEW

**Comment by rmackay9** [comment]
Putting on my parameter police hat for a moment - the other safety switch parameters are all under BRD_.  Do we want to split them up like this?

**Comment by Pedals2Paddles** [comment]
Excellent idea. However, what is the impact of this if you've disabled the safety switch?  I realize the easy answer is don't set this new parameter either.  But if you do set this, and the safety switch is disabled (or non-existent), I presume you're parked until rebooting?

**Comment by Naterater** [comment]
I just hope that in-air disarms don't also engage the safety switch for me... With planes I can survive without a motor, but not without servo outputs.

**Comment by WickedShell** [comment]
@Pedals2Paddles It's opt in. If you set this but disable the safety switch then the safety will come on. You can send a MAVLink message to restore it, but yes. (Given that you have to opt into this, and out of the safety switch I think this is quite acceptable though).

@Naterater Core problem is why are you getting in air disarms? Follow up: yes if you opt in that would stop the outputs. If you set the mask of servos to ignore the safety switch you would have servos even if the safety is on. Again because this is an opt in behaviour I think it's a quite acceptable balance. (I think it would make sense even as default if safety switch was generally enabled but I'm not pushing that for now :) )

**Comment by WickedShell** [comment]
@rmackay9 it's fundamentally associated with arming though which leaves an argument for calling it `ARMING` and it is something that is best done when disarming rather then by polling elsewhere.

**Comment by WickedShell** [comment]
Dev call: Move to BRD_SAFETYOPTION

**Comment by tridge** [comment]
as discussed on call, we will move this to a bit under BRD_SAFETYOPTION

**Comment by WickedShell** [comment]
Rebased and uses `BRD_SAFETYOPTION`

**Pull request merged**
