### PR TITLE
Manifest generation fix

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
Fix for #11632. The parsing of heli directory names was incorrect causing the platform to be set incorrectly which then caused all sorts of other downstream problems with the parser.

@peterbarker I left eh addition of "dirty" into release types in the pull. Not sure of that's ok.

### CODE REVIEW

**Comment by DonLakeFlyer** [comment]
Oops forgot some stuff:

* Manifest generation before changes: https://qgroundcontrol.s3-us-west-2.amazonaws.com/DonLakeFlyer/manifest.json.orig
* Manifest generated after changes: https://qgroundcontrol.s3-us-west-2.amazonaws.com/DonLakeFlyer/manifest.json
* Diff of before/after: https://qgroundcontrol.s3-us-west-2.amazonaws.com/DonLakeFlyer/manifest.json.diff

**Comment by tridge** [comment]
looks good, thanks @DonLakeFlyer !

**Comment by rmackay9** [comment]
@DonLakeFlyer, is this your first commit?  congrats and thanks!

One small thing, normally we prefix our commits with the subsystem name.  So for example this commit should have started with "Tools: ".  We like to do this because it makes it easier when it comes time to review a potentially massive list of commits to find those that are relevant for a release.  So for example, if I'm doing a Copter release, I can just look at the first few characters and judge quickly whether the commit is likely relevant for my release or not.

**Comment by DonLakeFlyer** [comment]
> is this your first commit?

Hmm, looking back at history my last one was in 2016!

> So for example this commit should have started with "Tools: ".

Got it.

**Comment by peterbarker** [comment]
This commit has broken the manifest.  The removed comments explained what was going on.

This is what we now have:
```
            "platform": "navio-octa", 
```

What we should have:

```
            "platform": "navio", 
            "frame": "octa",
```

**Pull request merged**
