### PR TITLE
AP Periph with Overhaul CAN System Layer

### PR DESCRIPTION
**Pull request by bugobliterator**
Tests:
- [x] F103 Peripheral Boards
- [x] F303 Peripheral Boards
- [x] H7 Peripheral Boards

### CODE REVIEW

**Comment by tridge** [comment]
@bugobliterator I tested this remotely on a f103 board that @pkocmoud had. It runs nicely.
The only problem now is that this disables most I2C compasses on the f103-GPS build. The f103-GPS build should include as many compasses as possible or it will break existing setups. Can you try and find another couple of kb or flash savings?

**Comment by bugobliterator** [comment]
> @bugobliterator I tested this remotely on a f103 board that @pkocmoud had. It runs nicely.
> The only problem now is that this disables most I2C compasses on the f103-GPS build. The f103-GPS build should include as many compasses as possible or it will break existing setups. Can you try and find another couple of kb or flash savings?

@tridge It already fits with all compasses enabled, I reverted bootloader to use ChibiOS driver to make that happen. I have pushed a commit that enables compasses on f103-GPS boards by default now.

**Comment by tridge** [comment]
@bugobliterator I've found the cause for the bl getting bigger - turns out it was my code that changed UART_ORDER to SERIAL_ORDER. I've added a commit to this PR to fix it, and now f103 bootloader is back to its old size

**Review by tridge — APPROVED** [review]

**Comment by tridge** [comment]
tested on a f103-GPS, all seems to be working, thanks!

**Comment by tridge** [comment]
failing revo-mini bl build

**Comment by peterbarker** [comment]
revo-mini build is failing with `AP_Bootloader.cpp:(.text.startup.main+0x5e): undefined reference to `can_update()'`

**Comment by tridge** [comment]
> revo-mini build is failing with `AP_Bootloader.cpp:(.text.startup.main+0x5e): undefined reference to `can_update()'`

fixed

**Comment by peterbarker** [comment]
Merged, thanks!

**Pull request merged**
