### PR TITLE
Rover 4.3 how to add user code init for rover,plane 

### PR DESCRIPTION
**Pull request by yanakorn2544**
Rover 4.3 how to add user code init for rover,plane

### CODE REVIEW

**Comment by rmackay9** [comment]
Looks like a mistake so closing

**Comment by yanakorn2544** [comment]
I want to add user code like in arducopter to ardurover.

**Comment by rmackay9** [comment]
@yanakorn2544,

Ideally we would prefer if lua scripts were used.  If you really want to add USER_HOOKS then it should be possible to implement it very much like in Copter.  New items would need to be added to the scheduler in Rover.cpp.

**Comment by yanakorn2544** [comment]
Can you suggest me a schedule for where is rover.cpp and what part?

**Pull request closed without merging**
