### PR TITLE
Create AP_Proximity intermediate Serial backend

### PR DESCRIPTION
**Pull request by peterbarker**
Saves 264 bytes on MatekF405-Wing.

I only have a physical RPLidarA2 to test this on.

I do have a simulation for the RPLidarA2, but it's not ready to go yet.

### CODE REVIEW

**Comment by peterbarker** [comment]
I've now tested this on my RPLidarA2.

**Comment by rmackay9** [comment]
@peterbarker, I can also test with my SF40C.. i'm away from my desk until later today but after that I should be able to test it I think.

**Comment by peterbarker** [comment]
@rmackay9 Could you test this, please?

**Comment by rmackay9** [comment]
I never tested this on my SF40C as I promised to above but Copter-4.0.0 is out now so hopefully it will be tested as a matter of course in master.  Merged, thanks!

**Pull request merged**
