### PR TITLE
Copter: Match cyclic rate to scheduler rate

### PR DESCRIPTION
**Pull request by muramura**
I'm testing flight with a Copter scheduler rate other than 400.
I think it's better to adjust from 400 fixed to scheduler rate.

### CODE REVIEW

**Comment by peterbarker** [comment]
Did you see this line in the driver?

```
    const uint16_t inertial_buffer_size = MAX((uint16_t)roundf(_lag * MIN(update_rate_hz, AP::scheduler().get_loop_rate_hz())), 1);
```

Are you slowing the main loop down?  If not, your change shouldn't have an effect, I'd have thought.

**Comment by muramura** [comment]
@peterbarker san.
I use Durandal and have a scheduler rate of 800Hz.

**Comment by peterbarker** [comment]
Ah.  I misread it.  So this will allocate more memory for the buffer.

**Review by amilcarlucas — CHANGES_REQUESTED** [review]
There is also a place i the yaw controller that is hardcoded at 100 Hz (400/4)

**Comment by muramura** [comment]
@khancyr san. Comment Thanks.
I understood that it was up to 400Hz.
I change it to specify 400 in the init method with no arguments.

**Comment by amilcarlucas** [comment]
Can you rebase this on master?

**Comment by peterbarker** [comment]
Replaced by https://github.com/ArduPilot/ardupilot/pull/28192

Turns out that parameter was important.

Thanks all.

**Pull request closed without merging**
