### PR TITLE
Allow Simulations to be run on our embedded platforms

### PR DESCRIPTION
**Pull request by peterbarker**
This allows simulations - generally known as "SITL" to be run on our embedded stm32-based platforms.

There are several precursor PRs that have been extracted from this to make it less daunting.

There are a few debug commits which will be removed before merge.

This can be tested by appending `env SIM_ENABLED 1` to a hwdef.dat file and flashing onto an autopilot.

At this point no actuators are allowed to move; this is likely to change before merge.

### CODE REVIEW

**Comment by amilcarlucas** [comment]
This is a huge step forward Peter !!! Thanks.

**Comment by nkruzan** [comment]
I am trying to compile for MatekF405-Wing... i have made some changes to get to compile this far but i struggle at this point, unsure what im doing wrong 
```
[736/825] Compiling libraries/AC_Fence/AC_Fence.cpp
In file included from ../../libraries/AP_HAL_ChibiOS/Semaphores.h:21,
                 from ../../libraries/AP_HAL/board/chibios.h:64,
                 from ../../libraries/AP_HAL/AP_HAL_Boards.h:137,
                 from ../../libraries/SITL/SIM_GPS.h:26,
                 from ../../libraries/SITL/SIM_GPS.cpp:9:
../../libraries/AP_HAL/AP_HAL_Macros.h:33:17: error: 'DO_NOT_USE_DOUBLE_MATHS' was not declared in this scope

```

here is branch with changes i have made https://github.com/peterbarker/ardupilot/compare/pr/sitl-on-hw...nkruzan:test/sitl-on-matekf405

thanks for any direction you can give.

**Comment by peterbarker** [comment]
> I am trying to compile for MatekF405-Wing... i have made some changes to get to compile this far but i struggle at this point, unsure what im doing wrong
> 
> ```
> [736/825] Compiling libraries/AC_Fence/AC_Fence.cpp
> In file included from ../../libraries/AP_HAL_ChibiOS/Semaphores.h:21,
>                  from ../../libraries/AP_HAL/board/chibios.h:64,
>                  from ../../libraries/AP_HAL/AP_HAL_Boards.h:137,
>                  from ../../libraries/SITL/SIM_GPS.h:26,
>                  from ../../libraries/SITL/SIM_GPS.cpp:9:
> ../../libraries/AP_HAL/AP_HAL_Macros.h:33:17: error: 'DO_NOT_USE_DOUBLE_MATHS' was not declared in this scope
> ```
> 
> here is branch with changes i have made [peterbarker/ardupilot@pr/sitl-on-hw...nkruzan:test/sitl-on-matekf405](https://github.com/peterbarker/ardupilot/compare/pr/sitl-on-hw...nkruzan:test/sitl-on-matekf405)
> 
> thanks for any direction you can give.

https://github.com/ardupilot/ardupilot/blob/master/libraries/AP_HAL/AP_HAL_Macros.h#L9

That line probable needs a `(CONFIG_HAL_BOARD == HAL_BOARD_CHIBIOS && AP_SIM_ENABLED)`

**Comment by nkruzan** [comment]
> That line probable needs a `(CONFIG_HAL_BOARD == HAL_BOARD_CHIBIOS && AP_SIM_ENABLED)`

thanks that got me past that error, i pushed more changes i needed to make to get to compile, i got there but it doesnt run after flashing the apj (the 3 led on solid). guess this isn't intended for the 1mb boards? 

only big board i have is beaglebone so cant really test more. bummer. 

maybe some tips in there about what else might need #if/#ifdef out if nothing else.

initially wanted this to test with configurator but now buzz have the udp working so can use actual sitl there. was a fun exercise anyway. thanks for sharing.

**Comment by peterbarker** [comment]
> thanks that got me past that error, i pushed more changes i needed to make to get to compile, i got there but it doesnt run after flashing the apj (the 3 led on solid). guess this isn't intended for the 1mb boards?

OK, so I've replicated that behaviour here on an `F35Lighning` F405.  I've been unable to narrow this down to date; I'll keep playing locally.  If I were to take a guess we're running out of RAM very early on in the boot process.

I *have* flashed this to a `Pixhawk1-1M` - and that does work, and I can run the simulation on it.  The EKF isn't entirely happy and there are many overruns.  Still, you can get up and about with EKF type 10 and move the simulated vehicle around in guided mode.  Since the board has a ToshibaLED you an definitely see when you arm the vehicle :-)

> initially wanted this to test with configurator but now buzz have the udp working so can use actual sitl there. was a fun exercise anyway. thanks for sharing.

Thanks for playing with it :-)

**Comment by nkruzan** [comment]
I did try again earlier today after your changes, but ended up with same result. Had to turn off a bunch of stuff in hwdef, decrease HAL_STORAGE_SIZE and set thermal scenario to 1 to get to compile. Maybe one of these days. :)

**Comment by peterbarker** [comment]
@nkruzan I've not got this branch running on F35Lightning.

Unpleasant issue to find.

Pretty sure what it comes down to is that the BSS was too large.  It's kind of right on the edge, and I think we'll probably need to do a round of "make allocating this object dynamic" in SITL to avoid it in future.  In the meantime I'll just document my way out of trouble with that one....

Would be nice if you could try this again on your MatekF405-Wing.

**Comment by nkruzan** [comment]
@peterbarker i push a branch with my hwdef and attach the apj i am uploading with mission planner 'load custom firmware' note that i am not embedding the bootloader in the apj. 

the steps i followed:
build apj with https://github.com/nkruzan/ardupilot/tree/test/sitl-on-matek-f405-wing-3
flash https://firmware.ardupilot.org/Plane/latest/MatekF405-Wing/arduplane.apj as sanity test using mission planner 'load custom firmware' and make sure it boot after (it does)
flash the attached arduplane.apj with mission planner 'load custom firmware' [arduplane.apj.tar.gz](https://github.com/ArduPilot/ardupilot/files/7965347/arduplane.apj.tar.gz) lights all stay on

i see the blue bootloader led rapid blink for a few seconds, but then red,green,blue led all stay on solid 

device does not appear when view lsusb when all led are on....i get `Bus 002 Device 045: ID 1209:5741 Generic` when bl led is blinky

I'm happy to help test whatever i can, just let me know.

**Comment by peterbarker** [comment]
On Sat, 29 Jan 2022, nkruzan wrote:

> build apj with https://github.com/nkruzan/ardupilot/tree/test/sitl-on-matek-f405-wing-3
> flash https://firmware.ardupilot.org/Plane/latest/MatekF405-Wing/arduplane.apj as sanity test using mission planner 'load custom firmware' and make sure it boot after (it does)
> flash the attached arduplane.apj with mission planner 'load custom firmware' arduplane.apj.tar.gz lights all stay on

Could you try Copter instead - just my branch if possible.

You could also try disabling quadplane and see if that helps.

The problem on the F35Lightning was just running out of memory, and a 
frightfully clever compiler causing issues.  So saving memory 
(particularly bss, so that allocated in static objects) is what's 
required.

**Comment by nkruzan** [comment]
@peterbarker I get same result with copter, only change was to add `env SIM_ENABLED 1`

**Comment by tridge** [comment]
a few notes from testing:
 - EKF unhappy, can go with EKF type 10 if need be, but worth looking at a replay log
 - maybe default to single IMU? SIM_IMU_COUNT=1 and SIM_BARO_COUNT=1
 - logging should be enabled

**Comment by peterbarker** [comment]
>     * EKF unhappy, can go with EKF type 10 if need be, but worth looking at a replay log

Fixed.

>     * maybe default to single IMU? SIM_IMU_COUNT=1 and SIM_BARO_COUNT=1

Simulating IMU failure might be useful....

>     * logging should be enabled

Yep, tested as working.
 
>     * system load looks unreasonably low (4% in 200Hz copter)

We're up to 22% - yay?

>     * needs rebase

Done.

>     * times not matching, off by 9 days

Fixed - it was trying to use GPS as an RTC source... which isn't going to work well...  I've changed the default for `BRD_RTC_TYPES` to only source from mavlink.

**Review by tridge — APPROVED** [review]

**Comment by tridge** [comment]
one more rebase please

**Comment by tridge** [comment]
adding a CubeOrange-SimHW hwdef and params file, so its built on CI and on the build server

**Comment by Nontinium** [comment]
Hey guys , i was able to compile for the F405, , by custom board does not have much featueres so its easier to wokr with, however what i have noticed is that the motors clamp to 1150 max for some reason all the param files are file, checked them already 3 times, if i dont use the Sim on hardware, the motors dont clamp

**Pull request merged**
