### PR TITLE
Add support for CAN bus on CubeOrange (STM32H7)

### PR DESCRIPTION
**Pull request by bugobliterator**
Flight tested with Here Flow and Here GPS.

### CODE REVIEW

**Comment by tridge** [comment]
thanks Sid!
please note the semphore build error for can sniffer example

**Comment by bugobliterator** [comment]
> thanks Sid!
> please note the semphore build error for can sniffer example

Fixed.

**Comment by tridge** [comment]
darn, I just tested with --debug --enable-asserts and it doesn't boot. So we need to find the cause for that

**Comment by tridge** [comment]
The bug is that we're trying to allocate slcan in an interrupt:
gdb) bt
#0  0x0811e378 in chSysHalt (reason=reason@entry=0x8154530 "SV#4") at ../../modules/ChibiOS/os/rt/src/chsys.c:209
#1  0x0811d79e in _dbg_check_lock () at ../../modules/ChibiOS/os/rt/src/chdebug.c:151
#2  0x0811da7c in chSysLock () at ../../modules/ChibiOS/os/rt/include/chsys.h:357
#3  0x0811db84 in chMtxLock (mp=mp@entry=0x20012eec <default_heap+12>) at ../../modules/ChibiOS/os/rt/src/chmtx.c:125
#4  0x0811d568 in chHeapAllocAligned (heapp=0x20012ee0 <default_heap>, heapp@entry=0x0, size=size@entry=344, align=align@entry=8) at ../../modules/ChibiOS/os/oslib/src/chmemheaps.c:192
#5  0x0811f31a in malloc_flags (size=344, flags=flags@entry=0) at ../../libraries/AP_HAL_ChibiOS/hwdef/common/malloc.c:109
#6  0x0811f3f6 in malloc (size=<optimized out>) at ../../libraries/AP_HAL_ChibiOS/hwdef/common/malloc.c:171
#7  0x0811f48a in calloc (nmemb=<optimized out>, size=size@entry=1) at ../../libraries/AP_HAL_ChibiOS/hwdef/common/malloc.c:205
#8  0x0803d904 in operator new (size=<optimized out>, size@entry=344) at ../../libraries/AP_Common/c++.cpp:19
#9  0x0809a0de in SLCANRouter::get_singleton () at ../../libraries/AP_HAL_ChibiOS/CANSerialRouter.h:73
#10 slcan_router () at ../../libraries/AP_HAL_ChibiOS/CANSerialRouter.cpp:29
#11 0x08099ba8 in ChibiOS_CAN::CanIface::readRxFIFO (this=this@entry=0x20019fe0, fifo_index=fifo_index@entry=0 '\000') at ../../libraries/AP_HAL_ChibiOS/CANFDIface.cpp:682
#12 0x08099be6 in ChibiOS_CAN::CanIface::handleRxInterrupt (this=0x20019fe0, fifo_index=fifo_index@entry=0 '\000') at ../../libraries/AP_HAL_ChibiOS/CANFDIface.cpp:689
#13 0x08099c68 in ChibiOS_CAN::(anonymous namespace)::handleInterrupt (line_index=0 '\000', iface_index=1 '\001') at ../../libraries/AP_HAL_ChibiOS/CANFDIface.cpp:99
#14 Vector90 () at ../../libraries/AP_HAL_ChibiOS/CANFDIface.cpp:1056
#15 <signal handler called>
#16 Vector1D4 () at ../../modules/ChibiOS/os/hal/ports/STM32/LLD/OTGv1/hal_usb_lld.c:681
#17 <signal handler called>
#18 0x55555554 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

**Comment by bugobliterator** [comment]
@tridge its fixed now.

**Comment by tridge** [comment]
> @tridge its fixed now.

not quite. You've fixed the symptoms but not the cause. If the allocation failed in the CanIFace constructor then it would still try to call the allocator in get_singleton() from the interrupt handler, causing a crash.
We can't have an allocation call on a path in an interrupt handler.

**Pull request merged**
