### PR TITLE
change acceleration xy with do_change_speed

### PR DESCRIPTION
**Pull request by alexprasetia**
Adding new features

from #9535, following the change from @chobitsfan , in here I try to extend the capability to change horizontal acceleration during an auto mode flight. The code has been tested with SITL.

adding set_accel_xy, a function to change horizontal acceleration in auto mode with Do_Change_Speed Command
Prm1 =4
Prm2 =desired acceleration (m/s^2)

ArduCopter

### CODE REVIEW

**Comment by rmackay9** [comment]
Hmm.. not sure about this.  I think using DO_SET_SPEED to actually change an acceleration is probably a step too far.  Better to create a new mavlink command called DO_SET_ACCELERATION (or maybe just DO_SET_ACCEL).

**Comment by OXINARF** [comment]
Hi @alexprasetia, thank you for your first contribution!

First of all, let me direct you to our contribution rules: http://ardupilot.org/dev/docs/submitting-patches-back-to-master.html Pay special attention to commit message rules.

Now, regarding the change itself: in #9535, Copter got new ways to change **speed** that we were already used in Plane - they weren't documented in MAVLink, but they were already in use for a long time. Now, this adds a new way to change **accelaration** (in a change speed message) that isn't documented (or in use as far as I know).

I'm not sure why you need to change the acceleration, but if that's really necessary (and @rmackay9 is OK with it), I'd suggest proposing a new MAVLink command for changing acceleration.

**Comment by rmackay9** [comment]
Yes, I think a new mavlink command is the way to go.  I've add the NeedsRework label to make it clear this PR needs a bit more love before it can go in.

**Comment by alexprasetia** [comment]
Thank you @OXINARF , I am sorry, its indeed still my first time of submitting a commit in here and i will look on the message rules now.

@rmackay9 thank you for your comment, I will see if I can try to build the new mavlink command for it

**Comment by khancyr** [comment]
This is quite old already and we didn't have progress on the mavlink side. I will close this. An issue for a new feature has been made to keep track of this. Thanks

**Pull request closed without merging**
