### PR TITLE
Tools: autotest: Allow EKF check to pass with rangefinder

### PR DESCRIPTION
**Pull request by khancyr**

### CODE REVIEW

**Comment by peterbarker** [comment]
Why?  These tests aren't supposed to be run with different vehicle configurations?!

**Comment by khancyr** [comment]
because I will add a precland test and a simpe land with rangefinder test (if rangefinder is enable, the final land sequence use only it instead of baro)

**Comment by OXINARF** [comment]
I think that we should instead change the check to be `(current & required_value) == required_value`; we should be checking the individual bits are set, not the actual number is the same.
Potentially we should also check that `(current & 3072) == 0` as we don't want those two bits set (in a single check that's `(current & 3903) == 831`).

**Comment by khancyr** [comment]
The idea from @OXINARF is better, I will redone it like that !

**Comment by khancyr** [comment]
@peterbarker @OXINARF changes done

**Comment by peterbarker** [comment]
What if some of the ekf status bits we're now ignoring are error bits?

**Comment by OXINARF** [comment]
@peterbarker I'll quote myself:

> Potentially we should also check that (current & 3072) == 0 as we don't want those two bits set (in a single check that's (current & 3903) == 831).

**Comment by OXINARF** [comment]
I clearly saw the wrong flags enum when I made my comment above - probably looked at the flags written to DF. The MAVLink message EKF_STATUS_MESSAGE has less flags and the bits I indicated will always be zero.

Correct code is:
- `if (current & 128) == 0 and (current & required_value) == required_value:`, OR
- `if (current & 959) == required_value:`

I'd prefer the second one together with:

```
required_bitmask = 831
check_bitmask = 959
```

But @peterbarker should say what he wants, he's the Tools maintainer.

**Comment by peterbarker** [comment]
Why don't we put together two lists, one with required bits and one with 
error bits, based on

<enum name="ESTIMATOR_STATUS_FLAGS">

required_bitmask = mav.ESTIMATOR_POS_HORIZ_REL |
 	            mav.ESTIMATOR_FULL_MOON | ...
error_bitmask = mav.ESIMATOR_GPS_GLITCH | ...

And make sure all of the bits in the first are set and none of the bits in 
the second are set.

I can never remember the correct namespace for those enums....

**Comment by OXINARF** [comment]
@peterbarker If we can access the enum, then we should use it, I wasn't sure we could do it here. Just a note: the enum you listed isn't the enum used by the EKF, it's the EKF_STATUS_FLAGS in ardupilotmega.xml; I guess that's the mistake I did previously too.

**Comment by peterbarker** [comment]
On Fri, 18 May 2018, Francisco Ferreira wrote:

> @peterbarker If we can access the enum, then we should use it, I wasn't
> sure we could do it here. Just a note: the enum you listed isn't the enum
> used by the EKF, it's the EKF_STATUS_FLAGS in ardupilotmega.xml; I guess
> that's the mistake I did previously too.

https://github.com/ardupilot/ardupilot/blob/master/Tools/autotest/common.py#L414

These are defined in /home/pbarker/rc/pymavlink/mavlink.py

So it should be mavutil.mavlink.EKF_ATTITUDE

... and now I've looked it up *again* :-)

**Comment by khancyr** [comment]
closed in favor of https://github.com/ArduPilot/ardupilot/pull/8932

**Pull request closed without merging**
