### PR TITLE
Correct DataFlash-over-mavlink log startup

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by OXINARF** [comment]
Merged, thanks!

**Comment by Pedals2Paddles** [comment]
Is this by chance what was causing the BAD LOGGING message and logging fail prearm messages when log backend was set for file & mavlink (3)?

**Comment by peterbarker** [comment]
@Pedals2Paddles There's a problem where you can't use both backends together and `log_disarmed`; did you have `log_disarmed` set?

**Comment by Pedals2Paddles** [comment]
@peterbarker Yes I do have `log_disarmed` enabled. But the strange thing is the logging seems to work fine even when it's claiming it isn't. I get DF logs to file and over mavlink while armed or disarmed. So I just have logging pre-arm check disabled for now.

**Pull request merged**
