### PR TITLE
.github: fix example error on CI

### PR DESCRIPTION
**Pull request by khancyr**
According to https://github.com/travis-ci/travis-ci/issues/4704#issuecomment-348435959
we should Turn off O_NONBLOCK to prevent the
BlockingIOError: [Errno 11] write could not complete without blocking

### CODE REVIEW

**Comment by peterbarker** [comment]
I'll be interested to see if this works; we set that flag within the Linux HAL (the cause of the problem here) so setting it here probably won't work.

**Comment by khancyr** [comment]
yep it doesn't work, I got a failure on 4th relaunch

**Comment by peterbarker** [comment]
@khancyr thanks for testing that.  Much appreciated.

Should we disable this while you get it sorted out?  People are getting these failures quite regularly.

**Comment by khancyr** [comment]
Yep, I got no idea why it fails on CI and not on local...

**Pull request closed without merging**
