### PR TITLE
ArduCoptor: added channels 9-16 to RC OVERRIDE in GCS_Mavlink.cpp

### PR DESCRIPTION
**Pull request by dposea**
Added channels 9 thru 16 to the rc override message for mavlink. 16 channels were already supported in other RC_Channels and Mavlink.

### CODE REVIEW

**Comment by careyer** [comment]
Awesome! Tested this change and it works perfectly. However in Mission Planner only 14ch show up. Is there a limitation to 14Ch in the firmware or does Mission Planner just not display channels 15+16?

**Comment by OXINARF** [comment]
@dposea Welcome to ArduPilot and thank you for your first contribution! Yes, it would be nice to add other vehicles in this PR - you can also add Sub, I'll check with @jaxxzer (Sub maintainer) that it is OK.

**Comment by jaxxzer** [comment]
> I'll check with @jaxxzer (Sub maintainer) that it is OK.

It is.

**Comment by jaxxzer** [comment]
> Can you add to a PR or should I create separate PRs for Plane and Rover?

@dposea You may add more commits to this PR (one for each vehicle), and push to your branch. The PR will automatically be updated.

**Comment by dposea** [comment]
Thanks, I'll do that this weekend. I wanted to do everything right even though it's a very minor change. Next I'm cleaning up autotune because the messages drove me nuts!!!  I also could not complete just one axis before running out of power. I live on a beach and it's never calm. Autotune needs to continue on the next flight if I can figure everything out. I'll discuss any changes on chat or forums before wasting time.

**Comment by OXINARF** [comment]
Superseded by #9988.

**Pull request closed without merging**
