### PR TITLE
HAL_ChibiOS: fixed build of VRUBrain-v51

### PR DESCRIPTION
**Pull request by tridge**
overflowing flash

### CODE REVIEW

**Review by bugobliterator — COMMENTED** [review]
Does this board support DFU flashing, just wondering if we can remove BL from ROMFS if not already done.

**Comment by bugobliterator** [comment]
Also do you think its time to add support for Conditionals in hwdef? We can probably enable some of these features for some builds.

**Comment by tridge** [comment]
> Does this board support DFU flashing, just wondering if we can remove BL from ROMFS if not already done.

I don't know if it supports DFU flashing

**Comment by tridge** [comment]
> Also do you think its time to add support for Conditionals in hwdef? We can probably enable some of these features for some builds.

out of scope for this. I just want to get it building for 4.1

**Pull request merged**
