### PR TITLE
Support for omni rover frames

### PR DESCRIPTION
**Pull request by Ammarf**
Adds support for omni-rover frames as part of the rover firmware.
- Added new functions in AP_MotorsUGV to handle throttle and steering inputs, omni rover output and an SRV_Channel_aux function that does the required math and sets the output pwm. 
- Added a new parameter called "omni_rover" that should be set to 1 in case of omni-rover frames.

### CODE REVIEW

**Comment by khancyr** [comment]
Very  nice ! Did you have a video of a omni rover working ? 
About the commit, I will made some comments later ! I don't think the change belong to SRVchannel, but should stay on motorugv .

**Comment by Ammarf** [comment]
[Here](https://drive.google.com/file/d/1O31S1WLM__NUQlfM_ILDJc3K7jFOuSA8/view?usp=sharing) is a short video of the omni rover running on manual mode. 
I also made a few quick changes, I removed the changes from SRV_Channel_aux and put everything in one function in AP_MotorsUGV to make it as concise as possible.

**Comment by rmackay9** [comment]
Some additional advice for submitting PRs most of it is [here on the wiki](http://ardupilot.org/dev/docs/submitting-patches-back-to-master.html).

- the commit subject line should start with the "subsystem" involved.  So for example, the commits should start with "Rover:" or "AP_MotorsUGV:".
- it is best to work on features in a new branch in your clone instead of your clone's master branch.  Using a new branch makes it much easier to [keep your clone up-to-date with ardupilot master](http://ardupilot.org/dev/docs/git-rebase.html).
- the commits should be "squashed" down into a small set of commits to make it easy to understand from the point of view of the code reviewer.  Have a peek at [this wiki page on using interactive rebase](http://ardupilot.org/dev/docs/git-interactive-rebase.html).
- commits should not include dead code or commented out code.

**Comment by rmackay9** [comment]
Some more specific changes I think we should make:

- let's remove the OMNI_ROVER parameter and is_omni_rover() function in the main vehicle code and instead create a "is_omni_rover" (or perhaps "has_omni_steering"?) method in AP_motorsUGV.h just below the "have_skid_steering" method.  This new function should return true if SRV_Channels::function_assigned() returns true for k_motors1, k_motor2 and k_motor3 and false in all other situations.  In this way we will automatically detect that it's an omni rover if the user has setup the three SERVOx_FUNCTION parameters.
- use atan2f/cosf/sinf instead of atan2/cos/sin
- in output_omni, "scaled_throttle" and "scaled_steering" aren't used it seems
- in mode.cpp, it looks like the call to g2.motors.set_steering(..) has been changed to pass in the steering as a number from -1 to +1.  I know the current method of passing in -4500 ~ +4500 seems crazy and we certainly should change it to a more reasonable range but as-is this change breaks all the other vehicles so for now it's best if update_omni internally changes the range to -1 ~ +1.  this is what the skid-steering output does as well.
- one small thing is our [style guide is here](http://ardupilot.org/dev/docs/style-guide.html) and in particular we normally put the curly brackets on the same line as the if-condition (i.e. "if (armed) {").

All this is par for the course and overally this is a great feature!

**Pull request closed without merging**
