### PR TITLE
AP_Notify: Eliminated need for Solo specific tones, added power off tone to px4 tones

### PR DESCRIPTION
**Pull request by Pedals2Paddles**
Evaluated solo specific tones file vs standard px4 tones files.  The only thing the Solo had that standard ArduPilot does not have is the GPS unplugged tone and the power off tone. This PR is needed to get Solo onto Master. Please backport into 3.5 if approved.
* GPS unplugged tone abandoned. Determined to be unnecessary.
* Power off tone merged into standard px4 tones file. Smart battery signalling a power off will make use of this tone. Has application for any smart battery equipped vehicle, not just Solo.
* Removed all references and dependencies to `ToneAlarm_PX4_Solo.cpp` and `ToneAlarm_PX4_Solo.h`
* Deleted `ToneAlarm_PX4_Solo.cpp` and `ToneAlarm_PX4_Solo.h` since they're no longer needed.

### CODE REVIEW

**Comment by khancyr** [comment]
@Pedals2Paddles Hello, you need to rebase you PR on master branch ! 
If you are on linux, git rebase master

**Comment by Pedals2Paddles** [comment]
Wow this PR took in a ton other commits in master, I'll try this again.  Closing.

**Comment by Pedals2Paddles** [comment]
@khancyr I thought I did but holy cow apparently that didn't work!  Fixing it now. Thx.

**Comment by khancyr** [comment]
you don't need to close the pr, just rebase and force push on the same branch will be good !

**Comment by Pedals2Paddles** [comment]
Oh. Too late. Good to know though since I'm sure I'll screw something up again in the future.

**Pull request closed without merging**
