### PR TITLE
Tools: move formating scripts to Tools/CodeStyle, add warning file

### PR DESCRIPTION
**Pull request by khancyr**
I don't think they are used, but shouldn't be...

### CODE REVIEW

**Comment by tridge** [comment]
I use ardupilot-astyle.sh, any reason I shouldn't?

**Comment by khancyr** [comment]
My bad the astyle seems good...that my local fork that got plenty old file...
I will double check the astyle formater when I got a computer

**Comment by khancyr** [comment]
remove uncrustify that isn't maintained.
remove xmlpretty, as xmllint already do a better job !
update astyle to be closer than our current style, mainly : 
change bracket style to 1tbs to prevent adding a break before else {}
add bracket on oneline statement
add padding on operator, comma
convert tabs to space

**Comment by peterbarker** [comment]
@khancyr this is now conflicting; is it worth pursuing?

**Comment by khancyr** [comment]
yep, I can do this one fast !

**Comment by khancyr** [comment]
rework on #14630

**Pull request closed without merging**
