### PR TITLE
AC_PID: zero pid_info.I when integrator zeroed

### PR DESCRIPTION
**Pull request by peterbarker**
Otherwise the reporting is wonky

### CODE REVIEW

**Comment by peterbarker** [comment]
I'm really thinking we should be taking an `AP_Logger::PID_Info` into `get_pid_info`.  ATM we're doing a *lot* of assignments into the PID's `_pid_info` object for no particularly good reason.  `_pid_info` AFAIK should only be used for reporting purposes, and we do that at a very small fraction of the rate we update the PID object.

**Comment by rmackay9** [comment]
Discussed at the dev call and we think this is probably correct but wanted @lthall to confirm he's ok

**Review by khancyr — APPROVED** [review]
Each time we update the _integrator, we update _pid_info.I , so we should be doing it here too.

Unfortunately, this isn't just used on reporting. Numerous place in the code use _pid_info.I , so it will need some testing.
So if we look at reset_I() usage, we want to reset the integrator a some place so the _pid_info.I report should be reseted too. 
The impact is small as it will be only between the reset() call and the next pid update.

Thus this lead to some difference between the pid class we got.
I think that this should be the default behavior on all pid class (pid_basic).

**Review by tridge — APPROVED** [review]

**Comment by tridge** [comment]
need to do the other PIDs too, eg. the AC_PID_XY

**Review by tridge — CHANGES_REQUESTED** [review]
need to do the other PID classes too, where needed

**Comment by rmackay9** [comment]
AC_PID_Basic needs it too I think.

**Comment by peterbarker** [comment]
This was done as a different PR 6 months ago: https://github.com/ArduPilot/ardupilot/pull/21214

And apparently it was the wrong thing to do according to https://github.com/ArduPilot/ardupilot/pull/22644

**Pull request closed without merging**
