### PR TITLE
Copter-3.6: Backport of loop time stretching

### PR DESCRIPTION
**Pull request by tridge**
backport of #12324

### CODE REVIEW

**Comment by rmackay9** [comment]
It's a cool change.  It'll likely come as no surprise that I'd like this one to "bake" in master for a while before we backport it to 3.6.  We're also so close to starting 4.0.0 testing that I'm unsure how many more 3.6.x point releases we will have.

**Comment by lthall** [comment]
Tested and worked well.

**Comment by rmackay9** [comment]
I think we can close this now because we're unlikely to do another Copter-3.6 release.

**Comment by tridge** [comment]
agreed

**Pull request closed without merging**
