### PR TITLE
Move RC_Channel enabling of AP_Avoidance into RC_Channel library

### PR DESCRIPTION
**Pull request by peterbarker**
Alternative to https://github.com/ArduPilot/ardupilot/pull/12754

@Hwurzburg

### CODE REVIEW

**Comment by peterbarker** [comment]
@Hwurzburg So this is passing tests now.

You mentioned you'd test it in SITL to make sure it was working appropriately.

**Comment by peterbarker** [comment]
@Hwurzburg If you could test this again it would be appreciated.

I had to do a small correction in `AP_Avoidance` to get the initial avoidance action correct.

**Comment by Hwurzburg** [comment]
tested on plane in sITL....set rc5 to enable, with ADSB disabled, and toggling RC5, proper messages...same with ADSB_ENABLE=1....proper messages with RC5 toggle...so at least its xercising the code that sets the enable/disable calls...

**Comment by peterbarker** [comment]
Thanks @Hwurzburg

**Pull request merged**
