### PR TITLE
AP_ServoRelayEvents: allow do-set-servo commands to affect sprayer, gripper

### PR DESCRIPTION
**Pull request by rmackay9**
This PR resolves this issue: https://github.com/ArduPilot/ardupilot/issues/13478 raised as part of Copter-4.0.1 testing ([discussion](https://discuss.ardupilot.org/t/do-set-servo-in-spray-function-does-not-work-in-4-0-0/51950)).

The PR allows DO_SET_SERVO and DO_REPEAT_SERVO commands (as part of a mission or sent in real-time from the GCS) to affect these SERVOx_FUNCTION outputs:

- k_sprayer_pump
- k_sprayer_spinner
- k_gripper

I have inspected the code and the sprayer, gripper, landing gear and camera control features seem compatible with do-set-servo in that the feature doesn't constantly update the servo outputs.  Also these outputs are not for control surfaces so are unlikely to cause crashes.

The landing gear one is probably the most dangerous because a user could accidentally retract the landing, lose GCS communications and then the vehicle could land without re-extending the gear because it's internal state thinks that the gear is already extended.

The alternative to this change is to ask the ground station developers to provide custom control pages to send mavlink messages to the feature.  This is actually a cleaner approach but this simple change is more likely to help users I think.

P.S. I've removed the affect on these other outputs

- k_landing_gear_control
- k_cam_iso
- k_cam_aperture
- k_cam_focus
- k_cam_shutter_speed

### CODE REVIEW

**Comment by WickedShell** [comment]
I review this as a regression, and really don't like it. As stated on the linked issue it messes with the libraries ability to do what it's supposed to be doing.

**Comment by rmackay9** [comment]
@WickedShell, I've reduced the scope to just affect sprayer and gripper which should make it less of an issue for Plane devs and users.

I've completed testing of the sprayer and gripper functions so this is ready to go from my point of view.

**Comment by rmackay9** [comment]
resolved merged conflicts and rebased on master

**Comment by rmackay9** [comment]
The first commit from this PR, "SRV_Channel: remove release and choke from FUNCTION param description" is included in Copter-4.0.3-rc1

**Comment by framosnt** [comment]
> This PR resolves this issue: #13478 raised as part of Copter-4.0.1 testing ([discussion](https://discuss.ardupilot.org/t/do-set-servo-in-spray-function-does-not-work-in-4-0-0/51950)).
> 
> The PR allows DO_SET_SERVO and DO_REPEAT_SERVO commands (as part of a mission or sent in real-time from the GCS) to affect these SERVOx_FUNCTION outputs:
> 
> * k_sprayer_pump
> * k_sprayer_spinner
> * k_gripper
> 
> I have inspected the code and the sprayer, gripper, landing gear and camera control features seem compatible with do-set-servo in that the feature doesn't constantly update the servo outputs. Also these outputs are not for control surfaces so are unlikely to cause crashes.
> 
> The landing gear one is probably the most dangerous because a user could accidentally retract the landing, lose GCS communications and then the vehicle could land without re-extending the gear because it's internal state thinks that the gear is already extended.
> 
> The alternative to this change is to ask the ground station developers to provide custom control pages to send mavlink messages to the feature. This is actually a cleaner approach but this simple change is more likely to help users I think.
> 
> P.S. I've removed the affect on these other outputs
> 
> * k_landing_gear_control
> * k_cam_iso
> * k_cam_aperture
> * k_cam_focus
> * k_cam_shutter_speed

Hi RMackey9, 

I am user spray function in quadcopters, I think this very import control of spray by control and GCS, but not by DO_SET_SERVO, but New GCS (Mission Planner) DO_SPRAY = Enable and Desable SPRAY_ENABLE parameter, SPRAY_Parameter is very important functions to control turn on or off but can control spray flush by drone speed, if user can use 100% or variable rate, is optional.

**Comment by rmackay9** [comment]
@framosnt, do, it's a good enhancement request.  Feel free to add it to [the issues list](https://github.com/ArduPilot/ardupilot/issues).

**Pull request merged**
