### PR TITLE
New Board: Dark. Connects to RPi

### PR DESCRIPTION
**Pull request by lostcaggy**
I started from scratch. Have done a rebase etc. and sorted whitespace issues. I did a successful test build on ubuntu linux

### CODE REVIEW

**Comment by magicrub** [comment]
much better, thank you! A couple of comments:

- For everyone else reviewing this, I recommend adding ?w=1 to the URL. Half of the PR is still whitespace changes. It's mostly this comment which just needs to get squashed: https://github.com/ArduPilot/ardupilot/pull/5008/commits/3aa9ec47d80d4c766b3d345821fb46303134a6eb
- Have you read the wiki about how to commit patches? Specifically [Log messages](http://ardupilot.org/dev/docs/submitting-patches-back-to-master.html#log-messages), everyone single one is the same (except for the whitespace one)

**Comment by tridge** [comment]
this looks good to me. Better without the white space changes, but I don't think we should hold it up for that

**Comment by tridge** [comment]
as Tom notes, we like having the subsystem (directory name) at the front of the patch, for example:
 HAL_Linux: changed some things
that makes it easier when preparing a release to categorise changes.
It's very easy to fix with an interactive rebase. I'd be happy to do that for you

**Comment by lostcaggy** [comment]
Hi tridge if you could do the interactive rebase that would be great. Perhaps you could point me to some tutorials so I could learn for the future. Thanks

**Comment by magicrub** [comment]
I agree @tridge , other than the whitespace and commit msg the PR is very clean. Good work @lostcaggy! 


>Perhaps you could point me to some tutorials

@lostcaggy  if you're on Windows or MacOS I'd suggest using [SourceTree](https://www.sourcetreeapp.com/) to manage github. There are lots of videos on using it and it is very powerful and with a great UI.

**Comment by lostcaggy** [comment]
@magicrub I've been using GitHub on MacOS. I'll have a look at SourceTree though. Thanks.

**Comment by tridge** [comment]
here is the PR with the prefixes fixed: https://github.com/tridge/ardupilot/commits/lostcaggy-darkwater

**Comment by lucasdemarchi** [comment]
I fixed some typos, added prefixes, squashed some commits that were doing the same thing and made the last commit fix things in place rather with a new commit on top.

Also, Makefile is deprecated for all boards, and for Linux boards they are half-broken so we are not adding more.  Please use waf for building it.

@lostcaggy please check everything is still working for you. Some tips:
- you don't need to repeat the same phrase in the git commit message... if there's any other information, a single line is sufficient
- `git commit --fixup=<commit-hash>` can be used to quicly fixup a past commit, then you can use `git rebase -i` to apply them to the proper commit. This is what I did with your last "fix whitespaces" commit.

Thanks. Applied, though I only verified it compiles fine.

**Comment by magicrub** [comment]
@lucasdemarchi Thanks for working on this Lucas!

**Comment by lostcaggy** [comment]
Thanks for all your help.

**Pull request closed without merging**
