### PR TITLE
waf: support python 3.12

### PR DESCRIPTION
**Pull request by tridge**
depends on:
 - https://github.com/ArduPilot/mavlink/pull/359
 - https://github.com/ArduPilot/waf/pull/17

note the waf PR will require a force push as it rebases on upstream 2.0.27

tested on ubuntu 24.04

### CODE REVIEW

**Review by peterbarker — APPROVED** [review]

**Comment by jonhoo** [comment]
Was it intentional that this wasn't included in [the recently-released Plane-4.5.5](https://github.com/ArduPilot/ardupilot/releases/tag/Plane-4.5.5)?

**Comment by rmackay9** [comment]
Hi @jonhoo,

We get this question a lot so perhaps we should extend our [Copter Release Procedures wiki page](https://ardupilot.org/dev/docs/release-procedures.html) so we can just point users at the answer each time.

In any case, every PR that is merge to master is not automatically backported to the stable releases.  Only those that have their "Project" set to something like "4.5 Backports" are considered for back porting.

Every PR merged to master will be part of the next major release though.  E.g. 4.6.0

In any case, I've just marked this one for Backporting so it will at least be considered.

Thanks for using AP!

**Comment by jonhoo** [comment]
Thanks for the quick reply! I actually did find that page and looked through it for a clue as to why this happened. I failed to find a Project for Plane-4.5 (I did find the [4.5 backports](https://github.com/orgs/ArduPilot/projects/8) list though), which threw me off. I also didn't find a reason for why the MR which landed in May wouldn't be included in the very recent 4.5.5 release which I (perhaps incorrectly) assumed would be forked after `master` and thus shouldn't need to be backported (I now suspect the answer is that I should have looked at when 4.5 was forked from `master`). And then I also didn't find a way to suggest that something be backported given the 4.5 backport list had already been created. So I figured it'd at that point probably be best to just ask 😅

**Comment by jonhoo** [comment]
Oh, and thank you for adding it! Without it, Ardupilot doesn't build for Python 3.12, so would be a welcome addition :)

**Comment by jonhoo** [comment]
Would it be useful for me to open a PR with the backport to the Plane-4.5 branch, or not so much?

**Comment by rmackay9** [comment]
Hi @jonhoo,

Thanks for that and yes, your understanding is totally correct above.  A backport PR always helps especially when the PR can't be cherry-picked into the branch without merge conflicts

**Comment by rmackay9** [comment]
this has been included in Copter-4.5.7-beta1

**Pull request merged**
