### PR TITLE
Tools: don't use strict comparison for param fetch all to cope with T…

### PR DESCRIPTION
**Pull request by khancyr**
…YPE one's

### CODE REVIEW

**Comment by peterbarker** [comment]
Is this what ArduPilot does, or does it compare it against epsilon?

**Comment by khancyr** [comment]
@peterbarker that because of _TYPE parameter : https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Airspeed/AP_Airspeed.cpp#L60 or https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_RSSI/AP_RSSI.cpp#L53 for example. TYPE = 2 also need param fetch as it enable new parameter. 
This was catch by @amilcarlucas

**Comment by OXINARF** [comment]
@khancyr Unless there is a bug somewhere, -1 is not like 0, it does not hide the parameters, that was my entire point.

**Comment by khancyr** [comment]
update with !=0

**Comment by OXINARF** [comment]
@peterbarker ?

**Pull request merged**
