### PR TITLE
Libraries: Clarify processing priorities

### PR DESCRIPTION
**Pull request by muramura**
I think it is better to clarify the scope of influence with ().
I agreed to point out the cppcheck command.

### CODE REVIEW

**Comment by peterbarker** [comment]
.... further, one-commit-per-directory, please.

**Comment by khancyr** [comment]
@muramura hello, could you correct the commit messages and split it by directory ?

**Comment by peterbarker** [comment]
OK, so by inspection these look good.

What testing have these changes had?  How did you ensure these were non-functional changes?  Did you run across these codepaths in any way?

Most of these lines are only crossed when seriously bad stuff has happened, and they're *only* of use to developers single-stepping the code.  This is essentially dead weight for 99.999999 of the time.  But we do need it to work as modifying the code can change (or eliminate) the hardfault happening at all.

That means it should be stepped across in a debugger.

If we're doing that, we may as well make it easier on the person doing the debugging by changing the three blocks to look like this:

```
    union {
        struct {
            uint8_t b0 : 1;
            uint8_t isFaultPrecise :1;
            uint8_t isFaultImprecise : 1;
            uint8_t isFaultOnUnstacking : 1;
            uint8_t isFaultOnStacking : 1;
            uint8_t b5 : 1;
            uint8_t b6 : 1;
            uint8_t isFaultAddressValid : 1;
        };
        uint8_t bits;
    } fault_bits;
    fault_bits.bits = uint8_t(SCB->CFSR >> SCB_CFSR_BUSFAULTSR_Pos);
    void(fault_bits.bits);
```

You can "p fault_bits" rather than having to look at each of the variables individually now.

that also saves us a few bytes, which is nice.

Again, 'though.  This sort of thing has to be stepped across as when hardfaults happen we want things to work when we're debugging them!

@muramura are you good with stepping across code with the debugger?

**Comment by khancyr** [comment]
@peterbarker those are cosmetics changes as they don't change the behavior if the compiler respect the C++ standard that specify that binary operation are done before ternary operator. ...

**Comment by peterbarker** [comment]
On Sat, 20 Jun 2020, Pierre Kancir wrote:

> @peterbarker those are cosmetics changes as they don't change the behavior if the compiler respect the C++ standard that specify that binary operation are
> done before ternary operator. ...

Yes, I'm quite aware of that.

As I said, by inspection they're fine.

**Comment by khancyr** [comment]
closing as it isn't worth to invest much time to prove that only parentheses changes are fine. @muramura If you want to do it, please reopen the PR with testing proof. Thanks

**Pull request closed without merging**
