### PR TITLE
AP_Camera: add support for Runcam 2 4k

### PR DESCRIPTION
**Pull request by Cam84Fr**
Adaptation of AP_Runcam for the Runcam 2 4k version : 
- new camera type (Run24k = 5),
- OSD menu modification for use with no "Save and Exit" option,
- Use same command than Split 2 4k and Hybrid for remote recording.

AP_Runcam.h and AP_Runcam.cpp modified.

### CODE REVIEW

**Review by andyp1per — CHANGES_REQUESTED** [review]
Very nice! Good work.

The changes look great - you just need to rebase, squash and rename the commits to match AP conventions - https://ardupilot.org/dev/docs/submitting-patches-back-to-master.html#preparing-commits

**Comment by Cam84Fr** [comment]
> Very nice! Good work.
> 
> The changes look great - you just need to rebase, squash and rename the commits to match AP conventions - https://ardupilot.org/dev/docs/submitting-patches-back-to-master.html#preparing-commits

Thank Andy,
I changed the title, I'm not totally sure but Rebase and Squash seems ok.

**Comment by andyp1per** [comment]
I tried to fix it for you but don't have permission. Do this:
```
git pull --rebase upstream master
git rebase -i HEAD~
```
change "pick" to "reword" and edit to have a single commit message that starts:
AP_Camera: add support for Runcam 2 4k

Then quit and
```
git push -f
```
and you should be done

**Comment by Cam84Fr** [comment]
Hi, done with difficulty but now I think it's good

**Comment by andyp1per** [comment]
Squash looks good but commit message is wrong. Do this:
```
git commit --amend -m "AP_Camera: add support for Runcam 2 4k"
git push -f
```
and you should be good

**Comment by Cam84Fr** [comment]
> Squash looks good but commit message is wrong. Do this:
> 
> ```
> git commit --amend -m "AP_Camera: add support for Runcam 2 4k"
> git push -f
> ```
> 
> and you should be good

Done and thank for your help, I learn in same time.

**Comment by andyp1per** [comment]
Yes but now you have two commits again, one of which is a merge commit which is a no-no - please run
```
git pull --rebase upstream master
git push -f
```
and I think that will clear it up

**Comment by Cam84Fr** [comment]
> Yes but now you have two commits again, one of which is a merge commit which is a no-no - please run

Hi,
It is done yesterday but now there is the message "out-of-date", I do something or not ?

**Comment by andyp1per** [comment]
Looks good!

**Review by andyp1per — APPROVED** [review]
Great work!

**Comment by peterbarker** [comment]
Merged, thanks!

**Comment by rmackay9** [comment]
By the way, as discussed on the dev call, I think we should consider trying to merge the RunCam library in AP_Camera.. but of course before that we will need to do a frontend-backend split on AP_Camera.. which I hope to do within about a month.

**Comment by Cam84Fr** [comment]
Thank you all,

Next step, testing the next Beta I guess.
For the wiki I can suggest the update.

Tell me.

**Pull request merged**
