### PR TITLE
Fix startup scream from Kakute F7 and OmnibusF4Pro buzzer

### PR DESCRIPTION
**Pull request by andyp1per**
This fixes the startup scream on both the F7 and F7 Mini by pulling the buzzer pin low in  the bootloader

### CODE REVIEW

**Comment by peterbarker** [comment]
Would be good to get someone else say this fixes the problem for them.  I don't have one here to test on.

**Comment by andyp1per** [comment]
Ok, I will find someone.

**Comment by tridge** [comment]
I've got a KakuteF7 AIO but it never screamed at me.
btw, we'd need a 2nd commit for the bootloader binary after running Tools/scripts/build_bootloader.py KakuteF7*

**Comment by andyp1per** [comment]
Ok, wasn't sure whether you had a special machine for building the bootloaders. Happy to do it myself.

Apparently the omnibusf4pro has this issue as well.

@tridge is your AIO powered by battery? I never get the scream on USB only.

**Comment by tridge** [comment]
> @tridge is your AIO powered by battery? I never get the scream on USB only.

ahh, no, it's USB. I'll try with a battery
...... tried battery, no scream, but rather worryingly there was a small bit of smoke. Still seems to work on USB, but not really a valid test

**Comment by peterbarker** [comment]
On Fri, 19 Jun 2020, Andrew Tridgell wrote:

>       @tridge is your AIO powered by battery? I never get the scream on USB only.
> 
> ahh, no, it's USB. I'll try with a battery
> ...... tried battery, no scream, but rather worryingly there was a small bit of smoke. Still seems to work on USB, but not really a valid test

You didn't set NTF_SMOKESIGNAL did you?

**Comment by andyp1per** [comment]
@tridge what kind of buzzer do you have connected? I think you will only get the scream with an active buzzer

**Comment by andyp1per** [comment]
I added the omnibus change. Hoping someone in the forums will confirm to save me some soldering.

**Comment by andyp1per** [comment]
This definitely works on the KakuteF7Mini - I upgraded the bootloader on another one I had and the scream is 100% gone.

**Comment by AndWik** [comment]
I have tried the 2020-06-20 version on a Kakute F7 AIO. The problem persist! When applying power the buzzer screams. On USB power the buzzer is quiet.
Do I have to download an updated bootloader or is it a change in the code. Flashed "new" bootloader yesterday.

Thanks
Anders

**Comment by andyp1per** [comment]
This PR includes a new bootloader which should be included if you build the firmware. You then use the bootloader update function in MP or mavproxy to update.

**Comment by andyp1per** [comment]
Looking at BF there are a bunch we could do. I think it's based off the "BEEPER_INVERTED" flag

OmnibusF7Nano - PB0
OmnibusF4Nano - PC5
KakuteF4 - PC9
OmnibusF7 - PD15

**Comment by andyp1per** [comment]
@AndWik how did you flash the bootloader?

**Comment by AndWik** [comment]
I tried the latest version today and updated the bootloader via MP when I was connected.
Then I removed the USB cable and connected the battery.
The buzzer has another, lower, frequency now* but starts beeping as soon as the power is connected.

*) When this thread was started

**Comment by andyp1per** [comment]
@AndWik I have a KakuteF7 AIO - I will solder on a buzzer and power and try it out.

**Comment by andyp1per** [comment]
Ok, this definitely works for the KakuteF7 AIO that I have - scream before, no scream after. I tried two different buzzers and battery power. Same result.

The omnibus F4Pro I have does not exhibit this problem, but also the fix here does not affect the outcome - new bootloader, buzzer still behaves sanely. So I suggest we put this in in case it solves the problem that someone else was seeing.

**Comment by andyp1per** [comment]
@AndWik what kind of buzzer are you using? I tested with magnetic active buzzers.

**Comment by AndWik** [comment]
I have three drones. Two with Kakute F7 AIO and one Kobus 2 drone with Kakute F7 Std. They all have a passive piezo buzzer attached between -Bz and the +5V next to it, as decribed in the Holybro doc.

As I could not attach a film I put it on my WEB-Server: http://fuzzyfool.no-ip.com/ArduPilot/

Best regards
Anders

**Comment by andyp1per** [comment]
That's exactly the tone I had yesterday that my fix cured on my AIO. I'm not sure what difference the passive piezo makes - I thought these wouldn't emit a tone unless there is an active alternating signal.

**Comment by AndWik** [comment]
I will update all of them later and test them tomorrow.

Thanks
Anders

**Comment by AndWik** [comment]
When I update the bootloader using MP it takes no time at all. Is this normal?

I get the buzzer tone with the friday copter version (for Kakute F7) and after upgraded bootloader using MP.

Tested on one of my drones.

Anders

**Comment by AndWik** [comment]
WOW! You have fixed it!

I have updated all my drones and the buzzer performs as it should

Thanks a lot
Anders

**Comment by Magnorio** [comment]
I am facing this issue now! It was not there before but recently when I connect the battery the buzzer is playing thia anoying sound until it initiates the ardulpilot tune. I updated the booloader but the issue persists. I am runing the latest version 4.0.9, are you also experiencing this issue? Thank You!

**Comment by andyp1per** [comment]
I'm not sure it was backported to 4.0 - did you try 4.1?

**Comment by brocciu** [comment]
Custom build on 4.5 with kakute F7, I can't get rid of the scream. What can I do ?

**Pull request merged**
