### PR TITLE
Copter:  Add precision landing status to telemetry

### PR DESCRIPTION
**Pull request by derekxm**
Issue #3348. If precision landing is enabled, arducopter publishes LANDING_TARGET MAVLINK message to ground stations.This should help debug precision landing sensors.

### CODE REVIEW

**Comment by magicrub** [comment]
Id like something like this for plane too. There was talk of making a new
MAVLink packet for AGL specific data, maybe that can still happen.

**Comment by derekxm** [comment]
@rmackay9 you think we can merge this?

**Comment by squilter** [comment]
I'd be interested in this feature.

**Comment by ClementChristomanos** [comment]
@rmackay9 @fnoop Since you guys began working on precland and vision projects again I think this feature would be very useful for real-time debugging, would you think this can be rebased & merged ?

**Comment by amilcarlucas** [comment]
@derekxm How about a rebase of this ?

**Comment by khancyr** [comment]
Closed as the standard mavlink message http://mavlink.org/messages/common#LANDING_TARGET do a better job

**Comment by khancyr** [comment]
@fnoop I know ! but this message isn't existant and not very complet. As I said, just fill and send back to GCS the LANDING_TARGET message. Do you want to try to do this ? I can help you !

**Pull request closed without merging**
