### PR TITLE
TOOLS: add support for GCOV code coverage tool 

### PR DESCRIPTION
**Pull request by davidbuzz**
... and HTML coverage reporting with LCOV.

first, "apt install gcovr lcov" as new prerequisites 
then run:
./waf configure --enable-gcov
./waf build --lcov-report 
and after much waiting review the report in HTML format with your preferred browser eg:
firefox reports/lcov-report/index.html

### CODE REVIEW

**Comment by peterbarker** [comment]
Red for the waf output seems a bit extreme.

This looks awesome.

**Comment by peterbarker** [comment]
... commit mesage should have `Tools` rather than `TOOLS`

**Comment by peterbarker** [comment]
I didn't get any REPORTS directory at the end of it.

```
LCOV/GCOV -> fly.ArduCopter started.... this will take quite some time...
Coverage Tests Executing:( ./Tools/autotest/autotest.py --debug --no-configure fly.ArduCopter )  > ./GCOV_fly.ArduCopter.log
LCOV/GCOV -> fly.ArduCopter see ./GCOV_fly.ArduCopter.log for log of activity)

real	15m39.686s
user	15m17.225s
sys	3m51.912s
pbarker@recursion:~/rc/ardupilot(coverage)$ echo $DISPLAY
```

Some of the tests failed - do they have to succeed to run the report generation?

**Comment by khancyr** [comment]
I really enjoy this, but should we put those function into a new file into ardupilowaf directory to keep the root wscript simple ?

**Comment by davidbuzz** [comment]
Peter, yes, all tests have to pass to get a report, why is your fly.Arducopter failing, mine doesn't. Check the output in ./GCOV*.log to see why.

**Comment by davidbuzz** [comment]
Khancyr, I'm not really a waf person, but putting the functions into subdir sounds reasonable, if possible, so I'll see what I can do .

**Comment by peterbarker** [comment]
@davidbuzz My guess is that it comes back to the compiler options required to do the coverage analysis.  They stuff the timing around sufficiently that the machine I'm trying to run it on can't cope.  We're doing better over time on this front, but not there yet.

I'll try running this on my primary machine and see what happens.

**Comment by peterbarker** [comment]
Merged via #10696 - awesome!

**Comment by khancyr** [comment]
very nice !

**Pull request closed without merging**
