### PR TITLE
Fix Broken SIM on Hardware build

### PR DESCRIPTION
**Pull request by joshanne**
Appears as though the read gyro functionality added in #21780 broke the SIM on Hardware functionality provided by `libraries/SITL/examples/on-hardware/sitl-on-hw.py`.

This disables the INS File support when building SITL for hardware.

### CODE REVIEW

**Comment by joshanne** [comment]
@peterbarker is it worth adding a build for the board `CubeOrange-SimOnHardware`?

**Review by peterbarker — APPROVED** [review]

**Comment by peterbarker** [comment]
> @peterbarker is it worth adding a build for the board `CubeOrange-SimOnHardware`?

In CI?  I think so, yes.

**Comment by joshanne** [comment]
> > @peterbarker is it worth adding a build for the board `CubeOrange-SimOnHardware`?
> 
> In CI? I think so, yes.

I would propose merge this, and the CI be a follow up PR - I see lots of discussion about github actions and CI in general, so I might create the issue and ask it be added during that rework.

**Comment by peterbarker** [comment]
> > > @peterbarker is it worth adding a build for the board `CubeOrange-SimOnHardware`?
> > 
> > 
> > In CI? I think so, yes.
> 
> I would propose merge this, and the CI be a follow up PR - I see lots of discussion about github actions and CI in general, so I might create the issue and ask it be added during that rework.

It'd already been marked as `MergeOnCIPass` :-)

Merged now - thanks!

**Pull request merged**
