### PR TITLE
AP_Periph: MSP fix last baro ms

### PR DESCRIPTION
**Pull request by giacomo892**
@tridge please merge before the next stable release

### CODE REVIEW

**Review by khancyr — APPROVED** [review]
That would be consistant with other sensor.
I wonder if it won't be better to store the first call into a const variable too.

**Review by magicrub — APPROVED** [review]
This looks good to me. I don't think we need to discuss at the dev call, seems pretty straightforward.

**Comment by magicrub** [comment]
@giacomo892 this change seems like an improvement... I think. But really doesn't have much impact. Is there a reason it's important to you?

**Comment by giacomo892** [comment]
> @giacomo892 this change seems like an improvement... I think. But really doesn't have much impact. Is there a reason it's important to you?

It's just nice to have as you said :) So worth to be in stable release asap :)

**Comment by giacomo892** [comment]
> That would be consistant with other sensor.
> I wonder if it won't be better to store the first call into a const variable too.

That's up to you 💯

**Comment by tridge** [comment]
i don't think this actually changes anything. I don't mind the change, but I don't see why this is release critical

**Pull request merged**
