### PR TITLE
Copter: Make mode flowhold a build option

### PR DESCRIPTION
**Pull request by stephendade**
As reported in https://discuss.ardupilot.org/t/cheerson-cx-of-and-kakute-f7-aio/89679, the flowhold mode isn't available for custom builds.

This PR adds the build option ``MODE_FLOWHOLD_ENABLED`` so users can include it in their custom builds.

Tested on a KakuteF4

### CODE REVIEW

**Comment by rmackay9** [comment]
Thanks for this.  I think this will lead to FlowHold being disabled by default though. I think we need something to initialise the MODE_FLOWHOLD_ENABLED definition in Copter's config.

**Comment by stephendade** [comment]
> I think we need something to initialise the MODE_FLOWHOLD_ENABLED definition in Copter's config.

Ahh yes ... I've added that in now.

**Review by rmackay9 — APPROVED** [review]

**Review by amilcarlucas — COMMENTED** [review]
This removes a lot of options in the build_options.py file. I guess that is a rebase error?

**Comment by rmackay9** [comment]
@amilcarlucas, I don't think this PR directly modifies the build_options.py file..

**Review by amilcarlucas — APPROVED** [review]
Sorry I read this in my cellphone and the colour coding confused me. 

Carry on. My mistake.

**Comment by rmackay9** [comment]
Alrighty then, merged!

**Pull request merged**
