### PR TITLE
Ardupilot add topotek gimbal

### PR DESCRIPTION
**Pull request by laozhou-fujian**
Hello, the changes have been made as per your request, and I have modified some of the code from the previous version.

### CODE REVIEW

**Comment by laozhou-fujian** [comment]
If you need the topotek gimbal for testing, please provide me with your address, and I will send you a gimbal free of charge.

**Comment by laozhou-fujian** [comment]
My email address is 3177821352@qq.com

**Comment by amilcarlucas** [comment]
Can you please rebase instead of merge? and squash all commits into a single one?

**Comment by rmackay9** [comment]
@laozhou-fujian,

Good to see that you've created a new branch.  Next try this to rebase on master:

- git remote add trunk https://github.com/ArduPilot/ardupilot.git
- git fetch trunk
- git rebase trunk/master

You can also "reset" your master branch to look like ardupilot's master branch by doing this

- git checkout master
- git fetch trunk
- git reset --hard trunk/master
- git push -f

**Pull request closed without merging**
