### PR TITLE
AP_Motors: added new MOT_PWM_TYPE=8 for PWM range

### PR DESCRIPTION
**Pull request by tridge**
this allows multirotors to set individual PWM ranges per motor. This
is needed for heliquads flying as multirotors

### CODE REVIEW

**Comment by davidbuzz** [comment]
hey @tridge  - is this a pr you are still interested in..?

**Comment by tridge** [comment]
> hey @tridge - is this a pr you are still interested in..?

yes. We've had another partner using multicopter for heliquads with servos recently. This PR still makes sense.

**Comment by peterbarker** [comment]
This looks right to me - but there's no testing evidence in here.

I believe this one has been tested on hardware, 'though?  As-is or near enough?

**Comment by tridge** [comment]
redo as an option bit in MOT_OPTIONS

**Comment by tridge** [comment]
merged after discussion on EU dev call

**Pull request merged**
