### PR TITLE
Copter: Specify the immediate value in a bit definition

### PR DESCRIPTION
**Pull request by muramura**
I describe the association between a bit mask and a parameter with a bit definition name.
It's hard to know which parameter I've made Ignore in the direct value.
Also, the ignore setting of bits 15-12 is meaningless.

### CODE REVIEW

**Comment by peterbarker** [comment]
New value looks incorrect.

```
>>> hex(mavutil.mavlink.POSITION_TARGET_TYPEMASK_VX_IGNORE | mavutil.mavlink.POSITION_TARGET_TYPEMASK_VY_IGNORE | mavutil.mavlink.POSITION_TARGET_TYPEMASK_VZ_IGNORE | \
...                                mavutil.mavlink.POSITION_TARGET_TYPEMASK_AX_IGNORE | mavutil.mavlink.POSITION_TARGET_TYPEMASK_AY_IGNORE | mavutil.mavlink.POSITION_TARGET_TYPEMASK_AZ_IGNORE | \
...                                mavutil.mavlink.POSITION_TARGET_TYPEMASK_FORCE_SET | \
...                                mavutil.mavlink.POSITION_TARGET_TYPEMASK_YAW_IGNORE| mavutil.mavlink.POSITION_TARGET_TYPEMASK_YAW_RATE_IGNORE)
'0xff8'
>>> 
```

Did I stuff my test here up somehow?

**Review by khancyr — APPROVED** [review]
@peterbarker the old value is wrong in the sens that the last 4 bits aren't used and define nothing

````
In [12]: bin(mavutil.mavlink.POSITION_TARGET_TYPEMASK_YAW_RATE_IGNORE)          
Out[12]: '0b100000000000'

````

**Review by peterbarker — COMMENTED** [review]
I contend that those bits should be set.  If those bits get defined in the mavlink then we'll definitely be ignoring them!  We're ignoring them right now - its just that they don't have a mnemonic ATM.

One possibility would be to give them names in here:
```
    // we ignore bits which are not defined in the specification:
    constexpr uint16_t POSITION_TARGET_TYPEMASK_BIT_12 = (1U<<12);
```

**Comment by khancyr** [comment]
fair point ! 
@muramura could you update with Peter suggestion ? thank

**Comment by khancyr** [comment]
close by #16925

**Pull request closed without merging**
