### PR TITLE
Emacs: remove headers

### PR DESCRIPTION
**Pull request by mothacehe**
Using a single .dir-locals.el has multiple advantages:
- If the coding style is modified, there is only one file to update (instead of 725+)
- It doesn't alter code for people who don't even use emacs.

The line: (c-mode . ((mode . C++))) of .dir-locals.el forces emacs to use c++-mode on headers (.h) who are by default hooked to c-mode.

### CODE REVIEW

**Comment by magicrub** [comment]
can you have both? That is, can we leave the header text in but add the file?

**Comment by lucasdemarchi** [comment]
Other editors may use these lines. I don't mind removing them though as I very much agree with your reasoning.

**Comment by mothacehe** [comment]
@magicrub: If there is an emacs header + a .dir-locals.el, the header has priority.

**Comment by lucasdemarchi** [comment]
Applied, thanks.

**Comment by gmorph** [comment]
I'm not an expert on this but I do use emacs all the time for editing.  If the .dir-locals.el file is only in the ardupilot directory and I'm editing something in a different directory is emacs going to "see" the .dir-locals.el file and apply the formatting automatically or do I need to "load" the .dir-locals.el file first before any editing?
Thanks, Grant.

**Comment by mothacehe** [comment]
@gmorph: The .dir-locals.el applies to all files in directories and all subdirectories under it. You don't need to load it, it is done automatically.

**Comment by magicrub** [comment]
Does anyone know of an IDE that takes advantage of the current header one?
Could it be replaced by a style file for those IDEs? That and like the best
way forward. We need one for eclipse.

**Comment by lucasdemarchi** [comment]
It's possible to configure vim to use mode lines.  I use vim (actually neovim since ~5months ago) and I prefer to configure coding style in another way.

There's this "spec": http://editorconfig.org/

Several editors have it bundled or a plugin to respect it.   I don't use, but it's probably what you are looking for.

**Pull request closed without merging**
