### PR TITLE
HAL_ChibiOS: modify APJ_BOARD_ID of YJUAV_A6SE

### PR DESCRIPTION
**Pull request by yunjiuav**

### CODE REVIEW

**Comment by yunjiuav** [comment]
image
The board hardware ID has been determined to be 1127, and the hardware definition has been updated synchronously.

**Review by peterbarker — APPROVED** [review]

**Comment by tridge** [comment]
I think this also needs a rebuild of the bootloader

**Comment by yunjiuav** [comment]
> I think this also needs a rebuild of the bootloader

Yes, we follow the steps, and the bootloader file will be submitted immediately if there is no problem with the definition file.

**Comment by yunjiuav** [comment]
The bootloader has been recompiled and submitted #24670

**Pull request merged**
