### PR TITLE
Adds velocity control to ROI points.

### PR DESCRIPTION
**Pull request by njoubert**
Hello guys and girls!

This commit is a core building block to improve the Region of Interest behavior in ArduCopter. We are using it with great results on top of DroneKit to get much smoother camera behavior, and we suggest that all FollowMe functionalities move towards using the approach enabled here.

This commit adds an additional capability to the AP_Mount ROI points. The ROI point can have a 3D velocity associated with it. The ROI point's latitude, longitude and altitude is updated based on this velocity at 50Hz. 

This commit also adds the additional capability to set ROI points using COMMAND_INT. This is important since COMMAND_INT gives centimeter-accurate lat-lon-alt values compared to the multi-meter accuracy of COMMAND_LONG. 

Setting ROI points with Velocity is exposed over MAVLink using a COMMAND_INT message. The x,y,z location is identical to setting an ROI point without a velocity, as used by COMMAND_LONG. param1 through param3 is used to specify the North, East and Down velocity of the ROI point.

Lastly, it adds support for logging the ROI point to dataflash using a "MNT" message. This occurs at 5Hz.

Documentation is currently a problem, as this new functionality does not appear inside the official MAVLink spec. We are happy to add it. This means that the MAV_CMD_DO_SET_ROI description does not accurately match the one on the official documentation. Any opinions? We could potentially update the documentation, or add a MAV_CMD_DO_SET_ROIVEL command.

### CODE REVIEW

**Comment by tridge** [comment]
the approach taken to DF logging in this PR means it will log even when logging is disabled (such as when disarmed).
Better to have a function in AP_Mount that does logging, then pass a reference to the dataflash to that function, and not pass to init()

**Comment by magicrub** [comment]
needs a rebase

**Comment by njoubert** [comment]
@tridge @magicrub @rmackay9 I've refactored this branch significantly. It should be good to go now!

**Comment by magicrub** [comment]
Travis didn't like it

**Comment by njoubert** [comment]
@magicrub woops! Fixed now!

**Comment by magicrub** [comment]
ardupilot-solo is a separate repo here https://github.com/3drobotics/ardupilot-solo/pulls . Wouldn't hurt to make a duplicate there, I'm not sure who manages it. Probably @jschall . The more PRs that go in there and not here just means they diverge more so and harder to rebase on master later so I'd like to think they'd be happy to pull in your change.

**Comment by LorenzMeier** [comment]
@tridge This should not be accepted and instead be put into the http://mavlink.org/messages/common#COMMAND_INT data path. There are more items (like waypoints themselves) that are affected and so its pretty pointless to fix this one-off and leave all the rest that's broken unfixed.

**Comment by njoubert** [comment]
@LorenzMeier hmm that sucks. Is that because you want mission items to also have the same capability?

Currently ArduCopter is *severely* limited by using floats for ROI points. lat-lon float values are on average ~2m off from their true value. We're attempting to autonomously film subjects, and if your look-at point is 2 meter off and you're only about 2m away, you're looking at completely the wrong thing.

**Comment by LorenzMeier** [comment]
You have the same issue for waypoints and commands as well - which is why the MISSION_ITEM_INT and COMMAND_INT were created. You will need to move everything over to those.

**Comment by njoubert** [comment]
OK. Sadly I'm 2 weeks from a paper deadline and won't have time to rewrite
this now. I'll fly this for my paper. If nobody else can pick it up in the
meantime I'll get back to it in a month or so.


-Niels

**Comment by rmackay9** [comment]
@njoubert, @magicrub, the solo guys are working on merging most of their changes back to master and then doing a release based on master (or the stable Copter-3.4 release when it comes out) so it might be sufficent to just PR it against master and skip PR-ing it against the solo branch.  As Tom says, @jschall could give his opinion on that.

Re the MISSION_ITEM_INT and COMMAND_INT.  The It's on the to-do list to add support for these but it's not done yet.  I wouldn't expect Niels to take on that effort.
For the new message (SET_ROI_GLOBAL_INT), there are 6 (or more?) fields that couldn't be fit into a COMMAND_INT or MISSION_ITEM_INT so I think a new message probably is required unless we can find another message that works.  SET_POSITION_TARGET_GLOBAL_INT is closest but I don't think it's appropriate to use that.

We could generalize the message a bit so that it could be used for follow-me (i.e. following behind another vehicle or a person on the ground) but I'm not sure it's worth it.

**Comment by magicrub** [comment]
What's the status of this PR?

**Comment by peterbarker** [comment]
This is showing its age, and I believe that it will need to be redone from scratch - a lot has changed in this code in 4.5 years!  Given the lack of activity there doesn't seem to be a huge call for the feature, so until someone finds the need to have these features I think we should close this.

**Comment by njoubert** [comment]
Fair enough!

**Pull request closed without merging**
