### PR TITLE
Add support for tailsitter quadplanes based on standard copter frames

### PR DESCRIPTION
**Pull request by kd0aij**
Set Q_FRAME_CLASS to 1 (MOTOR_FRAME_QUAD) and Q_FRAME_TYPE to 0 (MOTOR_FRAME_TYPE_PLUS)
for an airframe with motors on the wings and vertical fin/subfin.
Set Q_TAILSIT_MOTMX to 3 to enable only the wing motors in forward flight; 15 to enable all 4.

Issue: must arm in a VTOL mode in order for motors to spool up properly. If armed in a FW mode, motors will not spin until entering a VTOL mode. This is because output_motors_mask now checks the spool_mode and AP_MotorsMultiCopter::output_logic is not invoked in FW modes, meaning the spool mode is "shutdown".

### CODE REVIEW

**Comment by kd0aij** [comment]
@IamPete1 The 2 new commits address the issue with output_motor_mask checking the spool_mode.  I've tested them in SITL and on my Pixracer/Dart quad tailsitter.

I think this fix is also necessary for tiltrotors, but haven't done any testing of that yet.

**Comment by IamPete1** [comment]
@kd0aij I have spent ages trying to work out what is going on with the motor matrix spool issue. It is also there for tilt-rotors. However for tilt-rotors just the adding the call to output_logic makes it work without needing to set the spool state. very odd, I cant see anywhere that the tilt-rotor gets its spool state changed that tailsitter does not. 

Anyway rather than changing the muticopter spool mode i think it might be better to just put the mask functionality back to how it was. this can be done by replacing output_to_pwm(_actuator[i]) with 

get_pwm_output_min() + (get_pwm_output_max()-get_pwm_output_min()) * (_spin_min + (_spin_max-_spin_min)*apply_thrust_curve_and_volt_scaling(_actuator[i]))

this then saves changing spool modes, I also wonder if it is necessary to not spool down the copter controller [here](https://github.com/ArduPilot/ardupilot/blob/a21f4dc0c98de8f6ccd35ffdc7069337152818c2/ArduPlane/quadplane.cpp#L1246) ie, if were bypassing it anyway it shouldn't matter. I haven't tested this. 

If your going to be on the call tomorrow you could mark it for descustion, I think its more or less ready to go in.

**Comment by kd0aij** [comment]
I talked with Randy yesterday, and he suggested a few changes he'd want before merging. I think I also found a problem with breakage of the q_tailsit_mask functionality.  Hopefully I'll have some fixes to push later today.

The spool mode issue is definitely confusing; I may have to flowchart the whole thing to understand what's going on.  Somebody had done a blog with flowcharts recently, I think.

**Comment by kd0aij** [comment]
superseded by #10401

**Pull request closed without merging**
