### PR TITLE
ChibiOS support - part 3

### PR DESCRIPTION
**Pull request by tridge**
This PR is for continuing work on the ChibiOS port.

There are quite a few key features still needed:

    chibios build of IOMCU firmware
    buzzer support (pending from Mark)
    px4pro support
    fmuv1 support
    io firmware upload
    set_system_clock support
    analog stop pins
    serial5 support on fmuv3
    i2c and ICU filtering (i2c filtering done)
    mindpx-v2 logging
    PWM based rangefinders (in AP_RangerFinder_PWM_PX4)

Sid and I will be working on these features, pushing to this branch

### CODE REVIEW

**Comment by Pedals2Paddles** [comment]
@tridge I just ran the build with the latest from your branch. Happiness abounds.

- RC & PWM I/O has been restored
- Solo's mavlink gimbal is now fully operational.
- GoPro controls work through the mavlink gimbal as they should
- As before, Smart battery is working in all respects
- Dataflash logging over mavlink is working

**The performance monitor data is astounding!** The Solo is very heavy load on the Pixhawk's performance. As you can see, with the Nuttx / px4 firmware, it is extremely overtaxed at all times. The gimbal and logging take a heavy toll on it. Massive overruns at all times.  With ChibiOS, well the the numbers speak for themselves, I don't even need to describe the results.

**ArduCoper master 3.6-Dev // Nuttx & PX4**
PERF: 1316/4000 max=6659 min=2119 avg=2953 sd=597
PERF: 1280/4000 max=8157 min=1882 avg=2952 sd=616
PERF: 1275/4000 max=7370 min=2014 avg=2958 sd=637
PERF: 1313/4000 max=7256 min=1905 avg=2960 sd=607
PERF: 1328/4000 max=6748 min=1942 avg=2958 sd=600
PERF: 1313/4001 max=6854 min=1934 avg=2953 sd=584

**ArduCopter 3.6-Dev // ChibiOS**
PERF: 1/4000 max=3004 min=2200 avg=2501 sd=86
PERF: 2/4000 max=3308 min=2125 avg=2501 sd=96
PERF: 1/4000 max=3102 min=2197 avg=2501 sd=90
PERF: 2/4000 max=3102 min=2098 avg=2501 sd=88
PERF: 5/4000 max=3795 min=2104 avg=2505 sd=99
PERF: 0/4000 max=2998 min=2104 avg=2501 sd=94
PERF: 0/4000 max=2888 min=2100 avg=2500 sd=82

**Comment by Pedals2Paddles** [comment]
@tridge ChibiOS will break compatibility with px_uploader.py.  The USB serial point has "COM" in the string, and that causes px_uploader to ignore it.  See https://github.com/Pedals2Paddles/sololink/commit/94b77468afeb0a5fd1d09db0b244c61cf461cb20.
It works fine after removing that restriction as show in that commit.  However, I have to think there is a reason it was ignoring ports with COM in the string before?  Would fixing this cause more problems than it solves?

**Comment by WickedShell** [comment]
`AP_HAL_ChibiOS::set_system_clock` still needs to be implemented as well it appears, I haven't looked into how hard it is to actually implement it yet however.

**Comment by tridge** [comment]
merging after discussion with Randy

**Pull request merged**
