### PR TITLE
CI: add Azure pipelines (continuation of #10027)

### PR DESCRIPTION
**Pull request by OXINARF**
GitHub is playing games apparently and didn't re-open the previous PR, so new PR.

Follow the history in #10027, especially last comment.

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
@OXINARF nice!

One question: why are we building 32-bits rather than 64? Can we build both?

**Comment by OXINARF** [comment]
@lucasdemarchi Just one reason: our server will download these artifacts so that Mission Planner can use them - and (unfortunately) there are still a number of users running 32bit Windows.

We can build both, but it might be a waste of time. Any reason why you would need it?

**Comment by magicrub** [comment]
@OXINARF if the majority of users are on x64, it would make sense to test for that one instead of we had to choose just one

**Comment by OXINARF** [comment]
@magicrub Something would have to be very wrong for it to build in 32bit and not in 64bit. In any case, as I've said, the daily autotest runs still happen in 64bit.

**Comment by WickedShell** [comment]
> if the majority of users are on x64, it would make sense to test for that one instead of we had to choose just one

I'd disagree with this on the basis that x64 windows to my knowledge always can run 32 bit applications, but there are still 32 bit only (low end/cheap) windows machines being built and sold, and not dropping support for these is still valuable.

**Comment by tridge** [comment]
this looks good, thanks!
I'll merge now, then switch over the download script for sitl binaries from appveyor

**Pull request merged**
