### PR TITLE
Copter: inhibit heartbeat until finished booting

### PR DESCRIPTION
**Pull request by magicrub**
Closes https://github.com/ArduPilot/ardupilot/issues/11591 where first heartbeat always has type QUADCOPTER and following heartbeats have correct Copter frame type configured

### CODE REVIEW

**Comment by peterbarker** [comment]
This will probably break the sensor-failure-loop as the initialised flag won't be set.  If we don't send heartbeats we're not acting correctly - routing will break and whatnot.

We could consider sending back `MAV_TYPE_GENERIC` until we are initialised - but we will need to check how GCSs behave when we change `MAV_TYPE` heartbeat-to-heartbeat.

**Comment by magicrub** [comment]
@peterbarker I have no idea what you're talking about. This has zero impact on when the flag gets changed.

In principle, we should not be sending a heartbeat with wrong data, ever. Especially intentionally. If that means the whole comms link is mute for another few milliseconds, then I think that's the better way to go. If a system is depending on a communication to be sent during an init then that subsystem sounds flawed.

One thing that I added, and then removed, was to immediately send a heartbeat after we set the flag because, obviously, we're skipping the first heartbeat now with this PR's change.

**Comment by peterbarker** [comment]
I was hoping there would be a `MAV_TYPE_UNKNOWN` - there really should be.  `GENERIC` is as close as we come.

I'm pointing out that the vehicle may not boot properly and be stuck in https://github.com/ardupilot/ardupilot/blob/pr%2Fsurface-tracking/libraries/AP_BoardConfig/AP_BoardConfig.cpp#L300

Sending out heartbeats is what lets a user possibly fix that situation.

Adding the addition check against `AP_BoardConfig::in_sensor_config_error()` would look like a fix for that - but this was just the first thing I thought of.  How does this interact with things like the initial gyro calibration?  We go to a bit of trouble to bring up an initial channel very early so we do get early comms: https://github.com/ardupilot/ardupilot/blob/pr%2Fsurface-tracking/ArduPlane/system.cpp#L58

**Comment by lucasdemarchi** [comment]
I agree we should not send wrong data at all instead of changing from unknown -> whatever. However, why do we delay so much setting the mav type?

Untested but it should be a matter of moving the call `set_default_frame_class()` to happen just after parameters are loaded in `Copter::init_ardupilot()`, right?

**Comment by lucasdemarchi** [comment]
btw, since we have a special HELI build, another option would be to *remove* this function and just embed the default value within the param table.

**Comment by peterbarker** [comment]
On Fri, 21 Jun 2019, Lucas De Marchi wrote:

> btw, since we have a special HELI build, another option would be to remove
> this function and just embed the default value within the param table.

Doesn't help on boats where your mav type depends on a parameter :-)

Also, sometime in the far-flung future it would be nice to have a single 
build combining multi/heli.  That feels like it's getting further away, 
however :-)

**Comment by lucasdemarchi** [comment]
It actually makes it closer if you with the approach of embedding the param.

**Comment by lucasdemarchi** [comment]
Well... Thinking that the first thing the user has to do is to configure the frame type, changing the default to unknown would be acceptable. And move the function call like I said so in the case there is still a build difference, that is respected.

**Comment by tridge** [comment]
this would break sensor failure handling

**Comment by magicrub** [comment]
How does this break stuff?

**Pull request closed without merging**
