### PR TITLE
AP_Mount: Remove incomplete comment outs

### PR DESCRIPTION
**Pull request by muramura**
Commented out process is incomplete.
I think incomplete processing is unnecessary.

### CODE REVIEW

**Review by khancyr — APPROVED** [review]
looks ok. @rmackay9 wanna merge or close ?

**Review by rmackay9 — APPROVED** [review]
Sure, it is a bit of a golden rule that we don't leave commented out code in there so let's get rid of it.  Txs

**Comment by rmackay9** [comment]
I can't immediately find how to re-start failed jobs.. the button seems to have moved..

**Comment by peterbarker** [comment]
Fun times, master now has uncommented those lines and uses them.  So we definitely don't want to merge this one now :-)

**Pull request closed without merging**
