### PR TITLE
AC_AttitudeControl: fix get_vel_target_z_cms description

### PR DESCRIPTION
**Pull request by mirkix**

### CODE REVIEW

**Review by lthall — APPROVED** [review]
Thanks! This is a mistake I make regularly. 

If you are reading through this code are there any other comments that could do with rewording or clarifying?

**Review by rmackay9 — APPROVED** [review]

**Comment by rmackay9** [comment]
Merged, thanks!

**Comment by mirkix** [comment]
@lthall Hello Leonard, no, that is all that is found so far.

**Comment by lthall** [comment]
Cool, thanks for picking this up. Let us know if you find any other problems!

**Pull request merged**
