### PR TITLE
AC_Sprayer: Change the comment of the variables in the form of doxygen.

### PR DESCRIPTION
**Pull request by muramura**
The header and source comments, can be used as a change and reference manual in the form of doxygen.

### CODE REVIEW

**Comment by OXINARF** [comment]
I think this is only worth it if someone is committed to do it all over the code base - there's no point in having this in only one library.

**Comment by muramura** [comment]
@OXINARF Comment Thanks.
I also think in the same way.
It is scheduled to make a similar work from now on other libraries.
Does it better to PR from change all?
This task is thought to be useful for the creation of drivers and flight mode.

**Comment by OXINARF** [comment]
@muramura No, separate PRs are easier to review and more likely to go in. If you are going to do this for other libraries I think this is a good thing to have.

Is the methods' documentation properly formatted for Doxygen? We shouldn't do only half of a class.

**Comment by muramura** [comment]
@OXINARF's Thank you for comment.
It is part of this class matches the format of doxygen.
"/<" Not the only addition.
Corrections and additions are required.
Especially for the arguments of the method, description has not been written.
I need to add a new this description.
Considering these things, at the timing of the bug fixes, who began to change in the format of doxygen was good think.

This PR is, I would like you to close.

**Comment by rmackay9** [comment]
We've also always talked about starting with one library to see how it would look, and then move onto others.  In any case, the result is quite readable so I've merged, thanks!

**Pull request closed without merging**
