### PR TITLE
AP_DDS: Local Velocity Publisher

### LINKED ISSUE #23279: AP_DDS: Add support for geometry_msgs/TwistStamped velocity publishing from AP
Add support for publishing the velocity of the vehicle in the local coordinate system. This message goes hand in hand with #23278 (they are published at the same rate at the same time). 

The Twist message captures the linear and angular velocities of the vehicle following ROS REP 103 conventions (SI units, ENU, right-handed quaternion orientation)

### PR DESCRIPTION
**Pull request by pedro-fuoco**
Resolves #23279 
Here is the PR working in its current state in SITL:
Screenshot from 2023-04-18 18-21-45
It is currently following:
```
// In ROS REP 103, it follows this convention
// X - Forward
// Y - Left
// Z - Up
// https://www.ros.org/reps/rep-0103.html#axis-orientation
```
For linear velocity, the data is earth-fixed but starts alligned with the robot body (x-forward)
For angular velocity, the gyro data is body-fixed.

### CODE REVIEW

**Comment by pedro-fuoco** [comment]
> For linear velocity, the data is earth-fixed but starts alligned with the robot body (x-forward)
For angular velocity, the gyro data is body-fixed.

Should we keep it that way ? Or do everything acording to NED ? This is easy to implement but the AP community needs to agree on how to do it

**Comment by Ryanf55** [comment]
> > For linear velocity, the data is earth-fixed but starts alligned with the robot body (x-forward)
> > For angular velocity, the gyro data is body-fixed.
> 
> Should we keep it that way ? Or do everything acording to NED ? This is easy to implement but the AP community needs to agree on how to do it

As before, we want to follow ROS rep's as best as possible. In REP-147, it says, even for aerial vehicles, to follow REP-105. 
https://ros.org/reps/rep-0147.html#coordinate-frames

That said, it doesn't clarify on NED vs ENU. For now, let's stick with ENU, since that's largely a convention in the ROS community, and this is a ROS interface. 

I think it's totally reasonable, later, to add an alternative subset of topics in NED convention, if it's needed.

**Comment by Ryanf55** [comment]
We spent some time testing, just deciding what coordinate system the orientation should follow on the vehicle. Likely, we will match what NAV2 is using, but I had issues bringing the examples up in NAV2.

**Comment by Ryanf55** [comment]
Please rebase this on master to fix conflicts with the pose topic. Then, I can test it. Thanks!

**Comment by pedro-fuoco** [comment]
Rebased and updated the axis orientation to follow ENU and what was agreed on #23480.
@Ryanf55 I've tested it in SITL with a controller and both the linear and angular velocities seem to check out! Feel free to check it out

**Review by Ryanf55 — APPROVED** [review]

**Pull request merged**
