### PR TITLE
hwdef: Fix Aocoda-RC H743Dual motor 5-8 mis-labeled issue

### PR DESCRIPTION
**Pull request by lida2003**
[ Fix Aocoda-RC H743Dual motor 5-8 mis-labeled issue #9948 ](https://github.com/iNavFlight/inav/pull/9948)

### CODE REVIEW

**Review by peterbarker — DISMISSED** [review]
@lida2003 should only be one commit.

I tried correcting this but don't seem to have permissions to do that on this PR.


`git rebase -i master` while the branch is checked out, `git push -f github` to push the result up

**Comment by lida2003** [comment]
> `git rebase -i master` while the branch is checked out, `git push -f github` to push the result up

@peterbarker OK,  done. Please check!

**Review by tridge — APPROVED** [review]

**Comment by rmackay9** [comment]
@lida2003 has asked that we try and include this in 4.5.4.

**Comment by lida2003** [comment]
@rmackay9 @Hwurzburg   And I think Wiki need to update also .  https://github.com/ArduPilot/ardupilot_wiki/pull/6010#issuecomment-2130728143

**Comment by Hwurzburg** [comment]
there is a pending 2.6 wiki PR for this already...#5896  which will merge when this change appears in a release (beta/stable)...its only in master now

**Pull request merged**
