### PR TITLE
Plane: support NAV_PAYLOAD_PLACE mission item for quadplanes

### PR DESCRIPTION
**Pull request by tridge**
This allows quadplanes to do package delivery using a lua script. Documentation is provided in the applets directory

This is a typical mission:
image

The script adds some PKG_ parameters to control the release height and hold time. It supports both payload place with hover, and waiting for a full landing before releasing the package

Testing has only been done in SITL so far

MissionPlanner needs the following change: https://github.com/ArduPilot/MissionPlanner/pull/3045

Demo video: https://www.youtube.com/watch?v=A8Romq6wiek

### CODE REVIEW

**Comment by IamPete1** [comment]
I'm not a fan. I don't think we should use `NAV_PAYLOAD_PLACE` unless it works the same as copter, there it will just work as described here you need to load a script. Depending on the script it can be quite a different behaviour, so reusing the same item causes confusion when moving between vehicles. In this PR I add a more generic Scripting nav mission item https://github.com/ArduPilot/ardupilot/pull/20548. something like that could be used, we could add a new command `NAV_SCRIPT_PAYLOAD_PLACE`, or keep a generic `NAV_SCRIPT_GENERIC` and use one of the mission item params as a identifier. This also adds several `plane.control_mode == &plane.mode_auto && plane.mission.get_current_nav_id() == MAV_CMD_NAV_PAYLOAD_PLACE` special cases in the quadaplane code, I have been trying to move away from that pattern as it makes the code harder to follow (and therefore easier to break). 

My preference would be to add support for generic scripting NAV mission items (we have generic DO mission items already). Then we implement a `vehicle:land(position)` binding that allows the landing code to be entered from scripting. I appreciate that will be a lot more work but I think it will be better in the long run.

**Comment by tridge** [comment]
@IamPete1 I think copter should add a package delivery script as well, allowing for the options I'm adding in this one. The copter PAYLOAD_PLACE is very inflexible in the ground handling (button press, tones, servo sequencing). It has the "detect payload touchdown" code, but we can't do that in quadplanes (I discussed with Leonard, and he agrees its just not feasible to use that in quadplanes)
The problem with a NAV_SCRIPT mission item is we need it to be an ID under 255, otherwise there just isn't space for the lat/lon/alt and the max descent. We shouldn't be wasting the IDs under 255 when we can use an existing one, and the exiting PAYLOAD_PLACE is a great fit, with very similar behaviour to copter except for the payload weight detection and doing the servo sequencing externally.
I agree on the mode_auto checks, a common method to make that neater makes sense

**Comment by IamPete1** [comment]
> I agree on the mode_auto checks, a common method to make that neater makes sense

My complaint is not one of neatness. It is that for example the seemingly trivial function `set_desired_spool_state` now has none trivial mode dependent behavior.

**Comment by tridge** [comment]
> It is that for example the seemingly trivial function `set_desired_spool_state` now has none trivial mode dependent behavior.

that is indeed nasty. It comes from not actually disarming when we touchdown, and instead just putting motors into SHUT_DOWN state. The problem is that other places force THROTTLE_UNLIMITED state.
A few other options:
 - allow full disarm, and script re-arms when needed
 - put a conditional in the places that force THROTTLE_UNLIMITED and don't do it

The plan to not disarm and instead use SHUT_DOWN is debatable. While on the ground the aircraft is in a potentially unsafe state, as it is pending an automatic takeoff so it being "armed" makes some sense, but we could instead disarm and setup mission logic to continue, while retaining the QPOS state ready for the climb.

**Comment by tridge** [comment]
@IamPete1 updated to address your comments, less intrusive now

**Review by IamPete1 — APPROVED** [review]
Looks good, much less tangled.

**Pull request merged**
