### PR TITLE
UAVCAN: update submodule to latest upstream tree

### PR DESCRIPTION
**Pull request by OXINARF**
As the title says updates the UAVCAN submodule to match the last commit in upstream.

### CODE REVIEW

**Comment by EShamaev** [comment]
Great! Thank you!

**Comment by EShamaev** [comment]
What is wrong with Semaphore on this PR?

**Comment by OXINARF** [comment]
@EShamaev Ubuntu servers failing, I've demanded a rebuild.

**Comment by EShamaev** [comment]
If all is OK with checks - let's merge?

**Comment by OXINARF** [comment]
Have you tested it? In principle this won't break anything, but our tests don't run UAVCAN, just build it.

**Comment by EShamaev** [comment]
During my builds for flight tests I always use latest uavcan and I pull it in manually to compile...
These changes were flying!

**Comment by EShamaev** [comment]
Flight tested today.
Works fine.

**Comment by bugobliterator** [comment]
@OXINARF this is much better, I will close my PR

**Comment by OXINARF** [comment]
Merged, thanks for testing!

**Pull request closed without merging**
