### PR TITLE
Add autotest for the no-short-failsafe option in auto mode for Plane

### PR DESCRIPTION
**Pull request by Aarush-Aggarwal**
The code is incomplete as of now. More checks need to be added.

### CODE REVIEW

**Review by khanasif786 — COMMENTED** [review]
@Aarush-Aggarwal Are you currently working on this.

**Comment by khanasif786** [comment]
#19190

**Comment by peterbarker** [comment]
Hmm.  These sorts of tests are actually a lot harder than they seem, due to interactions between the ground control station and the simulated vehicle.

Is this something you want to push ahead with?

**Comment by peterbarker** [comment]
No answer in a year on this one.

Please open a fresh PR if you'd like to pursue this one.

**Pull request closed without merging**
