### PR TITLE
.vscode: Don't override editor defaults

### PR DESCRIPTION
**Pull request by Ryanf55**
This prevents devs from using their own repo settings as discussed in https://github.com/ArduPilot/ardupilot/pull/18959

### CODE REVIEW

**Comment by TunaLobster** [comment]
Does this still provide new users suggested extensions in the UI?

**Comment by Ryanf55** [comment]
> Does this still provide new users suggested extensions in the UI?
The extensions.json file is intact and not moved.

**Comment by Ryanf55** [comment]
Master:
image


In PR:
image

**Review by andyp1per — APPROVED** [review]

**Comment by magicrub** [comment]
git'r'done!

**Pull request merged**
