### PR TITLE
Global: Change the tab code to whitespace

### PR DESCRIPTION
**Pull request by muramura**
I've been using a lot of tab code lately in adding file information, adding config parameter information, and adding classes.
I would change the tab code to whitespace.

### CODE REVIEW

**Comment by rmackay9** [comment]
I actually like the change, I think we should try and keep things tidy.  If other devs aren't in favour of the global change then I'll probably cherry pick in the changes for the libraries that I'm responsible for.

**Comment by khancyr** [comment]
if we are going to remove the tabs, we should do it part by part as autoconversion will surely mess up the coding style somewhere and this will lead to more PR to correct style only ...

**Comment by tridge** [comment]
I'd strongly prefer not to do this. I use git history a lot

**Comment by rmackay9** [comment]
I've merged a much reduced subset of the changes and I'll close this now..

**Pull request closed without merging**
