### PR TITLE
[wip] begin testing on osx

### PR DESCRIPTION
**Pull request by mrpollo**
this is a wip for now, please don't review this branch is going to get dirty !

### CODE REVIEW

**Comment by guludo** [comment]
> please don't review this branch is going to get dirty !

Why not opening the PR when that's ready for review, then? :-) (even if still a wip)

**Comment by mrpollo** [comment]
@guludo this PR is for TravisCI, I can probably make it work on my fork, but whats the problem with having this here?, it benefits from exposure, I have had comments from other community members offering help, can you please explain why wouldn't I push this PR as a wip early on?.

Perhaps I should edit the description, `s/review/merge/g`

**Comment by guludo** [comment]
@mrpollo Yep, the description. It just seemed weird opening a pull request and asking not to review it :-)

**Comment by khancyr** [comment]
Closed as it goes nowhere. We have now a config script for mac os

**Pull request closed without merging**
