### PR TITLE
build: improved ccache build efficiency for multiple boards

### PR DESCRIPTION
**Pull request by tridge**
This improves build efficiency for our firmware server by allowing ccache to get cache hits between similar boards.
The test I used was MatekF405 and MatekF405-bdshot, which are very similar.
With master the two builds run consecutively starting with a clean ccache are
 - MatekF405 150s
 - MatekF405-bdshot 152s

with this PR the two builds are:
 - MatekF405 131s
 - MatekF405-bdshot 39s

so this has achieved a 13% build time reduction for uncached builds and a 75% reduction in build time for similar builds with ccache
this should have a dramatic impact on the time for building new firmware on our build server
@peterbarker how can we autotest this speed gain?

### CODE REVIEW

**Review by andyp1per — APPROVED** [review]
Presumably this doesn't affect files that have #defines for specific MCUs?

**Review by khancyr — COMMENTED** [review]
I am probably not the best personne for this review but the header cleanup looks fine.
On things we need to checkout is  the impication of setting SDMMC  to 1 by default  for  the board  that don't have  sd card ?

**Comment by tridge** [comment]
> Presumably this doesn't affect files that have #defines for specific MCUs?

I added MCU defines in the STM32*py files to cope with that

**Comment by andyp1per** [comment]
> I added MCU defines in the STM32*py files to cope with that

Right, but (for example) we have specific code for H750 for example rather than just H7. Presumably these defines are still in chibios?

**Comment by tridge** [comment]
> Right, but (for example) we have specific code for H750 for example rather than just H7. Presumably these defines are still in chibios?

we do need to check those are right, and really should use the defines section of STM32H750xx.py and other files to setup macros for features

**Comment by rmackay9** [comment]
Fantastic to see we're going to be able to speed up the builds very significantly.

**Review by peterbarker — APPROVED** [review]
LGTM

**Pull request merged**
