### PR TITLE
Plane: add aux channels options (ch5, ch6, ch7)

### PR DESCRIPTION
**Pull request by taedla01**
Hello everyone,

This pull request is for those users like me that use their auxiliary channels to command the control surfaces or control their camera mounts and want to use the inputs of its auxiliary channels for other tasks.

The idea is to use independently the inputs and outputs of the auxiliary channels. For example, while the output channel 5 controls the right flap, the input channel 5 controls the camera shutter.

This is the configuration of my input and output channels:

Main Channels:
INPUT_CH1 & OUTPUT_CH1 = Ailerons
INPUT_CH2 & OUTPUT_CH2 = Elevator
INPUT_CH3 & OUTPUT_CH3 = Throttle
INPUT_CH4 & OUTPUT_CH4 = Rudder

Auxiliary Channels:
INPUT_CH5 = Camera trigger
INPUT_CH6 = Relay on / off
INPUT_CH7 = Parachute
INPUT_CH8 = Flight mode

OUTPUT_CH5 = Right Flap
OUTPUT_CH6 = Left Flap
OUTPUT_CH7 = Camera Mount Roll Stabilization
OUTPUT_CH8 = Camera Mount Pitch Stabilitation

I have implemented following options according to actual Arducopter code, so for now, reference numbers are getting same options:

// Ch5, Ch6 and Ch7 aux switch control
#define AUX_SWITCH_PWM_TRIGGER_HIGH 1800   // pwm value above which the ch5, ch6 or ch7 option will be invoked
#define AUX_SWITCH_PWM_TRIGGER_LOW  1200   // pwm value below which the ch5, ch6 or ch7 option will be disabled

#define AUX_SWITCH_DO_NOTHING       0       // aux switch disabled
#define AUX_SWITCH_CAMERA_TRIGGER   9       // trigger camera servo or relay
#define AUX_SWITCH_PARACHUTE_ENABLE 21      // Parachute enable/disable
#define AUX_SWITCH_PARACHUTE_RELEASE 22     // Parachute release
#define AUX_SWITCH_PARACHUTE_3POS   23      // Parachute disable, enable, release with 3 position switch
#define AUX_SWITCH_RETRACT_MOUNT    27      // Retract Mount
#define AUX_SWITCH_RELAY_1          28      // Relay_1 pin on/off
#define AUX_SWITCH_RELAY_2          29      // Relay_2 pin on/off
#define AUX_SWITCH_RELAY_3          30      // Relay_3 pin on/off
#define AUX_SWITCH_RELAY_4          31      // Relay_4 pin on/off

Now we can play with Tx switches for different uses while their output
channels are being busy in other tasks. 

Code compiles with Arduino IDE for Ardupilot and works great on legacy APM1.

Regards from Spain,
Dario

### CODE REVIEW

**Comment by tridge** [comment]
Hi Dario, sorry for the slow response on this. Randy and I have actually been discussing this a bit on the weekly dev calls and in private, I just neglected to write up what we'd discussed.
I do want to add support for aux switches (both in plane and in rover), but I'd like to do it in a way that it isn't tied to a particular channel number. Transmitters with 16 channels are now quite common, and I'd like to allow people to use the high channel numbers for these sorts of functions.
So I think we need the following:
 - a AP_AuxSwitch library in common with plane and rover (later in common with copter too)
 - AUX1_CHAN, AUX2_CHAN, AUX3_CHAN variables in that library for what input channel numbers are used.
 - AUX1_FUNCTION, AUX2_FUNCTION, AUX3_FUNCTION variables controlling what each switch does
 - a aux_switch.check() function that would check if a switch has been activated and return the function that has been activated
 - a call to aux_switch.check() in the plane code which would then have a switch statement to implement the functions (in aux_switch.pde)

Is this something that you would be willing to take on? If not then Grant or I could do it, but we are unlikely to get to it for at least a few weeks.

**Comment by taedla01** [comment]
@tridge  After a month under snow, it is time for back to the civilization... Things became terrible here last month due a several winter weather conditions. Unfortunately I can not continue with the work of the pull request #1656  because my old APM is out of flash space. With current master code I exceed the 246kb limit so for develop those enhancements I need a Pixhawk, and for now this is impossible for me.

By the way, I have increased the aux_switch options for actual code. Now we can play with SONAR, RTL, AUTOTUNE, AUTO and MISSION_RESET too. This options need to be tested...

Other questions concerning making an AP_Aux_Switch library for all vehicles: some incoherences between Copter, Rover and Plane need to be fixed before attempting to unify this new options. Mainly param_list, failsafe stuff and control switches.

Maybe best option for now could be implement this pull request directly on master code, test the new options and then choose which options will be included on the new library. If you want, I can do the changes for Rover too. As I commented before, I can not change code on current Plane and Copter branchs due an out of flash space on my APM1s. Sorry for the inconveniences. :(
imagen122

Cheers,
Dario.

**Comment by rmackay9** [comment]
APM1?! someone get this man a pixhawk!

**Comment by taedla01** [comment]
Hello everyone,

@tridge please, give me your opinión about this:
I think we can move some options and funciones from control_modes.pde to new switches.pde (and future library). Maybe next items could be best on switches.pde as these are not mandatory options for control main flight modes. They are:
FENCE_CH
FLAP_IN_CH
RST_MISSION_CH
RST_SWITCH_CH
INVERTEDFLT_CH

By the way, other question is what we do with min & max PWM aux channel definitions. Actually I have implemented the limits for aux channels on defines.h and just one definition for the three channels. Would you want to include this on parameters.pde as a param options and individual configuration for each one?

Cheers,
Dario.

**Comment by magicrub** [comment]
This PR needs a rebase. Otherwise, what's the status of this PR? Still valid?

**Comment by davidbuzz** [comment]
This PR is very old, we think it's probably no longer relevant so we are closing it now, please let us know if this is in error

**Pull request closed without merging**
