### PR TITLE
Tools: add generate_features_txt_files.py 

### PR DESCRIPTION
**Pull request by peterbarker**
(built on top of another PR which does some more on extract_features.py)

### CODE REVIEW

**Comment by Hwurzburg** [comment]
sample features.txt file?

**Comment by peterbarker** [comment]
> sample features.txt file?

```
pbarker@fx:~/rc/ardupilot(master)$ cat build/CubeOrange/bin/features.txt 
AC_AVOID_ENABLED
AC_OAPATHPLANNER_ENABLED
AP_AIRSPEED_ANALOG_ENABLED
AP_AIRSPEED_ASP5033_ENABLED
AP_AIRSPEED_DLVR_ENABLED
AP_AIRSPEED_ENABLED
AP_AIRSPEED_MS4525_ENABLED
AP_AIRSPEED_MS5525_ENABLED
AP_AIRSPEED_MSP_ENABLED
AP_AIRSPEED_SDP3X_ENABLED
AP_AIRSPEED_UAVCAN_ENABLED
AP_AIS_ENABLED
AP_BARO_BMP085_ENABLED
AP_BARO_BMP280_ENABLED
AP_BARO_BMP388_ENABLED
AP_BARO_DPS280_ENABLED
AP_BARO_EXTERNALAHRS_ENABLED
AP_BARO_FBM320_ENABLED
AP_BARO_LPS2XH_ENABLED
AP_BARO_MS56XX_ENABLED
AP_BARO_MSP_ENABLED
AP_BARO_SPL06_ENABLED
AP_BARO_UAVCAN_ENABLED
AP_BATTMON_FUELFLOW_ENABLE
AP_BATTMON_FUELLEVEL_ANALOG_ENABLE
AP_BATTMON_FUELLEVEL_PWM_ENABLE
AP_BATTMON_SMBUS_ENABLE
AP_FENCE_ENABLED
AP_FETTEC_ONEWIRE_ENABLED
AP_GPS_ERB_ENABLED
AP_GPS_GSOF_ENABLED
AP_GPS_MAV_ENABLED
AP_GPS_NMEA_ENABLED
AP_GPS_NOVA_ENABLED
AP_GPS_SBF_ENABLED
AP_GPS_SBP2_ENABLED
AP_GPS_SBP_ENABLED
AP_GPS_SIRF_ENABLED
AP_GPS_UBLOX_ENABLED
AP_LTM_TELEM_ENABLED
AP_MOTORS_FRAME_DECA_ENABLED
AP_MOTORS_FRAME_DODECAHEXA_ENABLED
AP_MOTORS_FRAME_HEXA_ENABLED
AP_MOTORS_FRAME_OCTAQUAD_ENABLED
AP_MOTORS_FRAME_OCTA_ENABLED
AP_MOTORS_FRAME_QUAD_ENABLED
AP_MOTORS_FRAME_Y6_ENABLED
AP_OPTICALFLOW_CXOF_ENABLED
AP_OPTICALFLOW_ENABLED
AP_OPTICALFLOW_HEREFLOW_ENABLED
AP_OPTICALFLOW_MAV_ENABLED
AP_OPTICALFLOW_PIXART_ENABLED
AP_OPTICALFLOW_PX4FLOW_ENABLED
AP_OPTICALFLOW_UPFLOW_ENABLED
AP_RANGEFINDER_ANALOG_ENABLED
AP_RANGEFINDER_BENEWAKE_CAN_ENABLED
AP_RANGEFINDER_BENEWAKE_TF02_ENABLED
AP_RANGEFINDER_BENEWAKE_TF03_ENABLED
AP_RANGEFINDER_BENEWAKE_TFMINIPLUS_ENABLED
AP_RANGEFINDER_BENEWAKE_TFMINI_ENABLED
AP_RANGEFINDER_BLPING_ENABLED
AP_RANGEFINDER_ENABLED
AP_RANGEFINDER_GYUS42V2_ENABLED
AP_RANGEFINDER_HC_SR04_ENABLED
AP_RANGEFINDER_LANBAO_ENABLED
AP_RANGEFINDER_LEDDARONE_ENABLED
AP_RANGEFINDER_LEDDARVU8_ENABLED
AP_RANGEFINDER_LIGHTWARE_SERIAL_ENABLED
AP_RANGEFINDER_LWI2C_ENABLED
AP_RANGEFINDER_MAVLINK_ENABLED
AP_RANGEFINDER_MAXBOTIX_SERIAL_ENABLED
AP_RANGEFINDER_MAXSONARI2CXL_ENABLED
AP_RANGEFINDER_NMEA_ENABLED
AP_RANGEFINDER_PULSEDLIGHTLRF_ENABLED
AP_RANGEFINDER_PWM_ENABLED
AP_RANGEFINDER_TERARANGER_SERIAL_ENABLED
AP_RANGEFINDER_TRI2C_ENABLED
AP_RANGEFINDER_UAVCAN_ENABLED
AP_RANGEFINDER_USD1_CAN_ENABLED
AP_RANGEFINDER_USD1_SERIAL_ENABLED
AP_RANGEFINDER_VL53L0X_ENABLED
AP_RANGEFINDER_VL53L1X_ENABLED
AP_RANGEFINDER_WASP_ENABLED
AP_ROBOTISSERVO_ENABLED
AP_TRAMP_ENABLED
AP_VOLZ_ENABLED
BEACON_ENABLED
EK3_FEATURE_EXTERNAL_NAV
GPS_MOVING_BASELINE
GRIPPER_ENABLED
HAL_ADSB_ENABLED
HAL_ADSB_SAGETECH_ENABLED
HAL_ADSB_SAGETECH_MXS_ENABLED
HAL_ADSB_UAVIONIX_MAVLINK_ENABLED
HAL_ADSB_UCP_ENABLED
HAL_BARO_WIND_COMP_ENABLED
HAL_BATTMON_INA2XX_ENABLED
HAL_CRSF_TELEM_ENABLED
HAL_CRSF_TELEM_TEXT_SELECTION_ENABLED
HAL_DISPLAY_ENABLED
HAL_EFI_ENABLED
HAL_EFI_NWPWU_ENABLED
HAL_EXTERNAL_AHRS_ENABLED
HAL_GENERATOR_ENABLED
HAL_HIGH_LATENCY2_ENABLED
HAL_HOTT_TELEM_ENABLED
HAL_INS_TEMPERATURE_CAL_ENABLE
HAL_MOUNT_ALEXMOS_ENABLED
HAL_MOUNT_ENABLED
HAL_MOUNT_GREMSY_ENABLED
HAL_MOUNT_SERVO_ENABLED
HAL_MOUNT_STORM32MAVLINK_ENABLED
HAL_MOUNT_STORM32SERIAL_ENABLED
HAL_MSP_COMPASS_ENABLED
HAL_MSP_ENABLED
HAL_MSP_GPS_ENABLED
HAL_MSP_OPTICALFLOW_ENABLED
HAL_MSP_RANGEFINDER_ENABLED
HAL_NAVEKF2_AVAILABLE
HAL_NAVEKF3_AVAILABLE
HAL_NMEA_OUTPUT_ENABLED
HAL_OSD_SIDEBAR_ENABLE
HAL_PARACHUTE_ENABLED
HAL_PICCOLO_CAN_ENABLE
HAL_PLUSCODE_ENABLE
HAL_PROXIMITY_ENABLED
HAL_RUNCAM_ENABLED
HAL_SMARTAUDIO_ENABLED
HAL_SOLO_GIMBAL_ENABLED
HAL_SPEKTRUM_TELEM_ENABLED
HAL_SPRAYER_ENABLED
HAL_VISUALODOM_ENABLED
HAL_WITH_DSP
HAL_WITH_MSP_DISPLAYPORT
LANDING_GEAR_ENABLED
MODE_FLIP_ENABLED
MODE_FLOWHOLD_ENABLED
MODE_FOLLOW_ENABLED
MODE_GUIDED_NOGPS_ENABLED
MODE_SYSTEMID_ENABLED
MODE_TURTLE_ENABLED
MODE_ZIGZAG_ENABLED
OSD_ENABLED
OSD_PARAM_ENABLED
RPM_ENABLED
WINCH_ENABLED
!AP_AIRSPEED_NMEA_ENABLED
!AP_BARO_DUMMY_ENABLED
!AP_BARO_ICM20789_ENABLED
!AP_BARO_ICP101XX_ENABLED
!AP_BARO_ICP201XX_ENABLED
!AP_BARO_KELLERLD_ENABLED
!AP_ICENGINE_ENABLED
!AP_OPTICALFLOW_ONBOARD_ENABLED
!AP_RANGEFINDER_BBB_PRU_ENABLED
!AP_RANGEFINDER_BEBOP_ENABLED
!AP_RANGEFINDER_SIM_ENABLED
!HAL_LANDING_DEEPSTALL_ENABLED
!HAL_MSP_SENSORS_ENABLED
!HAL_QUADPLANE_ENABLED
!HAL_SOARING_ENABLED
!HAL_TORQEEDO_ENABLED
!MODE_SPORT_ENABLED
pbarker@fx:~/rc/ardupilot(master)$ 
```

**Comment by amilcarlucas** [comment]
Any plans to feed this into the autotests, so that disabled features will not cause tests to fail?

**Comment by peterbarker** [comment]
> Any plans to feed this into the autotests, so that disabled features will not cause tests to fail?

I didn't have any plans to do so, but we have actually got one test in place which is disabled because the feature isn't built in.  So looking at the binary would neaten that up a bit.

Where do you see doing that as particularly useful, rather than relying on the person who is customising their SITL binary also disabling tests that are no longer relevant?

**Comment by amilcarlucas** [comment]
Getting correct and up-to-date coverage values on the minimal build.
I have high hopes that the coverage on the minimal build is higher than the full build.
And for certification, high coverage values are very good. The systems we use do have a very minimalistic feature set. We use mostly guided mode, precision landing and a gimbal, all other features are disabled :)

**Review by tridge — APPROVED** [review]

**Pull request merged**
