### PR TITLE
ArduPlane : change in multiplication

### PR DESCRIPTION
**Pull request by RuffaloLavoisier**
-improve computational speed

### CODE REVIEW

**Comment by Hwurzburg** [comment]
incorrect....forcing return of a float in an in16 function

**Comment by RuffaloLavoisier** [comment]
@Hwurzburg 
Fixed it. please check me.

**Comment by Hwurzburg** [comment]
conversion to float and recast back to integer may have a net negative cpu cycle gain....would have to use something like Godbolt to check...and would vary by cpu type

**Comment by RuffaloLavoisier** [comment]
> and would vary by cpu type

@Hwurzburg 
I'm missing that part. iii check again.

**Review by IamPete1 — COMMENTED** [review]
I don't think these are worth changing. I'm not sure we get the CPU saving in these cases anyway....

This also costs us more flash because of the casting. + 40 bytes on F405

**Comment by RuffaloLavoisier** [comment]
@IamPete1 
I agree.

**Pull request closed without merging**
