### PR TITLE
AP_Beacon: Avoid FALLTHROUGH warning in Marvelmind device driver.

### PR DESCRIPTION
**Pull request by amilcarlucas**

### CODE REVIEW

**Comment by OXINARF** [comment]
@amilcarlucas You committed with an e-mail not associated with your GitHub profile. Not a big issue, but it's nice to have commits linked to the GitHub author.

I'm a little amazed how these also gave warnings, doesn't make any sense to me, what was done here is completely standard. I'm guessing this has been tested with GCC 7 to see the warnings right?

**Comment by amilcarlucas** [comment]
Peter told me it gave warnings on his system, so I corrected it.
@peterbarker can you retest to make sure that I got all cases ?

**Comment by WickedShell** [comment]
These do not actually generate fall through warnings. However you do generate fallthrough warnings later on in this file that should be addressed:
```../../libraries/AP_Beacon/AP_Beacon_Marvelmind.cpp: In member function ‘virtual void AP_Beacon_Marvelmind::update()’:
../../libraries/AP_Beacon/AP_Beacon_Marvelmind.cpp:330:63: warning: this statement may fall through [-Wimplicit-fallthrough=]
                             process_beacons_distances_datagram();
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
../../libraries/AP_Beacon/AP_Beacon_Marvelmind.cpp:333:25: note: here
                         case AP_BEACON_MARVELMIND_POSITION_DATAGRAM_HIGHRES_ID:
                         ^~~~

../../libraries/AP_Beacon/AP_Beacon_Marvelmind.cpp: In member function ‘virtual void AP_Beacon_Marvelmind::update()’:
../../libraries/AP_Beacon/AP_Beacon_Marvelmind.cpp:330:63: warning: this statement may fall through [-Wimplicit-fallthrough=]
                             process_beacons_distances_datagram();
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
../../libraries/AP_Beacon/AP_Beacon_Marvelmind.cpp:333:25: note: here
                         case AP_BEACON_MARVELMIND_POSITION_DATAGRAM_HIGHRES_ID:
                         ^~~~
```

**Comment by amilcarlucas** [comment]
Please reopen, I have fixed it now. Thanks for noticing :)

**Comment by WickedShell** [comment]
@amilcarlucas I can't actually reopen. I'm unfamiliar with why but apparently after something is closed if you push to it the PR can't be reopened? Sorry about that. If you want to submit a new PR that should be the easiest approach, I can't click the button as is because it's ghosted out though...

**Comment by amilcarlucas** [comment]
OK, I'll do that then.

**Pull request closed without merging**
