### PR TITLE
Copter: correct fence prearm check

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by peterbarker** [comment]
```
I think some discussion on the PR might be warranted - if people have fence-enable-on-a-switch, maybe they do want the prearm to stop them taking off without GPS lock?!
```

**Comment by rmackay9** [comment]
Let's change fence::get_enabled_fences() to return zero if the fence isn't enabled

**Comment by khancyr** [comment]
What is the problem here ? fence::get_enabled_fences() already return 0 when fences aren't enabled

**Comment by peterbarker** [comment]
On Tue, 28 Aug 2018, Pierre Kancir wrote:

> What is the problem here ? fence::get_enabled_fences() already return 0 when
> fences aren't enabled

Yes, I'd noticed that.  Which has left me mulling over how Luis had the 
problem....

**Pull request closed without merging**
