### PR TITLE
AP_Mount: send text feedback when gimbal gets detected

### PR DESCRIPTION
**Pull request by amilcarlucas**

### CODE REVIEW

**Review by rmackay9 — DISMISSED** [review]
In the new gremsy gimbal driver I've got a similar message but it is formatted a little differently:

`Mount: GREMSY PixyU fw:7.7.7.1.0`

So maybe this one should be  "Mount: MAVLink" or "Mount: SToRM32".

**Comment by olliw42** [comment]
ideally it would not be send then the gimbal is detected (initialized) but whenever it is "needed"

I do it by linking it to send banner 
(the banner appears to me to be always send out when e.g. a gcs connects, so it appeared to me to be not too bad, but there might better ways)
https://github.com/olliw42/BetaPilot/blob/BetaCopter41/libraries/GCS_MAVLink/GCS_Common.cpp#L3655-L3658
https://github.com/olliw42/BetaPilot/blob/BetaCopter41/libraries/GCS_MAVLink/GCS_Common.cpp#L3655-L3658
just as an idea

**Comment by peterbarker** [comment]
Ping @amilcarlucas - suggestions have been made here

**Comment by rmackay9** [comment]
I think @olliw42's suggestion is a good one.  If we want the user to reliably see the message then linking to the banner is probably the best way to do it.

So I think the question becomes whether displaying the gimbal info is important enough or not.  Comparing to other subsystems, we do display Servo output info in the banner because we found users were having troubles getting the outputs configured correctly (because the setup is complex) especially when using DShot/BLheli.  If we take it to the extreme then every subsystem would display something in the banner which would result in a huge block of text sent to the GCS each time the parameters are downloaded.  Maybe that would be useful and maybe then the issue would just become how often it is displayed which is a different issue we could fix as well.

**Comment by amilcarlucas** [comment]
OK, implemented Randy suggestion

**Comment by rmackay9** [comment]
Recently we're using GCS_SEND_TEXT more than gcs().send_txt() but I've merged anyway to keep things moving along.

**Pull request merged**
