### PR TITLE
Linux_HAL_Essentials: set default pwm to 0us

### PR DESCRIPTION
**Pull request by mirkix**
This PR is for the PRU Firmware (PWM and RCIN) used by BBBmini, BLUE and PocketPilot.

* Change default PWM value from 920us to 0us, now no PWM output until first PWM set by ArduPilot
* Prevent chance of 400ns spikes when PWM is set to 0us

### CODE REVIEW

**Comment by patrickpoirier51** [comment]
Logging in as beta tester to get the ''merged'' message so I can test & confirm

**Comment by OXINARF** [comment]
@mirkix Can I merge? This is really your territory, I think nobody can do a better review than you here.

**Comment by mirkix** [comment]
@OXINARF yes, please merge.

**Comment by OXINARF** [comment]
Merged, thanks!

**Pull request merged**
