### PR TITLE
SITL: update simpleRover C++ JSON interface example

### PR DESCRIPTION
**Pull request by srmainwaring**
This PR adds some minor enhancements to the simpleRover C++ JSON interface example 

- Add a CMakeLists.txt file to help with cross-platform builds.
- Modify the simpleRover example to respond to throttle commands on RC channel 3 (default for Rover) and move backwards as well as forwards.
- Add more detail to the readme doc.

### CODE REVIEW

**Review by TunaLobster — APPROVED** [review]
LGTM

**Comment by srmainwaring** [comment]
Thanks for the review @TunaLobster. In hindsight, I realise that to be consistent with the rest of AP I should have used waf to build the examples rather than cmake.

I have put together an expanded version of the simpleRover example that adapts `SITL::SimRover` to use the SITL-JSON backend, and have found that determining the AP library dependencies using cmake quickly gets out of hand. If you and @IamPete1 think it would be better to have a waf build instead, I'll update this PR with that (and post the full rover example as a follow up).

**Comment by TunaLobster** [comment]
I made this as an example to give to someone that had a sim they had made and wanted to integrate SITL with it. It saved me from having to rewrite the controllers again.

I don't think it needs to match the rest of the building method of ArduPilot because it's not directly integrated with ArduPilot like a vehicle or library. Maybe it would be nice though?

**Comment by srmainwaring** [comment]
Ok, I'll leave this PR as it is and leave the `waf` build for a follow up.

Btw. nice example! They've been very helpful for a project I'm working on.

**Review by tridge — APPROVED** [review]

**Pull request merged**
