### PR TITLE
AP_Motors: add CW_X for Hexa, Octa, OctaQuad

### LINKED ISSUE #13440: AP_Motors: add CW_X for Hexa, Octa, OctaQuad
We've got the [MOTOR_FRAME_TYPE_CW_X](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Motors/AP_Motors_Class.h#L60) implemented for quad frames but we should also implement it for Hexacopter, Octacopters and OctaQuadcopters.

Hexacopters and Octacopters are probably pretty straight forward, for OctaQuadcopters the top motor should be before the lower motor.  I.e. top front-right motor should be 1, bottom front-right should be 2, top back-right should be 3, etc..

We could also do Dodecahexa copters although the existing "X" implementation is the same.  So we could just have the case CW_X: just below the existing case X.

### PR DESCRIPTION
**Pull request by rishabsingh3003**
This PR fixes #13440 
It adds support for CW_X frame type in Hexa, Octa, OctaQuad.

### CODE REVIEW

**Comment by rishabsingh3003** [comment]
@rmackay9 since dodecahexa cwx and x are exactly same, do we need to add this in SITL?
Or is adding CW_X above the X enough? I believe adding this to SITL would be unnecessary but I will add if needed.

**Comment by rmackay9** [comment]
Thanks for this.  I hope to give it a quick test and then merge it tomorrow.

**Comment by andresrcdev** [comment]
Sorry,

I have no much idea about coding, but I was playing arround github and I have seen this issue.
I am not sure if this is no sense, or even if this is the place to say it, sorry if I am completely wrong, but I think that in line 650 and 651, AP_MOTORS_MOT_3 should be AP_MOTORS_MOT_5 and AP_MOTORS_MOT_4 should be AP_MOTORS_MOT_6?

 case MOTOR_FRAME_TYPE_CW_X:
                    add_motor(AP_MOTORS_MOT_1,   30, AP_MOTORS_MATRIX_YAW_FACTOR_CCW, 1);
                    add_motor(AP_MOTORS_MOT_2,   90, AP_MOTORS_MATRIX_YAW_FACTOR_CW,  2);
                    add_motor(AP_MOTORS_MOT_3,  150, AP_MOTORS_MATRIX_YAW_FACTOR_CCW, 3);
                    add_motor(AP_MOTORS_MOT_4, -150, AP_MOTORS_MATRIX_YAW_FACTOR_CW,  4);
                    **add_motor(AP_MOTORS_MOT_3,  -90, AP_MOTORS_MATRIX_YAW_FACTOR_CCW, 5);
                    add_motor(AP_MOTORS_MOT_4,  -30, AP_MOTORS_MATRIX_YAW_FACTOR_CW,  6);**

The same for the other CW_X types

**Comment by rishabsingh3003** [comment]
@andresrcdev you are right! Thank you so much for pointing that out! I can't believe I missed it. Very silly of me. It has been fixed now :)

**Comment by rmackay9** [comment]
Merged, thanks!

special thanks to @andresrcdev.  A detailed code review is super valuable.  thanks!

**Pull request merged**
