### PR TITLE
Leddarone div by zero and cleanup

### PR DESCRIPTION
**Pull request by magicrub**
Ensure no divide by zeros in LeddarOne and clean it up a little

Having a critical 'divide by' value as a class member that could change external to the function is fragile. It was not very obvious that a divide by zero was not possible in the current design, now it's very obvious and safer in case the code changes later.

### CODE REVIEW

**Comment by muramura** [comment]
why delete, variable is setting initial value.
before variable used,  set initial value.
this set is not used unknown value.

if this coding style is national style, japanese coding style is mejor by c(or c++) style.

**Comment by WickedShell** [comment]
@muramura because the initial value that is set is always overwritten before first dereference. Setting it wastes time/isn't needed. Arguably the compiler should fix that for you, but it isn't needed. (i/j could also be declared in the for loops without any problem as well)

**Comment by magicrub** [comment]
yeah, I almost moved the declaration into the loop but kept with the declare-all-at-top scheme. Also, the variables in the class are all set to zero in C+11 so setting them again to zero only wastes program memory and init time

**Comment by muramura** [comment]
@WickedShell , @magicrub thanks comments.
i understand.
My coding style will become more simple .
thanks you.

**Comment by rmackay9** [comment]
Merged, thanks!
@ShingoMatsuura could you test that master still works with the leddarone?  I'm pretty sure it should be fine..

**Comment by ShingoMatsuura** [comment]
l reviewed the PR. I think it will work fine. I am going to test with master.

**Comment by magicrub** [comment]
Thanks Randy!

**Comment by ShingoMatsuura** [comment]
Thanks @magicrub! I checked LeddarOne using master. The PR worked fine. I could confirmed sonarrange value in the status tab of Mission Planner.

**Pull request closed without merging**
