### PR TITLE
AP_HAL: make linux hardware define more readable

### PR DESCRIPTION
**Pull request by tuanngo0898**

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
tuanngo0898 thanks for your patch, but... the chances of this getting conflicts with pending PRs is maybe too high. I don't see a clear benefit of the added indentation, probably because I either jump from one `#if` to another with my editor (`%` shortcut in vim) or I already know what I'm looking for.

I'll let others to chime in if it's only me who doesn't see the benefit.

**Comment by lucasdemarchi** [comment]
Btw, it should be "readable", not "readerble" and the changes should be in the same commit.

**Comment by OXINARF** [comment]
@lucasdemarchi I absolutely see the benefit, looking at this file is a nightmare for me and I know I'm not alone in this, I've discussed it before with other people.

As for PR conflicts, I doubt there are many that would have them and the ones that do should be really easy to fix.

I can fix the commits when merging, but I really want your approval/disapproval first.

**Comment by lucasdemarchi** [comment]
@oxinarf ok, it's fine for me.

**Comment by magicrub** [comment]
This is certainly an improvement, so I approve (although I didn't check if any logic changed). However, a further improvement would be to make a file for each platform and the # ifdef simply does an # include of the file for each platform

**Comment by magicrub** [comment]
Needs a rebase. Need to remove the merge commit. Is everyone still happy with this? Seems to have slipped through the cracks.

**Comment by OXINARF** [comment]
I still want this in, my bad for missing it. I'll try to merge it in the next days.

**Comment by lucasdemarchi** [comment]
@tuanngo0898 can you please revise rather than merge/pull?

**Comment by khancyr** [comment]
closed by https://github.com/ArduPilot/ardupilot/pull/11438

**Pull request closed without merging**
