### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Kametor**
The link gives 404 error. The link I am suggesting is not more than in this page but working.

### CODE REVIEW

**Comment by IamPete1** [comment]
Looks like you might have to be signed into github and/or a AP member to see that list, the list on the web-sight probably also needs a update....

**Review by khancyr — CHANGES_REQUESTED** [review]
yep it doesn't seems to be working. Better remove the full sentence directly as pointing to the wiki doesn't present developers with merge rights.

**Comment by peterbarker** [comment]
@Kametor are you good to remove the entire sentence?

**Comment by Kametor** [comment]
@peterbarker yes, it should be removed

**Review by peterbarker — CHANGES_REQUESTED** [review]
@Kametor to be clear - the link doesn't actually go to the right place - we'd like the entire link removed :-)

**Review by khancyr — APPROVED** [review]

**Comment by Kametor** [comment]
@khancyr after your approvement should I close pull request? I am new in git. also some checks were not succesful it says, is it not a problem?

**Comment by peterbarker** [comment]
I've used git's "fixup" to squish your two commits down into one - thanks for the contribution - merging!

**Pull request merged**
