### PR TITLE
AP_HAL_ChibiOS: support BMP280 on FoxeerF405v2

### PR DESCRIPTION
**Pull request by andyp1per**

### CODE REVIEW

**Comment by peterbarker** [comment]
Tested and working by someone?

**Comment by andyp1per** [comment]
Waiting on foxeer to confirm

**Comment by peterbarker** [comment]
> Waiting on foxeer to confirm

Poke them again?  Probably want to get this into 4.6 sooner rather than later :-)

**Comment by andyp1per** [comment]
Verified by foxeer

**Pull request merged**
