### PR TITLE
Arducopter/AP_Mount: retract camera mount near ground

### PR DESCRIPTION
**Pull request by apmKrauser**
Retract camera mount at low altitude to prevent crash when landing.

While flying around in any flight mode the camera mount will be retracted as soon as the rangefinder (sonar_alt) reports an altitude below mnt_autortrct_h [cm](parameter can be changed in Missionplanner. 0 disables auto retract)

As soon as the altitude gets high enough again (100 cm above mnt_autortrct_h) the camera mount returns to its former position (neutral, rc_targeting, …). At this point it is necessary to exclude all take off and landing modes (I think this only affects Stabilize, Land, maybe RTL). The reason is that the sonar reports a wrong (1-2m to high) altitude eg. when the copter lands on lawn.

Auto retract in general and auto move out can be included/excluded via #defines in Apm_config.h and AP_mount.cpp

### CODE REVIEW

**Comment by magicrub** [comment]
is this still valid?

**Comment by apmKrauser** [comment]
I use it with ArduCopter 3.1.5 on a stretched and overweighted 450 Heli ;-)
Unfortunately I had memory problems with AC 3.2 on my APM 2 Board, hence, I did not really test it with 3.2.

**Comment by lucasdemarchi** [comment]
@rmackay9 I'm assigning this to you since you were commenting on it and giving feedback.

**Comment by R-Lefebvre** [comment]
I'm pretty skeptical about this for the same reason I am about auto-retract-deploy of landing gear.  Knowing our actual altitude above the ground accurately and reliably is not possible without a Lidar sensor, and thus this feature would probably be problematic.

Maybe at a minimum, it would be useful to add a function to retract the mount in Land mode like we do with landing gear? (if this isn't already done).

**Comment by apmKrauser** [comment]
@Randy: What stage has been reached with the elevation library you mentioned above?
I also thought about following algorithm, however it is not a perfect solution at all:

deploy altitude = minimal altitude + extra distance for hysteresis

retract when:
sonar altitude < minimal altitude

deploy when:
sonar altitude > deploy altitude  AND
gps-altitude over home (current_loc.alt - home.alt) > deploy altitude 

Maybe this should only be available for Lidar users.

**Comment by rmackay9** [comment]
@apmKrauser, i've got a work-in-progress branch called terrain3 that seems to work.  I was hoping to get it into Copter-3.4 (the next release) but we're running out of time and I need to finish off some motor library refactoring with Leonard first.

**Comment by lvale** [comment]
Can this closed? #1097 went in already....

**Comment by OXINARF** [comment]
@lvale This is different since it is for automatic retract when near ground. But this is really old, so, unless someone is going to rewrite it, I think it should be closed.

@apmKrauser Are you willing to be rebase this on master?

**Comment by magicrub** [comment]
Being old is not a good enough reason to close an issue.

**Comment by OXINARF** [comment]
This is a PR...

**Comment by magicrub** [comment]
<facepalm>

**Comment by OXINARF** [comment]
I think this would be a good feature to have, but this PR has been opened for more than 2 years without progress. Further it was asked if the OP was willing to rebase it on current master and after one month and a half no answer was given.
For these reasons I'm closing this, but feel free to re-open if it is rebased on master.

**Pull request closed without merging**
