### PR TITLE
Fixed f405-MatekGPS CAN bootloader and storage location

### PR DESCRIPTION
**Pull request by tridge**
The f405-MatekGPS had a typo that meant that it didn't enable CAN for bootloader on an AP_Periph device
Once that is fixed the bootloader becomes more than 16k, which means it doesn't fit in one sector. Unfortunately STORAGE_FLASH_PAGE was set to 1, meaning only 1 sector available.
The fix is to move storage to sectors 2 and 3, leaving 32k for the bootloader
This will reset parameters on boards that are updated, but fixes the long term issue

### CODE REVIEW

**Comment by MallikarjunSE** [comment]
I think I should make these changes on Sierra-F405 board. I took hwdef of this as reference.

**Comment by MallikarjunSE** [comment]
https://github.com/ArduPilot/ardupilot/pull/19232/files
No wonder I was not able to get CAN working on my board from this PR. I had taken the typo line for Bootloader.

**Comment by hendjoshsr71** [comment]
Working! Tested this using a Matek M9N-F4-3100 and a Matek DLVR F405.  (Both share the same hwdef) Must be uploaded using DFU mode via the STM32 CubeProgrammer.

Also caught 3 more failing boards I suspect with the new checks ;)
```bash
Failed builds:
  configure: MambaF405US-I2C
  configure: MambaF405v2
  configure: Pixracer-periph
```

**Review by peterbarker — APPROVED** [review]

**Comment by chobitsfan** [comment]
Hi @tridge I found it seems MatekH743 build is failed with `arm-none-eabi/bin/ld:common.ld:201 cannot move location counter backwards (from 0000000008197e00 to 0000000008180000)` after this commit.

**Pull request merged**
