### PR TITLE
Copter : add LAND_ALT_HIGH parameter

### PR DESCRIPTION
**Pull request by khancyr**
This parameter allow to customize the last step for landing.

### CODE REVIEW

**Comment by Pedals2Paddles** [comment]
This would replace the hard coded 10 meter final landing altitude, and I like that.  I've always thought that was kind of high for my purposes.

I think you can delete the various defines for LAND_START_ALT
https://github.com/ArduPilot/ardupilot/search?utf8=%E2%9C%93&q=LAND_START_ALT&type=

**Comment by khancyr** [comment]
Ok, I remove the define, it isn't usefull anymore to keep it just for the default value.

**Comment by rmackay9** [comment]
Is it LAND_ALT_HIGH or should it be LAND_ALT_LOW?

Other alternatives are LAND_SLOW_ALT and LAND_ALT_SLOW.  but I think LAND_ALT_LOW is perhaps best..

**Comment by khancyr** [comment]
OK I change for LAND_ALT_LOW

**Comment by rmackay9** [comment]
Merged, thanks!

**Pull request closed without merging**
