### PR TITLE
Libraries: change sqrt to safety sqrt

### PR DESCRIPTION
**Pull request by muramura**
I want to change to a safer sqrt method.

### CODE REVIEW

**Comment by Notorious811** [comment]
Can you please describe in brief the significance of this change and how this change will behave differently compared to before?

**Comment by muramura** [comment]
@Notorious811 san. ArduPillot's safe_sqrt returns 0 if the SQRT calculation result is NaN.


https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Math/AP_Math.cpp#L71

**Comment by muramura** [comment]
@khancyr san.  I'll prepare the test results. I'll change, again. Thanks for the comments.

**Comment by WickedShell** [comment]
I'm going to close this. Every proposed change was incorrect. The GPS is known to be positive already, and every other usage is actually getting the return type incorrect (and in location double it's reducing the accuracy in an unfortunate way, and for a lot of the math in location_double if you suddenly returned 0 for the sqrt the entire numeric computation below it blows up and is numerically unstable as well, at which point you aren't really any better then having propagated the NaN, because at least then it would be clear where the error came from.

This also manages to duplicate a lot of what you proposed in #13909 without having addressed the review you received at the time.

**Comment by muramura** [comment]
@WickedShell san. Thanks for the comment. I have lost control due to NaN propagation. I would rather stop being treated as a number for NaN.

I had forgotten my past PRs. I look back to the past before I PR.

**Comment by WickedShell** [comment]
`double` and `float` are always distinct types. The only thing that ArduPilot does weird is by default any floating point number IE `0.26` is supposed to be of type `float` rather then type `double`.

I don't disagree that looking into the NaN stuff isn't worth the time, the point I'm attempting to make is that if you just introduce a 0 into the calculations in location_double for example you will still get wildly erroneous/changing results that will cause a loss of control. You need to look through it further then just introducing a 0, as that can still cause things to blow up later. For what it's worth it looks like the relevant functions in `location_double` are only used in example code right now, so that's not your actual problem.

If you are chasing previous problems then you need to be chasing the path that matches the hardware/control flow you actually have. General improvements are good, but tweaking functions you aren't actually using will not provide you with any improvements in safety.

**Pull request closed without merging**
