### PR TITLE
AP_GPS: reorganize includes

### PR DESCRIPTION
**Pull request by lucasdemarchi**
Due to the way the headers are organized a single change in a
AP_GPS backend would trigger a rebuild for most of the files in the
project. Time could be saved by using ccache (since most of the things
didn't change) but we can do better, i.e.  re-organize
the headers so we don't have to re-build everything.

This makes internal headers internal and then other libraries only
depend on the AP_GPS.h header.

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
@WickedShell could you take a look?  This speeds up incremental build a lot when changing a single file in libraries/AP_GPS/

**Comment by magicrub** [comment]
+1

**Comment by WickedShell** [comment]
LGTM, I admit I was suffering due to this on the recent GPS changes I was working on, so this is quite nice.

**Comment by kwikius** [comment]
Nice work ;)

**Comment by lucasdemarchi** [comment]
Applied, thanks.

**Pull request closed without merging**
