### PR TITLE
Rename get_velocity methods to get_speed

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by khancyr** [comment]
meh ... just get rid of intertial nav is better ....

**Comment by amilcarlucas** [comment]
I do not get the point of this change.

**Comment by peterbarker** [comment]
On Wed, 6 Feb 2019, Amilcar Lucas wrote:

> I do not get the point of this change.

From 
https://www.enotes.com/homework.../whats-difference-between-speed-velocity-296735

"The short answer is that velocity is the speed with a direction, while 
speed does not have a direction. Speed is a scalar quantity—it is the 
magnitude of the velocity. Speed is measured in units of distance divided 
by time (e.g., miles per hour, feet per second, meters per second, etc.)."

**Comment by rmackay9** [comment]
Merged, thanks!  I merged it because it is more correct and it's a safe change and I don't think it will create too many merge conflicts with other PRs.  I know we have one PR to remove inertialnav but I think it's bit rotted a lot by now.

**Pull request merged**
