### PR TITLE
Combine boards with same hardware just different software config

### PR DESCRIPTION
**Pull request by bugobliterator**
This reduces clutter of boards with same hardware but different configs for instance AP_Periph boards based on f103 and f303 and bdshot and periph types, by making there hwdefs be under same main board folder.

Note: Better to be reviewed commit by commit rather than Files changed.

### CODE REVIEW

**Comment by tridge** [comment]
i'm not keen on this. We're not low on directories, and this makes builds more complex. I suspect it will break our firmware server layout and manifest
I just don't see the advantage

**Comment by bugobliterator** [comment]
> i'm not keen on this. We're not low on directories, and this makes builds more complex. I suspect it will break our firmware server layout and manifest
> I just don't see the advantage

Another reason I forgot to mention is, this will remove the remove the need for having multiple copies of default parameters. Maybe its just OCD, but I do think this makes things much more organised and cleaner.
Also can you point me to the Tools that you think might be affected, I will test them. If they break due to this PR, its definitely a no brainer to drop it.

**Comment by peterbarker** [comment]
On Fri, 21 May 2021, Siddharth Bharat Purohit wrote:

> Another reason I forgot to mention is, this will remove the remove the need for having multiple copies of default parameters. Maybe its just OCD, but I do think this makes things much more organised and cleaner.

Notionally we could pre-process the parameters files for #include

**Comment by magicrub** [comment]
The tool is a current GSoC project

**Comment by andyp1per** [comment]
I guess I think the build server might be harder to do without a flat directory structure

**Comment by bugobliterator** [comment]
Closing this PR. I agree its not worth the headache, let's just drop it.

**Pull request closed without merging**
