### PR TITLE
Plane: 4.4.1-beta1 preparation

### PR DESCRIPTION
**Pull request by tridge**
this includes the following changes:
 - plane: fixed nav_roll/nav_pitch when waiting for VTOL takeoff
 - Tools: fixed ccache test for newer ccache version
 - support himark DroneCAN servos
 - support hobbywing DroneCAN ESCs
 - AP_Param: fixed parameter defaults array length handling
 - Tools: allow selection of sdcard storage on custom build server
 - GCS_MAVLink: fixed corruption of FTP reply component ID
 - hwdef: add hwdef for SDMODELH7V1
 - hwdef: qiotek: correct HAL_BATT_MONITOR_DEFAULT define name
 - add 8 bi-directional dshot channels to KakuteH7-Wing
 - Add option to make EKF3 more robust to bad IMU and lagged GPS data
 - AP_HAL_Linux: update Navigator available GPIOs
 - pull RTS lines low on Pixhawk6C
 - added log_file_content scripting binding for aerobatics
 - AP_MotorsUGV: add asymmetry factor for skid-steering

I am open to more backports to 4.4.1. Please open PRs against Plane-4.4

### CODE REVIEW

**Comment by rmackay9** [comment]
I'd like to get this one added which fixes the PWM output for the Navigator autopilot which is critical for AP 4.4 to work on the BlueRobotics Blue boat. https://github.com/ArduPilot/ardupilot/pull/24835.  This has been tested on real hardware.

FYI @Williangalvani

**Comment by tridge** [comment]
> I'd like to get this one added which fixes the PWM output for the Navigator autopilot which is critical for AP 4.4 to work on the BlueRobotics Blue boat.

added

**Comment by vrquaeler** [comment]
Hi Tridge, 
is there any chance to get the commit **hwdef:add bdshot to MatekF765-SE** [https://github.com/ArduPilot/ardupilot/commit/f70c1e96c77669b8b83b36032950423d177c195d](url)
from master added? 
In case of doubt I am fine with a new "MatekF765-SE-bdshot" board definition too. Just to be sure not to break other existing (non-bdshot) builds.
Regards Sascha

**Review by rmackay9 — CHANGES_REQUESTED** [review]
Looks fine although the "Prepare for release 4.4.1-beta1" commit is missing so the version will still appear as "ArduPlane V4.4.0" to users.

**Comment by tridge** [comment]
> Looks fine although the "Prepare for release 4.4.1-beta1" commit is missing so the version will still appear as "ArduPlane V4.4.0" to users.

I usually do that direct to master

**Pull request merged**
