### PR TITLE
Copter: fix mode and fence gps check fail message

### LINKED ISSUE #14048: AP_NavEKF2: report 'EKF2 still initialising" but it is actually "Fence enabled, need 3D Fix"
## Bug report

**Issue details**
EK2_GPS_TYPE=3, GPS_TYPE=0, EK2_GPS_CHECK=0, FENCE_ENABLE=1
Copter will keep showing

> PreArm: EKF2 still initialising

But EKF is actually fine (initialization is completed). It is the fence cause problem. It may cause confusion and mislead users to report EKF problem.

**Version**
V4.0.4-dev, current master

**Platform**
[X] Copter

**Airframe type**
Quadcopter

**Hardware type**
KakuteF7

### PR DESCRIPTION
**Pull request by chobitsfan**
Thank @rmackay9 for [suggestions](https://github.com/ArduPilot/ardupilot/pull/14049#issuecomment-613204621)
This replace #14049, fix #14048

### CODE REVIEW

**Comment by amilcarlucas** [comment]
Is this copter 3.6 relevant?

**Comment by chobitsfan** [comment]
Hi @amilcarlucas I am sorry, but I’m not sure what you mean

**Comment by khancyr** [comment]
he want to check if we need to backport those change on Copter3.6 branch, any idea?

**Comment by amilcarlucas** [comment]
Sorry, I meant copter 4.0 :)

**Comment by chobitsfan** [comment]
Thank ypu @khancyr  @amilcarlucas 

> Sorry, I meant copter 4.0 :)

Yes. I found it in current master

**Comment by peterbarker** [comment]
On Thu, 16 Apr 2020, Amilcar Lucas wrote:

> Is this copter 3.6 relevant?

AFAIK nothing is relevant to 3.6 anymore.  There are many bugs fixed in 
4.0 not fixed in 3.6

**Comment by rmackay9** [comment]
Merged, thanks.  I'll probably leave this enhancement for Copter-4.1.

**Pull request merged**
