### PR TITLE
Allow mavlink PLAY_TUNE support to be compiled out

### PR DESCRIPTION
**Pull request by peterbarker**
This doesn't currently remove it anywhere, but this could make for a build_options.py thing at some stage (~250 bytes).

This saves ~100 bytes regardless by processing the packet in the notify frontend, and using the existing virtual `play_tune` method to get the backends to play the tune (factoring was done to allow scripting to play tunes, this is taking advantage of that factoring).

```
 master: bin/arduplane    961036      2328   128836                963364           19664
    new: bin/arduplane    960944      2328   128832                963272           19760
removed: bin/arduplane    960752      2328   128832                963080           19952
```

where "removed" is with a `--extra-hwdef`:

```
define AP_NOTIFY_MAVLINK_PLAY_TUNE_SUPPORT_ENABLED 0
```

This was tested in SITL (including Valgrind), and on a CubeBlack.  We get tones in SITL and the Cube.

Tones aren't emitted in SITL when using Valgrind (on master or on this PR).  Valgrind has some issues in master and in this PR when playing tones - but they appear to be internal to the SFML library.

### CODE REVIEW

**Comment by muramura** [comment]
The alarm is triggered using PLAY_TUNE from the companion computer application.
I need a way to know that the companion computer app cannot use PLAY_TUNE.
I need a response from FC that the specified MAVLINK message is not supported.

**Comment by peterbarker** [comment]
> The alarm is triggered using PLAY_TUNE from the companion computer application. I need a way to know that the companion computer app cannot use PLAY_TUNE. I need a response from FC that the specified MAVLINK message is not supported.

That's generally a problem for any mavlink message which isn't part of a protocol like `COMMAND_LONG`/`COMMAND_ACK` or `MISSION_COUNT`/`MISSION_ITEM_INT`.

We don't have a general way of indicating a message isn't understood (or accepted) by the autopilot, even if it *is* does have target fields (like `PLAY_TUNE` does).  The same problem is present for things like `SET_POSITION_TARGET` - you never know if the vehicle has accepted your message.  This is the reason we generally suggest people use `COMMAND_LONG` for communicating information that can change the vehicle state - you get confirmation back.  There's no way we wedge `PLAY_TUNE`'s field into a `COMMAND_LONG`, 'though :-)

@muramura I don't think your point here should block this PR being merged.  A lot of people don't have noise-makers on their vehicles and can use that flash space for something else.

@hamishwillee , just for something to muse upon.

**Comment by hamishwillee** [comment]
@peterbarker Thanks. Yes, I have thought about this many times. We even discussed this when we updated to [PLAY_TUNE_V2](https://mavlink.io/en/messages/common.html#PLAY_TUNE_V2) because I argued that if you're going to be able to support multiple tunes then you want a user to be able to query what tune formats are supported. I lost.

There was some thinking that we might use component information to query the set of supported messages - but this has no stakeholder (i.e. no one is willing to work though possible ideas and prototype). The biggest problem with this is that it is effectively "documentation" and can get out of sync. What we really want to do is make sure that some "normal code path with no side effects" is executed.

I hate one-off solutions, but we might explore if we could do something with [MAV_CMD_REQUEST_MESSAGE](https://mavlink.io/en/messages/common.html#MAV_CMD_REQUEST_MESSAGE) - i.e. have this ack and send out some nothing data if it is supported.

**Comment by tridge** [comment]
can be merged when all changes fns are tested

**Comment by hamishwillee** [comment]
Since you're playing with this all ready, any chance of an update to also support PLAY_TUNES_V2? There should be very little code change; the main difference was to allow the future possibility of different formats and easier handling of larger tunes via a single tune buffer. 
It's a (slightly) better message, and it would be good to one day be able to remove the old one.

**Comment by peterbarker** [comment]
> @peterbarker Thanks. Yes, I have thought about this many times. We even discussed this when we updated to 

Perhaps we should consider this with mavlink2.1.  Assuming that's got the incompat-bit which incorporates target system ID/component ID into the base packet structure, there should be scope here for a node to say, "you targetted me with this message but I have no idea what you're talking about" (when combined with the splitting of checksums which I may also be part of that proposal....)

Of course, that still doesn't mean that the vehicle's actually *acting* on the message, which is what I was getting at.  `SET_POSITION_TARGET_LOCAL_NED` won't have effect in most of ArduCopter's modes - and we'll silently ignore it.  If we're using SYSID_ENFORCE we might just ignore it if you're not from a specific system ID.  And the only way for the GCS to tell is lookig at the vehicle's motion and guessing whether you're having an effect (we do *not* mirror the parameters  into `POSITION_TARGET_LOCAL_NED`) from one to the other in ArduPilot).  `SET_POSITION_TARGET_LOCAL_NED` probably needs ` SET_POSITION_TARGET_LOCAL_NED_ACK` :-)

**Comment by peterbarker** [comment]
Tested on Pixhawk1-1M - led control and playtune works when compiled in, not otherwise.

**Comment by hamishwillee** [comment]
We're hijacking this thread a bit, but anyway ....

>> Perhaps we should consider this with mavlink2.1. Assuming that's got the incompat-bit which incorporates target system ID/component ID into the base packet structure, there should be scope here for a node to say, "you targetted me with this message but I have no idea what you're talking about" (when combined with the splitting of checksums which I may also be part of that proposal....)

What I _think_ you are suggesting here is perhaps an incompat bit that, if set, results in a message not executing the code path, but instead responding with an ACK of some kind to tell you that the command was understood - allowing a contextual check of support - ie. right now in this mode on this vehicle I do not know what that message means. 

Possibly also allowing it to be set for commands so that you could run the same kind of check for commands in a standard way.

Is that right? Certainly worth considering. I like that it is contextual, as compared to similar proposals like putting flight stack into a test mode, since it can depend on the current airframe and flight mode etc. But I think either way this might be hard/expensive for flight stacks to actually do in terms of implementing a test path "dunno what you are talking about".

Something based around/like request message command would be better - since you could do it on current mavlink - and I don't see how it would be more costly (though I may misunderstand the proposal).

It might need to be a new message though, since like you say, you don't want things getting SET_POSITION_TARGET_LOCAL_NED while you test for support.

>  SET_POSITION_TARGET_LOCAL_NED probably needs SET_POSITION_TARGET_LOCAL_NED_ACK :-)

It's supposed to be a high rate message, so I think that is impossible :-).

**Pull request merged**
