### PR TITLE
Vehicle override metadata

### PR DESCRIPTION
**Pull request by jaxxzer**
There are a few cases where the metadata for common parameters is not quite applicable to all vehicles using the parameter. This PR allows specifying metadata for individual vehicles on individual metadata fields. This only works when the --vehicle option is used on param_parse.py.

Also see https://github.com/bluerobotics/ardusub/issues/109

### CODE REVIEW

**Comment by magicrub** [comment]
I absolutely LOVE this idea. Lets mark it to discuss at the next dev call.

**Comment by jaxxzer** [comment]
This also works to specify multiple vehicles like `@ArduCopter,ArduPlane`

**Comment by peterbarker** [comment]
I have a similar patch: https://github.com/peterbarker/ardupilot/commit/ce1cd3955f43c71cd2528eb2940d272118b602ef

as part of this PR: https://github.com/ArduPilot/ardupilot/pull/6819

**Comment by jaxxzer** [comment]
Thanks for pointing that out @peterbarker. If I'm not mistaken, I am missing something like [this](https://github.com/ArduPilot/ardupilot/pull/6819/commits/b138c4196f670a52bf82781db3c70be7caa91a21) in this pr.

**Comment by OXINARF** [comment]
So, after I put the idea out, we've got two implementations, I should have written it sooner 😝 

I prefer @peterbarker's implementation, although @jaxxzer's idea of multiple vehicles for a single line is a good addition to it - shouldn't be hard for Peter to add it into his implementation.

@peterbarker Can you extract the param_parse.py (and related) changes from that PR into a new one? I have #6819 open to re-review but I haven't got to it yet and I see that these param stuff is useful right now for more cases.

**Comment by peterbarker** [comment]
@OXINARF https://github.com/ArduPilot/ardupilot/pull/6998

I've flogged the comma-separated-list idea from this PR.

I've also made the same change @jaxxzer made to AP_Arming as part of this PR so they're directly comparable.

**Comment by khancyr** [comment]
This can be close since it was done in #6998

**Comment by jaxxzer** [comment]
Thanks all!

**Pull request closed without merging**
