### PR TITLE
Eliminate send_statustext all and send_statustext_chan

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by magicrub** [comment]
Is this getting the _chan filter mixed up? I'm worried that with this and the previous PRs that we're losing the ability to send to specific MAVLink chans.

**Comment by magicrub** [comment]
if you convince me _chan is still intact, then I'm good with this going in. Sooner the better so it's next to the other big "wall" of commits from yesterday

**Comment by magicrub** [comment]
I see in one of the other associated PRs you mentioned that _chan will be .active or .active() soon.

**Comment by peterbarker** [comment]
On Mon, 10 Jul 2017, Tom Pittenger wrote:

> Is this getting the _chan filter mixed up? I'm worried that with this and
> the previous PRs that we're losing the ability to send to specific MAVLink
> chans.

link->send_text() works to send to a specific channel

Where link is an instance of GCS_MAVLINK.

In fact, this happens all the time when we're responding to a ground 
control station's interrogations.

**Comment by OXINARF** [comment]
Merged, thanks!

**Pull request closed without merging**
