### PR TITLE
Update Parameters.cpp

### PR DESCRIPTION
**Pull request by deverejohn**
Copter: Fix typos in parameter descriptions

### CODE REVIEW

**Comment by magicrub** [comment]
Thanks @deverejohn

**Comment by deverejohn** [comment]
am I supposed to leave open or close?

**Comment by WickedShell** [comment]
Leave it open until it's merged (or closed because it isn't accepted, although that shouldn't be a problem here).

As a general policy we prefer commits to be prefaced with the name of the vehicle or library that is being modified (with one commit per library or vehicle). So for example this commit would probably have a message like "Copter: Fix typos in parameter descriptions". If you want to update it yourself that's fine, otherwise someone will probably just tweak the commit message before merging. (But less work for the people reviewing commits is always appreciated)

Looks very reasonable though, thanks for catching the errors and taking the time to send in a fix!

**Comment by deverejohn** [comment]
thank you, I really appreciate that quick response!  I definitely would rather make it easy for everyone, so I will make sure to format the commit message appropriately.  I have a few more to fix, and Ill try to put as many into one commit as I have time... I'm guessing no one wants 50 commits with a single letter changed:-)   
I hate to ask another question here, but I will -  If I have a suggestion for slightly rewording text for clarity, would you rather have a submission like this or a bug report? 
-trying to help out -john

**Comment by WickedShell** [comment]
Yeah 50 commits of one letter changes is a bit of a burden :) (although if it's between vehicles or libraries each one should be it's own commit). The per vehicle thing isn't a huge problem though as you can submit the commits as a single PR.

Unless you think it's extremely controversial I'd probably just submit it in the same PR and point out in the comment in the PR that you reworded something and please review it. If there is a lot of objection/rewording it can be fixed from there/come in later. The only time I think I'd suggest separating it is if you think it has a change to hold up the rest of the PR of minor changes that should get in before a release or something.

**Comment by magicrub** [comment]
merged https://github.com/ArduPilot/ardupilot/commit/d89b82b69f2e2ac4c4118269e6861268812f87af Thanks @deverejohn !

**Pull request closed without merging**
