### PR TITLE
Copter: AP_Proximity and SF40c driver for object avoidance

### PR DESCRIPTION
**Pull request by rmackay9**
This PR adds support for the Lightware SF40c 360 degree range finder including a simple (GPS based) object avoidance by re-using the AC_Avoidance library (which is also used by the polygon fence).

This PR replaces: https://github.com/ArduPilot/ardupilot/pull/4712

Other various bits of information:

- The datasheet for the range finder can be found here: http://www.lightware.co.za/shop/en/scanning-and-obstacle-detection/45-sf40c-100-m.html
- We use the sensor's "Search Light" feature to find the closest object within 8 sectors (each sector is 45degrees with the 0th sector being straight forward of the copter).
- Each time the AP_Proximity::update function is called (which happens at 100hz) it asks for the closest object in the next sector. On the next iteration it will start looking for a reply and parse it and stick the result into a buffer.  This achieves about a 10hz update rate for a full rotation which is twice the sensor's actual update rate (it spins at 4.5hz)
- AC_Avoidance indirectly accesses the appropriate buffer for the direction the vehicle is flying in and shortens the vector so that the vehicle doesn't hit anything.  This could be improved by instead building a small polygon fence using the closest object (and angle to that object) in each sector.

This has been test flown and the video is here:
https://www.youtube.com/watch?v=BDBSpR1Dw_8

### CODE REVIEW

**Comment by rmackay9** [comment]
@dricketts, thanks for the advice.  I've certainly seen your other PR (or are there two?) and I've been meaning to comment on them.

**Comment by magicrub** [comment]
Is this for v3.5? Please please please let's get v3.4 released ASAP and nut
keep adding features.

**Comment by rmackay9** [comment]
Me adding features is not delaying the release.  I want AC3.4 out as much as the next person.  There's an item from @priseborough related to the EKF that I think we need sorted out (the potential for a vehicle to move as the EKF switches lanes).

**Comment by rmackay9** [comment]
For better or worse, I've merged this in.  @dricketts, I will come back and resolve the merge conflicts with your PRs.

**Pull request closed without merging**
