### PR TITLE
Plane: enforce acro rate limits in aerobatics scripting

### PR DESCRIPTION
**Pull request by Hwurzburg**

### CODE REVIEW

**Comment by kd0aij** [comment]
Those roll/pitch/yaw rate params set the range for the manual control sticks; doesn't seem appropriate to constrain set_target_throttle_rate_rpy to those values since they don't necessarily reflect the actual vehicle capabilities.

**Comment by Hwurzburg** [comment]
I beleive it needs some kind of limiting....otherwise scripts can unknowingly demand 1000deg/s or more rates....perhaps using SMAX..it seems to me that having scripts limited to the same rates pilot inputs in acro mode are, is reasonable

**Comment by kd0aij** [comment]
Perhaps I'm conflating two different issues here: do we (have/need) the capability to command actions like "full up elevator" in ACRO mode?

**Comment by Hwurzburg** [comment]
by "command" do you mean from a script? you can override any servo output with scripts....
this pertains to the nav_script_time mission command that can execute a script during mission waypoints to do aerobatics utilizing direct inputs to the pitch/roll/yaw rate controllers....currently a script can demand any rate (like from a scripts angle controller for knife-edges), even infinity....unobtainable rate demands lead to i term overshoots where none are desired...
the script CAN limit the rate by reading the ACRO rates, or by a fixed value, but it just increases complexity, whihch is growing very complex with these aerobatics routines ......and I see no need for rate controller demands exceeding the maximum rates a pilot would want to command in ACRO mode...this is , in fact, acrobatics..we could pass an argument flag in set_target_throttle_rpy to adhere or not adhere to acro rates, I suppose...

**Comment by kd0aij** [comment]
I suppose that most pattern maneuvers require controlled RPY rates, but aren't there some e.g. snap rolls which simply require full deflection of one or more control surfaces?  If so, then simply not constraining the rate demand might be sufficient to achieve both goals.

**Comment by Hwurzburg** [comment]
I would think a snap would just drive the servos full deflection directly until level is regained...not a controlled rate thing....and stalling moves are yet to be figured out

**Review by tridge — APPROVED** [review]

**Pull request merged**
