### PR TITLE
Try building some artifacts

### PR DESCRIPTION
**Pull request by skorokithakis**

### CODE REVIEW

**Comment by khancyr** [comment]
Please don't use our CI to build your personal work. You have access to GitHub action on your personal github account freely too.

Thanks

**Comment by skorokithakis** [comment]
Ugh, sorry, this wasn't meant to be a PR to the upstream. GitHub UI fail.

**Comment by khancyr** [comment]
About the content. We got a chibios docker builder, it will be simpler

**Comment by skorokithakis** [comment]
Oh nice, thanks! Do you have any pointers about where it is/how to use it? I'm trying to build artifacts automatically.

**Comment by khancyr** [comment]
Here you got some use of the chibios image :https://github.com/ArduPilot/ardupilot/blob/master/.github/workflows/test_chibios.yml . it is the build_ci.sh script but you could just do a `./waf configure --boards=omnibusf4` and `./waf build`
There an example for the artefact : https://github.com/ArduPilot/ardupilot/blob/master/.github/workflows/test_sitl_copter.yml#L128 
Just change the path to the build dir instead of the logs.

**Pull request closed without merging**
