### PR TITLE
Copter: Fenced during automatic flight

### PR DESCRIPTION
**Pull request by muramura**
I lost the multicopter that was flying automatically in Japan.
I want to limit the search area.
I felt that a fence was necessary for automatic flight.

### CODE REVIEW

**Comment by peterbarker** [comment]
Does this mean someone can't fly an auto mission without having a fence?

That doesn't seem a sensible coupling.

I solve the problem you're facing on the GCS side with this MAVProxy module, which just helps to enforce a workflow: https://github.com/ArduPilot/MAVProxy/tree/master/MAVProxy/modules/mavproxy_fieldcheck

Presumably at some stage we will also be able to add pre-arm checks in into the LUA scripting (@WickedShell)

**Comment by muramura** [comment]
@peterbarker san.  Comments Thanks.

I know that automatic flight is possible even if it cannot communicate with telemetry and radio.
I know that when an anomaly is detected during flight in an environment where communication is not possible, the flight change is determined by whether or not the fence failsafe is set.
I feel that when the aircraft is unable to communicate, a fence failsafe is necessary for the distance and altitude.
I feel that fence failsafe makes happiness for ArduPilot users.
When I update the firmware, if there is a LUA script that is always uploaded to SD, the script will be updated.

**Comment by peterbarker** [comment]
@muramura While I agree that flying with a fence is a good idea, I don't think it's a good idea to force people to do it.

Note that we do have other failsafes which users can configure to cover the "can't communicate" scenario you outline - GCS failsafe and RC failsafe, for example.

**Comment by rmackay9** [comment]
Yes, I agree with PeterB that we can't really add this to the main code because it will certainly upset some other users.  We do have Lua script pre-arm checks and failsafes on the to-do list so perhaps when that's done you can add a custom Lua script to add a similar check

**Comment by muramura** [comment]
@peterbarker san , @rmackay9 san.
Comments thanks.
I understand.

I had my friend inadvertently let it fly automatically without setting up failsafe and the aircraft crashed.
I did this PR because I thought there was someone like my friend.

**Pull request closed without merging**
