### PR TITLE
Mah calculated from soc

### PR DESCRIPTION
**Pull request by flytrexguy**

### CODE REVIEW

**Comment by WickedShell** [comment]
This will limit you to relatively large step sizes, (IE if you fly for 20 minutes this may be more then 12 seconds between updates, if you are flying for windows of 2 hours this would be more like a minute and 12 seconds between updates).

I wonder if it's worth retaining the integration, but reset to this point as the current integrated total every time the SOC percentage changes?

**Comment by Naterater** [comment]
Although this is an interesting idea, I'd rather see this only work on boot to provide partially charged batteries a chance to have their capacity estimated (from full). The conversation here outlines some discussion as to why I think along those lines. https://discuss.ardupilot.org/t/battery-monitoring-accuracy-type/49160/8

**Comment by lthall** [comment]
Before I would be happy for this go in I would like to see a link to the background work justifying the maths.

As far as I can see this is just a linear relation between maximum and minimum voltage that is directly related to capacity. The strong nonlinear nature of lithium battery discharge curves will mean that batteries will tend to measure close to

**Comment by lthall** [comment]
This linear method of calculating battery capacity based on maximum and minimum voltage will produce significant errors in capacity because of the non linear response of the battery voltage vs remaining capacity.
Then the voltage used must be the sag compensated voltage or when the aircraft is disarmed.

I would like to see a comparison of measured capacity based on the current usage of an initially full battery vs the value predicted by this method.
It would also be good to provide links to reference material if this is a standard approach.

Finally, why is this only in the CUAV CAN part of the code?

**Comment by peterbarker** [comment]
@flytrexguy did you wish to pursue this?  There are outstanding questions from @lthall

**Pull request closed without merging**
