### PR TITLE
AP_Frsky_Telem: increase stack size for SITL

### PR DESCRIPTION
**Pull request by andyp1per**
The frsky tests will not run on macOS without this

### CODE REVIEW

**Comment by andyp1per** [comment]
@peterbarker without this change the tests will not run on macOS

**Comment by khancyr** [comment]
maybe this is need for all boards ?

**Comment by andyp1per** [comment]
It's certainly needed on WSL as well

**Comment by andyp1per** [comment]
Looks like 2k isn't enough for travis (which is my experience with the FFT stuff). Bumping to 4k

**Comment by andyp1per** [comment]
@peterbarker the current failure is what I see elsewhere as well. Maybe a test issue, but nothing to do with my change. What I don't understand is how you were able to get a clean build as it's clearly broken!

**Comment by andyp1per** [comment]
I think that this fairly conclusively proves that https://github.com/ArduPilot/ardupilot/issues/13240 is real.

**Comment by andyp1per** [comment]
@peterbarker has fixed this a different way

**Pull request closed without merging**
