### PR TITLE
AP_BattMonitor_Bebop: remove fixed battery capacity

### PR DESCRIPTION
**Pull request by OXINARF**
All Parrot boards use this battery monitor but it was forcefully setting the battery capacity to the one in Bebop. This removes that fix and adds the capacity to the Bebop parameters.

### CODE REVIEW

**Comment by rmackay9** [comment]
One small thing is that we actually have two sets of bebop parameters, one for the Bebop1 and another for the Bebop2.  I think the Bebop2 has a larger battery (i.e. more than 1200mAh).

**Comment by OXINARF** [comment]
Yes and the Bebop2 parameters were already setting the correct battery capacity. But the library is overriding the parameter so in reality the Bebop2 always has the 1200 mAh value. This fixes that.

What is just realized is missing is the parameter in Disco, I'll add it later.

**Comment by magicrub** [comment]
Silly question: do the bebop 1 and bebop2 have separate param files?

**Comment by OXINARF** [comment]
@magicrub Yes.

**Comment by jberaud** [comment]
@magicrub They are very similar in terms of electronics and very different in terms of mechanics.

**Comment by magicrub** [comment]
@jberaud I got the answer I was looking for. I would be concerned if they were using the same a params.

**Pull request merged**
