### PR TITLE
ArduCopter: mark get_wp() const

### PR DESCRIPTION
**Pull request by hendjoshsr71**
marks get_wp() const. A drive by on my way to add get_wp() to sub

### CODE REVIEW

**Review by rmackay9 — COMMENTED** [review]
LGTM.  I think it would cause a compile error if any were missed.

**Review by khancyr — APPROVED** [review]

**Comment by peterbarker** [comment]
Oops, conflicting.

**Comment by hendjoshsr71** [comment]
Rebased

**Comment by rmackay9** [comment]
Merged, thanks!

**Pull request merged**
