### PR TITLE
EKF3 cleanups

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by peterbarker** [comment]
I've now flown this without issue.

**Review by khancyr — APPROVED** [review]
seems good.
Worth 500b flash on cubeblack

**Comment by peterbarker** [comment]
I've added a script here:

```
Create a replay log using master branch.
Check out a specified branch, compile and run Replay against replay log
Run check_replay.py over the produced log
```

It passes, so the EKF's output for the Replay autotest is unchanged between this and the master branch.

**Comment by khancyr** [comment]
Interesting, should we autotmated that?

**Comment by peterbarker** [comment]
@khancyr The patch adding the script is here: https://github.com/ArduPilot/ardupilot/pull/15885/commits/5740ffd77467f31df92440369baf8643b8dca859

**Comment by khancyr** [comment]
My point was more to have an autotest getting the lastest replay log from master and running your script on the test !

**Comment by peterbarker** [comment]
@khancyr the problem with your suggestion is that sometimes we *do* want to change the output from the EKF :-)

I guess we could potentially have a file which you *must* touch if you change the output of (e.g.) EKF3 - if the file has changed we assume the output from the EKF has changed and skip the test.  But given that we could change the simulated input to the EKF you might end up having to touch that file even if you haven't changed the EKF itself, which would kind of suck.

**Review by tridge — APPROVED** [review]

**Review by priseborough — APPROVED** [review]

**Pull request merged**
