### PR TITLE
Global: shorten the distinguished name

### PR DESCRIPTION
**Pull request by muramura**
I found the message split.
I shortened the distinguished names.
I was able to see that the message was no longer splitting.

After:
2020/07/26 23:09:12 : PreArm: VisO: roll/pitch diff 165.2 deg (>10)

Before:
2020/07/26 22:52:49 : PreArm: VisualOdom: roll/pitch diff 164.1 deg (>10
2020/07/26 22:52:19 : )

### CODE REVIEW

**Comment by rmackay9** [comment]
@muramura, thanks for this.  Could we make it "VisOdom"?

**Comment by muramura** [comment]
@rmackay9 san. I have changed the identifier to "VisOdom".
I was able to confirm, with this distinguished name, that it does not split.

**Comment by muramura** [comment]
@khancyr san. I've put together a list of changes.

**Comment by rmackay9** [comment]
Merged, thanks!

**Pull request merged**
