### PR TITLE
Tools:  update astyle

### PR DESCRIPTION
**Pull request by khancyr**
rework from https://github.com/ArduPilot/ardupilot/pull/10269 as I don't have right on Azurdrone repo anymore !

### CODE REVIEW

**Comment by khancyr** [comment]
@peterbarker It should be simple to merge !

**Comment by peterbarker** [comment]
This really ought to be three PRs.
 - One to remove uncrustify and reformat.sh
 - One to remove xmlpretty
 - One to change astyle

The first one would probably go in trivially.
The second one would probably go in after a small discussion.
The third one we could spend an entire devcall discussing :-)

Would you mind splitting this up, please?

**Comment by peterbarker** [comment]
This is NOT an improvement IMO:

```
-    for (uint8_t i=0; i<3; i++) {
+    for (uint8_t i = 0; i < 3; i++) {
```

Do you think any of the new options in here would be non-controversial?

**Comment by peterbarker** [comment]
.... AFAICS `add-braces` and `convert-tabs` are pretty much non-controversial.

**Comment by khancyr** [comment]
closing as we will spend to much time discussing this ...

**Comment by RuffaloLavoisier** [comment]
hello, is the Tools/CodeStyle directory working in practice?

**Pull request closed without merging**
