### PR TITLE
Move handling of airspeed calibration up to GCS_Common

### PR DESCRIPTION
**Pull request by peterbarker**
@WickedShell made me do it; see https://github.com/ArduPilot/ardupilot/pull/7953

The relevant patches here are on top of the patches in that other PR.

### CODE REVIEW

**Comment by peterbarker** [comment]
@OXINARF Did it ever depend on Plane having it enabled?  Looks like it only looked at airspeed.enabled().

I removed that check in the GCS_MAVLink conversion as the `calibrate()` function itself does the enabled check for each instance.

**Comment by OXINARF** [comment]
@peterbarker Ah you are right, somehow I read it as `plane.airspeed_enabled()` (notice the underscore instead of the dot). Then, when #7953 is fixed and this one rebased on it, I'll merge it!

**Comment by OXINARF** [comment]
@peterbarker Can you please rebase on top of #7953?

**Comment by peterbarker** [comment]
@OXINARF rebased

**Comment by OXINARF** [comment]
Merged, thanks!

**Pull request merged**
