### PR TITLE
S-Curve prototype code

### PR DESCRIPTION
**Pull request by lthall**
This is the first prototype for the S-curve navigation code. This is a work in progress and is primarily here to get feedback from the devs. I would not suggest flying this using a real aircraft.

Wider discussions on S-Curve navigation and features we should consider can be done here:

https://discuss.ardupilot.org/t/s-curve-progress

This PR contains:
- S-Curve library with the equations to calculate a straight leg
- Updated position controller for Alt-Hold
- Updated 2D and 1D pid loops for improved position control
- Feed forward attitude controller for improved position control performance and improved coordinated turns.

### CODE REVIEW

**Comment by khancyr** [comment]
Very nice ! Thanks you for this long work. I will spend some time to review it

**Comment by lukezhqin** [comment]
Very interested in this work!

**Comment by rmackay9** [comment]
Overall it's looking pretty OK.  A few comments below after a quick read through it:

AP_Math: we should probably stick to lower case, not camel case, also needs more commenting
AC_P_2D: we can pass in measurements as a "const Vector2f& measurement"
AC_PID_2D: really ok to remove the sanity check when setting the filters?
AC_PosControl: need to change the pid objects index in the parameter table
   : there's an if statement (line 352) that doesn't seem to do anything
   : I wonder if we really want to have a set_wp_destination_next() or if perhaps we should have two set_wp_destination calls, the existing one and a new one that accepts a next-wp
AC_AttitudeControl: input_euler_angle_roll_pitch_yaw_euler_rate_yaw() only needs to be virtual if something else is overriding it.
Copter: maybe here too we should have another version of wp_start instead of adding wp_next()

**Comment by rmackay9** [comment]
In AC_PosControl it uses sin() and cos() when it should probably use sinf() and cosf().  I've put a fix at the end of my branch here: https://github.com/rmackay9/rmackay9-ardupilot/commits/lthall-scurve1

Also it looks like we're running out of log message ids.  This isn't your problem but it causes a rebased version of your branch to fail.

**Comment by davidbuzz** [comment]
there also seems to be a number of CI targets that are failing... eg the semaphoreCI 'navio' and 'erlebrain2' builds with
../../ArduPlane/tuning.cpp:158:46: error: ‘class AC_PosControl’ has no member named ‘get_vel_z_p’, so it would be nice if the CI's all passed too.

**Comment by peterbarker** [comment]
I'm going to close this one now that we have a real PR: https://github.com/ArduPilot/ardupilot/pull/15896

Yay!

**Pull request closed without merging**
