### PR TITLE
Maintainer:hiro2233: Grant for APM 2.x branch maintainer.

### PR DESCRIPTION
**Pull request by hiro2233**
hi dev team, i PR this according with discuss in ardupilot webpage http://discuss.ardupilot.org/t/github-closing-out-old-issues-for-deprecated-hardware/11235.

It would be an honor to maintain the APM 2.x branch, i have many improvement that want to push and continue contributting with the code and development. It will help in the unversities to learn and study APM API system too introducing it in TD3 Workshop in Bolivia.

As you see i have finished some interesting development from this branch like my last port to atmega328p https://github.com/hiro2233/ArdupilotMicro and the Andrew scheduler ported for this micro https://github.com/hiro2233/ArdupilotTiny

EDIT3: This is the first official image for APM URUS, any changes to the logo will be welcomed and appreciated. http://pasteboard.co/ThESvwCd.jpg

RESPONSABILITY TO DO LIST AFTER GRANT:
-----------------------------------------
 - Try solve Issues and PR related to this branch APM 2.x (compilation issues at first time).
 - Push improvements for many sensors and new features compatibilty for sensors.
 - New protocol telemetry, portable and easy to integrate on any system.
 - EDIT2: Adding URUS system. That make APM 2.x boards in a BRAIN MODULE for ROBOTICS and AUTOMATIZATION Systems, maybe industrial (Like a PLC ), you will can attach an APM: AUTO_CAPE to enhance the capabilities.

- EDIT1: Adding APM:AUTO_CAPE based on URUS system. That make and convert APM 2.x boards as an UNIVERSAL CAPE for ANY platform Boards system and make compatibilty for lastest APM FIRMWARE VEHICLES RELEASES from master branch to work together.

Thanks in advance.

### CODE REVIEW

**Comment by kwikius** [comment]
Sounds good to me. Are you planning to start from the master-AVR branch? What are your plans about supporting boards other than APM? Are you planning to support all the different vehicles?
I can see an argument for making this specific to avr boards, in which case it can be optimised for them
The only issue is that over time it will diverge from the main branch, but I guess that already happened!

 There are many many APM boards still being made so this is a great move!

**Comment by hiro2233** [comment]
@kwikius  Thank you for your vote.

Yes i'm foccused in master-AVR branch and master branch too, i'm working with both, i thought to build a new board, but with this grant i will push all to  ardupilot project repo and i doesn't make a new board, the purpose is grow up the ardupilot community and make it more strongly and the possibility to introduce and make it be legal the GNU licence in my country Bolivia, it's the purpose that make me moving.

Meanwhile if i have food for live i will support to all vehicle, but first time i will support to Antenna Tracker and Copter because i started with it from 2 years ago and get involved with the code 24/7 from 8 month ago.

Maybe you will use URUS system like a standalone system, because it's will make many IoT (internet of things) devices that you want it's self. The URUS objetive that make APM a universal robotic ecosystem to build and make easily to use and integrate with other things.

Right now i'm porting NuttX to APM 2.x boards too and run APM vehicles system natively on that. I'm thinking that we could run lastest release on it with an extra AVR micro using URUS as a CAPE.
I have succesfully executed applications but internally in a region of the flash micro, i'm trying to run it externally from a SDCard or with a external Flash, but i'm having little troubles with SPI interrupts software only, passing it anyone will can make application based on APM running natively on NuttX in APM 2.x boards.

**Comment by OXINARF** [comment]
> New protocol telemetry, portable and easy to integrate on any system.

What is this?

> Adding URUS system that make and convert APM 2.x boards as an UNIVERSAL CAPE for Linux Boards system and make compatibilty for master branch to work together.

Can you explain what is URUS? Looking at the PR adding it, it is basically empty, just adds new board defines. Are you saying that URUS is a firmware to make APM2 boards be used as a cape? That sounds interesting but has nothing to do with what was asked, which is to maintain the master-AVR branch so that ArduPilot fully runs on legacy boards, not to make them capes.

**Comment by hiro2233** [comment]
> What is this?

A point from TO-DO list. The third on the exactly order.

> Can you explain what is URUS?

Read again the comment Nr. 3 from this conversation and you will understand what do it.

> Are you saying that URUS is a firmware to make APM2 boards be used as a cape?

It does not make clear the statement to you? Yes.

> That sounds interesting but has nothing to do with what was asked, which is to maintain the master-AVR branch so that ArduPilot fully runs on legacy boards, not to make them capes.

Read again the comment Nr. 1 from this conversation and you will understand that exist a TO-DO list with a order task to maintain the master-AVR branch.

**Comment by OXINARF** [comment]
@hiro2233 Please stop with the negative attitude towards me in all channels. I'm not going to tolerate that.

> New protocol telemetry, portable and easy to integrate on any system.

What is this new protocol?

> Read again the comment Nr. 1 from this conversation and you will understand that exist a TO-DO list with a order task to maintain the master-AVR branch.

That TODO list was done by you and that's what I am discussing. If you want to maintain the master-AVR branch you should do it to support the regular ArduPilot running in it, not making the master-AVR a special firmware so that APM2 boards are changed to be just a cape.

**Comment by hiro2233** [comment]
> @hiro2233 Please stop with the negative attitude towards me in all channels. I'm not going to tolerate that.

@OXINARF you offend me with what you're saying. I'm replying to your questions and i don't know why you're feeling that?

> What is this new protocol?
if you study the PASCAL code that i PR when you closed it, maybe you would understand how it will work. It's all clear that you are an admin board here, not a developer.

> That TODO list was done by you and that's what I am discussing. If you want to maintain the master-AVR branch you should do it to support the regular ArduPilot running in it, not making the master-AVR a special firmware so that APM2 boards are changed to be just a cape.

Who are saying or thinking that i will take the control and do anything that i want with the master-AVR?
Or you don't want to make ardupilot project grow up with development?

**Comment by OXINARF** [comment]
> @OXINARF you offend me with what you're saying. I'm replying to your questions and i don't know why you're feeling that?

I offend you? What did I say that could possible be offensive? You started by saying in Gitter that I "disturb the mind to the public" and now you answered my questions with an ironic tone.

> if you study the PASCAL code that i PR when you closed it, maybe you would understand how it will work. It's all clear that you are an admin board here, not a developer.

Your PASCAL code was an implementation of MAVLink, that's not a new protocol. Also, I told you that it was appreciated but it should be in the MAVLink repository, where all implementations reside.
As for being an admin board and not a developer, I'm not even going to dignify that with an answer.

> Who are saying or thinking that i will take the control and do anything that i want with the master-AVR?
Or you don't want to make ardupilot project grow up with development?

Yeah, no one said that, so I'm not sure where that question comes from. You made a TODO list with your plans for the master-AVR branch, I'm discussing it. Why would you have a problem discussing the plans for it?

**Comment by hiro2233** [comment]
@OXINARF Really the developer lose the time discussing with you like me, i told to you to have a good day in Gitter. So, do it. Again, have a good day, Mr. Francisco.

I don't will reply to you because you are evasive with my questions and make me losing the time.

**Comment by guiseco** [comment]
Take it easy guys!

**Comment by khancyr** [comment]
Guys, please don't reply on this PR for 2 days, then read again calmly everything, and made comments. 

For URUS, if I understand correctly, it will be an extension of APM  codebase for general purpose (blink led and what ever). But I don't think it is a good idea. IoT frameworks already exist and APM code should focus on low level control for mobiles robots otherwise for a multi purpose frameworks there is ROS (which is easier that APM to understand)

**Comment by kwikius** [comment]
I really like the sound of a Cape using Ardupilot for IO. I would love to get involved too if I didnt have so many other projects:
http://diydrones.com/profiles/blogs/a-new-use-for-an-apm2-x?xg_source=activity

Work on master-AVR branch does seem problematic. It would basically be a Fork wouldnt it?  I do like the sound of a stripped down Ardupilot though. APM boards suffered from having to accomodate more advanced processors.

If URUS is about finding other uses for APM then that too is a separate project surely, but it sounds great :)

**Comment by OXINARF** [comment]
>@OXINARF Really the developer lose the time discussing with you like me, i told to you to have a good day in Gitter. So, do it. Again, have a good day, Mr. Francisco.

I made my first comment here before I even saw you had talked to me in Gitter. You, on the other hand, responded here (with a negative attitude) after our discussion over there...
And yes, I lose my time over here discussing issues and PRs, that's how the project evolves. If you want to contribute to the project you should be prepared to answer questions.

> I don't will reply to you because you are evasive with my questions and make me losing the time.

I'm evasive? That's funny.

---

> Guys, please don't reply on this PR for 2 days, then read again calmly everything, and made comments.

I don't feel the need for that since I haven't done nothing wrong. As I'm always doing over here, I asked two questions about two points of his plan that I didn't understood. I'm sure I'm not the only one that sees that his response wasn't in a normal tone.

> For URUS, if I understand correctly, it will be an extension of APM codebase for general purpose (blink led and what ever). But I don't think it is a good idea. IoT frameworks already exist and APM code should focus on low level control for mobiles robots otherwise for a multi purpose frameworks there is ROS (which is easier that APM to understand)

Like @kwikius says and from what I understood, URUS is a special firmware to make APM2 be a cape for a RPI. I think that is a good project and I believe it could be in a branch here in ArduPilot (or a different repo within the organization), but not something for the master-AVR branch.

> @OXINARF please don't get made about not being a developper (I don't kown what is mean but whatever) ! Continue your review with your terminator (APM humanoide v42) robot eyes !

Ahahah thanks!

**Comment by hiro2233** [comment]
> I made my first comment here before I even saw you had talked to me in Gitter. You, on the other hand, responded here (with a negative attitude) after our discussion over there...

Really? I don't believe that are you saying, coming from the Mr. Francisco, the senior admin board. Gitter discussion are one thing and this are other thing. Don't mix the things.

> And yes, I lose my time over here discussing issues and PRs, that's how the project evolves. If you want to contribute to the project you should be prepared to answer questions.

I like that you are thinking on it. And you believed that you are prepared to answer questions? you don't have manner and profesional etical mode to talk with the people when arrive an issue or a PR to APM, with your "robotics eyes" and closing like a "terminator", practically you are saying to people: "Goodbye baby". You are eating your same medicine with this, it's not funny and not good for people that want to contribute. I'm telling you like as friend.

For you and general public knowing and clear any doubt:

About the new protocol:
I have a new structure protocol inspired from MAVLINK protocol and it not the same, because are very diferent and this will not replace MAVLINK protocol, i will put it on a Backend Protocol to chose the best one for the user.

About the URUS system:
It will be do more than a "blinki ledi", "beebee sounder", "pipi" or "titi thing", it's will be THE MOUNSTER, THE BIGGER, THE LOVED system for the SINGLE USER that want to build the loved profesional, hobbiest, gamer and industrial robotic and automated system with APM API.

I love APM team and the thing that they are making for the world, and i want to be a part for this purpose, sharing my know how to the people, professionally.

It's all.
Thank you very much for you consideration.
My apologies to make this beautiful PR and turn it on a little personal trouble from my friend, Mr. Francisco.

**Comment by tridge** [comment]
@hiro2233 do NOT be rude to @OXINARF. He puts a huge effort into reviewing patches, a thankless but vital task.
If you want to be involved in ArduPilot development then you must be civil

**Comment by hiro2233** [comment]
@tridge ok, i understand and i will do.
Sorry @OXINAR , i promise you that i will never take this attitude with you. :heart:

**Comment by hiro2233** [comment]
TO DEV TEAM:

i add one more task in the TODO list for the future responsability on master-AVR branch.

- EDIT1: Adding APM:AUTO_CAPE based on URUS system.

APM:AUTO_CAPE will be the orginal APM universal cape for other platforms and APM it's self. APM CAPE with APM Stack Autopilot System will work together.

**Comment by dgrat** [comment]
I think this commit is entirely useless. Wouldn't it be much more useful to make a PR solving one of the listed issues first?

**Comment by hiro2233** [comment]
Dear @dgrat i'm doing it right now, if you see i marked the issue to solve with @hiro2233 on the issues.
The first issue on the TO-DO list it already begin to prove my grant.
People need to know in first instance that i'm the responsible to maintain the code and future way of the branch in collaboration with the community set.

So i'm waiting to. The faith it's primordial and when a developer come with a true faith and see movement like that you do it with this PR https://github.com/ArduPilot/ardupilot/pull/4795, it gives much to think.

Thanks in advance, thank you for your consideration and thank you for your advice.

**Comment by magicrub** [comment]
Agreed, Daniel. A PR like this is earned. You don't get this with promises
of hard work. It's after the hard work has been finished and we like the
work you do. Obtaining maintainership is an honor, not a right.

On Sep 10, 2016 8:06 AM, "Hiroshi Takey" <notifications@github.com> wrote:

Dear @dgrat <https://github.com/dgrat> i'm doing it right now, if you see i
marked the issue to solve with @hiro2233 <https://github.com/hiro2233> on
the issues.
The first issue on the TO-DO list it already begin to prove my grant.
People need to know in first instance that i'm the responsible to maintain
the code and future way of the branch in collaboration with the community
set.

So i'm waiting to. The faith it's primordial and when a developer come with
a true faith and see movement like that you do it with this PR #4795
<https://github.com/ArduPilot/ardupilot/pull/4795>, it gives much to think.

Thanks in advance, thank you for your consideration and thank you for your
advice.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ArduPilot/ardupilot/pull/4794#issuecomment-246116698>,
or mute the thread

**Comment by magicrub** [comment]
Hiro,
Please don't simply tag yourself in a PR. We have no idea what that means.
Please say whatever it is you're trying to say.

**Comment by hiro2233** [comment]
@magicrub I understand, don't worry, it's a tradition on my person to complete first the hard work to earn the honor. I don't know how many time i have to live, so i think to complete it until at next week.

I'm tagging myself to find it in the search box to recognize where is the issue that i will can solve.

**Comment by magicrub** [comment]
Hiro, I look forward to your future apm 2.x pull requests. Until then, this should be closed.

**Comment by magicrub** [comment]
Hiro, just say you'd like it assigned to yourself and we can do that for you.

**Comment by hiro2233** [comment]
@magicrub no problem, i agree. Thank you very much.

**Pull request closed without merging**
