### PR TITLE
AP_BatteryMonitor: remove AP_BattMonitor_MPPT_PacketDigital class

### PR DESCRIPTION
**Pull request by shiv-tyagi**
This solves the issue #19453.
@rmackay9 could you please review it?

### CODE REVIEW

**Review by hendjoshsr71 — APPROVED** [review]
LGTM. 

It shouldn't compile if you missed a spot after removing the whole class.

Note: we should either remove this line from the custom build server too [Link](https://github.com/ArduPilot/CustomBuild/blob/08863c5b62d4a0e43f51a19f2b27066fc24e39bb/app.py#L110)  or add the defines back into the UAV_CAN monitor type where additions were made in the referenced PR..

**Comment by rmackay9** [comment]
Thanks for this.  We should also remove, "20:MPPT" from the BATTx_MONITOR parameter description.

Also I see in AP_CANManager it has, "AP_CANManager::Driver_Type_MPPT_PacketDigital" so I think we need to remove all reference to this as well and the AP_CANManager's parameter description for, "9:PacketDigital".

**Comment by magicrub** [comment]
I think this is ok as long as it has the doc stuff that Randy mentioned. The CAN stuff could be a different PR since it's going to be different commits anyway.

**Comment by rmackay9** [comment]
Merged, thanks!

**Pull request merged**
