### PR TITLE
Rename APMrover2 to Rover

### PR DESCRIPTION
**Pull request by peterbarker**
As discussed around conference-time.

### CODE REVIEW

**Comment by khancyr** [comment]
Haaa I was keeping from doing for some years but let's do it !

**Comment by rishabsingh3003** [comment]
This is a welcomed change! But there are still some minor places I think that are left. For eg, right [here](https://github.com/ArduPilot/ardupilot/blob/04d760d54c11d880a269b6be8374e95c4045288f/APMrover2/Parameters.cpp#L4).  How strict are we being here, in changing the name?

**Comment by peterbarker** [comment]
@rishabsingh3003 A prime example of a useless comment getting out of date IMO....

I was just after the technical aspects in the first case.  But I'll do another pass and see what I find.

**Comment by peterbarker** [comment]
I've changed more things.

**Comment by khancyr** [comment]
maybe change the main directory to ArduRover to be with the other ... but I don't really care

**Comment by jmachuca77** [comment]
Wait a minute, this definitely doesn't follow the naming conventions of the other vehicles. Why are we changing from one non-compliant name to another non-compliant name?

**Comment by peterbarker** [comment]
On Wed, 8 Apr 2020, Pierre Kancir wrote:

> Still one change on azure file, but that isn't blocking

I looked at changing that and decided against it - there's compatability 
code, and I haven't played with Azure stuff much.

Follow-up PR can get it using build.Rover test.Rover etc, I think?


Peter

**Comment by peterbarker** [comment]
On Wed, 8 Apr 2020, Pierre Kancir wrote:

> maybe change the main directory to ArduRover to be with the other ... but I don't really care

I discussed with Randy and he thought "Rover" too :-)

**Comment by peterbarker** [comment]
On Wed, 8 Apr 2020, Jaime Machuca wrote:

> Wait a minute, this definitely doesn't follow the naming conventions of the other vehicles. Why are we changing from one non-compliant name to another
> non-compliant name?

Look at this page: https://ardupilot.org/ardupilot/

How many "ArduRover"s do you count?

How many "Rover"s do you count?

"ArduRover" where there's no context.  "Rover" where there is, and given 
this is in the source tree I suggest there's context.

**Comment by auturgy** [comment]
Valid point about consistency, but my understanding is that the ultimate intent is to also drop “ardu” from the other vehicles, so we’ll have ArduPilot at the top level, then just Plane, Copter, Rover, Sub and AntennaTracker etc below that.

**Comment by magicrub** [comment]
I agree with Jaime, unless what James says will actually happen. Also, this whole thing will likely need a sweep of wiki changes as well

**Comment by rmackay9** [comment]
A horrifyingly big change but the majority of opinions on the dev team during the call was to merge it.  Thanks very much!

**Comment by jmachuca77** [comment]
If we drop Ardu then its a good change... we should drop that everywhere, including the project name.

**Pull request merged**
