### PR TITLE
Rover: 4.1.0-beta1 release notes and version update

### PR DESCRIPTION
**Pull request by rmackay9**
This PR includes the release notes and version update for Rover-4.1.0-beta1 release.  I'm raising it as a PR to allow other developers to review the list and highlight anything I've missed.

All feedback welcome!

### CODE REVIEW

**Comment by andyp1per** [comment]
- Smart Audio
- Bi-directional dshot for RPM telemetry (I think this applies to rover)
- ChibiOS upgrade to 20.3
- RunCam Split 4 and RunCam hybrid support
- OSD Parameter control
- CRSF Parameter control
- CRSF VTX Control
- Spektrum VTX Control
- CRSF passthrough for Yaapu widget
- Many flash logging fixes

**Comment by rishabsingh3003** [comment]
4) Object Avoidance:
Simple Avoidance:
a) Backing away from obstacles supported (**vehicle will maintain margin from obstacles**)
b) Intel RealSense 435/455 camera support (companion computer required). **Other cameras are not tested but should work**.
b) Simple Avoidance change in acceleration is limited (Param: AVOID_ACCEL_MAX). Should make avoidance smoother.
Path Planner:
a) New OA type: Dijkstra with BendyRuler
b) BendyRuler hesitancy improvements 
c) New option while recovering from Object Avoidance (OA_OPTIONS) ( Rover only)

Proximity Library Changes:
a) Can store 3D obstacles
b) New mavlink message: OBSTACLE_DISTANCE_3D
c) New low-pass filter for removing noise from sensors

10) Scripting enhancment:
a) Button, RangeFinder, **Proximity** and RPM sensor support

**Comment by rmackay9** [comment]
This looks like a list of the new autopilots (extracted from firmware.ardupilot.org) although I worry that some of these boards are not really fully tested and verified to be owrking.

BeastF7
--
BeastH7
CUAV-Nora
CUAV-X7
FlywooF745
MambaF405v2
MatekH743
Pix32v5
QioTekZealotF427
R9Pilot
SuccexF4
mRoControlZero
mRoNexus
mRoPixracerPro

**Comment by rmackay9** [comment]
Thanks @andyp1per and @rishabsingh3003.  I think I've now included the changes you've mentioned.

Sometimes I reworded it either because I didn't really understand the change or because I thought the new wording might be easier to understand.

**Comment by andyp1per** [comment]
- Faster gyro sampling rates on F7 and faster (INS_GYRO_RATE)
- Faster dshot rates (SERVO_DSHOT_RATE)
- Custom compass orientation

**Comment by andyp1per** [comment]
Probably should mention @SYS filesystem improvements as per @tridge 's talk

**Comment by rmackay9** [comment]
OK, added in some form although it's hard to get the wording just right unless it comes from the dev directly.  I think I'll merge this latest version after it passes CI.

**Pull request merged**
