### PR TITLE
AP_HAL_SITL: initialize rcout safety state

### PR DESCRIPTION
**Pull request by robertlong13**
This allows BRD_SAFETY_DEFLT=1 to work correctly for SITL.

### CODE REVIEW

**Comment by IamPete1** [comment]
I would have expected a change in `AP_HAL_SITL` why does it need to be in the vehicle?

**Review by khancyr — COMMENTED** [review]
looks wrong. 
you can pass BOARD_SAFETY_ENABLE_DEFAULT 1 to force it . I don't think that using safety button on SITL is convenient things

**Comment by robertlong13** [comment]
> BOARD_SAFETY_ENABLE_DEFAULT

**Comment by robertlong13** [comment]
> looks wrong. you can pass BOARD_SAFETY_ENABLE_DEFAULT 1 to force it . I don't think that using safety button on SITL is convenient things

Nope, that doesn't work. That's exactly what this PR is fixing. The entire BRD_SAFETY_DEFLT parameter is broken in SITL.

As for why I wanted this change:
1. I was trying to reproduce a bug in SITL that I was only able to reproduce on Cube. I was trying to see if safety had anything to do with it (it didn't) but there's no way at all for SITL to start with the safety switch on at boot.
2. Simulation training.

**Comment by robertlong13** [comment]
> I would have expected a change in `AP_HAL_SITL` why does it need to be in the vehicle?

Yeah, looking at this in the cold light of day, I have no idea why I thought this was the best place to do this 😆. Fixed.

**Review by IamPete1 — APPROVED** [review]
LGTM. `BRD_SAFETY_DEFLT` is zero in SITL, so this should have no change in behavior unless you change it.

**Review by tridge — APPROVED** [review]

**Comment by peterbarker** [comment]
I've rebased this on a fix for Rover's RangeFinder test.

I think what's happening is that the vehicle used to move forward a little but the change in safety state stops that happening.

We used to point the rangefinder laterally,so moving forward brought it in-line with the post.

Very strange.

**Pull request merged**
