### PR TITLE
AP_HAL_Linux: Scheduler: added _timer_tick for uartD

### PR DESCRIPTION
**Pull request by smirnov1993**

### CODE REVIEW

**Comment by OXINARF** [comment]
This is a backport of #5348 and should wait until that goes in.

**Comment by lucasdemarchi** [comment]
ArduPlane-release? @OXINARF  @tridge is the branch correct?  We should get a separate branch for the latest release so we don't need to `push -f` when next becomes current, no?

**Comment by magicrub** [comment]
Good catch. This should be on master.

**Comment by lucasdemarchi** [comment]
@magicrub it's already applied on master. See @OXINARF's comment.

This PR is a backport to the release branch so when there's a minor release it includes this fix.  My comment is that we should have a branch per major release, not just one release branch.

**Comment by OXINARF** [comment]
Plane has done it that way and if it works for them it's not worth a fight. With Copter we have decided to make tags and keep branches for the last two major releases.

Anyway, this is in master now and it is a matter of @tridge and @magicrub deciding if they are going to release a 3.7.2 (and so this specific PR should be merged) or if they will just do 3.8.0 out of master and this can be closed.

**Comment by magicrub** [comment]
This doesn't seem critical enough to have a 3.7.2, it'll be straight to 3.8 since we have so many driver/PX4 changes.

**Comment by OXINARF** [comment]
Ok, then let's close this.

**Pull request closed without merging**
