### PR TITLE
Mode semi auto

### PR DESCRIPTION
**Pull request by a2sandres**
* Flight mode developed by Aerospace Scannig Technologies AERSOCANTECH.
 * Programmed by Systems Engineer ANDRES ARDILA SEDANO nick name a2sAndres.
 * This flight mode is based on the Auto and Alt_hold flight modes, which allows manual altitude control. 
 * While entering the height control the aircraft stops.
 * it re-starts the forward advance by giving it pitch input and continuing with the flight plan.
 */

### CODE REVIEW

**Comment by hdtechk** [comment]
Sorry I'm not a dev but even I can tell this need rebased on master mode zigzag is already using number 24

**Comment by a2sandres** [comment]
No matter the numeration, it is really irrelevant to development. I'm interested if you can add the flight mode or if you suggest changes or modifications to improve that mode

**Comment by khancyr** [comment]
Hello,

What was the intend behavior ? 
I think that having an altitude override for the automode will be a good addition, but I don't think your approach is the good one. Having a switch option or parameter to enable the feature in mode_auto should be enough.

You should remove all comments about your name, the git history is enough
Moreover there are trailling files, could you remove them ?

**Comment by a2sandres** [comment]
the intention is to add to this behavior for fumigation drones, and answering your question if I can remove the mentions of my name in the comments and the behavior with parameters is in #9578

**Comment by GlidLov** [comment]
i had used a older industrial flight controller (closed source) which had this exact feature. It's simply awesome and it gives an incredible amount of additional safety while flying

**Comment by OXINARF** [comment]
Closing this as duplicate of #9578

**Comment by a2sandres** [comment]
> i had used a older industrial flight controller (closed source) which had this exact feature. It's simply awesome and it gives an incredible amount of additional safety while flying

hello I would like to know which flight controller you used and had this behavior

**Comment by GlidLov** [comment]
Zerotech Gemini flight controller

**Pull request closed without merging**
