### PR TITLE
AP_common: Add stdio.h when using SITL_printf

### PR DESCRIPTION
**Pull request by patrickelectric**
Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

### CODE REVIEW

**Comment by patrickelectric** [comment]
@OXINARF this macro is used to debug SITL, while using it to perform some tests it was necessary to add stdio.

**Comment by OXINARF** [comment]
Where is it used? I couldn't find any place.

**Comment by patrickelectric** [comment]
Isn't. Is a debug function to use while working over SITL, I am just correcting the implementation.

**Comment by patrickelectric** [comment]
@OXINARF  if you need a better explanation, you may want to talk with @tridge (5f7af390eca76f960bdc4b6fa83a4e33160bf1e1.)

**Comment by OXINARF** [comment]
Ok, so I guess this was added to use whenever someone is developing code and needs to do debug - which is why it isn't used anywhere.

Merged, thanks!

**Pull request merged**
