### PR TITLE
Copter: decrease default ANGLE_MAX, increase WPNAV_SPEED and ACCEL

### PR DESCRIPTION
**Pull request by rmackay9**
This PR tries to set a few important defaults to better values for most users:

- ANGLE_MAX (vehicle's maximum lean angle) is decreased from **45deg** to **30deg** because the vast majority of vehicles cannot maintain altitude at a 45 lean angle.  This will reduce the max horizontal acceleration in Stabilize, AltHold, PosHold from about 9.81m/s/s to 5.6m/s/s which improves safety.  This will **not** reduce the vehicle's maximum speed which most vehicle achieve at about 20deg lean angle.
- WPNAV_SPEED is increased from 5m/s to 10m/s (affects Loiter, RTL, Guided)
- WPNAV_ACCEL is increased from 1m/s/s to 2.5m/s/s (affects Loiter, RTL, Guided)

This PR also includes a minor change to the MANUAL_CONTROL autotest to account for the reduce lean angle

These changes were made in discussion with @lthall.  Independently @peterbarker also mentioned the defaults were too low during recent SCurve testing.

### CODE REVIEW

**Review by IamPete1 — APPROVED** [review]
I think these are sensible changes.

**Comment by bnsgeyer** [comment]
@rmackay9  @lthall  So you are reducing the attitude controller angle max (ANGLE_MAX)?   While this may not reduce the maximum speed, it does reduce maneuverability and it will affect pilot feel.  Do we really have that many users crashing because they did not see their aircraft falling out of the sky at max angle?  Believe me, I am in favor of providing safe default parameters but I'm not convinced this is necessary.  I have mixed feelings about this.

Why not impose angle limits on the position controller and loiter controller through LOIT_ANG_MAX and PSC_ANG_MAX.  I see more issues with the position controller max angle default (0) reverting to the attitude controller max angle.  I've seen traces of heli's going +/- 45 deg auto mode when trying to decel.  

@JoshWelsh  what do you think?

**Comment by lthall** [comment]
Hi Bill,

The default parameters should be thought of as the parameters for the new users or users uninformed in those parts of the code. The goal of these parameters is to give these people a safe but useable combination of parameters that will provide them with a good experience. Existing or more experienced users have probably changed most of these parameters except lean angle max. I suspect most existing users rarely use more than 30 degrees and those that do will quickly increase the lean angle max to 45 degrees again.

**Review by lthall — APPROVED** [review]

**Comment by JoshWelsh** [comment]
> @JoshWelsh what do you think?

I'm on the fence.  

I get the hesitation because of the simple fact that many users _are_ using the default of 45 and having that change to 30 may annoy them because they'll have to go in and change it back to 45.  I'm also sensitive to the safety aspect but I wish we had more data to evaluate than each of us just sharing what we suspect most users are using.  That said, Randy probably reviews more logs than most and if he says the default should go to 30, and that Leonard guy agrees, I'm finding myself having a had time generating an opinion to the contrary.  

We could always do the #ifdef we discussed in Skype for TradHeli, but I don't know how many users will truly notice this unless they're told.  After looking at my log today of my high performance heli, and seeing that it very rarely went over 30 degrees (maxing out at 33) I'd just be very surprised if people noticed.  The few that do can probably just update their parameter and carry on.

**Comment by rmackay9** [comment]
I agree that it is really about what is most useful for the largest number of users.  I think 45 deg is too high for probably 90% of users.  When people ask me to help them tune a vehicle i nearly always recommend they reduce this value to 30 deg or 35deg.

My feeling is that we should try these defaults and see what the user feedback is during beta testing.

**Comment by tridge** [comment]
we may need to update this:
https://github.com/ardupilot/ardupilot/blob/master/ArduPlane/quadplane.cpp#L535

**Comment by rmackay9** [comment]
As discussed on the dev call I've set the defaults for QuadPlane to 500 m/s and 100m/s/s.
image

**Pull request merged**
