### PR TITLE
Pull common modeswitch reading into library

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by OXINARF** [comment]
@peterbarker Should I look at this now or isn't it ready yet?

**Comment by peterbarker** [comment]
On Thu, 24 Aug 2017, Francisco Ferreira wrote:

> @peterbarker Should I look at this now or isn't it ready yet?

Part of this patch set was adding FLTMODE_CH to Copter.  Having done that, 
I decided that's completely the wrong idea - you've already seen the 
RC_Channel change.

My current plan is to make FLTMODE an RC_Channel option.  Right before I 
eliminate RCMap in favour of RC_Channel options :-)

If you want to kill this PR for tidiness reasons, feel free.  The 
mode-switch stuff itself is worth pulling out, but this PR is currently 
contaminated by the FLTMODE_CH stuff.

**Comment by amilcarlucas** [comment]
Purity, very nice :)

**Comment by amilcarlucas** [comment]
@peterbarker would be if you would _make FLTMODE an RC_Channel option_ and closed this PR.

**Comment by khancyr** [comment]
override by https://github.com/ArduPilot/ardupilot/pull/8170 ?

**Comment by peterbarker** [comment]
As @khancyr points out - now done better elsewhere.

**Pull request closed without merging**
