### PR TITLE
[WIP] Enabling optical flow sensor on APMrover2

### PR DESCRIPTION
**Pull request by juancamilog**
Based on instructions by Randy(see https://discuss.ardupilot.org/t/pxflow-ardurover-support/22872/9), I've started work to enable the use of an optical flow sensor (particularly the PX4Flow sensor) with the APMrover2 firmware.

This is work in progress. The current version compiles fine, and we get OPTICAL_FLOW:flow_rate_* and OPTICAL_FLOW:flow_comp_m_* messages with nonzero values (which mean that the flow sensor is working. The current main issues are:

-  The OPTICAL_FLOW:flow_* messages are constantly zero
-  Sonar measurements (ground distance), using the sonar that's onboard the PX4Flow sensor are unavailable
-  We have no idea if the optical flow measurements are actually being used by the state estimator
-  OPTICAL_FLOW messages are only arriving to the GCS if the vehicle is disarmed

I would really appreciate any suggestions on fixing these issues, or if you see that I'm doing something that is obviously wrong.

The purpose of this PR is to enable optical flow measurements on rovers. For slow speeds, with lenses with small focal lengths, and at a reasonable distance form the ground,  optical flow might not be completely useless.

### CODE REVIEW

**Comment by rmackay9** [comment]
.. I think our EKF only consumes the optical flow data if there is a lidar present .. I'd forgotten about this requirement.. this might make getting the px4flow lidar working or we might need to add a parameter to specify the distance from the optical flow sensor to the ground..

**Comment by juancamilog** [comment]
I added the AP_RangeFinder_Fake class, which always reports the ground clearance as the distance measurement. To enable it, you need to set RNGFND_TYPE to 21 (The new fake rangefinder type), RNGFND_ORIENT to 25 (Down) and RNGFND_GNDCLEAR to the approximate distance of the flow sensor to the ground when mounted on the rover. Still needs testing, and I don't expect it to work well if the ground is bumpy, or if the vehicle becomes airborne.

**Comment by juancamilog** [comment]
Following Patrick's suggestion here https://discuss.ardupilot.org/t/pxflow-ardurover-support/22872/17, Iv'e refactored the AP_RangeFinder_Fake class to AP_FixedRange.

**Comment by khancyr** [comment]
This is very old. The idea is good but we don't have much demands for this and it would need a full rewrite as all API have moved. I will close this. Thanks anyway

**Pull request closed without merging**
