### PR TITLE
AP_Scripting: add binding for get_output_pwm

### PR DESCRIPTION
**Pull request by TunaLobster**
Example script also included. Command window from SITL test below. Documentation PR is [here](https://github.com/ArduPilot/ardupilot_wiki/pull/2763).

image

### CODE REVIEW

**Comment by TunaLobster** [comment]
Sounds good. I went the quick and dirty route with the example. Changes made. Changed example script filename to reflect. I hope all of that worked correctly.

**Comment by IamPete1** [comment]
For the notify LEDs we decided using a timer was wrong and that we should just change the param to take control and then change it back after the desired time. 

Not a objection, just a observation, I did a timer based method for the LED too initially

**Comment by TunaLobster** [comment]
This PR is slightly messed up. It's upstream ref is in #14366 with the first 2 commits. I was looking at adding a second method that would translate a ms time input into a under of loops. I'll take a look at the LED one.

**Comment by IamPete1** [comment]
The LED logic would be to change the output to a scripting on using param set then set it and change the param back after the time has elapsed. Not suggesting you change this, just hoping to have some discussion.

**Comment by TunaLobster** [comment]
Removed the servo_get_pwm.lua file.

**Comment by TunaLobster** [comment]
This is good to go from what I can tell. @WickedShell Does this have your approval?

**Pull request merged**
