### PR TITLE
Rover: magically set home when toggling first waypoint in

### PR DESCRIPTION
**Pull request by peterbarker**
Currently the first toggle will put home in rather than the first
waypoint

### CODE REVIEW

**Comment by rmackay9** [comment]
I wonder how there could not be a home position.  If the vehicle has a position estimate it should also have a home location.  My concern is just that we are adding a discrepancy between the first waypoint.

I would say you shouldn't be able to save a waypoint without a position estimate... or perhaps more directly without a home position having been set already.

**Comment by peterbarker** [comment]
As discussed with @rmackay9 a `wp clear` leaves you with zero waypoints - no home.  Changing that to not clear home could easily confuse ground control stations who may be expecting zero waypoints after a clear ('though I guess there's always race conditions against other GCSs...)

**Comment by rmackay9** [comment]
@peterbarker, so I guess you're still going to change this so the mission's auto-magic home is the ahrs home?  i.e. when it adds the first waypoint it won't use the current location but instead the ahrs.home?

**Comment by peterbarker** [comment]
On Fri, 15 Feb 2019, Randy Mackay wrote:

> @peterbarker, so I guess you're still going to change this so the mission's auto-magic home is the ahrs home? i.e. when it adds the first waypoint it
> won't use the current location but instead the ahrs.home?

Weeeellll... this is currently working Just Like Copter :-)

Give-or-take method to get current location.

Perhaps we'd be better off moving this functionality up into common code 
as a first step?

**Comment by rmackay9** [comment]
OK, if it's the same as Copter then it's certainly no worse than what we have now.  So I've merged and perhaps follow-up PRs can make the situation better. thanks!

**Pull request merged**
