### PR TITLE
sim_vehicle.py: handle different return types from uname()

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by peterbarker** [comment]
... sometimes it's a `tuple`, sometimes its a `<class 'platform.uname_result'>`

**Comment by magicrub** [comment]
reading this PR gives me anxiety. Too much magic for such a simple thing! LOL

**Comment by peterbarker** [comment]
Not required after Tom's fix.

**Comment by peterbarker** [comment]
> reading this PR gives me anxiety. Too much magic for such a simple thing! LOL

The key thing I was trying to do there is to avoid breaking things for people where it's working, while getting it to work for the others..

**Pull request closed without merging**
