### PR TITLE
DataFlash: clean up public interface

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
While you're at it, what do you think about
- Rename DataFlash_Class to DataFlash?
- make methods follow other places using lowercase?

Of course this wouldn't be here, i'm just curious since I stumbled on it during my refactors.

**Comment by peterbarker** [comment]
@tridge and I discussed this yesterday.

He's pretty keen to have `DataFlash` renamed to something else, as
"DataFlash" is starting to get a little inaccurate, you might say ;-)

Current theory is that instead of:

```
DataFlash_Class::instance()->Log_Write("CTRL",
                                       "TimeUS,RMSRollP,RMSRollD,RMSPitchP,RMSPitchD,RMSYaw",  
                                       "Qfffff",
                                        AP_HAL::micros64(),
                                       (double)sqrtf(_control_monitor.rms_roll_P),
                                       (double)sqrtf(_control_monitor.rms_roll_D),
                                       (double)sqrtf(_control_monitor.rms_pitch_P),
                                       (double)sqrtf(_control_monitor.rms_pitch_D),
                                       (double)sqrtf(_control_monitor.rms_yaw));
```

We'd have:

```
Log::write("CTRL",
           "TimeUS,RMSRollP,RMSRollD,RMSPitchP,RMSPitchD,RMSYaw",
           "Qfffff",
           AP_HAL::micros64(),
           (double)sqrtf(_control_monitor.rms_roll_P),
           (double)sqrtf(_control_monitor.rms_roll_D),
           (double)sqrtf(_control_monitor.rms_pitch_P),
           (double)sqrtf(_control_monitor.rms_pitch_D),
           (double)sqrtf(_control_monitor.rms_yaw));
```
and

```
Log::write_MSG("Boo");
```


in place of 
```
DataFlash_Class::instance()->Log_Write_MSG("Boo")
```

I don't like the shadowing of `write`, of course, and I'm open to suggestions there....

 - I'm worried about code churn
   - we could potentially introduce `Log::` as the new way of doing it while not churning any code
 - I'm worried that we'll no longer have a convenient "handle" to refer to DataFlash logging.  So what do we call "DataFlash over MAVLink" in general conversation?  (n.b. please don't judge me on what I consider "general conversation" ;-) )

**Comment by lucasdemarchi** [comment]
> He's pretty keen to have DataFlash renamed to something else, as
> "DataFlash" is starting to get a little inaccurate, you might say ;-)

Even better then!

> I'm worried that we'll no longer have a convenient "handle" to refer to DataFlash logging. So what do we call "DataFlash over MAVLink" in general conversation? (n.b. please don't judge me on what I consider "general conversation" ;-) )

Flight stack Log, [black box log](https://en.wikipedia.org/wiki/Flight_recorder), or just log. Any of these "over mavlink" make perfect sense.

If we can agree on how it should be and make the transition fast, I think it can be done without having to introduce a second class, but it's totally up to you.

**Comment by peterbarker** [comment]
On Wed, 30 Aug 2017, Lucas De Marchi wrote:

> Flight stack Log, black box log, or just log. Any of these "over mavlink"
> make perfect sense.

How about "AP_Log" instead of "Log"?  We should really "namespace" it 
anyway, and we *could* say "AP_Log-over-MAVLink"....

**Comment by lucasdemarchi** [comment]
I still prefer Log or
```
namespace ap {
class Log
};
}
```

These uppercase `AP_` prefixes all over are a pain to type. Maybe I'm too tired of my PR (#6779) :-p

**Comment by OXINARF** [comment]
I agree we should move to using an `ap` namespace instead of prefixing everything with `AP_`, but that's a technically decision that should probably be taken in the mailing list.

This PR is simple enough, let's continue discussion on #6867. Merged, thanks!

**Pull request merged**
