### PR TITLE
AP_HAL_SITL: gps correct glitch

### PR DESCRIPTION
**Pull request by khancyr**
Unused from https://github.com/ArduPilot/ardupilot/commit/341b926a430a3fbb5284ac2aac59d14152eb1c46

### CODE REVIEW

**Comment by WickedShell** [comment]
Hm... This is actually bad, 341b926 only added glitching to the ublox SITL GPS's, rather then all of them.

What should actually be done is the glitch parameters from that commit need to be lifted up to this level of the API so that you can glitch any GPS backend, rather then only having glitching as a SITL option. I'd actually rather leave this code in for now, as a reminder to someone to fix it. That commit is a regression however to general SITL GPS testing.

**Comment by khancyr** [comment]
oh ! yes sorry ! I will rework that ! I didn't read enough to see that I remove the glitch for all gps

**Comment by WickedShell** [comment]
@khancyr to be fair, @rmackay9 removed it for all GPS's I just didn't notice it until you sent this in. I think all you need to do is lift the glitch expression out of the _update_gps_ublox(), and make sure it's done before it's passed in.

**Comment by rmackay9** [comment]
@WickedShell, yeah, sorry I could have done my previous commit better.  As part of the dual GPS stuff we needed to add the ability to glitch each GPS individually but I only made it work for the UBlox.

**Comment by khancyr** [comment]
@WickedShell @rmackay9 Ok I work the PR to handle the glitch for all gps and a possible second gps !

**Comment by khancyr** [comment]
rebased and remove initializer list as it is not support by travis right now ... :'(

**Comment by OXINARF** [comment]
@WickedShell Are you OK with this? It looks good to me. We should add a GPS_TYPE2 parameter to SITL and then we can have two different GPS drivers with different glitches for each - this is better than what we have now though.

**Comment by OXINARF** [comment]
Merged, thanks!

**Pull request merged**
