### PR TITLE
Plane: Land with higher airspeed when into-wind

### PR DESCRIPTION
**Pull request by magicrub**
When landing typically you want the lowest airspeed possible. However, gusty winds will cause a dangerous situation to cause a stall when flying slower than normal. This PR increases desired airspeed by half of the current head-wind. This is done in all landing flight stages.

A side effect of this is is more accurate landings when windy where you would normally land short. The landing spot is now more repeatable in variable wind conditions.

### CODE REVIEW

**Comment by WickedShell** [comment]
Can we please do this via landing library? This kind of thing is directly opposed to other landing types, and has to be refactored there anyways.

**Comment by magicrub** [comment]
I considered it but it just didn't really feel right. I'm easily swayed on that though. Same function names?

**Comment by WickedShell** [comment]
Sure, (I think the one helper could easily be folded in at not cost if nothing else is using it but it doesn't bother me either way).

float AP_Landing::get_target_airspeed() which could actually encapsulate the bit of state right before that offset would be perfect! It's even more of a a landing lib clean up :)

**Comment by magicrub** [comment]
Sounds good to me

**Comment by magicrub** [comment]
Updated.

**Pull request merged**
