### PR TITLE
Gobal: pass mavlink_message by const pointer

### PR DESCRIPTION
**Pull request by khancyr**
Not a big change but pass every mavlink message by const pointer !

### CODE REVIEW

**Comment by peterbarker** [comment]
On Mon, 29 Apr 2019, Pierre Kancir wrote:

> Not a big change but pass every mavlink message by const pointer !

I'd rather see passing by const reference if we're changing everything 
everywhere.

**Comment by khancyr** [comment]
I can do that ! That a much bigger change, but surely worth it !

**Comment by khancyr** [comment]
done ! save 10 bytes on each vehicle ^^

**Comment by peterbarker** [comment]
Merged, thanks!

**Pull request merged**
