### PR TITLE
Copter: New filtering PID controller

### PR DESCRIPTION
**Pull request by andyp1per**
New filtering PID controller, AC_PID_Filtered.
Use the filter library for the PID controller allowing 2-pass LPF and notch filters on the D-term.
Add configuration items for the notch filter. Apply biquad and notch to d-term.

Here is the D-term FFT graph for the PID using a single pass LPF
image

Here is the D-term FFT graph for the PID using a biquad LPF
image

Here is the D-term FFT graph for the PID using a biquad LPF and Notch on 180Hz
image

Copter flies smoother with the notch applied.

### CODE REVIEW

**Comment by andyp1per** [comment]
You can see that if I raise the gyro LPF filter frequency to let more noise (but more control) from the gyros into the PID loop, the effect becomes even more pronounced.

image

**Comment by andyp1per** [comment]
BTW Ignore the heading on the graphs, I am using https://github.com/ArduPilot/ardupilot/pull/11422 to produce these and MP only understands gyro/accel data so I have to fake it.

**Comment by guglie** [comment]
This seems very interesting for small copters!

**Comment by andyp1per** [comment]
There is a really good summary in https://www.rcgroups.com/forums/showpost.php?p=39726135&postcount=109 as to where betaflight got to with static filters before they starting incorporating dynamic filters

**Comment by andyp1per** [comment]
I've modified this to use two, separately configurable, PT1 filters instead of a single bi-quad which is what BF 4.0 does. The following graph is with the second filter set at 200Hz (the first set at 110Hz). You can see that the noise is really attenuated nicely and even the notch seems to have more effect.

image

**Comment by tridge** [comment]
hi Andy, @lthall would need to look at the maths of this, but structurally I'd like to suggest that you rework it so that the new options are implemented as an optional object inside AC_PID, with an enable parameter.
The problem with the approach you've taken is it will change the eeprom index numbers of all the PID values for all users, which will break their configs.
If you instead do it like the notch filter is done, where we declare the object inside AC_PID and have an enable parameter (maybe dynamically allocating it when enabled) then it would show up as extra parms on the PID. The parms would be hidden when not enabled.

**Comment by andyp1per** [comment]
Thanks @tridge - @lthall and I are having a long involved discussion on this, so will incorporate your comments if the PR is still appropriate after we have concluded.

**Comment by lthall** [comment]
Thanks for taking such a deep interest in this Andy!!

As we discussed, the notch on the gyro should have the same effect as the notch on the D term except it will also remove the noise from the P and I terms. This is also true for the 2p filter on the gyro. Being done at the full gyro sample rate it is also able to be set to higher frequencies than half the fast loop rate.

I think if you compare the results above to the current code with the notch set at the same frequency you will get almost identical results.

**Comment by lthall** [comment]
I just had another thought that you may be able to answer Andy. Is there anything we should do to make it easier for people to do their own controller designs like you have done here?

**Comment by andyp1per** [comment]
I think some small changes could be made to AC_PID to make it more extensible. I think probably this should be done in conjunction with https://github.com/ArduPilot/ardupilot/pull/11422 as you would want to easily analyse the results.

I also think that reuse of your Filter implementation (which is what a lot of this change is about) makes a lot of sense as that makes it easier to experiment. Not sure if you see any issues with that? Whether changes to the filtering are worth it remains to be seen - we need a moving notch first 🙂

**Comment by andyp1per** [comment]
So more thinking here - if you agreed to my suggestions around Filter reuse and AC_PID extensibility then it would be really easy to introduce build time options targeted at small copters/tinkerers only.

**Comment by andyp1per** [comment]
A lot of things have changed since I created this. I am going to close in favour of https://github.com/ArduPilot/ardupilot/pull/11795 and some of @lthall improvements. May reopen in a different form when things are clearer

**Pull request closed without merging**
