### PR TITLE
HAL_ChibiOS: move to single OSD font on some boards

### PR DESCRIPTION
**Pull request by tridge**
this saves about 12k on these boards. They were also extremely close
to overflowing flash, under 2k on some

Now that we support having an OSD font on the microSD card we can
reduce built in fonts without a large functionality impact

### CODE REVIEW

**Comment by andyp1per** [comment]
My goto options for saving flash on these boards are:
```
define GENERATOR_ENABLED 0
define AC_OAPATHPLANNER_ENABLED 0
define PRECISION_LANDING 0
```

**Comment by tridge** [comment]
> My goto options for saving flash on these boards are:

i've added those in. With those options these boards should be good for quite a while

**Comment by Hwurzburg** [comment]
I think he was saying keep the fonts on those boards that did not have an SD and add those instead of removing fonts?

**Review by Hwurzburg — APPROVED** [review]

**Comment by andyp1per** [comment]
> 
> 
> I think he was saying keep the fonts on those boards that did not have an SD and add those instead of removing fonts?

Right!

**Comment by tridge** [comment]
we discussed on the call, and decided to gain enough space to last a couple of months now

**Pull request merged**
