### PR TITLE
AP_Scripting: add rangefinder status_orient binding

### PR DESCRIPTION
**Pull request by tajisoft**
@WickedShell Following your advice, I felt it was good to add status_orient.  It works fine on REPL.

### CODE REVIEW

**Comment by rmackay9** [comment]
@tajisoft, great, thanks for this.  You've tested it of course?

**Comment by tajisoft** [comment]
@rmackay9 I still tested this using REPL only. I'll try to use real vehicle tomorrow. 
image

**Review by khancyr — APPROVED** [review]
TESTED on SITL and it is working as intend

**Review by IamPete1 — APPROVED** [review]
LGTM

**Review by tridge — APPROVED** [review]

**Pull request merged**
