### PR TITLE
Removed Microseconds from TimeUS field in logger documentaion

### PR DESCRIPTION
**Pull request by rishabsingh3003**
The list was getting quite big.... Thought I should fix it up before we document more of these logs.
Additionally, I have fixed a few typos that my built-in spell checker found.

### CODE REVIEW

**Comment by khancyr** [comment]
hello,

Why this change ? I assume it comes from a discussion somewhere but could you put an explanation ?

**Comment by peterbarker** [comment]
@khancyr Having units in any of these sets a bad precedent.  Units for LogMessages should appear in only one place - in the log message itself.  @amilcarlucas pointed it out on a previous discussion which I thought you were involved in :-)

**Comment by peterbarker** [comment]
Merged - thanks @rishabsingh3003 !

**Comment by khancyr** [comment]
ok, no worries, that was just to have a context.

**Comment by rishabsingh3003** [comment]
Thanks!

**Pull request merged**
