### PR TITLE
Take GPS fix char from different place in GPS packet

### PR DESCRIPTION
**Pull request by peterbarker**
See https://discuss.ardupilot.org/t/bug-in-ap-hott-telem-cpp-copter-4-0-4dev/53939/3

I have no idea if this is correct or not - I don't have the means to test it.

@lvale

### CODE REVIEW

**Comment by WickedShell** [comment]
@peterbarker was this including an extra branch that wasn't supposed to be coming in with this PR?

**Comment by peterbarker** [comment]
@WickedShell Thanks.  Whoops.  Fixed.

**Comment by tridge** [comment]
I've asked Ralf Helbing from Graupner to comment

**Comment by tridge** [comment]
Ralf has confirmed this fix is correct

**Pull request merged**
