### PR TITLE
Copter: fix units and multipliers in PL dataflash logs message

### PR DESCRIPTION
**Pull request by amilcarlucas**
Backport bugfix from master

### CODE REVIEW

**Comment by rmackay9** [comment]
@amilcarlucas, I'm OK to include this in the upcoming Copter-4.0.4 official release if you can test it before then.

**Comment by peterbarker** [comment]
@amilcarlucas really running short of time if you want this in 4.0.4

**Comment by amilcarlucas** [comment]
image
Here is a sceenshot showing all parameters working properly on mission planner.

**Comment by rmackay9** [comment]
Merged, thanks!

**Pull request merged**
