### PR TITLE
Copter: Simulink model and init scripts

### PR DESCRIPTION
**Pull request by fbredeme**
Meant to validate the models generated by the system Identification flight mode

- arducopter.slx: Simulates ArduCopter Stabilize and Althold controller and optional plant model
- sid_pre.m: Loads *.bin files to Matlab structures
- sid_sim_init.m: Loads signals and parameters from Matlab structure into Simulink model

Work sponsored by IAV GmbH.

### CODE REVIEW

**Comment by amilcarlucas** [comment]
Like we promised before, here it is a complete attitude controller simulink model.

Many thanks to Fabian.

**Comment by rmackay9** [comment]
We agreed we should put it in, Tools/simulink

**Comment by amilcarlucas** [comment]
can this be merged now?

**Review by rmackay9 — APPROVED** [review]

**Comment by rmackay9** [comment]
@amilcarlucas, yes, I've just re-run some of the failed jobs in the hope they pass next time.

**Comment by amilcarlucas** [comment]
cygwin still fails :(

**Comment by peterbarker** [comment]
@rmackay9 should we just force this in, given that 4.1 isn't something we can actually reasonably expect to not have bitrotted in terms of testing?  I know I don't pay any attention to it!

**Comment by rmackay9** [comment]
@peterbarker, sure, sounds good to me.  I'm not sure CI actually ever passed for the 4.1 branch

**Comment by amilcarlucas** [comment]
Thanks. We will do a 4.2 PR soon.

**Pull request merged**
