### PR TITLE
AP_RangeFinder: windows build fix by removing support for some finders on non-linux builds

### PR DESCRIPTION
**Pull request by rmackay9**

### CODE REVIEW

**Comment by tridge** [comment]
This would break LightWareI2C support in our autobuild binaries, and for everyone on PX4.
You could do an ifdef based on compiler version instead until the windows build is fixed

**Comment by OXINARF** [comment]
@tridge Does PX4 use this backend? I always though that PX4 only used the *_PX4* backends - there's even a comment in the code: `// I2C sensor types are handled by the PX4Firmware code`

**Comment by tridge** [comment]
yes, PX4 uses this backend for the LightWareI2C device. In the past all I2c drivers on PX4 have been inside PX4Firmware, but Lucas and I would like to start using the in-tree drivers so we have common drivers, which helps with testing.

**Comment by OXINARF** [comment]
>  Lucas and I would like to start using the in-tree drivers so we have common drivers

Yeah, that I knew, but I didn't know there was already a common driver. Well, this means that we need to fix the Windows installer faster.

**Comment by rmackay9** [comment]
Ok, closing this because a new tool chain installer is very close.

**Comment by magicrub** [comment]
confirmed: this fixes my windows build

**Pull request closed without merging**
