### PR TITLE
Support MatekF765-Wing

### PR DESCRIPTION
**Pull request by tridge**
Initial support works, but uart order not worked out properly, and board not yet soldered up for testing

ping @utkinpol

### CODE REVIEW

**Comment by utkinpol** [comment]
so, 2 comments. i think we really need to figure out some solution to UARTs order clause as with as many uarts as here it really gets impossible to comprehend - 
UART_ORDER OTG1 UART7 UART4 USART2 UART8 USART1 USART6 USART3

we really need to do something to make physical order of uart devices to match the serial numeration in the arducopter, as it is just ridiculous now - 7,4,2,8,1,6,3 - it is very cryptic. 

second - i would like to add this PB8 pin as a UART 5 RX  - it may be used for ESC telem input. 

UART_ORDER OTG1 UART7 UART4 USART2 UART8 USART1 USART6 USART3 UART5
...
# UART5
PB8 UART5_TX UART5 NODMA

**Comment by utkinpol** [comment]
Also,
the line 
PB9 TIM4_CH4 TIM4 GPIO(77) ALARM

i thin is supposed to use different timer - TIM11_CH1
PB9 TIM11_CH1 TIM11 GPIO(77) ALARM

**Comment by utkinpol** [comment]
i propose to use this file instead:
https://github.com/utkinpol/ardupilot/blob/PaulAtkin0619/libraries/AP_HAL_ChibiOS/hwdef/MatekF765-Wing/hwdef.dat

Buzzer is moved into LED pin - "PA8 TIM1_CH1 TIM1 GPIO(77) ALARM'. i do not see it used anywhere else, so, hopefully it may work
with the current limitation on the count of serial ports - UARTs order is: 'UART_ORDER OTG1 UART7 USART2 UART8 USART1 USART6 USART3 UART5'
UART 4 is re-purposed into CAN bus - dunno how important that is to have, but, unless we can have more serial ports it is the best way:
PD0 CAN1_RX CAN1
PD1 CAN1_TX CAN1
UART 5 is set fully, using now the awkwardly located pad PB8 - on the other side of the board, and re-purposing BZ- pad into the Tx:
PB8 UART5_RX UART5 NODMA
PB9 UART5_TX UART5 NODMA

Rx UART6 used for RCIN, and UART6 Tx will be used for smart telemetry link into the frsky.

**Comment by tridge** [comment]
> so, 2 comments. i think we really need to figure out some solution to UARTs order clause as with as many uarts as here it really gets impossible to comprehend -

I've fixed the uart order for this board

> second - i would like to add this PB8 pin as a UART 5 RX - it may be used for ESC telem input.

why not uart8 or uart4?

for now I've added it in commented out. We'd need to add uartH to add it

**Comment by utkinpol** [comment]
> > so, 2 comments. i think we really need to figure out some solution to UARTs order clause as with as many uarts as here it really gets impossible to comprehend -
> 
> I've fixed the uart order for this board
> 
> > second - i would like to add this PB8 pin as a UART 5 RX - it may be used for ESC telem input.
> 
> why not uart8 or uart4?
> 
> for now I've added it in commented out. We'd need to add uartH to add it

it makes sense
i am not sue what is the benefit having the 
PB9 BUZZER OUTPUT GPIO(80) LOW
in there, but it can be left for consistency. 
it also would help to add 
PA8 TIM1_CH1 TIM1 GPIO(77) ALARM NODMA

as this is practically needed for an operational tones, and if it would be placed after commented out
# 2812 LED
# PA8, TIM1_CH1

then people would know what to do if they need a LED. 

i still cannot get voltage to show, no matter what, dunno what is the issue.

**Comment by utkinpol** [comment]
Also, PE4 level must be HIGH by default, as Vsw is always at 0v. Needs to be set to LOW somewhere, or we will have no video voltage.

**Comment by utkinpol** [comment]
OK, i just realized that USART6 is not in the list of UARTs - why?

**Comment by tridge** [comment]
uartH is now in master

**Comment by tridge** [comment]
i'm going to merged this now to start getting builds, then we can add new features once merged as a new PR

**Pull request merged**
