### PR TITLE
Plane: Use prev_WP_loc for offset altitude calc, not current.

### PR DESCRIPTION
**Pull request by samuelctabor**
Currently glide slopes are always calculated from the current position to the next waypoint. This can cause non-repeatable glide slopes when disturbances cause the current altitude to differ from the target at the time of glide slope setup.

This changes to using the previous waypoint as the start point of the glide slope. This is unaffected by disturbances. The previous waypoint is used by the horizontal navigation system for crosstrack and so it already initialised appropriately when changing flight mode, next waypoint etc.

This issue is visible in the "MainFlight" test when the target alt goes from 100m to 40m to 28m. Note that there are actually two closely spaced waypoints at 28m, so a descent to 28m followed by flat section is expected. 

**Current**
Aircraft reaches 40m WP when still at ~55m. Glide slope is planned from 55m to 28m. This is then constrained to 40m, making the aircraft fly along at 40m target altitude for most of the mission segment before eventually starting descent.
image

**Proposed w/ defaults**
Glide slope is planned from 40m to 28m. This is less than GLIDE_SLOPE_MIN so the target goes right to 28m.
image

**Proposed w/ glideslope**
This time with GLIDE_SLOPE_MIN set to 1m it plans a glide slope from 40m to 28m over the mission segment.
image

### CODE REVIEW

**Comment by kniuk** [comment]
@samuelctabor it seems reasonable (I had it on my "to do" list also - nice we are noticing same problems) Although I would like to step in shoes of the autor of such code line. Maybe there was some smart thinking behind it, that we are not seeing.

**Comment by kniuk** [comment]
@samuelctabor  have you looked at usage of `set_offset_altitude_location` elsewhere in the code to be sure it will not have adverse impact?

**Comment by samuelctabor** [comment]
@kniuk Likewise. Looks like @tridge touched this code last (as a refactor in 2014) - so he'll be well placed to comment on the logic.

It looks like the only use outside of `setup_glide_slope` is a special case in `set_target_altitude_proportion` when above the original planned slope and the slope is positive. More thought is needed as to the impact on and the best way to handle this case.

**Comment by samuelctabor** [comment]
I've adjusted this to restore the ability to re-plan the path in the case of being above original path by GLIDE_SLOPE_THR and path is climbing.

To test this I added an autotest simulating a mission with a steep descent, followed by a more gradual climb to the original altitude. The aircraft can't follow the steep descent, creating the situation of the aircraft being above the gradual climb. In this situation GLIDE_SLOPE_THR should control whether the slope is re-planned using the current altitude.

If GLIDE_SLOPE_THR = 0, the slope should not be re-planned and so the aircraft should descend until it picks up the original gradual climb.

If GLIDE_SLOPE_THR = 5 (default), the slope should be re-planned and so the aircraft should not descend by any significant height.

The test runs the mission with both settings and checks the altitude deviation is as expected.

GLIDE_SLOPE_THR=5 (slope replanned)
image

GLIDE_SLOPE_THR=0 (no replanning).

image

**Review by tridge — APPROVED** [review]

**Pull request merged**
