### PR TITLE
Spelling fixes (NFC)

### PR DESCRIPTION
**Pull request by amilcarlucas**

### CODE REVIEW

**Comment by IamPete1** [comment]
Log bit mask mostly does not need a reboot.

**Comment by amilcarlucas** [comment]
Some bits require a reboot some others do not. I think its better to be on the safe side.

**Comment by IamPete1** [comment]
Do you know which bits in particular, of the top of my head I can't see any? It might be easier to just fix them?

**Comment by amilcarlucas** [comment]
I removed the LOG_BITMASK changes

**Review by magicrub — APPROVED** [review]

**Comment by rmackay9** [comment]
merged, txs

**Pull request merged**
