### PR TITLE
Add Wind estimation PR units

### PR DESCRIPTION
**Pull request by amilcarlucas**
@peterbarker asked for it, here it is!!!

### CODE REVIEW

**Review by khancyr — APPROVED** [review]
LGTM even it isn't a revert now

**Comment by magicrub** [comment]
Can you give an example when 1/s is preferred?

**Comment by amilcarlucas** [comment]
Well .. This PR is the only place it is preferred. @priseborough prefered to use 1/s instead of Hz :)

**Comment by peterbarker** [comment]
@priseborough could you approve this or say that "Hertz" is as good as "1/s", please?

**Comment by priseborough** [comment]
@magicrub I can give you an example. a control gain that converts an error in m to a velocity demand in m/s.It has unitys of 1/s. Using Hz for am application like that would be misleading.

**Review by priseborough — APPROVED** [review]

**Pull request merged**
