### PR TITLE
Tools: autotest added frsky serial_protocol 4 testing against mavlink

### PR DESCRIPTION
**Pull request by yaapu**
This add testing for all serial_protocol 4 frsky packet types.

EDIT: added protocol 10

### CODE REVIEW

**Comment by yaapu** [comment]
This will fail unless https://github.com/ArduPilot/ardupilot/pull/13846 is applied

**Comment by peterbarker** [comment]
This one's dependent PR was merged, but is failing with: 

```
    FRSkyPassThrough (Test FrSky PassThrough serial output) (Failed to get frsky data) (see /home/travis/build/ArduPilot/buildlogs/ArduPlane-FRSkyPassThrough.txt)
```

Any thoughts?

**Comment by yaapu** [comment]
@peterbarker I rebased and increased the timeout for the passthrough test suite, the issue was some telemetry data took a while to stabilize (like relative altitude) and 10sec where not enough

**Comment by peterbarker** [comment]
Merged, thanks!

**Pull request merged**
