### PR TITLE
autotest: standardize name of param files

### PR DESCRIPTION
**Pull request by lucasdemarchi**
Try to make the various param files to follow similar namings:

- Lowercase the few ones using uppercase
- Use dash to separate name components
- Start with "copter", "plane", "rover", etc instead of the mix we
  had
- Remove "params" from the filename since it's redundant with the
  extension

---

@khancyr @rmackay9 follow up on #4535 

I recommend reviewing with (not sure if github or other tools have a similar thing, this is an alias I have)

```
git diff -U0  --color-words --word-diff-regex="[^[:space:]]|([[:alnum:]]|UTF_8_GUARD)+" -M
```

### CODE REVIEW

**Comment by OXINARF** [comment]
copter-single and copter-coax have the same exact contents, I'm not sure if we should maintain the two or just keep one (not sure what the name would be).

**Comment by rmackay9** [comment]
if you wanted to combine copter-single and copter-coax I'd tend towards naming the file copter-single (or similar).  The underlying motors library for single and coax copters is also almost identical now and we should try and merge them someday.

**Comment by tridge** [comment]
yes, consistent naming is a nice improvement, thanks!

**Comment by lucasdemarchi** [comment]
We currently have a little problem in `Tools/autotest/autotest.py`. It's trying to do things like:

```
results.addfile('ArduPlane defaults', 'default_params/ArduPlane-defaults.parm')
```

I thought that maybe #4535 broke it, but no, it was already broken because those files didn't exist. Any idea what that lines were supposed to do? This grep shows them all:

```
git grep -e "-defaults.parm"
```

**Comment by peterbarker** [comment]
On Thu, 4 Aug 2016, Lucas De Marchi wrote:

> 
> We currently have a little problem in Tools/autotest/autotest.py. It's
> trying to do things like:
> 
> results.addfile('ArduPlane defaults', 'default_params/ArduPlane-defaults.par
> m')
> 
> I thought that maybe #4535 broke it, but no, it was already broken because
> those files didn't exist. Any idea what that lines were supposed to do? This
> grep shows them all:
> 
> git grep -e "-defaults.parm"

Those are dumped out by the get_default_params() routine, triggered by 
steps defaults.ArduPlane and friends.

Yours,
-- 
Peter Barker                          |   Programmer,Sysadmin,Geek.
pbarker@barker.dropbear.id.au	      |   You need a bigger hammer.
:: It's a hack! Expect underscores! - Nigel Williams

**Comment by lucasdemarchi** [comment]
> Those are dumped out by the get_default_params() routine, triggered by
> steps defaults.ArduPlane and friends.

ah... ok, thanks.

**Comment by khancyr** [comment]
@lucasdemarchi.... my bad. I had to have those files when I change directory. I think I need to be revert, since those files are only use in autotest. (maybe rename it as -autotest.parm ?)

**Comment by lucasdemarchi** [comment]
> if you wanted to combine copter-single and copter-coax I'd tend towards naming the file copter-single (or similar).

I'm not doing it on this PR though... I think we can postpone until single and coax are combined in the motor library.

> @lucasdemarchi.... my bad. I had to have those files when I change directory. I think I need to be revert, since those files are only use in autotest. (maybe rename it as -autotest.parm ?)

you didn't break it... this is **written** by autotest, not read, as @peterbarker clarified above.

I also tried doing a .parm -> .param renaming but it was not possible.... we have several places in the code using .parm, although real vehicles use .param in `Tools/Frame_params`. Example in `libraries/AP_HAL/AP_HAL_Boards.h`

**Comment by lucasdemarchi** [comment]
Applied.

**Pull request closed without merging**
