### PR TITLE
add mazzy star drone hwdef

### PR DESCRIPTION
**Pull request by Huibean**
add hardware define for Mazzy Star Drone

### CODE REVIEW

**Comment by khancyr** [comment]
Hello,

Could you append `AP_HAL_ChibiOS:` at the start of the commit message ?

**Comment by Huibean** [comment]
Hi @khancyr I have made the change

**Comment by Huibean** [comment]
@khancyr I have change to pr into master branch https://github.com/ArduPilot/ardupilot/pull/14696

**Comment by khancyr** [comment]
Cool! I didn't even notice that.... That looks good now

**Pull request closed without merging**
