### PR TITLE
Autotest gripper

### PR DESCRIPTION
**Pull request by khancyr**
make gripper sim more realistic.
add some parameter to reflect real material and chose at which pwm it open and which it close

### CODE REVIEW

**Comment by khancyr** [comment]
tested on SITL with https://github.com/khancyr/ardupilot/tree/precland-autotest

**Comment by rmackay9** [comment]
@peterbarker, you're OK with this?

**Comment by rmackay9** [comment]
By the way, I personally prefer if we don't use send_text in cases where things are working fine.  If you guys really want the status text in there when the gripper opens and closes then that's OK.. but personally I don't think we should have it.

**Comment by khancyr** [comment]
@rmackay9, I agree that we shouldn't have much status text, that's why I restrain text feedback on SITL only for the test. In fact, it doesn't even work... as we cannot catch those....
Anyway, this was just to have a feedback. What we really need is a new mavlink message and implement a feedback catching mechanism, because here we assume that we send the command and the gripper action always goes well...

**Comment by peterbarker** [comment]
Merged, thanks!

We should give consideration to how to present data like landing-gear status, gripper-status, sprayer-status etc etc to the GCS.

**Pull request merged**
