### PR TITLE
AP_GPS: fixed moving baseline Z check for attitude lag (for 4.0)

### PR DESCRIPTION
**Pull request by tridge**
4.0 version of https://github.com/ArduPilot/ardupilot/pull/17182

### CODE REVIEW

**Comment by WickedShell** [comment]
We are doing release notes for 4.1, why are we still PR'ing 4.0?

**Comment by lthall** [comment]
Because a really nice bloke is using 4.0 on an industrial aircraft that has had a problem that this will hopefully fix.

**Comment by tridge** [comment]
> We are doing release notes for 4.1, why are we still PR'ing 4.0?

I tend to put in PRs for 4.0 things even though I don't expect them to be merged/released, as it is a convenient way to hold 4.0 patches for active users. It isn't just Leonard that is affected by this problem. The sorts of users that are using moving baseline tend to be the ones that will wait quite a while to go to 4.1.

**Comment by WickedShell** [comment]
> I tend to put in PRs for 4.0 things even though I don't expect them to be merged/released, as it is a convenient way to hold 4.0 patches for active users. It isn't just Leonard that is affected by this problem. The sorts of users that are using moving baseline tend to be the ones that will wait quite a while to go to 4.1.

My concern with this is two fold:
  - It starts to hint to people we will do another 4.0 release for them
  - It's taking up space on the list of PR's to be reviewed. I went looking for things to review the other night and there is a surprising amount of open PR's to 4.0 that we have no intention of bringing in, they are just lingering. I don't mind seeing them opened then closed, and tagged as such, but I think leaving them lingering as open is actually an issue.

**Comment by tridge** [comment]
> It starts to hint to people we will do another 4.0 release for them

well, we might still do one. If we find a critical issue, then we could include a few other bug fixes

I could instead close and add to 4.0 backports project. I'll do that

**Comment by lthall** [comment]
This fixed the problem!

**Pull request closed without merging**
