### PR TITLE
AP_HAL_ChibiOS: add support for NucleoH755 board

### PR DESCRIPTION
**Pull request by radiohound**
Add support files for STM NucleoH755 board

### CODE REVIEW

**Review by nkruzan — COMMENTED** [review]
I took some time to review and see some differences in datasheet for stm32h757 compared to stm32h757xx.py, but will chalk them up to errors in datasheet...SRAM2 size, PB14&PB15 AF2, PJ2 AF13...

As for this pr is there reason you did not include as is in stm32h757xx.py?
`    'DEFINES' : {
        'HAL_HAVE_HARDWARE_DOUBLE' : '1',
        'STM32H7' : '1',
    }`

**Comment by radiohound** [comment]
Thank you nkruzan, there do seem to be some discrepancies in stm32h757xx.py, like the one you mention on PB14 (lack of USART3_DE). I will look deeper into it, and compare it to the stm32h757 and stm32h755 data sheets.

As for the defines you show, I accidentally used a stale version of stm32757xx.py without the change. I will update that. 
Thanks again.

**Comment by nkruzan** [comment]
If stm32h755xx.py and stm32h757xx.py will end up being identical, maybe the better route is to rename stm32h757xx.py to stm32h75xxx.py and fix all hwdef that reference it (there appear to be only 6 files, with only 2 of them being partner products). pinging @tridge and @bugobliterator for comments

@radiohound What sort of testing has been done with this PR?

**Comment by radiohound** [comment]
There is one difference between the pin functions  of h755 and h757 that applies to a few different pins. There is a DSIHOST_TE that has to do with communication to graphic displays that the h755 has.

So far, the board is currently communicating with a BMP388 and ICM20948 and connecting to MP, indicator lights are working. MP shows compass, altitude, pitch and roll working correctly.

**Comment by radiohound** [comment]
Did some more testing, and now have RCIN working with CRSFv2 telemetry working. Also have GPS working as well. Since the xx.py files look so similar, I like your idea to rename stm32h757xx.py to stm32h75xxx.py and change related files. It does seem like stm32h757xx.py needs to be changed to match the stm32h757 data sheet. I have proposed changes in pull request #20297.

**Comment by nkruzan** [comment]
Hello, you will need to squash your commits as appropriate, here is a link to guide on wiki that explains more. https://ardupilot.org/dev/docs/submitting-patches-back-to-master.html#submitting-patches-back-to-master

**Review by nkruzan — CHANGES_REQUESTED** [review]
Hello, you will need to squash your commits as appropriate, here is a link to guide on wiki that explains more. https://ardupilot.org/dev/docs/submitting-patches-back-to-master.html#submitting-patches-back-to-master

**Comment by radiohound** [comment]
Thank you for the help nkruzan. I am having trouble accomplishing this, so I am going to close this pull request and start over.

**Comment by nkruzan** [comment]
I use GitKraken it makes things easier for me

**Pull request closed without merging**
