### PR TITLE
Tools: Add nnaka to git test

### PR DESCRIPTION
**Pull request by nnaka**
Adding name to list to test forking / PR workflow for ardupilot

### CODE REVIEW

**Comment by rmackay9** [comment]
Looking pretty good.  If possible could you change the commit title to be "Tools: Add nnaka to git test"?

**Comment by nnaka** [comment]
@rmackay9  thanks for the feedback; updated the PR title as you suggested.

**Comment by nnaka** [comment]
@rmackay9 thank you for the feedback; I updated the commit title as you kindly suggested.
I went ahead and updated the PR title as well to match that.

**Comment by rmackay9** [comment]
Merged, thanks!

**Pull request merged**
