### PR TITLE
AP_RangeFinder: look for Lightware I2C lidar on both I2C buses

### PR DESCRIPTION
**Pull request by rmackay9**
This PR adds support for the Lightware I2C lidar to be found on the second I2C bus just as it is for the PulsedLight lidar.  This should resolve a number of requests that have come from Copter-3.5 users who are using the Cube flight controller (aka Pixhawk2).

I wasn't sure about removing the AP_HAL definitions especially the two that have "2" as their definition.  Presumably this means the lightware lidar would stop working on these boards?

### CODE REVIEW

**Comment by magicrub** [comment]
This looks fine, but we should really switch all of the types of calls to for loops for all i2c buses.

**Comment by magicrub** [comment]
What about the Linux boards that use i2c bus 2?

**Comment by OXINARF** [comment]
I think the best path until we have solved #6265 is to try to detect the backend with the macro, if not found do the thing with the 0 and 1 buses.

**Comment by rmackay9** [comment]
OK, i'm going to close this then.  txs for the review anyway!

**Pull request closed without merging**
