### PR TITLE
AP_Motors: Change to pass-through

### PR DESCRIPTION
**Pull request by muramura**
With pass-through, processing is combined into one.

### CODE REVIEW

**Comment by IamPete1** [comment]
you could do the same clean up in `AP_MotorsSingle` too.

**Comment by peterbarker** [comment]
This enumeration is specfied as an array offset, so I think this subtraction is actually reasonable.

```
Board                    AP_Periph  blimp  bootloader  copter  heli  iofirmware  plane  rover  sub
CubeOrange-periph-heavy  *
Durandal                            *      *           -56     *                 *      *      *
Hitec-Airspeed           *
KakuteH7-bdshot                     *      *           -64     *                 *      *      *
MatekF405                           *      *           -64     *                 *      *      *
Pixhawk1-1M-bdshot                  *                  -64     *                 *      *      *
f103-QiotekPeriph        *
f303-Universal           *
iomcu                                                                *
revo-mini                           *      *           -56     *                 *      *      *
skyviper-v2450                                         -64
```

**Review by peterbarker — APPROVED** [review]

**Comment by rmackay9** [comment]
It looks OK but it should be tested I think.  So confirmation that someone has tried to fly a coax copter in SITL or on a real vehicle.

**Comment by peterbarker** [comment]
> It looks OK but it should be tested I think. So confirmation that someone has tried to fly a coax copter in SITL or on a real vehicle.

From the FlyEachFrame autotest when flying the COAX frame:
image

**Pull request merged**
