### PR TITLE
AP_ExternalAHRS: Fix Build Option for InertialLabs

### PR DESCRIPTION
**Pull request by joshanne**
Opened after fixing some other build_options/extract_features in https://github.com/ArduPilot/ardupilot/pull/27796

Extraction of the feature generates `INERTIALLABS` but the define uses `INERTIAL_LABS`.

This fixes it so the feature matches the build option.

### CODE REVIEW

**Comment by joshanne** [comment]
@peterbarker following up from last weeks discussions.

**Comment by joshanne** [comment]
Looks like FenceFloorEnabledLanding is flapping.

**Review by peterbarker — APPROVED** [review]
LGTM.

Note that I have https://github.com/ArduPilot/ardupilot/pull/27777 on the way which, while a bit of a monster, will catch more of these issues in CI.

**Comment by peterbarker** [comment]
Merged, thanks!

**Pull request merged**
