### PR TITLE
Autotest: Add Eli Field location.

### PR DESCRIPTION
**Pull request by R-Lefebvre**
Matches up reasonably well with RealFlight.

### CODE REVIEW

**Comment by peterbarker** [comment]
@R-Lefebvre are you still interested in getting this one in?

**Comment by magicrub** [comment]
needs a rebase, plus the 120m altitude looks wrong. Slapping in 40.059488,-88.551314 to https://www.freemaptools.com/elevation-finder.htm says it's 204m

**Comment by magicrub** [comment]
@R-Lefebvre  Also, a heading of zero would point it straight up instead of along the runway path. Would you like some help fixing this?

**Comment by tridge** [comment]
replaced with #14827

**Pull request closed without merging**
