### PR TITLE
Run prearm checks on all vehicles @1Hz, displaying @0.0333Hz

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by peterbarker** [comment]
I've tested Copter, Plane, Rover, Sub and Blimp in SITL.  All run the prearms periodically.

**Comment by peterbarker** [comment]
@bnsgeyer this PR now contains a fix for Dual helis where the initialised_ok boolean was being unset at 1Hz from Copter's one_hz_loop.

**Comment by bnsgeyer** [comment]
@peterbarker Great.  Thanks!   Would this be an issue for heli quad as well.  I'm not familiar with what  you are doing here.

**Comment by peterbarker** [comment]
> @peterbarker Great. Thanks! Would this be an issue for heli quad as well. I'm not familiar with what you are doing here.

Yes, this would be an issue for HeliQuad and Heli Single.  I was hoping to not update those as we don't have any model in SITL to test against - and I certainly don't have those frames.  I'd be make the change blind, basically.

**Comment by peterbarker** [comment]
@bnsgeyer added a patch in here for HeliQuad.

Why `MotorsHeli_Single` isn't `MotorsHeli_Trad` I don't know...

**Comment by bnsgeyer** [comment]
> Why `MotorsHeli_Single` isn't `MotorsHeli_Trad` I don't know...

@peterbarker I'm not sure why that doesn't make sense you.  But MotorsHeli_Single is the traditional helicopter frame.  So is there something additional that needs to be done to cover this case for this PR.   Again I have no idea what this PR does and how it affects my frames.  Maybe we can get on discord voice later today (tomorrow for you) and discuss.

**Comment by peterbarker** [comment]
> > Why `MotorsHeli_Single` isn't `MotorsHeli_Trad` I don't know...
> 
> @peterbarker I'm not sure why that doesn't make sense you. But MotorsHeli_Single is the traditional helicopter frame. So is there something additional that needs to be done to cover this case for this PR. Again I have no idea what this PR does and how it affects my frames. Maybe we can get on discord voice later today (tomorrow for you) and discuss.

Ah, sorry.  The whole "Heli Single" thing - I always think of a "singlecopter" - but with a collective....

**Comment by peterbarker** [comment]
> @peterbarker I'm not sure why that doesn't make sense you. But MotorsHeli_Single is the traditional helicopter frame. So is there something additional that needs to be done to cover this case for this PR. Again I have no idea what this PR does and how it affects my frames. Maybe we can get on discord voice later today (tomorrow for you) and discuss.

I think this PR is complete now.  I could create a separate PR for the multicopter fixes.

The bug is that once per second (while disarmed) the motors library for Dual and Quad will briefly go into the "uninitialised" state:
 - Copter sets the `frame_class_and_type` into the motors library from the parameters.  That's in the `one_hz_loop` when we're not armed.
 - that method is only implemented by the Heli Motors base class and is this:  `set_initialised_ok(frame_class == MOTOR_FRAME_HELI);`, so for any frame other than the tradheli frame this will set initialised to false.
 - `initialise_outputs` is called continuously in the motors library while disarmed and will unconditionally set initialised to true in the backends so most people won't notice

My PR's goal here was to move the arming update function (responsible for periodically running the prearm checks) up to AP_Vehicle, instead of having separate implementations in all the vehicles.  This moved the call to the arming library into the scheduler, and it is now called in the same loop as the call to update the frame class-and-type - but afterwards.  So the arming checks are run directly after the initialised-ok flag being set to false, and thus the prearm checks fail when checking the motors library looks OK.  The call to `init_outputs` hasn't been made to reset the flag to true before the arming checks are made.

The fix is to jot down the frame and class and then each backend makes sure the currently-configured-in-parameters backend is them.  Most of the AP_Motors backends do it this way.

**Comment by bnsgeyer** [comment]
@peterbarker thanks for the explanation!

**Review by rmackay9 — APPROVED** [review]

**Comment by bnsgeyer** [comment]
@peterbarker I tested quadheli with your PR branch.  I had to load my parameters for this frame and then reboot because the frame_class needed be changed for a quadheli.  Once it rebooted I received a Pre-arm good message.  I then set the function for one of the motors to 0.  THere was no prearm message and it let me arm successfully.  The refreshed params show the servo function to still be 0.  I rebooted the controller and checked the servo function and it had been reset to the default value.
Based off of what  you explained in the devcall, it appears to be working for initialization on boot but may not catch a bad servo function if changed while after the boot.

**Comment by peterbarker** [comment]
Thanks @bnsgeyer - sounds like we should merge this now, then?

**Comment by bnsgeyer** [comment]
@peterbarker sounds like it behaves as you expected. So I’m good with merging it.  Thanks

**Comment by rmackay9** [comment]
Merged, thanks!

**Pull request merged**
