### PR TITLE
Rover: do not set_control_channels at all when armed

### PR DESCRIPTION
**Pull request by peterbarker**
Resetting these parameters while the vehicle is active can cause
null-pointer references in flight.

This limits it to only making changes when the vehicle is disarmed.

### CODE REVIEW

**Comment by rmackay9** [comment]
This definitely makes sense but I wonder what happens if arming is not required.. does it still run this at least once so rcmap works?

**Comment by peterbarker** [comment]
@rmackay9 Right you are.  This needs testing.

**Comment by peterbarker** [comment]
I've changed this up so that we do `set_control_channels` unconditionally on boot.

I tested this in SITL by puttin a decimated gcs().send_text to show me when it was called.

```
--- a/APMrover2/radio.cpp
+++ b/APMrover2/radio.cpp
@@ -15,6 +15,12 @@ void Rover::update_control_channels()
 
 void Rover::set_control_channels(void)
 {
+    uint32_t last_print = 0;
+    const uint32_t now = AP_HAL::millis();
+    if (now - last_print > 1000) {
+        last_print= now;
+        gcs().send_text(MAV_SEVERITY_INFO, "set_control_channels");
+    }
     // check change on RCMAP
     channel_steer    = rc().channel(rcmap.roll()-1);
     channel_throttle = rc().channel(rcmap.throttle()-1);
```

It was tested with `ARMING_REQUIRE` to both 0 and 1.

@rmackay9 I think this might actually contain an important safety fix now.  I don't think we were appropriately setting up the safety trim value or the set_servo_outputs method in the case ARMING_REQUIRE was zero - the same thing you pointed out in the first iteration of this PR!

**Comment by peterbarker** [comment]
Works as intended.  If you set e.g. `RCMAP_THROTTLE` to 56 then it waits until you disarm before it segfaults :-)  die-rcmap-die should fix that properly when it is merged.

**Review by khancyr — COMMENTED** [review]
That seems a good fix.
@peterbarker could you rebase this and bring it on dev call ?

**Comment by peterbarker** [comment]
Too old, too conflicty.  Will recreate if I feel up to it.

**Pull request closed without merging**
