### PR TITLE
AP_OSD:Add HD fonts for DJI googles

### PR DESCRIPTION
**Pull request by Hwurzburg**
tested...will add link in wiki once merged and I get a URL

### CODE REVIEW

**Comment by timtuxworth** [comment]
no lower case?

**Comment by Hwurzburg** [comment]
MWOSD and ArduPilot OSD Font sets have no lower case

**Comment by timtuxworth** [comment]
> MWOSD and ArduPilot OSD Font sets have no lower case
What would it take to fix that?

**Comment by Hwurzburg** [comment]
I complete redesign of the OSD system....and where would lower case be used? the only text is GCS messages and flight modes...and all the GCS messages are upper case emits from ArduPilot....

**Review by tridge — APPROVED** [review]

**Comment by timtuxworth** [comment]
> A extensive redesign of the OSD system and MSP telemetry definitions....and where would lower case be used? the only text is GCS messages and flight modes...and there are no free font indexes for a lower case set

GCS messages and flight modes. It seems pretty obvious to me (still new to ArduPilot) that this is a huge deficiency.

**Pull request merged**
