### PR TITLE
Rover: Add SmartRTL failsafe action

### PR DESCRIPTION
**Pull request by oneTimePad**
Add failsafe actions SmartRTL or RTL and SmartRTL or Hold

Tested in STIL and with build_all.sh #7553

### CODE REVIEW

**Comment by Pedals2Paddles** [comment]
Should (3) have hold as the failover if RTL returns false too?

**Comment by oneTimePad** [comment]
@Pedals2Paddles  Yeah, I was wondering what should happen in that case. Should a similar thing be done for (1)?

**Comment by Pedals2Paddles** [comment]
I think so.  I've never used rover, so I can't speak for their users. But it makes sense to have a failover action for any failsafe IMO.

**Comment by rmackay9** [comment]
Very nicely done!  Merged with no adjustments required.

**Pull request merged**
