### PR TITLE
AP_Landing: abort landing if gear was not deployed

### PR DESCRIPTION
**Pull request by EShamaev**
Checks the state of the gear before entering final stage of landing.

### CODE REVIEW

**Comment by EShamaev** [comment]
@magicrub Please advise if the place to take the decision to abort was picked right?

**Comment by Pedals2Paddles** [comment]
This currently only applies to plane, right?

**Comment by EShamaev** [comment]
Yes, to a plane with a regular landing slope.

**Comment by EShamaev** [comment]
Due to mistake in logic, the abort of landing got tested in SITL with Travis. Seems to work fine.

**Comment by magicrub** [comment]
@EShamaev I like that we check this, but it's missing something:

- we need to deploy the gear or else we get into a landing abort loop. If we can't deploy, then we need to self-disable or bypass the abort

- this sort of check probably needs more time to do the physical deploy. Checking for gear as you flare is a bit too late. Needs to be done in a separate check before the flare check. How about check for pre-flare stage or a few seconds to impact?

**Comment by EShamaev** [comment]
Well, if the gear is not used at all - it stays in unknown state and the check passes. That's how it passed Travis.
Tridge already merged auto deploying, so if the gear is used it will work in auto. Or if manual - by pilot.

As for flare - it is by default 3 seconds before impact and 3 meters before it, so I though it's safe to use. Otherwise - more parameters needs to be added.

**Comment by magicrub** [comment]
yes, all that is fine.. but it still gets into a loop that we want to avoid. There needs to be something that forces it out of a loop.

Default flare is 3s/3m but that doesn't mean it stays that way. Just checking for pre-flare OR flare is best.

**Comment by EShamaev** [comment]
Alright, this raises more questions.

If we do it right from aviation point of view - gear should be deployed at least when auto land WP starts to be executed, and best - 1 or 2 waypoints ahead of it. It should not be directly connected to time before impact or distance to the TD point.
This comes from assumption that in autopilot we use instrument approach practice and in this case, most common would be to deploy gear before/at intercept to the final approach course (or entering the pattern, which under instrument is usually straight-in).
Then checks should be made after predefined time that is enough for gear to deploy.

So what can be done:

- add a parameter - "gear deploy time";
- deploy gear immediately after encountering autoland WP (no matter what height/disctance) (needs modification of @tridge's code)
- check the gear after the set time and abort landing if it was not deployed.

**Comment by lvale** [comment]
@EShamaev Would be very helpful that you'd illustrate what kind of commercial Landing Gear systems have a mechanism to ensure their current state (Deployed vs Retracted) and/or elaborate a little on how users can be able to build such systems.

**Comment by EShamaev** [comment]
@lvale Actually there are a lot of, just few examples:

https://www.electron-retracts.com/product/er-40evo-set-b/
https://www.towerhobbies.com/cgi-bin/wti0001p?&I=LXHDDA&P=0
https://www.scaleflying.com/60-120-Size-Electric-Retracts-100-Single-_p_4289.html

The state is most easily monitored with simple end switch or if you want to go more complex, you can use magnetic sensor. Lot's of different possibilities.

I never considered this to be a major issue to anyone who builds a large enough plane that uses retractable gear.

If the question goes to real planes - the situation is pretty much the same. Either mechanical or proximity sensors, usually doubled on both up and down sides. Usually if there are doors, sensors are put on dors as well, as the logic for opening closing is not always straight forward.

Just an example:
image

**Comment by magicrub** [comment]
yeah, I would say all those suggestions, including the one I made, are enhancements to the existing PR so let's merge this one and make a new one for the other suggestions.

**Pull request merged**
