### PR TITLE
Tools: ardupilotwaf: add -Wsign-compare to SITL compilation

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by peterbarker** [comment]
We enforce this on some platforms... why not SITL?

**Comment by OXINARF** [comment]
Why not for all?

**Comment by magicrub** [comment]
Yeah, seems like a useful warning for all platforms.

**Comment by peterbarker** [comment]
On Thu, 10 May 2018, Tom Pittenger wrote:

> Yeah, seems like a useful warning for all platforms.

Yes, it would be.  But we compile with -Werror on some platforms, and 
adding this flag would break those platforms.  I'm particularly worried 
about MacOSX, which I don't have an environment for.

I'm pretty sure there's a whole bunch of flags floating around somewhere 
that should be "moved up" so that all platforms compile with them.  The 
list for ChibiOS is... extensive.

**Comment by OXINARF** [comment]
> But we compile with -Werror on some platforms, and adding this flag would break those platforms.

@peterbarker Have you tested that? CI for this PR doesn't seem to give any sign-compare warnings for SITL.

**Comment by peterbarker** [comment]
On Mon, 14 May 2018, Francisco Ferreira wrote:

>       But we compile with -Werror on some platforms, and adding this
>       flag would break those platforms.
> 
> @peterbarker Have you tested that? CI for this PR doesn't seem to give any
> sign-compare warnings for SITL.

CI won't pass if there are any in the code - it dies on one of the other 
platforms if there are.

**Comment by OXINARF** [comment]
@peterbarker I understand that it will die in other platforms if there is code that triggers that warning - and it should! My question was if that problem existed with current code - in which case we couldn't indeed add this for all boards.

But... For coincidence Randy had a build error with this in another PR: https://github.com/ArduPilot/ardupilot/pull/8388#issuecomment-388700523 I just realized that we build all boards with -Wall and -Wextra and sign-compare is included in it with both GCC and Clang.

**Comment by OXINARF** [comment]
@peterbarker Ping ^^

**Comment by OXINARF** [comment]
What I'm saying is that this warning is already turned on for ALL boards. On some boards we turn warnings into errors so this is already required in those.

**Comment by peterbarker** [comment]
On Tue, 22 May 2018, Francisco Ferreira wrote:

> What I'm saying is that this warning is already turned on for ALL boards. On
> some boards we turn warnings into errors so this is already required in
> those.

Ah - so the appropriate fix is to turn warnings into errors in SITL? :-)

**Comment by OXINARF** [comment]
Well the appropriate fix is to make warnings and errors the same for all boards instead of the spaghetti mess we have now.

All I'm saying is that the current code in this PR doesn't add anything new to what we already have. Turning warnings into errors in SITL is probably going to cause a headache to a lot of people, but I wouldn't personally oppose.

**Pull request closed without merging**
