### PR TITLE
AP_RangeFinder: Making devices optional

### PR DESCRIPTION
**Pull request by muramura**
I want to make rangefinder binaries optional for the following reasons:

1. I know that rangefinder drivers are getting more.
2. I can't attach all rangefinders to the aircraft.
3. I have already decided on a range finder when designing the fuselage.
4. Some aircraft do not use a range finder.
5. I know that when maintaining the aircraft, reducing unnecessary code can limit the scope of the investigation.
6. I want to write only the rangefinder to use to FC.

### CODE REVIEW

**Comment by Pedals2Paddles** [comment]
This would mean anyone wanting to use a rangefinder has to build their own custom firmware to enable access to the one they want to use.  This would also break every existing vehicle with a rangefinder.  None of this is necessary because it only uses the rangefinder driver that you select in the type parameter.   Also, the defines say disable but it is programmatically written as an enable.  Closing since I don't think this is a workable solution to a problem.

**Comment by rmackay9** [comment]
@Pedals2Paddles,
I don't think this PR actually breaks existing setups because the defines default to enabled.

Still, I'm not sure if other devs will accept this PR.  If the issue is reducing complexity to reduce possible support load I'm not sure this helps.  Better solution may include:

- using apjtools to define vendor specific parameter defaults
- adding read-only parameter support so parameters can't accidentally be changed by the user (unless they rewrite the firmware)

**Comment by peterbarker** [comment]
Putting new drivers behind pragmas might help us stay within 1MB on new boards, 'though.

**Comment by rmackay9** [comment]
@peterbarker, yes, I agree.  For this reason is could be useful.  There are quite a few lidar that could probably be moved into the HAL_MINIMIZED_FEATURES list.

**Comment by peterbarker** [comment]
I should mention I have a branch around here somewhere that allows Copter to be compiled without RangeFinder built in at all.

**Comment by rmackay9** [comment]
A list of lidar that could be disabled with minimized features:

- LeddarVu8 -- relatively new driver
- BLPing -- new and only used on boats
- uLanding -- expensive so rarely used
- Wasp?
- Lanbao?

**Comment by rmackay9** [comment]
@peterbarker,

re the branch with no range finder at all.. I'm not sure it's worth going this far.  rangefinders are pretty close to standard equipment.

**Comment by Pedals2Paddles** [comment]
oops. I see I was reading it backwards. So shouldn't the disable defs be in the hwdef rather than the header file now?

**Comment by auturgy** [comment]
I wouldn’t put lanbao behind minimised. It’s small and cheap: just like the boards effected by minimise :)

**Comment by magicrub** [comment]
The double negative is hard to read. Should be
If device ==enabled and at the top of the main cpp had a bunch of defines do a ifndef device then device = enabled like other drivers

**Comment by rmackay9** [comment]
Looks like this PR causes an unintentional functional change.

We discussed this on the dev call but decided that if the motivation is to reduce flash size then there are likely better methods for doing this (like ensuring only one of the possible EKFs is included in the code).

**Pull request closed without merging**
