### PR TITLE
hwdef: support hakrc minif4 aio fc

### PR DESCRIPTION
**Pull request by chobitsfan**
[HAKRC minif4 aio](https://www.banggood.com/20x20mm-HAKRC-MiniF4-F4-Flight-Controller-Integrated-with-Betaflight-OSD-5V-2A-BEC-for-RC-Drone-p-1246530.html?cur_warehouse=CN) is a very small flight controller suitable for a micro quad. It is a clone of omnibus f4 with minor changes. This PR allows user to use scl1/sda1 to connect external device because they are easier to connect than scl2/sda2 (scl2/sda2 need some soldering)

thanks to info provided by @msfujino in https://github.com/iNavFlight/inav/issues/4025

### CODE REVIEW

**Comment by anbello** [comment]
PB10 and PB11 could be used for UART3 instead of I2C2 to have one I2C and three UART

**Comment by chobitsfan** [comment]
Yes, It may be better to have 3 UART. I will test it when I go back to lab next week. Thank you.

**Comment by chobitsfan** [comment]
uart1 -> serial1
uart3 -> serial2
uart6 -> serial3

**Comment by krzysztofkuczek** [comment]
Hi,
I'm also trying to run plane firmware on this board, and the LED seems to be connected to pin 41...
when i changed
PB5 LED OUTPUT HIGH GPIO(57)
to
PB5 LED OUTPUT HIGH GPIO(41)
the green led is blinking during boot time...

Kris

**Comment by chobitsfan** [comment]
hi @krzysztofkuczek thank you. I will try it

**Comment by chobitsfan** [comment]
hi @krzysztofkuczek 
According to @msfujino 

> The resistance between PB6-LED-SCL is almost zero. The same waveform as PB6 is observed with LED and SCL. Although I did not see the pattern directly, I think that PB6-LED-SCL is connected.

I tested it, too.

**Comment by krzysztofkuczek** [comment]
Hi, i use it in my 118g little wing and it works without any problems :)
https://www.youtube.com/watch?v=5vqv_78T4WY

**Comment by chobitsfan** [comment]
hi @krzysztofkuczek it is cool! thank you for testing

**Comment by chobitsfan** [comment]
This is outdated and I switch to other FCs

**Pull request closed without merging**
