### PR TITLE
Differential spoilers support, elevon offset

### PR DESCRIPTION
**Pull request by gmorph**
Fixed differential spoilers support, added elevon offset
See PR #2935

### CODE REVIEW

**Comment by gmorph** [comment]
I rebased this on Master and made the necessary changes.  I have also tested this on my plane on the ground and it works.
Thanks, Grant.

**Comment by magicrub** [comment]
Great.  Thanks Grant!

**Comment by ethomas999** [comment]
@gmorph Sounds good; thanks.

--ET

**Comment by magicrub** [comment]
merged (https://github.com/ArduPilot/ardupilot/commit/7d824247af60dd9d3ce97d4d0f2cc19f25a619ef), thank you so much @ethomas997 for sticking it out. Sorry it took so long for us to get this one in. Special thanks to @gmorph for testing it.

**Comment by magicrub** [comment]
oh, there's two of you! @ethomas997 @ethomas999

**Pull request closed without merging**
