### PR TITLE
AP_InertialSensor: Disable -Werror=array-bounds on some getters

### PR DESCRIPTION
**Pull request by Jaaaky**
Fixes issue #19599 Failed to build for Pixhawk1 with O3

### CODE REVIEW

**Comment by Jaaaky** [comment]
I've found that send_scaled_imu() also sends compass info, so not sure if this is the right solution if a board has 3 compasses and 2 inertial sensors like Pixhawk1 with external compass.

**Review by peterbarker — APPROVED** [review]
LGTM

**Review by peterbarker — CHANGES_REQUESTED** [review]
Argh.  The compass thing....

**Comment by peterbarker** [comment]
@Jaaaky I remember looking at this a while back now and noticing the compass thing.

This is a weird one.  I can't see a good fix here.

One thing that could be done is to push/pop so that `-Werror=array-bounds` doesn't happen at all.

... why are you trying to compile with different optimisation flags, BTW?

**Comment by Jaaaky** [comment]
@peterbarker 
I see no reason why not use a higher optimization level as long as I've enough flash space and free memory..
I've done benchmarks some months ago and could see it's useful.


One more important thing I found that a habit of testing build with different optimization levels can show some "hidden" bugs.

**Comment by Jaaaky** [comment]
@peterbarker 
I've changed it to use diagnostics ignore push/pop .. Check it please.

**Comment by peterbarker** [comment]
> One more important thing I found that a habit of testing build with different optimization levels can show some "hidden" bugs.

Yes, and that's why this one intrigues me so much.  Is it really managing to tell us something here that we're not understanding?!

Perhaps we should check the various static-analysis suites to see if they see something.

**Comment by peterbarker** [comment]
AFAICS this is a correct implementation of what I was suggesting.  Whether we'll disable a valuable check for an optimisation level we don't use in standard builds is going to one one for DevCall.

**Comment by tridge** [comment]
I think this is a better fix:
https://github.com/ArduPilot/ardupilot/pull/19613

**Comment by tridge** [comment]
i'd like to find a method that doesn't lose the error

**Comment by tridge** [comment]
does this work?
```
uint8_t get_accel_count(void) const { return MIN(INS_MAX_INSTANCES-1, _accel_count); }
```

**Comment by Jaaaky** [comment]
> does this work?
> 
> ```
> uint8_t get_accel_count(void) const { return MIN(INS_MAX_INSTANCES-1, _accel_count); }
> ```

@tridge 
It worked, I've added a minor fix for get_temperature in GCS too as it also failed with the same error.
Please check now.

**Comment by Jaaaky** [comment]
@tridge  I've removed the "-1" I think it's a regular count, no need for -1,

I could see that _accel_count hold actual count not count-1

**Review by tridge — APPROVED** [review]

**Comment by tridge** [comment]
@Jaaaky thanks for following up on this!

**Pull request merged**
