### PR TITLE
HAL_ChibiOS: allow FrSky_INV to be controlled as GPIO

### PR DESCRIPTION
**Pull request by tridge**
this allows control via relay settings
ping @priseborough

### CODE REVIEW

**Comment by priseborough** [comment]
I'll give it a test.

**Comment by priseborough** [comment]
Can you please provide some advice on how the replay parameters should be used in this instance (attaching a non-inverted serial device to the frsky port). I've checked the schematic here: https://pixhawk.org/_media/modules/pixracer-r14.pdf and the parameter documentation and it is not clear to me. TXS

**Comment by priseborough** [comment]
Tested and confirmed working. To use FRSky port for serial, set RELAY_PIN = 78 and RELAY_DEFAULT = 0

**Comment by proficnc** [comment]
So... this allows the FRSky port to be used as an additional serial input?

**Comment by WickedShell** [comment]
If it's dependent upon the first relay pin it isn't compatible with camera triggering, if it can be any relay pin that's great news.

**Comment by tridge** [comment]
it can be any relay pin, yes
we should do it as a BRD_* param though

**Pull request merged**
