### PR TITLE
AP_OSD: updated font for Chinese

### PR DESCRIPTION
**Pull request by QioTek**
Simplified Chinese font, Convenient for people who use Chinese or Japanese kanji

### CODE REVIEW

**Comment by andyp1per** [comment]
Each additonal font adds several kilobytes to the flash size - I think you will need to be more selective about this.

**Comment by QioTek** [comment]
@andyp1per  Yes, it will adds 16K flash size. But it's worth it for Chinese and Japanese.

**Comment by andyp1per** [comment]
16k is a *lot*. It will overflow several boards - you will need to be more selective about this, or possibly wait for the custom build server.
If your board is a 2Mb board then the obvious thing to do is only enable this on 2Mb boards

**Comment by QioTek** [comment]
@andyp1per  I just compiled Matek series, Kakute series boards, include copter and plane firmware.  Those are 1M boards, Kakute series are 96K bootloader, none of them overflow at present.

**Comment by IamPete1** [comment]
I'm a little surprised we have so many fonts. Maybe we more languages is better than different versions of the same one. Would be quite nice to make them all compile time options.

@QioTek You also need to add change the font param description so people know how to select it.

**Comment by QioTek** [comment]
I will do it after merge. @IamPete1

**Comment by bys1123** [comment]
Looks nice, lots of chinese users is using official firmware. This is very helpful.

**Comment by Tanzhengooo** [comment]
Excellent! This is convenient for Chinese users to use.

**Comment by zhangdashuo** [comment]
It‘s useful for us

**Review by peterbarker — CHANGES_REQUESTED** [review]
`OSD_FONT` should be updated as part of this PR.

**Comment by IamPete1** [comment]
@QioTek did you mean to close this PR?, I think its certainty a good feature that we would love to have in AP. Its very close to being ready to go in. Just need to add the param description and squash the commits.

**Pull request closed without merging**
