### PR TITLE
Tidy scheduler loop function (NFC)

### PR DESCRIPTION
**Pull request by peterbarker**
This should be completely NFC.

It simply replaces nested `if` statements with a pair of `continue`s.

### CODE REVIEW

**Comment by peterbarker** [comment]
Notionally this could also be applied:

```
diff --git a/libraries/AP_Scheduler/AP_Scheduler.cpp b/libraries/AP_Scheduler/AP_Scheduler.cpp
index 002dd89408..a87d7ab1ec 100644
--- a/libraries/AP_Scheduler/AP_Scheduler.cpp
+++ b/libraries/AP_Scheduler/AP_Scheduler.cpp
@@ -172,7 +172,8 @@ void AP_Scheduler::run(uint32_t time_available)
                   (unsigned)_task_time_allowed);
         }
         if (time_taken >= time_available) {
-            goto update_spare_ticks;
+            time_available = 0;
+            break;
         }
         time_available -= time_taken;
     }
@@ -180,7 +181,6 @@ void AP_Scheduler::run(uint32_t time_available)
     // update number of spare microseconds
     _spare_micros += time_available;
 
-update_spare_ticks:
     _spare_ticks++;
     if (_spare_ticks == 32) {
         _spare_ticks /= 2;
pbarker@bluebottle:~/rc/ardupilot(scheduler-loop-tidy)$ 
```

I don't hate goto *that* much :-)

**Comment by khancyr** [comment]
Please !!!! Apply it too !

**Comment by dgrat** [comment]
This is basically the lite version of my commit: https://github.com/ArduPilot/ardupilot/pull/7703/commits/7c041d1c7e82aa9eedd2cf466c1ac3118e2025cd

**Comment by peterbarker** [comment]
@khancyr made me do it.  Pushed the `goto`-elimination patch on top.

**Comment by peterbarker** [comment]
@dgrat For some values of "lite".  The patches do have some similarity (elimination of one of the indentation blocks), but all my patches are doing is exchanging nesting for `continue`.  Just a readability thing, not a functional thing.  Your patches are definitely making functional changes!

I *think* this follow-up patch may fix a real problem, 'though - https://github.com/peterbarker/ardupilot/commit/f3946923437dc7c190ed3ba727b7a1df5fdba892 - but I did not add it here as it is not NFC.

**Comment by rmackay9** [comment]
I think @tridge is probably best placed to review this one.

**Comment by khancyr** [comment]
@peterbarker could you see with Tridge to merge that ? It seems good to go to me

**Pull request merged**
