### PR TITLE
AP_Windvane: Add support for NMEA wind vane types

### PR DESCRIPTION
**Pull request by IamPete1**
This add support for NMEA 0183 sensors using the [mwv message type
](http://www.catb.org/gpsd/NMEA.html#_mwv_wind_speed_and_angle)

Tested using a Calypso Wired Standard Ultrasonic sensor. 

https://calypsoinstruments.com/shop/product/ultrasonic-wired-standard-81

This is my first go at a digital protocol, it is based on the NMEA rangfinder type. Seems to work and return sensible numbers.

### CODE REVIEW

**Comment by WickedShell** [comment]
Not a thing to do here by any means, but we really need to do the cleanup one day of having a single generic NMEA parser, and then have a callback for term complete that each use case can set. We now have GPS, rangefinders, and wind sensors that are all running basically the same NMEA parser.

Anyways this isn't a blocker/hold up/request for any change. I just wanted to note it somewhere :)

**Comment by rmackay9** [comment]
this looks pretty good to me.. i haven't done a detailed check of all the logic but it works on the real hardware?

**Comment by rmackay9** [comment]
@WickedShell, [maybe we should merge this PR first](https://github.com/ArduPilot/ardupilot/pull/10941) so that we at least get rid of the duplicate hex_to_char function?

**Comment by IamPete1** [comment]
@rmackay9 Yep tested on KakuteF7 with rs232 converter. Get sensible numbers for speed and direction. Not tested in on the water yet.

**Comment by rmackay9** [comment]
Merged, thanks!

**Pull request merged**
