### PR TITLE
AP_Mount: Changed the type of gimbal angle acquisition and converted …

### PR DESCRIPTION
**Pull request by laozhou-fujian**
…the lowercase characters in the command to uppercase

### CODE REVIEW

**Review by peterbarker — CHANGES_REQUESTED** [review]
Does this break compatibility with older mount firmwares?

Should be a single commit, not three....

**Comment by laozhou-fujian** [comment]
> Does this break compatibility with older mount firmwares?
> 
> Should be a single commit, not three....

This will not compromise compatibility; it simply changes the attitude information transmitted from the gimbal to the flight controller from the previous internal gimbal frame angles to pitch and roll angles relative to the ground, while the heading remains as the previous internal gimbal frame angle. This is because the flight controller controls the gimbal using pitch and roll angles relative to the ground.

Since most of the data bits in the commands we send to control the gimbal are uppercase letters and numbers, although lowercase letters are also compatible, we prefer to standardize them as uppercase letters.

Previously, the reason for repeated submissions was that the automatic testing verification did not pass, but this will not happen again in the future.

**Comment by peterbarker** [comment]
> > Does this break compatibility with older mount firmwares?
> This will not compromise compatibility; it simply changes the attitude information transmitted from the gimbal to the flight controller from the previous internal gimbal frame angles to pitch and roll angles relative to the ground, while the heading remains as the previous internal gimbal frame angle. This is because the flight controller controls the gimbal using pitch and roll angles relative to the ground.

Great - so older gimbal firmwares can send in either frame, which is what I was asking about :-)

**Comment by peterbarker** [comment]
I've fixed the commit message and marked for DevCall.

**Comment by timtuxworth** [comment]
> Previously, the reason for repeated submissions was that the automatic testing verification did not pass, but this will not happen again in the future.

It's ok to submit multiple times until the PR is acceptable @laozhou-fujian , but you should "squash" the individual commits into one commit which keeps the GitHub history clean. https://ardupilot.org/dev/docs/git-interactive-rebase.html

**Comment by laozhou-fujian** [comment]
> > Previously, the reason for repeated submissions was that the automatic testing verification did not pass, but this will not happen again in the future.
> 
> It's ok to submit multiple times until the PR is acceptable @laozhou-fujian , but you should "squash" the individual commits into one commit which keeps the GitHub history clean. https://ardupilot.org/dev/docs/git-interactive-rebase.html

Okay, understood, thank you

**Comment by rmackay9** [comment]
Great to see this!  support for this gimbal is new for 4.6 and I have that I can also use to help test.

I think we should merge this

**Comment by peterbarker** [comment]
@rmackay9 sooo... did you want to test this before merging?  I'd intended to just merge it....

**Comment by rmackay9** [comment]
yes, I'll test this..

**Review by rmackay9 — APPROVED** [review]
I've tested this and it works fine, thanks!

**Pull request merged**
