### PR TITLE
AP_RobotisServo: Send register write values as little-endian

### PR DESCRIPTION
**Pull request by nexton-winjeel**
When writing values to a Robotis servo, the values need to be sent little-endian, as per the following:
* https://github.com/ROBOTIS-GIT/DynamixelSDK/blob/ef7ae1f6fc7f58f7276859244acc231297632d4d/c/src/dynamixel_sdk/protocol2_packet_handler.c#L1121
* https://emanual.robotis.com/docs/en/dxl/x/xm430-w350/#size

### CODE REVIEW

**Comment by peterbarker** [comment]
Was this tested?

I'm really guessing you tested this on a little-endian machine where this is a no-op.

Was this seriously causing someone trouble?

I mean, yeah, we'll merge this, but I am curious why the patch was proposed.

**Comment by nexton-winjeel** [comment]
>I'm really guessing you tested this on a little-endian machine where this is a no-op.

Yeah, tested on a little-endian machine.

> Was this seriously causing someone trouble?

I doubt it, but if someone happens to run this driver on a big-endian device, it won't end well. 

> I mean, yeah, we'll merge this, but I am curious why the patch was proposed.

Because it's a bug with a trivial fix.

**Comment by peterbarker** [comment]
> > I'm really guessing you tested this on a little-endian machine where this is a no-op.
> Yeah, tested on a little-endian machine, but not on a big-endian machine.

The latter are becoming hard-to-find.  Or at least find ones that can't be switched.

> > Was this seriously causing someone trouble?
> I doubt it, but if someone happens to run this driver on a big-endian device, it won't end well.

We gave up the pretense of supporting big-endian a while back - this bit's only the tip of the iceberg, I assure you!

> > I mean, yeah, we'll merge this, but I am curious why the patch was proposed.
> Because it's a bug with a trivial fix.

Yep, agreed, it is a bugfix, and I will merge it.

But there's two commits in here, and I don't trust that merge commit to just go away.  I also can't force-push your branch to fix the problem.  Could you rebase this such that there's only a single commit, please?

**Comment by peterbarker** [comment]
Replaced by https://github.com/ArduPilot/ardupilot/pull/28243 as I can't force-push this branch

The new PR is marked as merge-on-ci-pass

**Comment by peterbarker** [comment]
I've merged the other PR with the single commit in it.  Thanks!

**Pull request closed without merging**
