### PR TITLE
Tools: build_ci: speedup git download operations

### PR DESCRIPTION
**Pull request by khancyr**
Make build_ci.sh git operations a bit faster

### CODE REVIEW

**Comment by peterbarker** [comment]
Interesting.  Did you time this to see how much of a change it makes?

**Comment by khancyr** [comment]
@peterbarker 
```
 => [4/5] RUN mkdir MAVProxy     && cd MAVProxy     && git init     && git remote add origin https://github.com/ardupilot/MAVProxy     && git fetch orig  1.8s
 => [5/5] RUN mkdir MAVProxy2     && cd MAVProxy2     && git clone https://github.com/ardupilot/MAVProxy                                                  8.4s
```

Another output : 
```
#11 [4/5] RUN mkdir MAVProxy     && cd MAVProxy     && git init     && git remote add origin https://github.com/ardupilot/MAVProxy     && git fetch origin master --depth 1     && git reset --hard FETCH_HEAD
#11 sha256:190d5f7a1532be93310eb77e057f58d6593ebc0c06e0c01e2d3a3ef4dbd6d883
#11 0.412 hint: Using 'master' as the name for the initial branch. This default branch name
#11 0.412 hint: is subject to change. To configure the initial branch name to use in all
#11 0.412 hint: of your new repositories, which will suppress this warning, call:
#11 0.412 hint:
#11 0.412 hint:         git config --global init.defaultBranch <name>
#11 0.412 hint:
#11 0.412 hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
#11 0.412 hint: 'development'. The just-created branch can be renamed via this command:
#11 0.412 hint:
#11 0.412 hint:         git branch -m <name>
#11 0.413 Initialized empty Git repository in /ardupilot/MAVProxy/.git/
#11 1.589 From https://github.com/ardupilot/MAVProxy
#11 1.589  * branch            master     -> FETCH_HEAD
#11 1.589  * [new branch]      master     -> origin/master
#11 1.620 HEAD is now at 93ecdcf console: fixed Vcc display
#11 DONE 1.6s

#12 [5/5] RUN mkdir MAVProxy2     && cd MAVProxy2     && git clone https://github.com/ardupilot/MAVProxy
#12 sha256:29ad4f9878a1de3393fbf9d33e5322a457651fd0b43ae5fc300ceb6305e18022
#12 0.498 Cloning into 'MAVProxy'...
#12 DONE 8.8s
```

Another intersting stuff is how much size we get, which explay why it is faster : 
image

**Comment by khancyr** [comment]
for the context that is mosly what github action do when it checkout the branch !

**Comment by peterbarker** [comment]
> for the context that is mosly what github action do when it checkout the branch !

Yep, those numbers looks compelling.

Why are you doing this init-add-remote-fetch thing when `clone` takes a `--maxdepth`?

**Comment by khancyr** [comment]
right, git clone --depth=1 is working close to the same ! Will change to this then. Thanks.

**Comment by khancyr** [comment]
@peterbarker change done!

**Review by peterbarker — APPROVED** [review]
LGTM

**Pull request merged**
