### PR TITLE
Tools: ardupilotwaf: add entry for 64bit versions of Navigator

### PR DESCRIPTION
**Pull request by Williangalvani**

### CODE REVIEW

**Review by peterbarker — CHANGES_REQUESTED** [review]
Failed to build the navigator64 target:

`Could not find the program ['aarch64-none-linux-gnu-ar']`

**Comment by tridge** [comment]
needs to be added to board_list.py

**Review by peterbarker — CHANGES_REQUESTED** [review]
Needs patch next to existing "navigator" board in board_list.py

**Comment by tridge** [comment]
I ran this on firmware.ardupilot.org:
apt install g++-10-aarch64-linux-gnu

**Review by tridge — APPROVED** [review]

**Review by tridge — CHANGES_REQUESTED** [review]
please remove the COLCON_IGNORE change

**Review by tridge — APPROVED** [review]

**Pull request merged**
