### PR TITLE
AP_NavEKF2/3: read rangefinder indexing issue

### PR DESCRIPTION
**Pull request by muramura**
The sequences 1, 2, 0, 1, 2, 0... are used.
However, the subsequent array process uses 0, 1, 2.
There is a discrepancy in the array references.
I have set it to start from array 0.

### CODE REVIEW

**Comment by rmackay9** [comment]
@muramura,

Thanks very much for finding this and providing a fix.  I guess this bug causes the EKF to consume the incorrect distance?

Can you tell us if you've done any testing?

Thanks again.

**Comment by peterbarker** [comment]
>  However, the subsequent array process uses 0, 1, 2.

I'm curious about where this usage is.

AFAICS this PR will yield no actual behavioural change, as we require all three samples to be current so we can take a median value from them.  It doesn't really matter if we start filling these values in at offset 1 or 0 - we need to fill slot 0 before we will consume the values.

I think we should merge this PR anyway (assuming it has some testing!) as the new ordering is much more conventional.

**Comment by peterbarker** [comment]
Rebased it.

**Comment by tridge** [comment]
this is not a bug, order of a median doesn't matter

**Comment by rmackay9** [comment]
Hi @muramura,

We reviewed this on the dev call and decided that although it is odd, it is not a bug and so it is better to leave it alone instead of risk introducing a bug. Txs for finding this oddity.

**Pull request closed without merging**
