### PR TITLE
AP_Baro: fixed averaging of samples for several drivers

### PR DESCRIPTION
**Pull request by tridge**
This fixes drivers that were not accumulating pressure properly, leading to more noise than they should have

testing:
 - [x] BMP380
 - [x] BMP280
 - [x] LPS2XH
 - [x] SPL06

### CODE REVIEW

**Review by peterbarker — COMMENTED** [review]
This seems to be telling me we need an "new_sample" method on the backend base class rather than letting the backend subclasses accumulate themselves.  That may not work universally but would've avoided this mess.

**Comment by tridge** [comment]
> This seems to be telling me we need an "new_sample" method on the backend base class rather than letting the backend subclasses accumulate themselves.

that would be nice, yes, a new_pressure and new_temperature method.
meanwhile, can you test mini-pix with this change for the LPS2XH driver?

**Comment by andyp1per** [comment]
So this will affect the DPS310 as well right?

**Review by andyp1per — APPROVED** [review]

**Comment by tridge** [comment]
> So this will affect the DPS310 as well right?

no, DPS310 already did accumulation the right way

**Comment by anbello** [comment]
Sorry, MS5611 do accumulation in the right way?

**Pull request merged**
