### PR TITLE
EKF3: Add basic support for use of external nav system data

### PR DESCRIPTION
**Pull request by rmackay9**
This is a replacement PR for https://github.com/ArduPilot/ardupilot/pull/8730.

This is exactly the same as the previous PR except that it has been rebased on master.

I've tested that it works in a basic sense at least.  I tested on my regular Rover and the vehicle appears on the map and responds to small movements in position and heading.  I also see these messages in the console:

> EKF3 IMU1 ext nav yaw alignment complete
> EKF3 IMU1 initial pos NED = 0.0,0.0,0.0 (m)
> EKF3 IMU1 is using external nav data
> EKF3 IMU0 ext nav yaw alignment complete
> EKF3 IMU0 initial pos NED = 0.0,0.0,0.0 (m)
> EKF3 IMU0 is using external nav data
> EKF3 IMU1 tilt alignment complete
> EKF3 IMU0 tilt alignment complete

### CODE REVIEW

**Comment by anbello** [comment]
I think it should be better to have also the equivalent for EKF3 of this related PRs from @chobitsfan :
- https://github.com/ArduPilot/ardupilot/commit/3766ee1b60092bcad0ddcb209b3514380b6bffb8
- https://github.com/ArduPilot/ardupilot/commit/1e56ad483796ea7d98e237d79710320a2652e618
- https://github.com/ArduPilot/ardupilot/commit/08b9bf4a89e1d65b908aca3061662fc65708697a

**Comment by rmackay9** [comment]
@anbello, yes, it makes sense that we should try and add those features to EKF3 after this goes in. txs!

**Comment by rmackay9** [comment]
rebased on master..

**Comment by amilcarlucas** [comment]
Needs another rebase

**Comment by priseborough** [comment]
@rmackay9 I totally forgot about this. Did you still want to pursue it?

**Comment by rmackay9** [comment]
@priseborough, yes, we definitely need to get this working before we can switch over to the EKF3.  I'm happy to rebase this if that would help.

**Comment by rmackay9** [comment]
I've attempted to rebase this PR in this branch but I was not able to complete it because of some merge conflicts: https://github.com/rmackay9/rmackay9-ardupilot/commits/prise-ekf3-extnav2

**Comment by rmackay9** [comment]
Closing in favour of this updated PR: https://github.com/ArduPilot/ardupilot/pull/14106

**Pull request closed without merging**
