### PR TITLE
AP_Periph: add MCP9600 temperature sensor

### PR DESCRIPTION
**Pull request by magicrub**
Driver for an i2c temp sensor. It is currently only used in CubeOrange-periph

### CODE REVIEW

**Comment by tridge** [comment]
it is a bit more work, but a frontend/backend split would be worth doing, with a _TYPE parameter

**Comment by magicrub** [comment]
Follow-up PR?

**Comment by bugobliterator** [comment]
Yeah, backend/frontend split is definitely needed here.

**Comment by magicrub** [comment]
I've gone through this with adsb already. Can I get this in without it and then change it to a backend spilt afterwards in another PR?

**Comment by magicrub** [comment]
ok ok ok I'll make a new backend-split <sigh>

**Comment by peterbarker** [comment]
Basic MCP9600 simulator (enough for default parameters), and a little bit of debug code to help run this driver against that simulator is here: https://github.com/ArduPilot/ardupilot/compare/master...peterbarker:prx/sim-i2c-mcp9000?expand=1

**Comment by magicrub** [comment]
Thanks @hendjoshsr71 !!!!!

**Comment by magicrub** [comment]
I'll be rebasing this onto https://github.com/ArduPilot/ardupilot/pull/20060 which is the front/backend split

**Comment by magicrub** [comment]
closed in favor of https://github.com/ArduPilot/ardupilot/pull/21662

**Pull request closed without merging**
