### PR TITLE
Low-altitude Fence

### PR DESCRIPTION
**Pull request by kellyschrock**
Low-altitude Fence

Add a low-altitude fence type.

Once the copter has flown beyond a certain range
from launch (FENCE_LOW_RADIUS), the copter maintains
at least the altitude given by FENCE_ALT_MIN. Inside
the range, the min-altitude fence becomes inactive,
allowing for landing the copter.

Params:

. FENCE_ALT_MIN - Minimum allowed altitude
. FENCE_LOW_RADIUS - Trigger radius for low-alt fence
. FENCE_TYPE (new value) 4 - low-alt-fence

### CODE REVIEW

**Comment by gmorph** [comment]
Sorry, I'm not entirely clear on what this functionality does.  Am I right in thinking you want to set a distance from HOME (FENCE_LOW_RADIUS) where if the copter fly's past that point it maintains a certain altitude (FENCE_ALT_MIN).  Is that right?  If so what is the purpose of this functionality?  If it goes past a certain point wouldn't you prefer it to RTL?

Thanks, Grant.

**Comment by kellyschrock** [comment]
Hi Grant,

The point of this functionality is to prevent the copter flying below a
specific altitude, in the same way that FENCE_ALT_MAX prevents the copter
flying too high. Obviously it's necessary to land the copter eventually,
which is the reason for the FENCE_LOW_RADIUS parameter. If flying inside
the FENCE_LOW_RADIUS parameter's value (e.g. 20 meters), the copter can fly
normally (and land). Outside that radius, it maintains at least
FENCE_ALT_MIN altitude. I started a discussion at
http://diydrones.com/forum/topics/low-altitude-fence, hoping to solicit
peoples' input on the idea. Anyway, I've found is useful when flying over
large areas of tall grass or water, etc., and thought I would see if anyone
else found it to be a useful idea.

Thanks,
Kelly

**Comment by R-Lefebvre** [comment]
What would happen in the case where it enters critical battery failsafe and wants to autoland?  Which wins, the failsafe land, or the min fence?

**Comment by kellyschrock** [comment]
I'll test that again, but the idea is that the min fence wins. The
motivation for this change initially was because of a copter that was
landed in the water by an inexperienced pilot. The thinking is that landing
outside the FENCE_LOW_RADIUS distance from launch is the least desirable of
all things to do. I guess I was thinking that if they were using this
feature, the user would also configure the copter to RTL on a battery
failsafe. But to be honest, I don't know how (or whether) something like
that would be enforced.

**Comment by rmackay9** [comment]
The fence-low-radius might fit in well with something @jschall is working on which involves a upwards pointing cone around home used with RTL to avoid the vehicle climbing to RTL_ALT if it's near home.

**Comment by kellyschrock** [comment]
I like the sound of that feature. I've had RTLs when it was 12' from me,
and the 45ft. climb seemed kind of uncalled-for. :-)

**Comment by magicrub** [comment]
This fence feature would be useful for Plane too, right? I think Marc Merlin needs something like this

**Comment by lucasdemarchi** [comment]
Any news on this?

**Comment by kellyschrock** [comment]
I've heard nothing at all about this. Not sure who to contact, honestly.

**Comment by OXINARF** [comment]
This is merging into Copter-3.3 instead of master - which is the reason this isn't showing conflicts. This certainly needs some rebasing.

@kellyschrock If you still want this in, please open a PR targeting master.

**Comment by rmackay9** [comment]
I think it's a good idea, a good feature.
We'd probably want the radius to apply to the home location but also to any rally points.  That doesn't need to be there for it to make it into master though.

**Comment by rmackay9** [comment]
Sorry, it's probably my fault that it wasn't reviewed, merged earlier..

**Comment by kellyschrock** [comment]
@rmackay9 here's another PR against master, if interested: https://github.com/ArduPilot/ardupilot/pull/4568

**Pull request closed without merging**
