### PR TITLE
Add GPS_MAV type and MAV_GPS message support

### PR DESCRIPTION
**Pull request by allanm84**
Add support for the MAV_GPS message, passing this message to a GPS_MAV type.  This PR corresponds to https://github.com/mavlink/mavlink/pull/555

### CODE REVIEW

**Comment by OXINARF** [comment]
@allanm84 Any reason you don't have your e-mail in the commits associated to your GitHub profile?
Any reason you haven't added support for this message in Plane and Rover?

**Comment by allanm84** [comment]
@OXINARF No reason for different email config, just discrepancy on the computer I'm committing with.  I'll add plane and rover support to this PR shortly.

**Comment by OXINARF** [comment]
@allanm84 You can add several e-mails to GitHub and they all get recognized.

**Comment by allanm84** [comment]
BTW @OXINARF please wait for comments from @tridge and @rmackay9 as I've been working with them on these PRs.

**Comment by allanm84** [comment]
@OXINARF Plane and Rover support added

**Comment by WickedShell** [comment]
Do you have a link for the mavlink additions?

Has this been flight tested? If so what is the stability/timer interval between messages? (Just curious)

**Comment by allanm84** [comment]
@WickedShell The PR for the mavlink additions is here: https://github.com/mavlink/mavlink/pull/555

This has been flight tested indoors in a net using a proprietary position input.  Right now, we have a ~8hz position update, which is relatively stable.  The bigger issue is getting accurate timestamping to correspond with velocity data.  At the moment, I'm setting EK2_GPS_TYPE to 2 to circumvent that, however I will be working to get better timing/velocity input.

**Comment by rmackay9** [comment]
I think in other conversations we've called this "Fake GPS" support.  It's any easy-ish way to get an external position estimate into the EKF ahead of Paul Riseborough adding more official support.  I know that Roberto Navoni has used a similar method (but we haven't received his PR).  I haven't reviewed the commits in total yet but I support the general idea.

**Comment by meee1** [comment]
@allanm84 do you have a bin file of your current testing? just curious to see the velocity latency

**Comment by allanm84** [comment]
@meee1 I don't have a good bin file to show at the moment, but I'll try to push something up in the next few days that shows the latency.

**Comment by rmackay9** [comment]
Merged, thanks!

**Pull request closed without merging**
