### PR TITLE
Remove fmuv4 def

### PR DESCRIPTION
**Pull request by Hwurzburg**

### CODE REVIEW

**Comment by peterbarker** [comment]
Last commit should be `BUILD.md:` I think.

**Comment by Hwurzburg** [comment]
done....didnt know the proper commit label for this case....

**Comment by peterbarker** [comment]
Ah.  I'm not sure about removing the `fmuv4-beta` board here.  There were only a handful produces (and with ClikMate connectors!).  But they are a separate board with different setup to the (first) final version.

**Comment by tridge** [comment]
> Ah. I'm not sure about removing the `fmuv4-beta` board here.

I think we can remove it now

**Pull request merged**
