### PR TITLE
Copter: Send destination distance and bearing back to the GCS when us…

### PR DESCRIPTION
**Pull request by amilcarlucas**
…ing Guided_PosVel mode

### CODE REVIEW

**Comment by OXINARF** [comment]
I might be confused, but I think the PosVel mode doesn't have a destination, the target will continue being extended with the velocity you set it to.

And using the WPNav library just to get the distance and bearing is clearly an hack 🙂

**Comment by amilcarlucas** [comment]
PosVel mode has both a target destination and a velocity.
The Velocity mode only has a velocity

**Comment by amilcarlucas** [comment]
Should I extend this PR to all vehicles ?

**Comment by OXINARF** [comment]
> PosVel mode has both a target destination and a velocity.

Yes, it has a target destination, but that destination is changed in every loop so how can you reach it? The fact you are hacking into the WPNav library that isn't used in this PosVel mode shows that it isn't intended to be used.

I'll say that I don't really understand this mode as is because I don't really understand what it adds compared to the Vel mode. But that doesn't change the fact that I don't see any way you can say if the destination was reached in this method.

> Should I extend this PR to all vehicles ?

All as in Sub. If this is going to be merged then definitely it should also be done in Sub.

**Comment by amilcarlucas** [comment]
OK, found a better way to do this. Could not find the similar code in Sub though.

**Comment by amilcarlucas** [comment]
This one requires #7347 to be applied first

**Comment by rmackay9** [comment]
Merged, thanks!
By the way PosVel mode was developed and used a lot for smart shots.  It's useful if you want the vehicle to travel a very specific line.  With the velocity controller alone you can make it move in a straight line at a given speed quite easily but if you want to control where that line is exactly you need the posvel controller.

**Comment by amilcarlucas** [comment]
This paints a nice vector inside mavproxy. We are using this for a high precision (RTK-GPS based) follow me.
And it works great :)

**Pull request merged**
