### PR TITLE
GubeGreen: Add OREOLED support for Solo

### PR DESCRIPTION
**Pull request by AndKe**
Fixes Issue: https://discuss.ardupilot.org/t/4-1-4-issue-with-oreoled-greencube-solobuild/81655

### CODE REVIEW

**Comment by rmackay9** [comment]
@AndKe,

Could you change the commit description to, "AP_HAL_ChibiOS: add OREOLED to CubeGreen"?  We like to have clearer descriptions on commits because it makes backporting easier.

FYI @bugobliterator

**Comment by rmackay9** [comment]
@AndKe,

Just to be clear, it's the commit title that should be changed not the PR title..

**Comment by bugobliterator** [comment]
> @AndKe,
> 
> Just to be clear, it's the commit title that should be changed not the PR title..

As @rmackay9 mentioned needs to fix commit title. Other than that all good.

**Comment by AndKe** [comment]
Thanks! @rmackay9 and @bugobliterator  - it's fixed now.

**Review by andyp1per — APPROVED** [review]

**Comment by peterbarker** [comment]
Rebased to fix conflicts.

**Pull request merged**
