### PR TITLE
GPS: Raise the number of leap seconds

### PR DESCRIPTION
**Pull request by WickedShell**
Follows the discussion from #5510 and the dev call this raises the number of hard coded leapseconds to be current.

### CODE REVIEW

**Comment by amilcarlucas** [comment]
I think there are more GPS device drivers in the code with an hardcoded 15.
I'll take a look to see if I find them

**Comment by WickedShell** [comment]
Thanks!

**Comment by amilcarlucas** [comment]
AP_GPS.cpp:599
GPS__Backend.cpp:113

**Comment by OXINARF** [comment]
Merged, thanks!

**Pull request merged**
