### PR TITLE
Copter 4.1  PAW3903/3902 OpticalFlow sensor

### PR DESCRIPTION
**Pull request by svs072477**
Hi, I add support for PAW3903/3902 OpticalFlow sensor with auto  mode switching depending on the light.
But I do not know how to output the current mode to GCS messages.
Perhaps this modification will be useful and included in future releases.
File in attach
[AP_OpticalFlow.zip](https://github.com/ArduPilot/ardupilot/files/8055464/AP_OpticalFlow.zip)

### CODE REVIEW

**Comment by rmackay9** [comment]
Thanks for the contribution.  So I guess this PR is to add support for the [ARK Flow Sensor](https://arkelectron.com/product/ark-flow/)?  We are very interested in getting support for this flow sensor.

According to the web page the ARK flow sensor has a UAVCAN (aka DroneCAN) interface so it should work if FLOW_TYPE = 6 (DroneCAN) similar to the [HereLink flow sensor](https://ardupilot.org/copter/docs/common-hereflow.html).

By the way, we've got some [advice here on the wiki regarding raising PRs](https://ardupilot.org/dev/docs/submitting-patches-back-to-master.html).

**Comment by svs072477** [comment]
> Thanks for the contribution. So I guess this PR is to add support for the [ARK Flow Sensor](https://arkelectron.com/product/ark-flow/)? We are very interested in getting support for this flow sensor.
> 
> According to the web page the ARK flow sensor has a UAVCAN (aka DroneCAN) interface so it should work if FLOW_TYPE = 6 (DroneCAN) similar to the [HereLink flow sensor](https://ardupilot.org/copter/docs/common-hereflow.html).
> 
> By the way, we've got some [advice here on the wiki regarding raising PRs](https://ardupilot.org/dev/docs/submitting-patches-back-to-master.html).

Hi, I added support for PAW3902 because I replaced PMW3901 with it on my flight controller. I don't have APK Flow sensor, if I buy it, I'll try to make it support in Ardupilot.

**Comment by rmackay9** [comment]
I've created a branch here with your changes to the AP_Optical flow library.  https://github.com/rmackay9/rmackay9-ardupilot/commits/pixart-3903

If you send me your email somehow or point me at a commit you've done somewhere on github I'll change the commits so they are attributed to you.

**Comment by rmackay9** [comment]
I've closed this PR in favour of https://github.com/ArduPilot/ardupilot/pull/20100.  I just want to be sure this work isn't lost.

**Comment by rmackay9** [comment]
@svs072477 is there somewhere I can purchase one of these sensors on a breadboard so I can test it?

**Comment by svs072477** [comment]
> @svs072477 is there somewhere I can purchase one of these sensors on a breadboard so I can test it?

 We purchase paw3903 from Pixart directly, we needed 200 pieces. And it took a very long time

**Pull request closed without merging**
