### PR TITLE
Fix to Dual-Heli servo_test feature

### PR DESCRIPTION
**Pull request by bnsgeyer**
The fix to the Dual-heli servo_test function was only completed on the single heli frame.  This fixes the servo test function for the dual heli frame.

### CODE REVIEW

**Comment by rmackay9** [comment]
Are these in master yet?  I don't immediately see them in master..

**Comment by rmackay9** [comment]
I'm 99% sure these aren't in master yet.  So I'm not too comfortable just pushing these straight into the release candidate.  It's better instead to get them into master and then they can go out with the next point release.  I wasn't planning on doing any more release for Copter-3.5 (unless something serious came up).. but we can discuss that..

**Comment by rmackay9** [comment]
Merged to Copter-3.5 and master, thanks!

**Comment by bnsgeyer** [comment]
@rmackay9 sorry i was going to submit  them to master as well.   I will get them submitted today

**Comment by OXINARF** [comment]
@bnsgeyer Randy merged this to master already, no need to submit it anymore 🙂

**Pull request closed without merging**
