### PR TITLE
Refactoring use pragma once

### PR DESCRIPTION
**Pull request by RuffaloLavoisier**

### CODE REVIEW

**Comment by RuffaloLavoisier** [comment]
@IamPete1 
It's sad, but if it doesn't work, please close it

**Review by magicrub — CHANGES_REQUESTED** [review]
I agree with @IamPete1 , the changes look good except for the lua ones. Best to just leave those alone for smoother library upgrades in the future. Can you remove those?

**Comment by RuffaloLavoisier** [comment]
@magicrub 
Sorry I'm late. I modified it.

**Comment by peterbarker** [comment]
All of the files being changed in this PR come from external sources.

You can see that in the conflicting files here - they're sources from the PiccoloCAN development team, copied into our repository.

These really need to be changed in the originator source repositories, not in ArduPilot, or the changes will continually get lost when the files are updated from the external source.

Thanks for looking at this - `#pragma` is much nicer than the older style stuff you're replacing in here.  It's just not the right repo to be making the changes in.

**Pull request closed without merging**
