### PR TITLE
IOMCU: fixed inability to regain RC input 

### PR DESCRIPTION
**Pull request by tridge**
This fixes an issue where loss and regain of an RC receiver can sometimes result in not regaining RC input.
The sequence of events that leads to this bug with SBUS are:
 - normal startup and SBUS detection
 - loss of SBUS input, rc.cpp starts changing the config of SD3 every 2s between 100 and 115 kbaud, switching sd3_config variable from 0 to 1 (0 means 100000 config)
 - RC input is restored while the port is in sd3_config=1 state
 - the line transitions of the SBUS signal will occasionally produce an input byte on either SD1 or SD3 even though the inversion/baud/parity is incorrect. These occasional spurious bytes are enough to keep rc_stats.last_good_ms within 2000ms of the current time, which means we never swap sd3_config back
 - user does not get RC input back

With a protocol like Fport which is 115200 inverted the sequence is similar, but sd3_config is in 0 state when the RC input comes back

Note that the ability to reproduce this bug can depend on the exact RC input values when RC is restored, so a single 1us change in trim, or switches can change the result as it changes if the protocol bytes can be mis-interpreted as valid bytes on the wrong baudrate or inversion

Note: this bug affects 4.2, 4.3, 4.4 and master. It affects any setup with a receiver that sends no pulses when RC input is lost
Also note that the bug is probabilistic. Some setups will have the bug more often than others. The difference can be just in the exact stick trim at the time RC is regained, resulting in a slightly different pattern of bits in the RC input stream

### CODE REVIEW

**Comment by andyp1per** [comment]
Do we know why this only affects the iofirmware? Also I don't understand the DSM/SBUS logic - a comment to that effect might be helpful

**Comment by cuhome** [comment]
@tridge Please check if the bug caused by this pr.:https://github.com/ArduPilot/ardupilot/pull/22844

**Comment by pompecukor** [comment]
I have to learn to report everything. we were victims of this bug and did not realize it was from the firmware, we automatically assumed it was the link that we were using. Should have reported and had the log checked. Anyway good find.

**Comment by tridge** [comment]
> @tridge Please check if the bug caused by this pr.:#22844

it is closely related, but the bug was there before that PR

**Comment by tridge** [comment]
> And 4.33 higher firmware has this bug.

The bug was first introduced in this PR in January 2020:
https://github.com/ArduPilot/ardupilot/pull/12945
It was included in the 4.0.6 release. All versions after that have had the bug. Some later changes may have changed the probability of the bug happening, but that is where the bug itself started.

**Review by bugobliterator — APPROVED** [review]

**Comment by tridge** [comment]
> Do we know why this only affects the iofirmware? Also I don't understand the DSM/SBUS logic - a comment to that effect might be helpful

yes, we know why it is iofirmware only, as the bug is in iofirmware/rc.cpp which is only in the IO firmware.

**Pull request merged**
