### PR TITLE
Send Geofence Breach message to the GCS

### PR DESCRIPTION
**Pull request by timtuxworth**
Without this, if the plane breaches the geofence, there is no notification in the GCS.

### CODE REVIEW

**Comment by peterbarker** [comment]
> Without this, if the plane breaches the geofence, there is no notification in the GCS.

That's actually false; the GCS is informed of breaches using a the `FENCE_STATUS` message.  Problem is that they're not making that information prominent.  statustexts are prominent, but kind of a crap way to move information around.

OTOH - users using OSDs probably also won't get notification - and that's important.  I'm marking this for DevCall.

This branch needs a rebase - should just be the single commit.

**Comment by timtuxworth** [comment]
> > Without this, if the plane breaches the geofence, there is no notification in the GCS.
> 
> That's actually false; the GCS is informed of breaches using a the `FENCE_STATUS` message. Problem is that they're not making that information prominent. statustexts are prominent, but kind of a crap way to move information around.
> 
> OTOH - users using OSDs probably also won't get notification - and that's important. I'm marking this for DevCall.
> 
> This branch needs a rebase - should just be the single commit.

I get this when I try to "fetch from upstream", what am I doing wrong?
```
This branch is not behind the upstream ArduPilot:master.
No new commits to fetch. Enjoy your day!
```

**Comment by timtuxworth** [comment]
> > Without this, if the plane breaches the geofence, there is no notification in the GCS.
> 
> That's actually false; the GCS is informed of breaches using a the `FENCE_STATUS` message. Problem is that they're not making that information prominent. statustexts are prominent, but kind of a crap way to move information around.
> 
> OTOH - users using OSDs probably also won't get notification - and that's important. I'm marking this for DevCall.
> 
> This branch needs a rebase - should just be the single commit.

This is the only commit that matters, I'm not sure how the other stuff got in there, sorry about that:
53fdcfd616c52b1edee22067694c16db71f44c0e

**Comment by peterbarker** [comment]
@timtuxworth https://ardupilot.org/dev/docs/git-interactive-rebase.html

**Comment by timtuxworth** [comment]
I made a bit of a mess of my repo, so I decided to start again from scratch. See my new PR here: https://github.com/ArduPilot/ardupilot/pull/20275

**Pull request closed without merging**
