### PR TITLE
Rover first motorlib

### PR DESCRIPTION
**Pull request by khancyr**
This create the base for a motor library for rover.
It separted the motor ouput handling and mixing in a library.
It also add support for different pwm type and and frequecies

### CODE REVIEW

**Comment by amilcarlucas** [comment]
Nice stuff. We plan to add mecano wheels support on top of this stuff. Are you going to beat us to it ?

**Comment by khancyr** [comment]
@amilcarlucas mecano wheels ? you mean https://en.wikipedia.org/wiki/Omni_wheel ? The goal is to support more rover type more easily ! so feel free to add more mode ^^

**Comment by rmackay9** [comment]
@khancyr, I've had a look at the PR and I think it's definitely going in the correct direction.  I've put a couple of commits on top of this PR here: https://github.com/rmackay9/rmackay9-ardupilot/commits/khancyr-rover-motorlib.

What I've done is taken it a step further by mostly removing any direct setting of the outputs from the main vehicle code.

This basically works but there are a couple of things I've broken perhaps:

- the failsafe stuff is not properly feeding into the throttle
- auto check is also not fed in properly.

**Comment by khancyr** [comment]
@rmackay9 Rebased on your work and master. I correct skid steer in value, and slew rate.
Maybe the fix for slew rate isn't optimal : I move the slew rate param in MotorsUGV.
For brushed, I am a little mixed. We can support 2 types of brushed control  :
- the normal one (and cheaper), like those use with arduino board : They got input for pwm and a switch for direction. So we ouput a real pwm signal by calculating the duty cycle that is the power passed to the motor. So it need to put the trim at the min value (at 1500 we want 0% duty cycle) and only take the abs value of what is calculated by the mixer. The direction is handle by using relay.
- the pwm improved : like on Nick rover, that use duty cyle to also carry direction. Duty cycle > 50% is forward, and < 50% backward.

**Comment by rmackay9** [comment]
I've squashed and rebased your code and put into this new PR: https://github.com/ArduPilot/ardupilot/pull/6547

I'm closing this PR if that's OK.

**Pull request closed without merging**
