### PR TITLE
autotest: rename common.py to vehicle_test_suite.py

### PR DESCRIPTION
**Pull request by peterbarker**
Having a file called "AutoTest not providing the object AutoTest is confusing, so rename both the file and the object that is created.

This should allow factoring of `autotest.py` in the future.

### CODE REVIEW

**Review by tridge — APPROVED** [review]

**Comment by magicrub** [comment]
needs a rebase

**Comment by peterbarker** [comment]
> needs a rebase

Done, thanks

**Comment by peterbarker** [comment]
@khancyr do you think this is OK?

**Comment by khancyr** [comment]
@peterbarker fine by me. can merge!

**Comment by Ryanf55** [comment]
Ideally, this wiki page needs update: https://ardupilot.org/dev/docs/the-ardupilot-autotest-framework.html#autotest-structure

**Pull request merged**
