### PR TITLE
waf: make build a little bit smarter about submodules

### PR DESCRIPTION
**Pull request by guludo**
Hi all,

This PR adds two fixes in order to make the build system a little bit smarter with respect to submodules:

1. Don't try to load 'git_submodules' and consequently don't update submodules if the source directory isn't a git repository. That's useful for release tarballs.
2. Don't cause trouble to developers working on submodules by updating submodules if the update isn't recursively fast-forward (with respect to the submodule's current HEAD).

Best regards,
Gustavo Sousa

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
I think this is great. Maybe also add a way so that if the user exports an env var like ARDUPILOT_NO_SUBMODULE_UPDATE it skips the submodule update.

**Comment by tridge** [comment]
works for me, thanks!

**Comment by tridge** [comment]
we may need a bit more error checking. Just got this:
./modules/waf/waf-light plane
Waf: Entering directory `/home/tridge/project/UAV/APM/build/sitl-debug'
Waf: Leaving directory `/home/tridge/project/UAV/APM/build/sitl-debug'
Build failed
Traceback (most recent call last):
  File "/home/tridge/project/UAV/APM/modules/waf/waflib/Runner.py", line 270, in task_status
    return tsk.runnable_status()
  File "Tools/ardupilotwaf/git_submodule.py", line 90, in runnable_status
    if not self.is_fast_forward(path):
  File "Tools/ardupilotwaf/git_submodule.py", line 62, in is_fast_forward
    bld.fatal('git_submodule: failed to parse diff')
  File "/home/tridge/project/UAV/APM/modules/waf/waflib/Context.py", line 481, in fatal
    raise self.errors.ConfigurationError(msg, ex=ex)
ConfigurationError: git_submodule: failed to parse diff

this is the output of git diff:
tridge@blu:~/project/UAV/APM/ArduPlane(ap-icengine)$ git diff
Submodule modules/mavlink 5d736ca..bacc88d:
  > common.xml: added MAV_CMD_DO_ENGINE_CONTROL

**Comment by guludo** [comment]
Thanks for the feedback, Tridge! I'll take a look

**Comment by guludo** [comment]
@tridge I think you probably have `diff.submodule` as "log" on your git config. I just pushed a new version with an explicit "--submodule=diff" on the git-diff command. Could you please check if that fixes the issue?

**Comment by guludo** [comment]
Oops "--submodule=short", actually.

**Comment by guludo** [comment]
@lucasdemarchi What should the contents of `ARDUPILOT_NO_SUBMODULE_UPDATE` be? The submodules no to be updated?

**Comment by lucasdemarchi** [comment]
@guludo I think that if this env var is exported (with any value), we should tweak both configure and build phases to skip the submodule update.

**Comment by OXINARF** [comment]
@lucasdemarchi Why is that needed? Just use the configure option...

**Comment by lucasdemarchi** [comment]
@tridge asked for something like that on gitter. Maybe what we have with
this PR is already sufficient, dunno.

An env var would be handy for developers who dislike the default of
updating submodules and don't want to type --no-submodule-update every
single call to configure

Em 25 de jul de 2016 2:01 PM, "Francisco Ferreira" <notifications@github.com>
escreveu:

**Comment by guludo** [comment]
I'd say we add the new feature without the env var and wait to see if the env var feature is really necessary.

**Comment by OXINARF** [comment]
> An env var would be handy for developers who dislike the default of
updating submodules and don't want to type --no-submodule-update every
single call to configure

My worry is that once we add an env var to an option, there will be people asking for other options and it turns into a maintenance nightmare.
Also why do people run configure so much? Maybe what we need to do is reduce the number of times configure is needed.

In the end I agree with @guludo, let's get this in and see if the env var is really needed.

**Comment by lucasdemarchi** [comment]
Fair enough. In it is. Thanks!

**Pull request closed without merging**
