### PR TITLE
Change optimisation from -O3 to -O2

### LINKED ISSUE #12413: Code size blowout - sparky2 no longer conmpiling
### Bug report

**Issue details**

We've blown the code size out enough that sparky2 is no longer compiling.

The relevant commits *really* shouldn't have led to this blow-out.

**Version**

```
9b746b89db bin/arduplane  975968  1272  129976  1107216
0041874826 bin/arduplane  980544  1272  129976  1111792
96c6544997 BAD
255981c60c BAD
```

Failure on 96c6544997:
```
/home/pbarker/gcc-arm-none-eabi-6-2017-q2-update/bin/../lib/gcc/arm-none-eabi/6.3.1/../../../../arm-none-eabi/bin/ld: bin/arduplane section `.text' will not fit in region `flash'
/home/pbarker/gcc-arm-none-eabi-6-2017-q2-update/bin/../lib/gcc/arm-none-eabi/6.3.1/../../../../arm-none-eabi/bin/ld: region `flash' overflowed by 4452 bytes
collect2: error: ld returned 1 exit status
```

From git log:
```
96c654499796d0cd3fc6d5121f69eff91db8de7b AP_NavEKF3: moved intermediate variable
s to common memory
00418748268177e85a16a84572b12d9c1c8fef32 AP_NavEKF2: moved intermediate variable
s to common memory
9b746b89dbe49637b09edfccb9c902ad78671809 AP_Math: added fill_nanf()
```

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[ X ] Plane
[  ] Rover
[  ] Submarine

**Hardware type**
sparky2

### PR DESCRIPTION
**Pull request by tridge**
This changes optimisation of math intensive code from -O3 to -O2. A test on a F427 of the EKF2 code shows this is actually slightly faster (although the difference is very small, less than 1 percent).
This lowers flash usage on fmuv2 by about 13k
fixes #12413

### CODE REVIEW

**Comment by WickedShell** [comment]
This actually lowers the optimization level on all boards though including boards that are otherwise set to O3 (mostly just seems weird to step back the EKF explicitly in that case). Do we really want to do that? It's also worth noting that the entire savings of this is less then the additional usage that 2 EKF patches introduced to master recently.

**Comment by tridge** [comment]
@WickedShell I'm tempted to change the -O3 on the 2M flash boards to -O2 as well. It looks like -O3 is not really a win, and probably even more so on the high end boards that have data and instruction caches

**Comment by WickedShell** [comment]
@tridge Yeah, I'm definitely not opposed to benchmarking and being lead by that, I am a bit opposed to just changing it for the sake of flash fitting :D

**Comment by tridge** [comment]
I've now changed the high end boards to use -O2, and added easy to use code for benchmarking EKF2.
Results on H743 based board:

 - with -O1 55us
 - with -O2 49us
 - with -O3 52us
 - with -Os 51us

so O3 was actually a very poor choice for H7. -Os would have been better!

**Comment by Jaaaky** [comment]
> I've now changed the high end boards to use -O2, and added easy to use code for benchmarking EKF2.
> Results on H743 based board:
> 
>     * with -O1 55us
> 
>     * with -O2 49us
> 
>     * with -O3 52us
> 
>     * with -Os 51us
> 
> 
> so O3 was actually a very poor choice for H7. -Os would have been better!

What about fmuv3 boards?
I can recall well that I've got lower load on it with O3 than O2 and Os.

**Comment by Jaaaky** [comment]
Here are my results on Pixhawk1:
So I think it has a clear benefit there.

O3
ekf2 avg 95.57 us

O2
ekf2 avg 98.90 us

O1
ekf2 avg 102.49 us

Os
ekf2 avg 107.80 us

**Pull request merged**
