### PR TITLE
AP_NavEKF2:Added switching offset to baro height data

### PR DESCRIPTION
**Pull request by apinxiko**
If the vehicle flies within the range of e.g. 30m x 10m and zigzag path with Lightware SF11 Lidar installed, cumulative altitude issue can then be confirmed under the condition that the range finder is not used as the primary height source when the horizontal ground speed is greater than EK2_RNG_USE_SPD. This could only result from the combination of  EK2_ALT_SOURCE = 0 and EK2_RNG_USE_HGT = 70.

alt_baro_rnguse_70

By determining that we use offset to baro resulting from other height source once immediate after switching back to baro height use, this could be circumvented as follows.

alt_baro_rnguse_70_mod

### CODE REVIEW

**Comment by amilcarlucas** [comment]
please use `git rebase master` and `git push -f` to clean the comits

**Comment by OXINARF** [comment]
@apinxiko This change doesn't make sense to me; we only calculate the offset when we aren't using baro and after we return to using baro we want to use the offset so that the height doesn't have a jump - if we only use it once, how is it useful?
I'm also failing to see how your second graph is better than the first, CTUN.Alt doesn't seem to follow neither baro nor rangefinder.

Let's see what @priseborough has to say though.

**Comment by apinxiko** [comment]
I admit that my second result is not so good in a way that not only is baro height drift confirmed but CTUN.Alt does follow the slight different path as compared with CTUN.SAlt and CTUN.BAlt.

The most important thing for this pr is that CTUN.Alt ends up hitting FENCE_ALT_MAX eventually, so EKF altitude also shown on the mission planner is important.

This pr comes off as nothing more than cumulative CTUN.Alt and CTUN.DAlt can tentatively be minimized so that they don’t hit FENCE_ALT_MAX eventually.

**Comment by rmackay9** [comment]
I think what's very odd about this log (I have a copy but it can be seen in the top graph as well) is that the CTUN.Alt (EKF altitude above home) and the CTUN.BAlt (barometer altitude above ekf origin) do not agree even though EK2_ALT_SOURCE = 0 (use baro).  Perhaps the EKF is using the range finder if the EK2_RNG_USE_HGT > 0.  Even if this is true though, I don't see what is causing the EKF's altitude to drift upwards.  As Francisco says, I think we need some input from @priseborough.

**Comment by apinxiko** [comment]
Assuming that we set “EK2_ALT_SOURCE = 0 (use baro)”….

As we can see within the method of “selectHeightForFusion”, if the vehicle speeds up greater than “EK2_RNG_USE_SPD (RngSwSpd)”, “activeHgtSource” turns out become “HGT_SOURCE_BARO”, then the vehicle uses primary barometer based alt source.

Also, if the vehicle slows down less than “EK2_RNG_USE_SPD (RngSwSpd)”, as rmackay9 says, EKF is then using rangefinder based alt source instead (i.e. “activeHgtSource” turns out to be “HGT_SOURCE_RNG”).

If the vehicle undergoes these two situations repeatedly, “baroHgtOffset” given by the method of “calcFiltBaroOffset” is gradually growing in a positive or negative direction (depending upon its offset values between barometer and rangefinder, though).

So, we need to minimize curb growth in baroHgtOffset, which is also taken into account in the equation of “hgtMea = baroDataDelayed.hgt - baroHgtOffset” as much as possible.

**Comment by priseborough** [comment]
This is caused by ratcheting of the baro offset as the vehicle repeatedly switches between range  range and and baro fusion. Potential mitigators include:

1) Ensure that the range finder to IMU body frame position offset is represented correctly in the parameters.
2) Ensure installation minimises baro errors caused by attitude changes in wind
3) Add a hysteresis time so that it will remain in baro mode for longer when dropping below the speed threshold

This PR will not fix the underlying issue and may cause other problems if the vehicle is being flown up and down terrain changes.

**Comment by priseborough** [comment]
Can you provide a link to your log?

**Comment by priseborough** [comment]
I've checked the code and the baro height offset which is a low pass filtered difference between the baro height measurement and the EKF vertical position state is only updated whenever the EKF is using a height source other than the baro.

https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_NavEKF2/AP_NavEKF2_Measurements.cpp#L594

This means when the vehicle is being flown slowly and is using range finder, the ground is the zero height datum. This has implications if the vehicle is flown slowly up or down a slope.

The original use case for the EK2_RNG_USE_HGT (and EK2_RNG_USE_SPD) parameter feature was for a vehicle doing a vertical takeoff and landing, climbing above range finder height, flying a mission, then landing with a vertical descent. It was not designed for terrain following.

**Comment by apinxiko** [comment]
@priseborough I understand the case example given by EK2_RNG_USE_HGT along with EK2_RNG_USE_SPD is not intended to do manual terrain following. So we may have to add a delay or hysteresis time so that it will remain in baro mode for longer when dropping below EK2_RNG_USE_SPD so as to prevent underlying issues from causing other problems when undergoing terrain changes.

**Comment by priseborough** [comment]
For terrain following it would be better to continue to use baro as the height reference and use the terrain estimator output in the height controller.

**Comment by OXINARF** [comment]
@apinxiko I'm closing this as it doesn't fix the actual issue neither implements the proposed fix (adding a hysteresis time to remain in baro time longer when going below the speed set in EK2_RNG_USE_SPD). 
However, I thank you for your contribution, feel free to open a new PR with the proposed change.

**Pull request closed without merging**
