### PR TITLE
Fixed IMU reset issue on F35Lightning

### PR DESCRIPTION
**Pull request by tridge**
This fixes the underlying issue for IMU FIFO resets on the F35Lighting. It re-enables fast sampling (disabled in #15097) and adds an internal error in case other boards suffer from this issue.
The basic problem was the SPI clock at 8MHz doesn't work reliably on this board

### CODE REVIEW

**Review by andyp1per — APPROVED** [review]

**Comment by vierfuffzig** [comment]
awesome, thanks a lot for looking into this. is this due to a hardware quality limitation of this individual board?

**Comment by tridge** [comment]
> awesome, thanks a lot for looking into this. is this due to a hardware quality limitation of this individual board?

I suspect the traces are just a bit marginal, and 8MHz gets too much corruption, but someone would need to do a much deeper look with a scope to find out. I'm just happy that a lower clock fixes it.

**Comment by vierfuffzig** [comment]
@tridge working great so far!
image

**Comment by tridge** [comment]
> @tridge working great so far!

thanks! merged

**Pull request merged**
