### PR TITLE
Move emit of primary-GPS-changed into AP_GPS

### PR DESCRIPTION
**Pull request by peterbarker**
This wasn't really a sensor-health thing, either....

New addition to the blending test ensures we see the message come out in the log

This change will mean all vehicles can expect to see this event emitted.

### CODE REVIEW

**Review by amilcarlucas — APPROVED** [review]
Nice change

**Review by tridge — APPROVED** [review]

**Comment by rmackay9** [comment]
As discussed, let's initialise the primary value so we don't get a message in the log every time soon after startup.

**Comment by peterbarker** [comment]
Incidentally, I'm kind of the opinion it would be OK to retain the current behaviour of logging a primary change if you're set up to not-auto-switch *and* not auto-switching.  It's an atypical setup and we could save flash and complexity.

**Comment by peterbarker** [comment]
I've added the requested change - so now we don't emit this message for any change on the first loop, which is what will happen if you *both* set `GPS_PRIMARY` to (e.g.) 1 *and* change `GPS_AUTO_SWITCH` to zero.

Initialising the `primary_instance` state to be equal to the `GPS_PRIMARY` variable is insufficient without also checking `GPS_AUTO_SWITCH`.  While we probably *should* honour `GPS_PRIMARY` even at initialisation regardless of `GPS_AUTO_SWITCH` being on or off, this patch should still be the same shape IMO - leave the logic in `update_primary`, don't duplicate it in initialisation.

**Comment by peterbarker** [comment]
Oh.  Tested in SITL by setting `LOG_DISARMED`, `GPS_PRIMARY` and `GPS_AUTO_SWITCH` and checking what `EV` messages got emitted.

**Review by tridge — APPROVED** [review]

**Pull request merged**
