### PR TITLE
Tools: remove sim_vehicle.sh

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by tridge** [comment]
this doesn't work yet. It probably works for simple uses of sim_vehicle.sh, but not more complex ones. 
For example, here is how I typically do helicopter testing:
sim_vehicle.sh -b sitl-heli-debug -j4 -f flightaxis:192.168.2.48 --console --map
I don't know how to do that with sim_vehicle.py

**Comment by peterbarker** [comment]
After the first patch in this series:

../Tools/autotest/sim_vehicle.py --debug -f heli --model flightaxis:192.168.2.48 --console --map

**Comment by tridge** [comment]
i've brought in the two patches to sim_vehicle.py, but not the removal of sim_vehicle.sh. I'll try to exclusively use the python version for a while and see if I can do everything needed. I also need to check that Leonard can use the python script (last time it didn't work for him)
thanks!

**Comment by lucasdemarchi** [comment]
@tridge any news?

**Comment by magicrub** [comment]
my sim_vehicles.py is working on Windows now but I'm still not comfortable removing .sh

**Comment by lucasdemarchi** [comment]
Let's apply or close this?

**Comment by gmorph** [comment]
My feedback I've only been using the .py for Rover SITL testing on Linux and haven't had any issues.  I'm ok with removing the .sh as I'm no longer using it anyway.  But I can't speak for the Windows users.

**Comment by lucasdemarchi** [comment]
@magicrub we can always revert this commit later and bring it back if it proves challenging to polish sim_vehicle.py. Are you opposed to it?

**Comment by magicrub** [comment]
I've been using the .py lately on Windows and it's working good. I'm ok removing sim_vehicle.sh as long as we keep make px4-v2 available.

**Comment by lucasdemarchi** [comment]
Yep, this is only for sitl, not touching the build system for pixhawk.

**Comment by lucasdemarchi** [comment]
Applied, thanks.

**Pull request closed without merging**
