### PR TITLE
Rover: move motors lib to own directory

### PR DESCRIPTION
**Pull request by IamPete1**
This is just a move of `AP_MotorsUGV` to its own `AR_Motors` directory

This means we have to compile 1 less file on copter and plane and 15 fewer files on Rover, should speed up builds all round (a tiny bit anyway). 

No change in flash size as the unneeded files were never linked despite being compiled. I found this when a bug in `AP_MotorsUGV.cpp` stopped me compiling plane.

### CODE REVIEW

**Review by khancyr — COMMENTED** [review]
Hummm , I am not against moving the lib, but that won't fix the issue correctly. 
Something is wrong as we use vehicle libs from libraries level without even a compilation guard.
Nice finding, let's solve this

**Comment by rmackay9** [comment]
I'm ok with this but can you fix the description of the first commit?

**Comment by IamPete1** [comment]
@rmackay9 done, hopefully that is better, i'm never very sure what to call stuff that crosses over directory's like that.

**Comment by rmackay9** [comment]
Merged, thanks!

**Pull request merged**
