### PR TITLE
AP_HAL_ChibiOS: Add RADIX2HD target (4.4 backport)

### PR DESCRIPTION
**Pull request by mluessi**
Backport of the RADIX2 HD target for 4.4. 

Tools PR for board ID: #24898 

Note: Needs #24896 to compile successfully.

### CODE REVIEW

**Review by andyp1per — APPROVED** [review]

**Comment by mluessi** [comment]
Updated it to use a custom `STM32_PLL1_DIVQ_VALUE`, so it works with update #24896

**Comment by mluessi** [comment]
Please let me know if anything else is needed. It would be nice to get this into 4.4.

**Review by andyp1per — APPROVED** [review]

**Comment by andyp1per** [comment]
A reasonable candidate for 4.4.1 I think @tridge @rmackay9

**Review by tridge — APPROVED** [review]

**Comment by mluessi** [comment]
@andyp1per @tridge thank you. Glad it made it in :)

**Pull request merged**
