### PR TITLE
get Marvelmind to work without a compass

### PR DESCRIPTION
**Pull request by amilcarlucas**
Original from Hendrik at http://www.marvelmind.com/forum/viewtopic.php?f=2&t=808&start=36 
This is just WIP do get the ball rolling

### CODE REVIEW

**Comment by WickedShell** [comment]
@amilcarlucas are you still working on this, or can it be closed?

**Comment by amilcarlucas** [comment]
I hope I can work on this, next February

**Comment by OXINARF** [comment]
@amilcarlucas This has been open for more than a year, always as a WIP, with code that isn't mergeable. As such, I'm closing this, but feel free to re-open once you have something ready to be contributed.

**Comment by amilcarlucas** [comment]
We have now an almost working alternative solution.
We will post wiki PRs once we are done.

Thanks for digging this up, and closing it.

**Comment by chobitsfan** [comment]
Hi @amilcarlucas
I am using motion capture system for copter indoor flight. Because of indoor mag interference, I am trying to use orientation from motion capture system to replace compass on copter.  Would you be able to give some advice or sharing your work on this (use orientation from external system instead of compass). Thank you very much

**Pull request closed without merging**
