### PR TITLE
IOFW: fixed memory usage of IO firmware

### PR DESCRIPTION
**Pull request by tridge**
This is a quick fix for the memory usage on the IOMCU. I am preparing a more complete fix

### CODE REVIEW

**Review by andyp1per — CHANGES_REQUESTED** [review]
This doesn't fix the problem - I am still unable to update the IOFW on latest master, I think its a communication issue rather than a size issue

**Comment by andyp1per** [comment]
Upload failure is caused by
```
1e5d9fb2997bea1cc6c80d9a0a1ea15cd0353eac is the first bad commit
commit 1e5d9fb2997bea1cc6c80d9a0a1ea15cd0353eac
Author: Pierre Kancir <pierre.kancir.emn@gmail.com>
Date:   Mon Nov 2 18:46:48 2020 +0100

    Copter: set initial mode on startup
```
@khancyr  ?

**Comment by khancyr** [comment]
Hummm my PR doesn't touch anything related to iofw.

**Comment by khancyr** [comment]
Did you check on another vehicle than copter ?

**Comment by andyp1per** [comment]
I'm afraid the evidence is incontrovertible 😄 I've just reverted that change on master and the problem goes away

**Comment by andyp1per** [comment]
... and with that reverted and this PR I am finally able to update the IO firmware to the latest!

**Review by andyp1per — APPROVED** [review]

**Pull request merged**
