### PR TITLE
Tools: add Debian 12 support to prereqs script

### PR DESCRIPTION
**Pull request by yuri-rage**
Added `bookworm` alongside `lunar` and `mantic`.

Tested via Proxmox LXC container(s) running fully updated Debian 12 instances.

### CODE REVIEW

**Review by khancyr — COMMENTED** [review]
Excellent 👍, will give a try tomorrow

**Comment by yuri-rage** [comment]
> > Excellent 👍, will give a try tomorrow
> 
> Can we get any CI images to add this to the test environment job? Great to see this work done so early.

Happy to help, but I'm afraid I'm quite unfamiliar with test environment so may need a little hand-holding there.

I see you made an empty commit on the `.vscode` file warning not to override editor defaults. Would you be open to a PR to include the following, which makes the default bash interactive shell a login shell? If this setting is not present in an otherwise default environment, `.profile` is ignored in VS Code's terminal, and most of the bash-centric goodness that gets incorporated by the prereqs script is moot. It does not override the default shell, so those using zsh or fish, for example, would be unimpacted.

```
  "terminal.integrated.profiles.linux": {
    "bash": {
        "path": "bash",
        "args": [
            "-l"
        ]
    },
```

**Comment by Ryanf55** [comment]
> > > Excellent 👍, will give a try tomorrow
> > 
> > 
> > Can we get any CI images to add this to the test environment job? Great to see this work done so early.
> 
> Happy to help, but I'm afraid I'm quite unfamiliar with test environment so may need a little hand-holding there.
> 
> I see you made an empty commit on the `.vscode` file warning not to override editor defaults. Would you be open to a PR to include the following, which makes the default bash interactive shell a login shell? If this setting is not present in an otherwise default environment, `.profile` is ignored in VS Code's terminal, and most of the bash-centric goodness that gets incorporated by the prereqs script is moot. It does not override the default shell, so those using zsh or fish, for example, would be unimpacted.
> 
> ```
>   "terminal.integrated.profiles.linux": {
>     "bash": {
>         "path": "bash",
>         "args": [
>             "-l"
>         ]
>     },
> ```

Yea, go for it. That seems like an obvious improvement.

**Comment by khancyr** [comment]
@Ryanf55 the test environement should use a default distribution image that is what we do. So no need for new CI image.

**Review by khancyr — APPROVED** [review]
tested with docker. works fine

**Pull request merged**
