### PR TITLE
AP_Soaring: Remove redundant ALERT messages

### PR DESCRIPTION
**Pull request by samuelctabor**
- Remove debug messages encountered in normal operation that don't result in an action, previously sent at ALERT priority.
- Update remaining messages to reference the relevant parameter names.

### CODE REVIEW

**Comment by davidbuzz** [comment]
looks good to me.

**Review by peterbarker — CHANGES_REQUESTED** [review]
Second commit message should be `Plane: mode_thermal: adjust messages to reference parameter names`

On that subject, 'though - by making that change you are coupling two pieces of code in different files - i.e. if you change the way we determine that the thermal has ended in AP_Soaring (add another parameter, source data from somewhere else, ....) then the message we send in mode_thermal.cpp` will almost certainly be forgotten and we'll give the user misleading information.  The plain-English versions match the enumeration value names, so they don't suffer from that same problem.  This is not a blocker - I'm just noting this new coupling.

**Comment by samuelctabor** [comment]
> Second commit message should be `Plane: mode_thermal: adjust messages to reference parameter names`
> 
> On that subject, 'though - by making that change you are coupling two pieces of code in different files - i.e. if you change the way we determine that the thermal has ended in AP_Soaring (add another parameter, source data from somewhere else, ....) then the message we send in mode_thermal.cpp` will almost certainly be forgotten and we'll give the user misleading information. The plain-English versions match the enumeration value names, so they don't suffer from that same problem. This is not a blocker - I'm just noting this new coupling.

Thanks. Fixed the commit message and added a comment to AP_Soaring as a reminder to keep the messages in sync with the logic.

**Comment by samuelctabor** [comment]
Any further comments on this @peterbarker ? The CI failures are unrelated I think.

**Review by peterbarker — APPROVED** [review]

**Pull request merged**
