### PR TITLE
AP_CRSF_Telem: fix pitch direction

### PR DESCRIPTION
**Pull request by vierfuffzig**
i was under the impression we had fixed that previously in https://github.com/ArduPilot/ardupilot/pull/14946

### CODE REVIEW

**Comment by andyp1per** [comment]
@vierfuffzig no, your fix was wrong - I got pitch in the wrong direction with your original change. The current behavior is in line with what TBS tell me.

**Comment by vierfuffzig** [comment]
imho it‘s a convention issue, not so much about right or wrong ;) obviously this inverts ardupilot pitch direction. current handling however breaks compatibility with existing openTX lua-scripts that follow bf/inav convention obviously, and afaik there‘s no simple way to invert a telemetry sensor value in your transmitter.

**Comment by andyp1per** [comment]
@vierfuffzig I tried this on my CRSF setup - pitch goes it in the correct direction when I look at the values in MP. So something else is going on here.

**Comment by vierfuffzig** [comment]
afaik there‘s no standardized utilisation of transmitter-based crsf telemetry in the ardupilot environment as for now. crsf-to-mavlink forwarding to my knowledge only works via bt using the fullsize crosssfire TX module. this will likely show correct pitch direction on mavlink GCSes as is. udp forwarding however does not work on the microTX yet (as of fw 4.03), so the only viable use in that hardware setup is transmitter-based lua scripts that are streamlined for bf/inav. those however afaik use inverted pitch convention (as we‘re using -ahrs.pitch on osd horizon as well, as it is based on the bf horizon code).
what we really need most likely is an openTX telemetry script streamlined for ardupilot use that will fully support ardupilot flightmode / arm - message handling as well, plus fixing crsf-to-mavlink-udp on the microTX / tango hardware‘s wifi modules.

**Comment by andyp1per** [comment]
My test setup is not using malink at all - I am learning the CRSF telemetry values using OpenTX - these show nose up as pitch positive, which I think is what mission planner shows also?

**Comment by vierfuffzig** [comment]
yup, currently available telemetry scripts however do use inverted bf convention and there aren‘t too many alternatives right now afaik. you‘re absolutely right this isn‘t an ardupilot issue really.

**Comment by andyp1per** [comment]
Does mavlink publish the opposite sense?

**Comment by vierfuffzig** [comment]
did some more testing and i‘m gonna close this as you‘re completely right, pitch inversion needs to be set on the receiving end depending on what autopilot sw is used, which is kind of sad imho. sorry for wasting your time with this.

**Pull request closed without merging**
