### PR TITLE
Tools: adding log2param.py  (restore parameters from tlog or bin)

### PR DESCRIPTION
**Pull request by AndKe**
This tool let user restore configuration (make a .param) file based on a .bin or .tlog.
Parameter changes during the log are shown in console.
This is a good config recovery tool.

### CODE REVIEW

**Comment by khancyr** [comment]
very nice ! I love that !
Just, I am not sure we should restrict it to python 3

**Comment by peterbarker** [comment]
Shouldn't we enhance `mavparms.py` if required?


```
pbarker@bluebottle:~$ mavparms.py $TLOG | head
ACRO_LOCKING    0.000000
ACRO_PITCH_RATE 180.000000
ACRO_ROLL_RATE  180.000000
ADSB_ENABLE     0.000000
AFS_ENABLE      0.000000
AHRS_COMP_BETA  0.100000
AHRS_EKF_TYPE   2.000000
AHRS_GPS_GAIN   1.000000
AHRS_GPS_MINSATS 6.000000
AHRS_GPS_USE    1.000000
```

**Comment by peterbarker** [comment]
@AndKe the name was like that when I got here :-)  It's even more fun when you take into account:

```
pbarker@bluebottle:~$ mavparms.py $DFLOG | head
ACRO_LOCKING    0.000000
ACRO_PITCH_RATE 180.000000
ACRO_ROLL_RATE  180.000000
ADSB_ENABLE     0.000000
AFS_ENABLE      0.000000
AHRS_COMP_BETA  0.100000
AHRS_EKF_TYPE   2.000000
AHRS_GPS_GAIN   1.000000
AHRS_GPS_MINSATS 6.000000
```

My question still stands...

BTW, you might look through some of the other tools... things like `mavparmdiff.py`.  And some of the silly things you can do with `param diff` in MAVProxy.

**Comment by AndKe** [comment]
@peterbarker if you are asking "Shouldn't we enhance mavparms.py if required?" 
then yes, (when it's existence is known) 
- and no, if there is a plan to move to newer python anyway.
The mavparamdiff.py is a nice tool (except for the manic use of zeros).

- should I just close this PR ?

**Comment by peterbarker** [comment]
@AndKe PRs welcome to remove the instance number of zeroes in `mavparmdiff.py`.

Do you think we should add `mavparms.py` to the Wiki somewhere?  It obviously needs more advertising.

In the meantime, I think we should be enhancing the existing tools rather than duplicating effort.

**Comment by AndKe** [comment]
@peterbarker   - I might give it a shot sometime, right now I am well set with tools that do the job.
mavparms.py , and the geotag.sh both deserve/need a proper wiki page, if people discover tools like that, it  promotes more sophisticated uses, and helps discover other gems in the repository.   There are far too many users that don't even know about mavproxy.

**Pull request closed without merging**
