### PR TITLE
AP_HAL_ChibiOS: fix KakuteF4 PWM pinout

### PR DESCRIPTION
**Pull request by stephendade**
Similar to #10363 - the PWM pinout for the KakuteF4 was incorrect (Servo 1 and 3 were swapped). This patch fixes it.

I've tested with my KakuteF4 and it's all working good now.

### CODE REVIEW

**Comment by auturgy** [comment]
Which version?The ordering should be such that the signal pads on the AIO match the default ArduPilot motor order (unfortunately - our motor order is daft).

**Comment by stephendade** [comment]
Version 2.2, non-AIO.

I've got a V2 AIO somewhere ... I'll test it tomorrow evening

**Comment by stephendade** [comment]
@auturgy - good you asked about that! Turns out the Kakute V2 AIO has a different pinout again. So this patch isn't any good.

So we'll need different hwdefs for the AIO and non-AIO Kakute's.

I'm curious where the current hwdef came from ... was there a V1 Kakute somewhere that this hwdef fits?

**Comment by stephendade** [comment]
For those playing at home, the current servo_out mappings are:
KakuteF4 AIO (V2):
APM Servo1 = Kakute M2
APM Servo2 = Kakute M3
APM Servo3 = Kakute M4
APM Servo4 = Kakute M1

KakuteF4 non-AIO (V2.2):
APM Servo1 = Kakute M3
APM Servo2 = Kakute M2
APM Servo3 = Kakute M1
APM Servo4 = Kakute M4

**Comment by stephendade** [comment]
I've done a new PR to replace this - so closing.

**Pull request closed without merging**
