### PR TITLE
Tools: add HighwayField to locations.txt

### PR DESCRIPTION
**Pull request by CallanDaniel**
Add Highway Airfield (South Africa) to locations.txt

### CODE REVIEW

**Comment by peterbarker** [comment]
Is this literally the name of the airstrip on navigation maps and whatnot?

There are lots of airstrips around which could be *described* as "HighWayfield" - I'm a bit wary of putting in simply descriptive names.

**Comment by CallanDaniel** [comment]
@peterbarker Highway Airfield is the name registered with the South Africa Civil Aviation Authority (ZA-0115). I just shortened it to HighwayField for ease of calling it in SITL.

**Comment by peterbarker** [comment]
Merged, thanks!

**Comment by rmackay9** [comment]
Note that the commit should have been prefixed with "Tools:" or something similar.. Not a big deal but ..

**Comment by CallanDaniel** [comment]
Noted, thanks.

**Pull request merged**
