### PR TITLE
Plane: implement throttle suppression for quadplanes

### PR DESCRIPTION
**Pull request by tridge**
This implements automatic throttle suppression for quadplanes to avoid accidental motor startup on the ground

### CODE REVIEW

**Comment by magicrub** [comment]
would have been nice if it somehow tied into is_flying

**Comment by tridge** [comment]
the problem with using is_flying() is a circular dependency.

**Comment by magicrub** [comment]
what if the is_flying check has something like:
if (quadplane.active) { // or whatever that flag is
is_flying_probability = quadplane.last_motors_active_ms > 0 && quadplane.motors->get_throttle() > 0
}

**Comment by magicrub** [comment]
merged, thanks!

I'd like to see this converted to a bool return and be taken advantage of (CAREFULLY) in is_flying. I almost pre-preemptively converted this to bool for future use, but we can do that later.

**Pull request closed without merging**
