### PR TITLE
ArduCopter: Fix filename in header

### PR DESCRIPTION
**Pull request by mirkix**
Fix filename in header

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
Nice, thanks.

I slight different approach that I tend to prefer is: what if we just removed the filename from the comment, so we would have them like this: 

```
 /*
  * Init and run calls for acro flight mode
  */
```

instead of

```
 /*
  * control_acro.cpp - init and run calls for acro flight mode
  */
```

because you are already inside the file.

**Comment by lucasdemarchi** [comment]
@rmackay9 ?

**Comment by mirkix** [comment]
@lucasdemarchi OK, wait for @rmackay9

**Comment by rmackay9** [comment]
Sure, removing the file name from the comment makes sense to me.  Slightly related, in the past, when commenting a function we would put the name of the function into the comments but we've stopped doing that now.

**Comment by mirkix** [comment]
#4537

**Pull request closed without merging**
