### PR TITLE
Tools: Modernize Python 2 code to get ready for Python 3

### PR DESCRIPTION
**Pull request by cclauss**
Use http://python-future.org code to take a more automated and complete approach than #6833

Make the minimal, safe changes required to convert the repo's code to be syntax compatible with both Python 2 and Python 3. There would _definitely_ be much more work required to complete the port to Python 3 but this is a minimal, safe first step.

Run: `futurize --stage1 -w **/*.py`

See Stage 1: "safe" fixes http://python-future.org/automatic_conversion.html#stage-1-safe-fixes

$ `pip install future`
$ `git checkout -b modernize-python2-code`
$ `futurize --stage1 -w **/*.py` # done in zsh for ** globbing
$ `git commit --all -m "Modernize Python 2 code to get ready for Python 3"`
$ `git push --set-upstream origin modernize-python2-code`

### CODE REVIEW

**Comment by khancyr** [comment]
looks good, but could you rebase on master to remove the merge commit and the genmsg stuff ?

**Comment by cclauss** [comment]
@khancyr It would be awesome if you could help me understand how to do that.

I am so frustrated learning command line git.  Above I have provided the git commands that I used above to create the PR but I have so little success at doing things like:
* git commit --amend
* git reset ~HEAD
* git rebase squash
* rewriting history, etc.

I really need someone to mentor me thru git on the command line.  I have Git Pocket Guide and Git Pro but I still don't have a grasp on doing this stuff.  _Would you be willing_ to set up a junk repo in your account that I could practice on and you could advise me until I get rebase and merge commit mastered?  After that, I could come back here as squash like a git pro.  I will understand completely if you say no.

**Comment by khancyr** [comment]
git rebase is very simple, it takes the commit you chose as base and add your new commit on top of it. In case of rebasing on master, well, it take the last commit from master branch and put your commit on it.

The best thing is to do, git rebase -i master . That way git will ask you what you want to do with each of your commit. 
In your case, I would do, git rebase -i master . You should have something like on cmdline or on gui if you configure one
`````
 pick 2a0fad4d Modernize Python 2 code to get ready for Python 3
 pick 00ac856a Modernize Python 2 code to get ready for Python 3
 pick 043f469d Merge branch 'modernize-python2-code'

 # Rebase 170afb6..02e5bd1 onto 170afb6 (2 command(s))
 #
 # Commands:
 # p, pick = use commit
 # r, reword = use commit, but edit the commit message
 # e, edit = use commit, but stop for amending
 # s, squash = use commit, but meld into previous commit
 # f, fixup = like "squash", but discard this commit's log message
 # x, exec = run command (the rest of the line) using shell
 # d, drop = remove commit
 #
 # These lines can be re-ordered; they are executed from top to bottom.
 #
 # If you remove a line here THAT COMMIT WILL BE LOST.
 #
 # However, if you remove everything, the rebase will be aborted.
 #
 # Note that empty commits are commented out
````
Then do this 
````
 pick 2a0fad4d Modernize Python 2 code to get ready for Python 3
 f 00ac856a Modernize Python 2 code to get ready for Python 3
 f 043f469d Merge branch 'modernize-python2-code'
````
That will merge all your commit into the first one.
Now you have only one commit, you could either do a git reset HEAD~ , remove the genmsg modification and git add, git commit. Or also do a git rebase -i master and chose option e to edit the commit.
Git will warn you if there are some conflict and you will have to fix them before continue the rebase
In case you get something wrong during the rebase, you can abort it with git rebase --abort.
In case, you mess up everything after the rebase, you can still revert back to the previous version you let on github with git reset Upgrade-to-Python3/modernize-python2-code --hard

**Comment by OXINARF** [comment]
@cclauss Do you use a Git GUI? For someone that doesn't know Git well that's very useful. I'm not a pro with Git but I'm not a beginner either and I still use Git GUIs to check commit history, fix rebase conflicts and many times do commits too. Anyway, I'm sure I've told you before, we are available in Gitter to help you with Git.

Besides needing to be rebased (and the merge commit be gone) and the genromfs changes removed, it also needs to broken into multiple commits, one per folder and commit messages made accordingly and following our rules. I'll say again, that we are available to help with doing this.

**Comment by magicrub** [comment]
If on Windows or Mac, I suggest Source tree.

**Comment by jmachuca77** [comment]
Plus one on source tree 

Best regards,

Jaime Machuca
CEO | Element Aero | www.element.aero
Mail. jaime@element.aero

Off. +52 (33) 3805 4627
Cel. +52 1 (33) 3945 3350




Este correo electrónico y cualquier archivo transmitido en él, son confidenciales y para uso exclusivo de los individuos y entidades a quienes está dirigido. Si usted no es el destinatario previsto o la persona encargada de recibirlo, y tiene por error este mensaje, queda prohibido y sin validez el uso, difusión, re-envío, reimpresión o copia. Toda oferta y/o aceptación de propuestas comerciales, celebración de contratos u otros actos tendientes a la adquisición de bienes o servicios, así como el establecimiento de cualquier clase de obligación legal para Element Aero SAPI de CV, deberá confirmarse por escrito firmado autógrafamente por funcionario competente, excepto que se cuente con un contrato vigente que autorice el uso de este medio para tales fines. Si usted recibió este correo por equivocación, favor de notificar inmediatamente por este medio a su remitente, y después borrarlo de su correo

**Pull request closed without merging**
