### PR TITLE
Tools: remove deleted parameters

### PR DESCRIPTION
**Pull request by mothacehe**
RCx_REV and SERVO_RNG_ENABLE no longer exists, they need to be erased
from param files.

### CODE REVIEW

**Comment by jberaud** [comment]
@mothacehe You are making the same mistake I did a while ago. We currently have an issue which is those files are used by the GCSs even with official releases, so you can't modify for other boards than Disco.

**Comment by lucasdemarchi** [comment]
isn't it a matter to tell GCSs to use the param files from stable branches?

**Comment by DonLakeFlyer** [comment]
> isn't it a matter to tell GCSs to use the param files from stable branches?

Only if you can come up with a standard naming scheme that can be depended on for all firmware types. I'm not sure that exists now. Also not sure if there is standardization on branch versus tag and so forth.

**Comment by OXINARF** [comment]
Don is right, we need to do some work on our end first to make it easier for GCS.

**Comment by mothacehe** [comment]
While I agree with you about GCS related work, I think this change be applied because it is compatible with previous releases :
* RCx_REV=1 params were the default, and aren't needed anymore
* SERVO_RNG_ENABLE is only used by Disco, and GCS are not able to update this file on Disco

**Comment by jberaud** [comment]
@OXINARF Is compatibility with the latest release enough for you?

**Comment by tridge** [comment]
these changes are safe, as they are the defaults anyway, so applying

**Pull request merged**
