### PR TITLE
fix RCx_OPTION value for walking height in source comment (203-> 211)

### PR DESCRIPTION
**Pull request by hfujikawa77**
I fixed the source comment based on this commit.

ArduPilot/ardupilot@a97786c#diff-4394277d4bfb7b48f27084825c024642a3522592a67620c50fcea4877dbe1ea1

### CODE REVIEW

**Comment by rmackay9** [comment]
This looks good to me but can you add "RC_Channel:" to the front of the commit?

**Comment by hfujikawa77** [comment]
@rmackay9 
Thank you for your reviewing. I added 'RC_Channel: " to commit message.
https://github.com/ArduPilot/ardupilot/pull/19470/commits/0d009d7032b8e09c6bc251271a42e9d707b83e96

**Comment by peterbarker** [comment]
@hfujikawa77 there should be two commits here.

One should be prefixed with `AP_Button`.  The other should be prefixed with `RC_Channel` - we use those to tell us which directories changes are made in.

@hfujikawa77 please let me know if you're going to have trouble fixing this up.  The basic flow you're after is this:
 - backup your repository using zip or whatnot
 - git rebase -i master
 - squash all commits by changing "pick" to "s" - except on the first which should get "r" for reword
 - fix the commit message to not have any directory name
 - run `Tools/gittools/git-subsystem-split` - which will prepend the directory name for you
 - force push the branch up to github

**Comment by hfujikawa77** [comment]
I will respond with another PR. This PR will be closed.
#19492

**Pull request closed without merging**
