### PR TITLE
Add anyleaf H7 board

### PR DESCRIPTION
**Pull request by David-OConnor**
Hi! This is a draft, as it currently isn't working. The hardware works, and the config added here compiles, but the device then doesn't show a comm port after powering on once flashed with AP. Any help as to how to troubleshoot would help! (Maybe a way to step through the init process or put print statements in it while connected via St-Link, to see where it's failing? )

### CODE REVIEW

**Comment by andyp1per** [comment]
There's nothing obviously wrong with your config - have you tried getting a debugger on the board?

**Comment by andyp1per** [comment]
Try putting a breakpoint in main_loop()

**Comment by David-OConnor** [comment]
I have a debugger. Which file is that in? Thank you!

**Comment by andyp1per** [comment]
HAL_ChibiOS_Class.cpp

**Comment by David-OConnor** [comment]
Interesting. I haven't figured out how to connect/compile/flash to ArduPilot using SWD at this point, but I have a related question: Are there any H743 boards supported by AP that use 16Mhz HSEs? Is there a way to configure AP to use HSI instead? 

I have verified the board and USB work from Betaflight and custom firmware. As an ansantz, for the most part, any H743 firmware should at least flash and connect as a com port with any H743 board, as the configs mainly affect IO. I verified this by flashing a Matek config onto a Diatone H743 board I have. The Matek firmware *will not* work on my custom board. This potentially implicates, as a hunch, the PLL config with 16Mhz HSE.

#1: Where can I find the PLL config code?
#2: How can I configure HSI as the PLL input source?

Thank you!

**Comment by andyp1per** [comment]
- Where can I find the PLL config code?

libraries/AP_HAL_ChibiOS/hwdef/common/stm32h7_mcuconf.h

- How can I configure HSI as the PLL input source?

I think you set the crystal speed to 0 in your hwdef - have a look at the hwdef for some of the nucleo boards as I think they do thuis

- Using ST-Link, how can I flash using a debugger, and insert a print statement before and after RCC config? I couldn't find the RCC setup in the file in HAL_ChibiOS_Class.cpp. (https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_HAL_ChibiOS/HAL_ChibiOS_Class.cpp)?

RCC setup is all done in ChibiOS, you are unlikely to get print to work at that low a level. Look in modules/ChibiOS/os/hal/ports/STM32/STM32H7xx/hal_lld.c

**Comment by David-OConnor** [comment]
Thank you for the info. After inspecting the registers using St-Link after flashing Ardupilot with BL (At 0Mhz and 16Mhz oscillator settings), something is going wrong early: The USB source isn't selected, and PLL is off; ie RCC looks like defaultish settings.

**Comment by andyp1per** [comment]
Its worth putting a breakpoint in the USB LLD init and see whether that is getting called.

**Comment by David-OConnor** [comment]
Thank you - will give that a try.

**Comment by David-OConnor** [comment]
The latest is it compiles, flashes, shows a USB device COM port, and connects in MP.

The IMU doesn't work, and I have the errors: "Config Error: fix problem then reboot", and "Config Error INS: unable to initialize driver". 

How would you troubleshoot that? Thank you.

**Comment by andyp1per** [comment]
You need to step through the IMU initialization in a debugger

**Comment by David-OConnor** [comment]
Thank you. Do you know how to do that? I haven't found the docs on opening a debug session, or connecting using a debugger.

**Comment by andyp1per** [comment]
https://ardupilot.org/dev/docs/debugging-with-gdb-on-stm32.html

**Pull request closed without merging**
