### PR TITLE
[PreArm] Warning text overflow fix

### PR DESCRIPTION
**Pull request by tecnic08**
Fix for this issue https://github.com/ArduPilot/ardupilot/issues/13294

### CODE REVIEW

**Comment by davidbuzz** [comment]
seems reasonable, LGTM

**Comment by peterbarker** [comment]
While this looks like a reasonable fix, I'm not sure we should be putting resources into maintaining the old stable release.

There are already things going into 4.0 that people really ought to be flying and that will NOT be being backported.

**Comment by rmackay9** [comment]
It would be good to squash the commits and then the commit should be prefixed with "AP_Arming: ".

As @peterbarker says, it's unlikely that we will be doing any more release of Copter-3.6.x now that Copter-4.0 is out.

**Comment by tecnic08** [comment]
I squashed the commit.
If Copter-4.0 does not have this issue, please just merge into Copter-3.6. Just in case there will be something in the future.

**Comment by rmackay9** [comment]
We discussed this on the dev call and agreed that we wouldn't merge this to Copter-3.6 because it gives the impression that we might release another version of Copter-3.6 which is extremely unlikely.

I've merged it anyway but perhaps I shouldn't have!

**Pull request merged**
