### PR TITLE
Show max variances across all lanes for EKF_STATUS_REPORT mavlink msg

### PR DESCRIPTION
**Pull request by tridge**
This gives the operator some warning if one of their backup lanes is not happy

### CODE REVIEW

**Comment by WickedShell** [comment]
I'm not sure if I like this as it leaves the user unsure if the vehicle's current estimator is doing okay. Could we instead add an extension to the report to indicate which core it is/if it's the current primary?

**Comment by tridge** [comment]
@WickedShell it is possible to switch lanes at any time. If the backup lane is unhealthy then the pilot should actually be worried as something is wrong in the vehicle.

**Comment by WickedShell** [comment]
@tridge Yes, but this is user hostile as you are declaring a panic situation to them when the vehicle is still safe. Yes the backup isn't there and we should flag that, but the vehicle is still estimating correctly. I know of several use cases that this would trigger a mandatory loss of vehicle when the vehicle still was safe. I'd like to get the information down, but I'd absolutely hate to see us lose the explicit reporting of the current estimator.

**Comment by tridge** [comment]
@WickedShell note that this only affects mavlink reporting, not internal EKF failsafes

**Comment by WickedShell** [comment]
@tridge I'm aware, my point remains.

**Comment by priseborough** [comment]
There is real possibility of a switch to a second instance caused by GPS glitches and other transient errors. We have many log examples illustrating this so although a failure of the backup instance is not a flight emergency as it would be with the primary, neither should it be ignored.

In my experience, where I have seen the second IMU with degraded performance relative to the primary has always been associated with vibration or excessive thermal sensitivity.

**Comment by WickedShell** [comment]
As I said, I don't want to ignore it, I just want to be able to display both of them independently, to allow saner management from the operator.

**Comment by tridge** [comment]
after dev call discussion we decided to:
 - add a flag bit in status field for primary
 - add mavlink2 extension for instance

**Pull request closed without merging**
