### PR TITLE
Fix stm32l4+ flash issue

### PR DESCRIPTION
**Pull request by tsubashchandar**
stm32l4+ flash reset register has been reset properly

### CODE REVIEW

**Review by tridge — CHANGES_REQUESTED** [review]
I've changed it to be 0xC3FBU so we don't set reserved bits:
image
can you please test the change?
thanks!

**Comment by peterbarker** [comment]
@tsubashchandar we've previously hit problems where setting reserved bits caused problems, thus tridge's patch.

**Comment by tsubashchandar** [comment]
Okay , I will test and update. Thanks

**Comment by tsubashchandar** [comment]
It is working fine . We can merge it

**Review by tridge — APPROVED** [review]

**Pull request merged**
