### PR TITLE
Tools: SITL Copter-heli.parm remove WP_YAW_BEHAVIOR

### PR DESCRIPTION
**Pull request by hendjoshsr71**
This removes a default SITL parameter on heli that was overriding the default define to `WP_YAW_BEHAVIOR_LOOK_AHEAD`.

**On Master: Points to Last WP**
image

**After PR Points in Direction of RTL**
image

### CODE REVIEW

**Comment by bnsgeyer** [comment]
@hendjoshsr71 Not sure why this was added.  What does this affect and why do you want to remove it?

**Comment by hendjoshsr71** [comment]
> @hendjoshsr71 Not sure why this was originally added. What does this affect and why do you want to remove it?

Basically, I want heli SITL to act like it would on default heli board parameters. On a heli returning to land rolled on your side isn't exactly efficient flight.

**Comment by hendjoshsr71** [comment]
Having this line in defaults.parm overides the TradHeli defaults set here: https://github.com/ArduPilot/ardupilot/blob/98285854009968eabe30aa515e3b3a1e83ad7788/ArduCopter/config.h#L57

**Comment by bnsgeyer** [comment]
@hendjoshsr71 ok makes sense.  Looks like this was added 7 years ago.  I agree that it should be left to the default used in the code.  Thanks!

**Review by bnsgeyer — APPROVED** [review]
LGTM!

**Pull request merged**
