### PR TITLE
fixed set_target_angle_and_climbrate's use_yaw_rate fields don't work

### LINKED ISSUE #20417: Copter: scripting's set_target_angle_and_climbrate's use_yaw_rate fields don't work
Our lua script bindings allow a copter's angle (in euler angles) and climbrate (in m/s) to be controlled by a lua script.  The [binding](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Scripting/generator/description/bindings.desc#L223) also includes a couple of extra fields that should allow specifying the yaw rate as well.  I think the intention was that the if the yaw rate is provided that the yaw angle is ignored but in any case, it seems in the Copter implementation ([see Copter::set_target_angle_and_climbrate()](https://github.com/ArduPilot/ardupilot/blob/master/ArduCopter/Copter.cpp#L394)) we don't use these two fields at all.

### PR DESCRIPTION
**Pull request by khanasif786**
fixes #20417

### CODE REVIEW

**Comment by khanasif786** [comment]
I have tested the behaviour in SITL. It ignores the yaw when yaw_rate is given and acquires a roll and pitch angles with given yaw rate.

**Comment by lthall** [comment]
It is not acceptable to add extra rate parameters into a function that already takes them.

In practise all you have done is hijack the function and override it completly.

**Review by lthall — COMMENTED** [review]
I would not support this change.

**Comment by khanasif786** [comment]
> It is not acceptable to add extra rate parameters into a function that already takes them.
> 
> In practise all you have done is hijack the function and override it completly.

I have understood the rate one as it is already passing in form of angular_velocity but what about the boolean which tellls to set yaw_rate or not.

**Comment by khanasif786** [comment]
Or should I add an overloaded Definition of ```ModeGuided::set_angle``` function that includes those extra parameter ?

**Comment by lthall** [comment]
I won't be happy if you change that function at all.

**Comment by khanasif786** [comment]
> I won't be happy if you change that function at all.
Is this mean overloading is the solution ?

**Comment by lthall** [comment]
The problem is this function is fundamentally not for the task in that LUA call. That function is for fully defined attitude control.

This problem is not just with LUA but also mavlink commands. Initially we didn't implement mavlink commands properly and instead used simplistic (and wrong) implementations. Now guided is being fixed to do it properly but some of these LUA commands have inherited the mess and should be changed to a sensible command.

We have discussed adding simpler mavlink commands with matching guided commands. So a separate guided function all together is the only way forward.

The real solution to the problem is to change the LUA function and remove ", bool use_yaw_rate, float yaw_rate_degs)".

**Review by hendjoshsr71 — COMMENTED** [review]
As discussed on Discord we should figure out the intention of the the Lua method `set_target_angle_and_climbrate()` fully to figure out where to go here....

Asif and I tried using this function without the yaw_tae part active that I suggest below.

Here is the result of using the Lua script that tick tocks between -45deg and 45deg. I have not yet figured why once it reaches 315deg Yaw Desired the desired yaw changes from 315 deg to something else before the next LUA command to 45deg shown in GUIA occurs. 

My timeout is set to 10 seconds vs a LUA update of 7 seconds

image

**Comment by rmackay9** [comment]
@khanasif786, @lthall, @hendjoshsr71,

Hi guys, thanks very much for the efforts on this.  It's important that the user/lua script can control the vehicle much like it is flow in AltHold mode so we need some ability to specify the target roll and pitch angles and the yaw rate.

Because Leonard isn't happy with the change to the ModeGuided::set_angle() call, we should consider adding a new guided mode method to accept the target roll and pitch angles and the yaw rate.

**Comment by tridge** [comment]
I suggest we have an example lua script that has a function:
 set_euler_rp_yaw_rate(roll_deg, pitch_deg, yaw_rate_dps)
that then implements that functionality via the existing APIs

**Pull request closed without merging**
