### PR TITLE
Add terminate option (-42) to AFS_WP_GPS_LOSS

### PR DESCRIPTION
**Pull request by ethomas997**
This adds an Advanced-Failsafe option for flight termination in response to the GPS_LOSS condition.  The option is selected by setting AFS_WP_GPS_LOSS to -42 (instead of a waypoint number).

In combination with #12309, this allows me to configure my lightweight-foam AUTO plane to disarm and glide to ground if the GPS guidance fails.

I implemented something like this a while back using new parameter options (#3386), but doing it this way requires fewer code changes.

### CODE REVIEW

**Comment by tridge** [comment]
I think I would prefer to add a AFS_OPTIONS bitmask, and have one of the bits be "terminate on GPS loss". That would be clearer for the user to set, and would allow us to add other bits to AFS_OPTIONS in the future for other special case behaviour

**Comment by ethomas997** [comment]
I'm not opposed to doing it via a new AFS_OPTIONS bitmask parameter.  What do you think about my TERMINATE_ACTION_DISARM (#12309) mod?

**Comment by davidbuzz** [comment]
just a note to let u know that i tried this patch ontop of the 4.0-beta1 branch and it worked as expected in SITL when I tweaked the SITL so that i could simulate loss events on the two GPS's separately... loosing either gps on its own (via SIM_GPS_* parameter changes ) and it didn't 'terminate' , but loosing both at the same time and it did.   
However, it did not appear work as-expected with a  'real' pixhawk cube and two real ublox GPS units, as it appears there are hand-over delays between the two GPS units that mean that after unplugging one of the ublox units (while the other one clearly has a good lock ) the system terminated in a situation where I feel it should not have.  We setup the dual-gps system according to here: http://ardupilot.org/copter/docs/common-gps-blending.html , so perhaps it might be related to GPS_AUTO_SWITCH = 2 (blend), not sure at this stage.

**Comment by davidbuzz** [comment]
tridge has said he won't be accepting this as-is, ("I think I would prefer to add a AFS_OPTIONS bitmask"), and no movement from the original author in quite a while.  its also got a but when used with 'real' dual-gps systems that cause them to terminate too soon.

**Pull request closed without merging**
