### PR TITLE
EKF: convert EKF3 derivation to ftype

### PR DESCRIPTION
**Pull request by tridge**

### CODE REVIEW

**Comment by priseborough** [comment]
Did you mean to include https://github.com/ArduPilot/ardupilot/pull/17999/commits/1ed055143c01ae5e0752f989119145beea7af468 ?

**Comment by priseborough** [comment]
We also need to modify the code gen script here: https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_NavEKF3/derivation/code_gen.py#L22 to output ftype instead of float

**Comment by tridge** [comment]
> Did you mean to include [1ed0551](https://github.com/ArduPilot/ardupilot/commit/1ed055143c01ae5e0752f989119145beea7af468) ?

nope, fixed, thanks

**Comment by tridge** [comment]
> We also need to modify the code gen script here: https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_NavEKF3/derivation/code_gen.py#L22 to output ftype instead of float

done, thanks

**Comment by amilcarlucas** [comment]
This reduces the flash cost on all builds :)

**Review by priseborough — APPROVED** [review]

**Pull request merged**
