### PR TITLE
Correct builds when features enabled/disabled

### PR DESCRIPTION
**Pull request by peterbarker**
relay, ghost and microstrain changes all caused problems.

Running test_build_options with the pattern-matching option is quick and finds these sorts of problems - we should ask what happens when people add these to the build options... Really need to see if the feature list changes between the branch and master and try this automatically...

### CODE REVIEW

**Review by Ryanf55 — APPROVED** [review]

**Review by magicrub — APPROVED** [review]
@peterbarker  Do we actually need to wait for the devcall for the merge? I assume you want to talk about enforcing this feature-enable test at PR time?

**Comment by Ryanf55** [comment]
As someone who doesn't quite understand how the feature extraction works and how to test it, having some guardrails in CI or at least some documentation on how to use it would be very helpful in the longer term.

**Comment by magicrub** [comment]
@Ryanf55 well, directly quoting the message by @peterbarker where I took the liberty of slightly rephrasing his word "quick"

> "Running test_build_options with the pattern-matching option is <something even a monkey can do which means hard for CI but PeterB can make CI do anything so he's happy to spend the time on that so that it automatically> finds these sorts of problems"

**Comment by peterbarker** [comment]
Thanks @Ryanf55 and thanks - I think! - @magicrub :-P

Merging it.

**Pull request merged**
