### PR TITLE
AP_HAL_ChibiOS: revo-mini-i2c probe for external compasses

### PR DESCRIPTION
**Pull request by TulleU**
allow for probing of external compasses on i2c

### CODE REVIEW

**Review by andyp1per — APPROVED** [review]

**Review by khancyr — APPROVED** [review]
This need a rebase against master branch and it could go in

**Comment by TulleU** [comment]
ok, so one test failed for some reason that's unrelated to this PR, how do I restart the builds/tests

**Comment by hendjoshsr71** [comment]
@TulleU  I have cleaned up your commits and rebased this for you.

In ArduPilot we dont use merge commits when you want to rebase code you can look at these steps, https://ardupilot.org/dev/docs/git-rebase.html

Basic steps,

`git checkout master`
`git pull ardupilot master`  (here ardupilot is the remote representing the upstream repository 
`git checkout YOUR_BRANCH`
`git rebase master`   (This places your changes on top of your master branch.)

**Review by hendjoshsr71 — APPROVED** [review]

**Comment by TulleU** [comment]
aah, now I understand the the PR process, thanks for the help hendjoshsr71

**Comment by peterbarker** [comment]
Merged, thanks!

**Pull request merged**
