### PR TITLE
Add heading flight mode

### PR DESCRIPTION
**Pull request by omred173**
Hi everyone, First time I write here
I’ll like to offer flight mode that i use in big uav for none-gps flight at BVLOS ( as a manual dead reckoning), And also required when you fly BVLOS with ATC ( air traffic control) 
Heading flight : allowing to fly specific magnetic headings by enter 3 digit in the GCS,  The airspeed  / ground speed for multirotor, and altitude will be controlled as FBWB

### CODE REVIEW

**Comment by IamPete1** [comment]
This needs rebasing on master, looks like its currently against 4.3

**Comment by magicrub** [comment]
Is this cruise mode but without GPS? Would be easier to modify cruise mode

**Comment by omred173** [comment]
> This needs rebasing on master, looks like its currently against 4.3

How to rebasing to master

**Comment by omred173** [comment]
> Is this cruise mode but without GPS? Would be easier to modify cruise mode

Its possible, but as i know cruise mode fly ground track, i case of gps loss its use dead reckonings  including last known wind to fly and without good sensor it will drift very fast.

we need to fly magnetic heading as it’s reading by the compass.
It’s also the standard when ATC ask you to fly heading

**Pull request closed without merging**
