### PR TITLE
Plane: don't link in AC_Avoidance on plane

### PR DESCRIPTION
**Pull request by tridge**
saves about 7k of flash

### CODE REVIEW

**Review by magicrub — DISMISSED** [review]
This should all be AC_AVOID_ENABLE with default disabled if plane

**Comment by tridge** [comment]
> This should all be AC_AVOID_ENABLE with default disabled if plane

we can't do vehicle specific enables in header files

**Comment by magicrub** [comment]
> > This should all be AC_AVOID_ENABLE with default disabled if plane
> 
> we can't do vehicle specific enables in header files

I meant something like this: https://github.com/ArduPilot/ardupilot/blob/master/ArduCopter/config.h#L640-L642

**Comment by tridge** [comment]
> I meant something like this

vehicle config.h is not available in libraries

**Review by IamPete1 — APPROVED** [review]
Looks OK to me

**Pull request merged**
