### PR TITLE
Tools/environment_install: ensure venv is installed on all Ubuntus

### PR DESCRIPTION
**Pull request by tpwrules**
Corrects missing 22.04 Jammy case and avoids need for hardcoded table. Split out from #28080 .

Totally untested but seems right...

### CODE REVIEW

**Review by khancyr — CHANGES_REQUESTED** [review]
doesn't work. It enable venv on focal: see https://github.com/ArduPilot/ardupilot/actions/runs/10983477074/job/30492890484 

We got some autotest for that use the install scripts . If you are used to Docker that is quite simple to test those changes

**Comment by khancyr** [comment]
Not sure why we want venv now on jammy ?

**Comment by tpwrules** [comment]
Why would a venv only be desired on some versions? CI passes on all of them?

I think the motivation is that ESP-IDF needs venv.

**Comment by tpwrules** [comment]
Discussed briefly on the devcall and the consensus was that changing this is not desired. We will come up with an ESP32 specific solution if necessary.

**Pull request closed without merging**
