### PR TITLE
support PH Mini

### PR DESCRIPTION
**Pull request by jschall**
depends on https://github.com/ArduPilot/PX4Firmware/pull/54

### CODE REVIEW

**Comment by bbasso** [comment]
I believe this is the only blocking change to support PH mini support. @jschall - do you know who can resolve conflicts and merge?

**Comment by jschall** [comment]
@bbasso this still works and I am flying a PH Mini on a 250 quad.

**Comment by proficnc** [comment]
Items within this system cause harm to existing boards.

the changes in the PX4 section that cause the PH mini to be defined utilize the detection of the ICM for this.

the Pixhawk 2.1 also uses this chip as an option.  this is not an acceptable means of detection of the mini.
Rule 1, do no harm. 

There are hardware pins on the I/O PortC specifically allocated for identifying the hardware type. these should be used if you need a specific configuration.

please see https://github.com/jschall/ardupilot/blob/346d9acb524c472d6aeb515c1f75e98a613b9b97/mk/PX4/ROMFS/init.d/rc.APM#L322

**Comment by tridge** [comment]
This PR has been obsoleted by:
https://github.com/ArduPilot/ardupilot/pull/4604
Once that is reviewed and pulled in I will need someone to test it on a PHMINI. Brandon, can you do that?

**Comment by bbasso** [comment]
@tridge - yes I can

**Comment by tridge** [comment]
@bbasso to facilitate testing I have put a fw for you to try here:
http://uav.tridgell.net/PHMINI/
you will find it will fail to boot fully until you set BRD_TYPE=5. It will boot sufficiently for you to change that parameter. Then reboot.
If it fails after that then please tell me what error it gives on USB

**Comment by bbasso** [comment]
@tridge It doesn't work, I'm afraid. Connects via MAVlink (sometimes), but fails to give attitude data. I did set BRD_Type to 5 but it didn't make any difference. The custom build @jschall made works great, so must be a problem on the build side. I assumed that was Copter firmware?

**Comment by tridge** [comment]
please show me the output you get when you try it. Connect on USB with a terminal program and look at the output

**Comment by bbasso** [comment]
It takes 3-4 attempts to get it to connect, but once it does it generates the following. After all the MAVlink params download, it throws out constant "Check BRD_TYPE" errors, like this:

Check BRD_TYPE: No MPINFO MissionPlanner.MAVLinkInterface - MAVLINK: 3 wait time out btr 41 len 63
bps 17 loss 1 left 0 mem 16.6552734375 mav2 False sign False mav1 1 mav2 0 signed 0
INFO MissionPlanner.MAVLinkInterface - Mavlink Bad Packet (crc fail) len 65 crc 15403 vs 0 pkno 32 LOCAL_POSITION_NED
bps 65 loss 1 left 0 mem 16.6435546875 mav2 False sign False mav1 0 mav2 0 signed 0
INFO MissionPlanner.MAVLinkInterface - mav 7-1 seqno 195 exp 193 pkts lost 2


Fuller dump, starting midway through param download:

INFO MissionPlanner.MAVLinkInterface - 762 got param 574 of 599 name: RPM2_SCALING
INFO MissionPlanner.MAVLinkInterface - 763 got param 575 of 599 name: ADSB_ENABLE
INFO MissionPlanner.MAVLinkInterface - 764 got param 576 of 599 name: AVD_ENABLE
INFO MissionPlanner.MAVLinkInterface - 765 got param 577 of 599 name: AVD_F_ACTION
INFO MissionPlanner.MAVLinkInterface - 766 got param 578 of 599 name: AVD_W_ACTION
INFO MissionPlanner.MAVLinkInterface - 767 got param 579 of 599 name: AVD_F_RCVRY
INFO MissionPlanner.MAVLinkInterface - 768 got param 580 of 599 name: AVD_OBS_MAX
INFO MissionPlanner.MAVLinkInterface - 769 got param 581 of 599 name: AVD_W_TIME
INFO MissionPlanner.MAVLinkInterface - 770 got param 582 of 599 name: AVD_F_TIME
INFO MissionPlanner.MAVLinkInterface - 771 got param 583 of 599 name: AVD_W_DIST_XY
INFO MissionPlanner.MAVLinkInterface - 772 got param 584 of 599 name: AVD_F_DIST_XY
INFO MissionPlanner.MAVLinkInterface - 773 got param 585 of 599 name: AVD_W_DIST_Z
INFO MissionPlanner.MAVLinkInterface - 774 got param 586 of 599 name: AVD_F_DIST_Z
INFO MissionPlanner.MAVLinkInterface - 775 got param 587 of 599 name: AUTOTUNE_AXES
INFO MissionPlanner.MAVLinkInterface - 776 got param 588 of 599 name: AUTOTUNE_AGGR
INFO MissionPlanner.MAVLinkInterface - 777 got param 589 of 599 name: AUTOTUNE_MIN_D
INFO MissionPlanner.MAVLinkInterface - 778 got param 590 of 599 name: NTF_LED_BRIGHT
INFO MissionPlanner.MAVLinkInterface - 779 got param 591 of 599 name: NTF_BUZZ_ENABLE
INFO MissionPlanner.MAVLinkInterface - 781 got param 592 of 599 name: NTF_LED_OVERRIDE
INFO MissionPlanner.MAVLinkInterface - 782 got param 593 of 599 name: THROW_MOT_START
INFO MissionPlanner.MAVLinkInterface - 783 got param 594 of 599 name: TERRAIN_FOLLOW
INFO MissionPlanner.MAVLinkInterface - 784 got param 595 of 599 name: WP_TKOFF_NAV_ALT
INFO MissionPlanner.MAVLinkInterface - 785 got param 596 of 599 name: BTN_ENABLE
INFO MissionPlanner.MAVLinkInterface - 786 got param 597 of 599 name: THROW_NEXTMODE
INFO MissionPlanner.MAVLinkInterface - 787 got param 598 of 599 name: THROW_TYPE
INFO MissionPlanner.Controls.ProgressReporterDialogue - DoWork Done
INFO MissionPlanner.MAVLinkInterface - 8/4/2016 5:36:02 PM 6 Initialising APM
bps 20085 loss 1 left 0 mem 16.1552734375 mav2 False sign False mav1 604 mav2 0 signed 0
Open MissionPlanner.GCSViews.SoftwareConfig SWConfig
Open MissionPlanner.GCSViews.ConfigurationView.ConfigPlanner Planner
Check BRD_TYPE: No MPINFO MissionPlanner.MAVLinkInterface - MAVLINK: 3 wait time out btr 41 len 63
bps 17 loss 1 left 0 mem 16.6552734375 mav2 False sign False mav1 1 mav2 0 signed 0
INFO MissionPlanner.MAVLinkInterface - Mavlink Bad Packet (crc fail) len 65 crc 15403 vs 0 pkno 32 LOCAL_POSITION_NED
bps 65 loss 1 left 0 mem 16.6435546875 mav2 False sign False mav1 0 mav2 0 signed 0
INFO MissionPlanner.MAVLinkInterface - mav 7-1 seqno 195 exp 193 pkts lost 2
Check BRD_TYPE: No MPbps 17 loss 2 left 7 mem 16.4384765625 mav2 False sign False mav1 1 mav2 0 signed 0
INFO MissionPlanner.MAVLinkInterface - Mavlink Bad Packet (crc fail) len 65 crc 58984 vs 0 pkno 32 LOCAL_POSITION_NED
]INFO MissionPlanner.MAVLinkInterface - mav 7-1 seqno 197 exp 196 pkts lost 1
bps 82 loss 3 left 0 mem 16.6953125 mav2 False sign False mav1 1 mav2 0 signed 0
bps 17 loss 3 left 0 mem 16.4453125 mav2 False sign False mav1 1 mav2 0 signed 0
Check BRD_TYPE: No MPINFO MissionPlanner.MAVLinkInterface - MAVLINK: 3 wait time out btr 41 len 63
bps 17 loss 3 left 0 mem 16.3759765625 mav2 False sign False mav1 1 mav2 0 signed 0
INFO MissionPlanner.MAVLinkInterface - Mavlink Bad Packet (crc fail) len 65 crc 26331 vs 0 pkno 32 LOCAL_POSITION_NED
bps 65 loss 3 left 0 mem 16.3740234375 mav2 False sign False mav1 0 mav2 0 signed 0
INFO MissionPlanner.MAVLinkInterface - mav 7-1 seqno 202 exp 200 pkts lost 2
INFO MissionPlanner.MAVLinkInterface - 8/4/2016 5:36:12 PM 6 Initialising APM
Check BRD_TYPE: No MPINFO MissionPlanner.MAVLinkInterface - MAVLINK: 3 wait time out btr 41 len 63

**Pull request closed without merging**
