### PR TITLE
Rover: display the type of failsafe on GCS

### PR DESCRIPTION
**Pull request by tatsuy**
This PR let users see of what kind of failsafe is triggered.
image

### CODE REVIEW

**Comment by rmackay9** [comment]
I love this change but let's remove the 0x01 (and other similar numbers) completely.

**Comment by tatsuy** [comment]
I fixed it to "Radio Failsafe".
and I also changed to "Radio Failsafe Cleared" referring to the code of the copter.
https://github.com/ArduPilot/ardupilot/blob/master/ArduCopter/events.cpp#L82

image

**Comment by tatsuy** [comment]
I did rebase

**Comment by rmackay9** [comment]
Merged, thanks!

**Pull request merged**
