### PR TITLE
HAL_Linux: avoiding setting the SPI mode on every transfer

### PR DESCRIPTION
**Pull request by tridge**
This was causing the Disco kernel to print a debug message on every
SPI transfer, which makes for a very noisy kernel and large kernel logs

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
Yep... I thought several times lately on "why do we set the mode every time??" hehee... And now a proper PR. Thanks.

The motivation in my opinion is more that we don't do the 2 syscalls.... because this applies to every system and not only disco.

However,  the possible reason I remembered for not doing this was: if the bus is shared with another programs/kernel. In this case bad things will happen, because kernel  and other programs will think they have one mode set when the driver in fact has another one.

**Comment by jberaud** [comment]
Our kernel driver has a problem though, because it prints using dev_info (printk(KERN_INFO...) every time the setup function is called.
This is to be fixed but can help noticing that there are too many syscalls like here.

**Comment by lucasdemarchi** [comment]
not the best way to detect too many syscalls, though :)

Btw, you could be using dev_dbg() and then one can easily enable/disable the extra debug via dyndbg: https://www.kernel.org/doc/Documentation/dynamic-debug-howto.txt

**Comment by jberaud** [comment]
I just proposed a patch using dev_dbg :-)

**Comment by tridge** [comment]
> However, the possible reason I remembered for not doing this was: if the bus is shared with another programs/kernel. In this case bad things will happen, because kernel and other programs will think they have one mode set when the driver in fact has another one. 

really? I would have though the kernel would have kept the mode per open fd.

**Comment by tridge** [comment]
it must be kept per open fd, as otherwise we have an existing very nasty race condition. There is no inter-process lock between the set of the mode and the transfer.
So if it doesn't keep it per open fd then the API is fundamentally broken :-)

**Comment by lucasdemarchi** [comment]
> it must be kept per open fd, as otherwise we have an existing very nasty race condition. 

It's not per fd... I checked on the driver 1 week ago.

> There is no inter-process lock between the set of the mode and the transfer.

yep

> So if it doesn't keep it per open fd then the API is fundamentally broken :-)

it is. I guess the API was added with the intent to be used as a debug api, not something for real consumption like we do. I can raise the subject on lkml and see the feedback.

**Comment by tridge** [comment]
ok, wow. At least that means my PR doesn't make it any more broken than it already was :-)
ardupilot needs exclusive access to the SPI bus

**Comment by lucasdemarchi** [comment]
See the open function:
https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/drivers/spi/spidev.c#n584
```
filp->private_data = spidev;
```

And then the ioctl():
https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/drivers/spi/spidev.c#n424

mode is saved in `spi->mode` which is shared by all file descriptors.

**Comment by lucasdemarchi** [comment]
> ok, wow. At least that means my PR doesn't make it any more broken than it already was :-)

It actually raises the race window a lot, it's even not a race anymore, but a bad behavior from our side.... And if this race is fixed upstream, we won't profit from it.

**Comment by hiro2233** [comment]
Try to put the CS to a PHYSICAL pin or to a reserved space mem register only for CS, Bebop are managing the CS internally in the Kernel and it are changing internally the settings. Try it and i'm sure the trouble is there.

**Comment by tridge** [comment]
what about if we did a SPI_IOC_RD_MODE and check it matches? If it doesn't we report a warning and then do a set of the mode.
That way we get a warning if we ever lose the race, and still have the same number of syscalls we have now.

**Comment by tridge** [comment]
@hiro2233 its nothing to do with the CS pin

**Comment by hiro2233** [comment]
@tridge i see, i told it because i had a problems with CS pin on RPI and mode transfers. But i will continue testing it.

**Comment by tridge** [comment]
i've pushed a revised patch that uses a RD_MODE on each transfer and warns about bus conflicts

**Comment by lucasdemarchi** [comment]
Applied, thanks!

**Pull request closed without merging**
