### PR TITLE
Copter: Use the definition

### PR DESCRIPTION
**Pull request by muramura**
I think it's better to specify a definition value.
You need to check the header file to understand if the "1" in the message matches the name of the definition.

### CODE REVIEW

**Comment by WickedShell** [comment]
I'm not sure I see the advantage here? We already locked the value of the define, and can't change the parameter without breaking stuff, and the net effect is this increases the firmware size, without helping the readability of the error message.

**Comment by muramura** [comment]
I can't understand what the 1 in the message is just from the code.
The code uses the definition name to determine it.
To understand the source, we need to look at the header file.
This can be a pain in the ass.

**Comment by amilcarlucas** [comment]
This is better solved with a comment in the code. A simple NFC change.

**Review by khancyr — COMMENTED** [review]
Please bring evidence that it doesn't bring more flash usage.
If it does then just putting a comment should be enough. Or using a static constexpr to build the string.

If it doesn't then it is fine to go

**Comment by muramura** [comment]
@khancyr san..  I like code in business that doesn't care about the value of the definition name.  The direct value becomes unknown over time.  If you want to explain the value of the definition name in the code, change the judgment value of the if statement to 1.  This will link to the message.

**Comment by peterbarker** [comment]
@muramura san   the textual comments here are meant as a guide to the pilot that their parameters are specifying something is wrong with their configuration and the vehicle's current state.

Perhaps we ought to do away with the unhelpful numbers and go with:
```
                 check_failed(ARMING_CHECK_PARAMETERS, display_failure, "RTL_ALT_TYPE is above-terrain but no terrain data");
```
?

**Comment by peterbarker** [comment]
We're going with https://github.com/ArduPilot/ardupilot/pull/16488 instead - thanks for bringing this up!

**Pull request closed without merging**
