### PR TITLE
Mavlink upstream updates

### PR DESCRIPTION
**Pull request by amilcarlucas**
Copter compiles fine with this.
I did not test the other vehicles.

### CODE REVIEW

**Comment by amilcarlucas** [comment]
This requires mavlink#110 and that is why CI fails

**Comment by amilcarlucas** [comment]
I pushed the mavlink branch into the ardupilot/mavlink repository. The tests should now run until the end.
I also rebased this in the latest ardupilot master and updated to the latest pymavlink master.

**Comment by amilcarlucas** [comment]
All CI tests pass now.

**Comment by tridge** [comment]
I've merged mavlink repo changes, and added temperature changes to this PR
this is good to merge when CI passes

**Comment by amilcarlucas** [comment]
Thanks for merging the mavlink and pymavlink changes

**Pull request merged**
