### PR TITLE
Pass vector by const ref when needed

### PR DESCRIPTION
**Pull request by khancyr**
NFC
Gain in speed and flash

### CODE REVIEW

**Comment by rmackay9** [comment]
LGTM

**Comment by rmackay9** [comment]
Merged, thanks!

**Comment by lukezhqin** [comment]
@rmackay9 Hi, I recently read the copter-4.0 rc2  branch and found this commit here. Did you only do this change to protect the parameters from being changed inside the function? Or we may have some running efficiency impovement or something else I would miss using this commit?

**Comment by khancyr** [comment]
there maybe a performance improvement but is should be minimal. It mainly made the code conform to c++ standard and prevent useless copy  on read only object.

**Comment by lukezhqin** [comment]
@khancyr many thanks for your reply.

**Pull request merged**
