### PR TITLE
treewide: fix shebangs - /bin/bash -> /usr/bin/env bash

### PR DESCRIPTION
**Pull request by sorki**
Most scripts/tools use non-portable `/bin/bash`, switch to environment agnostic `/usr/bin/env bash`.

### CODE REVIEW

**Review by peterbarker — APPROVED** [review]
Looks right.

Was it causing an issue?

Marked for DevCall to see what people think of `treewide: ` as a concept...

**Comment by sorki** [comment]
On NixOS there's no `/bin/bash` :smile: There's only `/bin/sh` and `/usr/bin/env` (only two binaries in these directories). 

This allows using scripts and building everything on NixOS - If there's interest I can publish a follow-up PRs with Nix files that allow quickly setting up a development shell or performing a full build without having to fiddle with dependencies.

**Comment by peterbarker** [comment]
Merged, thanks!

**Comment by tpwrules** [comment]
Already done: https://github.com/tpwrules/ardupilot-dev-flake . Need to write a bit of docs but basically they are "run `nix develop` and then all the popular Ardupilot commands".

**Pull request merged**
