### PR TITLE
QuadPlane: Abort VTOL takeoffs that take too long to complete

### PR DESCRIPTION
**Pull request by WickedShell**
This allows you to define a time limit for VTOL takeoffs, useful for when environmental reasons are causing you to fail to climb fast enough and you are running out of power due to that/landing would become questionable. If the limit is exceeded the system shifts to `QLAND` as the failure handler.

This is the start to a number of reasons to abort a takeoff, and simply happens to be the easiest to quickly add.

### CODE REVIEW

**Comment by WickedShell** [comment]
Extended to include an airspeed limit. As long as the plane is aligned with the wind (and weathervaning should get you somewhat close as long as you weren't to far off), the airspeed sensor becomes a good source of wind data in a steady hover (particularly if you are using forward assist such that the plane is level and simply climbing or descending). Using this you can then automatically abort the takeoff if the system would exceed it's wind limits. This is particularly important with quadplanes where you might be unable to descend in high winds and gain altitude uncontrollably when you decide to land at the end of a flight. This will at least give you a better chance of not taking off past your weather limits, or if you clear a tree line that was hiding very high wind from you on the ground.

**Comment by WickedShell** [comment]
Flight tested on a real aircraft.

**Comment by WickedShell** [comment]
Untagged as a dev call topic, I want to experiment with replacing the flight timer part of this with a scaler based on your tuned climb rate vs altitude to cover, which should scale better for various height takeoffs.

**Comment by WickedShell** [comment]
I have re factored this to use a scaled estimate of how long it will take us to complete the takeoff for determining a takeoff failure rather then using a user provided parameter in seconds. The advantage of this is that you can handle a wider range of takeoff altitudes without having to adjust the parameter. The basis for my math (someone please cross check me) was left in the code as LaTeX.

@kd0aij @IamPete1 outside of @tridge you guys are the main quadplane users I know of. This should work just fine with tailsitters as well, but please feel free to test it, and if you have any comments about the implementation and idea please let me know.

**Comment by IamPete1** [comment]
@WickedShell Looks good to me, the only thing I can see is that this does not take into account any slowing down time. I think it does the time to accelerate to pilot_velocity_z_max the the rest of the distance at pilot_velocity_z_max. So this is the minimum time to get there. I'm not 100% familiar with how take off commands work but I guess it aims to be stopped at the desired altitude rather than still climbing, so you would have to add on the deceleration time too.

**Comment by WickedShell** [comment]
> I'm not 100% familiar with how take off commands work but I guess it aims to be stopped at the desired altitude rather than still climbing, so you would have to add on the deceleration time too.

Argh, at first glance I think you're correct. Ironically I think I'd actually be totally happy with quadplane takeoffs that just got to the transition state as fast as possible rather then slow down to hit the target altitude correctly, but that would probably be more confusing for most people, so we'll leave the behavior alone and just make this account for the deceleration time...

**Comment by kd0aij** [comment]
Assuming that acceleration time is significant, the math looks good to me. Otherwise why not just use (delta altitude) / (expected rate of climb)?

**Comment by WickedShell** [comment]
> I'm not 100% familiar with how take off commands work but I guess it aims to be stopped at the desired altitude rather than still climbing, so you would have to add on the deceleration time too.

It's fairly insignificant on my aircraft, but I didn't think I could generalize that to all aircraft reasonably. It also is more significant if using a very small height change for some reason (most likely because you were using the respect frame option and were restarting the takeoff while at a couple meters below transition height This is somewhat handled because I forced a minimum time of 5 seconds, but again it doesn't generalize well to vehicles that have slower acceleration for any reason (or high max speed)).

**Pull request merged**
