### PR TITLE
Plane: Parachute ALT_MIN should be not above home, but above ground

### PR DESCRIPTION
**Pull request by naktinis**
Added a method `Plane::relative_ground_altitude` that returns altitude above terrain (if terrain data available) or home (otherwise).

Use this method for checking parachute deployment altitude.

### CODE REVIEW

**Comment by naktinis** [comment]
@magicrub this is a pull request for #3837.

While making the changes I thought of adding a boolean parameter to this method: `void Plane::relative_ground_altitude(bool use_terrain)`. In this case some places could be refactored from this:

    float correction = relative_altitude() - rangefinder_state.height_estimate;

    #if AP_TERRAIN_AVAILABLE
        float terrain_altitude;
        if ((target_altitude.terrain_following || g.terrain_follow) && 
            terrain.height_above_terrain(terrain_altitude, true)) {
            correction = terrain_altitude - rangefinder_state.height_estimate;
        }
    #endif

into this:

    bool use_terrain = target_altitude.terrain_following || g.terrain_follow;
    float ground_altitude = relative_ground_altitude(use_terrain);
    correction = ground_altitude - rangefinder_state.height_estimate;

or even into a one-liner (although I prefer the above):

    correction = relative_ground_altitude(target_altitude.terrain_following || g.terrain_follow) - rangefinder_state.height_estimate;

What do you think about this signature? Also, about this pull request in general.

**Comment by magicrub** [comment]
correction is something specific to rangefinder and its' use is very limited to landing only (right now). I'll have to talk to @tridge about expanding it to other uses.

**Comment by magicrub** [comment]
But otherwise, this PR looks good. Thanks!

**Comment by magicrub** [comment]
merged, thanks!

**Pull request closed without merging**
