### PR TITLE
Parameter: CRASH_DETECT Param doc update to add 1 in value set

### PR DESCRIPTION
**Pull request by loki077**
As this was causing a CI check we made locally to compare param values to param_metadata generated xml file.

### CODE REVIEW

**Review by peterbarker — APPROVED** [review]
I've corrected the commit message and marked this for DevCall in case it doesn't get merged sooner.

Note that some of these fields are guidelines only; not necessarily `Values`, but certainly `Ranges`.

**Review by magicrub — CHANGES_REQUESTED** [review]
Why not update the bitmask field too?

**Comment by peterbarker** [comment]
> Why not update the bitmask field too?

Fair call.  In fact, that is the *correct* fix, as both MAVProxy and MissionPlanner ignore the @Values field if @Bitmask is present!

I have created https://github.com/ArduPilot/ardupilot/pull/27082 to enforce the same rule as we have had in libraries for years - you can only have one of @Values or @Bitmask

@loki077 you could simply remove the @Values as part of this PR - or we could merge mine which will close this one as Merged.

**Comment by loki077** [comment]
@peterbarker I have forced pushed the change. You can also make it a part of your PR.

**Comment by peterbarker** [comment]
> @peterbarker I have forced pushed the change. You can also make it a part of your PR.

I've merged that other PR now - so closing this one.

Thanks!

**Pull request closed without merging**
