### PR TITLE
AP_HAL_ChibiOS: ICM42688 for OrqaF405Pro

### PR DESCRIPTION
**Pull request by andyp1per**

### CODE REVIEW

**Comment by rmackay9** [comment]
This looks like a fix for the issue brought up in this discussion https://discuss.ardupilot.org/t/orqa-3030-f450-issue/127483

**Comment by andyp1per** [comment]
> This looks like a fix for the issue brought up in this discussion https://discuss.ardupilot.org/t/orqa-3030-f450-issue/127483

Yes it is, just waiting for confirmation that the orientation is the right way round.

**Comment by andyp1per** [comment]
Confirmed correct by the user

**Review by tridge — APPROVED** [review]

**Comment by rmackay9** [comment]
this is included in ArduPilot-4.6.0-beta3

**Pull request merged**
