### PR TITLE
AP_Airspeed: fix spd3x correct pressure issue

### PR DESCRIPTION
**Pull request by liang-tang**
issue  https://github.com/ArduPilot/ardupilot/issues/8220

### CODE REVIEW

**Comment by Naterater** [comment]
I'll give it a test soon. I have 5 of those darn things in stock, so I'm invested in this!

**Comment by OXINARF** [comment]
@WickedShell @Naterater Any news on this?

**Comment by WickedShell** [comment]
@OXINARF I haven't had time to test yet, this should be combined with a tube length correction factor or my test is known to fail already.

**Comment by WickedShell** [comment]
I didn't get to flight testing this, but I did run through the math, and it fixes a significant amount of accidental quantization in the middle of the math.

**Pull request merged**
