### PR TITLE
AP_Scripting: Replace the build of the makefile with Waf

### PR DESCRIPTION
**Pull request by brotherlymite**
I'm using **waf rule based task generators** to build which automatically builds as the **dependencies change**. (might not be the most efficient way)

I've added a waf recurse in the main directory wscript to go to the AP_Scripting wscript and builds as the dependencies change.

Also, the build files get created in the build directory of the main ardupilot directory and get cleaned every time we call ./waf distclean.

### CODE REVIEW

**Comment by tridge** [comment]
this is a good first try, thanks!
the key now is to get it to pass CI tests. You can see that semaphore is currently failing, plus the travis test isn't really testing it properly as the generated files are still in the repository. What you need now is:
 - a 2nd commit that removes the lua_generated_bindings.cpp and lua_generated_bindings.h files
 - ensure that "./waf clean" removes the generated files
Then get CI to pass by tracking down the errors.
We will also need configure checks to find the native compiler instead of hard-coding gcc, but that isn't as critical as the above steps.

**Comment by brotherlymite** [comment]
Thanks, @tridge for the detailed review,

I have removed the -Werror flag as it was causing the semaphore build to fail (don't really know if it's safe to remove the flag) also I've added a bld.add_group() to each of the commands to have a double-check that tasks don't run parallelly which could result in a failed build.

I've tried removing the lua_generated_bindings.cpp and lua_generated_bindings.h files but it's causing a failed build as the files are generated at build time and the header calculations are done before. (Will try to fix this up soon)

The other builds are failing due to hardcoding gcc (as you said) and will try to add the native compiler (Although its a bit difficult to pass a native compiler to rule based task generators so just wanted to ask if my approach to this using rule based task generators correct?)

And yeah "./waf clean" removes the object file and the gen-bindings so do we also want to remove the lua_generated_bindings.cpp and lua_generated_bindings.h files.

**Comment by tridge** [comment]
> I have removed the -Werror flag as it was causing the semaphore build to fail (don't really know if it's safe to remove the flag)

I think it is fine to remove it for this case

> I've tried removing the lua_generated_bindings.cpp and lua_generated_bindings.h files but it's causing a failed build as the files are generated at build time and the header calculations are done before. (Will try to fix this up soon)

you'll need the generator build and run to happen as part of the early stages of the build. Have a look at how we generate the mavlink headers and the UAVCAN headers as an example.

**Comment by WickedShell** [comment]
>> I have removed the -Werror flag as it was causing the semaphore build to fail (don't really know if it's safe to remove the flag)

> I think it is fine to remove it for this case

Wait, no I actually really like/bank on having `-wError` when testing changes to the generator.

**Comment by tridge** [comment]
@brotherlymite any progress on this?

**Comment by brotherlymite** [comment]
I'm still getting build error if I remove lua_generated_bindings.h lua_generated_bindings.cpp , as the files are getting generated in the source directory and waf is not able to compile the generated files in one go , which is causing linking error.
So I guess we have to set the task signatures for the generated files.
I've tried adding a Task class and in the post_run setting the task signatures but that isn't working as well

```
class luagen(Task.Task):
	
	#ext_out = ['.h']
	def run(self):
		shell=True,
		return self.exec_command ('{} -o ../lua_generated_bindings -i {}'.format (
			self.inputs[0].abspath(),
			self.inputs[1].abspath()
		) ,cwd = './libraries/AP_Scripting/generator',)

	def post_run(self):
		super(luagen, self).post_run()
		for node in self.outputs:
			node.sig = node.cache_sig = self.cache_sig
```

**Comment by tridge** [comment]
> files are getting generated in the source directory

the files need to be generated in the build directory. The source directory should be read-only from the point of view of the build system

There are several existing examples that you should be able to follow:

building libcanard in AP_Periph:
https://github.com/ardupilot/ardupilot/blob/master/Tools/AP_Periph/wscript#L56

building uavcan headers:
https://github.com/ardupilot/ardupilot/blob/master/wscript#L406

building mavlink headers:
https://github.com/ardupilot/ardupilot/blob/master/wscript#L393

**Comment by brotherlymite** [comment]
@tridge Sorry for the delayed response I have my finals coming up soon.
And also thanks for the detailed reply.
So this commit generates the `lua_generated_bindings.cpp` and `lua_generated_bindings.h` in the build directory and also handles the include dependencies on the generated files by the files in the source directory.
However, I'm yet to compile the generated files in the build directory.
I've tried adding 
`bld.env.AP_LIBRARIES += [ '../build/'+ bld.env.BOARD +'/libraries/AP_Scripting/' ]`
but as the files are generated dynamically , it gives a source not found error.
I'll try to fix this up soon.

**Comment by davidbuzz** [comment]
Is this still relevant? I thought the scripting bindings are now being automatially handled in master..?

**Comment by peterbarker** [comment]
Closed by https://github.com/ArduPilot/ardupilot/pull/14329 - thanks!

**Pull request closed without merging**
