### PR TITLE
AP_Arming: Notify arm instructions only

### PR DESCRIPTION
**Pull request by muramura**
I live in Japan.
Japan has four seasons.
The temperature rise time of IMU depends on the season.
The temperature can be known by the status of GCS.
Therefore, I think it is good only at arm time.

AFTER
Screenshot from 2023-01-05 02-05-51

BEFORE
Screenshot from 2023-01-05 01-58-10

### CODE REVIEW

**Review by IamPete1 — COMMENTED** [review]
I disagree, if vehicle is not ready to arm its useful to know why. You can also see it increasing in temp without having to go and find the reported temp and threshold.

**Comment by peterbarker** [comment]
- a lot of prearm strings which could be gleaned with deep knowledge of AP internals
 - this message should be emitting the target temperature too
 - we have an option bit to not emit statustexts if you don't want any prearm texts

This string should say IMO.

**Comment by muramura** [comment]
Thanks for your comment.
When the arm is released, I think the notification level is INFO.
When armed, I think the notification level is "CRITICAL".
The notification level "CRITICAL" is displayed on the HUD for MP and on a pop-up for QGC.
I think INFO in the check_failed method.

**Comment by muramura** [comment]
I know of a FC that has more than one IMU.
For example, there is CUBE ORANGE, PIXHAWK 6X, etc.
I don't think it's a good idea to judge only by the temperature of the primary.
IMU can be switched during flight.
Therefore, if there is more than one IMU, each temperature should be changed to check.
Also, I would like to be informed of the pre-arm checks.
If PreArm is attached, it is set to GCS_SEND_TEXT for pop-up display.

Screenshot from 2023-01-09 14-03-45
Screenshot from 2023-01-09 14-03-37

**Review by khancyr — CHANGES_REQUESTED** [review]
unfortunately we cannot do this.
On board that have heaters not all IMU are temperature controled, so we shouldn't check all IMU temps on prearm

**Pull request closed without merging**
