### PR TITLE
AP_Airspeed: disable airspeed (_TYPE=0) as rover default

### PR DESCRIPTION
**Pull request by magicrub**
No reason to have this enabled for rover a default

### CODE REVIEW

**Comment by WickedShell** [comment]
On by default makes the windvane stuff work better/require less configuration, and doesn't cost anything other then a quick bus scan. Are you having device collisions?

**Comment by rmackay9** [comment]
maybe it will clear up this unnecessary error message on startup?  https://github.com/ArduPilot/ardupilot/issues/10371

**Comment by magicrub** [comment]
@WickedShell the windvane stuff is just for boats, right? Wouldn't that me a much smaller audience? I suppose leaving it in wouldn't hurt (minus the gcs msg bug). Just annoying, yet another param I will be disabling and more params to download.

**Comment by rmackay9** [comment]
I vote for defaulting it to disabled if it makes less params visible ..

**Comment by WickedShell** [comment]
Huh, didn't actually think it was an enable parameter, but apparently it is :) Between that/gcs message seems fair to change the default for rover. Most people don't ever get to see that message, but still shows up in the log/is other wise confusing :)

**Comment by rmackay9** [comment]
alrighty then, Merged, thanks!

**Pull request merged**
