### PR TITLE
AP_HAL_ChibiOS/Scheduler: add external watchdog for JFB110.

### PR DESCRIPTION
**Pull request by jfbblue0922**
This is the watchdog for JFB110（the new flight controller of JAE）. 

When using an external watchdog, add "WDI_OUT_INTERVAL_TIME_MS" to the definition file (hwdef.dat),

This program was tested on JFB100 hardware.

### CODE REVIEW

**Comment by rmackay9** [comment]
Hi @jfbblue0922,

Txs very much for this.  In general I think this looks pretty OK (although @tridge will be a better judge).  One issue though is that this definition isn't in the JFB100 board though so this new code is never used.

I guess the intention is to add the HAL_GPIO_PIN_WDI_OUT definition to the JFB100 (or JFB110) board hwdef file once it is merged to master?

**Comment by magicrub** [comment]
LGTM

**Comment by rmackay9** [comment]
@jfbblue0922,

By the way, could you explain the purpose of this external watchdog?  I think what it does is toggle a pin high and low at regular intervals.  So it is basic health reporting implemented at a very low level.  TBH, I'm not sure why we would need this when we have so much more sophisticated health reporting in the form of MAVLink.

I'm also not sure we should use the word "watchdog" because we normally use this word for situations where AP has had a critical software failure and the autopilot's main loop has stopped.  Maybe we should call it "hardware heartbeat" or something similar.

**Comment by jfbblue0922** [comment]
@rmackay9 

JFB100 has external WDT, because it designed to detect halt of flight controller with "simple logic".
In the future, we plans to try multiple fc systems using this flight controller.
I have no objection to the name hardware heartbeat.

HAL_GPIO_PIN_WDI_OUT definition is already included in the merged JFB100 hwdef.dat.
I would like to close this PR and make another PR again.

**Pull request closed without merging**
