### PR TITLE
AP_Button: update BTN_FUNCx param descriptions

### LINKED ISSUE #16533: AP_Button: BTN_FUNCx param descriptions should match RCx_OPTIONS
We can improve the ease-of-use of the Buttons feature ([see wiki here](https://ardupilot.org/copter/docs/common-buttons.html)) by allowing the user to directly select the function they want attached to the button instead of having to manually look up the number on the wiki page.  This should be possible by simply copying the RCx_FUNCTION parameter descriptions @Values field to the BTN_FUNC1/2/3/4 parameter description.

### PR DESCRIPTION
**Pull request by YashMaxy**
Just added the RCx_FUNCTION parameter description's values field to the BTN_FUNC parameter description

Resolves #16533

### CODE REVIEW

**Comment by Hwurzburg** [comment]
LGTM

**Review by Hwurzburg — APPROVED** [review]

**Review by peterbarker — APPROVED** [review]
LGTM.

**Comment by peterbarker** [comment]
Merged, thanks!

**Comment by rmackay9** [comment]
Nicely done @YashMaxy

**Pull request merged**
