### PR TITLE
Change from sqrt to safe_sqrt

### PR DESCRIPTION
**Pull request by muramura**
I think it would be better to use a more secure method.

### CODE REVIEW

**Comment by tridge** [comment]
I agree with @WickedShell, we shouldn't be doing this everywhere, it just wastes CPU

**Comment by muramura** [comment]
@WickedShell san, @tridge san, @rmackay9 san...
I will raise the clock as a means to increase the processing capacity. Pixhawk 4, Pixhack v 5 is 216 MHz. Pixhawk 2 is 168 Mhz. Pixhawk 4 has 1.2 times the capability of Pixhawk 2. I think that you can choose non safe method and safe method by looking at the hard type.

**Comment by peterbarker** [comment]
On Sat, 3 Nov 2018, Andrew Tridgell wrote:

> I agree with @WickedShell, we shouldn't be doing this everywhere, it just wastes CPU

I'll add that taking this out of the logging calls hides potential 
problems and gains us nothing.

**Comment by WickedShell** [comment]
@muramura What I think we are trying to get to is that while boards are getting faster we'd rather spend the CPU on new features rather then on checks that can be proven to never trigger, and in other cases can't affect the safety of flight, but do prevent us from realizing we had an issue we should be investigating.

**Comment by rmackay9** [comment]
Closing 'cuz I don't think we will be able to pull anymore of this in.  Txs though!

**Comment by muramura** [comment]
I want to clarify that it occurred by informing gcs in case of invalid value in safe_sqrt method.

**Pull request closed without merging**
