### PR TITLE
FETtec one wire on top of AP_ESC_Telem backend v5

### PR DESCRIPTION
**Pull request by amilcarlucas**
This one is based on top of a newer version #16725 with https://github.com/andyp1per/ardupilot/pull/18 on top of it.

requires #16725

It is mostly similar to #16850 , #16963, #17012 and #17063 but it is based on top of some other commits.

- [x] feature complete:
- control motor speed
- copy ESC telemetry data into MAVLink telemetry
- save ESC telemetry data in Dataflash logs
- use RPM telemetry for dynamic notch filter frequencies
- sum the current telemetry info from all ESCs and use it as virtual battery current monitor sensor
- average the voltage telemetry info and use it as virtual battery voltage monitor sensor
- [x] passes CI
- [x] compiles when HAL_WITH_ESC_TELEM = 0 (requires editing in the libraries/AP_Scripting/generator/description/bindings.desc file)
- [x] compiles when HAL_WITH_ESC_TELEM = 1
- [x] compiles when  HAL_AP_FETTECONEWIRE_ENABLED = 0
- [x] compiles when  HAL_AP_FETTECONEWIRE_ENABLED = 1
- [x] compiles when  HAL_AP_FETTECONEWIRE_ENABLED = 1 and HAL_WITH_ESC_TELEM = 0 (requires editing in the libraries/AP_Scripting/generator/description/bindings.desc file)
- [x] protocol is documented in the `README.md` file in the same location as the `.cpp` implementation file
- [x] configuration instructions are on PR ArduPilot/ardupilot_wiki#3335 the for the [ardupilot wiki](https://github.com/amilcarlucas/ardupilot_wiki/blob/patch-11/common/source/docs/common-fettec-onewire.rst)
- [ ] flight tested with a Hex frame using the last 6 channels (FETtec ID 7 to 12) 1 to 6 are unused/unassigned
- [ ] mavlink telemetry works (analyzed a `.TLOG` file to see that [ESC_TELEMETRY_1_TO_4](https://mavlink.io/en/messages/ardupilotmega.html#ESC_TELEMETRY_1_TO_4) and [ESC_TELEMETRY_5_TO_8](https://mavlink.io/en/messages/ardupilotmega.html#ESC_TELEMETRY_5_TO_8) messages are present or that [ESC_TELEMETRY_5_TO_8](https://mavlink.io/en/messages/ardupilotmega.html#ESC_TELEMETRY_5_TO_8) and [ESC_TELEMETRY_9_TO_12](https://mavlink.io/en/messages/ardupilotmega.html#ESC_TELEMETRY_9_TO_12) messages are present - using MissionPlanner->Ctrl-F->MavLinkInspector->Vehicle1->Comp1 - and their contents correct)
- [ ] `.bin` dataflash log files have ESC telemetry data in ESC7..12
- [x] flight tested with a Hex frame using the first 6 channels (FETtec ID 1 to 6)
- [ ] mavlink telemetry works (analyzed a `.TLOG` file to see that [ESC_TELEMETRY_1_TO_4](https://mavlink.io/en/messages/ardupilotmega.html#ESC_TELEMETRY_1_TO_4) and [ESC_TELEMETRY_5_TO_8](https://mavlink.io/en/messages/ardupilotmega.html#ESC_TELEMETRY_5_TO_8) messages are present - using MissionPlanner->Ctrl-F->MavLinkInspector->Vehicle1->Comp1 - and their contents correct)
- [x] `.bin` dataflash log files have ESC telemetry data in ESC1..6
- [ ] six independent [notch filters](https://ardupilot.org/copter/docs/common-imu-notch-filtering.html) work (used a hex for testing) 
- INS_HNTCH_ENABLE = 1,
- [INS_HNTCH_MODE](https://ardupilot.org/copter/docs/parameters.html#ins-hntch-mode-harmonic-notch-filter-dynamic-frequency-tracking-mode) = 3 (ESC telemetry),
- [INS_HNTCH_OPTS](https://ardupilot.org/copter/docs/parameters.html#ins-hntch-opts-harmonic-notch-filter-options) = 2 (dynamic notch)
- [INS_HNTCH_REF](https://ardupilot.org/copter/docs/parameters.html#ins-hntch-ref) = 1
- [ ] [IMU noise levels](https://ardupilot.org/copter/docs/common-imu-fft.html) measured before [notch filtering](https://ardupilot.org/copter/docs/common-imu-notch-filtering.html)
- [INS_LOG_BAT_MASK](https://ardupilot.org/copter/docs/parameters.html#ins-log-bat-mask) = 1
- [INS_LOG_BAT_OPT](https://ardupilot.org/copter/docs/parameters.html#ins-log-bat-opt-batch-logging-options-mask) = 0
- @teezeefpv please add a  [MissionPlanner FFT picture](https://ardupilot.org/planner/docs/common-measuring-vibration.html) here like described in the [noise analysis page](https://ardupilot.org/copter/docs/common-imu-batchsampling.html)
- [ ] [IMU noise levels](https://ardupilot.org/copter/docs/common-imu-fft.html) measured after [notch filtering](https://ardupilot.org/copter/docs/common-imu-notch-filtering.html)
- [INS_LOG_BAT_OPT](https://ardupilot.org/copter/docs/parameters.html#ins-log-bat-opt-batch-logging-options-mask) = 2
- @teezeefpv please add a [MissionPlanner FFT picture](https://ardupilot.org/planner/docs/common-measuring-vibration.html) here like described in the [noise analysis page](https://ardupilot.org/copter/docs/common-imu-batchsampling.html)
- [ ] Telemetry measurements replace the need for power monitoring hardware when [BATT_MONITOR](https://ardupilot.org/copter/docs/parameters.html#batt-monitor-battery-monitoring) = 9 (BLHeli ESC)
  - [ ] voltage
  - [ ] current
  - [ ] consumed power
  - [ ] temperature

Compared to master this PR needs just 592 bytes for ArduCopter on a Durandal flight controller :)

I also [backported most of this to ArduCopter-4.0.7](https://github.com/ArduPilot/ardupilot/pull/16874)

Flight logs will be uploaded to [Copting GmbH Google Drive](https://drive.google.com/drive/folders/15L3EWuRJ4yhAwteYoU15bQeZkAslj1bL?usp=sharing). It also contains older logs from previous firmware versions. Tested on a Hexacopter with Air gear 450 motors, FETtec OneWire ESCs and CubeOrange.

### CODE REVIEW

**Comment by amilcarlucas** [comment]
@teezeefpv @coptingtech the "half-voltage" bug has been fixed with commit 957ad61

**Comment by andyp1per** [comment]
hey @amilcarlucas it's going to be hard to review this until the esc notch PR is in

**Comment by amilcarlucas** [comment]
@andyp1per you should only review the three files in the AP_FETtecOneWire directory. You should ignore everything else for now.

**Comment by amilcarlucas** [comment]
@andyp1per you should only review the three files in the AP_FETtecOneWire directory. You should ignore everything else for now.

**Comment by teezeefpv** [comment]
Hi.

I just like to add the latest flight with V5. It is a 12" Quad, FFT is enabled, dynamic notch using ESC telemetry is enabled. As the copter is oscillating and noisy without the notch enabled,  I can tell that this one is working. My target was to test and log the telemetry again, especially voltage and current. 

I analysed the  dataflash-log using https://plot.ardupilot.org. I can tell that Voltage, Current and RPM is shown correctly. They can be checked in the list. 

The temp is shown correctly in Mission Planner, but the log shows it divided by 100. It seems like it has to be multiplied somewhere.

There is also something with the consumption. It increases slowly like it should, but there are two peaks in the log. I am not sure if this is a failure in the telemetry or just logging/sd card.

The flight ends with a crash. The copter became tilted. I was not able to get it leveled again. The log shows some EKF recalibration stuff, I believe it was nothing with the ESCs/Onewire.

[00000033.zip](https://github.com/ArduPilot/ardupilot/files/6337270/00000033.zip)

**Comment by amilcarlucas** [comment]
The bugs reported by @teezeefpv should be fixed there. Except the current consumption spikes. Those I have no clue.
Closed in favor of #17225

**Pull request closed without merging**
