### PR TITLE
AP_InertialSensor: Correct scaling of batch data

### PR DESCRIPTION
**Pull request by peterbarker**
@tridge found that we were applying the wrong scaling factors.  Again.

### CODE REVIEW

**Comment by magicrub** [comment]
isn't this massively significant?

**Comment by jaxxzer** [comment]
@magicrub It looks like this was only used for logging and wouldn't affect flight.

**Comment by peterbarker** [comment]
On Fri, 9 Mar 2018, Tom Pittenger wrote:

> isn't this massively significant?

Silly, but not a danger.

This scaling factor is sent through with the data.  It just means we were 
(a) not taking full advantage of the full space available in the data type 
and (b) possibly overflowing the data type in the second sensor type.

We've used this tool a bit and didn't notice until last night.

**Comment by peterbarker** [comment]
On Fri, 9 Mar 2018, Tom Pittenger wrote:

> isn't this massively significant?

... also, I should mention I've put together some documentation here:

https://github.com/peterbarker/ardupilot_wiki/commit/b7eafd7a3082f7c4fb2c06305c76fca0fc1176e3

Still a WIP.

**Pull request merged**
