### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by okok125**
I added the motor output mapping in the readme file. Convenient for users to install and connect. Thank you, please help me see if this is correct.

### CODE REVIEW

**Comment by Hwurzburg** [comment]
Motor numbers(or servo functions) are mapped to outputs by SERVOx_FUNCTIONS and are determined by the user params.
Not sure why or what you think this accomplishes and is most certainly incorrect for most users
if you are  saying the the board output numbers do not match the hwdef connections to the cpu then we need to fix the hwdef  and need SDModel to verify and approve

**Comment by rmackay9** [comment]
Hi @okok125,

Thanks for this.   Could you update the commit message (and to be clear I mean the commit itself, not the PR) to be something like, "ChibiOS: add motor output to SDMODELH7V1 README"

Sorry to be nitpicky but we like to have the subsystem prefixed and clear descriptions to ease backporting

**Comment by rmackay9** [comment]
@Hwurzburg

My guess is that he's saying the labels on the board's Mx labels don't map to the SERVOx parameters as a user might assume which seems terrible!

image

**Comment by Hwurzburg** [comment]
that would require verification from SDModel, a schematic, or dev verification with a board (I don't have one, I have the V2) in order to approve this in my opinion

**Comment by okok125** [comment]
There is currently no problem with the firmware of my SDMODEL H7V1, and I have no problem using it. I just want to remind users. When she uses Ardupilot, the motor wiring does not use the BF motor code. She needs to change the MP internal SERVO OUT to the sequence of 4,1,2,3 so that it can fly normally.
I refer to the documents here and have actually verified that the motor output is also mapped in this way.
https://ardupilot.org/copter/docs/common-holybro-kakuteh7.html

**Pull request closed without merging**
