### PR TITLE
Run the harmonic notch update at the loop rate

### PR DESCRIPTION
**Pull request by andyp1per**
Testing shows that faster notch updates reduces artificial shot noise. With bi-directional dshot very fast update rates are possible.

### CODE REVIEW

**Comment by andyp1per** [comment]
Flew 6 batteries with BLHeli and KakuteF7Mini - all fine

**Comment by rmackay9** [comment]
I guess you could check the CPU load to see if it changes.  I guess this will double the CPU impact of the notch filter but I'm not personally aware of whether that is significant.  If it improves performance then it is probably the best thing to do anyway.

**Comment by andyp1per** [comment]
After fairly extensive testing I have concluded that this has no impact on the load

**Comment by andyp1per** [comment]
Added an option and moved back into scheduler as requested by @rmackay9 and @tridge

**Review by khancyr — APPROVED** [review]
LGTM

**Review by lthall — APPROVED** [review]
This is very sensible.

**Review by tridge — APPROVED** [review]

**Pull request merged**
