### PR TITLE
Plane: Quadplane: tiltrotor: add Q_OPTION to keep motors tilted up when disarmed in FW modes

### PR DESCRIPTION
**Pull request by IamPete1**
Some tiltrotors cannot tilt motors forward when on the ground without props hitting ground (even when not spinning), this adds a option to keep the tilts pointed up. Manual mode is a exception to allow ground testing.

`Q_OPTIONS` is getting fairly full, this could be added under a new `Q_TILT_OPTIONS` parameter for tiltrotor specific options.

### CODE REVIEW

**Comment by Hwurzburg** [comment]
This function already exists as a switch option...flare

**Comment by pompecukor** [comment]
> This function already exists as a switch option...flare

Hi, Can you expand on that, we need something that works while on the ground and disarmed. To never let motors tilt forward, even if switch to RTL or FBWA. Please explain how to do it.

**Comment by Hwurzburg** [comment]
RCx_OPTION 89....forces tilts up at low throttle in fw modes for landing by switch

**Comment by IamPete1** [comment]
> This function already exists as a switch option...flare

The flair option requires the pilot to do stuff to disable / enable, it also does not work in auto throttle modes such as RTL.

**Review by tridge — APPROVED** [review]

**Comment by rmackay9** [comment]
This is included in 4.3.3-rc1

**Pull request merged**
