### PR TITLE
Allow individual Baro backends to be compiled out

### PR DESCRIPTION
**Pull request by peterbarker**
... also, allow instantiate a single Baro on SkyViper-v2450

### CODE REVIEW

**Review by amilcarlucas — COMMENTED** [review]
You could add all those new macros to the  Tools/scripts/build_options.py file

**Comment by peterbarker** [comment]
> You could add all those new macros to the Tools/scripts/build_options.py file

Yes, quite right.

That can be done as another PR which we can bicker over separately, 'though - and it doesn't need to be me to push that one through :-)

**Comment by peterbarker** [comment]
After a rebase on top of removing a bunch of things from SkyViper-v2450:
```
master: bin/arducopter   1119308      2760   193940               1122068          958688
   new: bin/arducopter   1105056      2760   193936               1107816          972944
```

**Comment by peterbarker** [comment]
Test flown on a SkyViper.  Still has a Baro

**Comment by peterbarker** [comment]
I've made the change suggested on today's DevCall to rely on the compiler eliding the functions based on the use of the prove() function or not.

I think this is absolutely incorrect:
 - it's contrary to the pattern we're using in many other places in the code
 - it doesn't provide as strong guarantees as the `#if`s - we could end up referencing symbols somehow and them not being elided
 - it's contrary to how MSP, ExternalAHRS and UAVCAN were all already done - which was the way I'd changed all the backends to use.

I'd like to pop the latest commit off this and commit the original.

**Comment by peterbarker** [comment]
... I should also mention that we can't add a `BARO` line to SkyViper as it doesn't have a constructor suitable for `BARO_PROBE_LIST` it seems.

**Comment by peterbarker** [comment]
https://github.com/ArduPilot/ardupilot/pull/19917 is a follow-on PR which makes use of these new defines to neaten the external i2c baro probing.

**Comment by tridge** [comment]
- need to explain fw size changes
- need to check that MSP, CAN and externalahrs baros still work

**Comment by tridge** [comment]
test flown with CAN and MSP baro

**Review by tridge — APPROVED** [review]

**Pull request merged**
