### PR TITLE
Added VFS system for virtual filesystem backends

### PR DESCRIPTION
**Pull request by tridge**
This implements a virtual filesystem space, allowing for multiple filesystem backends. This initial commit adds the @ROMFS/ prefix for ROMFS files. This allows Lua scripts to be embedded in ROMFS.
This replaces #13749 as it is much more general
Flash cost on CubeOrange is 1144 bytes
For ChibiOS builds scripts are placed in libraries/AP_HAL_ChibiOS/hwdef/BoardName/scripts/*.lua
For SITL builds scripts are in ROMFS/scripts in top level of build

### CODE REVIEW

**Comment by peterbarker** [comment]
```
+ modules/waf/waf-light all
Waf: Entering directory `/home/runner/ardupilot/build/fmuv3'
Failed to embed /home/runner/ardupilot/build/fmuv3/hw.dat
Failed to created ap_romfs_embedded.h
```

**Comment by tridge** [comment]
> ```
> + modules/waf/waf-light all
> Waf: Entering directory `/home/runner/ardupilot/build/fmuv3'
> Failed to embed /home/runner/ardupilot/build/fmuv3/hw.dat
> Failed to created ap_romfs_embedded.h
> ```

fixed, it depends on order of clean and configure. Interestingly, that also affected our build size!

**Comment by peterbarker** [comment]
```
Installing collected packages: pyflakes, pycodestyle, entrypoints, mccabe, flake8
Successfully installed entrypoints-0.3 flake8-3.7.9 mccabe-0.6.1 pycodestyle-2.5.0 pyflakes-2.1.1
./build/fmuv3/env.py:1:1: E999 ValueError: source code string cannot contain null bytes
}q(XHAL_WITH_UAVCANqX1qX
^
1     E999 ValueError: source code string cannot contain null bytes
1
```

**Comment by tridge** [comment]
> source code string cannot contain null bytes

yep, semaphore should not be checking generated python file env.py, I've added build to the excluded directories for flake8 in semaphore

**Comment by peterbarker** [comment]
Shouldn't we be writing out an `env.pkl` rather than `env.py`?

Doesn't look like we generate any Python in our build process ATM (yay!), but if we do then blanket-whitelisting the build directory may remove some useful static checking.

**Comment by rmackay9** [comment]
I'll give this a test, sorry for the delay!

**Comment by rmackay9** [comment]
I've successfully tested this, thanks!

**Pull request merged**
