### PR TITLE
Copter: these two errors are too common to be called "emergency"

### PR DESCRIPTION
**Pull request by tridge**
using emergency leads to panic messages in the GCS
image

### CODE REVIEW

**Review by andyp1per — APPROVED** [review]

**Review by rmackay9 — CHANGES_REQUESTED** [review]
I totally agree we should change the level but we almost never use MAV_SEVERITY_ERROR so I think perhaps we should use MAV_SEVERITY_WARNING (or INFO).  I think "ERROR" should be reserved for software or configuration errors.

WARNING, INFO and CRITICAL are the levels we most commonly use so I wonder how that got in in the first place!

**Comment by rmackay9** [comment]
@IamPete1 I guess you still have this on your to-do list to investigate the false positives?   I think you're waiting on a log file which shows false positives.

**Comment by peterbarker** [comment]
@rmackay9 we're way too simplistic about determining what the code is here.  For reference, here's the relevant enumeration and what the codes are supposed to mean:

```
    <enum name="MAV_SEVERITY">
      <description>Indicates the severity level, generally used for status messages to indicate their relative urgency. Based on RFC-5424 using expanded definitions at: http://www.kiwisyslog.com/kb/info:-syslog-message-levels/.</description>
      <entry value="0" name="MAV_SEVERITY_EMERGENCY">
        <description>System is unusable. This is a "panic" condition.</description>
      </entry>
      <entry value="1" name="MAV_SEVERITY_ALERT">
        <description>Action should be taken immediately. Indicates error in non-critical systems.</description>
      </entry>
      <entry value="2" name="MAV_SEVERITY_CRITICAL">
        <description>Action must be taken immediately. Indicates failure in a primary system.</description>
      </entry>
      <entry value="3" name="MAV_SEVERITY_ERROR">
        <description>Indicates an error in secondary/redundant systems.</description>
      </entry>
      <entry value="4" name="MAV_SEVERITY_WARNING">
        <description>Indicates about a possible future error if this is not resolved within a given timeframe. Example would be a low battery warning.</description>
      </entry>
      <entry value="5" name="MAV_SEVERITY_NOTICE">
        <description>An unusual event has occurred, though not an error condition. This should be investigated for the root cause.</description>
      </entry>
      <entry value="6" name="MAV_SEVERITY_INFO">
        <description>Normal operational messages. Useful for logging. No action is required for these messages.</description>
      </entry>
      <entry value="7" name="MAV_SEVERITY_DEBUG">
        <description>Useful non-operational messages that can assist in debugging. These should not occur during normal operation.</description>
      </entry>
    </enum>
```

If the thrust-loss error was actually correct then `EMERGENCY` might be appropriate on a quadcopter (0% thrust means you are going to fall out of the sky) but `ERROR` might be appropriate on an octaquad (0% thrust from a motor means you're going to be able to have a soft touchdown, typically).

A 10% loss of thrust is different to a 100% loss of thrust - but we're not than nuanced.

From a practical POV we need to drop these down.  But we have to fix the false-positive rate or people will become accustomed to seeing them and just ignore them!

Until we make the false-positive rate on these more sensible I'd suggest all the way down at `NOTICE`.

**Review by IamPete1 — APPROVED** [review]

**Comment by tridge** [comment]
changed based on long dev call discussion, now removed I threshold

**Comment by peterbarker** [comment]
I've corrected the commit message

**Pull request merged**
