### PR TITLE
SR73 merge to master

### PR DESCRIPTION
**Pull request by BrightSoulXYHY**
It seems there are some problem when using multi-CAN peripherals with HEX-GPS CAN protocol. When HEX-GPS connect to CubeBlack other CAN peripherals  do not work.

### CODE REVIEW

**Comment by khancyr** [comment]
Hello, this is the developpement  feature service.

Please open a post on https://discuss.ardupilot.org/ with a dataflash log for support questions. thanks

**Comment by Lumono** [comment]
@khancyr Can you open this again, actually we are talking Peter Hall to discuss this feature now.
https://discuss.ardupilot.org/t/how-to-add-new-can-sensor-in-range-finder/73377/

Peter wants a merge file for this CAN sensor.

Thanks,

**Comment by rmackay9** [comment]
@Lumono,

No need to re-open I think.  No code is lost by closing this PR and this PR is not something that we could possibly merge in its current form.  Good luck on the CAN lidar driver.

**Comment by Lumono** [comment]
Thanks @rmackay9 , I will let @IamPete1 know.

**Pull request closed without merging**
