### PR TITLE
Tools: Update solo default params to not forward to the gimbal

### PR DESCRIPTION
**Pull request by WickedShell**
@peterbarker as promised, alternative to #15128, this is the minimum PR without removing the API yet

### CODE REVIEW

**Comment by peterbarker** [comment]
Uh.  Wait.

We need to discuss with @rmackay9  - he was thinking we want this flag for other things!

**Comment by tridge** [comment]
I don't think the param change is a good fix. As long as we have a set_channel_private() API then that API should work. It either needs to clear the routing table for that channel, or apply the fix from #15128 
This PR would leave people who upgrade their solos without applying those param changes (or who load old param files) with broken gimbals

**Comment by peterbarker** [comment]
@WickedShell did you want to pursue this one?  Broken gimbals sound bad.

**Comment by WickedShell** [comment]
I wanted to remove the API and just change the default here, but I was told
on the call to do the minimal approach... If we can commit to a single
direction then I'm happy to help out, but I keep getting conflicting
changing standards on this, so I stopped addressing it.

**Comment by peterbarker** [comment]
I think I might close this.

My PR has fixed the problem in master, so this is redundant unless that change is removed, and @tridge has concerns about relying on parameters.

If we remove the API we can add something to purge the routing table - and re-remove the code that you initially removed...

**Pull request closed without merging**
