### PR TITLE
Remove GCS includes from headers

### PR DESCRIPTION
**Pull request by peterbarker**
Remove many inclusions of GCS.h header, notably the one in the HAL Util.h file.  This stops us creating dependencies where none exist, improving cache efficency

```
Board                     AP_Periph  blimp  copter  heli  iofirmware  plane  rover  sub
AIRLink                              112    0       0                 0      0      0
ARKV6X                               112    0       0                 0      0      0
ARK_GPS                   0                                                         
AeroFox-Airspeed          0                                                         
AeroFox-PMU               0                                                         
AtomRCF405NAVI                       0      0       0                 0      0      0
BeastF7                              0      0       0                 0      0      0
BeastF7v2                            0      0       0                 0      0      0
BeastH7                              0      0       0                 0      0      0
BeastH7v2                            0      0       0                 0      0      0
BirdCANdy                 0                                                         
CUAV-Nora                            120    0       0                 0      0      0
CUAV-Nora-bdshot                     120    0       0                 0      0      0
CUAV-X7                              120    0       0                 0      0      0
CUAV-X7-bdshot                       120    0       0                 0      0      0
CUAV_GPS                  0                                                         
CUAVv5                               120    0       0                 0      0      0
CUAVv5-bdshot                        120    0       0                 0      0      0
CUAVv5Nano                           120    0       0                 0      0      0
CUAVv5Nano-bdshot                    112    0       0                 0      0      0
CarbonixF405              0                                                         
CarbonixL496              0                                                         
CubeBlack                            112    0       0                 0      0      0
CubeBlack+                           120    0       0                 0      0      0
CubeBlack-periph          0                                                         
CubeGreen-solo                              0                                       
CubeOrange                           112    0       0                 0      0      0
CubeOrange-ODID                      120    0       0                 0      0      0
CubeOrange-SimOnHardWare                    0                                       
CubeOrange-bdshot                    120    0       0                 0      0      0
CubeOrange-joey                      112    0       0                 0      0      0
CubeOrange-periph         0                                                         
CubeOrange-periph-heavy   0                                                         
CubeOrangePlus                       120    0       0                 0      0      0
CubePilot-CANMod          0                                                         
CubePurple                           112    0       0                 0      0      0
CubeSolo                                    0                                       
CubeYellow                           112    0       0                 0      0      0
CubeYellow-bdshot                    120    0       0                 0      0      0
DevEBoxH7v2                          0      0       0                 0      0      0
DrotekP3Pro                          112    0       0                 0      0      0
Durandal                             120    0       0                 0      0      0
Durandal-bdshot                      112    0       0                 0      0      0
F35Lightning                         0      0       0                 0      0      0
F4BY                                 0      0       0                 0      0      0
FlyingMoonF407                       0      0       0                 0      0      0
FlyingMoonF427                       120    0       0                 0      0      0
FlywooF745                           0      0       0                 0      0      0
FlywooF745Nano                       0      0       0                 0      0      0
FreeflyRTK                0                                                         
G4-ESC                    0                                                         
H757I_EVAL                                                                          
H757I_EVAL_intf                                                                     
HerePro                   0                                                         
Hitec-Airspeed            0                                                         
HitecMosaic               0                                                         
HolybroG4_GPS             0                                                         
HolybroGPS                0                                                         
JHEMCU-GSF405A                       0      0       0                 0      0      0
JHEMCU-GSF405A-RX2                   0      0       0                 0      0      0
KakuteF4                             0      0       0                 0      0      0
KakuteF4Mini                         0      0       0                 0      0      0
KakuteF7                             0      0       0                 0      0      0
KakuteF7-bdshot                      0      0       0                 0      0      0
KakuteF7Mini                         0      0       0                 0      0      0
KakuteH7                             0      0       0                 0      0      0
KakuteH7-bdshot                      0      0       0                 0      0      0
KakuteH7Mini                         0      0       0                 0      0      0
KakuteH7Mini-Nand                    0      0       0                 0      0      0
KakuteH7v2                           0      0       0                 0      0      0
MambaF405-2022                       0      0       0                 0      0      0
MambaF405US-I2C                      0      0       0                 0      0      0
MambaF405v2                          0      0       0                 0      0      0
MambaH743v4                          0      0       0                 0      0      0
MatekF405                            0      0       0                 0      0      0
MatekF405-CAN                        0      0       0                 0      0      0
MatekF405-STD                        0      0       0                 0      0      0
MatekF405-TE                         0      0       0                 0      0      0
MatekF405-Wing                       0      0       0                 0      0      0
MatekF405-Wing-bdshot                0      0       0                 0      0      0
MatekF405-bdshot                     0      0       0                 0      0      0
MatekF765-SE                         112    0       0                 0      0      0
MatekF765-Wing                       0      0       0                 0      0      0
MatekF765-Wing-bdshot                0      0       0                 0      0      0
MatekH743                            112    0       0                 0      0      0
MatekH743-bdshot                     112    0       0                 0      0      0
MatekH743-periph          0                                                         
MatekL431-Airspeed        0                                                         
MatekL431-DShot           0                                                         
MatekL431-EFI             0                                                         
MatekL431-GPS             0                                                         
MatekL431-Periph          0                                                         
MatekL431-Rangefinder     0                                                         
MatekL431-bdshot          0                                                         
MazzyStarDrone                       0      0       0                 0      0      0
Nucleo-G491               0                                                         
Nucleo-L476               0                                                         
Nucleo-L496               0                                                         
NucleoH743                                                                          
NucleoH755                                                                          
OMNIBUSF7V2                          0      0       0                 0      0      0
OmnibusNanoV6                        0      0       0                 0      0      0
OmnibusNanoV6-bdshot                 0      0       0                 0      0      0
PH4-mini                             112    0       0                 0      0      0
PH4-mini-bdshot                      120    0       0                 0      0      0
Pix32v5                              112    0       0                 0      0      0
PixC4-Jetson                         120    0       0                 0      0      0
PixSurveyA1                          112    0       0                 0      0      0
Pixhawk1                             112    0       0                 0      0      0
Pixhawk1-1M                          0      0       0                 0      0      0
Pixhawk1-1M-bdshot                   0      0       0                 0      0      0
Pixhawk4                             120    0       0                 0      0      0
Pixhawk4-bdshot                      120    0       0                 0      0      0
Pixhawk5X                            120    0       0                 0      0      0
Pixhawk6C                            120    0       0                 0      0      0
Pixhawk6X                            112    0       0                 0      0      0
Pixhawk6X-ODID                       112    0       0                 0      0      0
Pixracer                             112    0       0                 0      0      0
Pixracer-bdshot                      112    0       0                 0      0      0
Pixracer-periph           0                                                         
QioTekZealotF427                     120    0       0                 0      0      0
QioTekZealotH743                     120    0       0                 0      0      0
R9Pilot                              0      0       0                 0      0      0
ReaperF745v2                         0      0       0                 0      0      0
SITL_arm_linux_gnueabihf             0      0       0                 0      0      0
SITL_x86_64_linux_gnu                0      0       0                 0      0      0
SPRacingH7                           0      0       0                 0      0      0
Sierra-F405               0                                                         
Sierra-F412               0                                                         
Sierra-F9P                0                                                         
Sierra-L431               0                                                         
SkystarsH7HD                         0      0       0                 0      0      0
SkystarsH7HD-bdshot                  0      0       0                 0      0      0
SuccexF4                             0      0       0                 0      0      0
Swan-K1                                                               0             
TBS-Colibri-F7                       112    0       0                 0      0      0
VRBrain-v51                          0      0       0                 0      0      0
VRBrain-v52                          0      0       0                 0      0      0
VRBrain-v54                          0      0       0                 0      0      0
VRCore-v10                           0      0       0                 0      0      0
VRUBrain-v51                         0      0       0                 0      0      0
ZubaxGNSS                 0                                                         
airbotf4                             0      0       0                 0      0      0
bbbmini                              0      0       0                 0      0      0
blue                                 0      0       0                 0      0      0
crazyflie2                           0      0       0                 0      0      0
edge                                 0      0       0                 0      0      0
erlebrain2                           0      0       0                 0      0      0
f103-ADSB                 0                                                         
f103-Airspeed             0                                                         
f103-GPS                  0                                                         
f103-HWESC                0                                                         
f103-QiotekPeriph         0                                                         
f103-RangeFinder          0                                                         
f103-Trigger              0                                                         
f303-GPS                  0                                                         
f303-HWESC                0                                                         
f303-M10025               0                                                         
f303-M10070               0                                                         
f303-MatekGPS             0                                                         
f303-PWM                  0                                                         
f303-TempSensor           0                                                         
f303-Universal            0                                                         
f405-MatekAirspeed        0                                                         
f405-MatekGPS             0                                                         
fmuv2                                0      0       0                 0      0      0
fmuv3                                112    0       0                 0      0      0
fmuv3-bdshot                         112    0       0                 0      0      0
fmuv5                                112    0       0                 0      0      0
iomcu                                                     0                         
iomcu_f103_8MHz                                           0                         
luminousbee4                         0      0       0                 0      0      0
luminousbee5                         112    0       0                 0      0      0
mRo-M10095                0                                                         
mRoControlZeroClassic                112    0       0                 0      0      0
mRoControlZeroF7                     112    0       0                 0      0      0
mRoControlZeroH7                     112    0       0                 0      0      0
mRoControlZeroH7-bdshot              120    0       0                 0      0      0
mRoControlZeroOEMH7                  120    0       0                 0      0      0
mRoNexus                             112    0       0                 0      0      0
mRoPixracerPro                       120    0       0                 0      0      0
mRoPixracerPro-bdshot                120    0       0                 0      0      0
mRoX21                               120    0       0                 0      0      0
mRoX21-777                           112    0       0                 0      0      0
mindpx-v2                            112    0       0                 0      0      0
mini-pix                             0      0       0                 0      0      0
modalai_fc-v1                        120    0       0                 0      0      0
navigator                            0      0       0                 0      0      0
navio                                0      0       0                 0      0      0
navio2                               0      0       0                 0      0      0
obal                                 0      0       0                 0      0      0
omnibusf4                            0      0       0                 0      0      0
omnibusf4pro                         0      0       0                 0      0      0
omnibusf4pro-bdshot                  0      0       0                 0      0      0
omnibusf4pro-one                     0      0       0                 0      0      0
omnibusf4v6                          0      0       0                 0      0      0
pxf                                  0      0       0                 0      0      0
pxfmini                              0      0       0                 0      0      0
revo-mini                            0      0       0                 0      0      0
revo-mini-bdshot                     0      0       0                 0      0      0
revo-mini-i2c                        0      0       0                 0      0      0
revo-mini-i2c-bdshot                 0      0       0                 0      0      0
revo-mini-sd                                                                        
skyviper-f412-rev1                          0                                       
skyviper-journey                            0                                       
skyviper-v2450                              0                                       
sparky2                              0      0       0                 0      0      0
speedybeef4                          0      0       0                 0      0      0
speedybeef4v3                        0      0       0                 0      0      0
```

### CODE REVIEW

**Comment by peterbarker** [comment]
... I've looked at the blimp size changes and there aren't any changes in symbols in the binaries.

**Comment by tridge** [comment]
worth a bit of time to work out why blimp changes, just to reinforce confidence in the tools

**Comment by peterbarker** [comment]
```
pbarker@fx:~/rc/ardupilot(pr/more-include-fixes)$ arm-none-eabi-size /tmp/tmpsoe8p4fp/out-master-CUAV-Nora/CUAV-Nora/bin/blimp
   text	   data	    bss	    dec	    hex	filename
1253516	   1944	 971016	2226476	 21f92c	/tmp/tmpsoe8p4fp/out-master-CUAV-Nora/CUAV-Nora/bin/blimp
pbarker@fx:~/rc/ardupilot(pr/more-include-fixes)$ arm-none-eabi-size /tmp/tmpsoe8p4fp/out-branch-CUAV-Nora/CUAV-Nora/bin/blimp
   text	   data	    bss	    dec	    hex	filename
1253632	   1944	 970900	2226476	 21f92c	/tmp/tmpsoe8p4fp/out-branch-CUAV-Nora/CUAV-Nora/bin/blimp
```

**Comment by peterbarker** [comment]
The discrepancies for Blimp come down to the compiler no longer eliding the strings in the init method for the CAN Manager.  Blimp creates this object but never calls init on it (which the other vehicles do).  Both master and this branch get rid of the init method itself, but the compiler just fails to clean up the init strings in this branch.

master:
```
0812d51c <_ZZL10nibble2hexhE15ConversionTable>:
 812d51c:       33323130 37363534 42413938 46454443     0123456789ABCDEF
 812d52c:       435f5041 614d4e41 6567616e 756d2072     AP_CANManager mu
 812d53c:       62207473 69732065 656c676e 006e6f74     st be singleton.
 812d54c:       2073250a 55424544 003a2047 2073250a     .%s DEBUG :..%s 
 812d55c:       4f464e49 00003a20 2073250a 4e524157     INFO :...%s WARN
 812d56c:       00003a20 2073250a 4f525245 003a2052      :...%s ERROR :.
 812d57c:       6c696146 74206465 6e69206f 61697469     Failed to initia
 812d58c:       6573696c 4e414320 746e4920 61667265     lise CAN Interfa
 812d59c:       25206563 00000064 4d4e4143 00005247     ce %d...CANMGR..
 812d5ac:       204e4143 65746e49 63616672 64252065     CAN Interface %d
 812d5bc:       696e6920 6c616974 64657a69 6c657720      initialized wel
 812d5cc:       0000006c 69646441 4920676e 7265746e     l...Adding Inter
 812d5dc:       65636166 20642520 44206f74 65766972     face %d to Drive
 812d5ec:       64252072 00000000 2078614d 626d756e     r %d....Max numb
 812d5fc:       6f207265 41432066 7244204e 72657669     er of CAN Driver
 812d60c:       78652073 64656563 0d0a6465 00000000     s exceeded......
 812d61c:       20676f4c 66667562 6e207265 6120746f     Log buffer not a
 812d62c:       6c696176 656c6261 00000000 4d4e4143     vailable....CANM
 812d63c:       67616e61 75207265 20646573 6f666562     anager used befo
 812d64c:       61206572 636f6c6c 6f697461 00002e6e     re allocation...
 812d65c:       005f3150 005f3250 005f3144 005f3244     P1_.P2_.D1_.D2_.
 812d66c:       41434c53 00005f4e 4c474f4c 4c455645     SLCAN_..LOGLEVEL
 812d67c:       00000000                                ....
```


new:
```
0812d51c <_ZZL10nibble2hexhE15ConversionTable>:
 812d51c:       33323130 37363534 42413938 46454443     0123456789ABCDEF
 812d52c:       435f5041 614d4e41 6567616e 756d2072     AP_CANManager mu
 812d53c:       62207473 69732065 656c676e 006e6f74     st be singleton.
 812d54c:       2073250a 55424544 003a2047 2073250a     .%s DEBUG :..%s 
 812d55c:       4f464e49 00003a20 2073250a 4e524157     INFO :...%s WARN
 812d56c:       00003a20 2073250a 4f525245 003a2052      :...%s ERROR :.
 812d57c:       6c696146 74206465 6e69206f 61697469     Failed to initia
 812d58c:       6573696c 4e414320 746e4920 61667265     lise CAN Interfa
 812d59c:       25206563 00000064 4d4e4143 00005247     ce %d...CANMGR..
 812d5ac:       204e4143 65746e49 63616672 64252065     CAN Interface %d
 812d5bc:       696e6920 6c616974 64657a69 6c657720      initialized wel
 812d5cc:       0000006c 69646441 4920676e 7265746e     l...Adding Inter
 812d5dc:       65636166 20642520 44206f74 65766972     face %d to Drive
 812d5ec:       64252072 00000000 2078614d 626d756e     r %d....Max numb
 812d5fc:       6f207265 41432066 7244204e 72657669     er of CAN Driver
 812d60c:       78652073 64656563 0d0a6465 00000000     s exceeded......
 812d61c:       20676f4c 66667562 6e207265 6120746f     Log buffer not a
 812d62c:       6c696176 656c6261 00000000 4d4e4143     vailable....CANM
 812d63c:       67616e61 75207265 20646573 6f666562     anager used befo
 812d64c:       61206572 636f6c6c 6f697461 00002e6e     re allocation...
 812d65c:       005f3150 005f3250 005f3144 005f3244     P1_.P2_.D1_.D2_.
 812d66c:       41434c53 00005f4e 4c474f4c 4c455645     SLCAN_..LOGLEVEL
 812d67c:       00000000                                ....
```

Perhaps we shouldn't be trusting elision quite so much...

(I did try an older compiler and it gave much the same results)

**Review by tridge — APPROVED** [review]

**Pull request merged**
