### PR TITLE
AP_VisualOdom: Support logging VISION_POSITION_DELTA message even when VISO_TYPE is not enabled

### PR DESCRIPTION
**Pull request by hoangthien94**
This PR attempts to let the [`VISION_POSITION_DELTA`](https://mavlink.io/en/messages/ardupilotmega.html#VISION_POSITION_DELTA)  message be logged whenever the FCU receives it.

Currently, the MAVLink message [`VISION_POSITION_DELTA`](https://mavlink.io/en/messages/ardupilotmega.html#VISION_POSITION_DELTA) will only be logged when param `VISO_TYPE = 1` (visual odometry enabled), as can be seen [here](https://github.com/ArduPilot/ardupilot/blob/c56acb49d6a992dff109d599c9133ade4d19d928/libraries/AP_VisualOdom/AP_VisualOdom.cpp#L111). 

My understanding from reading [GCS_Common.cpp](https://github.com/ArduPilot/ardupilot/blob/master/libraries/GCS_MAVLink/GCS_Common.cpp) is that for other vision-related messages, they will be logged whenever the messages are present. Thus, doing the same for `VISION_POSITION_DELTA` would be consistent.

### CODE REVIEW

**Comment by OXINARF** [comment]
In my opinion this isn't a good change. The reason other messages are logged is because there are no way to disable them - once they are received, they are passed to EKF.

That's not the case here. If we aren't using the VISION_POSITION_DELTA messages because it is disabled, then I don't see why we would be logging them.

**Comment by hoangthien94** [comment]
@OXINARF Thank you for the discussion. That makes total sense to me. 

The reason I find this might be useful is because `VISION_POSITION_DELTA` messages can be used to log complementary data for SLAM/external navigation data sources. Specifically, while `VISION_POSITION_ESTIMATE` and `ATT_POS_MOCAP` provides absolute position x y z, `VISION_POSITION_DELTA` provides the change in position. `VISION_POSITION_DELTA` also contains field `confidence_level`, which can be used to show SLAM's tracking confidence level, if such data is available.

How about we make a param that allows user to log the message even when `VISO_TYPE` is not available, would that be appropriate in this case?

**Comment by OXINARF** [comment]
Let me see if I understand your point: you are saying that your SLAM is sending VISION_POSITION_ESTIMATE messages but also VISION_POSITION_DELTA messages and you want both to be logged, but only the first one will be used in the EKF.

To me it seems like a rather thin use-case: there is no data correlation, the information from VISION_POSITION_DELTA wouldn't be used in ArduPilot. Also you can log it on the external system if you really need them.

> How about we make a param that allows user to log the message even when VISO_TYPE is not available, would that be appropriate in this case?

I think we have enough parameters already, I wouldn't add one for this.

This is my personal opinion though, we should see what others think.

**Comment by rmackay9** [comment]
I'm afraid I agree with @OXINARF and we shouldn't merge this.  I think what @hoangthien94 is struggling with is he can't get the confidence field into ardupilot so he's using another completely different message.  That's not the way to do it though I'm afraid.  If the message is missing a confidence field then we should add it using a MAVLink2 extension.  I think I'll close this one although I'll monitor the comments and we can re-open if required.  Also feel free to raise this at the weekly developer meeting.   I can make sure it's on the agenda if you like.

**Pull request closed without merging**
