### PR TITLE
Tools: param_parse.py: add support for CopyBitmaskFrom

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by peterbarker** [comment]
Tested by generating on master and on this branch and diffing the `apm.pdef.xml`s

**Comment by peterbarker** [comment]
I wonder if we should do this instead:
```
#if SERIALMANAGER_NUM_PORTS > 2
    // @Param: 2_OPTIONS
    // @CloneFieldsFrom: SERIAL1_OPTIONS
    // @DisplayName: Telem2 options
#endif

So it clones all fields and then you can override/overwrite just the ones you care about

**Review by tridge — APPROVED** [review]

**Comment by tridge** [comment]
nice option! copyfieldsfrom could be a future enhancement

**Review by Hwurzburg — APPROVED** [review]
nice!

**Pull request closed without merging**
