### PR TITLE
Invert ifndef HAL_NO_LOGGING to be just HAL_LOGGING_ENABLED

### PR DESCRIPTION
**Pull request by peterbarker**
I've:
 - flashed this onto a MatekF405-Wing on my desk here and tested logging
 - built the bootloaders
 - built the io firmware
 - run SITL and tested logging

### CODE REVIEW

**Comment by tridge** [comment]
@peterbarker I have added the default for AP_Periph, please check

**Comment by peterbarker** [comment]
> @peterbarker I have added the default for AP_Periph, please check

Should we also remove the values from the hwdef files as part of this patchset?

**Comment by tridge** [comment]
> Should we also remove the values from the hwdef files as part of this patchset?

yes, we should

**Comment by peterbarker** [comment]
> > Should we also remove the values from the hwdef files as part of this patchset?
> 
> yes, we should

Done

**Comment by peterbarker** [comment]
I've done the same tests as above again.

I'd have to point out that this directive is actually mostly ineffective on our main firmwares ATM; the define only affects various libraries which use functions from AP_Logger (and thus get compilation failures when AP_Logger isn't linked).  Actually making `HAL_LOGGING_ENABLED` effective on the vehicle does save substantial amounts of flash - ~30kB in a quick test I did here.  

Many more `HAL_LOGGING_ENABLED` calls will need to be sprinkled around the code to get full effect from it - for example, in `AP_NavEKF3_Logging.cpp`

**Review by tridge — APPROVED** [review]

**Pull request merged**
