### PR TITLE
Copter: Disable RTL in auto mode

### PR DESCRIPTION
**Pull request by muramura**
I disabled the RTL.
I got an error "error ModeAuto requires ModeRTL which is disabled".
I need to disable AUTO as well to disable RTL.
I think this specification is wrong.
I will limit the range of RTL disable.

RTL can be replaced by WP. Also, if you want a landing, you can achieve this by setting the LAND command after it.

### CODE REVIEW

**Review by khancyr — COMMENTED** [review]
why not ! I didn't check all implications, but the changes present here are good.

**Comment by peterbarker** [comment]
I wouldn't be against this if we rejected missions if they contained an RTL mission item (or if our mission-end action was RTL).  We're going to make it very easy for people to compile things like this out of the code in the future, and we don't want people to be surprised by fundamental things like their vehicle hovering outside of communications range rather than entering RTL.

`Auto_RTL` should be entirely removed from the enumerated list of auto sub-modes.  That will enforce handling *everywhere* `Auto_RTL` is used.

**Comment by muramura** [comment]
I disabled the ENUM value.

**Comment by khancyr** [comment]
@muramura hello, Could you rebase on Master, it should pass the test now. Then we will merge it . Thanks

**Comment by rmackay9** [comment]
I think it is a reasonable requirement that enabling Auto means that RTL must also be enabled so I don't think we should merge this actually.

I'm going to go ahead and close this.  If I've misunderstood then please feel free to re-open.

**Pull request closed without merging**
