### PR TITLE
AP_Frsky_Telem: dual battery support

### PR DESCRIPTION
**Pull request by floaledm**
Provides telemetry information through the FrSky link for the second battery instance.

Tested working.

### CODE REVIEW

**Comment by magicrub** [comment]
LGTM

**Comment by magicrub** [comment]
In the future you may want to change _paramID to an enum with a _MAX or _SIZE thing so you're chasing less magical numbers..

**Comment by lvale** [comment]
I believe this requires a change on the protocol documentation on the wiki ? @magicrub

**Comment by tomlauzon** [comment]
@lvale good catch. Will submit a PR to the wiki asap

**Pull request merged**
