### PR TITLE
hwdef: minimize_features on mini-pix, not minimize_fpv_osd

### PR DESCRIPTION
**Pull request by peterbarker**
Andy pointed out this was the wrong include in a recent PR, post-merge.

### CODE REVIEW

**Comment by peterbarker** [comment]
'though, amusingly, I was actually using the ArduPilot fpv functionality on this board via DJI stuff.

**Comment by Hwurzburg** [comment]
I thought we discussed this...since this is more a hobbyist target than a high end F407, the loss of CRSF telem would be avoided using fpv_osd rather than minimze_features

**Comment by andyp1per** [comment]
It's supposed to be a pixhawk equivalent. It doesn't even have on-board OSD - I think minimize_features is probably more appropriate

**Comment by Hwurzburg** [comment]
not passionate about this...

**Review by Hwurzburg — APPROVED** [review]

**Pull request merged**
