### PR TITLE
WIP: add support for quadmotor tailsitters

### PR DESCRIPTION
**Pull request by kd0aij**
The first 3 commits add servo functions k_throttleTop and k_throttleBot for 2 additional motors in a "plus" configuration. Differential thrust from the new top and bottom motors aid the elevons in pitch control when in VTOL modes. In fixed-wing modes, the top and bottom motors are disabled; their ESCs should have braking ON in order to stop the props and reduce drag.

The 4th commit adds hover throttle learning for tailsitters only; it is controlled by parameter Q_M_HOVER_LEARN: 0 is disabled, 1 is learn, 2 is learn and save.  The hover thrust value is saved to parameter Q_M_THST_HOVER

The 5th commit disables yaw setpoint unlocking when yaw control error is large; this is currently controlled by a hardwired parameter: AC_ATTITUDE_THRUST_ERROR_ANGLE and is set to 30 degrees.
I haven't seen an issue with this in SITL, but have often encountered it with real tailsitters; the net effect feels like "uncommanded yaw" and is quite disorienting for this pilot. I expect this behavior is useful for multicopters which end up in "unusual" attitudes, but it seems to have no advantage for tailsitters.

### CODE REVIEW

**Comment by IamPete1** [comment]
Any reason why we cant enable hove throttle learning for all Quadplanes? There is the parameter to turn it off in the motors library in any-case, I guess we could always change the param to default to off so we don't cause any behavior change. That could probably be its own PR. 

For the Quad motors would you not be better using the motor_1, motor_2.. motor_4 from Quads, then you would get all the clever quad logic for head room and min and max and things. Then you could add the motors 1 and 2 to the plane outputs. 

some feature creep would be to add a forward motors mask param so we could cover all supported copter motor configs as a tail sitter. ie the mask would tell it which motors to use for forward flight and which to shut off. 

I will have a fly of this in realflight when I get a chance. 

Thanks!

**Comment by kd0aij** [comment]
@IamPete1 Thanks for the comments:
I just pushed some updated SITL models and parameters to https://github.com/ArduPilot/SITL_Models
that I've been testing this with. They are Stryker_quad and Dart with short and long span.  The base model for both is the "Hadron" delta wing; Stryker has span and shape similar to the old Stryker and Dart is essentially a 250 class quadcopter with span of 40cm and about 80cm (long version).

I agree that we could remove the constraint on hover throttle learning if disabled by default, but Tridge thinks it is never appropriate for "conventional" quadplanes.

If I understand things correctly, the multicopter logic in this PR is treating the four motors the same as motor_1-4.  Note that the motor enable flags I added apply to motor indexes 1-4 also.

Regarding motor masks, that sounds like a good idea, but I haven't thought much about generalizing the code yet and don't really understand how the existing mask works. But my motor enable flags are probably either redundant or in conflict with a correct implementation.   Advice would be appreciated.

**Comment by IamPete1** [comment]
I think the way to go would be to add some new frame class that define a Quadplane that hovers at a different angle to forward flight. We could just add 100, so this would be a frame class 101 quad tail sitter. The existing tail sitter stuff could go to 110 for tail sitting bi-copter. 

Then we can use the copter logic. It adds clever stuff to the basic mixer currently used. We would get thrust to pwm scaling, throttle limiting to maintain attitude, current limits and other things. I think we should be able to get it to work so you can run any copter frame as a tail sitter. 

@tridge  I guess your concerned about wind with hover throttle learning for quadplaines? I think so long as we default it to off it is OK to add for all frame types? at-least it gives people the option then.

**Comment by kd0aij** [comment]
@IamPete1 I'll take a shot at adding a new quad tailsitter frame class which uses AP_MotorsMatrix instead of AP_MotorsTailsitter.  That should at least help me to understand the code.

**Comment by IamPete1** [comment]
I have just done a PR for rudder differential thrust through AP_MotorsMatrix for forward flight. This allows any of the frame types to be used in forward flight with a number of the motors switched off. Currently its only used for tilt rotors but it should be easy for us to add a new mask param to define the which motors to disable and use it for tail sitters. That should then take care of the forward flight side of using AP_MotorsMatrix. 

https://github.com/ArduPilot/ardupilot/pull/10133

**Comment by kd0aij** [comment]
@IamPete1 I've been working on a branch which inherits the MotorsTailsitter from MotorsMatrix, and have put up a PR against my own branch here for reveiw: https://github.com/kd0aij/ardupilot/pull/3

It's working in SITL with one major caveat: there is a bias in the FW roll setpoint which depends on RLL2SRV_TCONST. There's a debug print in the roll stabilize method which shows the symptom, but I've been unable to find the cause. Maybe I'm causing a very interesting memory corruption problem...

**Comment by kd0aij** [comment]
replaced by https://github.com/ArduPilot/ardupilot/pull/10401

**Pull request closed without merging**
