### PR TITLE
waf: make format specifier errors fatal

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by peterbarker** [comment]
Currently failing on cygwin in CI:

```
../../libraries/GCS_MAVLink/GCS_MAVLink.cpp: In function ‘void comm_send_buffer(mavlink_channel_t, const uint8_t*, uint8_t)’:
../../libraries/GCS_MAVLink/GCS_MAVLink.cpp:151:68: error: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 2 has type ‘size_t {aka unsigned int}’ [-Werror=format=]
         AP_HAL::panic("Short write on UART: %lu < %u", written, len);
```

The `z` format-length specifier was made for this - but our in-built vsprintf (etc) don't support that.  All our current panic methods don't seem to use our own vsprintf...

**Comment by peterbarker** [comment]
Marking as `devcall`.  Should we canonicalise on the use of our own `vsnprintf` or just use the system-supplied one?

Our own gives consistency across platforms.
Our own doesn't support things like like `%m` and `%zu`.  Adding them looks non-trivial.

We currently use a mixture of the two - seemingly at random - which means we're wasting flash.

**Comment by WickedShell** [comment]
@peterbarker I have no clue, but the inconsistency has driven me crazy, I'd love a definitive answer.

**Comment by peterbarker** [comment]
tridge has fought this battle before and retreated.  Abandoning this attempt.  Will be saving the bit that uses asprintf in the UAVCAN server stuff, however.

**Pull request closed without merging**
