### PR TITLE
Copter: Add thrust slew time

### PR DESCRIPTION
**Pull request by lthall**
This is the re based version of:
Add Thrust Slew time to copter #9470

I tried to be cleaver and do it on that pull request but it did not go to plan. Sorry.

### CODE REVIEW

**Comment by Pedals2Paddles** [comment]
Cool, thanks Leonard. I'll give it shot tomorrow after work.

**Comment by Pedals2Paddles** [comment]
Been working on tuning and chatting with @lthall about it.  The tuning is being difficult.  And the main failure scenario for the solo is when throttle is punched from low to high.  As such, it seems likely the slew time needs to be moved from before linearization to after linearization.  Per @lthall that will give the slew more impact where it needs it, and less impact where it is not needed.  And will probably help with the tuning as well.

**Comment by lthall** [comment]
Yes this needs a rework. The current implementation impacts the tune of the aircraft significantly. The slew is currently on thrust output and needs to be moved to actuator output.

**Comment by Pedals2Paddles** [comment]
Closed in favor of https://github.com/ArduPilot/ardupilot/pull/9929

**Pull request closed without merging**
