### PR TITLE
added logging of dropped log messages

### PR DESCRIPTION
**Pull request by tridge**
useful for telling how bad the microSD card is, and if there may be lost messages that change log interpretation

### CODE REVIEW

**Comment by WickedShell** [comment]
Can we get a variant for plane as well?

**Comment by rmackay9** [comment]
Looks good to me, feel free to push to master.

**Comment by tridge** [comment]
plane is already done

**Comment by tridge** [comment]
applied

**Comment by peterbarker** [comment]
On Wed, 20 Apr 2016, Andrew Tridgell wrote:

> useful for telling how bad the microSD card is, and if there may be lost
> messages that change log interpretation

dropped messages is a per-backend thing.

dataflash-over-mavlink hsa a separate message type, LOG_DF_MAV_STATS which 
is emitted at 1Hz (Dataflash_MAVLINK.cpp:509.  I think when the same is 
done for DataFlash_File modifications at the vehicle level won't be 
required like this.

**Pull request closed without merging**
