### PR TITLE
AP_HAL_ChibiOS: avoid referencing flash sector/page 22 on 1MB boards

### PR DESCRIPTION
**Pull request by peterbarker**
Pixhawk1-1M still flashes and boots after this.

Saves some space:
```
F4BY
pr/stm32-sector-fix:
bin/arducopter  967328  1284  129880  1098492
master:
bin/arducopter  968896  1284  129880  1100060


Pixhawk1-1M:
pr/stm32-sector-fix:
bin/arducopter  991616  1200  195624  1188440
master:
bin/arducopter  993340  1200  195628  1190168
```

Also... it's unclear as to whether we want to continue to fall back to flash on any of these boards that have a RAMTRON driver as a flakey ramtron can have you jumping between two sets of parameters (etc).

### CODE REVIEW

**Comment by chobitsfan** [comment]
This seems prevent cubeblack from building. Maybe I miss something? Thank you

**Comment by peterbarker** [comment]
@chobitsfan it compiles for me.  Can you paste your error in, please?

**Comment by chobitsfan** [comment]
../../libraries/AP_HAL_ChibiOS/hwdef/common/chibios_common.mk:233: recipe for target 'modules/ChibiOS/obj/flash.o' failed

In file included from ../../libraries/AP_HAL_ChibiOS/hwdef/common/chconf.h:31:0,
                 from ../../modules/ChibiOS/os/rt/include/ch.h:90,
                 from ../../modules/ChibiOS/os/hal/osal/rt/osal.h:32,
                 from ../../modules/ChibiOS/os/hal/include/hal.h:28,
                 from ../../libraries/AP_HAL_ChibiOS/hwdef/common/flash.h:18,
                 from ../../libraries/AP_HAL_ChibiOS/hwdef/common/flash.c:51:
./hwdef.h:43:28: error: expected declaration specifiers or '...' before numeric constant
 #define STORAGE_FLASH_PAGE 22
                            ^
../../libraries/AP_HAL_ChibiOS/hwdef/common/flash.c:131:15: note: in expansion of macro 'STORAGE_FLASH_PAGE'
 static_assert(STORAGE_FLASH_PAGE < STM32_FLASH_NPAGES,
               ^
../../libraries/AP_HAL_ChibiOS/hwdef/common/flash.c:132:15: error: expected declaration specifiers or '...' before string constant
               "STORAGE_FLASH_PAGE out of range");../../libraries/AP_HAL_ChibiOS/hwdef/common/chibios_common.mk:233: recipe for target 'modules/ChibiOS/obj/flash.o' failed

In file included from ../../libraries/AP_HAL_ChibiOS/hwdef/common/chconf.h:31:0,
                 from ../../modules/ChibiOS/os/rt/include/ch.h:90,
                 from ../../modules/ChibiOS/os/hal/osal/rt/osal.h:32,
                 from ../../modules/ChibiOS/os/hal/include/hal.h:28,
                 from ../../libraries/AP_HAL_ChibiOS/hwdef/common/flash.h:18,
                 from ../../libraries/AP_HAL_ChibiOS/hwdef/common/flash.c:51:
./hwdef.h:43:28: error: expected declaration specifiers or '...' before numeric constant
 #define STORAGE_FLASH_PAGE 22
                            ^
../../libraries/AP_HAL_ChibiOS/hwdef/common/flash.c:131:15: note: in expansion of macro 'STORAGE_FLASH_PAGE'
 static_assert(STORAGE_FLASH_PAGE < STM32_FLASH_NPAGES,
               ^
../../libraries/AP_HAL_ChibiOS/hwdef/common/flash.c:132:15: error: expected declaration specifiers or '...' before string constant
               "STORAGE_FLASH_PAGE out of range");../../libraries/AP_HAL_ChibiOS/hwdef/common/chibios_common.mk:233: recipe for target 'modules/ChibiOS/obj/flash.o' failed

In file included from ../../libraries/AP_HAL_ChibiOS/hwdef/common/chconf.h:31:0,
                 from ../../modules/ChibiOS/os/rt/include/ch.h:90,
                 from ../../modules/ChibiOS/os/hal/osal/rt/osal.h:32,
                 from ../../modules/ChibiOS/os/hal/include/hal.h:28,
                 from ../../libraries/AP_HAL_ChibiOS/hwdef/common/flash.h:18,
                 from ../../libraries/AP_HAL_ChibiOS/hwdef/common/flash.c:51:
./hwdef.h:43:28: error: expected declaration specifiers or '...' before numeric constant
 #define STORAGE_FLASH_PAGE 22
                            ^
../../libraries/AP_HAL_ChibiOS/hwdef/common/flash.c:131:15: note: in expansion of macro 'STORAGE_FLASH_PAGE'
 static_assert(STORAGE_FLASH_PAGE < STM32_FLASH_NPAGES,
               ^
../../libraries/AP_HAL_ChibiOS/hwdef/common/flash.c:132:15: error: expected declaration specifiers or '...' before string constant
               "STORAGE_FLASH_PAGE out of range");

**Comment by peterbarker** [comment]
@chobitsfan OK, could you paste that `hwdef.h` in, please?

Still not able to replicate.  Which OS/compiler are you using?

**Comment by chobitsfan** [comment]
https://drive.google.com/open?id=1_PM8T37aSnV9SlaP_xahmoGaC6VV5Huf

ubuntu 16.04 gcc-arm-none-eabi-4_9-2015q3

**Comment by peterbarker** [comment]
@chobitsfan OK, still not able to reproduce with that compiler :-(

You have tried doing an `rm -rf build` ?

**Comment by chobitsfan** [comment]
Yes, I have tried it and it do not work. I use git reset --hard to test. c917cd4dbb31508628a8079e2720787b52b1f14b is good and 1a123e5f8d1974c075fb39ff40a39bac45af97a6 is failed

**Comment by peterbarker** [comment]
@chobitsfan I might try on a VM next.

**Comment by chobitsfan** [comment]
thank you @peterbarker . May I ask your OS/compiler?

**Comment by chobitsfan** [comment]
I tested it on Windows 10 with linux subsystem, gcc-arm-none-eabi-6-2017-q2 and it works!

**Comment by peterbarker** [comment]
```
pbarker@bluebottle:~$ g++ --version
g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

pbarker@bluebottle:~$ which g++
/usr/lib/ccache/g++
```

```
pbarker@bluebottle:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
pbarker@bluebottle:~$ 
```

**Comment by chobitsfan** [comment]
Hi @peterbarker 

After update my compiler on ubuntu from gcc-arm-none-eabi-4_9-2015q3 to gcc-arm-none-eabi-6-2017-q2. it works well. It looks like gcc-arm-none-eabi-4_9-2015q3 is too old for this.

It is my fault and I am very very sorry for wasting your time. This is an user support question and I should not ask here. I did not check compiler version update in the first place because everything works well one day ago.

Thank you very much

**Pull request merged**
