### PR TITLE
RC_Channel: treat zero trim as average of min and max

### PR DESCRIPTION
**Pull request by tridge**
this prevents a problem with arming after RC calibration by
MissionPlanner

### CODE REVIEW

**Comment by tridge** [comment]
I did test it, and it does fix the issue.
We have asked for a fix in MP, but we've been waiting for it for a long time. I was inspired to do this today as a user I was helping hit this and was totally confused by it. 
We could fix it at boot time, but right now we don't have a RC_Channels init function to hook it in, plus a user then could not do an RC calibrate and then fly without a reboot. MP will break the trim value each time you calibrate.
The only other thing I can think of is to not do the arming check on channels beyond the number of channels the receiver is reporting.

**Comment by tridge** [comment]
ping @meee1

**Comment by lvale** [comment]
this does not occur on other GCS's like QGC.

**Comment by Kelly-Foster** [comment]
I ran into this issue, failed to arm because of trim value for unused channels below min.  Took some head scratching to figure out why ch15 mattered, and worked around it by manually modifying the trim params for the upper unused channels.  It would be nice to not have to hack things like this [after a radio calibration].  Failing to arm because of out of range parameter on unused channels makes no sense.

**Comment by tridge** [comment]
@WickedShell we need a fix for this, and we need it right now. The experience right now with the most widely used GCS is that if you follow all the wiki instructions you end up with a plane that can't fly.
We need this fix in 3.9.0.
I've now pushed a simpler fix to this PR that just skips checks for RC channels the user doesn't have. Please check it.

**Comment by rmackay9** [comment]
I've ping'd @meee1 about this issue.  [This is the MP issue that needs to get fixed](https://github.com/ArduPilot/MissionPlanner/issues/1853).

**Comment by tridge** [comment]
@rmackay9 presumably arming won't pass if RC is off. Once it is on the number of channels will be constant unless you reconfigure your transmitter

**Comment by WickedShell** [comment]
@tridge I'm happier with only checking the present channels. I still think we need to address this properly on the GCS side (and then back out this proposed patch) or a (small) hole remains however. Consider the case where a user set their input roll channel to be a channel that isn't present.

This also has effectively removed the input configuration protection for a vehicle which is flying using RC_Overrides without ever using a RC reciever, because `get_valid_channel_count(void)` will never account for overridden channels, and we still are reliant on the property of `min <= trim <= max` when using overrides.

**Comment by WickedShell** [comment]
We could address the override hole I mentioned above by changing the loop back to being over all channels and the first thing we do is
```
if (i >= num_channels && !(ch->has_override())) {
    continue;
}
```

This would accept valid overrides to get around the RC limit.

**Comment by rrr6399** [comment]
@tridge,  just to follow up with @WickedShell , we fly without an R/C at all by disabling the throttle failsafe (THR_FS).  If an R/C is required during an emergency, the R/C is turned on and the GCS detects that a non-overridden channel (channel 5 in our case) is non-zero and disables the overrides on channels 1-4 so that the R/C will work correctly.  (Right now the GCS just uses the mid-point of the R/C ranges for trim.)

**Pull request merged**
