### PR TITLE
Rover: Classify ENUM

### PR DESCRIPTION
**Pull request by muramura**
I will classify ENUM.

### CODE REVIEW

**Comment by nkruzan** [comment]
Saves a bit of flash.

**Review by nkruzan — COMMENTED** [review]
Saves a small amount of flash.

**Comment by rmackay9** [comment]
This looks pretty OK to me.  I'd like to delay merging this though until after the Rover SCurves PR goes in because it will probably cause a mass of merge conflicts.  https://github.com/ArduPilot/ardupilot/pull/19220

**Comment by khancyr** [comment]
closed by https://github.com/ArduPilot/ardupilot/pull/25066

**Pull request closed without merging**
