### PR TITLE
Fix wrong baro for FlywooF745

### PR DESCRIPTION
**Pull request by Tdogb**
Barometer on my board is the DPS310 instead of the BMP280. This implies there might be a mix of hardware configs out there. How does ardupilot handle this usually?

### CODE REVIEW

**Comment by andyp1per** [comment]
Just add both BAROs to the hwdef.

You need to remove all the other commits in the PR

**Review by andyp1per — DISMISSED** [review]
Just add both BAROs to the hwdef.

You need to remove all the other commits in the PR

**Comment by peterbarker** [comment]
I have rebased this and made appropriate changes to make this mergeable.

@Tdogb can you confirm that your FlywooF745 really did have a DP310 on it, and that your patch in here fixed it at the time, please?

**Comment by Tdogb** [comment]
> I have rebased this and made appropriate changes to make this mergeable.
> 
> @Tdogb can you confirm that your FlywooF745 really did have a DP310 on it, and that your patch in here fixed it at the time, please?

This should have fixed it yea

**Review by tridge — APPROVED** [review]

**Pull request merged**
