### PR TITLE
AP_Compass: add rotation option for AK8963_MPU9250

### PR DESCRIPTION
**Pull request by vierfuffzig**
allows using non-neutrally rotated AK8963 compass on MPU9250 as internal
reference: https://github.com/ArduPilot/ardupilot/pull/9459

### CODE REVIEW

**Comment by OXINARF** [comment]
@lucasdemarchi Are you saying this should use HAL_INS_DEFAULT_ROTATION if it is defined instead?

**Comment by vierfuffzig** [comment]
@lucasdemarchi / @OXINARF  i surely had expected that too, but it did not. neither INS_ROT nor COMPASS_ROT defines in hwdef did have any effect on compass rotation, requiring to set the mag as external and use COMPASS_ORIENT param to fix it. imho this mag/mpu's spi compas backend as is does not expect non-neutral rotation, and applying this PR did fix things. please correct me if i'm missing something.

cheers, basti.

**Comment by lucasdemarchi** [comment]
I see what's going on. You are using the generic HAL_COMPASS_DEFAULT instead of using an entry for your board. And it can't simply be HAL_INS_DEFAULT_ROTATION because the compass' axes is not aligned with the imu axes.

For the other boards this is "solved" since each of them has a different call to probe_mpu9250() passing the rotation they need.

**Comment by OXINARF** [comment]
> For the other boards this is "solved" since each of them has a different call to probe_mpu9250() passing the rotation they need.

@lucasdemarchi Which we agree makes no sense? 🙂 

> And it can't simply be HAL_INS_DEFAULT_ROTATION because the compass' axes is not aligned with the imu axes.

@lucasdemarchi Are you saying that if the 9250 IMU rotation is zero, then the compass needs a different (pre-defined) rotation? I'm wondering if there is any reason why we can't get that rotation automatically when probing via the 9250 IMU.

**Comment by lucasdemarchi** [comment]
> Are you saying that if the 9250 IMU rotation is zero, then the compass needs a different (pre-defined) rotation? I'm wondering if there is any reason why we can't get that rotation automatically when probing via the 9250 IMU.

because there's no method to do that. The access from compass to the ins has no way to know the rotation of that instance.

**Comment by tridge** [comment]
it isn't ideal, and it would be good to automate it, but this PR does the job for now, applying
@vierfuffzig thanks for the fix!

**Comment by AbhishekJoshi** [comment]
@vierfuffzig Hi, I know this is an old PR, but I want to ask you one thing as I'm struggling to understand MPU9250s.

With a default MPU-9250 rotation (based on yaw 270), what external compass setting did you use to make the MPU-9250 compass work ?

**Pull request merged**
