### PR TITLE
fix error with python3.7 and gcc 7.3.1

### PR DESCRIPTION
**Pull request by Huibean**
fix waf error TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType with python3.7 and gcc 7.3.1 math.h error

### CODE REVIEW

**Comment by Huibean** [comment]
something wrong with travis-ci

**Comment by Huibean** [comment]
something wrong with travis-ci

**Comment by khancyr** [comment]
Hello,

Could what did you compile to get and error that need include math.h in this file ?

**Comment by Huibean** [comment]
@khancyr same issue as here https://discuss.ardupilot.org/t/current-arduplane-has-a-compiler-error-acos-not-found/42553

`
/usr/local/Cellar/gcc-arm-none-eabi/20180627/arm-none-eabi/include/c++/7.3.1/cmath:83:11: error: '::acos' has not been declared
   using ::acos;
           ^~~~
compilation terminated due to -Wfatal-errors.`
Maybe I should handle this in another pr

**Comment by khancyr** [comment]
haaa that on 3.6 branch 
More over the commit what just a copy from Tridge one's. Just ask to put his PR in 3.6 backport or cherrypick his commit as you didn't really create a new commit.
But on all case with 4.0 comming out, I am not sure that 3.6 will still be supported.

**Comment by khancyr** [comment]
And this should point to master first and then be backported !

**Comment by Huibean** [comment]
@khancyr tridge's PR has other changes, I just get it working by adding math.h, anyway I just remove that change in this PR, it can not pass the travis CI test

**Comment by rmackay9** [comment]
@khancyr, @Huibean, I went ahead and merged this because I think it does no harm at least.  We won't be doing any more Copter-3.6.x releases I think but perhaps it will help any developers that are still working of the 3.6 branch.  Of course it's always best if developers work off of master but if they can.

**Pull request merged**
