### PR TITLE
fix typo...new wiki info reflects this change also

### PR DESCRIPTION
**Pull request by Hwurzburg**
reflected in wiki update: https://github.com/ArduPilot/ardupilot_wiki/pull/2630

### CODE REVIEW

**Comment by rmackay9** [comment]
I can't say if this is correct or not but in any case, I think the commit should be prefixed with "Tools:" and should probably be a bit more specific about what it's changing

**Comment by Hwurzburg** [comment]
sorry I do so many in the wiki where this discipline is not used....corrected....

**Comment by Hwurzburg** [comment]
@peterbarker can you merge this?....wiki already reflects this...thanks

**Comment by Hwurzburg** [comment]
thanks!

**Pull request merged**
