### PR TITLE
AP_HAL_ChibiOS: Pixhawk6X peripheral power on at startup

### PR DESCRIPTION
**Pull request by rmackay9**
This addresses the Hereflow startup issue recorded in the [4.5.0 issues list](https://github.com/ArduPilot/ardupilot/issues/26103) and discussed [here on the forums](https://discuss.ardupilot.org/t/copter-4-5-0-released/115614/47).

The issue is that the HereFlow sensor connected to a Pixhawk6X does not start successfully with 4.5.0 but does with 4.4.4.  The temporary work around is for users to set BRD_BOOT_DELAY to 3000 which slows AP's startup until after the flow sensor has initialised.

This PR includes a better fix by providing power to the Hereflow sensor as soon as the autopilot is powered on.  Note that this change affects more than just the CAN port (but I'm not personally sure what other ports are affected).  This change affects these boards:

- Pixhawk5X
- Pixhawk6C
- Pixhawk6X
- Durandal

This has been tested on real hardware including:

- Confirmed the user's report is correct.  E.g. Pixhawk6X with Hereflow with 4.4.4 works, 4.5.0 does not
- Confirmed that setting BRD_BOOT_DELAY to 3000 allowed 4.5.0 to work
- Confirmed that changing the nVDD_5V_PERIPH_EN to LOW allowed 4.5.0 to work with BRD_BOOT_DELAY = 0

This PR changes both the "HIPOWER" and "PERIPH" definitions.  In fact, only the 2nd definition must be changed to resolve the issue but I suspect they should be consistent.

From a quick search for "nVDD_5V_PERIPH_EN OUTPUT HIGH" these other boards may have similar issues:

- ARKV6X
- DrotekP3Pro
- fmuv5
- JFB100
- PixC4-Jetson
- RadiolinkPIX6

I'm unsure if other boards might have similar problems.

### CODE REVIEW

**Comment by amilcarlucas** [comment]
What about radios that use RTS for bootloader hold?

**Comment by rmackay9** [comment]
Hi @amilcarlucas,

Indeed, I saw that comment and it is in pretty much every board that delays the power on.  Some boards do not delay the power on though so I suspect the comment is out-of-date.

Another alternative is just to power on the CAN bus first (e.g. the 2nd definition only).  I've tested that as well successfully.

Maybe @tridge knows.

**Review by tridge — APPROVED** [review]

**Comment by tridge** [comment]
I think we should at least apply on:
 - Pixhawk6C
 - Pixhawk5X
 - Durandal

**Comment by rmackay9** [comment]
@tridge,

I've updated the hwdef files for the three boards mentioned (Pixhawk6C, Pixhawk5X, Durandal).

As a drive-by change I also correct the comments for two other boards (CUAV-X7, CUAV-Nora) that seemed to be saying the peripherals were OFF at startup when they were actually ON.

**Review by tridge — APPROVED** [review]

**Comment by rmackay9** [comment]
This is included in 4.5.2-beta1

**Pull request merged**
