### PR TITLE
aerofc: Add and use a new I2C bus

### PR DESCRIPTION
**Pull request by zehortigoza**
To this work is necessary also update the FPGA RTL(intel-aero/intel-aero-fpga#2)

### CODE REVIEW

**Comment by zehortigoza** [comment]
@lucasdemarchi ^

**Comment by zehortigoza** [comment]
What should I do to semaphoreci and continuous-integration/travis-ci/pr use my PX4Firmware patches?

**Comment by magicrub** [comment]
does this help with external compass stability?

**Comment by zehortigoza** [comment]
@magicrub I don't think so but we plan to give instructions to users connect a I2C sonar so doing this right now to avoid problems in sharing the same I2C bus between 3 devices.

**Comment by lucasdemarchi** [comment]
> What should I do to semaphoreci and continuous-integration/travis-ci/pr use my PX4Firmware patches?

I can push the PX4Firmware changes to a branch on ArduPilot/PX4Firmware, then we retrigger the build

**Comment by lucasdemarchi** [comment]
Marking as WIP as this shouldn't be pushed yet due to the (unreleased) FPGA change requirement.  Let's also do some flight tests.

**Comment by lucasdemarchi** [comment]
> does this help with external compass stability?

It looks external compass problems are more related to a) bad compass calibration or b) the compass is lose in the pole and rotating while you fly.

**Comment by lucasdemarchi** [comment]
New version at #6723

**Pull request closed without merging**
