### PR TITLE
AP_Mission: Better AUTO watchdog restore

### PR DESCRIPTION
**Pull request by Jaaaky**
This allows to run any commands following the last nav_waypoint
that may be required or change flight behavior for following wps

### CODE REVIEW

**Comment by magicrub** [comment]
Seems better than original method. Lgtm.

**Comment by peterbarker** [comment]
Laudable goal.

But will jumping to the previous navigation command always get you to `_nav_cmd.index` after simply running all your `DO`s and whatnot?  I'm thinking particularly of all of the condition stuff which may not be true after a reboot (and may, in fact, not currently be calculable given the newly-minted state of the vehicle).

I also don't understand the ordering inferred by `MIN` here - I can't see why they have to be in any particular order.

How was this tested?  Do you have the missions around (and the points at which the vehicle locked up...)?

**Comment by rmackay9** [comment]
@magicrub, I understand the desire to reduce the PR list but I don't think this should have been merged so quickly.

@Jaaaky, what testing has been performed and on which vehicles?

**Comment by Jaaaky** [comment]
> Laudable goal.
> 
> But will jumping to the previous navigation command always get you to `_nav_cmd.index` after simply running all your `DO`s and whatnot? I'm thinking particularly of all of the condition stuff which may not be true after a reboot (and may, in fact, not currently be calculable given the newly-minted state of the vehicle).

Consider do_change_speed, do_set_relay, do_repeat_servo, do_cam_trig_dist, do_inverted_flight.. Maybe a do_parachute even can save the plane?
do_fence_enable too can be important?

Of course this wouldn't run the do_commands before _prev_nav_cmd_wp_index, but it's best-effort restore.

> I also don't understand the ordering inferred by `MIN` here - I can't see why they have to be in any particular order.
> 

MIN() afraid it reached end of the mission? So +1 could load index past mission last item?
I know that _prev_nav_cmd_wp_index is set only if there is some command after it, but user can modify the mission while running -without reset- so wants to be in the safe side.

> How was this tested? Do you have the missions around (and the points at which the vehicle locked up...)?

Yes of course I've tested that using SITL. I'm planning for real flight test.
I've locked up the plane while going it a wp after do_inverted_flight.

**Comment by Jaaaky** [comment]
@rmackay9 Yes tested on ArduPlane SITL. No other vehicle has persistent_data.waypoint_num watchdog restore.

**Comment by peterbarker** [comment]
On Sun, 25 Aug 2019, Jaaaky wrote:

>       thinking particularly of all of the condition stuff which may not be true after a reboot (and may, in fact, not currently be calculable given
>       the newly-minted state of the vehicle).
> 
> Consider do_change_speed, do_set_relay, do_repeat_servo, do_cam_trig_dist, do_inverted_flight.. Maybe a do_parachute even can save the plane?
> do_fence_enable too can be important?

That's all true.  I'm just worried that we may end up flying to the wrong 
waypoint (perhaps through a hillside?).

Perhaps - for those users advanced enough to care - we could create 
something akin to a DO_LAND_START mission item that we jump to in case of 
watchdog reset.  It could do those DO things you were suggesting - or 
directly pop the parachute - and perhaps have facility to jump to the last 
recorded watchdog waypoint (DO_JUMP_WATCHDOG_WP).

Another option would be to let scripting detect watchdog reset and do... 
whatever scripts do...

> MIN() afraid it reached end of the mission? So +1 could load index past mission last item?
> I know that _prev_nav_cmd_wp_index is set only if there is some command after it, but user can modify the mission while running -without reset- so wants
> to be in the safe side.

My point is that in the face of jumps your previous navigation command 
could very well have a higher sequence number than your current waypoint 
command.  Is this something you tested?

**Comment by Jaaaky** [comment]
> My point is that in the face of jumps your previous navigation command could very well have a higher sequence number than your current waypoint command. Is this something you tested?

No, needs testing. But with MIN() it would run the current one not prev+1, LGTM. What do you think?

**Comment by Jaaaky** [comment]
> That's all true. I'm just worried that we may end up flying to the wrong waypoint (perhaps through a hillside?). 

Why would this happen particularly with this patch? It would go to the same waypoint - as previously - any way.

> Perhaps - for those users advanced enough to care - we could create something akin to a DO_LAND_START mission item that we jump to in case of watchdog reset. It could do those DO things you were suggesting - or directly pop the parachute - and perhaps have facility to jump to the last recorded watchdog waypoint (DO_JUMP_WATCHDOG_WP).

I don't think we should go further than a best-effort attempt to resume what was being run. scripting should be used if such advanced things are needed.

**Comment by rmackay9** [comment]
As @peterbarker says, I think with DO_JUMP commands in the mission this could end up with the wrong navigation command so I don't think this change is correct.  I'm going to leave this for @tridge and @WickedShell to decide on because it only affects plane.

**Comment by WickedShell** [comment]
Yeah, this is less safe and I think it should be reverted. I also suspect it doesn't give you what you actually want. If you want to try this you need to actually store and log the index of the first `DO_` we are currently running.

The larger problem I suspect though is that this doesn't actually buy you much, all the do commands for gimbal/payload control don't really matter IMO as you've just experienced an inflight reboot, all we want is to land safely. The more useful commands like DO_PARACHUTE enable/landing gear stuff may have been many nav commands back which means just the previous command's do's aren't helping you. What command is the target to ensure actually happens here?

**Comment by Jaaaky** [comment]
@wickedshell
What is the case where this is less safe? If any, it could be solved. We can run a test with most complicated cases and see what happens.

I see that this is very useful. At least you run the commands/conditions/sequences meant to be run just before current wp so actually the most significant commands in this case.

**Comment by Jaaaky** [comment]
For do_parachute many waypoints before, then it would already be run and that's fine.
But for the current waypoint, I may do
codition_distance 100
do_parachute 1
wp x,y

And a reset could occur 300 meters before the wp. So do_parachute would never be run otherwise.

**Comment by WickedShell** [comment]
Let's consider the simple case: a mission of just navigation waypoints, 1-10. Let's say the vehicle is flying to item 3 when the GCS operator sets the current waypoint to be 10 (notionally a landing or something). The previous nav waypoint in this scenario is 3. If the vehicle is restarted while flying to 10 your change will send it back to 3, then 4 in order, which is very different then what it was doing, and a lot harder to predict the vehicle state.

Your proposed use case is weird though, because for this to work with a watchdog assumption you'd have to plan *every* nav waypoint with a do_parachute before it, outside of this not coping with the scenario I gave above.

As a general side note: If you have a parachute it's probably reasonable to have an option to just pop the parachute on watchdog reset if the vehicle was armed....

**Comment by Jaaaky** [comment]
On set_current_cmd, _prev_nav_cmd_wp_index can be set to AP_MISSION_CMD_INDEX_NONE. It's meaningful as we shouldn't care about previous if the user has set the current, much like mission reset.
When prev_wp set to NONE, it would save the current one.

**Comment by WickedShell** [comment]
I'm pretty sure that's a much larger refactor then it sounds like due to the current reuse of the code. (IE the proposed change without patching would break some stuff in normal plane landing.) (There may be a hacky way around that I haven't thought of yet). This also goes back to needing more thought before this came in. Again unless you add it to every waypoint you are losing all your previous vehicle state setting commands, which between geofence, speed, parachute I think you are still losing a lot more then this is buying you, with fewer corner cases to come in and fix.

**Pull request merged**
