### PR TITLE
AP_NavEKF2: support VISION_SPEED_ESTIMATE

### LINKED ISSUE #4498: Support for: (#104) VICON_POSITION_ESTIMATE, MAVlink
#### Platform

[  ] Copter
#### Hardware type

Pixhawk

It would be nice to have support for this message to override EFK position estimation, when a ground truth is available.

Also supporting VISION_SPEED_ESTIMATE ( #103 ) and VISION_POSITION_ESTIMATE ( #102 ) would be very nice and I see lots of people trying to do this. Most of them moved to pixhawk stack where the message is supported.

### PR DESCRIPTION
**Pull request by chobitsfan**
fix #4498

It enables EKF2 fuse speed from VISION_SPEED_ESTIMATE just like speed from GPS
GCS/companion computer can use VISION_SPEED_ESTIMATE to send their velocity estimate.
It makes copters loiter performance a little better when using external navigation data (VISION_POSITION_ESTIMATE or ATT_POS_MOCAP)

below is the observation of motion capture system
vision_speed

### CODE REVIEW

**Comment by chobitsfan** [comment]
Thank you. I have changed it

**Comment by rmackay9** [comment]
I think we need this rebased but more importantly it would be good to get @priseborough's opinion on whether this is the right way to do this.

**Comment by amilcarlucas** [comment]
@priseborough can you take a look at this ?

**Comment by chobitsfan** [comment]
Hi @priseborough thank you

There are 2 logs in zip file, copter fly with the same firmware. In one log, gcs do not send VISION_SPEED_ESTIMATE, in another log gcs send VISION_SPEED_ESTIMATE
[vis_speed_test.zip](https://github.com/ArduPilot/ardupilot/files/3052496/vis_speed_test.zip)

The covariance in VISION_SPEED_ESTIMATE is a MAVLink v2 only extension and not available in MAVLink v1. Maybe we can use EK2_VELNE_M_NSE if covariance is not available in the message? Just like EK2_POSNE_M_NSE also used for external navigation system position observation noise.

**Comment by amilcarlucas** [comment]
This needs a rebase

**Comment by amilcarlucas** [comment]
Would be great to get this rebased

**Comment by rmackay9** [comment]
@amilcarlucas, I'm not sure it's great to ask the developer for a rebase unless someone is going to actively test and push it through the peer review (i.e. raise it on the dev call etc) to be sure it's merged.  I think it could just be frustrating for the developer to rebase it but then have it ignored again.

On the other hand, I think this PR is still important and I am getting closer to testing it and getting it merged.. but I'm probably still a week or two away from doing that.

**Comment by chobitsfan** [comment]
Thank you @amilcarlucas and @rmackay9 

I am sorry that I am in middle of other matters and do not have time to rebase and test it.  I will do it as soon as possible once my hand is free. Thank you

**Comment by chobitsfan** [comment]
I have rebase it and add a VISS log message to log VISION_SPEED_ESTMATE

**Comment by rmackay9** [comment]
@chobitsfan, great, thanks for this.

By the way, after this PR goes in, if you and other devs are happy with the approach I will likely merge the handling of this message into the AP_VisualOdom library.  I've done this for the vision-position-estimate messages in this new PR: https://github.com/ArduPilot/ardupilot/pull/13982

**Comment by chobitsfan** [comment]
Of course @rmackay9 Thank you

**Comment by rmackay9** [comment]
I just wanted to add that I haven't forgotten about this PR.  We have a lot of EKF fixes and changes being made recently and although this hasn't gone in, it also hasn't been forgotten, it's just about ordering.

**Comment by chobitsfan** [comment]
Thank you @rmackay9 
If you need help, please feel free to ask :)

**Comment by chobitsfan** [comment]
replaced by #14368

**Pull request closed without merging**
