### PR TITLE
AP_HAL_ChibiOS: Enable ESC telemetry and compass use for Omnibus F7 v2

### PR DESCRIPTION
**Pull request by Servox3**
Configured pin settings for the Omnibus F7 v2 flight controller to allow external ESC telemetry and compass.
ESC telemetry is configured by adding UART7 receiver pin in hwdef.dat
Compass I2C communication is configured by enabling pullup on I2C pins

### CODE REVIEW

**Comment by OXINARF** [comment]
@Servox3 Thank you for your first contribution! We don't allow merge commits, so you should rebase the code on master instead of doing a merge.

If you need help with Git (or other development issues), feel free to drop by our Gitter chat (http://gitter.im/ArduPilot/ardupilot).

**Comment by Servox3** [comment]
I rebased the code on master as requested

**Comment by IamPete1** [comment]
@Servox3 are you still interested in this? Needs another rebase....

**Comment by andyp1per** [comment]
We should close. These boards are impossible to buy now and I was unable to make bdshot work

**Pull request closed without merging**
