### PR TITLE
AUAVX21 bootloader

### PR DESCRIPTION
**Pull request by kd0aij**
moves px_uploader.py from modules/PX4Firmware to Tools/scripts
and adds support for the AUAVX2.1 with its new board ID of 33
Also adds the concept of a compatibility list matching board IDs to firmware IDs.

### CODE REVIEW

**Comment by OXINARF** [comment]
@kd0aij I guess the request to copy the script from the submodule into this repo came from @tridge?
 I'm not against it, but we need to change our tools to use it, otherwise it's pointless.

I'm not sure if @lucasdemarchi likes this though, it will make it harder to port fixes from PX4.

**Comment by lucasdemarchi** [comment]
If it's going to be used for other HALs like the chibios one, it's a sane thing to do. Of it's only for boards with px4firmware, I don't see an advantage.

**Comment by kd0aij** [comment]
@OXINARF Right, I originally created https://github.com/ArduPilot/PX4Firmware/pull/81 against PX4/Firmware and tested there. But @tridge prefers to do it this way in order to also support chibios. 
Not quite pointless, though, since it does work from the command line :)

**Comment by OXINARF** [comment]
> Not quite pointless, though, since it does work from the command line :)

@kd0aij We probably can count with one hand the number of people using it directly from the command line 🙂

**Comment by kd0aij** [comment]
This PR will be completed when support for ChibiOS is added

**Comment by magicrub** [comment]
what's status on this? @kd0aij says it's ready when there's ChibiOS support. It has arrived.

**Comment by khancyr** [comment]
do we still need this ?

**Comment by kd0aij** [comment]
@magicrub @tridge I had forgotten about this, and don't know whether this functionality has since been implemented in some other way. IIRC, my comment that it "will be completed" meant that Tridge would integrate it eventually :)
I assume that the X21 is handled correctly by GCSs, but I haven't tested that myself lately.

**Comment by tridge** [comment]
we don't need the rename of the script as that has been done and the script is now Tools/scripts/uploader.py
I'm not sure about the compatible IDs change. I suspect that is still needed. Can you rework it to just have that change against master?

**Comment by kd0aij** [comment]
new PR: https://github.com/ArduPilot/ardupilot/pull/10683

**Pull request closed without merging**
