### PR TITLE
AP_RangeFinder: TeraRanger Evo error codes rejection

### PR DESCRIPTION
**Pull request by pl-kabaradjian**
This pull request corrects a bug where the error codes of the sensor were taken into the moving average thus making the distance measurement incorrect. We also changed a bit the structure, added missing semaphore release, changed naming and added comments.

The driver has been tested indoor and outdoor without any issues. My only concern is the following: in the case where the sensor had no valid measurements between two update() calls, should the state distance be set to some value (0 for example) along to setting the status to "RangeFinder_NoData"? or should it keep the last valid measurement (safer ?) ?

Thanks in advance for your time !

### CODE REVIEW

**Comment by rmackay9** [comment]
@pl-kabaradjian, sorry it's taken so long to get to this PR.  Could you rebase this on master?  we should get rid of the "Merge.." commits from the PR.  If that's too difficult I can get rid of them as part of the merge.

Now, I guess that perhaps this adds support to the existing TeraRangerTower driver so that it supports the new EVO version?  .. but I just merged [this other PR](https://github.com/ArduPilot/ardupilot/pull/8732) which adds a new driver for the EVO.  Does that mean that this PR's change isn't required any more?

@msadowski, any ideas?

**Comment by msadowski** [comment]
@rmackay9 I'm a bit out of the loop with those things now but it seems to me that the other PR was for the Teraranger Tower (serial port comms, up to 8 sensors connected at the same time) and this one is for a single sensor talking through I2C. 

Since those two PRs target different hardware I would say that this merge is also desirable.  

@pl-kabaradjian about the behaviour of the driver when there is no valid data then I'd personally go for indicating not valid measurement instead of keeping the last value. This sound safer to me as some part of the code down the line can switch to other sources of height/altitude information instead of relying on fake data.

**Comment by pl-kabaradjian** [comment]
@rmackay9 This PR is to update the driver of a Single Teraranger Evo used as a RangeFinder (here using I2C). So it is not related to the Tower Evo code (i.e the PR you are mentioning) that communicates through serial to a dedicated piece of hardware as pointed out by @msadowski.

Concerning the rebase i will try in the beginning of next week but it shouldn't be an issue.

@msadowski we are already updating the status of the RangeFinder_State structure to "RangeFinder_NoData", but I was wondering wether the distance in the state structure should be set to zero or left as the last value. This, in order to handle the case where some part of the code would read the distance without checking the status first.

@rmackay9 any idea of the correct behaviour in that case?

**Comment by rmackay9** [comment]
Actually it was easy to cherry-pick in the changes so merged!

**Comment by rmackay9** [comment]
I'm also including this in Copter-3.6.0-rc8 which will go out in the next day or two.

**Comment by pl-kabaradjian** [comment]
Thanks @rmackay9  and @msadowski for your time!

**Pull request closed without merging**
