### PR TITLE
Mission: fix bounds checking of MISSION_ITEM lat/lon

### PR DESCRIPTION
**Pull request by WickedShell**
Addresses #4249

### CODE REVIEW

**Comment by magicrub** [comment]
I made check_latlng() specifically for this and thought I caught all the use cases. Thanks for finding this!

**Comment by WickedShell** [comment]
The only problem with using that rather then checking individually in place
is you can't send the correct MAV_RESULT enum.

**Comment by magicrub** [comment]
Yup. I plan to fix that tomorrow.

**Comment by magicrub** [comment]
Thanks, merged.

**Pull request closed without merging**
