### PR TITLE
AP_Scripting: Only allow scripting restart if disarmed

### PR DESCRIPTION
**Pull request by IamPete1**
This requires the vehicle to be disarmed for scripting to be re-started. Scripts can still be stopped while armed. This is because I found another case where scripting restart causes a flight controller lockup and watchdog on real hardware. 

In that case I restarted the `math.lua` test. There have been several of these that we have now fixed, but there might be more we have not found. 

Crash dump output and watchdog decode from that one are here: 
 https://discord.com/channels/674039678562861068/719466647710072832/1120113508877598780

### CODE REVIEW

**Comment by timtuxworth** [comment]
Scripting is being used and recommended for hard-core flight time work like device drivers. If it can stop and stay stopped, then those recommended uses might need to be re-considered.

**Comment by IamPete1** [comment]
> Scripting is being used and recommended for hard-core flight time work like device drivers. If it can stop and stay stopped, then those recommended uses might need to be re-considered.

Its not a script problem, its that restarting scripts can cause the flight controller to lock up. Its fine for the majority but there are some cases we have not tracked down. 

If you don't try and restart there is no problem.

**Review by tridge — CHANGES_REQUESTED** [review]
we need to get to the bottom of the actual cause

**Comment by IamPete1** [comment]
This is the reproduction:

- Default params, `SCR_ENABLE` 1, `SCR_VM_I_COUNT` to 100000 (10x the default)
- Load [math.lua](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Scripting/tests/math.lua)
- Reboot and let it run, you should see a `Math tests passed` message 
- Restart scripting

 I used a CubeOrange-Plus on master. The same thing works on stable, I have not tried other boards.

**Comment by tridge** [comment]
@IamPete1 this PR fixes the issue for me:
https://github.com/ArduPilot/ardupilot/pull/24218

**Comment by IamPete1** [comment]
We have fixed the particular crash that prompted me to open this, https://github.com/ArduPilot/ardupilot/pull/24231

However, I suspect there are others we have not found yet....

**Pull request closed without merging**
