### PR TITLE
these functions return bool, and doing bitwise operations on a bool is incorrect

### PR DESCRIPTION
**Pull request by davidbuzz**

### CODE REVIEW

**Review by peterbarker — CHANGES_REQUESTED** [review]
You've *significantly* changed the behaviour of this code.

We probably need to add a comment here explaining what the whole `&` vs `&&` thing is all about.  `&` never shortcuts.  `&&` does.

**Comment by rmackay9** [comment]
We've been down this road a few times before so clearly we need a comment at the top.

The reason we do it this way is to ensure that all the checks are run not just the first one.

**Comment by davidbuzz** [comment]
when building with clang, the compiler complained that doing bitwise operations on a bool was bad behaviour.   clang.

**Comment by davidbuzz** [comment]
ok, so maybe we need to put some explicit cast/s in here or something to quieten the compiler, or at least a comment saying its considered ok despite the compiler ..?

**Comment by davidbuzz** [comment]
i guess i'll just close it then.  :-(

**Comment by rmackay9** [comment]
@davidbuzz i think both those suggestions are good ones.

**Pull request closed without merging**
