### PR TITLE
Copter: add disarm on land detect option to PILOT_THR_BHV

### PR DESCRIPTION
**Pull request by jschall**

### CODE REVIEW

**Comment by rmackay9** [comment]
I wonder if this behaviour should be here or whether it might be better to be copied into every control_xxx.cpp file where it checks the ap.land_complete state.  I know that sounds like a lot of duplication but it seems more consistent to me with how we've written the flight modes.

**Comment by jschall** [comment]
Hmm... I think that makes sense. I can modify the PR.

**Comment by rmackay9** [comment]
ok txs.  I've added the rework flag which you can feel free to remove once you've updated the PR.  txs

**Comment by jschall** [comment]
@rmackay9 
Problem: this needs to happen only on the transition from flying to landing, and not just if(ap.land_complete) - otherwise it will disarm upon arming. I looked at putting it in e.g. control_loiter, but I found that there is no way to do something on a state transition - i.e., loiter_state is a local variable and thus is not actually a state (very weird, might as well have a big if-else.) Shall I refactor the mode "state machines" so that they actually have persistent state or would you prefer to reconsider your position on accepting this PR as-is?

I'm a fan of doing it this way (i.e. event driven). Otherwise we have to add a state so that we can detect the rising edge on ap.land_complete. I'd be a big fan of architectural changes such that this sort of problem could be solved by ALT_HOLD registering an event handler for LAND_COMPLETE and thus the behavior can be specified by the mode.

**Comment by jschall** [comment]
@rmackay9 ping

**Comment by rmackay9** [comment]
Merged!  Thanks and once again, sincere apologies for how long this took.

**Pull request closed without merging**
