### PR TITLE
AP_GPS: Add missing const to the rest of the headers

### PR DESCRIPTION
**Pull request by Ryanf55**
* Related to #23743, but I missed this since I didn't realize the buffer was not modified in-place

### CODE REVIEW

**Review by magicrub — APPROVED** [review]

**Review by rmackay9 — DISMISSED** [review]
Hold on now, I don't think we should be actively changing formatting when there's a a disagreement in the team about style.  If we start doing this then we could end up with a tug of war of competing PRs.

Maybe this one file is OK but let's not make a habit of it.

**Comment by Ryanf55** [comment]
> Hold on now, I don't think we should be actively changing formatting when there's a a disagreement in the team about style. If we start doing this then we could end up with a tug of war of competing PRs.
> 
> Maybe this one file is OK but let's not make a habit of it.

Thanks. I'm happy to talk about this const-thing, and related safety coding standard to the dev team at the next dev call.

**Comment by magicrub** [comment]
Randy. Only you are against the const. I don't know why you resist it. This should be an insta merge.. not a dev call topic

**Comment by rmackay9** [comment]
@magicrub,

I don't think I'm the only one.  In general I will go with the flow if I'm the only one.

**Comment by andyp1per** [comment]
const for pointers is a good thing, not sure why this would be controversial.

**Comment by peterbarker** [comment]
> const for pointers is a good thing, not sure why this would be controversial.

This isn't just const-for-pointers-and-references.

This is also `const` for pass-by-value things like floats and integers.  I don't think anybody is arguing about pointers/references, just the pass-by-value things.

It comes down to this:
```
void MyClass::foo(const char *buffer, uint8_t buflen) {
    const uint8_t max_bytes_to_process = 17;
}
```

vs

```
void MyClass::foo(const char *buffer, const uint8_t buflen) {
    const uint8_t max_bytes_to_process = 17;
}
```

vs

```
void MyClass::foo(const char *buffer, uint8_t buflen) {
    uint8_t max_bytes_to_process = 17;
}
```

Nobody's going to argue about the `const` on the `char*`

In all cases there all integers are on the stack.  The buffer length should definitely not change for the duration of the function body - so why not `const` it to make sure that if some *does* decide to change the function body to do a `while (buflen--)` they don't end up breaking code further down in the function?

Note the local variable - *nobody* is going to argue about having `const` in there.  But we *do* argue about it when the local comes in as part of the function parameters!

Also, please note my use of `{` not on its own line in the function definition.  Added that as an alternative fuel source for this bonfire.

**Comment by rmackay9** [comment]
@peterbarker, thanks for the clarification, I agree with what the issue is.

@andyp1per's right that this is not a good example of the issue we argue over.  Somehow I thought this was adding a const in front of the uint8_t arguments but in fact it's only in front of the pointer arguments which is a good idea.

So I'm happy with this going in, sorry for holding things up.

**Pull request merged**
