### PR TITLE
ESP32: new HAL layer for esp32 including hal

### PR DESCRIPTION
**Pull request by davidbuzz**
new HAL layer for esp32
see libraries/AP_HAL_ESP32/README.md for more.
Author: Charles Villard <charlesvillard10@gmail.com>
Author: Buzz <davidbuzz@gmail.com>

### CODE REVIEW

**Comment by nkruzan** [comment]
Thanks for all the hard work that has went into this!

**Comment by davidbuzz** [comment]
@Silvanosky  and myself will both be available to discuss thois PR at the next eu dev call .

**Comment by davidbuzz** [comment]
note - tridge said he's happy for anyone to merge it when ci passes.

**Comment by davidbuzz** [comment]
re-running ci due to seemingly-unrelated flapping test in FetTEC tests.

**Pull request merged**
