### PR TITLE
Replace OPTFLOW define with OPTICAL_FLOW

### PR DESCRIPTION
**Pull request by olliw42**
this replaces the define OPTFLOW with OPTICAL_FLOW

OPTFLOW is also used in some enums, and as a result it was e.g. not possible to define the usage of optical flow in the hwdef file; writing e.g. "define OPTFLOW 0" did produce errors. This renaming resolves this. It might be a good thing anyway to not have such name overlapping.

### CODE REVIEW

**Comment by amilcarlucas** [comment]
Should`nt this be HAL_WITH_OPTICAL_FLOW?

**Comment by andyp1per** [comment]
> 
> 
> Should`nt this be HAL_WITH_OPTICAL_FLOW?

Yes I think if we are going to change it it should be to the new standard, which I think would be:

either ```HAL_OPTICAL_FLOW_ENABLED``` or ```HAL_WITH_OPTICAL_FLOW```

**Comment by olliw42** [comment]
well, I certainly don't care what name would be used and am happy to change to any, nor would I understand what the rules are, but it is confusing

there are some HAL_OPTFLOW_ONBOARD_xxx and HAL_OPTFLOW_PX4xxx in the HAL libs

also, in none of the config.h nor the build-with-disabled-features.py I find options named HAL_xxxx, they are all named the "old" way ...

so, just from that pattern it looks a bit weird...

my personal feeling would be that a name with an ENABLED in it would be most readable

**Comment by hendjoshsr71** [comment]
Closing this one as it was fixed as part of https://github.com/ArduPilot/ardupilot/pull/19615

Thank you though for the work on this one!

**Pull request closed without merging**
