### PR TITLE
Copter: Added support for change-alt command in Guided mode #1507

### PR DESCRIPTION
**Pull request by salonijain12**
Added support for change-alt command in Guided mode #1507

### CODE REVIEW

**Comment by rmackay9** [comment]
Thanks for the change.  A few issues:
- there's no need to update the copter's current_loc to the target location.
- Guided mode has a few "sub modes" (velocity control, position control, etc).  We don't know which sub-mode it's in so to ensure it's the position mode and that it's correctly organised, we should call guided_set_destination().  We should probably also check that the vehicle is in GUIDED mode.

**Comment by salonijain12** [comment]
@rmackay9 , Thanks for the review. Yes it is good to call guided_set_destination() instead of calling set_wp_destination().
Please help me to understand below point:
"there's no need to update the copter's current_loc to the target location." -- Does this means that we should change the destination wp altitude and not update the current_loc as target location. 

That is, we should first get the wp destination by copter.wp_nav.get_wp_destination() and then change its altitude to the altitude present in command and then call guided_set_destination() after checking the mode as GUIDED.

**Comment by rmackay9** [comment]
@salonijain12, yes, I think that sounds correct.  Definitely no reason to change the current_loc's altitude because that's the vehicle's current estimated altitude.  If you change that who knows what will happen at other points in the code where it checks the vehicle's altitude for various reasons.

**Comment by salonijain12** [comment]
@rmackay9 , Thanks, I will share the updated PR

**Comment by khancyr** [comment]
@rmackay9 Any objection to close this one ? We should use setpoints to update alt and not the hack on the wp

**Comment by khancyr** [comment]
Closed as really outdated and doesn't use the right message.

**Pull request closed without merging**
