### PR TITLE
Sub: add to the main makefile

### PR DESCRIPTION
**Pull request by amilcarlucas**

### CODE REVIEW

**Comment by rmackay9** [comment]
I'm not qualified to review this one I think so I've taken myself off the list and added Peter!

**Comment by amilcarlucas** [comment]
@OXINARF Thanks for the heads up. I'll look into that.

**Comment by amilcarlucas** [comment]
Done

**Comment by OXINARF** [comment]
Merged, thanks!

**Comment by amilcarlucas** [comment]
Why is the state of this PR closed and not merged ?

**Pull request closed without merging**
