### PR TITLE
Servo output optimization

### PR DESCRIPTION
**Pull request by andyp1per**
Split out from https://github.com/ArduPilot/ardupilot/pull/27029

This is an optimization that avoids a repeated N^2 lookup in motor output that proves to be quite expensive at high rates (i.e. involving dshot).

### CODE REVIEW

**Review by IamPete1 — COMMENTED** [review]
I think we could re-work `find_channel` to pull the index of the first set bit in the existing `channel_mask`, the result should be the same except it would work for all outputs.

**Comment by andyp1per** [comment]
> I think we could re-work `find_channel` to pull the index of the first set bit in the existing `channel_mask`, the result should be the same except it would work for all outputs.

That's a neat idea - I will try it!

**Comment by andyp1per** [comment]
> I think we could re-work `find_channel` to pull the index of the first set bit in the existing `channel_mask`, the result should be the same except it would work for all outputs.

Actually I don't think this works as there is no map from function to channel - you first have to find a channel with the right function before you can find the output. Avoid the long iteration though the function map is the main thing being avoided here. Maybe I have misunderstood your idea - if so could you please elaborate?

**Comment by andyp1per** [comment]
Closing is favour of https://github.com/ArduPilot/ardupilot/pull/27849

**Pull request closed without merging**
