### PR TITLE
adjust the sequence of sensors

### PR DESCRIPTION
**Pull request by gitfishup**
adjust the sequence of IMU sensors to have a good performance.

### CODE REVIEW

**Comment by gitfishup** [comment]
@tridge Could you please have a review?

**Review by peterbarker — DISMISSED** [review]
Commit message needs to change; should be something like:

```
AP_HAL_ChibiOS: hwdef: reorder CUAV-X7 IMUs

adjust the sequence of IMU sensors to have good performance.
```

**Comment by gitfishup** [comment]
> Commit message needs to change; should be something like:
> 
> ```
> AP_HAL_ChibiOS: hwdef: reorder CUAV-X7 IMUs
> 
> adjust the sequence of IMU sensors to have good performance.
> ```

Do you mean "git commit -m AP_HAL_ChibiOS: hwdef: reorder CUAV-X7 IMUs adjust the sequence of IMU sensors to have good performance." or the after commit ,the conversation message?

**Comment by gitfishup** [comment]
> Commit message needs to change; should be something like:
> 
> ```
> AP_HAL_ChibiOS: hwdef: reorder CUAV-X7 IMUs
> 
> adjust the sequence of IMU sensors to have good performance.
> ```

how about this?

**Review by tridge — APPROVED** [review]

**Comment by tridge** [comment]
@peterbarker I checked that we do give appropriate arming failures for reordered IMUs

**Pull request merged**
