### PR TITLE
AP_AHRS: Set degree level board orientation for racing quads making use of tilted rotors

### PR DESCRIPTION
**Pull request by dgrat**
This patchset allows free definitions of the board orientation.
Defining a board orientation with degree resolution is especially important for racing quads.
Such quads make often use of tilted rotors applied on the frame.
Currently, the tilit correction is applied directly after board orientation (enum) was applied. 

**Note:** I did not remove the old board orientation code, because of compatibility reasons, 
but I hope it will be fine to remove it later. Also want to mention that the condition of matrix3f is not good.

**Example:**  In case you use e.g. 10° tilted motor mounts, 
it is necessary to correct this tilt for stable hover, otherwise the copter goes straight on.
Here I added some parameters allow to define the board orientation at degre level. 
If the copter thinks it is tilted by e.g. 10° it should hover in a stable way with such mounts. 

@magicrub 
Thanks for review first version, but I added some changes. I think, this one will be able to fly.

### CODE REVIEW

**Comment by tridge** [comment]
how is this better than the current AHRS_TRIM_X and AHRS_TRIM_Y parameters? They are in radians, but the user just sets the rotors level and then asks the GCS to perform a trim.
Note that a change went in recently by Jon Challinger to make the existing trim parameters accurate over a wide range of angles.

**Comment by dgrat** [comment]
@tridge 
Because range: -0.1745 +0.1745

**Comment by dgrat** [comment]
@tridge 
and because these variables are undefined.

**Comment by tridge** [comment]
It's easy to fix the range.
if we're after a better way to set these then we could fix it in the GPS, or we can just redefine these in degrees and rename them. Re-doing the maths doesn't seem right to me. The existing maths has been very carefully done by Jon.

**Comment by dgrat** [comment]
@tridge 
Sounds reasonable. Do you think we can remove the board_orientation parameters?
Theoretically, all we need is the trim..

**Comment by WickedShell** [comment]
Custom orientation came in in #7877. Sorry this seems to have been ignored.

**Pull request closed without merging**
