### PR TITLE
APM_Control: prevent divide by zero on YawController

### PR DESCRIPTION
**Pull request by khancyr**
Append with XPlane see https://discuss.ardupilot.org/t/arduplane-sitl-floating-point-exception/64241
I am not sure of my solution. Better fix welcome.

### CODE REVIEW

**Comment by peterbarker** [comment]
It would be nice to know how we can get a zero speed scaler in there.

Given the way the speed scaler is passed around in Plane, fixing it in yaw controller might just move the problem elsewhere (it may exhibit in ways other than division-by-zero....)

Do you know if this was a quadplane?  https://github.com/ardupilot/ardupilot/blob/master/ArduPlane/Attitude.cpp#L29 one way we can get a zero speed scaler, but it is quadplane-specific.

... or a zero scaling speed parameter: https://github.com/ardupilot/ardupilot/blob/master/ArduPlane/Attitude.cpp#L16

Definitely worth the discussion as to whether to paper over the problem as this PR does :-)

**Comment by khancyr** [comment]
Yeee I am not sure of my solution nor the root cause. I have asked for more info on how to trigger this.

I open this as PR as it seems critical and would be easier to track down that way.
But it is definitely worth yo check that scaler cannot be zero as currently nothing protect it

**Comment by peterbarker** [comment]
@khancyr it was decided at the DevCall to avoid papering over the problem.  Do you have a means to reproduce this problem and extract a stack trace?

**Comment by peterbarker** [comment]
Nudge @khancyr

**Comment by khancyr** [comment]
I got no way to produce this. I think I will close this for now

**Pull request closed without merging**
