### PR TITLE
Servo function doc

### PR DESCRIPTION
**Pull request by arikrupnik**
3264fd750b47fe3bb4f716b23e23557e5d351fab added three new `SERVOx_FUNCTION` values. Should we include them in the relevant `AP_GROUPINFO`?

### CODE REVIEW

**Comment by rmackay9** [comment]
I think this looks generally OK but @arikrupnik could you remove the "Rover: fixing typo in comment" and the "Merge.." commits?  Maybe you need to do a rebase on master.

**Comment by arikrupnik** [comment]
Not sure what happened there with the typo commit--I thought it had already been merged.
Rebased.

**Review by rmackay9 — APPROVED** [review]

**Review by rmackay9 — CHANGES_REQUESTED** [review]
Ah, one more thing.  The commit title should start with "SRV_Channel:" instead of "libraries:".  Sorry I didn't notice this on my previous review.  After that's fixed I think we can merge, txs

**Comment by arikrupnik** [comment]
Rebased again to accommodate recent addition of sail mast rotation servo function

**Comment by peterbarker** [comment]
Labelled DevCall in case Randy doesn't get to it.

**Review by tridge — APPROVED** [review]

**Comment by rmackay9** [comment]
Merged, thanks!

**Pull request merged**
