### PR TITLE
AP_Scripting: update serial_test.lua

### PR DESCRIPTION
**Pull request by craigy72**
AP_Scripting: correct uart example

### CODE REVIEW

**Comment by rmackay9** [comment]
@craigy72, one small thing, the commit should be prefixed with "AP_Scripting:"

**Comment by craigy72** [comment]
I'm no GitHub expert tbh but I think I have made the correct change?

**Comment by rmackay9** [comment]
@craigy72,

It's probably correct.. but re the change, instead of changing the title of the PR, it's the title of the commit that should be fixed up. txs!

**Comment by craigy72** [comment]
Ok created a new commit - hope that works for you.

**Comment by rmackay9** [comment]
OK, I've squashed and merged to master thanks!

Note, this PR appears closed but the contents have actually be merged and the author remains as craigy72.

**Pull request closed without merging**
