### PR TITLE
Remove Trailing Whitespace

### PR DESCRIPTION
**Pull request by MichelleRos**
Thought I'd do a bit of a clean up.

### CODE REVIEW

**Review by peterbarker — CHANGES_REQUESTED** [review]
Please don't.  This makes the git history much harder to traverse.

This is a real problem which causes me time.

**Comment by peterbarker** [comment]
... what would be nice is a mechanism where no new bad trailing whitespace can be introduced.  i.e. the delta has to be no-worse than master.

**Comment by MichelleRos** [comment]
@peterbarker Well, VSCode has an option where it removes it from any file you edit (this PR of course, I didn't do with that since it only does one file at a time)... But I thought you guys didn't like whitespace changes mixed in with other commits. That's why I thought a clean-up PR would be helpful.
I will now be turning off the remove trailing whitespace option...

**Comment by rmackay9** [comment]
@MichelleRos,

In general I'm happy to merge formatting fixes for copter and rover or the libraries that I'm maintainer for.. you'd need to split them into separate commits though as well.  You're of more than welcome to fix blimp too of course 'cuz you're the maintainer of that one.

**Pull request closed without merging**
