### PR TITLE
AP_HAL_ChibiOS: fix kakutef7/mini motor glitch when using dshot

### LINKED ISSUE #9861: KakuteF7 DMA on UARTs causes DShot issue
This is a bug report from Paul Atkin @utkinpol 
Paul is using a KakuteF7, and finds that he needs to use NODMA on UARTs to get reliable flight on a small racing quad.
Paul, please put all details in this issue, including:

 - parameters (full file)
 - at least one DF log showing the issue
 - list of all peripherals (receiver, any uart connections, any i2c devices etc)
 - any other information that you think may be helpful

### PR DESCRIPTION
**Pull request by chobitsfan**
fix #9861
replace #15241 and #14995

### CODE REVIEW

**Review by andyp1per — APPROVED** [review]

**Comment by andyp1per** [comment]
Tested on my KakuteF7 mini, all seems ok. According to the forums this successfully fixes a motor glitch. Adding to dev call for @tridge review/feedback.

**Comment by 1wick** [comment]
Is it possible the Omnibus Nano has the same issue?   I'm trying to figure out some motor glitches I'm having on my omnibus copters.  Usually little twitches.  Sometimes a big one where if I'm not very high, I'd crash.

**Comment by tridge** [comment]
this causes us to lose DMA for receive on Telem1 (USART1). That is probably OK for these boards

**Comment by chobitsfan** [comment]
Thank you @tridge 

> this causes us to lose DMA for receive on Telem1 (USART1).

Yes. I am afraid that there may be no better arrangement due to DMA controller and motor pinout. Maybe I could add a note in kakutef7/aio/mini doc, to suggest user to uart2 instead of uart1.

**Comment by chobitsfan** [comment]
Hi @1wick 

> Is it possible the Omnibus Nano has the same issue? I'm trying to figure out some motor glitches I'm having on my omnibus copters. Usually little twitches. Sometimes a big one where if I'm not very high, I'd crash.

It is possible because STM32F4/F7 seems use the same DMA controller. However I do not have omnibus f4 nano, and I am not sure about it.

**Comment by tridge** [comment]
btw, I suspect a better fix would be to add retries to the DShot DMA sends. Right now if the DShot DMA send fails then we just skip it for that loop. It would be really nice to be able to automatically retry when the DMA channel becomes available. That would require some restructuring in HAL_ChibiOS, but would likely fix this properly for all boards

**Comment by chobitsfan** [comment]
Thank you @tridge 

>It would be really nice to be able to automatically retry when the DMA channel becomes available

I could try to do it. It may need thoroughly test, because it affect all boards.

**Comment by peterbarker** [comment]
.... so are we merging this one, @chobitsfan ?  @andyp1per ?

**Comment by andyp1per** [comment]
@peterbarker yes please. UART1 is next to the Video pins on the KakuteF7Mini so natural to use it for CRSF VTX control or smart audio - so DMA not so necessary. I think slower performance preferable to copters dropping out of the sky

**Comment by peterbarker** [comment]
Merged, thanks!

**Comment by amilcarlucas** [comment]
How about backporting this to 4.0 ?

**Comment by chobitsfan** [comment]
> How about backporting this to 4.0 ?

Yes. I think I need to create a branch based on [copter-4.0](https://github.com/ArduPilot/ardupilot/tree/Copter-4.0) and create a PR? Thank you

**Pull request merged**
