### PR TITLE
RC_Channel: improved efficiency of min_max_configured

### PR DESCRIPTION
**Pull request by tridge**
this is quite a costly function due to scan in AP_Param. It takes
about 4 to 5 milliseconds when done as part of AP_Arming

### CODE REVIEW

**Comment by WickedShell** [comment]
Is this the possible source/major contributor to the reliable 1Hz long loop counts someone was reporting on copter recently?

**Comment by tridge** [comment]
yes, its the primary cause of really long loops while disarmed.
When armed this code doesn't run.

**Comment by peterbarker** [comment]
LGTM.

**Comment by rmackay9** [comment]
.. cuz everyone's in agreement, merged!

**Pull request merged**
