### PR TITLE
waf: fix build for px4

### PR DESCRIPTION
**Pull request by guludo**
Hi all,

This PR is fixing the build for PX4 boards. I can't test it right now, I'll try doing that when I get the chance.

@OXINARF I cherry picked some of your commits. I changed the commit message of one of them, if that's alright to you.

This is just fixing the build for PX4. Enhancements requested at http://discuss.ardupilot.org/t/waf-build-for-px4/8396 are still to be done.

Best regards,
Gustavo Sousa

### CODE REVIEW

**Comment by guludo** [comment]
Besides, it's been already a long time since we started using submodules. :-)

**Comment by guludo** [comment]
s/I can't test it right now/I can't **flight** test it right now/

**Comment by lucasdemarchi** [comment]
Tested uploading to a pixhawk and connecting with mavproxy. It works fine.

**Comment by lucasdemarchi** [comment]
Applied with a slight different order and with a revert in PX4Firmware

**Pull request closed without merging**
