### PR TITLE
Compass/All vehicles: remove compass.accumulate

### PR DESCRIPTION
**Pull request by rmackay9**
compass.accumulate is a noop on all backends so after discussion with @tridge, I've created this PR to remove it from the compass library and all vehicles.

For Rover, Sub and Copter, the accumulate is removed and only the compass.init_location() call remains which tells the compass it's location so it can lookup it's declination.  I've reduced it's update rate to 1hz, we could increase this to 10hz if people think it's important.

Plane and Tracker's compass_accumulate functions could be removed completely because their compass.init_location is called as part of the udpate_GPS function.

### CODE REVIEW

**Comment by WickedShell** [comment]
Looking briefly at what actually happens in the `compass_init_location` I wonder if it should just be moved into the 1 second loop? It's in the same vein as the home position updates that happen there, and it's being run at the same frequency. Moving it should slightly reduce the overhead.

You can also probably remove the check for compass enabled, as all the initial_location call does is set an initial automatic declination. It doesn't require the compasses actually be detected to work. The advantage of doing this early is that if compasses are suddenly enabled in flight the declination is already correct, otherwise you could get up to a second of stale declination data if you moved the vehicle. (This is a crazy edge case though, the main win is just the simplicity of not checking the parameter)

**Comment by rmackay9** [comment]
@WickedShell, yes, I also thought about putting it into the one-hz loop as well.  I'll move it there..

**Comment by rmackay9** [comment]
@WickedShell, you OK this this?

**Comment by WickedShell** [comment]
@rmackay9 Yeah, looks fine to me. I might have gone further and actually manually inlined the init function, but that's definetly a style thing, and I'm happy with it as currently presented.

**Pull request merged**
