### PR TITLE
Do not create bad vector from uninitialised location

### PR DESCRIPTION
**Pull request by peterbarker**
This vector should only be using when the seg_end_type says it should be used.  As it currently stands the Location will be all-zeroes so the vector will be... odd.

Closes https://github.com/ArduPilot/ardupilot/issues/12215

### CODE REVIEW

**Comment by peterbarker** [comment]
Testing-wise this has only been tested as far as autotest tests things, including the new test.

**Comment by peterbarker** [comment]
It would *possibly* be better to pass through pointers if the Location / Vector3 are valid rather than relying on the segment type to determine if the values contained in the Location/Vector3 are valid.  That's a rather more intrusive change.

**Comment by tridge** [comment]
I've tested this with spline waypoints and it flies correctly

**Comment by rmackay9** [comment]
ok great, merged!

**Pull request merged**
