### PR TITLE
AP_Proximity: Allow multiple proximity backends

### PR DESCRIPTION
**Pull request by rishabsingh3003**
This is a big overhaul of the Proximity library to allow for multiple backends, i.e connect multiple lidars. With this PR I think it is much closer to its near relative, the AP_RangeFinder library.

The problem was that we had included a lot of methods in the Backend that did not belong there (example: 3D boundary code, OA DB functions, etc). As a result, I had to shift them into new, more appropriate classes so that they are not copied/duplicated when we connect multiple proximity sensors.

TO-DO:

- [ ] Figure out arming check behaviour

- [ ] Figure out how to log multiple sensors

- [ ] Test for breakages

### CODE REVIEW

**Comment by xianglunkai** [comment]
@rishabsingh3003 very good! 
I think maybe a less modification method can be referred to as follows:
https://github.com/xianglunkai/ardupilot/tree/sf_usv_master/libraries/AP_Proximity
In this way, you can only change the backend and front.
Thank you very much!

**Comment by rishabsingh3003** [comment]
Hi @xianglunkai 
Thanks for linking your branch. I am planning to handle parameters better, just like the RangeFinder library. It seems like you have done the same in your branch.

The reason why this PR is so invasive and big is that I am trying to align the Proximity library to the traditional backend-frontend split. The problem is that when we make new backends, we will end up duplicating the huge 3-D boundary which we only really need to construct once. Let me know if you have more suggestions for me

**Comment by xianglunkai** [comment]
@rishabsingh3003 Yes, you are right. Consider putting 3-D boundary on the back end as a singleton instance ？

**Comment by rmackay9** [comment]
by the way, my main sponsor brought this up recently so this is higher on my to-do list.

**Pull request closed without merging**
