### PR TITLE
Tools: improve compass calibration testing

### PR DESCRIPTION
**Pull request by khancyr**
Improve calibration testing process:
Try calibration cancellation and check it doesn't write params and orient
Try calibration start during an already calibration running and check that it doesn't reset the calibration
Try calibration failure and check that it doesn't write params and orient
Try arming during calibration and check it is rejected
Try calibration, wait success, check that it doesn't write params without acceptation, check acception, check that params are updated, check that orientation is updated, check that it request reboot to arm. Test arming after calibration.

Two things aren't tested yet: selecting the compass to calibration, calibrate all compass at once, buzzer and notify during calibration

### CODE REVIEW

**Comment by tridge** [comment]
thanks for this work! It is failing due to non-ascii chat on common.py:3916. It can be a good idea to run flake8 over new python code

**Comment by tridge** [comment]
btw, when developing a test, it is a good idea to manually make the test fail by temporarily breaking the code you are testing just to confirm the test really does catch the error

**Comment by peterbarker** [comment]
@bugobliterator you've been writing more tests in this area too, I believe?

Are things going to conflict horribly?

**Comment by bugobliterator** [comment]
> @bugobliterator you've been writing more tests in this area too, I believe?
> 
> Are things going to conflict horribly?

Yes, I just saw this, and I think there will be lot of conflict. There's a lot of overlap on what I am implementing and this PR.

**Comment by khancyr** [comment]
Rebase with @bugobliterator changes on SITL and loop over multiple compass.
The test now test differents bitmask : 0, 1, 11, 111.
Each time it test : 
- Try calibration cancellation at 30% and check it doesn't write params and orient. It also try that another compass cal request don't reset the current calibration state. 
- Try calibration failure with low fitness parameter and check that it doesn't write params and orient. Try arming during calibration and check it is rejected

- Try calibration, wait success, check that it doesn't write params without acceptation, check acception, check that only the requested parameters are updated, check that orientation is updated, check that it request reboot to arm. Test arming after calibration, and unsure that we cannot try calibration if armed.

One test that I didn't write is to unsure that only external compass got the update of orientation.
Currently, having wrong orientation on the internal compass make the calibration to report a failure.
I didn't test buzzer and notify.

I have manually test the failure of the tests by modifying the library.

**Comment by khancyr** [comment]
closed as merged as part of another PR

**Pull request closed without merging**
