### PR TITLE
AP_ESC_Telem: fix rounding in RPM logging

### PR DESCRIPTION
**Pull request by mbuzdalov**
The variables `rpm` and `rawrpm` were cast to `int32_t` before they get multiplied by 100, which is wrong. This PR fixes it.

This PR is mutually exclusive with #25978.

### CODE REVIEW

**Review by magicrub — APPROVED** [review]
LGTM, thanks!

**Review by andyp1per — APPROVED** [review]

**Comment by IamPete1** [comment]
Why don't we log as float? int32 is the same size.

**Comment by mbuzdalov** [comment]
> Why don't we log as float?

I guess RPM came once as int32, and when that was refactored, logging was not changed.

I am happy to convert this to float and try it out, if you wish.

**Comment by magicrub** [comment]
replaced by https://github.com/ArduPilot/ardupilot/pull/25978

**Pull request closed without merging**
