### PR TITLE
Support icm42xxx gyro rate

### PR DESCRIPTION
**Pull request by andyp1per**
This is on top of #21233

Support fast sample rates on the ICM-42xxx series. This also sets the anti-aliasing filters to half the sample rate.

### CODE REVIEW

**Comment by andyp1per** [comment]
Results from a very short hover in my office:

image

The noise looks good to me and we get the expected outcomes post-filter. This is for the ICM-42688. The pre-filter results for the ICM-42605 are on the right. I'm guessing the large cut up above 1500Hz is the on-board notch filter. In this config (4k gyros) the ICM-42688 has an AAF at 2Khz and the ICM-42605 has none - I think you can see this in the lack of roll-off on the far right graph but its not obviously much worse and doesn't matter by the time we have done our own filtering.

**Comment by andyp1per** [comment]
1min hover in loiter with ICM-42688 as the primary:

image

**Comment by andyp1per** [comment]
ICM-42688 short dynamic flight:

image

**Comment by andyp1per** [comment]
1min hover in loiter with ICM-42605 as the primary
image

**Comment by andyp1per** [comment]
ICM-42605 short dynamic flight

image

**Comment by andyp1per** [comment]
There is clearly more noise on the ICM-42605 at lower frequencies, although I'm not totally sure where it is all coming from since it doesn't all appear in the pre-filter logs - maybe its because the batch logging is sequential so the logging does not happen at precisely the same time and the noise is not quite the same.

I get high vibes on both IMUs (30-50m/s/s) and some clipping in dynamic flight, certainly much worse than the MPU6000 (5-10m/s/s). I will need to experiment with the accels at either a lower sample rate or more heavily filtered to see if that makes any difference. Clearly the accel sensor is quite sensitive - so maybe the issue is simply that it is a better sensor.

**Comment by andyp1per** [comment]
42688 @4Khz with 3P AAF at 1Kz in hover:

image

There definitely appears to be a reduction in aliasing noise (e.g. around 150Hz) and you can see the stronger rolloff at the higher frequencies

**Comment by andyp1per** [comment]
Same config, dynamic flight:

image

Definitely less aliasing noise and accels are much better

**Comment by andyp1per** [comment]
And here is where it is tons better:

image

much lower vibes and no clipping, so my guess is that a lot of these issues were caused by high frequency aliasing noise. There might be an argument for going even lower on the accel AAF.

**Comment by andyp1per** [comment]
After a lot of discussion with @priseborough and @lthall we have zeroed in on this scheme which appears to work well:
```
  set the filter frequencies and scaling

  The AAF for gyros needs to be high enough to avoid group delay and low enough to have
  (ideally) 40dB at the nyquist frequency so that noise above this is not folded into the
  range seen by ArduPilot. A reasonable approximation for the former is 1Khz and for the latter
  1/4 of the sample frequency, so for 1/4 sample frequency > 1Khz we pick 1Khz and for 1/4 sample
  frequency < 1Khz we use 1/3 sample frequency instead.

  The AAF for accels is set lower to minimise noise and clipping. The constraint is that the
  group delay between gyros and accels should be <5ms to inertial nav errors.

  The UI filter block cannot be disabled and is fixed at ODR/4. This is a 2p filter by default
  (as is the AAF). Since the order of the UI filter does not appear to significantly affect
  group delay at higher ODRs it is left at the default. The group delay of the AAF is not documented,
  but we assume it is similar to the UI 2p performance:

  2Khz  - 0.2ms
  1Khz  - 0.4ms
  666Hz - 0.6ms
  500Hz - 0.8ms
  333Hz - 2.0ms
  190Hz - 2.4ms

  Since the UI group delay is the same for both accels and gyros we only need to consider the
  difference in group delay for the AAFs. At the highest ODR of 4Khz or 8Khz the group delay for
  gyros will be 0.4ms thus the accel AAF can safely be set to ~190Hz.
```

**Comment by lthall** [comment]
I would stick with 1/4 all the way on the gyro, maxing out at 1kHz.

**Comment by SupaflyFPV** [comment]
> After a lot of discussion with @priseborough and @lthall we have zeroed in on this scheme which appears to work well:
> 
> ```
>   set the filter frequencies and scaling
> 
>   The AAF for gyros needs to be high enough to avoid group delay and low enough to have
>   (ideally) 40dB at the nyquist frequency so that noise above this is not folded into the
>   range seen by ArduPilot. A reasonable approximation for the former is 1Khz and for the latter
>   1/4 of the sample frequency, so for 1/4 sample frequency > 1Khz we pick 1Khz and for 1/4 sample
>   frequency < 1Khz we use 1/3 sample frequency instead.
> 
>   The AAF for accels is set lower to minimise noise and clipping. The constraint is that the
>   group delay between gyros and accels should be <5ms to inertial nav errors.
> 
>   The UI filter block cannot be disabled and is fixed at ODR/4. This is a 2p filter by default
>   (as is the AAF). Since the order of the UI filter does not appear to significantly affect
>   group delay at higher ODRs it is left at the default. The group delay of the AAF is not documented,
>   but we assume it is similar to the UI 2p performance:
> 
>   2Khz  - 0.2ms
>   1Khz  - 0.4ms
>   666Hz - 0.6ms
>   500Hz - 0.8ms
>   333Hz - 2.0ms
>   190Hz - 2.4ms
> 
>   Since the UI group delay is the same for both accels and gyros we only need to consider the
>   difference in group delay for the AAFs. At the highest ODR of 4Khz or 8Khz the group delay for
>   gyros will be 0.4ms thus the accel AAF can safely be set to ~190Hz.
> ```

thanks for this, very interesting...

**Comment by robustini** [comment]
Very interesting, my Crocodile 7 is happier, thanks @andyp1per!

**Comment by andyp1per** [comment]
Merged into #21233

**Pull request closed without merging**
