### PR TITLE
SRV_Channel: added AM32 to the SERVO_DSHOT_ESC param docs

### PR DESCRIPTION
**Pull request by tridge**
setting 3 works well with AM32

### CODE REVIEW

**Comment by tridge** [comment]
@andyp1per what value should users use for BlueJay?

**Comment by andyp1per** [comment]
@tridge BlueJay should be 2 and 4. I think AM32 should be 1 and 3 - the timing is the same for both, its just that 1 does not request EDT information.

**Comment by tridge** [comment]
@andyp1per thanks, updated PR. I had a user ask me about BlueJay setting today

**Review by andyp1per — APPROVED** [review]
Note that there is an argument that says if there are no versions of AM32 that don't support EDT then we should always recommend 3, but what you have here is undoubtedly correct.

**Pull request merged**
