### PR TITLE
AP_Math: Some clean-up suggestions

### PR DESCRIPTION
**Pull request by dgrat**
@lucasdemarchi 
  - Macros: ToRad/ToDeg removed
  - constrain_* wrappers removed 
  - linear_interpolate replaced

I know you have doubts, because of the constrain wrappers, but as long as they exist, people will use them, and I think it is better if not.

### CODE REVIEW

**Comment by OXINARF** [comment]
@dgrat Once again this is failing the SITL test in a way that it shouldn't - the aircraft is continuously hitting the ground but the EKF variance doesn't go up?

I also want to say that **I** disagree with all three commits. Replacing the old ToRad/ToDeg macros is fine, but the replacement for template is not. I think it will bring more trouble than solving some. The other two are for the same reason: I much prefer to use the wrappers than having to use templates everywhere.

**Comment by dgrat** [comment]
@OXINARF 
why?

**Comment by dgrat** [comment]
@OXINARF 

The problem is still that a module is not found. Could a file is not considered while rebase?

```
Created /home/travis/build/ArduPilot/buildlogs/ArduCopter-test.tlog.gpx with 69853 points
/bin/sh: 1: gpsbabel: not found
	zip warning: name not matched: /home/travis/build/ArduPilot/buildlogs/ArduCopter-test.tlog.kml

zip error: Nothing to do! (/home/travis/build/ArduPilot/buildlogs/ArduCopter-test.tlog.kmz)
Traceback (most recent call last):
  File "/home/travis/.local/bin/mavflightview.py", line 10, in <module>
    from MAVProxy.modules.mavproxy_map import mp_slipmap, mp_tile
  File "/home/travis/.local/lib/python2.7/site-packages/MAVProxy/modules/mavproxy_map/__init__.py", line 11, in <module>
    from MAVProxy.modules.mavproxy_map import mp_elevation
  File "/home/travis/.local/lib/python2.7/site-packages/MAVProxy/modules/mavproxy_map/mp_elevation.py", line 12, in <module>
    import numpy
ImportError: No module named numpy

```

**Comment by dgrat** [comment]
If you wish to have wrapper functions everywhere for everything it is fine, I don't force anyone to take a commit. I personally, wouldn't produce such code :D

**Comment by OXINARF** [comment]
> why?

Why I think it will bring more trouble? Because I think people won't remember that they have to use float to do a simple radians/degrees conversion, so I'm seeing code like `radians(20)` getting into master and then causing problems. If we are always returning float now, why not continue to do it? That's what is expected.

> The problem is still that a module is not found. Could a file is not considered while rebase?

As I've told you before, that is not the problem. The underlying problem is a bug in Copter (that is now fixed in master), but even with that bug the test shouldn't behave like that. My guess is that your conversion to template is wrong in some place and causing the EKF not to rise even while banging on the floor.

> If you wish to have wrapper functions everywhere for everything it is fine, I don't force anyone to take a commit. However, I personally wouldn't produce such code :D And the SITL test is weird, if you look at the raw log you see there is soemthing weird going on in one of the scripts :D

Can you tell me what we gain with the template versions vs the wrappers?

**Comment by dgrat** [comment]
@OXINARF 
Got the problem.

**Pull request closed without merging**
