### PR TITLE
AP_HAL_ChibiOS: use standard FPV config for SpeedyBeeF405WING

### PR DESCRIPTION
**Pull request by andyp1per**
We get endless support questions relating to features of the SpeedyBeeF405WING - e.g. https://discuss.ardupilot.org/t/speedybee-f405-wing-no-esc-telemetry/112650 - this PR simply adopts minimize_fpv_osd which includes all the features that people are after. There is still 50k flash free after this.

### CODE REVIEW

**Review by Hwurzburg — COMMENTED** [review]
I am fine with this although we should inform SpeedyBee before merging since they actually specified what features to remove...I can tell them
Also why did choosing to add the ESC telem in the build server NOT work to enable this? are we going to fix that?

**Comment by andyp1per** [comment]
@Hwurzburg as far as I know this does not remove any additional features - it only adds in missing features

**Comment by Hwurzburg** [comment]
> @Hwurzburg as far as I know this does not remove any additional features - it only adds in missing features
it does...the bolded ones I consider issues:
!AP_ADVANCEDFAILSAFE_ENABLED
-!HAL_BARO_WIND_COMP_ENABLED
-!AP_CAMERA_MAVLINK_ENABLED
**-!AP_CAMERA_MOUNT_ENABLED**
-!HAL_DISPLAY_ENABLED
-!HAL_HIGH_LATENCY2_ENABLED
-!AP_INERTIALSENSOR_KILL_IMU_ENABLED
**-!AP_LANDINGGEAR_ENABLED**
-!AP_LTM_TELEM_ENABLED
-!AP_MAVLINK_MSG_MOUNT_CONFIGURE_ENABLED
-!AP_MAVLINK_MSG_MOUNT_CONTROL_ENABLED
-!AP_MAVLINK_MSG_RELAY_STATUS_ENABLED
-!AP_MISSION_NAV_PAYLOAD_PLACE_ENABLED
-!AP_MOTORS_FRAME_DECA_ENABLED
-!AP_MOTORS_FRAME_DODECAHEXA_ENABLED
-!AP_MOTORS_FRAME_OCTAQUAD_ENABLED
-!AP_MOTORS_FRAME_Y6_ENABLED
-!HAL_MOUNT_ALEXMOS_ENABLED
**-!HAL_MOUNT_ENABLED
-!HAL_MOUNT_SERVO_ENABLED**
-!HAL_MOUNT_SIYI_ENABLED
-!HAL_MOUNT_STORM32SERIAL_ENABLED
-!AP_NOTIFY_NCP5623_ENABLED
-!AP_RC_CHANNEL_AUX_FUNCTION_STRINGS_ENABLED
-!AP_SBUSOUTPUT_ENABLED
**-!QAUTOTUNE_ENABLED**

**Comment by andyp1per** [comment]
@Hwurzburg ok I have added those back in - still 15k free which seems decent

**Review by Hwurzburg — APPROVED** [review]

**Pull request merged**
