### PR TITLE
AP_Compass: fix calibrator on NuttX

### PR DESCRIPTION
**Pull request by jschall**
The value of INT16_MIN on NuttX is positive.

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
Please fix the Nuttx header so we won't have to remember this and refrain from using it in other places

**Comment by jschall** [comment]
It is fixed upstream.

**Comment by lucasdemarchi** [comment]
Só... Cherry pick the commit

**Comment by lucasdemarchi** [comment]
@jschall See https://github.com/ArduPilot/PX4NuttX/pull/9

Tested with the following diff:

```c++
diff --git a/libraries/AP_Compass/CompassCalibrator.cpp b/libraries/AP_Compass/CompassCalibrator.cpp
index de1215e..b67e380 100644
--- a/libraries/AP_Compass/CompassCalibrator.cpp
+++ b/libraries/AP_Compass/CompassCalibrator.cpp
@@ -707,6 +707,9 @@ uint16_t CompassCalibrator::get_random(void)
 //////////// CompassSample public interface //////////////
 //////////////////////////////////////////////////////////
 
+#if INT16_MIN != -32768
+#error wat???
+#endif
 #define COMPASS_CAL_SAMPLE_SCALE_TO_FIXED(__X) ((int16_t)constrain_float(roundf(__X*8.0f), INT16_MIN, INT16_MAX))
 #define COMPASS_CAL_SAMPLE_SCALE_TO_FLOAT(__X) (__X/8.0f)
```

**Comment by jschall** [comment]
Do it however you like. I have no appetite for yak-shaving.

**Pull request closed without merging**
