### PR TITLE
AC_Avoid: Report fence mitigation

### PR DESCRIPTION
**Pull request by IamPete1**
This uses a new mavlink extension to report when mitigation action is taken to prevent a fence breach, This is the requited ArduPilot mavlink PR https://github.com/ArduPilot/mavlink/pull/108, the extension is already in mavlink master.

### CODE REVIEW

**Comment by IamPete1** [comment]
This is also a enabler for https://github.com/ArduPilot/ardupilot/pull/12117

**Comment by rmackay9** [comment]
Looks pretty good, you've tested it in SITL?  Also I just want to be sure that it only triggers when the vehicle is slowing because of a fence, not because of an object seen with the proximity sensor?

I guess it's only horizontal right?  It's probably ok for it to only cover horizontal for now in any case.

**Comment by IamPete1** [comment]
I hadn't considered proximity, but your right it should not trigger for that, I think it might currently in Z. I will check. I have tested that it runs in SITL but I wasn't seeing the extended message in MP's mavlink inspector, I guess because I would need to update MP's mavlink also.

**Comment by IamPete1** [comment]
This has now passed thanks to the advice on how to snyc the correct submodule commit. I think so-long as I have done that correctly this is ready to go in. I have set plane to always report no fence mitigation action, I think this is correct? The only other question is if it is OK to leave the updated message in mavlink common or if it should be moved to ardupilotmega since it is now different to the upstream one.

**Comment by peterbarker** [comment]
On Tue, 5 Nov 2019, Peter Hall wrote:

> This has now passed thanks to the advice on how to snyc the correct submodule commit. I think so-long as I have done that correctly this is ready to go
> in. I have set plane to always report no fence mitigation action, I think this is correct? The only other question is if it is OK to leave the updated
> message in mavlink common or if it should be moved to ardupilotmega since it is now different to the upstream one.

Submit a patch ustream to fix it IMO.

**Comment by auturgy** [comment]
Patch upstream please. Would also be useful link this PR to it.

Regards,

James

**Comment by IamPete1** [comment]
rebased to fix mavlink conflict

**Comment by IamPete1** [comment]
I'm completely failing to get this to point at the right mavlink stuff now, not sure where I have gone wrong? Should I change the submodule branch? I have also tried to cherry pick the relevant commit on top but it can seem to find it, should be this one https://github.com/ArduPilot/mavlink/commit/54d1270c47f1641ebe04fc7fd5acff7da334ccf0

**Comment by peterbarker** [comment]
@IamPete1 looks like you need to force-push your branch in ardupilot/mavlink; this head commit should be `8cfe` if I'm thinking right: https://github.com/ArduPilot/mavlink/commits/fence_warn

**Comment by IamPete1** [comment]
rebased and hopefully fixed my mavlink linking issue

**Comment by rmackay9** [comment]
as discussed on the dev call, now that the mavlink change has gone in, this just needs rebasing and that last commit fixed so that we use AP's latest mavlink commit.

**Comment by IamPete1** [comment]
I think https://github.com/ArduPilot/ardupilot/pull/12874 has to go in first, as its AP/Mavlink message got in first, I cant advance the head past that to get to the Mavlink commit for this?

**Comment by rmackay9** [comment]
@IamPete1, I don't think it's an issue is it?  I think we just need the last commit of this PR pointing to the ArduPilot/mavlink repo's HEAD

**Comment by IamPete1** [comment]
rebased and advanced cherry picked the mavlink commit in, Would be great if someone could check the mavlink sub module is OK.

**Comment by IamPete1** [comment]
I'm failing at advancing to my commit without the EFI one

**Comment by IamPete1** [comment]
rebased, no longer need to update mavlink as its already in sync with master

**Comment by rmackay9** [comment]
Merged, thanks!

**Pull request merged**
