### PR TITLE
Allow to embed parameters in ROMFS

### PR DESCRIPTION
**Pull request by lucasdemarchi**
This allows PX4-based boards to embed default parameters in the ROMFS, saving them as /etc/defaults.parm. This sets the defaults for aerofc, to be used in the Intel Aero RTF.

### CODE REVIEW

**Comment by WickedShell** [comment]
We had something along those lines at one point, @tridge had pointed it out to both @magicrub and myself for custom vehicles if we wanted to bake it into firmware. What happened to it?

**Comment by lucasdemarchi** [comment]
> We had something along those lines at one point, @tridge had pointed it out to both @magicrub and myself for custom vehicles if we wanted to bake it into firmware. What happened to it?

I wasn't aware of a previous effort to have this. And... what do you mean? Is this "custom vehicle" another way to do it or what?

**Comment by peterbarker** [comment]
On Mon, 5 Jun 2017, WickedShell wrote:

> We had something along those lines at one point, @tridge had pointed it out
> to both @magicrub and myself for custom vehicles if we wanted to bake it
> into firmware. What happened to it?

Are you refering to the PX4 ROMFS?

**Comment by WickedShell** [comment]
There was a way to bake in a default parameters file if you were doing your
own build. So for either case we were both deploying firmware images to a
bunch of identical vehicles, so we could bake the parameters into the ROMFS
directly. I never did it as it was a bit more effort then just deploying an
given hash.

Peter: yeah

**Comment by magicrub** [comment]
@WickedShell what @lucasdemarchi is doing is just taking advantage of the current default.parm method by baking it into the build system. Example, if we "make solo" we could have different defaults than "make aerofc-v1" and so on.

**Comment by magicrub** [comment]
I don't see why this can't be extended to linux boards too, no reason to limit to "px4" boards. Example "make bebop2" will come with all the right tuning baked in.

**Comment by lucasdemarchi** [comment]
Check #6379

**Comment by Pedals2Paddles** [comment]
This was already working for PX4 based builds. The solo uses it all day. And all my betas for the solo in the last 2 months have been using it too. I can't speak to the other boards. But I don't think it was missing or broken for Pixhawks at least.

**Comment by magicrub** [comment]
Please describe "working for PX4 based builds". What command did you do to compile master branch to get this behavior and what file is used for the new set of defaults that are special to the SOLO?

**Comment by Pedals2Paddles** [comment]
Actually nothing. It just worked. If there is a defaults.parm file in that directory, the build used it and so did parameter resets. I did literally nothing. Just out the file there and compile.

**Comment by OXINARF** [comment]
You guys are mixing a lot of stuff for such a simple PR.

- Make build system will copy anything that is in the [ROMFS directory](https://github.com/ArduPilot/ardupilot/tree/master/mk/PX4/ROMFS) into NuttX `/etc` folder
- waf build system only copies some specific files from the ROMFS directory (so you can't just put files there and expect them to be copied)
- no board, in any build system, includes a param file by default
- this adds the default param file for aerofc board in the waf build system (without having to manually copy anything, like Matt does for Solo)
- Linux is quite different because we don't ship an entire OS, just the ArduPilot binary. It is possible to do it with the proposed upload method

@lucasdemarchi this has passed CI, as far as I'm concerned, merge away!

**Comment by Pedals2Paddles** [comment]
I should add that I was using make at the time. I'm not sure what you by no build system includes it by default. If you mean it won't use the param file by default, it did. I changed nothing. Just put the file in and it was used.

**Comment by magicrub** [comment]
@Pedals2Paddles you're literally saying "works without having to do anything as long as I do something first"

**Comment by Pedals2Paddles** [comment]
That's a little over literal. I'm pointing out that, at least when using make on a px4 build, using a defaults.param file just works without making any other changes and certainly without this PR. I can't speak for waf builds or any other board types though as I stopped using make around the time I stopped needing a default file last week.

**Comment by Pedals2Paddles** [comment]
Example here in my ArduCopter solo beta repo. https://github.com/Pedals2Paddles/ardupilot/tree/solomod-master/mk/PX4/ROMFS

**Comment by magicrub** [comment]
@Pedals2Paddles that's not "master", it's a vehicle specific branch you're on.

**Comment by Pedals2Paddles** [comment]
It's a branch of master, rebased just prior to build, in which the only difference is a few files in AP_Notify (that were actually merged into master last night), and the defaults.parm in ROMFS. No other changes to the code such as in this PR. No special build commands.  Just the usual `make px4-v3` and voila. The ArduPilot-Solo repo on 3DR also had nothing coded any differently, I checked before even trying to use it.

If you guys don't believe me that this worked, I can send you the px4 file. There is a whole facebook group of beta testers running it, along with the Solo sitting on the table next to me.  All of which successfully use the values in defaults.parm exactly as expected. If you do a parameter reset, you get the values in defaults.parm rather than the typical ArduCopter defaults. It made our beta testing much easier in that respect.

**Comment by OXINARF** [comment]
@Pedals2Paddles It's not a matter of believing, it's a matter of using the right words. You said:

> I changed nothing. Just put the file in 

Which is a contradiction... If you are copying a file manually you are doing something. This changes does it for you with the waf build system - which makes perfect sense since aerofc is a specific vehicle, not a generic board like the Pixhawks.

**Comment by magicrub** [comment]
> and the defaults.parm in ROMFS

uh huh... Are you going to put that in master? nope...

**Comment by Pedals2Paddles** [comment]
OK. I think explained in detail what I did and exactly what the result was with an example. I never suggested putting the solo defaults in master or contradicted anything. I'm just explaining _*how it performed for me as currently configured in master*_.  Which I believe is exactly what peter and michael were discussing a few comments above. That's all.

**Comment by lucasdemarchi** [comment]
@OXINARF Thanks for clarifying

@Pedals2Paddles as others pointed out the difference is that with this there's no "copy a file to a directory" to get it embedded into the firmware. In the end both approached end up adding a file in `/etc/defaults.parm`. The advantage of the approach I'm taking is that there is no forking involved... Anyone building master branch will get the default parameters, just like they do in your case. The compromise is that we need to add a target for that specific vehicle. I can do that for solo if you want to try.

**Comment by lucasdemarchi** [comment]
Thank you all for the comments.

**Comment by Pedals2Paddles** [comment]
That's cool! I would love to give that a try for the Solo.  The nature of such a vehicle makes it a LOT easier to work with if the parameter defaults are specific to the vehicle. We've been working to not _need_ that. But it would none the less be extremely helpful and save a lot of steps.  As long as it won't be a burden on the build system.

**Comment by magicrub** [comment]
The idea would be to add "make solo" or the same for waf...

**Comment by Pedals2Paddles** [comment]
Cool. Strictly for running your own builds? Or would this all be on the build server and Travis too?

**Pull request merged**
