### PR TITLE
Add RC option for flightmode pause/resume

### PR DESCRIPTION
**Pull request by peterbarker**
Tested in SITL with both guided/auto on Copter.

### CODE REVIEW

**Review by rmackay9 — CHANGES_REQUESTED** [review]
Thanks for this, we surely need to update some parameter docs..

I wonder if it should be FLIGHTMODE_PAUSE or maybe just Pause?  It doesn't work in all modes so we might want to display a failure to the user.

**Comment by peterbarker** [comment]
```
LOITER> Mode LOITER
rc height 25
11 2000
LOITER> AP: Flight Mode Pause failed
height 14
```

**Comment by peterbarker** [comment]
> Thanks for this, we surely need to update some parameter docs..

Whoops.  Added the parameter docs.
 
> I wonder if it should be FLIGHTMODE_PAUSE or maybe just Pause? It doesn't work in all modes so we might want to display a failure to the user.

Now displays a failure to the user if they try to use it and the mode says no.

**Review by rmackay9 — APPROVED** [review]
LGTM.

I think that Rover could probably support pausing now too now that it uses SCurves.  Just musing though and not in any way trying to add to your work load because nobody's actually asked for it yet.

**Comment by peterbarker** [comment]
> I think that Rover could probably support pausing now too now that it uses SCurves. Just musing though and not in any way trying to add to your work load because nobody's actually asked for it yet.

@mustafa-gokce did offer an implementation: https://github.com/ArduPilot/ardupilot/pull/19552

**Comment by rmackay9** [comment]
@peterbarker,

OK, thanks.  That implementation is OK but we should do it the same way we've done it for Copter which works better especially when the vehicle is in the middle of a corner.

**Pull request merged**
