### PR TITLE
AP_Math: Add missing constexpr

### PR DESCRIPTION
**Pull request by patrickelectric**
Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

### CODE REVIEW

**Comment by WickedShell** [comment]
@patrickelectric do you get any changes in the resulting build from this? I'm guessing not, but it'd be an interesting note here.

**Comment by patrickelectric** [comment]
The patch only adds constexpr keyword to allow these functions to run at compile and runtime, the results of the functions does not change.

**Comment by WickedShell** [comment]
I realize that, I was curious if it actually has helped the compiler at all, or if its just a no op change for being more verbose.

**Comment by patrickelectric** [comment]
The size is different, as expected, constexpr creates a smaller binary:
```

**Comment by patrickelectric** [comment]
@WickedShell I just check the binary and saw that it does not change the size but it changes the binary content.
`diff ardusub_with_constexpr_objdumṕ ardusub_without_constexpr_objdumṕ`
http://ix.io/2dyh

This patch also empowers future patchs that want to create functions with constexpr that uses the ones in this patch.

**Pull request merged**
