### PR TITLE
SITL: fix simulated RC failure while receiving RC overrides

### PR DESCRIPTION
**Pull request by jeff567**
This fixes the behavior of SIM_RC_FAIL = 1 (no pulses) when RC override messages are being received.

Currently, in SITL, if the user sets SIM_RC_FAIL = 1 while sending RC overrides, conventional RC messages are still received by the vehicle for channels not being overridden.  In this [screen recording](https://www.youtube.com/watch?v=Rrjh9ruWUpY), the vehicle is sent RC overrides for channel 4 to induce yaw motion.  SIM_RC_FAIL is then set to 1.  Conventional RC messages are then sent for channels 1 and 2, to which the vehicle responds.  Expected behavior is for the vehicle to not receive these conventional RC messages, as there is a simulated RC failure.

This [screen recording](https://www.youtube.com/watch?v=Oj37U4ZvjbM) shows the behavior after applying this patch.  After setting SIM_RC_FAIL to 1, the vehicle no longer receives the conventional RC commands while still responding to the RC overrides.

This does not affect behavior with SIM_RC_FAIL = 2, which already appears to be correct.

### CODE REVIEW

**Comment by peterbarker** [comment]
@jeff567 this looks good, thanks.

Could you rebase this so there's only a single commit, please?  We don't allow merge commits into our main branch.  Let me know if you'd like me to do that for you.

**Comment by jeff567** [comment]
ah, sorry about that!  I'll just close this PR and create a new one with a single commit.
here is the new PR:
https://github.com/ArduPilot/ardupilot/pull/21607

**Comment by peterbarker** [comment]
> ah, sorry about that! I'll just close this PR and create a new one with a single commit. here is the new PR: #21607

All good, thanks.  I've approved that other PR.

Next time you might like to look at git interactive rebasing - it lets you pretend you got everything right, first time.  We have some instructions over here: https://ardupilot.org/dev/docs/git-interactive-rebase.html

**Comment by jeff567** [comment]
got it, thank you!

**Pull request closed without merging**
