### PR TITLE
Tracker: remove unused includes

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by rmackay9** [comment]
@IamPete1, you're fine with this as well?  I think we can merge this any time 'cuz if it wasn't right it wouldn't compile.

**Comment by magicrub** [comment]
This should be safe to merge. I say do it.

**Comment by amilcarlucas** [comment]
Ar you guys using the iwyu tool? https://include-what-you-use.org/

**Comment by peterbarker** [comment]
On Mon, 25 Nov 2019, Amilcar Lucas wrote:

> Ar you guys using the iwyu tool? https://include-what-you-use.org/

Nope :-)

I think Francisco looked at it a bit.

**Pull request merged**
