### PR TITLE
AC_AttitudeControl: Alt Hold init bug

### PR DESCRIPTION
**Pull request by lthall**
Addresses a problem where we don't initialise the acceleration PID properly when we switch from a manual mode in flight.

### CODE REVIEW

**Comment by rmackay9** [comment]
great so what we need to add now is some screen shots showing before and after (i.e. the problem before, the wonderful result after).. I might be able to do this in SITL..

**Comment by rmackay9** [comment]
Here are before and after screen shots of the difference.  We can see in the "before" image that the throttle output (in green) jumps slightly while it does not in the "after" image.
before-after-thr-jump

The procedure used in this test was:

- param set PSC_ACCZ_FILT 5
- climb to 100m in stabilize mode (just to give us some altitude)
- switch to alt_hold mode ("alt_hold") and move throttle to minimum ("rc 3 1000") to descend quickly to create an altitude hold error
- move throttle back to middle ("rc 3 1500") and quickly switch to stabilize mode ("stabilize")
- switch back to AltHold ("alt_hold") and note throttle output change

**Comment by WickedShell** [comment]
@lthall Would this fix the problem we observed at the conference when we were tuning my plane and after landing in QLoiter, and going to QStabilize when we went back to QLoiter we got a momentary jump in throttle that was much higher before it came back down?

**Comment by rmackay9** [comment]
Not a ton of review on this but it's causing merge conflicts with other PRs so merging..

**Comment by lthall** [comment]
> @lthall Would this fix the problem we observed at the conference when we were tuning my plane and after landing in QLoiter, and going to QStabilize when we went back to QLoiter we got a momentary jump in throttle that was much higher before it came back down?

Yes, I have been seeing this happen from time to time. It is a little tricky because it requires a specific set of mode changes and states to see it.

**Pull request merged**
