### PR TITLE
Added RC option for fixed wing autotune in any stabilized flight mode

### PR DESCRIPTION
**Pull request by tridge**
Good for people who only ever fly in AUTO mode

### CODE REVIEW

**Comment by IamPete1** [comment]
Does this mean we can remove the auto-tune waypoint? 

I think its also worth adding a check for the correct type of stick mixing. Direct stick mixing will result in a very bad tune and without any stick mixing the tune will never complete. 

A nice enhancement.

**Comment by IamPete1** [comment]
Looks like this will allow you to start any mode. Should probably check not manual, acro, training or autotune mode.

**Comment by tridge** [comment]
> Looks like this will allow you to start any mode. Should probably check not manual, acro, training or autotune mode.

if you want to start in those modes you can - it won't do anything unless the stabilize APIs are called.

**Comment by IamPete1** [comment]
> if you want to start in those modes you can - it won't do anything unless the stabilize APIs are called.

Right, but then at some later point you switch into one of those modes you end-up auto tunning without realizing.

**Comment by tridge** [comment]
> Right, but then at some later point you switch into one of those modes you end-up auto tunning without realizing.

the user has deliberately asked for it. We do the same for lots of other RC switches (eg. inverted). The user may deilberately takeoff with this set for first flight in manual.
I don't think a flight mode check is worthwhile, it just adds flash and restricts how users can use it. Starting the autotune code is not a dangerous thing to do.

**Comment by rmackay9** [comment]
At the risk of being nitpicky, it looks like the RC option number was from the wrong group.  Same goes for QRTL from this PR: https://github.com/ArduPilot/ardupilot/pull/19325.

Too late to change?

**Pull request merged**
