### PR TITLE
autotest: check battery_status.charge_state is critical on failsafe

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by alexwien7** [comment]
That's a test case that answers the question whether charge_state is always set or just when failsafe mode is enabled.
It came up  on talk on QGC 4.1.3 relying on this field, when they dropped the check for remaining battery percent.

**Comment by hendjoshsr71** [comment]
@alexwien7 charge_state is always set to one of UNDEFINED, OK, LOW, or CRITICAL

@peterbarker you could complete the autotests for the other states or the original author could add them in ;)  .  BTW I'm never quite sure when unit tests or autotests are overkill, wanted, vs. needed?

**Comment by peterbarker** [comment]
> @alexwien7 charge_state is always set to one of UNDEFINED, OK, LOW, or CRITICAL

In what cases do we set this to `UNDEFINED` in a mavlink packet we actually send?

AFAICS the sanity check at the top should never be hit, and the `switch` statement should always choose OK, LOW or CRITICAL.

> @peterbarker you could complete the autotests for the other states or the original author could add them in ;) . BTW I'm never 

There are lots of things that I could do, yes. Including review and merge pull requests that augment our tests :-)

> quite sure when unit tests or autotests are overkill, wanted, vs. needed?

They're never "needed" by the project.  We merge lots of stuff that I'd strongly prefer we had autotests for :-)

**Comment by hendjoshsr71** [comment]
> > @alexwien7 charge_state is always set to one of UNDEFINED, OK, LOW, or CRITICAL
> 
> In what cases do we set this to `UNDEFINED` in a mavlink packet we actually send?
> 

None. I was just being a bit too compete on the possibilities even though it, should never be sent. 

> AFAICS the sanity check at the top should never be hit, and the `switch` statement should always choose OK, LOW or CRITICAL.
> 
> > @peterbarker you could complete the autotests for the other states or the original author could add them in ;) . BTW I'm never
> 
> There are lots of things that I could do, yes. Including review and merge pull requests that augment our tests :-)
> 
> > quite sure when unit tests or autotests are overkill, wanted, vs. needed?
> 
> They're never "needed" by the project. We merge lots of stuff that I'd strongly prefer we had autotests for :-)

**Comment by alexwien7** [comment]
> In what cases do we set this to `UNDEFINED` in a mavlink packet we actually send?

I think in Ardupilot < 4.1 the chargeState is always UNDEFINED. The OK, LOW, CRITICAL were introduced in 4.1

**Comment by hendjoshsr71** [comment]
> > In what cases do we set this to `UNDEFINED` in a mavlink packet we actually send?
> 
> @peterbarker @hendjoshsr71 I think in Ardupilot < 4.1 the chargeState is always UNDEFINED. The OK, LOW, CRITICAL were introduced in 4.1

@alexwien7 That is correct.

**Comment by peterbarker** [comment]
On Wed, 18 Aug 2021, alexwien7 wrote:

>       In what cases do we set this to UNDEFINED in a mavlink packet we actually send?
> 
> I think in Ardupilot < 4.1 the chargeState is always UNDEFINED. The OK, LOW, CRITICAL were introduced in 4.1

@alexwien7 sounds right.  autotest suite changes on master are only 
relevant to master's code flows, which is where my query was aimed.  The 
equivalent test on <4.1 (assuming it had the mavlink to support it) would 
assert that it came back UNDEFINED each time.

**Pull request merged**
