### PR TITLE
Tools: add a test for Plane's SET_ATTITUDE_TARGET support

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by OXINARF** [comment]
Apparently Quaternion requires numpy, so we would need to install that too.

**Comment by peterbarker** [comment]
On Fri, 1 Jun 2018, Francisco Ferreira wrote:

> Apparently Quaternion requires numpy, so we would need to install that too.

Where would that requirement need to be added?  travis?  Vagrantfile? 
Anything else?

**Comment by OXINARF** [comment]
@peterbarker In the autotest server for sure. I'm not sure if the prereq scripts should also install it or not.

**Comment by peterbarker** [comment]
@OXINARF The install-prereqs script already includes python-numpy as a deb.

I've added a patch to add it to the build_ci.sh script.

**Pull request merged**
