### PR TITLE
AP_GPS: correct uBlox M10 configuration on minimised boards

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by tridge** [comment]
@peterbarker thanks!

**Comment by peterbarker** [comment]
Tested and working on my Bixler.

**Review by tridge — APPROVED** [review]

**Comment by tridge** [comment]
@peterbarker looks like we need this in 4.4.x too

**Comment by peterbarker** [comment]
> @peterbarker looks like we need this in 4.4.x too

https://github.com/ArduPilot/ardupilot/pull/25477
https://github.com/ArduPilot/ardupilot/pull/25478

**Pull request merged**
