### PR TITLE
AP_OSD: add flytime item

### PR DESCRIPTION
**Pull request by sh83**
This is cleaned up version of https://github.com/ArduPilot/ardupilot/pull/8928

### CODE REVIEW

**Comment by tridge** [comment]
I think we should make AP_Stats a singleton, then add an access for is_flying() in AP_Stats. Maybe even make AP_Stats track the total flight time?
It would be more accurate, as things like the hover threshold will be wrong for racing quads with low hover throttle, and would also be badly wrong for slope soaring, where the plane may be below takeoff height, with no motor

**Comment by sh83** [comment]
@tridge, good point, i will change flying detection. The question where other statistics vars(like travelled distance, max altitude and so on) should be calculated?
Probably also inside ap_stat, but with ifdefs.

**Comment by tridge** [comment]
updated to use AP_Stats

**Comment by peterbarker** [comment]
On Thu, 19 Jul 2018, Andrew Tridgell wrote:

> I think we should make AP_Stats a singleton, then add an access for is_flying() in AP_Stats. Maybe even make AP_Stats track the total flight time?

Mmmm.... while we do poke AP_Stats with is_flying, a general is_flying() 
state method might want to be on AP_Notify instead. OSDs are, after all, a 
form of notification....

**Comment by tridge** [comment]
@peterbarker randy has previously objected to using AP_Notify in that way. 
Also, we need the total flight time, which AP_Stats is already calculating

**Comment by rmackay9** [comment]
My objection re the AP_Notify flags is when they're used to pass vehicle state information between subsystems especially when those subsystems affect how the vehicle flies/moves.  So if AP_Notify::is_flying() was used to move landing gear that would not be good IMO.

So adding a is_flying() to AP_Notify that's only used to send info the pilot doesn't bother me.  I don't really mind if it comes out of AP_Stats either.. I think if we make  AP_Stats the holder of the "is_flying" state that would be bad though.  So if we started changing vehicle movements based on the AP_Stats::is_flying() that would be bad I think.

**Comment by Hwurzburg** [comment]
dont have the branch any more...noticed one display formatting issue that should be fixed in AP-Screen.cpp, line 824: change to add leading zero on minutes
**_backend->write(x, y, false, "%c%3u:%02u", SYM_FLY, t/60, t%60);_**

**Comment by tridge** [comment]
rebased

**Pull request merged**
