### PR TITLE
Make AP_Mission consider non _INT frame equivalent to their non-int counterpart

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by rmackay9** [comment]
I've tested this with QGC but it doesn't seem to resolve the problem.  My testing procedure is:

1. start QGC and connect to the vehicle
2. upload a mission with one mission command using Terrain alt
3. download the mission and check the altitude frame still shows Terrain
4. connect with MP and download the mission and confirm the altitude frame still shows Terrain

So at the moment both steps 3 and 4 are failing.  The mission command's altitude frame is being changed to Absolute.  What's different vs master is that it seems the altitude itself is being modified along with the frame.

**Comment by WickedShell** [comment]
@rmackay9 do you have a tlog of the upload from QGC for reference?

**Comment by rmackay9** [comment]
@WickedShell, I'm not quite sure where QGC tlogs appear .. I've looked but can't find them :-(

**Comment by peterbarker** [comment]
As discussed with @rmackay9 elsewhere, this wasn't intended as a fix for the QGC terrain-alt issue (https://github.com/ArduPilot/ardupilot/issues/12917).  I have put an extensive comment on that issue explaining that QGC seems to be uploading with the incorrect frame.

This was to address another point made in yesterday's devcall, which was that we should consider the _INT frames equivalent to the non-_INT equivalents.  We accept either but only ever send the non-INT frames is the idea.

Without this patch we do NOT accept several of the _INT frames when uploading missions - the included tests showed that.

**Comment by rmackay9** [comment]
ok, thanks.  I think we can merge this then.. I guess the semaphore failures are nothing to worry about?

**Comment by peterbarker** [comment]
@rmackay9 oh, the semaphore failures are something to worry about, but they're definitely not due to this PR - every PR is failing semaphore ATM because we're overflowing `MatekF405-Wing`'s flash.

So yes, I think this is good to go.

**Pull request merged**
