### PR TITLE
Adapt to CUAV Nora V1.2 hardware

### PR DESCRIPTION
**Pull request by CUAVcaijie**
1. RGB led modified from WS2812 LED to ordinary IO
2. RM3100 be on SPI2
3. By default, CAN RGB LED is turned on
4. Use the first, second and third IMU in EKF2

### CODE REVIEW

**Comment by CUAVcaijie** [comment]
> The 5 commits need to be squashed to one commit with "HAL_ChibiOS: " prefix, apart from that looks fine
> 
> Why disable the temperature control btw?

Temperature increase will cause the sensor to drift, is it necessary for general users to imu heating?

**Comment by CUAVcaijie** [comment]
The heater can be used in areas where the temperature is below 0 ° C; for areas above 0 ° C, the effect of the heater is not ideal, and users need to wait for the heater to reach the specified temperature. Do you think it would be better to turn it on?

**Comment by auturgy** [comment]
The heater isn’t to stop the sensor freezing, but to provide a stable board temperature. This prevents sensor drift.
Ardupilot has a pi controller for the heater, and parameters to enable/disable and set target temperature.
If you’re concerned about the time taken to reach the target temperature, just advise your users to use a USB power bank (or similar) to power the fc whilst traveling/setting up, so it is already warm when you are ready to fly.
There’s a long history of debate over this: whether correction tables or calibration algorithms are better than a heater, but ultimately most users generally don’t or can’t do thermal calibration properly, and most manufacturers would prefer not to. Installing a heater overcomes this.

**Comment by CUAVcaijie** [comment]
Ok i turn the heater back on

**Comment by tridge** [comment]
I've updated the PR for the bootloader change and merged

**Comment by rmackay9** [comment]
This is included in Copter-4.0.4-rc2

**Pull request closed without merging**
