### PR TITLE
Copter: fixed aux channel outputs in RC failsafe

### PR DESCRIPTION
**Pull request by tridge**
note that the HAL changes are not strictly needed if we remove the cork/push from AP_Motors. 
We do need to move the cork/push up to the vehicle level though to ensure we correctly output at the right rate on all platforms (especially with one-shot)

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
This is needed for any HAL using PCA9685... and this is needed for "main" motors, not auxiliary servos. Why is it being moved to vehicle code?

**Comment by tridge** [comment]
@lucasdemarchi it was moved to vehicle code so that we end up with a single push when we have aux servos as well as main motor servos. Think of the case of a one-shot copter with a servo gimbal. We don't want the output of the servo gimbal to trigger a new set of pulses to the one-shot ESCs. So we want the cork/push to cover all outputs. We can only do that at the vehicle level

**Comment by lucasdemarchi** [comment]
I only see the cork/push being removed and not added in another place, so I must be missing something

**Comment by tridge** [comment]
its added here: https://github.com/ArduPilot/ardupilot/pull/6065/commits/c9359eb5d4a488d0f42c433923a8a6b723e8f460

**Comment by lucasdemarchi** [comment]
Ok, I missed that then.

So the callout we have here is more or less:

```c++
Copter::motors_output() {
  AP_RCOutput::cork()

  // aux outputs
  SRV_Channels::output_ch_all()
    AP_RCOutput::write()

  // main outputs
  AP_Motors::output()
    AP_Motors::output_to_motors()
      AP_Motors::rc_write()
        AP_RCOutput::write()

  AP_RCOutput::push()
}
```

> We don't want the output of the servo gimbal to trigger a new set of pulses to the one-shot ESCs. So we want the cork/push to cover all outputs. We can only do that at the vehicle level

Makes sense since all outputs (main and aux) are backed by the same RCOutput object.

**Comment by lucasdemarchi** [comment]
@tridge Now that this isn't done on AP_Motors anymore, don't we need to apply the same to all the other vehicles? I see `motors->output()` being called in quadplane and there's also Sub.

**Comment by lucasdemarchi** [comment]
> The way cork and push is implemented in all HALs doesn't really support nested calls: the outermost cork will effectively work, but then the innermost push is the one doing the effective push

As I understand his reasoning, cork/push would be banned from HAL, effectively delegating this to vehicle code. I didn't check if there any leftover calls though.

**Comment by OXINARF** [comment]
> As I understand his reasoning, cork/push would be banned from HAL, effectively delegating this to vehicle code. I didn't check if there any leftover calls though.

Not banned from HAL, that's not possible when libraries are writing to the HAL's RC output.

I'll say that I don't quite understand the need to have support for nested cork/push if we are removing it from libraries and relying on the vehicle to do it. I think that nested cork/push is good to have, but then I would leave the cork/push in libraries that do multiple outputs and want them to be synced - that allows libraries to say those outputs need to be output at the same time, as well as allows vehicles to group different libraries outputs in one.

**Comment by rmackay9** [comment]
I'm ok with this change.  I see what's going on but I'm not an expert in this area so I leave it to the better judgement of @tridge, @OXINARF and @lucasdemarchi.

**Comment by rmackay9** [comment]
At @tridge's prompting I tested this and found that (as Tridge expected) it breaks the Copter ESC calibration.  I believe the fix is pretty straight forward.

**Comment by OXINARF** [comment]
@rmackay9 Breaks as in there is no motor output or the output isn't synced?

**Comment by rmackay9** [comment]
@OXINARF, there's no motor output it seems.

**Comment by tridge** [comment]
@rmackay9 I've pushed a fix for ESC calibration. Can you test?

**Comment by rmackay9** [comment]
Yes, thanks!  I'll test and if all goes well, merge and release with -rc5 on mon.

**Comment by OXINARF** [comment]
@tridge Have you read my review? Nested cork/push doesn't work and a vehicle can't guarantee that different outputs (motors and servos) are done at the same time - which I guess is the reason why you had to remove the cork/push from Motors library.

@rmackay9 This touches Sub too, so I think it should be tested by @jaxxzer before merging.

**Comment by tridge** [comment]
@OXINARF yes, I understand we don't do full nested corking, but the HAL fixes do at least mean that we don't send double outputs when we have nested cork/push calls.
To properly fix it we'd need a cork nesting counter, but the fix I have put in at least means that if there is a nested call it won't break oneshot ESCs (which are timing critical)
That and the removal of the cork/push from AP_Motors makes things behave correctly on the bus. I would be very open to adding a nesting level to cork/push in a future PR

**Comment by tridge** [comment]
pushed

**Pull request closed without merging**
