### PR TITLE
Copter: added support for dual and transverse helis 

### PR DESCRIPTION
**Pull request by tridge**
This is a revival of https://github.com/ArduPilot/ardupilot/pull/1860 from Fredrik Hedberg, using the new parameter and servo structures.
It can successfully fly the Chinook model in RealFlight, and the built-in SITL heli-dual model.
Many thanks to @fhedberg for his patience in getting this revived for master

### CODE REVIEW

**Comment by RobertWZ** [comment]
built-in SITL heli-dual model,can fly?

**Comment by tridge** [comment]
yes, the built in model works. Just start it up and fly it just like the single heli model (remember to control channel 8 for interlock)

**Comment by frizensami** [comment]
Hoping to test this on real tandem hardware soon, will keep the updates coming.

**Comment by tridge** [comment]
video link of it flying in SITL here: http://discuss.ardupilot.org/t/chinook-heli-support-in-ardupilot/15757

**Comment by tridge** [comment]
rebased on master, planning on pushing this once travis passes

**Comment by tridge** [comment]
merged to master

**Pull request merged**
