### PR TITLE
Copter: Notify the fence breach at the notification level

### PR DESCRIPTION
**Pull request by muramura**
I RTL'd during auto-flight.
I didn't know why I RTL'd.
I know there are multiple fail-safes for RTL.
I want to know what caused the RTL.
I made sure to notify the operator when I BREACH the fence.

APM PLANNER2：
Screenshot from 2021-02-13 09-28-08

SITL:
Screenshot from 2021-02-13 09-18-17

### CODE REVIEW

**Comment by peterbarker** [comment]
Wow!

I *just* got through writing something to accomplish much the same thing - but by emitting a FENCE_STATUS message instead!  Pretty amazing coincidence.  I did that so that one of the *Rover* autotests will be come reliable about detecting a fence breach.

My patch here https://github.com/ArduPilot/ardupilot/pull/16605/commits/00fce0978cd0c365beff6ef451a2f752e7315f1f does this at the AC_Fence level rather than the vehicle level, which I think is more appropriate.  I *think* the GCS should make appropriate announcements based on `FENCE_STATUS` - so I don't know whether a STATUSTEXT is appropriate.

**Comment by muramura** [comment]
@peterbarker san.
To show or hide messages in GCS, it is an addition to the fence status process.
SEND_TEXT is a function that is already implemented in GCS.
GCS shows and hides messages according to the notification level.
Notifying with SEND_TEXT does not affect GCS.

In other ArduPilot processes, we use the following together.
    gcs().send_text(MAV_SEVERITY_NOTICE, "Geofence triggered");
    gcs().send_message(MSG_FENCE_STATUS);

**Comment by rmackay9** [comment]
I think it makes sense to emit a warning send-text like this.  I'd prefer if we stay away from all caps though so let's change it to "Fence Breached".

**Comment by rmackay9** [comment]
Ah, we also need to make sure that we don't get a silly "Fence Breached" message at startup with this change.  That will just annoy users.

**Comment by muramura** [comment]
@rmackay9 san. I'll make the change.

**Review by khancyr — APPROVED** [review]
Requested changes were made. It is quite constraint and Randy validate that it is useful to have a status text for this. So I think this is safe to merge

Peter solution could come with another PR as a more generic solution for all vehicles !

**Comment by rmackay9** [comment]
Merged, thanks!

**Pull request merged**
