### PR TITLE
Loggerfixes

### PR DESCRIPTION
**Pull request by Hwurzburg**

### CODE REVIEW

**Comment by Hwurzburg** [comment]
@khancyr Pierre,,,where? I'll fix

**Comment by khancyr** [comment]
@Hwurzburg ha ! I was commenting the PR to justify why it is NFC, you corrected the typos !

**Comment by Hwurzburg** [comment]
okay, you got me...what does NFC mean in this context?...  No Fat Chicks, No Fxxing Clue,No Frelling Chance...I am lost, sorry

**Comment by amilcarlucas** [comment]
Non functional change. Hence not dangerous

**Comment by Hwurzburg** [comment]
thanks....

**Pull request merged**
