### PR TITLE
Use loop rate Hz rather than uS for initialising GyroFFT

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by andyp1per** [comment]
@peterbarker my recollection is that loop_rate_hz did not return the right value early on during initialization which is why I used the target us. I think probably you would need to double check on a real flight controller.

**Comment by peterbarker** [comment]
> @peterbarker my recollection is that loop_rate_hz did not return the right value early on during initialization which is why I used the target us. I think probably you would need to double check on a real flight controller.

`loop_rate_hz` is the value we store in the parameters; it's the period which we calculate it.

I dropped a send_text in anyway:

```
--- a/libraries/AP_GyroFFT/AP_GyroFFT.cpp
+++ b/libraries/AP_GyroFFT/AP_GyroFFT.cpp
@@ -182,6 +182,7 @@ AP_GyroFFT::AP_GyroFFT()
 // initialize the FFT parameters and engine
 void AP_GyroFFT::init(uint16_t loop_rate_hz)
 {
+    gcs().send_text(MAV_SEVERITY_WARNING, "using loop_rate_hz=%u", (unsigned)loop_rate_hz);
     // if FFT analysis is not enabled we don't want to allocate any of the associated resources
     if (!_enable) {
         return;
```

and got:

image

**Comment by tridge** [comment]
> `loop_rate_hz` is the value we store in the parameters; it's the period which we calculate.

please test on quadplanes, which change loop rate hz on init

**Comment by peterbarker** [comment]
image

... works because `init_ardupilot` is called in `AP_Vehicle.cpp` before we init gyrofft

**Review by tridge — APPROVED** [review]

**Pull request merged**
