### PR TITLE
Add FETtec OneWire (ESC telemetry) support to ArduCopter 4.1.0-rc1

### PR DESCRIPTION
**Pull request by amilcarlucas**
Backport of #17363 to the stable branch

Replaces #18305

According to Randy this should go in 4.1.1 or 4.1.2 release.

ArduPilot/ardupilot_wiki#3335 should be merged after this one.

We have flight tested this version in multiple vehicles

### CODE REVIEW

**Comment by amilcarlucas** [comment]
Can this be added to the backports project?

**Comment by tridge** [comment]
@rmackay9 this one is actually pretty low risk, if not enabled then it doesn't do anything. Main risk is flash space. We'd need to make sure it doesn't stop any boards from building

**Comment by amilcarlucas** [comment]
This only affects 2MB boards

**Comment by khancyr** [comment]
This have been merged on v4.1 serie already. Closing

**Pull request closed without merging**
