### PR TITLE
GCS_MAVLink: Added channel 17 and 18

### PR DESCRIPTION
**Pull request by muramura**
I add channels 17 and 18.
MAVLINK messages support 1-18.

### CODE REVIEW

**Comment by peterbarker** [comment]
On Tue, 11 Feb 2020, murata,katsutoshi wrote:

> I add channels 17 and 18.
> MAVLINK messages support 1-18.

Unless we increased NUM_RC_CHANNELS this would bring us absolutely no 
benefit and cost us a very small amount of flash and some processing time.

Zero benefit and some cost == not worth it, yes?

**Comment by rmackay9** [comment]
Yeah, sorry, with no benefit there's not much point so I'll close this.  Txs anyway

**Comment by muramura** [comment]
@peterbaker san, @rmackay9 san.

Thanks for your comment. I already know that a radio that supports 18 channels is available from Futaba. I fix about 18 channels.

**Comment by auturgy** [comment]
There’s a lot of value in separating the number of outputs from the number of inputs, particularly as we move towards canbus actuators/devices where the historical limit related to the number of pwm outputs should not be a consideration.
The reluctance to remove this outdated limitation is perplexing.

**Pull request closed without merging**
