### PR TITLE
something in optical flow I donnt understand and may be bugs

### PR DESCRIPTION
**Pull request by luweikxy**

### CODE REVIEW

**Comment by luweikxy** [comment]
questions about delAngBodyOF and cantFuseFlowData

**Comment by luweikxy** [comment]
There are 5 problems or bugs,  you can see these problems or bugs in "Files changed"

**Comment by luweikxy** [comment]
@priseborough

**Comment by rmackay9** [comment]
An interesting way to ask questions!  :-)
I'm going to close this, better to discuss on our gitter channel or on the discuss servers before raising a PR.

**Pull request closed without merging**
