### PR TITLE
AP_Motors: Notify GCS of motor failure

### PR DESCRIPTION
**Pull request by muramura**
Notify GCS of motor abnormality.
Operators have difficulty visually confirming motor anomalies during flight.
I notify the GCS of a motor failure so that the operator can recognize it.

AFTER:
Screenshot from 2023-04-16 11-21-23

### CODE REVIEW

**Comment by IamPete1** [comment]
We do already send a warning at the copter level, https://github.com/ArduPilot/ardupilot/blob/37f638c5f7cc709f32e57bbfd9f83c344597dc4d/ArduCopter/crash_check.cpp#L168

Not really a fan of this, we already had to add a option to turn off the copter warning because it was annoying people.

**Comment by muramura** [comment]
@IamPete1 san.  Comments thanks.
This message is notified 6 seconds after a motor failure occurs.
This PR is notified almost simultaneously.
The quadcopter I am developing flies at a height of 2 or 3 meters above the ground.
Six seconds later is very slow.

Screenshot from 2023-04-16 21-57-36

**Comment by IamPete1** [comment]
I think this is going to be far too spammy for most users. You could add a scripting binding for the thrust balance and run the extra check in a script.

**Comment by muramura** [comment]
Thanks for the comment.
I am developing PIXHAWK1.
As for the LUA script, it is deprecated.
Not all of the ArduPilot users are using FC over FMUV5.

**Comment by khancyr** [comment]
@muramura it think you forget something, the motor unbalance will indeed work in case of motor failure but in case you got a copter underpowered or with a bad tune, it will also say you got unbalanced. Most user won't know what it means.
Moreover, sending it at high rate will just be spam and will hide some other potential issue or information, whereas it doesn't bring more informations on the copter state.

**Comment by khancyr** [comment]
closing this as per my and Peter review. Thanks anyway

**Pull request closed without merging**
