### PR TITLE
Update AP_MotorsMatrix.cpp for new airframe

### PR DESCRIPTION
**Pull request by dhruvilodonata**
The Quad VTOL has X configuration but the angles differ from 45°. The angles in my frame are 38.34, -128.34, 128.34 and 38.34.

### CODE REVIEW

**Comment by Hwurzburg** [comment]
the mixer guru (@IamPete1 ) says you would be better using the standard x mixer
also this could be done in a LUA script rather than using flash space for a rarely used configuration
probably will not be accepted due to the above...sorry

**Comment by IamPete1** [comment]
To elaborate slightly more, this is a example of adding a motor matrix from a script.

https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Scripting/examples/MotorMatrix_setup.lua

This hex example has the same add motor helper as in the `cpp`, so you can more or less copy and paste the changes from this PR into the script.

https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Scripting/examples/MotorMatrix_fault_tolerant_hex.lua

The reason that your probably better with the standard X mixer is that all the motors are balanced across roll and pitch. By moving away from the symmetrical case the front motors throttle up more than the rear motors throttle down for pitch. This results in a net increase in throttle. This cross coupling between axis is much harder for the controllers to deal with than a bit of steady state offset that would result from the motors not being symmetrical. 

In anycase, I don't think we would accept this frame type into the CPP because its too unusual. If you need a hand getting scripting up and running so you can load the mixer that way we can help, but as I say I think it will fly worse than using the standard mix.

**Comment by dhruvilodonata** [comment]
So actually, I am working on a tilt rotor mechanisms, and there are total 6 motors, 4 are tilt and 2 are wing integrated. This is the reason why we the four motors are not at 45°. The wing integrated runs till the front and back transition. In the first testing, we have planned to do hover test without wing integrated ones. 

I have one question though, As the wing integrated motors are smaller than the tilting ones, they are taking only 20% of the MTOW while tilting motors take 80% of the MTOW. 

In motormatrix.cpp line 500; 
add_motor_raw(int8_t motor_num, float roll_fac, float pitch_fac, float yaw_fac, uint8_t testing_order, float throttle_factor)

Should i put 0.1 (only one wing integrated motor) for the throttle factor? Or is there any other way that flight controller send thrust command accordingly like 80% between 4 tilt rotors and 20% between to wing integrated motors?

**Comment by IamPete1** [comment]
Hard to say without more information, throttle factor is mostly used to correct for a roll and pitch offset due to CG. Unless you have seen some issue with them all at the default of 1 there is probably no need to change them.

**Comment by dhruvilodonata** [comment]
So this would be my lua script for custom airframe...
# Custom motor mixing for the quadcopter in X configuration with angle different than 45°

local AP_MOTORS_MATRIX_YAW_FACTOR_CW = -1
local AP_MOTORS_MATRIX_YAW_FACTOR_CCW = 1

local AP_MOTORS_MOT_1 = 0
local AP_MOTORS_MOT_2 = 1
local AP_MOTORS_MOT_3 = 2
local AP_MOTORS_MOT_4 = 3

MotorsMatrix:add_motor_raw(AP_MOTORS_MOT_1, -1, 0.791, AP_MOTORS_MATRIX_YAW_FACTOR_CW, 1);
MotorsMatrix:add_motor_raw(AP_MOTORS_MOT_2, 1, 0.791, AP_MOTORS_MATRIX_YAW_FACTOR_CCW, 2);
MotorsMatrix:add_motor_raw(AP_MOTORS_MOT_3, 1, -0.791, AP_MOTORS_MATRIX_YAW_FACTOR_CW, 3);
MotorsMatrix:add_motor_raw(AP_MOTORS_MOT_4, -1, -0.791, AP_MOTORS_MATRIX_YAW_FACTOR_CCW, 4);


assert(MotorsMatrix:init(4), "Failed to init MotorsMatrix")

motors:set_frame_string("scripting custom X example")
---------------------------------------------------------------------------------------
I have enabled the scr_enable parameter. 

So i just upload this script in mission planner -> config -> MAVftp -> APM -> script. 

Will it run automatically or do i have to add some parameters and assign this script to it? 

For the throttle factor question, May be I can use the parameter; Q_M_Boost_scale to 0.1 and (servo 9-12 function value  motor 1 to 4 with Dshot) assign servo 13 and 14 (wing integrated motors) function to value 81 for “Boost Throttle”  (https://ardupilot.org/copter/docs/booster-motor.html) or in the worst case, i reduce the max pwm value signal for the servo 13 and 14 (function value motor 5 and 6). Does it sounds feasible? 

I have one question, As this kind of model is not there in the ardupilot and my wing integrated motors runs till the transition and then turn off. I am using the arduplane 4,3,7 with required parameters changed. Will the two wing integrated motors turn off automatically after completion of transition?

**Comment by dhruvilodonata** [comment]
@IamPete1 @Hwurzburg, your inputs would be highly appreciated, as i am very close to the scale model testing.

**Pull request closed without merging**
