### PR TITLE
Fix compiler version on macOS

### PR DESCRIPTION
**Pull request by giacomo892**
Installing on the mac the same compiler we are using on other platforms
@khancyr discussed on discord

### CODE REVIEW

**Comment by giacomo892** [comment]
> Could you update the commit message to
> Tools: Fix compiler version on macOS
> 
> Thanks

Done

**Comment by peterbarker** [comment]
@andyp1per you've played recently - did you do something similar?

**Comment by giacomo892** [comment]
> The fix is correct. But I'm confused, we never used to use brew for this because it gave the wrong version, so I'm pretty sure someone broke it between now and when I last messed with it.

brew has always installed gcc5 here and it is quite a long time I am here :)

**Comment by jmachuca77** [comment]
I don't know if this is the correct way of doing this, we have a fork of the brew tap here ardupilot/homebrew-px4, if we want to change the version of the compiler installed then we should update the tap, not the script.

What version should It install? currently it is set to install 54, and it is working for me.

**Comment by andyp1per** [comment]
It should install 6.3.1 q2

**Comment by giacomo892** [comment]
Could also be a good time to upgrade to GCC 7 or 8. 
They produce also smaller binaries

**Comment by peterbarker** [comment]
In terms of *what* should be installed - by preference it should be exactly the same compiler as on the platforms, *not* an upgrade.  We don't recommend people generally fly binaries compiled with anything else - 'though we really would like to move forward at some stage.

Sooo... from what @jmachuca77 says, this is the wrong fix?  Should we close this PR in that case?

**Comment by giacomo892** [comment]
Then I can PR a fix directly into the PX4 brew repo, unless PX4 needs GCC 5

**Comment by peterbarker** [comment]
> Then I can PR a fix directly into the PX4 brew repo, unless PX4 needs GCC 5

I think that's the correct fix; "PX4" is well-and-truly out-of-date as a name, mind you.

**Comment by giacomo892** [comment]
See https://github.com/ArduPilot/homebrew-px4/pull/3
Closing this one

**Pull request closed without merging**
