### PR TITLE
Copter: improve landing detection by using filtered acceleration

### PR DESCRIPTION
**Pull request by rmackay9**
This PR modifies the update_throttle_mix() method so that it uses filtered accelerations (filtered at 1hz) instead of the raw accelerations.  This is consistent with the update_land_detector() function and makes the landing detector more resistant to high vibrations.

High vibrations leading to a failed landing detector has been seen in the logs of at least one user.

Perhaps @lthall can say whether there's any downsides to the additional filtering.

Below is a test with this change applied to Copter-3.6.12 (see below for why I didn't use master) after setting SIM_ACC_RND = 20
before-after

This PR also makes some minor formatting and function name changes to both Copter and Plane.  These are non-functional changes.

Note: we should probably make the same change in Plane but I could not immediately figure out where to introduce the change

Note2: I attempted to test with master but apparently there are no longer any vibrations in master?  @andyp1per can you check that your changes to SITL haven't disabled vibration by default?

### CODE REVIEW

**Comment by lthall** [comment]
I think this is a safe change that will make aircraft more tolerant of high frequency accel noise.

**Comment by andyp1per** [comment]
@rmackay9 I'm still waiting for https://github.com/ArduPilot/ardupilot/pull/13169 to go in as there are known problems with the vibration support as it stands 🙂. That said the noise is now somewhat proportional to throttle - could it be that you throttle is zero in this test?

**Comment by rmackay9** [comment]
@andyp1per, no, the throttle is definitely not zero.  The issue is quite obvious by graphing the RCOU message values in master.  At least in my tests they produced perfectly identical outputs for each motor.  It's as if there's no noise in the IMU at all.

**Comment by andyp1per** [comment]
Ok, do you have a test I can try?

**Comment by rmackay9** [comment]
@andyp1per,

Thanks very much for looking into this.  So this is the test I did using the Copter-3.6 branch (which seems OK to me) vs master.

- param set SIM_ACC_RND 5
- param set SIM_ACC2_RND 5
- loiter
- arm throttle
- rc 3 1800 (and wait a few seconds)
- rc 3 1200 (wait for land)
- rc 3 1000
- disarm

Then I downloaded the log and graphed the RCOU messages.  Below is a screen shot.
sim-acc-rnd-rcout-before-after

**Comment by andyp1per** [comment]
https://github.com/ArduPilot/ardupilot/pull/13649 should fix the noise issues in master

**Comment by rmackay9** [comment]
@andyp1per, awesome, thanks very much for the fix related to (missing) accel noise in master!

**Comment by andyp1per** [comment]
Did it work?

**Comment by rmackay9** [comment]
I've gone ahead and merged this but as discussed on the dev call I'll attempt to make a similar fix for plane. https://github.com/ArduPilot/ardupilot/issues/13664

@andyp1per, yes, it's looking much better now, thanks!
image

**Comment by rmackay9** [comment]
This has been successfully flight tested now and seems to greatly improve the landing detection for the one vehicle in question at least.

**Comment by rmackay9** [comment]
This is included in Copter-4.0.4-rc1

**Pull request merged**
