### PR TITLE
AP_Common: Add same_loc_as() function to Location

### PR DESCRIPTION
**Pull request by sypaq-nexton**
There is currently a 2D comparison (`Location::same_latlon_as()`), but there is no 3D comparison.

This also adds a `Location::same_alt_as()` function.

### CODE REVIEW

**Comment by rmackay9** [comment]
Thanks again for this.  I guess there is a consumer of this method coming in a follow up PR?  we normally don't add methods that aren't used.

**Comment by sypaq-nexton** [comment]
@rmackay9: There are a couple of places (in `ArduPlane.cpp` and `quadplane.cpp`) where this should be used. I can add these to this PR if you want.

There are a number of other places (in nav code) where I _think_ this function should be used (in place of `same_latlon_as()`), but I'm not sure.

**Comment by rmackay9** [comment]
@sypaq-nexton,

Txs again.  My guess is that one more commit should be added that makes use of the new method or a follow-up PR that uses the methods... but I think putting it all in one PR makes sense.

**Comment by khancyr** [comment]
We need somebody with the right priviledge to relaunch the test, I have put a demand for this.

**Review by tridge — APPROVED** [review]

**Review by peterbarker — APPROVED** [review]

**Pull request merged**
