### PR TITLE
Scripting: implement a tilting rudder as a lua script

### PR DESCRIPTION
**Pull request by tridge**
For vehicles with rudders on tilting motors, which should be fixed wing rudder in fwd flight and VTOL rudder in hover

### CODE REVIEW

**Comment by IamPete1** [comment]
New bindings work great in this use case. My concern would be that someone tries to use them in another case. They will be nonsense in fixed wing flight just never updating and they bypass the spool logic. As I say this case is fine, but if someone were to implement a mixer with motors they would probably have a bad time. 

We do have the servo output functions for rate output, but they only include feed forward. We could add some that are feed forward and rate I guess. But again If someone were to use them for motors they would probably have a bad time. 

You could calculate the yaw output from the motor pwms. But that is a fair bit of extra effort.

I would like to include control surfaces and tilting motors into the/a quadratic programming mixer eventually. Such scailing as this would just fall out of the maths.

**Comment by IamPete1** [comment]
Recently used this on a tilt-rotor copter, worked great. There are a couple of things it needs. Firstly I had to grab average throttle to do thrust scaling, as a hack I was able to grab throttle from the boost motor servo output with a scale of 1. So a binding for `get_throttle_out` and `get_throttle` would solve that. Also had some issues with ground resonance I think that could be stepped on by abiding spool state with `get_spool_state`. Harder is the limits to prevent I term wind up, need some way to set the limit flags from scripting asynchronously.

**Review by hendjoshsr71 — COMMENTED** [review]
We should consider getting the bindings at least into 4.3 for this.

**Comment by IamPete1** [comment]
I think this needs limit flags, throttle and spool state. I have added here: https://github.com/IamPete1/ardupilot/tree/tilt_rudder%2Bthrottle%2Blimits

Throttle, forward and lateral are needed for doing motors. As its spool state: 0faa6c972d3b95bcf495cea7a1111b17f1ec055d

Limit flags prevent integrator windup: 64f96a4d88bcab8c61fb8288c5781a10e78c3ed5 cba55c34d37dc53a96208d7374f9e68a302fac79

**Comment by tridge** [comment]
@IamPete1 I've incorporated your additions in this PR

**Review by IamPete1 — APPROVED** [review]
I think this looks good, but then again 3/4 of the commits are mine. ;)

**Review by lthall — APPROVED** [review]

**Pull request merged**
