### PR TITLE
Plane: fixed issue with overspeed in QPOS_POSITIION1

### PR DESCRIPTION
**Pull request by tridge**
this fixes the backflip issue on the convergence that Henry found

### CODE REVIEW

**Comment by Hwurzburg** [comment]
played with it for an hour...cant find anything wrong....what determines the radius for not going into fw mode? some fraction of RTL_RADIUS? perhaps that should be parameterized? the changeover from ALT_HLD_RTL to the approach slope appears to be 5X RTL_RADIUS, correct? has to be pretty complex for initial climbs within that radius

**Review by Hwurzburg — APPROVED** [review]

**Comment by Hwurzburg** [comment]
More SILT testing....noted that VTOL_LAND in mission does not follow the same altitude profile as QRTL...ie it stays at entry alt until position2 is reached....maybe thats intended....I would think Q_RTL_ALT would be the target for POS2 at VTOL_LAND point.
another thought, we should add QRTL as an Q_RTL_MODE option now, shouldn't we?

**Comment by Hwurzburg** [comment]
Test flew at the field with Convergence...behaves 100% like the RF SITL....also tested bit 15/17 of Q_OPTIONS in SITL and real Convergence....works fine....but  I would put the stop point a little higher than midstick since that is normal position for Cruise and nudge in AUTO...especially if you have the TX laid down...so it will always move to the land phase and stop if you are off the sticks....you have to have the throttle stick low enough that it would cause altitude loss in other modes for the landing to proceed...not a biggie, but was a nuisance when I was playing with it..
there is one strange glitch...as you transition from POS1 to POS2 there is always a 30deg or so yaw rotation....can be either direction....looks a bit strange...

**Comment by tridge** [comment]
> what determines the radius for not going into fw mode? some fraction of RTL_RADIUS?

if you are less than 1.5*radius then it bypasses the fixed wing section in QRTL. radius is the max of RTL_RADIUS and WP_LOITER_RAD.

**Pull request merged**
