### PR TITLE
Cleanup Dronecan generate build step

### PR DESCRIPTION
**Pull request by bugobliterator**
* moves bootloader to use dronecan dsdl compiler
* adds dynamic source option to ap_stlib, making it much convenient to add generated source code.
* do dronecan_dsdlc operation as a bld() task rather than pre build task, which doesn't recompile if dsdl is changed.

### CODE REVIEW

**Comment by tridge** [comment]
@bugobliterator looks very nice! just needs some info on testing on various MCUs and python versions

**Comment by bugobliterator** [comment]
> @bugobliterator looks very nice! just needs some info on testing on various MCUs and python versions

I have tested Bootloader and AP_Periph on CubeOrange-periph.
Tested build on python2.7.18 and python3.10.4

**Comment by tridge** [comment]
looks good, but needs extensive testing

**Comment by ukmook** [comment]
Tested on F103GPS, after loading the built .bin file on node I connected to Mission Planner and was able to upload new firmware.

**Review by tridge — APPROVED** [review]

**Pull request merged**
