### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by reubenfinch**
The IST8310, does not have SPI

### CODE REVIEW

**Comment by magicrub** [comment]
it's the same text on CUAVv5 and PH4-mini

**Comment by rmackay9** [comment]
Normally we ask that commits be prefixed with the subsystem name which is normally somewhere in the pathname to the file.  So it would be good to add "AP_HAL_ChibiOS:" to the front of this commit message.

**Comment by amilcarlucas** [comment]
The commit message should be something like:
"AP_HAL_ChibiOS: Correct the README.md, the IST8310 magnetometer uses I2C, not SPI"

**Comment by khancyr** [comment]
update, add information on other fmuv5 based board, update target.

**Comment by OXINARF** [comment]
Merged, thanks @reubenfinch and @khancyr!

**Pull request merged**
