### PR TITLE
Tools: IO_Firmware: remove NuttX-based IO firmware blob

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by tridge** [comment]
need to remove the USE_NUTTX_IOFW option in waf too

**Comment by peterbarker** [comment]
@tridge done

**Comment by tridge** [comment]
missed spots in wscript
https://github.com/ArduPilot/ardupilot/blob/master/wscript#L94
and
https://github.com/ArduPilot/ardupilot/blob/master/wscript#L365

**Comment by peterbarker** [comment]
> missed spots in wscript
> https://github.com/ArduPilot/ardupilot/blob/master/wscript#L94

Pretty sure I already got that one?!

> https://github.com/ArduPilot/ardupilot/blob/master/wscript#L365

That one I missed because of a `use-nuttx` vs `use_nuttx` grep failure :-/  Fixed now.

**Comment by tridge** [comment]
looks good, thanks!

**Comment by OXINARF** [comment]
@tridge are you waiting on something else? This looks good to me now but as you didn't merge yourself, I'm not sure if I should go ahead.

**Pull request merged**
