### PR TITLE
AP_Baro: Add retries for initializing DPS280 and DPS310

### PR DESCRIPTION
**Pull request by joshanne**
This is a very similar fix as to what was implemented for the SPL06 (#16964).

I found the **Pixracer Pro** could not cannot reliably initialize the Baro driver, and so performing retries was necessary. The problem results in no further progression through the startup process, and it appears to get stuck outputting the lines:
```
APM: Config Error: fix problem then reboot
Config error: Baro: unable to initialise driver
APM: Config error: Baro: unable to initialise driver
```

If this is acceptable, is the print for number of retries required? A similar print is in `AP_InertialSensor_BMI088::setup_accel_config` for the number of tries it took to setup accel config.

I'll post the logs in separate comments for distinct separation.
Before changeset:
```
Mode(0)> 
Mode(0)> 
Mode(0)> APM: Config Error: fix problem then reboot
Config error: Baro: unable to initialise driver
APM: Config error: Baro: unable to initialise driver
reboot
Mode(0)> Got COMMAND_ACK: PREFLIGHT_REBOOT_SHUTDOWN: ACCEPTED
Device /dev/serial/by-id/usb-mRo_mRoPixracerPro_3E0039000951303035343937-if00 is dead
Device /dev/serial/by-id/usb-mRo_mRoPixracerPro_3E0039000951303035343937-if00 reopened OK
Mode(0)> no link
link 1 down
Mode(0)> no link
AP_Logger_File: buffer size=204800
link 1 OK
heartbeat OK
APM: Initialising ArduPilot
disabling flow control on serial 2
disabling flow control on serial 3
BMI088: accel config OK (1 tries)
BMI088: found accel
BMI088: found gyro
APM: Calibrating barometer
APM: Barometer 1 calibration complete
Init Gyro***
APM: ArduPilot Ready
APM: AHRS: DCM active
APM: EKF3 IMU0 buffs IMU=19 OBS=7 OF=17 EN:17 dt=0.0120
APM: EKF3 IMU1 buffs IMU=19 OBS=7 OF=17 EN:17 dt=0.0120
reboot
Mode(0)> Got COMMAND_ACK: PREFLIGHT_REBOOT_SHUTDOWN: ACCEPTED
Device /dev/serial/by-id/usb-mRo_mRoPixracerPro_3E0039000951303035343937-if00 is dead
Device /dev/serial/by-id/usb-mRo_mRoPixracerPro_3E0039000951303035343937-if00 reopened OK
no link
link 1 down
no link
Config error: Baro: unable to initialise driver
APM: Config error: Baro: unable to initialise driver
link 1 OK
heartbeat OK
APM: Config Error: fix problem then reboot
APM: Config Error: fix problem then reboot
Config error: Baro: unable to initialise driver
APM: Config error: Baro: unable to initialise driver
Mode(0)> APM: Config Error: fix problem then reboot
Config error: Baro: unable to initialise driver
APM: Config error: Baro: unable to initialise driver
```

### CODE REVIEW

**Comment by joshanne** [comment]
After changeset:
```
Mode(0)> 
Mode(0)> reboot
Mode(0)> Got COMMAND_ACK: PREFLIGHT_REBOOT_SHUTDOWN: ACCEPTED
Device /dev/serial/by-id/usb-mRo_mRoPixracerPro_3E0039000951303035343937-if00 is dead
link 1 down
Device /dev/serial/by-id/usb-mRo_mRoPixracerPro_3E0039000951303035343937-if00 reopened OK
no link
no link
DPS310: read took 1 retries
AP_Logger_File: buffer size=204800
link 1 OK
heartbeat OK
APM: Initialising ArduPilot
disabling flow control on serial 2
disabling flow control on serial 3
BMI088: accel config OK (1 tries)
BMI088: found accel
BMI088: found gyro
APM: Calibrating barometer
APM: Barometer 1 calibration complete
Init Gyro***
APM: ArduPilot Ready
APM: AHRS: DCM active
APM: EKF3 IMU0 buffs IMU=19 OBS=7 OF=17 EN:17 dt=0.0120
APM: EKF3 IMU1 buffs IMU=19 OBS=7 OF=17 EN:17 dt=0.0120
APM: EKF3 IMU0 initialised
APM: EKF3 IMU1 initialised
APM: AHRS: EKF3 active
APM: EKF3 IMU0 tilt alignment complete
APM: EKF3 IMU1 tilt alignment complete
APM: EKF3 IMU1 initial yaw alignment complete
APM: EKF3 IMU0 initial yaw alignment complete

Mode(0)> 
Mode(0)> reboot
Mode(0)> Got COMMAND_ACK: PREFLIGHT_REBOOT_SHUTDOWN: ACCEPTED
Device /dev/serial/by-id/usb-mRo_mRoPixracerPro_3E0039000951303035343937-if00 is dead
link 1 down
Device /dev/serial/by-id/usb-mRo_mRoPixracerPro_3E0039000951303035343937-if00 reopened OK
Mode(0)> no link
no link
DPS310: read took 1 retries
AP_Logger_File: buffer size=204800
link 1 OK
heartbeat OK
APM: Initialising ArduPilot
disabling flow control on serial 2
disabling flow control on serial 3
BMI088: delaying accel config
BMI088: found accel
BMI088: found gyro
APM: Calibrating barometer
APM: Barometer 1 calibration complete
Init Gyro*BMI088: accel config OK (3 tries)
**
APM: ArduPilot Ready
APM: AHRS: DCM active
APM: EKF3 IMU0 buffs IMU=19 OBS=7 OF=17 EN:17 dt=0.0120
APM: EKF3 IMU1 buffs IMU=19 OBS=7 OF=17 EN:17 dt=0.0120
APM: EKF3 IMU0 initialised
APM: EKF3 IMU1 initialised
APM: AHRS: EKF3 active
APM: EKF3 IMU1 tilt alignment complete
APM: EKF3 IMU0 tilt alignment complete
APM: EKF3 IMU0 initial yaw alignment complete
APM: EKF3 IMU1 initial yaw alignment complete
APM: PreArm: Check firmware or FRAME_CLASS
APM: PreArm: Throttle below Failsafe
APM: PreArm: 3D Accel calibration needed
APM: PreArm: Compass 1 not Found
reboot
Mode(0)> Got COMMAND_ACK: PREFLIGHT_REBOOT_SHUTDOWN: ACCEPTED
Device /dev/serial/by-id/usb-mRo_mRoPixracerPro_3E0039000951303035343937-if00 is dead
Device /dev/serial/by-id/usb-mRo_mRoPixracerPro_3E0039000951303035343937-if00 reopened OK
no link
link 1 down
no link
DPS310: read took 1 retries
AP_Logger_File: buffer size=204800
link 1 OK
heartbeat OK
APM: Initialising ArduPilot
disabling flow control on serial 3
disabling flow control on serial 2
BMI088: delaying accel config
BMI088: found accel
BMI088: found gyro
APM: Calibrating barometer
APM: Barometer 1 calibration complete
Init Gyro*BMI088: accel config OK (3 tries)
**
APM: ArduPilot Ready
APM: AHRS: DCM active
APM: EKF3 IMU0 buffs IMU=19 OBS=7 OF=17 EN:17 dt=0.0120
APM: EKF3 IMU1 buffs IMU=19 OBS=7 OF=17 EN:17 dt=0.0120
APM: EKF3 IMU0 initialised
APM: EKF3 IMU1 initialised
APM: AHRS: EKF3 active
Mode(0)> APM: EKF3 IMU1 tilt alignment complete
APM: EKF3 IMU0 tilt alignment complete
APM: EKF3 IMU1 initial yaw alignment complete
APM: EKF3 IMU0 initial yaw alignment complete
```

**Comment by peterbarker** [comment]
@joshanne this makes me start to wonder if we've got a regression somewhere else.  Can you see if the behaviour is the same on the stable branches, please?

**Comment by joshanne** [comment]
> @joshanne this makes me start to wonder if we've got a regression somewhere else. Can you see if the behaviour is the same on the stable branches, please?

Interesting - Copter 4.0.7 seems to be fine (only tested 10 reboots, but it would've shown up in that time).

**Comment by joshanne** [comment]
@peterbarker 

I can go back through more commits on master and see if/where it falls over, later today.

**Review by tridge — APPROVED** [review]
i haven't seen this problem, but if you have then I'm happy to include the change

**Comment by tridge** [comment]
> Interesting - Copter 4.0.7 seems to be fine (only tested 10 reboots, but it would've shown up in that time).

when you reproduce this, are you soft rebooting or power cycling?

**Comment by joshanne** [comment]
> when you reproduce this, are you soft rebooting or power cycling?

It was occuring more often while debugging (which is annoying when you can't get past the early init code). It's happening every second `reboot` from mavproxy. Right now I can't seem to get it to occur through power-cycling, but I could swear it did...

**Comment by joshanne** [comment]
Update: It's occuring almost every power cycle with the debug code flashed into the board.

**Comment by tridge** [comment]
I can reproduce now, and I've found that just adding:
```
    dev->set_chip_select(true);
    dev->set_chip_select(false);
```
before the whoami check fixes the issue for me.

**Comment by joshanne** [comment]
> before the whoami check fixes the issue for me.

Can confirm toggling chip select also fixes the issue for me. Happy to close this change out if the plan is to handle this in another layer somewhere (HAL? ChibiOS?)

**Comment by tridge** [comment]
I'll close this and we can go with the simpler fix in #17054

**Pull request closed without merging**
