### PR TITLE
Copter: Clarify private variables

### PR DESCRIPTION
**Pull request by muramura**
I have seen many classes with "_" prepended to private variables.
I think this rule is good.
I want to apply this rule to understand ZIGZAG mode.

### CODE REVIEW

**Comment by rmackay9** [comment]
Hi there, I'm totally happy with this but I'd like to merge [this other PR first](https://github.com/ArduPilot/ardupilot/pull/11080).  As a slight warning, I'm happy with adding the underscore but the opinion is split amongst the maintainers.  For example I don't think Tridge thinks it's worth adding the underscore so if this change was made to one of the shared libraries it probably wouldn't be accepted.

**Comment by muramura** [comment]
@rmackay9 san...   Thanks for your comment.
I would like to support other Copter flight mode classes.
Opinions are divided among ArduPilot members.
I understand.

**Comment by peterbarker** [comment]
On Fri, 12 Apr 2019, Randy Mackay wrote:

> Hi there, I'm totally happy with this but I'd like to merge this other PR first. As a slight warning, I'm happy with adding the underscore but the opinion
> is split amongst the maintainers. For example I don't think Tridge thinks it's worth adding the underscore so if this change was made to one of the shared
> libraries it probably wouldn't be accepted.

I don't really care either way, but I don't like code churn just to fix it 
one way or the other.  See "Wikipedia edit wars"...

**Comment by muramura** [comment]
@peterbarker san.. Coments thanks.
I understand.
I saw the source to change the ZIGZAG mode. It was hard to read because I was different from other classes.
When changing the function of the source, make sure to change it together.

**Pull request closed without merging**
