### PR TITLE
Add autotest for Copter autotune

### PR DESCRIPTION
**Pull request by peterbarker**
Also, factor some repeated maths in the AutoTune mode.

### CODE REVIEW

**Comment by tridge** [comment]
looks good to me

**Comment by khancyr** [comment]
Should we land, reject autotune value and then continue autotest ?

**Comment by rmackay9** [comment]
Merged, thanks!  sorry, I didn't see @khancyr's question before merging.

**Comment by peterbarker** [comment]
@khancyr Pull requests welcome :-P  We should be testing more functionality, of course - both accept/no-accept variants, that sort of thing.  And adding simulated wind to test @tridge 's position-hold as well :-)

**Pull request merged**
