### PR TITLE
ESP32 board cleaning

### PR DESCRIPTION
**Pull request by wiktor-m**
**AP_HAL_ESP32: fix build esp32icarus** - The esp32icarus board didn't compile, I guess because nobody cared. There were 3 boards for the ESP32, compiling all of them may simplify the automated tests as all will compile.
**AP_HAL_ESP32: fix the board names** - pin numbers and board names are better stored in one separate file for a given board. Adding a new board will only modify one place, not several files.
**AP_HAL_ESP32: add empty board - without any sensors** - An empty board that does not contain any sensors, it is a great help for a novice user, by flashing an empty board, you can connect via MP and gradually add sensors. When there is a problem with one sensor, the MP connection does not work and such a user does not know what to do next. I had this problem and spent many days debugging what is wrong.

### CODE REVIEW

**Comment by davidbuzz** [comment]
Hi wiktor, whats the purpose of the PR? What  testing has it had?

**Comment by wiktor-m** [comment]
**AP_HAL_ESP32: fix build esp32icarus** - The esp32icarus board didn't compile, I guess because nobody cared. There were 3 boards for the ESP32, compiling all of them may simplify the automated tests as all will compile.
**AP_HAL_ESP32: fix the board names** - pin numbers and board names are better stored in one separate file for a given board. Adding a new board will only modify one place, not several files.
"AP_HAL_ESP32: add empty board - without any sensors" - An empty board that does not contain any sensors, it is a great help for a novice user, by flashing an empty board, you can connect via MP and gradually add sensors. When there is a problem with one sensor, the MP connection does not work and such a user does not know what to do next. I had this problem and spent many days debugging what is wrong.

**Comment by davidbuzz** [comment]
@wiktor-m  - can i ask u to put that descriptive text into esp32empty.h , or into the libraries/AP_HAL_ESP32/README.md  with a similar description ?   "eg:  'esp32-empty' is an empty board that does not contain any sensors, it is a great help for a novice user, by flashing an empty board, you can connect via MP and gradually add sensors. When there is a problem with one sensor, the MP connection does not work and such a user does not know what to do next. "  ?  otherwise, i think the PR is good.

**Comment by wiktor-m** [comment]
Testing:
**AP_HAL_ESP32: fix build esp32icarus** - before the change it didn't compile, after the change it compiles
**AP_HAL_ESP32: fix the board names** - After compiling, tested in MP. The name of the board "esp32-empty" MP was visible in the logs. Before the change it was always esp32-buzz, no matter what the board was.
**AP_HAL_ESP32: add empty board - without any sensors** - A very simple board that has no sensors, of course, has been tested and MP connects to it via WiFi and UART too.

**Comment by wiktor-m** [comment]
@davidbuzz I added description in esp32empty.h

**Review by davidbuzz — APPROVED** [review]

**Comment by wiktor-m** [comment]
@davidbuzz Could you merge?

**Review by peterbarker — APPROVED** [review]

**Pull request merged**
