### PR TITLE
AP_GPS_NOVA: support tersus/novatel/comnav gps

### PR DESCRIPTION
**Pull request by meee1**
support new gps's

### CODE REVIEW

**Comment by tridge** [comment]
looks good thanks, applied!

**Comment by jinchengde** [comment]
@meee1 so do we support NOVA RTK GPS now?

**Comment by meee1** [comment]
yes, ive tested with a comnav and tersus gps. https://www.youtube.com/watch?v=NytMod9meHs

**Comment by jinchengde** [comment]
thanks！got

**Pull request closed without merging**
