### PR TITLE
AP_Mount: extension of functionality for Alexmos mounts

### PR DESCRIPTION
**Pull request by lekston**
Hello all,

I have passed a few last weeks extending the support for Alexmos mount resulting in this PR. I hope you will bare with me during this quite verbose description.

The main focus here is placed on:
 a) supporting additional messages from the SimpleBGC (FW version 2.60)
 b) adding full support for the GPS_POINT mode
 c) implementing NEUTRAL and RETRACTED modes in a way that ensures correct alignment of the mount in the copters reference frame
 d) supporting continuous infinite rotation in MAVLINK (position), RC (speed) and GPS_POINT modes
 e) providing smooth transitions between MAVLINK (position), RC (speed) and GPS_POINT modes (e.g. when switching between RC and GPS mount keeps pointing in the same direction as long as no joystick deflection is present)
 f) ensuring alignment of the mount's IMU reference frame North with the Magnetic North as measured by Copter's magnetometers
 g) add mechanism for compensating the mount's IMU zenith reference (to ensure level attitude reference during and after prolonged coordinated turns)
 h) translating (0,360) and/or (-180,180) pan/yaw range to Alexmos specific (-720, 720) yaw range (strange indeed but without this the gimbal controller would not make a correct transition via yaw range wrap). The use of (-720, 720) degree pan range does wrap correctly (gimbal continues rotating as demanded).
Some more details on points f and h are provided below.

HW config used for testing:
 - continuous rotation, 3-axis gimbal with single IMU mounted on the inner frame (axis order outside-in: YAW, ROLL, TILT)
 - gimbal controller is not fitted with any dedicated magnetometer
 - gimbal uses all 3 encoders (required to use the patch, encoders must be calibrated)
 - Alexmos mount Follow mode should be disabled for this PR to work
 - MNT_JSTKSPEED param set to 100

As for the f) above, since the SimpleBGS/Alexmos gimbal controller (HW as specified above) boots up it fixes its internal "North" reference forward (i.e. in the direction in which it is pointing during boot). Now, all CMD_CONTROL messages (except msg mode RELATIVE, which is totally different) will set Pan with respect to this arbitrary direction which has nothing to do with the True North. Hence, for correct operation of GPS point Alexmos IMU north must be compensated so I used the CMD_AHRS_HELPER msg here. Unfortunately, the rotation of the North and Zenith vectors from the copter frame to the mount IMU frame (installed on the inner gimbal) must be done by the APM using encoder reading since Alexmos built-in routines for translating the compensation vectors have side-effects (i.a. Gyro Offset gets messed with). All in all, having this North compensation is crucial for GPS_Point functionality.

As for h), the most surprising characteristic of the SimpleBGC is the fact that the reported pan/yaw angle is in the range of (-720, 720) deg (not the same as encoder reading!) and the commanded pan/yaw angle must use the same representation or otherwise the mount will rotate the wrong way after reaching the wrap-around angle.

Also, if you would want to do some additional testing I've pushed a (quite patchy) debug branch of this PR here:
https://github.com/lekston/ardupilot/tree/C3_4_2X_shared

Problems with this patch that I know of and I am open to suggestion on how to proceed:
 - mount's IMU north reference compensation is called only on entry to RETRACTED mode (so this mode must be re-entered from time-to-time during flight)
 - mount's IMU north reference compensation should be called on regular basis (how often? I tested once per 1, 3, 5 secs... and this should be customizable, I think as it has some impact on the gimbals stabilization quality)
 - mount's IMU zenith reference compensation is not called at all (when to do this? in most conditions the IMU on the stabilized inner frame works in more sterile conditions than the Copters EKF so I decided to refrain from calling this compensation routine as long as no coordinated turns are done)
 - currently only continuous 360deg gimbals works well in the above specified setup
 - the driver does not provide any customization to allow for other gimbal configurations
 - should we want customization, additional mount configuration parameters would fall within AP_Mount class which is the parent of AP_Mount_Alexmos - would that be acceptable at all?

I verified the operation of the code provided in this PR on a test bench (used during all development: Pixhawk hooked to 3D gimbal and to GPS NMEA emulator) and in-flight (1 x 15min flight).

Note: I had to use the patch presented in PR #5091 in order to make the gps_point mode work correctly.

Looking forward to any valuable feedback.

Best regards,
Przemek (alias Pshemeck)

### CODE REVIEW

**Comment by rmackay9** [comment]
I hope to get an AlexMos board and gimbal some time soon so I'm happy to test that.  I think mine will be just a 2D gimbal... but at least I can test if things are working on a 2D gimbal.

**Comment by lekston** [comment]
That would be great! On my side I will see how to detect whether the gimbals has encoders or not (as otherwise, large part of this PR my have side-effects).

**Comment by magicrub** [comment]
woah, this has been lingering for a while. @lekston is this still useful?

**Comment by lekston** [comment]
I can bring it up to date during the weekend. The thing I am unable to do on my own thought is testing on mount configurations different than the ones we use in FlyTech. Perhaps there is some other way to work around it? What about a code review from some mount developers?

**Comment by lekston** [comment]
Unfortunately, as of now I do not have any access to a test setup for this mount enhancement as the last one belongs to our client now. As soon as my company has another order for a similar observation copter I will be happy to update and test this. My apologies for keeping you wait.

**Pull request closed without merging**
