### PR TITLE
Regularise compass backend defines

### PR DESCRIPTION
**Pull request by peterbarker**
This makes SITL, MSP, UAVCAN and ExternalAHRS all look much the same, and much the same as other libraries which have had this treatment.

### CODE REVIEW

**Comment by tridge** [comment]
need to somehow demonstrate we don't lose features on some board

**Comment by peterbarker** [comment]
Peter will write a test which builds all boards on master (base branch), then on this PR

**Comment by peterbarker** [comment]
```
Board                     AP_Periph  blimp  copter  heli  iofirmware  plane  rover  sub
AIRLink                              0      0       0                 0      0      0
ARKV6X                               0      0       0                 0      0      0
ARK_GPS                   0                                                         
AeroFox-Airspeed          0                                                         
AeroFox-PMU               0                                                         
AtomRCF405NAVI                       0      0       0                 0      0      0
BeastF7                              0      0       0                 0      0      0
BeastF7v2                            0      0       0                 0      0      0
BeastH7                              0      0       0                 0      0      0
BeastH7v2                            0      0       0                 0      0      0
BirdCANdy                 0                                                         
CUAV-Nora                            0      0       0                 0      0      0
CUAV-Nora-bdshot                     0      0       0                 0      0      0
CUAV-X7                              0      0       0                 0      0      0
CUAV-X7-bdshot                       0      0       0                 0      0      0
CUAV_GPS                  0                                                         
CUAVv5                               0      0       0                 0      0      0
CUAVv5-bdshot                        0      0       0                 0      0      0
CUAVv5Nano                           0      0       0                 0      0      0
CUAVv5Nano-bdshot                    0      0       0                 0      0      0
CarbonixF405              0                                                         
CarbonixL496              0                                                         
CubeBlack                            0      0       0                 0      0      0
CubeBlack+                           0      0       0                 0      0      0
CubeBlack-periph          0                                                         
CubeGreen-solo                              0                                       
CubeOrange                           0      0       0                 0      0      0
CubeOrange-ODID                      0      0       0                 0      0      0
CubeOrange-SimOnHardWare                    0                                       
CubeOrange-bdshot                    0      0       0                 0      0      0
CubeOrange-joey                      0      0       0                 0      0      0
CubeOrange-periph         0                                                         
CubeOrange-periph-heavy   0                                                         
CubeOrangePlus                       0      0       0                 0      0      0
CubePilot-CANMod          0                                                         
CubePurple                           0      0       0                 0      0      0
CubeSolo                                    0                                       
CubeYellow                           0      0       0                 0      0      0
CubeYellow-bdshot                    0      0       0                 0      0      0
DevEBoxH7v2                          0      0       0                 0      0      0
DrotekP3Pro                          0      0       0                 0      0      0
Durandal                             0      0       0                 0      0      0
Durandal-bdshot                      0      0       0                 0      0      0
F35Lightning                         0      0       0                 0      0      0
F4BY                                 0      0       0                 0      0      0
FlyingMoonF407                       0      0       0                 0      0      0
FlyingMoonF427                       0      0       0                 0      0      0
FlywooF745                           0      0       0                 0      0      0
FlywooF745Nano                       0      0       0                 0      0      0
FreeflyRTK                0                                                         
G4-ESC                    0                                                         
H757I_EVAL                                                                          
H757I_EVAL_intf                                                                     
HerePro                   0                                                         
Hitec-Airspeed            0                                                         
HitecMosaic               0                                                         
HolybroG4_GPS             0                                                         
HolybroGPS                0                                                         
JHEMCU-GSF405A                       0      0       0                 0      0      0
JHEMCU-GSF405A-RX2                   0      0       0                 0      0      0
KakuteF4                             0      0       0                 0      0      0
KakuteF4Mini                         0      0       0                 0      0      0
KakuteF7                             0      0       0                 0      0      0
KakuteF7-bdshot                      0      0       0                 0      0      0
KakuteF7Mini                         0      0       0                 0      0      0
KakuteH7                             0      0       0                 0      0      0
KakuteH7-bdshot                      0      0       0                 0      0      0
KakuteH7Mini                         0      0       0                 0      0      0
KakuteH7Mini-Nand                    0      0       0                 0      0      0
KakuteH7v2                           0      0       0                 0      0      0
MambaF405-2022                       0      0       0                 0      0      0
MambaF405US-I2C                      0      0       0                 0      0      0
MambaF405v2                          0      0       0                 0      0      0
MambaH743v4                          0      0       0                 0      0      0
MatekF405                            0      0       0                 0      0      0
MatekF405-CAN                        0      0       0                 0      0      0
MatekF405-STD                        0      0       0                 0      0      0
MatekF405-TE                         0      0       0                 0      0      0
MatekF405-Wing                       0      0       0                 0      0      0
MatekF405-Wing-bdshot                0      0       0                 0      0      0
MatekF405-bdshot                     0      0       0                 0      0      0
MatekF765-SE                         0      0       0                 0      0      0
MatekF765-Wing                       0      0       0                 0      0      0
MatekF765-Wing-bdshot                0      0       0                 0      0      0
MatekH743                            0      0       0                 0      0      0
MatekH743-bdshot                     0      0       0                 0      0      0
MatekH743-periph          0                                                         
MatekL431-Airspeed        0                                                         
MatekL431-DShot           0                                                         
MatekL431-EFI             0                                                         
MatekL431-GPS             0                                                         
MatekL431-Periph          0                                                         
MatekL431-Rangefinder     0                                                         
MatekL431-bdshot          0                                                         
MazzyStarDrone                       0      0       0                 0      0      0
Nucleo-G491               0                                                         
Nucleo-L476               0                                                         
Nucleo-L496               0                                                         
NucleoH743                                                                          
NucleoH755                                                                          
OMNIBUSF7V2                          0      0       0                 0      0      0
OmnibusNanoV6                        0      0       0                 0      0      0
OmnibusNanoV6-bdshot                 0      0       0                 0      0      0
PH4-mini                             0      0       0                 0      0      0
PH4-mini-bdshot                      0      0       0                 0      0      0
Pix32v5                              0      0       0                 0      0      0
PixC4-Jetson                         0      0       0                 0      0      0
PixSurveyA1                          0      0       0                 0      0      0
Pixhawk1                             0      0       0                 0      0      0
Pixhawk1-1M                          0      0       0                 0      0      0
Pixhawk1-1M-bdshot                   0      0       0                 0      0      0
Pixhawk4                             0      0       0                 0      0      0
Pixhawk4-bdshot                      0      0       0                 0      0      0
Pixhawk5X                            0      0       0                 0      0      0
Pixhawk6C                            0      0       0                 0      0      0
Pixhawk6X                            0      0       0                 0      0      0
Pixhawk6X-ODID                       0      0       0                 0      0      0
Pixracer                             0      0       0                 0      0      0
Pixracer-bdshot                      0      0       0                 0      0      0
Pixracer-periph           0                                                         
QioTekZealotF427                     0      0       0                 0      0      0
QioTekZealotH743                     0      0       0                 0      0      0
R9Pilot                              0      0       0                 0      0      0
ReaperF745v2                         0      0       0                 0      0      0
SITL_arm_linux_gnueabihf             0      0       0                 0      0      0
SITL_x86_64_linux_gnu                0      0       0                 0      0      0
SPRacingH7                           0      0       0                 0      0      0
Sierra-F405               0                                                         
Sierra-F412               0                                                         
Sierra-F9P                0                                                         
Sierra-L431               0                                                         
SkystarsH7HD                         0      0       0                 0      0      0
SkystarsH7HD-bdshot                  0      0       0                 0      0      0
SuccexF4                             0      0       0                 0      0      0
Swan-K1                                                               0             
TBS-Colibri-F7                       0      0       0                 0      0      0
VRBrain-v51                          0      0       0                 0      0      0
VRBrain-v52                          0      0       0                 0      0      0
VRBrain-v54                          0      0       0                 0      0      0
VRCore-v10                           0      0       0                 0      0      0
VRUBrain-v51                         0      0       0                 0      0      0
ZubaxGNSS                 0                                                         
airbotf4                             0      0       0                 0      0      0
bbbmini                              0      0       0                 0      0      0
blue                                 0      0       0                 0      0      0
crazyflie2                           0      0       0                 0      0      0
edge                                 0      0       0                 0      0      0
erlebrain2                           0      0       0                 0      0      0
f103-ADSB                 0                                                         
f103-Airspeed             0                                                         
f103-GPS                  0                                                         
f103-HWESC                0                                                         
f103-QiotekPeriph         0                                                         
f103-RangeFinder          0                                                         
f103-Trigger              0                                                         
f303-GPS                  0                                                         
f303-HWESC                0                                                         
f303-M10025               0                                                         
f303-M10070               0                                                         
f303-MatekGPS             0                                                         
f303-PWM                  0                                                         
f303-TempSensor           0                                                         
f303-Universal            0                                                         
f405-MatekAirspeed        0                                                         
f405-MatekGPS             0                                                         
fmuv2                                0      0       0                 0      0      0
fmuv3                                0      0       0                 0      0      0
fmuv3-bdshot                         0      0       0                 0      0      0
fmuv5                                0      0       0                 0      0      0
iomcu                                                     0                         
iomcu_f103_8MHz                                           0                         
luminousbee4                         0      0       0                 0      0      0
luminousbee5                         0      0       0                 0      0      0
mRo-M10095                0                                                         
mRo-canpwm                0                                                         
mRoControlZeroClassic                0      0       0                 0      0      0
mRoControlZeroF7                     0      0       0                 0      0      0
mRoControlZeroH7                     0      0       0                 0      0      0
mRoControlZeroH7-bdshot              0      0       0                 0      0      0
mRoControlZeroOEMH7                  0      0       0                 0      0      0
mRoNexus                             0      0       0                 0      0      0
mRoPixracerPro                       0      0       0                 0      0      0
mRoPixracerPro-bdshot                0      0       0                 0      0      0
mRoX21                               0      0       0                 0      0      0
mRoX21-777                           0      0       0                 0      0      0
mindpx-v2                            0      0       0                 0      0      0
mini-pix                             0      0       0                 0      0      0
modalai_fc-v1                        0      0       0                 0      0      0
navigator                            0      0       0                 0      0      0
navio                                0      0       0                 0      0      0
navio2                               0      0       0                 0      0      0
obal                                 0      0       0                 0      0      0
omnibusf4                            0      0       0                 0      0      0
omnibusf4pro                         0      0       0                 0      0      0
omnibusf4pro-bdshot                  0      0       0                 0      0      0
omnibusf4pro-one                     0      0       0                 0      0      0
omnibusf4v6                          0      0       0                 0      0      0
pxf                                  0      0       0                 0      0      0
pxfmini                              0      0       0                 0      0      0
revo-mini                            0      0       0                 0      0      0
revo-mini-bdshot                     0      0       0                 0      0      0
revo-mini-i2c                        0      0       0                 0      0      0
revo-mini-i2c-bdshot                 0      0       0                 0      0      0
revo-mini-sd                                                                        
skyviper-f412-rev1                          0                                       
skyviper-journey                            0                                       
skyviper-v2450                              0                                       
sparky2                              0      0       0                 0      0      0
speedybeef4                          0      0       0                 0      0      0
speedybeef4v3                        0      0       0                 0      0      0
```

**Review by tridge — APPROVED** [review]

**Comment by tridge** [comment]
needs a rebase

**Pull request merged**
