### PR TITLE
Global: Change @values and @bitmask to @bitmask only

### PR DESCRIPTION
**Pull request by muramura**
I'll change the pertinent one based on the comment in #15291 .

### CODE REVIEW

**Comment by magicrub** [comment]
@bitmask sorry, looks like the github tag comes from text in the git commit message. If @muramura can't change his messages you might want to block the announcements from your end somehow for this specific repo.

**Comment by muramura** [comment]
@bitmask san, @magicrub san. I have changed the AT mark in the title.

**Comment by amilcarlucas** [comment]
I'm not sure I like this. Some users find bitmasks confusing, and do not know how to calculate them, the values do get out of date fast, but provide at least some directions ....

**Comment by tridge** [comment]
I don't see a justification for globally removing this. There are some where values better represents what users want

**Comment by tridge** [comment]
discussed on dev call, and closing

**Pull request closed without merging**
