### PR TITLE
AP_UAVCAN: uavcan DNA range min/max, and dual-bus support for DNA

### PR DESCRIPTION
**Pull request by davidbuzz**
- suitable for multiple pixhawks on the same CAN bus
 - or co-existing with an other DNA server.
 - or multi-bus setups where you don't want id's on the different bus to conflict for other reasons.
 - if a node from a previous setup is found in persistent storage that is outside of the defined range, it's removed and the node treated as a new one, and assigned a new id inside the range.
eg: this will cause the DNA server to only assign CAN node id's in the 40-80 range, inclusive.
>param set CAN_D1_UC_AL_MIN 40
>param set CAN_D1_UC_AL_MAX 80
reboot required after changing these.

### CODE REVIEW

**Comment by davidbuzz** [comment]
note to self, I'm not sure that this works with param of CAN_P2_DRIVER = 2 yet, ie  with the pixhawk treating it's two different CAN ports as two different bus's.   testing in progress, and will update this PR once that's done.

**Comment by davidbuzz** [comment]
i've added a bunch of debug statement/s to the two CAN-DNA server instances that are started-up when CAN_P2_DRIVER = 2 and fixed the assumption/s that there is only ever one, and tested it, so I'm going to push the lots-of-debug here for comment.    As far as this PR is concerned, please ignore all the nasty debugbing statement/s likedebug_uavcan_mav(...) and debug_uavcac(...), as they will be cleaned up and removed once someone other than me has tried this code with multiple bus's enabled and multiple instances of the DNA server running....

**Comment by davidbuzz** [comment]
@bugobliterator , you've done stuff with the DNA server recently, maybe u can comment on the general direction this is heading ..?

**Comment by bugobliterator** [comment]
@davidbuzz sorry this PR slipped through. Are you still interested in pursuing this?

**Comment by davidbuzz** [comment]
The scenario we had this PR for was three pixhawk's , each 100% unaware of each other existance, and each responsible for one 'lane' of a 'three lane' redundant CAN system...   but the 'gotcha' is that in order to do diagnostics/debugging of CAN packets in a meaningful manner, we stream all three of these bus's info together into one 'super stream' of packets that we capture and analyse via a linux computer... ( ignoring for a moment how the packets get there... imagine there were 3 babels involved )  my point being this linux computer needs to "see" all the nodes on all three busses at once, without ID conflicts.  So we limit the 'range' each bus can have to non-overlapping node id's.   the second CAN port on each pixhawk is not used as part of this 'three lane' system, its used for 3x gps , one to each pixhawk.   
I don't think your solution will work as an alternative to this, as it assume's these pixhawk's can see each other on a shared bus... where for us, the only device that is omni-present on theree bus's is diagnostics equipment and not flight critical if it fails.

**Comment by bugobliterator** [comment]
@davidbuzz yeah, I see how for your particular scenario this is needed, anyways let me know if you want this PR resurrected. Its in need of a rebase. Once rebased, I can do the review and work towards merging it. Again, apologies for the hold up!

**Comment by peterbarker** [comment]
I'm afraid everything's been rewritten multiple times since this PR was created.

We do have the dual-bus support now IIUC, and for some reason the range thing isn't a problem.

Please create a fresh PR if you'd like to push anything forward here.

**Pull request closed without merging**
