### PR TITLE
AP_Landing:  Change the switch statement for the future to comment explanation.

### PR DESCRIPTION
**Pull request by muramura**
I do not think that it is necessary to be a switch statement now.
Therefore,
Can be substituted by comment explanation.

### CODE REVIEW

**Comment by OXINARF** [comment]
@magicrub Should this be merged or closed? I know AP_Landing is going through changes, so this switch is probably better to stay.

**Comment by WickedShell** [comment]
I nominate close this. We will be using the switch shortly, and the compiler is optimizing this anyways, so I don't think we need to step through the noise of changing it now, as well as the probable conflicts with the other landing pr.

**Comment by muramura** [comment]
i understand.
there switch statements is optimized.
and 
other pr is used switchs.

this pr is close.

**Comment by magicrub** [comment]
Yeah, this is a work in progress. More cases are coming soon..

**Pull request closed without merging**
