### PR TITLE
Offboard reserve mode ID

### PR DESCRIPTION
**Pull request by Ryanf55**
Reserve mode 30 for offboard so it's the same on all vehicles.

### CODE REVIEW

**Comment by rmackay9** [comment]
Thanks for this. I'd vote for using mode 29 or 30.  29 is an odd number but that's OK.

**Comment by Ryanf55** [comment]
> Thanks for this. I'd vote for using mode 29 or 30. 29 is an odd number but that's OK.

I'll do 30!

**Comment by timtuxworth** [comment]
Does this have to line up with @IamPete1 's work on "scripted modes", where it will be possible to create new modes in Lua script that inherit from Guided?

**Comment by Ryanf55** [comment]
> Does this have to line up with @IamPete1 's work on "scripted modes", where it will be possible to create new modes in Lua script that inherit from Guided?

Yea that's the idea. We need to work together on a long term design, this is just a reservation if we choose to stop using guided for offboard on plane, and make it consistent between all the vehicles.

**Review by rmackay9 — APPROVED** [review]
thanks!

**Review by tridge — APPROVED** [review]

**Pull request merged**
