### PR TITLE
AP_TECS: add documentation for TECS and TEC2

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by peterbarker** [comment]
... when generating the XML document on the server we could generate an empty log using the relevant messagewriters (just containing `FMT`, `UNIT`, `MULT`), and augment the XML document with data gleaned from the log.  This will also allow us to validate the metadata.

**Comment by peterbarker** [comment]
Sample .rst output

```
.. Dynamically generated list of Logger Messages
.. This page was generated using Tools/autotest/logger_metdata/parse.py

.. DO NOT EDIT

.. _logmessages:

Onboard Message Log Messages
============================

This is a list of log messages which may be present in logs produces and stored onboard ArduPilot vehicles.


.. _TECS:

TECS: Information about the Total Energy Control System
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+--------+-----------------------------------------------------------------------------------------------------+
| spdem  | True AirSpeed TECS is currently trying to achieve                                                   |
+--------+-----------------------------------------------------------------------------------------------------+
| ith    | throttle integrator value                                                                           |
+--------+-----------------------------------------------------------------------------------------------------+
| dh     | current climb rate ("delta-height")                                                                 |
+--------+-----------------------------------------------------------------------------------------------------+
| f      | flags                                                                                               |
+--------+-----------------------------------------------------------------------------------------------------+
| h      | height estimate (UP) currently in use by TECS                                                       |
+--------+-----------------------------------------------------------------------------------------------------+
| iph    | Specific Energy Balance integrator value                                                            |
+--------+-----------------------------------------------------------------------------------------------------+
| sp     | current estimated True AirSpeed                                                                     |
+--------+-----------------------------------------------------------------------------------------------------+
| dsp    | x-axis acceleration estimate ("delta-speed")                                                        |
+--------+-----------------------------------------------------------------------------------------------------+
| dspdem | demanded acceleration output ("delta-speed demand")                                                 |
+--------+-----------------------------------------------------------------------------------------------------+
| w      | current TECS prioritisation of height vs speed (0==100% height,2==100% speed, 1==50%height+50%speed |
+--------+-----------------------------------------------------------------------------------------------------+
| th     | throttle output                                                                                     |
+--------+-----------------------------------------------------------------------------------------------------+
| hdem   | height TECS is currently trying to achieve                                                          |
+--------+-----------------------------------------------------------------------------------------------------+
| ph     | pitch output                                                                                        |
+--------+-----------------------------------------------------------------------------------------------------+
| dhdem  | climb rate TECS is currently trying to achieve                                                      |
+--------+-----------------------------------------------------------------------------------------------------+


.. _TEC2:

TEC2: Additional Information about the Total Energy Control System
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+--------+----------------------------------------------------------------------------+
| LF     | aerodynamic load factor                                                    |
+--------+----------------------------------------------------------------------------+
| PErr   | difference between estimated potential energy and desired potential energy |
+--------+----------------------------------------------------------------------------+
| EDelta | current error in speed/balance weighting                                   |
+--------+----------------------------------------------------------------------------+
| KErr   | difference between estimated kinetic energy and desired kinetic energy     |
+--------+----------------------------------------------------------------------------+


.. _FMT:

FMT: Message defining the format of messages in this file
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+--------+----------------------------------------------------------------------------+
| length | the number of bytes taken up by this message (including all headers)       |
+--------+----------------------------------------------------------------------------+
| labels | the labels of the message being defined                                    |
+--------+----------------------------------------------------------------------------+
| type   | unique-to-this-log identifier for message being defined                    |
+--------+----------------------------------------------------------------------------+
| name   | name of the message being defined                                          |
+--------+----------------------------------------------------------------------------+
| format | character string defining the C-storage-type of the fields in this message |
+--------+----------------------------------------------------------------------------+


.. _GPS:

GPS: Data from first configured GPS
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+--------+---------------------------------------------------------+
| Status | GPS fix type (2D, 3D, ...)                              |
+--------+---------------------------------------------------------+
| HDop   | Horizontal Degree of Position; indicator of fix quality |
+--------+---------------------------------------------------------+
| GCrs   | GPS-supplied ground course                              |
+--------+---------------------------------------------------------+
| NSats  | number of satellites used in fix                        |
+--------+---------------------------------------------------------+
| Yaw    | GPS-supplied vehicle yaw                                |
+--------+---------------------------------------------------------+
| GWk    | GPS week (weeks since GPS epoch)                        |
+--------+---------------------------------------------------------+
| TimeUS | microseconds since system boot                          |
+--------+---------------------------------------------------------+
| VZ     | GPS-supplied vertical speed                             |
+--------+---------------------------------------------------------+
| Lat    | measured vehicle latitude                               |
+--------+---------------------------------------------------------+
| U      | used - true of the GPS is enabled for use               |
+--------+---------------------------------------------------------+
| GMS    | milliseconds since start of GPS week                    |
+--------+---------------------------------------------------------+
| Lng    | measured vehicle longitude                              |
+--------+---------------------------------------------------------+
| Spd    | GPS-supplied vehicle xy speed                           |
+--------+---------------------------------------------------------+
| Alt    | measured vehicle altitude (above geoid)                 |
+--------+---------------------------------------------------------+



```

**Comment by WickedShell** [comment]
I've discussed this with Peter directly before, but noting it directly here. I'm not a fan of this as it's extremely verbose for adding the documentation, and makes the separation even worse then the current effort to declare log entries. This format also doesn't cope with repeated entries like BATn well.

**Comment by peterbarker** [comment]
I've investigated alternate approaches to this, most notably optionally compiling the metadata in.  Nothing else has worked as well as this.  (chief problem of the "compile it in" concept is Log_Write messages; if you want to generate the documentation for them you have to cross that codepath.

I don't think the verbosity can be avoided.  And I think it's clear enough that even non-deeply-technically-competent contributors could modify and add to the format proposed here.

The repetition (`BATn`) issue should go away as we start to move to instance numbers rather than multiple message IDs.

Lastly, something is better than nothing.  People want this stuff documented, and this is... something.

**Comment by Hwurzburg** [comment]
@peterbarker so my list would be: ATT,ATUN,BARO,BAT,CTUN,GPS,MAG,MODE,PID/PIDQ (cant these be recursed with SUBGROUPs somehow to minimize effort?),QTUN,RAT,RCIN,RCOU,TECS,VIBE
a bit more than a dozen, but not by a lot...but @tridge and @rmackay9 should also comment...

**Pull request merged**
