### PR TITLE
Winch: Optionalize the winch.

### PR DESCRIPTION
**Pull request by muramura**
https://github.com/ArduPilot/ardupilot/issues/7682

I tried Randy 's comment "Remove winch class" of the assignment.
The solution was not possible,
However, the winch is not essential, so I think that it would be better if you could specify it with options.

### CODE REVIEW

**Comment by rmackay9** [comment]
Very nice.  Thanks for this!

A couple of things: 

- there are some unintended formatting changes.
- the #defines should be at a lower level if possible.  So for example in the switch statement, put them inside the case so we don't get a compile warning.  similarly put them  inside the winch_init (or is it init_winch).

thanks again!

**Comment by muramura** [comment]
@rmackay9 san. Comments Thanks.
I change the designation of WINCH_ENABLED.
I referred to GRIPPER_ENABLED.

**Comment by rmackay9** [comment]
@muramura, I guess you see the extra formatting changes in the commit?  For example this line:

> mavlink_msg_pid_tuning_send(chan, PID_TUNING_ROLL,

If possible it's best not to make unrelated formatting changes like this.  Maybe put it in a new commit.

**Comment by rmackay9** [comment]
I've merged this to master after a bit of rework.

I definitely appreciate the fix and maybe I'll improve our developer wiki to make it more clear how PRs should be done.

**Comment by muramura** [comment]
@rmackay9 san, thanks for the change. .
I will not change code that is irrelevant to PR.

**Pull request closed without merging**
