### PR TITLE
Update Airsim Lidar Avoidance

### PR DESCRIPTION
**Pull request by rajat2004**
Fix AirSim lidar data calculation, also update the params to use BendyRuler by default

### CODE REVIEW

**Comment by rajat2004** [comment]
I'm still not sure if the new Proximity method is entirely correct, but the old one definitely seems wrong. Will be great to have a review of that!
And this will cause conflicts with https://github.com/ArduPilot/ardupilot/pull/13024, so probably that one'll go first and then will fix this

**Comment by rajat2004** [comment]
Rebased on master, tested to be working, would be good to have a review of whether the new sector update code and params are correct

**Comment by rajat2004** [comment]
File renamed for more intuitive usage, since the params in it are not Copter-specific, and for using with Rover as well

**Comment by rmackay9** [comment]
Merged, thanks!

**Pull request merged**
