### PR TITLE
ChibiOS: change KakuteF7 to EKF2 and remove HAL_MINIMIZE

### PR DESCRIPTION
**Pull request by Hwurzburg**
to allow test/dev community to continut to refine new features

### CODE REVIEW

**Review by andyp1per — APPROVED** [review]

**Comment by tridge** [comment]
i'd rather defer this and see if we can reduce flash cost of EKF3

**Comment by tridge** [comment]
on firmware server, KakuteF7 has plenty of free flash space, over 100k

**Comment by Hwurzburg** [comment]
@tridge the motivation for this was that as of last week or so, the firmware server was not building this board due to space....its great that it has space now...I just tried a point 20 days ago and it was out of space by 3.5K...so something changed recently...but as of the first of the year it had not build since Dec14th

**Comment by andyp1per** [comment]
@tridge that's because this board was switch to HAL_MINIMIZE_FEATURES very recently so has lost a whole bunch of features

**Pull request closed without merging**
