### PR TITLE
AP_HAL_F4Light: add python3 support

### PR DESCRIPTION
**Pull request by cclauss**
* __print()__ is a function in modern Python
* define __raw_input()__ in Python 3
* remove redundant import of __time__
* define __xrange()__ in Python 3
* New style exceptions for Python 3
* __file()__ was removed in Python 3
* PEP8 avoidance of backslash

### CODE REVIEW

**Comment by rmackay9** [comment]
Seems OK to me but it's really up to @night-ghost (the maintainer) if he's happy with this.  If he's happy we can quickly push the merge button.

As a side note, the subject line of the commit should start with "AP_HAL_F4Light:" so perhaps it should be, "AP_HAL_F4Light: use print()"

**Comment by khancyr** [comment]
LGTM, the subject should be more "AP_HAL_F4Light: add python3 support"

**Comment by khancyr** [comment]
@cclauss that the commit message that should be changed ! ;-P

**Comment by night-ghost** [comment]
I really don't use python tools except dfu_create and I have idiosyncrasy on Python, so my opinion on this theme should be in the last place, if it works.

**Comment by tridge** [comment]
pushed with a fix to commit comment to add HAL_F4Light:
thanks!

**Pull request closed without merging**
