### PR TITLE
Copter: explain why call set_max_speed_z in run()

### PR DESCRIPTION
**Pull request by chobitsfan**
Thanks @peterbarker very much for answering my question in discord
I think it may help others developers

### CODE REVIEW

**Comment by rmackay9** [comment]
thanks for this.  This will conflict with Leonard's large pos controller update PR so let's hold off on merging this https://github.com/ArduPilot/ardupilot/pull/17345.

**Comment by peterbarker** [comment]
@chobitsfan time to look at this one again now Leonard stuff is in?

**Comment by chobitsfan** [comment]
Hi @peterbarker 
Thank you for reminding me. Done.

**Comment by lthall** [comment]
If we are going to add this here we should add it everywhere it is appropriate.

**Comment by chobitsfan** [comment]
Hi @lthall 
Perhaps we could add it here?
https://github.com/ArduPilot/ardupilot/blob/d907328f8065aa74fa3f77ec5e1a53ee5e0ca1e6/libraries/AC_AttitudeControl/AC_PosControl.h#L143

**Comment by peterbarker** [comment]
@chobitsfan I think the comments actually do need to go everywhere that line appears in the mode files, as Leonard suggests.  That's where the questions will appear to people.

Did you still want to pursue this one?  It's been a long time!

**Comment by chobitsfan** [comment]
Hi @peterbarker Thank you. I agree with you and @lthall. I will close this PR because it will change too many files.

**Pull request closed without merging**
