### PR TITLE
Tools: Param Parse: multi line @Values

### PR DESCRIPTION
**Pull request by IamPete1**
Allows formatting to be reworked making it much easier to read and reducing conflicts. No change in parsed output.

Is a little odd in that if there is a a `@Values{vehicle}` anywhere all `@Values` without a vehicle type will be ignored. This means if something does apply to all vehicles it needs them all to be called out. eg: `@Values{Copter, Rover, Plane, Blimp}: 0:Do Nothing`. A new "all" tag might make this less painful.

The next one would be the servo functions. Again there its a little more complicated, because there is a full list and then a vehicle list for copter plane and rover. So in that case we need everything twice eg:
```
// @Values: -1:GPIO
// @Values{Copter, Rover, Plane}: -1:GPIO
// @Values: 0:Disabled
// @Values{Copter, Rover, Plane}: 0:Disabled
```
We can't just take the none vehicle value if there is no vehicle one, because the vehicle wants to exclude as well as include options. We could make a super set of all the vehicle parameters for the generic, but we currently have some conflicting values. EG:
```
// @Values{Copter, Rover}: 4:RTL
// @Values{Plane}: 4:ModeRTL
...
// @Values{Copter}: 30:Lost Copter Sound
// @Values{Rover}: 30:Lost Rover Sound
// @Values{Plane}: 30:Lost Plane Sound
...
// @Values{Copter, Rover, Plane}: 153:ArmDisarm (4.2 and higher)
// @Values{Blimp}: 153:ArmDisarm
```
Of course we could unify those between vehicles, but that would make this PR a change to the parsed output.

### CODE REVIEW

**Comment by Hwurzburg** [comment]
I am sure we have many with a generic (no vehicle name) and then specific ones....so many values are missing for some vehicles/params, no?

**Comment by IamPete1** [comment]
Yeah, there are lots of missing RC options that work on all vehicles. This just a move to the new format with no changes, we can fix all that stuff in the future.

**Comment by WickedShell** [comment]
Doesn't MP have it's own parser that would also need an update? Per line readability this is definitely good, from a code editing point of view it feels rough. But that's probably the right tradeoff.

**Comment by IamPete1** [comment]
> Doesn't MP have it's own parser that would also need an update?

I think MP is now using this parser.

**Comment by rmackay9** [comment]
This seems much more maintainable.. readers will be scrolling down a long way to get through the parameter descriptions in some cases but still really good.

**Review by peterbarker — APPROVED** [review]

**Pull request merged**
