### PR TITLE
Fix VTOL-land loiter-to-alt (actually land the vehicle....)

### PR DESCRIPTION
**Pull request by peterbarker**
The loiter-to-alt-for-vtol-land code is not initialising loiter.direction - so if you have not loitered in this boot then loiter.direction was zero.

This leaves this multiplication at zero: https://github.com/ardupilot/ardupilot/blob/master/ArduPlane/navigation.cpp#L40 - which means you never complete the waypoint as the spiral-vtol-land code also checks sum_cd for being > 1: https://github.com/ardupilot/ardupilot/blob/master/ArduPlane/commands_logic.cpp#L1039

The trivial included test doesn't pass before but does pass after this patch.  The plane will just keep circling in master.

I'm guessing we should probably also initialise the loiter direction properly in the spiral-landing code - perhaps we won't land with counter-clockwise circles, for example....

This *may* have been (ironically?) broken by https://github.com/ArduPilot/ardupilot/pull/21182

### CODE REVIEW

**Comment by IamPete1** [comment]
Did you forget to add the mission?

**Comment by peterbarker** [comment]
> Did you forget to add the mission?

It's a long tradition.

I've added it now.

**Review by IamPete1 — APPROVED** [review]
I put in a little if to check for loiter direction not being set. Looks like its a problem in lots of places, it also means that we don't do the correct loiter navigation if its 0. 

So I think this is the correct fix, I would be un-surprised to find there were other cases where this is a issue that we have not found yet.

It should not cause any issue as it is left none zero after were done loitering and we don't have reports of stuff not working after having loitered.

**Comment by tridge** [comment]
I've pushed a fix to cope with both directions of loiter

**Comment by tridge** [comment]
@IamPete1 there is a 2nd bug, when WP_LOITER_RAD is small the plane turns out then comes back in, which causes an overshoot landing and breaks the point of the approach landing

**Comment by peterbarker** [comment]
I've popped my fix off after discussions with tridge; the problem is that it only catches half the bugs (not setting the loiter direction), and planes orbiting CCW won't land.

I've augmented the test to orbit both ways.

**Review by IamPete1 — APPROVED** [review]

**Review by tridge — APPROVED** [review]

**Comment by peterbarker** [comment]
> I put in a little if to check for loiter direction not being set. Looks like its a problem in lots of places, it also means that we don't do the correct loiter navigation if its 0.

That sounds like a useful check - can you show me that patch?

**Pull request merged**
