### PR TITLE
AP_AdvancedFailsafe: Add triggering AFS by aux input pin

### PR DESCRIPTION
**Pull request by Pedals2Paddles**
This will allow an external device to trigger the advanced failsafe termination by pulling an aux input pin high or low.  Also in this PR, I have enabled AFS in copter (maybe temporarily) since that's where a use case recently came up. However I can pull that out into a separate PR if needed. 

The most obvious use for this that recently came up is for an external parachute controller.  This will allow the external chute controller to trigger AFS cutting the motors when it pops the chute.  Any other external failsafe or deadman can utilize this to.

I still cannot figure out how to set an aux pin high or low in SITL to test this, and I don't have hardware available to test it for real with.  If someone can show me how to do that, that'd be great.

### CODE REVIEW

**Comment by eengelgau** [comment]
Hi Pedals, These folks are our customer and who we are advocating for.  There is a branch in the PX4 code base where this was implemented.  See https://github.com/PX4/Firmware/pull/13726.

I'm not a PX4 expert by any means, but I do have a lot of background why this is needed and we have been working on drone recovery systems for almost 10 years now.

-Gene

**Comment by auturgy** [comment]
Why AFS not AP_Parachute?
AFS is rarely used, and I think it would be more intuitive for users if we add another CHUTE_TYPE (ie external trigger), and use that interface.

**Comment by IamPete1** [comment]
why not use AP_Button to get the input?

**Comment by peterbarker** [comment]
On Sun, 12 Jan 2020, Peter Hall wrote:

> why not use AP_Button to get the input?

Initially I'd thought the same thing - perhaps attach an RC_Channel 
AUX_FUNC to a button being pressed.  You have to note here that the button 
library would be need to be heavily modified to handle PWM inputs - 
currently it looks at pin levels only.  That implies min/max PWM value 
parameters.

So, perhaps, a new RC aux function, "handle_parachute_deployed" sort of 
thing.  This would call a method on the parachute library which would do 
whatever it does when the parachute has been deployed - stop motors, start 
alarms, that sort of thing.

Is that extra layer of indirection worth it, however?  It would be fewer 
parameters eventually.  It would also allow for non-PWM triggering of the 
same functions (so simple pin assertion).

We should probably already have an RC aux option to trigger AFS, it occurs 
to me.

**Comment by rmackay9** [comment]
when AFS was first implemented, I wasn't keen on having it enabled by default because it was very separate to the existing failsafes.  I haven't looked at it recently but my recollection is that we could have done the same kinds of things by extending the existing failsafes rather than adding on a new library.

**Comment by Pedals2Paddles** [comment]
I'm not sure what the purpose of AP_Button even is really. I doesn't appear to even be used?

My understanding up to now was that if you have an sbus or spektrum or ppm RC connected, then you can't connect some other source of RC PWM input on the other channels that are not being used.  If that understanding is incorrect, then this can also be done by adding AFS to the aux switch options since the external chute devices do PWM outputs too.

As far as AFS in copter goes, this can probably be accomplished with emergency stop just as well without enabling AFS.

**Comment by eengelgau** [comment]
Hi all, I've been following this issue along.  It looks like this is moving toward being able to have the Flight Termination functionality needed by an external ATS (automatic parachute trigger system) implements via external PWM input? To reiterate that a PWM pulse input on some PH aux port or channel of say 2000us (+- some tolerance) is asserted will then the rotors stop?

This is my post on the message board: https://discuss.ardupilot.org/t/add-external-flight-termination-feature-to-autdupilot-per-astm-f3322-18/50976

-Gene

**Comment by IamPete1** [comment]
Maybe we could add some sort of AP_Input that combines AP_Button with PWM input, potential saving some params, we have PWM in for rssi, fuel level battery monitor and probability some other places. Could add analogue inputs pins also i guess.

**Comment by auturgy** [comment]
Thanks Gene,
yes: basically we’re having a gentle debate about where the external parachute trigger/termination signal is best inserted into the codebase.
Matt grabbed the problem and ran with it (which is great), but some of us think that a different approach might achieve the desired outcome in a better way.
ArduPilot is a complex codebase, and there are almost always multiple ways of implementing something, so debates about relative technical merit of the various options are normal/healthy :)

This is flagged for our weekly dev call, in about 9 hours, so we should settle on an approach then.
Once that architectural decision is made, it’s actually a relatively straightforward feature to introduce (being safety critical will need robust testing though).

Regards,

James

**Comment by auturgy** [comment]
Matt: that would be useful (good opportunity to factor out some duplicated code and provide future flexibility), but perhaps scope creep in the context of this specific problem. Dev call topic :)

Regards,

James

**Comment by eengelgau** [comment]
Hi James, great and thanks so much to the group for taking this up!

I can supply our SATS-MINI ATS systems if someone would like to test with this, just let me know.  Were here to help.

-Gene

**Comment by khancyr** [comment]
We already have multiple way to get input on Pins, so we should reuse.
I think that AFS shouldn't enable by default as the configuration can be tricky.
Maybe an Companion computer/external input class where we can have input from pin for feedback would be a better way.

**Comment by Pedals2Paddles** [comment]
A PR with scope creep?  I wouldn't have it any other way :+1: 

I'm actually leaning towards not using AFS for this purpose. The chute library already handles cutting the motors and logging.  So probably best to route the inputs to the chute library functions and let do its thing.

_If PWM input can be used outside of the existing sbus/spektrum/ppm RC input_, then an external parachute controller with PWM output can work with ArduPilot today with no changes needed. `CHx_OPT` for parachute release (22)
`CHUTE_ENABLED` for enabled (1)
`CHUTE_DELAY_MS` for zero (0) to stop the motors immediately.
This will stop the motors and log it as a chute release.  It's going to try triggering an output which isn't needed. Some changes to the `chute_type` parameter would eliminate that unnecessary triggering.  This is probably the fast and easy win for external chute controller compatibility.

For an external controller that provides a 5v or ground rather than PWM, that is will be a feature add since there is no such path into parachute or AFS now.

**Comment by Skycatpro** [comment]
Hi guys, I'm Henri from Skycat.pro and have been discussing this topic with Gene for a while. I have one old wish which perhaps can be implemented as well: Continue logging after the parachute release.
Randy thought this feature some years ago and may remember challenges and requirements.

When its time for the aerial testing period, I can participate in that.

**Comment by khancyr** [comment]
@Skycatpro,

Hello,
It is better to open another thread for your addition. The discussion here is around how to implement simply the pwm input for external parachute trigger.
About your request, I am pretty sur it was done some time ago and should already be in copter4.0. If that isn't the case it could be done simply and I could share how to do it. But let's speak about that on another thread.

**Comment by tridge** [comment]
we discussed this on todays dev call and decided we would add BTN parameters equivalent to RCn_OPTION, so any RCn_OPTION can be triggered by a button

**Comment by peterbarker** [comment]
On Mon, 13 Jan 2020, Henri wrote:

> well: Continue logging after the parachute release.

This should already be the case - at least for 15 seconds.

Let us know if it doesn't do that.

**Comment by eengelgau** [comment]
Hi All, I wanted to check if this is underway now and when there might be a version available for testing? The customer is looking forward to having this feature addressed so rotors can stop properly when the parachute ejects.

-Gene

**Comment by Skycatpro** [comment]
> On Mon, 13 Jan 2020, Henri wrote: well: Continue logging after the parachute release.
> This should already be the case - at least for 15 seconds. Let us know if it doesn't do that.

Peter, I do! 
I ordered another smaller frame and install latest FW to it. That craft can be risked with the prerelease version tests as well. The large test frame is currently locked to FW what it was last summer or so.

**Comment by peterbarker** [comment]
On Fri, 17 Jan 2020, Henri wrote:

>       On Mon, 13 Jan 2020, Henri wrote: well: Continue logging after
>       the parachute release.
>       This should already be the case - at least for 15 seconds. Let
>       us know if it doesn't do that.
> 
> Peter, I do!

Uh.... that was kind of an inconclusive answer.  Are you saying that that 
logging *doesn't* continue?

> I ordered another smaller frame and install latest FW to it. That craft can

Great!

> be risked with the prerelease version tests as well. The large test frame is
> currently locked to FW what it was last summer or so.

Be very, very wary of flying code that old.  At the least you will want to 
familiarise yourself with the release notes of the Copter releases in that 
series.  There are been some absolutely critical safety issues fixed.

**Comment by peterbarker** [comment]
On Fri, 17 Jan 2020, eengelgau wrote:

> Hi All, I wanted to check if this is underway now and when there might be a
> version available for testing? The customer is looking forward to having
> this feature addressed so rotors can stop properly when the parachute
> ejects.

I'm not sure Matt is charging on with this any more.  We did decide on a 
different path vs what Matt was implementing.

I don't have a chute here.  If Matt doesn't want to continue and someone 
can send me something suitable for a 250-sized quad I can have a play.

> -Gene

Yours,
-- 
Peter Barker                          |   Programmer,Sysadmin,Geek.
pbarker@barker.dropbear.id.au	      |   You need a bigger hammer.
:: in what circumstances would you want reverse thrust for takeoff? --tridge

**Comment by khancyr** [comment]
A chute is optional for testing, we just need something visual like led or servo plug on chute output and trigger the code on ground without propellers to see the result. That should also validate the continous log.

**Comment by Pedals2Paddles** [comment]
I think the solution proposed in the last dev call is far more useful and all encompassing than this.  So I'm closing this, but feel free to keep discussing the topic.

**Comment by eengelgau** [comment]
Hi Matt, Is there another PR / branch being worked on where the flight termination (or ability to do it via external PWM) will be implemented?  We'd like to follow that.

-Gene

**Comment by Pedals2Paddles** [comment]
Not that I know of yet.

**Comment by eengelgau** [comment]
Ok, I'll check back from time to time to see when this update may be moving forward so we can follow it.

-G

**Pull request closed without merging**
