### PR TITLE
Return id of max empty compass state when PRIO id is 0

### PR DESCRIPTION
**Pull request by bugobliterator**
This fixes the issue of needless parameter swapping that occurs when PRIO_ID and DEV_ID both are zero for more than 1 devices. This issue did not create any bad behaviour except for extraneous FRAM writes.

### CODE REVIEW

**Comment by tridge** [comment]
I think this may expose an additional bug in Compass::configured(). It does this:
```
    StateIndex id = _get_state_id(Priority(i));
    // exit immediately if dev_id hasn't been detected
    if (_state[id].detected_dev_id == 0) {
        return false;
    }
```
we now could end up indexing into _state[] with an out of range value

**Comment by bugobliterator** [comment]
> I think this may expose an additional bug in Compass::configured(). It does this:
> 
> ```
>     StateIndex id = _get_state_id(Priority(i));
>     // exit immediately if dev_id hasn't been detected
>     if (_state[id].detected_dev_id == 0) {
>         return false;
>     }
> ```
> 
> we now could end up indexing into _state[] with an out of range value

No, actually _state is of size MAX_COMPASS_INSTANCE+1 the extra state is defined for exactly these kinds of circumstances. This additional state is used as a replacement for unused/undefined compasses.

**Comment by Hwurzburg** [comment]
Per request, I tested this....a build off master with my one compass system, would alternatively switch compass 2 and 3 ODI offsets, etc each boot....loaded this PR directly....multiple reboots, they remain the same
compassjump

**Comment by tridge** [comment]
thanks for testing Henry!

**Comment by rmackay9** [comment]
@Hwurzburg, no big pressure of course but if you have an easy way of testing this could you give Copter-4.0.4-rc2 a test just to ensure it resolves the problem?  It certainly should but I'd just like to be 100% sure.

**Comment by Hwurzburg** [comment]
Unfortunately, I can't seem to get it to flop back and forth now on older firmware....tried Copter 4.0.3, and tried a later version of master before the commit which was doing it before repeatably every boot...so do not have a control to compare against any more....maybe @andyp1per  could give it a shot...sorry

**Comment by andyp1per** [comment]
My goto test - autotune - is now having other issues, pids are not saving :(

**Comment by rmackay9** [comment]
@Hwurzburg, np, thanks for giving it a try.  I'm going to assume it's fixed if nobody can reproduce the issue.

**Pull request merged**
