### PR TITLE
Tools: add psutil used by kill_tasks_psutil for sim_vehicle.py

### PR DESCRIPTION
**Pull request by tajisoft**
If you kill one while using multiple instances, the other MAVProxys will lose connectivity. This is because an ImportError occurred and kill_task_pkill function was called when killing the task.
I have tested in Ubuntu18/20 on WSL/WSL2. I think it should work fine in native ubuntu.

No psutil
image

After install psutil
image

### CODE REVIEW

**Comment by magicrub** [comment]
Nice one! What do you think @peterbarker

**Review by khancyr — CHANGES_REQUESTED** [review]
Comes from https://github.com/ArduPilot/ardupilot/pull/13405
From the discussion, old psutil won't help so it need some version restrictions.
Previous PR https://github.com/ArduPilot/ardupilot/pull/13681

It might be good to add psutil on all install scripts we got for easier management.

The commit message need "Tools:" at the start

**Comment by tajisoft** [comment]
@khancyr Thank you for your comment.

> From the discussion, old psutil won't help so it need some version restrictions.

Here is my pip freeze outputs on Ubuntu20/WSL2.
```
attrs==19.3.0
Automat==0.8.0
beautifulsoup4==4.8.2
blinker==1.4
certifi==2019.11.28
chardet==3.0.4
Click==7.0
cloud-init==20.2
colorama==0.4.3
command-not-found==0.3
configobj==5.0.6
constantly==15.1.0
cryptography==2.8
cupshelpers==1.0
cycler==0.10.0
dbus-python==1.2.16
decorator==4.4.2
defer==1.0.6
distro==1.4.0
distro-info===0.23ubuntu1
entrypoints==0.3
future==0.18.2
gcovr==4.2
html5lib==1.0.1
httplib2==0.14.0
hyperlink==19.0.0
idna==2.8
importlib-metadata==1.5.0
incremental==16.10.1
intelhex==2.3.0
Jinja2==2.10.1
jsonpatch==1.22
jsonpointer==2.0
jsonschema==3.2.0
keyring==18.0.1
kiwisolver==1.0.1
language-selector==0.1
launchpadlib==1.10.13
lazr.restfulclient==0.14.2
lazr.uri==1.0.3
lxml==4.6.2
macaroonbakery==1.3.1
MarkupSafe==1.1.0
matplotlib==3.1.2
MAVProxy==1.8.30
more-itertools==4.2.0
netifaces==0.10.4
numpy==1.17.4
oauthlib==3.1.0
olefile==0.46
pexpect==4.8.0
Pillow==7.0.0
protobuf==3.6.1
psutil==5.8.0
ptyprocess==0.6.0
pyasn1==0.4.2
pyasn1-modules==0.2.1
pycairo==1.16.2
pycups==1.9.73
pygame==2.0.1
PyGObject==3.36.0
PyHamcrest==1.9.0
PyJWT==1.7.1
pymacaroons==0.13.0
pymavlink==2.4.14
PyNaCl==1.3.0
pyOpenSSL==19.0.0
pyparsing==2.4.6
pyRFC3339==1.1
pyrsistent==0.15.5
pyserial==3.4
python-apt==2.0.0+ubuntu0.20.4.1
python-dateutil==2.7.3
python-debian===0.1.36ubuntu1
pytz==2019.3
PyYAML==5.3.1
requests==2.22.0
requests-unixsocket==0.2.0
scipy==1.3.3
SecretStorage==2.3.1
service-identity==18.1.0
simplejson==3.16.0
sip==4.19.21
six==1.14.0
soupsieve==1.9.5
ssh-import-id==5.10
systemd-python==234
Twisted==18.9.0
ubuntu-advantage-tools==20.3
ufw==0.36
unattended-upgrades==0.1
urllib3==1.25.8
wadllib==1.3.3
webencodings==0.5.1
wxPython==4.0.7
zipp==1.0.0
zope.interface==4.7.1
```
The psutil==5.8.0 was installed in my ubuntu. As this comment 4.0.0 is minimum? https://github.com/ArduPilot/ardupilot/pull/13405#issuecomment-620961759

> It might be good to add psutil on all install scripts we got for easier management.

I think kill_tasks_psutil function is only for Ubuntu(linux) right? If so I think there is no need to add in all. How do you guys think?

**Review by khancyr — COMMENTED** [review]
Could you just move it to SITL_PKGS line 101 ?
I guess it should work on macos and windows too but need testing so it will be for another PR.

I am good with this.

**Comment by amilcarlucas** [comment]
Needs to pass CI tests before it can be merged. Can you fix that?

**Comment by tajisoft** [comment]
@amilcarlucas Thank you for comment. I rebased this branch and I think it is ok now.

**Review by khancyr — APPROVED** [review]

**Review by peterbarker — APPROVED** [review]

**Comment by peterbarker** [comment]
Merged, thanks!

**Pull request merged**
