### PR TITLE
Remove CLI

### PR DESCRIPTION
**Pull request by peterbarker**
This removes the ArduPilot CLI.

This is not to be confused with the NuttX `nsh`!  `nsh` is not going anywhere.

The CLI, if enabled as part of compilation (not the default) allowed testing of various parts of the code - and log download.  The testing is now available through MAVLink, and log download in this manner has been deprecated for many years.

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
Yay!!

**Comment by lucasdemarchi** [comment]
AP_Menu is now unused, as well as the MENU_FUNC defines, no?

**Comment by peterbarker** [comment]
@lucasdemarchi Sadly, no.  I thought so too, then discovered some of the examples use menus.

MENU_FUNC should be gone for the most part, too.  I just found a straggler in Tracker now that you pointed it out :-)

**Comment by lucasdemarchi** [comment]
> @lucasdemarchi Sadly, no. I thought so too, then discovered some of the examples use menus.

If it's only examples we could hide the define somewhere so nobody tries to use it again :)

**Comment by rmackay9** [comment]
Great to see this.  I'm keen this goes in for it's own reasons but also it will conflict with another PR i'm about to raise.. so this one needs to go in first.

**Comment by rmackay9** [comment]
Merged!  One little thing that I've noticed is the AP_Menu is likely still in the make.inc file..

**Comment by OXINARF** [comment]
@peterbarker If you ever find yourself with nothing to do, removing AP_Menu entirely would welcome too I think. The examples shouldn't be important enough that they can't have a simple modification to remove AP_Menu.

**Pull request merged**
