### PR TITLE
Add support for EagleTree Airspeed v3 sensor

### PR DESCRIPTION
**Pull request by peterbarker**
Closes https://github.com/ArduPilot/ardupilot/issues/8288

Yet to be seen if this is actually a useful in-flight sensor.

Needs to be sent on a flight with a second airspeed sensor so we can directly compare the results.

Adds a simulator the the sensor, too.

### CODE REVIEW

**Comment by peterbarker** [comment]
image

(that's just with a param-set of ARSPD2_TYPE to 14)

**Comment by WickedShell** [comment]
Are you aware they are out of business and you can no longer buy the sensor
from them?

If there is an active clone market, or a strong push from a partner, I
could see it, but I'm no longer sure that it's warranted to add the driver
for something that is no longer made, since we will carry it forward
forever...

**Comment by peterbarker** [comment]
This company did go out of business, and apparently the sensors suffer from thermal drift rather badly.

**Comment by WickedShell** [comment]
Okay given those two bits of info I'd definitely nominate closing this, but
probably worth running through a dev call first.

**Comment by auturgy** [comment]
Why don’t we close this? It’s an obsolete sensor with measured poor performance that is no longer available

**Pull request closed without merging**
