### PR TITLE
Plane: fixed misspellings of 'transition'

### PR DESCRIPTION
**Pull request by Hwurzburg**
NFC
while fixing spelling appearing in wiki, just fixed them all

### CODE REVIEW

**Review by IamPete1 — APPROVED** [review]
Well this is embarrassing....  I think theses are all me.

**Comment by Hwurzburg** [comment]
@peterbarker done

**Review by khancyr — APPROVED** [review]
LGTM

**Comment by magicrub** [comment]
merged, thanks!

**Pull request merged**
