### PR TITLE
Global: Change to boolean value

### PR DESCRIPTION
**Pull request by muramura**
The bit type is a boolean.
0 and 1 are integer values.
Change to a Boolean value.

### CODE REVIEW

**Review by khancyr — APPROVED** [review]
Looks ok. doesn't change anything

**Review by magicrub — APPROVED** [review]
Lgtm. Needs a rebase.

**Review by rmackay9 — APPROVED** [review]

**Review by tridge — APPROVED** [review]

**Comment by tridge** [comment]
has a conflict

**Comment by rmackay9** [comment]
If you can rebase this we will merge it, thanks

**Comment by muramura** [comment]
@rmackay9 san.  I would change.

**Comment by muramura** [comment]
I changed it.

**Pull request merged**
