### PR TITLE
Rover: Loiter in HOLD mode for boat.

### PR DESCRIPTION
**Pull request by tajisoft**
I think boats need to behave like Loiter in HOLD mode.

### CODE REVIEW

**Comment by IamPete1** [comment]
why not just use loiter?

**Comment by tajisoft** [comment]
@IamPete1 I think you are right. But boat also has HOLD mode. I think HOLD = stay in same location.

**Comment by IamPete1** [comment]
@tajisoft is there any functionality this adds apart from helping a un - intuitive mode name? Maybe we could add the functionality in another way. We went over this with sailboat and it was decided hold mode should not use any throttle. 

Maybe hold mode could be renamed to STOP mode, I think this would be a more intuitive name, but quite a big change to make in all documentation and GCS's.

**Comment by rmackay9** [comment]
Yes, I don't think Hold mode should be trying to Hold position.  Perhaps "Hold" is an unfortunate name but that's where we are..

**Comment by tajisoft** [comment]
Thank you for your feedback. I was misunderstanding.

**Comment by rmackay9** [comment]
@tajisoft, by the way, Coverity (an autottest) turned up an issue in Rover to do with Loiter. https://github.com/ArduPilot/ardupilot/issues/10188

**Pull request closed without merging**
