### PR TITLE
SET_SENSORS_OFFSETS support for third compass

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
Replacement for #3739. I sacrified an insufficient amount of chicken blood to the github rebase/squash/force gods. Hence, I had to start all over.

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
https://github.com/lucasdemarchi/ardupilot/tree/review/pr-3740 with indentation fixed and commits split per vehicle. 

@DonLakeFlyer are you going to send a PR to mavlink to update the docs?

**Comment by DonLakeFlyer** [comment]
Yes, once this is merged in

**Comment by DonLakeFlyer** [comment]
https://github.com/mavlink/mavlink/pull/522

**Comment by rmackay9** [comment]
Just a couple of minor things:
1. we normally don't use "int" but instead uint8_t (or something like that)
2. separate commits per vehicle.
I think I can probably make those minor fixes as I merge but for the future.

**Comment by DonLakeFlyer** [comment]
Thanks Randy. I didn't know that.

**Comment by lucasdemarchi** [comment]
@rmackay9 that's what I did and pushed the branch linked above.

**Comment by lucasdemarchi** [comment]
and now I see you already noticed that :)

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (409/400 (102%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext7.iad.github.net ([192.30.252.198]:54059 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1afmMN-000af1-Ub
	for yann.dupuy@zyapps.com; Tue, 15 Mar 2016 11:38:00 +0100
Date: Mon, 14 Mar 2016 16:59:43 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1457999983;
	bh=lyCGLWAtobCNq0RZnjCIhK1+SJaVPbfJyDLbC3BpHw0=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=B4yprDXMPtqE96NULMDu4j+sstnHdgNq4alu83/IP51/2B58oI15iQ2oPzx2WxJ+q
	 4k9tRrhsofO3qypx7tlBqqBja/3EmidtqzBaZd7XnOgtTVwUuxnMcoT7y10gTahsZ3
	 1ncPKdnTjN4Pf1YPTkhxPnB5RxqvEITEushd6mR4=

**Comment by DonLakeFlyer** [comment]
Do you want me to make the int changes?

**Comment by lucasdemarchi** [comment]
it would be good... I did it here, but I don't have a board handy with 3 compasses to test on. Here is my branch:

https://github.com/lucasdemarchi/ardupilot/commits/third-compass

**Comment by DonLakeFlyer** [comment]
I'll update it and retest on my PixRacer.

**Comment by DonLakeFlyer** [comment]
I've been trying to test this with my PixRacer on 3.4. So far no luck. QGC cal complains about inconsistent compasses, can't arm. So maybe something wrong with the cal there. Tried MP onboard cal. Couldn't quite make sense of that. I guess it calibrates each compass one at a time. Then various beeps and I think it finished, but no real indication of that. I think I went all the way through it. When I try to fly, it complains about safety switch (which there isn't one). So kind of stuck being able to verify the change.

**Comment by DonLakeFlyer** [comment]
Also FYI: I can 3 compass cal this on PX4 stack without any problems and it flies fine. So the vehicle itself it good from a hardware standpoint. At this point I can fly it on ArduPilot even using MP to cal.

**Comment by OXINARF** [comment]
@DonLakeFlyer If you don't have a safety switch I believe you need to set BRD_SAFETYENABLE to 0.

**Comment by DonLakeFlyer** [comment]
Thanks. Will try that. First step will be to get it flying using MP settings just to make sure it works. Then I'll retry with a QGC cal to see what happens.

**Comment by DonLakeFlyer** [comment]
BRD_SAFETYENABLE gets me past the safety switch thing. But I can't get past prearm: inconsistent compasses even with the onboard compass cal I did with MP.

**Comment by DonLakeFlyer** [comment]
I'm not totally sure I did the Mission Planner onboard compass cal right. It's not very clear what you are supposed to do. As far as I can tell it calibrates each compass individually, since only one id percentage changed at a time. And then at the end you get a different set of beeps so you know it's done, and all ids went to 100%? Wasn't clear if I needed to click "Accept"? Which I did.

Is there any way to debug this "Inconsistent compass thing" to figure out what is really causing it to say that?

**Comment by OXINARF** [comment]
@DonLakeFlyer I don't know much about that, so I can't help. Maybe talk to @tridge? He's been working in Pixracer lately.

**Comment by lucasdemarchi** [comment]
@DonLakeFlyer have you increased the fitness? Depending on your frame and where you did the calibration it's very difficult to pass with default fitness value. Thinking about the UI for an onboard compass Cal, it should be possible to set this value in the same screen.

All compasses are calibrated at the same time (actually you can tell it to calibrate one sensor, but I don't think MP is doing that). When I do the onboard calibration I use mavproxy. Just call "magcal start" And "watch *progress*". You will see the progress for all sensors. @guludo is working on this onboard calibration to give more feedback to the GCS. Next step would be to implement it in QGC

**Comment by lucasdemarchi** [comment]
Applied. @DonLakeFlyer could you send the corresponding patch to the mavlink repository?

Thanks.

**Pull request closed without merging**
