### PR TITLE
AP_MotorsMulticopter: Use same throttle value used by motors

### PR DESCRIPTION
**Pull request by lthall**

### CODE REVIEW

**Comment by R-Lefebvre** [comment]
Is this a bug in AC3.4 that must be fixed before release?

**Comment by rmackay9** [comment]
Merged, thanks!

**Comment by R-Lefebvre** [comment]
Would have been nice to understand this a bit better to figure out if it affects helicopters. I noticed the fix is for multirotor only.

**Comment by OXINARF** [comment]
@R-Lefebvre There's no hover learn feature in helicopters, so this wouldn't affect it.

**Comment by R-Lefebvre** [comment]
Ok, thanks.  I'll have to look at this situation more closely.  I understand that in Stab and Acro, we have a user defined throttle curve. But I'm not sure how this works out in the auto-throttle modes, not learning hover throttle to have a basis for the throttle output?  I'm pretty sure this used to be done, because I remember having to fix a bug on this 1-2 releases ago.

**Pull request closed without merging**
