### PR TITLE
iampete interp gains

### PR DESCRIPTION
**Pull request by kd0aij**
@IamPete1 Could you take a look at this to see if I merged it correctly from your branch gain_interp_quad?
Assuming the wind estimation won't be good enough for flying around in Qmodes, I retained my gain scaling code, but it's not called at present. I'd like to pull your method into the renamed tailsitter_gain_scaling() method in order to make the code easier to read, if possible.

### CODE REVIEW

**Comment by IamPete1** [comment]
I might have a go at rebasing my branch and see if I can tidy it in to a function or something

**Comment by kd0aij** [comment]
was hoping to save you the trouble of rebasing, but I can see how this branch 
might not save you any time :)
It does fly, but there are some oscillations with the RF8 Stryker_quad

**Comment by IamPete1** [comment]
I also want to have a look at the yaw damper as Tridge suggested

**Comment by kd0aij** [comment]
replaced by #9167

**Pull request closed without merging**
