### PR TITLE
Switch to USB ID 0x1209/0x5741 for non-composite devices

### PR DESCRIPTION
**Pull request by tridge**
This ID has now been allocated by pidcodes. This finally gets us away from using the ST IDs

### CODE REVIEW

**Comment by tridge** [comment]
this works well in MissionPlanner. It doesn't yet work well for QGC. I've asked @DonLakeFlyer  to have a look at it

**Comment by magicrub** [comment]
woah! Doesn't work for QGC but lets merge it now anyway? When you say "doesn't work well", does that mean if you're running QGC then you can't update anymore?

**Comment by DonLakeFlyer** [comment]
Putting this here as well:

This: https://github.com/mavlink/qgroundcontrol/pull/8204 should fix the new VID/PID autoconnect problem. I have not been able to test this. I am living out of a camper van for the next month and I don't have all my stuff with me. So if someone else could verify that auto connect works once this goest through. That would be super helpful. 

Take me a little longer to update driver. Maybe tomorrow. I'm not sure who this impact firmware flashing yet.

**Comment by rmackay9** [comment]
@DonLakeFlyer,

We are planning to release this change with Copter-4.0.3 which will start beta testing today.  It normally takes between 3 to 7 days to get a point release out.  Will stable QGC be able to handle this?

**Comment by DonLakeFlyer** [comment]
> We are planning to release this change with Copter-4.0.3 which will start beta testing today. It normally takes between 3 to 7 days to get a point release out. Will stable QGC be able to handle this?

@rmackay9 Daily builds added this a few weeks ago. New Stable will be out soon.

**Comment by rmackay9** [comment]
@DonLakeFlyer, great thanks.  After a bit of testing with QGC we decided to skip the change for the upcoming Copter release (4.0.3) and instead include it in 4.0.4.

**Pull request merged**
