### PR TITLE
SRV_Channel: Changing servo functions are now reboot required

### PR DESCRIPTION
**Pull request by WickedShell**
Changing from a PWM function to GPIO now requires a reboot.

This was noticed as part of being very confused why relay pins were suddenly invalid. There also doesn't seem to be any documentation available that explains this to users. I resolved it by looking at the code and tracing the PR history. Things like: https://ardupilot.org/copter/docs/common-relay.html need an update.

### CODE REVIEW

**Comment by nkruzan** [comment]
Hello, there is a small note on the relay page explaining that a reboot is needed. 
Screenshot_2022-03-02_13-41-41

**Comment by WickedShell** [comment]
Sorry I should have been more clear. I don't see anything on the servo page talking about setting SERVOx_FUNCTION to -1 as a GPIO if you are trying to use a relay. The PR here is just reflecting that changing to GPIO requires a reboot as far as I can tell, but maybe that's actually related to the relay setup needing to reinitialize? I'll check it out real quick.

**Comment by nkruzan** [comment]
Ok, when we get nailed down what need updated in wiki, I'm happy to submit the changes. I was going to add a reboot needed note to the page you suggested, but saw it was already there.

**Comment by WickedShell** [comment]
> Ok, when we get nailed down what need updated in wiki, I'm happy to submit the changes. I was going to add a reboot needed note to the page you suggested, but saw it was already there.

The page I linked needs to talk about `SERVOx_FUNCTION -1`for the aux outputs on IOMCU processors, and for any of the normal PWMable pins on a non IOMCU processor

**Comment by nkruzan** [comment]
@peterbarker has added pr for the documentation issue. https://github.com/ArduPilot/ardupilot_wiki/pull/4191

**Review by peterbarker — APPROVED** [review]

**Comment by peterbarker** [comment]
Merged, thanks!

**Pull request merged**
