### PR TITLE
MAVLink: added link latency correction function

### PR DESCRIPTION
**Pull request by tridge**
This adds a link lag measurement estimate for correcting for clock offset and transport lag for vision messages

### CODE REVIEW

**Comment by tridge** [comment]
@rmackay9 fixed

**Comment by fnoop** [comment]
This is a really exciting development!  Does this assume that the sender already has already synchronised timestamps with TIMESYNC, and that the sender also accounts for sensor latency?  So this assumes that the minimum offset it sees is the actual link latency and applies a correction to the incoming message based on that?
Wait that doesn't make sense.  Is this assuming that the incoming timestamps are GPS based, and it's trying to guess the latency based on the difference in GPS time between the two devices and use that to correct the incoming message timestamp?

**Comment by rmackay9** [comment]
@fnoop, I'm not an expert on how this works but the idea is that it does not require the SYSTEM_TIME or TIMESYNC messages.

Now that you mention it, I think we maybe got it wrong with the set-time PR because we were trying to use SYSTEM_TIME when we should have been using TIMESYNC.  The problem we face is that we have very few people around who understand how this should work with ROS.

At the moment when we have ROS connected, we are seeing, "wrong FCU time" messages.  Maybe we should move this discussion to either the vision-projects gitter chat or [this discussion](https://discuss.ardupilot.org/t/vision-position-estimate-not-appearing-in-qgroundcontrol).

**Comment by rmackay9** [comment]
Merged, thanks!

**Comment by chobitsfan** [comment]
hi @tridge 
offboard_usec should be a time since boot? or it can be a unix time?
thank you

**Pull request merged**
