### PR TITLE
AP_Marvelmind example: correct printf usage

### PR DESCRIPTION
**Pull request by khancyr**

### CODE REVIEW

**Comment by khancyr** [comment]
In fact, it was failing to compiling on gcc 5.4 on another board. 
I didn't think about where we want the ouput to be... the problem comes from the #if HAL_OS_POSIX_IO ... I don't have the hardware to test.

About f6687a2, I look at other and it wasn't here too ... pretty big mess. 

Maybe removing the #if HAL_OS_POSIX_IO is enough and no need to use hal.console

**Comment by OXINARF** [comment]
> In fact, it was failing to compiling on gcc 5.4 on another board.

What board?

> About f6687a2, I look at other and it wasn't here too ... pretty big mess.

It's not needed everywhere, depends if the code will initialize the UART or not. It's also only needed for PX4 because the USB console in NuttX can't be initiliazed until USB is connected.

> Maybe removing the #if HAL_OS_POSIX_IO is enough and no need to use hal.console

Yeah, I don't know why that macro is needed, AFAIK `printf` is in the C/C++ standards, it doesn't depend on POSIX - if it does something is another question.

**Comment by dgrat** [comment]
Our printf function should anyway beeing replaced. Currently, there is no check whether the parameters make sense at all. Would be better the compiler would do that.

**Comment by khancyr** [comment]
Fixed by https://github.com/ArduPilot/ardupilot/pull/7475

**Pull request closed without merging**
