### PR TITLE
AP_NavEKF3: delete \n from the log using gcs().send_text

### PR DESCRIPTION
**Pull request by tatsuy**
Delete the new line from IMU logs with enabling EKF3
ekf2

ekf3

### CODE REVIEW

**Comment by muramura** [comment]
I think, a message that is doing the same writing I think that you can change it together if there are other.

**Comment by tatsuy** [comment]
@muramura Thank you for your advice.
These messages I fixed are always displayed when ardupilot boot.
I decided to fix only one that I mind because this PR is not important.

**Comment by muramura** [comment]
@tatsuy san. OK...
I will change about the following and PR.

ardupilot/ArduCopter/ekf_check.cpp
ardupilot/APMrover2/commands_logic.cpp
ardupilot/libraries/AP_Camera/AP_Camera.cpp
ardupilot/libraries/AP_GPS/AP_GPS_SBP2.cpp
ardupilot/libraries/AP_HAL_PX4/RCInput.cpp
ardupilot/libraries/AP_Soaring/AP_Soaring.cpp
ardupilot/libraries/AP_Soaring/Variometer.cpp

**Comment by rmackay9** [comment]
Merged, thanks!

**Pull request merged**
