### PR TITLE
AP_CANManager: remove MPPT_PacketDigital parameter description

### PR DESCRIPTION
**Pull request by shiv-tyagi**
This solves the issue #19532. @rmackay9 If you could please review it.

### CODE REVIEW

**Comment by rmackay9** [comment]
Yes, looking good thanks.

We seem to have this stray HAL definition as well that can go, "HAL_PERIPH_ENABLE_BATTERY_MPPT_PACKETDIGITAL"

**Review by rmackay9 — APPROVED** [review]

**Review by hendjoshsr71 — APPROVED** [review]
Generally, we split up commits by library so 4 commits at the moment.

If you need help with that let me know.

**Comment by shiv-tyagi** [comment]
@hendjoshsr71 I have split the commits. Please check if I did it correctly.

**Comment by rmackay9** [comment]
Merged, thanks for this!

**Pull request merged**
