### PR TITLE
Init motor pins for correct initialization of some ESCs

### PR DESCRIPTION
**Pull request by huhen**
In a bundle of the flight controller (KakuteF7) and the esc (Tekko32_F3_C_Multi), with the standard bootloader, the esc did not initialize, however, if restart the board after starting the firmware, everything works. During the experiments, I came to the conclusion that during the operation of the loader, the pins must be pulled to the ground.

### CODE REVIEW

**Comment by amilcarlucas** [comment]
Should I backport this to 4.0 ?

**Comment by huhen** [comment]
As I understand it, this is not tied to the firmware version, this only applies to the bootloader.

**Comment by tridge** [comment]
I've updated your PR branch (master, please use a different branch name in future) with a fix for commit msg and add the bl binaries
I've tested on a KakuteF7, this is ready to merge when it passes CI

**Review by tridge — APPROVED** [review]

**Comment by peterbarker** [comment]
It passed CI.  22 days ago....

Perhaps we need a `MergeAfterCI` tag....

**Pull request merged**
