### PR TITLE
Copter: support for arming and disarming using an auxsw

### PR DESCRIPTION
**Pull request by peterbarker**
See http://discuss.ardupilot.org/t/motor-arm-disarm-with-a-radio-switch/11403/10

### CODE REVIEW

**Comment by lvale** [comment]
bad idea....If someone flicks the switch than it's dead. If the objective is to stop motors then use Option 31.

**Comment by peterbarker** [comment]
Just to be clear; the craft must think it is landed before it will disarm - in the same way that rudder-disarming works.  Flicking the switch while the vehicle is in free flight - while not a good idea! - will not necessarily kill the vehicle (you would need a false-positive for is-landed too).

**Comment by R-Lefebvre** [comment]
I'm quite cool to this idea.

I read the relevant thread, and, I don't see how this makes things better, while possibly making things quite a bit worse.

The user has asked us to not ask why he wants this.  I don't think that is an acceptable request, especially in the case where the code is being modified in a safety-critical area.

First, comparison to other systems like Cleanflight, are irrelevant, because our "arming" is quite different from there's.  For us, arming isn't just start/stopping the motors, it is also registering a whole bunch of other navigation and FS features.

There's so many problems here.

First, the implementation in this PR will not allow quick disarming in the case of an inverted landing.  That is what Interlock/Estop is for.

If the PR is amended to allow in-flight disarming, it would then create a scenario where the user could disarm in flight, and then immediately re-arm.  This would result in Home being reset to an in-air location.

Now, the requester here might understand the risks and/or not care.  But we are creating a feature that will lead to a lot of problems for others.  It's going to increase our support load.  And for what reason?  What is the good reason to allow this?

I'm sorry, but at this point, I am quite against this.

**Comment by rmackay9** [comment]
I don't mind this change actually.  The only thing that I'm not sure about is whether the disarm should perhaps be changed to a forced disarm.  I.e. the landing check shouldn't need to be true.  It should act more like the emergency-stop / interlock (as Rob has suggested).

**Comment by R-Lefebvre** [comment]
I'm still waiting for a valid use-case for why we would want to allow this.  "Just because and I'm not going to tell you why" and "all the cool kids are doing it" don't seem like valid reasons to me.  This is a safety critical change.

**Comment by peterbarker** [comment]
@rmackay9 I've removed the requirement for landing to be complete for the disarm to occur.  This becomes a kill-my-copter switch.

@R-Lefebvre 

Valid use cases... "I want to arm my copter quickly"! Possibly the ultimate in instant-gratification requirements, the delay required for rudder-arming irks some people.  I was somewhat sceptical of this as an interface, but having used it I actually quite like it.

In terms of setting home in-flight, I'm pretty sure we already have this problem if you take off in stabilize without a position lock and get a position lock while flying.  We should also make a note that disarming in-flight is not recommended.

This is also an *option* you can have on your switches; nobody is making anybody use it.  Providing a more familiar arming mechanism for potential converts is a good thing.

**Comment by OXINARF** [comment]
My opinion is that this is a very dangerous addition in its current form. Having a switch to do arming/disarming is fine, but it should behave in the same way as the stick gesture.
With the current implementation someone will look at the options, see a ArmDisarm option, think it behaves the same way as the stick gesture and use it, potentially having an accident either with instant arming or disarming.

If a zero-wait arming is desired I think a parameter should be added to make the arm delay configurable.

**Comment by R-Lefebvre** [comment]
Peter, I always put safety before expediency.  People wanted push button start on their cars, and then look what happened.

Question: if a person flicks the Arm switch with the throttle not at zero, will we let it arm?

**Comment by peterbarker** [comment]
On Wed, 5 Oct 2016, Robert Lefebvre wrote:

> Peter, I always put safety before expediency. People wanted push button
> start on their cars, and then look what happened.

Ummm.  What did happen?  AFAIK that *is* a feature on modern cars?!

> Question: if a person flicks the Arm switch with the throttle not at zero,
> will we let it arm?


Depends on how the user has configured their vehicle.  Arming checks must 
pass, just like with the stick gesture.

**Comment by R-Lefebvre** [comment]
A lot of people died and Toyota was sued, is what happened.  And they continue to die.

I don't think current arming checks check for the throttle to be low.  Because the gesture ensures that it is low.

**Comment by R-Lefebvre** [comment]
Ok, I looked, so it does check the throttle is down. Well, at least there's that.

**Comment by peterbarker** [comment]
On Wed, 5 Oct 2016, Robert Lefebvre wrote:

> A lot of people died and Toyota was sued, is what happened. And they
> continue to die.

Huh. CO poisoning.  That sucks.

> I don't think current arming checks check for the throttle to be low.
> Because the gesture ensures that it is low.

Nah, we check for throttle: 
https://github.com/ArduPilot/ardupilot/blob/master/ArduCopter/arming_checks.cpp#L772

**Comment by lvale** [comment]
If we combine this PR with this https://github.com/ArduPilot/ardupilot/pull/4891 it might easily get dangerous.....

**Comment by peterbarker** [comment]
On Sat, 29 Oct 2016, Luis Vale Gonçalves wrote:

> If we combine this PR with this #4891 it might easily get dangerous.....

I fail to see how.

They are both methods to arm the vehicle; the effects don't stack.

The only thing is that your switch will be in the disarmed position while 
your vehicle is actually armed.  You would need to move it to the armed 
state and then to disarmed to disarm using the switch at that point.  Also 
note that you don't need to "force arm" to get into this state - just 
arming from the GCS is sufficient (or rudder-arming, for that matter).

I *hope* people wouldn't generally use the "force-arm-from-gcs" option. 
It's really just there for when you would otherwise do "arm uncheck all\n 
arm throttle\n arm check all\n"

Having used this auxsw method to arm my quads - I'm not going back :-)

**Comment by geofrancis** [comment]
the arming by switch is normal on racing quads, i would prefer this method of arming on my little arducopter 250 but i would keep stick arming for larger machines.

**Comment by rmackay9** [comment]
Although we didn't get complete consensus I've pulled this into master.  I think it's an optional feature that's not enabled by default so it's less dangerous in that sense.

**Comment by ungerik** [comment]
What I don't get: it's OK to use the flight control sticks that are intended to do something else for the job, but it's not OK to use another switch that would be dedicated to just that one task? They are both just switches on the same device, open to the same user errors. The same safety measures could apply.

**Comment by peterbarker** [comment]
On Mon, 7 Aug 2017, Erik Unger wrote:

> What I don't get: it's OK to use the flight control sticks that are intended
> to do something else for the job, but it's not OK to use another switch that
> would be dedicated to just that one task? They are both just switches on the
> same device, open to the same user errors. The same safety measures could
> apply.

*shrug*.

No need to re-open the argument; the option is available on Copter's 
stable branch now :-)  Have fun, remember that while flying it is a "kill 
my copter" switch.

**Pull request closed without merging**
