### PR TITLE
Add support for the mRo X2.1-777, a new flight controller from Mayan …

### PR DESCRIPTION
**Pull request by pkocmoud**
…Robotics based on the x2.1 upgraded to a STM32F777 MCU

### CODE REVIEW

**Comment by auturgy** [comment]
Needs a different board ID, as 135 is taken (F35_Lightning). Suggest claiming a board ID as part of this PR (https://github.com/ArduPilot/Bootloader/blob/master/board_types.txt).

**Comment by auturgy** [comment]
No worries. Perhaps PR a number in this repo, and once merged we can then push it to get back in sync.

Regards,

James

**Comment by proficnc** [comment]
very nice!

**Comment by tridge** [comment]
nice! Is this all tested and ready to go in, or still a work in progress?
Do you want this board added to our auto-build for firmware.ardupilot.org?

**Comment by pkocmoud** [comment]
@tridge This is tested to be working but it should not be considered stable until I have more time running it. That said merging to master would aid me in the process. 

If the auto-build is not too much trouble then yes please.

**Comment by tridge** [comment]
@pkocmoud i've merged it and added it to the auto-build
builds should start appearing on firmware.ardupilot.org in an hour or so

**Pull request merged**
