### PR TITLE
Tools: scripts: uploader.py: update --identify option

### PR DESCRIPTION
**Pull request by kd0aij**
mention STM32F42XX_ERRATA document for 1M flaw
*** someone managed to buy some rev 1 chips recently ***

@peterbarker Is this what you meant?

### CODE REVIEW

**Comment by peterbarker** [comment]
Yep, this is what I had in mind - but a google for that document name didn't give me any hit. and I think we need that.

**Comment by kd0aij** [comment]
It's the second hit when I do a google search, but the URL is a bit long:
https://www.st.com/resource/en/errata_sheet/dm00068628-stm32f427437-and-stm32f429439-line-limitations-stmicroelectronics.pdf

**Comment by peterbarker** [comment]
On Thu, 13 Aug 2020, Mark Whitehorn wrote:

> 
> It's the second hit when I do a google search, but the URL is a bit long:
> https://www.st.com/resource/en/errata_sheet/dm00068628-stm32f427437-and-stm32f429439-line-limitations-stmicroelectronics.pdf

Maybe dm00068628 instead?

**Comment by kd0aij** [comment]
maybe "STM32F42XX Errata sheet sec. 2.1.10" would make more sense and also be searchable?
".pdf" shouldn't have been in there

**Comment by peterbarker** [comment]
On Thu, 13 Aug 2020, Mark Whitehorn wrote:

> maybe "STM32F42XX Errata sheet sec. 2.1.10" would make more sense and also be searchable?
> ".pdf" shouldn't have been in there

Yep!

Has this been tested on hardware?

**Comment by kd0aij** [comment]
a bit paranoid, aren't we?
```
$ ./Tools/scripts/uploader.py --identify
If the board does not respond within 1-2 seconds, unplug and re-plug the USB connector.
Attempting reboot on /dev/ttyS10 with baudrate=57600...
If the board does not respond, unplug and re-plug the USB connector.
Found board 9,0 bootloader rev 5 on /dev/ttyS10
Bootloader Protocol: 5
OTP:
  type: PX4
  idtype: =00
  vid: 000026ac
  pid: 00000010
  coa: 08pi9RjiVY1TK5CPiSvW8w6k11FsMF1R4vX9fS77WvG272BCFGI7MNzeMoja018JDlPn6XGNg9nOQ351M9huPycNAqZ3jNIoikrIk7ecVS/IK7Scrtt9XF7zRRlcTynIiRXglJCN4VSc3Ns3tvYdl0IM9ifufeCRyQGYoIDqpCU=
  sn: 005100243034510937383933
ChipDes:
  family: STM32F42x
  revision: 1
Chip:
  10076419 STM32F42x_43x rev1 (flawed; 1M limit, see STM32F42XX Errata sheet sec. 2.1.10)
Info:
  flash size: 1032192
  board_type: 9 (fmuv3)
  board_rev: 0
Identification complete
```

**Comment by peterbarker** [comment]
Merged, thanks.

**Comment by peterbarker** [comment]
> a bit paranoid, aren't we?

I'm sure there's errata for that somewhere.

**Pull request merged**
