### PR TITLE
AP_GPS: bypass the baudrate auto-detection code, it does not work for…

### PR DESCRIPTION
**Pull request by amilcarlucas**
… AsteRX-M2 UAS FW 4.2.2

This does not fix the issue that AsteRX-M2 UAS FW 4.2.2 do not get proper configured out-of-the-box, but it is maybee a start

### CODE REVIEW

**Comment by WickedShell** [comment]
Baud rate cycling does work on a AsteRx-M or M2, and is quite convient, so I don't see particular value in removing it. The print messages could be improved I agree, but the auto bauding is useful.

**Comment by karthikdesai** [comment]
Yes but it being stuck in this detection loop, we thought it wasn't getting detected right so we tried bypassing it

**Comment by karthikdesai** [comment]
https://discuss.ardupilot.org/t/septentrio-gps-detection-stuck-in-loop/20574
@/all We are referring to this BTW.

**Comment by WickedShell** [comment]
Yeah, because the loop will go through the baud rate I think the baud attempts are nice, although we don't ever force the baud to 115200 like we do in the u-blox driver, so it is possible to lock in on a off baud rate.

Basically unless this compelling fixes a problem I'd rather keep allowing the auto bauding on the driver.

**Comment by OXINARF** [comment]
I agree with @WickedShell, I don't see any reason to remove this. The linked discussion says the issue is with connecting early to MP, so I don't see how it connects to this.

Also, if it were to go in, it should be moved up in the code to where the other drivers that don't detect baud rate are.

@WickedShell You are the GPS maintainer, so your call on closing this.

**Comment by WickedShell** [comment]
I was waiting on some follow up testing/comments before applying it, but since this appears to be fixed by an external change and the patch didn't improve the situation at all for the AsteRx units I'm going to close it at this point.

**Pull request closed without merging**
