### PR TITLE
Factor out common POSIX semaphore code

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by OXINARF** [comment]
This is good, but it's been proposed by @lucasdemarchi already: https://github.com/ArduPilot/ardupilot/pull/5548

**Comment by peterbarker** [comment]
Huh.  If it helps, this PR is based on code I wrote in 2015 :-)

**Comment by OXINARF** [comment]
Great minds think alike 🙂 

This one is simpler and so easier to merge, but in a longer term solution I prefer @lucasdemarchi's approach. That said, we already have some common code in AP_HAL.

**Comment by lucasdemarchi** [comment]
I think AP_HAL should be kept as a "interface-only" namespace (yes I know we don't respect that already, but I'd rather move things out rather than in).

From #5548... I really think we should pay attention to item (2) from the PR. And also remove the need for `Util::new_semaphore()`.

**Pull request closed without merging**
