### PR TITLE
Fix RPI boards

### LINKED ISSUE #6233: AC3.5: Segmentation fault in Linux RCInput_RPI
#### Issue details
RPI , Linux based FC that use GPIO for PPM input is crashing with this error: Segmentation fault in Linux::RCInput_RPI::_timer_tick() 

#### Version
3.4.2  -  3.5

#### Platform
[  ] All
[  ] AntennaTracker
[x  ] Copter
[  ] Plane
[  ] Rover

#### Airframe type
_N/A)_

#### Hardware type
_RPI GPU based inteerupt handler like PXF'MINI_

#### Logs
_Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 774]
0x000b8974 in Linux::RCInput_RPI::_timer_tick() ()
(gdb) bt 0x00119730
0x000b8974 in Linux::RCInput_RPI::_timer_tick() ()_

Does crash with or without PPM signal on FC
Might be indirectly reated to: https://github.com/ArduPilot/ardupilot/issues/5226
Works OK with: V3.4-dev (5362dff5)

### PR DESCRIPTION
**Pull request by lucasdemarchi**
@patrickpoirier51 @LanderU @staroselskii can you give this a try?

Should fix #6233

### CODE REVIEW

**Comment by patrickpoirier51** [comment]
Looking good = 3 sequences of 20 minutes with no crash 
CPU usage went fro 66 to 76 % (looking at top ) when compare to old release.
Thanks Lucas

**Comment by tridge** [comment]
thanks Lucas!

**Comment by LanderU** [comment]
It works also in Erle-Boards thanks @lucasdemarchi.

**Comment by patrickpoirier51** [comment]
@lucasdemarchi 
So the fix was to ignore these signals ?
Signal               Value     Action    Comment
SIGTTIN         21,21,26    Stop       Terminal input for background process
SIGTTOU        22,22,27    Stop       Terminal output for background process
SIGWINCH    28,28,20      Ign        Window resize signal (4.3BSD, Sun)

**Comment by lucasdemarchi** [comment]
No, the fix was to increase the stack (the first commit). These others were added because I was testing this inside a screen process and it was a pain to let ardupilot die for unrelated reasons

**Comment by patrickpoirier51** [comment]
Ok that make sense , thanks for this

**Comment by playertr** [comment]
I'm pretty sure this bug cropped up again for me! I was getting a corrupted stack on a Raspberry Pi Zero that I've hacked together from the PXFMini configuration and custom hardware (LSM9DS1, UBlox M8, and PCA9685). So far, it looks like doubling the stack size to 2048 * 1024 has stopped the segfaults so far, but I'm not certain.

Do you have any advice for debugging this sort of thing? I'm not certain whether there is any tool within Ardupilot, GDB, or another service to watch the Ardupilot stack grow while it's running.

**Comment by lucasdemarchi** [comment]
There is a debug in the scheduler that will print the current stack used of all threads every 1s

**Comment by playertr** [comment]
Thank you! It looks like increasing the stack was necessary and sufficient.

`Stack Usage:
	timer = 3961
	io    = 1364
	rcin  = 1195
	uart  = 1350`

**Pull request merged**
