### PR TITLE
log messages number changed to enum

### PR DESCRIPTION
**Pull request by umarpreet1**
i have changed the log messages number in defines.h of copter and sub from #define to  enum. #7839

### CODE REVIEW

**Comment by rmackay9** [comment]
@umarpreet1, generally looks OK.  I guess you're cleaning up the PR.

One thing is I don't think we need to worry about the specific numbers of each message.  So the "=0xxxx" stuff can be removed from the enum.

**Comment by night-ghost** [comment]
Do not the numbers have to be compatibility with MP? Without specifying an exact value, any insertion in the middle of the enum will result in a hard-to-find bug

**Comment by umarpreet1** [comment]
I am getting this error while building :--
In file included from ../../ArduSub/Sub.h:81:0,
                 from ../../ArduSub/AP_Arming_Sub.cpp:2:
../../ArduSub/defines.h:126:5: error: redeclaration of 'LOG_PROXIMITY_MSG'
     LOG_PROXIMITY_MSG,      
     ^
compilation terminated due to -Wfatal-errors.
Please Help me out to solve this problem

**Comment by OXINARF** [comment]
@umarpreet1 Thank you for your first contribution! I'm not sure if you have read our contribution rules so here is a link to them: http://ardupilot.org/dev/docs/submitting-patches-back-to-master.html Most important ones are the commit message format, one commit per-vehicle/library and cleaning the commit history with rebase and squash. If you have any doubts, don't hesitate to ask here or in our Gitter chat (http://gitter.im/ArduPilot/ardupilot).

Now, about your error, LOG_PROXIMITY_MSG is defined in the DataFlash library (https://github.com/ArduPilot/ardupilot/blob/master/libraries/DataFlash/LogStructure.h#L1543), which is why you are getting a redefinition. It should be safe to remove it from Sub, it's not used there.

@night-ghost DataFlash log describes itself, only number that needs to be kept is the one for FMT message since that will describe all other messages. It might be that some parser is incorrectly relying on numbers, but that's wrong.

**Comment by night-ghost** [comment]
@OXINARF  thanks understood

**Comment by OXINARF** [comment]
@peterbarker I hope that by as is, you meant the final diff and not the commit history 😉

@umarpreet1 So #7903 does the same as this and is almost good to merge. As you did it first, I want to give you the opportunity to fix this PR so that it can be merged. Is this something you want to do?

**Comment by umarpreet1** [comment]
Thanks for giving me opportunity @OXINARF 
there was some error on travis ci ,now my pr has successfully passed the tests and i think it is ready to merge.
Kindly review it or merge it accordingly

**Comment by rmackay9** [comment]
Oops, I'm afraid another user beat you to the finish on this one.  the other PR had the  commits all compressed together ([see how to do it here](http://ardupilot.org/dev/docs/git-interactive-rebase.html)) .  Thanks and don't worry, there are hundreds of other issues to fix :-).

**Comment by umarpreet1** [comment]
It is completely ok @rmackay9  at least i leaned something from it. i will soon start working on new issue and will try to solve it perfectly.

**Pull request closed without merging**
