### PR TITLE
Add Scripting Bindings for BLHeli Telemetry 

### PR DESCRIPTION
**Pull request by Gone4Dirt**
This PR gives access to BHeli telemetry from scripting.

### CODE REVIEW

**Review by WickedShell — CHANGES_REQUESTED** [review]
I'd like to defer this until after #16725 at which point we can get this from the ESC telemetry library and it will work for all ESC's. This is fine as a patch locally for now, but I don't think it's something we should bring in, as it won't cover all the cases, and the prep work is actively being done (and actually is really important).

**Comment by Gone4Dirt** [comment]
@WickedShell yeah, no problem.  Thanks for letting me know.

**Comment by WickedShell** [comment]
Once we get that in though expanding the existing ESC bindings is a no brainer!

**Comment by Gone4Dirt** [comment]
This has now been implmented via ESC_Telem bindings and is not needed

**Pull request closed without merging**
