### PR TITLE
Update for navigator R3 hardware

### PR DESCRIPTION
**Pull request by jaxxzer**
We've done a board revision and moved a lot of things around. This pr depends on #16976 and #15607 .

### CODE REVIEW

**Comment by tridge** [comment]
looks good, but needs rebase after separate PRs are merged

**Comment by jaxxzer** [comment]
@tridge rebased!

**Comment by Hwurzburg** [comment]
@jaxxzer Jacob, I need to discuss using some of your contributions to QGC in the AP wiki....can you contact me on Discord or via email? hwurzburg@yahoo.com...thanks

**Comment by Hwurzburg** [comment]
Jacob, who drew the sub frames for QGC? I am working on the Sub AP Wiki and would like to add the Vectored6DOF-90 frame drawing and if it is easy for the original author, that would be great...who drew them?

**Comment by jaxxzer** [comment]
@Hwurzburg I believe @rjehangir drew the images

**Pull request merged**
