### PR TITLE
Tools: Update install-prereqs-ubuntu

### PR DESCRIPTION
**Pull request by patrickelectric**
Add lsb-core check for lsb_release

Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

### CODE REVIEW

**Comment by magicrub** [comment]
What does lsb-core do?

**Comment by patrickelectric** [comment]
@magicrub 	this package is necessary to install lsb_release

**Comment by khancyr** [comment]
https://packages.ubuntu.com/search?keywords=lsb-release , could you update the PR ?

**Comment by patrickelectric** [comment]
I just tested in 16.04 and 18.04, both recognize lsb-core:
image
 
http://packages.ubuntu.com/search?keywords=lsb-core
Is showing in 18.04 also in ubuntu website. 

lsb-release fail in 16.04;

**Comment by patrickelectric** [comment]
@khancyr 	Thanks, got it. Patch updated.

**Comment by magicrub** [comment]
@khancyr is this ready to merge?

**Comment by khancyr** [comment]
@magicrub, yep seems good

**Pull request merged**
