### PR TITLE
AP_HAL_PX4: Adds UARTF as command line option

### PR DESCRIPTION
**Pull request by mayanez**
It looks like this might have been missing from the original PR: https://github.com/ArduPilot/ardupilot/pull/3927

### CODE REVIEW

**Comment by magicrub** [comment]
Interesting timing, we were just talking about removing CLI at last dev call. Do you use the CLI? What do you do with it?

**Comment by magicrub** [comment]
Nevermind, I was thinking of a different command line

**Comment by OXINARF** [comment]
@mayanez It was probably forgotten as it isn't very important - you can probably count on one hand how many people ever used these options to start ArduPilot in NuttX. Calling `begin` is good, even if it is also called early in the ArduPilot general boot (and that's why it works today).

The patch looks good, thanks! I'll give it a bit of time for @tridge to look at it as he is the PX4 HAL maintainer.

**Comment by tridge** [comment]
I have no objections to this, but I'm curious what the motivation for it is. The command like for specifying the uarts is there for when we started up from a shell script and chose the uarts based on detected board type in that script. We don't do that any more, so under what conditions would someone want to pass in different uarts for the ardupilot process?

**Comment by mayanez** [comment]
I'm using it for setting UART F for sensorhub. For example, on Pixhawk 2 there are 4 serial devices + 1 for nuttx nsh. I simply take over the uart originally configured for TELEM 2 or GPS 2 and use it for sensorhub and set UART F to use that interface at runtime.

**Comment by OXINARF** [comment]
Since @tridge doesn't object and it is being used by @mayanez, I think it doesn't hurt to put it in - it is just replicating what is already there, not exactly adding something new. Merged, thanks!

**Pull request merged**
