### PR TITLE
Copter: correct TERRAIN_FOLLOW parameter comments

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by rmackay9** [comment]
Shouldn't it be a comma?

**Comment by magicrub** [comment]
That's what I was thinking.  Should be a comma.

**Comment by peterbarker** [comment]
*sigh*.  My first cherry-pick didn't work, so I "redid" my hand.  Mistake.

**Comment by rmackay9** [comment]
merged, thanks!

**Pull request closed without merging**
