### PR TITLE
Library: Change the parse unnecessary character string to print or println.

### PR DESCRIPTION
**Pull request by muramura**
The printf method is used for character string output which does not need parsing.
Therefore
Change to a print or println method without parsing.

### CODE REVIEW

**Comment by gmorph** [comment]
What do we gain from this?  Speed improvement?  String safety?  Or is it change for more technical correctness?  Just wondering is all.
Thanks, Grant.

**Comment by muramura** [comment]
@gmorph Thank you for your inquiry.
1A: It is "Speed improvement".
2A: You can use it. (Supported hardware)

**Comment by tridge** [comment]
I don't think this is worthwhile. None of these print functions are speed critical. We never print in a situation where speed matters.
It also makes it harder to switch between hal functions and system functions. I quite commonly change a hal.console->printf() to a printf() while I am debugging.
I'd actually rather see this go the other way and remove the old print and println functions. That would save some flash space and would be a genuine improvement in readability.

**Comment by muramura** [comment]
@tridge san. Comments thank you.

The print, println, and printf methods mimic the java language.
The print and printf methods also exist in the Ruby language.
Print is output without format specification.
Printf is formatted and outputted.
I think that this concept can also be found in C language.
If you do not want to change it, add "Do not change" to the comment.

**Comment by OXINARF** [comment]
@muramura C/C++ has only printf and that's enough, since print or println are just convenience functions in other languages.

Although we have merged changes like this before, I agree with @tridge that the best is to remove println and print and stay just with printf. If you want to do a PR with that, we'll review and merge it. I'm going to close this one.

**Comment by muramura** [comment]
@OXINARF @tridge 
I understood to unify it with printf.
Change print and println to printf, and PR newly.

**Pull request closed without merging**
