### PR TITLE
Tools: Check if version exist before installing it

### PR DESCRIPTION
**Pull request by patrickelectric**
Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

### CODE REVIEW

**Review by khancyr — APPROVED** [review]
seems good

**Comment by patrickelectric** [comment]
@khancyr the issues appears to be not connected to the PR

**Comment by patrickelectric** [comment]
ping @Williangalvani

**Review by khancyr — APPROVED** [review]
ok for me. I don't have mac to test

**Comment by peterbarker** [comment]
@andyp1per @bugobliterator FYI

**Pull request merged**
