### PR TITLE
AP_CANManager:Ensure that the can transmission interval is greater than 1ms

### PR DESCRIPTION
**Pull request by CUAVcaijie**
> Problem reproduced: 

Reappear the environment:
Ground station: 
Mission Planner1.3.74 
Firmware version：
34a52e9cfe8e2a3f7b0c74e9dd2fc7386aef7fae
Reproduce Process ：
image
Stuck at downloading firmware 
image
Analysis using UAVCAN GUI Tool 
image
image

> Search error:

file：libraries/AP_CANManager/AP_SLCANIface.cpp 
Line 692 in the file，（_can_iface->send(out_frame, AP_HAL::native_micros64() + 1000, out_flags);）
The return value is 0. It means that TX's sending mailbox is full

> resolvent:

Increase the interval time of can transmission.

### CODE REVIEW

**Comment by CUAVcaijie** [comment]
@bugobliterator Are there any questions?

**Comment by bugobliterator** [comment]
> @bugobliterator Are there any questions? 

Sorry, have been bit busy. Give me a day or two I will get back to you.

**Comment by CUAVcaijie** [comment]
okay, thank you

**Comment by bugobliterator** [comment]
I think better solution is probably to try sending and if failed don't pop the rx buffer.

**Comment by bugobliterator** [comment]
Can you try this patch https://github.com/ArduPilot/ardupilot/pull/16884 , let me know if it fixes the issue you are having.

**Pull request closed without merging**
