### PR TITLE
PR: ArduPlane + latest JSBSim: Wrong airspeed units conversion, issue #10567

### PR DESCRIPTION
**Pull request by simfinite**
PR for [issue #10567](https://github.com/ArduPilot/ardupilot/issues/10567)

### CODE REVIEW

**Comment by magicrub** [comment]
looks ok but I think @tridge should take a look before merging

**Comment by peterbarker** [comment]
Thanks for the fix.  Problem is that anybody running an older JSBSim (me, sorry! :-) ) will now have a broken setup.

Is there any convenient way to get a version from JSBSim?

**Comment by simfinite** [comment]
I wasn't aware that the current master still supports older JSBSim versions... There is actually a `version` flag in the UDP message, however, it seems that it has always been set to '24' via the [constant FG_NET_FDM_VERSION](https://github.com/JSBSim-Team/jsbsim/blob/253a2663c8799821013df2f79df4a5d386f6cd88/src/input_output/net_fdm.hxx#L24).` At least it's 24 for all versions I have laying around... can you check yours?

I don't know another way to get the JSBSim version. Running `JSBSim --version` returns "JSBSim Version: 1.0" plus the build date and time. @tridge 's fork returns "JSBSim Version: 1.0 <build date> (ArduPilot)"... could be used to determine old setups based on this fork, but it wouldn't capture other old versions.

**Comment by peterbarker** [comment]
On Sun, 24 Feb 2019, simfinite wrote:

> I wasn't aware that the current master still supports older JSBSim versions... There is actually a version flag in the UDP message, however, it seems that

Hmph.  Doesn't seem to.  We need an autotest for this.

> it has always been set to '24' via the constant FG_NET_FDM_VERSION.` At least it's 24 for all versions I have laying around... can you check yours?

It's 24 here.

> I don't know another way to get the JSBSim version. Running JSBSim --version returns "JSBSim Version: 1.0" plus the build date and time. @tridge 's fork
> returns "JSBSim Version: 1.0 (ArduPilot)"... could be used to determine old setups based on this fork, but it wouldn't capture other old versions.

Well, doesn't seem to matter now.  Probably best to plough on.

**Comment by OXINARF** [comment]
@tridge Please fix commit messages before merge, but even more important close the issues the PR is addressing 😉

**Comment by tridge** [comment]
ahh, darn, sorry Francisco

**Comment by simfinite** [comment]
@peterbarker, for what it's worth, latest JSBSim has some nice features that are well worth the upgrade, like Karman turbulence models for example ([see here on how to use it](https://github.com/simfinite/ardupilot/commit/49c5ceff093f406984e2e6f75229a253267527ce)). Anyway, thank's for merging.

**Pull request merged**
