### PR TITLE
AP_LeakDetector: Add navigator board support

### PR DESCRIPTION
**Pull request by patrickelectric**

### CODE REVIEW

**Comment by Williangalvani** [comment]
Running some tests here:

- [x] Individual leak probe
 - [ ] SOS leak sensor 

Should we get that "11" into an Enum somewhere so QGC can see it?

**Comment by patrickelectric** [comment]
> Should we get that "11" into an Enum somewhere so QGC can see it?

We should do what is current done by the pixhawk in QGC.

**Comment by Williangalvani** [comment]
I believe the metadata comes from [here](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_LeakDetector/AP_LeakDetector.cpp#L10).

**Comment by patrickelectric** [comment]
@Williangalvani thanks, done.

**Review by Williangalvani — APPROVED** [review]

**Review by jaxxzer — APPROVED** [review]

**Pull request merged**
