### PR TITLE
BeagleBone : comments corrected in RcAioPRU.p

### PR DESCRIPTION
**Pull request by dorovl**
Please receive below two small corrections on the PRU assembler comments.

### CODE REVIEW

**Comment by dorovl** [comment]
@khancyr I just changed some wrong comments and Travis CI is blocking. Can you help me?

**Comment by peterbarker** [comment]
travis choked.  Kicked it over.

**Comment by dorovl** [comment]
> travis choked. Kicked it over.
@peterbarker What do you suggest?

**Comment by dorovl** [comment]
Please commit the changes (comments only).

**Comment by lucasdemarchi** [comment]
Looks good, but this needs a rebase - we don't merge master branch. Commit message should also follow the style with "Tools:" prefix

**Comment by dorovl** [comment]
@lucasdemarchi, please note that this commit is a small correction of: https://github.com/ArduPilot/ardupilot/pull/13814

Regarding the commit messages, I took the same nomenclature as changed by rmackay9, that is with a  "BeagleBone : " prefix (to be coherent).

Regarding the https://github.com/ArduPilot/ardupilot/pull/13814, the merge has been done directly in master. If not OK for you, please provide me more detailed instructions of what to do.

**Comment by dorovl** [comment]
> @dorovl hello,
> 
> You seems to have a protection on your branch, I cannot correct it.
> Could you just run `git rebase -i master` to update your branch ? just keep the last commit

@khancyr, hello Pierre, I did a:

```
#git stash
#git rebase -i master
#git push --set-upstream origin comments_corrected
#git status
On branch comments_corrected
Your branch is up to date with 'origin/comments_corrected'.
#git stash pop
```
I hope is now OK?

**Comment by khancyr** [comment]
@dorovl Sorry something went wrong. You were close but you master branch isn't on sync with ArduPilot master. 
Could you follow instruction from https://ardupilot.org/dev/docs/git-rebase.html starting from point 3. and it should be good ! At the end you should only have your commit as difference from ArduPilot master !

**Comment by dorovl** [comment]
@khancyr, Hello Pierre, I did the procedure, but I ended by doing a **forced** push:
`git push -f origin comments_corrected`
Now the status is "Able to merge".

**Pull request merged**
