### PR TITLE
AP_NavEKF2/3: Set the range value from 0

### PR DESCRIPTION
**Pull request by muramura**
I learned that the value of -1 had no meaning.
I learned that I am processing if it is greater than zero.
I changed the meaningless range value.

### CODE REVIEW

**Review by khancyr — COMMENTED** [review]
Indeed value equal or under 0 aren't used.
So changing from -1 to 0 don't change the default behaviour. But I still prefer the -1 as it is cleared than 0 in that case.
Maybe it would be also better to add a comment to the description.

**Comment by rmackay9** [comment]
Let's let @priseborough decide.  -1 or 0 has the same effect..

**Review by priseborough — COMMENTED** [review]
I'm OK with this change, but can we please add text to the @Description field to explain that setting the parameter to 0 deactivates the feature.

**Comment by muramura** [comment]
@priseborough san. I have described 0 in the description.

**Review by priseborough — APPROVED** [review]

**Comment by tridge** [comment]
this will cause MissionPlanner to pop up a parameter range error when loading old parameters as old params will be -1

**Comment by rmackay9** [comment]
We discussed this on the dev call and came to the conclusion that it is probably not worth changing this.  There's no real issue with using -1 or 0 for the default parameter value so the change is more likely to cause issues rather than solve them.

Thanks anyway!

**Pull request closed without merging**
