### PR TITLE
Update GIT_Success.txt

### PR DESCRIPTION
**Pull request by prathapjaga**

### CODE REVIEW

**Comment by rmackay9** [comment]
Hi @prathapjaga,

Can you remove the merge commit?  Also if possible change the "Update GIT_Success.txt" commit to "Tools: Update GIT_Success.txt".  Please note that I'm talking about the commit description, not the PR description.

**Review by rmackay9 — CHANGES_REQUESTED** [review]
Let's get rid of the merge commit.

**Comment by prathapjaga** [comment]
> Let's get rid of the merge commit.



> Hi @prathapjaga,
> 
> Can you remove the merge commit? Also if possible change the "Update GIT_Success.txt" commit to "Tools: Update GIT_Success.txt". Please note that I'm talking about the commit description, not the PR description.

i removed merge commit.

**Comment by rmackay9** [comment]
@prathapjaga, actually it looks like there are two merge commits now!  Git is tricky!

**Comment by prathapjaga** [comment]
> @prathapjaga, actually it looks like there are two merge commits now! Git is tricky!

then how to block the merge

**Comment by MichelleRos** [comment]
Using `git rebase -i` on master should remove the merge commits and also let you rename the commit to start with `Tools:`.

**Comment by magicrub** [comment]
Looks like you've made another PR https://github.com/ArduPilot/ardupilot/pull/25500 of this same thing. Closing this one.

**Pull request closed without merging**
