### PR TITLE
AP_NavEKF3: Measurements: add position compensation to accel from gyro

### PR DESCRIPTION
**Pull request by IamPete1**
This adds correction for accels from rotation, maths from here, just subtract rather than add:

https://github.com/ArduPilot/ardupilot/blob/795bb19cb99b32973584cdd354a514b3c39847c2/libraries/AP_InertialSensor/AP_InertialSensor_SITL.cpp#L160-L176

I still need to do some testing, we might find that the gyro noise means that this compensation is worse than none.

There maybe a better place to put this in the EKF than where I have it.

### CODE REVIEW

**Comment by priseborough** [comment]
The EKF does its computations at the IMU location, then 'moves' the state estimates to the body origin so this patch is unnecessary. If acceleration at the body origin is required, then we would be better  do that as separate correction using cross products of a filtered gyro product. The EKF IMU input data is not filtered - it is the result of an integration downsampling method.

**Comment by Gone4Dirt** [comment]
@priseborough can you elaborate on that a little more please? You recommend doing the acceleration correction post filter.  Is that because this implantation is using the derivative of the gyro data and you are concerned it will be too noisy?

To expand on the original motivation of this PR.  We were working on a large multirotor where the FC is mounted ~1m forward of the CG.  When in any flight mode that uses a height estimate the vehicle notably rotates around the F/C when rolling and pitching.  Compared with stabilise for example where the copter rolls and pitches about about the CG.  Hence why acceleration at the body origin is required.

**Comment by IamPete1** [comment]
I hope this is closer to what we need, https://github.com/ArduPilot/ardupilot/pull/23511/files

**Comment by priseborough** [comment]
@IamPete1 The INS*POS_X,Y,X parameters should be set up for the position of the IMU relative to the body frame origin (usually at the c.g.) and the other sensors, GPS, rangefinder, optical flow, etc also having their positions set relative to the same datum where X is fwd, Y is right and Z is down. When this is done the position and velocity outputs from the EKF will be at the body frame origin.

**Pull request closed without merging**
