### PR TITLE
Fix params names for Bebop

### PR DESCRIPTION
**Pull request by jberaud**

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
@rmackay9 it's very hard to keep track of the renames after the fact. Could we please rename the params in our own param at the same time we rename them in the codebase?

Also, doing only for bebop doesn't make sense for me... it should be done for all frames/boards.

**Comment by jberaud** [comment]
@lucasdemarchi Randy objected to my last pr with the names fixed for all boards that GCSs look for these param files on master even if the current version used on the vehicle is a stable release.
To me, this behaviour is wrong but since my concern is that the bebop's software doesn't crash at startup (bad param in default param file causes a critical error), I'd rather fix that untill the GCS's behaviour is fixed.

**Comment by lucasdemarchi** [comment]
I second that. We should upload the param files to ardupilot.org and GCSs should use that.  It's a pain for those (us) using the master branch.

**Comment by lucasdemarchi** [comment]
Applied, thanks.

**Pull request closed without merging**
