### PR TITLE
WIP: add support for quadmotor tailsitters

### PR DESCRIPTION
**Pull request by kd0aij**
replaces #8113, rebased on master

adds 2 new motor functions, k_throttleTop and k_throttleBot
and implements them in tailsitter.cpp, along with reductions in control surface gains when in VTOL mode at high roll or pitch angles (assuming that means high airspeed)

### CODE REVIEW

**Comment by magicrub** [comment]
does this also add support for 6 vertical motors? :)

**Comment by kd0aij** [comment]
No, it only supports the quad plus frame geometry.  Like this: https://discuss.ardupilot.org/t/dual-motor-tailsitters/15302/1154

**Comment by pierreletullier** [comment]
hi Mark,
The back transition is sometime not working very well. It seems to me that there is not enough thrust to go from level flight up to q_tailsit_angle. I think the throttle hover learning could be responsible because q_m_thst_hover is used to set throttle during the first part of the transition. I checked my logs and found that during the first part of the transition throttle is set to 1450 but I it should be around 1600 as I have set q_m_thst_hover to 0.6. Is there a means to disable throttle hover learning in order to test my hypothesis ?
regards,
pierre

**Comment by kd0aij** [comment]
Setting Q_M_HOVER_LEARN to 0 should disable the learning function. A value of 2 causes the learned value to be saved to Q_M_THST_HOVER, so you can check the learned value after each flight.  My tests show that the saved value agrees well with RATE.AOut, so it seems to be working correctly.
Regarding throttle values on back-transition, I agree that sometimes there is insufficient throttle applied, but I haven't been able to figure out why.

**Comment by pierreletullier** [comment]
Is throttle hover learning active whatever the lean angle ?  Because the amount of throttle decrease with the lean angle.  Do you know the time needed to save q_m_thst_hover ?

**Comment by kd0aij** [comment]
QuadPlane::update_throttle_hover() only updates hover throttle if z velocity demand is zero, and we are in a level hover (< 0.5 degrees roll and pitch). There is a 10 second time constant: AP_MOTORS_THST_HOVER_TC

**Comment by pierreletullier** [comment]
you are right, Q_M_hover_learn to 0 disable hover learn. The problem with back transition is in fact airframe dependent as the wing wants to lean on one side in the first part of the transition and because the differential thrust in not controlled by the pixhawk during that time. More thrust mitigate the problem.

**Comment by kd0aij** [comment]
@pierreletullier
Regarding the problem with the tilt-vectored quadTailsitter top/bot motors fighting desired pitch: Here's a plot from your log at 
https://drive.google.com/file/d/1M9zpuYwEx7MlGQZtqeAOO2q4NIOKisul/view?usp=sharing
which shows top and bottom throttle, tilt servos and pitch angles.

It shows that bot/Top throttles are fighting the desired pitch angle, but that is opposite to what I observe with the Stryker and Dart models (both real and SITL).  It also shows the tilt servos are active during QHOVER, presumably controlling yaw, but I can't see where that is happening in the tailsitter code. Your servo_function params are the same as mine, except that I don't have tilt servos, so my Q_TILT_MASK is zero.  But according to your log you also have Q_TILT_MASK=0. Is that incorrect?  

@tridge Advice on how tilt vectoring works in VTOL modes would be appreciated.

**Comment by pierreletullier** [comment]
Q_tilt_mask is a quadplane parameter but not a tailsitter parameter. Yes, tilt servos are active in all stabilized modes (fbwa too).
The file is probably not the right file, its is my full log.
When you say top and bottom motor fight the desired pitch, maybe you did not notice that in my configuration servo 7 is 90 so bottom motor and servo 8 is top motor.
At the beginning I observed the bottom motor to spin faster than expected (but with the right action with respect to the desired pitch). But now I think this is a tuning issue because the wing overshoot the desired angle so I am currently working on finding the right CG position, elevon and tilt motor position.... I think the level accelerometer calibration is also important. My conclusion is the quad code works nicely, it adds extra stability and recovery ability in hover and the lift given by the bottom motor is efficient against stall in fbwa mode. 
Just some words about back transition and throttle hover learn. When making the back transition at very low speed my wing had a tendency to lean left (which can be fearing) until it reaches q_tailsit_angle but again it was a tuning issue (right wing lighter in my case and probably because top and bottom motor had CW prop). More speed makes the problem less obvious. For the moment I have disabled hover learn but I will try to enable it again after some more tests.

**Comment by kd0aij** [comment]
replaced by #10401

**Pull request closed without merging**
