### PR TITLE
AP_Compass: fix reordering compass devid by priority at boot

### PR DESCRIPTION
**Pull request by bugobliterator**
We were using detected compass state id as we do during runtime. But these values are not filled during boot, leading to invalid ordering per Priority. This PR fixes that by using stored params instead.

This doesn't impact functioning of Compass library, just is bad UX. As user might see different order under devid list and logging/telemetry.

### CODE REVIEW

**Comment by tridge** [comment]
@bugobliterator getting a build error for AP_Periph builds:
../../libraries/AP_Compass/AP_Compass.cpp: In member function 'void Compass::_reorder_compass_params()':
../../libraries/AP_Compass/AP_Compass.cpp:811:13: error: '_priority_did_list' was not declared in this scope
         if (_priority_did_list[i] == 0) {
             ^~~~~~~~~~~~~~~~~~

**Comment by peterbarker** [comment]
Errr.

```
AT-0032.8: FAILED: "CompassReordering (Test Compass reordering when priorities are changed)": NotAchievedException('COMPASS_ORIENT has wrong value; want=1.000000 got=2.000000 transforms=[(1, 2), (2, 1)]',) (see /home/pbarker/rc/buildlogs/ArduCopter-CompassReordering.txt)
```

This is with https://github.com/ArduPilot/ardupilot/pull/15088

**Comment by tridge** [comment]
I've added Peters test from #15088 to this PR

**Review by tridge — APPROVED** [review]

**Comment by rmackay9** [comment]
@tridge this should be merged to Copter-4.0 of course?

**Pull request merged**
