### PR TITLE
Copter: factorize arm or land check

### PR DESCRIPTION
**Pull request by khancyr**
Factorize a check on copter.
We may get a better name.
Save some space

### CODE REVIEW

**Comment by rmackay9** [comment]
Seems like a good change to me.  We could perhaps call it "check_disarmed_or_landed()"? Happy to hear other options.

**Comment by khancyr** [comment]
rename with Randy suggestion

**Comment by peterbarker** [comment]
Perhaps `is_disarmed_or_landed`?

**Comment by peterbarker** [comment]
Can be merged after the name change.

**Comment by rmackay9** [comment]
Renamed and then merged, thanks!

**Pull request closed without merging**
