### PR TITLE
AP_Scripting:Update plane aerobatics scripts with adds and fixes

### PR DESCRIPTION
**Pull request by Hwurzburg**
example mission video:
https://cdn.discordapp.com/attachments/797952826847920128/928298942322577428/New_Project.mp4

mission

### CODE REVIEW

**Comment by Hwurzburg** [comment]
added some more tweaks in addition to arbitrary knife edge angled flight:
- assure wings level before starting loop....fixed loop pitch rate vs speed (makes for circular loops)...added altitude recovery at end of loop in case its needed during tuning...
- added ability to cascade tricks without intervening waypoints
- removed axial roll throttle argument...not needed now, will maintain altitude
- added pause trick to give time spaces between cascaded tricks

**Comment by Hwurzburg** [comment]
with latest changes: /home/henry/Dropbox/RealFlight/Aerobatics/Sequence 1.mp4

**Comment by Hwurzburg** [comment]
on real plane https://www.dropbox.com/s/8icarj7q2agwu15/long_aero.bin?dl=0

**Comment by Hwurzburg** [comment]
further updates to use scripting param blocks, performance tweaks....retest on real vehicle this coming week

**Comment by Hwurzburg** [comment]
all tricks have been extensively test flown, rolling circle fails....I have a tricks on a switch version that I will test today and think will work better ....I will incorporate into the script if successful and bring to devcall

**Comment by Hwurzburg** [comment]
flight tested with master and new rolling circle trick....ready to merge

**Review by tridge — APPROVED** [review]

**Pull request merged**
