### PR TITLE
Replay: Remove AP_InertialNav

### PR DESCRIPTION
**Pull request by khancyr**

### CODE REVIEW

**Comment by rmackay9** [comment]
@khancyr, can we just remove the InertialNav.update function like this?  It seems unlikely to me.  I guess you haven't actually tested this change?

**Comment by khancyr** [comment]
I am not use to replay, but it seems safe as it is only updated and no libraries with dependencies on it are called. Let's wait @peterbarker input on this

**Comment by peterbarker** [comment]
@khancyr Have you run some logs through replay before and after to test?

**Comment by peterbarker** [comment]
In particular: https://github.com/ArduPilot/ardupilot/pull/8088/commits/e3f3eb9addb1b3dd369b019a57a289fec2bda997

**Comment by OXINARF** [comment]
I was thinking this was dangerous to do, but I think @khancyr is right. AP_InertialNav isn't a singleton and it isn't passed to any library in Replay - so how would code call it? Seems impossible to me that it is used anywhere.

**Comment by peterbarker** [comment]
Rebased, tested to a trivial extent (and fixed) and merged.

**Pull request closed without merging**
