### PR TITLE
Travis: use container-based builds with cache

### PR DESCRIPTION
**Pull request by OXINARF**
Change Travis to use container-based builds, which has the following advantages:

- faster boot time
- cache available to use
- more time for each job (undocumented)

With the cache, we are saving the ccache database, the python packages, our tools and using Travis' network-local APT cache.

The biggest improvement is having the ccache database from build to build, but it should be noted that it can't solve everything, a simple change (for example, the recent add of one function to AP_HAL/RCOutput.h) can invalidate a big chunk of the cache because the file is included in many places.

This is not the greatest metric - because it is the exact same code - but here's a link to a build: https://travis-ci.org/OXINARF/ardupilot/builds/123532539 Times are cut significantly.

Semaphore is going to fail this build - it needs to be changed to run the _install-apt-ci.sh_ script before the configure one.
@lucasdemarchi is the diydrones account in Semaphore a simple account or an organization? If it is an organization can I be added to it? If it isn't, I think this is the appropriate time to create the ArduPilot organization there and add some people to it.

P.S.: The reason I left a commit with a single word change was because that's the only needed change to go back to usual Travis builds and so I wanted to leave it separate. I can always squash it with the next commit if requested.

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
> Semaphore is going to fail this build - it needs to be changed to run the install-apt-ci.sh script before the configure one.

done

**Comment by lucasdemarchi** [comment]
> @lucasdemarchi is the diydrones account in Semaphore a simple account or an organization? If it is an organization can I be added to it? If it isn't, I think this is the appropriate time to create the ArduPilot organization there and add some people to it.

Anyone with write access to the github repository can create/change configuration in semaphore. However, the one who created the account in semaphore needs to add the others. I'll add you there

**Comment by OXINARF** [comment]
Thanks Lucas

**Comment by lucasdemarchi** [comment]
@OXINARF I triggered a new build on semaphoreci before applying this. LGTM.

**Comment by OXINARF** [comment]
@lucasdemarchi You had put an extra _.sh_ in the Semaphore configuration, I fixed it and requeued for build

**Comment by lucasdemarchi** [comment]
Thanks. Applied.

**Pull request closed without merging**
