### PR TITLE
AP_BLHeli fixes for MSP_SET_MOTOR message et al

### PR DESCRIPTION
**Pull request by 4712**
Added missing ack to MSP_SET_MOTOR message
Added ACK_I_INVALID_CHANNEL as response for cmd_DeviceReset/cmd_DeviceInitFlash on bad channel selection
Fixed params for MSP_MOTOR_CONFIG
Adapted some timeouts.
Reservation of an MCU_ID area to simplificate adding of upcoming BLHeli_32 MCU.

### CODE REVIEW

**Comment by 4712** [comment]
Could someone be so kind to review and merge this pr?

**Comment by 4712** [comment]
@yaapu @tridge any reason, why merge still pending here since long?

**Comment by andyp1per** [comment]
@4712 I've added it as a devcall topic

**Comment by tridge** [comment]
Thanks for this! I'm happy for this to be merged once @andyp1per has some some testing

**Comment by andyp1per** [comment]
Tested on both BLHeli32 and BLHeli_S - all fine

**Pull request merged**
