### PR TITLE
Add channel 9-16 to rc overrride in GCS_Mavlink.c for Plane, Copter, Rover, and Sub

### PR DESCRIPTION
**Pull request by dposea**
This goes with pull request #9605. In addtion to Copter I changed ArduSub, ArduPlane, and ArduRover GCS_Mavlink.c files. I was not sure how to add more changes to my first pull request

### CODE REVIEW

**Comment by dposea** [comment]
Guys, I messed this up. It picked up a merge to my fork in addition to the commit I wanted included. I have searhed but none of the options for removing a commit from a pull request seem tio be a solution. Please tell me how to fix this, or I could just do another pull request without the merge commit. I think deleting my fork and forking again is what I want to do, is that the best way to create oull requests?

**Comment by peterbarker** [comment]
@dposea I've made some assumption about your git layout below.

Notably, I've assumed the remote "origin" is ardupilot and the remote "github" is https://github.com/dposea/ardupilot

If that's not the case, tread even more carefully.

I've also assumed you are checked out on your master branch with a clean working tree.

Typically one does not commit into your "master" branch.  You create topic branches and push those topic branches around.

 Make a topic branch to hold a backup of your changes:

`git branch override-high-channels-201812111304`

Make a topic branch for your changes:
`git branch override-high-channels`

Reset your master branch to track origin:
`git reset --hard remotes/origin/master`

Check out your topic branch:
`git checkout override-high-channels`

Rebase that branch on (remote) master:
`git rebase remotes/origin/master`

Push your topic branch over your master branch on github (not typical, but that's what your PR here is based on; typically you would push the topic branch up and PR that):

`git push -f github override-high-channels:master`

**Comment by peterbarker** [comment]
@dposea Assuming this actually works with both mavlink1 and mavlink2 connections, the only odd thing is the indentation which needs fixing (ammend your commit / force-push the branch)

However, you may have noticed the code you're modifying is essentially the same across all vehicles.  We can do better here by moving the bulk of the code into `libraries/GCS_MAVLINK/GCS_Common.cpp`, into a method `virtual void GCS_MAVLINK::handle_rc_channels_override()`.  Each of the vehicles will override that, simply to override the "I got a heartbeat" code (we hope to unify all that stuff into the future too!).  The sysid_mygcs stuff can be done in the base class using the `sysid_mygcs()` callback.

These changes don't need to be done as part of this PR, but you might find removing code rather than adding it satisfying.  Please let me know if you'd like to do this work as part of this PR or as a future PR.

**Comment by dposea** [comment]
Thanks for the explanation. I followed a tutorial on updating a fork to the latest "master",  and I see why that was not the right solution. Anything I could think of to get rid of that commit would leave me where I started with a fork that wasn't current. I thought it better to ask rather than making the problem a lot worse trying to fix it. I need to study your reply a bit to make sure I do it right in the future. I'll be glad to move the code into the library code.  Should I also move other common rc_channel messages too? It seems that the individual GS_Mavlink.c files should only define or override messages specific to that platform, all else being common. I'll take a look at the scope of doing the changes the right way and I'll let you know if I can get that done correctly. I'd love to be able to give something back to the ardupilot project. 

I don't think mavlink1 supports 16 channels. I was told Mavlink2 is now standard, and that seems to be true. If not the extra channels need to only be added to mavlink 2 builds.

**Comment by peterbarker** [comment]
On Tue, 11 Dec 2018, David Posea wrote:

> the library code. Should I also move other common rc_channel messages too?

Just this one :-)  Don't cope-creep yourself, let others do that for you 
:-)

> I don't think mavlink1 supports 16 channels. I was told Mavlink2 is now
> standard, and that seems to be true. If not the extra channels need to only
> be added to mavlink 2 builds.

It's a matter of you need to make sure overrides when both mavlink1 and 
mavlink2 are in play.

Please let me know if you need assistance.

**Comment by dposea** [comment]
I'm a bit confused by the use of a virtual function. Do virtual fucntions have implementations in the base class? If my override functions have the implementation code there is no savings.  

case MAVLINK_MSG_ID_RC_CHANNELS_OVERRIDE:       // MAV ID: 70
{
       if(msg->sysid != copter.g.sysid_my_gcs) {
             break; // Only accept control from our gcs
        }
        GCS_MAVLINK::handle_rc_channel_override_message(msg);
        copter.failsafe.last_heartbeat_ms = tnow;
}

is how I would have implemented it if you had not said to use a virtual function. Can you explain if its not too much trouble. I have been researching virtual functions but havent seen a solution that applies. I realize the sysid can also be made common but have not looked at that yet. 

Thanks,

David Posea

**Comment by peterbarker** [comment]
> I'm a bit confused by the use of a virtual function. Do virtual fucntions have implementations in the base class? If my override functions have the implementation code there is no savings.

`virtual` means a virtual-method-dispatch table is created; when the base class calls a method it looks in the vmdt to work out which function to *actually* call, rather than the one in the base class implementation.  Without this keyword calling a method in the base class would only call the base class implementation.  You can make a "pure virtual" method By assigning `0` to the symbol in the declaration of the class - that forces all derived classes to provide an implementation.  Any override of a base class non-pure method can call the base case method using a specific syntax you can find throughout AP's codebase.  (n.b. rough description, probably misleading and technically incorrect in various respects ;-) )

> 
> case MAVLINK_MSG_ID_RC_CHANNELS_OVERRIDE: // MAV ID: 70
> {
> if(msg->sysid != copter.g.sysid_my_gcs) {
> break; // Only accept control from our gcs
> }
> GCS_MAVLINK::handle_rc_channel_override_message(msg);
> copter.failsafe.last_heartbeat_ms = tnow;
> }
> 
> is how I would have implemented it if you had not said to use a virtual function. Can you explain if its not too much trouble. I have been researching virtual functions but havent seen a solution that applies. I realize the sysid can also be made common but have not looked at that yet.

So instead of having the `case` in `GCS_MAVLINK_Copter::handleMessage` a case goes into `GCS_MAVLINK::handle_common_message`.  You'd create a non-virtual `handle_rc_override` method in there *That* method does something like if
```
if (msg->sysid != sysid_my_gcs()) {
  return;
}
.
.
```

For argument's sake, that method will call a (pure-?)virtual `rc_override_packet_processed()` method which can reset the `last_heartbeat_processes_ms` variable in the vehicle.  This is an interim arrangement until we move GCS failsafe variables elsewhere.  @OXINARF seem reasonable?

@dposea if this all seems too hard, your PR as-is is OK.  It adds functionality without breaking anything :-)

**Comment by peterbarker** [comment]
On Tue, 11 Dec 2018, David Posea wrote:

> Just to be sure libraries/GCS_MAVLink/GCS_Common.cpp handle_common_msg can
> handle the actual rc_channel data, then call a virtual function to be
> overriden by each vehicle to update the heartbeat timer, and I'll figure out
> sysid it's used everywhere . Will that work and not break the ardupilot
> style too badly? I just realized thats exactly what you were saying all
> along and I misunderstood completely. I just could not make the mental leap
> past putting common code in a virtual function.

Yep.  It's something we do quite a bit in ArduPilot, 'though I believe 
some style-guides recommend against it for various reasons.

**Comment by OXINARF** [comment]
@dposea There was no need for a new pull request, you could just have added to the old one. When you need help with Git, the best way is asking in our Gitter channel (http://gitter.im/ArduPilot/ardupilot).

@peterbarker It seems reasonable, I'm just worried about a simple PR turning into a complex one.

**Comment by rmackay9** [comment]
@dposea, yes, if you force push it it will replace what's here which should be fine.

**Comment by peterbarker** [comment]
@dposea Any update?

**Comment by Seeelefant** [comment]
Absolutely strongly highly recommended improvement, please try to get this feature in next release.
Best
--Seeelefant

**Comment by OXINARF** [comment]
This has now been done (and merged) by #10407. Thank you for your contribution @dposea!

**Pull request closed without merging**
