### PR TITLE
Apply Ardupilot CodeStyle to Copter Mode Files

### PR DESCRIPTION
**Pull request by blaab2**
It is easier to review code changes if the Ardupilot CodeStyle is already applied.

This PR applies the Ardupilot CodeStyle to the Copter Mode Files. The Ardupilot CodeStyle is available in `${workspaceFolder}/Tools/CodeStyle/astylerc`

### CODE REVIEW

**Comment by Ryanf55** [comment]
Hi, sorry, we just can't do this to existing code in a piecemeal effort. Yes, it makes the code is more readable, but you've just ruined the history, and anyone with outstanding PR's is now going to have conflicts. It introduced a lot of work and potential bugs having to deal with conflicts

**Comment by blaab2** [comment]
Hi Ryanf55, thanks for the fast review. I didn’t get your history point. However, I see that this may lead to merge conflicts (like every PR that changes code does …). Interestingly, these conflicts should not occur if the other PRs contain well formatted code and follow the guidelines. 

If you don’t want to apply code formatting in a dedicated PR, I suggest that you close this PR and maybe keep an eye on the code formatting within the open PRs.

**Comment by Ryanf55** [comment]
Follow along this issue, where we are discussion approaches. 
https://github.com/ArduPilot/ardupilot/issues/24555

If you are interested in working on code formatting, it would be great if you could help us figure out how to call our astyle formatter from pre-commit.

**Comment by rmackay9** [comment]
I must say I like fixing up the formatting even though we didn't merge it for practical reasons

**Pull request closed without merging**
