### PR TITLE
Autotest: new autotest implementation

### PR DESCRIPTION
**Pull request by khancyr**
The idea is to bring more complet tests on ardupilot to test (idealy) all functionnalities and catch little regression or miss. 
So, this PR is still a WIP.

It is a rework of  https://github.com/ArduPilot/ardupilot/pull/5766, on which I create a base abstract class Autotest that should implement what can be shared between vehicle.
I make a first implement of the new autotest for Rover as example. 

The main point is that each vehicle will have the same base class and will do quite the same test as actually the same features aren't test on all vehicles. It will also centralize the common test, and give plenties of example on how to use ardupilot features !

### CODE REVIEW

**Comment by gmorph** [comment]
Do you know how much extra time this adds to the autotest?

**Comment by magicrub** [comment]
The good news is that it passed :) but maybe that's easier with the new test? Hmm...

**Comment by khancyr** [comment]
@gmorph If I implement all the tests I am thinking of, I think it will at least double the testing time.
But we could go with another strategie, and select only critial test on PR and do all once a week something like that. Or use travis matrix or/and stages to split the tests by vehicles.

**Comment by OXINARF** [comment]
Right now Rover isn't tested in Travis, only Copter and QuadPlane are. I think we should add a basic set for all vehicles, but we need to consider the time it takes. We then run all tests in our autotest server and I think that adding more tests is always good, even if it will take more time to complete.

**Comment by khancyr** [comment]
@OXINARF Rover is already tested on travis ^^ . It just do a square save waypoint and redo it in auto. Basic but better than nothing !

**Comment by OXINARF** [comment]
Apparently I merged that patch but I didn't remember it :smile: Well, great it is checking something!

**Comment by khancyr** [comment]
closed in favor of https://github.com/ArduPilot/ardupilot/pull/7589

**Pull request closed without merging**
