### PR TITLE
Fixed incorrection assumptions on return of snprintf/vsnprintf

### PR DESCRIPTION
**Pull request by tridge**

### CODE REVIEW

**Comment by magicrub** [comment]
seems pretty important to retain the error results

**Comment by OXINARF** [comment]
The ones for hal.util aren't actually needed because our implementation doesn't follow the spec, it returns what was effectively written and not what would be if there was space - doesn't hurt either though.

**Comment by tridge** [comment]
> Note that these aren't taking into account that these functions can return a negative value on error.

how? Our hal.util->snprintf always returns a >= 0 value. The asprintf varients can return -1 on allocation failure, but the non-allocating ones can't

**Comment by peterbarker** [comment]
@tridge I was just noting that we're not following spec on returning 0 - and we just saw that not following spec can seriously bite.

I don't intend this as a blocker.  It's just more institutional knowledge that "our" `snprintf` never fails.

**Comment by tridge** [comment]
> I was just noting that we're not following spec on returning 0 - and we just saw that not following spec can seriously bite.

under what circumstances can the linux snprintf or vsnprintf return a negative number?
The ones that output to a file can (eg. vfprintf), but as far as I know the ones that write into a pre-allocated string can't return a negative number

**Comment by peterbarker** [comment]
@tridge Practically I very much doubt they do.  And I don't think I've ever seen anybody test their results for being negative.  Doc says they can, and they do return signed, however.

**Pull request merged**
