### PR TITLE
Copter: added support for IST8310 external compass to linux_blue

### PR DESCRIPTION
**Pull request by dorovl**
Hello,

While the Ublox Neo-M8N GPS with HMC5883L compass from Hobbyking is now discontinued, there are lot of Ublox Neo-M8N GPS with IST8310 compass on the market, like this one: https://www.aliexpress.com/item/32895770315.html. Therefore, it was worth to add support for the IST8310 external compass to BeagleBone Blue.

Please find below some tests:

image3

image4

image2

Regards, Vlad

### CODE REVIEW

**Comment by tridge** [comment]
this shouldn't be needed in master as BLUE has HAL_PROBE_EXTERNAL_I2C_COMPASSES which probes for all types of external compasses.
Have you tested if it already works with master?

**Comment by dorovl** [comment]
Hi Andrew,

I tested the BLUE on master. It seems to work, however, the AP_Compass_test example produces a segmentation fault. See tests below:

picture1

picture2

Regards, Vlad

**Comment by OXINARF** [comment]
**NOTE: this is targeting Copter-3.6 branch!**

**Comment by tridge** [comment]
@OXINARF ahh, thanks, I didn't notice.
@dorovl copter 4.0 will be starting to go out quite soon, so I don't think this change is likely to make it into 3.6. We should fix the example code though. Can you do a debug build, get a backtrace with gdb and do a patch to fix the segv in master in the test code?

**Comment by dorovl** [comment]
OK Andrew, I will try.

**Comment by dorovl** [comment]
Hi Andrew,

I tried to build the flight controllers in debug mode after updating today, but I have a link error.

After doing :

```
./waf configure --board=blue --debug
./waf

[ 878/1047] Linking build/blue/bin/arducopter
lib/libArduCopter_libs.a(AP_KDECAN.cpp.0.o): In function `AP_KDECAN::loop()':
/home/debian/sd_tmp/ardupilot/build/blue/../../libraries/AP_KDECAN/AP_KDECAN.cpp:419: undefined reference to `AP_KDECAN::SET_PWM_MIN_INTERVAL_US'
collect2: error: ld returned 1 exit status
```
image1

I will build the examples with:

`./waf examples`

I think this will work.

Regards, Vlad

**Pull request closed without merging**
