### PR TITLE
AP_NavEKF3: reduce updates to wind estimates while dead reckoning

### PR DESCRIPTION
**Pull request by rmackay9**
This PR is work from @priseborough and it disables learning of wind estimates while the vehicle is dead reckoning.  This has been tested in SITL and below are before vs after pictures of the EKF3's wind estimates.  The red line shows when the GPS is disabled.
master-before
prise-after

This does not seem to make a huge difference to where the vehicle actually lands.  Below is a SITL test with the Copter dead-reckoning failsafe set to 50 sec (meaning the EKF keeps trying to estimate position for 50sec after loss of GPS).

prise-after-sitl-map

### CODE REVIEW

**Comment by pavloblindnology** [comment]
@rmackay9 Thanks for this PR.
10x noise scaling means 10x slower wind updating change, which still can lead to some unrealistic values eventually. I think much higher value can be used - like 100x, 1000x, to almost completely eliminate any updates.
In your SITL test you have weak wind 2-3m/s and relatively short flight time. So, the difference in +-1m/s doesn't influence the result too much. For longer flights the wind estimation error could be much higher without this PR.

**Comment by priseborough** [comment]
Increasing observation noise will have the unwanted side effect of reducing how much the error growth in other states is constrained. I would try experimenting with a few other options before merging this option. For example:

a) Setting wind velocity state process noise to zero
b) Setting wind velocity state variances to 0
c) Setting wind state Kalman gains to 0

If you share a replayable log illustrating the problem I can quickly test these options.

**Comment by rmackay9** [comment]
@priseborough,

Txs very much for the feedback.  I've created a replay-able log here using master https://www.dropbox.com/s/oour00jjfs4jg39/randy-wind-est-22Aug2022.zip?dl=0

In this log you can see where the GPS is disabled by checking for RC9 being pull high (to 2000).  From then on you'll see that the wind estimates continue to be updated.  Here is a graph of RCIN.C9, XKF2.VWN and VWE
image

**Comment by priseborough** [comment]
@rmackay9 I've pushed a patch to here that locks in the wind state estimates when using drag fusion to dead reckon. In the  supplied log the wind stater estimates aren't that good to start with, but with the patch they don't change after dead reckoning starts. 

https://github.com/priseborough/ardupilot/tree/pr-dragFusionDeadReckoning

Screen Shot 2022-09-04 at 2 31 45 pm

This will not always make the dead reckoning more accurate and there is an alternative approach when we set process noise to zero which will allow some additional change to the wind states.

**Review by priseborough — APPROVED** [review]

**Comment by rmackay9** [comment]
This has now been tested successfully on a real vehicle.

**Review by priseborough — APPROVED** [review]

**Comment by pavloblindnology** [comment]
@rmackay9 @priseborough 
Hi. I've been playing with failsafe dead-reckoning in SITL with Copter-4.4 (I've merged this PR to the branch, since it's only in master currently).
And have found interesting results when dead-reckoning for a while.
The idea is to have copter return-to-launch from a distance of few km (FS_DR_ENABLE = RTL, FS_DR_TIMEOUT > 120 sec). The particular scenario described has simulation wind set to 0 m/s, home position ~4km straight South, and initial yaw straight North. Once I turn GPS off in simulation, everything goes well, the dead-reckoning starts and copter pitches backward with no roll (since the inital orientation is away from the home), and starts moving backward toward the home. As shown in the picture.
Screenshot from Screencast 2023-05-16 18:20:43 mp4
But then the roll starts increasing until in about 100-200s (depends quite randomly on simulation) it reaches max values, while the pitch decreases almost to 0. Though the estimated copter position is still along the straight line toward the home, with yaw right away from it


When simulated actual yaw reaches values close to 90 or 180, Ardupilot switches to DCM, changes simulated actual yaw, and almost instantly switches back to EKF. The pitch & roll are now again close to what they are expected to be (max positive pitch, 0 roll).


And the cycle continues till the next switch to DCM. Note, that this time estimated ground speed (as well as aerial) is almost zero, though pitch & roll are not.


In some time IMU stops aiding and estimated position starts moving to the left while roll is max positive


And then dead-reckoning stops, we have EKF variance failsafe and copter lands.


The behavior I expect in this particular scenario is that the copter should pitch backward and estimated position move along the straight line toward the home, with estimated yaw and roll close to 0. The actual simulated position/yaw should deviate from this straight line, of course, based on wind estimation erros, etc.

Do I understand right or what do I miss here? Could you please comment.
Interestingly, with non-zero simulation winds (tested with 4 m/s, 90 deg), the behavior is similar but more stable.
The full logs and video can be found [here](https://drive.google.com/drive/folders/1xICNM-VE8Usn0cvWxR9ydgOCe7LKRiO0?usp=share_link).

**Comment by pavloblindnology** [comment]
Graph of simulated RPY shows that EKF to DCM switch happens somewhere near yaw transitioning between 0 and 360. Can it be connected?
SIM RPY

Also noted, that simulated yaw rate (shown in mavexplorer) doesn't account for transitioning of yaw from 0 to 360 and gives spikes. Is it expected?
SIM Yaw YawRate

**Comment by rmackay9** [comment]
@pavloblindnology,

Thanks for testing this.  I don't really have any answers for you but it might be good to set "map set showsimpos 1" to see where the vehicle actually is.  I suspect it is not even close to where the EKF thinks it is.

I think the time limit for this wind estimate based solution is somewhere between 30sec and 60sec so I'm not too surprised to hear that above 100sec it's not working well.

It's a guess but I don't think the behaviour is related to the yaw passing through 0~360.  I suspect if the test was done with the vehicle flying East or West the vehicle would fly very similarly but the graphing might look better.

Thanks again.

**Comment by pavloblindnology** [comment]
> Thanks for testing this. I don't really have any answers for you but it might be good to set "map set showsimpos 1" to see where the vehicle actually is. I suspect it is not even close to where the EKF thinks it is.
Simulated position coincides with gps position, which is shown by default. It's just the simulated yaw which doesn't - it coincides with EKF yaw (north) in my case. So, the pictures above show the actual simulated position.

> I think the time limit for this wind estimate based solution is somewhere between 30sec and 60sec so I'm not too surprised to hear that above 100sec it's not working well.
> 
> It's a guess but I don't think the behaviour is related to the yaw passing through 0~360. I suspect if the test was done with the vehicle flying East or West the vehicle would fly very similarly but the graphing might look better.
Tested with East/West - yes, behavior is similar.

What surprises me is that the behavior is very non-deterministic. Sometimes everything goes as expected even after 100-300sec of DR - EKF thinks it goes straight home, so it just keeps max pitch with no roll (under condition that copter's nose is away from home).
But more often it either starts decreasing pitch (even to the max value of opposite sign - from +30 to -30deg, e.g.) and increasing roll. In this case simulated position slows down and then starts moving away from home.
Or, EKF keeps pitch at max and almost zero roll, but EKF position slows down and then stands still, while simulated position moves toward home as expected.

**Comment by pavloblindnology** [comment]
> Or, EKF keeps pitch at max and almost zero roll, but EKF position slows down to zero and then accelerates in the opposite direction, while simulated position moves toward home as expected. How is it possible, that EKF has max positive pitch, zero wind, but moves in the opposite direction?

The plot shows that in this case the "Innovation in vehicle drag acceleration (X-axis component)" continues to change, though the inputs (pitch, acceleration, gyros) are constant.
ekf_vel_slow_down_with_constant_pitch

**Pull request merged**
