### PR TITLE
AP_Compass:Add QMC5883L internal i2c bus support

### PR DESCRIPTION
**Pull request by ljwang1102**
add QMC5883L internal i2c bus support, QMC5883 and HMC5983 have the same size, pin,So the circuit does not need to be modified,then it need internal i2c bus support

### CODE REVIEW

**Comment by OXINARF** [comment]
@ljwang1102 You need to rebase this on master, no merge commits are allowed. Also, please follow our [contribution guidelines](http://ardupilot.org/dev/docs/submitting-patches-back-to-master.html), specially the commit message format.

**Comment by ljwang1102** [comment]
Sorry, I'll resubmit it

**Comment by ljwang1102** [comment]
I'll closed

**Comment by Pedals2Paddles** [comment]
You can actually leave it open and just repush the branch once it is cleaned up.  Every time you repush the branch, the PR Is updated to reflect the latest.  It even restarts the checks.

**Pull request closed without merging**
