### PR TITLE
GCS_MAVLink: fixed critical error on prefight cal ops

### LINKED ISSUE #15176: Sub: after calibrate pressure I get "Prearm: internal error (0x8000)"
**Issue details**

After calibrate pressure I get "Prearm: internal error (0x8000)"

**Version**
4.0.0 and up

**Platform**
[X] Submarine

**Hardware type**
Pixhawk 1 and Pixhawk 4 mini

**Logs**
After calibrate pressure I get "Prearm: internal error (0x8000)"
I would have to reboot to get error to clear.
I was able to fix the issue by commenting out lines 215-225 of AP_Baro.cpp
error 0x8000 is main loop stuck.. 
Seems this code is locking up the main loop

`    for (uint8_t i = 0; i < 10; i++) {
        uint32_t tstart = AP_HAL::millis();
        do {
            update();
            if (AP_HAL::millis() - tstart > 500) {
                AP_BoardConfig::sensor_config_error("Baro: unable to calibrate");
            }
            hal.scheduler->delay(10);
        } while (!healthy());
        hal.scheduler->delay(100);
    }`

Had issue with bar30 sensor keller sensors. 
several version of ardusub 4.0.0
Using both pixhawk1 and 4 mini

### PR DESCRIPTION
**Pull request by jaxxzer**
fix #15176

### CODE REVIEW

**Comment by peterbarker** [comment]
I'm a bit confused as to why you're pulling back all of these other patches here.

AFAICS they don't relate to the `-mno-thumb-interwork` issue - but I could probably dig up the patch for that one with a little work.  Basically ought not be using an x86 compiler to create an stm32 binary :-)

**Comment by jaxxzer** [comment]
@peterbarker Yes I'm trying get ci to finish. I thought it might be some environment variables changed in the travis dashboard. I can't figure it out...

**Comment by peterbarker** [comment]
Oh, I remember this one!

There's a syntax error in .travis.yml

```
      env: CI_BUILD_TARGET="sitltest-rover sitltest-sub""
```


I did fix that in master - can't find the relevant patch, 'though

**Comment by peterbarker** [comment]
@jaxxzer was fixed in cefd30a0864aad39968934be26231330cf96b7fd

... without comment, even in the extended commit description... oh well.

**Comment by jaxxzer** [comment]
i'll get the ci in another pr

**Pull request merged**
