### PR TITLE
Plane: fixed use of FF for surfaces in tailsitters

### PR DESCRIPTION
**Pull request by tridge**
This fixes the missing feed-forward term for quadplane tailsitters when in hover. The FF is the dominant term for pitch and yaw, so missing this explains why tuning was so hard

### CODE REVIEW

**Comment by IamPete1** [comment]
Looks like this is also a issue for tiltrotors, might be better to include it in the original getter functions, looks like those are the only uses anyway. 

I thinks this is another of my bugs, maybe from when I added bicopter support to copter. It would have effected the control surfaces only, tilt motors would still be getting FF.

**Comment by IamPete1** [comment]
In fact it looks like it was a by-product of https://github.com/ArduPilot/ardupilot/pull/11673

**Review by IamPete1 — APPROVED** [review]
LGTM, we should double check tilt - rotors too

**Comment by jmachuca77** [comment]
So are TVBS affected too?

**Comment by IamPete1** [comment]
@jmachuca77 Not the vectoring, but the control surfaces are.

**Pull request merged**
