### PR TITLE
Add new default parameters file for ModalAI D0013 drone

### PR DESCRIPTION
**Pull request by katzfey**
A baseline set of default parameters that can be used to fly the D0013 drone.

### CODE REVIEW

**Comment by rmackay9** [comment]
Great to see this @katzfey!

No big deal of course but it might be good to squash the commits together.  Not a blocker though

**Comment by katzfey** [comment]
Okay, yeah, sorry, I'm still a noob!

**Comment by katzfey** [comment]
Should I close it and resubmit?

**Comment by rmackay9** [comment]
@katzfey,

It should be possible to squash them together and then force push.  We have a wiki page here about it https://ardupilot.org/dev/docs/git-interactive-rebase.html

**Comment by tridge** [comment]
looks like it doesn't have a rate tune yet?

**Comment by katzfey** [comment]
Rebased, squashed commits, and added tune parameters

**Review by tridge — APPROVED** [review]

**Pull request merged**
