### PR TITLE
Tools:autotest, frsky passthrough fix for long status text message test

### PR DESCRIPTION
**Pull request by yaapu**

### CODE REVIEW

**Comment by yaapu** [comment]
there is still an issue with frame 0x5007, it takes too long to get a valid poll for frametype i.e. param type=1

**Comment by peterbarker** [comment]
```
Tools/autotest/common.py:9037:9: F841 local variable 'sent_request' is assigned to but never used
```

**Comment by yaapu** [comment]
> ```
> Tools/autotest/common.py:9037:9: F841 local variable 'sent_request' is assigned to but never used
> ```

fixed, thanks

**Comment by peterbarker** [comment]
Merged, thanks!

**Pull request merged**
