### PR TITLE
Add missing build defines

### PR DESCRIPTION
**Pull request by amilcarlucas**

### CODE REVIEW

**Comment by rmackay9** [comment]
Looks good to me, just needs a rebase I think and then we can merge.

**Comment by rmackay9** [comment]
the merge commit looks a bit weird.  I guess resolving the conflicts is a WIP..

**Comment by amilcarlucas** [comment]
Yes, @rmackay9 rebasing using the webgui gives strange commits.
rebased using the mormal way now

**Comment by OXINARF** [comment]
Merged, thanks!

**Pull request merged**
