### PR TITLE
Copter: precland: don't use altitude from bad location

### PR DESCRIPTION
**Pull request by peterbarker**
We go through here when we don't have our current location.

### CODE REVIEW

**Comment by rmackay9** [comment]
@peterbarker, this looks like the right thing to do but i'm wondering how this came up?  Was it just through inspection of the code that this was noticed or was there a user report?

**Comment by peterbarker** [comment]
On Sun, 1 Dec 2019, Randy Mackay wrote:

> @peterbarker, this looks like the right thing to do but i'm wondering how this came up? Was it just through inspection of the code that this was noticed
> or was there a user report?

This came up as part of testing rangefinder serial drivers in autotest.

https://github.com/ArduPilot/ardupilot/pull/12943

I was very surprised when it fell over!  It fell over because of the 
sanity check in AP_Location that we don't use an uninitialised location 
for anything.

I believe the Wasp rangefinder was reporting itself as NoData at the time 
- that's another patch in that PR above to fix the simulation....

**Comment by peterbarker** [comment]
@rmackay9 Oh, I'd also like to point out that we've just set the height from an invalid value, so life still isn't all roses :-)  I believe we'll never use that value because rangefinder_alt_ok won't be set.

What I did here was a simple fix to not have the thing use the invalid value.

However, tracing things through, it seems that if the rangefinder range is not valid we'll never use the passed-in-value in AC_PrecLand, so I'm really not sure how the terrain_use() clause is actually useful.

Was the intent to allow precision landing in the case you have no rangefinder but do have the terrain database?

**Comment by rmackay9** [comment]
@peterbarker, yes, I think the intention was to allow it to use the terrain database if no range finder is available.  In practice though I wonder how well that can possibly work because it's very likely to be off by a couple of meters.

**Comment by peterbarker** [comment]
@rmackay9 So yeah:

```
commit e311139a21984166f373589617e547a21941c72c
Author: Jonathan Challinger <mr.challinger@gmail.com>
Date:   Thu Jul 7 10:56:24 2016 -0700

    Copter: use terrain alt for precland if rangefinder is unavailable
```

But a week later f2ef8eec8cd00be054b59bb03c6b6aa327223a8a and 7405f82d619b394211a1ec33a900f4ba62ab2ec1 killed it.

**Comment by rmackay9** [comment]
Merged, thanks!

**Pull request merged**
