### PR TITLE
ChibiOS: update to stable_18.2.x

### PR DESCRIPTION
**Pull request by tridge**
This updated the ChibiOS version to stable 18.2.x. It is based on work by @bugobliterator with some changes by me

### CODE REVIEW

**Comment by amilcarlucas** [comment]
ChibiOS 18.2.1 is out for over one month now, and it contains a lot of bugfixes. Is it hard to switch to it ?
Why was it not used instead ?

**Comment by tridge** [comment]
It actually includes the latest 18.2.x updates, sorry for the poor msg

**Comment by tridge** [comment]
@bugobliterator I have updated this on master, and tested on:
 - KakuteF4
 - fmuv5
 - mini-pix
 - CubeBlack
Looking good so far
Note that I have added an --enable-asserts configure option, to make debug builds with ChibiOS asserts easier

**Comment by tridge** [comment]
I have switched to 32 bit intervals. That should be plenty, even for boards with 16 bit timers, as we use loops for long sleeps.
It makes the code considerably smaller and faster (especially for the bootloader)

**Pull request merged**
