### PR TITLE
AP_Scripting: add support for getting fw version

### PR DESCRIPTION
**Pull request by IamPete1**
adds support for `FWVersion:fw_string()` returning `ArduCopter V4.2.0-dev (922dc8c0)`

### CODE REVIEW

**Review by TunaLobster — APPROVED** [review]
Looks good to me. I can add the fields that Randy was talking about later and take the discussion on that. Thanks! I wasn't sure how much of a corner case this was for it to warrant a generator change.

**Review by WickedShell — CHANGES_REQUESTED** [review]
I'd prefer to see us instead offer 4 different function calls:
  1. vehicle name (as a string I guess), 
  2. major version
  3. minor version
  4. git hash

As far as I can tell these are the only things we really want out of the version string, and to do anything useful and programmatic with them a script will have to do a lot of string splitting and parsing, and we can very easily break that in the future. If you want a version API that needs to be held consistent, or the API for ID'ing the version won't be useful. (Particularly if we end up with a bunch of different interpretations being deployed)

**Comment by peterbarker** [comment]
On Tue, 30 Nov 2021, WickedShell wrote:

> I'd prefer to see us instead offer 4 different function calls:
>
>  1. vehicle name (as a string I guess),
>  2. major version
>  3. minor version
>  4. git hash
> 
> As far as I can tell these are the only things we really want out of the version string, and to do anything useful and programmatic with them a script will have to do a lot of string splitting and parsing, and we can very easily break that in the future. If you want a version API that needs to be held consistent,
> or the API for ID'ing the version won't be useful. (Particularly if we end up with a bunch of different interpretations being deployed)

I'd also rather the LUA scripts not have to parse the text.

**Comment by IamPete1** [comment]
added support for feild alises and the requested bindings. 

We now have these:
```
-- desc
---@class FWVersion
FWVersion = {}

-- get field
---@return string
function FWVersion:hash() end

-- get field
---@return integer
function FWVersion:patch() end

-- get field
---@return integer
function FWVersion:minor() end

-- get field
---@return integer
function FWVersion:major() end

-- get field
---@return integer
function FWVersion:type() end

-- get field
---@return string
function FWVersion:string() end
```

**Review by TunaLobster — APPROVED** [review]

**Review by tridge — APPROVED** [review]

**Comment by tridge** [comment]
@WickedShell please re-review, thanks!

**Comment by peterbarker** [comment]
@IamPete1 needs a rebase

**Pull request merged**
