### PR TITLE
AP_HAL_ChibiOS: add 8 bi-directional dshot channels to KakuteH7-Wing

### PR DESCRIPTION
**Pull request by andyp1per**
Requested by Holybro

### CODE REVIEW

**Comment by Hwurzburg** [comment]
when you suggested bdshot when I was doing the hwdef, you only said 4 outputs....why is this possible now?

**Comment by andyp1per** [comment]
To save DMA channels, but it seems ok. If we do need to save more channels removing dshot from 9-10 would help

**Comment by Hwurzburg** [comment]
I sent Holybro this to test since I am away....

**Comment by andyp1per** [comment]
> I sent Holybro this to test since I am away....

Thanks - yes it was Vince asking for it

**Review by tridge — APPROVED** [review]

**Pull request merged**
