### PR TITLE
AP_NavEKF2/3: replace blank prearm failure message with "EKF2/3 still initialising"

### PR DESCRIPTION
**Pull request by rmackay9**
This resolves issue https://github.com/ArduPilot/ardupilot/issues/11800 found during Copter-4.0 testing in which a blank "PreArm:" pre-arm failure message was appearing.

The issue had a similar symptom to the one fixed in this PR but is actually separate: https://github.com/ArduPilot/ardupilot/pull/12651

This has been tested on a CubeBlack flight controller with a wiped eeprom (the best way to make the issue appear is to clear all parameters) using EKF2 and EKF3.

EKF2 testing:
ekf-prearm-msg

EKF3 testing:
ekf3-prearm-msg

If @priseborough or someone else has a better idea for the string then I'm very happy to change it

### CODE REVIEW

**Comment by peterbarker** [comment]
So this will be a divergence from the same fix in master.

1c187d8feb78a1c71311baa8458f52b6cccd6dba

and

3619856fc9bac3744d83c7b9a0127e0f1f56f667

Not sure which message is better.  The one in master is more specific.

**Comment by rmackay9** [comment]
@peterbarker are these fixes in master already or in some other PR?  If they're in master already then I'm surprised because I've been testing with master and I'm seeing blank PreArm messages.

**Comment by peterbarker** [comment]
> @peterbarker are these fixes in master already or in some other PR? If they're in master already then I'm surprised because I've been testing with master and I'm seeing blank PreArm messages.

OK, my bad.  Different code path.

**Comment by rmackay9** [comment]
Well, I think this is low risk so I've merged this.

**Pull request merged**
