### PR TITLE
HAL_ChibiOS: added support for TBS-Colibri-F7

### PR DESCRIPTION
**Pull request by tridge**
This is a fmuv5 board varient.

This has not been flight tested, and peripherals have not been tested (due to lack of cables)

Issues:
 - [x] logging to microSD
 - [x] IMU heater

### CODE REVIEW

**Comment by lvale** [comment]
Regular DF13 accessories

**Comment by tridge** [comment]
any idea where I can find the pinouts?

**Comment by lvale** [comment]
On the DF13 plugs, from a casual measurement, the pinouts appear to be the same as defined by Dronecode/Pixhawk style boards. The black 12 pin plug, I'm trying to locate them on the tbs site, but apparently there are several versions.... :(

**Comment by lvale** [comment]
Not sure on the 12V pin mentioned, there are notes on the TBS site to cut that pin so it must be (hope) a Not Connected/Not used

screenshot 2019-02-17 at 11 28 13

**Comment by lvale** [comment]
Some more educated guesses.....

untitled 2

**Pull request merged**
