### PR TITLE
Copter: tidy failsafe action handling

### PR DESCRIPTION
**Pull request by peterbarker**
Mode changes will not work when mode not compiled in

### CODE REVIEW

**Review by andyp1per — APPROVED** [review]

**Review by rmackay9 — APPROVED** [review]
Looks good but I'd like to check that some testing has been done?  I'm 99% sure it's fine but just to be sure..

**Review by IamPete1 — APPROVED** [review]
LGTM.

I wonder if we should have a arming check if the user has set the failsafe action to a mode that does not exist. Or SRTL with SRTL disabled.

**Comment by peterbarker** [comment]
> Looks good but I'd like to check that some testing has been done? I'm 99% sure it's fine but just to be sure..

Yes, I've compiled without RTL and it behaves appropriately.  Only user-visible change is they don't see an attempt to change into an unknown mode before the enter LAND.

**Comment by peterbarker** [comment]
> LGTM.
> 
> I wonder if we should have a arming check if the user has set the failsafe action to a mode that does not exist. Or SRTL with SRTL disabled.

I think that's would be a good check.

I think there might some cleanup available - we've got a series of defines in here which are used for the parameter value - but we might be able to use the FailsafeAction enumeration instead, which might be nice.

**Pull request merged**
