### PR TITLE
default to MavLinkV1 on CubeSolo

### PR DESCRIPTION
**Pull request by khimaros**
see also https://github.com/ArduPilot/ardupilot/issues/22155

### CODE REVIEW

**Comment by khancyr** [comment]
Hello, could you update your commit message to add "AP_HAL_Chibios: " at start as per our commit rules ?
Thanks

**Comment by khimaros** [comment]
@khancyr done

**Comment by tridge** [comment]
@davidbuzz I did a PR to the router to understand MAVLinkv2 many many years ago (3DR days). Is that not merged yet?

**Comment by tridge** [comment]
@davidbuzz up to you as maintainer of solo for merge

**Comment by davidbuzz** [comment]
> @davidbuzz I did a PR to the router to understand MAVLinkv2 many many years ago (3DR days). Is that not merged yet?

unfortunately solo remains fundamentally stuck at mavlink1 due to the gimbal only supporting mavlink1, the routing/forwarding code in the tx's linux box still being on mavlink 1, etc.   a *concerted* effort update these was made by me more than a year ago, and I failed, as there's *so many* moving parts that need to be handled at the same time, and it was beyond my skillset+motivation combo.

 - good news, the gimbal code is open source, so it *could* now be upgraded to mav2, but again someone's got to want it badly enough, and that's not currently me.   I *did* succeed in compiling the gimbal sources, and so i know how.  :-)

**Comment by davidbuzz** [comment]
...I'd just merge this and leave solo a v1 till someone wants it badly-enough to take it on.

**Comment by davidbuzz** [comment]
.. both peter and i have made attempts at parts of this at diffeeent times.

**Review by davidbuzz — APPROVED** [review]

**Comment by khimaros** [comment]
thank you @davidbuzz -- since i prepared this PR, i spoke further with @JBB2068 who highlighted some additional parameters which he has been using with his releases for Solex. i've tested two Solos with those builds for ~2-3 hours of total flight time without issue.

@davidbuzz would you be willing to approve a PR which pulled in the full set of modified default params listed here? https://github.com/user-attachments/files/16092996/default.params.txt -- if so, i can either update this PR or create a new one to follow up.

**Comment by tridge** [comment]
@davidbuzz the problem is that we are becoming more dependent on v2. Over time more and more things won't work with v1

**Comment by tridge** [comment]
discussed on the call, decided to merge

**Comment by davidbuzz** [comment]
right now, the best answer for Solo is to stay on mavlink1 until such time as someone is able to do a big and well-tested PR across the arto-tx code, arto-rx code,gimbal, gcs-software,and the 'cubesolo' ArduPilot target running on it as well, all at the same ,time, and test it all together ensuring that forwarding of the gimbal mavlink to the ground works, that the GCS/s are able to consume the forwarded packets like they do now, and all the corner cases are properly handled.... its not just a "ardupilot" problem.

**Comment by davidbuzz** [comment]
... and that will *probably* mean upgrading the gimbal code to mavlink2 as well

**Comment by davidbuzz** [comment]
"Over time more and more things won't work with v1" - yep, agreed, its an imperfect solution, but solo "right now" needs v1, and till someone scratches that itch, its gonna stay that way.     If ardupilot's "opensolo" target stops working with actual solo's, then opensolo will just stop using it. It has before, and the world didn't end.   eg for a long while 4.0.7 was where it was at for solo user/s.     I was able to (eventually) move most solo user/s past that, and other people like Matt Lawrence and Jon Brotherton have helped push solo forward where they can as well. .... but ardupilot needn't worry about solo too much, if u need to break it, we'll work it out.

**Pull request merged**
