### PR TITLE
Param units and fixes

### PR DESCRIPTION
**Pull request by amilcarlucas**

### CODE REVIEW

**Comment by OXINARF** [comment]
You've splitted the commits but you didn't address my other comments in the previous PR.

**Comment by amilcarlucas** [comment]
I missed those, sorry.

These are the stats from ArduCopter:
% 4   Percent 3 percentage 2
1/s 1 Hz 49
Amps 2
Amps/Volt 2
Centi-Degrees 12  Centi-degrees 3
Centi-Degrees/Sec 1
Centi-Degrees/Sec/Sec 3
Centimeters 6 centimeters 12 cm 2
Centimeters/Second 1 cm/s 8
Degrees 18
Microseconds 2 PWM 3 pwm 65
Milliseconds 1 msec 8 milliseconds 7 ms 2
Offset per Amp or at Full Throttle 9
Percent*10 5
Radians 4 rad 2
Seconds 6 seconds 6
Volt 2 Volts 9
Watts 1
cm/s/s 6
cm/s/s/s 1
cs 2
deg/s 1  deg/sec 1
degrees 3
degrees celsius 1  degreesC 1
gauss 2
gauss/s 4
kilometers 1
m 42   meters 12 Meters 4
m/s 9
m/s/s 14
m/s/s/s 2
mAh 3
meters/Volt 4
millibar 1
milligauss 9
pascals 1
rad/s 15
rad/s/s 2
Total 403

The other vehicles will add even more confusion to this mess.

PWM is not a unit as far as I know, microsecond is. Can I fix it ?

**Comment by OXINARF** [comment]
> PWM is not a unit as far as I know, microsecond is. Can I fix it ?

True, but I think people understand it better.

**Comment by amilcarlucas** [comment]
Should I use PWM or pwm ?

**Comment by OXINARF** [comment]
> Should I use PWM or pwm ?

I think it doesn't really matter. According to your stats, pwm is the most used, so I would probably go with that, but it's fine go to with PWM.

**Comment by amilcarlucas** [comment]
All changes done

**Comment by OXINARF** [comment]
Merged, thanks!

**Pull request closed without merging**
