### PR TITLE
Copter: factor out takeoff_trigger from althold, sport and loiter

### PR DESCRIPTION
**Pull request by peterbarker**
This removes common code blocks from three different flight modes and makes the logic easier to read through.

### CODE REVIEW

**Comment by peterbarker** [comment]
@OXINARF Resolved the conflict.

I'm tending towards the static methods ATM, but as you point out this may cause issues down the line.  Those problems *can* also be resolved by poking the `copter.` object - that feels kinda wrong, 'though.

**Comment by OXINARF** [comment]
> I'm tending towards the static methods ATM, but as you point out this may cause issues down the line. Those problems can also be resolved by poking the copter. object - that feels kinda wrong, 'though.

Yeah, that's why I don't quite like that approach, especially as, technically, static methods shouldn't depend on any non-static objects/methods.
I think I would be more supportive of a CommonModeState object shared by all modes.

**Comment by peterbarker** [comment]
@OXINARF I assume the discussion of static-vs-something-else shouldn't hold up this being merged.  As it stands this is just factoring.

**Comment by OXINARF** [comment]
Absolutely not, it was just waiting for CI to pass.

Merged, thanks!

**Pull request merged**
