### PR TITLE
AP_RangeFinder: Clarify the purpose of input registers

### PR DESCRIPTION
**Pull request by muramura**
1. I clarified the unknown register from the following specification.
2. I fixed the byte order of the timestamp.

Byte 2: MODBUS specification "Byte Count" is defined in the response table on page 16.
Byte 3-6: "20: Least significant 16 bits of timestamp." "21: Most significant 16 bits of timestamp." Is defined on page 23 of the Leddar One User Guide.
Byte 9-10: "23: Number of detections" is defined on page 23 of the Leddar One User Guide.

MODBUS SPEC:
http://www.modbus.org/docs/Modbus_Application_Protocol_V1_1b3.pdf

Leddar One User Guide
http://www.robotshop.com/media/files/pdf2/rb-led-02-04_-_54a0025-2_leddar_one_user_guide_-_2016-09-01.pdf

### CODE REVIEW

**Comment by magicrub** [comment]
If number_detections can exceed 8 bits, it should be changed to 16 bits so that we can detect and correctly handle it.

// number of detections (index:10)
     number_detections = read_buffer[LEDDARONE_DETECTION_DATA_NUMBER_INDEX];

**Comment by muramura** [comment]
@magicrub san Comment Thank you.
I will check the operation.

**Comment by muramura** [comment]
I variable the number_detections variable type from uint8_t to uint16_t.
This is defined as 16 bit big endian by specification.
The following is the test result.
====
Additional address=01
Function code=04
Byte count=14
Least significant 16 bits of timestamp=5A 30
Most significant 16 bits of timestamp=00 41
Temperature in 1/256th of a Celsius=24 B3
Number of detections=00 01 ★
Distance in millimeters of first detection=01 56
Amplitude of first detection=80 41
Distance in millimeters of second detection=00 00
Amplitude of second detection=00 00
Distance in millimeters of third detection=00 00
Amplitude of third detection=00 00
CRC=DD 28
===
number_detections=0001 ★

**Comment by OXINARF** [comment]
I've pushed the first commit on this. The second one isn't needed because there are only a max of 3 detections - so it's fine just reading the least significant part of the register.

**Pull request closed without merging**
