### PR TITLE
Tools: added my name to GIT_Success

### PR DESCRIPTION
**Pull request by VineetTambe**

### CODE REVIEW

**Review by rmackay9 — CHANGES_REQUESTED** [review]
@VineetTambe,

Looks OK but an you change the commit to start with "Tools: "?  To be clear I mean the commit title not the PR title.

**Comment by rmackay9** [comment]
Txs, can you squash the commits?

**Comment by rmackay9** [comment]
@VineetTambe,

Looks like you'll need to do a "rebase" on master and then squash the commits.

**Comment by VineetTambe** [comment]
@rmackay9 
Hopefully, I have done what you asked for. Thanks for understanding!!

**Comment by khancyr** [comment]
@VineetTambe hello, there is still some errors. As you can see, you bring some other change in your PR. You need to update your master branch before doing a rebase. See https://ardupilot.org/dev/docs/git-rebase.html

At the end, you should have sole commit with only your change on GIT_Success

**Comment by VineetTambe** [comment]
done

**Comment by rmackay9** [comment]
@VineetTambe, I'm afraid the commit still includes changes to other files besides Git_Test.txt..

**Comment by VineetTambe** [comment]
Is this correct?
If this doesn't work I think I should start clean by:

1. deleting my branch
2. rebasing the master again 
3. creating a new branch 
4. making my change to GIT_Success.txt
5. commit 
6. force push

should I go ahead with this?

**Comment by rmackay9** [comment]
@VineetTambe, looking good now. merged!

**Comment by VineetTambe** [comment]
Yay !!!

**Pull request merged**
