### PR TITLE
Add SITL support for AP Periph using new CAN setup

### PR DESCRIPTION
**Pull request by bugobliterator**
AP Periph GPS module can now be built in SITL. using following commands:
`./waf configure --board sitl_gps`
`./waf AP_Periph`

Then simply AP_Periph binary needs to be run along with main vehicle SITL configured to use CAN GPS.

Additional commands to enable single Virtual CAN in linux systems:
```
sudo modprobe vcan
sudo ip link add dev vcan0 type vcan
sudo ip link set up vcan0
```

### CODE REVIEW

**Comment by khancyr** [comment]
shouldn't we implement a clock server for better management of SITL instance clocks ?
I did a fast reading, and the SITL part seems OK and well constrain, so the impact on the current SITL should be low or null

**Comment by bugobliterator** [comment]
> shouldn't we implement a clock server for better management of SITL instance clocks ?

Yes, I agree, that would be best solution. We can work on that bit, and try getting rid of "native clock" methods eventually.

**Review by tridge — CHANGES_REQUESTED** [review]
also add usage for SITL with AP_Periph in Tools/AP_Periph/README.md

**Comment by magicrub** [comment]
Needs a rebase. I'll be testing it. I'm excited to get this in.

**Review by tridge — APPROVED** [review]

**Comment by tridge** [comment]
very impressive work!

**Pull request merged**
