### PR TITLE
Plane: disallow changing to INITIALISING mode

### PR DESCRIPTION
**Pull request by peterbarker**
At the moment you can change into this mode via mavlink.

That's not good - we won't fly well in this mode.

We already bounce attempts to enter thermal mode, so returning false from entering a mode is already tested.

### CODE REVIEW

**Review by khancyr — COMMENTED** [review]
won't this crash on start up as we set the initial mode at https://github.com/ArduPilot/ardupilot/blob/master/ArduPlane/system.cpp#L140 ? 

We should also forbid arming in initialising mode 
Rover got the same issue : see https://github.com/ArduPilot/ardupilot/issues/16043

**Comment by peterbarker** [comment]
> won't this crash on start up as we set the initial mode at https://github.com/ArduPilot/ardupilot/blob/master/ArduPlane/system.cpp#L140 ?

That call doesn't set `INITIALISING` as the mode; it sets a *different* mode from a parameter.  If that fails then we'll probably stay in `INITIALISING`. 

> We should also forbid arming in initialising mode

Yes we shouldn't arm :-)

tridge and I briefly discussed adding a properly-named callback to determine that.

> Rover got the same issue : see #16043

PR welcome ;-)

**Comment by khancyr** [comment]
Haaa my bad, that the mode constructor that should set the initializing mode not a set_mode so it should be fine. I didn't look carefully on the ctrl+f result ...

**Review by tridge — APPROVED** [review]

**Comment by davidbuzz** [comment]
needs autotest. :-)

**Comment by peterbarker** [comment]
On Mon, 25 Jan 2021, Buzz wrote:

> needs autotest. :-)

They exist - but only in a branch here where I'm working on more elaborate 
arming checks.

**Pull request merged**
