### PR TITLE
Correct a typo for PH4-mini serial port number

### PR DESCRIPTION
**Pull request by bys1123**
reference: SERIAL4 -> UART6 (RCIN port)

### CODE REVIEW

**Comment by Hwurzburg** [comment]
While you are at it, perhaps you could also change the url link to product to point the correct page: https://shop.holybro.com/pixhawk4-mini_p1120.html ?

**Comment by bys1123** [comment]
@Hwurzburg Thanks, updated.

**Review by khancyr — APPROVED** [review]
Hello,

This looks good. But we have a strict formatting on commit message. Could you append "HAL_ChibiOS:" at the start of your commits.

**Comment by Hwurzburg** [comment]
and squash to a single commit, if you have a problem doing this, I can do it for you...

**Comment by bys1123** [comment]
@Hwurzburg @khancyr Thanks, fixed.

**Review by khancyr — APPROVED** [review]
LGTM

**Comment by peterbarker** [comment]
merged, thanks!

**Pull request merged**
