### PR TITLE
[Plane] Fix verify_loiter_heading acceptance criteria.

### PR DESCRIPTION
**Pull request by lekston**
Follow up on issue #7934 to avoid too early exit from loiter_to_alt.

### CODE REVIEW

**Comment by magicrub** [comment]
tested this a bunch, works great. Thank you!

**Comment by magicrub** [comment]
@tridge how do you feel about squeezing this into the v3.8.5beta release cycle?

**Comment by magicrub** [comment]
It's effecting other users here https://github.com/mavlink/qgroundcontrol/issues/6137 so releasing it sooner rather than later would be good idea

**Comment by WickedShell** [comment]
3.8.5 beta needs to become stable and stop having things slid onto it. Given that we are about to start 3.9 I'd say this should simply ship with that.

**Comment by kikislater** [comment]
If I took latest version from here http://firmware.eu.ardupilot.org/Plane/latest/ PR should be included ? 
Am I right ?

**Pull request merged**
