### PR TITLE
AP_Scripting: fixed rudder in sport aerobatics

### PR DESCRIPTION
**Pull request by tridge**
rudder was not being activated in sport aerobatics

### CODE REVIEW

**Review by Hwurzburg — COMMENTED** [review]
works unless you stop the mission using it, restart the mission later, then knife edge fails again untill scripting is restarted

actually cant find a pattern...seems a bit random...how my suggested change seems to make it solid...

**Comment by tridge** [comment]
> actually cant find a pattern...seems a bit random...how my suggested change seems to make it solid...

what suggested change?

**Comment by Hwurzburg** [comment]
??? its right above your question...move your added line to line 259 in the pitch_controller

**Comment by Hwurzburg** [comment]
SITL tested...looks good now..

**Review by Hwurzburg — APPROVED** [review]

**Pull request merged**
