### PR TITLE
AP_Notify: change compass calibration tone

### PR DESCRIPTION
**Pull request by jschall**

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
any problem with the current one?

**Comment by jschall** [comment]
The only problem with the current one is that it is not this ;)

https://jschall.github.io/#MBMST128L4e16d16e%3Ca.%3Ep4f16e16f8e8d.p4f16e16f%3Ca.%3Ep4d16c16d8c8%3Cb8%3Ed8cp8e16d16e%3Ca.%3Ep4f16e16f8e8d.p4f16e16f%3Ca.%3Ep4d16c16d8c8%3Cb8%3Ed8cp8%3Cb16%3Ec16dp8c16d16e8d8c8%3Cb8a%3Efe2p4f16e16d8e2.pp

**Comment by lvale** [comment]
Shouldn't commercial copyrighted musics be avoided ?

**Comment by jschall** [comment]
Yes. Merging this would be a terrible idea.

**Pull request closed without merging**
