### PR TITLE
Add AocodaRCH7DUAL fireware

### PR DESCRIPTION
**Pull request by jianwwpro**
Add new AocodaRCH7DUAL fieware

### CODE REVIEW

**Review by Hwurzburg — CHANGES_REQUESTED** [review]
Needs board id reserved and used
Needs Readme file like https://github.com/ArduPilot/ardupilot/tree/master/libraries/AP_HAL_ChibiOS/hwdef/KakuteH7

**Comment by peterbarker** [comment]
@jianwwpro are you still keen on chasing this one?

**Comment by lida2003** [comment]
Here is the latest one for Aocoda RC H743 Dual: https://github.com/ArduPilot/ardupilot/tree/master/libraries/AP_HAL_ChibiOS/hwdef

The boardid is 

https://github.com/ArduPilot/ardupilot/blob/4daca86ba170bba4ef6acb86929441cbf5755d67/libraries/AP_HAL_ChibiOS/hwdef/Aocoda-RC-H743Dual/hwdef.dat#L8-L8

https://github.com/ArduPilot/ardupilot/blob/4daca86ba170bba4ef6acb86929441cbf5755d67/Tools/AP_Bootloader/board_types.txt#L339-L341

**Comment by peterbarker** [comment]
@jianwwpro as @lida2003 points out, we merged support for this board in https://github.com/ArduPilot/ardupilot/pull/25648

Many thanks for this pull request - it seems the manufacturer of the board got in ahead of you, 'though!

**Comment by lida2003** [comment]
@peterbarker @jianwwpro Thanks

**Pull request closed without merging**
