### PR TITLE
AP_Bootloader: add board id for PixFlamingo L4R5 v1

### PR DESCRIPTION
**Pull request by tsubashchandar**
Add new board id for custom board PixFlamingo L4R5 v1

### CODE REVIEW

**Review by peterbarker — APPROVED** [review]

**Comment by peterbarker** [comment]
I've rebased this to get rid of the merge commit

**Review by khancyr — APPROVED** [review]
LGTM free to use number

**Comment by tsubashchandar** [comment]
@peterbarker why one check failed?

**Comment by peterbarker** [comment]
@tsubashchandar merged, thanks!

**Pull request merged**
