### PR TITLE
RC_Channel private data members v2

### PR DESCRIPTION
**Pull request by kwikius**
V2 of https://github.com/ArduPilot/ardupilot/pull/4067

### CODE REVIEW

**Comment by tridge** [comment]
my first reaction is that I like this cleanup, it is long overdue and does make RC_Channel easier to read. The only issue will be very carefully checking that there are no unintended changes in behaviour. So far I haven't spotted any, but it will certainly need very careful review.
Thanks!

**Comment by kwikius** [comment]
Hi Tridge,
Thanks for the comments. I am glad it is deemed worthwhile. To be diligent, I have avoided  doing automated fixing up beyond one at a time search and replace per page, to make sure I have eyeballed each change that has been done. And I will do some more thorough reviewing as well.

**Comment by rmackay9** [comment]
It's nice to see someone trying to tackle RC_Channel.  It's probably our oldest library and most in need of refactoring.
Not trying to increase the scope but there are some other issues including that MIN and MAX values are used both for input and output.  the calc_pwm function should probably be replaced by a more automatic conversion either by the "set" or the "get" functions.

**Comment by tridge** [comment]
the MIN/MAX is indeed a problem, but I'd like to see the first set of changes have zero functionality change.
After we have that in we need to think about how we will tackle the MIN/MAX problem.

**Comment by tridge** [comment]
btw, I assume you've noticed it has failed some travis tests? Looks like a few updates to the example programs are missing

**Comment by kwikius** [comment]
@tridge  I am working through the tests and examples atm . (Sorry I am struggling a bit with how to keep this clean. If I rebase I lose commits, but if not I get a lot of bits and pieces. Or I just make a new PR?. Not a git expert sorry.. For now  I will just push bits and pieces )

As far as the class itself goes, yeah it is a mess :)  I think it is a question of trying to identify the different things it is trying to do.

**Comment by tridge** [comment]
I went through these patches carefully and I couldn't spot any errors. Well done!
pushed to master

**Pull request closed without merging**
