### PR TITLE
bugfix for tricks-on-a-switch activation cleanup

### PR DESCRIPTION
**Pull request by kd0aij**
Make last_trick_action_state fetch conditional on TRIK_ENABLE in plane_aerobatics.lua
and (cosmetic change for clarity) move declaration near TRIK_ACT_FN param setup in sport_aerobatics.lua.
Tested both scripts in SITL with RealFlight PA Addiction.

### CODE REVIEW

**Comment by timtuxworth** [comment]
> Seems to fix the problem.... @timtuxworth have you test flown?

Sorry I crashed my Extra, so not since this fix.

**Comment by timtuxworth** [comment]
> Seems to fix the problem.... @timtuxworth have you test flown?

I've tried on SITL - what it does do is that if TRIK_ENABLE is 0, it will keep throwing "attempt to index a nil value (local 'TRIK_ACT_FN'). I don't think that is ok.

**Comment by Hwurzburg** [comment]
The fix here does not do that....you must still be using the old script...

**Review by Hwurzburg — APPROVED** [review]
test flown and approved

@kd0aij you need to remove the DRAFT label in order to merge

**Pull request merged**
