### PR TITLE
Readme: Add coverity badge

### PR DESCRIPTION
**Pull request by WickedShell**
We should maybe also collapse travis/semaphore to one line with both of them on it.

### CODE REVIEW

**Comment by OXINARF** [comment]
I'm not sure if we should do this, for the only reason that Coverity is wrongly understood (like the discussion in Dronecode forum showed).

**Comment by WickedShell** [comment]
Yeah, the only reason I had fit suggesting adding it was too make more
people think of it/review the issues that are detected. But you definitely
have a point... Hmmm I can see either way on this then.

**Comment by magicrub** [comment]
Covarity needs to be taught/trained that variables declared in a class are
always initialized to zero. Most of the errors are that.

**Comment by OXINARF** [comment]
> Yeah, the only reason I had fit suggesting adding it was too make more
people think of it/review the issues that are detected

I don't think that adding a badge will do that. Making it automatically tested once a month was my plan to get people more aware, and I think it helped a bit, but not enough.

> Covarity needs to be taught/trained that variables declared in a class are
always initialized to zero.

Coverity needs to learn a lot of things. They can't parse our scheduler tables for example... But from the moment they haven't answered my e-mail (sent months ago) I stopped caring much about them.

**Comment by magicrub** [comment]
Fixing the uninitialized variable thing will drop a significant number of
errors. That alone is worth doing if possible.

**Comment by WickedShell** [comment]
The problem with the monthly builds in someways is that only the people who
are already on the coverity system will receive the e-mails. So there is
already a small subset of people who actually are checking the results,
although the counter is that maybe it's enough people?

On Sat, Aug 6, 2016 at 5:02 PM, Francisco Ferreira <notifications@github.com

**Comment by OXINARF** [comment]
> The problem with the monthly builds in someways is that only the people who
are already on the coverity system will receive the e-mails.

That is true. But is a badge enough to get more people to look at it? I mean, I never look at the readme, not sure if others do.

**Comment by WickedShell** [comment]
I only see the badges as it's the landing page for GitHub and they are
colorful and stand out. But then again my primary monitor is a 1080p in
portrait mode so I see a lot of screen real estate at once that might
otherwise be missed

**Comment by lucasdemarchi** [comment]
I think that having a coverity badge doesn't hurt and provides a quick link to the coverity results so people can look at them. Even though they have false positives (and a lot), it's better than nothing.

**Comment by lucasdemarchi** [comment]
E.g. when I want to see new problems in kmod I often go to its github repository (https://github.com/lucasdemarchi/kmod) which has a quick link to coverity report.

**Comment by mbelluzzo** [comment]
I agree that it can raise awareness for the issues that matters even that there are a lot of false positives. Maybe someone will get motivated to add a filter for those.

The only change I would do to this is to have all badges in a single row.

**Comment by magicrub** [comment]
speaking of Covarity, I looked into training Covarity and it seems we would
have to add a sample function in each location that it's throwing the
uninitialized error. That's a horrible method, but I don't see any other
way. Details here:
https://scan.coverity.com/tune

**Comment by magicrub** [comment]
This was discussed on the dev call. This is ready to merge, although here are some nice-to-haves:
- add some titles to each badge such as "Travis: " in front of thetravis badge so we know where the "build passing" badge comes from.
- put all badges on a single line

**Comment by WickedShell** [comment]
I can update with this changes unless you want to just do it

**Comment by magicrub** [comment]
either way, but I can't now. Tomorrow

**Comment by lucasdemarchi** [comment]
Applied. Tweaking the appearance of the badges can be done in a separate PR. Thanks.

**Pull request closed without merging**
