### PR TITLE
KakuteH7Mini-Nand rename

### PR DESCRIPTION
**Pull request by andyp1per**
Holybro are going to call the KakuteH7Mini v2 (or 1.3) the KakuteH7Mini-Nand

### CODE REVIEW

**Comment by tridge** [comment]
this has implications for the firmware server directory structure, especially for stable releases. Can be done, but best to discuss on EU call

**Comment by peterbarker** [comment]
Maybe just change marketing name?

**Comment by tridge** [comment]
we could just change the manifest name and not subdir name

**Comment by tridge** [comment]
@andyp1per need to discuss with you

**Comment by vincentpoont2** [comment]
We called this new Kakute H7 Mini "Kakute H7 Mini V1.3", the physical board has silkscreen showing that.
It ships with Betaflight and BF requires it to use use same target as before. In the far future, we probably will have a v2, so I ask Andy to changed this target to "KakuteH7Mini-Nand". 

Please let me know if there is any issue or recommended resolution.

image

**Comment by andyp1per** [comment]
@vincentpoont2 I think we have a resolution now - hopefully get this merged next week

**Review by tridge — APPROVED** [review]

**Comment by tridge** [comment]
@andyp1per need to follow up with a remove of the build directories

**Pull request merged**
