### PR TITLE
Add support for Here4 as Flight Controller

### PR DESCRIPTION
**Pull request by bugobliterator**
* To use the firmare generated by the build on production Here4. User needs to first update Here4 through DroneCAN tool or Mission Planners DroneCAN config.
* The firmware needs to be of .bin format. 
* After first update, users can connect through the serial port. Check https://docs.cubepilot.org/user-guides/here-4/here-4-manual#pinout for breakout board pinouts.
* For future updates to firmware, use flash bootloader through mission planner, and then user should be able to update firmware through Serial port.

Please note that once the firmware is updated to FC, updates through DroneCAN tool will not work, to rollback to GPS firmware user will need to update using APJ file available here https://github.com/CubePilot/GNSSPeriph-release/releases.

### CODE REVIEW

**Review by Hwurzburg — DISMISSED** [review]
needs a full readme with board  photo, pinouts, wiring diagram, etc.

**Comment by rmackay9** [comment]
This is so crazy but I've got to try it.  For rovers and boats using the GPS as both a GPS and an FC makes sense.  Of course we will need to pair it with CAN ESCs and servos I expect.

**Comment by bugobliterator** [comment]
> This is so crazy but I've got to try it. For rovers and boats using the GPS as both a GPS and an FC makes sense. Of course we will need to pair it with CAN ESCs and servos I expect.

No, there is PWM out, please refer the breakout board https://docs.cubepilot.org/user-guides/here-4/here-4-manual#pinout 
8 PWM outs and RCIN

**Comment by bugobliterator** [comment]
> needs a full readme with board photo, pinouts, wiring diagram, etc.

Yeah, I will add the docs to the hwdef folder. Currently the docs for pinouts are here https://docs.cubepilot.org/user-guides/here-4/here-4-manual#pinout

**Comment by alexispap51** [comment]
> - After first update, users can connect through the serial port
Does this mean that we cannot use the CAN interface (along with UAVCAN) afterwards to communicate with Here4?

**Comment by bugobliterator** [comment]
> > * After first update, users can connect through the serial port
> 
> Does this mean that we cannot use the CAN interface (along with UAVCAN) afterwards to communicate with Here4?

Yes you can, just can't update Here4 firmware firmware through the DroneCAN update mechanism

**Comment by Hwurzburg** [comment]
@bugobliterator since we just link to Cube website pages for Cube autopilots, I won't be picky about the readme....but your docs on the HERE4 are not complete enough for anyone to use this as an autopilot at this point IMO....also, you might want to point out how to connect to use the GPS module AS the autopilot GPS (CAN jumper cable?) when you do expand the docs

**Review by tridge — APPROVED** [review]

**Comment by rbachtell** [comment]
If we are using the only serial port for firmware upload can that port then be used by another serial device for telemetry such as Herelink?

**Comment by rbachtell** [comment]
@bugobliterator After several hours of testing I have come to the conclusion that the receive and transmit pins are reversed on either the breakout board or the here4 serial port. I had to reverse the pins on my FTDI cable in order to get proper communication for flashing the FC firmware and then on my WiFi card that has been in operation for several years on different Cube AP systems. Might want to check this out on your end.

**Comment by bugobliterator** [comment]
> @bugobliterator After several hours of testing I have come to the conclusion that the receive and transmit pins are reversed on either the breakout board or the here4 serial port. I had to reverse the pins on my FTDI cable in order to get proper communication for flashing the FC firmware and then on my WiFi card that has been in operation for several years on different Cube AP systems. Might want to check this out on your end. Edit: The board checks out OK, I swapped rx/tx on the 10 pin connector, functions as expected now

@rbachtell actually the RX/TX swap on UART is by design, the reason is the default usecase of Here4 is as a Peripheral. In which case the UART needs to be from the perspective of what it will normally connect to which is a Flight Controller. To maintain 6-Pin to 6-Pin connection without RX/TX crossed those pins need to be swapped on Here4 or any GPS modules that we have made in the past and they need to be marked as per what Flight Controller's pinout.
As there is now a possibilty of Here4 as an FC, I can see users getting into the confusion as you did. The perspective is now changed, Here4 is no longer the Peripheral but FC itself. I will make a note of this and update our Docs accordingly. Thanks for reporting this!

**Comment by rbachtell** [comment]
Ah, makes perfect sense.  Everything is set up and looks good, waiting for weather for field test. Thanks for the prompt reply and explanation. Randy BachtellSent from my iPhoneOn Jan 18, 2024, at 4:01 PM, Siddharth Bharat Purohit ***@***.***> wrote:﻿

@bugobliterator After several hours of testing I have come to the conclusion that the receive and transmit pins are reversed on either the breakout board or the here4 serial port. I had to reverse the pins on my FTDI cable in order to get proper communication for flashing the FC firmware and then on my WiFi card that has been in operation for several years on different Cube AP systems. Might want to check this out on your end. Edit: The board checks out OK, I swapped rx/tx on the 10 pin connector, functions as expected now

@rbachtell actually the RX/TX swap on UART is by design, the reason is the default usecase of Here4 is as a Peripheral. In which case the UART needs to be from the perspective of what it will normally connect to which is a Flight Controller. To maintain 6-Pin to 6-Pin connection without RX/TX crossed those pins need to be swapped on Here4 or any GPS modules that we have made in the past and they need to be marked as per what Flight Controller's pinout.
As there is now a possibilty of Here4 as an FC, I can see users getting into the confusion as you did. The perspective is now changed, Here4 is no longer the Peripheral but FC itself. I will make a note of this and update our Docs accordingly. Thanks for reporting this!

**Pull request merged**
