### PR TITLE
Scripting: use generator to load manual bindings

### PR DESCRIPTION
**Pull request by IamPete1**
This moves loading of manual bindings to the generated code. This means that it uses the same method to move from memory to flash. This saves 373 bytes of memory (simple loop in SITL). It also allows us to mix and match auto generated and manual bindings for a singleton.

Should be no change in behavior for those using the bindings. 

Also saves 80 bytes of flash. 

replaces https://github.com/ArduPilot/ardupilot/pull/15246

### CODE REVIEW

**Review by tridge — COMMENTED** [review]
nice!
what testing has this had?

**Comment by IamPete1** [comment]
Rebased to fix conflict. 

Just tested i2c, logging and CAN on real hardware. Tested millis, micros and mission in SITL.

**Review by tridge — APPROVED** [review]

**Comment by IamPete1** [comment]
rebased again.

**Comment by IamPete1** [comment]
rebased

**Pull request merged**
