### PR TITLE
Fix Linux build for Rover stable

### PR DESCRIPTION
**Pull request by peterbarker**
Just a commit which has so far been missed in Rover backports.

### CODE REVIEW

**Comment by peterbarker** [comment]
You can replicate the error this fixes by checking out APMrover2-stable then configuring for `edge` then compiling for bin/ardurover

**Comment by rmackay9** [comment]
@peterbarker,

It looks like CI/Travis isn't passing, should we worry?

By the way, it's unlikely that we will do a Rover-4.0.1 release.

**Comment by peterbarker** [comment]
@rmackay9 I'm looking at that failure ATM.

We changed release compilers, and I believe moved away the old release compiler from where it did live.

The patches to change the travis environment to use the new compiler haven't been merged back into Rover stable.

What is your understanding - are we to use the new compiler on Rover-stable?

**Comment by peterbarker** [comment]
> It looks like CI/Travis isn't passing, should we worry?

I believe this can be merged as-is.  It will mean that we get an "edge" build for Rover on the autotest server.  CI failing is a separate issue; the release server will use the newer compiler.

**Comment by rmackay9** [comment]
ok, merged, thanks!

**Pull request merged**
