### PR TITLE
Correct RPM_PIN dt

### PR DESCRIPTION
**Pull request by khancyr**
dt_avg was using integer division and thus lost some part of the division. Changing the division to float correct this.

The other commit remove a zero assignement that is useless and bring more const.

### CODE REVIEW

**Comment by peterbarker** [comment]
This looks right to me.  What testing has been done?

**Comment by peterbarker** [comment]
@khancyr this is now conflicting.  Did you want to pursue this?

**Comment by khancyr** [comment]
Tested on cube black with hack setup but enought to see the result: 

RPM1_TYPE 2
RPM1_PIN 50
SERVO9_FUNCTION -1

Servo tester on AUX1

int == current version with int cast
float == PR version with float cast

```
AP: RPM1: int 3654.971, float 3654.939
AP: RPM1: int 3654.971, float 3654.934
AP: RPM1: int 3655.193, float 3655.082
AP: RPM1: int 3654.971, float 3654.896
AP: RPM1: int 3654.971, float 3654.860
AP: RPM1: int 3654.971, float 3654.896
AP: RPM1: int 3655.193, float 3655.008
AP: RPM1: int 3655.193, float 3655.045
AP: RPM1: int 3654.971, float 3654.896
AP: RPM1: int 3654.971, float 3654.971
AP: RPM1: int 3655.193, float 3655.008
AP: RPM1: int 3655.193, float 3655.162
AP: RPM1: int 3655.193, float 3655.082
AP: RPM1: int 3654.971, float 3654.971
AP: RPM1: int 3655.193, float 3655.045
AP: RPM1: int 3655.193, float 3655.119
AP: RPM1: int 3655.193, float 3655.156
AP: RPM1: int 3655.193, float 3655.082
AP: RPM1: int 3655.193, float 3655.156
AP: RPM1: int 3655.193, float 3655.119
AP: RPM1: int 3655.193, float 3655.156
AP: RPM1: int 3655.416, float 3655.230
AP: RPM1: int 3655.193, float 3655.130
AP: RPM1: int 3655.193, float 3655.193
AP: RPM1: int 3655.193, float 3655.156
AP: RPM1: int 3655.416, float 3655.305
AP: RPM1: int 3655.416, float 3655.268
AP: RPM1: int 3655.416, float 3655.305
AP: RPM1: int 3655.416, float 3655.268
AP: RPM1: int 3655.193, float 3655.156
AP: RPM1: int 3655.416, float 3655.268
```
Not much different but on cumulation is will make difference

**Review by peterbarker — APPROVED** [review]

**Review by rmackay9 — APPROVED** [review]
LGTM.

FYI @andyp1per @tridge

**Pull request merged**
