### PR TITLE
Copter: Obey CAMERA == DISABLED

### PR DESCRIPTION
**Pull request by amilcarlucas**

### CODE REVIEW

**Comment by peterbarker** [comment]
This seems reasonable - but why just camera?

mount, just below it, is going to be pretty much the same arguments as for doing camera...

**Comment by amilcarlucas** [comment]
I have done 4 PRs on this :)

**Comment by rmackay9** [comment]
Merged, thanks!

**Comment by amilcarlucas** [comment]
Please also take a look at the other 3 PRs that I did similar to this one: #7731 #7733 #7734

**Pull request merged**
