### PR TITLE
Plane: added EKF yaw reset handling to quadplane

### PR DESCRIPTION
**Pull request by tridge**
this follows the implementation from copter. Thanks to Leonard for the
suggestion

### CODE REVIEW

**Comment by rmackay9** [comment]
Just a comment about positioning the call, it's not really flight mode related is it?  Maybe it should go into the vehicle's fast loop just like copter?  if we want to be super consistent with copter then we could name the function, "check_ekf_reset()".

**Comment by rmackay9** [comment]
I thought about this some more and here is a situation where I think the placement of the check-yaw-reset will cause problems:

- arm and take-off as a plane
- EKF resets the yaw at some point
- vehicle is switched to QHOVER, the check_yaw_reset runs and moves the target around by the angle of the EKF reset (which occurred many seconds before) so vehicle changes heading (the point of this yaw-reset code is to make sure the vehicle doesn't change heading).

**Comment by tridge** [comment]
thanks Randy, you're right, I'll re-work it to avoid that

**Comment by tridge** [comment]
fixed and pushed to master

**Pull request closed without merging**
