### PR TITLE
Holybro Durandal Analog RSSI fix (+ tiny imperfection fix for VSERVO rail and IOMCU 12-bit ADC scaling)

### LINKED ISSUE #16451: Analog RSSI scaling on Holybro Durandal. Less than 45% of full analog input range is used.
## Bug report
Analog RSSI input scaling on [Holybro Durandal](http://www.holybro.com/product/durandalbeta/) needs improvement, as presently only less than half of the measurement range is used.

**Issue details**
Presently when RSSI_PIN_HIGH is set to 3.3V, all values above approx. 1.36V are handled as 0xFF (255).
When RSSI_PIN_HIGH is set to 5.0V, the threshold above which output is 0xFF is approx. 2.15V.

Expected behavior: 0 to 0xFE should be mapped to full scale from 0 to 3.3V (RSSI_PIN_HIGH set to 3.3V) or 0 to 5.0V (when RSSI_PIN_HIGH is set to 5V). 0xFF should be reserved for invalid, as according to MAVLink specs, but this is a separate issue. Here it's about scaling **analog RSSI input** of **Durandal** that is using only a small proportion of the full swing range and **saturates** way **too early**.

Following other settings were used for test:
RSSI_TYPE is 1 (=Analog Pin)
RSSI_ANA_PIN is 103 (=Pixhawk SBUS)
RSSI_PIN_LOW is 0
BRD_SBUS_OUT is 0

**Version**
ArduPlane V4.0.8 (and also the same with ArduPlane V4.0.7)

**Platform**
[  ] All
[  ] AntennaTracker
[  ] Copter
[X] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
FLYING_WING

**Hardware type**
Holybro Durandal (purchased directly from Holybro)

### PR DESCRIPTION
**Pull request by rotorman**
This fixes the analog RSSI saturation bug on Holybro Durandal.

The second commit in this PR, additionally fixes a small imprecision of servo rail voltage scaling on Holybro Durandal (with voltage divider 9.744V is giving full scale output and not 9.900V) and also additionally fixing 12-bit ADC full scale division. Highest value for 12-bit ADC is 0x0FFF = 4095. To unitize the output (to get 1.000 for the max value), the denominator should be 4095 and not 4096.

The proposed changes are tested successfully on Holybro Durandal hardware. I will attach the schematics of IOMCU of Durandal that Holybro support sent me to show that the proposed changes are based on valid claims.

[HolybroDurandalIOMCUschematics.pdf](https://github.com/ArduPilot/ardupilot/files/6097032/HolybroDurandalIOMCUschematics.pdf)

(This PR recaps #16607 that I closed due to being stale for too long)

Fixes #16451

### CODE REVIEW

**Comment by rotorman** [comment]
Test failing, likely related to #16836

**Comment by peterbarker** [comment]
> Test failing, likely related to #16836

Merged that and restarted failing tests here.

**Comment by IamPete1** [comment]
I think the correct fix for the scaling issue is to change the hwdef here:
https://github.com/ArduPilot/ardupilot/blob/8bd04c17c85e8ac2e794771608cde91e7c5660dd/libraries/AP_HAL_ChibiOS/hwdef/Durandal/hwdef.dat#L201

**Comment by rotorman** [comment]
Superseded by #18754. Closing.

**Pull request closed without merging**
