### PR TITLE
Use main loop rate for SYS_STATUS load_average

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by peterbarker** [comment]
Note this also includes a patch covered under #6697

**Comment by rmackay9** [comment]
We handle the possibility of used-time being over the limit correctly of course?

I don't see anything wrong, i'm just always concerned about the possibility of negative numbers being returned when it's not expected.

As a side note, I'm surprised the (_spare_ticks == 0) returns 0.0 instead of 1.0.  maybe that only happens during startup?

**Comment by peterbarker** [comment]
@Randy: no better or worse than we did before.

OTOH, if you do change the loop rate at least you have a chance of getting the correct number.

The 1.0 vs 0.0 was probably somebody protecting against div-by-zero and not giving the return value too much thought.  I've not given it any thought myself, either :-)

Related to this PR is the fact that we continue to use the `#defines` for the loop rate constants, despite the fact that the loop rate may have been changed using the variable.  I'm starting to look at those ATM.

**Comment by OXINARF** [comment]
This looks fine to me, I think it can only be dangerous if the loop rate is set to 0 or a huge value - both of which shouldn't even allow the system to run properly.

Unless someone says no, I'll merge this in 10 hours.

**Comment by OXINARF** [comment]
Merged, thanks!

**Pull request merged**
