### PR TITLE
Added ship takeoff and landing support for quadplanes

### PR DESCRIPTION
**Pull request by tridge**
This implements takeoff and landing from moving platforms (intended for ships) to quadplanes. It requires some quite extensive re-work to the quadplane code. Only tested in SITL so far
This will be worked on after #14938 is merged

### CODE REVIEW

**Comment by magicrub** [comment]
@tridge I'm working with Dan on this and fixed a sqrt double compile problem on his end and pushed it to this branch/pr. I also found a potential divide-by-zero bug

**Comment by magicrub** [comment]
I removed the divide-by-zero check, it needs to be the default 110000 number. I was thinking the ratio there. (I rewrote it in my head 10 times). Anyway, the big blocker for Dan was the sqrt() call which was killing Dan's build. Worked fine for me but still needed to be fixed.

**Comment by magicrub** [comment]
@tridge I see you rebased and removed my fix. Please use sqrtf() instead of sqrt().

**Comment by tridge** [comment]
> @tridge I see you rebased and removed my fix. Please use sqrtf() instead of sqrt().

fixed, thanks

**Pull request closed without merging**
