### PR TITLE
autotest: add test for two consecutive drops with no reboot

### PR DESCRIPTION
**Pull request by peterbarker**
This adds a new autotest.

It arms the vehicle in throw mode, then lifts the vehicle gently to ~100m - and then drops it.  It checks we go through the throw mode stages and that we eventually have zero velocity.  It then switches to alt-hold mode and lands the vehicle.

It then sets "throw nextmode" to auto, loads a mission and repeats the drop procedure.  It then waits for the vehicle to disarm at the end of the mission.

It completes all of that successfully, but there appear to be several problems with the way the vehicle is being controlled.

This autotest can be run with

`./Tools/autotest/autotest.py --gdb --debug build.Copter test.Copter.ThrowDoubleDrop`

### CODE REVIEW

**Comment by peterbarker** [comment]
Here's a weird thing:
image

Integrator is slammed to max as we go into auto, but then fades.  But given the motors are still ramping from zero to `MOT_SPIN_MIN` (`MOT_SPOOL_TIME` is 2s), any integrator is probably wrong.

**Comment by peterbarker** [comment]
Second weird thing:  throw mode stage processing:

image

We move from the first to the final stage in basically no time - and seemingly without dropping the altitude required (1m +/-50cm)

**Comment by peterbarker** [comment]
I wonder if we should have another step in the throw mode state machine which waits for the *actual* spool state to be `AP_Motors::SpoolState::THROTTLE_UNLIMITED`

**Comment by davidbuzz** [comment]
hey peter, that autotet looks good... if its passing (despite being sub-optimal results), there's no reason we can't merge this, is there.?

**Comment by peterbarker** [comment]
Merged, thanks for the nudge, @davidbuzz

**Pull request merged**
