### PR TITLE
AP_Arming:correct ARMING_RUDDER description

### PR DESCRIPTION
**Pull request by Hwurzburg**
NFC...correct description of parameter as discussed in Devcall..will also update each wiki arming page

### CODE REVIEW

**Review by khancyr — APPROVED** [review]
yep much better.

**Review by magicrub — CHANGES_REQUESTED** [review]
Text change is fine but you have a module update in the same commit

**Comment by Hwurzburg** [comment]
fixed

**Comment by magicrub** [comment]
I don't think this needs a DevCall discussion, merging now..

**Pull request merged**
