### PR TITLE
AIRLink hwdef: added heater parameters

### PR DESCRIPTION
**Pull request by aviaks**
Added missing heater parameters to hwdef for AIRLink hardware.

### CODE REVIEW

**Review by tridge — COMMENTED** [review]
did you tune these and check the values are right? Overriding the defaults is only needed if the board has a particularly powerful heater that can cause oscillation in a baro that is close to the heater. 
how rapidly does it go from room temp to 45?

**Comment by tridge** [comment]
ahh, I see, it was missing HAL_HAVE_IMU_HEATER, merging

**Review by tridge — APPROVED** [review]

**Comment by aviaks** [comment]
@tridge Thanks! PI values are fine, the primary reason for a change was missing `define HAL_HAVE_IMU_HEATER 1`. When this is missing in hwdef file, heater control is not enabled. The same most likely happens to the other boards which use heater and don't have this definition.

**Comment by rmackay9** [comment]
If possible let's remember to set the Project if we backport it.  I've done this for this PR.

**Pull request merged**
