### PR TITLE
AP_HAL_ChibiOS: hardware definition for Kakute F7 Mini

### PR DESCRIPTION
**Pull request by andyp1per**
ChibiOS hardware definitions and bootloader for the Kakute F7 Mini

https://shop.holybro.com/kakute-f7-mini_p1133.html

Board id 145 comes from https://github.com/ArduPilot/Bootloader/blob/master/board_types.txt

### CODE REVIEW

**Comment by andyp1per** [comment]
@tridge this seems to be working now and I have done the bootloader dance as well

**Comment by vierfuffzig** [comment]
@andyp1per as suggested on discuss forum you might want to reference existing KakuteF7 hwdef and just redefine apj board ID, flash defines and maybe fix UART order match hardware port mapping reg. UARTS 6 and 7.

**Comment by tridge** [comment]
looks good to me!
@vierfuffzig I'm OK with them being separate. There are quite a few changes between them. Either approach is OK for this level of changes I think

**Comment by vierfuffzig** [comment]
@tridge as far as i can see right now it's an exact copy of the non-mini version except for using flash instead of SD for logging.

**Comment by andyp1per** [comment]
How do I undef an SPIDEV declaration if I am to do it this way?

**Comment by andyp1per** [comment]
Ok, I have done the include thing for the bootloader as it is identical apart from  the board id. That seems to work great as I ended up with an identical binary file.

I have kept the other file separate and made the changes above.

**Comment by andyp1per** [comment]
Thanks!

**Pull request merged**
