### PR TITLE
AP_GPS: get ellipsoid height from ublox GPS and UAVCAN GPS

### PR DESCRIPTION
**Pull request by Vkd4U2NtVkZOVg**
This PR is get the right ellipsoid height from GPS(ublox and UAVCAN GPS only for now), It's tested on CUAV X7 and CUAV CAN GPS and F9P.

### CODE REVIEW

**Review by khancyr — COMMENTED** [review]
Seems correct on first read

**Review by WickedShell — CHANGES_REQUESTED** [review]
As it is I don't think we should bring this in. There isn't anything using it, it will eat add a decent amount of memory usage to every location we have, and it will become rapidly inconsistent, because all the altitude manipulations will not preserve what happens when you change the normal height the ellipsodal will stay untouched, which then leads to being out of sink. Similarly if you translate it, the ellipsoidal height should possibly be reprojected? It's very unclear what the correct answer is here.

**Comment by Vkd4U2NtVkZOVg** [comment]
@WickedShell I think you are right about the memory usage. I add this because in some application, user want the copter to fly at ellipsiod height not MSL height. if it's not help I should probably close this PR

**Comment by tridge** [comment]
a GPS_OPTIONS bit to always use the elipsoid height (if supported by that backend) would be a simpler alternative

**Comment by WickedShell** [comment]
> a GPS_OPTIONS bit to always use the elipsoid height (if supported by that backend) would be a simpler alternative

I'd caution on this that you wouldn't be compliant with any of the MAVLink spec anymore, and any absolute altitude planned missions would be flown at a surprising altitude from a GCS perspective. I'm just not sold on the feature as currently presented.

**Comment by tridge** [comment]
closing as GPS_DRV_OPTIONS gives the key functionality

**Pull request closed without merging**
