### PR TITLE
AP_HAL_ChibiOS: Restore soaring on F405-Wing board.

### PR DESCRIPTION
**Pull request by samuelctabor**
Re-enables soaring now that some other features have been turned off.

### CODE REVIEW

**Comment by Hwurzburg** [comment]
isn't that a base undefine in 1MB boards?

**Review by peterbarker — APPROVED** [review]
LGTM

**Comment by samuelctabor** [comment]
> isn't that a base undefine in 1MB boards? wouldn't you have to positively define it as enabled ?

It's disabled if HAL_MINIMIZE_FEATURES is true, but that isn't the case for all the 1MB boards.

**Comment by Hwurzburg** [comment]
sorry, your are right I was looking at the wrong part of my list....in the midst of trying to correct the wiki for limitations and have decoded current exclusions for 1M, HAL_MINIMIZE, and individual boards....just looked at the wrong part of the list...

**Comment by Hwurzburg** [comment]
and just realized this killed my Soaring test vehicle....F405-Wing is uber popular on the Phoenix 2400 glider user group...please merge this!

**Comment by samuelctabor** [comment]
> btw I had just realized that my Soaring test vehicle had just died when upgrading to master....F405-Wing is uber popular on the Phoenix 2400 glider user group...please merge this!

It's only been disabled in master for the last week. Unfortunately 4.1.0beta1 went out during that time so it is disabled in current beta.

**Comment by tridge** [comment]
> It's only been disabled in master for the last week. Unfortunately 4.1.0beta1 went out during that time so it is disabled in current beta.

i'll apply this change for beta2, likely in the next week

**Review by tridge — APPROVED** [review]

**Pull request merged**
