### PR TITLE
sudo to --user

### PR DESCRIPTION
**Pull request by MohamedAliRashad**
I think those are all the sudo pip statements in the code base to fix from sudo to --user.

### CODE REVIEW

**Comment by peterbarker** [comment]
Naturally, the support questions will be, "how do I install for all users?".

Marking devcall for discussion.

**Comment by peterbarker** [comment]
@tridge likes this idea.  Are you sure this continues to work on all platforms?  In particular, mac is hard for many of us to test.

**Comment by peterbarker** [comment]
General agreement that this is a good idea.

**Comment by MohamedAliRashad** [comment]
> @tridge likes this idea. Are you sure this continues to work on all platforms? In particular, mac is hard for many of us to test.

@peterbarker i have no mac to test this actually but we can change it for now and wait for the issues to pop up

**Comment by OXINARF** [comment]
@MohamedAliRashad Certainly better 🙂 We now need to squash all those commits and prefix the commit message with `Tools: ` but whoever merges can do that (since this is your first contribution, thanks for that by the way!). If you haven't read our contribution rules, please do so for the future: http://ardupilot.org/dev/docs/submitting-patches-back-to-master.html

**Comment by peterbarker** [comment]
I've pulled this in after:
 - using git rebase and the "fixup" directive to merge all the commits
 - changing the commit message on the sole remaining commit to accord with our standards

I might suggest you look up how to use git "topic branches" to do you work on, rather than committing into your master branch.  Working on your master branch causes many issues; errors pointing out your branch and upstream have diverged.  You probably want to use `git reset --hard HEAD^` a few times on your master branch to fix things - but please make a backup of your git repository first!

**Comment by peterbarker** [comment]
@MohamedAliRashad Thanks!

**Pull request closed without merging**
