### PR TITLE
AP_Filesystem: fixed set_mtime semaphore

### PR DESCRIPTION
**Pull request by tridge**

### CODE REVIEW

**Comment by davidbuzz** [comment]
hey tridge - just curious what the bad behaviour was/is that occurs without this.    ... or is it just defensive code against two threads trying to mtime a file at the same time (i can't think of a case where thats likely with our current filesystem, but maybe you did ).   LGTM , as it's a safer to have it.

**Comment by WickedShell** [comment]
@davidbuzz Scripting and FTP if nothing else. With that being said we have the flag set for fatfs to be thread safe so that shouldn't be a problem either way, so I'm not sure whats fully driving this.

**Comment by tridge** [comment]
> @davidbuzz Scripting and FTP if nothing else. With that being said we have the flag set for fatfs to be thread safe so that shouldn't be a problem either way, so I'm not sure whats fully driving this.

actually we set FF_FS_REENTRANT=0, that changed when we added our own semaphore

**Comment by WickedShell** [comment]
Why do we think we do better then FF? I'd prefer to keep that on, even if we add our own in front of it.

**Pull request merged**
