### PR TITLE
FETtec OneWire on top of AP_ESC_Telem backend v7

### PR DESCRIPTION
**Pull request by amilcarlucas**
This one is based on top of a newer version #16725 with https://github.com/andyp1per/ardupilot/pull/19 on top of it.

requires #16725

It is mostly similar to #16850 , #16963, #17012, #17063, #17201 and #17225 but it is based on top of some other commits.

- [x] feature complete:
  - [x] control motor speed
  - [x] copy ESC telemetry data into MAVLink telemetry
  - [x] save ESC telemetry data in Dataflash logs
  - [x] use RPM telemetry for dynamic notch filter frequencies
  - [x] sum the current telemetry info from all ESCs and use it as virtual battery current monitor sensor
  - [x] average the voltage telemetry info and use it as virtual battery voltage monitor sensor
  - [x] average the temperature telemetry info and use it as virtual battery temperature monitor sensor
  - [x] report telemetry communication error rate in the dataflsh logs
- [x] passes CI
- [x] compiles when HAL_WITH_ESC_TELEM = 0
- [x] compiles when HAL_WITH_ESC_TELEM = 1
- [x] compiles when  HAL_AP_FETTECONEWIRE_ENABLED = 0
- [x] compiles when  HAL_AP_FETTECONEWIRE_ENABLED = 1
- [x] compiles when  HAL_AP_FETTECONEWIRE_ENABLED = 1 and HAL_WITH_ESC_TELEM = 0
- [x] protocol is documented in the `README.md` file in the same location as the `.cpp` implementation file
- [x] [configuration instructions](https://github.com/amilcarlucas/ardupilot_wiki/blob/patch-11/common/source/docs/common-fettec-onewire.rst) are on PR ArduPilot/ardupilot_wiki#3335 the for the [ardupilot wiki](https://ardupilot.org/ardupilot/)
- [ ] flight tested with a Hex frame using the last 6 channels (FETtec ID 7 to 12) 1 to 6 are unused/unassigned
- [ ] mavlink telemetry works (analyzed a `.TLOG` file to see that [ESC_TELEMETRY_1_TO_4](https://mavlink.io/en/messages/ardupilotmega.html#ESC_TELEMETRY_1_TO_4) and [ESC_TELEMETRY_5_TO_8](https://mavlink.io/en/messages/ardupilotmega.html#ESC_TELEMETRY_5_TO_8) messages are present or that [ESC_TELEMETRY_5_TO_8](https://mavlink.io/en/messages/ardupilotmega.html#ESC_TELEMETRY_5_TO_8) and [ESC_TELEMETRY_9_TO_12](https://mavlink.io/en/messages/ardupilotmega.html#ESC_TELEMETRY_9_TO_12) messages are present - using MissionPlanner->Ctrl-F->MavLinkInspector->Vehicle1->Comp1 - and their contents correct)
- [ ] `.bin` dataflash log files have ESC telemetry data in ESC7..12
- [x] flight tested with a Hex frame using the first 6 channels (FETtec ID 1 to 6)
- [x] mavlink telemetry works (analyzed a `.TLOG` file to see that [ESC_TELEMETRY_1_TO_4](https://mavlink.io/en/messages/ardupilotmega.html#ESC_TELEMETRY_1_TO_4) and [ESC_TELEMETRY_5_TO_8](https://mavlink.io/en/messages/ardupilotmega.html#ESC_TELEMETRY_5_TO_8) messages are present - using MissionPlanner->Ctrl-F->MavLinkInspector->Vehicle1->Comp1 - and their contents correct)
- [x] `.bin` dataflash log files have ESC telemetry data in ESC1..6
- [ ] four independent [notch filters](https://ardupilot.org/copter/docs/common-imu-notch-filtering.html) work (used a hex for testing, the last two motors are ignored) 
- INS_HNTCH_ENABLE = 1,
- [INS_HNTCH_MODE](https://ardupilot.org/copter/docs/parameters.html#ins-hntch-mode-harmonic-notch-filter-dynamic-frequency-tracking-mode) = 3 (ESC telemetry),
- [INS_HNTCH_OPTS](https://ardupilot.org/copter/docs/parameters.html#ins-hntch-opts-harmonic-notch-filter-options) = 2 (dynamic notch)
- [INS_HNTCH_REF](https://ardupilot.org/copter/docs/parameters.html#ins-hntch-ref) = 1
- [INS_HNTCH_FREQ](https://ardupilot.org/copter/docs/parameters.html#ins-hntch-freq) = 60
- [INS_HNTCH_BW](https://ardupilot.org/copter/docs/parameters.html#ins-hntch-bw) = 30
- [x] [IMU noise levels](https://ardupilot.org/copter/docs/common-imu-fft.html) measured before [notch filtering](https://ardupilot.org/copter/docs/common-imu-notch-filtering.html)
- [INS_LOG_BAT_MASK](https://ardupilot.org/copter/docs/parameters.html#ins-log-bat-mask) = 1
- [INS_LOG_BAT_OPT](https://ardupilot.org/copter/docs/parameters.html#ins-log-bat-opt-batch-logging-options-mask) = 0
- @teezeefpv please add a  [MissionPlanner FFT picture](https://ardupilot.org/planner/docs/common-measuring-vibration.html) here like described in the [noise analysis page](https://ardupilot.org/copter/docs/common-imu-batchsampling.html)
- [ ] [IMU noise levels](https://ardupilot.org/copter/docs/common-imu-fft.html) measured after [notch filtering](https://ardupilot.org/copter/docs/common-imu-notch-filtering.html)
- [INS_LOG_BAT_OPT](https://ardupilot.org/copter/docs/parameters.html#ins-log-bat-opt-batch-logging-options-mask) = 2
- @teezeefpv please add a [MissionPlanner FFT picture](https://ardupilot.org/planner/docs/common-measuring-vibration.html) here like described in the [noise analysis page](https://ardupilot.org/copter/docs/common-imu-batchsampling.html)
- [x] Telemetry measurements replace the need for power monitoring hardware when [BATT_MONITOR](https://ardupilot.org/copter/docs/parameters.html#batt-monitor-battery-monitoring) = 9 (ESC). Used a normal battery monitor on [BATTERY2](https://mavlink.io/en/messages/ardupilotmega.html#BATTERY2) and compared the MAVLink telemetry results with [BATTERY_STATUS](https://mavlink.io/en/messages/common.html#BATTERY_STATUS) using `MissionPlanner`->`Ctrl-F`->`MavLinkInspector`->`Vehicle1`->`Comp1`:
  - [x] voltage
  - [x] current
- [x] Make sure that BATT1 data (from FETtec ESCs) and BATT2 data (from a normal battery monitor) match in the `.bin` dataflash log files:
  - [ ] voltage
  - [x] current
  - [ ] consumed power
  - [ ] temperature (will not match, but is present and valid on BATT1)

Compared to master this PR needs just 592 bytes for ArduCopter on a Durandal flight controller :)

I also [backported most of this to ArduCopter-4.0.7](https://github.com/ArduPilot/ardupilot/pull/16874)

Flight logs will be uploaded to [Copting GmbH Google Drive](https://drive.google.com/drive/folders/15L3EWuRJ4yhAwteYoU15bQeZkAslj1bL?usp=sharing). It also contains older logs from previous firmware versions. Tested on a Hexacopter with Air gear 450 motors, FETtec OneWire ESCs and CubeOrange.

### CODE REVIEW

**Comment by teezeefpv** [comment]
I analyzed the log files provided by Copting in Dropbox.
This is from Log "00000123.BIN" with Notch disabled. I noticed that "INS_NOTCH_ENABLE" is 0 while "INS_HNTCH_ENABLE" is still 1. 

This picture shows the FFT for "00000123.BIN":
image

I compared it with LOG "00000120.BIN" where the "INS_NOTCH_ENABLE" is 1:
image

@andyp1per can you tell whether this is the expected behaviour for the dynamic notch?

Temperature is behaving normal and scaled correctly in Mission Planner and plot.ardupilot.org. 

Also consumed power is logged without issues. 
In my opinion this points can be checked.

image

Current for each ESC seems to be correct. As the config for the second current was  not correct it can not be easily compared. A new flight will be made for this.

**Comment by teezeefpv** [comment]
just flew outside and compared the current. 

image
Green is ESC telemetry current. 

image
The slight offset is ok, as the ESCs only measure the motor current.

image
As far as I see the visible difference is because of the lower sample rate from the analog sensor. When sampled at nearly the same time, the values mostly fit.



image
I missed the spikes on the voltage. Also haven't expected them to be there. I have no idea why there are spikes in the telemetry. I will investigate on that.

**Comment by amilcarlucas** [comment]
Please also compare the voltage, and the power consumption.
The temperature of the virtual battery must match the esc temperature

**Comment by andyp1per** [comment]
> @andyp1per can you tell whether this is the expected behaviour for the dynamic notch?

So it looks ok, except that it doesn't go low enough. I think this is because INS_HNTCH_FREQ represents the minimum frequency and in the case of this copter it should be lower. So I would change to something like:
```
INS_HNTCH_FREQ = 60
INS_HNTCH_BW = 30
```
then you will capture the below-hover-throttle noise

**Comment by teezeefpv** [comment]
Voltage looks good.
image

Consumption is a little bit confusing, as there is only one name for all usedmah values, but might be ok. 
image

There is only one label to choose in the log-analyser. And it seems to aggregate the variables to one plot, which causes it to jump between the values. The values differ because "battery_usedmah" for the overall current sensor is capturing the standby current and rising slowly before and after the flight, the ESCs only capture their own current while the motors spin.  The slope seems to be equal, when the motors spin. I am currently not very sure about this, because the flight was to short and only a few mAh are consumed. The logs of the next flight will show more.
image

Battery_Status->Temperatur is shown in the log-analyser, but "battery_temp" in the status is always 0.
image

**Comment by amilcarlucas** [comment]
@teezeefpv To make sure we bypass any mission planner display errors, please use the MissionPlanner->Ctrl-F->MavLinkInspector->Vehicle1->Comp1 to analyze the Mavlink telemetry data instead.

**Comment by teezeefpv** [comment]
> @teezeefpv To make sure we bypass any mission planner display errors, please use the MissionPlanner->Ctrl-F->MavLinkInspector->Vehicle1->Comp1 to analyze the Mavlink telemetry data instead.


This is from the live output from the Inspector.
image

I noticed, that the current consumed switches between -78510 and the used mAh.
image
image

**Comment by amilcarlucas** [comment]
@andyp1per looks like the BATTERY_STATUS Mavlink message contains false `temperature` and `current_consumed` data. Can you fix that on your PR?

**Comment by andyp1per** [comment]
Sure I will take a look

**Comment by amilcarlucas** [comment]
Closed in favor of #17255

**Pull request closed without merging**
