### PR TITLE
AP_GPS: To change from the decision process to bit processing.

### PR DESCRIPTION
**Pull request by muramura**
To change from the decision process to bit processing.
It expresses the non-use of the GPS information in the bit flag.
However, defining the position of the flag by the numerical value.
This definition is not easy to get a bit of information for numerical.
Therefore, the conversion from the numerical value of the bit value.
Can be obtained easily bit information by converting.

### CODE REVIEW

**Comment by magicrub** [comment]
may be more efficient and condensed but its still a little hard to read still. You seem really determined to optimize this specific section of logic :)

**Comment by OXINARF** [comment]
I still think this is more unreadable.

And I think you shouldn't import math.h directly, but our AP_Math.h

**Comment by muramura** [comment]
Build for Navio2
To the source of up to revision "commit 32a74e37d26d78b4df4daea3be7a3970f781982f", it is changed only this "AP_GPS_MAV.cpp".

I finished the build successfully.

What for this phenomenon may be what kind deal.
＝＝＝
[737/737] Linking build/navio2/bin/arducopter-hexa
Waf: Leaving directory `/home/pi/work/ardupilot/build/navio2'
BUILD SUMMARY
Build directory: /home/pi/work/ardupilot/build/navio2
Target               Text    Data  BSS    Total 
------------------------------------------------
bin/arducopter-hexa  924153  1484  35228  960865

**Comment by kwikius** [comment]
@muramura 

This can be done neatly  with bitfields  in a union:
(You would need to add tests though to check it works OK on all platforms)
```c++
#include <cstdint>

union gps_ignore_bits{

   struct {
      bool const alt : 1;
      bool const hdop : 1;
      bool const vdop : 1;
      bool const vel_horiz:1;
      bool const vel_vert :1;
      bool const speed_accuracy : 1;
      bool const horz_accuracy : 1;
      bool const vert_accuracy : 1;
   };
   private:
   uint8_t m_value;
   public:
   gps_ignore_bits(uint8_t v):m_value{static_cast<uint8_t>(v ^ 0xFF)}{};

} __attribute__((__packed__));

#include <iostream>

constexpr uint8_t vert_accuracy = 1 << 7;
constexpr uint8_t hdop = 1 << 1;
int main()
{
   gps_ignore_bits ignore_bits{vert_accuracy | hdop};

   std::cout << "ignore vert acc ? " << std::boolalpha << ignore_bits.vert_accuracy <<'\n';
   std::cout <<  "ignore alt ? " << ignore_bits.alt <<'\n';
   std::cout <<  "ignore hdop ? " << ignore_bits.hdop <<'\n';
}
```

**Comment by muramura** [comment]
@kwikius Comment Thank you.
This program was run by Navio2 (raspberry PI3).
result:
ignore vert acc ? false
ignore alt ? true
ignore hdop ? false

I think.
This result is not correct.

**Comment by muramura** [comment]
I saw the test results.
However, what to do, I do not know.
I want to receive advice.

**Comment by kwikius** [comment]
@muramura. I updated the example. Is it correct now?

```c++

#include <cstdint>

// fake up the mavlink stuff
struct mavlink_gps_input_t{
  uint8_t ignore_flags;
};

union gps_have_bits{

   struct {
      bool const alt : 1;
      bool const hdop : 1;
      bool const vdop : 1;
      bool const vel_horiz:1;
      bool const vel_vert :1;
      bool const speed_accuracy : 1;
      bool const horz_accuracy : 1;
      bool const vert_accuracy : 1;
   };
   private:
   uint8_t m_value;
   public:
   gps_have_bits(mavlink_gps_input_t const & packet):m_value{static_cast<uint8_t>(~packet.ignore_flags)}{};

} __attribute__((__packed__));

#include <iostream>


template <bool B> bool expect(const char * text, bool in)
{
   std::cout << "have "<< text << "  = " << std::boolalpha << in << ": ";
   bool result = false;
   if ( in == B){
      std::cout << "PASS";
      result = true;
   }else{
      std::cout << "FAIL";
   }
   std::cout << "\n";
   return result;
}

int main()
{
   mavlink_gps_input_t packet;
   packet.ignore_flags = (1<<7) | (1<<1); // ignore hdop and vert_accuracy
   gps_have_bits have_bits{packet};

   bool result = 
   expect<true>("alt",have_bits.alt) &&
   expect<false>("hdop",have_bits.hdop) &&    // ignore hdop and vert_accuracy
   expect<true>("vdop",have_bits.vdop) &&
   expect<true>("vel_horiz",have_bits.vel_horiz) &&
   expect<true>("vel_vert",have_bits.vel_vert) &&
   expect<true>("speed_accuracy",have_bits.speed_accuracy) &&
   expect<true>("horz_accuracy",have_bits.horz_accuracy) && 
   expect<false>("vert_accuracy",have_bits.vert_accuracy);    // ignore hdop and vert_accuracy

   if ( result){
     std::cout << "\n------------------ TEST PASSED :) -------------------\n";
   }else{
     std::cout << "\n------------------ TEST FAILED :( -------------------\n";
   }
}
```

**Comment by muramura** [comment]
@kwikius Comment Thank you.
In the past, in combination with the bitset of the "structure of the bit" I have been in PR.
This PR Comments:
bit definition (numeric, bit7 = 128, bit6 = 64 ... bit0 = 1) is performed at MAVLink side.
When the bit definition is changed, to correct this "structure of the bit".
Please consider a method that does not have this "structure of the bit" to this method.

Therefore,
As one of the ideas was this PR.

**Comment by muramura** [comment]
To modify the format of the citation of AP_Math.h.
To < > from " ".

**Comment by kwikius** [comment]
@muramura. Sure but it is unlikely to change. You can add static assert to make sure. 

You can also put the gps_have_bits definition in a header and your source code will be really clean :)

```c++
// fake up the mavlink stuff
#if 0
#define GPS_INPUT_IGNORE_FLAG_ALT   ((uint8_t) 1U << 0U)
#define GPS_INPUT_IGNORE_FLAG_HDOP  ((uint8_t) 1U << 1U)
#else
// ######################## I SWITCHED THESE Flags too these so it will fail now
#define GPS_INPUT_IGNORE_FLAG_ALT   ((uint8_t) 1U << 1U)
#define GPS_INPUT_IGNORE_FLAG_HDOP  ((uint8_t) 1U << 0U)
//###################################################################
#endif

#define GPS_INPUT_IGNORE_FLAG_VDOP  ((uint8_t) 1U << 2U)
#define GPS_INPUT_IGNORE_FLAG_VEL_HORIZ ((uint8_t) 1U << 3U)
#define GPS_INPUT_IGNORE_FLAG_VEL_VERT  ((uint8_t) 1U << 4U)
#define GPS_INPUT_IGNORE_FLAG_SPEED_ACCURACY ((uint8_t) 1U << 5U)
#define GPS_INPUT_IGNORE_FLAG_HORIZONTAL_ACCURACY ((uint8_t) 1U << 6U)
#define GPS_INPUT_IGNORE_FLAG_VERTICAL_ACCURACY  ((uint8_t) 1U << 7U)

#include <cstdint>

struct mavlink_gps_input_t{
  uint8_t ignore_flags;
};

//--------------- gps_have_bits.h -------------------

union gps_have_bits{

   struct {

     static_assert(  (GPS_INPUT_IGNORE_FLAG_ALT                      == 0b1) && 
                     (GPS_INPUT_IGNORE_FLAG_HDOP                     == 0b10) && 
                     (GPS_INPUT_IGNORE_FLAG_VDOP                     == 0b100) &&  
                     (GPS_INPUT_IGNORE_FLAG_VEL_HORIZ                == 0b1000) &&   
                     (GPS_INPUT_IGNORE_FLAG_VEL_VERT                 == 0b10000) &&  
                     (GPS_INPUT_IGNORE_FLAG_SPEED_ACCURACY           == 0b100000) && 
                     (GPS_INPUT_IGNORE_FLAG_HORIZONTAL_ACCURACY      == 0b1000000) &&  
                     (GPS_INPUT_IGNORE_FLAG_VERTICAL_ACCURACY        == 0b10000000)  ,
// ################################ Someone changed the mavlink gps flags ###########################
                     " Hey? Mavlink GPS Flags have been changed !!! " );
// ################################ Someone changed the mavlink gps flags ###########################

      bool const alt : 1;
      bool const hdop : 1;
      bool const vdop : 1;
      bool const vel_horiz:1;
      bool const vel_vert :1;
      bool const speed_accuracy : 1;
      bool const horz_accuracy : 1;
      bool const vert_accuracy : 1;
   };
   private:
   uint8_t m_value;
   public:
   gps_have_bits(mavlink_gps_input_t const & packet):m_value{static_cast<uint8_t>(~packet.ignore_flags)}{};

} __attribute__((__packed__));

// ------------------- ~ gps_have_bits.h -----------------------

#include <iostream>

template <bool B> bool expect(const char * text, bool in)
{
   std::cout << "have "<< text << "  = " << std::boolalpha << in << ": ";
   bool result = false;
   if ( in == B){
      std::cout << "PASS";
      result = true;
   }else{
      std::cout << "FAIL";
   }
   std::cout << "\n";
   return result;
}

int main()
{
   // fake up the mavlink stuff
   mavlink_gps_input_t packet;
   packet.ignore_flags = GPS_INPUT_IGNORE_FLAG_VERTICAL_ACCURACY | GPS_INPUT_IGNORE_FLAG_HDOP; // ignore hdop and vert_accuracy

   gps_have_bits have_bits{packet};

   bool result = 
   expect<true>("alt",have_bits.alt) &&
   expect<false>("hdop",have_bits.hdop) &&    // ignore hdop and vert_accuracy
   expect<true>("vdop",have_bits.vdop) &&
   expect<true>("vel_horiz",have_bits.vel_horiz) &&
   expect<true>("vel_vert",have_bits.vel_vert) &&
   expect<true>("speed_accuracy",have_bits.speed_accuracy) &&
   expect<true>("horz_accuracy",have_bits.horz_accuracy) && 
   expect<false>("vert_accuracy",have_bits.vert_accuracy);    // ignore hdop and vert_accuracy

   if ( result){
     std::cout << "\n------------------ TEST PASSED :) -------------------\n";
   }else{
     std::cout << "\n------------------ TEST FAILED :( -------------------\n";
   }
}
```

**Comment by muramura** [comment]
https://github.com/ArduPilot/mavlink/pull/19
To add a bit definition to common.xml of Mavlink.
To PR in this github.

**Comment by OXINARF** [comment]
@muramura I have talked about this with @WickedShell (the maintainer of GPS library) and we decided that this didn't bring great benefit and it is harder to read. We appreciate your contributions (you have been fixing things nobody notices which is awesome!) and we hope you continue to open PRs to fix or improve other pieces of code.

**Comment by WickedShell** [comment]
I'm closing this as it's cluttering the code up significantly, for a very, very small if any win.

**Comment by muramura** [comment]
@OXINARF, @WickedShell  
thank you for yours comments.
Thank you for yours consideration.
I understand.
I will push the new PR.

**Pull request closed without merging**
