### PR TITLE
Increase CH_CFG_ST_TIMEDELTA on BeastH7 and disable ISR during flash updates

### PR DESCRIPTION
**Pull request by andyp1per**
Without these changes the BeastH7 will continuously watchdog

### CODE REVIEW

**Comment by tridge** [comment]
> Without these changes the BeastH7 will continuously watchdog

on master?
I think we need to work out why. Changing the timedelta doesn't make any sense to me on a H7.
I really wish my BeastH7 would arrive!

**Comment by andyp1per** [comment]
> on master?
> I think we need to work out why. Changing the timedelta doesn't make any sense to me on a H7.
> I really wish my BeastH7 would arrive!

Yes on master. I discovered this by having a debug build and looking at the fault code. The ChibiOS code recommends increasing the time delta as a solution.

**Comment by andyp1per** [comment]
Note that with these changes the board is perfectly stable, without them it is not.

**Comment by tridge** [comment]
> The ChibiOS code recommends increasing the time delta as a solution.

can you point me at that recommendation?

**Comment by andyp1per** [comment]
http://forum.chibios.org/viewtopic.php?t=4611

**Comment by andyp1per** [comment]
Closing in favour of https://github.com/ArduPilot/ardupilot/pull/18416

**Comment by tiralonghipol** [comment]
@andyp1per  what is the latest version of usable firmware for the iFlight Beast h7? any link?
thanks!

**Comment by andyp1per** [comment]
https://firmware.ardupilot.org/Copter/beta/BeastH7/ or https://firmware.ardupilot.org/Copter/latest/BeastH7/

**Comment by tiralonghipol** [comment]
Thank you so much! Will test it soon, I just got the board

**Pull request closed without merging**
