### PR TITLE
Tools: Add JSON format in param_parse

### PR DESCRIPTION
**Pull request by patrickelectric**
Example output here:
https://jsonblob.com/4fc798b8-2137-11ea-95cc-9db3a505b5b0

### CODE REVIEW

**Comment by peterbarker** [comment]
output doesn't look correct; too much stuff being thrown into "fields"?

```
"fields": {
            "0": "Disabled",
            "1": "Enabled"
          },
```

**Comment by WickedShell** [comment]
The nesting under vehicles seems weird... It gives the top level library name (IE `AHRS_`) but then has an array of maps, why wouldn't it be a map of maps, where the keys are the param names as sent via MAVLink? It would be less data in the file and much easier to look up. (Frankly I'd actually remove the entire `param` indirection layer, and the `AHRS_` and just have a single map by name to each param by name at the top level.) The collation to `AHRS_` can easily be done by a GCS/consuming client, and they also may want to collapse them further, I'm not sure what this outside level is actually buying you. (I know we did this kind of thing in some of the other emitters, but it always seems to be buying complexity, particularly when it's in a more data oriented format like this.

**Comment by patrickelectric** [comment]
> output doesn't look correct; too much stuff being thrown into "fields"?
> 
> ```
> "fields": {
>             "0": "Disabled",
>             "1": "Enabled"
>           },
> ```

This should be in a "value" key right ?

**Comment by patrickelectric** [comment]
> The nesting under vehicles seems weird... It gives the top level library name (IE `AHRS_`) but then has an array of maps, why wouldn't it be a map of maps, where the keys are the param names as sent via MAVLink? It would be less data in the file and much easier to look up. (Frankly I'd actually remove the entire `param` indirection layer, and the `AHRS_` and just have a single map by name to each param by name at the top level.) The collation to `AHRS_` can easily be done by a GCS/consuming client, and they also may want to collapse them further, I'm not sure what this outside level is actually buying you. (I know we did this kind of thing in some of the other emitters, but it always seems to be buying complexity, particularly when it's in a more data oriented format like this.

I'll try to organize it better.

**Comment by magicrub** [comment]
fields should not be "value", should be "values".

By the way, I love this! Thank you for making it!!

**Comment by WickedShell** [comment]
@patrickelectric The rough format I'd suggest is actually this: https://jsonblob.com/9e0fb0e6-21ef-11ea-95cc-1f58f337144d (I arrived at this by just taking the EDN output, and running it out a JSON encoder). The main feature of this is params are easy to look up by name. Of special note the LOG_BITMASK is an interesting example, look at how I managed the bitmask values, it's just an array where the bit number is the index, and any skipped entries just get a null value written out.

**Comment by patrickelectric** [comment]
New version available, you can check the output here: https://jsonblob.com/26d9ea12-25f2-11ea-8b19-37dd860a7f4f
I'm using the vehicle name as the main key since this makes more sense and allow multiple vehicles being defined in the same json.

From the examples provided by @WickedShell, this version does not have the 'name' field since it's the same as the key but everything else should be the same.

**Comment by WickedShell** [comment]
@patrickelectric Why have things like `ArduSub:ACRO_BAL_PITCH`. Surely the prefix is unneeded and making it more confusing?

I'd recommend doing the splitting of the Bitmask in some form in the generator, so a user isn't responsible for doing the regex to split the string on commas/separate out the bit number. I found that it was actually hard to have a robust rule for this, and when I did the EDN generator I could make it a compile time failure where we had bad doc strings, which actually let me fix problems in a couple of libraries. So lifting the splitting of the bits out of being a consumers problem is definitely worth it. The same comment applies to the values entry as well.

**Comment by patrickelectric** [comment]
> @patrickelectric Why have things like `ArduSub:ACRO_BAL_PITCH`. Surely the prefix is unneeded and making it more confusing?

That's not the intended behaviour, the file has 10k lines and some problems are hard to catch, sorry.

> I'd recommend doing the splitting of the Bitmask in some form in the generator, so a user isn't responsible for doing the regex to split the string on commas/separate out the bit number. I found that it was actually hard to have a robust rule for this, and when I did the EDN generator I could make it a compile time failure where we had bad doc strings, which actually let me fix problems in a couple of libraries. So lifting the splitting of the bits out of being a consumers problem is definitely worth it. The same comment applies to the values entry as well.

That's a good idea, I believe that the last version here provides that:
https://jsonblob.com/90eff412-2638-11ea-8b19-194c524ac128

**Comment by patrickelectric** [comment]
@WickedShell @peterbarker @magicrub, any update ?

**Comment by patrickelectric** [comment]
Ping

**Comment by WickedShell** [comment]
I'm happy with the JSON output at this point, although I haven't audited the code for it. I'm not sure why the XML output is dieing.

**Comment by peterbarker** [comment]
@patrickelectric perhaps we ought to add a format-version field in case you want to fiddle with this at a later date?

**Comment by WickedShell** [comment]
@patrickelectric Ah, XML output is broken because you are mutating the state that's passed into you. You need to consider that read only (or just make yourself a copy first). After that's fixed we should be ready to start bringing it in.

**Comment by patrickelectric** [comment]
@WickedShell yes, I just found it thanks!

@peterbarker good idea!

**Comment by patrickelectric** [comment]
One of the travis tests related to arducopter failed: FAILED 1 tests: ['fly.ArduCopter']
But I believe that it's not related to this patch.

**Comment by peterbarker** [comment]
Merged it, thanks!

**Pull request merged**
