### PR TITLE
Added ESC_TELEMETRY to mavlink streams

### PR DESCRIPTION
**Pull request by tridge**
This was lost in the rebase of the previous PR
ping @priseborough and @Naterater

### CODE REVIEW

**Comment by priseborough** [comment]
Can confirm that ESC messages are received when this patch is incorporated. There are some plotting issues when using mavproxy, but that is a separate issue.

**Comment by tridge** [comment]
thanks Paul. You can graph in mavproxy with square brackets to show the individual RPMs.
For example, if you added this to your $HOME/.mavinitrc:

@alias add gesc2rpm graph ESC_TELEMETRY_1_TO_4.rpm[0] ESC_TELEMETRY_1_TO_4.rpm[1]

then typing "gesc2rpm" will show you a graph with RPM for the first two ESCs

**Comment by priseborough** [comment]
I notice with my bench testing that when using the ESC telemetry as a surrogate power monitor via setting BATT_MONITOR = 9, that the current displayed when plotting BATTERY_STATUS.current_battery is high by a factor of 8 compared to both the ESC_TELEMETRY_1_TO_4.current and an off-board power meter.

**Comment by priseborough** [comment]
Found the issue. The BLHeli battery monitor calculation averages current across 8 motors regardless of how many are being monitored: https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_BattMonitor/AP_BattMonitor_BLHeliESC.cpp#L45

AP_BLHELI_MAX_ESCS is hardcoded to 8

**Comment by priseborough** [comment]
The precise factor of 8 has also been confirmed in the data log - see

screen shot 2018-06-26 at 9 19 56 pm

It looks like this is a corner case that occurs if the second ESC (in a twin engine plane) does not send telemetry which suggests that this function call https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_BattMonitor/AP_BattMonitor_BLHeliESC.cpp#L47 is returning the same ESC1 data for all indexes in this situation.

**Comment by Evan1010** [comment]
Just to be clear, ESC Telemetry for UAVCAN is still unimplemented? I can't find any handlers for it in the codebase.

**Pull request merged**
