### PR TITLE
AP_InertialSensor: use primary gyro (not accel) for get_delta_angle_dt

### LINKED ISSUE #8463: why function get_delta_angle_dt use _primary_accel, but not _primary_gyro?
Hi, all

I'm reading following source, and see that function get_delta_angle_dt is using _primary_accel.
Should it use _primary_gyro?

https://github.com/ArduPilot/ardupilot/blob/b014b6c85720aaa1459112e404443212c786244f/libraries/AP_InertialSensor/AP_InertialSensor.h#L111

### PR DESCRIPTION
**Pull request by peterbarker**
Closes #8463

### CODE REVIEW

**Comment by magicrub** [comment]
this seems kinda major

**Comment by peterbarker** [comment]
@magicrub FWIU there's really only one device out there that this would affect.  But yes, it does seem odd!

**Review by tridge — APPROVED** [review]

**Comment by tridge** [comment]
definately needs a flight test, but I'm sure this is correct (and also won't make any difference)

**Comment by peterbarker** [comment]
Flight tested just fine.

**Pull request merged**
