### PR TITLE
Plane: backport support for Python 3.12 to 4.5

### PR DESCRIPTION
**Pull request by jonhoo**
Backport of https://github.com/ArduPilot/ardupilot/pull/26889.

### CODE REVIEW

**Comment by jonhoo** [comment]
Apologies for the force pushes – my local `Plane-4.5` was behind so wanted to make this apply cleanly before review.

**Comment by peterbarker** [comment]
This is a single commit - was this really a single commit into master?  That would be contrary to our usual standards as it's got a mavlink commit in there.

We need to know what else went into that mavlink branch as part of that new submodule reference.  We might need to reference a new commit in there if we are uncomfortable with other stuff implied by that mavlink submodule update

**Comment by jonhoo** [comment]
The original PR was indeed three commits, though the commits that updated the individual subprojects weren't any more informative than "python 3.12 support":

- https://github.com/ArduPilot/ardupilot/pull/26889/commits/31e15c18629d877873ba6ea613092939f779ca46
- https://github.com/ArduPilot/ardupilot/pull/26889/commits/c523dc096e3f1b701a28cd51d6c885efa198a94d

**Comment by jonhoo** [comment]
The CI failure seems pretty weird (and maybe unrelated?):

```
ld: building fixups: pointer not aligned at __ZN12AP_FWVersion5fwverE+0x34 from /Users/runner/work/ardupilot/ardupilot/build/sitl/AntennaTracker/Tracker.cpp.47.o
```

**Comment by jonhoo** [comment]
Now, it _is_ true that for the backport, this ends up picking up a few extra commits to mavlink, but a cursory look at them suggests they'd be okay to bring in here (i.e., not worth doing a cherry-pick):

https://github.com/ArduPilot/mavlink/compare/1e04d8b8634dafc8c9a2496c6922e0749e00c009...2825252d6d13eb347520f028b3c580ab29bd78e5%5E

**Comment by peterbarker** [comment]
@jonhoo this is unlikely to be merged as a single commit.

Thanks for checking out the mavlink commits.

The CI failure happens at random on MacOSX.   Fixed in https://github.com/ArduPilot/ardupilot/pull/26700 - I've marked that for backporting.

**Comment by jonhoo** [comment]
Okay, I have now cherry-picked the individual commits instead.

**Comment by jonhoo** [comment]
Is it worth also backporting this to 4.3 and 4.4?

**Comment by rmackay9** [comment]
Hi @jonhoo,

Thanks for this.  I don't think it's worth creating a 4.3 or 4.4 backport because we don't plan to do any more releases for those version.

**Comment by rmackay9** [comment]
This is included in Copter-4.5.7-beta1

**Pull request merged**
