### PR TITLE
Tools setup script for Ubuntu 15.10 failed

### PR DESCRIPTION
**Pull request by billbonney**
Using these instructions the script failed on 15.10

http://dev.ardupilot.com/wiki/building-px4-for-linux-with-make/

Created a new script for 15.10
Fixed the Yes/NO question prompt to show N is default

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
Can we have a single script and if needed just tweak its behavior?  In the long run maintaining more scripts is troublesome.

**Comment by billbonney** [comment]
Well maintaining one script isn't working, so I agree!. I'll get a better one when I have bit more time, but at least now we know it's an issue

**Comment by khancyr** [comment]
Hum strange, got lubuntu 15.10 and it is working fine...

**Comment by lucasdemarchi** [comment]
@khancyr these are supposed to be the same versions. What problem did you have?

**Comment by khancyr** [comment]
my bad... Wily default arm-none-eabi isn't working .... So we must stick to the one on dyidrone website or use https://launchpad.net/~terry.guo/+archive/ubuntu/gcc-arm-embedded (normaly the last one is the same than dyidrone)

**Comment by lucasdemarchi** [comment]
ok... so I think the problem is that in the new ubuntu version there's a package with the same name as the one in the ppa, but it doesn't work. Adding the ppa and trying to install apparently installs the one from the ubuntu repository and not from the ppa.

However the current script doesn't use the toolchain from the ppa, but rather download it directly. So... not sure what this PR fixes actually.

**Comment by khancyr** [comment]
Toolchains problem is a side problem. We may ask for user on ubuntu >15.10 if they want to remove default ubuntu arm-none-eabi toolchain and dl the one on diydrone website.
Bill modification's change gcc-4.6-base:i386 to gcc-5-base:i386 for ubuntu 15.10 and use N as default response. 
By the way, why use gcc-4.6-base:i386 since we use gcc-4.9 everywhere ? (and why i386 ? )

**Comment by lucasdemarchi** [comment]
GCC 4.6 shouldn't really be there. There are lots of outdated dependencies here. I think the the CI scripts are more authoritative on needed packaged

**Comment by lucasdemarchi** [comment]
any update on this?

**Comment by lucasdemarchi** [comment]
Should be fixed by #3917 or a variant thereof, so closing this.

**Pull request closed without merging**
