### PR TITLE
AC_WPNav: reduce vehicle twitch between spline and straight waypoint commands

### PR DESCRIPTION
**Pull request by rmackay9**
When a copter completes a spline waypoint and the next waypoint is a straight line waypoint, the waypoint controller commands the vehicle to slow down for a moment before returning to the desired speed (held in WPNAV_SPEED).  To the user this appears as a slightly ugly twitch backwards.

splinetostraighttwitch

The reason for the slow-down relates to how we use the "leash" differently in spline and straight-line waypoints.  The "leash" connects the vehicle and the target point that it's chasing.  The target point advances along the segment between the previous and next waypoint but is held back from traveling too far along the segment by this leash.

In the spline controller, the leash is a straight line between the vehicle and the target point  In the straight line controller however it's an "L" shape so it extends from the vehicle to the closest point on the segment and from there it extends to the target point.

This PR changes the straight line waypoint controller's leash so that it's effectively a straight line between the vehicle and target point. So as to not rewrite everything though, I've just calculated the sides of the "L" shaped leash so it's equivalent.

splinetostraightbeforeafter

I ran over this with Leonard and he's happy with this change.

By the way, we know the reason for the remaining 3 degrees of twitch which I've raised an issue for here: https://github.com/ArduPilot/ardupilot/issues/6115

### CODE REVIEW

**Comment by khancyr** [comment]
Hello, I got just in implementation question  
```
    float track_leash_length_sq = sq(_track_leash_length);
    float track_error_z_sq = sq(track_error_z);
    float track_error_xy_sq = sq(track_error_xy);
    float track_leash_slack_z = (track_leash_length_sq > track_error_z_sq) ? safe_sqrt(track_leash_length_sq-track_error_z_sq) : 0;
    float track_leash_slack_xy = (track_leash_length_sq > track_error_xy_sq) ? safe_sqrt(track_leash_length_sq-track_error_xy_sq) : 0;
    track_leash_slack = MIN(track_leash_slack_z, track_leash_slack_xy);
    track_desired_max = track_covered + track_leash_slack;
```
Instead of using square calculus and sqrt, why don't just use abs ?
```
    float track_leash_slack_z = fabsf(track_leash_length) - fabsf(track_error_z);
    if (track_leash_slack_z < 0) {
        track_leash_slack_z = 0;
    }
    float track_leash_slack_xy = fabsf(track_leash_length) - fabsf(track_error_xy);
    if (track_leash_slack_xy < 0) {
        track_leash_slack_xy = 0;
    }
    track_leash_slack = MIN(track_leash_slack_z, track_leash_slack_xy);
    track_desired_max = track_covered + track_leash_slack;
```
It is equivalent but computationaly simplier no ?

**Comment by OXINARF** [comment]
@khancyr Either my math is failing me or that isn't equivalent.

@rmackay9 I know this area of code very badly so I can't be of much help here. If Leonard is OK with it and you've tested it, I think it's good to go.

**Comment by EShamaev** [comment]
@khancyr It might be done computationally simpler if square root is taken one time depending on the (track_error_z_sq < track_error_xy_sq) and not twice and removing sq if it's not needed.

`
float track_leash_length_abs = fabsf(_track_leash_length);
float track_error_z_abs = fabsf(track_error_z);
float track_error_xy_abs = fabsf(track_error_xy);

if(track_error_z_abs > track_error_xy_abs)
{
    track_desired_max = (track_leash_length_abs > track_error_z_abs) ? safe_sqrt(sq(track_leash_length) -sq(track_error_z)) : 0;
} else {
    track_desired_max = (track_leash_length_abs > track_error_xy_abs) ? safe_sqrt(sq(track_leash_length) -sq(track_error_xy)) : 0;
}
`

**Comment by khancyr** [comment]
@oxinarf let's prentend I said nothing 😵

**Comment by EShamaev** [comment]
Or another way, simpler to read:

```
float track_leash_length_abs = fabsf(_track_leash_length);
float track_error_max_abs = MAX(fabsf(track_error_z), fabsf(track_error_xy));

track_desired_max = (track_leash_length_abs > track_error_max_abs) ? safe_sqrt(sq(_track_leash_length) -
 sq(track_error_max_abs)) : 0;
```

This way, worst case is 1 sqrt and 2 sq instead of 2 sqrt and 3 sq. Best case is 0 sqrt and 0 sq instead of 0 sqrt and 3 sq. I consider fabs negligibly fast.

**Comment by rmackay9** [comment]
Thanks for the review.  I've modified to incorporate @EShamaev's improved calcs (I've tested and it's equivalent after adding "track_covered").  I'll push to master once travis says it's ok.  thanks again!

**Pull request merged**
