### PR TITLE
Update GIT_Success.txt

### PR DESCRIPTION
**Pull request by santosh-mahadev**
test commit

### CODE REVIEW

**Comment by khancyr** [comment]
hello,

You are close to have it right. You two smalls mistakes : 
- you need to make the git commit message to explain briefly what your change are doing. In this case, you add your name to the GIT_Success.txt file.
- On ArduPilot we append the subsystem change on the git commit message.
Then a good message would be "Tools: added name to GIT_Success.txt"
That what you find in the wiki : https://ardupilot.org/dev/docs/git-branch.html

To correct your git message you will have to learn some new commands. The simpler will be to do a `git commit --amend` this will allow you to modify the message. Then you will need to force push (`git push -f`) you branch to your fork to update the pull request on Github.

Good luck. 
If you have more issue, feel free to ask more assistance here or on gitter

**Comment by santosh-mahadev** [comment]
hi 
how to amend commit on github desktop I don't find option for commit amend. Please let me know

**Comment by khancyr** [comment]
Hello,

This need a little rework as I explain. Feel free to do the rework and open back this PR or another. I am closing this for now.
Thanks

**Comment by magicrub** [comment]
@khancyr  oh geez, come on. This should have been merged as-is. The folder prefix on the comment is to help with sorting during releases. seeing "GIT_Success.txt" is clarity enough. Being ultra-strict on PRs like this, especially on their first, is not productive.

**Pull request closed without merging**
