### PR TITLE
AP_Arming.cpp: fix _CHECKS param description

### PR DESCRIPTION
**Pull request by vierfuffzig**
this fixes the reference to default being 0, which imho is long deprecated.

### CODE REVIEW

**Review by peterbarker — APPROVED** [review]
Should've been fixed long ago, thanks.

**Review by amilcarlucas — APPROVED** [review]

**Review by rmackay9 — CHANGES_REQUESTED** [review]
This is better but this line is a bit awkward, "For most users it is recommended to not set this away from default (1 = all checks enabled)."

I think we should change this line to, "Most users should leave this at the default value of 1 (all checks enabled)."

**Comment by vierfuffzig** [comment]
thanks @rmackay9 i‘ll fix this accordingly.

**Comment by peterbarker** [comment]
I've just fixed the commit message up (`AP_Arming.cpp -> AP_Arming`), and intend to merge it after CI passes.

**Comment by vierfuffzig** [comment]
thanks @peterbarker !

**Comment by peterbarker** [comment]
Merged, thanks!

**Pull request merged**
