### PR TITLE
autotest: correct sub parameter name PSC_VELZ_P, fix test to match

### PR DESCRIPTION
**Pull request by peterbarker**
This parameter is present in the parameters file but doesn't actually exist on the vehicle.

Correcting the name leads to some different control, so there's a minor update to one of the tests.

### CODE REVIEW

**Comment by peterbarker** [comment]
Happy to take suggestions on alternative values for the P gain instead :-)

**Comment by peterbarker** [comment]
@patrickelectric @Williangalvani I've got a PR which has to include this fix (it's more rigorous in terms of making sure the parameters in those files actually apply!).

I'd like to merge this and we can tighten up the parameter and test parameter later....

**Comment by Williangalvani** [comment]
Sounds reasonable to me. I have been meaning to improve the depth hold tests for a while now to take more cases in consideration, so I expect I'll revisit these parameters soon.

**Comment by rmackay9** [comment]
Merged after approvals from Patrick and Willian

**Pull request merged**
