### PR TITLE
Copter 3.3 gps NMEA fix

### PR DESCRIPTION
**Pull request by mahisorn**
Allow GPxxx, GNxxx, and GXxxx NMEA messages to be parsed by in Copter 3.3.3.
Code is copied from master branch.

### CODE REVIEW

**Comment by fnoop** [comment]
Great!
https://github.com/ArduPilot/ardupilot/issues/1241

**Comment by OXINARF** [comment]
@mahisorn I don't think we will have any other 3.3 release, in which case this is unneeded.

**Comment by mahisorn** [comment]
@OXINARF If there is no further release or patch version of 3.3, I agreed that this pull request is not needed. 

My intention is to make Tersus working on 3.3.3 because the latest stable version offered by Mission Planner and QGroundControl is 3.3.3 (as of 2016-05-10). For someone that is planing to use 3.3.3 in there product. This information might be helpful and save them sometime :)

By the way, the NMEA code in master branch do not have this issue.

**Comment by OXINARF** [comment]
@mahisorn This depends on @rmackay9, but we are getting ready to start beta testing of 3.4 (master), and because this isn't an issue that impacts safety, I don't think that releasing a patch with it is probable. But let's wait for Randy's answer.
Thank you for your work anyway :+1:

**Comment by rmackay9** [comment]
Yes, I have to say that I'm not super keen to do a full release just for this fix considering that Copter-3.4 is about to begin beta testing.

**Comment by mahisorn** [comment]
@rmackay9 Thank you for clarifying the releasing process. Since I already agreed with @OXINARF, should we close this pull request and leave it as a reference for other 3.3 users that might need this fix ?

**Comment by OXINARF** [comment]
We all agree, so I'm closing it.

**Pull request closed without merging**
