### PR TITLE
AP_NavEKF2: clear error message after initialize complete

### LINKED ISSUE #14048: AP_NavEKF2: report 'EKF2 still initialising" but it is actually "Fence enabled, need 3D Fix"
## Bug report

**Issue details**
EK2_GPS_TYPE=3, GPS_TYPE=0, EK2_GPS_CHECK=0, FENCE_ENABLE=1
Copter will keep showing

> PreArm: EKF2 still initialising

But EKF is actually fine (initialization is completed). It is the fence cause problem. It may cause confusion and mislead users to report EKF problem.

**Version**
V4.0.4-dev, current master

**Platform**
[X] Copter

**Airframe type**
Quadcopter

**Hardware type**
KakuteF7

### PR DESCRIPTION
**Pull request by chobitsfan**
fix #14048

### CODE REVIEW

**Comment by peterbarker** [comment]
Why are we asking for a prearm failure reason without first checking that the EKF won't do what we need it to do?

**Comment by chobitsfan** [comment]
Thank you @peterbarker 

In `AP_Arming_Copter::mandatory_gps_checks`

https://github.com/ArduPilot/ardupilot/blob/f70ab73a1f6747a5773c29c73a487b89b27f52a8/ArduCopter/AP_Arming.cpp#L531-L536

When fence is enabled but position is not OK,  EKF is asked for a fail reason. Because users set EK2_GPS_TYPE=3, EKF has no fail message. So it return latest message, that is ` EKF2 still initialising`. But EKF is actually initialized. If it return nullptr, `mandatory_gps_checks` will report `Fence enabled, need 3D Fix`. which is the correct reason

**Comment by rmackay9** [comment]
We discussed this on the dev call and the odd thing is that the Copter pre-arm checks are using position_ok() and then asking the ahrs for it's failure string.  Really the arming checks should only ask for that arming string if the ahrs pre-arm check is failing... so I think we need to add this call to the ahrs and if that passes then the copter arming checks should output some other reason string.

**Comment by chobitsfan** [comment]
Thank you @rmackay9 
I found copter call `prearm_failure_reason()` twice
https://github.com/ArduPilot/ardupilot/blob/04b0a8a62a65c4cfec7e899f5872315c1df8e8ef/ArduCopter/AP_Arming.cpp#L507-L508

https://github.com/ArduPilot/ardupilot/blob/04b0a8a62a65c4cfec7e899f5872315c1df8e8ef/ArduCopter/AP_Arming.cpp#L531-L537

It seems a little strange. maybe it is related to fence?

**Comment by chobitsfan** [comment]
Thank @rmackay9 for suggestions. I am closing it for #14104

**Pull request closed without merging**
