### PR TITLE
AP_ExternalAHRS: Reserve Aeron ID

### PR DESCRIPTION
**Pull request by Jackwooh**
We are planning to add our IMU support as an ExternalAHRS in the Ardupilot.

### CODE REVIEW

**Review by Ryanf55 — APPROVED** [review]

**Review by IamPete1 — CHANGES_REQUESTED** [review]
Per https://github.com/ArduPilot/ardupilot/pull/25773#issuecomment-1856046906 commit message needs fixing. `AP_ExternalAHRS: Reserve aaeron ID` 

You should be able to do a interactive rebase and reword it. https://ardupilot.org/dev/docs/git-interactive-rebase.html

@Ryanf55 or myself could do it for you if you can't work it out.

**Comment by IamPete1** [comment]
I have fixed up the commit message.

**Comment by Ryanf55** [comment]
> Per [#25773 (comment)](https://github.com/ArduPilot/ardupilot/pull/25773#issuecomment-1856046906) commit message needs fixing. `AP_ExternalAHRS: Reserve aaeron ID`
> 
> You should be able to do a interactive rebase and reword it. https://ardupilot.org/dev/docs/git-interactive-rebase.html
> 
> @Ryanf55 or myself could do it for you if you can't work it out.

Thanks for catching that, sorry, I wrongly assumed the title inherited the new commit message.

**Comment by Jackwooh** [comment]
@tridge @IamPete1

**Pull request merged**
