### PR TITLE
VisualOdom: Support ODOMOTRY mavlink message

### PR DESCRIPTION
**Pull request by tridge**
This works with the ModalAI VOXL vision inertial odometry system
Example of velocities and positions with EK2 on GPS and EK3 on VIO. Copter was manually aligned pointing north on startup to make log comparison easy between earth and body frame data. Copter was "flown" hand-held (I did make the obligatory motor noises for realism)
image
image

### CODE REVIEW

**Comment by rmackay9** [comment]
Well, that didn't take long, great!

**Review by rmackay9 — APPROVED** [review]
LGTM, thanks!

**Comment by rmackay9** [comment]
@tridge I think we can remove the "needs testing" and "wip" labels right?

**Comment by roque-canales** [comment]
Hello I tryed voxl cam, and there is errors on speeds that send voxl to ardupilot.

voxl send earth frame pos and vels, I detailled the issue there in the discuss, with simple dataflash log showing the issue.

Please check it out:
https://discuss.ardupilot.org/t/voxlcam-on-copter-4-2-issue/87439/2

i have the voxlcam so i can make tests for you.

**Comment by ricardossilvestre** [comment]
Hello @tridge how are you doing? I am having a problem with the VOXL cam and I don't know if you can help me. I have a ROVER model that I use together with a VOXL-CAM, that is capable of visually estimating the odometry (local position values) of the circuit path, due to the circuit being underground and no GPS signal is available, the information is sent to the CUAV X7 Flight Controller where I can recover the data using the SD card slot.

I have a problem where, for some reason, while in the circuit with the QGroundControl controller the local position of the odometer is reseted in some specific places (as shown in the figure below), I believe due to the camera losing reference.

I was wondering if there was a way to correct this error so I could correctly estimate the position. If not possible would there be a way to export the *.ulg file to a *.csv for example and then manually removing the problematic points, and then re-exporting it to *.ulg so I could visualize the data in the http://logs.px4.io/ website?

Here’s two logs that I took that can help.

For this one the discontinuity apperars around 13:20 https://logs.px4.io/plot_app?log=2196a6ba-f03f-438c-bc69-28420727308a

And for this one the discontinuity appears around 11:40 https://logs.px4.io/plot_app?log=9a360a9b-ebb0-4a1a-82ac-d351c06b9c08

**Pull request merged**
