### PR TITLE
AP_HAL_ChibiOS: External flash optimizations (H750 etc.) backport to 4.4

### PR DESCRIPTION
**Pull request by mluessi**
This is a backport of the external flash optimizations from #23947 to version 4.4 .

There were some additional changes needed for ChibiOS, the linker files, and the hwdef Python script. 

The ChibiOS changes are in ArduPilot/ChibiOS#75

I have bench tested this with CubeOrange (internal flash target) and a RADIX 2 HD (H750, external flash).

EDIT: I have minimized the changes to try and achieve binary equivalence. The changes now produce binaries of the same size. -- Andy

### CODE REVIEW

**Comment by rmackay9** [comment]
@andyp1per will continue to try and get this PR to the point where the binary is unchanged for unaffected boards.

**Comment by peterbarker** [comment]
Two bootloaders fail to compile because we haven't backported the dependency fixes.  They compile fine stand-alone.

@andyp1per can explain the other discrepancies, I think.

```
Thread failure: ('DevEBoxH7v2', 'testtest', '/tmp/tmpzm_2infp/out-branch-DevEBoxH7v2', ['blimp', 'bootloader', 'copter', 'heli', 'plane', 'rover', 'sub'], [])
Thread failure: ('SPRacingH7', 'testtest', '/tmp/tmpzm_2infp/out-branch-SPRacingH7', ['blimp', 'bootloader', 'copter', 'heli', 'plane', 'rover', 'sub'], [])
Board,AP_Periph,blimp,bootloader,copter,heli,iofirmware,plane,rover,sub
AIRLink,,*,*,*,*,,*,*,*
ARKV6X,,*,*,*,*,,*,*,*
ARK_GPS,*,,,,,,,,
ARK_RTK_GPS,*,,,,,,,,
AeroFox-Airspeed,*,,,,,,,,
AeroFox-Airspeed-DLVR,*,,,,,,,,
AeroFox-PMU,*,,,,,,,,
AtomRCF405NAVI,,*,*,*,*,,*,*,*
BeastF7,,*,*,*,*,,*,*,*
BeastF7v2,,*,*,*,*,,*,*,*
BeastH7,,*,*,*,*,,*,*,*
BeastH7v2,,*,*,*,*,,*,*,*
BirdCANdy,*,,,,,,,,
BlitzF745AIO,,,*,*,,,,,
C-RTK2-HP,*,,,,,,,,
CUAV-Nora,,*,*,*,*,,*,*,*
CUAV-Nora-bdshot,,*,*,*,*,,*,*,*
CUAV-X7,,*,*,*,*,,*,*,*
CUAV-X7-bdshot,,*,*,*,*,,*,*,*
CUAV_GPS,*,,,,,,,,
CUAVv5,,*,*,*,*,,*,*,*
CUAVv5-bdshot,,*,*,*,*,,*,*,*
CUAVv5Nano,,*,*,*,*,,*,*,*
CUAVv5Nano-bdshot,,*,*,*,*,,*,*,*
CarbonixF405,*,,,,,,,,
CarbonixL496,*,,,,,,,,
CubeBlack,,*,*,*,*,,*,*,*
CubeBlack+,,*,*,*,*,,*,*,*
CubeBlack-periph,*,,,,,,,,
CubeGreen-solo,,,*,*,,,,,
CubeOrange,,*,*,*,*,,*,*,*
CubeOrange-ODID,,*,*,*,*,,*,*,*
CubeOrange-SimOnHardWare,,,,*,,,,,
CubeOrange-bdshot,,*,*,*,*,,*,*,*
CubeOrange-joey,,*,*,*,*,,*,*,*
CubeOrange-periph,*,,,,,,,,
CubeOrange-periph-heavy,*,,,,,,,,
CubeOrangePlus,,*,*,*,*,,*,*,*
CubeOrangePlus-SimOnHardWare,,,,*,,,,,
CubeOrangePlus-bdshot,,*,*,*,*,,*,*,*
CubePilot-CANMod,*,,,,,,,,
CubePurple,,*,*,*,*,,*,*,*
CubeSolo,,,*,*,,,,,
CubeYellow,,*,*,*,*,,*,*,*
CubeYellow-bdshot,,*,*,*,*,,*,*,*
DrotekP3Pro,,*,*,*,*,,*,*,*
Durandal,,*,*,*,*,,*,*,*
Durandal-bdshot,,*,*,*,*,,*,*,*
F35Lightning,,*,*,*,*,,*,*,*
F4BY,,*,*,*,*,,*,*,*
FlyingMoonF407,,*,*,*,*,,*,*,*
FlyingMoonF427,,*,*,*,*,,*,*,*
FlywooF405S-AIO,,*,*,*,*,,*,*,*
FlywooF745,,*,*,*,*,,*,*,*
FlywooF745Nano,,*,*,*,*,,*,*,*
FoxeerH743v1,,0,*,0,0,,0,0,0
FreeflyRTK,*,,,,,,,,
G4-ESC,*,,,,,,,,
H757I_EVAL,,,*,,,,,,
H757I_EVAL_intf,,,*,,,,,,
HEEWING-F405,,,*,,,,*,,
HEEWING-F405v2,,,*,,,,*,,
HerePro,*,,,,,,,,
Hitec-Airspeed,*,,,,,,,,
HitecMosaic,*,,,,,,,,
HolybroG4_Compass,*,,,,,,,,
HolybroG4_GPS,*,,,,,,,,
HolybroGPS,*,,,,,,,,
JFB100,,*,*,*,*,,*,*,*
JHEMCU-GSF405A,,*,*,*,*,,*,*,*
JHEMCU-GSF405A-RX2,,*,*,*,*,,*,*,*
KakuteF4,,*,*,*,*,,*,*,*
KakuteF4Mini,,*,*,*,*,,*,*,*
KakuteF7,,*,*,*,*,,*,*,*
KakuteF7-bdshot,,*,*,*,*,,*,*,*
KakuteF7Mini,,*,*,*,*,,*,*,*
KakuteH7,,*,*,*,*,,*,*,*
KakuteH7-Wing,,*,*,*,*,,*,*,*
KakuteH7-bdshot,,*,*,*,*,,*,*,*
KakuteH7Mini,,*,*,*,*,,*,*,*
KakuteH7Mini-Nand,,*,*,*,*,,*,*,*
KakuteH7v2,,0,*,0,0,,0,0,0
MambaF405-2022,,*,*,*,*,,*,*,*
MambaF405US-I2C,,*,*,*,*,,*,*,*
MambaF405v2,,*,*,*,*,,*,*,*
MambaH743v4,,0,*,0,0,,0,0,0
MatekF405,,*,*,*,*,,*,*,*
MatekF405-CAN,,*,*,*,*,,*,*,*
MatekF405-STD,,*,*,*,*,,*,*,*
MatekF405-TE,,*,*,*,*,,*,*,*
MatekF405-TE-bdshot,,*,*,*,*,,*,*,*
MatekF405-Wing,,*,*,*,*,,*,*,*
MatekF405-Wing-bdshot,,*,*,*,*,,*,*,*
MatekF405-bdshot,,*,*,*,*,,*,*,*
MatekF765-SE,,*,*,*,*,,*,*,*
MatekF765-Wing,,*,*,*,*,,*,*,*
MatekF765-Wing-bdshot,,*,*,*,*,,*,*,*
MatekH743,,*,*,*,*,,*,*,*
MatekH743-bdshot,,*,*,*,*,,*,*,*
MatekH743-periph,*,,,,,,,,
MatekL431-Airspeed,*,,,,,,,,
MatekL431-BattMon,*,,,,,,,,
MatekL431-DShot,*,,,,,,,,
MatekL431-EFI,*,,,,,,,,
MatekL431-GPS,*,,,,,,,,
MatekL431-HWTelem,*,,,,,,,,
MatekL431-Periph,*,,,,,,,,
MatekL431-Proximity,*,,,,,,,,
MatekL431-Rangefinder,*,,,,,,,,
MatekL431-bdshot,*,,,,,,,,
MazzyStarDrone,,*,*,*,*,,*,*,*
Nucleo-G491,*,,,,,,,,
Nucleo-L476,*,,,,,,,,
Nucleo-L496,*,,,,,,,,
NucleoH743,,,*,,,,,,
NucleoH755,,,*,,,,,,
OMNIBUSF7V2,,*,*,*,*,,*,*,*
OmnibusNanoV6,,*,*,*,*,,*,*,*
OmnibusNanoV6-bdshot,,*,*,*,*,,*,*,*
PH4-mini,,*,*,*,*,,*,*,*
PH4-mini-bdshot,,*,*,*,*,,*,*,*
Pix32v5,,*,*,*,*,,*,*,*
PixC4-Jetson,,*,*,*,*,,*,*,*
PixPilot-V3,,*,*,*,*,,*,*,*
PixPilot-V6,,*,*,*,*,,*,*,*
PixSurveyA1,,*,*,*,*,,*,*,*
PixSurveyA2,,*,*,*,*,,*,*,*
Pixhawk1,,*,*,*,*,,*,*,*
Pixhawk1-1M,,*,*,*,*,,*,*,*
Pixhawk1-1M-bdshot,,*,,*,*,,*,*,*
Pixhawk1-bdshot,,*,,*,*,,*,*,*
Pixhawk4,,*,*,*,*,,*,*,*
Pixhawk4-bdshot,,*,*,*,*,,*,*,*
Pixhawk5X,,*,*,*,*,,*,*,*
Pixhawk6C,,*,*,*,*,,*,*,*
Pixhawk6C-bdshot,,*,*,*,*,,*,*,*
Pixhawk6X,,*,*,*,*,,*,*,*
Pixhawk6X-ODID,,*,*,*,*,,*,*,*
Pixhawk6X-bdshot,,*,*,*,*,,*,*,*
Pixracer,,*,*,*,*,,*,*,*
Pixracer-bdshot,,*,*,*,*,,*,*,*
Pixracer-periph,*,,,,,,,,
QioTekZealotF427,,*,*,*,*,,*,*,*
QioTekZealotH743,,*,*,*,*,,*,*,*
QioTekZealotH743-bdshot,,*,*,*,*,,*,*,*
R9Pilot,,*,*,*,*,,*,*,*
ReaperF745,,*,*,*,*,,*,*,*
SITL_arm_linux_gnueabihf,,0,,0,0,,0,0,0
SITL_x86_64_linux_gnu,,0,,0,0,,0,0,0
SIYI_N7,,*,*,*,*,,*,*,*
Sierra-F405,*,,,,,,,,
Sierra-F412,*,,,,,,,,
Sierra-F9P,*,,,,,,,,
Sierra-L431,*,,,,,,,,
SkystarsH7HD,,*,*,*,*,,*,*,*
SkystarsH7HD-bdshot,,0,*,0,0,,0,0,0
SpeedyBeeF405WING,,*,*,*,*,,*,*,*
SuccexF4,,*,*,*,*,,*,*,*
Swan-K1,,,*,,,,*,,
TBS-Colibri-F7,,*,*,*,*,,*,*,*
VRBrain-v51,,*,*,*,*,,*,*,*
VRBrain-v52,,*,*,*,*,,*,*,*
VRBrain-v54,,*,*,*,*,,*,*,*
VRCore-v10,,*,*,*,*,,*,*,*
VRUBrain-v51,,*,*,*,*,,*,*,*
ZubaxGNSS,*,,,,,,,,
airbotf4,,*,*,*,*,,*,*,*
bbbmini,,*,,*,*,,*,*,*
blue,,*,,*,*,,*,*,*
crazyflie2,,*,*,*,*,,*,*,*
edge,,*,,*,*,,*,*,*
erlebrain2,,*,,*,*,,*,*,*
f103-ADSB,*,,,,,,,,
f103-Airspeed,*,,,,,,,,
f103-GPS,*,,,,,,,,
f103-HWESC,*,,,,,,,,
f103-QiotekPeriph,*,,,,,,,,
f103-RangeFinder,*,,,,,,,,
f103-Trigger,*,,,,,,,,
f303-GPS,*,,,,,,,,
f303-HWESC,*,,,,,,,,
f303-M10025,*,,,,,,,,
f303-M10070,*,,,,,,,,
f303-MatekGPS,*,,,,,,,,
f303-PWM,*,,,,,,,,
f303-TempSensor,*,,,,,,,,
f303-Universal,*,,,,,,,,
f405-MatekAirspeed,*,,,,,,,,
f405-MatekGPS,*,,,,,,,,
fmuv2,,*,,*,*,,*,*,*
fmuv3,,*,*,*,*,,*,*,*
fmuv3-bdshot,,*,,*,*,,*,*,*
fmuv5,,*,*,*,*,,*,*,*
iomcu,,,,,,*,,,
iomcu_f103_8MHz,,,,,,*,,,
luminousbee4,,*,,*,*,,*,*,*
luminousbee5,,*,*,*,*,,*,*,*
mRo-M10095,*,,,,,,,,
mRoCANPWM-M10126,*,,,,,,,,
mRoControlZeroClassic,,*,*,*,*,,*,*,*
mRoControlZeroF7,,*,*,*,*,,*,*,*
mRoControlZeroH7,,*,*,*,*,,*,*,*
mRoControlZeroH7-bdshot,,*,*,*,*,,*,*,*
mRoControlZeroOEMH7,,*,*,*,*,,*,*,*
mRoNexus,,*,*,*,*,,*,*,*
mRoPixracerPro,,*,*,*,*,,*,*,*
mRoPixracerPro-bdshot,,*,*,*,*,,*,*,*
mRoX21,,*,*,*,*,,*,*,*
mRoX21-777,,*,*,*,*,,*,*,*
mindpx-v2,,*,*,*,*,,*,*,*
mini-pix,,*,*,*,*,,*,*,*
modalai_fc-v1,,*,*,*,*,,*,*,*
navigator,,*,,*,*,,*,*,*
navio,,*,,*,*,,*,*,*
navio2,,*,,*,*,,*,*,*
obal,,*,,*,*,,*,*,*
omnibusf4,,*,*,*,*,,*,*,*
omnibusf4pro,,*,*,*,*,,*,*,*
omnibusf4pro-bdshot,,*,*,*,*,,*,*,*
omnibusf4pro-one,,*,*,*,*,,*,*,*
omnibusf4v6,,*,*,*,*,,*,*,*
pxf,,*,,*,*,,*,*,*
pxfmini,,*,,*,*,,*,*,*
rFCU,,,*,,,,,,
rGNSS,*,,,,,,,,
revo-mini,,*,*,*,*,,*,*,*
revo-mini-bdshot,,*,*,*,*,,*,*,*
revo-mini-i2c,,*,*,*,*,,*,*,*
revo-mini-i2c-bdshot,,*,*,*,*,,*,*,*
revo-mini-sd,,,*,,,,,,
skyviper-f412-rev1,,,,*,,,,,
skyviper-journey,,,,*,,,,,
skyviper-v2450,,,,*,,,,,
sparky2,,*,*,*,*,,*,*,*
speedybeef4,,*,*,*,*,,*,*,*
speedybeef4v3,,*,*,*,*,,*,*,*
thepeach-k1,,*,*,*,*,,*,*,*
thepeach-r1,,*,*,*,*,,*,*,*


real    140m30.897s
user    3717m39.752s
sys     596m52.253s
pbarker@threads:~/rc/ardupilot$
```

**Review by peterbarker — CHANGES_REQUESTED** [review]
Some boards are changing in here which shouldn't - notably KakuteH7v2

Need to explain that one...

**Comment by tridge** [comment]
@andyp1per needs to pass CI :-)

**Comment by andyp1per** [comment]
@tridge github was having problems yesterday - that was the reason for all the CI failures :)

**Comment by andyp1per** [comment]
The KakuteH7v2 change was due to the PLL changes for 480Mhz clocks - I don't believe these changes are necessary so I have taken them out. SPRacingH7 still builds fine.

**Review by peterbarker — APPROVED** [review]
Results show that backport builds are fine.  Except for the ones suffering from dependency bug.

**Review by tridge — APPROVED** [review]

**Pull request merged**
