### PR TITLE
Stop allowing a vector2 to be called as a function

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by rmackay9** [comment]
LGTM although I'm not the plane lead..

**Comment by tridge** [comment]
why the change? My guess is calling it as a fn would produce smaller code

**Comment by peterbarker** [comment]
On Thu, 4 Jun 2020, Andrew Tridgell wrote:

> why the change? My guess is calling it as a fn would produce smaller code

Overriding the () operator to act as assignment is a non-obvious change to 
the way the language is usually used.  There's a perfect good operator we 
can use for that operation....  I know it initially confused me when 
learning the codebase.

The code size cost isn't dreadful.

master
   bin/arduplane  1388528  1472  195352  1585352
pr/no-vector2-as-function
   bin/arduplane  1388528  1472  195352  1585352
pr/no-vector3-as-function
   bin/arduplane  1388532  1472  195356  1585360

**Comment by davidbuzz** [comment]
i don't mind which we use, but we should be consistent.

**Pull request merged**
