### PR TITLE
bootloaders: update CubeOrange bootloader to include flash-from-sd su…

### PR DESCRIPTION
**Pull request by peterbarker**
…pport

this is just a rebuild of this firmware; the changes have been in the hwdef for a very long time

### CODE REVIEW

**Comment by rmackay9** [comment]
@tridge @bugobliterator you're OK with this?

**Review by bugobliterator — APPROVED** [review]

**Review by bugobliterator — CHANGES_REQUESTED** [review]
Can we add it for CubeOrangePlus as well.

**Review by tridge — APPROVED** [review]

**Comment by peterbarker** [comment]
CubeOrangePlus done here: https://github.com/ArduPilot/ardupilot/pull/25185

**Comment by peterbarker** [comment]
... CubeRedPrimary is absolutely non-trivial; abin generation is broken when external flash is involved, and the modifications to the bootloader also don't support it.  We'd need to add a header field to the .abin to indicate what sort of image is contained in it, and interpret that in the bootloader so we know where to put it.

@bugobliterator did you really want to hold this PR up for that work to be done? :-)

**Comment by peterbarker** [comment]
... preliminary work for support is here: https://github.com/peterbarker/ardupilot/pull/new/pr/cuberedprimary-flash-from-sd

**Review by bugobliterator — APPROVED** [review]

**Comment by bugobliterator** [comment]
> @bugobliterator did you really want to hold this PR up for that work to be done? :-)

Not really, approved

**Pull request merged**
