### PR TITLE
Fixed null ptr deref of terrain on rover with OSD support

### PR DESCRIPTION
**Pull request by tridge**
Fixes this issue:
https://discuss.ardupilot.org/t/h743-wing-rover-not-saving-changes-after-power-down/69442/6

### CODE REVIEW

**Review by andyp1per — APPROVED** [review]

**Comment by rmackay9** [comment]
Great, thanks for finding this.  Let's try and get it merged before tomorrow when I plan to release Rover-4.1.0-rc1.

**Review by rmackay9 — APPROVED** [review]
This seems OK to me.

**Comment by amilcarlucas** [comment]
Can we call it 4.1.0-alpha1 instead?

**Comment by rmackay9** [comment]
@amilcarlucas, yes, that's probably a good idea. :-)

**Pull request merged**
