### PR TITLE
ArduPlane: Fixes spiralling loiter when no fence return point is present and exclusion fence is only fence uploaded

### PR DESCRIPTION
**Pull request by joshanne**
This can be validated with the autotest that was added, or manually by:
* Add exclusion fence
* Set `FENCE_ACTION` to `GUIDED(6)`
* Takeoff with plane
* Fly into exclusion fence
* observe vehicle using home as fence return point instead of "spiral loitering".

### CODE REVIEW

**Comment by joshanne** [comment]
@Hwurzburg attn. Addresses your spiraling loiter that you demonstrate in your video.

**Review by khancyr — COMMENTED** [review]
That seems good on code and test side. But on the use case, I am not sure that is a good behavior. Previously, we were :
"I breach the fence and now I am lost, please HELP !"
Now, we return to home that can bring quite a long way with other potential problems.

**Comment by joshanne** [comment]
> 
> 
> That seems good on code and test side. But on the use case, I am not sure that is a good behavior. Previously, we were :
> "I breach the fence and now I am lost, please HELP !"
> Now, we return to home that can bring quite a long way with other potential problems.

@Hwurzburg begs to differ on the expected behaviour. If the answer is to simply alert the user more formally, then I can make that change too.

**Comment by joshanne** [comment]
More discussion refer here: https://github.com/ArduPilot/ardupilot_wiki/pull/3494

**Comment by khancyr** [comment]
I am not much in Plane behaviour, so I will a plane maintainer take the decision on what to do on this case !

**Comment by Hwurzburg** [comment]
The expected behaviour for a breach with a guided return point is to return to that point...if none is entered, then the safest behaviour is to return home, rather than loitering since the user may have no ground station to inform him of the breach....
this is similar to Copter fence actions in that if the specified action cannot be performed (ie SmartRTL but its disabled due to point overflow, etc. is to fall back to another return mechanism or land)...in addition, current behvior can also send the vehicle back to a point out of the inclusion zone if the return point is not specified and a guided return action is enable....

**Review by Hwurzburg — APPROVED** [review]
LGTM...played with SITL fixed the bug I was concerned with...thanks

**Review by tridge — APPROVED** [review]

**Comment by peterbarker** [comment]
Legit CI failure, I think.

**Comment by joshanne** [comment]
> Legit CI failure, I think.

I've just pushed the fix - it just clicked to me that the state of the vehicle may not be default after each test. There was an exclusion zone being loaded just north of home location, and when the test is run individually it passes. When run as part of the suite, it flies somewhere _**other**_ than the exclusion zone.

I now circumvent the requirement for the exclusion zone by using a tin-can (the only real requirement for this test is that the fence is not a Polygon Inclusion fence). Now, no matter what direction we fly, we will hit the fence.

**Comment by joshanne** [comment]
@peterbarker Autotests are passing after the change was made, I'm not sure what's going on with the `semaphoreci` builds 😕

**Comment by peterbarker** [comment]
Merged, thanks!

**Pull request merged**
