### PR TITLE
Inbuilt QEP and motor driver modules implementation in BBBlue for Ardurover 24th oct, 2017

### PR DESCRIPTION
**Pull request by rahulsharma11**
Inbuilt QEP and motor driver modules implementation in BBBlue for Ardurover.

### CODE REVIEW

**Comment by magicrub** [comment]
This looks like an in-progress branch with a long list of things that can not be accepted into the master repo. Are you still working on this?

**Comment by rahulsharma11** [comment]
Hi magicrub,
I am not currently working on this.
The changes are there to use BBBlue inbuilt QEP and DC motor driver modules for Ardurover instead of  external ESCs. Also inbuilt QEP modules was not there till now, so i did that to reduce the hardware. It is also working "https://www.youtube.com/watch?v=bZ1S2o1ZjoU". 

The only thing needed is to provide an option in GUI whether to choose inbuilt BBBlue driver or external ESCs for Navigation in Ardurover. That i don't know.

**Comment by rahulsharma11** [comment]
Hi, is that check issue because of i did the git checkout for APMrover2-beta not Ardupilot-beta?

**Comment by magicrub** [comment]
Pull requests must be a branch on top of master, not on any old tags.

**Comment by rahulsharma11** [comment]
Hi,
I got that and removed all unnecessary files and headers. Also builded and tested again, Will commit the final change soon.

**Comment by rahulsharma11** [comment]
And didn't get what you said "needs to be done on top of master". As i have forked the ardupilot source code from master branch and did the changes and then committed. Is there any other way to do that?

**Comment by magicrub** [comment]
>..i have forked the ardupilot source code from master branch..

Yup, that's fine. My mistake. I thought you meant something else when you said "i did the git checkout for APMrover2-beta", but that was just building, not git checkout.

**Comment by magicrub** [comment]
Please take a look at this wiki entry: http://ardupilot.org/dev/docs/contributing.html

**Comment by rahulsharma11** [comment]
Hi magicrub,
Apologize for the recent new commit. 
Will add the comments for each new file added with final commit.

**Comment by rahulsharma11** [comment]
Hi,
Please delete this PR as i will create a new final PR with all my changes and descriptions.

**Pull request closed without merging**
