### PR TITLE
hwdef: change MatekH743 to -Os

### PR DESCRIPTION
**Pull request by tridge**
leave space for more features. was down to 6k flash free

### CODE REVIEW

**Comment by hendjoshsr71** [comment]
This will be needed for my adding AP_Airspeed to be added to copter as it pushes this board over the edge with only 1.5KB free for _bdshot last time I built all the boards.

**Comment by andyp1per** [comment]
My plan is to run a before/after test on a flying copter with --enable-stats on and see how the thread loads vary. I don't expect any surprises - but who knows

**Comment by andyp1per** [comment]
On the BeastH7 this is before:
```
ThreadsV2
ISR           PRI=255 sp=0x30000000 STACK=1280/1536 LOAD= 3.4%
ArduCopter    PRI=182 sp=0x30000600 STACK=4560/7168 LOAD=21.1%
idle          PRI=  1 sp=0x30015940 STACK= 144/ 352 LOAD=47.1%
UART_RX       PRI= 60 sp=0x3003E900 STACK= 768/1104 LOAD= 0.5%
OTG1          PRI= 60 sp=0x3003DA08 STACK= 240/ 656 LOAD= 0.3%
monitor       PRI=183 sp=0x30012388 STACK= 480/ 848 LOAD= 0.2%
timer         PRI=181 sp=0x30013608 STACK=1456/1872 LOAD= 0.7%
rcout         PRI=181 sp=0x30012CC8 STACK= 432/ 848 LOAD= 7.3%
rcin          PRI=177 sp=0x30012728 STACK= 432/1360 LOAD= 2.9%*
io            PRI= 58 sp=0x300119E8 STACK=1496/2384 LOAD= 0.6%*
storage       PRI= 59 sp=0x30013068 STACK= 856/1360 LOAD= 0.2%*
UART2         PRI= 60 sp=0x3003CE40 STACK= 248/ 656 LOAD= 0.1%
UART3         PRI= 60 sp=0x3003C348 STACK= 384/ 656 LOAD= 0.1%
UART4         PRI= 60 sp=0x3003B850 STACK= 384/ 656 LOAD= 0.2%
UART7         PRI= 60 sp=0x3003AD58 STACK= 296/ 656 LOAD= 0.1%
I2C0          PRI=176 sp=0x30039A78 STACK= 824/1360 LOAD= 0.1%
OSD           PRI= 59 sp=0x300357F8 STACK= 632/1360 LOAD= 0.3%*
UART1         PRI= 60 sp=0x30036858 STACK= 248/ 656 LOAD= 0.1%
log_io        PRI= 59 sp=0x30036B50 STACK=1056/1656 LOAD= 0.6%
SPI1          PRI=181 sp=0x30026230 STACK= 560/1360 LOAD=11.6%
apm_fft       PRI= 58 sp=0x300253A0 STACK= 752/1360 LOAD= 1.4%
FTP           PRI= 58 sp=0x3001FFA8 STACK=1456/2896 LOAD= 0.3%
```
and after:
```
ISR           PRI=255 sp=0x30000000 STACK=1272/1536 LOAD= 3.3%
ArduCopter    PRI=182 sp=0x30000600 STACK=4576/7168 LOAD=22.1%
idle          PRI=  1 sp=0x30015940 STACK= 144/ 352 LOAD=44.0%
UART_RX       PRI= 60 sp=0x3003E900 STACK= 760/1104 LOAD= 0.4%
OTG1          PRI= 60 sp=0x3003DA08 STACK= 256/ 656 LOAD= 0.2%
monitor       PRI=183 sp=0x30012388 STACK= 480/ 848 LOAD= 0.2%
timer         PRI=181 sp=0x30013608 STACK=1488/1872 LOAD= 0.7%
rcout         PRI=181 sp=0x30012CC8 STACK= 432/ 848 LOAD= 7.8%
rcin          PRI=177 sp=0x30012728 STACK= 464/1360 LOAD= 3.5%*
io            PRI= 58 sp=0x300119E8 STACK=1488/2384 LOAD= 0.7%*
storage       PRI= 59 sp=0x30013068 STACK= 880/1360 LOAD= 0.3%*
UART2         PRI= 60 sp=0x3003CE40 STACK= 296/ 656 LOAD= 0.1%
UART3         PRI= 60 sp=0x3003C348 STACK= 368/ 656 LOAD= 0.2%
UART4         PRI= 60 sp=0x3003B850 STACK= 368/ 656 LOAD= 0.2%
UART7         PRI= 60 sp=0x3003AD58 STACK= 296/ 656 LOAD= 0.2%
I2C0          PRI=176 sp=0x30039A78 STACK= 856/1360 LOAD= 0.1%
OSD           PRI= 59 sp=0x300357F8 STACK= 688/1360 LOAD= 0.3%*
UART1         PRI= 60 sp=0x30036858 STACK= 240/ 656 LOAD= 0.2%
log_io        PRI= 59 sp=0x30036B50 STACK=1048/1656 LOAD= 0.7%
SPI1          PRI=181 sp=0x30026230 STACK= 584/1360 LOAD=12.2%
apm_fft       PRI= 58 sp=0x300253A0 STACK= 744/1360 LOAD= 1.5%
FTP           PRI= 58 sp=0x3001FFA8 STACK=1432/2896 LOAD= 0.3%
```
So we've lost about 3% CPU across the board, but nothing appears particularly egregious. I'll probably do a follow-up PR just to optimize a couple of things I know are CPU intensive, but this looks good to go on the face of it.

**Review by andyp1per — APPROVED** [review]

**Comment by chobitsfan** [comment]
> leave space for more features. was down to 6k flash free

Hi @tridge I think it may be something strange. According to http://www.mateksys.com/?portfolio=h743-slim , it use STM32H743VI which has 2MB flash (just like CubeOrange)

**Pull request merged**
