### PR TITLE
EKF3: always attempt to setup all cores

### PR DESCRIPTION
**Pull request by rmackay9**
This resolves issue https://github.com/ArduPilot/ardupilot/issues/5822 involving a segmentation fault because some EKF3 cores had null _ahrs pointers.

### CODE REVIEW

**Comment by priseborough** [comment]
Makes sense to me.

In theory this could also happen to EKF2, but in practice, because EKF2 doesn't wait for the GPS delay to be confirmed before initialising the data buffers, it is unlikely.

**Comment by rmackay9** [comment]
Ok thanks.  I've added the same code to EKF2 now as well.  Doesn't hurt so might as well keep them consistent.

**Comment by tridge** [comment]
should we have a bitmask of what cores have been successful setup? I'm only concerned that setting up a core multiple times could be bad. What if first core fails setup and 2nd succeeds? Doesn't 2nd get setup again later?

**Comment by rmackay9** [comment]
I've zapped the EKF2 fix.  So once it passes travis/semaphore I'll merge to master.

**Pull request merged**
