### PR TITLE
GCS_MAVLink: fix VISP logging for ATT_POS_MOCAP mocap messages

### PR DESCRIPTION
**Pull request by vincekurtz**
Resolves issue #8132.

### CODE REVIEW

**Comment by rmackay9** [comment]
My guess is that it would be better to move the VISP message into a shared function and use that to write instead of copying the code.  @peterbarker what do you think?

**Comment by OXINARF** [comment]
I totally agree with @rmackay9, especially because this is using the Log_Write functionality and it would be easy to miss changing in one place and forgetting about the other (CI should catch most cases of this, but if name is changed it won't).

**Comment by vincekurtz** [comment]
Is this updated commit what you were thinking of as far as a shared function goes?

**Comment by rmackay9** [comment]
Great, thanks! merged!

**Pull request merged**
