### PR TITLE
Tools: param_parse.py: sort SIM_ parameters into the output files

### PR DESCRIPTION
**Pull request by peterbarker**
primarily to make the Wiki look nicer

### CODE REVIEW

**Comment by Hwurzburg** [comment]
tested with added RC_FAIL....looks good....merge it!

**Review by Hwurzburg — APPROVED** [review]

**Comment by tridge** [comment]
@peterbarker alternative https://github.com/ArduPilot/ardupilot/pull/22635
@Hwurzburg had told me he shouldn't hold his breath for you to do it, I didn't realise you'd done one
please close mine if you prefer this one

**Comment by peterbarker** [comment]
> @peterbarker alternative #22635 @Hwurzburg had told me he shouldn't hold his breath for you to do it, I didn't realise you'd done one please close mine if you prefer this one

Let's merge this one and then discuss yours.

I'd like to understand why we're not sorting parameters generally (as yours does).

Note that this PR merges parameters from sub-groups (e.g. `SIM_GRPE`) - I can't see how yours can be doing that....

**Comment by tridge** [comment]
> I'd like to understand why we're not sorting parameters generally (as yours does).

mine only sorts SIM parameters

**Pull request merged**
