### PR TITLE
vector3: return w1 not zero vector

### PR DESCRIPTION
**Pull request by xianglunkai**
fix liitle bugs when w1=w2

### CODE REVIEW

**Review by IamPete1 — APPROVED** [review]

**Comment by IamPete1** [comment]
Looks like you will also have to update the test. 

https://github.com/ArduPilot/ardupilot/blob/8fa6432e3a49ad3b080ffeca8c6b44257e0ad75f/libraries/AP_Math/tests/test_3d_lines.cpp#L29

**Comment by xianglunkai** [comment]
Thank you! test have been fixed!

**Review by rishabsingh3003 — APPROVED** [review]
Ah, that was a mistake I made. Thanks for fixing it!
Did you mean to include th harmonic notch change as well? Not sure if it belongs to this PR

**Comment by xianglunkai** [comment]
@rishabsingh3003 Txs,only merge vector3 pr.

**Comment by amilcarlucas** [comment]
@xianglunkai we can not select what parts to merge. You need to remove the harmonic notch change yourself

**Comment by xianglunkai** [comment]
@amilcarlucas Txs

**Review by peterbarker — APPROVED** [review]

**Pull request merged**
