### PR TITLE
Plane: Disarm after parachute release

### PR DESCRIPTION
**Pull request by python36**
Based on discussion of PR #25562.

Disarm after parachute release to avoid parachute tangling.

### CODE REVIEW

**Comment by python36** [comment]
@IamPete1 @khancyr please review this PR. If there are concerns, I can replace this with parametric functionality (CHUTE_THR_DISARM).

**Comment by timtuxworth** [comment]
Just a thought - would it be better to do an emergency stop on the motors rather than a disarm?

**Comment by python36** [comment]
@timtuxworth It doesn't matter to me how to do it. I want to avoid getting the parachute tangled. Now I’m solving it with custom firmware, which is not very good.

**Comment by python36** [comment]
Hi. Maybe make a new bit in CHUTE_OPTIONS?
1 - disarme after releasing the parachute.

Please don't ignore me :) this is very important for me

**Comment by tridge** [comment]
@python36 I think we could consider moving the disarm into the AP_Parachute library so it is common code instead of being in each vehicle, and maybe add a CHUTE_OPTIONS bit to optionally disable the disarm?

**Comment by rmackay9** [comment]
I'd even be happy without the option.. I think the vehicle should always disarm, the only question may be whether it should keep logging or not.. but I think we have an option for that already.

**Comment by python36** [comment]
@tridge @rmackay9 thanks for the reply. I will create a new PR and then close this one. thank you

**Comment by python36** [comment]
Create new PR #26129 taking into account previous wishes.

**Pull request closed without merging**
