### PR TITLE
Copter: Tradheli - fix issue with position moving while on ground

### PR DESCRIPTION
**Pull request by bnsgeyer**
This PR will fix an issue users may experience while spooling down.  Currently the code does not initialize the Nav controllers while the aircraft is spooling down spooling down or sitting on the ground with rotors static (armed or disarmed).  This can cause the aircraft to roll over because as the rotor is spooling down it still has sufficient control power to apply inputs from the Nav controller.  this is only being pushed to Copter-3.6 because the spool logic PR for tradheli is scheduled to go into 3.7 which remedies this situation.  It is a simple change.  Here is a plot of position controller velocity command and actual velocity.   a longitudinal velocity command from the transmitter was made to show when the controller was still allowed to make inputs the aircraft.  the first lift off and touchdown demonstrates an in air disarming.  Note that the controller followed the actual.  this means that in the event of an actual in flight disarming, the pilot will have to revert to another mode to control the aircraft, which is desirable in any case as the pilot as no control in the vertical axis.  the second takeoff and landing shows the effect of disabling motors interlock while in flight.  this shows that the nav controller command was not zeroed until the land complete flag was true which follows the logic in the code.
loiter_fix

@ChristopherOlson  if you have a chance to test this, it is always  appreciated.  I had done my testing in the SITL.  I feel it is low threat and would be fine if you didn't but always good to have someone take a second look.

### CODE REVIEW

**Comment by ChristopherOlson** [comment]
Ah, great Bill. I will test this right away.

**Comment by lvale** [comment]
Thanks @bnsgeyer

**Comment by rmackay9** [comment]
Merged, thanks!

**Comment by R-Lefebvre** [comment]
Hi Bill, I just tried this fix back-ported to AH3.5.  It seems to have the desired effect that the leash head isn't moving around. But seems to have the undesired side-effect that the copter does not stabilize at all.  Seems there is some Rate activity, but no Stabilize activity. (ie: servos move to resist angular movement, but not to self-right).

I assume it's the same for 3.6?

**Pull request merged**
