### PR TITLE
GCS_MAVLink: accept and send rc_channel_override

### PR DESCRIPTION
**Pull request by magicrub**
The general purpose of this is to allow almost any arbitrary hardware to act as a RC RX to MAVLink_override converter. Helpful for generic transmitters to work on SITL and over digital links without a GCS.

Add in some almost-a-hack-but-not-quite code that allows sending and receiving rc_override msgs. In the current state it is a non-functional change. To enable, you change the define, TX and RX are separately enabled. Using the define gives an "air gap" in safety instead of a param.

### CODE REVIEW

**Comment by WickedShell** [comment]
I feel like this has a bit of a misunderstanding how RC input works in SITL. You may use the `rc` command in MAVProxy, but SITL actually has a extra port that MAVProxy special cases (or is supposed to anyways). You can see the handling here: https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_HAL_SITL/SITL_State.cpp#L243

Anyways using overrides here will execute a different control path, and cause you to experience different behavior on the simulated vehicle then you would get using the actual RC input path, which makes this a somewhat poor way of actually try and connect your real RC input.

**Comment by magicrub** [comment]
So make this other device March the gcs sysid? No.

Again, this is still useful in SITL and for real digital links where you have a "short range" RC TX that can talk over a very long digital data link. Single link, aircraft doesn't need RC input.

I'm open to suggestions on how to make it less of a hack. Where would a Param like this live?

**Comment by peterbarker** [comment]
@tridge did something like this for SkyViper, so he could use the SkyViper controller on SITL.  Those patches may be available in the SkyViper repo and be worth looking at.

**Comment by OXINARF** [comment]
@magicrub 

> So make this other device March the gcs sysid? No.

Because... ?

> Again, this is still useful in SITL and for real digital links where you have a "short range" RC TX that can talk over a very long digital data link. Single link, aircraft doesn't need RC input.

Again, that can be easily replaced by a simple example, there is no need for a full ArduPilot firmware or to put this in the regular code.

**Comment by magicrub** [comment]
@OXINARF see @peterbarker 's example of why it's a good idea to have something like this

**Comment by OXINARF** [comment]
@magicrub ? @peterbarker's example is the same as yours... In what way would a example not work for it?

**Comment by WickedShell** [comment]
I'd strongly rather see this as an example rather then living in the main libraries that are used for everything, and from a usage perspective it shouldn't add any complication for a user since it would be a custom build anyways.

**Comment by magicrub** [comment]
Sounds like you guys don't want anything remotely useful like this. I'll just keep it in my bag of tricks for my self, master won't get it.

**Comment by OXINARF** [comment]
@magicrub Nobody told you that... We just asked to make it an example instead of putting in main code.

**Pull request closed without merging**
