### PR TITLE
AP_Scheduler: Refactoring

### PR DESCRIPTION
**Pull request by dgrat**
1) Refactoring
2) Macro removal with up-2-date version

Do these commits go in or not (yes/no)? 
The testsuite fails (but shouldn't) if I manually add a timer check within the scheduler loop (commented out). I do not like that there is a setting for the scheduler frequency, but the actual call rate can be entirely different. I currently don't really know why it fails if you enforce the defined frequency, but my first guess is that the scheduler frequency setting does not match the embedding loop frequency in the vehicles.

### CODE REVIEW

**Comment by tridge** [comment]
I don't really like this, sorry, I think it is excessive use of templates. I don't think we actually have any type safety issues with the current code?

**Comment by tridge** [comment]
btw, zero-initialising all the class variables is a bad idea. It just makes for larger flash size without changing anything

**Comment by dgrat** [comment]
@tridge Thanks for checking, 
do you have an idea why the commented section would fail the test at travis?

+/*
+    // the scheduler can run faster than the given frequency would allow 
+    if(AP_HAL::micros() - _last_run_us < _loop_period_us) {
+        return;
+     }

**Comment by peterbarker** [comment]
On Mon, 12 Feb 2018, Daniel Frenzel wrote:

> 
> @tridge Thanks for checking,
> do you have an idea why the commented section would fail the test at travis?

The block you've pasted is missing a closing */ ?

> 
> +/*
>
>  *  // the scheduler can run faster than the given frequency would allow
>  *  if(AP_HAL::micros() - _last_run_us < _loop_period_us) {
>  * 
>
>    return;
>  * 
> 
> }
>

**Comment by dgrat** [comment]
@peterbarker 
No this is not what I meant. I added this block for testing, because the scheduler behaved a little unintuitive if I set e.g. the frequency to 50 Hz but call the tick()/run() every 10 ms. I added this check to limit the execution of the run() function (after moving the useless tick() function into run()). However, it seems to break the test (so I commented it out), and I think the reason is in the inertial class.

**Comment by dgrat** [comment]
Ask me if something is not clear?

**Comment by hiro2233** [comment]
hi @dgrat 
about the comment, /* */ is used on C standard and // is for C++ standard indeed. This is a parsing bug on GCC.

**Comment by dgrat** [comment]
I guess, no one understood what I wrote :/

**Comment by hiro2233** [comment]
@dgrat ok, if you are refering about the code inside the comment, that is other thing, i guess you need to be more specific to understand what do you need to do, you are mixing two standard on your commented code.

About the code indide the C commented standard.

void != int

thats break the build process depending on the flag warn enabled.

**Comment by magicrub** [comment]
@dgrat When thousands of people are looking at the source, readability is very important

**Comment by dgrat** [comment]
@magicrub 
Please explain what you mean with "readability is very important"
What is particulary hard to read? What is complicated at these three lines of code?
Everything I wanted is that someone uncomments them and maybe tries to find a reason for the described problem **(which is btw unrelated to this commit)**  and no **it is no build error**. Just re-read the description. 

@hiro2233 
What are you writing about?

```
    if(AP_HAL::micros() - _last_run_us < _loop_period_us) {
        return;
     }
```

**Comment by hiro2233** [comment]
@dgrat yes that, on your code the only one reason to break the build process is if your function is not equal to void. It's will be good if you put the error link from travis.

are you getting that error with the ardupilot's standard waf build system?

**Pull request closed without merging**
