### PR TITLE
Logging for 3rd EKF core

### PR DESCRIPTION
**Pull request by bugobliterator**

### CODE REVIEW

**Comment by rmackay9** [comment]
@priseborough, are you OK with this as well?  I think it's OK but just to be sure..

**Comment by tridge** [comment]
Thanks Sid!
needs testing then should be merged
we should also enable a 3rd IMU in SITL, to allow for easier testing

**Comment by rmackay9** [comment]
@peterbarker or I will test after the dev call and then assuming that works we will merge it

**Comment by peterbarker** [comment]
Tested on a CubeBlack here.

**Pull request merged**
