### PR TITLE
Support YAW in GPS_INPUT for Vicon 

### PR DESCRIPTION
**Pull request by tridge**
This adds support for a yaw field in GPS_INPUT which provides a way for external GPS sources to provide yaw information to EKF3

This PR depends on https://github.com/ArduPilot/mavlink/pull/105 and should wait on that PR being merged

### CODE REVIEW

**Comment by rmackay9** [comment]
@tridge, we already have quite a few messages for providing external position sources including the "mocap" and "vicon" messages.  Any reason why you'd prefer to use GPS messages?

**Comment by tridge** [comment]
@rmackay9 yes, several reasons

 - it allows for testing of GPS based flight control indoors in a highly controlled and accurate environment
 - it works with EK3, whereas the vision position messages are EK2 only
 - it allows testing of a mixture of GPS and vision based control with known truth data, for testing transitioning from GPS to non-GPS flight control in one flight

**Comment by rmackay9** [comment]
@tridge,

OK, but on it's own the second bullet point (EKF3's lack of support for vicon messages) is probably not a good reason to move to GPS messages because we have [this outstanding PR](https://github.com/ArduPilot/ardupilot/pull/10374) which adds support.  @priseborough (or someone) just needs to spend a bit more investigating why it's not stable

**Comment by tridge** [comment]
@rmackay9 sure, but it isn't on it's own. I'm actively using this in a vicon. It is very useful to be able to switch between the GPS and vision data. They should give the same results. When they don't then that allows us to investigate bugs in the vision fusion code.

**Comment by rmackay9** [comment]
As discussed on skype, i'm not suggesting we hold up this PR because regular GPSs can provide yaw so it makes sense that we allow this with the GPS_INPUT mavlink message as well.

**Pull request merged**
