### PR TITLE
AP_Mount: Ignore RC input values outside of the valid range

### PR DESCRIPTION
**Pull request by gitgitgogogo**
https://github.com/ArduPilot/ardupilot/issues/6096
https://github.com/ArduPilot/ardupilot/issues/2375
https://github.com/ArduPilot/ardupilot/issues/2426

### CODE REVIEW

**Comment by khancyr** [comment]
need to fix the commit message too
AP_Mount: limit input to input range
or something like that 

Those lib are quite mess, a good rewrite would simplify this ... but that is out of the scope of this PR

**Comment by khancyr** [comment]
@gitgitgogogo that is not the github PR that you need to change but the commit message ^^
Look here for some help : http://ardupilot.org/dev/docs/git-interactive-rebase.html

**Comment by amilcarlucas** [comment]
Now you can use a `git rebase -i master` to squash the commits and correct the message.

The message should look like this:
```
AP_Mount: Ignore RC input values outside of the valid range

fixes #2375
fixes #2426
fixes #6096
```

**Comment by gitgitgogogo** [comment]
It's ok now. This is my first PR😄

**Comment by khancyr** [comment]
Thanks ! It looks got to me! Let's wait it pass travis and we could merge

**Comment by khancyr** [comment]
This was solve by https://github.com/ArduPilot/ardupilot/pull/9953

**Pull request closed without merging**
