### PR TITLE
HAL_ChibiOS: hwdef: add new hardware MFE-PixSurveyA1

### PR DESCRIPTION
**Pull request by mfe-xiao**
HAL_ChibiOS: hwdef: add new hardware MFE-PixSurveyA1
Tool: added MFE-PixSurveyA1 board ID

### CODE REVIEW

**Comment by timtuxworth** [comment]
The "A1" will be stripped when this board id is displayed in any GCS such as Mission Planner/QGC. Suggest you abbreviate to 13 characters or less.

**Comment by mfe-xiao** [comment]
> 
ok, I've renamed mFE-PixSurveya1 to PixSurveyA1.

**Comment by mfe-xiao** [comment]
> The "A1" will be stripped off when this board id is displayed in any GCS such as Mission Planner/QGC. Suggest you abbreviate to 13 characters or less.

ok, I've renamed mFE-PixSurveya1 to PixSurveyA1

**Review by tridge — APPROVED** [review]

**Comment by Hwurzburg** [comment]
@mfe-xiao please add a README.md file for this autopilot to aid in wiki development

**Pull request merged**
