### PR TITLE
hwdef:include minimal in minimize_common

### PR DESCRIPTION
**Pull request by Hwurzburg**
just doesnt make sense to me that minimize common doesnt do this, and so then will fpv_osd and minimize features

btw we are going to need a periph specific include soon...F103-GPS is getting tight

### CODE REVIEW

**Review by andyp1per — APPROVED** [review]
Makes sense to me

**Review by peterbarker — CHANGES_REQUESTED** [review]
This should using `include`, not in-lining the files.

**Comment by Hwurzburg** [comment]
I was hoping that we could eventually git rid of them entirely...just have minimize features or minimize fpv osd or minimze ap periph at some point...having lots og these is confusing as to which to apply when

**Comment by Hwurzburg** [comment]
@peterbarker per our conversations, have removed minimal everywhere...almost all uses were either on osd based parts which moved to the fpv_osd include or minimize_features was already used

**Pull request merged**
