### PR TITLE
AP_GPS: New driver AP_GPS_NORTH for deal with our RTK gps

### PR DESCRIPTION
**Pull request by jaluna**
We want to incorporate our libraries/AP_GPS/AP_GPS_NORTH driver for deal with our RTK gps. This driver is based in AP_GPS_NMEA with some changes.

Juan A Luna
North Europe 2012, SL
http://northsurveying.com/

### CODE REVIEW

**Comment by WickedShell** [comment]
What does this do that is different then the standard NMEA one? I scanned it really quickly and only really saw identical behaviour. If there aren't any major changes then why not just extend the NMEA driver directly to support it?

**Comment by rmackay9** [comment]
I think through a bit of bad timing, this conflicts with the GPS_MAV type that just went in.  It's no big deal except that I think it will need to be moved to "15" in the GPS_Type enum.
https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_GPS/AP_GPS.h#L72

**Comment by jaluna** [comment]
Hello WickedShell,

yes, maybe is more easy to fix NMEA driver for detect RTK state on GPS.

But there are also a major difference, see the Ctor, we cannot accept the string sent here

//gps.send_blob_start(state.instance, _initialisation_blob, sizeof(_initialisation_blob));

Juan

**Comment by jaluna** [comment]
Yes, rmackay9, but easy to solve conflict

Juan

**Comment by WickedShell** [comment]
Does that blob somehow lock the GPS up? (If so what specific part, as some
of the generic autotdetect stuff outside of the NMEA driver is throwing
some NMEA strings (although I think manufacturer specific) that you would
have to be able to handle.

**Comment by WickedShell** [comment]
All of the blobs are proprietary messages, why can't it accept those?

**Comment by jaluna** [comment]
I don't know if can affect. I need to consult it. For safety, I have removed it. We cannot leave margin of error.

http://diydrones.com/profiles/blogs/group-flights-of-drones-with-rtk-gps-and-real-life-precision-of

Maybe can you accept a "empty" blob in NMEA driver?

Juan

**Comment by jaluna** [comment]
hi, after thinking better, **we are not connecting TX wire from pixhawk to your receiver**. So, you can leave blob because never will received.

So, the important fix is in the NMEA driver, because is unable to detect RTK state in their current version

Juan

**Comment by WickedShell** [comment]
Without the Rx wire, RTK operation is only supported with an additional radio? (Just curious)

NMEA driver would just add the empty blob to the others, so it's not really going to help anything. Again unless you have only NMEA specified (and even then I'm not sure) the autodetect blobs will be emitted at the receiver which it would have to handle.

Anyway as an initial starting point maing the NMEA parser understand RTK NMEA sentences is fundamentally worth doing anyways (probably as a separate PR).

As a last note this would be merged into master not copter-3.4 so that's what the PR should be opened against in the future.

**Comment by tridge** [comment]
I'd also like to note that the NMEA driver has a major limitation that it does not provide vertical velocity, as there is no standard NMEA message for vertical velocity. If your GPS can report vertical velocity via some extra sentence type then it would be well worth adding that. The EKF really does want to get vertical velocity for best results.
Also, it would be possible to have two GPS type selects in GPS_TYPE map to the same driver, then the driver could look at the type to determine behaviour. This would allow you to have specialise behaviour for your GPS while still taking advantage of the NMEA driver

**Comment by jaluna** [comment]
Dear WickedShell,

yes, our RTK solution is external. We connect only RX and GND pins of the GPS connector of Pixhawk. See photo below

http://gnssrtkmodule.com/index.php/manuals/7-rtkite-to-pixhawk-integration-guide

Juan

**Comment by jaluna** [comment]
Dear tridge,

the idea to parametrize the behaviour of NMEA driver is very interesting for me, because were also working in processing of gps values in ArduPilot, so the NORTH driver is not yet a copy of NMEA driver, have new code (internal filters). So, an option is to parametrize NMEA driver to use these filters or not.

For other hand, WickedShell, yes, we have also added this driver to branch Master (see https://github.com/jaluna/ardupilot/tree/master/libraries/AP_GPS) because is the version that we use for land Rover (APMrover2). We are testing with a vineyard robot http://skyacreswinery.com/vineyard/

Juan

**Comment by WickedShell** [comment]
Closing in favor of #6949 and #6955. As far as I can tell all this was addressing was removal of the init blob, and handling of some of the RTK fix types in the GGA message, which the previous pair of PR's addresses. If this is incorrect then feel free to reopen/update this as needed.

**Pull request closed without merging**
