### PR TITLE
AC_PosControl: fix minor bug for set_max_speed_z()

### PR DESCRIPTION
**Pull request by lukezhqin**
I believe what you guys actually want to do is just what I mean in this PR here.

### CODE REVIEW

**Comment by rmackay9** [comment]
Ah, yes.  this looks better, thanks!

**Comment by lukezhqin** [comment]
> Ah, yes. this looks better, thanks!

Sure thing! We can do better with all guy's efforts.

**Comment by rmackay9** [comment]
Oh, I just realised this went into the Copter-4.0 branch.. really it should go into master.  I will cherry-pick it into master but for next time, let's do master branch first.

**Comment by lukezhqin** [comment]
> Oh, I just realised this went into the Copter-4.0 branch.. really it should go into master. I will cherry-pick it into master but for next time, let's do master branch first.

Sorry, I was a litter confused by the master and missing develop branch maybe. I shall noticed this in the future.

**Comment by rmackay9** [comment]
this is included in Copter-4.0.0-rc3

**Pull request merged**
