### PR TITLE
moved AC_WPNav's init_brake_target and update_brake to mode_brake.cpp

### PR DESCRIPTION
**Pull request by rishabsingh3003**
This PR moves AC_WPNav's init_brake_target and update_brake to mode_brake.cpp. It is in response to issue #11504.

I checked the BRAKE Mode in SITL and it seems to working perfectly.

### CODE REVIEW

**Comment by rmackay9** [comment]
Hi @rishabsingh3003, thanks very much for this.  Looks like it's functionally correct.  A couple of style things to change before we merge if possible:

- let's just put the code directly into the ModeBrake::init and ModeBrake::run methods instead of putting them in new functions.  It doesn't make much difference but the code is short enough that it will save future developers from having to look around.
- can you split the change into two commits?  one that affects AC_WPNav and the other Copter.  Each commit should start with "AC_WPNav: " or "Copter:".

Thanks!

**Comment by rishabsingh3003** [comment]
HI @rmackay9 , I submitted a PR as per your instructions. Makes sense to do it this way. I am very new to github and not too experienced as a programmer either. Hopefully this is what was required.  Changed it into two commits, and got rid of the new functions.

**Comment by rmackay9** [comment]
@rishabsingh3003, getting there.  The commits need to be "squashed" and then a "force push" is required to clean up the commits so there's only 2.  [There's some advice here on the wiki about using "interactive rebased"](http://ardupilot.org/dev/docs/git-interactive-rebase.html).

**Comment by rmackay9** [comment]
I'll close this PR now because I've rebased it on master and resolve the issues with the commits subject line.
https://github.com/ArduPilot/ardupilot/pull/11567

**Pull request closed without merging**
