### PR TITLE
OSD: Add panel parameter descriptions

### PR DESCRIPTION
**Pull request by Hwurzburg**

### CODE REVIEW

**Comment by OXINARF** [comment]
@Hwurzburg Have you tested this? Pretty sure it doesn't work.

**Comment by Hwurzburg** [comment]
Not quite sure how to test that the WIki will pick it up....I had asked @tridge if this was the way to add the comments and he thought so...

**Comment by Hwurzburg** [comment]
The only solution I've been advised is that I would take a complete redo of the params, tripling them to >90...its too much work for me to undertake this....its sad that this means that there will be no documentation of the display panels, especially those that are non-intuitive...if anyone knows of an easy way to add a description to those panels, let me know...

**Comment by sh83** [comment]
I think it is possible to rework docs generation tools to handle this case nicely (without need to copy-paste 20+ params), isnt it?

**Comment by Hwurzburg** [comment]
Tridge showed me a way to do it without a horrible amount of work....should get the most important ones done in a day or so....

**Comment by Hwurzburg** [comment]
I am a bit handicapped since I cannot test the changes....  params_parse.py script has bug in that it does not build all params from the AP_OSD modules..... eg  OSDx_VSPEED, _WIND, etc. are not built into the html file, but others of the same class are....not sure I can proceed...

**Comment by Hwurzburg** [comment]
Updated and squashed...

**Pull request merged**
