### PR TITLE
Libraries: Comment out unused methods

### PR DESCRIPTION
**Pull request by muramura**
I found with the cppcheck tool that there is an unused method.
I could not easily determine which method is being used and which method is being used.
I thought that it could be easily determined by specifying it with #if 0 and #endif preprocessors.

### CODE REVIEW

**Comment by rmackay9** [comment]
I think we should just delete them methods in AP_RangeFinder, AP_Proximity, AP_OpticalFlow, AP_Gripper.

I suspect the AP_Radio::dump_registers should remain.  I don't know about the others.

**Comment by WickedShell** [comment]
Yeah. I'm pretty opposed to the #if 0 thing here. It doesn't buy us anything, the symbols are being omitted anyways, and it's more to track while editing/will go stale. Either we keep them or delete them, I'm pretty opposed to this as a partial step.

**Comment by muramura** [comment]
@rmackay9 san., @WickedShell san... Comments Thanks.
When I change the source, I search in grep and make sure there are no omissions.
I would like to run the cppcheck tool etc every time I change it.
I feel that I was leaving the idea that the original developer would use it in the future for deleting.
I think that it is easy to judge when changing, if there is "currently not used" in the method comment.
I quit #if 0 #endif.
I would like to add the method comment above.
How is it?

**Comment by WickedShell** [comment]
@muramura just delete the methods that aren't used. `dump_registers` are developer convenience features and should be retained, but I think you will find it doesn't make a difference in build size to leave them around, and it's better then `#if 0` because the code still has to be compileable, rather then silently bit rotting.

**Comment by OXINARF** [comment]
This needs to be carefully checked. On a first quick pass I've already found out code being removed that is indeed being called somewhere (AP_Gripper_EPM).

**Comment by WickedShell** [comment]
Closing as abandoned, and other changes are needed based on the discussion. Feel free to open a new PR with the required changes (or push them into this then reopen it).

**Pull request closed without merging**
