### PR TITLE
New Frame to manage YAW in a plus frame with NYT

### PR DESCRIPTION
**Pull request by Iragne**
Hi all,

I created a new frame for ardupilot that is able to manage yaw like a tri copter for a NYT plus.
Today it's a frame mainly to manage a F35B airplaine were we have a yaw like a tricopter 

Happy to discuss about it. 

here some links
https://youtu.be/6Pp2PLNoluQ
https://discuss.ardupilot.org/t/tail-tilt-yaw-servo-do-not-work/83784/7

### CODE REVIEW

**Comment by IamPete1** [comment]
The goto solution for such things is now lua scripting. We have bindings for everything you need.

```
-- get throttle motor output
---@return number
function motors:get_throttle() end

-- get throttle motor output
---@return integer
---| '0' # Shut down
---| '1' # Ground idle
---| '2' # Spooling up
---| '3' # Throttle unlimited
---| '4' # Spooling down
function motors:get_spool_state() end

-- get yaw FF output
---@return number
function motors:get_yaw_ff() end

-- get yaw P+I+D
---@return number
function motors:get_yaw() end

-- set external limit flags for each axis to prevent integrator windup
---@param roll boolean
---@param pitch boolean
---@param yaw boolean
---@param throttle_lower boolean
---@param throttle_upper boolean
function motors:set_external_limits(roll, pitch, yaw, throttle_lower, throttle_upper) end
```
You then output to the yaw servo on one of the scripting functions.

**Comment by Iragne** [comment]
@IamPete1 it's exactly what i'have done the first time but due to too low memory on my F765-WSE and issue to get AHRS to the right Type. I stop Lua Script. Happy to discuss this with you and all issue I faced with my setup

**Comment by IamPete1** [comment]
Happy to try and get scripting to work for you if we can. There are some other advantages, we could do the 3BSM mixing in the script as well.

Have you seen Eric's F35 talk? (@LoftedAero) He has a custom mixer somewhere too, if I recall correctly his is a new class that inherits from motors mutil (Sorry I can't find his branch). We would not accept these changes as they are now as it confuses the standard mutirotor mixer too much. A new class would fix that, although we still may not accept it if its possible with scripting, its a very specialized mixer. 

https://www.youtube.com/watch?v=iBbFxsB6KV0

**Comment by Iragne** [comment]
@IamPete1 No I haven't seen his talk yet but thanks for Sharing.
I'm puzzled now, I can easily create a separate class to avoid the confusion and I fully agree with you, it should be in a separate class. In a same time if you say me that it will not be accepted it's not worth the effort. my goal was also to help LalaRC (https://www.youtube.com/channel/UCwbV1lfgV-7ZamC-dyi6grA) with an official option for this issue.

Now going back to Lua script with all issues i had on my board (Mateksys F765-WSE), I don't know if it's worth loosing both our time on it. I recall that the refresh rate of the lua script was very slow and made the compute not accurate. also this refresh ratio impacted the stabilization.  (that is why i enter in the ardupilot code).
Also the documentation of Lua was not really easy so .... 

I'm not sure for instance to properly understand 
function motors:set_external_limits(roll, pitch, yaw, throttle_lower, throttle_upper) end
Here it's what i should do in lua
`
const float compensation_gain = get_compensation_gain();
yaw_thrust  = (_yaw_in + _yaw_in_ff) * compensation_gain * sinf(radians(_yaw_servo_angle_max_deg));
float cc = cosf(_pivot_angle);
_pivot_angle = safe_asin(yaw_thrust);
_thrust_rpyt_out[3] = _thrust_rpyt_out[3] / cc;
`

But iI'm not sure how i can do that part

`
// compensation for battery voltage and altitude
const float compensation_gain = get_compensation_gain(); 

// set the updated thrust for the mot_4
_thrust_rpyt_out[3] = _thrust_rpyt_out[3] / cc;
`

**Comment by IamPete1** [comment]
It is a little involved in lua, but it should all be possible. To be clear I'm not saying that we wouldn't accept a new dedicated mixer, just that its not a guaranteed merge. If we can come up with something that works for all the F35 type vehicles that various people are making then there is more chance. However as I say, I think you would still need to use scripting to do the 3BSM mixing (that would not get in to the main code, too many parameters and config required). If your using scripting anyway for that it is not so bad to do the mixing there too. 

I have to admit I have not tried scripting on a F7 recently but H7 boards should handle it no problem. 

To change the thrust of the rear motor you would have to use the dynamic matrix bindings to change the motor pitch scale factor. 

The `set_external_limits` allows the script to tell the PID controllers that they are the limit of travel in yaw. This prevents them from winding up I term against the limit. Its the scripting equivalent of your `limit.yaw = true` on line 273.

**Comment by Iragne** [comment]
So sorry I close this pr. But still for my project I will continue my fork. As soon as I will have something working correctly. I will try to implement the Lua script.

**Pull request closed without merging**
