### PR TITLE
Move Scheduler call to compass-cal-update up to AP_Vehicle

### PR DESCRIPTION
**Pull request by peterbarker**
`COMPASS_CAL_ENABLED` still doesn't work. but at least it's closer.

### CODE REVIEW

**Review by IamPete1 — APPROVED** [review]
Change looks correct. 

Note that this does up the rate from 50 to 100hz on plane, rover and tracker.

**Review by tridge — COMMENTED** [review]
why is this costing more flash?

**Comment by peterbarker** [comment]
> why is this costing more flash?

image

I think that says that the AP_Vehicle var_info constructor got larger for some reason.

I can't fathom that so far.

**Comment by peterbarker** [comment]
`MatekF405-Wing`
```
Binary Name      Text [B]       Data [B]     BSS (B)        Total Flash Change [B] (%)      Flash Free After PR (B)
---------------  -------------  -----------  -------------  ----------------------------  -------------------------
antennatracker   20 (+0.0030%)  0 (0.0000%)  4 (+0.0031%)   20 (+0.0030%)                                    325212
arducopter-heli  20 (+0.0021%)  0 (0.0000%)  4 (+0.0031%)   20 (+0.0021%)                                     33580
ardurover        20 (+0.0023%)  0 (0.0000%)  4 (+0.0031%)   20 (+0.0023%)                                    127556
arducopter       20 (+0.0021%)  0 (0.0000%)  -4 (-0.0031%)  20 (+0.0021%)                                     43484
ardusub          20 (+0.0025%)  0 (0.0000%)  -4 (-0.0031%)  20 (+0.0025%)                                    166808
blimp            20 (+0.0030%)  0 (0.0000%)  4 (+0.0031%)   20 (+0.0030%)                                    305944
arduplane        20 (+0.0020%)  0 (0.0000%)  -4 (-0.0031%)  20 (+0.0020%)                                      3836
```

**Review by tridge — APPROVED** [review]

**Pull request merged**
