### PR TITLE
AP_Scripting: Updated aerobatics with path tracking example

### PR DESCRIPTION
**Pull request by MatthewHampsey**
Added path tracking of trajectories generated by functions parameterised by time.

Pair programmed with @tridge and Andy Palmer

### CODE REVIEW

**Comment by tridge** [comment]
@MatthewHampsey thanks Matthew! A real pleasure working with you and Andy on this

**Comment by rmackay9** [comment]
@MatthewHampsey normally our commits start with the subsystem name so it might be good to change the commit title to be, "AP_Scripting: updated aerobatics with path tracking example".

Also a tiny nitpick is I think the very last line of the lua script has been changed unnecessarily.  Something about line endings or carriage return or something is missing I think.

**Comment by MatthewHampsey** [comment]
> @MatthewHampsey normally our commits start with the subsystem name so it might be good to change the commit title to be, "AP_Scripting: updated aerobatics with path tracking example".
> 
> Also a tiny nitpick is I think the very last line of the lua script has been changed unnecessarily. Something about line endings or carriage return or something is missing I think.

Whoops! Fixed the missing line terminator and amended the commit message and PR title. Thanks.

**Review by rmackay9 — APPROVED** [review]
I haven't checked every line but in general it looks ok to me.

**Comment by tridge** [comment]
I think this can be closed now?

**Pull request closed without merging**
