### PR TITLE
AP_NavEKF3: allow easier arming without compass

### PR DESCRIPTION
**Pull request by rmackay9**
This is an alternative to PR https://github.com/ArduPilot/ardupilot/pull/16061 and its primary purpose is to make it easier for users (of all vehicles) to arm without a compass by only setting COMPASS_USE/2/3 = 0.  Previously users would also have had to set EK3_SRC1_YAW = 0.

Changes included in this PR are:

- original PR's change to the parameters to make them enums removing the need for casting (non-functional change)
- the active_source_set structure is replaced with a simple uint8_t index.  This also allows the init() function to be removed (non-functional change)
- AP_NavEKF_Source::getYawSource() now returns None if EK3_SRCx_YAW == Compass but COMPASS_USE/2/3 == 0.  This makes the setup for no-compass users easier because they don't need to modify any EK3_ parameters.  The pre-arm check that would trigger is also disabled.

This has been lightly tested on a real autopilot to confirm that users can arm with EK3_SRCx_YAW == Compass and COMPASS_USE/2/3 == 0.
randy-no-compass-arming-test

As mentioned this applies to all vehicles which means we are essentially condoning Copter to fly without a compass.  When I actually tried to fly without a compass, even in Stabilize mode, I found the EKF failsafe triggered immediately.  I wonder if we can hear from @andyp1per what the requirements are to fly a copter with no compass.

### CODE REVIEW

**Comment by andyp1per** [comment]
I think this is good - I would like to see the same for GPS.

I disable the EKF failsafe on all my small copters - it triggers too easily when flying aggresively

Note that the EK3 initializing issue is still not fixed for me

**Comment by rmackay9** [comment]
Rebased on master and fixed up an autotest that was specifically checking that the pre-arm was failing.

@andyp1per,
I think it would be good to get some of the required setup steps for no-compass operation added to [this wiki page](https://ardupilot.org/copter/docs/common-compassless.html).  I think we've actually never officially supported no-GPS, no-compass operation but you've found a way to make it work.

**Review by tridge — APPROVED** [review]
looks good!

**Comment by rmackay9** [comment]
@Hwurzburg, I wonder if you could confirm that this fix works for you?  I'm happy to create a binary for your autopilot if that would help (just tell me what you're using).

**Comment by Hwurzburg** [comment]
Will do....will set it up on the bench now...I am pretty comfortable with git manipulation and builds now....thanks though

**Comment by Hwurzburg** [comment]
just a quick test on an OmnibusF4pro with plane...without setting compass_usex to all 0, get the compass prearm failure...once set to 0 no compass pre-arm failure....cant arm beacause of logging and gps on the bench, but the arm failure no longer specifies compass....so its good to go

**Comment by Hwurzburg** [comment]
test flew today added to Pauls EKF fixes....worked fine, although Pauls stuff on second launch after bench wait while powered had a really scary hand launch... https://www.dropbox.com/s/6ilo1xu68d9zs8q/1220-ef3_test.BIN?dl=0

**Comment by rmackay9** [comment]
I've also tested these on a real vehicle flying in and out of my garage and all seems fine so merged!

**Pull request merged**
