### PR TITLE
AP_Mission: Fix if there are multiple do_cmd commands between the nav…

### PR DESCRIPTION
**Pull request by hpycuit**
…_cmd command at mission and only the first do_cmd will be executed other do_cmd will be ignored.

### CODE REVIEW

**Comment by rmackay9** [comment]
I don't think this is correct behaviour or at least its different from how the do commands are run at the moment.  Perhaps it's not documented very precisely but at the top of the [Copter Mission Command List](http://ardupilot.org/copter/docs/mission-command-list.html) page we say, "The Do commands will be run in order as soon as the preceeding navigation command before them starts".  I think this change might mean that if a new nav command starts the do-command immediately after it might not start because an earlier do-command has not completed.

For example in the case below, even after the vehicle reached waypoint-command1 and started moving towards, waypoint-command2, the do-command3 might not start running if do-command2 hadn't completed.
1. waypoint-command1
2. do-command1
3. do-command2
4. waypoint-command2
5. do-command3

If my understanding is correct, then I don't think this new behaviour is correct.  Or at least it's a change in behaviour that we would need to discuss.

**Comment by WickedShell** [comment]
@rmackay9 I'm not sure I get your comment, in the scenario you outlined do-command3 should never start until after waypoint-command2 has completed.

**Comment by rmackay9** [comment]
@WickedShell, yes you're right.  I've fixed the comment above.

**Comment by hpycuit** [comment]
@rmackay9 
Sorry,because the log record gives me a misunderstanding, after reading the code, I think the do command will be lost and modified the code.According to your reply, I read the code again, do command will not be lost;But do I need to do the do command2 that I did before waypoint command2 to be able to execute at waypoint command2, and is it better to execute logically than this?
The generation command is the following:
1.waypoint-command1
2.do-command1
3.do-command2
4.waypoint-command2
5.do-command3
But the actual implementation might look something like this:
1.waypoint-command1
2.do-command1
4.waypoint-command2
3.do-command2
5.do-command3
Please refer to the log I provided, the loss of command2 and command3 appeared in the log, and the order of execution changed.
[log_and_waypoint.zip](https://github.com/ArduPilot/ardupilot/files/1645414/log_and_waypoint.zip)

**Comment by rmackay9** [comment]
Ok, so I think I understanding of the effect of this PR's change.  Our current implementation abandons do-commands that are not run before we complete the nav-command.

My feeling is the current behaviour in master of abandoning do-commands is the correct behaviour.

**Comment by rmackay9** [comment]
We discussed this on the dev call today and the major concern with this solution is that it means a do command might not be executed immediately as the next navigation command is started (because the new do-command might be held up while an older do-command completes).

Some ideas for solutions to the underlying, "do-command may not execute" issue came up.  One idea was to have multiple do-commands running in parallel although this adds some complexity including what happens if two do-commands affecting the same feature are run at the same time?  For example two condition-yaw commands would end up interfering with each other.

Another solution may be simply to warn the user that some do-commands have been skipped by sending a message to the ground station and (optionally) logging a message to the dataflash log.

I'm going to close this PR now.  Thanks very much for the efforts in any case and I hope you'll continue to contribute in the future!

**Pull request closed without merging**
