### PR TITLE
AP_NavEKF2: Get the minimum number of satellites from the config parameter

### PR DESCRIPTION
**Pull request by muramura**
There is a minimum number of GPS satellites in the config parameter.
I think it is better for the user to use this number of satellites.
I would like to use more minimum number of satellites for GNSS and RTK positioning.

### CODE REVIEW

**Comment by peterbarker** [comment]
Why do you care about the number of satellites?

I'd rather have 6 satellites and 10cm positional accuracy than 30 satellites and 20cm positional accuracy.

Satellites are a means to an end, not an end unto themselves.

**Review by khancyr — COMMENTED** [review]
The 6 satellites comes from the min limit to have the gnss units to do a good position survey, I don't think we need to modify this.
Having a static const value could be good to prevent the hardcoded value to be split across files

**Comment by rmackay9** [comment]
Thanks for highlighting this parameter and I think it's reasonable for a developer to try and re-use this parameter across all AHRSs.  If not, why is it there?

I suspect the answer is that this is a case of DCM using the general AHRS namespace when really it should have its own like EKF2 and EKF3 do.  Sadly it is unlikely that this will ever change but perhaps we should make it clear in the parameter description that they are DCM only otherwise I think it's reasonable that users would think they apply to all AHRS.

**Comment by peterbarker** [comment]
EK2 is a legacy estimator; we won't merge things like this into it for stability reasons, sorry.

**Pull request closed without merging**
