### PR TITLE
CI: simplify build script

### PR DESCRIPTION
**Pull request by OXINARF**
Simplify build script so that we don't need to keep adding boards to arrays every time we want to add or change the tested boards.

After this goes in I'm going to change Semaphore to test different boards then the ones in Travis.

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
For Linux boards you can also stop using make and only build with waf. Make is already deprecated.

**Comment by OXINARF** [comment]
@lucasdemarchi Do you have a timeline for removing Make for Linux? If it is a short timeline I'll remove it now, otherwise I would prefer to only remove it before we remove Make - just to make sure that nothing goes in that breaks Make.

**Comment by lucasdemarchi** [comment]
Timeline is probably one release of each vehicle. But for make I think we can just do scheduled builds of master rather than building everything. This by itself would reduce a lot the time we wait to check if a build succeeded.

**Comment by OXINARF** [comment]
What do you mean with scheduled builds? I just remembered that the Ardupilot server builds master binaries with make, so maybe this is enough for now. I'll add a commit to remove make for Linux in a bit. Can I also remove it for sitl? SITL test would still use make.

**Comment by lucasdemarchi** [comment]
> What do you mean with scheduled builds?

Not sure about Travis but in semaphore you can schedule daily builds for example of a certain branch. My proposal is to have a daily build of master using make, but for PRs we only use waf for Linux boards.

>  Can I also remove it for sitl? SITL test would still use make.

Sitl test already covers sitl, so sitl can be removed.

**Comment by OXINARF** [comment]
Ok Lucas, but that involves more work because we need to check when it is a scheduled job and build with Make only then.
So I ask that this is merged now and I'll do the work to remove Make later (this week hopefully).

**Comment by lucasdemarchi** [comment]
Applied, thanks.

**Pull request closed without merging**
