### PR TITLE
Plane: Change mode to RTL on end of mission rather then staying in auto

### PR DESCRIPTION
**Pull request by WickedShell**
Previous behavior was to do the RTL while in auto. From a users perspective this could look like a flyaway due to the plane not aiming at the way point it says its flying at, as well as being extremely surprising why its not on the mission/trying to get to the last way point in the mission.

### CODE REVIEW

**Comment by WickedShell** [comment]
Theres some more clean up of now dead code, don't merge yet.

**Comment by WickedShell** [comment]
This does have a slight behavior change thats worth noting: If you have RTL_AUTOLAND turned on and you jump past the landing sequence when you finish the mission it would go to the landing sequence and attempt to land the aircraft. This is only possible if you planned a landing sequence in the mission originally however and then had way points after the landing that you jumped to.

I'm not sure how many people are affected by this. It seems like a reasonable behavior for the autopilot, however people might be used to/relying on the current behavior.

**Comment by magicrub** [comment]
yeah, you'd need to have a broken mission for that to happen but we should check with @tridge with regard to how comfortable he is about changing that behvaior. RTL is something a lot of people rely on.

**Comment by magicrub** [comment]
I lost track, where are we on this? Last I remember @tridge gave the thumbs up on the concept so it's ready for review+merge?

**Comment by tridge** [comment]
applied, thanks!

**Pull request closed without merging**
