### PR TITLE
Move initialisation of SerialManager and GCS up to AP_Vehicle

### PR DESCRIPTION
**Pull request by peterbarker**
Functional changes here:
 - `AP_Stats` is initialised *after* we initialise the serial manager and the GCS console.  `AP_Stats` doesn't do anything that warrants being initialised before SerialManager, and if things to wrong in stats init it would be good to get diagnostic output (if any)
 - Sub sets the delay callback much earlier.  A good thing as it is more consistent with the other vehicles and may give GCS feedback while calibrating.
 - we set the ins log bitmask bit rather later in Plane.  Considering we initialise logging much than this code, it doesn't matter

### CODE REVIEW

**Comment by khancyr** [comment]
AP_Stats could be moved too, can't it ?

**Comment by peterbarker** [comment]
@khancyr `AP_Stats` is protected by `#ifdefs`.  We only get to use the `HAL_` optional compilation things in libraries.  Whether AP_Vehicle counts as a library... nobody knows ;-)

**Comment by peterbarker** [comment]
The Rover thing is more than just adding the `override`.  That method is doing some seriously funky stuff to do with outputs, and will require a chunk of inspection before moving the call up in the initialisation order.  It also should be removed from Rover's `init_ardupilot` method.

So one thing I notice is that set_control_channels in Rover calls functions on the motors library *before* the motors library is `init()`'d.  Fun stuff.

**Comment by peterbarker** [comment]
I've looked through the Rover change and think moving the set_control_channels should be OK.  The calls made in there are configuring ranges and types on input and outputs, which should affect things only in a positive manner.

... still needs to be run on some vehicles.

**Comment by peterbarker** [comment]
I've now put this on a Rover and it didn't cause any fires.

**Pull request merged**
