### PR TITLE
Rover: Minor fixes for the Windows build

### PR DESCRIPTION
**Pull request by gmorph**
With the recent inclusions of these libraries (AC_Fence and AP_Proximity) the build configuration needed to be updated so waf worked on Windows.  Linux was unaffected.

### CODE REVIEW

**Comment by khancyr** [comment]
LGTM !
@amilcarlucas it should fix your problem ^^

**Comment by hiro2233** [comment]
Hello,
this https://github.com/ArduPilot/ardupilot/pull/6728 fix for all vehicles indeed.

**Comment by OXINARF** [comment]
@gmorph Can you tell which tools you are using on Windows? Is it our Pixhawk toolchain?
@amilcarlucas Same question.

We shouldn't just merge this without understanding the root cause. Build on Windows and Linux should be exactly the same. I'm pretty sure I know the reason: the linker on Windows isn't removing the unneeded methods like it should and so a link error happens. We kind of depend on that happening though - otherwise we either can't do common code or all vehicles need to compile all libraries that are used in common code (and that would make the binaries bigger).

**Comment by OXINARF** [comment]
Just to make it clear: AC_Fence and AP_Proximity haven't been added to Rover yet. There are PRs to do it, but they haven't been merged yet. So there should be no need to add it to the build yet.

**Comment by khancyr** [comment]
@oxinarf my main explaination for this requirement is the move of proximity stuff into dataflash and gcs common. But I agree with you that it should have a bug in the toolchain or on our rules for cygwin...

**Comment by hiro2233** [comment]
@OXINARF  the linker on cygwin doesn't dirscard the unused function.

**Comment by hiro2233** [comment]
`void DataFlash_Class::Log_Write_Proximity(AP_Proximity &proximity)`
This function is unused in all vehicles and libraries.

**Comment by hiro2233** [comment]
@OXINARF Pixhawk toolchain on windows is built under MSYS evniroment, not Cygwin indeed. The problem is in Cygwin.

**Comment by gmorph** [comment]
@OXINARF - I'm using cygwin and WAF from the command line to build SITL.
./modules/waf/waf-light configure --board sitl
./modules/waf/waf-light build --target bin/ardurover
I am having these issues on master - not with PRs that my be coming.  These are problems for me now trying to build SITL for Rover.
I think its coming from AP_Proximity_SITL as that is also using AC_Fence.

**Comment by OXINARF** [comment]
OK, thanks @gmorph. So it looks like the issue is that the GNU ld has a very experimental garbage collector for PE/COFF binaries. Although I'm generally against hacks, I think that, in this case, it is a better solution than having to compile more libraries in all other targets/hosts. I'll try to have something working soon.

**Comment by OXINARF** [comment]
@gmorph @amilcarlucas @hiro2233 

Can you guys test https://github.com/OXINARF/ardupilot/commits/pr/fix-windows-sitl-build ? Thanks.

**Comment by karthikdesai** [comment]
@OXINARF Hey Francisco,
Just compiled SITL on your branch using waf on Cygwin in Windows. Received no errors!

**Comment by hiro2233** [comment]
@OXINARF Compile all bin group ok with standard Cygwin features, but with posix case-sensitive feature enabled it's doesn't build ok.

This error throw with posix feature enabled.
francisco2

There is a little big detail indeed, your workaround affects all enviroments, that touch everything, not only Cygwing.

This is compile all ok with this PR and include the libraries needed for Cygwin targets.
https://github.com/ArduPilot/ardupilot/pull/6728

francisco

**Comment by gmorph** [comment]
@OXINARF - I did the following
./modules/waf/waf-light distclean
./modules/waf/waf-light configure --board sitl
./modules/waf/waf-light build --target bin/ardurover
no errors.  
Note the make.inc still has the new libraries added into it in this branch.  I realise that waf doesn't use this but just thought I'd mention it for completeness.
Thanks, Grant.

**Comment by OXINARF** [comment]
@karthikdesai Thanks

@hiro2233 That issue isn't related to this one.

@gmorph Yes, doing the same trick in the Make build system would be too much work for a system that is deprecated, so I left that part.

OK, I merged my branch, so I'm closing this.

**Pull request closed without merging**
