### PR TITLE
Plane: Aerodynamic Load Factor / Stall Factor correction - closes issue  #6747

### PR DESCRIPTION
**Pull request by auturgy**
This is the simplest fix: just changing the equation.  I haven't changed the variable name, although I feel I should have, as doing so broke a number of things including dataflash/logging that I didn't want to mess with.  I may make those alterations as a separate PR idc.
THIS PR WILL ALTER FLIGHT PERFORMANCE AND REQUIRES INFLIGHT VALIDATION as the stall ratio now calculated is significantly larger due to relocation of the sqrt, permitting greater bank angles.
Closes https://github.com/ArduPilot/ardupilot/issues/6747

### CODE REVIEW

**Comment by yuxiqun** [comment]
@auturgy Great！You are right. I am looking forward to an early realization.

**Comment by tridge** [comment]
this doesn't look right to me - I don't mind renaming the variable, but I'd want to see a much more careful analysis before I make a change to the bank angle limit. Paul and I went through that pretty carefully and we think it is right.
Is there some reason you think the calculated bank angle limit is wrong?

**Comment by magicrub** [comment]
related to https://discuss.ardupilot.org/t/how-to-get-my-plane-to-turn-tighter-in-auto-mode/20300/10

**Comment by auturgy** [comment]
I took your limit condition as representing your math (LF = 1.1 @ 25 degrees).  This is true for the "real" Aerodynamic Load Factor, but not for the Stall Factor (SF = 1.05 @ 25 degrees).  I didn't actually work numbers through your code.  I should have: it turns out both our math is right, and its the limit/comment that is misleading.  
1.0f / safe_sqrt(cosf(radians(demanded_roll))) ==  safe_sqrt(1.0f / cosf(radians(demanded_roll))). 
(which is obvious and a little embarassing in hindsight)
So the first change in this PR doesn't actually do anything.
The second part isn't really necessary (proposed == current at zero angle of bank), and relies on the SF>1 to avoid numerical errors, so may be best left out anyway.

What remains is what I didn't change:  the 25 deg bank angle limit is artificially limiting: Stall Factor 1.1 = 35 degrees of bank before stall, not 25.  This reduces maneuverability in a particular part of the flight envelope (1.05<SF<1.1).  So the limiting condition could be dropped to 1.05 (preferred, I think), or the roll limit increased to 35 degrees, or leave as is.

**Comment by magicrub** [comment]
>So the limiting condition could be dropped to 1.05 (preferred, I think), or the roll limit increased to 35 degrees, or leave as is.

Would you mind updating the PR for this? A force-push would be fine. We can discuss it from there and either merge or close.

Thanks for double-checking the math! We can always use more eyes on the maths code.

**Comment by auturgy** [comment]
Thanks Tom.  I should be able to do that over the weekend.  I'll change the variable names too, which I think reaches into 3 or 4 other files - I might need some help there so I don't break logging/DF and fail CI.
Would you prefer a push on this PR, or close this and open a clean one?

**Comment by tridge** [comment]
With the high level of uncertainty in airspeed measurements I would prefer to keep a tighter limit on roll when close to stall. 
Also, when close to stall the amount of control with the ailerons/elevons tends to be less, especially if tuning is not perfect. Overshoots by a 5 to 10 degrees is common.
The key factor is that ArduPilot should err on the side of avoiding stall. Once we have stalled then recovery is very difficult for an autopilot (it often fails).
I'd be happy for comments to be updated, but I'm not keen on loosening these conditions.

**Comment by magicrub** [comment]
@auturgy please push (or force-push) to same branch/PR

**Comment by davidbuzz** [comment]
no movement since 2017.

**Comment by davidbuzz** [comment]
tridge has essentailly said 'will not merge' on this as it stands, no movement in a long time.

**Pull request closed without merging**
