### PR TITLE
Copter: Arbitrary pre-arm distance

### PR DESCRIPTION
**Pull request by muramura**
I'm flying a multicopter of a size such as Toy Drone BUG3, F550, F890.
I want to take off from the safe area of the aircraft.
I want to change the avoidance distance when pre-arming according to the size of the aircraft.
I made it changeable.

### CODE REVIEW

**Comment by rmackay9** [comment]
@muramura, or maybe we should just remove this pre-arm proximity distance check?  I often hit it as well and it's a bit annoying.

**Comment by muramura** [comment]
@rmackay9 san.. Comments thanks.

I need to arm the aircraft where people and cars pass.
I sometimes take drones off the road.
I do not want the aircraft to harm people.
I think this feature is effective.

**Comment by khancyr** [comment]
Hello, I don't think we should remove this check as it can prevent two stupid accident : 
- somebody to close
- taking off and triggering an avoidance movement that would be unexpected.

I think a better approach would be to move this check either on proximity or in avoidance check, and allow it to be warn only (for those that like to lost their fingers)

**Comment by peterbarker** [comment]
No answer in 4+ years; closing.

**Pull request closed without merging**
