### PR TITLE
Copter: bump version on master to 3.7.0

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by peterbarker** [comment]
@lvale reports that some users are getting confused between running the master branch and running the Copter betas.

Bump the version on master to avoid this confusion.

**Comment by peterbarker** [comment]
Note that our version strings do incude enough information to differentiate 3.6dev from 3.6rc

**Comment by Pedals2Paddles** [comment]
> Note that our version strings do incude enough information to differentiate 3.6dev from 3.6rc

I wonder if it would be best to do this upon the first RC release for that reason.

**Comment by rmackay9** [comment]
Merged, thanks.  Normally I do this after we've done the last rebase on master.  I think -rc6 was the last rebase although -rc7 was pretty close to a rebase.

**Pull request merged**
