### PR TITLE
AP_GPS: move initialisation of some members into header

### PR DESCRIPTION
**Pull request by peterbarker**
It's neater and fixes some initialiser-list-order problems

### CODE REVIEW

**Comment by peterbarker** [comment]
... also no compiler-output-change, which is cute:
```
Board                    AP_Periph  blimp  bootloader  copter  heli  iofirmware  plane  rover  sub
CubeOrange-periph-heavy  *                                                                     
Durandal                            *      *           *       *                 *      *      *
Hitec-Airspeed           *                                                                     
KakuteH7-bdshot                     *      *           *       *                 *      *      *
MatekF405                           *      *           *       *                 *      *      *
Pixhawk1-1M-bdshot                  *                  *       *                 *      *      *
f103-QiotekPeriph        *                                                                     
f303-Universal           *                                                                     
iomcu                                                                *                         
revo-mini                           *      *           *       *                 *      *      *
skyviper-v2450                                         *                                       
```

**Review by IamPete1 — APPROVED** [review]
LGTM

**Comment by tpwrules** [comment]
It becomes harder to see and reason about the initial values if they are moved IMHO.

**Comment by peterbarker** [comment]
> It becomes harder to see and reason about the initial values if they are moved IMHO.

OK, we can agree to disagree on this.

I see it as a natural extension of the initialise-your-variabls-where-you-declare-them pattern uses in straight-line coding.

**Pull request merged**
