### PR TITLE
build: don't build examples with old build system

### PR DESCRIPTION
**Pull request by lucasdemarchi**
We currently check examples are buildable with waf which doesn't need
the libraries to be specified in a make.inc file.  Having the makefiles
there is misleading since people try to build and realize the build is
broken.

### CODE REVIEW

**Comment by magicrub** [comment]
This only applies when make support is dropped completely. Any dependencies holding that back still?

**Comment by lucasdemarchi** [comment]
I think we can apply it before that since currently the example build gets
broken very often (see last commit form kwikius). I think we should just
update our docs for building and uploading examples.

And wrt drop make-based build, I think the only thing holding that back is
the muscular memory of people used to the old commands. Oh, and
documentation update, particularly for windows.

Em 4 de out de 2016 1:34 PM, "Tom Pittenger" <notifications@github.com>
escreveu:

**Comment by OXINARF** [comment]
@lucasdemarchi It is true that we build examples with waf, but that doesn't mean that Make doesn't work. The examples were broken in PX4 because of the way we initiate drivers, it wasn't because of Make.

I'm fine with removing it though, I think it is a good first step to remove the old build system.

**Comment by magicrub** [comment]
What we need is for make to post a message about waf then exit.

On Oct 4, 2016 9:53 AM, "Gustavo José de Sousa" <notifications@github.com>
wrote:

*@guludo* approved this pull request.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/ArduPilot/ardupilot/pull/4931#pullrequestreview-2756068>,
or mute the thread

**Comment by lucasdemarchi** [comment]
Part of the examples were broken because they missed the dependency on
ap_boardconfig library.

Em 4 de out de 2016 1:45 PM, "Francisco Ferreira" <notifications@github.com>
escreveu:

**Comment by kwikius** [comment]
@lucasdemarchi  The examples were silently broken in PX4 since if you dont call AP_BoardConfig.init then you get no drivers running. But the build passes OK. and the board runs, just nothing happens. You need to call the BoardConfig::init function, which I eventually tracked down
https://github.com/ArduPilot/ardupilot/blob/master/ArduPlane/system.cpp#L130
The function is a nop in all other boards so only affects px4.
You don't see any diagnostic on the console with sd-card inserted since inserting the usb powers up the board but you cant start a teminal if no usb is inserted, so by the time you have started a terminal the diagnostic has gone. 

 If you add the board config init function without adding the Board config lib you get a linker error. But none of this has to do with make.
In fact waf is a complete blackbox. I have no idea how to get it to build anything including examples. Are there any docs or anything? Also seems slower than make FWIW.
Anyway before dropping make someone better right some docs how to do it with waf

**Comment by lucasdemarchi** [comment]
> In fact waf is a complete blackbox. I have no idea how to get it to build anything including examples. Are there any docs or anything? Also seems slower than make FWIW.

if you have no idea how to get to build anything, how do you find it slower? 
https://github.com/ArduPilot/ardupilot/blob/master/BUILD.md

In the specific case of examples:

```
./waf configure --board px4-v2
./waf examples
```

It's also the way we build them in CI.

This builds all examples.  If you are comparing the build time, you would need to go through each directory in the make build system and build all examples.

**Comment by lucasdemarchi** [comment]
And when I said we still need to update the documentation I meant ardupilot.org since BUILD.md already covers how the build system works and now to build with it.

**Comment by kwikius** [comment]
I dont want to build all the examples. I just want to build one, modify it, then see what happened. Currently I go to the directory I am working and type make. How to do the same with waf? The examples are for people to experiment with and learn a bit about ardupilot arent they? BTW. for px4 the Nuttx stuff would be better as a static lib. Make one mod to one example source file and it takes minutes to rebuild. Not very fun!

**Comment by guludo** [comment]
> I dont want to build all the examples.

https://github.com/ArduPilot/ardupilot/blob/master/BUILD.md#building-a-specific-program

Example: `waf --targets examples/INS_generic`.

You can use `waf list | grep examples` to see all the examples you can build.

> I just want to build one, modify it, then see what happened. Currently I go to the directory I am working and type make. How to do the same with waf?

The answer is above. Although I'd like to mention that when https://github.com/ArduPilot/ardupilot/issues/4561 is implemented, the command can get smaller. Anyway, on my Linux machine, something like `alias w=waf --targets examples/INS_generic` has been very useful when I build something constantly.

**Comment by lucasdemarchi** [comment]
> I dont want to build all the examples.

you can still pass `--targets` and build a single example.

> Currently I go to the directory I am working and type make.

you surely type `make <something>`, not only make.

> How to do the same with waf?

As I said there's missing doc on ardupilot.org. We are very much aware of the.  The BUILD.md file should cover much of what's need. Constructive feedback is appreciated.

So... suppose you are testing examples on PX4. What you do (once) is:

```
./waf configure --board px4-v2
```

Then:

```
./waf --targets examples/AHRS_Test
```

Testing another example:

```
./waf --targets examples/AHRS_Test
```

Building and uploading to the board:

```
./waf --targets examples/AHRS_Test --upload
```

See the documentation mentioned. You may query a list of possible targets. If you want a list of examples:

```
./waf list | grep examples/
```

> BTW. for px4 the Nuttx stuff would be better as a static lib. Make one mod to one example source file and it takes minutes to rebuild. Not very fun!

sigh. This is exactly what we do in waf. As opposed to the make build system, we build the common parts once creating some static libraries.  Experiment building all the examples, modifying one of them and building again.

**Comment by kwikius** [comment]
OK. I have been testing it out. It works OK  :) I didnt know about BUILD.md but anyway I think it really needs to be documented in the wiki as that is where new users start rather than in the repo. Maybe just a link to build.md, except in html as not all browsers can read the markdown 
Also using waf  is simpler since there is a waf script in the ardupilot directory now so you don't have to do the alias
As for speed, No way this is faster than a well written makefile. You can try running the command twice without touching any source and it takes around 30 seconds to do nothing ( make would  just look at what was touched in its sources, rather than "scanning dependencies" this must take  time, especially if it is python!), but that is the downside of automation I guess. 
Anyway it works and doesnt start on the so-called "generating uorb topic headers etc ... " in px4 which is a big improvement.
but no one will know about it unless it is in the wiki :)

**Comment by lucasdemarchi** [comment]
> You can try running the command twice without touching any source and it takes around 30 seconds to do nothing

Humn... this only happens for px4. For some reason it needs to relink and generate the .px4 file again. Part of the problem is the way the integration with PX4 works. Maybe it can be optimized later.
For Linux boards this doesn't happen and I get the return of the second call in 2.8s.

**Comment by guludo** [comment]
> Maybe just a link to build.md, except in html as not all browsers can read the markdown

That's actually processed by GitHub, if we use https://github.com/ArduPilot/ardupilot/blob/master/BUILD.md for the link.

**Comment by guludo** [comment]
>> Maybe just a link to build.md, except in html as not all browsers can read the markdown

>That's actually processed by GitHub, if we use https://github.com/ArduPilot/ardupilot/blob/master/BUILD.md for the link.

Unless we want to embed that on the wiki, which probably what you meant.

**Comment by peterbarker** [comment]
I'm in favour of removing these Makefiles as another step towards a single build system.

However, as @magicrub suggested, I think adding some Makefiles which simply point the caller at waf is a really good idea.  This is based on my experience with the simplistic "just blow away sim_vehicle.sh" methodology, which didn't work out so well.

**Comment by kwikius** [comment]
It might be an idea to check them first to see if they do what they are intended to do. I suspect that a lot still need to be fixed to actually work.

See https://github.com/ArduPilot/ardupilot/pull/4927

That fixed some but there are plenty no checked. Here is a list which may or may not be accurate of what I didnt get to checking
AP_BattMonitor
AP_Mission
AP_Motors
AP_Notify
AP_OpticalFlow
AP_Parachute
AP_RangeFinder
DataFlash
GCS_MAVLink
PID
RC_Channel
AP_HAL/examples/UART_test

**Comment by tridge** [comment]
I also think this is a good step to be all-waf
pushed!

**Pull request closed without merging**
