### PR TITLE
AP_HAL_ChibiOS: swap order of ICM20602 and ICM20948_ext on CubeOrange

### PR DESCRIPTION
**Pull request by bugobliterator**

### CODE REVIEW

**Comment by WickedShell** [comment]
Does this not mess up your accel calibration and such?

**Comment by bugobliterator** [comment]
> Does this not mess up your accel calibration and such?

Yeah, the calibrations will be cleared, and will require to be redone.

**Comment by WickedShell** [comment]
A compromise would be to set the primary IMU parameter. That wouldn't help the DCM fallback path on plane, but wouldn't result in a breaking of every existing system... From a UX perspective that's pretty terrible.

**Comment by bugobliterator** [comment]
@WickedShell we don't have priority ordering in INS frontend. I guess we can set EK2_PRIMARY and EK3_PRIMARY instead, which will be equivalent. I will do that instead.

**Comment by WickedShell** [comment]
> @WickedShell we don't have priority ordering in INS frontend. I guess we can set EK2_PRIMARY and EK3_PRIMARY instead, which will be equivalent. I will do that instead.

That is what I was thinking. It's worth noting though that this won't help with the DCM fallback path. It may be worth adding a #define for the primary down the road. I'm not sure how much we care if DCM and EKF are using different sensors though.

**Comment by tridge** [comment]
I think changing EK3_PRIMARY is a better option, maybe EK2_PRIMARY too
It's not just the one off re-cal, it is the cal again if you go back to earlier firmware. Would make beta testing very painful

**Comment by WickedShell** [comment]
Okay, I'm good with the changes then. Do we want to do this for the CubeOrange-bdshot as well?

**Comment by bugobliterator** [comment]
> I think changing EK3_PRIMARY is a better option, maybe EK2_PRIMARY too
> It's not just the one off re-cal, it is the cal again if you go back to earlier firmware. Would make beta testing very painful

I have set EK2_PRIMARY as well

**Comment by bugobliterator** [comment]
> Okay, I'm good with the changes then. Do we want to do this for the CubeOrange-bdshot as well?

Ohh I missed that, I will try to get it done through hwdef.inc

**Review by tridge — APPROVED** [review]

**Comment by tpwrules** [comment]
Can you explain the motivation for this change? I am observing high position and velocity innovations and resulting `ErSc` values confined to EKF3 lane 0 in my custom hex build with a CubeOrange Plus running 4.3.0 resulting in EKF lane changes during certain maneuvers.

Switching `EK3_PRIMARY` to 1 solves these problems and results in better flight. My build is not amazing with respect to vibrations and I understand not all the IMUs in the Cubes are vibration isolated.

Was the former default the non-isolated IMU? Should this change be made on the CubeOrange Plus by default too?

**Comment by bugobliterator** [comment]
@tpwrules both IMUs are isolated, this backport is part of the solution of potential bug on ICM20602, second part is here https://github.com/ArduPilot/ardupilot/pull/22091. This change has nothing to do with isolated IMUs.
CubeOrangePlus is not impacted by this, as it doesn't contain ICM20602 .
Cubes have 2 IMUs that are isolated and one body fixed. Default order are good for most usecases. But it's possible you might need to change them. There are various tools and instruction to deal with vibrations. Please refer arducopter documentation for the same. If you are still facing issues, please seek help through ardupilot or cubepilot forums with logs.

**Pull request merged**
