### PR TITLE
SRV_Channel: allow DO_SET_SERVO, DO_REPEAT_SERVO and rc pass-thru on a single channel

### PR DESCRIPTION
**Pull request by rmackay9**
This is a replacement for this existing PR: https://github.com/ArduPilot/ardupilot/pull/11468 and resolves this issue: https://github.com/ArduPilot/ardupilot/issues/11210

The purpose is to allow both RC pass through from a pilot's transmitter and DO_SET_SERVO and DO_REPEAT_SERVO commands on the same output channel.

This has been tested on a Cube flight controller by doing this:

- compiling for Copter and uploading to the flight controller
- set RC7_DZ = 20 (default is 0)
- set SERVO7_FUNCTION = 56 (rcinput from channel 6)
- setup MP's tuning page to show "rc6in" and "rc7out"
- used the TX's ch6 tuning knob to change the rc6 input and confirmed rc7 updated smoothly
- used MP's Flight Data screen's Servo tab to set DO_SET_SERVO commands. observed that rc7 out updated to the expected pwm value.
- moved the rc6 input slightly and confirmed the rc7 output did not changed
- moved rc6 input more than 20pwm and confirmed the rc7 output jumped to the rcinput value
- repeated the above tests with small missions containing DO_SET_SERVO and DO_REPEAT_SERVO commands

### CODE REVIEW

**Comment by rmackay9** [comment]
@OXINARF when you get a moment maybe you could give this a quick review?

**Comment by tridge** [comment]
will this allow small changes from do_set_servo?

**Comment by rmackay9** [comment]
@tridge, as discussed on mumble, the do-set-servo works even for small changes.  Txs for the review, merging!

**Comment by tatsuy** [comment]
I've tried this on the real rover. It works well!
Thanks for the review and correction.

**Pull request merged**
