### PR TITLE
fence.init() was getting called even when AC_FENCE was DISABLED

### PR DESCRIPTION
**Pull request by dwiel**

### CODE REVIEW

**Comment by rmackay9** [comment]
@dwiel,

Looking good, I'm surprised it didn't create a compile error (or perhaps it did?).

In any case, can you modify the commit to be prefixed with "Copter:"?

**Comment by dwiel** [comment]
fixed

**Comment by peterbarker** [comment]
On Tue, 9 Jun 2020, Randy Mackay wrote:

> Looking good, I'm surprised it didn't create a compile error (or perhaps it did?).

I periodically run Tools/autotest/build-with-disabled-features.py to catch 
these.  I can't see how this wouldn't fail.

**Comment by rmackay9** [comment]
Ah, shoot, this went into the Copter-4.0 branch.  We should always merge first into master, then we backport to Copter-4.0

**Comment by dwiel** [comment]
Doh, I'm sorry about that. Should I redo the PR on master?

**Comment by rmackay9** [comment]
@dwiel, no, it's OK.  It's actually already fixed in master it seems.  All good, txs for the fix.

**Pull request merged**
