### PR TITLE
Copter DCM fallback

### PR DESCRIPTION
**Pull request by andyp1per**
In fast copters with high lean angles the EKF can get corrupted quite easily by GPS innovations leading to flyaways. In these cases DCM appears to be much more reliable. This PR allows copter to fallback to DCM in the same way that plane currently does.

### CODE REVIEW

**Comment by rmackay9** [comment]
It would be good if @priseborough can review the logs you're seeing.  As many know, I'm not a fan of bringing back DCM to copter.  The major reason for that was that it created a lot of support issues because it is so different from the EKFs many features didn't work (arming failures, EKF failsafe for example).

**Comment by andyp1per** [comment]
Just experimenting for now @rmackay9 - obviously if it does not help then I'll look elsewhere, but I have had two flyaway / crashes with the current EKF code.

**Comment by rmackay9** [comment]
@andyp1per, OK.  At the risk of being nitpicky, I guess when you say, "flyaway" you mean the vehicle lost position control.  ..but it probably didn't fly very far right?  The EKF failsafe should trigger before the vehicle gets too far.  Of course, if the EKF has lost its attitude estimate then it will be hard to even Land.

I think an enormous amount of development and testing would be required for us to safely support the fall back to DCM.

**Comment by andyp1per** [comment]
@rmackay9 the position estimate was out by 300m - that seems pretty far to me

**Comment by rmackay9** [comment]
@andyp1per, the estimate could be off by 300m but that doesn't mean the vehicle will fly off 300m of course.  I'm just questioning the use of "flyaway" that's all.  We have protections to prevent flyaways.

**Comment by priseborough** [comment]
@andyp1per Can you share the logs with me? I would rather we invest time in making the EKF more robust to your use case than resurrecting an old estimator that was dropped in part due to significant vulnerabilities to GPS and magnetometer errors.

**Comment by MichelleRos** [comment]
@priseborough I've also had quite a bit of EKF issues on my copter - 7 inch quad as well. 
Just about every flight for me is constant lane changes with scaled EKF innovations spiking above 1...

In any case, I'd love to hear if you and @andyp1per make any progress on this front. I can send logs as well, but they'll probably be pretty similar to Andy's ones.

**Comment by MichelleRos** [comment]
As far as this PR, I think it'd be really good to have this as a fallback - I don't think the idea is to fly permanently on DCM. Just to have it as a backup in case the EKF goes bad.

**Comment by priseborough** [comment]
I have prototyped a user selectable option for the EKF that will stop it completely rejecting GPS data for setups with large sensor errors https://github.com/priseborough/ardupilot/commits/pr-ekf3-gps-velpos-igate-mod and this should address the issue.

To help me develop this further can someone please provide flight logs that show the issue recorded with LOG_DISARMED=1 and LOG_REPLAY=1.

**Comment by andyp1per** [comment]
> To help me develop this further can someone please provide flight logs that show the issue recorded with LOG_DISARMED=1 and LOG_REPLAY=1.

Hi Paul, I am happy to do this but the weather is not playing ball (snow and wind) and I am away at the weekend. It's possible @MichelleRos also might be able to provide some logs from her vehicle. Do you need logs with your change enabled?

**Comment by MichelleRos** [comment]
@andyp1per I have a lot of replay logs where the EKF was hanging on by a thread (scaled innovations spiking above 2 at times and very frequent lane switching) - this happens pretty much every FPV flight I do - but I haven't recently managed to EKF failsafe it. The lane switching is really irritating though because of the constant messages printed out and the quad seems to jerk a bit every time it switches.

@priseborough the one EKF flyaway I had was not because of it ignoring the GPS, but it ignoring the baro (looks like your branch stops that too?) - it went straight up to about 40m while in land mode because it decided that both the GPS and the baro were lying to it (even though they agreed quite nicely) and it was gonna just integrate the IMUs instead... And it hadn't even failsafed. While this only happened once, the fact that this can happen makes me rather nervous about the EKF... Which is why I almost never fly at CMAC even though it's a drone flying field but is right next to a highway, because I just don't want to risk having a flyaway and the quad going through someone's windscreen...

In any case, perhaps we should continue this conversation in the "freestyle quads and the EKF/DCM" thread under the copter channel in Discord to avoid clogging up this PR's discussion?

**Comment by andyp1per** [comment]
@MichelleRos sounds like your replay logs might be suitable for now - are you able to send them over to Paul?

**Comment by rmackay9** [comment]
@andyp1per,

Now that PaulR's change has gone in we can close this?

**Pull request closed without merging**
