### PR TITLE
AP_BattMonotor: Allow the same event to be triggered repeatedly

### PR DESCRIPTION
**Pull request by xianglunkai**

### CODE REVIEW

**Comment by WickedShell** [comment]
This doesn't seem correct. This will lead to being unable to override the system in many events. Consider an action like QLand. If the user wants to interrupt this from happening they won't be able to, as the landing will be reasserted continuously, the same would happen with RTL.

Is there a usecase or intention I'm missing here?

**Comment by xianglunkai** [comment]
However, if the user interrupt the RTL behavior  , the RTL behavior cannot be triggered again although the power is low

**Comment by xianglunkai** [comment]
I seem the radio failsafe will trigger the  RTL repeatedly. Why is the battery not like this? This can prevent users from forgetting to replace the battery!

**Comment by WickedShell** [comment]
> I seem the radio failsafe will trigger the RTL repeatedly. Why is the battery not like this? This can prevent users from forgetting to replace the battery!

I'm not sure I'm following on the radio failsafe comment. We trigger the failsafe again as long as the failsafe has been cleared in between. Battery failsafes don't currently clear, because the voltage failsafes are prone to triggering too many times and lack any hysteresis.

As the PR stands unless I'm missing something this looks a user out of control of their vehicle permanently, which isn't appropriate. How does triggering the failsafe repeatedly stop the user from forgetting? It's worth noting that if you are using a GCS there will be a warning the whole time to tell you that the battery is low. This is also why there are two levels of failsafes a low and critical one.

**Pull request closed without merging**
