### PR TITLE
AP_Radio: expect delay whil resetting radios

### PR DESCRIPTION
**Pull request by peterbarker**
@hsteinhaus would you be able to test this patch?

(ref: https://discuss.ardupilot.org/t/arducopter-4-0-on-v2450-internal-error-0x8000/49570/4)

### CODE REVIEW

**Comment by peterbarker** [comment]
[arducopter.LOG](https://github.com/ArduPilot/ardupilot/files/3889892/arducopter.LOG)

This is a .abin file; github made me rename it.

**Comment by hsteinhaus** [comment]
@peterbarker Sure, will give it a try tonight.

**Comment by hsteinhaus** [comment]
No more internal errors and the Sky Viper is flying fine. Unfortunately no log on the card after flight, but I guess due to a corrupted SD card. Will try another flight with a new battery later.

**Comment by hsteinhaus** [comment]
Again no DF log on the card. The LOG_BITMASK was 65534, LOG_DISARMED was set to zero. After enabling LOG_DISARMED, I was able to obtain the attached log. After disabling it again, logging was working normally. I guess the logging hickups are just the usual FAT troubles and unrelated to the patch.

[000005.BIN.LOG](https://github.com/ArduPilot/ardupilot/files/3894223/000005.BIN.LOG)
[000002.BIN.LOG](https://github.com/ArduPilot/ardupilot/files/3894224/000002.BIN.LOG)

**Comment by peterbarker** [comment]
Thanks @hsteinhaus

**Comment by amilcarlucas** [comment]
I guess this needs to be in the Copter-4.0 branch as well

**Pull request merged**
