### PR TITLE
FETtec OneWire on top of AP_ESC_Telem backend v3

### PR DESCRIPTION
**Pull request by amilcarlucas**
This one is based on top of a newer version #16725 with https://github.com/andyp1per/ardupilot/pull/14 on top of it.

requires #16725

It is mostly similar to #16850 and #16963 but it is based on top of some other commits.

- [x] feature complete:
- control motor speed
- copy ESC telemetry data into MAVLink telemetry
- save ESC telemetry data in Dataflash logs
- use RPM telemetry for dynamic notch filter frequencies
- sum the current telemetry info from all ESCs and use it as virtual battery current monitor sensor
- average the voltage telemetry info and use it as virtual battery voltage monitor sensor
- [x] passes CI
- [x] protocol is documented in the `README.md` file in the same location as the `.cpp` implementation file
- [ ] [configuration instructions](/ArduPilot/ardupilot_wiki/pull/3335) are on the ardupilot wiki
- [ ] flight tested with a Hex frame using the last 6 channels (FETtec ID 7 to 12) 1 to 6 are unused/unassigned
- [ ] mavlink telemetry works (analyzed a `.TLOG` file to see that [ESC_TELEMETRY_1_TO_4](https://mavlink.io/en/messages/ardupilotmega.html#ESC_TELEMETRY_1_TO_4) and [ESC_TELEMETRY_5_TO_8](https://mavlink.io/en/messages/ardupilotmega.html#ESC_TELEMETRY_5_TO_8) messages are present or that [ESC_TELEMETRY_5_TO_8](https://mavlink.io/en/messages/ardupilotmega.html#ESC_TELEMETRY_5_TO_8) and [ESC_TELEMETRY_9_TO_12](https://mavlink.io/en/messages/ardupilotmega.html#ESC_TELEMETRY_9_TO_12) messages are present - using MissionPlanner->Ctrl-F->MavLinkInspector->Vehicle1->Comp1 - and their contents correct)
- [ ] `.bin` dataflash log files have ESC telemetry data in ESC7..12
- [x] flight tested with a Hex frame using the first 6 channels (FETtec ID 1 to 6)
- [ ] mavlink telemetry works (analyzed a `.TLOG` file to see that [ESC_TELEMETRY_1_TO_4](https://mavlink.io/en/messages/ardupilotmega.html#ESC_TELEMETRY_1_TO_4) and [ESC_TELEMETRY_5_TO_8](https://mavlink.io/en/messages/ardupilotmega.html#ESC_TELEMETRY_5_TO_8) messages are present - using MissionPlanner->Ctrl-F->MavLinkInspector->Vehicle1->Comp1 - and their contents correct)
- [x] `.bin` dataflash log files have ESC telemetry data in ESC1..6
- [ ] six independent [notch filters](https://ardupilot.org/copter/docs/common-imu-notch-filtering.html) work (used a hex for testing) 
- INS_HNTCH_ENABLE = 1,
- [INS_HNTCH_MODE](https://ardupilot.org/copter/docs/parameters.html#ins-hntch-mode-harmonic-notch-filter-dynamic-frequency-tracking-mode) = 3 (ESC telemetry),
- [INS_HNTCH_OPTS](https://ardupilot.org/copter/docs/parameters.html#ins-hntch-opts-harmonic-notch-filter-options) = 2 (dynamic notch)
- [INS_HNTCH_REF](https://ardupilot.org/copter/docs/parameters.html#ins-hntch-ref) = 1
- [ ] [IMU noise levels](https://ardupilot.org/copter/docs/common-imu-fft.html) measured before [notch filtering](https://ardupilot.org/copter/docs/common-imu-notch-filtering.html)
- [INS_LOG_BAT_MASK](https://ardupilot.org/copter/docs/parameters.html#ins-log-bat-mask) = 1
- [INS_LOG_BAT_OPT](https://ardupilot.org/copter/docs/parameters.html#ins-log-bat-opt-batch-logging-options-mask) = 0
- @teezeefpv please add a  [MissionPlanner FFT picture](https://ardupilot.org/planner/docs/common-measuring-vibration.html) here like described in the [noise analysis page](https://ardupilot.org/copter/docs/common-imu-batchsampling.html)
- [ ] [IMU noise levels](https://ardupilot.org/copter/docs/common-imu-fft.html) measured after [notch filtering](https://ardupilot.org/copter/docs/common-imu-notch-filtering.html)
- [INS_LOG_BAT_OPT](https://ardupilot.org/copter/docs/parameters.html#ins-log-bat-opt-batch-logging-options-mask) = 2
- @teezeefpv please add a [MissionPlanner FFT picture](https://ardupilot.org/planner/docs/common-measuring-vibration.html) here like described in the [noise analysis page](https://ardupilot.org/copter/docs/common-imu-batchsampling.html)
- [x] voltage and current measurements replace the need for power monitoring hardware:
- [BATT_MONITOR](https://ardupilot.org/copter/docs/parameters.html#batt-monitor-battery-monitoring) = 9 (BLHeli ESC)

Compared to master this PR needs just 592 bytes for ArduCopter on a Durandal flight controller :)

I also [backported most of this to ArduCopter-4.0.7](https://github.com/ArduPilot/ardupilot/pull/16874)

### CODE REVIEW

**Comment by amilcarlucas** [comment]
@andyp1per what do you think about commit fa9aad4 from @teezeefpv  ?
Looks like RPM had a 100 scaling before?

**Comment by amilcarlucas** [comment]
Welcome @coptingtech, I hope to see nice contributions from you here ! :)

**Comment by andyp1per** [comment]
> @andyp1per what do you think about commit [fa9aad4](https://github.com/ArduPilot/ardupilot/commit/fa9aad4602babf94a617e14378433140a5122b35) from @teezeefpv ?
> Looks like RPM had a 100 scaling before?

Yes, nice catch!

**Comment by amilcarlucas** [comment]
Andy please select "rebase and merge" instead of "merge pull request" when merging my pull requests.

**Comment by andyp1per** [comment]
> 
> 
> @andyp1per what do you think about commit [fa9aad4](https://github.com/ArduPilot/ardupilot/commit/fa9aad4602babf94a617e14378433140a5122b35) from @teezeefpv ?
> Looks like RPM had a 100 scaling before?

Oh wait, no this is not correct - it needs to be multiplied by 100 because that's what the format says it is, the format is "e" which is   "int32_t * 100", so * 100 is correct I believe and corresponds with what all the other drivers were doing before.

**Comment by amilcarlucas** [comment]
So the RPM handling functions are all using real RPM and not RPM/100 ?

**Comment by andyp1per** [comment]
> 
> 
> So the RPM handling functions are all using real RPM and not RPM/100 ?

Yes

**Comment by teezeefpv** [comment]
I added the conversion from the telemetry in eRPM (which is send as eRPM/100) to eRPM (by *100) and the conversion from eRPM to RPM into the AP_FETtecOneWire.cpp in line 136. 
`update_rpm(i, requestedTelemetry[i]*100/(pole_count.get()/2));`

I don't know if this is the right place, but there were no additional conversion that calculates eRPM. I think it makes sense to pass rpm as the function is called "update_rpm". I measured the real motor speed and compared it with the mavlink output and it shows the correct RPM. 

So do I need to add additional *100 to the real RPM? And in general or just for logging, telemetry or something? 

Correct me please if I am wrong, but I think the eRPM calculation for BlHeli is not correct. It is divided by motor poles, not by motor pole pairs. If the motor has 14 motor poles, eRPM has to be divided by 7 (which is motor poles divided by 2 to get the pairs)

**Comment by andyp1per** [comment]
@teezeefpv the calculation in BLHeli is correct because this is what BetaFlight does and also results in RPM values that are correct for notch calculation. I can't comment on whether BLHeli32 is returning the correct values - but it doesn't matter, they are not going to change and we have to calculate RPM in the way shown.

The calculation is ```erpm * 200 / motor_poles``` which is the same as you have above

**Comment by amilcarlucas** [comment]
@teezeefpv to reduce the number of divisions you should use
 `update_rpm(i, requestedTelemetry[i]*100*2/pole_count.get());`

And do not use * 100 anywhere else. Basically `git revert fa9aad4`

**Comment by coptingtech** [comment]
@amilcarlucas  Thanks for the info. Will be testing it soon.

**Comment by coptingtech** [comment]
Flight logs will be uploaded here [https://drive.google.com/drive/folders/15L3EWuRJ4yhAwteYoU15bQeZkAslj1bL?usp=sharing]]. It also contains older logs from previous firmware versions. Tested on a Hexacopter with Air gear 450 motors, Fettec ESC and CubeOrange.

**Comment by amilcarlucas** [comment]
@coptingtech I only need 3 files per flight: `.bin`, `.tlog`, `.mp4`

**Comment by amilcarlucas** [comment]
@teezeefpv we can remove the draft state and start peer reviews once more tests are done.

**Comment by amilcarlucas** [comment]
@teezeefpv I finished protocol documentation in the README.md file and moved the configuration stuff to the wiki. Can you review it?

**Comment by coptingtech** [comment]
I installed the new version on the copter. We noticed that the battery voltage shown is 7.7V, although voltage shown by the ESC 1-4 is around 15V. And the temperature of the ESCs jumps between 40-240. I have uploaded the tlog and bin files in the [drive ](https://drive.google.com/drive/folders/15L3EWuRJ4yhAwteYoU15bQeZkAslj1bL)(Arducopter_00f82fc3)

**Comment by amilcarlucas** [comment]
@coptingtech please post comments on #17063. This PR is no longer open

**Pull request closed without merging**
