### PR TITLE
AP_Motors: Add DECA frame class and type string

### PR DESCRIPTION
**Pull request by muramura**
I think the frame type indicates the shape of the frame.
I think the + is better than the PLUS.
I have also added a DECACOPTER frame class, frame type.

Screenshot from 2021-03-09 00-37-26

### CODE REVIEW

**Review by amilcarlucas — APPROVED** [review]
It does save memory :)

**Comment by rmackay9** [comment]
Thanks for catching the missing DECA frame class string.  I would definitely like to merge this part of the change.

I don't think there's much advantage to changing "PLUS" to "+" though so let's remove this part of the change.

**Comment by muramura** [comment]
@rmackay9 san.  I decided to just add the DECA frame class and type string.

**Comment by rmackay9** [comment]
Merged, thanks!

**Pull request merged**
