### PR TITLE
Update default.parm file for new Copter-3.6 batt parms

### PR DESCRIPTION
**Pull request by lordneeko**

### CODE REVIEW

**Comment by khancyr** [comment]
I would say that it should be a problem to switch it back on 150 , for an user using default setting and toy_mode, it is safer. 
But let's see what other say !

**Comment by rmackay9** [comment]
Might be good to start the commit with "Tools:".  Maybe Tridge should confirm..

**Comment by khancyr** [comment]
try to look here : http://ardupilot.org/dev/docs/git-interactive-rebase.html

**Comment by lordneeko** [comment]
I removed the change to land_speed since that was an unknown as to why it got changed from the skyrocket factory defaults.

**Pull request closed without merging**
