### PR TITLE
Make and use AP_LANDINGGEAR_ENABLED

### PR DESCRIPTION
**Pull request by peterbarker**
The vehicle definitions weren't really accomplishing much:
```
Master:
bin/arducopter   1807572      3484   258884               1811056          155016

This PR:
bin/arducopter   1805316      3484   258884               1808800          157272
```

The patch in RC_Channels makes the difference.

elf_diff shows no difference between Copter binaries when landing gear is included.

This starts to include landing gear on Plane on Pixhawk1-1M, clearly not acceptable.

What's the way forward there?  Stop including it on any vehicle if `HAL_MINIMIZE_FEATURES`?

### CODE REVIEW

**Comment by rmackay9** [comment]
Normally we use "Copter:" instead of "ArduCopter:" as the prefix for changes to the Copter vehicle.

**Comment by peterbarker** [comment]
> Normally we use "Copter:" instead of "ArduCopter:" as the prefix for changes to the Copter vehicle.

Mmmm... have you checked the commit list recently? :-)

I really do prefer "Copter:", but the split-script uses ArduCopter".

**Comment by rmackay9** [comment]
@peterbarker,

Yeah, I figured the split script was the reason you'd used the "ArduCopter:" prefix..

**Comment by tridge** [comment]
try in whitelist, see how much it costs with extended test_ccache.py

**Comment by peterbarker** [comment]
```
Board              AP_Periph  blimp  copter  heli  plane  rover  sub
Durandal                      -248   0       0     0      -248   -240
Hitec-Airspeed     0                                             
KakuteH7-bdshot               -224   0       0     0      -224   -224
MatekF405                     -376   0       0     0      -232   -376
Pixhawk1-1M                   -368   0       0     -320   -224   -368
f103-QiotekPeriph  0                                             
f303-Universal     0                                             
revo-mini                     -216   0       0     0      -216   -216
skyviper-v2450                       -376                        
```

**Comment by peterbarker** [comment]
When compiled with:
```
define AP_LANDINGGEAR_ENABLED 0
define LANDINGGEAR_ENABLED 0
```
```
Board              AP_Periph  blimp  copter  heli   plane  rover  sub
Durandal                      -248   -2240   -2256  -1824  -248   -240
Hitec-Airspeed     0                                              
KakuteH7-bdshot               -224   -2216   -2216  -1584  -224   -224
MatekF405                     -376   -2232   -2240  -1848  -232   -376
Pixhawk1-1M                   -368   -2336   -2184  -312   -224   -368
f103-QiotekPeriph  0                                              
f303-Universal     0                                              
revo-mini                     -216   -2208   -2216  -1744  -216   -216
skyviper-v2450                       -384                         
```

elf-diff for Copter/Durandal shows library functions being removed:

image
image

**Pull request merged**
