### PR TITLE
AP_AHRS: call INS update in AP_AHRS::update w/o holding data sem

### PR DESCRIPTION
**Pull request by peterbarker**
We shouldn't be holding the data semaphore while waiting for the samples
- lots of things might be unnecessarily blocked

DCM's update function doesn't need to take the semaphore as it is
already taken by AP_AHRS

### CODE REVIEW

**Comment by tridge** [comment]
once this has been flight tested, and log reviewed, happy to go in

**Comment by peterbarker** [comment]
@andyp1per tridge mentioned this might be of interest because of crsf stuff

**Comment by peterbarker** [comment]
I've tested this on a SkyViper.

innovations look "fine" for whatever "fine" looks like on a Skyviper - same before/after.

What is interesting is that I don't get the `PM` message in the dataflash logs on SkyViper either before or after this patch!

**Comment by peterbarker** [comment]
I've now tested this again on a CubeBlack on the bench.  No changes in the `PM` message I can see.

**Comment by andyp1per** [comment]
> @andyp1per tridge mentioned this might be of interest because of crsf stuff

I'm not sure I understand how this affects CRSF, but great 😄

**Comment by peterbarker** [comment]
On Tue, 31 Aug 2021, Andy Piper wrote:

>       @andyp1per tridge mentioned this might be of interest because of crsf stuff
> 
> I'm not sure I understand how this affects CRSF, but great 😄

The CRSF, like OSD, takes the AHRS semaphore when retrieving its data:

https://github.com/ardupilot/ardupilot/blob/master/libraries/AP_RCTelemetry/AP_CRSF_Telem.cpp#L794

That semaphore was only available while the main loop was running but 
only after the AHRS update was done!  And *then* you have to deal with 
thread priorities to see who wins (and hope something sleeps if you 
wouldn't otherwise win).

**Pull request merged**
