### PR TITLE
SITL Location corrected

### PR DESCRIPTION
**Pull request by AndKe**

### CODE REVIEW

**Comment by OXINARF** [comment]
This needs to be rebased in master (no merge commits are allowed) and squashed. Usually the commit message should also be something like "Tools: added <xyz> to locations.txt", but this isn't always followed, so it's OK if it doesn't follow the exact correct spec - in any case, a more descriptive message would be appreciated.

@AndKe I would do that if you were new here, but I'd like you to learn these basic skills for the future. If you need help with this, ask here or in Gitter and I'll help you.

**Comment by AndKe** [comment]
Thanks. I'll redo it from scratch, don't know how I ended up with that
mess.  :)

**Comment by OXINARF** [comment]
@AndKe It's not very messy and very easy to fix with a Git interactive rebase - if you haven't played with it this might be a good time to look it up.

**Comment by magicrub** [comment]
PRO TIP: for something simple like this its easy enough to just rebase on master then reset mixed and recommit. No rebase -i needed.

**Comment by AndKe** [comment]
Tanks - I rebased on current master, did git reset --mixed, made  a new
commit - I think it's correct, and I learned new stuff, but then I get
```
 git push origin locations
To https://github.com/AndKe/ardupilot.git
 ! [rejected]        locations -> locations (fetch first)
error: failed to push some refs to 'https://github.com/AndKe/ardupilot.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

```
I do not wish to fetch that - do I ?  - that would bring back the problems ?

**Comment by AndKe** [comment]
did a push -f now, does it look good now ? (I think so)

**Comment by OXINARF** [comment]
@magicrub I guess that depends on your preference, I would use interactive rebase here, way faster to me.

@AndKe Great! Thank you for fixing it.

**Pull request merged**
