### PR TITLE
ChibiOS: added KakuteF7 port

### PR DESCRIPTION
**Pull request by tridge**
work in progress

### CODE REVIEW

**Comment by tridge** [comment]
you're right, I put this together very quickly based on the omnibusf7v2. I have the schematic, and can fix this properly quite quickly. I'll try to get it done tomorrow

**Comment by Huibean** [comment]
Having trouble with sd card logging but the SPI1 pin specific seems right

**Comment by Huibean** [comment]
Just test RCIN with Spektrum Satellite, the RCIN should mapping to UART6 Rx?

**Comment by Huibean** [comment]
I just finish adding RC by change PC7 to `PC7 TIM8_CH2 TIM8 RCININT FLOAT LOW
` and cancel UART6

**Comment by Huibean** [comment]
I mounted KakuteF7 to a QVA250 frame and finish GPS loitor and RTL test which works fine, now lack to voltage and current detect and SD card logging, once I finish I could PR changes to this Branch

**Comment by tridge** [comment]
great, thanks!

**Comment by tridge** [comment]
I've cleaned up the PR a bit, and added OSD
should be ready to merge when CI passes

**Comment by tridge** [comment]
hmm, microSD is mounting, but IO is failing

**Pull request merged**
