### PR TITLE
PID lib removal

### PR DESCRIPTION
**Pull request by khancyr**
We have PID and AC_PID, I find that AC_PID is more complete and PID is only used on deepstall landing so we should be able to easily remove it.

### CODE REVIEW

**Comment by WickedShell** [comment]
Off the cuff I'm not a fan. If it's only used in deepstall at the moment whats the harm in maintaining it? This could have been looked at before 3.8 released, but now would involve breaking changes to people who have setup parameters for deepstall as I don't see a translation layer for the parameters.

If I set the same gains would I actually see the same resultant behavior from AC_PID?

**Comment by khancyr** [comment]
Damned french guys! Always late for war!
The math on both are quite the same. AC_PID is more granular as you can split the part and have variable LP cut frequency, on PID it is fix to 20Hz. I haven't made advance check but the output should be the same.
What bother me is having to implementation, newcomers will not know which one use ... And I rather prefer to have only one to cleanup ;-P

**Comment by tridge** [comment]
the maths is close now, but AC_PID is going to be changing a lot with Leonards plans
I don't think we should combine these, it breaks things for plane users for no reason

**Comment by tridge** [comment]
it also doesn't build, which doesn't fill me with confidence that the change is well thought out. 
sorry Pierre, closing

**Comment by khancyr** [comment]
hello, 
Ok no problem! But I didn't find  why travis is failling...

**Comment by rmackay9** [comment]
Putting aside the specific issues with the PR, I agree with the motivation to consolidate on a single PID library if we can.  I think the AC_PID class has received the most love so it's the obvious candidate.  We could rename it to AP_PID to reflect this.

**Pull request closed without merging**
