### PR TITLE
AP_Compass:enable_QMC5883 to use

### PR DESCRIPTION
**Pull request by ljwang1102**
#6633 This problem does not matter with QMC588,and The new code I did not find the problem

### CODE REVIEW

**Comment by ljwang1102** [comment]
@tridge 
@rmackay9 I think it can be added to AC3.5.3

**Comment by OXINARF** [comment]
@rmackay9 Can you please test this?

**Comment by OXINARF** [comment]
@rmackay9 Can you please test this?

**Comment by jamming** [comment]
HMC5883/5983 is very difficult to purchase right now. So, when will release the AC3.5.3?

**Comment by OXINARF** [comment]
I've reverted the commit that disabled the QMC5883 by default, so this is done now. Thanks!

Fixes #6988

**Pull request closed without merging**
