### PR TITLE
GCS_MAVLink: divide time allowed to send messages fairly

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by peterbarker** [comment]
Testing:
 - Rover
 - 50Hz
 - 1x esp8266 @ 115200
 - 1x telemetry radio @ 57600
 - 1x USB connection
 - 1x direct serial connection to my laptop @ 921600

The direct serial connection isn't responding to anything sent to the autopilot.  I'm currently believing that to be a separate issue.

Attempting to set the streamrate to 10Hz on the 921600 link yields 6Hz.  All other channels maintain 4Hz.

However.

This works much better on this branch than on master - but it works actually pretty well with all of the message Rover puts out even on master - not falling into a heap like it seems to on Plane.

I'll put Plane on another autopilot here.

**Comment by peterbarker** [comment]
This *signficantly* unbreaks things for Plane.

Same setup as for Rover - which generally works OK even on master.

Completely unusable @50Hz.  300Hz fixes it.

This patch also fixes things.

The difference between Rover and Plane?

Plane says "use 500 microseconds for sending all mavlink messages".  We make sure we have at least 200 microseconds before we start to send any mavlink message, meaning we're allowing 300 microseconds to send data on all four links in this case.

Rover is allowing 1000 microseconds.  Meaning it is allowing 800 microseconds to send all messages - so it generally works on master anyway.

**Comment by peterbarker** [comment]
hardwired 921600 serial connection problem was purely physical.  Different usb-ttl adapter works fine.

**Comment by tridge** [comment]
thanks for looking at this so quickly Peter!

**Comment by rmackay9** [comment]
I don't really understand what this is but it's included in Copter-4.0.4-rc1

**Pull request merged**
