### PR TITLE
AP_Vehicle: add 0x to internal error statustext

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by peterbarker** [comment]
> LGTM. This still fits on a single line of course?

Oh yes :-)

**Comment by hendjoshsr71** [comment]
I'd be sort of tempted, to add the line number here as I thought we output that to the GCS.
But that isn't really needed by users. And that is in the log messages (assuming logging is working of course ;)) .

**Comment by peterbarker** [comment]
> I'd be sort of tempted, to add the line number here as I thought we output that to the GCS. But that isn't really needed by users. And that is in the log messages (assuming logging is working of course ;)) .

This is a mask of all internal errors that have occurred, so there's no single line number involved.

If that is relevant for a flight you're doing, I suggest landing, packing it up for the day and finding something else to do for the afternoon.  Probably drinking.

**Comment by WickedShell** [comment]
> I'd be sort of tempted, to add the line number here as I thought we output that to the GCS. But that isn't really needed by users. And that is in the log messages (assuming logging is working of course ;)) .

It may help with random reports from users who aren't being good about providing logs, then again we probably need the log file anyways so it might not be worth it.

**Comment by hendjoshsr71** [comment]
LOL you're hilarious Peter! :)  I've had these occur recently with multiple folks on the ground on boot. And pulling a log is extra work.

But IEs aren't really normal user serviceable anyways

**Pull request merged**
