### PR TITLE
Copter: cope with flying a long distance from the origin

### PR DESCRIPTION
**Pull request by tridge**
The copter position controller often does calculations like this:

  position += velocity * dt;

when this is run at the loop rate then the delta to the position is small enough relative to the position that it becomes zero when we are at a long distance from the origin. At a speed of 1.5m/s the delta becomes zero at around 100km from the origin. This means that flying more 100km from the origin leads to navigation failures.
This PR converts the position portion of the copter position controller to double precision. This allows for flying at up to around 800km from the origin. To go beyond that we need to convert the EKF to double precision, see PR #17356 

To aid in testing the PR also adds SIM_INIT_LAT_OFS, SIM_INIT_LON_OFS and SIM_INIT_ALT_OFS. These offset the initial GPS position (for first 20s after startup), which moves the origin. The issues with flying at a long distance from the origin then become very apparent.
A simple test is to fly in LOITER with RC4 at 1400, this demanding a small forward speed. Without this PR the copter does not move forward. With this PR it does.
Even with this PR there is a small amplitude oscillation in velocity at 112km (lat offset of 1). I don't yet know what causes that

Note: We need to look at the CPU cost of this on F405 boards. If unacceptable it would be possible to make this compile time by using a Vector2p and Vector3p type, which would be Vector2f or Vector2d based on a build option, the 'p' standing for position.

### CODE REVIEW

**Comment by tridge** [comment]
I plan on rebasing this on #17823

**Comment by tridge** [comment]
test on CubeBlack. Setup is:
 - dual GPS (one UAVCAN, one uart)
 - loiter mode
 - EK3_MAG_CAL=4 to force mag fusion
Baseline master firmware: averaging 284 sched misses per 10s, SYS_STATUS.load approx 665
with this PR, averaging 286 sched misses per 10s (within noise), SYS_STATUS.load approx 670
so very little difference in CPU load. There is a flash cost though

**Comment by WickedShell** [comment]
What's the difference in RAM and stack usage? I'm not expecting that to be
a blocker, but I am curious since I'd expect that to go up at last a bit.

**Comment by tridge** [comment]
PR now redone on top of poscontrol API cleanups, and double precision only enabled for boards with > 1M flash

**Comment by tridge** [comment]
> What's the difference in RAM and stack usage?

RAM cost on CubeBlack: about 70 bytes, stack cost is actually slightly negative as this PR cleans up to use Vector2 in a lot of places instead of Vector3

**Comment by tridge** [comment]
rebased

**Review by lthall — APPROVED** [review]

**Pull request merged**
