### PR TITLE
DevEnv: Add C++ and Lua recommended extensions for VSCode

### PR DESCRIPTION
**Pull request by TunaLobster**
Right now this is a short list. VSCode will read this list and suggest these extensions when a the repository is opened for the first time. It is not required, but will make it easier for a new user to start coding more easily.

@hendjoshsr71 @IamPete1 Thoughts?

### CODE REVIEW

**Comment by IamPete1** [comment]
`ms-python.python` and `ms-python.vscode-pylance`?

I also have `streetsidesoftware.code-spell-checker`, I'm not sure if that says more about my level of spelling or the effectiveness of the extension....

**Comment by hendjoshsr71** [comment]
I will separate this out with my full list and those I think are super useful,

We should eventually add some notes on why the extension is useful if not obvious somewhere else. 

Use all the time,

Git History : [Link](https://marketplace.visualstudio.com/items?itemName=donjayamanne.githistory)
Allows you to view a file's GIT history or right click individual lines to get the git blame history.  By then copying and pasting the SHA1 into the search bar into github.com/ardupilot  you can find the relevant issue and discussion.

2. Astyle (I'm not sure how well this works.) [Link](https://marketplace.visualstudio.com/items?itemName=chiehyu.vscode-astyle)

3.  Code Spell Checker as well
4. python and pylance as well

I have it download and sometimes remember to call it, but I usually use command line.
5. ardupilot-devenv 
6. GitHub is decent as you can see comments from PRs on it but I forget to use it. 

I imagine @bugobliterator & @davidbuzz  have opinions here as well.

**Comment by TunaLobster** [comment]
I use that for spell checking too. Added the setting to make the language GB English for the workspace. I use a 3rd party Grammarly extension in my wiki workspace.

Added Python and PyLance. There are several git extensions that can be helpful for different people. I jump around between them trying different things. I usually end up back in the terminal for git things.

I am also not sure about the astyle extensions. I know we don't usually mess with legacy formatting unless there are code changes in the area to preserve history. One other thing along the formatting lines are the VSCode snippets. Which is auto-completion for commonly used code blocks.

**Comment by hendjoshsr71** [comment]
> I use that for spell checking too. Added the setting to make the language GB English for the workspace. I use a 3rd party Grammarly extension in my wiki workspace.
> 
What about Aussie english ;) ??

> I am also not sure about the astyle extensions. I know we don't usually mess with legacy formatting unless there are code changes in the area to preserve history. One other thing along the formatting lines are the VSCode snippets. Which is auto-completion for commonly used code blocks.

Astyle is on the wiki here I'm just not sure the extensions actually works.... 
[link](https://ardupilot.org/dev/docs/style-guide.html?highlight=astyle)

The GIT blame one is extremely useful to figure out why or how something was done before. 

I think some sort of GIT tool is important because we shouldn't orient our developer tools & wiki to just command line folks. (Or those who beceome converts over time me :)  Though i still like a GUI to view the git history and do an interactive rebase. Normal aerospace, controls, and other less "software" people should have a quick path to get into things without that.

But this can just go into the VSCode Wiki discussion here instead. https://github.com/ArduPilot/ardupilot_wiki/issues/3776

> That extension pack has several things that ArduPilot doesn't use. Trimming it down to just the ones we use (i.e. roll our own "pack") to me seems like the better play.

Is Remote WSL automatically included with a WSL install?  If not that should be here. [link](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl)

**Comment by TunaLobster** [comment]
I can confirm that that that astyle extension works. The astylerc file is not complete though. It does some default styling choices for header files. I'll raise an issue for that. I'm not diving down that path in this PR.

I'm partial to the GitLens extension. [Link](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens)

WSL extension does get installed by default. (at least from my memory) It could also be in a Cygwin environment.

**Comment by hendjoshsr71** [comment]
> I'm partial to the GitLens extension. [Link](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens)
I'll give it a try.  I like that it automatically tells you the PR number. :) And if with every line you know who to complain to ;)

**Comment by IamPete1** [comment]
I have been ignoring my local changes using `git update-index --assume-unchanged .vscode/settings.json` so I don't have to discard every time.

Annoyingly VSCode does not support a default config and then a override in a second file, I did have a search about recently, there has been a open issue for ages.

**Pull request merged**
