### PR TITLE
Copter 3.5 modify SITL default behavior

### PR DESCRIPTION
**Pull request by pmshopUSMC**
SITL does not match what copter is capable of.
The simulator, based on 3.5.4 AC code limits the forward speed to 1000cm/s when using a max lean of 35°.
However, anyone's copter based on 3.5.4 AC code can fly at a forward rate of 1500cm/s when using a max lean of 35°.
I have even recorded 1965cm/s with max lean of 35°
http://www.dronelogbook.com/flightDetailSharing.php?id=0369034C-E268-2841-1F35-3A4542EF3083
tlog is all I have at the moment
In reviewing the tlog, I noted at many times the copter only needed 10° pitch to maintain 1500mc/s or near to.

Version
3.5.4

Platform
[ ] All
[ ] AntennaTracker
[X] Copter
[ ] Plane
[ ] Rover
[ ] Submarine

Airframe type
All

Hardware type
All

Logs
[2017-09-22 15-04-33.zip](https://github.com/ArduPilot/ardupilot/files/1536334/2017-09-22.15-04-33.zip)

### CODE REVIEW

**Comment by khancyr** [comment]
Hello,

Please rebase on master and follow http://ardupilot.org/dev/docs/contributing.html to make a proper PR.

**Comment by pmshopUSMC** [comment]
khancyr,
I have no idea how to do what you ask - rebase on master?
And I have edited the PR

**Comment by magicrub** [comment]
https://www.youtube.com/results?search_query=how+to+do+a+git+rebase&page=&utm_source=opensearch

**Comment by pmshopUSMC** [comment]
I see this will take some commands.
I issued the PR on a work computer that will not allow the install of unauthorized software.
I will perform the rebase when I get home.
Unless an admin has the power to do so - I really do not want to screw anything up.

**Comment by khancyr** [comment]
your commit is just trying to merge copter 3.5.4 into master ... that bring nothing ... did you forget the SITL changes ?

**Comment by pmshopUSMC** [comment]
What did I forget about the SITL changes?

**Comment by khancyr** [comment]
isn't this PR about to bring better dynamics for SITL copter model ? Where are the changes ? You are just merging copter 3.5 into master, that bring nothing. Put your changes into master branch instead of copter 3.5.

**Comment by pmshopUSMC** [comment]
It is just an enhancement request to change the limitation of SITL max lean angle to make top simulated speed of 2000cm/s possible when angle_max is set to 35°.
When Angle_max is set to 35°, top forward speed in SITL is 1000cm/s
However, when a copter is loaded with the same firmware and same Angle_Max of 35° as the SITL...max forward speed of the copter is up to 2000cm/s.

I do not have any coding knowledge to make these changes mentioned perviously.

**Comment by khancyr** [comment]
Ok then this isn't the good place, enhancement request must be on issue, here is for code modifications submission. 
However, I doubt somebody will do it soon as the current model is enough for most case, and those changes can be complex to be well done.

**Comment by peterbarker** [comment]
On Wed, 6 Dec 2017, pmshopUSMC wrote:

> It is just an enhancement request to change the limitation of SITL max lean
> angle to make top simulated speed of 2000cm/s possible when angle_max is
> set to 35°.
> When Angle_max is set to 35°, top forward speed in SITL is 1000cm/s
> However, when a copter is loaded with the same firmware and same Angle_Max
> of 35° as the SITL...max forward speed of the copter is up to 2000cm/s.

The model in SITL is approximately a 450-size Iris.  Not a speed demon. 
The vehicle's thrust is probably what's limitting you, not the angle max. 
Try graphing the throttle-out and see if it is going to ~80% (some 
throttle left over for stability).  My guess is as you increment angle-max 
you will hit a point where it refuses to push the throttle higher.  You 
can adjust that upper limit, but it won't push your vehicle much faster.

Please note that our SITL isn't really meant to be aerodynamically 
accurate.  It's comically bad in places.  If you want something 
closer-to-truth then you can model vehicles in RealFlight8 quite well and 
fly them with ArduPilot.

Of course, getting someone to pay for RealFlight8 is possibly an 
insurmountable problem.

It would be nice to be able to say why the behaviour has changed between 
3.4 and master - but there's been a lot of change since then!

**Pull request closed without merging**
