### PR TITLE
FIX build in docker for Pixhawk6C

### PR DESCRIPTION
**Pull request by karu2003**
Could not find the program ['arm-none-eabi-ar']
(complete log in /ardupilot/build/config.log)

Path FIX in Docker.

### CODE REVIEW

**Comment by khancyr** [comment]
Hello,

I cannot reproduce the issue. What commands are you running ?

**Comment by karu2003** [comment]
rm -rf ardupilot
docker system prune -a
git clone --recurse-submodules https://github.com/ArduPilot/ardupilot.git
docker build . -t ardupilot
docker run --rm -it -v `pwd`:/ardupilot ardupilot:latest bash -c "./waf configure --board=Pixhawk6C --static && ./waf build"

**Comment by khancyr** [comment]
build fine
```

No APP_DESCRIPTOR found
[1175/1176] apj_gen build/Pixhawk6C/bin/arducopter.bin
[1176/1176] bin cleanup build/Pixhawk6C/bin/arducopter.bin
Waf: Leaving directory `/ardupilot/build/Pixhawk6C'

BUILD SUMMARY
Build directory: /ardupilot/build/Pixhawk6C
Target          Text (B)  Data (B)  BSS (B)  Total Flash Used (B)  Free Flash (B)  External Flash Used (B)
----------------------------------------------------------------------------------------------------------
bin/arducopter   1755412      3736   520692               1759148          206924  Not Applicable
```

notice that the --static is useless on any stm boards

**Comment by khancyr** [comment]
I will close this as the patch isn't good anyway as it will break ccache. Thanks anyway. no idea why it isnt' working for you but it should be

**Pull request closed without merging**
