### PR TITLE
AP_Bootloader: add f4by bootloader

### PR DESCRIPTION
**Pull request by sh83**
This adds bootloader for f4by board.
Also board id reverted back to 20. Currently users have boards with nuttx based fw and bootlooader with id 20. Using the same id simplify updating. Seems no conflict with other boards.
Also it would be great if this board will be added to autobuild.

### CODE REVIEW

**Comment by tridge** [comment]
nuttx based firmware for f4by?

**Comment by auturgy** [comment]
You never merged the pr...

Regards,

James

**Comment by sh83** [comment]
Yes, it has nuttx fw. PR was not accepted in mainstream, so they just compile fw himself.

**Comment by tridge** [comment]
sorry, I should have known that!

**Comment by kozinalexey** [comment]
hi, thank you very much,  I tested the binary files, everything works!

**Comment by mstrinzha** [comment]
These PR's are never submitted into mainstream: https://github.com/ArduPilot/ardupilot/pull/4651 and https://github.com/ArduPilot/PX4Firmware/pull/65

**Comment by tridge** [comment]
ok, I'll fix up the board_types.txt to use 20 ...
we should then add f4by to the autobuild list

**Pull request merged**
