### PR TITLE
Copter: fix condition yaw in automode

### PR DESCRIPTION
**Pull request by khancyr**
Prevent to use the wrong yaw because of the leash
To see the problem, here is a simple mission: the second waypoint is at 90 deg from the first. After reaching the first waypoint, I want to have a relative yaw of -90 deg.
[wp_yaw_fix.txt](https://github.com/ArduPilot/ardupilot/files/2691477/wp_yaw_fix.txt)

With master, we get 
capture d ecran de 2018-12-18 18-09-25
The drone get -90 from the direction between wp 0 to 1. That is because of the leash, when wp 1 is passed the condition yaw is triggered and calculated with the wrong yaw (since we haven't really passed wp1)

With the patch : 
capture d ecran de 2018-12-18 18-10-24
The condition yaw is acheived between wp 1 and 2 as expected !

### CODE REVIEW

**Comment by OXINARF** [comment]
@khancyr Can you explain a bit more what the problem was? I'm failing to see how this is fixing something related to the leash.

**Comment by khancyr** [comment]
@OXINARF Sorry, I write the pr and then was disturb by something else ... I update the first post with picture of the issue and how to trigger it  !

**Comment by rmackay9** [comment]
I'll need to test this I think to be sure..

**Comment by rmackay9** [comment]
sorry, i still haven't reviewed this but I really hope/plan to by next week's call

**Comment by peterbarker** [comment]
Where's the autotest?

**Comment by rmackay9** [comment]
So the issue that this PR tries to address is that if a mission has a CONDITION_YAW with a relative heading, the heading should be relative to the path between the two surrounding waypoints instead of relative to the vehicle's heading at the moment the CONDITION_YAW was run.

I'm actually not sure that this is what the user would expect but more importantly I'm pretty sure this change relies on a race condition when it uses the wp_nav->reached_wp_destination().

When a vehicle reaches a waypoint, the AP_Mission library immediately kicks off the next NAV and DO commands (almost simultaneously).  If the CONDITION_YAW is the very first "DO" command then it seems the next NAV command hasn't fully started yet so **reached_wp_destination()** returns false.  If it's the 2nd DO command though then it returns false.  This means that the user will get different behaviour if they say had a DO_SERVO command right before the CONDITION_YAW command.

The underlying issue is really caused by a fundamental known issue with our navigation controller.  It's the use of the leash (as Pierre says) and this causes other problems as well - most importantly it causes the vehicle to cut corners in missions.  We will eventually rewrite the navigation controller and the problem will go away.  Until then we can try and think of other solutions but I think this solution is fragile.

**Comment by khancyr** [comment]
Close as it would be better to fix the wpnav to handle all message

**Pull request closed without merging**
