### PR TITLE
Copter: upward facing surface tracking and fix rangefinder glitch protection

### PR DESCRIPTION
**Pull request by rmackay9**
This PR adds upward facing surface tracking allowing the vehicle to track the ceiling instead of the floor which can be useful for bridge inspection.  It also resolves some issues with the existing glitch detection which surely couldn't have been working as intended.  The changes include:

- Copter's range finder update rate is increased from 20hz to 50hz
- Copter glitch detection is moved from surface tracking's **adjust_climb_rate()** to sensor.cpp's **read_rangefinder()**.  The existing implementation must have been incorrect because adjust_climb_rate is called from the flight mode code at 400hz which is far faster than read_rangefinder()'s 20hz update rate.  This meant that the glitch counters could not be working as intended because a single glitch (read by read_rangefinder) would persist for 20 iterations of adjust_climb_rate.
- New auxiliary function switch (75:SurfaceTrackingUpDown) allows users to specify whether they wish to track upwards, downwards or not at all.  Defaults to downwards.  Text warnings are sent to the GCS and mode-change-failed tones are played if the switch selection fails.
- Surface tracking is enhanced to work with upward facing range finder

Some other minor changes:
- Surface tracking is moved from Attitude.cpp to a new surface_tracking.cpp (NFC)
- CTUN logging is changed so the "DSAlt" (desired sonar alt) and "SAlt" (sonar alt) show the desired/actual distance instead of just the desired/actual sonar based altitude.  the format for the SAlt was changed from an int-in-cm to a float-in-meters.  This consumes an extra 2 bytes of log space but removes some mixing of cm and m.

This has been tested in SITL but the following tests will also be completed before merging:

- [ ] Test that the EKF can accept rangefinder data at 50hz
- [x] Flight test both upward and downward surface tracking -- done!

### CODE REVIEW

**Comment by amilcarlucas** [comment]
Any progress on the field tests ?

**Comment by rmackay9** [comment]
@amilcarlucas, we did a test yesterday but it was only a partial success.  The vehicle did hold height below a ceiling correctly but the glitch protection didn't seem to be working because sudden changes in altitude would cause the vehicle to descend when instead they should just be ignored.

**Comment by rmackay9** [comment]
OK, I think I've found and fixed the typo that caused problems during testing yesterday.

**Comment by rmackay9** [comment]
I've rebased this on master and resolved a harmless merge conflict.

**Comment by rmackay9** [comment]
We've successfully tested this on a real vehicle now.  I'm keen for any feedback but failing that I'll just merge it in the next day or two.

**Comment by rmackay9** [comment]
This has been successfully flight tested now.  The last thing we need to check is that the EKF is happy if we send range finder data at 50hz.

**Comment by rmackay9** [comment]
upwards and downwards surface tracking have been successfully tested on real vehicles and the range finder update rate has been restored to 20hz to avoid issues with the EKF not being able to accept the higher rate.

**Pull request merged**
