### PR TITLE
Rover: add Simple mode

### PR DESCRIPTION
**Pull request by Ammarf**
This PR adds Simple mode to Rover/Boat. 

The mode will have 2 behaviors, initial heading and cardinal directions (feedback on the naming is more than welcome). The SIMPLE_TYPE parameter is set by default to "Initial Heading" but you can choose "Cardinal Directions" by setting it to 1.

Setting it to "Initial Heading" will allow you to steer the vehicle towards the position the vehicle was facing when it was armed by pulling the throttle stick forward (no steering input), but otherwise you'll be able to steer the vehicle normally. I tested this one and it works fine.

Setting it to "Cardinal Directions" will allow you to control the vehicle's heading relative to cardinal directions by using the angle of the transmitter's stick as the desired heading, so pulling the stick forward will set the heading to north, and pulling it to the right (0 throttle, max positive steering) will set the heading to east and so on. The magnitude of the vector the transmitter stick makes is used as the desired speed. A few things to point out about this submode:

1- If you set the heading to south, the vehicle will turn around to face south, which means the vehicle won't be able to reverse in this submode. 
2- If your vehicle is facing north and you set the heading to say a 170 degrees, the vehicle turns clockwise to face the desired heading. If it's facing north and you set the heading to 190 degrees (or -170 degrees). the vehicle will turn counterclockwise until it faces the desired heading. However, this means that if you go from 170 degrees to 190 degrees, the steering output will jump from maximum positive output to maximum negative output (the vehicle will turn 340 degrees in the wrong direction until it reaches 190). 
3- I could only achieve stable results when "I" and "D" in the steer rate PID were set to 0  or really small values.

This is a quick test I did a while ago ([video](https://youtu.be/jdwhbTeMf9A)).

### CODE REVIEW

**Comment by rmackay9** [comment]
Ah, this will also need to be rebased because I'm afraid I just merged a change from PeterB that stole the auxiliary switch enum this PR uses.

**Comment by Ammarf** [comment]
I needed to set the "apply_scaling" in set_steering() to false which is why I'm just directly using the heading controller in mode_simple.cpp. I could have calc_steering_to_heading() check for lateral control ability if that is better.

**Comment by rmackay9** [comment]
@Ammarf, I don't really understand why apply-scaling and lateral control is important but you've looked at this a lot more than I have...  I really think though that calc_steering_to_heading() should be used.

**Comment by Ammarf** [comment]
I moved init_simple_heading() to mode_simple.cpp, I also removed the sin_yaw stuff. I did a few more tests on the calc_steering_to_heading() issue, seems like the issue only occurs when I try it out on a testing bench (ground_speed would be something like -0.00xx causing the steering to be negative when it shouldn't be), anyways I removed the turn rate controller.

**Comment by rmackay9** [comment]
@Ammarf, I tested this in SITL but still doesn't seem right.. it's probably because ModeSimple::update() is still using set_steering() instead of calling calc_steering_to_heading()...

**Comment by peterbarker** [comment]
On Fri, 17 Aug 2018, Randy Mackay wrote:

> @Ammarf, I tested this in SITL but still doesn't seem right.. it's
> probably because ModeSimple::update() is still using set_steering()
> instead of calling calc_steering_to_heading()...

Is there anything in autotest for this new feature?

**Comment by Ammarf** [comment]
I rebased and changed the initial_heading submode to have it use calc_steering_to_heading() instead of set_steering().

**Comment by rmackay9** [comment]
I've tested this and found a fair number of issues actually.  I'm closing this and I've raised [another PR](https://github.com/ArduPilot/ardupilot/pull/9395) which includes fixes to this PR.

**Pull request closed without merging**
