### PR TITLE
Plane: Added Y4 config name to Q_Frame_Type Quadplane

### PR DESCRIPTION
**Pull request by jmoros08**
Added Y4 config to Quadplane Q_frame_type, already supported in AP_MotorsMatrix

### CODE REVIEW

**Comment by tridge** [comment]
thanks!
If you can, the commit message should start with "Plane: "
if you don't know how to do this I can do it for you

**Comment by jmoros08** [comment]
Thanks Tridge, done!

**Comment by tridge** [comment]
> Thanks Tridge, done!

sorry, I should have been clearer, it is the commit, not the PR title (ie. the permanent record, not the PR)
easiest method is "git commit --amend"

**Comment by jmoros08** [comment]
Will open a new pull request

**Pull request closed without merging**
