### PR TITLE
PX4: removed attempt at formatting microSD

### PR DESCRIPTION
**Pull request by tridge**
this never worked, and its a bad idea anyway

### CODE REVIEW

**Comment by magicrub** [comment]
what didn't work about it?

**Comment by tridge** [comment]
the format never succeeded (bugs in the format command in nuttx)
It also seems like a bad idea. If you get a glitch on the SD while booting you lose all your logs

**Comment by WickedShell** [comment]
+1 I actually really don't like the idea of the autopilot deciding to reformat my SD card. I might have other essential data on their/old logs.

I definitely don't mind a MAVLink command that would allow us to choose to reformat at runtime though, that could be convenient, but definitely isn't essential (and if it's going to randomly fail then thats even worse).

**Comment by peterbarker** [comment]
Looks good to me.  Merged!

**Comment by ranqingfa** [comment]
@WickedShell  Good idea! I also think its great if we could format microsd in GCS!

**Comment by ranqingfa** [comment]
I want to add this fuction, but didnot find the code of formating sdcard in NuttX.

**Pull request merged**
