### PR TITLE
Copter: get mav heartbeats out when board detection fails

### PR DESCRIPTION
**Pull request by peterbarker**
@rmackay9 @OXINARF please consider for 3.5

### CODE REVIEW

**Comment by peterbarker** [comment]
There is the question as to whether we should be looking at in_mavlink_delay, but the nullptr check is good and fixes *my* problem :-)

**Comment by OXINARF** [comment]
How does this fix the problem? It checks if the motors class exists, which it wouldn't only when the FRAME_CLASS parameter hasn't been set. How does that fix the board type not being detected?

This still is a worthwhile fix, although I would prefer to keep the time check at the beginning.

**Comment by rmackay9** [comment]
It's hard to imagine this is a dangerous change so I vote for it going in.

**Comment by peterbarker** [comment]
The motors object is created (https://github.com/ArduPilot/ardupilot/blob/master/ArduCopter/system.cpp#L185) after board detection (https://github.com/ArduPilot/ardupilot/blob/master/ArduCopter/system.cpp#L129)

If board detection fails we end up in a loop (https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_BoardConfig/px4_drivers.cpp#L517).  Because we call delay() in that loop, the in_mavlink_delay callback gets called.

On Rover and Copter we check in_mavlink_delay, and that's sufficient to bypass the time-remaining check.

On Copter we don't look at that.  As mentioned, we probably should, but at this point my reading of the code is that motors is probably nullptr at this time.  Just ran it under gdb, and that's confirmed.

OTOH, I also dug this gem up in gdb while running `copter.scheduler.time_available_usec()`:

```
/home/build/work/GCC-4-9-build/src/gdb/gdb/infrun.c:6229: internal-error: normal
_stop: Assertion `get_frame_type (frame) == DUMMY_FRAME' failed.
```
... and gdb crashed.  I put the check for nullptr first because I figure we're already in uncharted territory at this point - we're not really initialised, but we're covering a lot of code with this mavlink stuff!  Minimising the code we cross would seem to be a Good Idea.



So... I reckon the null-pointer checks works for now, huh? :-)

**Comment by rmackay9** [comment]
@OXINARF is asleep at this precise moment but I suspect he's a-ok with this so merged!

**Pull request merged**
