### PR TITLE
NavEKF: account for autopilot-to-body rotation in getQuaternion

### PR DESCRIPTION
**Pull request by kd0aij**
method description:: "return the quaternions defining the rotation from NED to XYZ (body) axes", but did not account for rotation from autopilot to vehicle body frame
Fixes failure to arm (attitudes_inconsistent) when AHRS_TRIM is larger than threshold: see #10836

### CODE REVIEW

**Comment by kd0aij** [comment]
except for logging, getQuaternion is called only by AP_AHRS_NavEKF::get_secondary_quaternion() 
and AP_AHRS_NavEKF::attitudes_consistent()

get_secondary_quaternion is only used for logging
 and attitudes_consistent is called only by AP_Arming::ins_checks

**Comment by tridge** [comment]
this changes the logged quaternion for the EKF, so I think we should ask @priseborough to check its OK

**Comment by kd0aij** [comment]
@priseborough Then the method description appears not to match its function
"// return the quaternions defining the rotation from NED to XYZ (body) axes"
Or is this "body" frame  different from the vehicle body frame?

**Comment by priseborough** [comment]
Unfortunately the we did not make a distinction between autopilot and body frames of reference at the start. The use of 'body' and 'earth' frame was the naming convention adopted when the nav equations were derived, however when this was integrated into the vehicle code, it was not the same 'body' frame that the control loops use.

For user facing documentation, it would be better to use 'autopilot' instead of body to avoid confusion when describing internal EKF data.

The documentation is unclear on the effect in how AHRS_TRIM. For example when installing an external magnetometer, it should it be aligned to the frame of reference before the AHRS_TRIM rotation.

Also the AHRS_TRIK documentation says that the Z component is un-used, whereas all three components are used by the EKF when it outputs the euler angles used by the controllers.

Then there is the use of TRIM_PITCH_CD.

**Comment by kd0aij** [comment]
Thanks for the clarification; that makes sense now. 
FYI, In working on https://github.com/ArduPilot/ardupilot/pull/10985 I noticed that AP_AHRS_DCM maintains both _dcm_matrix and _body_dcm_matrix, and they are described as "attitude of board" and "attitude of flight vehicle body" in the header file. 
But in AP_AHRS_NavEKF, _dcm_matrix is the rotation from vehicle body to NED frame, so I added a comment stating that in the header file.

**Pull request closed without merging**
