### PR TITLE
Plane: added fixed wing tilt vectoring for tilt quadplanes

### PR DESCRIPTION
**Pull request by tridge**
This adds Q_TILT_FIX_ANGLE and Q_TILT_FIX_GAIN for control of tilt vectoring in tilt vectored quadplanes. This is based on the feature developed by @kris000 
The tilt is scaled inversely with throttle and also inversely with the fixed wing speed scaler to remove the impact of surface speed scaling from the plane roll/pitch controllers

### CODE REVIEW

**Comment by IamPete1** [comment]
would be nice to bring this up a level and apply to tailsitters too and remove `Q_TAILSIT_VFGAIN` this is certainty a better implementation that that is currently.

**Comment by kris000** [comment]
Testing is normal!
https://youtu.be/RI_kEBEjpis

**Review by kris000 — APPROVED** [review]

**Comment by tridge** [comment]
> would be nice to bring this up a level and apply to tailsitters too and remove `Q_TAILSIT_VFGAIN` this is certainty a better implementation that that is currently.

I've added the same scaling function for Q_TAILSIT_VFGAIN. We can't share the code completely as tilt rotors center about a tilt of 1, whereas tailsitters center about a zero tilt, and use different ways to specify the angle range.

**Review by IamPete1 — APPROVED** [review]
LGTM - but not tested myself

**Pull request merged**
