### PR TITLE
Logging: log used IMU,compass/Mag

### PR DESCRIPTION
**Pull request by ashvath100**
Added some extra columns to the NKF4 (1st EKF lane) ,NKF9 (2nd EKF lane) and NKF14 (3rd EKF lane)messages.
PE : primary EKF lane (renamed current "PI" to "PE")
UI : used IMU instance
UM : used compass/mag instance

### CODE REVIEW

**Comment by peterbarker** [comment]
@ashvath100 I'd like to move to having an instance number in these packets - you'll have noticed the pointless repetition when doing this patch.

Unfortunately, moving to 16 fields by adding these precludes having an instance number.

Is it OK if we hold off on logging this data until we sort instance fields out?  We may need another message to hold things like primary-EKF-core which is NOT a per-core thing.

**Comment by peterbarker** [comment]
@ashvath100 PR for using instance numbers for these messages is here: https://github.com/ArduPilot/ardupilot/pull/12997

Is it just me or should we really move the primary-core to `NKF5` and `XKF5`?  At the moment we're storing a copy-per-core, which is rather odd.

In terms of columns - looks like we already log the compass used into `NKF2.index`.

**Comment by ashvath100** [comment]
@peterbarker it did seem repetitive ,I made this PR considering  #12188 . Moving primary-core index to NKF5 and XKF5 does seem to be an appropriate thing to do.

**Comment by peterbarker** [comment]
This was naturally done as a GSoC project; we have an XKFS (sensor logging) message.

We do appear to have `NKF5.MI` - magnetometer used for EKF2.

We do not seem to log either of `accel_active` or `gyro_active` for the cores, which is odd.

@ashvath100 did you still want to pursue this?

**Pull request closed without merging**
