### PR TITLE
Copter: send mission_item_reached in guided

### LINKED ISSUE #16806: Copter/Sub/Plane/Rover: should we send message_item_reached message in Guided?
PR https://github.com/ArduPilot/ardupilot/pull/16796 brought to light the small issue that our vehicles are inconsistent in whether they send message_item_reached messages when they reach a Guided mode target.  Copter and Sub do not.  Plane and Rover do.

This question was raised by @jmachuca77

### PR DESCRIPTION
**Pull request by chobitsfan**
fix #16806, most code copied from #16796 (thanks @rmackay9)

tested on mro pixracer pro, indoor with motion capture system

### CODE REVIEW

**Review by khancyr — APPROVED** [review]
That seems good.

**Comment by amilcarlucas** [comment]
A bit of a scope creep, but can you add it to the sub as well?

**Comment by chobitsfan** [comment]
Hi @amilcarlucas Sure. I can do it. But I do not have sub hardware. So I can only test it in SITL

**Comment by rmackay9** [comment]
Merged, thanks!

**Pull request merged**
