### PR TITLE
Move handling of incoming statutext messages up

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by WickedShell** [comment]
Consistency is good,  I have no objection to whats shown, but did you consider translating the parameters into a common struct in AP_Vehicle? (Or better yet shifting it into a GCS_MAVLink parameter?) It's definitely better then it was, but is still a bit of a weird tie in/dependency for something that is clearly just a GCS_Mavlink concept and doesn't actually vary in the vehicles at all.

**Comment by peterbarker** [comment]
@WickedShell Actually, yes I did think about that!

I considered making it a parameter on GCS_MAVLINK - but discarded that as having a `SYSID_MY_GCS` per mavlink connection would blow people's minds....

At the moment we don't have a parameters object for the GCS singleton; perhaps into the future we might, but I think that would overly-complicate things at the moment!

**Comment by WickedShell** [comment]
I think it'd be great! But yes, doesn't need to happen now :)

**Comment by OXINARF** [comment]
Merged, thanks!

**Pull request merged**
