### PR TITLE
Copter: add exit() method to Mode class (NFC)

### LINKED ISSUE #14689: Copter: add exit() method to Mode class
Copter's mode class ([see code here](https://github.com/ArduPilot/ardupilot/blob/master/ArduCopter/mode.h#L49)) has an init() and run() function but is missing the exit().

We probably cannot completely remove the contents of the [Mode::exit_mode() function](https://github.com/ArduPilot/ardupilot/blob/master/ArduCopter/mode.cpp#L316) but we can probably move more than half to reside in each mode.

This should be a non-functional change so while relatively easy to implement make sure you test it!  Remember to check that any change in order of execution has no negative impacts.

### PR DESCRIPTION
**Pull request by tatsuy**
fixes #14689

There are some changes in order of execution.
So I'm going to check these to make sure there are no negative impacts.

- [x] confirm to call exit() of each flightmode
- [x] SmartRTL
- [x] Follow
- [x] Zigzag
- [x] Acro
- [x] Auto
- [x] AutoTune
- [x] set_accel_throttle_I_from_pilot_throttle
- [x] Takeoff_stop

### CODE REVIEW

**Comment by rmackay9** [comment]
Looks good, thanks!

**Comment by muramura** [comment]
Old flight mode exit, next old flight mode takeoff ok?

**Comment by tatsuy** [comment]
Thanks, I moved exit() after takeoff_stop().
As a result, only Auto and AutoTune are reordered.
I have confirmed that changing these has no negative impact.

**Comment by rmackay9** [comment]
Merged, thanks!

**Pull request merged**
