### PR TITLE
autotest: 4.4 Backport of a variety of backports to stabilize CI

### PR DESCRIPTION
**Pull request by magicrub**
A variety of CI backports to Plane-4.4. We may want to reduce this list but these all look juicy and help stabilize CI in different ways. Only autotest python files are changed except the balanceBot one which needed a SITL change. Most of these are commits from @peterbarker .

- WindEstimate from PR https://github.com/ArduPilot/ardupilot/pull/24666
- Sprayer from PR https://github.com/ArduPilot/ardupilot/pull/23823
- Deepstall from 2 PRs https://github.com/ArduPilot/ardupilot/pull/23524 and https://github.com/ArduPilot/ardupilot/pull/24667
- Rover timeout PR https://github.com/ArduPilot/ardupilot/pull/23442
- BalanceBot from PRs https://github.com/ArduPilot/ardupilot/pull/24314 and https://github.com/ArduPilot/ardupilot/pull/25046
- "autotest: correct implicit reboot after a failed test" from PR https://github.com/ArduPilot/ardupilot/pull/23422
- autotest: exempt sailboats from initial location  - PR https://github.com/ArduPilot/ardupilot/pull/23453
- gyro inconsistient - PR https://github.com/ArduPilot/ardupilot/pull/23518
- autotest: stop vehicle from entering RTL instantly when it enter - PR https://github.com/ArduPilot/ardupilot/pull/23678
- autotest: poll ftp status at interval - PR https://github.com/ArduPilot/ardupilot/pull/23931
- autotest: timesync roundtrip after setting parameter - PR https://github.com/ArduPilot/ardupilot/pull/23961
- autotest: care not which CAN GPS is unhealthy when in maintenance mode - PR https://github.com/ArduPilot/ardupilot/pull/23984
- autotest: remove binary before attempting to build it - PR https://github.com/ArduPilot/ardupilot/pull/24236
- autotest: tweak plan GCS failsafe test - PR https://github.com/ArduPilot/ardupilot/pull/24420
- autotest: remove copter wait_for_alt - PR https://github.com/ArduPilot/ardupilot/pull/24503
- autotest: disarm vehicle in exception handle for PrecLand test - PR https://github.com/ArduPilot/ardupilot/pull/24582
- autotest: remove generation of defaults files - PR https://github.com/ArduPilot/ardupilot/pull/24781
- autotest: fix flapping Rally test - PR https://github.com/ArduPilot/ardupilot/pull/24806
- autotest: tweak Soaring test - PR https://github.com/ArduPilot/ardupilot/pull/24921
- autotest: loosen constrain on proximity distance message - PR https://github.com/ArduPilot/ardupilot/pull/24956
- Improve autotest mavlink connection resiliency - PR https://github.com/ArduPilot/ardupilot/pull/23930
- autotest: set ICE_RPM_THRESH for quadplance-ice - PR https://github.com/ArduPilot/ardupilot/pull/24765
- many other misc improvements that looked good that I clumped in at the end and extend thresholds

### CODE REVIEW

**Comment by magicrub** [comment]
this passed CI on the "first try" :)

**Comment by magicrub** [comment]
I'm still occasionally seeing these tests fail CI on my Plane 4.4.1 branch that I'm doing flight testing with. I have custom code going, including scripts, so I'll need to rule those out.. but the DynamicNotches are definity troublesome.

**Copter.tests2b**
- "DynamicNotches (Use dynamic harmonic notch to control motor noise.)": NotAchievedException('Triple-notch peak was higher than single-notch peak -24.506024dB > -26.753855dB')
- "DynamicNotches (Use dynamic harmonic notch to control motor noise.)": NotAchievedException('Double-notch peak was higher than single-notch peak -24.548567dB > -27.309522dB')
- "DynamicRpmNotches (Use dynamic harmonic notch to control motor noise via ESC telemetry.)": NotAchievedException('Notch-per-motor peak was higher than single-notch peak -22.550128dB > -24.496709dB')
- "Replay (test replay correctness)": NotAchievedException('check_replay failed')
-  "ScriptMountPOI (test the MountPOI example script)": AutoTestTimeoutException('Prearm bit never went true')


**Rover.Scripting (test_scripting_print_home_and_origin)**
- "Scripting (Scripting test)": AutoTestTimeoutException('Prearm bit never went true')


**Rover.ScriptingSteeringAndThrottle**
-  "ScriptingSteeringAndThrottle (Scripting test - steering and throttle)": AutoTestTimeoutException('Prearm bit never went true')

**Comment by magicrub** [comment]
@rmackay9 @peterbarker  test Copter.tests2b needs to get split up. It's huge.

**Comment by magicrub** [comment]
For the record, those still-flapping tests I believe are all still flapping on master

**Review by khancyr — APPROVED** [review]
LGTM

Only CI is touched (beside sitl balanced bot), so if the tests pass, we are fine

**Comment by peterbarker** [comment]
> I'm still occasionally seeing these tests fail CI on my Plane 4.4.1 branch that I'm doing flight testing with.
> 
> **CopterTests2b**
> 
>     * "DynamicNotches (Use dynamic harmonic notch to control motor noise.)": NotAchievedException('Triple-notch peak was higher than single-notch peak -24.506024dB > -26.753855dB')
> 
>     * "DynamicNotches (Use dynamic harmonic notch to control motor noise.)": NotAchievedException('Double-notch peak was higher than single-notch peak -24.548567dB > -27.309522dB')
> 
>     * "DynamicRpmNotches (Use dynamic harmonic notch to control motor noise via ESC telemetry.)": NotAchievedException('Notch-per-motor peak was higher than single-notch peak -22.550128dB > -24.496709dB')
> 
>     * "Replay (test replay correctness)": NotAchievedException('check_replay failed')

Yep, those all look very familiar!

**Comment by peterbarker** [comment]
> @rmackay9 @peterbarker test Copter.tests2b needs to get split up. It's huge.

You create, I'll approve and merge :-)

**Comment by magicrub** [comment]
@tridge is merge manager for the release branches so we need his thumbs up at some point. This could also get slapped into the copter branch

**Comment by magicrub** [comment]
some of these were merged into Plane 4.4.2 but not all. I guess that's that for this PR.

**Pull request closed without merging**
