### PR TITLE
Copter: GCS notification if ekf2 and ekf3 are selected

### PR DESCRIPTION
**Pull request by muramura**
I read Randy's comment.
I am more likely to recognize a misconfiguration by notifying me via message.

AFTER:
Screenshot from 2021-01-23 06-57-36

Randy commens:
It is best not to enable both EKF2 and EKF3 at the same time because it could overload the CPU on some autopilots. It is unlikely to crash but it may fly badly.

https://discuss.ardupilot.org/t/ardupilot-latest-switched-to-use-ekf3-by-default/66334

### CODE REVIEW

**Comment by rmackay9** [comment]
Thanks for this.  Normally we would use a pre-arm check though to warn users of an issue instead of repeatedly sending a text message to the console.

I think it's unlikely though that either this change or a pre-arm check will be merged though because there are valid cases where the user might want both running.  Also some autopilots (like CubeOrange, Holybro Durandal, etc) have the CPU power to run both without any problem.

**Comment by muramura** [comment]
@rmackay9 san. Comments thanks.
I output a message with a pre-arm check.

**Comment by muramura** [comment]
I decided to use the pre-arm to determine the effective settings of EKF2 and EKF3.
I decided to go with the faster clock, FMUV6, as OK.

Screenshot from 2021-01-23 16-58-31

**Comment by peterbarker** [comment]
I really don't like this change.

There are going to be a lot of users who are deliberately and happily running both EKFs, possibly on customer vehicles, and they don't want big red warning messages flashing up when there's nothing technically wrong with it.

If we're worried about CPU usage then we should be monitoring CPU usage, *not* checking for these possible-problems.

**Comment by rmackay9** [comment]
Yes, I agree so closing.  Thanks anyway!

**Pull request closed without merging**
