### PR TITLE
updated CAN parameters to have the correct options

### PR DESCRIPTION
**Pull request by proficnc**

### CODE REVIEW

**Comment by OXINARF** [comment]
I see no use in code for value 3, where is it coming from?

Also the commit message needs to be _AP_BoardConfig: update CAN parameters to have the correct options_

**Comment by proficnc** [comment]
3 sets motors to CAN mode.

**Comment by OXINARF** [comment]
From code, setting it to 2 or 3 does exactly the same. So either there is something wrong in code or that documentation is wrong.

**Comment by proficnc** [comment]
CAN 3 sets addressing mode.

**Comment by magicrub** [comment]
@proficnc please point to the code that takes advantage of 3 and 4. It appears to not be supported in master.

**Comment by gmorph** [comment]
Any update on this or can we close it out?

**Comment by OXINARF** [comment]
#5096 should be merged instead but it needs a squash. Closing this one and tracking there.

**Pull request closed without merging**
