### PR TITLE
Tools: Update SV2450 default.parm file for AC-3.6

### PR DESCRIPTION
**Pull request by lordneeko**
Update default parameters for Skyviper 2450 GPS battery failsafes, changed in AC-3.6

### CODE REVIEW

**Comment by khancyr** [comment]
@rmackay9 @tridge, simple fix

**Comment by rmackay9** [comment]
Thanks for this.  I think maybe we should be using the "LOW" values instead of "CRT"?  In my view there are two levels and the LOW is the one we setup by default... at least this is how I documented it on the wiki.  Of course functionally it's the same but the mission planner for example also sets the LOW values (not the CRT values).

**Comment by rmackay9** [comment]
@lordneeko, it could be done that way but it's not consistent with how we've setup the mission planner.  The LOW_ level has replaced the single level we had before and the CRT level is the new level.  My guess as to how it should be used is LOW is setup to RTL and then when the battery gets really really low the CRT kicks in and lands the vehicle before it just falls out of the sky.

**Comment by rmackay9** [comment]
Merged, thanks!

**Pull request closed without merging**
