### PR TITLE
AP_NavEKF_Source: set compass_required if we require a compass

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Review by rmackay9 — CHANGES_REQUESTED** [review]
If we add this then I think we should also default the EK3_SRC1/3/YAW to 0:None in AP_NavEKF_Source.

This will make it slightly easier for users to disable their compass because they won't then need to go in and set all three source sets yaw parameters to zero, they can simply set the first one.

**Comment by peterbarker** [comment]
I wonder if we should add a mask for which source sets can be used.  So if you wanted to be able to switch between different sensor sets you'd have to mask them in.

**Comment by rmackay9** [comment]
@peterbarker, re adding a mask parameter, maybe but I think we should wait until someone asks for it or we are more sure that it is a real issue.  In my tests at least I haven't seen issues when switching to sources set as None beyond the expected EKF failsafe that triggers a land.

**Comment by peterbarker** [comment]
I've added the patch discussed at the DevCall today.  Starting SITL with `-w`:

```
STABILIZE> EK3_SRC1_POSXY   3.000000
EK3_SRC1_POSZ    1.000000
EK3_SRC1_VELXY   3.000000
EK3_SRC1_VELZ    3.000000
EK3_SRC1_YAW     1.000000
EK3_SRC2_POSXY   0.000000
EK3_SRC2_POSZ    0.000000
EK3_SRC2_VELXY   0.000000
EK3_SRC2_VELZ    0.000000
EK3_SRC2_YAW     0.000000
EK3_SRC3_POSXY   0.000000
EK3_SRC3_POSZ    0.000000
EK3_SRC3_VELXY   0.000000
EK3_SRC3_VELZ    0.000000
EK3_SRC3_YAW     0.000000
EK3_SRC_OPTIONS  1.000000
```

**Comment by rmackay9** [comment]
Great, thanks.  I suspect it's failing the new autotest for source switching.  We probably just need to add changes so the autotest sets the EK3_SRC2_YAW =1 and _POSZ = 1

**Comment by peterbarker** [comment]
@rmackay9 I'm afraid the patch required was a touch more intrusive.

The arming checks were adamant that you `NONE` was not a valid source for PosZ.  I've relaxed that here.

**Comment by rmackay9** [comment]
@peterbarker,

or maybe we should leave the default there for POSZ and just change the default for compass.

**Comment by peterbarker** [comment]
@rmackay9 done - just removed the yaw one

**Review by rmackay9 — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
