### PR TITLE
CI: disable clang build for chibios as broken

### PR DESCRIPTION
**Pull request by peterbarker**
Extracted from https://github.com/ArduPilot/ardupilot/pull/18542

### CODE REVIEW

**Comment by peterbarker** [comment]
@khancyr why wasn't this broken before?

**Comment by davidbuzz** [comment]
lgtm

**Comment by khancyr** [comment]
@peterbarker as we unset cc variable, waf don't find clang and use the default compiler

**Comment by peterbarker** [comment]
@khancyr merged this

**Pull request merged**
