### PR TITLE
AP_RangeFinder: Set the I2C address with the config parameter

### PR DESCRIPTION
**Pull request by muramura**
This device can change the address of I2C. Therefore, I change it so that it can be set with the config parameter.

setAddress method Set New I2C Address:
https://github.com/pololu/vl53l0x-arduino/blob/master/VL53L0X.cpp

### CODE REVIEW

**Comment by rmackay9** [comment]
This is a good idea.. we just need to be sure that the defaults are set properly so that every user doesn't need to go in and configure that _ADDR parameter.

**Comment by muramura** [comment]
@rmackay9 san.. Comments thanks.
I learned that 0x00 can not be assigned as an individual address in the I2C address.
I specify the default address if the I2C address of the configuration parameter is 0x00.
How is that?

I2C SPEC
https://www.i2c-bus.org/addressing/

**Comment by OXINARF** [comment]
How would this be used given that the new address has to be written on every boot?

**Comment by OXINARF** [comment]
@muramura As far as I know, the new address isn't saved, you have to set it on every boot. And that's going to be hard to do unless you initialize the VL53L0X separately and before the autopilot.

**Comment by OXINARF** [comment]
@muramura @rmackay9 Any further comments?

**Comment by peterbarker** [comment]
@OXINARF 's question hasn't been answered in a couple of years - and he seems to have raised a bit of a flaw.

Please re-open if you think of a way forward with this.

**Pull request closed without merging**
