### PR TITLE
Added logging of RC protocol bytes

### PR DESCRIPTION
**Pull request by andyp1per**
Based on https://github.com/ArduPilot/ardupilot/pull/13835

Requires ```RC_OPTIONS=16```

@tridge this told me what I need to know. I've cleaned up and squashed.

### CODE REVIEW

**Comment by andyp1per** [comment]
Added a script to decode the messages

**Comment by tridge** [comment]
@andyp1per ahh, sorry Andy, I did a decoder already which includes playback to a serial port, I just forgot to add it in this PR
Also Peter suggested we should use the char64 format. I'll fix the PR to use that

**Comment by andyp1per** [comment]
Hey @tridge no worries. i couldn't get the DFReader to work with char64 so gave up. It's getting the right change that is important! What about the Debug driver stuff I did? Does that work?

**Comment by tridge** [comment]
the problem with the debug backend is it loses the timing. I made the log_data() call for SRXL log before the CRC check in the hope it would be useful for you.
Do you have any frames captured yet for your SRXL data?

**Comment by andyp1per** [comment]
@tridge there is some data (here)[https://github.com/ArduPilot/ardupilot/pull/13835#issuecomment-601439825] that I captured using the debug back-end. The basic problem is that SRXL2 is totally different to the other SRXL's that we support including the header byte which is 0xA6. I think the correct thing to do here is integrate Horizon's open source library - I'll have a go at that in the next few days.

**Pull request closed without merging**
