### PR TITLE
AP_Airspeed library standalone from APM:Plane

### PR DESCRIPTION
**Pull request by AndersonRayner**
This series of commits makes the AP_Airspeed library standalone from the APM:Plane library.  Currently the airspeed sensor can't be used on Copter (even for logging purposes) due to the reliance on _airspeed_min_ and _airspeed_max_ which are part of AP_Vehicle::Plane.  This moves _airspeed_min_ and _airspeed_max_ to the AP_Airspeed library and updates all the references.

Updating will (most likely) require users to reset _ARSPD_MIN_ and _ARSPD_MAX_ to their previous _ARSPD_FBW_MIN_ and _ARSPD_FBW_MAX_ values.

### CODE REVIEW

**Comment by AndersonRayner** [comment]
Missed some stuff as picked up in the auto-checks.  Will update

**Comment by magicrub** [comment]
I like the idea but it may be misleading because the aircraft can operate
without an airspeed sensor. However, the param alone would make sense to be
named through it. Also, there is a way to forward the old param value to
the new one automatically.

**Comment by AndersonRayner** [comment]
Missed some stuff as picked up in the auto-checks.  Will update

**Comment by AndersonRayner** [comment]
@magicrub Thanks for the input.  Any suggestions as how to make it less misleading for users?  Also, how do you forward the param through the to new one?  I'll add that while I'm at it.

Basically I removed AP_Airspeed's dependance on APM:Plane as I'm hoping to log airspeed data on a quad.  The auto-checks failed for a build I didn't test (oops) so I'll hopefully get to fixing that one tonight.

**Comment by magicrub** [comment]
See the bottom of parameter. Cpp or hpp.

**Comment by tridge** [comment]
I don't mind moving the parameters, but as Tom says, we do need to do auto-upgrade.
See:
https://github.com/ArduPilot/ardupilot/blob/master/ArduPlane/Parameters.cpp#L1360

**Comment by tridge** [comment]
I'd also like the values to be accessed via functions, so airspeed.get_airspeed_min() not directly.

**Comment by magicrub** [comment]
Thanks @tridge . I didn't notice that the param is public and used everywhere. I need to stop reviewing code on my cell phone! Definitely need an accessor there like what Tridge said. Also, this may be a good opportunity to rename the param to "ARSPD_MIN" and "ARSPD_MAX" for simplicity. Would also love to change the units on it to a float in m/s but that gets a little more complicated.

**Comment by AndersonRayner** [comment]
@tridge - thanks for the link, was struggling to get that working.

@magicrub - I'll look into the m/s thing, I agree it would be nice to standardise to SI.  I have to change all the references to the original parameter so will be easy to do it as I go.

As for the accessors, I'll change them all over and update.

Thanks both for the advice!

**Comment by AndersonRayner** [comment]
Updates applied and moved to https://github.com/ArduPilot/ardupilot/pull/4229.  This branch broke more than I could fix...

**Pull request closed without merging**
