### PR TITLE
Adding custom addons to startup

### PR DESCRIPTION
**Pull request by martinscrach**
This part of code allow users to custom their startup as it is possible with PX4 autopilot.

### CODE REVIEW

**Comment by proficnc** [comment]
I like this concept! Thank you! 

Can you please describe how a user would build the .txt file? The structure? Can it have comments etc?

**Comment by martinscrach** [comment]
Thank you for your response !

Actually, the user can build his extras.txt on an editor such as Notepad++ and he has to write Nutshell command. The available functions are provided in the Mission Planner Terminal when you connect your pixhawk via an FTDI cable. You can add comments exactly the same way as in the rcS or rc.APM. Actually it is the same structure.
I'm trying to custom the autostart to wait for an entering byte on a AUX channel (something passing from false to true for example at the end of autostart), then change mode AUTO to do a mission automatically.
But it's impossible to replace the rc.APM in the pixhawk... It seems that functions "mv" and "rm" in the terminal are not implemented... So I would like to create my own firmware just to add these few lines of code at the end of rc.APM but I don't know how to do.... If you have an idea please help me !

Thank you !

Envoy? de mon iPhone

Le 22 juil. 2016 ? 23:55, proficnc <notifications@github.com<mailto:notifications@github.com>> a ?crit :


I like this concept! Thank you!

Can you please describe how a user would build the .txt file? The structure? Can it have comments etc?

-

**Comment by tridge** [comment]
your repo seems to have disappeared?
I can manually add this, although I'm curious why the script is run after ArduPilot starts. It means it can't be used for drivers that ArduPilot uses.

**Comment by martinscrach** [comment]
Thank you for your response !

Actually, the user can build his extras.txt on an editor such as Notepad++ and he has to write Nutshell command. The available functions are provided in the Mission Planner Terminal when you connect your pixhawk via an FTDI cable. You can add comments exactly the same way as in the rcS or rc.APM. Actually it is the same structure.
I'm trying to custom the autostart to wait for an entering byte on a AUX channel (something passing from false to true for example at the end of autostart), then change mode AUTO to do a mission automatically.
But it's impossible to replace the rc.APM in the pixhawk... It seems that functions "mv" and "rm" in the terminal are not implemented... So I would like to create my own firmware just to add these few lines of code at the end of rc.APM but I don't know how to do.... If you have an idea please help me !

Thank you !

Envoyé de mon iPhone

Le 22 juil. 2016 à 23:55, proficnc <notifications@github.com<mailto:notifications@github.com>> a écrit :


I like this concept! Thank you!

Can you please describe how a user would build the .txt file? The structure? Can it have comments etc?

**Comment by martinscrach** [comment]
Hi Andrew,

I resent my repo to get it visible on Github.
I took the script at the end because I thought it would be better to put it after all the autostart commands and initialization. Actually I would like to launch a mission automatically after the drone initialization. For instance, to fly the drone from A to B point. It would be really great if you add this because I didn't manage to create a customized firmware with this change.
Thank you !

Envoy? de mon iPhone

Le 4 ao?t 2016 ? 01:14, Andrew Tridgell <notifications@github.com<mailto:notifications@github.com>> a ?crit :


your repo seems to have disappeared?
I can manually add this, although I'm curious why the script is run after ArduPilot starts. It means it can't be used for drivers that ArduPilot uses.

-

**Comment by tridge** [comment]
how would a change in rc.APM affect flight mode or mission behavior?

**Comment by tridge** [comment]
I still don't see how this could be used to achieve what you want - there are no nsh level commands that can affect the ArduPilot flight mode, and it can't be used to affect driver load. I can't actually think of any use case that this would work for

**Comment by tridge** [comment]
I'm going to close this for now, if you can explain how it could actually be used then I would be more than happy to look at it again (and reopen the PR)

**Pull request closed without merging**
