### PR TITLE
AP_NavEKF2: optical flow fixups

### PR DESCRIPTION
**Pull request by jschall**
- Corrects poor aiding mode logic that causes filter to operate without any position or velocity fusion when flow data is invalid or is failing innovation consistency checks
- Modifies initial velocity variance in relative aiding mode, giving flow measurements a better chance of passing innovation consistency checks
- Adds flow timeout flag, anticipating further logic improvements

### CODE REVIEW

**Comment by jschall** [comment]
Recommend diffing with whitespace ignore:
https://github.com/ArduPilot/ardupilot/pull/4553/files?w=1

**Comment by jschall** [comment]
Flow timeout logic is tricky. On the one hand, the sensor could be bad or poorly configured, in which case we want to permanently switch to AID_NONE. For other causes, we want to reset and continue trying to use it.

Perhaps for now we should just declare flow invalid forever if it fails its consistency checks for too long?

**Comment by priseborough** [comment]
Agree that a permanent witch to AID_NONE is what we should do until we can come up with a more reliable method of checking optical flow health which will need a better health status message form the optical flow processing than we currently get with PX4Flow running the KLT firmware.

Can you please provide a test log demonstrating how this PR handles loss of optical flow.

**Comment by rmackay9** [comment]
I'm happy to pull this in once someone has actually test flown it

**Comment by lucasdemarchi** [comment]
@rmackay9 since you are playing with optical flow, maybe you would be the one to test fly it? :-)

**Comment by magicrub** [comment]
Does this count?
https://www.youtube.com/watch?v=Bzgey8iR69Q

**Comment by rmackay9** [comment]
Ok, I did not actually test this patch when making the video but I will do another test with it included.

**Comment by jschall** [comment]
@rmackay9 not sure that this patch is necessarily ready.

**Comment by magicrub** [comment]
I cherry picked https://github.com/ArduPilot/ardupilot/commit/25bee93fcc245256cd70a018c4e273bf7154e5d7 into master

**Comment by peterbarker** [comment]
> @rmackay9 not sure that this patch is necessarily ready.

Is it ready yet? :-)

**Comment by priseborough** [comment]
Still no log provided showing how it handles loss of optical flow.

**Comment by amilcarlucas** [comment]
Needs a rebase

**Pull request closed without merging**
