### PR TITLE
Add tabulate dependency

### PR DESCRIPTION
**Pull request by Ryanf55**
* Used in filter_size_compare_branches_csv.py

### CODE REVIEW

**Review by khancyr — APPROVED** [review]
LGTM

Used in some tools by CI too and not a lot of deps so that is as fine as junitparser

**Review by khancyr — CHANGES_REQUESTED** [review]
rectification : need to update commit style

**Comment by Ryanf55** [comment]
> rectification : need to update commit style

Fixed

**Review by peterbarker — APPROVED** [review]
LGTM

**Pull request merged**
