### PR TITLE
Save some flash by moving #ifs in GCS library

### PR DESCRIPTION
**Pull request by peterbarker**
The adjustments to the mavlink-id-to-ap-message-id mapping don't just save space, they also mean that if we can't produce the relevant message then teh GCS which tries to set the streamrate for that message will get back an unsupported response rather than a successful response (but then obviously get no messages....)

### CODE REVIEW

**Comment by peterbarker** [comment]
`MatekF405`:
```
 Binary Name      Text [B]         Data [B]     BSS (B)        Total Flash Change [B] (%)      Flash Free After PR (B)
---------------  ---------------  -----------  -------------  ----------------------------  -------------------------
arducopter-heli  -240 (-0.0255%)  0 (0.0000%)  0 (0.0000%)    -240 (-0.0254%)                                   38344
arduplane        -240 (-0.0247%)  0 (0.0000%)  0 (0.0000%)    -240 (-0.0247%)                                    9648
arducopter       -240 (-0.0257%)  0 (0.0000%)  0 (0.0000%)    -240 (-0.0257%)                                   48752
ardurover        -196 (-0.0230%)  0 (0.0000%)  -4 (-0.0031%)  -196 (-0.0230%)                                  131312
blimp            -240 (-0.0353%)  0 (0.0000%)  0 (0.0000%)    -240 (-0.0353%)                                  302652
ardusub          -240 (-0.0296%)  0 (0.0000%)  0 (0.0000%)    -240 (-0.0295%)                                  170620
antennatracker   -240 (-0.0363%)  0 (0.0000%)  0 (0.0000%)    -240 (-0.0362%)                                  320616
```

**Review by IamPete1 — APPROVED** [review]
LGTM

**Review by tridge — CHANGES_REQUESTED** [review]
need to work out why durandal saves 240 bytes

**Comment by peterbarker** [comment]
> need to work out why durandal saves 240 bytes

160 bytes because we're not `AP_SIM_ENABLED`

80 bytes because we're not APM_BUILD_Rover`

**Pull request merged**
