### PR TITLE
Copter: arm_checks() skips if arming in Auto mode.

### LINKED ISSUE #21415: Copter: pre-arm check that throttle is high should be skipped if arming in Auto
AP_Arming_Copter::arm_checks() skips over the pilot's throttle position checks if arming in Guided mode from a GCS.  I think we can also skip these checks if the vehicle is arming in Auto mode.  [See code here](https://github.com/ArduPilot/ardupilot/blob/master/ArduCopter/AP_Arming.cpp#L633).

### PR DESCRIPTION
**Pull request by prathamesh7255**
AP_Arming_Copter::arm_checks() skips over the pilot's throttle position checks if arming in Auto mode.
Hello, I am prathamesh patil, a B. Tech. student from India. This is my first pull request. I would be gratified to know if I have done anything in wrong way.

### CODE REVIEW

**Comment by magicrub** [comment]
closes #21415

**Comment by khancyr** [comment]
duplicate from https://github.com/ArduPilot/ardupilot/pull/21994
hello @prathamesh7255 , thanks for your contribution. The code change is good, but we are quite strict on the commit convention. I would request you to update your pull request to remove the merge commit (doing a rebase on the master branch should do it) and correct your commit message to be more explicit on what your change do and start with "Copter:"  to mark this as a change on Copter scope. 
You can have some help on the wiki : https://ardupilot.org/dev/docs/submitting-patches-back-to-master.html#preparing-commits on how to correct your commit . Feel free to reach people on discord if you need more assistance on git stuff.
you commit should looks like the one in  https://github.com/ArduPilot/ardupilot/pull/21994

This does work, but it need some param change (tested with SITL) : 
AUTO_OPTIONS 1 to allow arming
RC_OPTIONS 32 to disable throttle arming check on RC lib.

**Comment by prathamesh7255** [comment]
Thank you for your feedback. I have deleted the commits done earlier from my fork. I will come up with a new PR to resolve the issue.

**Comment by khancyr** [comment]
ok no problem, otherwise you can force push on this PR to update it when you are ready

**Comment by rmackay9** [comment]
Thanks @khancyr for noticing the duplication.  Normally we merge the first commit that is approved so I think I might merge the other one.  Thanks!

**Pull request closed without merging**
