### PR TITLE
Build System: Added WAF build system support for master-AVR.

### PR DESCRIPTION
**Pull request by hiro2233**
Added WAF build system support for master-AVR.

According with @gmorph and @tridge, i removed the non AVR build mechanism, only SITL, APM2 and APM1 are in WAF.

51 examples was updated with the script file and tested with APM2.6 board and these are targeted to APM2 and APM1.

Antennatracker, Plane and  Rover are targeted for APM2 and APM1. All Vehicles are targeted to SITL.

NOTE 1: The rising header checking on the ardupilotwaf was removed for AVR.
NOTE 2: Static building finish complete to the regular path, linking step is not working with avr toolchain at the moment, so we need to link by hand (i don't know how to do it, i'm not python friendly).

Extra steps by hand:
--------------------
E.g. antennatracker we need to do the next steps when the build finish:

1.- we need to link the library and the vehicle; finally we generate the elf object  file.

avr-g++ -Wall -Wextra -Os -Wl,--gc-sections,--relax -mmcu=atmega2560  -o build/apm2/bin/antennatracker.elf build/apm2/lib/bin/libantennatracker.a build/apm2/lib/libAntennaTracker_libs.a

2.- and finally we create the binary file to Intel hex format.

avr-objcopy -O ihex build/apm2/bin/antennatracker.elf build/apm2/bin/antennatracker.hex

Building:
--------

E.g. building antennatracker for APM2 boards:

$ ./waf configure --board apm2
$ ./waf clean
$ ./waf antennatracker

E.g. building antennatracker for APM1 boards:

$ ./waf configure --board apm1
$ ./waf clean
$ ./waf antennatracker

E.g. building antennatracker for SITL:

$ ./waf configure --board sitl
$ ./waf clean
$ ./waf antennatracker

Best regards,
hiro.

### CODE REVIEW

**Comment by gmorph** [comment]
I don't understand what we gain from this.  The AVR build is working.  Why make these extensive changes especially if it means we have to link by hand?

**Comment by magicrub** [comment]
I agree, grant. This adds huge complexity and I don't see any advantage.

**Comment by hiro2233** [comment]
The problem is the compatibility with master, make and waf differ on the compilation way. The URUS CAPE IO and drivers work with AVR too, so i see thats it's is very good for new developers.

So, at this point, i understand that we don't want 8 bits architecture on master or i'm missing something?
I see that many people still using APM 2.x boards, and this board can reach the realtime if we use it only as a IO CAPE attached with other platforms.

If we don't use it here, so i'm to be forced to put the 8bit architecture to the master anyway?

Please helpme porting this extra step on waf.
Thank you very much.

**Comment by hiro2233** [comment]
One more thing, master-AVR build use Arduino core, Waf use native avr toolchain.

**Comment by hiro2233** [comment]
I have developed HAL AVR for the new API on master too and it are building with WAF too.

**Comment by tridge** [comment]
i think that given this is less functional than the existing build (ie. it doesn't link) it doesn't really add something useful.
so its adding a lot of stuff to maintain for no real gain. Closing, sorry.

**Pull request closed without merging**
