### PR TITLE
Clean up SRV_Channels headers

### PR DESCRIPTION
**Pull request by peterbarker**
- moves AP_Periph default configuration of this library into ChibiOS
 - moves minimisation setting into mimimize.inc
 - moves include of the SRV_Channel.h header into the cpp files that use it, rather than a header included by that cpp file

SRV_Channel.h is a nexus header, so not including it in header files is a good thing.

### CODE REVIEW

**Comment by peterbarker** [comment]
```
Board              AP_Periph  blimp  bootloader  copter  heli  plane  rover  sub
Durandal                      0      0           0       0     0      0      0
Hitec-Airspeed     0                                                         
KakuteH7-bdshot               0      0           0       0     0      0      0
MatekF405                     0      0           0       0     0      0      0
Pixhawk1-1M                   16     0           16      8     16     16     16
f103-QiotekPeriph  0                                                         
f303-Universal     0                                                         
revo-mini                     0      0           0       0     0      0      0
skyviper-v2450                                   0                           
```

(`Pixhawk1-1M` is minimised, so its ROMFS gets an additional line in its hwdef_)

**Comment by tridge** [comment]
> (`Pixhawk1-1M` is minimised, so its ROMFS gets an additional line in its hwdef_)

odd ....

**Comment by tridge** [comment]
happy for this to merge when:
 - check for hwdef.h changes with configure_all.py
 - see if you can work out why Pixhawk1-1M changes

**Comment by peterbarker** [comment]
> > (`Pixhawk1-1M` is minimised, so its ROMFS gets an additional line in its hwdef_)
> 
> odd ....

`NUM_SERVO_CHANNELS` is new to the hwdef:

```
pbarker@fx:~/rc/ardupilot(master)$ diff -u build/Pixhawk1-1M/hwdef.h /tmp/hwdef.h 
--- build/Pixhawk1-1M/hwdef.h	2023-01-25 20:01:31.646564474 +1100
+++ /tmp/hwdef.h	2023-01-25 20:01:20.866509052 +1100
@@ -78,6 +78,7 @@
 #define AP_GPS_SIRF_ENABLED 0
 #define AP_SMARTAUDIO_ENABLED 0
 #define AP_TRAMP_ENABLED 0
+#define NUM_SERVO_CHANNELS 16
 #define BOARD_CHECK_F427_USE_2M "2M flash - use Pixhawk1 firmware"
 #define HAL_CAN_IFACE1_ENABLE
 #define HAL_CAN_IFACE2_ENABLE
@@ -304,13 +305,6 @@
 #define HAL_BARO_PROBE1  ADD_BACKEND(AP_Baro_MS56XX::probe(*this,hal.spi->get_device("ms5611")))
 #define HAL_BARO_PROBE_LIST HAL_BARO_PROBE1
 
-
-// firmware defaults
-
-#ifndef HAL_DSHOT_ALARM_ENABLED
-#define HAL_DSHOT_ALARM_ENABLED (HAL_PWM_COUNT>0)
-#endif
-
 // peripherals enabled
 #define STM32_I2C_USE_I2C1                  TRUE
 #define STM32_I2C_USE_I2C2                  TRUE
@@ -1449,3 +1443,10 @@
 
 
 
+
+// firmware defaults
+
+#ifndef HAL_DSHOT_ALARM_ENABLED
+#define HAL_DSHOT_ALARM_ENABLED (HAL_PWM_COUNT>0)
+#endif
+
```

**Comment by peterbarker** [comment]
> happy for this to merge when:
> 
>     * check for hwdef.h changes with configure_all.py

Done.  Changes are as expected.

> 
>     * see if you can work out why Pixhawk1-1M changes

Sorted, see other comment.  It was ROMFS.

**Pull request merged**
