### PR TITLE
AP_Frsky_Telem: added IMU temperature to FrSky PassThrough telemetry at 0x5001

### PR DESCRIPTION
**Pull request by zenuavsolutions**
this pull request replaces my old one  #8690

### CODE REVIEW

**Comment by OXINARF** [comment]
I have a different version of this here: https://github.com/OXINARF/ardupilot/commit/82877088bec37814ab5ab6a0b03d1aa4c417640a

It uses `constrain_float`, which is for the exact use case we have here.

I'll merge it tomorrow unless @zenuavsolutions, @floaledm or anyone else has objections.

**Comment by floaledm** [comment]
Thanks Francisco. Looks good. Wasn't familiar with `constrain_float`. Hopefully I remember to use it next time.

Would it be worth performing one last test of the code just to be sure? If so, would you mind doing that Jochen?

**Comment by zenuavsolutions** [comment]
@OXINARF great! Many thanks!
@floaledm yes i will do some tests on different boards i have here

**Comment by OXINARF** [comment]
@zenuavsolutions Let me know when you have tested.

**Comment by zenuavsolutions** [comment]
Your code with constrain_float is working! Tested on Pixhawk 1, pixracer and Cube
40d50193-478a-4c6f-801c-394e9c1d018d

**Comment by OXINARF** [comment]
@zenuavsolutions Thanks for testing!

Pushed my commit into master!

**Pull request closed without merging**
