### PR TITLE
AC_WPNav: lowering waypoint radius minimum to 1mm

### PR DESCRIPTION
**Pull request by guglie**
Currently WPNAV_RADIUS cannot be set lower than 10cm

### CODE REVIEW

**Comment by lvale** [comment]
Isn't that asking for a precision that will hardly be attained ? I would be ok with centimetre level, but millimetre .....

**Comment by guglie** [comment]
@lvale I knew this was going to be a discussion point, but I don't get why to limit this. A couple of years ago sub-10centimeters level wasn't considered feasible and now this under-the-hood limit wasn't clear. Maybe there's a need to notify the user when a parameter is being overwritten (probably resetting the parameter value is enough), because a lot of parameters are not clamped even if they're outside their suggested range so this is an uncommon behaviour.

By the way this is only the lower bound of the parameter, most users will continue to use the default value of 2 meters.

But if I'm the only one to think that, I'll raise this PR value to 1 centimeter.

**Comment by lvale** [comment]
@guglie Regular users tend to "test" the reasonable boundaries of what we design, and usually that creates some unforeseen problems. Having a millimetre precision would likely fall on that, and sincerely I see centimetre level only for some very specific (and expensive) external positioning systems, which will limit their usage to indoors and labs, which is not a very widespread application.

**Comment by guglie** [comment]
Thanks for the clarification Randy, I wasn't aware of that common unit misunderstanding.
I've set it to 5, but if you think to keep it at 10 can't we at least reset the parameter value to make it clear that the value has been clamped?

**Comment by rmackay9** [comment]
@guglie, great.  yes I agree that we should set the parameter's value so the user has a chance to know what's happened.  I'll pull this change in once it passes travis.  the commit message is incorrect but not the end of the world :-).

**Comment by guglie** [comment]
@rmackay9 oh sorry I forgot that, fixed.

**Pull request merged**
