### PR TITLE
AP_HAL: Add size() method to RingBuffer ObjectArray

### PR DESCRIPTION
**Pull request by fnoop**
Very simple addition to ObjectArray to add a total() method.  The only way currently of getting the total size of the buffer is to add available() + space().  size is a private member.

### CODE REVIEW

**Comment by khancyr** [comment]
LGTM.
I assume that you will make use of it later ?

**Comment by fnoop** [comment]
Yes this is part of the updates I'm preparing for AC_PrecLand, and allows to resize the inertial buffer based on a new PLND_LATENCY parameter, on the fly.  Without a method to determine the current size of the object array there's no way to detect if it needs recreating.

**Comment by fnoop** [comment]
@OXINARF I used size initially but compile failed:
```
[ 452/1149] Compiling ArduSub/control_poshold.cpp
In file included from ../../libraries/GCS_MAVLink/GCS.h:18:0,
                 from ../../ArduSub/Sub.h:35,
                 from ../../ArduSub/control_manual.cpp:1:
../../libraries/AP_HAL/utility/RingBuffer.h:307:14: error: ‘uint16_t ObjectArray<T>::size’ conflicts with a previous declaration
     uint16_t size;  // total buffer size
              ^
compilation terminated due to -Wfatal-errors.
```

**Comment by OXINARF** [comment]
@fnoop Ah! That's when not using an underscore prefix for private members really shows it's wrong 🙂 Ok, how about `length`? I think it's still better than total, what do you think?

**Comment by fnoop** [comment]
Length would be fine with me.  What about altering size to _size for a 'proper' fix, then using size() for the method name?

**Comment by OXINARF** [comment]
I don't have a problem with that, but if we are going to change size, we have to change all other private members. I'm not accepting two different styles in the same class, it's either one or the other. Also, if you do it, do a separate commit just putting the prefix (it should a NFC - non-functional change).

**Comment by fnoop** [comment]
@OXINARF Ok how does that commit look?  Apologies I changed total() to size() on this commit.  Have absolutely no idea to how to back it out and do a separate one, but will try if you want :)  Note that total()/size() is a new method so it won't affect any existing current behaviour anyway.
It's also failing px4 build on semaphoreci with a shadow declaration of this that I don't understand..

**Comment by OXINARF** [comment]
@fnoop It's the `size` argument of the constructor that it is complaining about. You can use something like `size_`.

**Comment by fnoop** [comment]
@OXINARF Thanks, that's fixed the CI builds :)

**Comment by lucasdemarchi** [comment]
@fnoop I squashed commits, reworded and changed the order, so there's first the commit to do the rename of the variable and then the commit  to add the size() method. I've done this with iterative rebase (`git rebase -i`) that you may be interested in for the next time.

thanks, applied.

**Comment by fnoop** [comment]
Fab, thanks @lucasdemarchi  :)

**Pull request closed without merging**
