### PR TITLE
Move handling of MAV_CMD_DO_GRIPPER up

### PR DESCRIPTION
**Pull request by peterbarker**
Also adds a gripper singleton

### CODE REVIEW

**Comment by WickedShell** [comment]
@amilcarlucas No, it's linked in now, but those vehicles aren't instantiating an object, or updating it as needed, so while the MAVLink side is ready, they still wont actually use it. (Although rover particularly does have a good use case for gripper)

**Comment by rmackay9** [comment]
LGTM

**Comment by amilcarlucas** [comment]
@WickedShell Thanks for explaining

**Comment by amilcarlucas** [comment]
@peterbarker I can not find that branch on your repository

**Comment by OXINARF** [comment]
Merged, thanks!

**Pull request merged**
