### PR TITLE
AC_Avoid: fix composition of fences

### PR DESCRIPTION
**Pull request by dricketts**
This fixes two related issues: https://github.com/ArduPilot/ardupilot/issues/4807 and https://github.com/ArduPilot/ardupilot/issues/4429. Both issues had the same root cause. In particular, the previous implementation would adjust the velocity for the first edge in the polygon, use this new velocity when adjusting for the second edge, and so on. However, the adjustment for the second edge could produce a new velocity that violates the first edge. Similarly, if the polygon fence code was run after the circular fence code, it could produce a velocity that violated the circular fence.

My solution involves two components:
1. Implement a function that computes the closest velocity to the desired velocity, subject to _linear_ constraints.
2. Compute linear constraints on velocity for all fences that are sufficient to keep the vehicle inside these fences. Pass these linear constraints to the function from (1).

(2) requires re-phrasing the circular fence in terms of linear constraints. I think the simplest approach is to just embed a regular polygon inside the circular fence. I think that this is a sufficient solution since the circular fence is very coarse to begin with.

The main downside to this patch is that the runtime is now quadratic in the number of edges (previously it was linear). However, this is only in the worst case. A more precise runtime is O(k*n) where k is the number of fence edges that must be adjusted for. In most cases, I expect k <= 1. If there is concern about the runtime, we can parameterize this code by a maximum value of k. After the velocity has been adjusted k times, the code will only adjust the magnitude of velocity, not the direction. This will not be optimal, but will at least have a guaranteed linear runtime.

I think that this new approach will make the avoidance code easily extensible. The idea is that there are many different sources of velocity constraints (polygon fence, no-fly zones, obstacles, etc.). In the future, we can generate all such constraints and then pass them to adjust_velocity_constraints. This guarantees that the velocity satisfies all constraints, without having to worry about weird interactions between, e.g. the polygon fence and obstacle avoidance.

Finally, this pull request builds on a previous one: https://github.com/ArduPilot/ardupilot/pull/4813. I'm not sure whether I should close the previous one, or do one after another. I think it would probably be easier to ignore the previous pull request.

### CODE REVIEW

**Comment by rmackay9** [comment]
sorry it's taking me so long to review this (I've been away, AC3.4 testing, etc).  It's high on my list still though.

**Comment by dricketts** [comment]
@rmackay9 no problem. I'm actually on vacation for the next couple weeks so I won't be able to respond much in the near future anyway.

**Comment by rmackay9** [comment]
Sorry for still not merging this.  I haven't forgotten but I'm a bit torn.  The issue is that after a fair number of flight tests, I find the sliding behaviour unnerving.  From the pilot's point of view it leads to a bit of an out-of-control feeling because you don't know exactly where the vehicle is going to go.  The pilot hasn't commanded it to fly sideways but it tends to.

I've added an issue to support "stop" in addition to or instead of "slide". http://ardupilot.org/dev/docs/code-overview-object-avoidance.html.

**Comment by dricketts** [comment]
@rmackay9 I actually originally implemented the stop policy, but Leonard and I decided on the slide policy for the following reason: with the stop policy, the behavior of the vehicle is very erratic when it is close to a boundary and moving parallel to the boundary. Consider the following scenario. The vehicle is next to a boundary and the pilot commands maximum velocity parallel to the boundary. Due to noise (e.g. in position estimate, desired velocity vector), the velocity vector will fluctuate between pointing just inside the boundary and pointing just outside the boundary. When it points outside, the vehicle will come to a stop and when it points inside, the vehicle will try to go at maximum speed.

Essentially, the stop policy exhibits a lack of robustness with the respect to noise, while the slide policy is smooth with respect to noise. That said, I only ever tested the stop policy in the simulator. Moreover, I've only probably flown a copter a grand total of 20 times in my life, so I don't actually have a sense of what is good behavior from the perspective of the pilot.

Perhaps the most compelling reason to use the stop policy is that the implementation is substantially simpler. The main reason is that, since the slide policy changes velocity vector direction, it is not trivially compositional. When you change the direction because of one edge (or obstacle), you have to make sure you didn't violate another edge that you already checked (which is precisely what this pull request is trying to fix). On the other hand, the stop policy is trivially compositional because edges and obstacles only shorten the velocity vector - you never have to recheck an edge you have already checked. To summarize, the stop policy will be easier and more efficient to extend to multiple fences/multiple types of obstacle avoidance, and five years from now, whichever new person takes a look at this code will have a much easier time understanding it.

**Comment by R-Lefebvre** [comment]
Whatever happened to this?

Perhaps what's is needed, is something in between slide and stop.  Make the fence "sticky".  Basically, have the copter slide around, but slowly.

**Comment by dricketts** [comment]
You could accomplish stick mode by computing the velocity from stop mode
and the velocity from slide mode and then outputting some point on the line
segment between these two vectors. Closer to the stop point would be more
sticky.

Unfortunately, I no longer have time to do any implementation on this.


On Mar 31, 2017 7:22 PM, "Robert Lefebvre" <notifications@github.com> wrote:

Whatever happened to this?

Perhaps what's is needed, is something in between slide and stop. Make the
fence "sticky". Basically, have the copter slide around, but slowly.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ArduPilot/ardupilot/pull/4829#issuecomment-290887327>,
or mute the thread

**Pull request closed without merging**
