### PR TITLE
AP_Scripting: Setup of applets directory and first applet entry

### PR DESCRIPTION
**Pull request by Hwurzburg**
Initial applet....depends on Pete's RC option script switch PR being merged

### CODE REVIEW

**Comment by WickedShell** [comment]
Do we want a separate repo for these? Mostly just wondering if that will be easier to get people to contribute to since it could be less strict on rules for commit formatting, as well as to try and keep general maintenance of random scripts from being noisy in the main ardupilot repo/spamming people with PR/issue updates for people who don't do scripting things.

**Comment by Hwurzburg** [comment]
I like the first reason for doing so..like SITL_Models..the second, we get a lot of spam on things that are of interest only to a small group....but am happy with whatever direction is decided....I just could not PR to a non existing repo, or at least dont know how to...

**Comment by tridge** [comment]
> Do we want a separate repo for these?

I prefer the same repo to cope with API changes

**Comment by davidbuzz** [comment]
+1 for doing it like this.

**Comment by peterbarker** [comment]
It was agreed at the devcall that this would be merged after CI passed.

**Pull request merged**
