### PR TITLE
HAL_ChibiOS: re-enable full features on KakuteF7 and OMNIBUSF7V2

### PR DESCRIPTION
**Pull request by tridge**
we now have enough space with recent changes for these boards

### CODE REVIEW

**Comment by peterbarker** [comment]
On KakuteF7:

This PR overflowed for Plane by 5kB for me - before rebase.

```
/home/pbarker/gcc-arm-none-eabi-6-2017-q2-update/bin/../lib/gcc/arm-none-eabi/6.3.1/../../../../arm-none-eabi/bin/ld: bin/arduplane section `.text' will not fit in region `flash'
/home/pbarker/gcc-arm-none-eabi-6-2017-q2-update/bin/../lib/gcc/arm-none-eabi/6.3.1/../../../../arm-none-eabi/bin/ld: region `flash' overflowed by 5244 bytes
collect2: error: ld returned 1 exit status
```

master:
```
  bin/arduplane  873948  1320  260908  1136176
```

After rebase:
```
  bin/arduplane  937492  1360  260868  1199720
```

So ~60kB and about as much to go.

I've pushed up the rebased branch and intend to merge based on these results.

**Comment by peterbarker** [comment]
omnibusf7v2:

before-rebase:
```
/home/pbarker/gcc-arm-none-eabi-6-2017-q2-update/bin/../lib/gcc/arm-none-eabi/6.3.1/../../../../arm-none-eabi/bin/ld: bin/arduplane section `.text' will not fit in region `flash'
/home/pbarker/gcc-arm-none-eabi-6-2017-q2-update/bin/../lib/gcc/arm-none-eabi/6.3.1/../../../../arm-none-eabi/bin/ld: region `flash' overflowed by 4608 bytes
collect2: error: ld returned 1 exit status
```
master:
```
  bin/arduplane  850912  1116  261112  1113140
```
after rebase:
```
  bin/arduplane  937056  1164  261064  1199284
```

**Comment by andyp1per** [comment]
Can you do the KakuteF7Mini as well? It's essentially the same board

**Comment by peterbarker** [comment]
On Mon, 29 Jun 2020, Andy Piper wrote:

> Can you do the KakuteF7Mini as well? It's essentially the same board

I'm a bit leary of actually merging these ATM - I don't actually have 
either of them, 'though a KakuteF7 is on the way.  I was going to merge 
after I tested one of them....

Do you know of anyone that could check the others for 'boots'?

But yes, I can add the Mini - I'd already considered doing that....

**Comment by peterbarker** [comment]
I've rebased this again (on top of some CI fixes), and added @andyp1per 's request into the mix.

**Comment by andyp1per** [comment]
I can't test the omnibus, but I can test the kakutes - will do that

**Comment by andyp1per** [comment]
This works fine on a kakutef7 mini

**Comment by peterbarker** [comment]
Andy checked this on KakuteF7 and Mini.  Thanks!

**Pull request merged**
