### PR TITLE
Tools: added name to GIT_Success.txt

### PR DESCRIPTION
**Pull request by Kametor**
This PR adds my name to the GIT_Success.txt file

### CODE REVIEW

**Comment by peterbarker** [comment]
@Kametor unfortunately, your PR here has conflicted, with someone else getting in ahead of you.

Do you know how to rebase your PR to make it mergeable?  If not I can help you with that.

**Comment by Kametor** [comment]
> @Kametor unfortunately, your PR here has conflicted, with someone else getting in ahead of you.
> 
> Do you know how to rebase your PR to make it mergeable? If not I can help you with that.

yes, thanks a lot.

**Comment by peterbarker** [comment]
@Kametor to rebase a PR I actually do need a branch to rebase - but you deleted the branch here :-)

I suggest you raise another PR now to add your name.

**Comment by rmackay9** [comment]
He created a new PR that I already merged: https://github.com/ArduPilot/ardupilot/pull/15930

**Pull request closed without merging**
