### PR TITLE
Stop vehicle code passing EKF scalars through to AttitudeControl

### PR DESCRIPTION
**Pull request by peterbarker**
This is not an NFC.

Circle-mode will honour the EKF-imposed limits.

WPNav will also honour the limits.  It is unclear to me if this is a good change or not - perhaps there are controller reasons we can't use the EKF's limits?

### CODE REVIEW

**Comment by lthall** [comment]
I believe this was put in there to handle the limits of Optical flow.
It lets us move into and out of optical flow and ensure that the EKF can handle the new form of position control.

**Comment by peterbarker** [comment]
Peter to add an autotest to show that the limits are being imposed.

**Comment by rmackay9** [comment]
As mentioned on the dev call, I'm happy for this to go in once we've tested it works in SITL

**Comment by peterbarker** [comment]
I've now added a test to Copter for these changes.

I've also added a couple of patches to work around a problem where we were asking for the navigation scalars before the EKF cores were initialised.  There are several other calls into the EKF which return `void` and don't manipulate the return values if the cores are not set up yet.

My testing also shows that you can reliably trigger an EKF variance if the simulated GPS is disabled in flight, which is interesting.

**Comment by peterbarker** [comment]
On Wed, 3 Oct 2018, Francisco Ferreira wrote:

>       My testing also shows that you can reliably trigger an EKF
>       variance if the simulated GPS is disabled in flight, which is
>       interesting.
> 
> @peterbarker What are you referring to as EKF variance? The EKF failsafe or
> the EKF variance values going up? If the latter, which ones go up? And is it
> with optical flow enabled or disabled?

You get a statustext "ekf variance" and the thing drops into land.  It's 
unrelated to these patches.  Only really noticed it with EKF3.

> Wasn't it supposed to check the altitude was limited?

Nope - it's the speed which is limited at low altitudes - flow rate 
sensor limits.  I dare say interesting things would happen if you were to 
rapidly lose altitude while flowing....

**Comment by OXINARF** [comment]
> Nope - it's the speed which is limited at low altitudes - flow rate
sensor limits.  I dare say interesting things would happen if you were to
rapidly lose altitude while flowing....

@peterbarker Not withholding the PR (which is now merged 🙂), but the height can also be limited  (https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_AHRS/AP_AHRS_NavEKF.h#L221) if avoidance is enabled (https://github.com/ArduPilot/ardupilot/blob/master/libraries/AC_Avoidance/AC_Avoid.cpp#L150).

> You get a statustext "ekf variance" and the thing drops into land.  It's
unrelated to these patches.  Only really noticed it with EKF3.

Humm, I didn't check, but that might be correct. If you lose GPS and don't have any other position information, the EKF failsafe will change to on state - which will likely send a variance message.

**Comment by peterbarker** [comment]
On Mon, 8 Oct 2018, Francisco Ferreira wrote:

> Humm, I didn't check, but that might be correct. If you lose GPS and don't have any other position information, the EKF failsafe will change to on state -
> which will likely send a variance message.

I think it happens regardless of mode.  And it was with OF enabled.  Worth 
chasing you think?

**Comment by OXINARF** [comment]
@peterbarker A crash would be much worse, but landing isn't exactly good, especially if not needed. If it's easily reproducible, I think chasing it is worth it.

**Pull request merged**
