### PR TITLE
create correct USB ID's for the Cube orange

### PR DESCRIPTION
**Pull request by proficnc**
Also corrected some naming to use the correct "The CUBE" naming convention 
It is The CUBE Black
The Cube Orange etc.
Also deleted the duplicate APJ_BOARD_ID

### CODE REVIEW

**Comment by peterbarker** [comment]
The black-cube definition should inherit from fmuv3, like this: https://github.com/ardupilot/ardupilot/blob/master/libraries/AP_HAL_ChibiOS/hwdef/skyviper-v2450/hwdef.dat#L5 - this will significantly reduce maintenance costs as the shape of hwdef.dat changes.

Rebase is required to eliminate the merge commit.

**Comment by proficnc** [comment]
How to rebase? And what’s a merge commit?

**Comment by OXINARF** [comment]
What's different between the Cube Black and the FMUv3?

**Comment by tridge** [comment]
@OXINARF the only difference is the USB IDs.
What I'd like to do instead is make the UDB IDs be settable using apj_tool.py

**Comment by peterbarker** [comment]
@proficnc A "merge commit" is where one branch is pulled into another.  The one labelled "Merge pull request #1 from proficnc/proficnc-patch-..." is one of those.  AP's policy is never to have merge commits on master; we always rebase branches so that all commits go on top of the previous master branch.  Think of it as a stream if you like - our master is one long river - it has no rivers joining it.  (will supply a car analogy if required).

There are plenty of guides to rebasing using git on the internet.  A short summary might be:
 - make a backup of your git tree by copying it sideways
`git branch cube-hwdef-changes` - make a backup of your current branch
`git rebase -i master`

You can then change the word in the first column to accomplish things - squash commits into others, reword commits etc etc.

Is your repo private, BTW?  I can't pull it into my repo here to really see what's going on.  You might consider having both an `ardupilot-private` and `ardupilot`, using the public one for PRs.

**Comment by tridge** [comment]
I've done a push to the PR branch to fix this up. Note that as space and / aren't allowed in device names on Linux, it shows up as:
/dev/serial/by-id/usb-Hex___ProfiCNC_CUBE_Black_32002F001747323532303436-if00
we'd also need to teach the various GCS implementations (and px_uploader.py) to recognise that string

**Comment by tridge** [comment]
what I was hoping was that the new ccache friendly build would make building this after fmuv3 be extremely fast, even without the apj_tool.py changes. For some reason it isn't getting cache hits on that. I'm looking into why.

**Comment by tridge** [comment]
replaced by #8811

**Pull request closed without merging**
