### PR TITLE
AP_BattMonitor: added temperature reading to INA2xx driver

### PR DESCRIPTION
**Pull request by tridge**
this will give more temperature monitoring to quite a few boards, good for detecting power supply overload

### CODE REVIEW

**Comment by Hwurzburg** [comment]
how is this logged or displayed? should it be an OSD panel? right now we only have BARO and AIRSPEED temp panels...nothing for other temp sensors

**Comment by tridge** [comment]
> how is this logged or displayed? should it be an OSD panel?

it is logged. Not on OSD yet, though could be. Mostly it is for diagnostics from log files

**Comment by IamPete1** [comment]
This is temperature of the sensor I think? Not the battery temperature. We need to make sure that is clear on the wiki.

**Comment by lthall** [comment]
> how is this logged or displayed? should it be an OSD panel? right now we only have BARO and AIRSPEED temp panels...nothing for other temp sensors

The telemetry provides a temperature with the other battery monitor data. So it can be plotted using mission planners tuning or quick display. It is also recorded in the data flash log. In my case I use this chip to monitor the temperature of the battery monitor / power distribution / BEC rather than the battery.

You can assign any temperature sensor to a battery / battery monitor. In this case it would make sense to attach the temperature to the battery monitor by default given it is part of the battery monitor chip. I will use a LUA script to provide warnings if the temperature climbs over 100 degrees C. I don't know if we require any additional displays but it is always nice.

> This is temperature of the sensor I think? Not the battery temperature. We need to make sure that is clear on the wiki.

This is the case of for all temperature sensors. Why do we have to explain that a temperature sensor will only measure the temperature of something if it is in close thermal contact with that thing. The voltage the sensor measures is also not the actual voltage at the battery, in my case it can be the voltage of the BEC.

**Comment by IamPete1** [comment]
> This is the case of for all temperature sensors. Why do we have to explain that a temperature sensor will only measure the temperature of something if it is in close thermal contact with that thing. The voltage the sensor measures is also not the actual voltage at the battery, in my case it can be the voltage of the BEC.

I was thinking of a device like this, https://www.mateksys.com/?portfolio=can-l4-bm#tab-id-2 where typically the sensor is not close to the battery. Typically monitors that provide battery temp have a dedicated probe on the battery.

**Comment by lthall** [comment]
I am happy.

**Review by peterbarker — APPROVED** [review]

**Review by lthall — APPROVED** [review]

**Pull request merged**
