### PR TITLE
Remove vestiges of Travis support

### PR DESCRIPTION
**Pull request by peterbarker**
Extracted from https://github.com/ArduPilot/ardupilot/pull/18542

### CODE REVIEW

**Comment by peterbarker** [comment]
I intend to merge this once it passes CI

**Comment by peterbarker** [comment]
@khancyr looks like those environment variables were used for more than just travis

**Comment by davidbuzz** [comment]
will this start passing after https://github.com/ArduPilot/ardupilot/pull/18557  goes in.?

**Comment by khancyr** [comment]
@peterbarker no, the faliure is legit. Before we weren't building with clang.
Now, clang build is working, but we cannot build chibios boards with clang yet . You could check that easily on previous build or even on your computer

**Comment by peterbarker** [comment]
@khancyr I've rebased this

**Comment by khancyr** [comment]
@peterbarker need to rebase again to have the unittest fix!

**Comment by peterbarker** [comment]
> @peterbarker need to rebase again to have the unittest fix!

Rebased on current master

**Pull request merged**
