### PR TITLE
make baro and airspeed calibration non-blocking

### PR DESCRIPTION
**Pull request by tridge**
This prevents a time jump for the EKF which can make it upset. An upset EKF is bad :-)

### CODE REVIEW

**Comment by magicrub** [comment]
YES! If a launch was done right after a cal the old blocking way, sounds
like bad things would happen

**Comment by WickedShell** [comment]
Is this non blocking airspeed as in step one of being able to cal airspeed
while armed?

**Comment by tridge** [comment]
@WickedShell, yes, we could in fact allow cal while armed with this change

**Comment by tridge** [comment]
i've added a patch to allow some calibrations while armed (non-blocking ones)

**Comment by tridge** [comment]
pushed to master
note that we refuse baro and airspeed cal if we think we are flying and we are armed

**Pull request closed without merging**
