### PR TITLE
GCS_MAVLink: Ignore heartbeats from the MAVLink gimbal

### PR DESCRIPTION
**Pull request by amilcarlucas**
Fixes GCS failsafe when a MAVLink gimbal is present

### CODE REVIEW

**Comment by rmackay9** [comment]
Txs for this.  I've added the DevCallTopic because there are various possible solutions:

1. user sets the existing SYSID_MYGCS and SYSID_ENFORCE so only their GCS is viewed
2. handle_heartbeat could be modified to ignore all heart beats with a sysid that matches the vehicle's.  This would stop the GCS failsafe triggering for other components of the vehicle like a companion computer or a mavlink enabled optical flow sensor (although these may not send heartbeats)
3. handle_heartbeat is modified to ignore heatbeats that don't have **component id** of
    - MAV_COMP_ID_MISSIONPLANNER (190)
    - MAV_COMP_ID_SYSTEM_CONTROL (250)


For reference here is a picture of MP's MAVLink Inspector and the various devices it sees.
image

**Comment by olliw42** [comment]
furthermore there can be other componrnts too, like cameras, gpses, what the heck else
IHMO again an example of how not do mavlink
randy's go into the correct direction IHMO, identify the type & ids which identify a gcs and use those to identify the gcs

pl also keep in mind that there might be more than one gcs!!
there seems to not be a mavlink solution for it, like a "primarx gcs", my approach is to assume it's the one with sysid 255, since that's what MP and QGC use as default
what that means IMHO is that you simply also consider SYSID_MYGCS (which you already do)

so, it IMHO would be a combination of randy s options

**Comment by tridge** [comment]
best to have an option to do MAV_TYPE in heartbeat

**Comment by rmackay9** [comment]
@amilcarlucas,

We discussed this at the dev call and we think this could only have happened if the gimbal's system id was somehow set to be the same as the ground station instead of the vehicle.  This could be an issue in the gimbal if it always sets it's system id to the id of the first heartbeat it receives.

Is there some way you could check what the system id of the gimbal is?  Perhaps you could use the MP mavlink inspector?

I'm going to close this I think because we decided at the call that this wasn't he way to resolve the problem.

Txs for the PR though in any case 'cuz it helped with the discussion!

**Pull request closed without merging**
