### PR TITLE
PX4: fixed DSM 14 channel on FMUv4 and add SRXL support

### PR DESCRIPTION
**Pull request by tridge**
This fixes FMU decoding of up to 14 DSM channels on a satellite receiver and also adds support for up to 20 channels using the SRXL protocol (as used on newer Spektrum receivers like the AR7700)

### CODE REVIEW

**Comment by tridge** [comment]
PX4Firmware change is here: https://github.com/ArduPilot/PX4Firmware/pull/68

**Comment by lucasdemarchi** [comment]
Now that we also have these parsers on our repository, do you see any problem in letting them here and share with all boards instead of in px4firmware?

**Comment by tridge** [comment]
@lucasdemarchi I developed them in HAL_Linux actually, and have a separate PR for that.

**Comment by tridge** [comment]
have a single source file for both px4firmware and AP_HAL is problematic as the build for the IO co-processes is C not C++, and doesn't use AP_HAL includes. We may be able to do it, but not worth it I think. If we did do it then it should be a separate PR
applied

**Pull request closed without merging**
