### PR TITLE
AP_Mount: validate modes before setting them

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by rmackay9** [comment]
Thanks for this.

I guess there are some cases where an invalid mode has been set or could be set?

**Comment by peterbarker** [comment]
> Thanks for this.
> 
> I guess there are some cases where an invalid mode has been set or could be set?

Indeed - setting the default mount mode to 17 will provoke an internal error whgen Siyi is your backend.

**Comment by rmackay9** [comment]
Is anything going to use the return value?

**Comment by peterbarker** [comment]
> Is anything going to use the return value?

It would be trivial to modify e.g. `AP_Mount::handle_command_do_mount_configure` to return failure if we actually do fail, which is why I made it bool.  Was only looking at stopping the internal error with this PR, 'though,.

**Review by rmackay9 — APPROVED** [review]

**Pull request merged**
