### PR TITLE
Copter: Add expected value to message

### PR DESCRIPTION
**Pull request by muramura**
I think that it is better for judgment error message to have judgment value.
I think the pilot will make it easier to correct the value with this message.

### CODE REVIEW

**Comment by peterbarker** [comment]
@khancyr Sure?

@muramura shouldn't have the same constant in two places. `const float tolerance = 0.6f;`, perhaps;

@muramura Also, the debug is incorrect - should be `requires <=`

**Comment by khancyr** [comment]
hum, after counting again, it should pass !

**Comment by peterbarker** [comment]
@muramura nudge on this one.

**Comment by rmackay9** [comment]
Merged, thanks!

**Pull request merged**
