### PR TITLE
Move adjust_rate_for_stream_trigger up

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by peterbarker** [comment]
@rmackay9 The Tracker version of this function didn't look at waypoint_receiving - even though it does manipulate that variable elsewhere.  Should we remove its override (changing functionality)?

**Comment by tridge** [comment]
yes, I think we can make tracker use the common function

**Comment by peterbarker** [comment]
Added commits for tracker based on tridge's comment.

**Comment by tridge** [comment]
applied, thanks!

**Pull request closed without merging**
