### PR TITLE
Copter: mission.update called from Auto's run()

### PR DESCRIPTION
**Pull request by rmackay9**
This PR makes the following changes:

- Mission verify commands are run at the full update rate instead of 50hz.  This has a small CPU cost but also means slightly less delay between a mission command completing and the next one starting.
- Auto missions can be restarted while the vehicle is disarmed (maybe resolves issue: https://github.com/ArduPilot/ardupilot/issues/16805)
- Autotest added to ensure this behaviour remains unbroken (replaces PR https://github.com/ArduPilot/ardupilot/pull/16807)

This has been lightly tested in SITL

### CODE REVIEW

**Comment by Gone4Dirt** [comment]
I did some SITL testing of this PR with a few different mission features including do_jumps and mission rewinds.  All works as you describe it should do.  The one thing I noticed however:  If I interrupt a mission, land, and disarm.  When arming in Auto again the mission restarts despite MIS_RESTART = 0:Resume Mission.  Is this the expected behaviour?  I assumed that the vehicle would resume the mission provided there hasn't been a reboot (e.g. a survey mission doing a 'hot swap' of batteries so not rebooting).  It might be that I am mistaken on the expected behaviour though?

**Comment by rmackay9** [comment]
@Gone4Dirt, thanks very much for testing this!

Re the MIS_RESTART param behaviour, I tested master and found that it acts the same.  So the mission always restarts (instead of resuming) if the vehicle has been disarmed regardless of the MIS_RESTART param value.  Put another way, the "resume" feature only works if the vehicle hasn't been disarmed in the interim.

I'm happy to discuss a possible enhancement to change this behaviour of course.  One difficulty of resuming a mission while the vehicle is on the ground is the takeoff command is skipped.

**Comment by WickedShell** [comment]
It's very useful to be in auto then arm, which actually works well (as long as you have a valid location I grant). My main concern is that this breaks the ability to tell which item the system will be jumping to when it actually gets armed. The current behavior allows us to monitor what item will be executed the moment we arm.

**Comment by rmackay9** [comment]
I've changed the PR since the last review in two ways:

1. the mission runs while the vehicle is disarmed in Auto (like master does)
2. the MISSION_START command is accepted even if the vehicle is disarmed.  This makes it easier for users to restart a completed mission while the vehicle is disarmed instead of forcing them to first arm and then restart the mission.

As a side note, I found these two requests from the dev team incompatible:

- mission should run while the vehicle is disarmed.  The benefits of this are:
  1. the user will see on the GCS map where the vehicle will go first
  2. the user can potentially add an ARM command to the mission so the moment they switch to Auto the vehicle will arm, takeoff and execute the mission.  Editorial: nobody's ever done this, it seems dangerous and users get a similar ease-of-use by using AUTO_OPTIONS=3 which allows arming in Auto and starting the mission without raising the throttle.
- If AUTO_OPTIONS=3 (allows arming in Auto & starting mission without raising throttle) then after the vehicle completes the mission and lands and disarmed.  **If the user arms again the mission should restart.**

The part in bold is the problem because it means the mission needs to be restarted:

1. when the vehicle completes the previous mission
OR
2. when the vehicle is next armed

If we choose option 1 then if the mission contains an ARM command at the beginning then the moment it landed and disarmed, it would restart the mission, arm and takeoff again.  This would be very odd and scary for users.

If we choose option 2 then MichaelDB's requirement to see on the GCS map where the vehicle will go before arming is not fulfilled.

**Comment by rmackay9** [comment]
discussed on the dev call so merging. txs!

**Pull request merged**
