### PR TITLE
vagrant changes

### PR DESCRIPTION
**Pull request by davidbitton**
I added cmake to list of PX4 packages and editing the jsbsim git URL to be more firewall friendly.

### CODE REVIEW

**Comment by magicrub** [comment]
I see a merge in here.  Can you rebase your branch please to remove that?

**Comment by peterbarker** [comment]
@davidbitton The cmake requirement has already been added; a rebase will show that patch disappears.

I believe the only diff in here is the make-URL-firewall-friendly, which looks like a reasonable change.

When you rebase this, there should only be a single commit, with only that URL changing.

Thanks!

**Comment by davidbitton** [comment]
ok. fixed and resubmitted.

**Comment by magicrub** [comment]
Next time you can just force push. Github will auto update the pullrequest.

**Comment by davidbitton** [comment]
Will do.

Sent from my mobile device.

Please excuse its brevity and/or typographical errors.

On Jun 19, 2016, at 9:47 PM, Tom Pittenger <notifications@github.com> wrote:

Next time you can just force push. Github will auto update the pullrequest.
On Jun 19, 2016 5:34 PM, "David B. Bitton" <notifications@github.com> wrote:

> ok. fixed and resubmitted.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/ArduPilot/ardupilot/pull/4339#issuecomment-227030030>,
> or mute the thread
> <
https://github.com/notifications/unsubscribe/AEj7G4wqCk-n8lxaEL-GRF1B-06hKiN-ks5qNeAVgaJpZM4I5FPB
>
> .
>

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/ArduPilot/ardupilot/pull/4339#issuecomment-227034899>,
or mute the thread
<https://github.com/notifications/unsubscribe/AAQ619RilVLr67IdtcfHLKa4bG5xV0THks5qNfE_gaJpZM4I5FPB>
.

**Pull request closed without merging**
