### PR TITLE
Tools: a script to list builds with flash free

### PR DESCRIPTION
**Pull request by tridge**
example: https://firmware.ardupilot.org/Tools/BuildSizes/builds.html

Pair programmed with MichelleR

### CODE REVIEW

**Review by MichelleRos — COMMENTED** [review]
Works well.
We probably need sorttable.js in the PR as well, right?

**Comment by hendjoshsr71** [comment]
Nice!  

We could probably make a Good First Issue to add
* sorting this page per vehicle
* bringing boards to the top and in red that aren't building or under some limit in KB available

**Review by peterbarker — APPROVED** [review]

**Comment by MichelleRos** [comment]
> Nice!
> 
> We could probably make a Good First Issue to add
> 
> * sorting the boards per vehicle by available flash
> * bringing boards to the top and in red that aren't building or under some limit in KB available?

Sorting by columns is implemented using the .js file - you can click on any column to sort by it. Do you mean sorting different vehicles separately?
I'd say it would be better to have a filtering option in that case - eg filter to only show Plane, then sort by the flash column.

The red colouring is a good idea - I feel like trying to add that actually. Although I'd also like an option to only display red boards, so one doesn't have to sort/scroll to find them.

**Comment by hendjoshsr71** [comment]
> > Nice!
> > We could probably make a Good First Issue to add
> > 
> > * sorting the boards per vehicle by available flash
> > * bringing boards to the top and in red that aren't building or under some limit in KB available?
> 
> Sorting by columns is implemented using the .js file - you can click on any column to sort by it. Do you mean sorting different vehicles separately? I'd say it would be better to have a filtering option in that case - eg filter to only show Plane, then sort by the flash column.
> 
> The red colouring is a good idea - I feel like trying to add that actually.

Oh cool! I didn't think to click the columns to sort as they did not have the usual down arrow to let you know you can sort (until I clicked on it and you told me) :)

Yeah I was suggesting sorting them separately  by vehicle by default.  (Though in reality this already naturally happens since plane has the least free flash, then copter , etc.)

Yeah filtering would probably be better.

Creating the separated list for failing boards might be nice so that we could later some how send to discord to annoy to do something about it ;)  (Once again a Good First Issue)

**Comment by tridge** [comment]
added beta and stable tables

**Pull request merged**
