### PR TITLE
Tools: TradHeli Params

### PR DESCRIPTION
**Pull request by ChristopherOlson**
Tunes PSC, LOIT, NAV, ATC specific to Copter 3.6 and New Loiter for single rotor helicopters.

### CODE REVIEW

**Comment by tridge** [comment]
Hi Chris,
It's fine to add this, but perhaps you'd prefer to just change the defaults for those parameters so all trad-heli users get different defaults without having to find and load a separate param file?
If you have a look at this:
https://github.com/ArduPilot/ardupilot/blob/master/ArduPlane/quadplane.cpp#L379
you'll see an example where tailsitters get different defaults in ArduPlane. It uses the function AP_Param::set_default_by_name(), wrapped in a convenient function here:
https://github.com/ArduPilot/ardupilot/blob/master/ArduPlane/quadplane.cpp#L616
You could have a similar table for helis, and even have different tables based on frame typ

**Comment by ChristopherOlson** [comment]
Hi tridge!
The reason I did it as a param file is to make it optional. It took Leonard and I a bit to find a "tune" for the PSC and LOIT that makes New Loiter and Auto work for heli's without porpoising in high speed flight. I tested the "tune" in 7 different heli's from 500 class to 806 and got 100% success with every one - the only thing that needs to be adjusted is the VFF's and tail settings, dependent on size of the machine and what servos are being used. Thunder Tiger also tested the "tune" in their test E700 machine and got fabulous results.

Randy suggested doing a frame file for the E700, but we can't do that for heli's because two machines of the same make and model will have a slightly different "tune" depending on how the mechanical linkages are set, and what servos are used. But we can do a param file that puts in a "tune" for 3.6 that has been proven to fly every machine I've tested it on so far "out of the box". The caveat is that not all users will want to use it, and prefer to "roll their own" by following the tuning wiki. The idea is to eventually have a better set of defaults for heli because a lot of users are failing to set everything correctly, as it is too complicated and they don't understand it. Where we can have a simple heli tuning page that adjusts VFF's and tail settings for a specific heli size to make it more user friendly like FBL units. But Bill doesn't necessarily agree with that concept yet.  So I thought the optional param file was the best, and if we get enough feedback from users that try it and it "just works", then we can do a table like that.

I think I should name the file to a different name though. Possibly a name starting with "TradHeli" instead of "Copter".

**Comment by bnsgeyer** [comment]
@ChristopherOlson I would include ATC_INPUT_TC.  That would directly affect the aircraft response.  This parameter use to be RC_FEEL.
Bill

**Comment by ChristopherOlson** [comment]
@bnsgeyer The purpose of this param file is to tune for New Loiter and Auto, as the defaults and settings carried forward from 3.5 will not work with heli's. Without this it will be a support nightmare trying to explain to folks how to tune it because the speed setting for New Loiter is very important to get it to work. And the braking accel is confusing because it doesn't work the way you would expect without the speed setting up around 30 m/s.  Having the speed setting too low also results in the "recoil effect" with a heli that you note with the oscillations or poor position holding. When you tested you had the speed set at 1500, which is too low and causes the heli to over-brake and "recoil".

I'm sure New Loiter will continue to be "tweaked" as time goes on. But these settings make it work perfectly with every heli I have tested so far. I have flown my big gasser to 47 m/s in level cruise with these settings with no problems noted.

I elected to leave the input time constant out as the default of .15 seems to work fine, and is a param the pilot will tune for "feel" flying with the sticks. It is not critical to the basic settings required to get Auto and New Loiter to work for heli's.

There are several other params that will be tuned for "feel" and response as well, depending on the size of the machine and pilot preference. Those include the RP VFF's, tail P and D, the angular accels, and new angular rates - which I purposely set to zero in this param file due to the problem you noted where you, for some reason, had one of them set to a non-zero value that didn't work. Zero disables the angular rate settings and those can be tuned later if the pilot desires to limit the rate.

This param file will show up in MP's dropdown list to load from the full parameter list. And I also have one for QGC.

I now have ~5.7 hours flying these settings with 3.6 in Auto, admittedly mostly with my big gassers as I don't use the electrics for much other than testing. The PSC performance has been exceptional. Actually better than 3.5. New Loiter takes a little bit of getting used to because it is very snappy with these settings, almost like flying in Acro. But that's the way Leonard wanted it to be.

**Comment by bnsgeyer** [comment]
@ChristopherOlson   Again, I'm not against this.  but in a previous post you made it seem like I am.  I realize that you have got a lot of time on 3.6-rc1 in many different heli's.  So you don't have to defend what your doing to me.  In my case I feel that there is some improvement that can be made but if this satisfies 90% of the user base then I'm fine with that.
By the way, I'm running 1800 RPM and the param list you provided in a separate post didn't include the accel_max params which I think will have a big effect on this.  So I will try your set of params and see how it handles.  Thanks for all the effort on this.

Bill

**Comment by ChristopherOlson** [comment]
@bnsgeyer yes, the accel max params I set at a mid-range that I've found works for all heli's. They will be a bit slow for a 450, about right for a 550-600, a bit fast for a big heli. The idea was to have a "drop-in tune" that is safe with no surprises to get especially New Loiter to work right so folks don't have the problems I had with it on initial testing.

Again, any of the accels, VFF's etc can be further tuned for the specific machine and pilot preference. Even the rate P's could be turned up just a little for smaller heli's. But I found that creates a problem, especially in the pitch axis with the new PSC in Auto, with porpoising with my 500. I wish I had a 450 to test, but I don't. But I think the pitch rate P will be ok for a 450 size, although VFF will have to be reduced to about .11 or .12 for a 450, as they are extremely responsive.

I'll look forward to your test as well. As I'm sure you're aware, this is very hard to do for TradHeli. But I think I'm very close to a usable initial "tune" so users don't get frustrated with 3.6. That's why I felt it's better to do a param file that's optional, rather than wiring new defaults into the code, until we get more feedback on it. I thought it's way easier to point to a param file and say, "try this" instead of trying to explain how to tune this thing. It is not easy.

Thanks!

**Comment by tridge** [comment]
It sounds like these params would be a better starting point for all helis, so I'm still inclined to think they should be the defaults, not something that has to be loaded as a param file. Users can still change params, they would just be starting from these as defaults - that is what set_default_by_name() does, it changes the default value, but doesn't override user values.

**Comment by rmackay9** [comment]
Well, maybe we can do both.. let's start by merging this one and then hopefully get the defaults better for heli so the file shrinks to a smaller set.

**Pull request merged**
