### PR TITLE
Move some Location methods.

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by magicrub** [comment]
print_latlon() is no declared?

**Comment by rmackay9** [comment]
LGTM, I'm happy with the Rover changes

**Comment by peterbarker** [comment]
@magicrub Yes, no declaration; there's no header file for the example to drop it in.

**Comment by khancyr** [comment]
nice, but why don't remove everything from math ?

**Comment by peterbarker** [comment]
@khancyr Working on it.... we actually really want to get it done before @WickedShell 's scripting hits as he's including many of these functions in the API...

**Comment by peterbarker** [comment]
@magicrub Are you OK with the Plane changes?  I think you wrote location_sanitise in the first place...

**Comment by peterbarker** [comment]
marked devcall for attention

**Pull request merged**
