### PR TITLE
Tools: Update GIT_Success.txt

### PR DESCRIPTION
**Pull request by yongler**
Test PR

### CODE REVIEW

**Comment by rmackay9** [comment]
Hi @yongler, txs for this.  Can you change the prefix of the commit to, "Tools: Update GIT_Success.txt"?

**Comment by yongler** [comment]
Done! Thank you

**Comment by rmackay9** [comment]
@yongler,

Txs for that.  Actually I meant update the commit title, not the PR title.

**Comment by rmackay9** [comment]
@yongler,

Txs again.  Could you squash the two commits together?

**Comment by hendjoshsr71** [comment]
@yongler instead of closing this what you want to is "amend" the commit message  
https://stackoverflow.com/questions/179123/how-to-modify-existing-unpushed-commit-messages

`git commit --amend -m "New commit message`

Personally, I prefer to use Gitkraken to do such things. As it is an easy right click edit message thing.
https://www.gitkraken.com/learn/git/problems/git-commit-amend

**Pull request closed without merging**
