### PR TITLE
implement cork() and push() in all AP_HAL RCOutput classes

### PR DESCRIPTION
**Pull request by tridge**
this implements cork() and push() for RCOutput on all HALs, and makes it mandatory
It also fixes the implementation of cork/push for PX4 and VRBrain, where it didn't actually do anything unless oneshot was enabled.

### CODE REVIEW

**Comment by magicrub** [comment]
I briefly looked over this with Tridge on mumble and it looks OK. I have not compiled/flown/tested it

**Comment by kwikius** [comment]
what is cork() ?

**Comment by rmackay9** [comment]
@kwikius, it's a way to ensure that all the RC outputs go out at the same time.  So especially with the PX4Firmware, before it goes out the back of the Pixhawk, it travels from the ardupilot level to the px4-io layer.  because the ardupilot and px4-io layers are not super tightly tied together, it's possible that the px4-io layer might output just half the RC updates immediately and then the rest a moment later.  That's my understanding anyway not having actually looked at the code.

**Comment by lucasdemarchi** [comment]
@rmackay that's right, but history is a bit more complicated. I did the cork/push implementation initially for the boards using PCA9685 (most of the RPI-based boards and Minlure). Besides outputting at the same time we needed this because doing a single I2C transfer is faster than several small ones. This is true in general, even more on our I2C controller because of a bug/misfeature in the kernel. We've got an average transfer time of 4 times faster after this implementation!! In the end we also end up fixing the driver in the kernel (https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/log/?qt=grep&q=i2c%3A+designware%3A ... Currently the last 5 non-merge patches), but it's still faster to do a single transfer: it's faster for the controller and you don't pay the scheduling time.

**Comment by kwikius** [comment]
@lucasdemarchi  This is an implementation thing. e.g for the backend  surely. . Overall it will increase latency

**Comment by lucasdemarchi** [comment]
@kwikius you have to check the caller's and how they update the motors. In this case it won't increase the latency and it will increase stability since all motors are updated at the same time.

**Comment by kwikius** [comment]
It must increase latency since you have to wait until all outputs have been calculated before you change any pwm register.  As you say previously, the real reason is to make a single transaction on I2C, but on boards such as PixRacer which have the pwm registers on the chip it is bound to be better to write the registers as soon as their values are calculated. This is at the heart of "One Shot". With this modification It seems to me that all boards must suffer due to the I2C bottleneck on some linux boards. Remember the PixRacer is designed fo quad racing where latency is a big issue.

**Comment by lucasdemarchi** [comment]
> It must increase latency since you have to wait until all outputs have been calculated before you change any pwm register.

@kwikius again, no.  Please check how the motors are updated.  There's no "wait for other motors to be calculated"... in almost all places (except for aux channels and some other corner cases) they are updated in a loop equivalent to:
```
for (ch = min; ch < CH_MAX; ch++) {
    hal.rcout->write(ch, value[ch]);
}
```

> As you say previously, the real reason is to make a single transaction on I2C, but on boards such as PixRacer which have the pwm registers on the chip it is bound to be better to write the registers as soon as their values are calculated.

No, as I said this was the original reason, but it also improves stability by making sure all motors see the update at the same time.

> This is at the heart of "One Shot". With this modification It seems to me that all boards must suffer due to the I2C bottleneck on some linux boards. Remember the PixRacer is designed fo quad racing where latency is a big issue.

No, please check the code.

**Comment by tridge** [comment]
@kwikius the changes make no difference with oneshot enabled as the oneshot code already did the right thing. Without oneshot they fix the semantics to match the correct behaviour of cork/push on all boards

**Pull request merged**
