### PR TITLE
UAVCAN hardpoint control

### PR DESCRIPTION
**Pull request by pavel-kirienko**
Controlling OpenGrab EPM (electropermanent magnet) and (in theory) other compatible grabbers via UAVCAN.

These changes depend on https://github.com/ArduPilot/PX4Firmware/pull/57, although they can be merged separately - nothing will break, the feature just will not work.

FYI @ctech4285 @silverburn

### CODE REVIEW

**Comment by gmorph** [comment]
Do you have a link so we can see a picture of the electro grabber?
You have a number of white space changes in the commit which make it harder to review.  Any chance you could update the commit with just the code changes?   "git add -p"  is your friend :-)
Thanks, Grant.

**Comment by pavel-kirienko** [comment]
Info about the grabber: https://docs.zubax.com/opengrab_epm_v3

The commits have been squashed and whitespace changes reverted. I don't understand though how whitespaces make changesets harder to review - `?w=1` at the end of the URL is your friend ;)

Let me know if there's something else that needs to be fixed.

Thanks!

**Comment by pavel-kirienko** [comment]
This is a quick reminder that this PR is ready to be merged.

**Comment by ctech4285** [comment]
Yeab I would very much like to see this merged pretty please

**Comment by silverburn** [comment]
Yeah, be really keen to be picked up too.

**Comment by tridge** [comment]
thanks Pavel! I tested here and it looks good. Merged.

**Pull request closed without merging**
