### PR TITLE
AP_HAL_ChibiOS: Make final tweaks to MambaF405US-I2C

### PR DESCRIPTION
**Pull request by tenten8401**
#17998 was mistakenly merged too early, this updates my branch to the one @FairyTalesl was working on

### CODE REVIEW

**Comment by tenten8401** [comment]
CC'ing @tridge

**Comment by tenten8401** [comment]
I think LED colors also need verifying? Doing a few other checks real quick

**Review by tridge — APPROVED** [review]

**Comment by FairyTalesl** [comment]
@tenten8401 latest config compiled and flashed İnav full chip erase but not worked. Mission Planner cant connect fc

**Comment by tenten8401** [comment]
Can you run tools/build_bootloaders.py on the target to rebuild bootloader? forgot to include that in this commit :(

Jul 25, 2021 5:12:55 AM FairyTalesl ***@***.***>:

**Comment by tridge** [comment]
> Can you run tools/build_bootloaders.py on the target to rebuild bootloader? forgot to include that in this commit :(

done

**Pull request merged**
