### PR TITLE
Fix metadata

### PR DESCRIPTION
**Pull request by amilcarlucas**

### CODE REVIEW

**Comment by Hwurzburg** [comment]
what functional impact does this have?

**Review by peterbarker — APPROVED** [review]
LGTM

**Comment by peterbarker** [comment]
Marking this for DevCall to make sure people are OK with the concept of a "range" for the main loop rate.

@Hwurzburg these obviously don't affect the flight code - but will be important for MethodicConfigurator and other places.  It may affect the interface in MissionPlanner poorly for the range check - perhaps a slider rather than a dropdown for the main loop rate.  @amilcarlucas have you checked that?

**Comment by amilcarlucas** [comment]
I did not test MP, but it will improve the Methodic configurator GUI.
And this is a better fix than adding extra exception code on the GCS side.

**Review by tridge — APPROVED** [review]

**Review by rmackay9 — APPROVED** [review]
we could increase the LOOP_RATE range to 800 but this is fine, txs!

**Pull request merged**
