### PR TITLE
SITL: fixed accuracy of lat/lon in AirSim

### PR DESCRIPTION
**Pull request by tridge**
and improve tuning of quadX
ping @rajat2004

### CODE REVIEW

**Comment by rajat2004** [comment]
@tridge Thanks for this! Performance in modes like guided is much better now, more responsive, altitude holding while takeoff is also nice
One thing which I noticed is when in Stabilize mode, with the throttle set to 1500, the drone goes down very quickly, the problem might be with `MOT_THST_EXPO` which is set to 0 in the params.
The range given in the param list is `0.25-0.8`, after setting it to the default value-`0.5`, sinking doesn't happen, though it still goes up very slowly after changing it to 1500 from 1700, so maybe some tuning needed there, not sure about it

**Comment by rajat2004** [comment]
Here's a log file - [00000023.BIN](https://drive.google.com/open?id=1XLDpm-616XeJerg3-5MAPPR4H1KrrNyg)
Also, any changes which should be made to https://github.com/microsoft/AirSim/pull/2347?

**Comment by rajat2004** [comment]
@tridge Could you pull in this commit also - https://github.com/rajat2004/ardupilot/commit/217e609c0b88753c12d0a79f6b1884f4d159cda7
It's for changing the param files in the example scripts

**Comment by tridge** [comment]
> @tridge Could you pull in this commit also - [rajat2004@217e609](https://github.com/rajat2004/ardupilot/commit/217e609c0b88753c12d0a79f6b1884f4d159cda7)
> It's for changing the param files in the example scripts

yep, already done

**Comment by tridge** [comment]
@rajat2004 the reason for the expo of zero is that I think airsim uses a simple linear thrust model, at least if I interpret this correctly:
https://github.com/Microsoft/AirSim/blob/master/AirLib/include/vehicles/multirotor/Rotor.hpp#L124

**Comment by rajat2004** [comment]
> > @tridge Could you pull in this commit also - [rajat2004@217e609](https://github.com/rajat2004/ardupilot/commit/217e609c0b88753c12d0a79f6b1884f4d159cda7)
> > It's for changing the param files in the example scripts
> 
> yep, already done

Great, thanks!



> @rajat2004 the reason for the expo of zero is that I think airsim uses a simple linear thrust model, at least if I interpret this correctly:
> https://github.com/Microsoft/AirSim/blob/master/AirLib/include/vehicles/multirotor/Rotor.hpp#L124

Looks like that, though I don't have any idea about this

**Pull request merged**
