### PR TITLE
Move send_data_stream to base class

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by OXINARF** [comment]
I don't like this implementation very much, it looks a bit complicated. For me, a better approach would be to have a method *stream_send(ID)* that vehicles would need to implement - in that method vehicles decide what messages to send for each stream.

**Comment by peterbarker** [comment]
@OXINARF In fact that's the next patch along, pretty much.  Except that the vehicles only supply information, not code.

This is part of trying to support the `MAV_CMD_SET_MESSAGE_RATE` message.

```
+struct ap_message_mavlink_messages {
+    const uint8_t ap_message_id; // narrowed from enumeration
+    const uint32_t *mavlink_ids;
+    const uint8_t num_mavlink_ids;
+    // const uint8_t clump_id; use to ensure we send all-or-none in a clump?
+};
+
+static const uint32_t MSG_RAW_IMU1_msgs[] = {
+    MAVLINK_MSG_ID_RAW_IMU,
+    MAVLINK_MSG_ID_SCALED_IMU2,
+    MAVLINK_MSG_ID_SCALED_IMU3
+};
+static const struct ap_message_mavlink_messages all_messages[] = {
+    {
+        MSG_RAW_IMU1, MSG_RAW_IMU1_msgs, sizeof(MSG_RAW_IMU1_msgs)
+    }
+};
+
+void GCS_MAVLINK::send_mavlink_message_id(uint32_t id) const
+{
+    switch(id) {
+    case MAVLINK_MSG_ID_RAW_IMU:
+        send_mavlink_msg_raw_imu();
+        break;
+    case MAVLINK_MSG_ID_SCALED_IMU2:
+        send_mavlink_msg_scaled_imu2();
+        break;
+    case MAVLINK_MSG_ID_SCALED_IMU3:
+        send_mavlink_msg_scaled_imu3();
+        break;
+    };
+}
+
```

I have a tree which sets up message intervals for each mavlink message based on the stream-rate parameters.  A few more minutes should allow me to change those rates based on the `SET_MESSAGE_RATE` command.

`send_stream` doesn't make sense in a world where rates are set on a per-mavlink-message basis - so I decided to skip the intermediate step where we sent streams based on these structures.

**Comment by OXINARF** [comment]
@peterbarker Ok, that makes sense. I would prefer to see the PR with all that in though, much easier to see the final picture.

**Comment by amilcarlucas** [comment]
A rebase should make the first 11 commits disappear, and the PR easier to review.

**Comment by peterbarker** [comment]
@amilcarlucas Rebased this a while ago.  And again just now :-)

**Comment by amilcarlucas** [comment]
@rmackay9 This is a good candidate to 3.6.0 :) before it bitrots once again

**Comment by jaxxzer** [comment]
Tested stream rates match

`5bf2fb186`: screenshot 2018-05-07 19 50 11

This pr, `1501804`:

screenshot 2018-05-07 19 55 19

**Comment by tridge** [comment]
this looks good to me, thanks Peter!

**Pull request merged**
