### PR TITLE
Copter: Precision Loiter

### PR DESCRIPTION
**Pull request by peterbarker**
Required some refactoring of the PrecLand backends.

Also sneaking in a tidy-up or two.

### CODE REVIEW

**Comment by rmackay9** [comment]
I test flew this today and it worked as expected.  Video is here: https://www.youtube.com/watch?v=KoLZpSZDfII

**Comment by OXINARF** [comment]
Maybe not for now, but should we rename the AC_PrecLand library to something like AC_PrecTarget? Also it looks like the AP_IRLock library could be integrated in the AC_PrecLand since each backend matches one or less drivers.

Other than that, this looks good. @rmackay9 good to go in?

**Comment by rmackay9** [comment]
@OXINARF, thanks for the review.
I think you're totally right about the AP_IRLock library.  I think we will make an "in tree" version of the IRLock library at some point so that would be a good time to consolidate it.

**Comment by rmackay9** [comment]
Merged!

**Pull request closed without merging**
