### PR TITLE
Copter: mode_auto: don't set takeoff dest from bad current location

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by rmackay9** [comment]
.. think we need some testing evidence for this kind of change..

**Comment by peterbarker** [comment]
Master:
```
STABILIZE> param set SIM_GPS_DISABLE
STABILIZE> SIM_GPS_DISABLE  1.000000

STABILIZE> mode auto
STABILIZE> no link
link 1 down
no link
```

The vehicle has panicked as it has no latitude/longitude, and it will set its takeoff destination to 0,0 and a very low absolute altitude.

After this patch:
```
STABILIZE> SIM_GPS_DISABLE  1.000000

STABILIZE> mode auto
STABILIZE> APM: Mission: 1 Takeoff
Got MAVLink msg: COMMAND_ACK {command : 11, result : 0}
waypoint 1
AUTO> Mode AUTO
```

As far as I am aware we can't actually take off at the moment without crossing the codepath with a valid current location, thus initialising things properly.  This may change if we allow arming in auto, at which point a larger change will be required.

Note that this function already does one early-return later on - with a terrain failsafe.

**Comment by rmackay9** [comment]
Normally we check using the position_ok() method rather than checking the current_loc.lat/lng != 0. I think it's probably better that we're consistent with how we check..

**Comment by peterbarker** [comment]
On Thu, 13 Jun 2019, Randy Mackay wrote:

> 
> Normally we check using the position_ok() method rather than checking the current_loc.lat/lng != 0. I think it's probably better that we're consistent
> with how we check..

We can't use position_ok here - that returns true in circumstances where 
current lat and lng are zero - most notaby when opticalflow is being used.

**Comment by rmackay9** [comment]
@peterbarker, but if our lat and lon are zero.. and our position_ok is true.. then I think we should be able to takeoff with a lat/lon of zero.. I wonder why it panics..

**Comment by peterbarker** [comment]
@rmackay9 If the EKF is using OpticalFlow and you pass through this code you may lock in bad lat/lon/alt.  If the vehicle then switches to absolute positioning you may take off using those locked-in bad values (theoretically, if we allowed arming in auto).

These uninitialised values include altitude.

Also note using `position_ok` would be a significant change in behaviour; it would mean if the EKF was unhappy with your position you would skip out of this routine.  That might not be a bad thing, just much more of a behavioural change.

**Comment by rmackay9** [comment]
I think the problem is likely larger than just the takeoff, it probably applies to all the "nav" commands it's just that we've caught it in SITL with the takeoff command.

I guess we need to make a decision on whether we want to allow the mission to run before we have a position estimate and before the vehicle is armed.  It is somewhat convenient to have it run when testing "do" commands (i.e. not navigation commands) that are right at the start of a mission that often don't need a position estimate (i.e. do-set-servo).  This is an edge case though.  Ther danger in allowing the mission to run is what we are seeing - the execution of the commands often requires a position estimate to do anything reasonable.  It's also perhaps odd that Auto mode will execute those do-commands before it is armed.

My guess is that we shouldn't start the mission until the vehicle is armed which means the mission won't be started until we have a good position estimate.  We could perhaps add a check into ModeAuto::update() that checks if the vehicle has been armed since the last iteration and if it has then it run mission.start_or_resume().

As part of this I think we could also do the following:

- move the mission.update() call to be run from inside of ModeAuto::update.  It's probably OK to run it on every iteration but perhaps we should slow it down to only run on every 8th iteration (this would result in 50hz for the default loop rate).
- remove Mode::run_autopilot() which is only implemented for ModeAuto and even then it only calls mission.update();
- remove Mode::update_navigation() which only calls run_autopilot.
- remove Copter::run_nav_updates() and call update_super_simple_bearing() directly from the scheduler

**Comment by rmackay9** [comment]
I've created an issue to capture the above discussion on a more complete fix: https://github.com/ArduPilot/ardupilot/issues/11598

I think we could potentially merge this PR now to resolve the failures in SITL and then move on to the more complete fix later (before the next release)

**Pull request merged**
