### PR TITLE
LCD Display performance fixes

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by magicrub** [comment]
Why was there a mutex on this anyway?

**Comment by OXINARF** [comment]
@peterbarker Have you tried changing the semaphores for not taking forever? Has anyone tried to do a single I2C transfer like was done in the beginning? I also don't think a vehicle would crash as it doesn't update the LCD when armed (if it is updating then something is wrong).

**Comment by peterbarker** [comment]
@OXINARF My original change was going to be to change to non-blocking or `(1)`.  @tridge said "just remove them", which was easier :-)

You are correct that we don't do the work when armed (and, yes, the problems did go away when armed).  However, loop times of 31,000 microseconds WILL annoy the EKF.  And while pre-arm checks will catch most cases of that, too many people fly with those disabled.

@magicrub It appears the intent was to avoid the timer thread getting an inconsistent view of the buffer.  however, since we don't run on anything which is bit-addressable, and the semaphore is taken only over assignment of a `uint8_t`, there actually *is* nothing being protected there!  `clear_screen` vs `_timer` *is* a legitimate race - the implications being that `_timer` may read a half-cleared display.  Which happens on arming, at least.  Seriously shrug-worthy in my opinion.

**Comment by tridge** [comment]
the semaphores weren't doing what they were aiming to do anyway, so best to remove them. It's pointless having a semaphore around an update of a 8 bit value in the pixel set function, as 8 bit updates are atomic anyway. So its just a waste of time.
If someone wants to re-add semaphores here properly then thats fine, but I'd prefer to see it use a dynamically allocated double buffer. That avoids locking completely, will reduce memory for people not using this device, and will be faster.
Meanwhile, removing these semaphores prevents the EKF getting upset while disarmed.

**Comment by rmackay9** [comment]
I think what led to confusion was the unintuitive interface on the semaphore "take" method.  "0" was assumed to be non-blocking.  I think we should change this default so -1 or a really big number if block-forever or maybe add new methods called "take_nonblock" and "take_blocking forever".

**Comment by peterbarker** [comment]
PR to change all instances of `take(0)` to pass in the macro value:
https://github.com/ArduPilot/ardupilot/pull/6175

**Pull request merged**
