### PR TITLE
AP_AHRS: make get_relative_position_D_home pure virtual

### PR DESCRIPTION
**Pull request by peterbarker**
Having a void function with a return parameter that isn't
filled in by the base class function seems like a bad idea

### CODE REVIEW

**Comment by WickedShell** [comment]
Ha! Nasty. But you know what would be more useful almost everywhere? Just return the float... I only didn't do it that way because none of the other get_relative_position_* functions behaved that way, but it would be cleaner on all code sites to just return the float directly.

**Comment by peterbarker** [comment]
On Tue, 21 Feb 2017, WickedShell wrote:

> Ha! Nasty. But you know what would be more useful almost everywhere? Just
> return the float... I only didn't do it that way because none of the other
> get_relative_position_* functions behaved that way, but it would be cleaner
> on all code sites to just return the float directly.

Would still need to be pure-virtual I think :-)

**Comment by WickedShell** [comment]
Yes, but it would be even better! :)

**Comment by WickedShell** [comment]
I've been thinking about adding a get_relative_altitude_home() function that just managed the equivalent of:
```
float foo;
get_relative_position_D_home(foo);
foo = - foo;
```

Because duplicating that everywhere at the moment is A) nasty B) confusing and C) Makes it harder to teach people/less clear whats happening.

**Comment by magicrub** [comment]
Failing Travis, player 1 game over. Player 2, you're up!

**Comment by peterbarker** [comment]
Huh.  OK, alternative fix: we just set the altitude to zero in the base class and tell everyone to use rovers.

**Comment by OXINARF** [comment]
The actual issue is that this method is different from all the others. All position methods return a boolean saying if the parameter has a valid value or not. I think this should have been done here too and the caller should then decide to use baro or not. If that change is not wanted then I propose that here we have:

```
posD = -_baro.get_altitude();
return;
```

**Comment by magicrub** [comment]
the _D_ version is unintuitive. What if we just remove the _D_ and use *-1 in cases that need it in that format?

**Comment by WickedShell** [comment]
@OXINARF The reason it doesn't implement the return false behavior is that @tridge rightly pointed out that a number of callers within the plane library *require* an idea of what their altitude is and that returning the baro instead protected them. The other thought is that we could still return a bool, and it indicates if the baro was used or the EKF's solution, but that is a bit unintuitive given the signatures of all the other functions.

@magicrub because other users do need the D version and it fits better within all the NED uses cases which is what we standardized. The only reason to pull relative altitude out into it's own function is that it would be more intuitive to a new developer how the should access the value.

**Comment by peterbarker** [comment]
Eh.  The niceties of having an _U_ version is kinda neither here nor there for this PR.

The fact that purifying the function showed that DCM AHRS would not touch the supplied return parameter's value (https://travis-ci.org/ArduPilot/ardupilot/jobs/204040121#L1539) is a bit of an issue.  Possibly enough to block Plane release?

**Comment by WickedShell** [comment]
@peterbarker are you planning to just patch this to provide the DCM implementation/fallback approach?

**Comment by peterbarker** [comment]
On Wed, 22 Feb 2017, WickedShell wrote:

> @peterbarker are you planning to just patch this to provide the DCM
> implementation/fallback approach?

I was just planning on causing problems, not fixing them!

I'll have a punt at fixing the DCM issue - but I'll only be guessing :-)

**Comment by peterbarker** [comment]
On Wed, 22 Feb 2017, WickedShell wrote:

> @peterbarker are you planning to just patch this to provide the DCM
> implementation/fallback approach?

Well, I took a stab at it.  Didn't crash any virtual vehicles in sim...

**Comment by OXINARF** [comment]
> @OXINARF The reason it doesn't implement the return false behavior is that @tridge rightly pointed out that a number of callers within the plane library require an idea of what their altitude is and that returning the baro instead protected them. The other thought is that we could still return a bool, and it indicates if the baro was used or the EKF's solution, but that is a bit unintuitive given the signatures of all the other functions.

That could be fixed with another API or if just Plane needed it, it would be easy to add a method to it that asked AHRS and, if that was unavailable, it would then use baro. The way it is now makes AHRS assume baro always provides altitude above home and, as far as I know, that depends on the vehicle, not on AHRS.
We should have a consistent API and this isn't one. Even the *D_home* and *D_origin* are inconsistent.

@peterbarker I doubt someone is compiling Plane or Rover without EKF support, but it's good to have this fixed. Looks good to be merged.

**Comment by peterbarker** [comment]
@OXINARF Yeah, I tried setting https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_AHRS/AP_AHRS_NavEKF.h#L36 to 0 - ATM that causes all sorts of chaos, starting with Optical Flow.  So ATM EKF seems to be absolutely required.

**Comment by tridge** [comment]
I merged this as it is clearly fixing a serious bug.
I'd be happy to look at alternative fixes later, but for now I wanted this fix in.

**Pull request merged**
