### PR TITLE
mavlink: Add signal_quality field to DISTANCE_SENSOR MAVLink message

### PR DESCRIPTION
**Pull request by amilcarlucas**
Add signal_quality field to DISTANCE_SENSOR MAVLink message

### CODE REVIEW

**Comment by amilcarlucas** [comment]
All tests pass, @WickedShell should I extend the number of ardupilot supported cells from 12 to 14 ?

**Comment by amilcarlucas** [comment]
Done the first rebase today

**Comment by amilcarlucas** [comment]
All tests pass :)

**Comment by tridge** [comment]
need to review and merge this first:
https://github.com/ArduPilot/mavlink/pull/151
then rebase

**Comment by amilcarlucas** [comment]
Rebased again, after the mavlink review from @peterbarker

**Comment by amilcarlucas** [comment]
All CI tests were passing before.
I now rebased it on top of the non-controversial mavlink changes that Perter merged with ArduPilot/mavlink#153
Please comment the ardupilot changes here, and the mavlink changes on ArduPilot/mavlink#151
I expect all CI test to pass again.

**Comment by amilcarlucas** [comment]
This one needs https://github.com/ArduPilot/mavlink/pull/156 to go in first

**Comment by peterbarker** [comment]
@amilcarlucas needs rebase...

**Comment by amilcarlucas** [comment]
rebased, can be merged as soon as CI tests pass

**Comment by amilcarlucas** [comment]
Can just the failing tests be re-triggered?

**Comment by amilcarlucas** [comment]
@peterbarker the tests passed in the past. I do not get why they are failing now. Can you check it out?

**Comment by amilcarlucas** [comment]
Closing to re-trigger CI

**Comment by amilcarlucas** [comment]
All tests pass now :) 👍

**Comment by peterbarker** [comment]
Checked the commit - it's remote/origin/master so all good.

Merging, thanks!

**Pull request merged**
