### PR TITLE
Fix segfault on startup for navio

### PR DESCRIPTION
**Pull request by lucasdemarchi**

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
@staroselskii could you take a look on this?  This fixes the segfault, but there's something wrong elsewhere... I always get a segfault after some minutes running (sometimes it's ~20min, but never more than 1h).

**Comment by staroselskii** [comment]
@lucasdemarchi 

Thanks for the fix. I'll take a closer look on Monday as I don't have have a Navio+ laying around at home right now. Awesome work as always. Thanks. I'll try to reproduce the issue. Has an analysis of a core dump yielded any results?

I guess, a driver like the one we have in RCInput_RPi has to be moved to the kernel. What do you think? This is a tedious task, though. I remember how long it took to debug this piece of code in userspace. This is also the main resource hog on Navio+. Is it a good idea to put a 2Khz thread thread to the kernel? I suppose we don't really meet strict deadlines here either way. I also think that the rate can and should be reduced.

**Comment by lucasdemarchi** [comment]
The rate should be reduced. I still don't grok all the complexity of this RCInput implementation... In the kernel we could probably have a minimal "interrupt timestamp" driver with multiple backends. I have one implemented with generic gpio that I can probably share... And then we could have a backend for RPI with its specialized hw.

**Comment by lucasdemarchi** [comment]
I didn't have time to analyze the crash. One thing I thought was to use the RPI image for navio2 with navio2 so to get a more up to date kernel. Is it sufficient to just blacklist na rcio_* modules for that?

**Comment by staroselskii** [comment]
> In the kernel we could probably have a minimal "interrupt timestamp" driver with multiple backends.

I remember implementing one myself but I didn't really get adequate results. The jitter was way to big to bear. But the driver was indeed extremely minimal. Just a ```request_irq( RISING | FALLING)``` followed by a simple code to postprocess. No threaded interrupts whatsoever, so I'd really like to have a look at your code. Moving this piece of code to kernel could also make differences between Navio+ and Navio 2 code even less. Does your code export the read data to sysfs or it's a classic device driver?

>  Is it sufficient to just blacklist na rcio_* modules for that?
The image is the same for Navio+ and Navio 2. But as you guessed Navio+ doesn't make use of rcio_*. So you can safely blacklist or uncomment the overlay in ```/boot/config.txt```.

>  I still don't grok all the complexity of this RCInput implementation... 
This is indeed not a piece of cake. The code quality is also low. Sorry for that. But as always we needed to get it done.

One of our interns did try to move it to kernel but to no avail. The DMA + PCM interconnection here is quite difficult to express clearly. I guess the third take might yield a result, though.

**Comment by samirbonnet** [comment]
Thank you very much Lucas. 
Clearly the issue was the premature initialisation of the HAL. Now it works wonderfully. I no longer have a segmentation fault when starting the code and so, I can fly my fixed wing UAV with the master branch. (git pull origin pull/5235/head for ppl interested).  Ok quiet ugly... but am not very patient by nature ! Keep up the good work !

**Comment by lucasdemarchi** [comment]
> I remember implementing one myself but I didn't really get adequate results. The jitter was way to big to bear. But the driver was indeed extremely minimal. Just a request_irq( RISING | FALLING) followed by a simple code to postprocess. No threaded interrupts whatsoever, so I'd really like to have a look at your code. Moving this piece of code to kernel could also make differences between Navio+ and Navio 2 code even less. Does your code export the read data to sysfs or it's a classic device driver?

It was a misc driver using a chardev. Configuration was done via ioctl(), configuring the size of the buffer, number o pins, etc and read could be done by calling read() and notfication via poll-family of functions.... I could use it either with PWM input or PPMSUM (at the time I had only PWM receivers, so that was important). AFAIR I had 10usec of jitter which  was one of the reasons I stopped it. I guess for you with PCM it would achieve a better latency. 

I'll dig my hard drives to find the code which may be relevant for others

**Comment by lucasdemarchi** [comment]
> Thank you very much Lucas. 
> Clearly the issue was the premature initialisation of the HAL. Now it works wonderfully. I no longer have a segmentation fault when starting the code and so, I can fly my fixed wing UAV with the master branch. (git pull origin pull/5235/head for ppl interested). Ok quiet ugly... but am not very patient by nature ! Keep up the good work !

thanks for testing.

**Comment by lucasdemarchi** [comment]
> The image is the same for Navio+ and Navio 2. But as you guessed Navio+ doesn't make use of rcio_*. So you can safely blacklist or uncomment the overlay in /boot/config.txt.

you may want to update the docs, pointing people to the correct image since it lists only the old image based on 3.18 kernel:
https://docs.emlid.com/navio/Downloads/Real-time-Linux-RPi2/

**Comment by staroselskii** [comment]
If I understood correctly, we now have code in master that crashed after a while on Navio+?

**Pull request merged**
