### PR TITLE
Added Dmod and slew rate to PID_TUNING message

### PR DESCRIPTION
**Pull request by tridge**
This gives an easy way to see oscillation when manually tuning
this also improves tailsitter SITL support. I was using plane-tailsitter model to test this change
this PR requires https://github.com/ArduPilot/mavlink/pull/219

### CODE REVIEW

**Review by peterbarker — APPROVED** [review]
LGTM

**Comment by peterbarker** [comment]
I've merged the mavlink PR, so the dance can continue.

**Comment by rmackay9** [comment]
This PR needs to go in before my PR can go in it seems. https://github.com/ArduPilot/ardupilot/pull/18345

**Comment by tridge** [comment]
@rmackay9 thanks, I've updated this PR with the padding needed, we should be able to merge this soon

**Review by rmackay9 — APPROVED** [review]

**Pull request merged**
