### PR TITLE
AP_HAL_ChibiOS:added new hardware PixPilot-V6

### PR DESCRIPTION
**Pull request by mfe-xiao**

### CODE REVIEW

**Review by Hwurzburg — CHANGES_REQUESTED** [review]
Needs README file

**Comment by mfe-xiao** [comment]
> Needs README file

okay.

**Comment by Hwurzburg** [comment]
Here is the desired format: https://github.com/ArduPilot/ardupilot/tree/master/libraries/AP_HAL_ChibiOS/hwdef/KakuteH7Mini-Nand

**Comment by mfe-xiao** [comment]
> Here is the desired format: https://github.com/ArduPilot/ardupilot/tree/master/libraries/AP_HAL_ChibiOS/hwdef/KakuteH7Mini-Nand

I have modified the format, please review. Thanks.

**Comment by Hwurzburg** [comment]
thank you!

**Review by Hwurzburg — APPROVED** [review]

**Comment by Hwurzburg** [comment]
@mfe-xiao I had already approved...

**Review by tridge — APPROVED** [review]

**Comment by rmackay9** [comment]
This is included in 4.3.3-rc1

**Pull request merged**
