### PR TITLE
removed HMC5843 compass support as it is not detected by the intel ae…

### PR DESCRIPTION
**Pull request by anemostec**
removed HMC5843 compass support as it is not detected by the intel aero board and thus was delaying the startup process

### CODE REVIEW

**Comment by OXINARF** [comment]
@anemostec What do you mean with "it's not detected"? Have you connected an external HMC5843 and it wasn't detected?

**Comment by anemostec** [comment]
The intel aero board could be operated on it's own without any external compass. The HMC5843 compass is not present on the intel aero board and thus should not be detected by ardupilot.

**Comment by OXINARF** [comment]
> The intel aero board could be operated on it's own without any external compass

Most boards can as most boards have internal compasses.

> The HMC5843 compass is not present on the intel aero board and thus should not be detected by ardupilot.

This code you are removing tries to detect an external compass, not an internal one. It's not in the Intel Aero board but it can be connected.
I'll defer to @lucasdemarchi but I'm pretty sure we don't want this code removed.

**Comment by Pedals2Paddles** [comment]
Wouldn't it be better to simply disable it with `COMPASS_TYPEMASK`?

**Pull request closed without merging**
