### PR TITLE
Tools: added name to GIT_Success.txt

### PR DESCRIPTION
**Pull request by bobroberts170**

### CODE REVIEW

**Comment by rmackay9** [comment]
Looks like this needs a rebase .. I could pull it in anyway but I can't see the branch name either for some reason.

**Comment by bobroberts170** [comment]
Randy I want to apologize, I have no clue what I am doing with regard to the git hub tutorial. I hope I haven't screwed anything up. I am very new to GitHub.

**Comment by rmackay9** [comment]
@bobroberts170, it's fine.. it's all in your repo so it's not affecting anyone else.  I think an "interactive" rebase to remove that last merge commit would be good.  Or you could just try again with a new branch in your repo..

**Comment by rmackay9** [comment]
I'll let this PR sit for another 24hrs but after that I'll probably close it if it hasn't been updated.  hope that's OK

**Comment by bobroberts170** [comment]
That's fine, you can go ahead and close it if you'd like, I won't be able
to get to it before then. Thank you for your kindness sir!

**Pull request closed without merging**
