### PR TITLE
AP_Math: remove code duplication

### PR DESCRIPTION
**Pull request by amilcarlucas**
Use functions from the Location class where possible.

On ArduCopter CubeBlack target this saves 212 bytes.

Before:

```
Target          Text     Data  BSS     Total  
----------------------------------------------
bin/arducopter  1017320  1152  195640  1214112

```

after:

```
Target          Text     Data  BSS     Total  
----------------------------------------------
bin/arducopter  1017108  1152  195644  1213904

```

### CODE REVIEW

**Comment by peterbarker** [comment]
@amilcarlucas Nice cleanup - but would it be better to eliminate these wrappers entirely (and location_offset, too!)?

**Comment by OXINARF** [comment]
@peterbarker Does that mean you think this shouldn't go in as is?

**Comment by peterbarker** [comment]
@OXINARF I haven't actually validated the code.  But if @amilcarlucas would like this in rather than eliminating them entirely I'm not going to block it, of course!  Just pointing out the same validation will have to be done once we nuke most of the functions in this file.

**Comment by amilcarlucas** [comment]
I will do the changes that Peter suggested soonish

**Comment by amilcarlucas** [comment]
@peterbarker is this what you meant ?

**Comment by peterbarker** [comment]
@amilcarlucas Looks like it.  Could you rebase and get it compiling, please?  Looks like some bad changes where you've said `.location` rather than `.offset`

**Comment by peterbarker** [comment]
Merged, thanks - especially for doing the requested additional cleanup!

**Pull request merged**
