### PR TITLE
AP_Mount: Support for pointing mount to circle center

### PR DESCRIPTION
**Pull request by khanasif786**

### CODE REVIEW

**Review by peterbarker — CHANGES_REQUESTED** [review]
Does this differ in target vs "at next waypoint"?  I *think* the target waypoint is the circle center when circling...

**Comment by khanasif786** [comment]
@peterbarker
> Does this differ in target vs "at next waypoint"? I _think_ the target waypoint is the circle center when circling...
Could you please explain this one more.

**Review by rmackay9 — CHANGES_REQUESTED** [review]
Hi @khanasif786,

Thanks for this.  I don't think we need to add the new MAV_MOUNT_MODE_CIRCLE_CENTER. Iinstead I think mode_circle.cpp should just call copter.camera_mount.set_roi_target() and pass in the center of the circle.

The only issue I think is that some users may not want to point the camera at the center of the circle so we should add a CIRCLE_OPTIONS parameter that allows enabling/disabling this feature.  Also my guess is that we should point the camera at the terrain alt of zero at the center of the circle.  So the camera mount should point at the ground at the center of the circle.

**Comment by amilcarlucas** [comment]
Even better whould be to allow configuring the height. Think about antenna tower inspection :)

**Comment by khanasif786** [comment]
@amilcarlucas. It will need a separate parameter to specify the height. However if more configuration is required then users can directly set the ROI using mavlink commands.

**Comment by khanasif786** [comment]
@rmackay9 . At this point what do you think there are 3 possibilities
1. We stick with current implementation and point parallel to the copter
2. We point to the 0 altitude
3. We have a separate parameter to specify the mount target height in circle mode

**Comment by rmackay9** [comment]
@khanasif786,

I think we only need to handle the most common use case because, as you say, if the user wants to do something more complicated they can use the existing gimbal control commands including DO_SET_ROI.  I think the most common use case will be users circling and filming something that is on the ground.

.. so I think adding a CIRCLE_OPTIONS parameter which enables/disables pointing the gimbal at the center would be best and the altitude should be 0m above the terrain.

**Comment by rmackay9** [comment]
Looking good, thanks!

**Pull request merged**
