### PR TITLE
Rover: add ekf failsafe support

### PR DESCRIPTION
**Pull request by tatsuy**
I added ekf(gps) failsafe function.
The issue is #5421.

Many codes are from Copter's EKF failsafe.

### CODE REVIEW

**Comment by tatsuy** [comment]
@rmackay9 
Thank you.
Now, I found more two issues related to GPS. #9853 #9847
I confirmed that it was not caused by this PR.

**Comment by magicrub** [comment]
This looks like generic code that belongs in a library

**Comment by tatsuy** [comment]
Should I put in EKF library?

**Comment by rmackay9** [comment]
I'm closing this because this PR's commit is in cluded in [this new PR.](https://github.com/ArduPilot/ardupilot/pull/10052)

**Pull request closed without merging**
