### PR TITLE
AP_HAL_ChibiOS: stm32h757xx.py update

### PR DESCRIPTION
**Pull request by radiohound**
The AltFunction_map needs some updates to match the pin functions of the stm32h757

### CODE REVIEW

**Comment by nkruzan** [comment]
Hi, we don't merge PR that come from a 'master' branch, you need to create a new branch in your repository, commit your changes to it and then do PR from there. There is a guide on the wiki that can help, https://ardupilot.org/dev/docs/git-branch.html

**Review by nkruzan — COMMENTED** [review]
Hi, we don't merge PR that come from a 'master' branch, you need to create a new branch in your repository, commit your changes to it and then do PR from there. There is a guide on the wiki that can help, https://ardupilot.org/dev/docs/git-branch.html

**Comment by radiohound** [comment]
Closing PR request so I can do it the correct way.

Thank you nkruzan

**Comment by hendjoshsr71** [comment]
@radiohound if you need GIT assistance we are more than happy to help you via resources and suggested commands.

For small items like squashing commits we can do that that for you if needed. (We just don't push onto someone's master branch for fix ups.)

**Pull request closed without merging**
