### PR TITLE
Add default storage dir macros for logs/terrain

### PR DESCRIPTION
**Pull request by lucasdemarchi**
@staroselskii would you like to move the other Emlid boards to the new directory?

Ping @mirkix @LanderU 

@jberaud if I get it right, bebop/disco should remain as they are, right?

### CODE REVIEW

**Comment by mirkix** [comment]
@lucasdemarchi Sounds good. I will remove my defines when this PR is merged.

**Comment by staroselskii** [comment]
I like the idea, but I also wonder why not move the .stg file as well?

**Comment by LanderU** [comment]
I like too.

**Comment by staroselskii** [comment]
I remember looking at a google document that addressed this problem. 

So it all looks good to me apart from the /var/APM/$SKETCH_NAME.stg staying where it was

**Comment by lucasdemarchi** [comment]
> So it all looks good to me apart from the /var/APM/$SKETCH_NAME.stg staying where it was

yep... I forgot that. Updating the PR to cover it.

**Comment by lucasdemarchi** [comment]
@LanderU @mirkix @staroselskii merged. Please feel free to send a PR to adopt the new directory (or I can send later based on your feedback)

**Pull request merged**
