### PR TITLE
Add missing const in member functions

### PR DESCRIPTION
**Pull request by patrickelectric**

### CODE REVIEW

**Comment by amilcarlucas** [comment]
How was this determined? was it a script?

**Comment by khancyr** [comment]
@amilcarlucas ccpcheck, clang-tidy, or any IDE with a linter will propose this to you

**Review by khancyr — APPROVED** [review]
It pass compilation tests so it should be fine

**Review by peterbarker — APPROVED** [review]
LGTM.

I wonder if we should lock this in with an additional CI check?

Note this makes no difference to the size of the Copter build on CubeBlack.

**Comment by patrickelectric** [comment]
Hi Peter,

Yep, that's the plan. I'll try to do that after some corrections around the
code first.

**Comment by rmackay9** [comment]
I'm surprised we can make these methods const:

AC_Autorotation::set_collective
AC_Autorotation::Log_Write_Autorotation
AC_AttitudeControl::control_monitor_log
AC_PolyFence_loader::load_point_from_eeprom
RangeFinder::Log_RFND
AP_SmartRTL::log_action
AP_WheelEncoder::Log_Write() 
GCS_MAVLINK::handle_mission_clear_all

I suspect Tridge will object to adding a CI test because it raises the bar on code submissions which adds another hurdle for new developers.

**Pull request merged**
