### PR TITLE
Automate Coverity Scan

### PR DESCRIPTION
**Pull request by OXINARF**
This will fail Semaphore, but that is supposed to happen because this will only be used by Travis. After it has been merged, I'll setup the monthly cron job.

I have left the needed scripts in the Tools/scripts folder to maintain a parallelism to master. There are three reasons for removal of all the other files: they are not needed, it reduces the time to clone the branch in Travis and, more importantly, I hope it helps to prevent anyone from pushing to this branch.

### CODE REVIEW

**Comment by magicrub** [comment]
19.5k lines deleted! Oh my.

**Comment by OXINARF** [comment]
@magicrub It's mostly removed files. What matters are the first 3 commits, the last one is just removing files. If you want to see what stays at that branch you can look here: https://github.com/OXINARF/ardupilot/tree/pr/automate-coverity-scan

Remember, this is for the coverity_scan branch, not master :)

**Comment by magicrub** [comment]
I had not looked into what the Covarity scan compiled, seems to only
compile sitl but I guess that makes sense. If we compiled px4 we would
drown in warmings from px4firmware and nuttx.

Which reminds me.  Is there any way to skip compiling nuttx by linking a
pre- compiled library instead? That would help speed things up.

**Comment by lucasdemarchi** [comment]
@magicrub this is what waf does for incremental builds. If it's not working it's a bug.

**Comment by lucasdemarchi** [comment]
I think we should at least compile the Linux target as well to improve coverage. Maybe also px4.

**Comment by OXINARF** [comment]
> I had not looked into what the Covarity scan compiled, seems to only
compile sitl but I guess that makes sense. If we compiled px4 we would
drown in warmings from px4firmware and nuttx.

Actually submodules will be ignored, so there's no problem compiling PX4, except the time it will take.

> I think we should at least compile the Linux target as well to improve coverage. Maybe also px4.

I agree that we should test one PX4 board and one Linux board as well, but that wasn't done before. It will consume a lot of time to compile three boards, so I need to think this through a little bit more.

**Comment by magicrub** [comment]
Why does it matter how much time it takes? This is monthly, right?

On Fri, Jun 3, 2016 at 7:48 AM, Francisco Ferreira <notifications@github.com

**Comment by OXINARF** [comment]
@magicrub Because of timeouts in Travis. I intend to test if it is possible or not, how long it will take, etc, but that is a follow-up task.

**Comment by magicrub** [comment]
Isn't Coverity the one doing the scan? Do they do it on the travis server?
I guess I just figured this was happening on a Coverity server.

**Comment by OXINARF** [comment]
The compilation happens in Travis and it is run by a Coverity Scan tool. Some kind of analysis is run in the Coverity server but that is much faster than the compilation.

**Comment by lucasdemarchi** [comment]
I don't like the code removal in this branch, but it's your call.

**Comment by OXINARF** [comment]
@lucasdemarchi Why Lucas? Is there any benefit in keeping old code?

**Comment by lucasdemarchi** [comment]
Just because it increases the difference from one branch to the other.

**Comment by lucasdemarchi** [comment]
I'm all I'm favor of removing old code from master branch an propagate to other branches

**Comment by OXINARF** [comment]
I understand that, but we are not supposed to push anything to this branch again, so vehicle/library code would get old anyway... This branch only exists because of the cron job, otherwise it wasn't needed.

**Comment by lucasdemarchi** [comment]
ok, I'm slightly convinced :)

Applied, thanks.

**Pull request merged**
