### PR TITLE
Move defaulting of HAL_DSHOT_ALARM into hwdef

### PR DESCRIPTION
**Pull request by peterbarker**
Notably this creates `add_bootloader_defaults` and `add_iomcu_firmware_defaults` and `add_normal_firmware_defaults` to `chibios_hwdef.py`.  `add_apperiph_defaults` worked out very well for us, so adding these seems to make sense.

Renames to `HAL_DSHOT_ALARM_ENABLED` to indicate it's a boolean; the similarly-named `HAL_PWM_ALARM` is actually a structure, not a boolean.

### CODE REVIEW

**Review by andyp1per — COMMENTED** [review]
It looks right to me but needs testing

**Review by tridge — APPROVED** [review]

**Comment by tridge** [comment]
needs testing by a user with dshot motors - @andyp1per can you test?

**Review by andyp1per — APPROVED** [review]
Worked on my beater with dshot alarm

**Comment by peterbarker** [comment]
@andyp1per I've marked this as MergeOnCIPass

**Pull request merged**
