### PR TITLE
Revert "CI: disable ccache for MacOS builds"

### PR DESCRIPTION
**Pull request by peterbarker**
This reverts commit c4327161bce5e4ee8b68b6ff4cdc8d19c0d9afc5.

### CODE REVIEW

**Comment by tpwrules** [comment]
Just checked that an old PR is now fixed. Homebrew or whomever must have fixed the dependency and this should pass.

**Comment by tridge** [comment]
> Just checked that an old PR is now fixed. Homebrew or whomever must have fixed the dependency and this should pass.

it wasn't a dependency issue, ccache was segfaulting

**Comment by tpwrules** [comment]
I figured it might be because of something wrong with a dependency because it's working now and its version hasn't changed recently.

**Comment by peterbarker** [comment]
I'm marking this one as MergeOnCIPass on the basis that the segfaulting was probably something bad which github have fixed in their CI.

It has already passed CI once, I've force-pushed it.

**Pull request merged**
