### PR TITLE
Plane: custom pre-takeoff pitch via param TKOFF_GND_PITCH

### PR DESCRIPTION
**Pull request by jschall**
This is from PR https://github.com/ArduPilot/ardupilot/pull/15536

### CODE REVIEW

**Comment by magicrub** [comment]
This is a variant of https://github.com/ArduPilot/ardupilot/pull/16677

**Comment by jschall** [comment]
@magicrub changed this so it is just a rebase of that.

**Comment by Hwurzburg** [comment]
why cant the existing params be setup to do this? you can set the SPD1 to be the ROTATE speed to hold the nose down until rotate speed is reached

**Comment by jschall** [comment]
@Hwurzburg as you can probably see from the code, this PR adds a parameter to specify the pitch angle to be targeted prior to rotate speed being reached. Prior to this PR, that was hard-coded to 5deg.

We use this for taking off from the top of a car, where we need to hold the nose down to prevent the aircraft from lifting off the launch mount prematurely.

**Comment by jschall** [comment]
@tridge the functionality from this PR seems to have gone in to master in a different form. The one that went in is missing pitchController.reset_I()

Seems reasonable to me to reset the integrator while on the takeoff roll. @magicrub should I make a PR to add that line?

**Comment by magicrub** [comment]
@jschall no, when that change went it that integrator was explicitly kept our due to some reasons I've now forgotten. It was discussed on a dev call when it merged. I've left it in our fork so maybe it's worth revisiting

**Pull request closed without merging**
