### PR TITLE
Rover Activation of OSD

### PR DESCRIPTION
**Pull request by Landflieger**
Activation of OSD - should now pass the tests ...

### CODE REVIEW

**Comment by Landflieger** [comment]
@sh83 could you explain to me, why px4-v1 build is failing? the board has no OSD... doesn't understand yet ...

**Comment by auturgy** [comment]
It might not be your pr causing it to fail.
I think master is failing for some reason at the moment.

Regards,

James

**Comment by rmackay9** [comment]
Also to make it work with make you may need to update the make.inc file.

**Comment by Landflieger** [comment]
@rmackay9 I will try my best tonight !

**Comment by Landflieger** [comment]
so I tried my best ... commit subject adjusted, rebased to get one commit, used astyle for cosmetics and added AP_OSD to libraries of make.inc ...

but now github throws a conflict in Rover.h

don't know why, cause I didn't change the code, I hope ...

**Comment by Landflieger** [comment]
@rmackay9 would you be so kind and close this pull request ... in a strange way, I've damaged not only my local repository but my github also ... :(  I take a short break, delete my fork and start again ...

**Comment by Landflieger** [comment]
detected I can close pull request by myself ....

**Pull request closed without merging**
