### PR TITLE
Tracker: correct scan mode pitch clamping

### PR DESCRIPTION
**Pull request by peterbarker**
I'm really confused by this.  This PR definitely seems to fix scan mode from being *totally* broken on my Tracker here.

How is scan mode working for anybody at the moment?

@IamPete1 is this generally working for you?  Am I missing something?

### CODE REVIEW

**Comment by IamPete1** [comment]
Scan mode worked for me when I put in the separate scan speed params, I think the only change here is the change to the constrain, although I have had to get up early so could be missing something. I do think the new logic is easier to follow than the original. The suggested range for the min pitch is negative https://github.com/ArduPilot/ardupilot/blob/5e4162b997fdc9e176ec0a309fb885ece35427f4/AntennaTracker/Parameters.cpp#L203 so I think that would suggest the constrain change is incorrect.

**Comment by peterbarker** [comment]
@IamPete1 the constraint is the only intended change.  Apologies for clouding it with the rearrangement.

So without the constraint change we end up constraining from e.g. 90 to 90 - which means there's only one valid value.

i.e. 
```
nav_status.pitch = constrain_float(nav_status.pitch, -g.pitch_min, g.pitch_max);
```
When `g.pitch_min` is -90 and `g.pitch_max` is 90 gives (defaults):

```
nav_status.pitch = constrain_float(nav_status.pitch, 90.0f, 90.0f);
```
... which is hardly useful.

I do have a headache right now, so... what am I mising?

**Comment by rmackay9** [comment]
This PR's change to the constraint looks correct to me.  There are two things that make me think it is correct:

- PITCH_MIN's default range is -90 to 0
- there is a very similar constraint in control_auto which uses g.pitch_min (like this PR) instead of -g.pitch_min (which is what's in master).

**Comment by rmackay9** [comment]
Merged!

**Pull request merged**
