### PR TITLE
AP_L1_Control:avoid big turn

### PR DESCRIPTION
**Pull request by xianglunkai**

### CODE REVIEW

**Comment by magicrub** [comment]
@xianglunkai Thank you for this PR! Can you tell us more about the problem this is solving? Also, please rebase your branch.

**Comment by amilcarlucas** [comment]
No, you still have not rebased it properly :(

**Comment by rmackay9** [comment]
I've created an issue to cover what this PR is trying to do https://github.com/ArduPilot/ardupilot/issues/20080.

We might close it unless I can figure out how to rebase and then push overtop of this PR

**Comment by rmackay9** [comment]
This PR needs to be rebased but it seems difficult for the submitter to do this and other developers (including me) can't access the branch listed in this PR so I'm going to close this PR and proceed with discussions on [the issue](https://github.com/ArduPilot/ardupilot/issues/20080).

**Comment by amilcarlucas** [comment]
To me looks like the only commit is: https://github.com/ArduPilot/ardupilot/pull/19975/commits/ea22395b37aa8ccc8c7b586c423d9cde3187a9dd

So just re-doing that single line change should be enough to get this fixed.

**Pull request closed without merging**
