### PR TITLE
Misc EKF2 bugfixes from Solo

### PR DESCRIPTION
**Pull request by jschall**

### CODE REVIEW

**Comment by tridge** [comment]
if we always do calcGpsGoodForFlight and we have alt_source==2, then we could switch quite rapidly between using baro and gps for height data? I think that could lead to some rapid changes in the reported altitude.

**Comment by tridge** [comment]
there is a build error in travis. Looks easy to fix.

**Comment by priseborough** [comment]
There is no explanation as to why 4a1c74e is needed

**Comment by jschall** [comment]
IIRC that one was put in because Solo would fail prearm checks immediately after landing when the GPS checks were enabled.

**Comment by jschall** [comment]
Sorry, was confused there. I need to document better. IIRC, this addressed an issue with the glitch detector where the vehicle could take off and get an immediate glitch.

> if we always do calcGpsGoodForFlight and we have alt_source==2, then we could switch quite rapidly between using baro and gps for height data? I think that could lead to some rapid changes in the reported altitude.

Actually, there is a logic bug here. If the filter stops using GPS aiding while gpsAccuracyGood is true (this is a questionable scenario, but moving on...), usingGpsForHgt becomes true indefinitely, regardless of GPS quality. It wouldn't cause rapid switching as far as I can tell, any more than it would cause rapid switching during aiding. I think this patch is the right thing to do.

**Comment by jschall** [comment]
Addressed the build issue, by the way.

**Comment by priseborough** [comment]
These patches are addressed in the following branch which will be submitted as a PR next week pending successful testing:

https://github.com/priseborough/ardupilot/tree/pr-ekf2SoloUpdates

I am trying to keep the various EKF changes from Solo consolidated as much as possible for efficiency in flight testing

**Pull request closed without merging**
