### PR TITLE
Tools: fix sim_vehicle.py tab on mac

### PR DESCRIPTION
**Pull request by guglie**
Just a simple fix for #7179

### CODE REVIEW

**Comment by peterbarker** [comment]
Is this patching around a race condition where the popen'd process isn't running by the time we go looking for it?

Would it make sense to retry looking for the process rather than simply moving on - at least for a little while?

**Comment by guglie** [comment]
Good point, maybe waiting 5 seconds?
If the process is not found is it better to raise an error or to move on?

**Comment by peterbarker** [comment]
On Wed, 29 Nov 2017, guglie wrote:

> Good point, maybe waiting 5 seconds?
> If the process is not found is it better to raise an error or to move on?

Not found might mean the process has karked it, so we can't wait forever.

So a loop like

tstart = time.time()
while time.time - tstart < 5:
 	tabs = p.findall(out)

         if len(tabs) > 0:
 	    break

 	time.sleep(0.1)

if len(tabs) > 0:
 	windowID.append(tabs[0])
else:
 	whinge()

**Comment by guglie** [comment]
Is this enough whinging?

**Comment by peterbarker** [comment]
Looks good to me - thanks!

I'll merge it once travis finishes.

**Comment by guglie** [comment]
Thanks @peterbarker I think it's ok now

**Comment by peterbarker** [comment]
Merged, thanks.

**Pull request merged**
