### PR TITLE
Add missing RebootRequired for SYSID_THISMAV

### PR DESCRIPTION
**Pull request by patrickelectric**
The parameter only takes effect if the vehicle reboots

### CODE REVIEW

**Comment by Williangalvani** [comment]
maybe this? I haven't tested yet
https://github.com/ArduPilot/ardupilot/pull/26570

**Comment by amilcarlucas** [comment]
These parameters should probably be changed to the AP_Vehicle class

**Comment by rmackay9** [comment]
I agree with @Williangalvani that we should add that update to the 1hz loop in Sub.

**Comment by patrickelectric** [comment]
This should be replaced by: https://github.com/ArduPilot/ardupilot/pull/26570

**Pull request closed without merging**
