### PR TITLE
SBF GPS driver: Use the COG calculated by the GPS

### PR DESCRIPTION
**Pull request by amilcarlucas**
Instead of calculating atan with potentialy small noisy velocity vectors, use the one provided by the GPS.
It only gets updated at speeds > 0.1 m/s and it saves us the atan() operation.

### CODE REVIEW

**Comment by amilcarlucas** [comment]
Yes, you are correct we did not flight test it yet, we are still working using the SITL.
Did you take a look at the atan COG estimate on speeds bellow 0,1 m/s ?
It jumps all over the place. I do not get why is that one is better than preserving the last known COG.
It already jumps all over the place, so fallback might be an option.
What does DNU stand for ?

**Comment by WickedShell** [comment]
DNU == Do Not Use

**Comment by amilcarlucas** [comment]
Oh, Thanks :)

**Comment by WickedShell** [comment]
After discussing with @priseborough there is a preference to stick with the velocity based CoG data.

It's worth noting I went and looked and even a u-blox shows massive CoG jumps at low speeds.

**Comment by amilcarlucas** [comment]
OK, fair enough. But can the second commit be cherry picked and merged ? Thanks

**Comment by WickedShell** [comment]
@amilcarlucas Open a new PR with just that commit, I don't want to push directly to master (even with just comment changes). Also worth noting that the first 3 changes in that commit appear to be substituting `-` with some other identical rendering character, whats happening there?

**Comment by amilcarlucas** [comment]
@WickedShell Thanks, I just did that.
the - sign was not get rendered properly, so I just replaced it with a simpler one

**Pull request closed without merging**
