### PR TITLE
Use GPIO_Sysfs for Emlid boards

### PR DESCRIPTION
**Pull request by staroselskii**
There's no need for a custom GPIO_RPi for Navios and Edge. This also makes it easier two use other gpiochips on Emlid's boards. The only limitation is that our Navio+ users might need to edit /boot/config.txt to make the master branch work properly. There's not a lot of Navio+ users, though. And I reckon probably no one uses bleeding edge master. We'll have the Raspbian image updated by the time it gets to a new ArduPilot release.

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
LGTM. Is it flight tested on navio, navio2 and edge?

Navio2Led could actually be something more generic since it just use /sys/class/led. Maybe have a Led_Sysfs, just like we have for gpio? Then for Navio2 we pass the right arguments in the constructor.

**Comment by lvale** [comment]
@staroselskii Don't you want to also add the support for the displays like we've discussed here https://community.emlid.com/t/oled-displays-on-navio/7594  ?

**Comment by staroselskii** [comment]
@lvale 

Yeah, sure, I remember about these. They will go in another PR, though.

**Comment by staroselskii** [comment]
@lucasdemarchi 

I'll update the class to make it more generic. Thanks for the feedback. It's been flight-tested on Navio 2 and Edge.

**Comment by lucasdemarchi** [comment]
Applied, thanks. I squashed the last commit in the respective one just to reduce the noise.

**Pull request closed without merging**
