### PR TITLE
Copter: reduce porpoising in Auto and Guided when speed is set too high

### PR DESCRIPTION
**Pull request by rmackay9**
This PR does two things to reduce porpoising:

- turns on the lean angle limiting in brake, spline and straight waypoint modes
- horizontal acceleration feedforward uses the change in desired velocity instead of the change in the complete target velocity.  This softens the response to disturbances while maintaining the responsiveness to requested velocity changes.

The work is mostly by Leonard with me helping with integration and testing.

I need to perform a bit more testing especially in Loiter and with Guided's velocity controller

### CODE REVIEW

**Comment by rmackay9** [comment]
I flight tested this and it's certainly smoother but less accurate.  We may need a parameter to allow users to choose between the existing behaviour or this new behaviour... so I've added the WIP label because I don't think we can merge to master as-is.

**Comment by jschall** [comment]
@rmackay9 Patch e2c8e4a will require a change to the tuning parameters.
```
                                                    2      
                                       d           d       
kD_old⋅kP_old⋅x(t) + (kD_old + kP_old)⋅──(x(t)) + ───(x(t))
                                       dt           2      
                                                  dt
```
The equation for the new one is:
```
                                         2      
                            d           d       
kD_new⋅kP_new⋅x(t) + kD_new⋅──(x(t)) + ───(x(t))
                            dt           2      
                                       dt
```
If you want the same damping properties:
```
⎧                                  kD_old⋅kP_old ⎫
⎨kD_new: kD_old + kP_old, kP_new: ───────────────⎬
⎩                                 kD_old + kP_old⎭

```
Substituting 1 for kP_old and kD_old:
```
{kD_new: 2, kP_new: 1/2}
```
Did it seem underdamped? Try it with POS_XY_P = 0.5, VEL_XY_P = 2.

**Comment by amilcarlucas** [comment]
When doing a 20 m radius circle flight path with ArduCopter on an OctaQuad with the gimbal ROI at the exact center of the circle and using a 2D (roll+pitch) gimbal, running at 4m/s, the yaw is off in average by -5 deg. And it fluctuates in a sinus form +/- 3deg depending on the position allong the circle.

This seams to be in part because the pitch is not kept constant. Does this patch takes care of that ??

**Comment by rmackay9** [comment]
I found increasing the VEL_XY_P default from 1.0 to 1.8 produced fairly good results on my IRIS.  I didn't find that reducing the POS_XY_P to 0.5 helped but perhaps there are other issues involved.

I've got a couple of logs her: https://www.dropbox.com/s/uqjlmk6y4ui0sqh/Randy_DesVelFF_10May2017.zip?dl=0

I wonder if some others could give this a try and provide feedback.  I'm thinking @jschall, @lthall  and maybe @lvale.

**Comment by rmackay9** [comment]
@amilcarlucas, it shouldn't really affect yaw because the change doesn't touch the yaw controller.  I think I'll wait for some other similar reports before investigating that because I'm pretty sure it must have been something else.

**Comment by rmackay9** [comment]
I'm closing this because I have a new Loiter from Leonard that I will submit shortly.

**Comment by amilcarlucas** [comment]
I liked this one :) When is the new one comming ?

**Comment by amilcarlucas** [comment]
ping

**Comment by amilcarlucas** [comment]
@lthall can you coment ?

**Pull request closed without merging**
