### PR TITLE
Sierra-F405 support

### PR DESCRIPTION
**Pull request by MallikarjunSE**
AP-Periph node with Board ID: 1052

### CODE REVIEW

**Comment by MallikarjunSE** [comment]
Hey @tridge 
Probably my first PR. Any suggestions?
Thank you!

**Review by peterbarker — DISMISSED** [review]
Need one commit/directory.

Commit messages should be `Tools: ...` and `hwdef: ...`

**Review by peterbarker — APPROVED** [review]

**Review by tridge — APPROVED** [review]

**Comment by Hwurzburg** [comment]
I think a readme file should be required before merging...

**Review by Hwurzburg — CHANGES_REQUESTED** [review]
Readme file should be a requirement for merging a new auropilot

**Comment by MallikarjunSE** [comment]
Hey @Hwurzburg should I put the readme file in hwdef folder or somewhere else? 
Thank you!

**Comment by Hwurzburg** [comment]
yes...see this example:https://github.com/ArduPilot/ardupilot/tree/master/libraries/AP_HAL_ChibiOS/hwdef/Durandal

**Pull request closed without merging**
