### PR TITLE
Wp_Nav: an easy way to correct speed reduce issue to avoid twitch

### PR DESCRIPTION
**Pull request by lukezhqin**
Bug report and fix:

This is an easy way to avoid attitude discontinuity which I believe it's for all kind of vehicles in this project. I would show you more about this wp_nav speed control issue I found and met in the real fight below. All I mentioned later are tested in the latest master branch and all the released tag versions still have this problem definatly.

 You guys would easily met this issue if you change one of your waypoint speed and reduce the request speed in the mission. Then after this do_cmd waypoint take effect in SITL or real filght, the vehicle would definitely make a sudden brake just like the following figure shows.

I konw it's better to try to update the '_leash' in pos_control.cpp but I actually haven't find a proper way yet. Now, my method may not look elegant enough but it can indeed avoid this waypoint change to reduce speed issue from distance limitation check of '_leash' once we update the speed request from the mission planned.

I would attache two log files here if you guys would like to check what I met. Both are using a same simple waypoint planned from MissionPlanner. Please help me solve this issue if you have more elegant ways.

### CODE REVIEW

**Comment by lukezhqin** [comment]
But how shall I upload this BIN file? I can't upload this from this website. And I think you guys may plan a very simple wayponit just like this:

And you would easily find out what I mean in this PR then.

**Comment by lukezhqin** [comment]
@rmackay9 Would you please kindly help review this PR? Thanks!

**Comment by lukezhqin** [comment]
The second commit can improve the performance of this PR. The first commit would sometimes met some strange problems when "_limited_speed_xy_cms < _track_speed" condition could be easily met and cause a same failure then, 
The modified codes won't decrease the "_limited_speed_xy_cms " which should be good as I thought. In fact the value "_limited_speed_xy_cms " would be locked until the speed reduced to enough low to met the position condition in wp_nav. But the final position target set to the pos_control would be rudely limited by the "limit_vector_length" function, which I thought could be the true problem for this discontinuty issue bug.
The following shows how this PR can reduce speed in mission with our attitude transition smoothly compared to the original master version.

**Comment by lukezhqin** [comment]
@rmackay9 ,could you please help me review this PR? I hope this bug could be fixed before the V4.0.0 released cause it's really one big probelm as I looked.

**Comment by lukezhqin** [comment]
@peterbarker , Could you please take some time to review this PR? Many thanks!

**Comment by rmackay9** [comment]
Hi, sorry to take so long to review this but I'm completely underwater with the Copter-4.0 support issues.  Another way to escalate is to get the PR tagged as "DevCallTopic" and then join the weekly developer meeting.  Sorry to be annoying..

**Comment by lukezhqin** [comment]
> Hi, sorry to take so long to review this but I'm completely underwater with the Copter-4.0 support issues. Another way to escalate is to get the PR tagged as "DevCallTopic" and then join the weekly developer meeting. Sorry to be annoying..

ur, and how can I add the devtopic tag? could you please help me about that?

**Comment by bnsgeyer** [comment]
@lukezhqin I think this PR is addressing the same issue that I am addressing this #12821.  My PR addresses this at the WP_Nav level and I think makes more sense as it is forcing WP nav to accel and decel at the wp_accel_cmss value.  We can talk about this on the call in a few minutes

**Comment by peterbarker** [comment]
Leonard will be looking at both this and Bill's PR.

**Comment by lukezhqin** [comment]
> @lukezhqin I think this PR is addressing the same issue that I am addressing this #12821. My PR addresses this at the WP_Nav level and I think makes more sense as it is forcing WP nav to accel and decel at the wp_accel_cmss value. We can talk about this on the call in a few minutes

@bnsgeyer , yes ,very good! I looked into your pr, that's exactly what I did later in these days. I also add a wp_nav_speeed. requested function.

**Comment by bnsgeyer** [comment]
@rmackay9 and @peterbarker,
 @lthall approved pr #12821. I suggest we close this PR and associated issue

**Comment by rmackay9** [comment]
@lukezhqin, thanks very much for looking so closely into the issue and raising this PR.

I'm going to close this one now because I've merged the alternative fix from @bnsgeyer.  If you could confirm at some point that the fix works that'd be great but no pressure of course.

Thanks again!

**Comment by lukezhqin** [comment]
@rmackay9 , finally you guys use a similar way as I before come up with. But I still think it's too expensive do float equal calc in our main loop only just want to update the targe max_speed in pos_control. I add this PR meant to ask for help about more elegant ways but fine I shall take this result then.

**Pull request closed without merging**
