### PR TITLE
Tools: reduce mavproxy memory usage on autotest

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by peterbarker** [comment]
@khancyr 

MANUAL> Unknown command 'relay set 0 0'

**Comment by khancyr** [comment]
well, finally we don't gain a lot as we still load a bunch of module ... I could be nice to get ride of some more . But that it is still a gain on travis!

**Comment by peterbarker** [comment]
@khancyr I think I'll fix the commit message here.  It's not really memory we're saving, it's computation time.

**Comment by peterbarker** [comment]
@khancyr This is absolutely fascinating.  The SurfaceTracking test is definitely, reliably broken on his PR.  It doesn't track the surface.  *Interesting*.

**Comment by khancyr** [comment]
hum ... it shouldn't be link to the fact that I remove terrain module from mavproxy ...
but we definitively save some ram in addition of CPU !

**Comment by OXINARF** [comment]
@peterbarker You don't have the terrain module loaded so SITL can't get terrain data, which means the terrain is always at the same altitude.

**Comment by khancyr** [comment]
we should implement terrain handling into SITL and even linux hal too ...

**Comment by OXINARF** [comment]
@khancyr What do you mean?

**Comment by khancyr** [comment]
mavproxy is a bottleneck, instead of relying on it, at least SITL should be able to retrieve terrain info on its own

**Comment by khancyr** [comment]
fix terrain module loading, fix commit message

**Comment by OXINARF** [comment]
> mavproxy is a bottleneck

Agreed.

> instead of relying on it, at least SITL should be able to retrieve terrain info on its own

That's a possibility, although it could mean having the terrain data twice.

**Comment by peterbarker** [comment]
@khancyr @OXINARF I do have this WIP branch: https://github.com/peterbarker/ardupilot/tree/wip/autotest-direct-sitl

**Comment by OXINARF** [comment]
@peterbarker Interesting. How many tests fail with it? Looks like you don't have Travis running on your fork.

**Comment by peterbarker** [comment]
@OXINARF I should probably set travis up on my fork.

IIRC the answer is "lots"....  I'll do a run now and see what happens.

**Comment by OXINARF** [comment]
> I should probably set travis up on my fork.

@peterbarker Tutorial for you: https://github.com/ArduPilot/ardupilot/issues/11131#issuecomment-484465326 😜

**Comment by khancyr** [comment]
Let's do the mavproxy removal by steps. It will be easier

**Comment by peterbarker** [comment]
On Fri, 12 Jul 2019, Francisco Ferreira wrote:

> @peterbarker You don't have the terrain module loaded so SITL can't get terrain data, which means the terrain is always at the same altitude.

Great, thanks!  Added that one.

Notionally we could just load several of these as needed, too.  I'm 
looking at you, relay module.

**Comment by peterbarker** [comment]
On Fri, 12 Jul 2019, Pierre Kancir wrote:

> Let's do the mavproxy removal by steps. It will be easier

Bits of this one could be pulled out into separate PRs - the parameter 
setting, for example.

**Pull request merged**
