### PR TITLE
Move try-send-message of servo-output-raw up

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by peterbarker** [comment]
On Thu, 10 May 2018, Francisco Ferreira wrote:

> What happened to Sub? It's clearly acceptable to change to use this method.

Wow, "clearly" isn't what I'd call it!

I *think* there would be two behavioural changes:
  - whatever the magic value 65535 is
  - returning of expected vs actual outputs, which may be different on an 
board blessed with an IO processor

Yeah, it would be good to be consistent.  But I don't really want to make 
functional changes in a reorganisational PR!

Pretty sure we're supposed to be doing what sub is doing, rather than what 
the base class does, anyway, in terms of motor outputs.

**Comment by OXINARF** [comment]
>   - returning of expected vs actual outputs, which may be different on an board blessed with an IO processor

Where are you seeing that difference? Both GCS_Common and Sub use `hal.rcout->read`, just GCS_Common uses the array method, while Sub does one at a time - but the end result is exactly the same.

>   - whatever the magic value 65535 is

I don't know where that magic value comes from, it was added by @tridge almost 2 years ago, before Sub was merged in - if Sub was here at the time then it would have been changed to use the common method too as @tridge did with all vehicles (which previously also didn't check this magic value). Also if it has any real meaning then I don't see why Sub wouldn't need to handle it in the same way.

> Pretty sure we're supposed to be doing what sub is doing, rather than what the base class does, anyway, in terms of motor outputs.

As I've said, they are doing the same. And I agree that we should send the real output, not what we expect the output to have.

**Comment by peterbarker** [comment]
@OXINARF You're absolutely right.

Sub patch added.

**Comment by OXINARF** [comment]
Merged, thanks!

**Pull request merged**
