### PR TITLE
AP_Mission: Have plane convert NAV_SPLINE points into NAV_WAYPOINT pts

### PR DESCRIPTION
**Pull request by magicrub**
Have plane convert NAV_SPLINE points into NAV_WAYPOINT pts.

This makes it so even if a NAV_SPLINE_WAYPOINT is in a mission that is sent to the aircraft, it will convert it to NAV_WAYPOINT in the mavlink handler as it's received and will then get stored as a NAV_WAYPOINT onboard.

### CODE REVIEW

**Comment by IamPete1** [comment]
Would it not make more sense to not accept the spline points in the first place? We could support spline points on quadplanes in the future.

**Comment by magicrub** [comment]
What we really need is a way for a vehicle to validate/approve the mission items. Right now, we accept all but then when we execute in the vehicle they hit a default switch and return false.

Meanwhile, I still think this particular fix is good for the foreseeable future. If it helps, I could handle the case in plane for spline and return false and add a comment there.

**Comment by rmackay9** [comment]
As a side note, I'm adding SCurve support to Rover and Spline support is just one easy step beyond that.  If Rover can use SCurves I suspect Plane could as well.

**Comment by peterbarker** [comment]
On Sat, 13 Nov 2021, Tom Pittenger wrote:

> What we really need is a way for a vehicle to validate/approve the mission items. Right now, we accept all but then when we execute in the vehicle they hit a default switch and return false.

Make this method virtual and override it for Plane - at least then it is a 
prearm failure:

https://github.com/ardupilot/ardupilot/blob/master/libraries/AP_Arming/AP_Arming.cpp#L716

I really don't like the idea of silently converting.

Rejecting the mission is problematic as you may not know the vehicle's 
capabilities as the mission is being uploaded - you may even end up in a 
chicken/egg problem.  An example of the former is uploading on a firmware 
that does support Splines but then flashing back to an older release - now 
you've got a mission you can't sensibly execute in its entirety.

**Comment by magicrub** [comment]
@peterbarker Prearm check is helpful, but not good enough. Missions can change during flight

**Comment by rmackay9** [comment]
In Copter it skips over commands that it doesn't recognise by considering them complete immediately.  Maybe Plane could do the same?

By the way, in Copter it may be possible to get stuck (but not crash) because (I think) it can only process (and ignore) one command per loop so if there was a do-jump back to this unknown command it might end up in an endless loop.. but not a tight loop, a long loose loop that would cause the vehicle to hold position until the user change the flight mode or a failsafe triggered.

**Comment by samuelctabor** [comment]
@rmackay9 currently it does skip them, and the exact situation you describe cost us a plane.

**Comment by magicrub** [comment]
closed in favor of https://github.com/ArduPilot/ardupilot/pull/19298

**Pull request closed without merging**
