### PR TITLE
Use double-precision hardware support on F745

### PR DESCRIPTION
**Pull request by andyp1per**
Cortex-m7 support is disabled on F745 chips, presumably to save flash - but actually using the double-precision library results in lower flash costs. On a KakuteF7Mini:

Before:
```
    "flash_free": 27868
```
After:
```
    "flash_free": 28052
```

### CODE REVIEW

**Review by tridge — CHANGES_REQUESTED** [review]
did you actually test this? The datasheet says it only has single precision:
image

**Comment by tridge** [comment]
@andyp1per note that when testing you need to test code that uses double precision maths

**Comment by andyp1per** [comment]
@tridge so looks like:
```
-mcpu=cortex-m7 -mfpu=fpv5-sp-d16 -mfloat-abi=hard
```
might be the correct set of options?

**Comment by muramura** [comment]
I have had to process double precision values in NAVAIO2 to deserve single precision because PIXHAWK1 does not support double precision.
Does this mean that from now on, the process of converting double precision values to single precision values will no longer be necessary?

**Comment by tridge** [comment]
> `-mcpu=cortex-m7 -mfpu=fpv5-sp-d16 -mfloat-abi=hard`

if testing shows that works, then yes, that should give you M7 instructions

**Comment by andyp1per** [comment]
Testing does not reveal any performance advantage for FFT so closing.

**Pull request closed without merging**
