### PR TITLE
Allow build for autopilots with only one compass enabled

### PR DESCRIPTION
**Pull request by bugobliterator**
Resolves https://github.com/ArduPilot/ardupilot/issues/17457

### CODE REVIEW

**Comment by bugobliterator** [comment]
@giacomo892 can you test if this works for you? use `omnibusf4pro-one` build.

**Comment by giacomo892** [comment]
It builds just fine on my other targets too. Thanks

**Review by tridge — APPROVED** [review]

**Comment by giacomo892** [comment]
@bugobliterator 
Looks like setting  HAL_COMPASS_MAX_SENSORS 1 on copter/plane breaks the use of the compass since it is not used by the IMU and GCS says:
No Compass backends available. 

So we have a BUG :(

**Comment by bugobliterator** [comment]
@giacomo892 I am not seeing any issue with HAL_COMPASS_MAX_SENSORS 1, can you share some more details, ping me on discord maybe, so I can help debug the issue.

**Pull request merged**
