### PR TITLE
AP_Motors: fixed col max and min for dual heli

### PR DESCRIPTION
**Pull request by tridge**
fixes H_SV_MAN behaviour

### CODE REVIEW

**Comment by bnsgeyer** [comment]
Looking at your commit made me think of heliquad.  Wouldn't you want to remove the yaw input on the heliquad collective min/mid/max check?

**Comment by tridge** [comment]
yes, needs to be done for heliquad too, thanks

**Comment by tridge** [comment]
@bnsgeyer done for heliquad now too

**Comment by bnsgeyer** [comment]
@tridge thanks for making the change.  I will check it in the sitl and complete my review.
thanks,
Bill

**Pull request merged**
