### PR TITLE
Copter: If flight mode is disabled, it won't be built in

### PR DESCRIPTION
**Pull request by muramura**
ACRO mode and FLIP mode are optional flight modes.
I did not incorporate these two types into the code if they are disabled.

### CODE REVIEW

**Review by khancyr — APPROVED** [review]
yep this is right.

**Comment by rmackay9** [comment]
This saves a tiny bit of flash but this isn't really necessary because we don't remove the enums.  E.g. it will compile fine and work without these changes.

I just think it makes the code harder to read so I probably won't merge this.

**Comment by muramura** [comment]
@rmackay9 san
Thanks for the comment.
I will consider, making the ENUM value of the flight mode undefined.

**Comment by rmackay9** [comment]
@muramura, re removing the ENUM, I'm just not sure it's worth trying to remove the enum... what is the value?

**Comment by khancyr** [comment]
There is a value at having this removed for partner for example.
If the code is removed, it doesn't need testing for certification !

**Comment by peterbarker** [comment]
Alternate PR was merged

**Pull request closed without merging**
