### PR TITLE
GCS Frontend

### PR DESCRIPTION
**Pull request by peterbarker**
Attempt a frontend/backend abstraction for GCS

### CODE REVIEW

**Comment by dgrat** [comment]
A few remarks: 
  1) The call of "const AP_Param::GroupInfo GCS_MAVLINK::var_info[]" requires still implementation in the vehicle directory
  2) GCS_Frontend is defined in the library and will get derived in the vehicle directory

Something like this I did in a commit before and @tridge was strictly against overloading and virtual functions. I hope he changed his mind.

**Comment by peterbarker** [comment]
@dgrat Thanks for pointing out the var_info thing.  I was aware, and it is obviously a wart.  I'll push up another commit which pulls that back into GCS_MAVLINK for Tracker, Plane and Rover.  Copter is slightly different and will override.

In terms of overloading and virtual functions - I believe these were a problem because the increased resource usage caused issues on the APM (even cases where you would have thought there should be no increased resource usage did seem to cause issues).  We no longer support AVR.

We are already using inheritance, overloading and virtual functions in DataFlash and AP_Arming.  @tridge suggested the pure-virtual approach used in the backend factoring.

Any more review you can give on the patches will be appreciated.

**Comment by peterbarker** [comment]
This PR turned out to be too much to process in one go.

I'm adding stuff slowly, as tridge has time to review it.

**Comment by magicrub** [comment]
wow, 158 commits?!?

**Comment by peterbarker** [comment]
On Fri, 5 Aug 2016, Tom Pittenger wrote:

> wow, 158 commits?!?

And *still* nothing on.

Actually, most of the problem there is that it touches a lot of different 
libraries (and all of the vehicles), across multipe logical changes.  e.g. 
"Plane: use GCS_Frontend send_home function".

**Comment by dgrat** [comment]
Actually, I also tried to push a MAVLink related commit. Not as big as this, but it already cleaned the class layout and used derived classed. The result was the same as here :D

**Comment by magicrub** [comment]
:(

**Pull request closed without merging**
