### PR TITLE
AP_HAL_F4light: add an ability to disable stats 

### PR DESCRIPTION
**Pull request by night-ghost**
to reduce flash degradation

### CODE REVIEW

**Comment by khancyr** [comment]
hum ... I think it would make more sense to do like recent PR on code reduction and make all AP_Stats optional rather than just prevent the update. It will allow to save a little of space and one write less on flash

**Comment by night-ghost** [comment]
Sure, you are right, will redo into STATS_ENABLED

**Comment by khancyr** [comment]
nice thanks ! 
LGTM !

**Comment by tridge** [comment]
fixed merge conflicts ....

**Pull request merged**
