### PR TITLE
AP_OSD: Fix vertical speed varying length

### PR DESCRIPTION
**Pull request by shellixyz**
Screenshot from 2020-11-28 23-16-52
Screenshot from 2020-11-28 23-17-21

### CODE REVIEW

**Comment by giacomo892** [comment]
@vierfuffzig This looks like a great solution :) 
Thanks @shellixyz !

**Comment by vierfuffzig** [comment]
@giacomo892 we talked about this on discord and i tried to raise a little awareness for the fact that we support other units than metric too.

that pre-decimal formatting obviously didn't have any actual effect, so setting it to `1.1f ` applies no actual change. 

defaulting non-decimal to 2 digits imho adds a benefit exclusively for metric unit users on quite sporty climbrates. it just passes the bucket of shifting one digit up, which is pretty much within the mostly used range on aviation units.

**Comment by shellixyz** [comment]
Indeed I forgot about the ft/min. Should be good now. 2 digits for m/s and ft/s with 1 decimal bellow 10 and 4 digits for ft/min

**Comment by vierfuffzig** [comment]
great, thanks @shellixyz !

**Comment by giacomo892** [comment]
Can we merge this right away or it needs to pass via a Dev Call?

**Review by tridge — APPROVED** [review]

**Pull request merged**
