### PR TITLE
AP_Logger: fix logging on 256Mbit flash chips

### PR DESCRIPTION
**Pull request by shellixyz**
256Mbit flash chips :
* have more than 65535 pages so the page number doesn't fit into an unsigned 16bit integer
* need the addressing mode to be changed to be able to use 32bit addresses

### CODE REVIEW

**Comment by tridge** [comment]
I'm seeing valgrind errors on this when I disarm (and thus stop logging)
==13172== Syscall param pwrite64(buf) points to uninitialised byte(s)
==13172==    at 0x4BE76F4: pwrite (pwrite64.c:29)
==13172==    by 0x1C9D92: AP_Logger_SITL::BufferToPage(unsigned int) (AP_Logger_SITL.cpp:64)
==13172==    by 0x1C5C09: AP_Logger_Block::FinishWrite() (AP_Logger_Block.cpp:79)
==13172==    by 0x1C744D: AP_Logger_Block::io_timer() (AP_Logger_Block.cpp:629)
==13172==    by 0x1C7505: void Functor<void>::method_wrapper<AP_Logger_Block, &AP_Logger_Block::io_timer>(void*) (functor.h:88)
==13172==    by 0x1A5011: Functor<void>::operator()() const (functor.h:54)
==13172==    by 0x24BF53: HALSITL::Scheduler::_run_io_procs() (Scheduler.cpp:220)
==13172==    by 0x24980C: HALSITL::Scheduler::timer_event() (Scheduler.h:46)
==13172==    by 0x24A268: HALSITL::SITL_State::_fdm_input_step() (SITL_State.cpp:199)
==13172==    by 0x24A312: HALSITL::SITL_State::wait_clock(unsigned long) (SITL_State.cpp:209)
==13172==    by 0x24BAC9: HALSITL::Scheduler::delay_microseconds(unsigned short) (Scheduler.cpp:86)
==13172==    by 0x1BCED1: AP_Scheduler::loop() (AP_Scheduler.cpp:314)
==13172==  Address 0x4e42642 is 2 bytes inside a block of size 256 alloc'd
==13172==    at 0x483AA05: calloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==13172==    by 0x191FF7: AP_HAL::Util::malloc_type(unsigned long, AP_HAL::Util::Memory_Type) (Util.h:147)
==13172==    by 0x1C5931: AP_Logger_Block::AP_Logger_Block(AP_Logger&, LoggerMessageWriter_DFLogStart*) (AP_Logger_Block.cpp:20)
==13172==    by 0x1C22EA: AP_Logger_SITL::AP_Logger_SITL(AP_Logger&, LoggerMessageWriter_DFLogStart*) (AP_Logger_SITL.h:16)
==13172==    by 0x1C28BE: AP_Logger::Init(LogStructure const*, unsigned char) (AP_Logger.cpp:176)
==13172==    by 0x13F6ED: Plane::log_init() (Log.cpp:295)
==13172==    by 0x15EEE1: Plane::init_ardupilot() (system.cpp:105)
==13172==    by 0x135D80: Plane::setup() (ArduPlane.cpp:120)
==13172==    by 0x248ABE: HAL_SITL::run(int, char* const*, AP_HAL::HAL::Callbacks*) const (HAL_SITL_Class.cpp:183)
==13172==    by 0x1375E7: main (ArduPlane.cpp:694)
==13172==  Uninitialised value was created by a stack allocation
==13172==    at 0x1C728A: AP_Logger_Block::io_timer() (AP_Logger_Block.cpp:600)
==13172==

**Comment by tridge** [comment]
in case you aren't familiar with testing this in SITL, you can test the block logging backend with valgrind like this:
cd ArduPlane
../Tools/autotest/sim_vehicle.py -D -V --console
param set LOG_BACKEND_TYPE 4
param set AHRS_EKF_TYPE 10
arm throttle

**Comment by tridge** [comment]
looks like the problem is that PageHeader is not packed now, so it has a 16 bit uninitialised gap
which means uninitialised write in io_timer()
Swapping the order of FilePage and FileNumber and marking the structure PACKED fixes it. That will also make it take less space.

**Comment by shellixyz** [comment]
Thanks for the hint. I didn't know it was possible to run SITL with Valgrind. I'm not very familiar with SITL.

I made the modification you suggested and it did seem indeed to fix the issue. I don't really get why it does though.

**Comment by tridge** [comment]
thanks! I've squashed the two commits together. I'll merge once it passes CI

>  I don't really get why it does though.

the structure had two bytes of padding that were uninitialised on the stack, but get written to the device. We could have just zeroed the structure, but better to pack as it saves storage space

**Pull request merged**
