### PR TITLE
New parameter LOG_FILE_DSRMROT rotates dataflash logfile on disarm

### PR DESCRIPTION
**Pull request by peterbarker**
This parameter, when set, will break your flights (or drives...) up into separate dataflash logs, assuming you disarm between flights.

### CODE REVIEW

**Comment by OXINARF** [comment]
@peterbarker Does this replace #3067?

**Comment by peterbarker** [comment]
@OXINARF It doesn't replace #3067, but certainly interacts with it!  Note my comment mentioning that #3067 wouldn't permit rotate-on-disarm - what this patch set actually does :-)

As to #4556 - I thought a separate PR just for that was reasonable.  I didn't want to work through conflicts between the two, 'though, this including that patch in this one.

**Comment by OXINARF** [comment]
> It doesn't replace #3067, but certainly interacts with it! Note my comment mentioning that #3067 wouldn't permit rotate-on-disarm - what this patch set actually does :-)

Really? I looked briefly at the code and got the impression that it closed log at disarm (but wouldn't allow that and log disarmed). Anyway, that PR needs a rebase and with this one what does that one do that this doesn't?

> As to #4556 - I thought a separate PR just for that was reasonable. I didn't want to work through conflicts between the two, 'though, this including that patch in this one.

That is fine, but I think a warning about that in the initial post is good to let the person merging know about it :smiley:

**Comment by peterbarker** [comment]
@OXINARF OK, I think you're correct.  My apologies to @pepevalbe - I should have worked on top of his tree - I just didn't think of it.  I think tridge's LOG_DISARMED changes and these changes I think cover #3067

**Comment by peterbarker** [comment]
@WickedShell Your concerns on GPS information messages for #3067 are valid for this PR as well.

OTOH, those GPS messages already may not be present because the user did something which closed the first log, or because LOG_DISARMED wasn't set.

I suggest we could add something into the vehicle startup message writer function (e.g. https://github.com/ArduPilot/ardupilot/blob/master/ArduCopter/Log.cpp#L776) to emit information about the GPSs detected - `gps.Write_Log_Startup_Messages()`, perhaps.  Like format messages, parameters, mission items etc, any time a log is opened the GPS data will be emitted.

**Comment by WickedShell** [comment]
@peterbarker Agreed. That seems like a quite reasonable approach as well.

**Comment by peterbarker** [comment]
@WickedShell This PR implements some of my suggestion on getting the GPS detection data into the log: https://github.com/ArduPilot/ardupilot/pull/4584

**Comment by magicrub** [comment]
What's the status of this? Ready to merge in?

**Comment by peterbarker** [comment]
@magicrub Yes, ready to merge.

**Comment by OXINARF** [comment]
This is ready to merge, let's go!

**Comment by magicrub** [comment]
Found this PR lingering in a ready to merge state. Merged!

**Pull request merged**
