### PR TITLE
AP_Motors: bugfix motors enabled when there is no output allocation

### PR DESCRIPTION
**Pull request by jaxxzer**
Currently, motors write to servo channels, regardless of servo function allocation.

This has been resolved in master already.

### CODE REVIEW

**Comment by rmackay9** [comment]
Do we want to rely on the SERVOx_FUNCTION being set?  I know in master it is set but I'm not sure if we want that to be a requirement.  I'm just thinking about users who may have somehow set the SERVOx_FUNCTION to zero and the motors won't spin anymore.  I suspect this would happen to very few users but I'd like to at least warn them if we think this could happen.

By the way, what's the issue if we write to servo-channels without them having a function assigned?

**Comment by jaxxzer** [comment]
I prefer to have clearly defined behavior. If the servo function is 'Disabled', it should not mean 'we will write motor outputs to it, but only if no other channel has already been specified for this motor'.

> By the way, what's the issue if we write to servo-channels without them having a function assigned?

I think this is a problem for similar reasons as above.

The bigger issue is that both the servo library and the motor library are writing to the same output simultaneously. We discovered this (in Sub) by changing our frame configuration from one with 6 motors to one with 8 motors. We still had our servo7 configured for rc passthrough (writing 1100 to our motors [full reverse], 1500 is 'stopped' for our ESCs). Then the motor connected to servo 7 started spinning on reboot! Looking with a scope, the output was jumping between 1500 (motors library, disarmed state) and 1100 (rc passthrough). Because both libraries are writing to the motors, the ESC was able to initialize and execute the full reverse command.

While I did not observe the exact same thing in Copter (probably because of slight scheduling differences), the same problem is there, and this could potentially happen. This means that a motor could unexpectedly spin up when reconfiguring parameters or frame type. Beside that, the servo outputs from the actually assigned function are being overwritten by the motors library.

**Comment by rmackay9** [comment]
I'm not too keen to push this into Copter-3.5 because it doesn't seem to be a critical failure.  I haven't seen any complaints from users really.  So I'm going to go ahead and close this OK?  If this is the wrong judgement I'm happy to discuss again and re-open it.

**Comment by rmackay9** [comment]
I've created an issue to capture @OXINARF's suggestion: https://github.com/ArduPilot/ardupilot/issues/7354

**Comment by DavidIngraham** [comment]
Can we open this for consideration again for copter 3.6?

I'm definitely a fan of behavior being consistent with the user's parameter settings

**Pull request closed without merging**
