### PR TITLE
AP_Rangefinder: various enhancements and bugfixes

### PR DESCRIPTION
**Pull request by jschall**
- Fixes indexing of _drivers array in AP_RangeFinder
- Fixes bugs where users of AP_RangeFinder API would only loop to num_sensors(), when sensors are indexed by instance number.
- Adds _BUS parameter for I2C rangefinders, implements for LightwareI2C and MaxsonarI2CXL
- Reworks copter's rangefinder height estimation so that it estimates a terrain height. This allows it to properly dead-reckon between rangefinder measurements.

### CODE REVIEW

**Comment by amilcarlucas** [comment]
Flew nicely today on a copter, but was not been used for alt corrections, the DF logs look very nice though.

**Comment by amilcarlucas** [comment]
Can this one be rebased please ?

**Comment by peterbarker** [comment]
This is very, very conflicted - it would probably be faster to redo the work than to rebase.

@jschall Is there anything in here that we should really, really pick out and try to get into master?

**Comment by amilcarlucas** [comment]
@jschall friendly ping?

**Pull request closed without merging**
