### PR TITLE
Only control widest pulse for dshot and oneshot

### PR DESCRIPTION
**Pull request by andyp1per**

### CODE REVIEW

**Comment by andyp1per** [comment]
@tridge I think this change is important but I am not in a position to test right now.

**Comment by tridge** [comment]
@andyp1per yes, looks good, but needs testing.

**Comment by andyp1per** [comment]
Tested on PWM and DSHOT on MatekH743. Tested on PWM on Pixhawk1-1M with IO outputs

**Review by tridge — APPROVED** [review]

**Comment by rmackay9** [comment]
Once again, I'd like to ask that we always have some description in the PRs.  I'm trying to come up with release notes for 4.1.0-beta6 and having no description of the change makes this difficult.

**Pull request merged**
