### PR TITLE
AP_Periph: Change where the number of instances is determined

### PR DESCRIPTION
**Pull request by muramura**
I had added the protocol settings for instance 1 and instance 2 when the number of instances was 2.
I think I need the protocol settings for instance 1 when the number of instances is 1.

### CODE REVIEW

**Comment by magicrub** [comment]
The reason it's like this is because if you only have 1 single CAN port, then the protocol is hardcoded as UAVCAN. I'm in favor of closing.

**Comment by muramura** [comment]
PIXHAWK1 has a single CAN connector.
In this case, I think it is NG to be fixed to UAVCAN.
For example, if you want to use TOSHIBA CAN with PIXHAWK1, you cannot select it.

**Comment by muramura** [comment]
I did not understand the specifications. I'll close.

**Comment by magicrub** [comment]
For clarity, you'll need UAVCAN on a periph to configure it. It's required.

**Comment by muramura** [comment]
@magicrub san
Thank you for your comment.

**Pull request closed without merging**
