### PR TITLE
Add Autotest badge

### LINKED ISSUE #9589: Autotest: Add test badges to README
Since the autotest is too slow to run on every pull request, why not show it at least on the Readme page? It is important that it shows somewhere else than at http://autotest.ardupilot.org/, so people at least know when something is broken without going there.

As there are 26 tests right now, I propose we either group them all into something like  
Or group by vehicles/task
    

Any thoughts?

### PR DESCRIPTION
**Pull request by Williangalvani**
This adds badges for the Autotest results in the Autotest web interface itself and to our Readme. Hopefully this improves awareness of failing tests there.

Passing:
> passing test

Failing:
> failing test

The [badge](https://img.shields.io/badge/Autotest-1\2-red.svg) is downloaded from the [shields.io](https://shields.io) website into the `buildlogs` folder and is acessible at `/autotest-badge.svg` so we can point at it from our Readme.

PS: The Readme image will be broken until the Autotest runs with these changes.

Fix #9589

### CODE REVIEW

**Comment by magicrub** [comment]
oOoOooo nice!

**Comment by peterbarker** [comment]
How are we off for exception handling here e.g. unable to download badge...

**Comment by Williangalvani** [comment]
> How are we off for exception handling here e.g. unable to download badge...

Good point. I'm open for suggestions about how to handle that. I can think of either just leaving the link broken, or adding a placeholder image saying the badge could not be downloaded.

**Comment by jaxxzer** [comment]
> How are we off for exception handling here e.g. unable to download badge...

Wouldn't this be considered a failure in itself? Thus, seeing something like this:
passing test
serves the intended purpose of letting you know something is wrong with autotest ;).

**Comment by peterbarker** [comment]
On Fri, 8 Feb 2019, Jacob Walser wrote:

>       How are we off for exception handling here e.g. unable to download badge...
> 
> Wouldn't this be considered a failure in itself? Thus, seeing something like this:
> passing test
> serves the intended purpose of letting you know something is wrong with autotest ;).

Problem is that it kills the entire process and you get nothing.

Also, random people's servers going down isn't necessarily our problem :-)

**Comment by peterbarker** [comment]
On Fri, 8 Feb 2019, Willian Galvani wrote:

>       How are we off for exception handling here e.g. unable to download badge...
> 
> Good point. I'm open for suggestions about how to handle that. I can think of either just leaving the link broken, or adding a placeholder image saying
> the badge could not be downloaded.

Placeholder image.  The link wouldn't ordinarily "break" unless you were 
to explicitly remove it ('though I'm hoping to fix that at some stage).

**Comment by Williangalvani** [comment]
> The link wouldn't ordinarily "break" unless you were to explicitly remove it ('though I'm hoping to fix that at some stage).

I assumed that the autotest folder was renamed before the next text ran, so the next test could run in a clean folder.
But I do think the placeholder is cleaner, I'll do that.

**Comment by peterbarker** [comment]
On Fri, 8 Feb 2019, Willian Galvani wrote:

> I assumed that the autotest folder was renamed before the next text ran,
> so the next test could run in a clean folder.

I will desperately try not to destroy your illusions, then.  Desperately.

**Comment by Williangalvani** [comment]
@peterbarker I updated it to do some validation and handle exceptions, and simplified some things.

**Comment by peterbarker** [comment]
Looking good.  My only concern is with the user-agent thing.  Bypassing those checks they have doesn't seem like a netizenny thing to do, unless I'm misunderstanding something?

**Comment by Williangalvani** [comment]
> Looking good. My only concern is with the user-agent thing. Bypassing those checks they have doesn't seem like a netizenny thing to do, unless I'm misunderstanding something?

I'm not sure exactly why that happens. `wget`is able to download the badges just fine. it seems to be a ClouFlare tools against bots/scrappers. 
[Urllib uses "urllib/VVV" by default](https://docs.python.org/2/library/urllib.html#url-opener-objects) (where VVV is the version number), I guess that User-Agent is not in their whitelist.

I can switch to use wget to download it, or just use wget's User-Agent in urllib so we don't need another process to do it.

**Comment by khancyr** [comment]
can't we put those svg on our server and get them from our server instead of shields.io ?

**Comment by khancyr** [comment]
test svg : 
`
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="90" height="20">
    <linearGradient id="b" x2="0" y2="100%">
        <stop offset="0" stop-color="#bbb" stop-opacity=".1"/>
        <stop offset="1" stop-opacity=".1"/>
    </linearGradient>
    <clipPath id="a">
        <rect width="90" height="20" rx="3" fill="#fff"/>
    </clipPath>
    <g clip-path="url(#a)">
        <path fill="#555" d="M0 0h55v20H0z"/>
        <path fill="#e05d44" d="M55 0h35v20H55z"/>
        <path fill="url(#b)" d="M0 0h90v20H0z"/>
    </g>
    <g fill="#fff" text-anchor="middle" font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="110">
        <text id="main" x="285" y="150" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="450">autotest</text>
        <text x="285" y="140" transform="scale(.1)" textLength="450">autotest</text>
        <text id="result" x="715" y="150" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="250">pass</text>
        <text x="715" y="140" transform="scale(.1)" textLength="250">pass</text>
    </g>
</svg>
`
text and color modification with python : 
`
import xml.etree.ElementTree as ET
tree = ET.parse('autotest-pass-red.svg')
root = tree.getroot()
print(root[2][1].attrib['fill'])
root[2][1].set('fill', "#2eff00")
print(root[2][1].attrib['fill'])

print(root[3][3].text)
root[3][2].text="failed"
root[3][3].text="failed"
print(root[3][3].text)
tree.write('autotest-pass-red.svg')

`

**Comment by Williangalvani** [comment]
Good point @khancyr 
I often forget that svg are basically text, so I can just use a template and populate it with. I'll do it here.

**Comment by Williangalvani** [comment]
I updated it to use a base svg as a template and just change its colors and text.

**Comment by peterbarker** [comment]
Merged, thanks!

**Pull request merged**
