### PR TITLE
SRV_Channel: add "trim value" output function

### PR DESCRIPTION
**Pull request by dorovl**
In the official documentation of [Autopilot Output Functions](https://ardupilot.org/copter/docs/common-rcoutput-mapping.html) is reported:

> For normal operation, the **Disabled output function sets the output value of the channel to the trim value** (for example, if SERVO5_FUNCTION is 0 then channel 5 will output SERVO5_TRIM). The exception to this is when a MAVLink override of the channel or a mission servo set is used. So in some ways “disabled” could be called “mission-controlled”.

According to my tests, disabling the output function does not set the output value of the channel to the trim value. Therefore, I propose here a small correction.

I tried first to set the disabled output function to the trim value (https://github.com/ArduPilot/ardupilot/pull/14975) but it seems this had some side effects (don't passed the Travis CI tests). Therefore, I created a new independent "k_trim_value" constant.

I my case, I have a 6-channel radio and I need to use the remaining RC channel (number 6) for "in flight tuning", while the governor input signal (or even the gyro input gain) can as well be controlled by a fixed signal (set here to the trim value).

Please find below some tests:

Test

### CODE REVIEW

**Comment by IamPete1** [comment]
Are the changes outside of servo channels required? You are just be overriding them in any-case?

**Comment by dorovl** [comment]
> Are the changes outside of servo channels required? You are just be overriding them in any-case?

The changes outside SRV_Channel are not required. Just changing libraries SRV_Channel.h and SRV_Channel_aux.cpp is sufficient. You're right: it's better for these changes to keep a local scope. I will update the commit accordingly.

**Comment by Hwurzburg** [comment]
why add another output function, why not just fix it to match intended operation for disabled state? if its just a test issue, then lets address that instead of adding another output function @peterbarker  inputs?

**Comment by IamPete1** [comment]
@Hwurzburg I did ponder this, if we don't do it currently, it would be quite a exciting change of behavior. I think the goal here is just to output a constant PWM. There are a couple of other was to do this, scripting, pass through, setting min = max = trim ect. 

@dorovl I'm not sure how this is related to in flight tuning, can you describe the use case in more detail?

**Comment by Hwurzburg** [comment]
@IamPete1 doesnt it just output the min value? if so, I will change the docs to reflect reality until this gets resolved or changed, if ever

**Comment by dorovl** [comment]
> why add another output function, why not just fix it to match intended operation for disabled state? if its just a test issue, then lets address that instead of adding another output function @peterbarker inputs?

Yes, this is what I did in https://github.com/ArduPilot/ardupilot/pull/14975, but it didn't passed the Travis CI tests... I didn't really understood the relation between the Travis error and my changes. I presumed that that there was some kind of complex side effect. I'm going to open the pull request again, so we might look closer at the Travis CI tests.

**Comment by dorovl** [comment]
> @Hwurzburg I did ponder this, if we don't do it currently, it would be quite a exciting change of behavior. I think the goal here is just to output a constant PWM. There are a couple of other was to do this, scripting, pass through, setting min = max = trim ect.
> 
> @dorovl I'm not sure how this is related to in flight tuning, can you describe the use case in more detail?

Yes, in my case, I have a 6-channel radio. I'm very happy with this radio and don't want to change for a more expensive 8 channel radio/receiver. I flown the helicopter successfully by using all the 6 channels, but I want to free a RC channel to do "in flight tuning" (i.e. tuning PIDs values with the rotary knob of the radio). The channel for the governor just needs a constant PWM, therefore the idea is to use the remaining RC channel (number 6) for "in flight tuning", while the governor input signal (or even the gyro input gain) can as well be controlled by constant PWM signal (set here to the trim value).

**Comment by dorovl** [comment]
> @IamPete1 doesnt it just output the min value? if so, I will change the docs to reflect reality until this gets resolved or changed, if ever

According to my tests, in Copter master and Copter-4.0.3, if the servo function is "Disabled" then the value of the PWM is 0 (whatever the Min/Max/Trim values are).

**Comment by Hwurzburg** [comment]
yep...just checked in SITL myself...will update wiki now...

**Comment by Hwurzburg** [comment]
btw, here is an easy way to get SERVO6 set to 1500 with only 2uS of jitter....since that is your goal
1. assign its function to aileron, or elev, etc.
2. Set the servo6 max to 1501, min to 1499, trim to 1500....it will be 1499-1501 all the time...

**Comment by IamPete1** [comment]
I wonder if its the same on boards with a IOMCU. Setting to another function only works if the code is using that function.

**Comment by dorovl** [comment]
> btw, here is an easy way to get SERVO6 set to 1500 with only 2uS of jitter....since that is your goal
> 
> 1. assign its function to aileron, or elev, etc.
> 2. Set the servo6 max to 1501, min to 1499, trim to 1500....it will be 1499-1501 all the time...
>    you can set it to any value you wish to change the governors set point

Thank you for the tip! I tested also on master (on BeagleBone Blue hardware). In my case, depending on the Channel 5 function (set to Motor 1 or to Motor 2) the output is either 1511 or 1486. This is not enough precise. More, I suspect that this setup might generate some unnecessary CPU processing:

Test2

Test3

**Comment by dorovl** [comment]
> > why add another output function, why not just fix it to match intended operation for disabled state? if its just a test issue, then lets address that instead of adding another output function @peterbarker inputs?
> 
> Yes, this is what I did in #14975, but it didn't passed the Travis CI tests... I didn't really understood the relation between the Travis error and my changes. I presumed that that there was some subtle side effect. I'm going to open the pull request again, so we might look closer at the Travis CI tests.

Finally, https://github.com/ArduPilot/ardupilot/pull/14975 finished with  SITLCompassCalibration and Accelerometer Calibration testing errors.

**Comment by Hwurzburg** [comment]
Try it as aileron output..should match my results for full ail input range changes

**Comment by dorovl** [comment]
> Try it as aileron output..should match my results for full ail input range changes

Thank you @Hwurzburg. Unfortunately this does not work, as the "Aileron" function seems inactive for an helicopter. The the equivalent function called "Motor1", actuates the cyclic command by tilting the swashplate so that the blade pitch is cyclically varied between fore and aft. Because of the gyroscopic precession of the rotor, Motor1 acts directly on the rotor's roll axis.

Test4

**Comment by Hwurzburg** [comment]
sorry, have not used Trad Heli...was basing the selection on plane....
@bnsgeyer Bill, why does that output not obey the min/max limits? can you suggest an output functionin Trad heli that will constrain its value to min/max such there is only a the normal 5us or so of change so that it can be the governor setpoint?

**Comment by IamPete1** [comment]
@Hwurzburg It is just that aileron is never output in by heli. So it is left at the initial value of 0. Something must call set_output_scaled() on the function for it ever to move from 0.

**Comment by dorovl** [comment]
> sorry, have not used Trad Heli...was basing the selection on plane....
> @bnsgeyer Bill, why does that output not obey the min/max limits? can you suggest an output functionin Trad heli that will constrain its value to min/max such there is only a the normal 5us or so of change so that it can be the governor setpoint?

Thanks @Hwurzburg Henry for asking Bill. What is also important is a function that does not consumes any CPU time and also hasn't any jitter. The governor's setpoint affects the rotor speed, so I think it has to be quite accurate (5 us of jitter seems to me a bit too much). Maybe the proposed solution is not so bad... 🙂

**Comment by bnsgeyer** [comment]
> Yes, in my case, I have a FlySky FS-T6 6-channel radio. I'm very happy with this radio and don't want to change for a more expensive 8 channel radio/receiver. I flown the helicopter successfully by using all the 6 channels, but I want to free an RC channel for "in flight tuning" (i.e. tuning PIDs values with the rotary knob of the radio while flying). The channel for the governor just needs a constant PWM, therefore the idea is to use the remaining RC channel (number 6) for "in flight tuning", instead of the governor.

@dorovl  I don't think you understand how the code works.  Regardless of having a constant output from a servo port on the flight controller, Heli's require at least 6 RC channels on your transmitter/receiver as input to the flight controller.  They are
RC Channel 1 - aileron (roll control)
RC Channel 2 - elevator(pitch control)
RC Channel 3 - throttle (collective control)  this confuses many people because the throttle RC channel directly controls collective pitch for heli's. Depending on your rotor speed control (RSC) mode, it could also change throttle based on collective pitch which is the throttle curve mode.
RC Channel 4 - rudder (tail rotor)
RC Channel 5 - flight mode
RC Channel 6 - Motor Interlock - this is required for heli to turn on/off the motor and if you have set RSC mode to passthrough will use the PWM and push it straight to the Servo channel assigned as HeliRSC

So it is not possible to my knowledge to do what you want to do with a 6 channel transmitter.

**Comment by bnsgeyer** [comment]
> sorry, have not used Trad Heli...was basing the selection on plane....
@bnsgeyer Bill, why does that output not obey the min/max limits? can you suggest an output functionin Trad heli that will constrain its value to min/max such there is only a the normal 5us or so of change so that it can be the governor setpoint?

@Hwurzburg  Henry, the only servo outputs that will not allow the user to change the min and max are servo channels assigned to motors 1, 2, and 3.  These are swashplate servos and I have to keep their range at 1000 - 2000 to provide consistent swashplate control.  As for other servo functions, the only other ones heli uses are motor 4 (tailrotor), heliRSC, and helitailrsc.  The code does not make servo outputs to any others, except the RC passthroughs I guess.

**Comment by dorovl** [comment]
> > Yes, in my case, I have a FlySky FS-T6 6-channel radio. I'm very happy with this radio and don't want to change for a more expensive 8 channel radio/receiver. I flown the helicopter successfully by using all the 6 channels, but I want to free an RC channel for "in flight tuning" (i.e. tuning PIDs values with the rotary knob of the radio while flying). The channel for the governor just needs a constant PWM, therefore the idea is to use the remaining RC channel (number 6) for "in flight tuning", instead of the governor.
> 
> @dorovl I don't think you understand how the code works. Regardless of having a constant output from a servo port on the flight controller, Heli's require at least 6 RC channels on your transmitter/receiver as input to the flight controller. They are
> RC Channel 1 - aileron (roll control)
> RC Channel 2 - elevator(pitch control)
> RC Channel 3 - throttle (collective control) this confuses many people because the throttle RC channel directly controls collective pitch for heli's. Depending on your rotor speed control (RSC) mode, it could also change throttle based on collective pitch which is the throttle curve mode.
> RC Channel 4 - rudder (tail rotor)
> RC Channel 5 - flight mode
> RC Channel 6 - Motor Interlock - this is required for heli to turn on/off the motor and if you have set RSC mode to passthrough will use the PWM and push it straight to the Servo channel assigned as HeliRSC
> 
> So it is not possible to my knowledge to use the tuning feature with a 6 channel transmitter.

@bnsgeyer Bill, thank you for replying! You're right, but I have missed some clarifications:

The helicopter is a nitro engine vintage helicopter (Raptor 30 v1).
At the moment, the flight mode is fixed on "Stabilize". In the current setup the  flight mode can be only be changed from the GCS (ground control station). I think this is not a problem for the time being, as I'm still in tuning phase. Once the tuning in "Stabilize" mode would be achieved, the tuning knob would be reassigned to flight mode.

**This is how my RC Radio is setup:**

- RC Channel 1 - aileron (roll control)
- RC Channel 2 - elevator (pitch control)
- RC Channel 3 - throttle (linear curve between stick and throttle); there is a "throttle hold" switch on the radio preventing the throttle to rise accidentally
- RC Channel 4 - rudder (tail rotor)
- RC Channel 5 - in flight tuning (tuning knob)
- RC Channel 6 - collective pitch (linear curve between stick and collective pitch)

It's more or less based on the recommendations from Chris Olson's ArduPilot TradHeli Setup, Video 4.

**This is how the flight controller is set up:**

On the receiver PWM output, is a PWM → SBUS converter. Some PPM wires are swapped (remapped) like this:

- RC Channel 3 → RC Channel 8
- RC Channel 6 → RC Channel 3

The Rotor's Speed Control mode is: "Throttle Curve"
The Throttle Curve is: 25, 50, 60, 70, 100.
The Stabilize Collective Curve is: 0, 52, 62, 100.

And for the servos functions:

- Servo 1 - Motor1 - aileron (roll control)
- Servo 2 - Motor2 - elevator (pitch control)
- Servo 3 - Motor3 - collective pitch
- Servo 4 - Motor4 - rudder (tail rotor)
- Servo 5 - Trim value - governor setpoint (constant function, NEW)
- Servo 6 - RCIN5
- Servo 7 - not used
- Servo 8 - HeliRSC

Remark: Instead of setting Servo 6 to RCIN5, it might also be wire-swapped.

The GCS communicates with the flight controller with a RFD 868x Long Range Telemetry Modem (I use WiFi as backup link). If I really need a supplementary channel, it might be possible to use the RFD 868x PPM Passthrough (making a PWM to PPM converter with some Arduinos Nano).

I already flown the helicopter in a similar setup (excepting that RC Channel 5 was the governor setpoint in RCPassThru mode).

Unfortunately, by trying to find the optimal tuning, I had a small crash. After analysis I found:
- Excessive vibrations
- Bad dynamic response of analog servos at RC_SPEED 125 Hz (only the rudder servo is digital)
- The necessity of a button to tune from the radio: in case of a dangerous tuning range, the pilot can immediately turn the knob back and land the helicopter safely.

Therefore, for the next flight the following steps are planned:
- Set the RC_SPEED 50 Hz for all servos (done)
- Increase the flight controller suspension damping: make the shock mounts softer (done)
- Make tuning from the radio (done in my own version)
- Analysis of the Shock Response Spectrum (SRS) - we suspect that the box of the flight controller might induce some resonance frequencies
- The helicopter will be first flown in manual mode (RCPassThru on channel 1, 2, 3 and 6 + radio throttle curve set to : 29, 45, 60, 72, 100). In this phase, the vibrations levels will be registered and analyzed
- If vibrations levels are acceptable, then the manual mode will be disabled (cancel RCPassThru) and in-flight tuning of PIDs would be done from the RC button (tuning knob)
- Once the tuning achieved in "Stabilize" mode, the tuning knob channel would be reassigned to flight mode

This is why I thought that this "trim_value" function might be useful also to other people, if only to control the range of a servo without the remote control ON, set the external tail gyro gain, etc.

**Comment by bnsgeyer** [comment]
@dorovl please move your latest comment to a post on the tradheli thread of the discuss website. I see some problems with your set up and it is better to discuss how to fix your set up on the discuss website rather than here. I will read through your post in more detail but at first glance I see some big issues with your set up of collective and throttle channels.

**Comment by dorovl** [comment]
> @dorovl please move your latest comment to a post on the tradheli thread of the discuss website. I see some problems with your set up and it is better to discuss how to fix your set up on the discuss website rather than here. I will read through your post in more detail but at first glance I see some big issues with your set up of collective and throttle channels.

Thank you @bnsgeyer Bill, it has been moved here: https://discuss.ardupilot.org/t/set-up-of-collective-and-throttle-channels/60062

**Pull request closed without merging**
