### PR TITLE
Move Frsky Telemetry up into GCS - the base telemetry class

### PR DESCRIPTION
**Pull request by peterbarker**
We could rename AP_GPS to AP_Telemetry and `gcs()` to `telem()`

Only Rover has been moved to it.  I expect the other vehicles to not compile ATM.

Currently based on top of a separate PR which makes Frsky use singletons.

### CODE REVIEW

**Comment by OXINARF** [comment]
@peterbarker What's your view for the future of AP_GCS/AP_Telemetry (telemetry is more generic, but I think both names work)? Right now, the GCS class is very MAVLink connected/dependent which is precisely one of the reasons why we have rejected other protocols before.

Let me know when this is ready for review.

**Comment by peterbarker** [comment]
@OXINARF Getting everything hooked in from the GCS object itself is probably the first step.

That's basically being generally happy with frsky being a member of the GCS class rather than on each vehicle separately, even if there are bits and pieces that could be done better.

This will basically mean our telemetry backends will all kind of smell a little of mavlink for the time being.  With FRsky that seems to actually make sense as various bits of mavlink seem to have been incorporated into the protocol.  I'm looking at things like custom_mode() and frame_type() here.

How we reshape things in `gcs()` in the long term is an interesting issue.  Having mavlink as a pseudo-interop layer may not be a bad way to leave things.  It would save all of the telemetry objects having to know what each individual vehicle mode is, for example.

**Comment by peterbarker** [comment]
@OXINARF I should also mention I'm hoping to get rid of FRsky's looking at Copter's `ap` flags struct/uint32_t union thing.  That's just evil.  Hopefully it can be replaced with calls onto the gcs() object initially - for example, `vehicle_initialised()`.  I can't see any neat way of doing `simple` and `supersimple` in a nice way, however.

**Comment by lvale** [comment]
wasn't the general idea to have a single telemetry library with several backends, FrSky, Mavlink, HoTT, others...

**Comment by peterbarker** [comment]
On Tue, 12 Feb 2019, Luis Vale Gonçalves wrote:

> wasn't the general idea to have a single telemetry library with several
> backends, FrSky, Mavlink, HoTT, others...

That's what I'm proposing gcs() also known as "class GCS" is!

This PR makes it such that GCS now has bot has a set of mavlink 
backends and a single FrSky backend.

I don't think it would be much work to pull down the Devo stuff, for 
example.

**Comment by OXINARF** [comment]
@peterbarker 

> That's basically being generally happy with frsky being a member of the GCS class rather than on each vehicle separately, even if there are bits and pieces that could be done better.

I don't see why someone wouldn't be happy about this. We've talked so many times about an AP_Telemetry library and this was always the concept.

> With FRsky that seems to actually make sense as various bits of mavlink seem to have been incorporated into the protocol.

Into the C&T protocol I should clarify. Even then, I wouldn't say it is incorporated, it's just the easy way to get stuff was from MAVLink given it's so embedded everywhere.

> How we reshape things in `gcs()` in the long term is an interesting issue. Having mavlink as a pseudo-interop layer may not be a bad way to leave things. It would save all of the telemetry objects having to know what each individual vehicle mode is, for example.

I've got to strongly disagree there. If someone wants to add a new protocol, having to go through MAVLink as an interop layer is usually messy and we've seen that before on some proposed protocols.

I'm not sure I understand your example either: why would the telemetry object need to know each individual vehicle mode? I understand that MAVLink support has been made ArduPilot dependent by having the ArduPilot vehicle modes defined in the protocol spec, but many other protocols that could be used would be ArduPilot independent and shouldn't need to know the modes.

> I should also mention I'm hoping to get rid of FRsky's looking at Copter's `ap` flags struct/uint32_t union thing. That's just evil. Hopefully it can be replaced with calls onto the gcs() object initially - for example, `vehicle_initialised()`. I can't see any neat way of doing `simple` and `supersimple` in a nice way, however.

I absolutely agree and I think that should also be a design idea of the AP_GCS/AP_Telemetry library: each telemetry object should ask the frontend for things and not invade each vehicle to get stuff it wants.

For simple and supersimple (and other things that are vehicle dependent) I would make one of two things:
- make methods to validate if such thing is available, e.g. `bool is_simple_mode_available()`
- make the get methods return a bool for whether it is valid or not, e.g. `bool get_simple_mode(bool &is_in_simple_mode)`

I prefer the second one because it makes it less methods, but I think they both work.

**Comment by peterbarker** [comment]
On Wed, 13 Feb 2019, Francisco Ferreira wrote:

>       How we reshape things in gcs() in the long term is an
>       interesting issue. Having mavlink as a pseudo-interop layer
>       may not be a bad way to leave things. It would save all of the
>       telemetry objects having to know what each individual vehicle
>       mode is, for example.
> 
> I've got to strongly disagree there. If someone wants to add a new
> protocol, having to go through MAVLink as an interop layer is usually
> messy and we've seen that before on some proposed protocols.

The sensor bits are an interesting talking point here, I think.  Worth 
considering since I'm tidying those up a bit now and then.  Do we retain 
the mavlink-concept of present-enabled-health?  This is an example of 
where the C&T protocol has been influenced by mavlink (some would say just 
"derived from", perhaps?)

> I'm not sure I understand your example either: why would the telemetry
> object need to know each individual vehicle mode? I understand that

Well... C&T just pass the custom mode through verbatim.  But it's not a 
stretch to think a mode name, for example.

> I absolutely agree and I think that should also be a design idea of the
> AP_GCS/AP_Telemetry library: each telemetry object should ask the frontend
> for things and not invade each vehicle to get stuff it wants.
> 
> For simple and supersimple (and other things that are vehicle dependent) I
> would make one of two things:
>
>  *  make methods to validate if such thing is available, e.g. bool
>     is_simple_mode_available()
>  *  make the get methods return a bool for whether it is valid or not,
>     e.g. bool get_simple_mode(bool &is_in_simple_mode)
> 
> I prefer the second one because it makes it less methods, but I think they
> both work.

Yep, that sort of thing is the best I'd come up with, too.

**Comment by peterbarker** [comment]
Oh, should also mention on the "getting vehicle-specific information" thing that I'd considered doing what we do for GCS_MAVLINK - subclass it on a per-vehicle basis.

Still mulling that over - it would be nice to have a generic `GCS_Backend` / `Telemetry_Backend` base class, but without multiple inheritance that is problematic when you're already subclassing down the vehicle line.

It would also be complete overkill for what we're doing with frsky and devo.

**Comment by peterbarker** [comment]
I've pushed up patches which also move the Devo telemetry object up from Rover to GCS.

Concept seems to hold so far, and it's a little neater in that custom mode is coming from a single callback rather than being poked in to the telemetry libraries in different ways.

Note that I don't actually have any hardware to test these changes on :-)

**Comment by OXINARF** [comment]
@peterbarker 

> The sensor bits are an interesting talking point here, I think. Worth considering since I'm tidying those up a bit now and then. Do we retain the mavlink-concept of present-enabled-health? This is an example of where the C&T protocol has been influenced by mavlink (some would say just "derived from", perhaps?)

I think that concept is quite broken, we've had some discussions before on what some of those bits mean - and if not even the ArduPilot developers have it clear, how would, for example, a ROS GCS developer know? On the other hand, it might get tricky if we remove the concept (as is) from AP_Telemetry since we would then need to figure it out on MAVLink side and all vehicles are different on doing it.

>Oh, should also mention on the "getting vehicle-specific information" thing that I'd considered doing what we do for GCS_MAVLINK - subclass it on a per-vehicle basis.

This would resolve the tricky part I mentioned above. I think that in general though we should try to avoid subclassing the telemetry backends into vehicle versions.

>Still mulling that over - it would be nice to have a generic `GCS_Backend` / `Telemetry_Backend` base class, but without multiple inheritance that is problematic when you're already subclassing down the vehicle line.

Why would it be a problem? As an example: GCS_MAVLink inherits from Telemetry_Backend, GCS_MAVLink_Copter inherits from GCS_MAVLink.
It would then be a matter of AP_Telemetry constructor calling a `init_backends` method that could be overridden in AP_Telemetry_Copter.

>It would also be complete overkill for what we're doing with frsky and devo.

Agreed, although for FrSky that could be another way for the simple/supersimple thing.

**Comment by peterbarker** [comment]
Marking as devcall for discussion.  This might be useful: https://github.com/ArduPilot/ardupilot/pull/10499/files#diff-d0bc7d76933a4c9eddfe41dff66b7574L85 and https://github.com/ArduPilot/ardupilot/pull/10499/commits/c83ff1f59d1c5ed3135cec821d4d5621d0c12368#diff-4f15a04337259328467a92d8e35bab2fR1975

**Comment by peterbarker** [comment]
Discussed at devcall.  People generally happy with the concept.

**Comment by peterbarker** [comment]
Rebased and tested to work.

**Comment by lvale** [comment]
@peterbarker I've asked @yaapu to test it also, because he has some debugging on the radio that can help.

Alex :)

**Comment by yaapu** [comment]
@lvale , @peterbarker  I found a minor issue with the ap_status offsets in Ap_Frsky_Telem.h line 88

```
#define AP_SIMPLE_OFFSET            3
#define AP_SSIMPLE_OFFSET           4
#define AP_FLYING_OFFSET            6
```
these should be

```
#define AP_SIMPLE_OFFSET            5
#define AP_SSIMPLE_OFFSET           6
#define AP_FLYING_OFFSET            7
```

**Pull request merged**
