### PR TITLE
Don't share IMU DMA on MatekH743 to avoid SPI DMA contention

### PR DESCRIPTION
**Pull request by andyp1per**
This massively reduces DMA contention for me for this board - 3 channels go from 30% to essentially zero. I think contention is responsible for many of the issues seen with this board.

### CODE REVIEW

**Comment by tridge** [comment]
do we lose DMA on any peripherals with this change? check hwdef.h before and afterwards

**Comment by andyp1per** [comment]
No, no loss of DMA on any peripherals

**Comment by olliw42** [comment]
wouldn't it make more sense to use DMA where it is really useful/needed such as in the high speed stuff like the IMUs and rather not use it for anything else/all the low speed stuff
it wouldn't be the first DMA issue you had in the last years ...
could be time to rethink the "always-use-DMA" policy

**Comment by andyp1per** [comment]
Problem is we can't tell - for instance CRSF @416kb DMA is a requirement, but we don't know which UART the user is going to connect to. We're really only talking about UARTs at this point - its currently a ChibiOS requirement for I2C and for ADC, its our requirement for dshot and is a must for SPI. This is why tridge wants to be able to assign DMA dynamically to UARTs.

**Comment by tridge** [comment]
>  could be time to rethink the "always-use-DMA" policy

it is a bit tricky as decisions on DMA for SPI and I2C are compile time in current ChibiOS structure, and it is all or nothing. We'd need some fairly extensive ChibiOS changes to make that runtime

**Pull request merged**
