### PR TITLE
Plane: correct description of Q_TAILSIT_MOTMX param

### PR DESCRIPTION
**Pull request by Hwurzburg**

### CODE REVIEW

**Review by kd0aij — APPROVED** [review]
LGTM

**Review by IamPete1 — APPROVED** [review]

**Comment by magicrub** [comment]
Does this actually need a dev call topic label?

**Review by magicrub — APPROVED** [review]

**Comment by Hwurzburg** [comment]
> Does this actually need a dev call topic label?

not if you merge it (wink)...Tridge is swamped for the next week or more, and comes up for air at the calls...you and he are the only plane guys with merge rights, correct?

**Comment by magicrub** [comment]
Yes, but I won't merge it if you tag it with the devcall because that usually means you're requesting a discussion. If it didn't need discussion then please remove the label and I'll merge it.

**Pull request merged**
