### PR TITLE
.github: migrate semaphore to github actions

### PR DESCRIPTION
**Pull request by khancyr**
We could probably remove 
bebop, erlebrain2, pxfmini, pxf, and navio build . There are discontinued since long ago, I don't think there is much user left

### CODE REVIEW

**Comment by WickedShell** [comment]
Do you have different python enviroments somewhere in the github actions path? Explicitly forcing one CI to python2 and one to python3 in the past has been very valuable, and losing that would be bad.

**Comment by khancyr** [comment]
Besides of maintaining capabilities with old Linux distribution, I don't see what supporting python2 will bring.
But I think a way to have one run with python 2.

**Comment by WickedShell** [comment]
> Besides of maintaining capabilities with old Linux distribution, I don't see what supporting python2 will bring.

So I'd like to agree with you, but unless I missed a patch coming in to fix it, our DMA allocation is different under Python 2 and Python 3, which results in different builds. This is particularly critical as I've had problems on CubeOrange when built with Python 2 as soon as I push the baud rate up at all on Serial 3, it kills off telemetry throughput on Serial 1. So Python2 maintenance is actually painfully important right now.

**Comment by khancyr** [comment]
Having CI doing python2 compile test won't change anything on this matter. We should be fixing the issue on python3. And then drop py2

**Comment by tridge** [comment]
> This is particularly critical as I've had problems on CubeOrange when built with Python 2 as soon as I push the baud rate up at all on Serial 3, it kills off telemetry throughput on Serial 1

my recent shared DMA patch to the serial driver should fix that I think.

**Comment by amilcarlucas** [comment]
@WickedShell I think you meant:

"This is particularly critical as I've had problems on CubeOrange when built with Python **3** as soon as I push the baud rate up at all on Serial 3, it kills off telemetry throughput on Serial 1."

Is that correct?

**Comment by WickedShell** [comment]
> @WickedShell I think you meant:
> 
> "This is particularly critical as I've had problems on CubeOrange when built with Python **3** as soon as I push the baud rate up at all on Serial 3, it kills off telemetry throughput on Serial 1."
> 
> Is that correct?

Yes, sorry.

**Comment by tridge** [comment]
we need to do at least one stm32 build with py2, and drop the building with the old 6.3 compiler for 1M flash boards

**Pull request merged**
