### PR TITLE
adding support for volz servos serial protocol

### PR DESCRIPTION
**Pull request by EViationGuy**
Hi 

proceeding PR 7109:
https://github.com/ArduPilot/ardupilot/pull/7109

last pull request lost connection to my repository, so i took fresh master, added all changes and committed with comments, tested on pixhawk with VOLZ DA26 and DA30.

lest try to finish this merge.

### CODE REVIEW

**Comment by EViationGuy** [comment]
Ran Make px4-v3, ended with "PX4 ArduPlane Firmware is in ArduPlane-v3.px4"

not sure why it failed on travis-ci

**Comment by tridge** [comment]
i've rebased this on master

**Comment by tridge** [comment]
after discussion on dev call today this has been merged

**Comment by tridge** [comment]
Note that @peterbarker has suggested changing the instance method on AP_SerialManager like this:
https://github.com/ArduPilot/ardupilot/commit/298910fb7e9f9caddec8cf0d557fbc0061f3429e

**Pull request merged**
