### PR TITLE
Math - residual improvements

### PR DESCRIPTION
**Pull request by dgrat**
@lucasdemarchi 
Since most of the commits are pushed already, here are the remaining commits.
These include:
  - radians() and degrees() are now template functions and I took care that the right function (<float>) is used in the vehicle code
  - MIN()/MAX() are now called min()/max()
  - linear_interpolate() is now a template function and I added a zero check ..
  - the last commit inherits the "DBL_MATH" part and splits AP_Math into the two backends

As in the previous PR, the binary size is optimized. So adding these function will further reduce it. 
What do you think?

### CODE REVIEW

**Comment by OXINARF** [comment]
@dgrat I changed the title so that it doesn't seem like v8 didn't go in.
I think there are quite a few things we don't want here, but I'll let Lucas comment first.

**Comment by dgrat** [comment]
@lucasdemarchi 
I wonder why SITL build failed. Locally, it was working fine ..

**Comment by OXINARF** [comment]
@dgrat The build was fine, it was the SITL testing (flying) that failed. I've just relaunched it to see if it happens again.

**Comment by dgrat** [comment]
@OXINARF 
Still: 
```
Created /home/travis/build/ArduPilot/buildlogs/ArduCopter-test.tlog.gpx with 73773 points
/bin/sh: 1: gpsbabel: not found
	zip warning: name not matched: /home/travis/build/ArduPilot/buildlogs/ArduCopter-test.tlog.kml

zip error: Nothing to do! (/home/travis/build/ArduPilot/buildlogs/ArduCopter-test.tlog.kmz)
Traceback (most recent call last):
  File "/home/travis/.local/bin/mavflightview.py", line 10, in <module>
    from MAVProxy.modules.mavproxy_map import mp_slipmap, mp_tile
  File "/home/travis/.local/lib/python2.7/site-packages/MAVProxy/modules/mavproxy_map/__init__.py", line 11, in <module>
    from MAVProxy.modules.mavproxy_map import mp_elevation
  File "/home/travis/.local/lib/python2.7/site-packages/MAVProxy/modules/mavproxy_map/mp_elevation.py", line 12, in <module>
    import numpy
ImportError: No module named numpy
```

**Comment by OXINARF** [comment]
@dgrat I saw that, I don't know why it happens. The main issue is before that and has been identified. I'm going to look at this more because this might be a different one.

**Comment by OXINARF** [comment]
@dgrat I looked at it and (with the current issue we have in Copter) the EKF variance should be getting high and it isn't. Also it should be disarming motors and it isn't. I'm not sure how this is related to this PR, but since this happened twice, we need to be careful before bringing this in.

**Comment by lucasdemarchi** [comment]
I see several things here that I don't see myself applying:
  - renaming MIN and MAX
  - replace converter functions in a single PR - I actually prefer the non-template versions.

Adding the double version. While I don't see a big problem with adding I'm now a bit skeptical on its benefit.

**Comment by dgrat** [comment]
- The capitals don't really fit to the other function names.
 - The radian()/degrees() commit resolves some ambigious macros ToRad() ..
 - The other implementation will hopefully replace later the current one

**Comment by lucasdemarchi** [comment]
> The capitals don't really fit to the other function names.

but it conflicts with min/max from std

> The radian()/degrees() commit resolves some ambigious macros ToRad()

couldn't review it yet, but could you move radian/degrees change to their own commit?

**Comment by dgrat** [comment]
actually not, because of the namespace.

**Pull request closed without merging**
