### PR TITLE
AP_HAL: Fixed and updated RCInput example.

### PR DESCRIPTION
**Pull request by hiro2233**
Renamed max_channels to max_channels_display and use it max channels numbers for display values, it's for understand how RCInput works internally and prevent confusions for developers.
Added some code for prevent outbound array.
Added comments and fixed some code style.

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
@hiro2233 we don't accept PR with merge commits. Instead of doing the merge, could you rebase on master branch? Thanks.

**Comment by hiro2233** [comment]
@lucasdemarchi ok, i will rebase. Thanks in advance.

**Comment by hiro2233** [comment]
@lucasdemarchi please check, reworked. Thanks.

**Comment by lucasdemarchi** [comment]
Applied, thanks!

**Pull request closed without merging**
