### PR TITLE
RC_Channels logs input; add option to log at consumption rate

### PR DESCRIPTION
**Pull request by peterbarker**
At the moment each of our vehicles logs RC input @10Hz.

This PR moves responsibility for logging into the RC_Channels library.

By default logging continues to be done @10Hz, however if a new `LOG_CONSUMPTION` `RC_OPTIONS` bit is set we instead log at the rate at which we copy from the hal layer into the RC_Channels layer.

This is on a real Rover - the bit is set part-way through this graph:

image

Bouncing between 25Hz and 50Hz is the beat frequency for calls to `RC_Channels::read_input` and input parsed from the receiver.

### CODE REVIEW

**Comment by peterbarker** [comment]
This is a real Plane:
image

(you can see where the option is set....)

**Comment by peterbarker** [comment]
And a Solo:

image

**Comment by peterbarker** [comment]
There are 39 bytes in an `RCIN` message (3+8+14*2) (header+TimeUS+channels).

At 10Hz that's 390bytes/second.  Moving to 50Hz (as in the Plane example above) means an additional ~1600 bytes/second of logging, which is not inconsiderable.

**Comment by rmackay9** [comment]
I haven't really checked this PR thoroughly but just quickly, I think we can do better than the word "consumption" both for the function name and the parameter bit.  "consumption" seems like it would be related to something consuming the logs.  How about just "fast"? LOG_RC_FAST gets the point across I think.  We're attempting to log as fast as possible which is the rate at which the raw RC samples are arriving from the receiver.

**Comment by peterbarker** [comment]
@rmackay9 that's exactly what we're *not* doing here.

We're *not* logging these at the rate the receiver is producing them - we're logging at the rate that the `RC_Channels` library is sampling from the hal.  The receiver could be providing RC at 1kHz - but we simply don't care about that :-)

I'm not a great fan of "fast" - in other places in our code that also has a specific meaning - it's 400Hz.

We also can't use "raw" - as that's used in another sense for logging in RC, and it's not even the rate at which the hal can provide RC :-)

Still open to better names - but I don't think "fast" fits" :-)

**Comment by rmackay9** [comment]
OK, well, let's think of another name then.  I also thought of "raw" but then that  an be confused with the type of data rather than the rate.  As a hint, we should be looking for an adjective I think.  Not a verb or noun.

**Comment by peterbarker** [comment]
On Thu, 27 Aug 2020, Randy Mackay wrote:

> OK, well, let's think of another name then. I also thought of "raw" but then that an be confused with the type of data rather than the rate. As a hint, we
> should be looking for an adjective I think. Not a verb or noun.

"full" was suggested.

**Comment by rmackay9** [comment]
@peterbarker "full" is an adjective at least so it's not too bad.  TBH, I think "fast" is better still but both are ok.

**Pull request closed without merging**
