### PR TITLE
AP_BattMonitor: NFC improve coments

### PR DESCRIPTION
**Pull request by amilcarlucas**
The history got wiped in the previous commit anyway. This one just improves documentation.

### CODE REVIEW

**Comment by rmackay9** [comment]
Merged some of the changes.  I thought the period in the middle was a bit weird so I didn't merge those lines.

**Comment by amilcarlucas** [comment]
The SI documentation, says that that . belongs there.
This is NOT my personal preferences. This is part of the international standard.

**Comment by WickedShell** [comment]
Yeah at the end of the day I don't think a lot of these are better. This is
why I didn't make the changes originally. The periods are pointless and
hurt readability. These are not better, and I don't like them. I'm aware
they may be SI but it is not clearer. Sorry but I don't like this type of
change.

**Comment by amilcarlucas** [comment]
I do not understand why `Wh` is more understandable than `Watt.hours`.
Am I the only one that does understand it ????

Should we also add to the code guide that the maintainer can overwrite international standards.
I know that it was been an unwritten rule untill now. But I think it should be made more clear and explicit.

**Comment by rmackay9** [comment]
I don't think it's correct English when there's a period in the middle like that.  Maybe some group of SI people think it's cool but for most of us it's just weird.

**Comment by WickedShell** [comment]
@amilcarlucas look this is just noise. Adding comments that say something is in "microseconds" on a field already detonated as a timestamp that has the `_micros` suffix is pointless noise. It was already well documented what it was, and if that wasn't understandable then I'm afraid you shouldn't be editing code.

Similarly the internal variables and comments are littered with things like "wh" because that is the normal unit and abbreviation to use. It's to the point, in the context it's unambiguous and it convey's it correctly. Comments are not written as full sentences, and are not expected to be read that way. Adding things like "Watt.hours" is simply more verbose, not useful later in the code. This type of change is simply busy work. Along the same line, it may not be correct as "amps" or "volts" but there is not a question what unit you are referring to. It's unambiguous, it matches the normally used terminology. This type of PR has not aided the readability for most people, and actually in places makes it much more confusing.

**Pull request closed without merging**
