### PR TITLE
Allow to use sparse-endian.h everywhere

### PR DESCRIPTION
**Pull request by lucasdemarchi**
Tested on PX4 build for both waf and make.  Changes were made for qurt/qflight, but it needs some love^Wtest since it was already broken and there's no easy way to test the changes.

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
@lgywata with this applied your PR builds on PX4.

**Comment by mbelluzzo** [comment]
Lgtm

**Comment by lucasdemarchi** [comment]
Applied.

**Comment by EwingKang** [comment]
Hello, 
This update in [bytespap.h](https://github.com/ArduPilot/ardupilot/blob/b9f65996bcc5fd7a8b0a0d7146bebefd745ab4a6/libraries/AP_Common/missing/byteswap.h) seems to break the px4 toolchain on windows.
cxx error about missing __builtin_bswap16

> missing/byteswap.h:11:42: errror: '__builtin_bswap16' was not declared in this scope compilation 
> terminated`  due to -Wfatal-errors. 
I'm currently using [toolchaini v14](http://ardupilot.org/dev/docs/building-px4-with-make.html) as stated on the official website.
Someone says it's because of the outdated gcc, I'll try to update the gcc.

**Comment by lucasdemarchi** [comment]
We require a minimum of GCC 4.9. what's your version?

**Comment by EwingKang** [comment]
The original toolchain comes with 4.6.2 by 

> gcc --version

I've manually updated to 4.9.3 using

> mingw-get update
> mingw-get upgrade

The same message persisted.

**Comment by EwingKang** [comment]
Okay, according to [this bug](https://github.com/PX4/Firmware/issues/833)I've also check the version of arm-none-eabi-gcc by  

> arm-none-eabi-gcc --version 

I tried to update it by downloading the new version zip for win32, exract file, and brutally replace everything with the same name in c:/px4/toolchain/. 
The first attempt of update to latest version 5.4 failed and a make warning says I sould do 4.9.3, so I download the [4.9.2015-q3](https://launchpad.net/gcc-arm-embedded/4.9/4.9-2015-q3-update) and it actually worked! 
This is probably not a very nice way to update software, and I didn't test the resulting .px4 file. But at least the compile passed.

**Comment by guludo** [comment]
> We require a minimum of GCC 4.9.

I guess it's time to check gcc version on our build system.

**Pull request closed without merging**
