### PR TITLE
Global: Delete the new line character from the Panic message.

### PR DESCRIPTION
**Pull request by muramura**
I think that it is unnecessary to specify a carriage return at the end of the message. 
The Panic method outputs a line feed at the end of the message.

### CODE REVIEW

**Comment by khancyr** [comment]
very outdated, need rewrite

**Comment by OXINARF** [comment]
> The Panic method outputs a line feed at the end of the message.

This isn't actually true for ChibiOS.

There isn't much point on printing a new line after a panic, but it doesn't hurt either - I don't think we need to have commits just to change this; it's like the space fixing commits, if done integrated in another PR, fine, otherwise it's just unnecessary history.

Given the above and also given how old this is, I'm closing it.

**Comment by peterbarker** [comment]
On Tue, 30 Jul 2019, Francisco Ferreira wrote:

>       The Panic method outputs a line feed at the end of the message.
> This isn't actually true for ChibiOS.

We would probably accept a PR to add that carriage return, 'though, right?

**Comment by OXINARF** [comment]
I think so, yes.

**Pull request closed without merging**
