### PR TITLE
Correct handling of more than 256 fence items

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Review by rmackay9 — COMMENTED** [review]
LGTM.  Have you checked for any other callers to max_items?  Just wondering if there are downstream users (like Dijkstras) that may not have been exposed to more than 255 fence items

**Comment by peterbarker** [comment]
.... Dijkstra does seem to impose a 255 point limit, however.
OA_DIJKSTRA_POLYGON_SHORTPATH_NOTSET_IDX

**Comment by peterbarker** [comment]
Found and fixed a fence-transfered-via-FTP bug in here now.

We also were not gracefully handling an attempt to upload a fence with >255 vertexes - that's been fixed, too.

**Comment by peterbarker** [comment]
In addition to the new autotests I've done a bunch of tootling around in SITL to make sure fences still generally work.  Including Dijkstras with 765 points.

**Review by rmackay9 — APPROVED** [review]

**Pull request merged**
