### PR TITLE
Deal correctly with LED and DMA configuration changing

### PR DESCRIPTION
**Pull request by andyp1per**
Four bugs for the price of one:

- Removes the unnecessary extra pulse timeout that was set on the DMA completion IRQ. This is now just a straight 40us. This prevents us waiting twice as long as we need to.
- Calculates the LED timeout correctly preventing us waiting 4 times as long as we need to
- Always re-configures DMA in set_output_mode if DMA is being used, this prevents weird DMA overruns
- Re-allocates the LED buffers correctly when they change

### CODE REVIEW

**Comment by andyp1per** [comment]
Not working on Beast F7

**Comment by andyp1per** [comment]
Working now

**Comment by andyp1per** [comment]
This appears to have broken unidirectional dshot on a bi-directional build

**Comment by andyp1per** [comment]
Ok, stranger and stranger - the Beast H7 does not like DMA reconfiguration at all

**Comment by andyp1per** [comment]
The BeastH7 really does not like the DMA reconfiguration. For now I will restrict this to LED outputs, but it bears further investigation.

**Review by tridge — APPROVED** [review]

**Pull request merged**
