### PR TITLE
param_parse.py: emit SIM_ parameters along with everthing else

### PR DESCRIPTION
**Pull request by peterbarker**
This starts to emit the `SIM_` parameters along with all of the other parameters.

We will need to make sure it's clear in the Wiki that these are simulation parameters (somehow...).

MissionPlanner should start to display these when the vehicle actually has the parameter (in its simulation), which will be cool.

Current XML diff:
```
--- apm.pdef.xml-master	2023-01-07 12:01:30.994715169 +1100
+++ apm.pdef.xml	2023-01-07 12:31:37.822057604 +1100
@@ -23078,6 +23078,154 @@
         <field name="UnitText">seconds</field>
       </param>
     </parameters>
+    <parameters name="SIM_">
+      <param humanName="Baro Noise" name="SIM_BARO_RND" documentation="Amount of (evenly-distributed) noise injected into the 1st baro" user="Advanced">
+        <field name="Units">m</field>
+        <field name="UnitText">meters</field>
+      </param>
+      <param humanName="Baro Glitch" name="SIM_BARO_GLITCH" documentation="Glitch for 1st baro" user="Advanced">
+        <field name="Units">m</field>
+        <field name="UnitText">meters</field>
+      </param>
+      <param humanName="Baro2 Noise" name="SIM_BAR2_RND" documentation="Amount of (evenly-distributed) noise injected into the 2nd baro" user="Advanced">
+        <field name="Units">m</field>
+        <field name="UnitText">meters</field>
+      </param>
+      <param humanName="Baro2 Glitch" name="SIM_BAR2_GLITCH" documentation="Glitch for 2nd baro" user="Advanced">
+        <field name="Units">m</field>
+        <field name="UnitText">meters</field>
+      </param>
+      <param humanName="Baro3 Noise" name="SIM_BAR3_RND" documentation="Amount of (evenly-distributed) noise injected into the 3rd baro" user="Advanced">
+        <field name="Units">m</field>
+        <field name="UnitText">meters</field>
+      </param>
+      <param humanName="Baro3 Glitch" name="SIM_BAR3_GLITCH" documentation="Glitch for 2nd baro" user="Advanced">
+        <field name="Units">m</field>
+        <field name="UnitText">meters</field>
+      </param>
+      <param humanName="Sailboat simulation sail type" name="SIM_SAIL_TYPE" documentation="0: mainsail with sheet, 1: directly actuated wing">
+</param>
+      <param humanName="JSON master instance" name="SIM_JSON_MASTER" documentation="the instance number to  take servos from">
+</param>
+      <param humanName="SIM-on_hardware Output Enable Mask" name="SIM_OH_MASK" documentation="channels which are passed through to actual hardware when running on actual hardware">
+</param>
+    </parameters>
+    <parameters name="SIM_GRPE_">
+      <param humanName="Gripper servo Sim enable/disable" name="SIM_GRPE_ENABLE" documentation="Allows you to enable (1) or disable (0) the gripper servo simulation" user="Advanced">
+        <values>
+          <value code="0">Disabled</value>
+          <value code="1">Enabled</value>
+        </values>
+      </param>
+      <param humanName="Gripper emp pin" name="SIM_GRPE_PIN" documentation="The pin number that the gripper emp is connected to. (start at 1)" user="Advanced">
+        <field name="Range">0 15</field>
+      </param>
+    </parameters>
+    <parameters name="SIM_GRPS_">
+      <param humanName="Gripper servo Sim enable/disable" name="SIM_GRPS_ENABLE" documentation="Allows you to enable (1) or disable (0) the gripper servo simulation" user="Advanced">
+        <values>
+          <value code="0">Disabled</value>
+          <value code="1">Enabled</value>
+        </values>
+      </param>
+      <param humanName="Gripper servo pin" name="SIM_GRPS_PIN" documentation="The pin number that the gripper servo is connected to. (start at 1)" user="Advanced">
+        <field name="Range">0 15</field>
+      </param>
+      <param humanName="Gripper Grab PWM" name="SIM_GRPS_GRAB" documentation="PWM value in microseconds sent to Gripper to initiate grabbing the cargo" user="Advanced">
+        <field name="Range">1000 2000</field>
+        <field name="Units">PWM</field>
+        <field name="UnitText">PWM in microseconds</field>
+      </param>
+      <param humanName="Gripper Release PWM" name="SIM_GRPS_RELEASE" documentation="PWM value in microseconds sent to Gripper to release the cargo" user="Advanced">
+        <field name="Range">1000 2000</field>
+        <field name="Units">PWM</field>
+        <field name="UnitText">PWM in microseconds</field>
+      </param>
+      <param humanName="Gripper close direction" name="SIM_GRPS_REVERSE" documentation="Reverse the closing direction." user="Advanced">
+        <values>
+          <value code="0">Normal</value>
+          <value code="1">Reverse</value>
+        </values>
+      </param>
+    </parameters>
+    <parameters name="SIM_PLD_">
+      <param humanName="Preland device Sim enable/disable" name="SIM_PLD_ENABLE" documentation="Allows you to enable (1) or disable (0) the Preland simulation" user="Advanced">
+        <values>
+          <value code="0">Disabled</value>
+          <value code="1">Enabled</value>
+        </values>
+      </param>
+      <param humanName="Precland device center's latitude" name="SIM_PLD_LAT" documentation="Precland device center's latitude" user="Advanced">
+        <field name="Range">-90 90</field>
+        <field name="Increment">0.000001</field>
+        <field name="Units">deg</field>
+        <field name="UnitText">degrees</field>
+      </param>
+      <param humanName="Precland device center's longitude" name="SIM_PLD_LON" documentation="Precland device center's longitude" user="Advanced">
+        <field name="Range">-180 180</field>
+        <field name="Increment">0.000001</field>
+        <field name="Units">deg</field>
+        <field name="UnitText">degrees</field>
+      </param>
+      <param humanName="Precland device center's height above sealevel" name="SIM_PLD_HEIGHT" documentation="Precland device center's height above sealevel assume a 2x2m square as station base" user="Advanced">
+        <field name="Range">0 10000</field>
+        <field name="Increment">1</field>
+        <field name="Units">cm</field>
+        <field name="UnitText">centimeters</field>
+      </param>
+      <param humanName="Precland device systems rotation from north" name="SIM_PLD_YAW" documentation="Precland device systems rotation from north" user="Advanced">
+        <field name="Range">-180 +180</field>
+        <field name="Increment">1</field>
+        <field name="Units">deg</field>
+        <field name="UnitText">degrees</field>
+      </param>
+      <param humanName="Precland device update rate" name="SIM_PLD_RATE" documentation="Precland device rate. e.g led patter refresh rate, RF message rate, etc." user="Advanced">
+        <field name="Range">0 200</field>
+        <field name="Units">Hz</field>
+        <field name="UnitText">hertz</field>
+      </param>
+      <param humanName="Precland device radiance type" name="SIM_PLD_TYPE" documentation="Precland device radiance type: it can be a cylinder, a cone, or a sphere." user="Advanced">
+        <values>
+          <value code="0">cylinder</value>
+          <value code="1">cone</value>
+          <value code="2">sphere</value>
+        </values>
+      </param>
+      <param humanName="Precland device alt range" name="SIM_PLD_ALT_LIMIT" documentation="Precland device maximum range altitude" user="Advanced">
+        <field name="Range">0 100</field>
+        <field name="Units">m</field>
+        <field name="UnitText">meters</field>
+      </param>
+      <param humanName="Precland device lateral range" name="SIM_PLD_DIST_LIMIT" documentation="Precland device maximum lateral range" user="Advanced">
+        <field name="Range">5 100</field>
+        <field name="Units">m</field>
+        <field name="UnitText">meters</field>
+      </param>
+      <param humanName="Precland device orientation" name="SIM_PLD_ORIENT" documentation="Precland device orientation vector" user="Advanced">
+        <values>
+          <value code="0">Front</value>
+          <value code="4">Back</value>
+          <value code="24">Up</value>
+        </values>
+      </param>
+      <param humanName="SIM_Precland extra options" name="SIM_PLD_OPTIONS" documentation="SIM_Precland extra options" user="Advanced">
+        <field name="Bitmask">0: Enable target distance</field>
+      </param>
+    </parameters>
+    <parameters name="SIM_SPR_">
+      <param humanName="Sprayer Sim enable/disable" name="SIM_SPR_ENABLE" documentation="Allows you to enable (1) or disable (0) the Sprayer simulation" user="Advanced">
+        <values>
+          <value code="0">Disabled</value>
+          <value code="1">Enabled</value>
+        </values>
+      </param>
+      <param humanName="Sprayer pump pin" name="SIM_SPR_PUMP" documentation="The pin number that the Sprayer pump is connected to. (start at 1)" user="Advanced">
+        <field name="Range">0 15</field>
+      </param>
+      <param humanName="Sprayer spinner servo pin" name="SIM_SPR_SPIN" documentation="The pin number that the Sprayer spinner servo is connected to. (start at 1)" user="Advanced">
+        <field name="Range">0 15</field>
+      </param>
+    </parameters>
     <parameters name="SPRAY_">
       <param humanName="Sprayer enable/disable" name="SPRAY_ENABLE" documentation="Allows you to enable (1) or disable (0) the sprayer" user="Standard">
         <values>
```

### CODE REVIEW

**Comment by rmackay9** [comment]
very nice!

**Comment by Hwurzburg** [comment]
fyi.....Mission Planner already displays ALL SIM_xxxx parameters when a sim is running....

**Comment by peterbarker** [comment]
@Hwurzburg have you had a chance to test this with the WIki and be happy with how the pages look?

**Comment by rmackay9** [comment]
We should check that QGC is happy with this as well.  I know it complains if parameter definitions are missing, I assume it doesn't complain if there are extra parameter descriptions but we should probably check.

**Comment by Hwurzburg** [comment]
I am not sure this changes anything for a GCS....right now Mission Planner displays this when simulating:
image
QGC displays this:

**Comment by Hwurzburg** [comment]
looking good....tested...

**Comment by peterbarker** [comment]
@Hwurzburg I've popped your commit off this one, sorry.  It broke the build by removing half-a-parameter.  I did fix that but hten also noticed it seemed to corrupt things by adding extra parameters where there shouldn't have...

It's also weird that the github interface didn't mention your push to the branch!

**Pull request merged**
