### PR TITLE
[WIP] Move code to use RC_Channels singleton

### PR DESCRIPTION
**Pull request by patrickelectric**
Remove rc reference and move project to use RC_Channels singleton.

### CODE REVIEW

**Comment by patrickelectric** [comment]
@peterbarker or @khancyr, if possible, can take a look in the error here ? I don't know if can be something related to Rover and the special RC_Channel subclass or it's just a "normal" failure. Also, if convenient, can review this PR ? :)

**Comment by peterbarker** [comment]
Copied from PM:

```
Hi... your PR#9281... you realise you're doing the exact opposite of what the PR title is?

You're moving it from using the singleton (as returned by rc. to using static methods. The static methods are only there to avoid code churn now.

The "singleton" is a class which is instantiated once (typically as part of the static vehicle object). We now have many, many of these accesses by e.g. AP::ahrs(). etc etc. The rc one, like the gcs one, is accessed with rc(). (and gcs().)
```

**Comment by OXINARF** [comment]
I agree with @peterbarker, we are moving to the nicer singleton pattern and away from the ugly static interfaces.
I'm not sure I'll be on today's dev call, but I added the label to it so it can be decided.

**Comment by patrickelectric** [comment]
I agree with @peterbarker, I'll do some work around it.

**Comment by peterbarker** [comment]
@patrickelectric This is very, very conflicted now.  Did you want to close this one and open another one when you've had a chance to look a things again?

**Comment by amilcarlucas** [comment]
Almost a year without feedback

**Comment by patrickelectric** [comment]
This needs a rework, @Williangalvani is now the one dealing with this kind of reworks. I'll let him decide what to do.

**Comment by peterbarker** [comment]
I think I might actually close this one as "wrong" at this point.

`rc()` may give you a subclass of the `RC_Channels` library - and that may be important for the calls being made.

It can always be reopened / supeseded.

**Pull request closed without merging**
