### PR TITLE
Tools: add -Werror=suggest-override for gcc

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by WickedShell** [comment]
Can't do this due to GCC versioning.

**Comment by peterbarker** [comment]
@WickedShell Yep, you're right.  Amusingly, it *does* actually pick up some stuff in the failsafe code where the keyword could be added (CI results showed that).

**Comment by OXINARF** [comment]
If the problem is just GCC version, we can add it conditionally - waf provides what compiler it is and what version it is too.

**Comment by peterbarker** [comment]
On Wed, 8 May 2019, Francisco Ferreira wrote:

> If the problem is just GCC version, we can add it conditionally - waf provides what compiler it is and what version it is too.

I went looking before closing this issue; do we have an example of doing 
the version check anywhere?

**Comment by OXINARF** [comment]
I don't think we have version check, but it's similar to COMPILER_CC, except it is a list:
https://github.com/ArduPilot/waf/blob/337b0a96beeac517ecde081fb76dedd039089734/waflib/Tools/c_config.py#L1087

**Pull request closed without merging**
