### PR TITLE
Copter: Add support for tandem and transverse helicopters

### PR DESCRIPTION
**Pull request by fhedberg**
Provides support for tandem (CH-47 Chinook) and transverse (V22 Osprey, sans tilt) helicopters:
- Adds AP_MotorsHeli_Dual motor implementation supporting tandem and transverse setups, using differential-collective-pitch for roll/pitch, and mixing yaw into the two rotor swashes.
- Adds HELI_DUAL as new frame type.
- Adds SITL support for tandem and compound helicopters (already merged to master).
- Adds the FRAME_TYPE define, a parent of FRAME_CONFIG, which can be used to distinguish between multicopter and helicopter code.

### CODE REVIEW

**Comment by pistolero** [comment]
Dude, this is awesome. I'm building transverse tandem heli now. Can't wait to test this branch.

**Comment by uavfans** [comment]
how to run the SITL ,I have no money to building transverse tandem heli

**Comment by fhedberg** [comment]
@uavfans Execute "sim_vehicle.sh -f heli-dual --console".

**Comment by tridge** [comment]
I've pushed the SITL part of the changes into master. I'll leave the rest for Randy and Rob to continue to work on

**Comment by tridge** [comment]
could you add a parameter file for SITL for compound and dual? I just added Tools/autotest/Helicopter.parm as the normal heli parms. If you can add Helicopter-dual.parm and Helicopter-compound.parm that will make it easier to test

**Comment by fhedberg** [comment]
@R-Lefebvre @rmackay9 This is now rebased onto @R-Lefebvre latest work.

**Comment by fhedberg** [comment]
@rmackay9 @R-Lefebvre Rebased onto master.

**Comment by fhedberg** [comment]
@tridge Added the parameter files. Compound helicopter in SITL needs some tuning for the position control flight modes (works well in stabilize, tandem works well in all flight modes), but I experience the same issues with regular helicopter in SITL and haven't quite figured it out. Perhaps you or @r-Lefebvre have any ideas?

**Comment by uavfans** [comment]
can simulation tandem in SITL now ?

**Comment by fhedberg** [comment]
@uavfans Yes. 'sim_vechicle.sh -w -f heli-dual --console'

**Comment by uavfans** [comment]
~/ardupilot/ArduCopter$ sim_vehicle.sh -w -f heli-dual --console
~/ardupilot/ArduCopter ~/ardupilot/ArduCopter
Building sitl-heli-dual
make: *** No rule to make target `sitl-heli-dual'.  Stop.
make: *** No rule to make target `sitl-heli-dual'.  Stop.
There are error

**Comment by fhedberg** [comment]
@uavfans You'll need to make sure you're running this branch.

**Comment by fhedberg** [comment]
@R-Lefebvre @rmackay9 Rebased this onto master. Both new frame types flies great in SITL and in practice. The only unorthodox thing that still would be great to get feedback on is the AC_AttitudeControl_Heli_Compound idea.

**Comment by uavfans** [comment]
how to sim ,there a interlock,i can't to arming it

**Comment by uavfans** [comment]
Tow month ago ,I can use crrcsim for heli sim witn MP,today I can not  link to MP,and other heli sim can link to MP.

**Comment by rmackay9** [comment]
@uavfans, I think set the rc channel 8 high maybe?  "rc 8 1900"

**Comment by R-Lefebvre** [comment]
@fhedberg I'm not really a fan of the way you've done the Compound control here.  It appears that you have a parameter which sets the maximum forward pitch.  So as you push the pitch stick forward, the heli will pitch it's nose down, but then after that, begin to use the compound thruster.

There's nothing really wrong with this... but I don't think it's how it should work.  I'm quite sure than in full scale versions of this, the pilot has pitch control just as normal, and they have a collective lever, and a thruster lever.  

I believe it is more efficient to achieve fast forward flight by keeping the pitch at level, and then using just the thruster for forward speed.  Pitch would be used to control climb rate in fast forward flight, not collective.  It operates very much like an airplane in this way.

Having full control over all axes like this, actually would allow prolonged flight even after primary rotor drive failure.  The pusher prop continues to push it forward, and then with a bit of nose-up pitch, the main rotor is in autorotation. That won't be possible with your control system here.

I'd prefer to see an extra input channel used for thrust, and leave the attitude controller as it is.

**Comment by uavfans** [comment]
oh,I can sim by arm uncheck all

**Comment by uavfans** [comment]
@fhedberg  how to sim  heli-dual,I have run it ,but can not fly it . I review the code ,there are six input,servo[0]-servo[5]

**Comment by uavfans** [comment]
sero[7] for rsc

**Comment by fhedberg** [comment]
@R-Lefebvre Hey! Our dislike for the compound attitude controller is mutual ;) I completely agree that having greater control over all axes would be preferably. You're correct that the [full-scale version uses separate thrust control](http://www.blueskyrotor.com/blog/2013/12/how-to-speed-up-the-x3/). 

My thinking for going this way is in short twofold, first it works across all flight-modes and secondly it makes for minimal changes across the code-base. For STABILIZE and ACRO, decoupling attitude control and lateral trust would of course be an option and even perhaps preferably, but I really want/need something which is valid for AUTO as well.

As per the discussion with @rmackay9 on the booster pull-request (https://github.com/diydrones/ardupilot/pull/1932), the ideal solution involves a lot of conceptual changes and I wanted to take it peu à peu into master.

My idea for next steps (as a separate pull-request) would be to start working on a hybrid navigation controller and attitude controller using L1/TECS in high-speed forward flight, which separates attitude control from forward trust, and to include aerodynamic control-surfaces control as well. Would love to discuss on the dev-call, but it's timing is not very Europe friendly ;)

Separately, I have a tilt-rotor AP_Motors implementation here https://github.com/fhedberg/ardupilot/commit/3c8806fe2b0f5ac930888b2cfb2304dc55454158, which works in STABILIZE and ACRO, but I figured it would be easier (at least less risky from a practical perspective) to start with the hybrid controller on a compound, even though the tilt-rotor is really what I'd like to work towards.

Do you have any other suggestions?

**Comment by fhedberg** [comment]
Perhaps @rmackay9 or @tridge has some suggestions for short-term and long-term solutions for hybrid attitude/navigation control?

**Comment by fhedberg** [comment]
@R-Lefebvre Removed the compound attitude controller commits from this PR for now...

**Comment by fhedberg** [comment]
@R-Lefebvre Ok, I've removed the compound attitude controller. I'll see if I can figure out a better way and send that your way separately.

**Comment by fhedberg** [comment]
@R-Lefebvre Any more input on this one?

**Comment by fhedberg** [comment]
@r-lefebvre Any more input on this one?

**Comment by uavfans** [comment]
fhedberg，any progress

**Comment by rmackay9** [comment]
while I was reviewing this I wasn't immediately able to get the dual heli off the ground in the simulator.... I'll check some more.

**Comment by rmackay9** [comment]
I had a fairly detailed look at this today and I've got some changes that can be seen here:
https://github.com/rmackay9/rmackay9-ardupilot/commits/fhed-heli1
Basically the changes are to declare the servo objects inside the AP_Motors class instead of in the main vehicle which simplifies the constructor a bit and basically keeps it slightly more modular.  This was not possible until a few weeks ago.
Unfortunately after this change the heli-tiltrotor code crashes and I suspect it's because we can't have quite so many layers of parameters.  In particular I think it's the _tvec_servo that can't be created within the Tiltrotor class.

**Comment by rmackay9** [comment]
By the way, we've got a fairly major motor refacting which is getting close to completion.
https://github.com/rmackay9/rmackay9-ardupilot/commits/leo-mot8

I will attempt to merge these new heli classes in on top of that.  Moving the servo objects into the heli classes is a part of the refactoring.

**Comment by fhedberg** [comment]
@rmackay9 Rebased this onto master and adapted to the motors changes. I do however get the same var table issues as you experienced with both compound and tilt-rotor. Any pointers to how to work around?

**Comment by uavfans** [comment]
Still doing? , thought you didn't do it.

**Comment by fhedberg** [comment]
@rmackay9 Couldn't figure out the param subclassing issue so removed the compound and tilt-rotor implementations from this pull-request.

**Comment by C-Gaddis** [comment]
Randy & Fredrik - Any progress on this? I have an airframe that I'd be willing to test a beta on.

**Comment by Block137** [comment]
Please add choice/mixing for Aileron roll for transverse mode in addition to DCP for roll.
To be clear, tilt both swashplate sideway for roll instead of DCP or a mix of both.

I wish I could do this myself.

**Comment by Block137** [comment]
And also reverse yaw during negative collective.

**Comment by R-Lefebvre** [comment]
Interesting. Can you explain the benefit of aileron roll compared to  do for a transverse tandem?

**Comment by Block137** [comment]
I don't know how much the effect is. I might be totally wrong here.
Some transverse design such as Synchropter (Kaman K-max) has the masts very close together.
DCP would yaw it very hard instead of rolling.
Also differential cyclic for yaw might be less effective on this type of heli as well (will have no effect on coaxial)
Tandem or Chinook style have their rotors farther apart that DCP is effective enough to eliminate the need of 3rd CCPM actuator (some designs use only 4 servos total).

**Comment by Block137** [comment]
I tried to add yaw reverser as well as Intermesher mode.
Now I don't know how to post it here...yet. I've been into this for less than a week.
Pressing "Publish" button on Git-for-Windows returns No permission message so I'll attach it here instead.
[Attachment.zip](https://github.com/ArduPilot/ardupilot/files/644638/Attachment.zip)

Any suggestion is appreciated.

**Comment by magicrub** [comment]
The github for Windows app is not very good, take a look at Sourcetree. There are lots of how-to videos about git using it.

**Comment by Block137** [comment]
There is a lot more for me to learn.
But for now I can't adjust servo trim.
H_SVx_TRIM is not working. Is it working on other's?

I'm using Pixhawk 2.

**Comment by tridge** [comment]
Hi Fredrik,
I know it has been a very long time since we've looked at this, but I thought you might like to know that I plan on reviving this PR and adding support for tandem helis to master. 
At the time you did the PR supporting tandem helis required a separate build due to the way the parameter system works. I'm working on a change to make it possible to select different motors backend based on FRAME_TYPE within the heli build, including selecting different var_info arrays. The new SRV_Channel library also makes it much easier to implement backends like these, as you don't need to handle all the servo channel setup within the motors backend.
I have also setup a chinook model in RealFlight for testing, which will make it easier to test, and a friend of mine has built a small chinook model he wants to try.
This is not a request for you to do anything more on the PR - I just wanted to let you know that I think we will soon have all the pieces in place to properly support aircraft like this in master.

**Comment by C-Gaddis** [comment]
THANKS GUYS! This is great news. I have a tandem heli waiting for a
firmware that will fly it..  I really appreciate all your hard work.

Chris

**Comment by frizensami** [comment]
@tridge this is great news, I will also have a tandem frame soon that can be used for testing. Very interested in this project, do let me know if there's anything I can assist with.

**Comment by tridge** [comment]
I now have the Chinook in RealFlight flying with ArduPilot, using an adaption of Frederiks AP_MotorsHeli_Dual code to master
See https://github.com/tridge/ardupilot/tree/pr-copter-heli-dual
You need to set FRAME_CLASS to 11 to enable HELI_DUAL
You can also fly it with built-in SITL, using:
  sim_vehicle.py -f heli-dual

**Comment by tridge** [comment]
new PR for the dual-heli support in master
https://github.com/ArduPilot/ardupilot/pull/5867

**Comment by tridge** [comment]
note that this PR from Fredrik also includes AP_MotorsHeli_Compound and AP_MotorsHeli_Tiltrotor. Fredrik, do you want us to keep this PR open so those are not forgotten about? Adapting them in the same way I did for Heli-Dual should be straightforward

**Comment by RobertWZ** [comment]
Fredrik 
image

**Comment by OXINARF** [comment]
@fhedberg Should we still leave this open?

**Comment by davidbuzz** [comment]
No activity on this PR for nearly a year, and nearly 3 years since it was originally opened. the key parts of it have been completed by tridge elsewhere, and @fhedberg as the original author has made no comment.  closing.    Note that this PR can still be referenced once closed, so if someone wants to revise the parts of this that aren't done, they still can.

**Pull request closed without merging**
