### PR TITLE
Copter: remove dumb delay() in favor for millis()

### PR DESCRIPTION
**Pull request by night-ghost**
to speed up boot

### CODE REVIEW

**Comment by khancyr** [comment]
I am not sure if it is better, as the delay function call hal->delay that only block the main thread but not the other, here we block everything

**Comment by magicrub** [comment]
If that's the case, then this is doing the opposite of speeding up boot.

**Comment by night-ghost** [comment]
there is no other threads at this stage

**Comment by magicrub** [comment]
If that's true, then what's the difference with this change other than it actually delays longer?

**Comment by night-ghost** [comment]
there was another initializations before, so millis() at this point can be  from 400 to 1600 (board dependent), so time of delay here is much less than delay(1000)

**Comment by night-ghost** [comment]
breakpoint just before
delay

**Comment by peterbarker** [comment]
The real question is, 'why does this line and comment exist at all?'  No other vehicle has this delay.

GCS_MAVLink has the `telem_delay` parameter to stop the XBee bricking there.

The line in question would stop us bricking XBees for other reasons - any random serial-port driver that might write to a uart within a second of power-on.  That would seem to indicate we should move `TELEM_DELAY` out of GCS_MAVLink (perhaps into `BRD_` and renamed?).  At least then we'd be consistent across vehicles!

**Comment by tridge** [comment]
This may break some HALs. There are other threads running on ChibiOS and PX4 HALs for example, plus we'd need to re-test with XBee.
If you'd like to remove this delay for HAL_F4Light then I'd suggest adding a #ifndef HAL_DISABLE_XBEE_DELAY around the delay, and add that define for HAL_F4Light.

**Comment by tridge** [comment]
@peterbarker hmm, you're right, if the GCS code is already handling this delay, then maybe just remove it in copter?

**Comment by night-ghost** [comment]
>If you'd like to remove this delay for HAL_F4Light then I'd suggest adding a #ifndef 

I try to do a code simpler,  not more entangled. My version is a functional equivalent for delay(1000) so it can't break anything

**Comment by tridge** [comment]
> My version is a functional equivalent for delay(1000) so it can't break anything

not quite, its a busy loop, and other HALs have things running at that time (in fact, all HALs except F4Light have threads running).
It is particularly bad on HAL_Linux, where it would stop the entire OS

anyway, based on Peters comment I think we can just remove the delay(1000) completely

**Comment by night-ghost** [comment]
>its a busy loop,

HAL API don't exports yield() to be called within this loop. But yes, will change this

**Comment by tridge** [comment]
I've changed it to just remove the delay completely

**Pull request merged**
