### PR TITLE
Tools: correct quoting in run_in_terminal_window.sh

### PR DESCRIPTION
**Pull request by peterbarker**
Should fix problems with spaces in usernames.

### CODE REVIEW

**Comment by rmackay9** [comment]
i'm not qualified to determine if this is correct but I think peter is!  merged!

**Comment by deltatango2** [comment]
@peterbarker I was still having issues with this and I tracked it down to the passing of all arguments using $* vice "$@" the quoted version of each arg.  After making this change, I have successful operation in Windows 10 with xterm.

**Comment by peterbarker** [comment]
@deltatango2 any chance of a PR?

**Comment by deltatango2** [comment]
@peterbarker Sure thing, give me a bit to fork it and I'll send it your way.

**Pull request merged**
