### PR TITLE
AP_Notify: lost vehicle tone and support for BBBMini (v2)

### PR DESCRIPTION
**Pull request by lucasdemarchi**
v2 of #4042 

@juvinski I fixed the comments from @OXINARF, basically rebasing it and fixing the code style. Please double check this matches your original implementation and works on your board.

@mirkix let me know when you are happy with this.

### CODE REVIEW

**Comment by mirkix** [comment]
@lucasdemarchi Hi Lucas, looks good to me. Ordered two buzzer some days ago, when they arrive I will check in real. I think it can go in master when @juvinski checked that is working.

**Comment by juvinski** [comment]
Hi @lucasdemarchi, the code is working fine, thanks.
@mirkix, I was looking at https://github.com/ArduPilot/ardupilot/tree/master/Tools/Linux_HAL_Essentials/devicetree/bbbmini
and there is a reference of pin 8.36 as Buzzer with amplifier(and using a pwm output), this is right ?

**Comment by lucasdemarchi** [comment]
Applied, thanks.

**Comment by juvinski** [comment]
Hi @lucasdemarchi and @mirkix.
I found a strange behavior using pin 8.31. My first suspicious was about my test circuit,after create a real pcb and tested all components I figure out this strange behavior is something on beablebone. The default state of pin 8.31 is high(when turning beaglebone on and didnt applied any DTO) and any circuit - the buzzer circuit I made or simple a led with resistor, produces an square wave on this pin, and beaglebone does not boot. I made several tests with different test boards and I didn´t find a solution for use pin 8.31(the only way was booting beaglebone without the circuit and after boot connect), so I think is better to change pin to 8.32 - I tested with success this pin, but now what I must proceed? I can change the pin on @lucasdemarchi code and them submit a new pull request ?
Regards

**Comment by juvinski** [comment]
Just to be more clear, this is the high level of pin 8.31 at boot.
p8_31_boot
This is what happens - since boot when I connect any circuit on this pin.
wave_signal
causing the beaglebone black boot problem.

**Comment by lucasdemarchi** [comment]
You can submit a new PR just changing the pin. This is already applied.

One possible reason is that the BBB uses this pin during boot to select the boot media. Not sure this is the case, but this happened to me with MinnowBoard Max.

**Comment by juvinski** [comment]
I found two clues about it. First as you said, there are 16 pins (P8.31 to P8.46) are labeled as Expansion Boot Pins, and the BBB System Reference Manual are telling to avoid driven this pins at boot time. The second clue is to driven just after boot process started(SYS_RESETN pin set to high).
So, how this is a simple buzzer - I really think is more clever for now change pin than create a circuit dealing with SYS_RESETN signal :). I will change pin to another one - even the pin p8.32 are working now, but is marked as Boot Pin, so to avoid problems I will change to another one.
Thanks for the tip and help.

**Comment by mirkix** [comment]
@juvinski Than we have to look for a new pin. Please do not choose a pin that can be used with the PRU. They are very rare and I have something in mind where I need them.

**Pull request closed without merging**
