### PR TITLE
ArduPlane: clean up guided heading type initialization

### PR DESCRIPTION
**Pull request by timtuxworth**
CMD_GUIDED_CHANGE_HEADING was initializing heading values even if not using HEADING_TYPE_HEADING.

### CODE REVIEW

**Comment by peterbarker** [comment]
Could you explain why https://github.com/ardupilot/ardupilot/blob/master/ArduPlane/mode_guided.cpp#L65 is not crossed when using cog, please?

Some broad explanation in here of why you believe this is unused would be nice :-)

**Comment by timtuxworth** [comment]
> Could you explain why https://github.com/ardupilot/ardupilot/blob/master/ArduPlane/mode_guided.cpp#L65 is not crossed when using cog, please?

It seems like it would be crossed. I'm not sure why it matters, this PR doesn't change plane.guided_state.target_heading_limit

**Comment by timtuxworth** [comment]
fixed

**Comment by timtuxworth** [comment]
This change is wrong.

**Pull request closed without merging**
