### PR TITLE
AP_Scheduler: avoid calculating task interval every tick

### PR DESCRIPTION
**Pull request by linuxjumper**
task interval will not be changed, so there‘s no need to calculate task interval every tick.

### CODE REVIEW

**Comment by magicrub** [comment]
This is intentional, but overkill. The loop rate depends on the param which can change during runtime. Your proposed change requires a reboot which is not preferred. A better solution is to only compute it when the param changes.

**Comment by muramura** [comment]
@linuxjumper , @magicrub 
I also got the same comment in other.
Maybe, I think that there are those who think the same thing in the future.
Therefore,
I think that it is better to explicitly be changed during operation.

**Comment by linuxjumper** [comment]
There is no interface to modify those parameters which used to compute task interval. So task interval can not be changed during runtime.

**Comment by magicrub** [comment]
This is the param https://github.com/ArduPilot/ardupilot/pull/4949/files#diff-31b293f0339b0421b186db3c3af6e35bR53

It gets constrained on boot and is ignored in init because it is/was continuously computed.

**Comment by linuxjumper** [comment]
@magicrub Both _loop_rate_hz and rate_hz for each task will not be changed after the initialization of  AP_Scheduler. So there is no need to calculate task interval repeatedly.

**Comment by muramura** [comment]
@magicrub, @linuxjumper 
I think.
I want you to leave now.
Because
The optimum value of _loop_rate_hz tune with the GDB.
It can change with a single instruction.
However, in this PR, the number of task table because of unit16_t, set in a plurality of instructions.

**Comment by linuxjumper** [comment]
@muramura Yeah, that's a good reason.

**Comment by dgrat** [comment]
This PR increases the line count and adds a new array. 
Not sure whether it is worth it, because the change is not performance critical.

**Pull request closed without merging**
