### PR TITLE
AP_OSD: fixed enable of OSD on boards with no built-in OSD

### PR DESCRIPTION
**Pull request by tridge**
this fixes MSP enable
main thing that needs checking is if this causes flash overflow on any board

### CODE REVIEW

**Comment by magicrub** [comment]
We need a script that will loop through every board type in the waf config. Doesn't need to be on ci yet, but something locally to sanity check for sizes would be nice.

**Comment by tridge** [comment]
> We need a script that will loop through every board type in the waf config. Doesn't need to be on ci yet, but something locally to sanity check for sizes would be nice.

I use Tools/scripts/configure_all.py for that

**Comment by yaapu** [comment]
@tridge it's failing on replay.
Disabling MSP on replay builds fixes it, would it be ok?

msp.h

```
#ifndef HAL_MSP_ENABLED
#define HAL_MSP_ENABLED !HAL_MINIMIZE_FEATURES && !APM_BUILD_TYPE(APM_BUILD_Replay)
#endif
```

**Comment by tridge** [comment]
>  Disabling MSP on replay builds fixes it, would it be ok?

unfortunately we can't use build type checks in headers
I'll need to find another approach

**Comment by tridge** [comment]
@yaapu I finally got this passing CI !

**Comment by yaapu** [comment]
@tridge great! we had quite a few requests for this :-)

**Pull request merged**
