### PR TITLE
AP_HAL: remove BRD_PWM_COUNT reference

### PR DESCRIPTION
**Pull request by yuri-rage**
Quick PR to update comment text that contains a stale reference to BRD_PWM_COUNT.

https://discuss.ardupilot.org/t/brd-pwm-count-still-in-hwdef-dat/84160/2

### CODE REVIEW

**Review by Gone4Dirt — APPROVED** [review]

**Review by khancyr — APPROVED** [review]
LGTM

**Comment by rmackay9** [comment]
This looks OK to me, just one small thing, can you change the commit to start with "AP_HAL:"?

**Comment by yuri-rage** [comment]
Commit amended per request.

**Comment by tridge** [comment]
needs rebase and squash as single commit

**Comment by hendjoshsr71** [comment]
@yuri-rage It looks like your fork is actually forked from Rishabh's branch. 

You should instead fork from the main repo and then we could have fixed it up for you :)

Or perhaps you unchecked this box?

image

**Comment by yuri-rage** [comment]
I'll get it fixed up.  My lack of git-fu is showing...

I have an active pull request to Rishabh's fork regarding our work on the Lua rangefinder/prox libraries, so intended to keep that active while making this PR.

**Comment by yuri-rage** [comment]
Fixed.  My apologies.  Will fork main and use that for all future PRs.

**Comment by rmackay9** [comment]
Merged, thanks!

**Pull request merged**
