### PR TITLE
Adding Lee Field to locations.txt

### PR DESCRIPTION
**Pull request by mday299**
Added one of our air fields to locations.txt

### CODE REVIEW

**Comment by magicrub** [comment]
Welcome back! I'm looking forward to your work at GT

**Comment by mday299** [comment]
@magicrub Good to be back, Tom!  I anticipate a summer of PRs to annoy @tridge with. :)

**Comment by magicrub** [comment]
Now you get to annoy me too :) merged! https://github.com/ArduPilot/ardupilot/commit/a14bdf949ad081bbfc77d551abf27dd17b3651a6
Who's Charles Pippin?

**Comment by mday299** [comment]
This is Charles. [http://robotics.gatech.edu/team/faculty/pippin](http://robotics.gatech.edu/team/faculty/pippin)

I'm working with him on some UAV projects.

**Comment by mday299** [comment]
Charles Pippin | Institute for Robotics & Intelligent Machines at Georgia Tech
  
|  
|   
|   
|   |    |

   |

  |
|  
|   |  
Charles Pippin | Institute for Robotics & Intelligent Machines at Georg...
   |   |

  |

  |

**Pull request merged**
