### PR TITLE
TECS: Minimum groundspeed controller without Airspeed Sensor

### PR DESCRIPTION
**Pull request by mwrightE38**
Control throttle if groundspeed is less than minGSPD

### CODE REVIEW

**Comment by WickedShell** [comment]
Is this intended for plane or rover? Plane already has a minimum airspeed parameter, which is used to bump the target airspeed up, which is then passed to TECS which results in TECS managing the throttle for you. How does this improve that situation?

**Comment by mwrightE38** [comment]
Simple Pi controller for setting minimum groundspeed. 

Parameter Overview:

https://github.com/ArduPilot/ardupilot/pull/7968/commits/e0d8a8254caa1a8fd09d0797a51c131c9e9b7a75#diff-b6ecb54e20c4b89219bde19a4b8e93eeR242

minGSPD_P - P value
minGSPD_I - I value
minGSPD - minimum gspd allowed 

Requirements for throttle to be added on to trim_throttle. 

https://github.com/ArduPilot/ardupilot/pull/7968/commits/e0d8a8254caa1a8fd09d0797a51c131c9e9b7a75#diff-b6ecb54e20c4b89219bde19a4b8e93eeR759

1) Requires 3d fix
2) minGSPD must be greater than or equal to 0
3) Must pass flying check so throttle doesn't build while sitting on the ground
4) Auto landing may not be in progress.
 
Thought process behind it.


Planes should have a minimum allowed groundspeed. When flying without an airspeed sensor in strong winds it's possible for planes to attempt to only maintain altitude and make little progress. This allows them to push through the heavier winds and proceed with the mission. 

How it works:

_gspd_nudge is the extra calculated throttle from this controller that is added on after pitch throttle and trim throttle have been added.

The controller is allowed to add throttle on until the plane reaches a groundspeed greater than minGSPD + 1. This allows us a small amount of leeway over minGSPD. This is useful during gusts while the controller is active. When turning from a upwind segment to a downwind segment the added throttle from _gspd_nudge will turn off almost immediately protecting the plane from gaining the excessive throttle.

**Comment by mwrightE38** [comment]
@WickedShell This is intended for plane. Plane currently only has synthetic groundspeed control through the airspeed portion of code unless this has been implemented since the last dev call I attended.

**Comment by magicrub** [comment]
I've updated your title.

Have you seen the existing [MIN_GNDSPD_CM](http://ardupilot.org/plane/docs/parameters.html#min-gndspd-cm-minimum-ground-speed) param that [does this](https://github.com/ArduPilot/ardupilot/blob/master/ArduPlane/navigation.cpp#L133)?

I see yours works without airspeed sensor.. but the other one does that already too, so with that param there would be two things fighting each other. I admit that the existing one is not very clever and TECS does not have scope of it but since it's treated as an airspeed error it ends up tracking it smoothly still.

Also, no need to reinvent a PID> [We have a library](https://github.com/ArduPilot/ardupilot/tree/master/libraries/AC_PID) for that ([AP_WINCH is a good example](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Winch/AP_Winch.h#L85) to follow).

**Comment by magicrub** [comment]
the existing min ground speed works with and without airspeed sensor. In fact, here's the big comment above it:

>     // we calculate airspeed errors (and thus target_airspeed_cm) even
>     // when airspeed is disabled as TECS may be using synthetic
>     // airspeed for a quadplane transition
>     calc_airspeed_errors();
>

**Comment by mwrightE38** [comment]
@magicrub Doesn't that require the synthetic airpseed estimate to be enabled?

 http://ardupilot.org/plane/docs/parameters.html#tecs-synairspeed-enable-the-use-of-synthetic-airspeed 

The parameter states that this may be inaccurate. Is there a combination of parameters that allows this while disregarding the rest of the code based on synthetic airspeed?

**Comment by magicrub** [comment]
@mwrightE38 if you notice, the existing one in navigation.c is doing close to what you're doing but without the fancy PID. It measures ground speed and if its too slow then it bumps it up. It actually doesn't care what the airspeed is but it treats it like an airspeed error causing the throttle to go up

That synthetic one is a weird one that @tridge made to tame the pitch controller for quadplanes during transitions in certain wind/noWind conditions

**Comment by mwrightE38** [comment]
@magicrub You still need to have the plane configured for airspeed to use this unless I'm not following something correctly. 

https://github.com/ArduPilot/ardupilot/blob/518abfe1d0b2000a70a06213e4c5e9b3e7f2411b/ArduPlane/navigation.cpp#L153

https://github.com/ArduPilot/ardupilot/blob/518abfe1d0b2000a70a06213e4c5e9b3e7f2411b/ArduPlane/navigation.cpp#L133

https://github.com/ArduPilot/ardupilot/blob/c9664a9923fb25e3545f3294991316ff400d5129/ArduPlane/ArduPlane.cpp#L891

https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_SpdHgtControl/AP_SpdHgtControl.h#L28

https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_TECS/AP_TECS.cpp#L1065

**Comment by mwrightE38** [comment]
@magicrub Fair enough we could just implement the same thing tridge did a second time here if synthetic airspeed and the real airspeed controller are disabled but this is just how I implemented it.

**Comment by magicrub** [comment]
I think you just rebased this on another branch that has "mount" changes. Mind moving this branch to it's own dedicated one so we can review?
ping @tridge

**Comment by mwrightE38** [comment]
@magicrub  Right sorry about that. Slipped my mind that I made this PR.

**Pull request closed without merging**
