### PR TITLE
AP_OSD: Fix ground and wind speed varying length

### PR DESCRIPTION
**Pull request by shellixyz**

### CODE REVIEW

**Comment by giacomo892** [comment]
Flight tested. Thanks @shellixyz really improves the OSD display of the various speeds.

**Comment by skorokithakis** [comment]
Tested here as well, makes things much better indeed. Is it possible to merge this? @IamPete1?

**Comment by IamPete1** [comment]
@shellixyz looks like this is conflicting now, a re-base and it should be good to merge on the call, thanks.

**Comment by shellixyz** [comment]
Rebased :+1:

**Review by khancyr — APPROVED** [review]
PR: 
image

image

MASTER:
image

image

**Comment by khancyr** [comment]
@skorokithakis hello, could you either squash the commit or make a better commit message ?
Our convention on message is to append the library name at the start andexplain briefly the changes. So something like : AP_OSD: fix edge case for ground speed

**Review by khancyr — CHANGES_REQUESTED** [review]
See my comment

**Comment by skorokithakis** [comment]
Oh yes, certainly, thank you.

**Review by tridge — APPROVED** [review]

**Pull request merged**
