### PR TITLE
Copter: 4.1.0-beta8 release

### PR DESCRIPTION
**Pull request by rmackay9**
Copter-4.1.0-beta8 release including release notes and version update.

The individual PRs that are included can be seen in the ["4.1.0-beta8" column of this project](https://github.com/ArduPilot/ardupilot/projects/19).

### CODE REVIEW

**Comment by olliw42** [comment]
@rmackay9 
oh no, this does not include the latest mavlink messages, and the mavlink rssi changes, right? pl pl add them :):):)

**Comment by rmackay9** [comment]
@olliw42,

Thanks for the feedback.  This ship has sailed unfortunately but don't worry, another is pulling into the dock.  To be more clear, I'll bring it up with the other devs and see if we can include some mavlink changes.  At the moment, we just need to get 4.1.0 released and then we expect there will be a point release soon after.

**Comment by olliw42** [comment]
many thx for the response
it is, to be frank, somewhat disappointing though ... why do simple things have to take forever to come to the users ...
anyway, looking forward to 4.1.0 stable :)

**Comment by rmackay9** [comment]
@olliw42,

We've talked a bunch of times in the weekly dev calls about how we should have more frequent releases but at the same time, the beta testing and releases consume a huge amount of time, to the point where I almost can't do anything else during these periods.  I think if we had more people willing to take on the release management responsibilities we could do more frequent releases.  It's just tough to find people who want to get involved with this aspect of the project.

**Comment by olliw42** [comment]
@rmackay9 

I absolutely understand what you are saying, and there is nothing I would have to say to the contrary. However, I think I may have not well expressed myself. I was not asking for more frequent releases. I was also not talking about the admittedly tricky and complicated things like new controllers or new drivers, which involve lots of testing and other effort. I just think that beta releases could be good options to get also the simple changes there complications are hardly expected tested at little cost. Sorry if my dodgy wording has created irritations, was not my intention. :)

**Comment by rmackay9** [comment]
@olliw42, no irritations at all actually.  There's always room for improvement.  Maybe it's me saying that we need more frequent releases!  From now on we are trying to keep Plane, Copter and Rover all syncronised.. maybe that'll help because we can share the load of releases across more developers.  Anyway, txs for your thoughts.

**Pull request merged**
