### PR TITLE
AP_OSD: remove duplicate parameter definition

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Review by khancyr — COMMENTED** [review]
Seems good. But can't we auto check that on testing?

**Comment by peterbarker** [comment]
@khancyr I'm expecting this to fail CI - it's been failing for @andyp1per when he's tried to do the same.

You're right, 'though, we should be rejecting the current situation at parameter metadata generation time.

**Comment by peterbarker** [comment]
@andyp1per so this was my suggested fix - but it's not failing the test you suggested it would AFAICS?

**Comment by andyp1per** [comment]
IIRC you have to remove // @Path: AP_OSD_ParamSetting.cpp to get the test to fail. I think the change you have made causes the docs to be empty

**Comment by peterbarker** [comment]
Seems to leave an instance in.

And if we didn't have an instance then autotest should fail...

```
pbarker@bluebottle:~/rc/ardupilot(master)$ diff -u bad.xml ParameterMetaData.xml 
--- bad.xml	2020-11-20 08:22:57.322938424 +1100
+++ ParameterMetaData.xml	2020-11-20 08:24:41.239006447 +1100
@@ -10327,11 +10327,6 @@
       <Values>0:Disabled,1:Enabled</Values>
     </OSD5_ENABLE>
     <OSD5_PARAM1_EN>
-      <Description>Enables display of parameter 1</Description>
-      <DisplayName>PARAM1_EN</DisplayName>
-      <Values>0:Disabled,1:Enabled</Values>
-    </OSD5_PARAM1_EN>
-    <OSD5_PARAM1_EN>
       <Description>Enable setting</Description>
       <DisplayName>Enable</DisplayName>
       <User>Standard</User>
@@ -10374,22 +10369,12 @@
     </OSD5_PARAM1_TYPE>
     <OSD5_PARAM1_X>
       <Description>Horizontal position on screen</Description>
-      <DisplayName>PARAM1_X</DisplayName>
-      <Range>0 29</Range>
-    </OSD5_PARAM1_X>
-    <OSD5_PARAM1_X>
-      <Description>Horizontal position on screen</Description>
       <DisplayName>X position</DisplayName>
       <Range>0 29</Range>
       <User>Standard</User>
     </OSD5_PARAM1_X>
     <OSD5_PARAM1_Y>
       <Description>Vertical position on screen</Description>
-      <DisplayName>PARAM1_Y</DisplayName>
-      <Range>0 15</Range>
-    </OSD5_PARAM1_Y>
-    <OSD5_PARAM1_Y>
-      <Description>Vertical position on screen</Description>
       <DisplayName>Y position</DisplayName>
       <Range>0 15</Range>
       <User>Standard</User>
@@ -10969,11 +10954,6 @@
       <Values>0:Disabled,1:Enabled</Values>
     </OSD6_ENABLE>
     <OSD6_PARAM1_EN>
-      <Description>Enables display of parameter 1</Description>
-      <DisplayName>PARAM1_EN</DisplayName>
-      <Values>0:Disabled,1:Enabled</Values>
-    </OSD6_PARAM1_EN>
-    <OSD6_PARAM1_EN>
       <Description>Enable setting</Description>
       <DisplayName>Enable</DisplayName>
       <User>Standard</User>
@@ -11016,22 +10996,12 @@
     </OSD6_PARAM1_TYPE>
     <OSD6_PARAM1_X>
       <Description>Horizontal position on screen</Description>
-      <DisplayName>PARAM1_X</DisplayName>
-      <Range>0 29</Range>
-    </OSD6_PARAM1_X>
-    <OSD6_PARAM1_X>
-      <Description>Horizontal position on screen</Description>
       <DisplayName>X position</DisplayName>
       <Range>0 29</Range>
       <User>Standard</User>
     </OSD6_PARAM1_X>
     <OSD6_PARAM1_Y>
       <Description>Vertical position on screen</Description>
-      <DisplayName>PARAM1_Y</DisplayName>
-      <Range>0 15</Range>
-    </OSD6_PARAM1_Y>
-    <OSD6_PARAM1_Y>
-      <Description>Vertical position on screen</Description>
       <DisplayName>Y position</DisplayName>
       <Range>0 15</Range>
       <User>Standard</User>
```

**Comment by peterbarker** [comment]
@khancyr I looked at adding the duplicate check.

Unfortunately, because Heli and non-Heli Copter are runtime-switchable for the attitude control and motors we get name conflicts there.

https://github.com/ArduPilot/ardupilot/compare/master...peterbarker:wip/param-duplicate-check?expand=1

It *does* pick the problem up that this PR fixes, 'though :-)

```
pbarker@bluebottle:~/rc/ardupilot(wip/param-duplicate-check)$ ./Tools/autotest/param_metadata/param_parse.py --vehicle ArduCopter
Error in ../libraries/AC_AttitudeControl/AC_AttitudeControl_Heli.cpp
At param ATC_HOVR_ROL_TRM
ATC_RAT_RLL_P appears twice in parameters (also in ../libraries/AC_AttitudeControl/AC_AttitudeControl_Multi.cpp)
Error in ../libraries/AC_AttitudeControl/AC_AttitudeControl_Heli.cpp
At param ATC_RAT_RLL_P
ATC_RAT_RLL_I appears twice in parameters (also in ../libraries/AC_AttitudeControl/AC_AttitudeControl_Multi.cpp)
Error in ../libraries/AC_AttitudeControl/AC_AttitudeControl_Heli.cpp
At param ATC_RAT_RLL_I
ATC_RAT_RLL_IMAX appears twice in parameters (also in ../libraries/AC_AttitudeControl/AC_AttitudeControl_Multi.cpp)
Error in ../libraries/AC_AttitudeControl/AC_AttitudeControl_Heli.cpp
At param ATC_RAT_RLL_ILMI
ATC_RAT_RLL_D appears twice in parameters (also in ../libraries/AC_AttitudeControl/AC_AttitudeControl_Multi.cpp)
Error in ../libraries/AC_AttitudeControl/AC_AttitudeControl_Heli.cpp
At param ATC_RAT_RLL_VFF
ATC_RAT_RLL_FLTT appears twice in parameters (also in ../libraries/AC_AttitudeControl/AC_AttitudeControl_Multi.cpp)
Error in ../libraries/AC_AttitudeControl/AC_AttitudeControl_Heli.cpp
At param ATC_RAT_RLL_FLTT
ATC_RAT_RLL_FLTE appears twice in parameters (also in ../libraries/AC_AttitudeControl/AC_AttitudeControl_Multi.cpp)
Error in ../libraries/AC_AttitudeControl/AC_AttitudeControl_Heli.cpp
At param ATC_RAT_RLL_FLTE
ATC_RAT_RLL_FLTD appears twice in parameters (also in ../libraries/AC_AttitudeControl/AC_AttitudeControl_Multi.cpp)
Error in ../libraries/AC_AttitudeControl/AC_AttitudeControl_Heli.cpp
At param ATC_RAT_RLL_FLTD
ATC_RAT_RLL_SMAX appears twice in parameters (also in ../libraries/AC_AttitudeControl/AC_AttitudeControl_Multi.cpp)
Error in ../libraries/AC_AttitudeControl/AC_AttitudeControl_Heli.cpp
At param ATC_RAT_RLL_SMAX
ATC_RAT_PIT_P appears twice in parameters (also in ../libraries/AC_AttitudeControl/AC_AttitudeControl_Multi.cpp)
Error in ../libraries/AC_AttitudeControl/AC_AttitudeControl_Heli.cpp
At param ATC_RAT_PIT_P
ATC_RAT_PIT_I appears twice in parameters (also in ../libraries/AC_AttitudeControl/AC_AttitudeControl_Multi.cpp)
Error in ../libraries/AC_AttitudeControl/AC_AttitudeControl_Heli.cpp
At param ATC_RAT_PIT_I
ATC_RAT_PIT_IMAX appears twice in parameters (also in ../libraries/AC_AttitudeControl/AC_AttitudeControl_Multi.cpp)
Error in ../libraries/AC_AttitudeControl/AC_AttitudeControl_Heli.cpp
At param ATC_RAT_PIT_ILMI
ATC_RAT_PIT_D appears twice in parameters (also in ../libraries/AC_AttitudeControl/AC_AttitudeControl_Multi.cpp)
Error in ../libraries/AC_AttitudeControl/AC_AttitudeControl_Heli.cpp
At param ATC_RAT_PIT_VFF
ATC_RAT_PIT_FLTT appears twice in parameters (also in ../libraries/AC_AttitudeControl/AC_AttitudeControl_Multi.cpp)
Error in ../libraries/AC_AttitudeControl/AC_AttitudeControl_Heli.cpp
At param ATC_RAT_PIT_FLTT
ATC_RAT_PIT_FLTE appears twice in parameters (also in ../libraries/AC_AttitudeControl/AC_AttitudeControl_Multi.cpp)
Error in ../libraries/AC_AttitudeControl/AC_AttitudeControl_Heli.cpp
At param ATC_RAT_PIT_FLTE
ATC_RAT_PIT_FLTD appears twice in parameters (also in ../libraries/AC_AttitudeControl/AC_AttitudeControl_Multi.cpp)
Error in ../libraries/AC_AttitudeControl/AC_AttitudeControl_Heli.cpp
At param ATC_RAT_PIT_FLTD
ATC_RAT_PIT_SMAX appears twice in parameters (also in ../libraries/AC_AttitudeControl/AC_AttitudeControl_Multi.cpp)
Error in ../libraries/AC_AttitudeControl/AC_AttitudeControl_Heli.cpp
At param ATC_RAT_PIT_SMAX
ATC_RAT_YAW_P appears twice in parameters (also in ../libraries/AC_AttitudeControl/AC_AttitudeControl_Multi.cpp)
Error in ../libraries/AC_AttitudeControl/AC_AttitudeControl_Heli.cpp
At param ATC_RAT_YAW_P
ATC_RAT_YAW_I appears twice in parameters (also in ../libraries/AC_AttitudeControl/AC_AttitudeControl_Multi.cpp)
Error in ../libraries/AC_AttitudeControl/AC_AttitudeControl_Heli.cpp
At param ATC_RAT_YAW_I
ATC_RAT_YAW_IMAX appears twice in parameters (also in ../libraries/AC_AttitudeControl/AC_AttitudeControl_Multi.cpp)
Error in ../libraries/AC_AttitudeControl/AC_AttitudeControl_Heli.cpp
At param ATC_RAT_YAW_ILMI
ATC_RAT_YAW_D appears twice in parameters (also in ../libraries/AC_AttitudeControl/AC_AttitudeControl_Multi.cpp)
Error in ../libraries/AC_AttitudeControl/AC_AttitudeControl_Heli.cpp
At param ATC_RAT_YAW_VFF
ATC_RAT_YAW_FLTT appears twice in parameters (also in ../libraries/AC_AttitudeControl/AC_AttitudeControl_Multi.cpp)
Error in ../libraries/AC_AttitudeControl/AC_AttitudeControl_Heli.cpp
At param ATC_RAT_YAW_FLTT
ATC_RAT_YAW_FLTE appears twice in parameters (also in ../libraries/AC_AttitudeControl/AC_AttitudeControl_Multi.cpp)
Error in ../libraries/AC_AttitudeControl/AC_AttitudeControl_Heli.cpp
At param ATC_RAT_YAW_FLTE
ATC_RAT_YAW_FLTD appears twice in parameters (also in ../libraries/AC_AttitudeControl/AC_AttitudeControl_Multi.cpp)
Error in ../libraries/AC_AttitudeControl/AC_AttitudeControl_Heli.cpp
At param ATC_RAT_YAW_FLTD
ATC_RAT_YAW_SMAX appears twice in parameters (also in ../libraries/AC_AttitudeControl/AC_AttitudeControl_Multi.cpp)
Error in ../libraries/AP_Motors/AP_MotorsHeli_Dual.cpp
At param H_COL2_MID
H_SW_TYPE appears twice in parameters (also in ../libraries/AP_Motors/AP_MotorsHeli_Single.cpp)
Error in ../libraries/AP_Motors/AP_MotorsHeli_Dual.cpp
At param H_SW_TYPE
H_SW_COL_DIR appears twice in parameters (also in ../libraries/AP_Motors/AP_MotorsHeli_Single.cpp)
Error in ../libraries/AP_Motors/AP_MotorsHeli_Dual.cpp
At param H_SW_COL_DIR
H_SW_LIN_SVO appears twice in parameters (also in ../libraries/AP_Motors/AP_MotorsHeli_Single.cpp)
Error in ../libraries/AP_Motors/AP_MotorsHeli_Dual.cpp
At param H_SW_LIN_SVO
H_SW_H3_ENABLE appears twice in parameters (also in ../libraries/AP_Motors/AP_MotorsHeli_Single.cpp)
Error in ../libraries/AP_Motors/AP_MotorsHeli_Dual.cpp
At param H_SW_H3_ENABLE
H_SW_H3_SV1_POS appears twice in parameters (also in ../libraries/AP_Motors/AP_MotorsHeli_Single.cpp)
Error in ../libraries/AP_Motors/AP_MotorsHeli_Dual.cpp
At param H_SW_H3_SV1_POS
H_SW_H3_SV2_POS appears twice in parameters (also in ../libraries/AP_Motors/AP_MotorsHeli_Single.cpp)
Error in ../libraries/AP_Motors/AP_MotorsHeli_Dual.cpp
At param H_SW_H3_SV2_POS
H_SW_H3_SV3_POS appears twice in parameters (also in ../libraries/AP_Motors/AP_MotorsHeli_Single.cpp)
Error in ../libraries/AP_Motors/AP_MotorsHeli_Dual.cpp
At param H_SW_H3_SV3_POS
H_SW_H3_PHANG appears twice in parameters (also in ../libraries/AP_Motors/AP_MotorsHeli_Single.cpp)
Error in AP_OSD_ParamScreen.cpp
At param OSD5_SAVE_Y
OSD5_PARAM1_EN appears twice in parameters (also in AP_OSD_ParamScreen.cpp)
Error in AP_OSD_ParamSetting.cpp
At param OSD5_PARAM1_EN
OSD5_PARAM1_X appears twice in parameters (also in AP_OSD_ParamScreen.cpp)
Error in AP_OSD_ParamSetting.cpp
At param OSD5_PARAM1_X
OSD5_PARAM1_Y appears twice in parameters (also in AP_OSD_ParamScreen.cpp)
Error in AP_OSD_ParamSetting.cpp
At param OSD5_PARAM1_TYPE
OSD5_PARAM2_EN appears twice in parameters (also in AP_OSD_ParamScreen.cpp)
Error in AP_OSD_ParamSetting.cpp
At param OSD5_PARAM2_EN
OSD5_PARAM2_X appears twice in parameters (also in AP_OSD_ParamScreen.cpp)
Error in AP_OSD_ParamSetting.cpp
At param OSD5_PARAM2_X
OSD5_PARAM2_Y appears twice in parameters (also in AP_OSD_ParamScreen.cpp)
Error in AP_OSD_ParamSetting.cpp
At param OSD5_PARAM2_TYPE
OSD5_PARAM3_EN appears twice in parameters (also in AP_OSD_ParamScreen.cpp)
Error in AP_OSD_ParamSetting.cpp
At param OSD5_PARAM3_EN
OSD5_PARAM3_X appears twice in parameters (also in AP_OSD_ParamScreen.cpp)
Error in AP_OSD_ParamSetting.cpp
At param OSD5_PARAM3_X
OSD5_PARAM3_Y appears twice in parameters (also in AP_OSD_ParamScreen.cpp)
Error in AP_OSD_ParamSetting.cpp
At param OSD5_PARAM3_TYPE
OSD5_PARAM4_EN appears twice in parameters (also in AP_OSD_ParamScreen.cpp)
Error in AP_OSD_ParamSetting.cpp
At param OSD5_PARAM4_EN
OSD5_PARAM4_X appears twice in parameters (also in AP_OSD_ParamScreen.cpp)
Error in AP_OSD_ParamSetting.cpp
At param OSD5_PARAM4_X
OSD5_PARAM4_Y appears twice in parameters (also in AP_OSD_ParamScreen.cpp)
Error in AP_OSD_ParamSetting.cpp
At param OSD5_PARAM4_TYPE
OSD5_PARAM5_EN appears twice in parameters (also in AP_OSD_ParamScreen.cpp)
Error in AP_OSD_ParamSetting.cpp
At param OSD5_PARAM5_EN
OSD5_PARAM5_X appears twice in parameters (also in AP_OSD_ParamScreen.cpp)
Error in AP_OSD_ParamSetting.cpp
At param OSD5_PARAM5_X
OSD5_PARAM5_Y appears twice in parameters (also in AP_OSD_ParamScreen.cpp)
Error in AP_OSD_ParamSetting.cpp
At param OSD5_PARAM5_TYPE
OSD5_PARAM6_EN appears twice in parameters (also in AP_OSD_ParamScreen.cpp)
Error in AP_OSD_ParamSetting.cpp
At param OSD5_PARAM6_EN
OSD5_PARAM6_X appears twice in parameters (also in AP_OSD_ParamScreen.cpp)
Error in AP_OSD_ParamSetting.cpp
At param OSD5_PARAM6_X
OSD5_PARAM6_Y appears twice in parameters (also in AP_OSD_ParamScreen.cpp)
Error in AP_OSD_ParamSetting.cpp
At param OSD5_PARAM6_TYPE
OSD5_PARAM7_EN appears twice in parameters (also in AP_OSD_ParamScreen.cpp)
Error in AP_OSD_ParamSetting.cpp
At param OSD5_PARAM7_EN
OSD5_PARAM7_X appears twice in parameters (also in AP_OSD_ParamScreen.cpp)
Error in AP_OSD_ParamSetting.cpp
At param OSD5_PARAM7_X
OSD5_PARAM7_Y appears twice in parameters (also in AP_OSD_ParamScreen.cpp)
Error in AP_OSD_ParamSetting.cpp
At param OSD5_PARAM7_TYPE
OSD5_PARAM8_EN appears twice in parameters (also in AP_OSD_ParamScreen.cpp)
Error in AP_OSD_ParamSetting.cpp
At param OSD5_PARAM8_EN
OSD5_PARAM8_X appears twice in parameters (also in AP_OSD_ParamScreen.cpp)
Error in AP_OSD_ParamSetting.cpp
At param OSD5_PARAM8_X
OSD5_PARAM8_Y appears twice in parameters (also in AP_OSD_ParamScreen.cpp)
Error in AP_OSD_ParamSetting.cpp
At param OSD5_PARAM8_TYPE
OSD5_PARAM9_EN appears twice in parameters (also in AP_OSD_ParamScreen.cpp)
Error in AP_OSD_ParamSetting.cpp
At param OSD5_PARAM9_EN
OSD5_PARAM9_X appears twice in parameters (also in AP_OSD_ParamScreen.cpp)
Error in AP_OSD_ParamSetting.cpp
At param OSD5_PARAM9_X
OSD5_PARAM9_Y appears twice in parameters (also in AP_OSD_ParamScreen.cpp)
Error in AP_OSD_ParamScreen.cpp
At param OSD6_SAVE_Y
OSD6_PARAM1_EN appears twice in parameters (also in AP_OSD_ParamScreen.cpp)
Error in AP_OSD_ParamSetting.cpp
At param OSD6_PARAM1_EN
OSD6_PARAM1_X appears twice in parameters (also in AP_OSD_ParamScreen.cpp)
Error in AP_OSD_ParamSetting.cpp
At param OSD6_PARAM1_X
OSD6_PARAM1_Y appears twice in parameters (also in AP_OSD_ParamScreen.cpp)
Error in AP_OSD_ParamSetting.cpp
At param OSD6_PARAM1_TYPE
OSD6_PARAM2_EN appears twice in parameters (also in AP_OSD_ParamScreen.cpp)
Error in AP_OSD_ParamSetting.cpp
At param OSD6_PARAM2_EN
OSD6_PARAM2_X appears twice in parameters (also in AP_OSD_ParamScreen.cpp)
Error in AP_OSD_ParamSetting.cpp
At param OSD6_PARAM2_X
OSD6_PARAM2_Y appears twice in parameters (also in AP_OSD_ParamScreen.cpp)
Error in AP_OSD_ParamSetting.cpp
At param OSD6_PARAM2_TYPE
OSD6_PARAM3_EN appears twice in parameters (also in AP_OSD_ParamScreen.cpp)
Error in AP_OSD_ParamSetting.cpp
At param OSD6_PARAM3_EN
OSD6_PARAM3_X appears twice in parameters (also in AP_OSD_ParamScreen.cpp)
Error in AP_OSD_ParamSetting.cpp
At param OSD6_PARAM3_X
OSD6_PARAM3_Y appears twice in parameters (also in AP_OSD_ParamScreen.cpp)
Error in AP_OSD_ParamSetting.cpp
At param OSD6_PARAM3_TYPE
OSD6_PARAM4_EN appears twice in parameters (also in AP_OSD_ParamScreen.cpp)
Error in AP_OSD_ParamSetting.cpp
At param OSD6_PARAM4_EN
OSD6_PARAM4_X appears twice in parameters (also in AP_OSD_ParamScreen.cpp)
Error in AP_OSD_ParamSetting.cpp
At param OSD6_PARAM4_X
OSD6_PARAM4_Y appears twice in parameters (also in AP_OSD_ParamScreen.cpp)
Error in AP_OSD_ParamSetting.cpp
At param OSD6_PARAM4_TYPE
OSD6_PARAM5_EN appears twice in parameters (also in AP_OSD_ParamScreen.cpp)
Error in AP_OSD_ParamSetting.cpp
At param OSD6_PARAM5_EN
OSD6_PARAM5_X appears twice in parameters (also in AP_OSD_ParamScreen.cpp)
Error in AP_OSD_ParamSetting.cpp
At param OSD6_PARAM5_X
OSD6_PARAM5_Y appears twice in parameters (also in AP_OSD_ParamScreen.cpp)
Error in AP_OSD_ParamSetting.cpp
At param OSD6_PARAM5_TYPE
OSD6_PARAM6_EN appears twice in parameters (also in AP_OSD_ParamScreen.cpp)
Error in AP_OSD_ParamSetting.cpp
At param OSD6_PARAM6_EN
OSD6_PARAM6_X appears twice in parameters (also in AP_OSD_ParamScreen.cpp)
Error in AP_OSD_ParamSetting.cpp
At param OSD6_PARAM6_X
OSD6_PARAM6_Y appears twice in parameters (also in AP_OSD_ParamScreen.cpp)
Error in AP_OSD_ParamSetting.cpp
At param OSD6_PARAM6_TYPE
OSD6_PARAM7_EN appears twice in parameters (also in AP_OSD_ParamScreen.cpp)
Error in AP_OSD_ParamSetting.cpp
At param OSD6_PARAM7_EN
OSD6_PARAM7_X appears twice in parameters (also in AP_OSD_ParamScreen.cpp)
Error in AP_OSD_ParamSetting.cpp
At param OSD6_PARAM7_X
OSD6_PARAM7_Y appears twice in parameters (also in AP_OSD_ParamScreen.cpp)
Error in AP_OSD_ParamSetting.cpp
At param OSD6_PARAM7_TYPE
OSD6_PARAM8_EN appears twice in parameters (also in AP_OSD_ParamScreen.cpp)
Error in AP_OSD_ParamSetting.cpp
At param OSD6_PARAM8_EN
OSD6_PARAM8_X appears twice in parameters (also in AP_OSD_ParamScreen.cpp)
Error in AP_OSD_ParamSetting.cpp
At param OSD6_PARAM8_X
OSD6_PARAM8_Y appears twice in parameters (also in AP_OSD_ParamScreen.cpp)
Error in AP_OSD_ParamSetting.cpp
At param OSD6_PARAM8_TYPE
OSD6_PARAM9_EN appears twice in parameters (also in AP_OSD_ParamScreen.cpp)
Error in AP_OSD_ParamSetting.cpp
At param OSD6_PARAM9_EN
OSD6_PARAM9_X appears twice in parameters (also in AP_OSD_ParamScreen.cpp)
Error in AP_OSD_ParamSetting.cpp
At param OSD6_PARAM9_X
OSD6_PARAM9_Y appears twice in parameters (also in AP_OSD_ParamScreen.cpp)
pbarker@bluebottle:~/rc/ardupilot(wip/param-duplicate-check)$ 
```

**Comment by peterbarker** [comment]
AFAICS this works.  Passes tests, seems to remove the duplicates appropriately.  So I'm a bit confused.

@andyp1per should we merge this?

**Comment by peterbarker** [comment]
@Hwurzburg for visibility....

**Comment by andyp1per** [comment]
I'm confused as well, maybe my testing wasn't very good. If it doesn't break the tests then by all means merge.

**Comment by peterbarker** [comment]
I've removed all of the *other* duplicate documentation entries.

I tested the output rst files in a Wiki build and the warnings have gone away.

**Review by andyp1per — APPROVED** [review]

**Comment by andyp1per** [comment]
Apologies for the confusion. I really must have been imagining things.

**Pull request merged**
