### PR TITLE
AP_HAL_Linux: RCOutput_Bebop: fixed potential deadlock

### PR DESCRIPTION
**Pull request by linuxjumper**
unlock the mutex before continue to the next loop

### CODE REVIEW

**Comment by jberaud** [comment]
Thanks for spotting that.

**Comment by tridge** [comment]
applied, thanks!

**Comment by jberaud** [comment]
@linuxjumper I don't understand why you pushed the Airspeed change though.

**Comment by linuxjumper** [comment]
@jberaud anything wrong? I thought I had separated it into another pull request

**Comment by jberaud** [comment]
@linuxjumper ok, it's a mistake then https://github.com/ArduPilot/ardupilot/pull/4808/commits.
No worries, @tridge has merged the first commit only.

**Comment by OXINARF** [comment]
@jberaud Actually both were merged: https://github.com/ArduPilot/ardupilot/commit/cc28c8e6eec943447fa70649b48ff6e5f1b2bde3

**Comment by linuxjumper** [comment]
@jberaud that's fine, thank you.

**Comment by jberaud** [comment]
@OXINARF Ok. That's a problem then. If someone could review and/or revert the airspeed commit that would be fine because I really can't test that.

**Comment by linuxjumper** [comment]
@jberaud Actually, "data[0] & 0xC0" should never be 2 or 3. According to the [datasheet](http://www.te.com/commerce/DocumentDelivery/DDEController?Action=showdoc&DocId=Specification+Or+Standard%7FInterfacing_to_DigitalPressure_Modules%7FA1%7Fpdf%7FEnglish%7FENG_SS_Interfacing_to_DigitalPressure_Modules_A1.pdf%7FCAT-MIPS0037), the 2 MSBs of first i2c data packet is the status bits.

**Comment by OXINARF** [comment]
@linuxjumper I think a fair bit of times datasheets have been proven wrong, so testing should always be done.

**Comment by linuxjumper** [comment]
@OXINARF Yes, I couldn't agree more. I had made a mistake to not to separate it into another pull request. I found several ms4515do drivers([1](https://github.com/lsoltmann/Libraries/blob/master/MS4515.cpp) and [2](https://github.com/navstik/navstik-base/blob/master/src/Sensors/DifferentialPressure/hld/MS4515.c)), they did just what i did. Someone could review the airspeed commit would be great.

**Comment by tridge** [comment]
I did review the airspeed change, and it is correct. It does work both ways so it wasn't causing any issues, but the shift is correct.
I also tested it on Disco and its fine.

**Pull request closed without merging**
