### PR TITLE
Tools - added extra packages for Cygwin environment setup scripts

### PR DESCRIPTION
**Pull request by stephendade**
Added a few extra packages to support building ChibiOS targets in Cygwin

### CODE REVIEW

**Comment by rmackay9** [comment]
do we really want catkin_pkg?  this is a ROS related package and it surprises me that we would need this by default.

**Comment by khancyr** [comment]
the catkin_pkg shouldn't be needed for chibios... it was need by px4 but I don't think  it is require now

**Comment by stephendade** [comment]
I'll double check in the morning if catkin_pkg is actually required. I was doing some px4 stuff too ... so could be mixed up in there.

**Comment by OXINARF** [comment]
At least with waf we don't need catkin_pkg, I don't have it installed and I have no problem building.

**Comment by stephendade** [comment]
Yep, confirmed it works without catkin_pkg. I've amended the commit so that it's not included.

**Comment by rmackay9** [comment]
semaphore failed so kicking off again.. hopefully it'll work on a second attempt.

**Comment by lvale** [comment]
I've removed the catkin dependency on MacOS. There are no packages that depended on it, it was a px4 dev environment legacy

**Comment by rmackay9** [comment]
OK, it's passed the automated tests so merged!

**Comment by WickedShell** [comment]
@rmackay9 just to note: none of CI testing is running through cygwin/windows scripts, so this hasn't been tested by the CI system.

**Pull request merged**
