### PR TITLE
Make SYSID_SW_TYPE @Values consistent across vehicles

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
Talking about consistency... any reason for some of them to have "Ardu" prefix and others not?

**Comment by amilcarlucas** [comment]
I whould like to see consistent names as well, but otherwise LGTM

**Comment by jaxxzer** [comment]
Why do we have this parameter, is it still used by mission planner or something? This information is available via HEARTBEAT message. I've been considering taking this param out of Sub entirely.

**Comment by rmackay9** [comment]
Good questions above but I'm going to merge this in any case.  If @peterbarker wants to address in a follow up PR, he may!

**Pull request merged**
