### PR TITLE
Plane: remove logging of CMDI

### PR DESCRIPTION
**Pull request by peterbarker**
This is a duplicate of the data logged into "MAVC"

### CODE REVIEW

**Comment by peterbarker** [comment]
.... OK, not a duplicate, you don't get the unused `autocontinue` or `current` - but you *do* get `result` in `MAVC` :-)

**Comment by peterbarker** [comment]
.... OK, not a duplicate, you don't get the unused `autocontinue` or `current` - but you *do* get `result` in `MAVC` :-)

**Review by nkruzan — APPROVED** [review]
Saves flash on F405 plane

**Comment by peterbarker** [comment]
As @nkruzan says, saves bytes on F405:
```
Binary Name      Text [B]         Data [B]     BSS (B)       Total Flash Change [B] (%)      Flash Free After PR (B)
---------------  ---------------  -----------  ------------  ----------------------------  -------------------------
antennatracker   0 (0.0000%)      0 (0.0000%)  0 (0.0000%)   0 (0.0000%)                                      323940
blimp            0 (0.0000%)      0 (0.0000%)  0 (0.0000%)   0 (0.0000%)                                      305340
ardurover        0 (0.0000%)      0 (0.0000%)  0 (0.0000%)   0 (0.0000%)                                      146132
arducopter-heli  0 (0.0000%)      0 (0.0000%)  0 (0.0000%)   0 (0.0000%)                                       44192
ardusub          0 (0.0000%)      0 (0.0000%)  0 (0.0000%)   0 (0.0000%)                                      174700
arduplane        -444 (-0.0462%)  0 (0.0000%)  4 (+0.0031%)  -444 (-0.0461%)                                   20116
arducopter       0 (0.0000%)      0 (0.0000%)  0 (0.0000%)   0 (0.0000%)                                       57048
```

**Comment by davidbuzz** [comment]
The three CMD variants were made to make graphing of CMDI's for heading,speed and alt easier to graph, removing them looses this, personally, i'd prefer if this PR was not merged.

**Comment by davidbuzz** [comment]
An alternative option would be to leave the codein, and wrap the code in #defines so they aren't used on small builds like the F40x series .

**Comment by peterbarker** [comment]
> The three CMD variants were made to make graphing of CMDI's for heading,speed and alt easier to graph, removing them looses this, personally, i'd prefer if this PR was not merged.

Is anybody on the planet currently using these commands?

*How* exactly do these `CMDI` messages make it any easier to graph the information?!  Aren't the existing dataflash messages essentially identical?

**Review by WickedShell — APPROVED** [review]
I don't see a good reason to retain the separate ones, particularly because it's duplicated logging of the same thing, and a plane special. I don't think there are enough commands sent normally that means it would get to confusing to differentiate the commands in a graphing tool.

**Review by tridge — APPROVED** [review]

**Comment by davidbuzz** [comment]
>Is anybody on the planet currently using these commands?
One of the project i worked in used it. I'm not involved in that project any more , so  can't save if its still important to them, i guess since this was merged, we'll find out.

**Pull request merged**
