### PR TITLE
Deprecate EKF1 and replace with EKF3 for new feature evaluation

### PR DESCRIPTION
**Pull request by priseborough**
This has been tested using a pixhawk 2.1 on an Iris with range beacon only and GPS + Optical flow modes of operation. Tuning of the EKF3 is preliminary and provides equivalent innovation sequences.

EKF3 uses 24 states the same as EKF2 .

EKF 3 uses essentially the same interfaces and data buffers and control logic as EKF2.

EKF3 makes the following changes to the state vector:

- The 3 attitude error states are replaced with a direct quaternion representation (4 states)
- The XYZ gyro scale factor states are removed
- The Z axis accel bias is extended to include X and y axes

This is expected to provide a more accurate attitude solution for the majority of use cases,  but does lose some of the ability to recover from extreme attitude errors caused by bad IMU data.

At the moment it exceeds the flash space 1MB build limit that the build system applies to all Pixhawk 2 and lower boards regardless of capability, so a temporary change to the PX4Firmware has been made to enable it to be built for the Pixhawk 2.1.

### CODE REVIEW

**Comment by tridge** [comment]
after discussions with paul and @rmackay9 I will add a FMUV3 (px4-v3) build option to enable over 2MB flash. We will initially drop canbus support on FMUv2 to allow EKF3 to be tested as widely as possible, and have it enabled on FMUv2

**Comment by tridge** [comment]
I have a test branch here:
https://github.com/tridge/ardupilot/tree/priseborough-ekf3-wip
this adds FMUv3 and sets up FMUv2 to not build uavcan

**Comment by priseborough** [comment]
@tridge I've flown your test branch on a copter with a pixhawk 2.1 using optical flow, range finder and GPS with AHRS_EKF_TYPE = 3 and with EK2_IMU_MASK and EK3_IMU_MASK = 1. Flight characteristics were good and the log data for both EKF's looked good, however there were some frame over-runs:
 
screen shot 2016-12-11 at 9 44 02 pm

One explanation is that when running an EKF2 and EKF3,  the fusion processing is not time offset to level the load like it is when running either EKF2 or EKF3 on its own with two IMU's. I will repeat the test twice tomorrow with the following parameters to test this hypothesis:

AHRS_EKF_TYPE = 2, EKF2_ENABLE = 1, EK3_ENABLE = 0, EK2_IMU_MASK = 3

and:

AHRS_EKF_TYPE = 3, EKF2_ENABLE = 0, EK3_ENABLE = 1, EK3_IMU_MASK = 3

Other contributory factors are:

1) The larger number of sensors being fused by the EKF (Magnetometer, Baro, GPS, range finder and optical flow)

2) This was a pixhawk 2.1 (3 IMU's, two mags, two baros) with additional baro and mag sensors on the GPS, and also a range beacon sensor connected in addition to the optical flow and range finder,  so it is close to a worst case scenario in terms of sensor interrupts.

**Comment by magicrub** [comment]
Paul, that's a lot of sensors! Perhaps a test of a single EKF type with all
those sensors for sanity's sake?

**Comment by priseborough** [comment]
I ran separate tests again with EKF2 and EKF3 with only one core, and the results were better:

EKF2, one core:

screen shot 2016-12-12 at 8 26 50 am


EKF3, one core:

screen shot 2016-12-12 at 8 27 51 am

**Comment by tridge** [comment]
@gmorph and I did some flights today on a Firstar with EKF3 enabled. The last two flights started with zero accel offsets to test how it handled learning accel offsets from scratch. logs here:
http://uav.tridgell.net/GrantFirstar/
the first two flights suffered from a bug where the EKF3 state was not logged. It logged OK in copter, but not in plane or rover. I've fixed that in this branch:
https://github.com/tridge/ardupilot/tree/priseborough-ekf3-wip

**Comment by tridge** [comment]
during the test flights the first core of EKF3 did really well, but the 2nd core got bad position innovations. I've reproduced the problem in SITL. Using these parameters:
 http://uav.tridgell.net/EKF3-testing/ekf3-test.parm
which setup equal accel biases on both accels in SITL, the first core does really well, but the 2nd core gets very bad position innovations and fails to learn the accel biases correctly.
http://uav.tridgell.net/EKF3-testing/62.BIN

**Comment by tridge** [comment]
pushed, thanks Paul!

**Pull request merged**
