### PR TITLE
AP_Rally: tidy calculation of nearest rally/home

### PR DESCRIPTION
**Pull request by peterbarker**
Also clarify that the argument is in cm AMSL

### CODE REVIEW

**Review by khancyr — APPROVED** [review]
Good one.
small gains here.
safe to merge, equivalence is total.
usage was checked to ensure that only alt in cm were used and that is all good.

**Comment by peterbarker** [comment]
> I think I've noticed a problem with RTL from a fence breach. As far as I understand it a fence breach should RTL to a "Breach Point" (if set) - and I usually set one, but what I think I see is that fence breach is doing RTL to a Rally point, or to home and the breach point is being ignored. Is that behavior covered by this code @peterbarker ?

This test seems to show that we can return to the fence return point:
https://github.com/ardupilot/ardupilot/blob/master/Tools/autotest/arduplane.py#L1455

Check the value of your `FENCE_RET_RALLY` parameter.

This PR is only tangentially related to the problem you're seeing, and does not change behaviour.

**Comment by peterbarker** [comment]
@khancyr made a slight tweak here to tidy it a little more.

**Review by IamPete1 — APPROVED** [review]

**Comment by timtuxworth** [comment]
Thanks @peterbarker I've made a post on Discuss about the issue I'm seeing. I replicated it in SITL and I've posted some logs. https://discuss.ardupilot.org/t/fence-breach-ignores-fence-return-point-always-returns-to-launch-or-rally-location/87984?u=timtuxworth

**Review by tridge — APPROVED** [review]

**Pull request merged**
