### PR TITLE
Enable logging on iFlight 2RAW H743 and rename board

### PR DESCRIPTION
**Pull request by andyp1per**
iFlight requested the name change.

The flash chip is actually accessible via the microSD interface

### CODE REVIEW

**Comment by peterbarker** [comment]
@andyp1per I suggest creating a PR against the 4.5 branch, rather than just labelling this one.  You will need to adjust the LED defines at the very least for the 4.5 branch

**Comment by Hwurzburg** [comment]
this impacts the wiki page already pending and needs readme changes....hard to catch these without review or wiki label! a little help would be appreciated!

**Comment by rmackay9** [comment]
I tried to include this in 4.5.6-beta1 but was unable to due to a merge conflict.  If someone is keen on including this in 4.5 then a backport PR would be greatly appreciated!

**Comment by rmackay9** [comment]
I've removed the 4.5 backport label because this PR is included in https://github.com/ArduPilot/ardupilot/pull/27662

**Pull request merged**
