### PR TITLE
resolved stability issue in tail sitter in qrtl mode

### PR DESCRIPTION
**Pull request by nishant-sg**
ArduPlane : Fixing issue in tailsitter https://github.com/ArduPilot/ardupilot/issues/25771

Changed tailsitter condtion to maintain height after transition into VTOL and in QRTL mode
Increased duration transition to VTOL in tailisitter to 2 seconds to provide better stability.

Before:

https://github.com/ArduPilot/ardupilot/assets/70840360/1ede6dd3-1334-4d6c-93ac-c7cb5831fa06

After:

https://www.youtube.com/watch?v=CDkLzWjN6Zs

### CODE REVIEW

**Comment by robustini** [comment]
@nishant-sg this PR was not carried out correctly, it will never be approved like that.

**Comment by robustini** [comment]
Check this in my repo, this is the correct way to present a PR.

https://github.com/robustini/ardupilot/commit/29be894a9ed854ce5732af461f9f75e56110cbba

**Comment by robustini** [comment]
@nishant-sg check this in my repo, this is the correct way to present a PR, only the necessary changes in the files.
So please close this PR and redo a correct one, or if you want I'll apply mine by mentioning you for the fixes.

https://github.com/robustini/ardupilot/commit/7465a467decde8088f8e8ef0778379860d0c049a

**Comment by nishant-sg** [comment]
Yes I noticed some unwanted files have gone into the PR. I will fix it later in the day, thanks for pointing it out.

**Comment by robustini** [comment]
> Yes I noticed some unwanted files have gone into the PR. I will fix it later in the day, thanks for pointing it out.

Copy the changes from my fork, exactly as I did.

**Pull request closed without merging**
