### PR TITLE
Scripting: allow setting of ESC RPM from a lua script

### PR DESCRIPTION
**Pull request by tridge**
This gives a powerful way of setting up notches for LUA scripts, and reporting engine RPMs. I added this for CAN EFI engines, but it could be used for any ESC telem protocol

### CODE REVIEW

**Comment by IamPete1** [comment]
Shouldn't we have a scripting ESC telm backend? Seems like a bad idea to be racing whatever backed it is configured for.

**Comment by tridge** [comment]
> Shouldn't we have a scripting ESC telm backend? Seems like a bad idea to be racing whatever backed it is configured for.

you presumably won't have 2 different backends updating the same motors, so I don't see the race you're referring to

note that the race I fixed in one of the patches in this PR affects all existing backends

**Comment by IamPete1** [comment]
Your right, I guess my question then becomes how do we make sure we don't get two sources of data for each ESC. Possibly the assumption up to now is that you only ever have one type enabled at a time?

We could pass a source enum in the update calls and if it ever changes we could give a pre-arm error. 

We could also do a fancy manual binding for the `update_telem_data` function that took named values and automatically worked out the correct bit mask. I would be tempted to include the RPM in that. Its a little odd having RPM and everything else in a separate function when there is a handy bitmask for valid fields.

**Comment by tridge** [comment]
> We could pass a source enum in the update calls and if it ever changes we could give a pre-arm error.

I think it is just one of those "don't do that" things - users who setup ESC telem and scripting ESC telem at the same time will notice the issue and change their script

**Review by andyp1per — APPROVED** [review]

**Pull request merged**
