### PR TITLE
Sim state

### PR DESCRIPTION
**Pull request by khancyr**
This allow SITL to send the MAVLink SIM_STATE message that is different from ArduPilot SIMSTATE one.
It send quaternion, altitude and NED velocity that aren't present in the SIMSTATE msg

### CODE REVIEW

**Review by peterbarker — COMMENTED** [review]
Looks correct technically.

Has somebody asked for this?

**Comment by khancyr** [comment]
Yep, I am asking for it! I need the alt and speed information for some external tools

**Comment by peterbarker** [comment]
On Sun, 17 Jan 2021, Pierre Kancir wrote:

> Yep, I am asking for it! I need the alt and speed information for some external tools

OK, and you considered extension fields instead?  Not saying they're 
better (*I* havne't given it thought ;-), but it would be nice to know...

**Comment by tridge** [comment]
maybe just switch to SIM_STATE? Only lossage seems to be loss of precision in lat/lon

**Comment by tridge** [comment]
we'll merge now, but be nice to switch over completely

**Pull request merged**
