### PR TITLE
Tools: Install the right serial module for Ubuntu lunar

### LINKED ISSUE #24594: install_ubuntu_prereqs installs wrong serial
## Bug report

**Issue details**

Ubuntu 23.04 **lunar,** creating a virtual environment and trying to upload code to the board. 

Error: 

**Version**

latest master `47efaf9c6233a262198a27c557ef96806e875138`

**Platform**
[ x] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Hardware type**
All boards tested

**Logs**
``` 
$  ./Tools/environment_install/install-prereqs-ubuntu.sh
...
$ source ~/venv-ardupilot/bin/activate
(venv-ardupilot) ryan@ryan-B650-970:~/Development/ardu_ws/src/ardupilot$ nice ./waf plane --upload --upload-port=/dev/ttyACM2
Waf: Entering directory `/home/ryan/Development/ardu_ws/src/ardupilot/build/Pixhawk6X'
Checking for env.py
env added USE_ALT_RAM_MAP=1
env added OPTIMIZE=-O2
env added BUILD_ABIN=True
env added ENABLE_DFU_BOOT=1
env added WITH_FATFS=1
env added WITH_NETWORKING=True
env added PROCESS_STACK=0x1C00
env added MAIN_STACK=0x600
env added IOMCU_FW=0
env added PERIPH_FW=0
env added HAL_NUM_CAN_IFACES=2
env added HAL_CANFD_SUPPORTED=4
env added BOARD_FLASH_SIZE=2048
env added EXT_FLASH_SIZE_MB=0
env added INT_FLASH_PRIMARY=False
env added ENABLE_CRASHDUMP=True
env appended APP_RAM_START=None
env appended CPU_FLAGS=['-mcpu=cortex-m7', '-mfpu=fpv5-d16', '-mfloat-abi=hard', '-DARM_MATH_CM7', '-u_printf_float']
env added CORTEX=cortex-m7
env added APJ_BOARD_ID=53
env added APJ_BOARD_TYPE=STM32H743xx
env added USBID=0x1209/0x5740
env added FLASH_RESERVE_START_KB=128
env added EXT_FLASH_RESERVE_START_KB=0
env added FLASH_TOTAL=1966080
env added HAS_EXTERNAL_FLASH_SECTIONS=0
env added CHIBIOS_BUILD_FLAGS=USE_FATFS=yes USE_LWIP=yes CHIBIOS_STARTUP_MK=os/common/startup/ARMCMx/compilers/GCC/mk/startup_stm32h7xx.mk CHIBIOS_PLATFORM_MK=os/hal/ports/STM32/STM32H7xx/platform.mk MCU=cortex-m7 ENV_UDEFS=-DCHPRINTF_USE_FLOAT=1
Padded 20 bytes for bootloader.bin to 17888
Embedding file bootloader.bin:/home/ryan/Development/ardu_ws/src/ardupilot/Tools/bootloaders/Pixhawk6X_bl.bin
Embedding file hwdef.dat:/home/ryan/Development/ardu_ws/src/ardupilot/build/Pixhawk6X/hw.dat
Embedding file io_firmware.bin:Tools/IO_Firmware/iofirmware_lowpolh.bin
Embedding file param/CUAV_V6X_defaults.parm:/home/ryan/Development/ardu_ws/src/ardupilot/libraries/AP_HAL_ChibiOS/hwdef/Pixhawk6X/param/CUAV_V6X_defaults.parm
building /home/ryan/Development/ardu_ws/src/ardupilot/build/Pixhawk6X/modules/Micro-XRCE-DDS-Client/include/uxr/client/config.h
building /home/ryan/Development/ardu_ws/src/ardupilot/build/Pixhawk6X/modules/Micro-CDR/include/ucdr/config.h
[1128/1135] Linking build/Pixhawk6X/bin/arduplane
[1129/1135] Generating bin/arduplane.bin
[1130/1135] app_descriptor build/Pixhawk6X/bin/arduplane.bin
No APP_DESCRIPTOR found
[1131/1135] apj_gen build/Pixhawk6X/bin/arduplane.bin
[1132/1135] bin cleanup build/Pixhawk6X/bin/arduplane.bin
[1133/1135] Generating bin/arduplane.abin
[1134/1135] Uploading build/Pixhawk6X/bin/arduplane.apj
[1135/1135] Generating bin/arduplane.hex
githash 47efaf9c6233a262198a27c557ef96806e875138 md5 f051004af6ffdf2f30abcd453b38fe7c
Created bin/arduplane.abin

Loaded firmware for 35,0, size: 1856208 bytes, waiting for the bootloader...
If the board does not respond within 1-2 seconds, unplug and re-plug the USB connector.
Exception creating uploader: module 'serial' has no attribute 'Serial'
```

```
(venv-ardupilot) ryan@ryan-B650-970:~/Development/ardu_ws/src/ardupilot$ python3 -m pip list | grep serial
pyserial           3.5
serial             0.0.97
```

## Research

https://stackoverflow.com/questions/11403932/python-attributeerror-module-object-has-no-attribute-serial

### PR DESCRIPTION
**Pull request by Ryanf55**
Fixes #24594

### CODE REVIEW

**Comment by magicrub** [comment]
This looks like the correct change except I thought this gets installed along with ```MAVProxy```? Why do other versions not need to install this explicitly like this? This seems like a more basic package that all versions should install by moving it up next to ```pymavlink MAVProxy```

**Comment by Ryanf55** [comment]
> This looks like the correct change except I thought this gets installed along with `MAVProxy`? Why do other versions not need to install this explicitly like this? This seems like a more basic package that all versions should install by moving it up next to `pymavlink MAVProxy`

MAVProxy does install it, the reason this is broken is because you can't have `serial` and `pyserial` installed at the same time.
https://github.com/ArduPilot/MAVProxy/blob/2ca8c5ac164abc81561b09b8e4ca74099093cc6a/requirements.txt#L2

Why not just install MAVProxy, and remote this call to install `serial` entirely? Then, `pyserial` gets installed with `MAVProxy`.

**Comment by Ryanf55** [comment]
Yea, that's better. 
```
(.venv) ryan@ryan-B650-970:~/Development/ardu_ws/src/ardupilot$ python3 -m pip install MAVProxy
Collecting MAVProxy
  Using cached MAVProxy-1.8.62-py3-none-any.whl
Collecting pymavlink>=2.4.14
  Using cached pymavlink-2.4.39-py3-none-any.whl (11.4 MB)
Collecting pyserial>=3.0
  Using cached pyserial-3.5-py2.py3-none-any.whl (90 kB)
Collecting numpy
  Using cached numpy-1.25.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)
Collecting future
  Using cached future-0.18.3-py3-none-any.whl
Collecting lxml
  Using cached lxml-4.9.3-cp311-cp311-manylinux_2_28_x86_64.whl (7.9 MB)
Installing collected packages: pyserial, numpy, lxml, future, pymavlink, MAVProxy
Successfully installed MAVProxy-1.8.62 future-0.18.3 lxml-4.9.3 numpy-1.25.2 pymavlink-2.4.39 pyserial-3.5
```

**Review by khancyr — APPROVED** [review]
LGTM

**Review by khancyr — CHANGES_REQUESTED** [review]
well in fact pyserial should be in the default install list as we need it to upload and this doesn't depends on mavproxy

**Comment by Ryanf55** [comment]
> well in fact pyserial should be in the default install list as we need it to upload and this doesn't depends on mavproxy

Fixed!

**Pull request merged**
