### PR TITLE
Fix Riscv64 compiler error issue #25974

### PR DESCRIPTION
**Pull request by tmagik**
Fix https://github.com/ArduPilot/ardupilot/issues/25974

### CODE REVIEW

**Review by magicrub — APPROVED** [review]

**Comment by rmackay9** [comment]
Hi @tmagik,

Thanks for this.  Can you correct the commit to start with "AP_MotorsUGV:"?  .. and to be clear I meant the commit message, not the PR title.

FYI @mirkix

**Comment by rmackay9** [comment]
As mentioned on issue https://github.com/ArduPilot/ardupilot/issues/25974 there's no way that _motors_num can be larger than AP_MOTORS_NUM_MOTORS_MAX so this is a false positive I think.

**Review by rmackay9 — CHANGES_REQUESTED** [review]
@magicrub,

No, I don't think so.  There's no real problem in the AP code and our regular compiler isn't complaining so I think the compiler should be investigated.  Maybe there's a newer version that doesn't have the issue, maybe there's some advice on what optimisations cause this.  I'm not sure.

BTW, we can't merge this commit as is because of the commit message.

**Comment by tmagik** [comment]
> @magicrub,
> 
> No, I don't think so. There's no real problem in the AP code and our regular compiler isn't complaining so I think the compiler should be investigated. Maybe there's a newer version that doesn't have the issue, maybe there's some advice on what optimisations cause this. I'm not sure.
> 
> BTW, we can't merge this commit as is because of the commit message.

I fixed the commit message.

The compiler should definitely be investigated. It would help if it was easier to cross-compile for RiscV on non-linux platforms (macos). My M2 macbook compiles most things faster than the 96 core linux server I have.

**Comment by magicrub** [comment]
I'm re-flagging it for dev call so we can move forward on this

**Review by magicrub — APPROVED** [review]

**Pull request merged**
