### PR TITLE
Linux fixs

### PR DESCRIPTION
**Pull request by khancyr**
fix rangefinder compilation on bebop
fix an include
prevent deadlock on bebop output
fix warning on print format

### CODE REVIEW

**Comment by khancyr** [comment]
@lucasdemarchi If you are doing motor_test or all example with motor, you aren't using the corking. On Bebop driver that mean that you never send value to motors (push())

**Comment by lucasdemarchi** [comment]
> @lucasdemarchi If you are doing motor_test or all example with motor, you aren't using the corking. On Bebop driver that mean that you never send value to motors (push())

but the condition is exactly the opposite. If !corking then you push.

corking exists so the outputs to all the motors are written together - the fix to your problem ought to be elsewhere.

**Comment by khancyr** [comment]
Yes... This fix made no sense...
The issue is here https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_HAL_Linux/RCOutput_Bebop.cpp#L421
I take the fix from another backend... So I guess we should correct it.
I will remove this part to not hold the other parts

**Comment by lucasdemarchi** [comment]
I cherry-picked `AP_Rangefinder: fix compilation for Bebop`

**Comment by khancyr** [comment]
closing as the important part is merged! Thanks

**Pull request closed without merging**
