### PR TITLE
Tools: ardupilotwaf: make type narrowing an error

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by khancyr** [comment]
LGTM

**Comment by peterbarker** [comment]
@OXINARF Can you remember why allowing narrowing was required for clang to work?

My experiments here seem to say it works just fine...

**Comment by OXINARF** [comment]
@peterbarker It probably failed to build without it at the time. It's been 2.5 years ago, I don't remember exactly.

Have you tested macOS Clang? Apple used to do some modifications.

**Comment by OXINARF** [comment]
By the way, I'm all for adding more warnings into errors when they don't crash current builds, that way we avoid new code introducing new warnings.

**Pull request merged**
