### PR TITLE
esp32 esp32s3 sim on hw

### PR DESCRIPTION
**Pull request by nkruzan**
this is an initial try at getting sitl-on-hw working on esp32. 

currently can boot both esp32 classic and esp32s3 and connect mavlink via wifi

this only possible because of Peter's sitl-on-hw work. thanks Peter (and everyone else who has contributed)

to build for esp32:
./waf clean && rm -rf build/ && ./waf configure && ./Tools/scripts/sitl-on-hardware/sitl-on-hw.py  --board esp32sitl --vehicle plane --simclass Plane --frame plane-elevon

or  for esp32s3:
./waf clean && rm -rf build/ && ./waf configure && ./Tools/scripts/sitl-on-hardware/sitl-on-hw.py  --board esp32s3sitl --vehicle plane --simclass Plane --frame plane-elevon

then: (it rebuild a couple things but is easiest way to get flashed)
ESPBAUD=921600 ./waf plane --upload

goal is to get feedback and fixes. thanks for your time.

### CODE REVIEW

**Comment by mituritsyn** [comment]
have an error after 
./waf clean && rm -rf build/ && ./waf configure && ./Tools/scripts/sitl-on-hardware/sitl-on-hw.py --board esp32s3sitl --vehicle plane --simclass Plane --frame plane-elevon


```
[414/976] Compiling libraries/AP_PiccoloCAN/AP_PiccoloCAN_ESC.cpp
../../libraries/AP_PiccoloCAN/AP_PiccoloCAN_ESC.cpp: In member function 'virtual bool AP_PiccoloCAN_ESC::handle_can_frame(AP_HAL::CANFrame&)':
../../libraries/AP_PiccoloCAN/AP_PiccoloCAN_ESC.cpp:44:9: error: 'update_rpm' was not declared in this scope
         update_rpm(addr, rpm());
         ^~~~~~~~~~
compilation terminated due to -Wfatal-errors.

Waf: Leaving directory `/tmp/downloads/ardupilot/build/esp32s3sitl'
Build failed
 -> task in 'objs/AP_PiccoloCAN' failed (exit status 1): 
        {task 140311368039136: cxx AP_PiccoloCAN_ESC.cpp -> AP_PiccoloCAN_ESC.cpp.0.o}
 (run with -v to display more information)
FAILED: ./waf plane

```

**Comment by nkruzan** [comment]
> have an error after 
> ./waf clean && rm -rf build/ && ./waf configure && ./Tools/scripts/sitl-on-hardware/sitl-on-hw.py --board esp32s3sitl --vehicle plane --simclass Plane --frame plane-elevon
> 
> 
> ```
> [414/976] Compiling libraries/AP_PiccoloCAN/AP_PiccoloCAN_ESC.cpp
> ../../libraries/AP_PiccoloCAN/AP_PiccoloCAN_ESC.cpp: In member function 'virtual bool AP_PiccoloCAN_ESC::handle_can_frame(AP_HAL::CANFrame&)':
> ../../libraries/AP_PiccoloCAN/AP_PiccoloCAN_ESC.cpp:44:9: error: 'update_rpm' was not declared in this scope
>          update_rpm(addr, rpm());
>          ^~~~~~~~~~
> compilation terminated due to -Wfatal-errors.
> 
> Waf: Leaving directory `/tmp/downloads/ardupilot/build/esp32s3sitl'
> Build failed
>  -> task in 'objs/AP_PiccoloCAN' failed (exit status 1): 
>         {task 140311368039136: cxx AP_PiccoloCAN_ESC.cpp -> AP_PiccoloCAN_ESC.cpp.0.o}
>  (run with -v to display more information)
> FAILED: ./waf plane
> 
> ```
> 


The last line of this commit need to be added to esp32s3sitl.h 

https://github.com/nkruzan/ardupilot/commit/0aa89a3d71e19a2a7948d0f62c8fc711c9847aac

**Comment by mituritsyn** [comment]
> > have an error after
> > ./waf clean && rm -rf build/ && ./waf configure && ./Tools/scripts/sitl-on-hardware/sitl-on-hw.py --board esp32s3sitl --vehicle plane --simclass Plane --frame plane-elevon
> > ```
> > [414/976] Compiling libraries/AP_PiccoloCAN/AP_PiccoloCAN_ESC.cpp
> > ../../libraries/AP_PiccoloCAN/AP_PiccoloCAN_ESC.cpp: In member function 'virtual bool AP_PiccoloCAN_ESC::handle_can_frame(AP_HAL::CANFrame&)':
> > ../../libraries/AP_PiccoloCAN/AP_PiccoloCAN_ESC.cpp:44:9: error: 'update_rpm' was not declared in this scope
> >          update_rpm(addr, rpm());
> >          ^~~~~~~~~~
> > compilation terminated due to -Wfatal-errors.
> > 
> > Waf: Leaving directory `/tmp/downloads/ardupilot/build/esp32s3sitl'
> > Build failed
> >  -> task in 'objs/AP_PiccoloCAN' failed (exit status 1): 
> >         {task 140311368039136: cxx AP_PiccoloCAN_ESC.cpp -> AP_PiccoloCAN_ESC.cpp.0.o}
> >  (run with -v to display more information)
> > FAILED: ./waf plane
> > ```
> 
> The last line of this commit need to be added to esp32s3sitl.h
> 
> [nkruzan@0aa89a3](https://github.com/nkruzan/ardupilot/commit/0aa89a3d71e19a2a7948d0f62c8fc711c9847aac)

thanks already read it on discord

**Comment by tridge** [comment]
@nkruzan sorry, I didn't know you had done this when I did my own sim on hw PR for esp32 yesterday!
can you check if I missed anything from your PR?

**Comment by davidbuzz** [comment]
tridge's implemention is here:  https://github.com/ArduPilot/ardupilot/pull/25917

**Comment by davidbuzz** [comment]
can be closed now, as tridge's PR that does the same thing went in.

**Pull request closed without merging**
