### PR TITLE
autotest: Fix watch_altitude_maintained for Copter

### PR DESCRIPTION
**Pull request by mustafa-gokce**

### CODE REVIEW

**Comment by peterbarker** [comment]
@mustafa-gokce do you think we should just switch to `wait_altitude` in common.py instead?

**Comment by mustafa-gokce** [comment]
> @mustafa-gokce do you think we should just switch to `wait_altitude` in common.py instead?

@peterbarker I don't think it matches the behavior. 

[`wait_altitude`](https://github.com/ArduPilot/ardupilot/blob/master/Tools/autotest/common.py#L5585) waits for an altitude range and immediately returns if the current altitude is within the specified range.

[`watch_altitude_maitained`](https://github.com/ArduPilot/ardupilot/blob/master/Tools/autotest/common.py#L5585) on the other hand observes the vehicle's altitude `timeout` many seconds if it is at the specified altitude range.

Also, `wait_altitude` waits for the vehicle to be in the altitude range even if it is not in this range, which is good for waiting for the vehicle to reach the specified altitude range (e.g. taking off to the specific altitude), while `watch_altitude_maitained` throws an exception if the vehicle is not in this range in the first place.

I think it is a good idea to keep `watch_altitude_maitained` which is helpful for testing a command that changes the vehicle's target altitude and makes sure that the vehicle reaches that altitude and stays there (not falls down from the sky, or skyrockets) in a period of given time.

**Comment by mustafa-gokce** [comment]
@peterbarker But we can move `watch_altitude_maitained` to the `common.py` since I think it would be useful for Plane, too.

**Comment by peterbarker** [comment]
> [`wait_altitude`](https://github.com/ArduPilot/ardupilot/blob/master/Tools/autotest/common.py#L5585) waits for an altitude range and immediately returns if the current altitude is within the specified range.

Note quite true;s note that `**kwargs` gets passed through?  You can pass in a `min_duration` so that when it starts achieving it continues to.


> Also, `wait_altitude` waits for the vehicle to be in the altitude range even if it is not in this range, which is good for waiting for the vehicle to reach the specified altitude range (e.g. taking off to the specific altitude), while `watch_altitude_maitained` throws an exception if the vehicle is not in this range in the first place.

We could potentially add some more parameters to the underlying function, `wait_and_maintain` to add this functionality in.

> I think it is a good idea to keep `watch_altitude_maitained` which is helpful for testing a command that changes the vehicle's target altitude and makes sure that the vehicle reaches that altitude and stays there (not falls down from the sky, or skyrockets) in a period of given time.

I agree.  I also agree with your idea of moving it up - if we put it right next to the existing function up there maybe someone will get keen and add the required bits to `wait_and_maintain` at some stage :-)

**Comment by mustafa-gokce** [comment]
> Note quite true;s note that `**kwargs` gets passed through? You can pass in a `min_duration` so that when it starts achieving it continues to.

@peterbarker Oh, that's really good, thanks.
Actually, it is called `minimum_duration` but I found it by tracing it 🙂 

> I agree. I also agree with your idea of moving it up - if we put it right next to the existing function up there maybe someone will get keen and add the required bits to `wait_and_maintain` at some stage :-)

Done.

**Comment by peterbarker** [comment]
I've rebased this and marked it for MergeOnCIPass

**Comment by peterbarker** [comment]
Rebased this again on top of CI fixes

**Comment by peterbarker** [comment]
@mustafa-gokce hmmm.  Something seems to have gone wrong here - did this cross with another PR, do you think?

**Comment by peterbarker** [comment]
Merged, thanks!

**Pull request merged**
