### PR TITLE
Apm git tutorial

### PR DESCRIPTION
**Pull request by plvilleg**
my tutorial

### CODE REVIEW

**Comment by amilcarlucas** [comment]
Where is the tutorial?

**Comment by rmackay9** [comment]
Merged, thanks!

**Comment by plvilleg** [comment]
I'm following the tutorial in ardupilot.org/dev
And in there its that example.

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by magicrub** [comment]
Fyi that was 3 commits.

**Pull request closed without merging**
