### PR TITLE
INS: added support for the Invensense ICM-40609 IMU

### PR DESCRIPTION
**Pull request by tridge**
This adds support for the new ICM-4 series of IMUs. These should be a big improvement over older Invensense IMUs.
Key features:
 - 32kHz internal sample rate
 - nice FIFO design with header for error checking
 - optional anti-aliasing and notch filters
 - up to 24MHz SPI rate
 - improved temperature zero drift rates (5x better than ICM20948 for gyro and accel)
 
This driver sets it up for a fixed 2kHz for now. After initial testing we may adjust based on results

I've also added in the ICM-42688 and ICM-42605. @auturgy has confirmed the ICM-42688 works correctly. The ICM-42605 is untested, but likely to work.

### CODE REVIEW

**Comment by auturgy** [comment]
ICM42688 works on modalFC-v1 https://github.com/ArduPilot/ardupilot/pull/16255

**Comment by anbello** [comment]
Really interesting new device. Thanks for the driver.

I have a little OT consideration:

Looking on diagram on page 25 of datasheet (https://3cfeqx1hf82y3xcoull08ihx-wpengine.netdna-ssl.com/wp-content/uploads/2020/09/DS-000347-ICM-42688-P-v1.3.pdf) I see Anti-Alias filter in the digital domain, how could it be?

On every Sampling Theory book there is written (underlined) that Anti-Alias filter should be done in analog domain before the ADC otherwise once the alias are in can't be eliminated by digital filtering.

**Comment by tridge** [comment]
> I see Anti-Alias filter in the digital domain, how could it be?

It is a good question, and I plan on discussing it with @priseborough and @lthall 

> that Anti-Alias filter should be done in analog domain before the ADC otherwise once the alias are in can't be eliminated by digital filtering

that's true if you want to avoid aliasing of frequencies about 1/2 of the sample rate the filter uses. This sensor seems to have 32kHz data at the entry to the AA filter, so it should be effective up to 16kHz if my guess as to how it works is right. 
For now I just haven't enabled it as I'd like to discuss with Paul and Leonard first

**Review by peterbarker — APPROVED** [review]
LGTM.  Discussions elsewhere say that this will get augmented to take advantage of more bits-of-precision in a future PR but this is tested and good as-is.

I've created a simulator for this sensor here:  https://github.com/ArduPilot/ardupilot/compare/master...peterbarker:tridge-pr-invensense3?expand=1  Somehow we need to share all of the perturb-sample-data from `AP_InertialSensor_SITL` with over-simulated-bus sensors like that one.  It is also inactive by default as performance penalties will apply and for the most part it will not be useful for people.  I do intend to make it active in autotest at some stage.

**Pull request merged**
