### PR TITLE
bmi270 imu support on omnibusf4 flight controllers

### PR DESCRIPTION
**Pull request by ChriKrawi**
Modified the omnibusf4pro/hwdef.dat file to support the bmi270 imu. Verified the modifications on eachine x220 clone and omnibusf4 flight controller. Would like to merge my hwdef changes into the main branch.

### CODE REVIEW

**Comment by tridge** [comment]
@ChriKrawi you have exposed your private key in this PR. You need to change your ssh key NOW

**Comment by andyp1per** [comment]
@ChriKrawi thanks for looking at this! Please follow the wiki guide for submissions - https://ardupilot.org/dev/docs/submitting-patches-back-to-master.html. As a quick bit of initial feedback, you will be able to make these changes in the existing hwdef without requiring a new file. Take a look at the MambaH743v3 for instance which has two versions both supported in the same hwdef

**Comment by ChriKrawi** [comment]
> @ChriKrawi thanks for looking at this! Please follow the wiki guide for submissions - https://ardupilot.org/dev/docs/submitting-patches-back-to-master.html. As a quick bit of initial feedback, you will be able to make these changes in the existing hwdef without requiring a new file. Take a look at the MambaH743v3 for instance which has two versions both supported in the same hwdef

@andyp1per  I do not request a new file and my modifications were implemented like in the example you mentioned. There is ONE new hwdef file supporting both IMU's. My branch was also synchronized to the main ardupilot/master at the time i issued the pull request.

**Comment by andyp1per** [comment]
@ChriKrawi difficult to tell as you changed all the line endings. Click on "Files changed" above and you will see.
Your private key is still in the PR ...

**Comment by ChriKrawi** [comment]
> @ChriKrawi difficult to tell as you changed all the line endings. Click on "Files changed" above and you will see. Your private key is still in the PR ...

@andyp1per  Tried starting from the scratch, as modifications are pretty simple. Re-synced my fork, removed all commits and modified the hwdef.dat file again.  Reopend a new pull request with same topic. 
Changed the private key immediately after I got the warning from git-hub. Uploading the key happened by accident.  If the key is still visible NOW, I don't know how to make it undone. Using the key can't cause any harm.  THX for your support..

**Pull request closed without merging**
