### PR TITLE
Implement MISSION_CHECKSUM

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by tridge** [comment]
we may need to fix handling of the jump counter for this

**Comment by peterbarker** [comment]
> we may need to fix handling of the jump counter for this

Turns out to not be a problem; there's a statically allocated list of jump point counters which tracks this information.  I added a test for it anyway.

**Comment by peterbarker** [comment]
@hamishwillee we really need a GCS implementation to go along with it, 'though :-)

I haven't even seriously looked at adding that for MAVProxy yet.

**Comment by hamishwillee** [comment]
@peterbarker Not sure about QGC, but perhaps MAVSDK? @julianoes ?

**Comment by julianoes** [comment]
Is the mission checksum still required, even if missions are uploaded using MAVLink FTP where a CRC32 check is already available?

**Comment by hamishwillee** [comment]
> Is the mission checksum still required, even if missions are uploaded using MAVLink FTP where a CRC32 check is already available?

Yes, IMO.

The checksum is _broadcast_ to tell you of any changes to the uploaded mission, either using full or partial update (or presumably FTP upload). This allows re sync of the mission only if needed.

Using MAVLink FTP with a CRC check tells you whether or not you need to sync again only if you check. The checksum is what tells you that you need to do that check.

Generally I don't think we should force implementation of MAVFTP-based protocols on components. Though in this case not such a big deal because the only components interested are likely to implement MAVFTP - GCS and autopilot.

**Comment by peterbarker** [comment]
On Tue, 7 Sep 2021, Hamish Willee wrote:

>       Is the mission checksum still required, even if missions are uploaded using MAVLink FTP where a CRC32 check is already available?
> 
> Yes, IMO.
> 
> The checksum is broadcast to tell you of any changes to the uploaded mission, either using full or partial update (or presumably FTP upload). This allows re sync of the mission only if needed.
> 
> Using MAVLink FTP with a CRC check tells you whether or not you need to sync again only if you check. The checksum is what tells you that you need to do that check.
> 
> Generally I don't think we should force implementation of MAVFTP-based protocols on components. Though in this case not such a big deal because the only components interested are likely to implement MAVFTP - GCS and autopilot.

There's also the fact that mission-upload-via-FTP hasn't been formalised 
as any sort of standard.

**Comment by peterbarker** [comment]
We're moving towards formalising the ftp transfer; there are many advantages to do so, and avoids issues like regularly-changing parameters which complicate checksum solutions.

**Comment by peterbarker** [comment]
We discussed `MISSION_CHECKSUM` again at DevCall today and decided we'd have another look at it.

I stuffed up when trying to reopen this - the new PR is https://github.com/ArduPilot/ardupilot/pull/20834

**Pull request closed without merging**
