### PR TITLE
Copter: Delete a break that will not be executed

### PR DESCRIPTION
**Pull request by muramura**
I delete BREAKs that are not executed.
I find the meaningless code unnecessary.
I've never seen a programming book that describes BREAK after RETURN.
I don't see the point of writing code that will not be executed.

### CODE REVIEW

**Review by khancyr — COMMENTED** [review]
This change nothing except the code style. I am not sure we when to bother with a lot of PR similar like this one as there are numerous place like this one.

**Review by rmackay9 — APPROVED** [review]

**Comment by peterbarker** [comment]
Again, one of Leonard's PRs pokes around in this exact area, so we'll delay merge until his goes in.

**Comment by peterbarker** [comment]
Unsurprisingly, this conflicted with Leonard's work.

@muramura did you want to continue with this PR?

**Comment by khancyr** [comment]
This need to be rebase, I will close this until the work is down as this is low priority changes

**Comment by muramura** [comment]
This statement is wrong, because BREAK will never be executed.

**Pull request closed without merging**
