### PR TITLE
AP_Periph: fix command to build bootloader

### PR DESCRIPTION
**Pull request by mirkix**

### CODE REVIEW

**Review by khancyr — APPROVED** [review]
Nice catch !

**Comment by magicrub** [comment]
Thanks @mirkix . I'll merge as soon as CI passes.

**Review by magicrub — APPROVED** [review]

**Comment by magicrub** [comment]
@khancyr I removed the devcal label, we can merge this without discussion. I've been meaning to do this fix too. @mirkix beat me to it!

**Comment by magicrub** [comment]
This PR, like many other PRs, suffer from delayed/forgotten merges due to failing CI status because of an unrelated CI bug where Param set/get randomly fail. This has plagued us for years and is slowly getting worse. I think it's MAVProxy getting bogged down at high speeds (serial buffers not liking faster-than-real-time comm traffic). Nice to see @peterbarker is doing something about it on PR https://github.com/ArduPilot/ardupilot/pull/16270! Awesome work!

**Pull request merged**
