### PR TITLE
log sbus frame drops

### PR DESCRIPTION
**Pull request by kd0aij**
adds dropped frame counter to RCProtocol_SBUS 
clears the counter when RX is in failsafe 
adds "drops" field to RSSI log record

From old issue https://github.com/ArduPilot/ardupilot/issues/2721
The sbus decoder in PX4/Firmware had code to generate a "link quality" measure here:
https://github.com/StewLG/PX4Firmware/blob/e678a719327bd0513687c84d948844cb2e94c98a/src/modules/px4iofirmware/controls.c#L237
This counts the number of good frames in a sliding window covering the 32 most recent and defines link quality to be #good / 32. 

PR https://github.com/ArduPilot/ardupilot/pull/6467 allowed using this measure as the RSSI

useful links: 
https://github.com/ArduPilot/PX4Firmware/pull/38
https://github.com/ArduPilot/ardupilot/pull/6467/files
https://github.com/ArduPilot/ardupilot/pull/2798
https://github.com/ArduPilot/ardupilot/pull/1712
https://github.com/StewLG/PX4Firmware/blob/e678a719327bd0513687c84d948844cb2e94c98a/src/modules/px4iofirmware/controls.c#L286

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
how is the iomcu counting the number of frames dropped? Where's the firmware coming from?
sbus protocol doesn't have a seq, so it must be time-based. Couldn't we simply do this in ardupilot?

**Comment by kd0aij** [comment]
@lucasdemarchi see https://github.com/ArduPilot/ardupilot/blob/209a6e167af830aa354b4e590c1f3923677034f6/libraries/AP_RCProtocol/AP_RCProtocol_SBUS.cpp#L259
The return value of sbus_frame_drop was previously ignored.

What do you mean by "do this in ardupilot"? Is there something wrong with using AP_HAL/RCInput this way?

**Comment by lucasdemarchi** [comment]
My point is that this could be HAL-independent. The way it is there are multiple indirections. HAL -> RCProtocol -> HAL -> Logger.

**Comment by kd0aij** [comment]
That would be great! How would you do it?

**Comment by kd0aij** [comment]
@tridge Am I doing this the right way? I don't understand how this could be made HAL-independent.

**Comment by kd0aij** [comment]
Moved the dropped frame counter from HAL::RCinput to RCProtocol as suggested by @lucasdemarchi  and @tridge .  Thanks; much simpler now :)

I just added the dropped frame count to the RSSI log record, since the FrSky receivers also provide an (independent?) rssi value. In testing, I used the RSSI_CHANNEL option to send the receiver RSSI on an SBUS channel; mRo X21 with IOMCU and FrSky XSR RX:
image

**Comment by kd0aij** [comment]
who uses sbus any more?

**Pull request closed without merging**
