### PR TITLE
Only apply the 1M flash check on F427 boards

### PR DESCRIPTION
**Pull request by tridge**
This should fix an issue with the DrotekP3Pro
See discussion here:
https://discuss.ardupilot.org/t/firmware-upgrade-problem-error-firmware-image-is-too-large-for-this-board/67979

### CODE REVIEW

**Review by andyp1per — APPROVED** [review]

**Review by magicrub — APPROVED** [review]
Seems reasonable

**Comment by amilcarlucas** [comment]
Doesn't the user have a problem with 4.0.7?
Isn't this a fix for master?

**Comment by tridge** [comment]
> Doesn't the user have a problem with 4.0.7?

yes, but they can use this to load a new bootloader, which will then work with any version

**Comment by tridge** [comment]
testing done successfully by user in discuss

**Pull request merged**
