### PR TITLE
Blimp: Update displayed version to current version

### PR DESCRIPTION
**Pull request by MichelleRos**

### CODE REVIEW

**Review by rmackay9 — APPROVED** [review]

**Comment by rmackay9** [comment]
It would also be good to add a ReleaseNotes.txt file to the Blimp directory.

**Comment by MichelleRos** [comment]
@rmackay9 I'm happy to add one, though I'm unsure what to put in it - for the other vehicles that file is for the stable/beta/rc releases, but Blimp doesn't have any of those yet?
(I'm thinking it's probably best to leave stable/beta/rc releases until Blimp at least has auto/mission capability and a more "standard" frame?)

**Comment by rmackay9** [comment]
@MichelleRos, Ah ok.  so maybe when Blimp gets it's first official release we should add the Release Notes..

**Comment by rmackay9** [comment]
Merged, thanks!

**Comment by MichelleRos** [comment]
Thank you 🙂

**Pull request merged**
