### PR TITLE
Add and use a "bool read(c)" method to AP_HAL

### PR DESCRIPTION
**Pull request by peterbarker**
Actually checking the return value of the existing call is pretty clunky.  At this means we become more C++-ish vs the -1 return value from Arduino days.

### CODE REVIEW

**Comment by peterbarker** [comment]
```
Board              AP_Periph  blimp  bootloader  copter  heli  iofirmware  plane  rover  sub
Durandal                      -80    *           -128    -128              -104   -128   -104
Hitec-Airspeed     32                                                                    
KakuteH7-bdshot               -24    *           -120    -120              -88    -136   -88
MatekF405                     -8     *           -72     -72               -56    -80    -64
Pixhawk1-1M                   0      *           -48     -48               -48    -64    -56
f103-QiotekPeriph  24                                                                    
f303-Universal     -32                                                                   
iomcu                                                          16                        
revo-mini                     -16    *           -88     -88               -72    -96    -80
skyviper-v2450                                   -16                                     
```

**Comment by tridge** [comment]
need to check bootloader builds for flash space

**Comment by peterbarker** [comment]
> need to check bootloader builds for flash space

Which bootloader builds?  The table I provided shows it's zero for our " sample board selection".

**Comment by peterbarker** [comment]
> > need to check bootloader builds for flash space
> 
> Which bootloader builds? The table I provided shows it's zero-impact for our " sample board selection".

I've done all of the bootloader builds (using size_compare_branches.py and there are not differences in them between this and master.

**Comment by tridge** [comment]
happy to merge for 4.5

**Comment by tridge** [comment]
rebased and ready for merge

**Pull request merged**
