### PR TITLE
SRV_Channels.cpp: small correction

### PR DESCRIPTION
**Pull request by shubham-shahh**
as discussed with @peterbarker, it's not only Auxilary o/p but affects the main o/p as well.

### CODE REVIEW

**Review by khancyr — APPROVED** [review]

**Comment by rmackay9** [comment]
I'll leave it for @peterbarker to merge but I wonder if we need a more general term to replace "auxiliary" instead of just removing it.  "outputs" alone is very general and could include all kinds of things besides the main and auxiliary outputs.

**Review by peterbarker — APPROVED** [review]
LGTM

**Comment by peterbarker** [comment]
Merged, thanks!

Next time a slightly better commit description would be nice - e.g. `SR_Channels: correct documentation on GPIO_MASK`

**Comment by shubham-shahh** [comment]
> Merged, thanks!
> 
> Next time a slightly better commit description would be nice - e.g. `SR_Channels: correct documentation on GPIO_MASK`

Hi,
sorry, I'll be careful nextime
thanks

**Pull request merged**
