### PR TITLE
AP_BattMonitor: make INA3221 parameters visible for metadata gen

### PR DESCRIPTION
**Pull request by tpwrules**
Not sure if more files need to be added for other battery monitor types? I suppose as long as the file list has the union of all possible parameters... It doesn't look like the metadata generator deduplicates anyway, c.f. `BATTn_I2C_BUS`.

### CODE REVIEW

**Review by Hwurzburg — APPROVED** [review]

**Review by IamPete1 — CHANGES_REQUESTED** [review]
Sorry, should have spotted this on the original PR. The new monitors param indexes conflict with the AD7091 eg: https://github.com/ArduPilot/ardupilot/blob/684d95a8260f2d9adf694a06873911f90e0e4b6c/libraries/AP_BattMonitor/AP_BattMonitor_AD7091R5.cpp#L87

https://github.com/ArduPilot/ardupilot/blob/684d95a8260f2d9adf694a06873911f90e0e4b6c/libraries/AP_BattMonitor/AP_BattMonitor_INA3221.cpp#L70

One of the odd things about battery monitor is that all the backends are loaded as though they share and single param table so none the params in the sub tables can use the same index. It seemed link a nice simplification at the time but now were running out of indexes.....

**Comment by tpwrules** [comment]
I thought all monitors were supposed to use the same index range cause only one would be active at a time?

**Comment by tpwrules** [comment]
Reallocated the indices and fixed up to make a conflict hopefully less likely in the future. It seems we are still decent on absolute count for a while yet as long as we do not allocate blocks.

Needs to be backported to 4.6 now so the INA3221 IDs do not desync.

**Review by IamPete1 — APPROVED** [review]
Great, thanks!

**Comment by rmackay9** [comment]
I attempted to cherry-pick this into 4.6.0-beta3 but ran into merge conflicts so I've left it out for now

**Comment by tpwrules** [comment]
Turns out the INA3221 driver is not in 4.6, so that explains it! Removing the request for now, but this might come up again if any other battery driver stuff gets backported.

**Pull request merged**
