### PR TITLE
AP_Bootloader: reserve a board ID for JFB200

### PR DESCRIPTION
**Pull request by iwashitakirio**
This ID is for a new board developping by JAE.

### CODE REVIEW

**Review by peterbarker — CHANGES_REQUESTED** [review]
Please adjust the commit message (NOT the PR title!)

Should be `AP_Bootloader: reserve a board ID for JFB200` or `board_types: reserve a board ID for JFB200`

`

**Comment by iwashitakirio** [comment]
How do I edit the commit message?

**Comment by rmackay9** [comment]
Hi @iwashitakirio,

[We've got some information here on how to do it](https://ardupilot.org/dev/docs/git-interactive-rebase.html) but this is really a git question so random googling might be the best method.

**Comment by peterbarker** [comment]
@iwashitakirio I've squished everything down into a single commit with the correct naming.

Marking as MergeOnCIPass

**Review by peterbarker — APPROVED** [review]
LGTM

**Comment by iwashitakirio** [comment]
Thank you!
I will learn about git more.

**Pull request merged**
