### PR TITLE
Copter: add turtle mode to flight modes metadata

### PR DESCRIPTION
**Pull request by Hwurzburg**
mode is missing from Mission Planner since its not in the metadata

### CODE REVIEW

**Review by peterbarker — CHANGES_REQUESTED** [review]
Should not be removing README.md!

**Review by peterbarker — CHANGES_REQUESTED** [review]
LGTM

**Comment by Hwurzburg** [comment]
definitely....my git fu is failing me....gone now

**Review by peterbarker — APPROVED** [review]

**Review by rmackay9 — APPROVED** [review]
That's a surprise and makes me wonder how many users have used Turtle mode

**Comment by Hwurzburg** [comment]
I got back to my multis recently and tried BF turtle and liked not having to walk out to a crashed quad so much that when I converted the Kopis Holybro gave me I discovered this.....really pleased how well a default tune of this works....been flying all around the house with it....always used BF on quads due to its super non-tune default handling....was surprised how well  AP's defaults work on small quads

**Pull request merged**
