### PR TITLE
build: remove Linux boards from make

### PR DESCRIPTION
**Pull request by lucasdemarchi**
This way people don't copy and paste to add a new board: make build
system is deprecated for Linux boards for a long time and is now
unsupported.

qflight remains as the only Linux board since it's not buildable
with waf. When it is, more files and pieces can be removed from mk/.

### CODE REVIEW

**Comment by OXINARF** [comment]
Please hold this up until I remove the Make builds from CI - I'm working on it, only making final tests.

**Comment by lucasdemarchi** [comment]
@tridge can you add qflight to waf so we finish removing the other stale files?

**Comment by OXINARF** [comment]
@lucasdemarchi Do you want to rebase this and let CI pass? Just making sure I didn't mess up anything.

**Comment by lucasdemarchi** [comment]
@OXINARF I just did.

**Comment by OXINARF** [comment]
@lucasdemarchi ahahah that was insanely synchronized 😄

**Comment by lucasdemarchi** [comment]
> @tridge can you add qflight to waf so we finish removing the other stale files?

@tridge ping

**Comment by lucasdemarchi** [comment]
This is now applied, thanks  for the review.

**Pull request closed without merging**
