### PR TITLE
Update Parameter menu flightmodes for plane and copter

### PR DESCRIPTION
**Pull request by andyp1per**
Fixes https://github.com/ArduPilot/ardupilot/issues/20800

### CODE REVIEW

**Comment by andyp1per** [comment]
@rmackay9 FYI

**Comment by timtuxworth** [comment]
Is there any reason to restrict these to ONLY CAPITAL letters? I remember, back in the day, when some computers like my Dick Smith System 80, weren't capable of lower case, but I'm pretty sure most modern systems support them now. It does make sense for acronyms, but why caps lock for normal words?

Also "Thermal" is only 7 characters, and there are other 7 character modes, is the abbreviation really justified?

Could it not be QLand, QAcro, Thermal, LAQLand

**Comment by andyp1per** [comment]
Only uppercase https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_OSD/fonts/clarity_medium.png

**Comment by timtuxworth** [comment]
WOW!

**Review by rmackay9 — APPROVED** [review]
I agree with the comment about unnecessarily shortening THERMAL but it's up to Andy in the end..

**Comment by andyp1per** [comment]
I'm going to leave it as-is - we are aiming for 4 letters with all of these and there are a bunch of abbreviations of 7-letter words
LAQLAND is because I couldn't come up with a meaningful shorter abbreviation

**Comment by tridge** [comment]
@andyp1per have you tested this with SITL OSD for the various vehicles?

**Comment by andyp1per** [comment]
image

**Comment by andyp1per** [comment]
@rmackay9 I don't think this fixes the bug you think it does. The name displayed in the OSD is the result of name4() in the mode in question and is correctly set for AutoRTL. The fix here only updates the parameter menus, so I am not quite sure how the user saw F27

**Comment by rmackay9** [comment]
@andyp1per,

OK, thanks for the info.  It's possible that a lack of understanding led to some incorrect assumptions so I might sadly need to re-open that investigation.

In any case, if you can confirm you've tested this we can merge it.  Txs again.

**Comment by andyp1per** [comment]
Verified that the new flight modes appear in the CRSF parameter menu

**Comment by rmackay9** [comment]
Merged, thanks!

**Pull request merged**
