### PR TITLE
ArduCoptor: move get_pilot_desired_lean_angles to mode.cpp

### PR DESCRIPTION
**Pull request by raptor419**
move get_pilot_desired_lean_angles to mode.cpp

### CODE REVIEW

**Comment by OXINARF** [comment]
Hi @raptor419, welcome to ArduPilot and thank you for your first contribution!

Please let me point you to our contribution rules (http://ardupilot.org/dev/docs/submitting-patches-back-to-master.html), which you should read, mainly the parts about the rebase process (no merge commits are allowed) and the commit message format we want.
If you need any help feel free to drop by our Gitter chat: http://gitter.im/ArduPilot/ardupilot

**Comment by raptor419** [comment]
@OXINARF, can I kindly get some pointers about checking the validity of my code on my fork without merging it with ardupilot master??
Any help would be appreciated, sorry if I hastily made my first commits without verification. :)

**Comment by peterbarker** [comment]
On Fri, 2 Mar 2018, Harsh Bandhey wrote:

> @OXINARF, can I kindly get some pointers about checking the validity of my code on my fork without merging it with ardupilot master??

SITL is your best bet here.  Since it's only code moving rather than 
modification, I think you could be reasonably confident that if you can 
steer the vehicle around (using something like "rc 2 1400"), then you 
haven't broken anything.

> Any help would be appreciated, sorry if I hastily made my first commits without verification. :)

Great to see someone grabbing this stuff.  The PR system is here to help 
with review :-)

**Comment by rmackay9** [comment]
@raptor419, I wrote this wiki page to help users cleaning up their commits.  Can you give it a try?
http://ardupilot.org/dev/docs/git-interactive-rebase.html

**Comment by OXINARF** [comment]
@raptor419 Sorry for the delay in my answer. Peter and Randy already gave you good answers, but I was unsure if by checking validity of your code you meant actually testing it works (with SITL for example, like Peter suggested), or just checking it passes CI tests that all our pull requests go through.

If it's the latter, you can use Travis and Semaphore as we use here. Travis is easier to setup but we run more tests in Semaphore now. You can go to http://travis-ci.org, login with your GitHub account and then you just have to enable your ArduPilot fork to run builds. Semaphore is trickier, but if you want to also use it, let me know and I'll walk you through it.

**Comment by rmackay9** [comment]
This issue was closed by another developer so closing!  Thanks in any case and there are other things we need to move around so it would be great to see you attempt another issue.

**Pull request closed without merging**
