### PR TITLE
AP_NavEKF3: Changed if statements to switch statement.

### PR DESCRIPTION
**Pull request by muramura**
The same value is used in multiple if statements.
In this case, I think that it is better to use the switch statement.
Other
Change indentation.

### CODE REVIEW

**Comment by priseborough** [comment]
Please hold off this change - it will cause problems with https://github.com/ArduPilot/ardupilot/pull/5407

**Comment by gmorph** [comment]
Added NeedRework just so we know it will need to be updated after Paul works on #5407

**Comment by WickedShell** [comment]
@muramura did you want to rebase this/revisit it, or should this be closed?

**Comment by muramura** [comment]
@WickedShell san. Comment thanks.
I saw the latest source.
In this setAidingMode method, the original "PV_AidingMode" is implemented by if, else if statement. I think that this process can also be changed to a switch statement.
Because it is a mode, I think that the switch statement is better.
What do you think.

**Comment by muramura** [comment]
I closed this PR and made a new PR.

**Pull request closed without merging**
