### PR TITLE
Blimp: Remove previous flight mode

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Review by amilcarlucas — APPROVED** [review]

**Comment by MattKear** [comment]
@MichelleRos, are you happy with this PR?  I am keen that this goes in, so I can remove the commit from #27786.
The prev_control_mode variable was added by me in copter for autorotations.  I am looking to remove the functionality in copter that depended on this variable.  In tidying up I spotted that it was in blimp and not used.

**Review by MichelleRos — APPROVED** [review]
Yup, absolutely fine. Sorry I missed adding the approval earlier.

**Comment by rmackay9** [comment]
Merged, thanks!

**Comment by MattKear** [comment]
Thank you :-)

**Pull request merged**
