### PR TITLE
BETAFPV F405

### PR DESCRIPTION
**Pull request by andyp1per**
https://betafpv.com/collections/brushless-flight-controller/products/f4-1s-12a-aio-brushless-flight-controller-v3-

### CODE REVIEW

**Comment by andyp1per** [comment]
For anyone who wants to try:
[arducopter.zip](https://github.com/ArduPilot/ardupilot/files/12327759/arducopter.zip)

**Review by tridge — APPROVED** [review]

**Comment by Hwurzburg** [comment]
@andyp1per I do not see UART5RX pinned out anywhere....where is it?

**Comment by andyp1per** [comment]
> @andyp1per I do not see UART5RX pinned out anywhere....where is it?

No idea - maybe we should remove it from the hwdef

**Comment by Hwurzburg** [comment]
maybe it was ESC telem before they had BlueJay....but it should be removed...

Also, their recommended usages are:
 UART1 (DMA enabled): GPS or CRSF...its protocol is currently MAV2....not okay for CRSF, nor for GPS since UART4 is GPS by default
UART4 (no DMA): only shown as DJI but its protocol default is GPS not DJI

I think we should (to make BF/iNav migration easy and avoid user confusion):
1. remove UART5 and mark it EMPTY since its unusable
2. set DJI protocol for UART4 
3. set GPS protocol for UART1
4. change PC7 to TIM8 RCINT to allow SBUS to work even if a UART(3 in this case) is set for RC protocol

**Comment by andyp1per** [comment]
Yes agreed on 1-3. Don't agree with 4 without testing - they already have an SBUS pin out which I suspect is hardware inverted so no need for RCININT.

**Comment by Hwurzburg** [comment]
The issue is anyone using SBUS in BF or iNav will have to set SERIAL3 protocol back to -1, and SERIAL6 protocol to 23 in order to use their setup....with the change on the SBUS pin to RCIINT, they would have to do NO reconfiguration

**Pull request merged**
