### PR TITLE
waf: be compatible with git < 1.8.5

### LINKED ISSUE #4023: waf: fail to update submodule
#### Issue details
It's not possible to update submodule

#### Platform
- [x] All
- [x] AntennaTracker
- [x] Copter
- [x] Plane
- [x] Rover

### PR DESCRIPTION
**Pull request by lucasdemarchi**
The -C option was added to git in version 1.8.5 which is not available
in Ubuntu 12.04.

Fix #4023

@kwikius could you test this in your machine?

### CODE REVIEW

**Comment by guludo** [comment]
I prefer using `cwd` option for `cmd_and_log()` and also for the task main command. That way we keep them as non-shell commands.

**Comment by lucasdemarchi** [comment]
we can do that for runnable_status() and git_submodule_head_hash(). But what about the run_str?

**Comment by guludo** [comment]
A quick way would be adding a line around [this one](https://github.com/ArduPilot/ardupilot/pull/4031/commits/cdb12f8bbf84fa34340e8d04b94687e89c9fe908#diff-80c6ca6434ec12d57ab8a7e2c9110e53R84) with:
```python
         tsk.cwd = module_node.abspath()
```

The use `cwd=self.cwd` for the `cmd_and_log()` function.

**Comment by guludo** [comment]
LGTM now :-)

**Comment by lucasdemarchi** [comment]
Applied, thanks.

**Pull request closed without merging**
