### PR TITLE
Don't provide zero udpates for ESCs that have never been used

### PR DESCRIPTION
**Pull request by andyp1per**
Follow up to https://github.com/ArduPilot/ardupilot/pull/21370

### CODE REVIEW

**Review by tridge — APPROVED** [review]

**Comment by tridge** [comment]
@andyp1per looks good, thanks!

**Review by rmackay9 — CHANGES_REQUESTED** [review]
Isn't it a bit unusual to have one of the conditions of the for loop not actually depend upon the for loop?  I think it might be more clear if we moved the, "valid_escs < nfreqs" condition to before the for loop so it is not run at all.

**Comment by andyp1per** [comment]
> Isn't it a bit unusual to have one of the conditions of the for loop not actually depend upon the for loop? I think it might be more clear if we moved the, "valid_escs < nfreqs" condition to before the for loop so it is not run at all.

No, we are counting the number of valid ESCs. We have to run the loop to get this. We just want to make sure that the number of valid ones we count does not exceed the number asked for

**Comment by andyp1per** [comment]
I flew four batteries today with this change - all worked great

**Review by tridge — APPROVED** [review]

**Review by rmackay9 — APPROVED** [review]

**Pull request merged**
