### PR TITLE
Copter: fix units and multipliers in PL dataflash logs message

### PR DESCRIPTION
**Pull request by amilcarlucas**

### CODE REVIEW

**Comment by rmackay9** [comment]
@amilcarlucas,

Thanks for this, it's been tested of course?  any screen shots of the before vs after?

**Comment by peterbarker** [comment]
CI picked up the fact that the documentation needs fixing for the field rename.

If you could change "postion" to "position" too that would be nice :-)

Unit changes look good.  I think @rmackay9 would like to see screenshots of MissionPlanner getting the scale wrong, then getting it right.

I'd love to know how those original units ended up that way...

**Comment by amilcarlucas** [comment]
@rmackay9 It has been tested in SITL and on a real copter, on top of 4.0.4-rc2
I do not have screenshots of the before, but will do some of the after.

@peterbarker OK I will also do that change.
gitblame is your friend ;P

**Comment by amilcarlucas** [comment]
@peterbarker done

**Pull request merged**
