### PR TITLE
AP_Scripting/Copter: add dead reckon home lua script

### PR DESCRIPTION
**Pull request by rmackay9**
This adds a copter-deadreckon-home lua script that takes control of the vehicle in Guided_NoGPS mode and flies in the last known direction of home if there an EKF failsafe or the GPS quality drops below a specified level (e.g. satellite count drops low or speed accuracy value goes high).

Instructions for how to use the script are in the comments at the top of the script but here are the available controls

- DR_ENABLE : 1 = enabled, 0 = disabled
- DR_ENABLE_DIST : distance from home (in meters) beyond which the dead reckoning will be enabled
- DR_GPS_SACC_MAX : GPS speed accuracy max, above which dead reckoning to home will begin (default is 0.8).  Lower values trigger with good GPS quality, higher values will allow poorer GPS before triggering. Set to 0 to disable use of GPS speed accuracy.
- DR_GPS_SAT_MIN : GPS satellite count threshold below which dead reckoning home will begin (default is 6).  Higher values trigger with good GPS quality, Lower values trigger with worse GPS quality. Set to 0 to disable use of GPS satellite count.
- DR_GPS_TRIGG_SEC : GPS checks must fail for this many seconds before dead reckoning will be triggered (default is 3)
- DR_FLY_ANGLE : lean angle (in degrees) during dead reckoning.  Default is 10, most vehicles reach maximum speed at 22deg
- DR_FLY_ALT_MIN : min alt (above home in meters) during dead reckoning. zero to return at current alt
- DR_FLY_TIMEOUT : timeout (in seconds).  Vehicle will attempt to switch to NEXT_MODE after this many seconds of dead reckoning.  If it cannot switch modes it will continue in Guided_NoGPS.  Set to 0 to disable timeout
- DR_NEXT_MODE : flight mode vehicle will change to when GPS / EKF recovers or DR_FLY_TIMEOUT expires.  Default is 6=RTL, see FLTMODE1 parameter description for list of flight mode number.  Set to -1 to return to mode used before deadreckoning was triggered

[Here is video demonstration of the script in SITL](https://www.youtube.com/watch?v=esM0EqMH_BE)
[Here is a test flight on a real vehicle](https://youtu.be/esM0EqMH_BE)

Some known dangers of this script:

- the script simply flies towards home for the specified number of seconds (or until the GPS quality improves) meaning that it may fly right past home
- when dead reckoning starts, the vehicle turns around to face home quite aggressively
- in strong wind it may be blown significantly off course
- the script may be unable to change the vehicle in Guided_NoGPS if the RC and/or GCS failsafe have triggered.  I've added comments in the script on how to avoid this problem by setting SYSID_MYGCS = 77 (or any other unused number).

In the future I hope we can use the EKF's built-in dead reckoning when wind estimation is enabled.

### CODE REVIEW

**Comment by IamPete1** [comment]
You can add a binding for `get_relative_position_D_home` with:
```
singleton AP_AHRS method get_relative_position_D_home void float'Ref
``` 
How does RTL get on if we were not to use the script? I guess you would have to disable some mode entry checks to test it.

**Comment by rmackay9** [comment]
@IamPete1,

Txs very much for that.  so re get_relative_position_D_home, my mistake was using "function" instead of "method".  Thanks!

RTL totally doesn't work, it just can't without a good position and velocity estimate from the EKF.  According to PaulR though, if we setup [wind-estimation](https://ardupilot.org/copter/docs/airspeed-estimation.html) then the EKF should be able to do dead-reckoning and then regular RTL (and Auto, etc) would keep working.  In my superficial testing in SITL though the EKF3's dead-reckoning is not kicking in however... so we need to dig into that more.

**Comment by rmackay9** [comment]
@IamPete1,

What do you think about the Lua binding for the failsafes?  It's not exactly flexible in that it simply returns 4 failsafe states (rc, gcs, ekf and terrain) meaning if we add more failsafes we might need to change the interface.  I think it's OK as it is but.. maybe poke an "approved" on this PR if you're OK with it?

**Comment by pompecukor** [comment]
_"This adds a copter-deadreckon-home lua script that takes control of the vehicle in Guided_NoGPS mode **and** flies in the last known direction of home if there an EKF failsafe or the GPS quality drops below a specified level"_

@rmackay9 
First of all great job and thank you for making this on such short notice.
When I called you about implementing such a feature, I may have not been 100% clear. One important goal of this it to be able to work even if Guided_NOGPS and the GPS quality is still high.
The reason for this is as currently in */insert currently invaded country of your choice/*, the way the jammers work is not that they are preventing the reception of the signals. Quite opposite, they are saturating the frequency with Bad/Fake signals. So that the drone thing it is very healthy, but that it is 200mile away, somewhere else.
So the request was to have a mode, like the above, where the pilot intentionally chose to tell the aircraft to ignore the GPS, not matter what the GPS tells it.
Maybe I got this all wrong, just that you used the "and" work in the top description.

**Comment by IamPete1** [comment]
Fail safe bindings is certainly a good idea, I wonder if it would be better implemented per library. For example we could have a binding to RC to see if it is in fail safe, there would be no requirement that a fail safe action be setup at the vehicle level. A script could then be configured to take whatever action based on that information. 

For example we already have a plane flight time to home based battery failsafe action that works a little like this. 

Doing this as a single binding, as you noted, means its hard to add new failsafes. It also means that it only works for copter, library level bindings would work for all vehicles.

**Comment by rmackay9** [comment]
@IamPete1,

I agree it would be best if we moved the failsafe handling to libraries so that they could be shared across vehicles but that's huge scope creep of course. .. I could shrink the scope of the binding so that it only covers the ekf failsafe if you think that's better.

**Comment by IamPete1** [comment]
@rmackay9 You picked one of the examples that we don't already know in the library. 

We can ask battery via these methods;

https://github.com/ArduPilot/ardupilot/blob/d621910a590d39c354275467b32f8b39008d3356/libraries/AP_BattMonitor/AP_BattMonitor.h#L194-L198

We can ask RC via valid input method:

https://github.com/ArduPilot/ardupilot/blob/d621910a590d39c354275467b32f8b39008d3356/libraries/RC_Channel/RC_Channel.h#L451-L452

GCS we could add a binding for this method:

https://github.com/ArduPilot/ardupilot/blob/d621910a590d39c354275467b32f8b39008d3356/libraries/GCS_MAVLink/GCS.h#L1030-L1034

Terrain would be quite easy to add in the WPNAV library.

For EKF we do already have a binding for `get_variances`.

These methods don't give you the same thresholds as the main vehicle code. But I think that gives you more flexibility. For example you might setup your script to trigger its failsafe at a lower level than the main vehicle code. So the script has a chance to do its action but if it still gets worse the vehicle action takes over. 

Using the same states, as in this PR could results in a race between the script and the vehicle actions, the script might get its mode change in first only for the vehicle to change it back.

**Comment by rmackay9** [comment]
@IamPete1,

Txs for that.  Sounds like we're tending towards changing the binding to just cover the EKF failsafe (which I'm totally happy with).

I don't think we should re-implement the EKF failsafe in lua because although it gives more flexibility it also adds more complexity (more things for users to get wrong) and in this case at least we're essentially adding an ekf failsafe override.  So having different criteria would be counter productive actually.

**Comment by rmackay9** [comment]
I've changed the binding to "has_ekf_failsafed" which is closer to the existing battery failsafe accessor.  I've also re-tested and I'll merge once it passes CI.

**Pull request merged**
