### PR TITLE
Copter: refactor landing to reduce duplication, use vertical vel ff, slow down precision landing descent based on position error

### PR DESCRIPTION
**Pull request by jschall**
This is based on https://github.com/ArduPilot/ardupilot/pull/4437

Using the vertical velocity feedforward was needed to make the slowdown more responsive. I've tested it in SITL - here's a plot of a 7 m/s (extremely fast) descent slowing down to LAND_SPEED by 7.5 m height:
figure_1

This has had changes since I did the testing, so I will re-do the testing today.

### CODE REVIEW

**Comment by jschall** [comment]
That last commit should allow travis to do its thing, and it can be removed when the PR goes into PX4Firmware.

**Comment by rmackay9** [comment]
I guess we can close the older PR 'cuz this one includes all it's goodness?
https://github.com/ArduPilot/ardupilot/pull/4437

**Comment by jschall** [comment]
Depends how you want to do it. You can merge that one and then review the changes made in this one if you like.

**Comment by rmackay9** [comment]
Merged, thanks!

**Pull request closed without merging**
