### PR TITLE
AP_Compass:QMC5883 Add internal i2c bus and fix rotation error

### PR DESCRIPTION
**Pull request by ljwang1102**
add internal i2c bus support,and fix rotation error

### CODE REVIEW

**Comment by ljwang1102** [comment]
#6488 it merge into Copter-3.5 and it contains #6445 and now(#6500) ,This is atypical,So I push this ,Modify before push some of the problems.
Do I need to be closed #6488？

**Comment by OXINARF** [comment]
@ljwang1102 No need to close #6488

**Comment by ljwang1102** [comment]
@tridge this fixed rotation bug and  internal i2c bus support,and it has test

**Comment by ljwang1102** [comment]
here are test [log](https://www.dropbox.com/s/0fp11nfds0p8evy/2017-07-10%2017-34-28.bin?dl=0)

**Comment by ljwang1102** [comment]
@tridge Before pull #6445 have been added "Copter 3.5 Backports",so I want you review this pull and merge it as soon as possible,then it can add to "Copter 3.5 Backports" together

**Comment by tridge** [comment]
I have fixed the commit message and pushed to master

**Comment by hobbyman2** [comment]
@ljwang1102 
excuse me my friend now i heard that there is big problem the HMC5983 and HMC5883 is out of production and most of the pixhawk gps + compass modules use them and there is going to be no stock of them now
what is the alternatives is the QMC5883 is the alternative and is it going to be fully supported in the pixhawk firmware or is there another alternatives that could be used ?
is there other supported alternatives also ?

**Pull request closed without merging**
