### PR TITLE
Sitl support grouped output and different pwm type

### PR DESCRIPTION
**Pull request by khancyr**
this replace https://github.com/ArduPilot/ardupilot/pull/6734
It will split the sitl ouput in 4 groups (kind like on pixhawk) to permit to set differents pwm type on it.
It implements support of different pwm type (like brushed for example). The sitl backend isn't changed.
For brushed type,  It currently converts the output requested on duty cycle because that is easy to plot and understand. It is reconverted into the 1000 - 2000 range to prevent scaling and breaking all backends.
This is mostyl a copy of RCoutput from chibios HAL.
Need to check :

- [x] no regression on normal pwm
- [x] that models still wait first pwm to move
- [X] check brushed support

### CODE REVIEW

**Comment by khancyr** [comment]
rebased on master

**Comment by tridge** [comment]
I'm not sure what you're trying to achieve here. It seems to add a lot of complexity to SITL, and I don't see how it helps us test.
I am concerned that the extra complexity will make it harder to work with SITL.

**Comment by peterbarker** [comment]
@khancyr did you want to pursue this one?  I think we'd need to see some evidence that it helped cross extra codepaths or something to make it worthwhile.

**Comment by khancyr** [comment]
I still want this as is it very usefull to debug brushed configuration on SITL but it would need a full rewrite

**Pull request closed without merging**
