### PR TITLE
SITL: fixed JSBSim backend to work with latest releases

### PR DESCRIPTION
**Pull request by tridge**
This is based on work by Willem Eerland to make the ArduPilot JSBSim SITL backend work with the latest JSBSim releases, which now have a way to do lock-step scheduling without modifications

### CODE REVIEW

**Comment by magicrub** [comment]
Does this mean we could make jsbsim a submodule?

**Comment by OXINARF** [comment]
@tridge This will make it not work with your modified version, right? If so, then we should change Tools/autotest/win_sitl/jsbsim_install.sh and Tools/autotest/win_sitl/jsbsimAPM_install.sh (and the wiki).

@magicrub Why would we want to make it a submodule? It's a just a tool that you might want to install or not (same as all other simulators).

**Comment by tridge** [comment]
@OXINARF right, though what I'll do is update my branch to point at master, and we can also update the docs

**Comment by magicrub** [comment]
Making this a submodule will reduce the installation complexity.

**Pull request merged**
