### PR TITLE
Fix loiter slew bug

### PR DESCRIPTION
**Pull request by lthall**
This PR fixes the problem where we apply the yaw slew limit in auto mode to loiter.

### CODE REVIEW

**Comment by rmackay9** [comment]
I did some simple testing on this and confirmed that this resolves the problem:

1. ATC_RATE_Y_MAX controls the maximum rotation rate in all modes (or at least Loiter and Auto)
2. ATC_SLEW_YAW controls the maximum rotation rate in Auto

**Review by rmackay9 — APPROVED** [review]

**Comment by peterbarker** [comment]
@MichelleRos

**Comment by rmackay9** [comment]
It would be nice if @IamPete1 can confirm he's happy with this too.

**Comment by rmackay9** [comment]
Ah, we forgot to fixup the parmeter description for ATC_SLEW_YAW to mention that it doesn't affect Loiter.

**Pull request merged**
