### PR TITLE
move GSF logging from EKF files into GSF files

### PR DESCRIPTION
**Pull request by peterbarker**
Passing the data back to the EKFs is just painful; far easier to pass the relevant numbers into the common function.

This will allow us to add more logging to the GSF and get both EKFs at once.

### CODE REVIEW

**Review by amilcarlucas — COMMENTED** [review]
Yet another patch that removes more lines then it adds :)

**Comment by rmackay9** [comment]
I suspect it won't conflict but this is another GSF related PR that should go in: https://github.com/ArduPilot/ardupilot/pull/16595

**Comment by peterbarker** [comment]
> I suspect it won't conflict but this is another GSF related PR that should go in: #16595

That other PR needs a rebase, but this does rebase cleanly on top of that (and this was on master on my machine, so Paul's PR currently rebases cleanly on master....)

**Comment by peterbarker** [comment]
I've split this up into separate commits and added a test to make sure we get logs from both EKF2 and EKF3.

Now why the GSF doesn't start spitting out data from EK2 I don't know:

image

**Comment by peterbarker** [comment]
Also saves ~300 bytes on CubeOrange

**Review by tridge — APPROVED** [review]

**Pull request merged**
