### PR TITLE
Copter: log and notify when manual land repositionning is active

### PR DESCRIPTION
**Pull request by khancyr**
This is need for precland test where radio are present.... it will log and try to notify once when we switch to manual land repositionning

### CODE REVIEW

**Comment by rmackay9** [comment]
I'm not a big fan of blasting out messages to the GCS when things are working normally.  Does the GCS really need a text string displayed to the pilot when the pilot is moving the sticks?

**Comment by khancyr** [comment]
it will notify only once. I am not fan of sending text message but, that the only way to notify the user.

**Comment by rmackay9** [comment]
@khancyr, do they really need the notification though?

**Comment by khancyr** [comment]
OK I see your point... but yes the text nofication should be keeped, other wise you won't know that you aren't doing preclanding. It can easily append with radio with low deadband.

This is only use one precland... I wonder if I should modify the report to be done only if precland is used. It should reduce the noise for all other users

**Comment by khancyr** [comment]
@rmackay9 Ok, I remove the text message. It should only log now. I don't see a right solution to notifiy the user without message with normal operation or adding new variable ... that a bit much overkill for an issue that won't append often.

**Comment by rmackay9** [comment]
Merged, thanks!

**Pull request merged**
