### PR TITLE
use HAL_SEMAPHORE_BLOCK_FOREVER

### PR DESCRIPTION
**Pull request by peterbarker**
... whereever we were passing `0`

I believe these patches should be reviewed to ensure that block-forever is what the author thought was going to happen.

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
LGTM

**Comment by rmackay9** [comment]
I'm probably overstepping my bounds but I've merged it.

I think the really questionable one is the BLOCK_FOREVER in the AP_GPS_UAVCAN::read function.  Surely that can't be right so @EShamaev should look at that one.

**Comment by EShamaev** [comment]
Please advice why do you find it questionable? If there is issue with UAVCAN and that semaphore can not be taken then this backend can be considered not working. However I can hardly imagine scenario for it not working (sem).

**Comment by rmackay9** [comment]
@EShamaev, I'm not the expert in this area but the GPS's read() method is called from Copter's update_GPS().  That means that if for any reason the semaphore isn't available, the main loop will stop which be a bit catastrophic for the vehicle.

**Comment by EShamaev** [comment]
Yes, but the only place where it is used is handle_gnss_msg which has only 2 lines of code in sem, that can not hang and are blazing fast. So I find it safe.
However I see your point, and even if it's impossible, we can do prevention of that. From practical point of view, what is the maximum time we can spend waiting for semaphore without any catastrophic results? This question is more for copter guys.

**Comment by rmackay9** [comment]
Our loops are 2.5ms by default so we certainly wouldn't want to wait that long.  If it was 0.1ms we would probably not notice even if it took that long.  Higher than 1ms is probably too high.

**Comment by peterbarker** [comment]
On Mon, 8 May 2017, Randy Mackay wrote:

> Our loops are 2.5ms by default so we certainly wouldn't want to wait that
> long. If it was 0.1ms we would probably not notice even if it took that
> long. Higher than 1ms is probably too high.

OTOH, there's the counter-argument: if you miss getting the semaphore 
because the other thread currently has it - what are the implications for 
the driver in each case?  If the implications are not dire (e.g. 
you'll be called again much faster than the other thread is updating 
the data) then take_nonblocking might be appropriate.

**Comment by EShamaev** [comment]
Implication will be that we will skip the GPS packet, so that's not best option.
Considering extremely small time spent in the sem code, small time should be OK.
I will fix and test this in the CAN PR that is open now.

**Comment by rmackay9** [comment]
@EShamaev, we discussed this on the dev call and it may or may not be the best idea to change that block-forever to have a timeout.  I don't think I'm qualified to say which it should be so I think perhaps @tridge should say whether they think it's required.

**Comment by OXINARF** [comment]
I wasn't in the dev call so I don't know what was talked, but I've discussed this before with @tridge and there are a few drivers where we use the block forever in flying code. I don't like it, but @tridge wasn't worried about it so I'm not sure what the way forward should be.

**Pull request merged**
