### PR TITLE
Copter: (NFC) renames for readability

### PR DESCRIPTION
**Pull request by amilcarlucas**
This improves consistency by adding frame and unit information to variables and function calls.

### CODE REVIEW

**Comment by peterbarker** [comment]
My understanding we labelling things when they were not in their "typical" units - e.g. metres and metres/second

**Comment by rmackay9** [comment]
Yes I agree with @peterbarker.  So if it was "cm" we would/should add the extension but for meters and meters/second we shouldn't.

**Comment by amilcarlucas** [comment]
I'll redo this one with only _deg

**Comment by amilcarlucas** [comment]
Done.

**Comment by rmackay9** [comment]
Merged, thanks!

**Pull request merged**
