### PR TITLE
Rover/EKF: fix for vehicle moving when GPS_TYPE=0

### PR DESCRIPTION
**Pull request by arshPratap**
This PR provides a fix for the bug that was reported here #14279.Thanks!
ekf-rover

### CODE REVIEW

**Comment by rmackay9** [comment]
@arshPratap,

Thanks for this PR.  I made the same change in [this PR](https://github.com/ArduPilot/ardupilot/pull/15148) a few months to resolve another problem with falling back to DCM.  The consensus from the dev team though was that disabling DCM was too drastic a solution and in fact we [found another solution to that problem here](https://github.com/ArduPilot/ardupilot/pull/15884).

We may eventually end up disabling DCM but before then we should investigate other solutions to this problem which may involve a small fix to DCM or modifying the fallback logic so that disabling the GPS is not enough to cause fallback.

Sorry this wasn't clear in the issue, I'll update it now.

**Comment by arshPratap** [comment]
The suggested PR(discussing an alternative for disabling DCM ) was really helpful and provided  me with some good insights related to the issue that I had missed.Thanks a lot @rmackay9  sir for reviewing this PR.

**Review by khancyr — CHANGES_REQUESTED** [review]
as per Randy review, this fix will need a deeper change on EFK to DCM logic to be accepted.

**Comment by rmackay9** [comment]
I think I'll go ahead and close this PR.  thanks in any case though.

**Pull request closed without merging**
