### PR TITLE
Deprecate make for Linux boards

### PR DESCRIPTION
**Pull request by lucasdemarchi**
This outputs a warning for people to notice the make build system is deprecated.

Besides that, it fixes the make build wrt to the generation of mavlink headers, that was not correctly ordered wrt submodule updates.

### CODE REVIEW

**Comment by OXINARF** [comment]
@lucasdemarchi Shouldn't we add it to SITL too? Or aren't we ready for that yet? By the way, have you looked at https://github.com/ArduPilot/ardupilot/issues/4026#issuecomment-216427666?

**Comment by WickedShell** [comment]
I'd like to request that until waf works with cygwin on Windows that make
not be deprecated for sitl (or at least not removed/broken). (Unless that
issue was already solved and I missed it while out of town this week)

**Comment by OXINARF** [comment]
@WickedShell this is just putting a warning so it shouldn't change anything, you can continue to use make.

**Comment by lucasdemarchi** [comment]
what's the problem with building it on windows? If there is any, could you open an issue on github so we keep track of it?

I also can remove the "sleep" I added if people prefer the warning to possibly not be noticed.

**Comment by lucasdemarchi** [comment]
@WickedShell btw, this is to allow people to complain about missing features and bugs **before** we make the final switch.  If we don't do this we will keep postponing it because we don't use all the features needed and don't know what's missing. The "add a warning and continue" is a good compromise I think.

**Comment by OXINARF** [comment]
@lucasdemarchi Michael is talking about the mavgen problem #4018 
I believe that without the sleep no one will read the warning, so I vote for it to stay.

**Comment by WickedShell** [comment]
I think I just usually worry about starting the process when there are
known problems.

Anyways the windows issue is
https://github.com/ArduPilot/ardupilot/issues/4018

**Comment by lucasdemarchi** [comment]
Applied. I'll wait #4018 to be closed in order to apply for sitl.

**Pull request closed without merging**
