### PR TITLE
Dataflash: unit and multiplier fixes

### PR DESCRIPTION
**Pull request by amilcarlucas**

### CODE REVIEW

**Comment by peterbarker** [comment]
Cool!

Is `POS` consistent across vehicles?

**Comment by amilcarlucas** [comment]
I checked it in copter only :(

**Comment by amilcarlucas** [comment]
POS seamd to be written from void DataFlash_Class::Log_Write_POS(AP_AHRS &ahrs)
So it is consistent across vehicles.

**Comment by rmackay9** [comment]
Merged 'cuz @peterbarker seems happy and he's the dataflash maintainer.

**Pull request merged**
