### PR TITLE
AP_NavEKF2/3: Do not check for ground magnetic interference in submarines

### LINKED ISSUE #130: Plane: restart mission at start if mission completed and re-enter AUTO
this makes sense if the mission is completed

### PR DESCRIPTION
**Pull request by patrickelectric**
Fix bluerobotics/ardusub#130

Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

### CODE REVIEW

**Comment by patrickelectric** [comment]
We'll review first in bluerobotics/ardusub/pull/137

**Comment by magicrub** [comment]
How did the review go? Did you get better innovations?

**Comment by patrickelectric** [comment]
I was wrong, the review will be done here  :bowtie:

**Comment by OXINARF** [comment]
This is missing the same change to EKF3, right?

**Comment by patrickelectric** [comment]
Ty @OXINARF, code updated.

**Comment by priseborough** [comment]
Can you please explain the problem that this PR is intended to solve. The linked issue does explain this or provide a log.

**Comment by patrickelectric** [comment]
Sorry for not being clear, the idea behind this PR is to avoid a `finalResetRequest` when the submarine is restarted/arm while underwater.

**Comment by priseborough** [comment]
OK, so for underwater vehicles you wish to have one yaw alignment at initialisation and none thereafter. How about when starting near the launching vessel which has interference? In that case we should  do a switch to 3-axis fusion and a reset after it dives.

This needs more thought.

**Comment by jaxxzer** [comment]
There's a few use cases to consider:

Operating off a boat, in open ocean, at significant depths (we can say reset after reaching a certain depth)
Operating off a boat at shallow depths in a river or lake (we might never go below a few meters depth, but we can be 100m out laterally from the boat)
Operating off a dock/bridge/pier which may have ferrous support structure
Operating in a swimming pool (concrete/rebar) or water tank (may be steel itself)

I don't know if we can make a reasonable estimate of when it is appropriate to do a reset for every case.

**Pull request closed without merging**
