### PR TITLE
AP_GPS: remove pointless initialisers

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by rmackay9** [comment]
I've never seen the "using" keyword before in our codebase so I'll let someone more qualified merge it

**Comment by peterbarker** [comment]
We use this in quite a few places now, actually.

Copter uses it extensively in mode.h, for example.

**Comment by rmackay9** [comment]
ok, i'll leave it to @WickedShell to decide as he's our GPS maintainer

**Comment by peterbarker** [comment]
Merged after discussions with @WickedShell

**Pull request merged**
