### PR TITLE
AIRLink: added default parameters files

### PR DESCRIPTION
**Pull request by aviaks**
Added default parameters for: 
- Battery monitor
- UART for mission computer

### CODE REVIEW

**Review by khancyr — APPROVED** [review]
I don't have hardware to check the value, but this comes from the manufacturer so it should be fine

**Review by khancyr — APPROVED** [review]
@aviaks could you just change  the commit message to start with HAL_ChibiOS: ?
And I will get somebody to merge it

**Comment by hendjoshsr71** [comment]
@aviaks I have fixed the commit message up for you.

**Review by hendjoshsr71 — APPROVED** [review]

**Comment by aviaks** [comment]
Thank you @hendjoshsr71!

**Pull request merged**
