### PR TITLE
AP_HAL_ChibiOS: RADIX2HD Probe external I2C compasses (4.4 backport)

### PR DESCRIPTION
**Pull request by mluessi**
Backport of  #24724 to 4.4

### CODE REVIEW

**Review by andyp1per — APPROVED** [review]

**Comment by andyp1per** [comment]
@rmackay9 it would be good if this could make it into 4.4.3

**Comment by mluessi** [comment]
Please let me know if anything else needs to be done from my end.

**Comment by rmackay9** [comment]
This is included in Copter-4.4.4-beta1

**Comment by rmackay9** [comment]
Not the end of the world of course but the PR linked in the description seems incorrect?  No big deal just makes it slightly more difficult for me to figure out what the change is related to.

**Pull request merged**
