### PR TITLE
Tools: install-env: add libsmfl and pygame; allows joystick and OSD

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by peterbarker** [comment]
Works at least for OSD.

**Comment by Hwurzburg** [comment]
so osd works....but if you are in Mavproxy and module load joystick it complains that  YAML is not installed and cant find the joystick module

**Comment by peterbarker** [comment]
@Hwurzburg I've hadded in python-yaml and python3-yaml packages.  I also have a "PyYAML" python package installed on my laptop - I don't think it's used 'though.

**Comment by peterbarker** [comment]
```
Loaded module joystick
```

**Comment by peterbarker** [comment]
@Hwurzburg thanks for testing.

**Pull request merged**
