### PR TITLE
AP_HAL_Linux: Add Raspberry Pi Zero support 

### PR DESCRIPTION
**Pull request by patrickelectric**
Using kernel 4.7.79-2 the cpuinfo hardware tag have the processor name.

```
[pi@companion ~]$ cat /proc/cpuinfo
processor	: 0
model name	: ARMv6-compatible processor rev 7 (v6l)
BogoMIPS	: 697.95
Features	: half thumb fastmult vfp edsp java tls 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xb76
CPU revision	: 7

Hardware	: BCM2835
Revision	: 9000c1
Serial		: 0000000050f9d54a
```
This patch allows multiple string checks per boards

### CODE REVIEW

**Comment by rmackay9** [comment]
This is well outside my area of expertise but maybe @tridge or @lucasdemarchi can say whether this is OK and safe.

**Comment by lucasdemarchi** [comment]
I just thought this had recently been fixed. Now I realize the other pr is still pending . Is this any better than #7369?

**Comment by rmackay9** [comment]
@lucasdemarchi, it looks like that other PR is stuck on a discussion between you and @256shadesofgrey.

I'm unsure what to do but I'd say if this PR looks safe then let's put it in.

**Comment by 256shadesofgrey** [comment]
@lucasdemarchi  @rmackay9  On my boards with kernel 4.9 the /proc/cpuinfo shows BCM2835 on all of the RPi boards (1, 2, 3, Zero, Zero W). For this approach to work it would have to be changed to check for the revision string instead of the hardware string to work on newer kernels, but this would require more future maintenance, because there are quite many different revisions ( https://www.raspberrypi.org/documentation/hardware/raspberrypi/revision-codes/README.md ), and it would affect Bebop[2] and Disco boards.

Since this was only tested on 4.7 and not 4.9 according to the original comment, I suspect (and this is only speculation on my part at this point) this doesn't actually fix the bug, and will in fact falsely recognize RPi 2 and 3 as RPi 1 until there is a kernel fix.

**Comment by lucasdemarchi** [comment]
I rather merged #7369. @patrickelectric can you check master is working for you?

**Comment by patrickelectric** [comment]
Probably I'll check in this week.

**Comment by rmackay9** [comment]
Thanks @lucasdemarchi and @patrickelectric!

**Pull request closed without merging**
