### PR TITLE
SITL running on Webots 

### PR DESCRIPTION
**Pull request by HefnySco**
Webots is an open source robot simulator that provides a complete development environment to model, program and simulate robots.

The main important part in the pull request is the controller file that reads data from webots world and send it to ardupilot sitl. the ardupilot sitl module is a replication of SIM_Morse.cpp but slightly modified for Webots.

The module is working but needs enhancements in PID params and drone structure design.

**This is the same** [pull request 11912](https://github.com/ArduPilot/ardupilot/pull/11912) 
just handled branches.

### CODE REVIEW

**Comment by HefnySco** [comment]
@tridge kindly advise if there is any more changes are needed or I missed something.

**Comment by HefnySco** [comment]
I noticed that when using OpenStreetMap with webots the north direction is changed from [1,0,0] to [0,0,1] and that corrupt all sensors directions.
I updated controller to detect this case and update sensors readings accordingly.
I also made a nice demo [where a drone is flying at Giza pyramids](https://youtu.be/c5CJaRH9Pig) and locations are synced between SITL and webots.

**Comment by HefnySco** [comment]
> Hello,
> 
> It seems good, but it need some squashing on commits ! See in http://ardupilot.org/dev/docs/submitting-patches-back-to-master.html
> 
> You will need to squash the commits. Ideally, it should remain 3 commits :
> 
> * Tools: add Pyramid location
> * SITL: add Webots support and examples
> * AP_HAL_SITL: add Webots support
> 
> **Could you do it ? you could force push on this branch**

@khancyr Thank you for your feedback. I have implemented  commits-squashing.

**Comment by HefnySco** [comment]
> Whoops, something went wrong on rebase

@khancyr Sorry I am a beginner in git

**Comment by HefnySco** [comment]
@khancyr waw it looks like I destroyed something !!! why build failed... it works fine locally.
kindly help.

**Comment by HefnySco** [comment]
@khancyr finally everything should be OK :D

**Comment by tridge** [comment]
I have rebased this PR on master and fixed the errors due to the small structure change in SIM_Aircraft. I think this is ready for merge when it passes CI

**Comment by PrasadNR** [comment]
I am working on something similar. https://discuss.ardupilot.org/t/using-ardupilot-px4-with-webots-sitl-simulation/48343 Could anyone let me know how I can use this particular merge and where I could find documentation about it? 

@HefnySco Thanks for this initiative!

**Comment by HefnySco** [comment]
Hey @PrasadNR 
I replied to your [thread](https://discuss.ardupilot.org/t/using-ardupilot-px4-with-custom-sitl-simulation/48343/5?u=mhefny)
=============== let me write it again here:
**STEPS TO RUN SIMULATOR:**

1- open webots.
2- open world you want to Run for example **webots_quadX.wbt
3**- press “**RUN**” button on webots. it is _very important that ardupilot SITL simulator is not running._
4- now run **droneX.sh** after step “3” the order is **VERY** important here.

**Side Notes:**
1- Please make sure that you compile controller and world physics plugin.
2- controller argument takes port number in case you want to change port numbers.
3- when ever you need to rerun you should
a. STOP SITL simulator
b. Restart webots simulator
c. rerun SITL simulator.

I hope this helps

**Comment by PrasadNR** [comment]
@HefnySco Thanks for the reply. However, I am facing the same issue as before!

I am listing down the steps.

> git clone https://github.com/ardupilot/ardupilot.git
> cd ardupilot
> git submodule update --init --recursive
> ./waf configure
> ./waf
> cd D:/ardupilot/libraries/SITL/examples/Webots
> (Now, I navigate to ```D:\ardupilot\libraries\SITL\examples\Webots\worlds``` and double-click ```webots_quadX.wbt```. Webots opens up and the simulation is running.)
> bash droneX.sh

I get the following error:

> droneX.sh: line 5: /cygdrive/d/ardupilot/libraries/SITL/examples/Webots/Tools/autotest/sim_vehicle.py: No such file or directory

In fact, I manually checked the path. ```D:/ardupilot/libraries/SITL/examples/Webots``` doesn't have Tools folder.

**Comment by HefnySco** [comment]
ok I got the issue. please stay in ardupilot directory.
**when I run the .sh I do the following:**
- cd ardupilot
- ./libraries/SITL/examples/Webots/droneX.sh
or you can write it manually:
[sim_vehicle.py](https://github.com/ArduPilot/ardupilot/blob/master/Tools/autotest/sim_vehicle.py)  -v ArduCopter -w --model webots-quad --add-param-file=[file path of quadX.parm ]

**Comment by PrasadNR** [comment]
@HefnySco 

> Prasad@Lenovo-PC /cygdrive/d/ardupilot
> $ ./libraries/SITL/examples/Webots/droneX.sh
> SIM_VEHICLE: Start
> SIM_VEHICLE: Killing tasks
> SIM_VEHICLE: Starting up at SITL location
> SIM_VEHICLE: WAF build
> SIM_VEHICLE: Configure waf
> SIM_VEHICLE: "/cygdrive/d/ardupilot/modules/waf/waf-light" "configure" "--board" "sitl"
> Setting top to                           : /cygdrive/d/ardupilot
> Setting out to                           : /cygdrive/d/ardupilot/build
> Autoconfiguration                        : enabled
> Setting board to                         : sitl
> Using toolchain                          : native
> Checking for 'g++' (C++ compiler)        : /usr/bin/g++
> Checking for 'gcc' (C compiler)          : /usr/bin/gcc
> Checking for c flags '-MMD'              : yes
> Checking for cxx flags '-MMD'            : yes
> Checking for need to link with librt     : not necessary
> Checking for feenableexcept              : no
> Checking for HAVE_CMATH_ISFINITE         : yes
> Checking for HAVE_CMATH_ISINF            : yes
> Checking for HAVE_CMATH_ISNAN            : yes
> Checking for NEED_CMATH_ISFINITE_STD_NAMESPACE : yes
> Checking for NEED_CMATH_ISINF_STD_NAMESPACE    : yes
> Checking for NEED_CMATH_ISNAN_STD_NAMESPACE    : yes
> Checking for header endian.h                   : yes
> Checking for header byteswap.h                 : yes
> Checking for HAVE_MEMRCHR                      : no
> Checking for program 'python'                  : /usr/bin/python
> Checking for python version >= 2.7.0           : 2.7.16
> Checking for program 'python'                  : /usr/bin/python
> Checking for python version >= 2.7.0           : 2.7.16
> Source is git repository                       : yes
> Update submodules                              : yes
> Checking for program 'git'                     : /usr/bin/git
> Checking for program 'size'                    : /usr/bin/size
> Benchmarks                                     : disabled
> Unit tests                                     : enabled
> Scripting                                      : enabled
> Scripting runtime checks                       : enabled
> Checking for program 'rsync'                   : /usr/bin/rsync
> 'configure' finished successfully (11.288s)
> SIM_VEHICLE: Building
> SIM_VEHICLE: "/cygdrive/d/ardupilot/modules/waf/waf-light" "build" "--target" "bin/arducopter"
> Waf: Entering directory `/cygdrive/d/ardupilot/build/sitl'
> Embedding file sandbox.lua:libraries/AP_Scripting/scripts/sandbox.lua
> Waf: Leaving directory `/cygdrive/d/ardupilot/build/sitl'
> 
> BUILD SUMMARY
> Build directory: /cygdrive/d/ardupilot/build/sitl
> Target          Text     Data   BSS  Total
> --------------------------------------------
> bin/arducopter  2642989  82868  416  2726273
> 
> Build commands will be stored in build/sitl/compile_commands.json
> 'build' finished successfully (10.637s)
> SIM_VEHICLE: Using defaults from (/cygdrive/d/ardupilot/Tools/autotest/default_params/copter.parm)
> SIM_VEHICLE: Adding parameters from (libraries/SITL/examples/Webots/quadX.parm)
> SIM_VEHICLE: Run ArduCopter
> SIM_VEHICLE: "/cygdrive/d/ardupilot/Tools/autotest/run_in_terminal_window.sh" "ArduCopter" "/cygdrive/d/ardupilot/build/sitl/bin/arducopter" "-S" "-I0" "-w" "--model" "webots-quad" "--speedup" "1" "--defaults" "/cygdrive/d/ardupilot/Tools/autotest/default_params/copter.parm,libraries/SITL/examples/Webots/quadX.parm"
> SIM_VEHICLE: Run MavProxy
> SIM_VEHICLE: "/usr/bin/cygstart" "-w" "mavproxy.exe" "--master" "tcp:127.0.0.1:5760" "--sitl" "127.0.0.1:5501" "--out" "127.0.0.1:14550" "--out" "127.0.0.1:14551"
> RiTW: Starting ArduCopter : /cygdrive/d/ardupilot/build/sitl/bin/arducopter -S -I0 -w --model webots-quad --speedup 1 --defaults /cygdrive/d/ardupilot/Tools/autotest/default_params/copter.parm,libraries/SITL/examples/Webots/quadX.parm
> which: no osascript in (/usr/local/bin:/usr/bin:/cygdrive/c/Program Files (x86)/Common Files/Oracle/Java/javapath:/cygdrive/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/bin:/cygdrive/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/libnvvp:/cygdrive/c/ProgramData/Anaconda3:/cygdrive/c/ProgramData/Anaconda3/Library/mingw-w64/bin:/cygdrive/c/ProgramData/Anaconda3/Library/usr/bin:/cygdrive/c/ProgramData/Anaconda3/Library/bin:/cygdrive/c/ProgramData/Anaconda3/Scripts:/cygdrive/c/Program Files (x86)/Lenovo/FusionEngine:/cygdrive/c/Program Files (x86)/Intel/iCLS Client:/cygdrive/c/Program Files/Intel/iCLS Client:/cygdrive/c/windows/system32:/cygdrive/c/windows:/cygdrive/c/windows/System32/Wbem:/cygdrive/c/windows/System32/WindowsPowerShell/v1.0:/cygdrive/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/cygdrive/c/Program Files/Intel/Intel(R) Management Engine Components/IPT:/cygdrive/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/cygdrive/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT:/cygdrive/c/Program Files (x86)/Lenovo/Motion Control:/cygdrive/c/Program Files (x86)/Common Files/lenovo/easyplussdk/bin:/cygdrive/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/cygdrive/c/Program Files/NVIDIA Corporation/Nsight Compute 2019.4.0:/cygdrive/c/Program Files/Git/cmd:/cygdrive/c/Program Files/CMake/bin:/cygdrive/c/Program Files/nodejs:/cygdrive/f/OpenCV-3.4-CUDA/x64/vc14/bin:/cygdrive/c/Program Files (x86)/Windows Kits/8.1/bin/x64:/cygdrive/d/FlightGear_folder/FlightGear/bin:/cygdrive/c/Program Files/ffmpeg-4.2-win64-static/bin:/cygdrive/c/Program Files (x86)/sox-14-4-2:/cygdrive/c/Program Files/Java/jdk-13/bin:/cygdrive/c/Program Files/dotnet:/cygdrive/c/ProgramData/chocolatey/bin:/cygdrive/c/Users/Prasad/AppData/Local/Programs/Python/Python37/Scripts:/cygdrive/c/Users/Prasad/AppData/Local/Programs/Python/Python37:/cygdrive/c/Users/Prasad/AppData/Roaming/npm:/cygdrive/c/Program Files/Mercurial:/cygdrive/c/Program Files/Docker Toolbox:/cygdrive/c/Program Files/Docker Toolbox)
> which: no xterm in (/usr/local/bin:/usr/bin:/cygdrive/c/Program Files (x86)/Common Files/Oracle/Java/javapath:/cygdrive/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/bin:/cygdrive/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/libnvvp:/cygdrive/c/ProgramData/Anaconda3:/cygdrive/c/ProgramData/Anaconda3/Library/mingw-w64/bin:/cygdrive/c/ProgramData/Anaconda3/Library/usr/bin:/cygdrive/c/ProgramData/Anaconda3/Library/bin:/cygdrive/c/ProgramData/Anaconda3/Scripts:/cygdrive/c/Program Files (x86)/Lenovo/FusionEngine:/cygdrive/c/Program Files (x86)/Intel/iCLS Client:/cygdrive/c/Program Files/Intel/iCLS Client:/cygdrive/c/windows/system32:/cygdrive/c/windows:/cygdrive/c/windows/System32/Wbem:/cygdrive/c/windows/System32/WindowsPowerShell/v1.0:/cygdrive/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/cygdrive/c/Program Files/Intel/Intel(R) Management Engine Components/IPT:/cygdrive/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/cygdrive/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT:/cygdrive/c/Program Files (x86)/Lenovo/Motion Control:/cygdrive/c/Program Files (x86)/Common Files/lenovo/easyplussdk/bin:/cygdrive/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/cygdrive/c/Program Files/NVIDIA Corporation/Nsight Compute 2019.4.0:/cygdrive/c/Program Files/Git/cmd:/cygdrive/c/Program Files/CMake/bin:/cygdrive/c/Program Files/nodejs:/cygdrive/f/OpenCV-3.4-CUDA/x64/vc14/bin:/cygdrive/c/Program Files (x86)/Windows Kits/8.1/bin/x64:/cygdrive/d/FlightGear_folder/FlightGear/bin:/cygdrive/c/Program Files/ffmpeg-4.2-win64-static/bin:/cygdrive/c/Program Files (x86)/sox-14-4-2:/cygdrive/c/Program Files/Java/jdk-13/bin:/cygdrive/c/Program Files/dotnet:/cygdrive/c/ProgramData/chocolatey/bin:/cygdrive/c/Users/Prasad/AppData/Local/Programs/Python/Python37/Scripts:/cygdrive/c/Users/Prasad/AppData/Local/Programs/Python/Python37:/cygdrive/c/Users/Prasad/AppData/Roaming/npm:/cygdrive/c/Program Files/Mercurial:/cygdrive/c/Program Files/Docker Toolbox:/cygdrive/c/Program Files/Docker Toolbox)
> which: no konsole in (/usr/local/bin:/usr/bin:/cygdrive/c/Program Files (x86)/Common Files/Oracle/Java/javapath:/cygdrive/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/bin:/cygdrive/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/libnvvp:/cygdrive/c/ProgramData/Anaconda3:/cygdrive/c/ProgramData/Anaconda3/Library/mingw-w64/bin:/cygdrive/c/ProgramData/Anaconda3/Library/usr/bin:/cygdrive/c/ProgramData/Anaconda3/Library/bin:/cygdrive/c/ProgramData/Anaconda3/Scripts:/cygdrive/c/Program Files (x86)/Lenovo/FusionEngine:/cygdrive/c/Program Files (x86)/Intel/iCLS Client:/cygdrive/c/Program Files/Intel/iCLS Client:/cygdrive/c/windows/system32:/cygdrive/c/windows:/cygdrive/c/windows/System32/Wbem:/cygdrive/c/windows/System32/WindowsPowerShell/v1.0:/cygdrive/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/cygdrive/c/Program Files/Intel/Intel(R) Management Engine Components/IPT:/cygdrive/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/cygdrive/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT:/cygdrive/c/Program Files (x86)/Lenovo/Motion Control:/cygdrive/c/Program Files (x86)/Common Files/lenovo/easyplussdk/bin:/cygdrive/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/cygdrive/c/Program Files/NVIDIA Corporation/Nsight Compute 2019.4.0:/cygdrive/c/Program Files/Git/cmd:/cygdrive/c/Program Files/CMake/bin:/cygdrive/c/Program Files/nodejs:/cygdrive/f/OpenCV-3.4-CUDA/x64/vc14/bin:/cygdrive/c/Program Files (x86)/Windows Kits/8.1/bin/x64:/cygdrive/d/FlightGear_folder/FlightGear/bin:/cygdrive/c/Program Files/ffmpeg-4.2-win64-static/bin:/cygdrive/c/Program Files (x86)/sox-14-4-2:/cygdrive/c/Program Files/Java/jdk-13/bin:/cygdrive/c/Program Files/dotnet:/cygdrive/c/ProgramData/chocolatey/bin:/cygdrive/c/Users/Prasad/AppData/Local/Programs/Python/Python37/Scripts:/cygdrive/c/Users/Prasad/AppData/Local/Programs/Python/Python37:/cygdrive/c/Users/Prasad/AppData/Roaming/npm:/cygdrive/c/Program Files/Mercurial:/cygdrive/c/Program Files/Docker Toolbox:/cygdrive/c/Program Files/Docker Toolbox)
> which: no gnome-terminal in (/usr/local/bin:/usr/bin:/cygdrive/c/Program Files (x86)/Common Files/Oracle/Java/javapath:/cygdrive/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/bin:/cygdrive/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/libnvvp:/cygdrive/c/ProgramData/Anaconda3:/cygdrive/c/ProgramData/Anaconda3/Library/mingw-w64/bin:/cygdrive/c/ProgramData/Anaconda3/Library/usr/bin:/cygdrive/c/ProgramData/Anaconda3/Library/bin:/cygdrive/c/ProgramData/Anaconda3/Scripts:/cygdrive/c/Program Files (x86)/Lenovo/FusionEngine:/cygdrive/c/Program Files (x86)/Intel/iCLS Client:/cygdrive/c/Program Files/Intel/iCLS Client:/cygdrive/c/windows/system32:/cygdrive/c/windows:/cygdrive/c/windows/System32/Wbem:/cygdrive/c/windows/System32/WindowsPowerShell/v1.0:/cygdrive/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/cygdrive/c/Program Files/Intel/Intel(R) Management Engine Components/IPT:/cygdrive/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/cygdrive/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT:/cygdrive/c/Program Files (x86)/Lenovo/Motion Control:/cygdrive/c/Program Files (x86)/Common Files/lenovo/easyplussdk/bin:/cygdrive/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/cygdrive/c/Program Files/NVIDIA Corporation/Nsight Compute 2019.4.0:/cygdrive/c/Program Files/Git/cmd:/cygdrive/c/Program Files/CMake/bin:/cygdrive/c/Program Files/nodejs:/cygdrive/f/OpenCV-3.4-CUDA/x64/vc14/bin:/cygdrive/c/Program Files (x86)/Windows Kits/8.1/bin/x64:/cygdrive/d/FlightGear_folder/FlightGear/bin:/cygdrive/c/Program Files/ffmpeg-4.2-win64-static/bin:/cygdrive/c/Program Files (x86)/sox-14-4-2:/cygdrive/c/Program Files/Java/jdk-13/bin:/cygdrive/c/Program Files/dotnet:/cygdrive/c/ProgramData/chocolatey/bin:/cygdrive/c/Users/Prasad/AppData/Local/Programs/Python/Python37/Scripts:/cygdrive/c/Users/Prasad/AppData/Local/Programs/Python/Python37:/cygdrive/c/Users/Prasad/AppData/Roaming/npm:/cygdrive/c/Program Files/Mercurial:/cygdrive/c/Program Files/Docker Toolbox:/cygdrive/c/Program Files/Docker Toolbox)
> RiTW: Window access not found, logging to /tmp/ArduCopter.log
> Unable to start 'mavproxy.exe': The specified file was not found.
> SIM_VEHICLE: MAVProxy exited
> SIM_VEHICLE: Killing tasks

I guess I have to somehow add mavproxy binary to path. Let me explore that option.

**Comment by PrasadNR** [comment]
No luck. I am still getting

> RiTW: Window access not found, logging to /tmp/ArduCopter.log

even after installing MavProxy from http://firmware.ardupilot.org/Tools/MAVProxy/

This looks like a Windows specific issue though. Let me check further info about RiTW

**Comment by PrasadNR** [comment]
```/tmp/ArduCopter.log``` has the following text:

> Set parameter SIM_SPEEDUP to 1.000000
> Started Webots with 127.0.0.1:5599 type 2
> Starting sketch 'ArduCopter'
> Starting SITL input
> Using Irlock at port : 9005
> bind port 5760 for 0
> Serial port 0 on TCP port 5760
> Waiting for connection ....

**Comment by HefnySco** [comment]
Could it be a port issue.
Try to run webots simulation and then run telnet 127.0.0.1 5599
No stil needed. It should connect and u should see data on terminal.

**Comment by HefnySco** [comment]
It could be: Takeoff started that means sitl sends motor commands to takeoff but the commands didnt reach simulator.
I believe simulator is not connected to SITL. Try the telnet test.

**Comment by PrasadNR** [comment]
@HefnySco I am getting the following
image

**Comment by PrasadNR** [comment]
1. I was not able to get this up and running. (Even ```telnet 127.0.0.1 5599``` does not work)

2. Also @HefnySco , is it possible to link this flight controller code in Docker? I can run Webots and then link Webots simulation to docker via input and output network ports. In this setup though, it is _very_ specific to Windows and linking to simulation requires some work.

**Comment by HefnySco** [comment]
Based on your reply I do suspect port issue. Try to run on VM ubuntu.

**Comment by HefnySco** [comment]
I will prepare video to show you how easy it works. It is really straight forward on ubuntu.

**Comment by PrasadNR** [comment]
I just looked around. There are four docker based projects. I am not sure if there is any documentation surrounding them or if they are active. But, that should give me a headstart. I will give it a shot now and report back.

https://hub.docker.com/r/gmyoungbloodparc/ardupilot-sitl/
https://github.com/emantas/uav-sitl-docker
https://github.com/ptsneves/ardupilot-docker
https://github.com/mickaelbaron/docker4sitl
https://dev.px4.io/v1.9.0/en/test_and_ci/docker.html

**Comment by HefnySco** [comment]
This video shows easy steps to check that simulator is running without any SITL integration.
https://youtu.be/RHj9d62iQng

**Comment by HefnySco** [comment]
I can see in this [docker](https://github.com/emantas/uav-sitl-docker/blob/master/Dockerfil) port exposed
EXPOSE 10000-10001
EXPOSE 14550-14559

you can try to run webots to use port other than 5599 by changing controller arguments. also please not that webots uses TCP not UDP connection.

**Comment by HefnySco** [comment]
**IP is the issue:**
I changed [SIM_Webots.h](https://github.com/ArduPilot/ardupilot/blob/8310058c8c613015038fa84755cc34788b7d89ea/libraries/SITL/SIM_Webots.h) I changed **webots_ip** to my laptop IP and it worked.
**This is a fast workaround.**

**Comment by HefnySco** [comment]
A more formal solution using docker:
just open this port 
 **p 5599:5599** 
xhost +
docker run -it --privileged \
 --env=LOCAL_USER_ID="$(id -u)" \
 -v /tmp/.X11-unix:/tmp/.X11-unix:ro \
 -v ~/ARDU_PILOT_PATH:/ardupilot:rw \
 -e DISPLAY=:0 \
 -p 14556:14556/udp \
 -p 8080:8080 \
 -p 5599:5599 \
  evans000/uav-sitl bash

**Comment by PrasadNR** [comment]
@HefnySco As I am using Windows, solution 1 is not working. As for the solution 2, I am getting this:

image

**Comment by HefnySco** [comment]
I cannot see **--model webots-quad:IP:PORT** in the command you run.

**Comment by PrasadNR** [comment]
> 
> 
> I cannot see **--model webots-quad:IP:PORT** in the command you run.

Oh yes. I tried that too. For some reason, it is not running with ```127.0.0.1:5599``` .

I get "Takeoff started" and "link 1 ok" even though nothing happens in simulation.

> 
> module load help
> Loaded module help
> Unknown command 'graph timespan 30'
> Log Directory:
> Telemetry log: mav.tlog
> Waiting for heartbeat from tcp:127.0.0.1:5760
> MAV> mode auto
> STABILIZE> mode guided
> STABILIZE> arm throttle
> GUIDED> takeoff 10
> GUIDED> Take Off started
> Got MAVLink msg: COMMAND_ACK {command : 22, result : 4}
> Flight battery 100 percent

**Steps:**
cd D:/ardupilot
_(Double click D:\ardupilot\libraries\SITL\examples\Webots\worlds\webots_quadX.wbt and run Cygwin terminal as admin)_
python Tools/autotest/sim_vehicle.py -v ArduCopter -w --model webots-quad:127.0.0.1:5599 --add-param-file=libraries/SITL/examples/Webots/quadPlus.parm

image

**Comment by HefnySco** [comment]
**--model webots-quad**  is a must because this is the parameter that tells SITL that webots is waiting for it otherwise you are using the internal physics simulator embedded in SITL.
IP should not be 127.0.0.1 because if you are using the docker so the connection will not get outside it, you need to make the IP equal to your pc ... in my case it is 192.168.1.25.
===================================

Also please do the following test that was mentioned in the video and confirm it works with you. so that we know we passed a step at least.

**Comment by PrasadNR** [comment]
@HefnySco 

1. Thanks for the warning regarding IP address! Yes. I had made that mistake of using 127.0.0.1! Now, I figured out that the ```ipconfig``` gives out ```192.168.2.6``` as the ```IPv4``` address of ```Wireless LAN adapter Wi-Fi``` I guess I have to check Ethernet0 or something (not wireless. I am looking into this right now).

2. When I tried to run ```telnet 127.0.0.1 5599``` test, I got no results like before. But, I followed your video and did "Remove intermediate build files" and "Build the current project" for ardupilot_SITL_QUAD.c . I got the following error: https://pastebin.com/dsWNyTJ7 (I am not sure if this is because of some GSL setup in Windows or so)

3. I am _not_ using docker currently and running directly from cloned ardupilot folder in Windows.

I will look into point 1 (ipconfig) and update this post.

**Comment by PrasadNR** [comment]
Also, I believe the problem can be solved if Ardupilot can be run as server (maybe in docker). I am trying this method right now and I will report back if I get any success. I guess the main problem in running two drones or so in same simulation has to do with Ardupilot physics engine. Instead, if Webots physics engine (ODE) is used, I do believe this could work. However, I am not sure.

**Comment by PrasadNR** [comment]
I figured out a solution using my own implementation of Python for Mavic Pro in SITL. 

Source: https://github.com/PrasadNR/Webots-STATUS/blob/master/controllers/mavic2proController/mavic2proController.py

However, this does not use Ardupilot. Nor could I figure out a way to link Ardupilot with drone's sensors and four motor velocities in Webots.

**Comment by PrasadNR** [comment]
For future reference:

As I could not run ardupilot with Webots ODE physics engine, I wrote my own flight controller capable of doing waypoint navigation. The code can be found and can be used in other projects if needed. I was thinking along the lines of this for ardupilot. But, I found my own flight controller much easier to work with.

Link: https://github.com/PrasadNR/Webots-Quadcopter-Python-SITL/blob/master/controllers/mavic2proController/mavic2proController.py

**Comment by rajeshroy402** [comment]
> I am working on something similar. https://discuss.ardupilot.org/t/using-ardupilot-px4-with-webots-sitl-simulation/48343 Could anyone let me know how I can use this particular merge and where I could find documentation about it?
> 
> @HefnySco Thanks for this initiative!

Is your problem solved? I want to use PX4 in Webots.

**Comment by HefnySco** [comment]
The last update of Webots should work smooth. I still work on Linux Ubuntu 20.04. I must highlight that the current uploaded version works with webots2020a and  **not later version** the latest version of webots has major changes in coordinates. I already have made the updates but waiting for them to release a final official release before publishing the updates.

**Comment by HefnySco** [comment]
> For future reference:
> 
> As I could not run ardupilot with Webots ODE physics engine, I wrote my own flight controller capable of doing waypoint navigation. The code can be found and can be used in other projects if needed. I was thinking along the lines of this for ardupilot. But, I found my own flight controller much easier to work with.
> 
> Link: https://github.com/PrasadNR/Webots-Quadcopter-Python-SITL/blob/master/controllers/mavic2proController/mavic2proController.py

@PrasadNR My simulation does simulate a quadcopter and exchange sensor readings with ardupilot to apply calculations. so you can test ardupilot parameters. I believe the simulation you made is a quadcopter on webots and has nothong to do with ardupilot. please correct me if I am wrong.

**Comment by PrasadNR** [comment]
@HefnySco 

> I believe the simulation you made is a quadcopter on webots

Yes. More details can be found here: https://github.com/PrasadNR/Webots-Quadcopter-Python-SITL .

**Comment by HefnySco** [comment]
> > I am working on something similar. https://discuss.ardupilot.org/t/using-ardupilot-px4-with-webots-sitl-simulation/48343 Could anyone let me know how I can use this particular merge and where I could find documentation about it?
> > @HefnySco Thanks for this initiative!
> 
> Is your problem solved? I want to use PX4 in Webots.

updated SITL is https://github.com/ArduPilot/ardupilot/pull/18337 compatible with Webots 2021b

**Pull request merged**
