### PR TITLE
Copter: smoothing land on auto and update navigation report

### PR DESCRIPTION
**Pull request by khancyr**
this correct the report of the land position on auto mode.
It also allow smoother transition on land, indeed, if we need to land on spot, we will start by using the loiter_controler that is more raw that the wp_controler. This patch will now start using the wp controler before the loiter_controler ensuring a smooth transition

### CODE REVIEW

**Comment by rmackay9** [comment]
@khancyr, the first part looks good.  I wonder about the landing portion using the stopping point though. Have you tested that the vehicle attempts to land at the exact location specified (optionally) in the Land command?

**Comment by khancyr** [comment]
@rmackay9 Yes, this behavior isn't changed. The change only apply in the case where no location is specified

**Comment by khancyr** [comment]
@rmackay9 I have split the commit in two.

The first one is safe to merge as that is just for reporting the target.

The second on is a subtle change. It change from using loiter_controler to wpnav_controller. The stopping point calculated is the same as both are using _pos_control.get_stopping_point_xy(). The change append on the way the controller will behave. With the wpnav_controller the stopping constraint are less stricts that on the loiter one's. If we got too far from the stopping point (because of inertia, wind, etc.) the wpnav_controller will bring back the drone without a sudden and big angle change that put hard constraints to the mechanic of the drone

**Comment by rmackay9** [comment]
@khancyr,

I'm still not sure about this second part of the change.  It might be slightly better to modify land_start() to use the wpnav controller's get_stopping_point and then pass that into the land_start(Vector3f) if the issue is that the loiter controller has higher acceleration limits.

If possible could you provide some screenshots from SITL showing that the slowdown is smoother?

To be clear, I don't doubt that you've found a real issue so thanks for this.

**Pull request closed without merging**
