### PR TITLE
Update AP_Airspeed_MS4525.cpp

### PR DESCRIPTION
**Pull request by duran9dv**
update airspeed sensor to read and work with Pixhawk 4 adding { 3, MS4525D0_I2C_ADDR }, to the code

### CODE REVIEW

**Comment by magicrub** [comment]
How is this enabling it on Pixhawk 4?

**Comment by magicrub** [comment]
Ahh, I see. It related to another PR (https://github.com/ArduPilot/ardupilot/issues/9715). In the future, if a piece of code is fixing an existing published issue, it's nice to link them so we know it's not just random code to fix an unknown problem.

**Comment by duran9dv** [comment]
Thanks @magicrub, new here, i was about to reference/link the other issue here, does this merge mean it's now in the master code available in Mission Planner ?

**Comment by magicrub** [comment]
@duran9dv yes, in master. Take look
https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Airspeed/AP_Airspeed_MS4525.cpp#L47

**Comment by duran9dv** [comment]
awesome, will test tomorrow morning to confirm :) thanks @magicrub appreciate it

**Pull request merged**
