### PR TITLE
Sub: handle GPS_INPUT in base GCS_MAVLINK class

### PR DESCRIPTION
**Pull request by peterbarker**
Missed this one in 2aaaba8397284ef48fdc687bfa7b1935b141ca5d

### CODE REVIEW

**Comment by magicrub** [comment]
How did Travis miss this on the other PRs?

**Comment by WickedShell** [comment]
Travis wouldn't care about this. It's just checking the same case in to different code locations. Technically possible for a compiler to care about, but that is really deep code inspection to get to it...

**Comment by magicrub** [comment]
Oh, my bad. I was thinking it was related to that recent sub issue that it wasn't compiling due to gcs not being defined or something.

**Comment by OXINARF** [comment]
Ah I missed this one! Merged, thanks!

**Pull request merged**
