### PR TITLE
Copter: Fixed arming checks on the PID's to not allow negatives.  

### PR DESCRIPTION
**Pull request by ChrisBird**
Also added additional negative checks for the forward feed items.

### CODE REVIEW

**Comment by khancyr** [comment]
same as https://github.com/ArduPilot/ardupilot/pull/10168 ?

**Comment by ChrisBird** [comment]
Odd i rebased it before i submitted it.  This one also adds three new checks to ensure the forward feeds are not negative.

**Comment by auturgy** [comment]
Peter’s hasn’t been merged, so a rebase wouldn’t find it :)
Might be worth a chat with @peterbarker to decide which way to go

**Comment by peterbarker** [comment]
On Sat, 12 Jan 2019, auturgy wrote:

> Peter’s hasn’t been merged, so a rebase wouldn’t find it :)
> Might be worth a chat with @peterbarker to decide which way to go

I've just closed that one - Randy pointed out it wasn't really sufficient.

I've replaced it with https://github.com/ArduPilot/ardupilot/pull/10214 - 
that replaces the code with a couple of data structures, which may make it 
easier to add additional checks.

I was musing on making a validate(...) call on the PID objects themselves 
- but we use the same objects in different ways which makes that 
problematic.  If we can swing that somehow then all the other vehicles 
could take advantage of the validation.

**Comment by ChrisBird** [comment]
I'll have a look at the new pr, I'll close this one.

**Pull request closed without merging**
