### PR TITLE
A neater method of constructing Backends

### PR DESCRIPTION
**Pull request by kwikius**
A neater method of constructing sensor Backends.

I chose the AP_Baro as an example sensor, but the same applies to many other sensors

In this version a template function is declared in AP_Baro.h 

template \<uint32_t BackendID\>
AP_Baro_Backend* create_default_baro_backend(AP_Baro& baro);

Note there is no default function definition. It is up to each Backend to create a specialisation of the function.
The  BackendID is the value of the HAL_BARO_DEFAULT macro.

The resulting code reduction can be seen in the void AP_Baro::init(void) function in AP_Baro.cpp, which is now much cleaner and easier to read.

A more advanced version would use class tags and typedefs to provide the same functionality without the need for macros.

### CODE REVIEW

**Comment by magicrub** [comment]
I like it... I think. Templates usually make me cry but I think this is a net positive change

**Comment by kwikius** [comment]
I've removed the specific AP_Baro Backend headers from AP_Baro.cpp as now the frontend doesnt need to know how to construct backends directly.

Similar could be done in AP_Compass, AP_InertialSensor, AP_Rangefinder, AP_OpticalFlow etc.

**Comment by magicrub** [comment]
I like it. @tridge @rmackay9 @gmorph @lucasdemarchi @peterbarker ?

**Comment by peterbarker** [comment]
I like it, but I also have reservations about the template thing.  If something goes wrong you often end up with a message with way too many long words and punctuation.

Additionally, we'll be relying on optimisation to remove extra code generated - in particular, any of the `create_default_baro_backend` which were constructed (because the defines were set), but not used (because they weren't the default or a special case like HIL).  Small functions, so it doesn't really matter.

Comments required to let people know what's going on, as it isn't something we do anywhere else ATM :-)

**Comment by magicrub** [comment]
Also, of we let this in are you willing to port the changes to the other libraries too.. soon?

**Comment by lucasdemarchi** [comment]
I kind of like it, but I'm not sure it scales. Take a look on the compass classes. We are moving away from the ifdefs per board defining a "default" backend and just let they probe to check if sensor is available or at least add some sensors that may or may not be there. Having a configuration file that allows the choice to be in runtime rather than compile time would be the ultimate goal (you'd always be able to ifdef out though if you have space constraints).  I think this patch is moving to the opposite direction or did I miss anything?

**Comment by magicrub** [comment]
Also, if we let this in are you willing to port the changes to the other libraries too.. soon?

**Comment by tridge** [comment]
I'm also concerned about how it scales, plus it really just spreads the bus connection information out across multiple files. It isn't as easy to see all the bus options together any more.
As Lucas says, we want to move to a config file or at least a table later. The templates don't take us any closer to that goal.

**Comment by kwikius** [comment]
@tridge This is a similar situation to a virtual function. The backend provides the implementation. If the frontend has to know all about every possible backend then that is not scaleable.
I would argue that this version is more scalable since I have removed the requirement to have all the possible backend headers in the source file(since it was required to know their constructors and so their implementation)

@peterbarker As far as extra code, the linker should clean up anything not called, dependent on the linker settings.

As to the error message, here is the linker error message if I undefine the particular definition for px4 build

Makefile:1289: recipe for target 'build_firmware_px4fmu-v2' failed
/home/andy/cpp/projects/ardupilot/build/px4-v2/lib/bin/libardurover.a(AP_Baro.cpp.2.o): In function `AP_Baro::init()':
/home/andy/cpp/projects/ardupilot/build/px4-v2/../../libraries/AP_Baro/AP_Baro.cpp:285: undefined reference to `AP_Baro_Backend* create_default_baro_backend<5u>(AP_Baro&)'
collect2: error: ld returned 1 exit status

For creating new backends my usual route is to copy from an existing one to start with and I dont think it is complicated to understand. This is not a complicated use of template use.

As to comments, yes I will do a bit more documentation

@Lucasdemarchi
This approach is more scaleable than current. It would allow individual boards to decide whether they allowed runtime detection or not , since they define the function
rather than AP_Baro. (Personally I am more interested in low end boards where runtime detection is less optimal) With some modification, boards could add more sensors in their function.
Template function is just a function. can be used as any other function

As to AP_Compass, I cant see a problem.  I assume you mean Compass::_detect_backends function) Same sort of approach would apply
with (say) a detect_compass_backends<HAL_COMPASS_DEFAULT>() function. Same approach. 

@magicrub.  Well, I put this  here as a RFC. Obviously would only want to do the rest only if there was agreement that it is a good idea.

**Comment by kwikius** [comment]
EDIT. In fact the function could use the CONFIG_HAL_BOARD as the template argument. Then each board could do its connections as it wished, and maybe add all its sensors, runtime detect etc

**Comment by kwikius** [comment]
Closing this. It seems pretty simple and an improvement to me. I have made my arguments. It seems to be just a fear of templates that is the problem here, so on with the MACROS :)

**Comment by lucasdemarchi** [comment]
@kwikius just to make it clear since I would be the one to take this kind of patch in: the problem is not really the template but rather that it isn't going in the direction I pointed above. I like not having to include each Backend in order to construct them.

**Pull request closed without merging**
