### PR TITLE
 Copter: Integrate multiple battery information.

### PR DESCRIPTION
**Pull request by muramura**
I connect multiple smart batteries in parallel.
Voltage and current values displayed in GCS are values only for the primary.

When connecting in parallel, I think that it will be as follows.
- Voltage is high battery value,
- Current is the sum of each battery,
- Battery value with high remaining capacity

### CODE REVIEW

**Comment by OXINARF** [comment]
I don't see how this makes sense, we already send BATTERY2 messages: https://github.com/ArduPilot/ardupilot/blob/master/libraries/GCS_MAVLink/GCS_Common.cpp#L1275-L1287

**Comment by WickedShell** [comment]
Agreed, we already send the GCS all the correct information (more importantly then Battery2 we send [BATTERY_STATUS](http://mavlink.org/messages/common#BATTERY_STATUS) which contains the per cell voltage and we send it for every connected battery. This is a GCS issue, not an aircraft issue. Also depending on setup summing batteries like this is absolutely wrong/incorrect as whats presented only works if all batteries are propulsion batteries, (or I guess all avionics) but does not account for a mixture of avionics and propulsion batteries.

**Comment by muramura** [comment]
@OXINARF san. 
This process sends only the voltage and current of battery 2.
We can see the value of each of Battery 1, Battery 2 like this image.
In the case of a battery connected in parallel, I think that "total voltage, current" is necessary.

**Comment by WickedShell** [comment]
I retain the opinion that this should be done on the GCS side. There isn't enough space to send the 12 cells to the GCS in the existing BATTERY_STATUS, but it nicely splits over the 2 messages. It's also not a reasonable thing to force on any vehicle which has independent monitoring of a flight battery and an avionics battery. In short I think this is a spot where you should be instructing your GCS on how you want to view information, rather then forcing the autopilot to sum things that don't belong as a sum.

**Comment by muramura** [comment]
@WickedShell san..Thank you.
I understand. 
I will ask GCS to create integrated information using the values of Battery 1 and Battery 2.

**Pull request closed without merging**
