### PR TITLE
Face next wp (except RTL) before moving towards it

### LINKED ISSUE #11587: Copter: Slow yaw response while flying grid
**Issue details**

While flying a tight grid with WP_YAW_BEHAVIOR set to 1, the yaw response is delayed after reaching the second turnpoint in the grid. I would expect it to make a coordinated turn just like when reaching the first turnpoint.
I have attached a log and the first person kml, that shows the problem.

**Version**
V3.6.9

**Platform**
[  ] All
[  ] AntennaTracker
[X] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Problem reproduced on Quad and Octo frames.

**Hardware type**
Pixhawk, Pixhawk Cube

**Logs**

[Logs.zip](https://github.com/ArduPilot/ardupilot/files/3289576/Logs.zip)

### PR DESCRIPTION
**Pull request by amilcarlucas**
Improves the cut-corners issue when doing surveys

Fixes #11587

https://discuss.ardupilot.org/t/yaw-turn-types-in-auto-mode/40055
https://discuss.ardupilot.org/t/yaw-at-waypoints/45138/2

Tested in SITL

### CODE REVIEW

**Comment by peterbarker** [comment]
This will be handy for something I'm doing ATM.

An autotest would be good.

**Comment by Hasi123** [comment]
Any news on this?

**Comment by amilcarlucas** [comment]
@rmackay9 should I close this one now that S-curves are almost there?

**Comment by khancyr** [comment]
@amilcarlucas S-curve was merged, do we still need this ?

**Comment by amilcarlucas** [comment]
Nope, I do not think so. Thanks.

**Pull request closed without merging**
