### PR TITLE
Tools: TestGPSGlitch.py: Fix TabErrors for Python 3

### LINKED ISSUE #6997: Tools: TestGPSGlitch.py: TabError: inconsistent use of tabs and spaces in indentation
$ __python3 Tools/LogAnalyzer/tests/TestGPSGlitch.py__
```
  File "Tools/LogAnalyzer/tests/TestGPSGlitch.py", line 12
    def findSatsChan(self, channels):
                                    ^
TabError: inconsistent use of tabs and spaces in indentation
```

### PR DESCRIPTION
**Pull request by cclauss**
Fixes #6997  Python3 raises a TabError: inconsistent use of tabs and spaces in indentation

Also removed unused import and redundant parenthesis inside of an if statement.

### CODE REVIEW

**Comment by OXINARF** [comment]
@cclauss When doing changes like this you should always keep whitespace changes separate from any other change. If you go to https://github.com/ArduPilot/ardupilot/pull/7011/files?w=1, you get a diff with whitespaces changes ignored (not perfectly, but good enough) and you can see that you have done other changes that should be in a separate commit. I recommend you wait for @peterbarker's review before doing that though.

**Comment by cclauss** [comment]
When opening up a file, I endeavor to make those changes that make sense so we do not have a ton small PRs on a single file.  All changes to this file were squashed into a single "__perfect commit__" which (I have learned the hard way) is the only kind of pull request that is accepted into this repo.

**Comment by peterbarker** [comment]
This is what @OXINARF was getting at - something like this:
https://github.com/ArduPilot/ardupilot/pull/7017

Since we're changing every line anyway (and thus completely screwing up `git blame`), making it flake8-compliant at the same time makes a lot of sense.

**Comment by cclauss** [comment]
#7017

**Comment by cclauss** [comment]
Closed in favor of #7017

**Comment by OXINARF** [comment]
@cclauss 

> we do not have a ton small PRs on a single file

Why would you do that? Just make one PR with multiple commits...

> All changes to this file were squashed into a single "perfect commit" which (I have learned the hard way) is the only kind of pull request that is accepted into this repo.

Not true at all. If the PR doesn't follow our rules it can take more time to get in because someone will have to correct it before merging. A project this size needs to have rules or it becomes unmanageable. I'm trying to teach you the rules we go by so that you can follow them and get your PRs merged faster. It's up to you to follow them or not.

**Pull request closed without merging**
