### PR TITLE
Copter: re-added reason to mode change log msg

### PR DESCRIPTION
**Pull request by tridge**
this was lost in the mode restructuring

### CODE REVIEW

**Comment by rmackay9** [comment]
merged, thanks!

**Comment by peterbarker** [comment]
One too many rebases.

This PR removes the defaulting for the reason: https://github.com/ArduPilot/ardupilot/pull/7755

**Comment by olliw42** [comment]
isn't function-relevant, but for reasons of symmetry shouldn't it be `DataFlash.Log_Write_Mode(control_mode, control_mode_reason);` ?

**Comment by peterbarker** [comment]
On Wed, 21 Feb 2018, olliw42 wrote:

> isn't function-relevant, but for reasons of symmetry shouldn't it be
> DataFlash.Log_Write_Mode(control_mode, control_mode_reason); ?

Probably just

DataFlash.Log_Write_Mode(mode, reason);

**Pull request merged**
