### PR TITLE
Use CLASS_NO_COPY() macro to delete copy operations

### PR DESCRIPTION
**Pull request by jackhong12**
Solve #21837.

### CODE REVIEW

**Review by peterbarker — APPROVED** [review]
LGTM

**Comment by peterbarker** [comment]
@jackhong12 a prefix of `global: ` might be better than `all: `.  There's 70 commits in our history with the former, 1 with the latter.

**Comment by rmackay9** [comment]
@jackhong12, thanks for this.  I agree with what PeterB says.

Before we merge I would just like to hear from other devs that they are OK with this huge single commit.  It should be fine but it risks making back-ports more difficult and we've just branched for 4.3.  Again, it should be fine but I would just like to hear from other devs as well (which is why we've added it to the DevCall)

**Comment by peterbarker** [comment]
@jackhong12 ... I have a preference for the single commit, so please leave as-is for now :-)

**Comment by jackhong12** [comment]
Okay. Thanks for reviewing this!

**Review by tridge — APPROVED** [review]

**Comment by tridge** [comment]
@jackhong12 thanks for the contribution!

**Comment by peterbarker** [comment]
Merged, thanks @jackhong12

**Comment by jackhong12** [comment]
My pleasure. :)

**Pull request merged**
