### PR TITLE
Copter: correct documentation of use of DO_CHANGE_SPEED parameter

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Review by rmackay9 — COMMENTED** [review]
looks good.

nitpick: normally we don't use capitals on the first word do we?  no big deal of course.

**Review by rmackay9 — APPROVED** [review]

**Comment by Hwurzburg** [comment]
what about param3?....wiki says its used

**Comment by peterbarker** [comment]
@Hwurzburg these are comments within the Copter codebase - they're not part of our Wiki documentation.  Copter does not use param3.

**Comment by Hwurzburg** [comment]
@peterbarker :
1. While the comments are not directly part of the WIKI, the WIKI describes this command and its params for Copter in two places, both of which are incorrect and need changing...Plane wiki for this seems correct...but its probably worth noting that executing this command appears to be persistent until next boot or speed command and I am also not sure if Copter has the same protections against executing it in Pilot controlled and FS modes....need help getting those answers @rmackay9  @tridge 
2. Where in the Copter code for this command does it use 0=Airspeed? from my read setting param1 = 0 is the same as setting it to 1...so this portion of the added comment seems incorrect...

**Pull request merged**
