### PR TITLE
Kill HAL_PERIPH_ENABLE_MSP

### PR DESCRIPTION
**Pull request by peterbarker**
it was only defined if HAL_MSP_ENABLED was also defined, so kill it

Since Periph instantiates AP_MSP, it HAL_MSP_ENABLED must be set anyway

### CODE REVIEW

**Comment by magicrub** [comment]
I'm definitely in favor of changes this. However, this changes both Matek configs. Is that OK?

**Comment by tridge** [comment]
@peterbarker it was supposed to separate enable of MSP output from AP_Periph versus MSP input from other sensors. They are separate concepts

**Comment by peterbarker** [comment]
> @peterbarker it was supposed to separate enable of MSP output from AP_Periph versus MSP input from other sensors. They are separate concepts

I'm pretty sure I misunderstood that when writing this PR, because that's not how this currently works :-)

Outputting the sensors requires `HAL_MSP_ENABLED` to be set as the definition of the `AP_MSP` class is gated around `HAL_MSP_ENABLED`, and that class is instantiated in `AP_Periph.h` based on HAL_PERIPH_ENABLE_MSP`.

In other words, if `HAL_PERIPH_ENABLE_MSP` is set then `HAL_MSP_ENABLED` must be set.  If you remove `HAL_MSP_ENABLED` from `F405-MatekGPS`'s hwdef and compile it will still work - because that board isn't `MINIMIZE_FEATURES`, so `HAL_MSP_ENABLED` remains true.  If you explicitly turn it *off* you will get a compilation error because the `AP_MSP` class isn't defined.

Since the creation of `AP_MSP msp;` is gated on `HAL_PERIPH_ENABLE_MSP`, I really can't see how *just* having `HAL_MSP_ENABLED` is useful.  We don't parse MSP in AP_Periph AFAICS - while we instantiate the MSP singleton we never init() it so no thread is created.  I'm not even sure we need the singleton....

**Comment by tridge** [comment]
main thing is to ensure the Matek*GPS models that have a MSP and CAN port keep working

**Pull request closed without merging**
