### PR TITLE
AP_Math: Move crc16-ibm CRC calculation method to a common class

### PR DESCRIPTION
**Pull request by muramura**
Robotis Servos' CRC16 uses CRC16-IBM instead of its own calculations.
I prefer to make it a common class method for general CRCs.

https://emanual.robotis.com/docs/en/dxl/crc/

### CODE REVIEW

**Review by khancyr — APPROVED** [review]
LGTM
1-1 move to AP_Math
we did it for other crc even if there is only one consumer.
It is a little interesting as it make use gain some flash

**Review by tridge — APPROVED** [review]

**Comment by tridge** [comment]
needs rebase

**Comment by hendjoshsr71** [comment]
@muramura san I have rebased this for you.

**Comment by peterbarker** [comment]
@muramura @hendjoshsr71 

So not a "move":

```
 Binary Name      Text [B]        Data [B]     BSS (B)      Total Flash Change [B] (%)      Flash Free After PR (B)
---------------  --------------  -----------  -----------  ----------------------------  -------------------------
arducopter-heli  -56 (-0.0032%)  0 (0.0000%)  0 (0.0000%)  -56 (-0.0032%)                                   227588
blimp            -56 (-0.0044%)  0 (0.0000%)  0 (0.0000%)  -56 (-0.0044%)                                   686884
antennatracker   -56 (-0.0042%)  0 (0.0000%)  0 (0.0000%)  -56 (-0.0042%)                                   617700
ardusub          -56 (-0.0036%)  0 (0.0000%)  0 (0.0000%)  -56 (-0.0036%)                                   402220
arducopter       -56 (-0.0032%)  0 (0.0000%)  0 (0.0000%)  -56 (-0.0032%)                                   205092
arduplane        -56 (-0.0032%)  0 (0.0000%)  0 (0.0000%)  -56 (-0.0032%)                                   212084
ardurover        -56 (-0.0035%)  0 (0.0000%)  0 (0.0000%)  -56 (-0.0035%)                                   379532
```

This effect probably could have been had by declaring the function `static`, too, at at guess.

**Comment by peterbarker** [comment]
Merged, thanks

**Comment by hendjoshsr71** [comment]
Huh. So by making it static the compiler would have acted a  little smarter then....?

image

The 512 byte table just moves.
image

**Pull request merged**
