### PR TITLE
Rover add fence support (2/3)

### PR DESCRIPTION
**Pull request by khancyr**
based on https://github.com/ArduPilot/ardupilot/pull/6659

### CODE REVIEW

**Comment by rmackay9** [comment]
Do people think it's OK to add a reference to AC_Fence to AP_Arming?  AC_Fence is currently a copter specific library.

**Comment by WickedShell** [comment]
If it's hidden by some #ifdef's I'm fine with it. The normal approach has been the vehicle specific subclass that extends AP_Arming (like what you see in Plane). That being said I don't like the plane one as far as the code split.

**Comment by khancyr** [comment]
rebased and correct ordering warning and error in makefile

**Comment by khancyr** [comment]
rebased on master

**Comment by khancyr** [comment]
replace by https://github.com/ArduPilot/ardupilot/pull/6775

**Pull request closed without merging**
