### PR TITLE
Fix FrSky autotests

### PR DESCRIPTION
**Pull request by peterbarker**
Some of these are so that the tests run under Valgrind.

The changes to frsky itself are because we're testing against AHRS data in the autotest but we're using GPS data in FrSky.  I'm quite happy to change the tests instead - but we really ought to be using the AHRS for what it is good for.

### CODE REVIEW

**Comment by peterbarker** [comment]
@yaapu we can drop the changes to FRSky here if they make you uncomfortable.  They're not needed for the actual fixes in this PR.

The RPM changes are important, however.  The test code was always expecting a response from the autopilot for a polled sensor, and while it did time out and move onto the next sensor, it takes a long time to do that.  I've both fixed the problem which was causing it to stall *and* reduced the timeout in the test code.

**Comment by yaapu** [comment]
@peterbarker I'm fine with the changes, one thing that was overlooked by the original authors was the matching with the sources used by mavlink, so really no issue here, as for the RPM stuff I see no issues but I'd like to test it

**Review by yaapu — APPROVED** [review]

**Comment by peterbarker** [comment]
@yaapu I see it less as matching mavlink but rather as presenting the vehicle's best-guess as to where it is.  ArduPilot can do that even in the absence of a GPS, so IMO we're asking the wrong thing for data.  The "GPS" bent is really just historical, I reckon....

**Comment by yaapu** [comment]
@peterbarker my point is that I get complaints about frsky data not matching what MP or QGC shows, like altitude for instance which on GCS is often baro based but having said that I'm with you,I like the idea of the pilot seeing same data that the autopilot is "seeing"

**Comment by peterbarker** [comment]
@yaapu hmmm.  The vast majority of the time the GCSs will be using `GLOBAL_POSITION_INT` - same thing we're checking against in the autotests :-)

When do you think you might be able to test what you'd like to?

**Comment by yaapu** [comment]
@peterbarker tested protocol 4 with 1 or 2 rpm sensors, working fine, thanks for fixing this :-)

**Comment by tridge** [comment]
Please also change RPM_TYPE default for flightaxis to SITL
https://github.com/ardupilot/ardupilot/blob/master/libraries/SITL/SIM_FlightAxis.cpp#L82

**Pull request merged**
