### PR TITLE
AP_AHRS: fix custom rotation ToRad conversion

### PR DESCRIPTION
**Pull request by vierfuffzig**
this fixes https://github.com/ArduPilot/ardupilot/issues/12000

### CODE REVIEW

**Comment by vierfuffzig** [comment]
thanks @OXINARF , done

**Comment by tridge** [comment]
ping @jaxxzer 
given you added custom AHRS orientations can you comment on this? The docs say degrees, but it is implemented as radians. Are you actively using this now? Will this break existing setups?

**Comment by vierfuffzig** [comment]
this fix indeed would break existing setups using a custom rot, but imho chances it has actually been used are fairly limited, as users trying to set a custom rot will likely have found it not working as expected. that‘s why i thought fixing it would add more benefit than harm.

**Comment by vierfuffzig** [comment]
@jaxxzer as i understand it in your original patch https://github.com/ArduPilot/ardupilot/pull/7877 you initially used DEG_TO_RAD but changed that to euler to matrix upon review request.

**Comment by jaxxzer** [comment]
> @jaxxzer as i understand it in your original patch #7877 you initially used DEG_TO_RAD but changed that to euler to matrix upon review request.

I'm not sure what point you are trying to make. Your patch here reverts this to the original functionality in my patch, which was degrees. I used degrees for the parameter, because that's how most people think.

Somebody else changed it to radians between then and now.

**Comment by OXINARF** [comment]
> Somebody else changed it to radians between then and now.

@jaxxzer What @vierfuffzig was mentioning was that your initial proposed patch had a degrees to radians conversion. But, during the PR code review, it was pointed out that you had matrix calculations code that our Matrix class already had - in changing it, you lost the conversion to radians and nobody else noticed it either.

The link you pointed out shows exactly the same code we have in master and it also shows you are the author 😉

Anyway, important thing is: is anyone aware of this currently being used by anyone? This change would break their setup.

**Comment by tridge** [comment]
indeed, if this isn't being actively used by anyone in the sub community then I think we can fix it to use degrees.
@jaxxzer do you think it is being actively used? What level of pain would there be for existing users if we changed this?

**Comment by tridge** [comment]
discussed on dev call and decided to merge this

**Pull request merged**
