### PR TITLE
Remove safe PWM

### PR DESCRIPTION
**Pull request by IamPete1**
Follow up to https://github.com/ArduPilot/ardupilot/pull/18050 This removes the setting of safety PWM from rover, it is the last user so the functionality is then removed from the rest of the code.

Safe PWM should always be 0, if you want it to be PWM min then you should let that channel past `BRD_SAFTY_MASK`. We had numerous issues related to this on plane, although I don't think we have one for rover. People assume 'safe' means safe and that were not outputting to motor, currently you can change PWM trim and get motors to spin in safe mode.

Saves 64 bytes on the io-firmware

### CODE REVIEW

**Comment by khancyr** [comment]
It think that the only case we need this was the use of petrol engine, so if we got an alternative that is fine !

**Review by rmackay9 — APPROVED** [review]

**Comment by tridge** [comment]
needs testing with new IO fw loaded on a board with IOMCU

**Comment by IamPete1** [comment]
I have tested on a CubeOrange, all seems to work as expected. No errors in the log. Outputs work and are disabled/enabled correctly with the safety mask.

**Comment by tridge** [comment]
need to rebuild and test IO with new 10.2 compiler (apparently this was with 7.5)

**Comment by tridge** [comment]
need to test OVERRIDE_CHAN, or BRD_OPTIONS=0 and crash FMU using the lockup_autopilot command in mavproxy

**Comment by IamPete1** [comment]
All seems to work as expected. I did use the correct compiler version, must have checked WSL1 and not WSL2 on the EU call.

`/opt/gcc-arm-none-eabi-10-2020-q4-major/bin/arm-none-eabi-size`

There is no diff after a re-compile of the IO firmware. 

I tested master and then this using `OVERRIDE_CHAN` on plane. Outputs switch as expected, you can tell because the throttle is no longer suppressed in override.

**Pull request merged**
