### PR TITLE
AP_BLHeli: fix MASK and REMASK bitmask description

### PR DESCRIPTION
**Pull request by vierfuffzig**

### CODE REVIEW

**Comment by tridge** [comment]
This is deliberately done as a bitmask, and is meant to be used in the advanced parameter list, like this:
blh_mask

**Comment by tridge** [comment]
the real problem is that MP doesn't do bitmasks usefully in its full param list. Changing the @Values is no good as it doesn't allow you to select multiple at once. It creates a drop down list. We'd need 65535 entries in the @Values to allow for all of them

**Comment by vierfuffzig** [comment]
please excuse me being slow-witted on this. right now i'm probably causing more confusion than improvement. 
however, imho the change in BLH channel mapping as described in the referenced issue has the potential to harm users' hardware by unintentional output of a non-standard signal with extended range to a standard type servo.
that's why imho, in addition to the MP advanced param tab's bitmask option, a value-oriented parameter description in MP full list and wiki docs is desireable. arming_check bitmask for example uses both @Bitmask and @Values too, so maybe this is an option?

**Comment by rmackay9** [comment]
By the way, the latest MP will pop up a bit mask selector box if the use double clicks on the parameter from the full parameter list.

**Comment by vierfuffzig** [comment]
thanks @rmackay9 and @tridge , i accidentally found that selector box pop up just recently while setting another bitmask, that's a great addition. 
i guess it's just the BLH_MASK's mapping changing from from pre- to post nov 15th firmwares, coinciding with the BLH_AUTO function not always working as expected in plane-type single-motor setups, plus MP's full param list options handling that i'm still at odds with. 
subject to your assessment i'm completely ok to withdraw this PR if it doesn't add any value.

cheers, basti.

**Comment by tridge** [comment]
ok, thanks

**Pull request closed without merging**
