### PR TITLE
AC_PrecLand: Add buffer parameter and correlate timestamps, rebased, …

### LINKED ISSUE #6297: AC_PrecLand _inertial_history buffer should be set by parameter
#### Issue details
In AC_PrecLand, the _inertial_history buffer effectively determines the latency of the incoming landing coordinates to the IMU for attitude correction.   This is set to an integer multiple of the timing loop (400hz) and is fixed in AC_PrecLand.h at 8, which corresponds to 20ms.
`    AP_Buffer<inertial_data_frame_s,8>       _inertial_history;`

This figures was apparently derived from the latency of the IRLock system which has specific dedicated hardware for landing detection.  However, for more general use the 'Companion Computer' backend is used to send Mavlink messages through to AC_Precland.  The latency of these messages from the camera capture will vary widely, but will almost always be far higher than the preset 20ms.  This leads to incorrect IMU correction and dangerous movements of the craft.

The EKF estimator (the default) seems to be particularly sensitive to this, being largely unuseable and quite dangerous when using the Companion backend.

#### Version
3.5-rc6

#### Platform
[  ] All
[  ] AntennaTracker
[ x ] Copter
[  ] Plane
[  ] Rover

#### Airframe type
Quadcopter

#### Hardware type
Pixhawk

### PR DESCRIPTION
**Pull request by fnoop**
…fixes #6297 #5959

This adds a 'PLND_BUFFER' parameter that can be used to set the length of an inertial buffer within AC_PrecLand.  This was previously fixed at 20ms and fixed to use the last available inertial frame, so effectively locked the latency between the two systems (Flight Controller and Measurement Sensor) to 20ms, and appears to have been set to work with the IRLock system.  However, most visual systems using the companion backend will typically have latencies more in the 50-200ms range and so the attitude compensation is applied to long-lost inertial frames and causes dangerous behaviour.

The PLND_BUFFER now influences the length of this buffer and is set to 20ms by default, so will behave in the same way as before, but it can be setup up to 250ms (and the buffer is changed immediately if the parameter is changed), to allow slower/higher latency systems.

In addition, this commit also now honours the 'time_usec' field of LANDING_TARGET mavlink message, and extends AC_PrecLand  to consume this timestamp in a way that other backends can also be extended to use (_backend->get_los_timestamp()).  If the timestamp is set, it attempts to correlate the closest inertial frame to the sensor frame.  If it cannot correlate the frames (if the frame is out of bounds of the inertial buffer), the measurement is ignored.  If the timestamp is not set, it continues the previous behaviour of blindly using the oldest inertial frame.

In conjunction with the earlier TIMESYNC work, this should now allow AC_PrecLand to automatically adjust to latencies dynamically, if the backend provides a synchronised measurement timestamp.  vision_landing (https://github.com/fnoop/vision_landing) is such a system.

This is not a perfect finished system yet, by any means.  There are still numerous issues to address, but this gets us one (or two) steps closer.

A few notes:
 - Changes inertial buffer from the fixed-at-compile-time AP_Buffer to AP_HAL RingBuffer which can be changed on the fly, uses recent PR #6963 
 - Debug output is present, will remove in a subsequent commit
 - TIMESYNC/MAVlink mechanism is very sub-optimal, huge jitter and latency inherent.  Needs improving (PR to come)
 - The sending sensor (companion computer/camera) is still responsible for capturing a synchronised timestamp at the time of frame capture

### CODE REVIEW

**Comment by fnoop** [comment]
@rmackay9 @jschall @OXINARF  - If you guys have a few minutes to spare, could you please look at this PR?  I'm sure it will need some more work, but would be good to have some feedback so I can make whatever changes are necessary.  It would go along way to making precland more useable with a wide variety of companion computer/vision systems.

**Comment by rmackay9** [comment]
I totally agree this is an important PR.  I'm keen on it and so it's on my list!

**Comment by amilcarlucas** [comment]
I think there is something wrong in this branch .... 8000 lines of code over 130 commits...
I think a proper rebase on master is needed.

**Comment by fnoop** [comment]
Oh balls, I updated my master branch and then tried rebasing this branch from master.  Obviously I've done something wrong :(  Oh well, it's not going anywhere anyway so I'll just close it.

**Comment by OXINARF** [comment]
@fnoop Closing it doesn't help. I've started reviewing it, but I'm not very familiar with this library or the EKF in it, so it takes more time to look at it as I need to teach myself.

Unfortunately it looks like your commits have completely vanished from this PR - do you still have them locally? If you do, I can help you rebase. If not, I think the last version was https://github.com/ArduPilot/ardupilot/compare/master...OXINARF:review/7046, correct? In that case, re-open this PR and activate the option to let maintainers push to your branch and I'll push a rebased commit.

**Comment by fnoop** [comment]
@OXINARF Thanks for taking a look at it, unfortunately this is just all way above my head.  So sorry to waste your time.

**Comment by OXINARF** [comment]
@fnoop I think it was mostly you putting time into it and it's a shame to trash this work - something that has been wanted by many. But it's really up to you.

**Comment by rmackay9** [comment]
We want this change, it's still high on my list to review..

**Pull request closed without merging**
