### PR TITLE
waf: read directories list from directories_list files

### PR DESCRIPTION
**Pull request by ncarrier**
This simplifies using other build systems as it is the main piece of information they need to build both four vehicle types.

### CODE REVIEW

**Comment by OXINARF** [comment]
If this simplifies the work of others I have no objection for it, but I would prefer the name to be _libs_list_ instead of _directories_list_. But let's wait for @guludo's input before making any change.

**Comment by guludo** [comment]
I don't like that approach. My reasons:

 1. This might introduce eventual ambiguity as ap_stlib could be called from anywhere, even from the same wscript.
 2. This adds the overhead of needing an extra file just for just listing the ap libraries for a ap_stlib, which doesn't bring any benefit to the project itself.

> This simplifies using other build systems as it is the main piece of information they need to build both four vehicle types.

I'm not sure if that's totally true. For example, there are some compiler and linker flags that are required for a successful compilation.

Anyway, is there any issue on making the external build system call `waf` to build the libraries?

**Comment by ncarrier** [comment]
Hello,
Thank you for your comments.

> This might introduce eventual ambiguity as ap_stlib could be called from anywhere, even from the same wscript.

I'm not sure I understood this point, can you please explain what you mean ? If ap_stlib is called in multiple places, we can either read the list multiple times, or read it once in a common part and pass it at each ap_stlib call.

> This adds the overhead of needing an extra file just for just listing the ap libraries for a ap_stlib, which doesn't bring any benefit to the project itself.

It is not completely true, if one day, the APM project decides to change again it's build system, then the information will be there. And in general, separating data from logic isn't a bad thing IMO.

> For example, there are some compiler and linker flags that are required for a successful compilation.

Sure, but they are much less likely to change.

> Anyway, is there any issue on making the external build system call waf to build the libraries?

I see plenty:

- compiling directly is faster
- the use of submodules, in my integration of APM for Disco, I only need mavlink and ArduPilot
- the flags shall be handled by the top level build system, having two build systems complicates this

In the end, calling waf can be done in two manners :

- by integrating it properly as a new class of build module, which is a lot of works and involves a significant knowledge of waf
- by creating manually the build targets, which normally handled the build system and is a lot of work too and error prone


Regarding the naming of the files, libs_list is perfectly fine for me.

**Comment by lucasdemarchi** [comment]
Sorry, but I have to NACK this approach. It's not the proper way to integrate ardupilot.

The build system is not only responsible for handling what files are compiled. There include directories. There are defines that must be handled correctly. There are generated header files that must be generated correctly. For example: ap_config.h and mavlink headers. The fact that you don't generate ap_config.h correctly is the reasons hacks like https://github.com/ArduPilot/ardupilot/commit/f090e9b27ccc92bf7a4295ab90d4ca855d366760 are added to the codebase.

> compiling directly is faster

I challenge you to show the numbers. If it's faster it's just because you are missing steps or not being future-proof on detecting changes to the toolchain. I'd be very surprised to be proven wrong. Be my guest.

> the use of submodules, in my integration of APM for Disco, I only need mavlink and ArduPilot

Waf only uses the modules you need. So in this case you'd need only ardupilo, mavlink and waf itself.

> by integrating it properly as a new class of build module, which is a lot of works and involves a significant knowledge of waf
> by creating manually the build targets, which normally handled the build system and is a lot of work too and error prone

This is not true. The integration should be 2 lines only: waf configure to pass the board and waf build to pass the target. If it's more than that, there's something wrong with the build system. This is how integration in atom or yocto or builroot or pkgbuild or koji or whatever distro-creator should be done.

> the flags shall be handled by the top level build system, having two build systems complicates this

This is what you are doing actually, not us. You should delegate the build for our build system rather than forcing upstream to support external build systems. This is very fragile and will be an eternal source of bugs.

**Comment by lucasdemarchi** [comment]
2 examples here: https://gist.github.com/lucasdemarchi/fab8727828cd85c7501e64db9840f97b

One with PKGBUILD (for archlinux) and another a .bb, for OE/yocto.  Neither of them know anything about waf. One package it for desktop-like distros and the other for creating a complete rootfs.  Why does it need to be different in your case?  Don't get me wrong, I appreciate integrating Disco, but would be good to get it right, without increasing the build system maintenance even more.  We want to change the build system and still not cause any problems for you or anyone packaging ardupilot.

It'd be nice if you could reconsider how you are packaging it.

**Comment by lucasdemarchi** [comment]
I'm closing this since we discussed it at length on gitter.

**Pull request closed without merging**
