### PR TITLE
AP_Arming: Do not set check results each time.

### PR DESCRIPTION
**Pull request by muramura**
I put a check result each time.
It is possible with one statement.
Therefore,
1. Delete the check result variable
2. Immediately return the check result.

### CODE REVIEW

**Comment by peterbarker** [comment]
This patch wasn't a good one to merge IMO.

We *intentionally* ran all of those checks to inform the user of all of the problems they have.

I suggest we revert this commit.

**Comment by OXINARF** [comment]
This is a bitwise operation, not a logical AND, so if I'm not mistaken this will run all of them.

**Comment by peterbarker** [comment]
I think you're right, sorry.

I find the original less confusing :-)

**Comment by magicrub** [comment]
I agree, original is easier to read.

**Comment by OXINARF** [comment]
Interesting. The only thing I didn't like much about this was the & in the beginning of the line, I prefer it at the end but we don't have any rule for that so I let it go.
Why do you find the original more readable? It only misses a couple of assignments. I very much prefer readable code to performant code if the differences are negligible (like they are here) but I didn't think this would make a difference to anyone.

**Pull request merged**
