### PR TITLE
AP_KDECAN: map channel to motors directly

### PR DESCRIPTION
**Pull request by bugobliterator**
Fix issue which doesn't let KDECAN work with Plane Firmware

### CODE REVIEW

**Comment by magicrub** [comment]
Excellent, thank you @bugobliterator !!!! I'll make sure to test this.

**Comment by tridge** [comment]
we need to discuss how this will change existing setups. Should we make it a different can type (same code, select mapping scheme?)

**Comment by tridge** [comment]
I think we should change the enum value of Driver_Type_KDECAN to force people to reconfigure with this mapping change

**Comment by rmackay9** [comment]
I noticed while setting up the KDECAN ESCs that there is no option to set an ESC's number to "1" (using KDECAN's UI) so we need to check that with this change it is possible to setup a mapping to the autopilot's SERVO1 output.

**Comment by samuelctabor** [comment]
I've just tested this and found that - 
 - KDE ESC ID 2 appears to map to ArduPlane SERVO1. I haven't checked any other IDs yet
 -The mapping isn't what I expected. The ESC does not initialise (judging from the beeps) until throttle reaches a little below 50%, and then the motor starts at 50%. The graph of SERVO_OUTPUT_RAW.servo1_raw is normal i.e 50% input gives 1500 output.

**Comment by samuelctabor** [comment]
Vehicle code, no AP_Periph involved yet.

**Comment by samuelctabor** [comment]
See also https://github.com/ArduPilot/ardupilot/issues/16905

**Comment by rmackay9** [comment]
I'll close this in favour of PR https://github.com/ArduPilot/ardupilot/pull/17149 but I've given @bugobliterator co-author on the commit that is very similar to what is in this PR.  Txs!

**Pull request closed without merging**
