### PR TITLE
Copter 3.6

### PR DESCRIPTION
**Pull request by 2357531789**
Hello, I am debugging the yaw parameters of my multi-axis UAV. I found "MOT_YAW_HEADROOM" and tried to adjust it, but I found that it was ineffective. No response was gained through any changes to it. Do you understand why?

My six-axis is a big fellow with a wheelbase of 1600mm and 29-inch propeller. It can't satisfy me in Yaw performance. So I found this parameter. It will produce angle deviation under cross-wind interference when hovering. It's about 5-10 degrees. I've tried to debug pid, but the problem still exists!

Program version 3.6.4, the controller is pixhack v3, the power is 6s, 29 inches and 8308 motor vk175, in the case of hanging a small camera, it can fly stably for about 85 minutes.

### CODE REVIEW

**Comment by rmackay9** [comment]
This looks like a mistake. As Pierre says this should probably be raised as an issue instead of a PR.

**Comment by 2357531789** [comment]
> 这看起来像是一个错误。正如皮埃尔所说，这应该是一个问题，而不是公关。

I'd like to ask when the 3.7 stable firmware will be completed.

**Comment by rmackay9** [comment]
@2357531789, we haven't set a date yet but I think it will still be a couple of months before we start beta testing.

**Comment by 2357531789** [comment]
> @ 2357531789，我们还没有确定日期，但我认为在开始beta测试之前还需要几个月的时间。

@rmackay9 I want to participate in the test, but I don't know what to test, because I don't know what to change. Besides, I don't know how to use this forum very well. I just came here and communicated through translation. At present, I have found many problems, but I don't know how to feedback.

**Comment by rmackay9** [comment]
Hi @2357531789,

The best way to report problems is [here in the Copter-3.6 forums](https://discuss.ardupilot.org/c/arducopter/copter-36).  Once problems are confirmed to be software bugs/issues we raise them in [the issues list](https://github.com/ArduPilot/ardupilot/issues).

**Pull request closed without merging**
