### PR TITLE
Waf: Update waf submodule to Ardupilot/waf master.

### PR DESCRIPTION
**Pull request by kwikius**
Github/Ardupilot/waf repo has been updated, but Ardupilot is still using previous submodule version. For the mods see https://github.com/ArduPilot/ardupilot/issues/25923.

### CODE REVIEW

**Comment by kwikius** [comment]
> Is there a reason to update (bugfix, new feature), or is this just upkeep?

bugfix.

**Comment by Ryanf55** [comment]
> Am still having this issue when I use a script to run sitl
> 
> ```
> #!/usr/bin/env bash
> 
> cd $HOME/cpp/projects/ardupilot/Rover
> 
> python3 ../Tools/autotest/sim_vehicle.py -D -v Rover\
>  --console --map rover --model JSON\
>  --custom-location='51.65942820951469,-1.9304530221089151,18.96,0'\
>  --add-param-file=$HOME/GazeboSim/SITL_Models/Gazebo/config/catamaran.param\
>  -C --load-module=joystick
> ```
> 
> outputs
> 
> ```
> SIM_VEHICLE: Start
> SIM_VEHICLE: Killing tasks
> SIM_VEHICLE: Starting up at [51.65942820951469, -1.9304530221089151, 18.96, 0.0]
> SIM_VEHICLE: WAF build
> SIM_VEHICLE: Configure waf
> SIM_VEHICLE: "/home/andy/cpp/projects/ardupilot/modules/waf/waf-light" "configure" "--board" "sitl" "--debug"
> /usr/bin/env: ‘python’: No such file or directory
> SIM_VEHICLE: (Configure waf) exited with code 32512
> SIM_VEHICLE: Killing tasks
> ```
> 
> So then I have to go into modules/waf and do
> 
> ```
> >$ git pull origin master
> 
> From https://github.com/ArduPilot/waf
>  * branch              master     -> FETCH_HEAD
> Updating 1b1625b8..4a088504
> Fast-forward
>  waf-light | 2 +-
>  1 file changed, 1 insertion(+), 1 deletion(-)
> ```
> 
> After that running the script works ok

Did you ever do a `git submodule update --init --recursive`?

**Comment by kwikius** [comment]
> Did you ever do a `git submodule update --init --recursive`?

OK. I have now done a fresh clone of ardupilot 

>$ git clone https://github.com/ArduPilot/ardupilot.git
Cloning into 'ardupilot'...
....
...
...
remote: Total 447772 (delta 523), reused 674 (delta 343), pack-reused 446771
Receiving objects: 100% (447772/447772), 311.44 MiB | 2.92 MiB/s, done.
Resolving deltas: 100% (331736/331736), done.
Updating files: 100% (6013/6013), done.

>$ git submodule update --init --recursive
...
...
...
Submodule path 'modules/mavlink/pymavlink': checked out '4d8c4ff274d41b9bc8da1a411cb172d39786e46b'
Submodule path 'modules/waf': checked out '1b1625b8e7da6e1307d73335cb995fa8813d5950'

\#execute script
>$ cd ../
>$ ./ap-cat.sh 
Starting Ardupilot Gazebo Catamaran simulation
SIM_VEHICLE: Start
SIM_VEHICLE: Killing tasks
SIM_VEHICLE: Starting up at [51.566151, -4.034345, 10.0, -135.0]
SIM_VEHICLE: WAF build
SIM_VEHICLE: Configure waf
SIM_VEHICLE: "/home/andy/cpp/projects/ap_temp/ardupilot/modules/waf/waf-light" "configure" "--board" "sitl" "--debug"
/usr/bin/env: ‘python’: No such file or directory
SIM_VEHICLE: (Configure waf) exited with code 32512
SIM_VEHICLE: Killing tasks
\# -------------------
\# update waf to master...
>$ cd ardupilot/modules/waf
>$  git pull origin  master
From https://github.com/ArduPilot/waf
 * branch              master     -> FETCH_HEAD
Updating 1b1625b8..4a088504
Fast-forward
 waf-light | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
\# execute script
>$ cd ../../../
>$ ./ap-cat.sh
Starting Ardupilot Gazebo Catamaran simulation
SIM_VEHICLE: Start
SIM_VEHICLE: Killing tasks
SIM_VEHICLE: Starting up at [51.566151, -4.034345, 10.0, -135.0]
SIM_VEHICLE: WAF build
SIM_VEHICLE: Configure waf
SIM_VEHICLE: "/home/andy/cpp/projects/ap_temp/ardupilot/modules/waf/waf-light" "configure" "--board" "sitl" "--debug"
Setting top to                           : /home/andy/cpp/projects/ap_temp/ardupilot 
Setting out to                           : /home/andy/cpp/projects/ap_temp/ardupilot/build 
Autoconfiguration                        : enabled 
....
...
...
\# so now building fine...

So latest  version of github/Ardupilot/waf  is not in github/Ardupilotardupilot waf submodule, hence this PR

also look in ardupilot/modules/waf/waf-light  

before modules/waf pull from master shebang is 

\#!/usr/bin/env python

\#script fails

\#after update

\#!/usr/bin/env python3

\#script succeeds

**Comment by kwikius** [comment]
> This is a user setup error, can you please create a post on ardupilot discuss, link it here, and I will answer there? It's unrelated to this issue.

Posted at https://discuss.ardupilot.org/t/waf-update-waf-submodule-to-ardupilot-waf-master-user-setup-errror/113544

**Comment by kwikius** [comment]
closing this as fixed here https://discuss.ardupilot.org/t/waf-update-waf-submodule-to-ardupilot-waf-master-user-setup-errror/113544

**Pull request closed without merging**
