### PR TITLE
Tools: environment_install: add xterm to Cygwin packages

### PR DESCRIPTION
**Pull request by IamPete1**
This adds xtrem, allowing the sitl 'window thingy' to show once you have set your display variable

### CODE REVIEW

**Comment by stephendade** [comment]
Ahh, nice. Once I've got a X server setup I can get the Ardupilot console.

Only issue is that when I ctrl+c in sim_vehicle, the arduplane terminal doesn't close or exit.

Doing a ``psgrep -ea`` shows that whilst the arduplane executable closes, the xterm does not.

Not a show stopper here, but would be good to have sim_vehicle better handle closing processes in cygwin.

**Comment by peterbarker** [comment]
Merged, thanks!

**Comment by stephendade** [comment]
@IamPete1: Could you also add this to the Cywin install instructions in the wiki?

**Comment by IamPete1** [comment]
@stephendade sure, I actually miss the window staying open now I am using WSL, it was useful sometimes

**Pull request merged**
