### PR TITLE
Add a fake job to allow your build to "fast_finish"

### PR DESCRIPTION
**Pull request by cotsog**

### CODE REVIEW

**Comment by magicrub** [comment]
How does this work? In what circumstances does it fail earlier?
Also, you have as many commits as you do lines of code changes. Please squash to a single commit :)

**Comment by OXINARF** [comment]
@magicrub This come in as a result of an e-mail I sent to Travis support that fast finish wasn't working. Fast finish allows the entire build to show as failed when the one job fails, without having to wait for all jobs to fail. Unfortunately Travis only has this working when you have a job that is allowed to fail.

**Comment by cotsog** [comment]
@magicrub: you can have more details about our `fast_finish:` feature [here](https://docs.travis-ci.com/user/customizing-the-build#Fast-Finishing). As @OXINARF mentioned, it only works if you have [the `allow_failure:` key](https://docs.travis-ci.com/user/customizing-the-build#Rows-that-are-Allowed-to-Fail) as well.

I'll let you decide if you want this workaround or not. I believe you should be able to squash my commits when merging the PR.

Hope this helps.

**Comment by hiro2233** [comment]
@cotsog the are many people pushing PR in the master like me, but i think this is a good practice that the code grow up seriously following APM policy with merging code. Linux hasn't grown up if there that were by Linus, and obviously the people that agree their poilcy.

**Comment by magicrub** [comment]
What's the status on this?

**Comment by OXINARF** [comment]
@magicrub I haven't really decided what would be better but I'm more inclined that we are better without this workaround (hence I haven't applied it), so I'm closing this.

**Pull request closed without merging**
