### PR TITLE
Add SDMODELH7V1

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by andyp1per** [comment]
@peterbarker looks good to me, but I think you are going to have to do a configure_all and compare to check nothing got broken by the hwdef changes. Feels like that change might be better in a separate PR?

**Comment by peterbarker** [comment]
> @peterbarker looks good to me, but I think you are going to have to do a configure_all and compare to check nothing got broken by the hwdef changes. Feels like that change might be better in a separate PR?

It is already a separate PR :-)  #24174

**Comment by Hwurzburg** [comment]
README.md? or is this a private autopilot?

**Comment by peterbarker** [comment]
> @peterbarker looks good to me, but I think you are going to have to do a configure_all and compare to check nothing got broken by the hwdef changes. Feels like that change might be better in a separate PR?

Rebased on that other PR which has been merged.

**Review by andyp1per — APPROVED** [review]

**Pull request merged**
