### PR TITLE
Enable Gopro controls for Solo gimbal in mavlink communication

### PR DESCRIPTION
**Pull request by mtbsteve**
@davidbuzz @rmackay9 here is another attempt to make the Gopro controls work for a Solo in Arducopter Master. It should work for CubeSolo, CubeGreen and fmuv3 boards when HAL_SOLO_GIMBAL_ENABLED is met and when a Gopro heartbeat is broadcasted. I tested it successfully with AC 4.3.3-RC1 on a Solo with a CubeSolo board and a non-Solo copter with CubeBlack installed.

### CODE REVIEW

**Comment by rmackay9** [comment]
Hi, sorry I didn't see this.  This looks like a decent solution.  @peterbarker what do you think?

**Comment by davidbuzz** [comment]
if the following tests all pass, im in favour of it...
1 - the solo transmitter detects the gimbal ,and doesn't report any error/s
2 - the "paddle" on the back-left-underneath of the solo transmitter that is used to move the gimbal up/down , actually moves the gimbal up and down
3 - when missionplanner is connected to the wifi access point and setup to recieve udp mavlink packets, it recieves packet/s from both gimbal and drone, and can read/set paraams etc from the drone as usual.

**Comment by proficnc** [comment]
Was this supposed to be closed?

**Comment by mtbsteve** [comment]
@proficnc No, I had an issue with my PC which caused me to delete and reinstall the repo what somehow in turn closed the PR. 
So yes, the PR is still alive, and I would appreciate very much if you guys can incorporate the fix into master. The PR re-enables the Gopro communication between Camera/Gimbal, the controller and the GCS.

**Pull request closed without merging**
