### PR TITLE
AP_Compass: don't push in if set as extra devid

### PR DESCRIPTION
**Pull request by IamPete1**
This should fix a issue were low priority compasses push in if the higher priority compasses have not shown up. This can be the case with three DroneCAN compasses. If they are not powered at boot currently the internal can jump from extra to primary. This stops that. 

I still need to find some more CAN compasses to test this out IRL.

### CODE REVIEW

**Comment by IamPete1** [comment]
I do wonder if we should remove the ability to automatically replace compasses all together, the removing missing button in mission planner is quite easy and magically changing stuff round can be confusing/unexpected for the user.

**Comment by bugobliterator** [comment]
> I do wonder if we should remove the ability to automatically replace compasses all together, the removing missing button in mission planner is quite easy and magically changing stuff round can be confusing/unexpected for the user.

I agree, but this replacement mechanism is kept to be in line with legacy behavior which was that you could replace compasses in the field without config changes. 

UNREG_COMPASS_ID doesn't live through reboot, as you can see its just set not set and save. So I don't think this code would behave as expected.

General assumption in AP_Compass is that there are no more than 3 compasses connected/enabled at once. The proper way to avoid situation like above is to have internal compass disabled entirely, to that end maybe adding an option or param telling AP_Compass to disable all internal compasses entirely would be a better path.

**Review by bugobliterator — CHANGES_REQUESTED** [review]
I agree, but this replacement mechanism is kept to be in line with legacy behavior which was that you could replace compasses in the field without config changes.

UNREG_COMPASS_ID doesn't live through reboot, as you can see its just set not set and save. So I don't think this code willbehave as expected.

General assumption in AP_Compass is that there are no more than 3 compasses connected/enabled at once. The proper way to avoid situation like above is to have internal compass disabled entirely, to that end maybe adding an option or param telling AP_Compass to disable all internal compasses entirely would be a better path.

**Comment by pompecukor** [comment]
I am very happy with having option to disable internal entirely.
But also automatic reordering, legacy or not, does not make sense to me, even with field installation. You will have to calibrate it anyway, so whIch make sense more. In those extremely rear occasions that someone would change compass on the field they might as well press a few configuration buttons.
The thing is, not just for boot time, but even if there is a failure (electronic) and novice end user won't know and the System reorders internally, then it can lead to catastrophic flight and that within any warming.

**Comment by IamPete1** [comment]
I tracked down the issue further and have opened https://github.com/ArduPilot/ardupilot/pull/23706, @bugobliterator you were right this fix is not correct.

**Pull request closed without merging**
