### PR TITLE
Add some serial rangefinder simulators

### PR DESCRIPTION
**Pull request by peterbarker**
Three of the Benewake Serial protocols.
Lanbao
LightWareSerial

The simplest of the simulators simply fill in      `virtual uint32_t packet_for_alt(uint16_t alt_cm, uint8_t *buffer, uint8_t buflen) = 0;`

### CODE REVIEW

**Comment by khancyr** [comment]
Looks good but I wonder if we won't need some subdirectory on SITL/ as if we start to implement more sensor it will became unmaintainable .

**Comment by peterbarker** [comment]
Added LeddarOne and BLping

**Comment by peterbarker** [comment]
> Shouldn't you convert the alt ?

To what?

**Comment by khancyr** [comment]
haa my bad ! That isn't selectable ... so now worries !

**Comment by peterbarker** [comment]
Added uLanding rangefinders.

**Comment by peterbarker** [comment]
Added wasp rangefinder simulator, including settings (none of which we act on ATM)

**Comment by peterbarker** [comment]
Added NMEA rangefinder simulator.

**Pull request merged**
