### PR TITLE
Rover: add NAV_DELAY support

### PR DESCRIPTION
**Pull request by magicrub**
Rover: add NAV_DELAY support. For boats it will try to loiter, else it will stop (hold).

### CODE REVIEW

**Comment by rmackay9** [comment]
it looks pretty good.  the only change I might suggest is to put _ms on the end of the times and delays that are in milliseconds.  This may not have been done for Copter (I'm not sure) because the code is a bit older but more recently we've been appending the units if it's not SI units.

It's been tested to work in SITL of course?

**Comment by magicrub** [comment]
yes, has been tested. I only tested the seconds delay but it's a copy/paste from copter

**Comment by magicrub** [comment]
Good idea. I renamed variables to append _ms. I also renamed them on Sub and Copter and also changed the variables from int32 to uint32 (which I already did on rover) which I think was a bug? All the maths are unsigned.

**Comment by rmackay9** [comment]
I've tested it and it mostly works but I don't think the verify_nav_delay should be responsible for stopping the vehicle or switching it to loiter mode.

The problem is that for non-boats, this leaves Auto's _submode in whatever it's previous state was and the vehicle may or may not actually stop.  I reproduced the vehicle not stopping by doing this:

- created a mission with 4 commands
   - wp1
   - rtl
   - nav_delay of 10 sec
   - wp2
- switched the vehicle to auto, let it drive to wp1 and then start rtling
- "wp set 3" to move the mission command to command 3 (nav-delay), the vehicle kept driving towards home for 10 seconds and then began driving towards wp2

**Comment by magicrub** [comment]
@rmackay9  force pushed with these changes:
- removed copter and sub changes (moved to PR https://github.com/ArduPilot/ardupilot/pull/12008)
- rebased onto master
- during a rover nav_delay the _submode is changed to Auto_HeadingAndSpeed
- upon finishing the delay, it resumes previous sub_mode (not sure if this is necessary)

**Comment by rmackay9** [comment]
If it were me I probably would have created a new stop submode in Auto because the heading and speed control is different.  For example I think a skid-steering vehicle could twitch back and forth a bit as it's heading changes.

By the way, in the comments it mentions that boats will Loiter but I didn't immediately see how that would happen.

**Comment by magicrub** [comment]
https://github.com/ArduPilot/ardupilot/pull/11999/files#diff-88e177e479c9ae77a29fb64a85ec3da0L74

**Comment by rmackay9** [comment]
I'm going to close this PR in favour of the new PR but we can of course reopen this one if necessary

**Pull request closed without merging**
