### PR TITLE
Copter: SF40c driver and AP_Proximity/AC_Proximity integration

### PR DESCRIPTION
**Pull request by rmackay9**
This PR adds support for the Lightware SF40c 360 degree range finder including a simple (GPS based) object avoidance by re-using the AC_Avoidance library (which is also used by the polygon fence).

I've marked this as a Work-in-progress mostly because it hasn't been test flown yet.

Other various bits of information:
- The datasheet for the range finder can be found here: http://www.lightware.co.za/shop/en/scanning-and-obstacle-detection/45-sf40c-100-m.html
- This set of commits mostly uses the sensor's "Search Light" feature to find the closest object within 8 sectors (each sector is 45degrees with the 0th sector being straight forward of the copter).  It also reads the sensor's status register (but doesn't do anything with it) and it sets the motor speed to 4.5hz (i.e. it does 4.5 full rotations per second).
- the request/reply communications with the sensor are pretty straight forward at the moment, every time the AP_Proximity::update function is called (which happens at 10hz) it asks for the closest object in the next sector.  On the next iteration it will start looking for a reply and parse it and stick the result into a buffer.
- AC_Avoidance then basically accesses the appropriate buffer for the direction the vehicle is flying in and shortens the vector so that the vehicle doesn't hit anything.
- I'm seeing 5ms ~ 10ms delay for the sensor to reply to a request.  With 8 sectors we're achieving about a 10hz update rate which is OK because that's twice the sensor's underlying update rate.

### CODE REVIEW

**Comment by magicrub** [comment]
Stop adding features and get 3.4 released! :) there's always 3.4.1....

**Comment by R-Lefebvre** [comment]
Or 3.5...  Our tertiary rev level is typically only used for bug fixes.  New features go into secondary rev levels.

**Comment by rmackay9** [comment]
Yes, this is not intended for Copter-3.4.

**Comment by rmackay9** [comment]
Closing because I've created a new PR with various bug fixes found during testing.

**Pull request closed without merging**
