### PR TITLE
AP_HAL_ChibiOS: add support for NucleoH755 board

### PR DESCRIPTION
**Pull request by radiohound**
This addition allows for cheap testing of a STM32H755 (dual core). This borrows the setup file STM32H757xx.py, as there are almost no changes between the chips. CRSF in and out, gps, ICM20948, BMP388, servo output, settings saving to on board flash are working.

### CODE REVIEW

**Comment by radiohound** [comment]
Virtual testing has been done with sim-on-hardware #20339 with many virt flights. One flight of almost an hour and a half, and many shorter virt flights. 

I do get a WDG: error with all zeros on some virt flights. This looks to be an issue on some H7  hardware that is currently being looked into. 

I don't have a SD card hooked up yet, but plan to, so I can get more debug info.

**Comment by tridge** [comment]
> I do get a WDG: error with all zeros on some virt flights. This looks to be an issue on some H7 hardware with on flash storage, that is currently being looked into.

please test if this is fixed by rebasing on master, it should be

**Comment by tridge** [comment]
please add "AUTOBUILD_TARGETS None" as per this PR:
https://github.com/ArduPilot/ardupilot/pull/20463
we don't need to autobuild this, instead users can build themselves or on custom.ardupilot.org
thanks!

**Comment by khancyr** [comment]
@radiohound hello, you need to perform a rebase on master branch to get rid of the merge commit. See some help here : https://ardupilot.org/dev/docs/git-interactive-rebase.html . Once you rebase we should be able to merge your PR !

**Comment by radiohound** [comment]
> > I do get a WDG: error with all zeros on some virt flights. This looks to be an issue on some H7 hardware with on flash storage, that is currently being looked into.
> 
> please test if this is fixed by rebasing on master, it should be

Yes, the WDG error seems to be fixed, Thank you!

**Comment by radiohound** [comment]
> @radiohound hello, you need to perform a rebase on master branch to get rid of the merge commit. See some help here : https://ardupilot.org/dev/docs/git-interactive-rebase.html . Once you rebase we should be able to merge your PR !

Thanks for your help khancyr

**Comment by tridge** [comment]
squashed the two commits

**Pull request merged**
