### PR TITLE
EKF changes to enable rover operation without a magnetometer

### PR DESCRIPTION
**Pull request by priseborough**
This is work in progress to address the issuer raised here: https://discuss.ardupilot.org/t/rover-without-magnetic-compass. I am still working through the Rover code to understand how the ahrs fly forward attribute can be better set.

Thee changes should be acgive when _ahrs->get_vehicle_class() == AHRS_VEHICLE_GROUND and _ahrs->get_compass()->use_for_yaw for the selected sensorinstance  returns false.

### CODE REVIEW

**Comment by priseborough** [comment]
To work best, the body frame origin should be over the non steering axle if the vehicle uses steering wheels or at the centroid of the wheelbase if it is skid steer. This can be accomplished by setting the IMU and GPS position offsets consistent with that definition.

**Comment by jmachuca77** [comment]
I hope they don’t steal too many things ;)... rober... rover... ok, ok... bad joke

**Comment by priseborough** [comment]
Looks like I mis-spelt robber, should have used two b's. It's hard to steal stuff when you keep needing to look at your compass.

**Comment by priseborough** [comment]
The problem arises when the river moves in reverse with a rc input for channel 3 of less than 1500. When the stick is released back to centre, the  fly forward flag is being set before the vehicle stops which causes the incorrect heading to be set.

We need better fly forward logic. Can we use motor feedback from the ESC to determine if the vehicle is moving forward?

**Comment by priseborough** [comment]
The problem is caused here: https://github.com/ArduPilot/ardupilot/blob/master/APMrover2/APMrover2.cpp#L157

As soon as the reverse throttle is released, the vehicle is still moving backwards, but the fly forward goes immediately true. We need a way of detecting that the vehicle has stopped before in_reverse is allowed to go false. A simple time delay might be sufficient.

**Comment by rmackay9** [comment]
@priseborough, thanks for this.

I can fix this issue I think by only switching into reverse once the vehicle has transitioned from forward to reverse.  Do you think we need to fix this in_reverse flag issue before this PR goes into master?

**Comment by priseborough** [comment]
I think we do. Otherwise someone starting in reverse without a magnetomer will have a heading that is 180 degrees out.

**Comment by rmackay9** [comment]
@esaattia, not merged yet I'm afraid.  I'm working on it though.

**Comment by mikerob** [comment]
This looks like functionality that could complement (or be complemented by) the ability to use two DGNSS sources to get heading by placing one at the front and one at the back of the vehicle.

This - https://github.com/ArduPilot/ardupilot/issues/3934 - talked about it for copter, but it should be easier on Rovers and Planes to get the baseline distance for a decent heading.

I think Randy or Grant were working on a PR to enable a commercial GPS module that did this externally (it incorporated to receivers and spat out the heading), I just can't find it.

**Comment by rmackay9** [comment]
I think [this PR from me to improve Rover's reversing behaviour](https://github.com/ArduPilot/ardupilot/pull/8312) will make things better in terms of correctly telling the AHRS when the vehicle is moving forwards.  It's not perfect, but the amount of time the vehicle code incorrectly tells the EKF it's moving forward when it's actually reversing is much less I think.

**Comment by karthikdesai** [comment]
*pings* :D

**Comment by priseborough** [comment]
@mikerob , @rmackay9, @gmorph This was the branch with the prototype changes to support use of RTK GPS units that output antenna yaw angle (not to be confused with ground course)

https://github.com/priseborough/ardupilot/tree/gpsYawSensor-wip

**Comment by priseborough** [comment]
I guess that would work. Do you have hardware that could be used to test it?

**Comment by rstager** [comment]
@priseborough I have a non-skid rover that I would like to test these changes on.  Any words of advice? Do things seem to be working in the field?

**Comment by danielwidmann** [comment]
I quickly tried these changes in the SITL and they don't seem to work with `COMAPSS_USE` set to 0 in combination with EKF3.

I think the reason is that is the logic in `checkAttitudeAlignmentStatus()` differs between EKF2 and EKF3. On the EKF3, `gpsYawResetRequest` is never getting set. @priseborough do you know if there is a reason for this difference?
https://github.com/ArduPilot/ardupilot/blob/820f9bd2606a861027f066919e006b50adea00c1/libraries/AP_NavEKF3/AP_NavEKF3_Control.cpp#L395-L398 
https://github.com/ArduPilot/ardupilot/blob/820f9bd2606a861027f066919e006b50adea00c1/libraries/AP_NavEKF2/AP_NavEKF2_Control.cpp#L353-L362

On top of that there seems to be a problem with the gyro bias estimation. Without a compass, the gyro bias covariance takes a long time to reduce (This makes sense as there probably is no other measurement that could estimate the gyro drift). Ardupilot will use DCM instead of the EKF because `delAngBiasLearned` and as a result `readyToUseGPS()` is not getting set.

**Comment by davidbuzz** [comment]
labeled as WIP, so can't be merged, but no movement in years, proposing to close it, or maybe get some other movement on it.

**Comment by rmackay9** [comment]
I agree, we've got GSF and GPS-for-yaw now which this is probably the first steps towards.

**Comment by davidbuzz** [comment]
randy agreed this is essentially superceeded now.

**Pull request closed without merging**
