### PR TITLE
AP_OpticalFlow: add UPFlow serial driver

### PR DESCRIPTION
**Pull request by auturgy**
Closes https://github.com/ArduPilot/ardupilot/issues/11328
Basically a duplicate of the CXOF driver, modified for the different packet structure/order
It builds, but that is the limit of testing.  Needs testing on hardware.

### CODE REVIEW

**Comment by auturgy** [comment]
overflows MatekF405-wing by 20 bytes (1Mb flash).  Suggestions?

**Comment by bys1123** [comment]
image
image
Data Format Reference for other developers.

**Comment by rmackay9** [comment]
@auturgy, the easiest thing to try and do is move some feature or flight mode into HAL_MINIMIZE_FEATURES.

- BUTTON_ENABLED is the only one that stands out to me (see Copter's config.h)

I think the next step is to look for rarely used drivers.  Some ideas:

-  AP_Proximity's SF40C_v09 driver.
- AP_RobotisServos are very rarely used

Maybe there are some compass or imu drivers that we could get rid of.

**Comment by auturgy** [comment]
Ok. I’ll have a chat to @peterbarker and see what we come up with.

**Comment by andyp1per** [comment]
MatekF405-wing deosn't have HAL_MINIMIZE_FEATURES switched on - I think it should as I keep tripping over flash limits on this board.

**Comment by auturgy** [comment]
Yeah: massive scope creep, so I’ll address it separately, but I think I’ll do an audit of minimise to see what we can shove behind it en masse, to push this problem as far down field as possible

**Comment by andyp1per** [comment]
I actually think we have the cut wrong. We have used it to address the old Pixhawk limitation in a certain class of copter but we also run into it on these single boards which are put on a very different class of copter. I suspect there ought to be two definitions based on the different kind of targets.

**Comment by auturgy** [comment]
I sort of agree - but the old errata on Pixhawk is such a legacy issue I think I’d rather ignore it moving forward :)
One issue is that those old boards (I still have one for the bench) actually have more constrainted flash, as they need to carry the iomcu firmware within the main flash space.
As above, I’ll look at the flash problem separately and see what I can come up with.

**Comment by andyp1per** [comment]
Do we know why the MatekF405-wing is so much worse than some of the other simple boards?

**Comment by auturgy** [comment]
I don’t think it is really, it’s just that it’s the representative F405 target in that autotest/CI.
The F405Wing does have basically every possible pin broken out, so is the worst case for that family of target.

Regards,

James

**Comment by FLYBYME** [comment]
What Can I do to help get this merged?

**Comment by rmackay9** [comment]
I didn't notice this PR until just now but in any case, we merged an alternative PR here: https://github.com/ArduPilot/ardupilot/pull/16883.  The two drivers are very similar.  sorry and thanks anyway!

**Pull request closed without merging**
