### PR TITLE
Add Sub to autotest suite

### PR DESCRIPTION
**Pull request by jaxxzer**

### CODE REVIEW

**Comment by jaxxzer** [comment]
I've tested this incrementally as I went. I'm running it from scratch now to verify after cleaning up. Should take a few hours to get the results. Please let me know if I am missing something, we would really like to get our binaries on firmware.ardupilot.org so that we can make them available through GCS.

**Comment by OXINARF** [comment]
Great to see this Jacob! I'll take a look, but I'll wait for @tridge or @peterbarker review since they have more knowledge about these scripts than me.

**Comment by jaxxzer** [comment]
Here is an output log of autotest.py along with a manifest produced. The binaries were already built when this was run.
[autotest-results.tar.gz](https://github.com/ArduPilot/ardupilot/files/800874/autotest-results.tar.gz)

**Comment by jaxxzer** [comment]
ardusub-test tlog

**Pull request merged**
