### PR TITLE
AP_DDS: publish relative true airspeed to /ap/airspeed

### PR DESCRIPTION
**Pull request by tizianofiorenzani**
- Publish the true airspeed as a 3D vector in body frame to the topic `/ap/airspeed` of type `geometry_msgs/msg/Vector3Stamped`.
- Topic is published only if airspeed is available.
- Code has been copied from `GCS_Mavlink`.

Issue: https://github.com/ArduPilot/ardupilot/issues/28300

**Test**

- `colcon build --packages-up-to ardupilot_sitl`
- Launch the sitl with Plane and takeoff.
- Echo the topic with `ros2 topic echo /ap/airspeed`

image

### CODE REVIEW

**Comment by tizianofiorenzani** [comment]
@Ryanf55: I left this topic published as Vector3: should we use the Stamped version instead?

**Comment by Ryanf55** [comment]
> @Ryanf55: I left this topic published as Vector3: should we use the Stamped version instead?

Yea, that's a good idea to have a timestamp.

**Comment by tizianofiorenzani** [comment]
@Ryanf55 Updated, tested and history cleaned.

**Review by Ryanf55 — APPROVED** [review]

**Comment by tridge** [comment]
needs rebase

**Comment by Ryanf55** [comment]
After rebase, check behavior in SITL, or add an automated test.

**Comment by tizianofiorenzani** [comment]
Rebased and tested in SITL:

**Copter**

image image

**Plane**

image 
image

**Comment by Ryanf55** [comment]
Looks good. Once CI passes, a maintainer will merge.

**Pull request merged**
