### PR TITLE
AP_RPM: Allow more instances

### PR DESCRIPTION
**Pull request by magicrub**
Allow AP_RPM instances RPM_MAX_INSTANCES up to 9

### CODE REVIEW

**Comment by IamPete1** [comment]
We really should move to instance logging.

**Comment by magicrub** [comment]
> We really should move to instance logging.

What do you mean?

**Comment by IamPete1** [comment]
> What do you mean?

We currently log the first two instances in a single message, we should move to a log with a instance number and also log health. 

https://github.com/ArduPilot/ardupilot/blob/baa6bc0e2bddfa8e4f8b7c4489c859e035400f73/libraries/AP_RPM/AP_RPM.cpp#L306-L311

Currently this adds the new inertances, but there not logged and not sent back over MAVLink, so there fairly pointless.

**Comment by magicrub** [comment]
@IamPete1 oh, right. Of course. Well, they're not useless if they're feeding other libraries. I'm not sure if I should adding the logging in this PR or a follow-up. What do you think? It will obviously require some refactoring and such which is quasi-out-of-scope. I'm happy to make follow-up PRs for it. Less excited about rolling it into this one

**Comment by magicrub** [comment]
I initially had a need for this on a periph but now 2 instances are OK. So, other than that no else has asked for this to my knowledge so I'm ok closing it. However, it's still potentially useful for future stuff and follows the pattern of other libraries. Just need to figure out the logging bit of it but in the case of a periph then the usefulness of implementing logging is questionable anyway.

I'll tag for devcall to get a thumbs up/down on if it's worth perusing as-is and/or with logging changes in this/future PR.

**Comment by magicrub** [comment]
the periph use-case I have in mind was a single device/hub that handled 4 of CAN -> PWM_ESCs channels with each having an RPM feedback populating an ESC_Telem feedback message (could also populate voltage/current and temperatures as well)

**Comment by IamPete1** [comment]
I have had to add extra RPM instances in the past, I think adding some more is worthwhile, 9 instances might be a bit much, but two additional instances would be useful.

**Review by tridge — CHANGES_REQUESTED** [review]
need to make RPM message an instance with RPM[0].rpm RPM[1].rpm etc

**Comment by rmackay9** [comment]
Let's make it 4 instances.. that should be enough.

**Comment by magicrub** [comment]
Changed max to 4 instances and updated logger to be instance basec

**Comment by rmackay9** [comment]
This looks OK to me.  It's been tested of course including testing that the logs appear correctly for multiple instances?

**Comment by magicrub** [comment]
> This looks OK to me. It's been tested of course including testing that the logs appear correctly for multiple instances?

The logging needs testing. I'll report back when I've done that

**Comment by magicrub** [comment]
Would be nice to get another review of this to ensure I correctly implemented the method that was discussed in the last dev call.

**Review by tridge — APPROVED** [review]
just needs test

**Comment by peterbarker** [comment]
... now needs rebase...

**Comment by peterbarker** [comment]
I've force-pushed this branch after rebasing it on top of Matt's RPM-logging-improvements branch (which I vastly prefer over moving to WriteStreaming!)

**Comment by peterbarker** [comment]
Tested the logging in SITL.  Works fine.

**Pull request merged**
