### PR TITLE
SITL: use parm inheritance for copter models

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by khancyr** [comment]
Good to go ! 
@peterbarker I add the same for gazebo iris !

**Comment by OXINARF** [comment]
@peterbarker Can you just rename SITL to Tools in the commit messages? I know it is used in SITL but the files are in the Tools folder. Also, you've tested this, right?

**Comment by khancyr** [comment]
@OXINARF I test and it works as intend!

**Comment by peterbarker** [comment]
Push in, thanks @khancyr @OXINARF

**Pull request closed without merging**
