### PR TITLE
Tools: remove xmlpretty, xmlint do a better job

### PR DESCRIPTION
**Pull request by khancyr**

### CODE REVIEW

**Comment by peterbarker** [comment]
OK, so.  What was this used for?  Obviously making xml look pretty - much *which* XML?

**Comment by khancyr** [comment]
according to history, it looks like it was used on mavlink xml 
@jschall any old memory ?

**Comment by amilcarlucas** [comment]
Yes it is used by upstream Mavlink. But currently commented out in our Fork.

**Comment by peterbarker** [comment]
@amilcarlucas I'm a bit confused as the file being removed here is in the ArduPilot tree, not in our mavlink subrepo.

Can we assume that we can remove this on the basis that xml_format.sh should be used instead?

@khancyr what effect does running xml_format.sh against `ardupilotmega.xml` have?

**Comment by khancyr** [comment]
Normally the formatter is part of the ci test.... I will double check but at least on mavlink master that the case

**Comment by peterbarker** [comment]
Wow, xmlpretty is *really*, *really* not a good idea.  I just ran it.

OTOH, the tidying script in the mavlink repo only changes one message.

Perhaps this might be a good use of a pre-commit hook in git?

Anyways, thanks, merged!

**Comment by khancyr** [comment]
we could make the CI blocking is case of formatting issue, that is pretty simple !

**Comment by amilcarlucas** [comment]
That is already the case in upstream mavlink. I can bring that in, if that is desired.

**Comment by khancyr** [comment]
@amilcarlucas yes please ! Make our mavlink CI even with mavlink master CI !

**Pull request merged**
