### PR TITLE
Copter: further precision landing rework

### PR DESCRIPTION
**Pull request by jschall**
This fixes up some issues with the PX4 IR-LOCK driver, runs the precision land update at 400hz to eliminate the latency from having two asynchronous 50hz loops. It also further fixes up the math, properly applying a pinhole camera model.

### CODE REVIEW

**Comment by jschall** [comment]
Also note that the commit log hasn't been squashed. Some changes were made that were later discovered to be incorrect. Please review by looking in the "files changed" tab.

**Comment by tridge** [comment]
i've added a couple of comments in the PX4Firmware PR

**Comment by rmackay9** [comment]
One small thing, because the precision landing is now updating at 400hz, it may record a *lot* of updates to the dataflash.  Maybe we need to throttle it so that it only updates at 10hz or something like that.

**Comment by jschall** [comment]
Yep. I will look at doing that.

**Comment by jschall** [comment]
@rmackay9 updated to move logging to 25hz logging, squashed commit log, fixed the math thing in the PX4Firmware PR.

**Comment by jschall** [comment]
Note: depends on https://github.com/ArduPilot/PX4Firmware/pull/59

**Comment by jschall** [comment]
I also added terrain altitude support.

**Comment by rmackay9** [comment]
Merged as part of the other PR. https://github.com/ArduPilot/ardupilot/pull/4445

**Pull request closed without merging**
