### PR TITLE
Adding URUS System.

### PR DESCRIPTION
**Pull request by hiro2233**
With URUS you could make like automated control Home, Robotics Games (Like Lego Mindstorm) and more, working with APM Apis and Raspberry Pi under Linux OS.

At first time i will try get this work for Domotic System (Automated System Home), you could do on:

URUS:Home basic system.
--------------------------

- ON/OFF Lights directly.
- ON/OFF Lights at specified times.
- OPEN Doors with keypad.

URUS:Home Advanced system.
--------------------------------

- Control via Internet all system.
- Control Airconditioner temperature and modes with IR.
- Control Lights intensity with RC Outputs.
- Sensor proximity.
- Face detection with camera and OpenCV.

Structure name project
-----------------------------
The structure base name for application will be: URUS. For Home systems will be like: URUS: Home.
Examples structured project names likes for robotics, URUS: Arm; URUS: FishGame; URUS: SkateBoard; and so...

Greetings,

Hiroshi.

### CODE REVIEW

**Comment by tridge** [comment]
@hiro2233 
Does this board exist yet? Is this an existing board you are porting to?
The reason I ask is the HAL boards entry in the PR sets up for HIL sensors, which is rather strange.

**Comment by hiro2233** [comment]
@tridge It's for RAW Raspberry Pi board with BCM2835 chip at first time for basic functions, i'm in the board development at this moment for advanced functions.

Note that I enabled GPIOs only.

Greetings.

**Comment by tridge** [comment]
ok, thanks for the clarification. Have you thought about using the BBBMini setup? That is very low cost and gives you the full set of sensors.

**Comment by hiro2233** [comment]
Mmm probably this setup make similar to BBBMini, the goal is create new board as a low cost cape for RPI with option to attach low cost sensors too.

Really there are two goals, one it's for RAW RPI periphals without any cape boards. The second, is re-use the APM2.6 board as a CAPE for RPI. It's will be good for people are begining with APM developtment.

The URUS:Home are with basic on/off light functions right now, using AP_MENU, AP_Scheduler and AP_InertialSensor libraries.
I'm using AP_Menu as console to configure the system and receive single parameters from external client.

**Comment by magicrub** [comment]
what's the status of this PR?

**Comment by hiro2233** [comment]
Hi Tom, i still working on that, in the next week i will push the basic system.

Thanks in advance.

**Comment by hiro2233** [comment]
Hi @lucasdemarchi, it's Reworked, please check. Thanks in advance.

**Comment by lucasdemarchi** [comment]
@hiro2233 sorry for the delay, I'll take a look soon.

**Comment by hiro2233** [comment]
@lucasdemarchi No problem, i'm working in final basic system phase, i'm testing URUS mavlink communication right now. I have finished a "hardware cape" from this system too, it's will be the basic structure learning APM API in TD3 Workshop.

**Comment by hiro2233** [comment]
@lucasdemarchi Thank you very much.

**Comment by tridge** [comment]
I don't fully understand the use case for a HIL-only port, but it does seem low impact in the code and does mean you could get the base code running without any sensors on a RPi, so I think we should put this in.
Lucas, you ok with this being merged?

**Comment by OXINARF** [comment]
@tridge This has conflicts and it is for master. Are we really adding a board to master that doesn't do anything?

**Comment by tridge** [comment]
@OXINARF the conflicts are trivial to resolve and the addition is very low impact as far as maintenance goes.
I have actually done something very similar to this when doing bring-up on a new board. Doing an initial bring-up without real sensors (using just HAL) is a good first step, then you add the sensors one by one.
So this could act a bit like AP_HAL_Example but for Linux ports.

**Comment by OXINARF** [comment]
@tridge I agree with that if this is going to be implemented soon. But this PR has been opened since March and it hasn't evolved. We already have a lot of boards that work on top of RPI, at some point it is a burden to maintain (and not really worth it if nobody uses those boards).

**Comment by lucasdemarchi** [comment]
> Lucas, you ok with this being merged?

I'm ok with applying it. But changes to the makefiles should be removed and a new target added to waf. Just like I said for Dark board, I'm not adding more boards to the make build system since it's deprecated and I don't want to maintain it.

**Comment by hiro2233** [comment]
Hi @lucasdemarchi , ok i understand your point, could you help me merging it meanwhile with makefile and later i will integrate to waf build system as soon as possible? Thank you very much for your time.

**Comment by hiro2233** [comment]
This PR https://github.com/ArduPilot/ardupilot/pull/4670 is an approach to this one.

**Comment by lucasdemarchi** [comment]
Rebased, resolved the conflicts, removed the changes to makefiles and added the necessary changes to waf.  I just tested the build works (See the BUILD.md file). 

It's now applied. Please check if it's working for you. Thanks.

**Comment by hiro2233** [comment]
@lucasdemarchi Thank you very much!!! You are the best one!

I will test it and i'll report to you.

**Comment by hiro2233** [comment]
Thank you @tridge and Dev Team! The best one!

**Pull request closed without merging**
