### PR TITLE
AP_Proximity: TeraRanger Tower Evo support

### PR DESCRIPTION
**Pull request by msadowski**
This pull request adds support for TeraRanger Tower Evo. There are lots of changes compared to the TeraRanger One driver (e.g. clockwise sensor order, a need to request modes and initialize streaming) hence to keep the backwards compatybility we created a new driver (Proximity Type: 6).

The driver has been tested in an indoor scenario in AltitudeHold mode and it worked beautifully. Please, feel free to let us know if you would like to see anything changed.

### CODE REVIEW

**Comment by pl-kabaradjian** [comment]
Hello @rmackay9, here is a friendly ping for this request as we didn't have any update since its opening. 
Also we are about to launch Teraranger Tower Evo and we would like to know how far is the next release to inform our customer that they can use official version for this product (and not manually build our repository)

Cheers and thanks in advance for your time,

**Comment by rmackay9** [comment]
@pl-kabaradjian,

Thanks for this.  I've had a quick look but need to do a more complete review.  I'm aiming to get this included in Copter-3.6.  In the next release candidate if we can get it into master in time, failing that, the release candidate after the next one.

**Comment by pl-kabaradjian** [comment]
Thanks @OXINARF and @rmackay9!
We greatly appreciate your help on this. By the way, here is a preview [video](https://www.youtube.com/watch?v=ThxoVRs5mjM) of the collision avoidance in action with our new product TeraRanger Tower Evo if you're interested. It is always nice to see the code in action!

**Comment by charleslinquist** [comment]
There are so many object avoidance systems available, all with a different range, FOV, cost, etc.  And all with a different interface. 
Wouldn't it be easier to define a standard and then use a small uC (Arduino, ARM, PIC) to iniitialize the sensor and convert the output for the FC?  The uC could buffer the data and the FC could poll at whatever rate (10Hz?) was convenient.  I don't know which hardware interface would be best for the existing code, but I2c would seem like a good option.  Some sensor manufacturers might eventually add the new "Environment Condition" protocol as a standard, eliminating additional hardware.

**Comment by pl-kabaradjian** [comment]
Thanks for your time, much appreciated!

**Pull request merged**
