### PR TITLE
AP_Motors: Constrain get_throttle_hover value with allowed range

### PR DESCRIPTION
**Pull request by SergeyBokhantsev**

### CODE REVIEW

**Review by rmackay9 — APPROVED** [review]
This looks good to me.  @bnsgeyer are you happy for this change to go in for TradHeli?

**Comment by bnsgeyer** [comment]
@SergeyBokhantsev @rmackay9 This is already constrained in the update_throttle_hover function.  Why do we need to do it again?

**Comment by rmackay9** [comment]
@bnsgeyer, only because it's possible for users to disable hover thrust learning and manually update the parameter.  I believe this happened to @SergeyBokhantsev (or someone he knows) which led to this PR.

**Review by bnsgeyer — APPROVED** [review]
LGTM

**Comment by rmackay9** [comment]
Merged, thanks!

**Pull request merged**
