### PR TITLE
AP_HAL_ChibiOS:remove synth curr from bds with onbd current

### PR DESCRIPTION
**Pull request by Hwurzburg**

### CODE REVIEW

**Comment by andyp1per** [comment]
shouldn't this simply be in minimal.inc?

**Comment by Hwurzburg** [comment]
No....only bds with on board integrated current sensors

**Comment by andyp1per** [comment]
most of the 1Mb boards have an ESC connector with a current wire designed to use the current sensor on the ESC - the vast majority of people will be using this

**Comment by Hwurzburg** [comment]
This battery monitor was designed   exactly  for those kind of boards for those not using esc with current telem

**Review by tridge — APPROVED** [review]

**Pull request merged**
