### PR TITLE
Stop using AHRS library as conduit for beacon object

### PR DESCRIPTION
**Pull request by peterbarker**
... we now have a singleton for this, so we don't need to hold this in the AHRS object.

### CODE REVIEW

**Comment by rmackay9** [comment]
Has this has been tested somehow?

**Comment by peterbarker** [comment]
@rmackay9 I couldn't get a SITL beacon test to actually navigate, but I did get:

```
1970-01-01 10:05:51.11: BCN {TimeUS : 351116164, Health : 1, Cnt : 4, D0 : 584.3232421875, D1 : 584.27978515625, D2 : 584.119140625, D3 : 584.16259765625, PosX : -0.24973750114440918, PosY : 0.18676605820655823, PosZ : 584.0899658203125}
```

and:

```
APM: EKF2 IMU0 is using range beacons
APM: EKF2 IMU0 initial pos NE = 20.4,11.0 (m)
APM: EKF2 IMU0 initial beacon pos D offset = -583.4 (m)
APM: EKF2 IMU1 is using range beacons
APM: EKF2 IMU1 initial pos NE = 20.4,11.0 (m)
APM: EKF2 IMU1 initial beacon pos D offset = -583.4 (m)
APM: EKF2 IMU0 has stopped aiding
APM: EKF2 IMU1 has stopped aiding
APM: EKF2 IMU0 is using range beacons
APM: EKF2 IMU0 initial pos NE = 20.4,11.0 (m)
APM: EKF2 IMU0 initial beacon pos D offset = 583.1 (m)
APM: EKF2 IMU1 is using range beacons
APM: EKF2 IMU1 initial pos NE = 20.4,11.0 (m)
APM: EKF2 IMU1 initial beacon pos D offset = 583.1 (m)
```

Which shows that the beacon object is getting around just fine.

I've tidied the test up and pushed it up in a disabled state.  Symptoms of the failure is just that when waiting for the absolute position of the aircraft that last quote above gets spewed out repeatedly and we never get a global position.  I can be run with `
./Tools/autotest//autotest.py build.ArduCopter fly.ArduCopter.BeaconPosition`

**Comment by rmackay9** [comment]
Does this mean that we've broken beacon support somehow?  perhaps just the BCN_LATITUDE, BCN_LONGITUDE and BCN_ALT weren't set?  Sorry if this is scope creep, I'm just worried that we are breaking things, changing things that make it harder to figure out how it's been broken and moving on..

**Comment by peterbarker** [comment]
@rmackay9 I'm assuming beacon support is just fine and I just don't know how to run it.

You can see my attempts at setting the vehicle up for beacon here: https://github.com/ArduPilot/ardupilot/pull/11665/files#diff-205ba7eeea0bd19f1af46b8419add13eR3362

Can you see what I'm missing there?

**Comment by rmackay9** [comment]
The wiki is here but I see it hasn't been updated since Copter-3.6 went out.  http://ardupilot.org/copter/docs/common-pozyx.html#configuration-through-the-ground-station

I don't think beacons work with the EKF2 even though theEK2_BCN_ parameters exist.  so let's set EK3_ENABLE = 1, EK2_ENABLE = 0.

**Comment by peterbarker** [comment]
@rmackay9 Same thing, but now with the added bonus of:

```
APM: PreArm: EKF3 Roll/Pitch inconsistent by 14 deg
APM: PreArm: EKF attitude is bad
APM: PreArm: AHRS not healthy
```

:-)

**Comment by peterbarker** [comment]
@rmackay9 I pushed up the changes to make it use EKF3

**Comment by rmackay9** [comment]
Ah well.  not sure then.

**Comment by peterbarker** [comment]
@rmackay9 the beacon altitude wasn't being set.  That was causing the EKF to start/stop the beacon aiding.  That's fixed.  EKF3 is unhappy with its attitude, and EKF2 doesn't give an absolute position.  But... progress?

**Comment by rmackay9** [comment]
@peterbarker, sounds like progress but as mentioned several times in various discussions and meetings I'm not keen on any further non-functional structural changes ahead for the copter and rover releases especially those that can't be shown to work.  It really is best if efforts are focused on functional changes and bug fixes.  No-fly zone support is top of the list after @magicrub's OA database PR goes in

**Comment by peterbarker** [comment]
This change has been shown to work.  The test is also broken in master, in the same way.

**Comment by rmackay9** [comment]
@peterbarker, sorry to be such a stickler, but is it actually working?  i.e. the vehicle can fly in SITL using beacons instead of GPS or is it rather just as broken as master appears to be?

**Comment by peterbarker** [comment]
On Sat, 29 Jun 2019, Randy Mackay wrote:

> @peterbarker, sorry to be such a stickler, but is it actually working? i.e. the vehicle can fly in SITL using beacons instead of GPS or is it rather just
> as broken as master appears to be?

It's just as broken as it is in master.  I wasn't hoping to fix beacons, 
just avoid using AHRS as a "well, everybody hasthe AHRS, so just grab it 
from over there" conduit.  We were doing that before we adopted 
singletons.

But the output I pasted above shows that AP::beacon() is working to get 
logging, and the output from the EKF shows that it is getting the beacon 
object it needs just fine as well.  That's the limit on the firmware 
changes here - how the beacon object is retrieved.

What this PR also gives is a test which should pass (I think...) but 
doesn't.  I'm actually leaning towards the theory that the test is 
incorrect at this point, as tridge did have beacons happening quite 
recently.  The test could be brought in separately.

Looking at the marvelmind and pozyx pages, a few things of interest:
  - marvelmind says use ekf3, pozyx does not
  - both pages say disable the GPS arming check, but I'm not sure at this 
point that's required
  - marvelmind suggests taking the beacon height from the beacons too - so 
I added that in to the test - but it seemed to make things worse rather 
than better.

**Comment by rmackay9** [comment]
OK, merged!

**Pull request merged**
