### PR TITLE
AP_Motors: tradheli-update parameter display names

### PR DESCRIPTION
**Pull request by bnsgeyer**
This PR shortens up tradheli parameter display names to make them more readable in QGC.  There was no functional change in this PR.

### CODE REVIEW

**Comment by bnsgeyer** [comment]
@rmackay9 please merge.  this PR just changes display names for the parameters.  there is no functional change.  thanks!

**Comment by rmackay9** [comment]
OK, merged.  I had a quick look at it yesterday actually.. personally I don't like the start parameter names or descriptions with Min/Minimum/Max/Maximum but instead I like to start them with the feature name.  This is all your baby though so it's just a suggestion

**Comment by bnsgeyer** [comment]
@rmackay9  I did notice that as I was changing them.  Any particular reason why?  They will be grouped by feature in the new heli setup pages in QGC and MP.  Just wondering

**Comment by rmackay9** [comment]
@bnsgeyer, it's really just about the grouping.  MP's full parameter list and full parameter tree screens order them using the underlying parameter name but the Standard Params and Advanced Params screens seem to order using the description.

Maybe we should ask @meee1 to change it so that it's ordered by parameter name on these screens too.

**Comment by rmackay9** [comment]
this has been added to Copter-4.0.0-rc3

**Pull request merged**
