### PR TITLE
AP_Baro: KellerLD fix uninitialized var

### PR DESCRIPTION
**Pull request by hendjoshsr71**
Found while running Valgrind  ArduSub SITL for another PR.

Partial Valgrind Output
image

### CODE REVIEW

**Review by peterbarker — APPROVED** [review]
Well it'll do the job.

But really, just returning any time a read fails would be a better pattern IMO.  Bets someone adds some code to look at some of the other values that will fail to be read?

**Comment by hendjoshsr71** [comment]
Fair enough critique, I was trying to just drive by..... Famous last words.

**Comment by hendjoshsr71** [comment]
@peterbarker updated for your liking?

**Comment by peterbarker** [comment]
> @peterbarker updated for your liking?

Sorry, I really didn't mean to make work for you.  I should've approved it as-was.

If we're going to fix it properly, how about https://github.com/ArduPilot/ardupilot/pull/18126 ?

Both of these would need to be tested on hardware anyway, I think.  Or at least against a simulator to show there's no regression on reading out these pmax and pmin values.

**Comment by hendjoshsr71** [comment]
> > @peterbarker updated for your liking?
> 
> Sorry, I really didn't mean to make work for you. I should've approved it as-was.
> 
> If we're going to fix it properly, how about #18126 ?
> 
> Both of these would need to be tested on hardware anyway, I think. Or at least against a simulator to show there's no regression on reading out these pmax and pmin values.

LOL. No problem. 
I see you couldn't let the rest of it be either.   ;)

Closing in favor of #18126

**Pull request closed without merging**
