### PR TITLE
AP_HAL_ChibiOS: fix kakutef7 motor glitch when using dshot

### LINKED ISSUE #9861: KakuteF7 DMA on UARTs causes DShot issue
This is a bug report from Paul Atkin @utkinpol 
Paul is using a KakuteF7, and finds that he needs to use NODMA on UARTs to get reliable flight on a small racing quad.
Paul, please put all details in this issue, including:

 - parameters (full file)
 - at least one DF log showing the issue
 - list of all peripherals (receiver, any uart connections, any i2c devices etc)
 - any other information that you think may be helpful

### PR DESCRIPTION
**Pull request by chobitsfan**
fix #9861

discussion https://discuss.ardupilot.org/t/motor-glitch-issues-kakute-f7-w-tekko32-4in1/51872/27 and https://discuss.ardupilot.org/t/kakute-f7-6-inch-flip-crash-need-help-with-logs/42527

log when it happens [motor_glitch.zip](https://github.com/ArduPilot/ardupilot/files/5032886/motor_glitch.zip)
 it seems motor suddenly stop running in the middle of flight
image

This problem was caused by shared DMA stream between SPI1 (sd card) and TIM1 (motor output). `dma_resolver.py` arrange `SPI1_TX` and `TIM1_UP` to share the same DMA stream. It causes DMA contention 
debug output of  dma_resolver.py shows `Sharing TIM1_UP on (2, 5) with ['SPI1_TX']`

#9874 did solve this problem by mark USART1 & USART2 NODMA, because `dma_resolver.py` will arrnage `TIM1_UP` use DMA stream 3 and `SPI1_TX` using DMA stream 0. USART1 / USART2 do not interference motor output, but free their DMA stream will make `dma_resolver.py` able to arrange SPI1 and TIM1 to different DMA stream

flight log for this PR. 3 full battery flight, telem1 connected to mavproxy
[fix_kakutef7_motor.zip](https://github.com/ArduPilot/ardupilot/files/5032934/fix_kakutef7_motor.zip)

However, this PR will cause `dma_resolver.py` unable to arrange a DMA stream for USART1_RX

### CODE REVIEW

**Comment by andyp1per** [comment]
I don't understand the fix, but the problem is real.

**Comment by chobitsfan** [comment]
Hi @andyp1per This PR add motor output (TIM1 & TIM3) to DMA_PRIORITY, so that dma_resolver.py will try not share their DMA stream with others.  It avoid DMA contention.

In fact, it is the default in `write_dma_header()`
https://github.com/ArduPilot/ardupilot/blob/53553c7c7128a6b9f351814cfa5e734aeee816be/libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py#L1683

**Comment by amilcarlucas** [comment]
I think it would be a good idea to add a more descriptive commit message. One that explains the problem and explains that it fixes an issue on the Kakute F7

**Comment by chobitsfan** [comment]
Yes, I agree. Thank you @amilcarlucas

**Comment by andyp1per** [comment]
@chobitsfan do you need the same fix on the KakuteF7Mini?

**Comment by amilcarlucas** [comment]
Should this be backported to stable?

**Comment by chobitsfan** [comment]
> @chobitsfan do you need the same fix on the KakuteF7Mini?

Hi @andyp1per  I think so but I do not have kakutef7mini to test it

**Comment by andyp1per** [comment]
@chobitsfan I can test - I have many, all using dshot

**Comment by chobitsfan** [comment]
@andyp1per Thank you very much for helping

**Comment by chobitsfan** [comment]
replaced by #15256

**Pull request closed without merging**
