### PR TITLE
Copter: Support NAV_GUIDED_ENABLE commands outside of a Mission.

### PR DESCRIPTION
**Pull request by mday299**
Good for companion computers that want to enable NAV_GUIDED.

### CODE REVIEW

**Comment by OXINARF** [comment]
@mday299 What am I missing here? How is this used outside of a mission?

**Comment by rmackay9** [comment]
I think NAV_GUIDED is really "Guided" mode within the "Auto" flight mode.  So I think if someone wants to use it outside of a mission (i.e. outside of the Auto flight mode) they can just use the Guided flight mode.
Within AUTO, the NAV_GUIDED_ENABLED allows setting time and distances checks on Guided mode so that we resume the mission if the companion-computer or GCS were to fly the vehicle too far away or fly for too long.  But I don't see how we could make use of that outside of Auto (in Auto mode, when the distance or time is exceeded it moves onto the next auto command or RTLs if it's out of commands).  

Outside of Auto mode.. we already have the fence. 

I wonder if I'm missing something..

**Comment by mday299** [comment]
Randy's comment is correct -- we could use the GUIDED mode to do the same thing.  However, we'd like to use AUTO and the NAV_GUIDED_ENABLE mission command already supports this.  All I'm doing is allowing the command to be sent via mavlink from a companion computer at any arbitrary time rather than via a scripted mission command.

**Comment by OXINARF** [comment]
Randy has the final saying here but I don't like that approach. When in Auto you are following a mission, period. If you want to control the vehicle with Guided at an arbitrary time just change to Guided mode. When you are done with it, change to Auto and continue the mission.

**Comment by magicrub** [comment]
I like this method because switching to and from guided for object
avoidance during auto is kind of annoying to handle. For quick things this
is better. I don't see any problem having this in there, it offers
flexibility.

**Comment by khancyr** [comment]
Hi, I can't agree more with magicrub! Having some kind of override on auto is good especialy for avoidance!

**Comment by OXINARF** [comment]
Any external avoidance system should send information to ArduPilot so that our autopilot decides what to do. That should work for any mode, so this isn't needed. If you want the external avoidance system to command the vehicle in all cases, then you are looking at Guided mode.

And why would you want to do avoidance at an arbitrary time during a mission? If you think that is needed, then why do it only for Auto mode? Why wouldn't that be useful for Loiter for example?

**Comment by magicrub** [comment]
Clearly you haven't worked on avoidance code in ardupilot, especially from
a companion computer.

This should definitely go in.

**Comment by OXINARF** [comment]
@magicrub I'm not sure what that means, but OK. I'm done with it, @rmackay9 will decide.

**Comment by lvale** [comment]
I can see both @OXINARF and @magicrub positions as valid IF we consider ONLY collision avoidance during AUTO.

Problem that if a vehicle is in a auto mode and a companion computer tells it to change mode (Guided or other), then that companion should be responsible for the following changes. This is already the usual behaviour.

On the other hand if we want a "nanny mode" also known as collision avoidance that should work as a flight mode modifier just like simple and supersimple work.

**Comment by magicrub** [comment]
Self Avoidance during auto already switches to an auto-avoid mode.

**Comment by rmackay9** [comment]
@magicrub, I don't understand your comment either.  As far as I can see, @OXINARF understands what the correct approach should be and is asking the right questions.

@mday299 hasn't actually said this is for object avoidance but in any case, what the PR seems to do is basically switch the vehicle into Guided-within-AUTO at an arbitrary time by creating a free floating command that's not part of the command list.  Because it's a free floating command, I'm pretty sure it will mess up at least the reporting of where we are in the mission list.  I think it will also mess up the command verify because the mission library will keep trying to verify the command that it thinks it's running.
As a minor point, there's no check in the new code to ensure the vehicle is in AUTO mode but that should be easy to add.

By the way, my preferred approach to add object avoidance in Auto is to make either the waypoint navigation code (AC_WPNav) and/or the position controller (AC_PosControl) use the new AC_Avoidance library (currently only the Loiter controller uses it)... and if the companion computer is the one that knows where objects are (perhaps using SLAM) then we should (and will) add a way for a companion computer to tell the vehicle code where objects are so that the vehicle code will stop in time.  We will add a "MAV" type proximity sensor which will accept DISTANCE_SENSOR messages (http://mavlink.org/messages/common#DISTANCE_SENSOR) with the orientation field set to one of 8 horizontal directions (i.e. 45degree sectors in 8 directions).

The "nanny" approach might work where the companion computer is watching during auto and then it grabs control if it thinks the vehicle is heading into danger.  But that could be done just as easily by switching the vehicle into Guided mode.  When the companion computer is done it could switch back to AUTO and the mission should resume from where it left off.  I think this accomplishes the same thing without the "free floating command" and the problems that come with it.

I've also been thinking a little bit about a path planning interface which would allow handing some control over the path taken to an external path planner.  That idea is still half-baked though I'm afraid.

**Comment by rmackay9** [comment]
To add some detail to what @magicrub has said, he's referring to the avoidance of manned vehicles if an ADSB ping sensor (from uAvionix) is attached to the vehicle.  http://ardupilot.org/copter/docs/common-ads-b-receiver.html

@peterbarker has referred to this as "macro Avoidance" meaning the avoidance of very large far-away objects.  I think most people are interested in "micro avoidance" which is closer objects like buildings and trees.

**Comment by magicrub** [comment]
@mday299 we discussed this on the dev call and decided this is generally a bad idea. Before we close this, do you have any strong arguments to use this feature? What is your use-case?

**Comment by mday299** [comment]
@magicrub -- Roger that.  My use case was as you had described earlier in this thread.  I think I have a workaround (put NAV_GUIDED_ENABLE at the beginning of my mission file) so it's fine to close this request.

Meanwhile, any movement on this request?

https://github.com/ArduPilot/ardupilot/pull/5107

**Pull request closed without merging**
