### PR TITLE
Create AP_AHRS base class for use in AP_Mount

### PR DESCRIPTION
**Pull request by sypaq-nexton**
We want to be able to use `AP_Mount` in `AP_Periph`. However, `AP_Mount` currently references the `AP_AHRS` singleton, which is not available in `AP_Periph`.

This PR:
* creates an abstract base class for `AP_AHRS` that provides the minimum accessors required for `AP_Mount`;
* adds a new `AP::ahrs_base()` accessor; and
* updates the `AP_Mount` backend and drivers to use the new `AP::ahrs_base()` accessor.

FYI: @tridge, @rmackay9, @joshanne

### CODE REVIEW

**Comment by IamPete1** [comment]
Why not use `#ifndef HAL_BUILD_AP_PERIPH` inside mount to remove all the AHRS calls?

**Comment by sypaq-nexton** [comment]
> Why not use `#ifndef HAL_BUILD_AP_PERIPH` inside mount to remove all the AHRS calls?

Because some of the Mount functions require vehicle position and/or orientation to calculate a solution. We'd like the Mount to behave the same if it is connected via AP_Periph or if it is connected directly, so we need another way to provide the data required.

**Comment by IamPete1** [comment]
I would have thought a new ExternalAHRS type of DoneCAN would be the better fit. As we have for VectorNAV ect.

**Comment by sypaq-nexton** [comment]
Yes, but the `AP_AHRS` library is _big_. We don't want to instantiate the whole of `AP_AHRS` in `AP_Periph` if we don't need it.

**Comment by IamPete1** [comment]
You don't need it all for mount, but other stuff might want more things in the future and before long your not saving much flash. Have you found a size for AHRS? We can define out EK2 and EK3 but it looks like your stuck with DCM at the moment. I would guess its less than 10K?

**Comment by sypaq-nexton** [comment]
@IamPete1: I attempted to incorporate `AP_AHRS` and `AP_ExternalAHRS` into `AP_Periph`, but it's not feasible, hence the changes proposed in this PR.

`AP_AHRS` makes extensive use of the singletons in the `AP` namespace. Some of these uses are behind `*_ENABLED` feature flags (e.g. `AP::airspeed()`), but many are assumed to be always present, including:
  * `AP::ins()`
  * `AP::compass()`
  * `AP::gps()`
  * `AP::baro()`
  * `AP::logger()`

However, these libraries are not always present in `AP_Periph`. As such, `AP_AHRS` (and therefore `AP_ExternalAHRS`) can't be added to `AP_Periph` without extensive changes.

**Comment by sypaq-nexton** [comment]
I've updated this to create a new `AP::ahrs_base()` accessor, rather than pass an `ahrs` reference into `AP_Mount`.

**Comment by IamPete1** [comment]
This is better, but I still find it quite a little weird. Would be good to see the DroneCAN data capture implementation to get a better idea of what the final solution would look like.

**Comment by sypaq-nexton** [comment]
No longer have time to work on this. I'll re-visit it at a later date.

**Pull request closed without merging**
