### PR TITLE
Update install-prereqs-ubuntu.sh

### PR DESCRIPTION
**Pull request by KONGLZ123**
old: http://firmware.ardupilot.org/Tools/PX4-tools/
new: http://firmware.us.ardupilot.org/Tools/PX4-tools/

### CODE REVIEW

**Comment by khancyr** [comment]
@KONGLZ123 Why this change ? Both are working but it is better to use the current one to get the redirection depending on location : like eu for me ^^

**Comment by KONGLZ123** [comment]
@khancyr Ah, novice on the road ...  I always unsuccessful, I thought in the Ubuntu need accurate URL, so ...\-_-/...

**Comment by khancyr** [comment]
Sorry I didn't understand, the current script isn't working well or you are unsuccessful to submit a PR ?

**Comment by KONGLZ123** [comment]
Sorry, I did not make it clear. Theoretically, after the implementation of the following order will be able to build the firmware success, right?
```
Tools / scripts / install-prereqs-ubuntu.sh -y
```
I installed ubuntu on the virtual machine, do these operations, but unsuccessful. Prompt the following error
```
Compilation terminated
Make [3]: *** [/home/klz1314/ardupilot/ArduCopter/afs_copter.cpp.o] Error 1
Make [3]: Leaving directory `/home/klz1314/ardupilot/modules/PX4Firmware/Build/px4fmu-v2_APM.build/home/klz1314/ardupilot '
Make [2]: *** [/home/klz1314/ardupilot/modules/PX4Firmware/Build/px4fmu-v2_APM.build//home/klz1314/ardupilot/module.pre.o] Error 2
Make [2]: Leaving directory `/home/klz1314/ardupilot/modules/PX4Firmware/Build/px4fmu-v2_APM.build '
Make [1]: *** [/home/klz1314/ardupilot/modules/PX4Firmware/Build/px4fmu-v2_APM.build/firmware.px4] Error 2
Make [1]: Leaving directory `/ home / klz1314 / ardupilot '
Make: *** [px4-v2] Error 2
```
In addition, would like to ask two questions:
1. on Windows 10 on the h: disk, using px4 tool chain, I can not build the code successfully, but I copy the code to c: or f: disk, can be successful. In the h disk reported the following error:
```
Make [1]: *** [generateuorbtopicheaders] Error 139
Make [1]: Leaving directory `/ h / Code / ardupilot / modules / PX4Firmware '
Make: *** [px4-io-v2] Error 2
```
Is not the tool chain does not support h disk?
2. I use "Bash on Ubuntu on Windows", I can not find my usb device (in the window10 can be connected Mission Planner), I follow the Ubuntu method can not be successful, but there is no window 10 under Ubuntu information. Do you have any suggestions?

very sorry to bother you~

**Comment by OXINARF** [comment]
@KONGLZ123 As @khancyr explained, this change is wrong. We want to use the general link and not region specific ones - it would still work because you are always redirected to your region, but better to have the general link there.
For your doubts, please post in the forum (http://discuss.ardupilot.org) or ask in Gitter chat (http://gitter.im/ArduPilot/ardupilot). You'll need to post more than that though, those small logs don't show the actual error.

**Pull request closed without merging**
