### PR TITLE
AP_Airspeed: Updated Airspeed example.

### PR DESCRIPTION
**Pull request by hiro2233**

### CODE REVIEW

**Comment by magicrub** [comment]
I think this is correct, but the GCS is not a singleton so it shouldn't be needed. @peterbarker do you know how the gcs singleton interacts with the examples?

**Comment by hiro2233** [comment]
check this https://github.com/ArduPilot/ardupilot/blob/master/libraries/GCS_MAVLink/GCS.h#L462

and this call https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Airspeed/AP_Airspeed.cpp#L165 to uninitialized function and cause a segdump from this one
https://github.com/ArduPilot/ardupilot/blob/master/libraries/GCS_MAVLink/GCS.h#L472

**Comment by peterbarker** [comment]
@magicrub Yep, this is a reasonable fix.  The examples can break if someone adds a call into the `gcs()` singleton where we haven't had one before, and where the examples cross that codepath.

**Comment by OXINARF** [comment]
Approved by @peterbarker, so merged, thanks!

**Pull request merged**
