### PR TITLE
init_ardupilot cleanup and improvements

### PR DESCRIPTION
**Pull request by khancyr**
Hello, 
I am working on new motor lib for rover, and the initlization sequence was pretty hard to understand for newcomer, and things were mixed up.
So, I try to comment and make thing similar on all vehicle as there should be much different.
I moved things in setup() that should be in init_ardupilot()
In init_ardupilot(), I try to keep the same sequence for all, I think we should comment the sequence steps to prevent further mixing. What I do is : 
-init generic vehicle stuff
- load param
- init board
- init servo out and relay
- init usb, serial, telem
- init mandatory sensors : battery, compas, baro, gps
- init rc_in
- finish init with other stuff .

I think that good initialisation order should be : 
- vehicle + boad indentifiation
- motor ouput : should be fast to prevent unexpected move
Then, can message be send during init_ardupilot() ? I don't think, but I think that the next step should be to init the communication and logging stuff. With that we can analyze how the initilisation is going.
- init communication and logging
- init sensors : should it be all ? or only mandatory ? Should we feed directly ahrs with sensors as soon as init ? Currently it isn't, as sensors are init and later the pointer is passed to ahrs.
- lately, init rc_in to prevent unexpected thing from RC radio.
- lastly, mission and high level things

What do you think?

Other things : Copter doesn't have g.num_resets.set_and_save(g.num_resets + 1), should we add it ?

Edit: Other motivation for these change is that I try to implement a new motor lib for rover and correct the mess in rover ... but it seems to me that it is not only related to rover, cleaning those stuff on all vehicles will be a good thing !

### CODE REVIEW

**Comment by khancyr** [comment]
I didn't do the same for Sub as thing were pretty differents, but ideally it should be rework to be compatible with other.

**Comment by khancyr** [comment]
well looks like I break things ....

**Comment by OXINARF** [comment]
This will need careful review and testing, sometimes there are unclear dependencies.

Regarding num_resets I wasn't aware that even existed, AP_Stats also has a boot counter.

**Comment by khancyr** [comment]
@OXINARF yep that why I submit it now, I think it will be worth it. About the num_resets, AP_Stats do the same with bootcount so I think we should remove it from other vehicle.

**Comment by khancyr** [comment]
OK error found. In copter and rover rc_out init need to know some value from rc_channel throttle. But in plane, it doesn't. 
Moreover, plane got 4 stages : set_control_channels (that init rc in/out), init_rc_in (that just set rc_channel deadzones), init_rc_out_main (that set failsafe and trim for the 4 mains ouputs), init_rc_out_aux (that init the other ouputs)
copter got 2 : init_rc_in (that init only input) and init_rc_out (that init ap_motors with some value from rc_in, and other servo) 
rover got 3 : set_control_channels (that init rc in/out), init_rc_in (that init deadzone and aux servo [why here?]), and init_rc_out (that set failsafe and trim).

We should have quite the same function but it end that every vehicle is doing things in different order or in function not related ...

**Comment by amilcarlucas** [comment]
I vote for removal of num_resets in favor of AP_Stats::bootcount

**Comment by tridge** [comment]
@khancyr I'm very reluctant to make this sort of change without a lot more assurance it doesn't break anything. Init order is quite critical. If you get it wrong then you'll get things like motors starting on quadplanes on reboot or incorrect servo movement on mid-air reboot in failsafe handling.
It takes a _lot_ of effort to ensure this type of change is correct, and testing with a lot of airframe types. I'm not confident you have done that level of testing.

**Comment by khancyr** [comment]
@tridge I agree with you. I also speak with Randy, it this will be a huge work for pretty no other benefice than readability for newcomers...

One thing that we can extract from this now is the removal of num_resets on plane and rover because it is already on AP_Stats !

**Pull request closed without merging**
