### PR TITLE
New unified HAL for OpenPilot Revo Mini 

### PR DESCRIPTION
**Pull request by night-ghost**
(based on https://github.com/scenkov/ardurevo)

### CODE REVIEW

**Comment by kwikius** [comment]
Nice Job. Hope this gets in.

**Comment by tridge** [comment]
great! Looks like a very interesting port
We have a policy of splitting up commits per directory, which makes review a lot easier. I have done that for this PR here:
https://github.com/tridge/ardupilot/commits/night-ghost-master
we will need quite a bit of review of the PR, and it would help if you could do a force push of the above branch so we do the review on a version with the commits split up. 
Thanks!

**Comment by tridge** [comment]
this seems to bring in more of the CMSIS library than is really needed, is that deliberate?

**Comment by night-ghost** [comment]
Sorry but original port was done here https://github.com/scenkov/ardurevo, I only adopt it to new API and to Ardupilot's native build system. So I don't know lots of details in internals.

**Comment by tridge** [comment]
ok, is the original author interested in helping get this in?
Also, can you tell me how to upload a firmware once built? I have fixed a couple of build issues (see my tree above) and I'd like to test on a CC3D board I have here (is CC3D compatible with this?). Any particular bootloader setup needed?

**Comment by night-ghost** [comment]
Mea cupla, my bug - when adopting I looked to the implementation of the VRBRAIN HAL.
But I do not have any idea about the intentions of the original author. My board is Revo Mini, and binary upload done via Makefile from original port

upload: $(SKETCHBIN)
       $(LIBMAPLE_PATH)/support/scripts/reset.py && sleep 1 && dfu-util -a1 -d $(USBID) -D $(SKETCHBIN) -R

**Comment by night-ghost** [comment]
splitting up commits per directory breaks tests, the only changes in directories another than HAL_REVOMINI are pin assignments for board support in "#else if" before last "#else" so it shouldn't break anything.

**Comment by night-ghost** [comment]
Sorry the above is not true for AP_BoardLED.cpp and it should be updated

**Comment by tridge** [comment]
why would it break tests?
there are quite a few changes in non-HAL directories, some of which are hangovers from earlier versions of the code that can be removed. Breaking it up makes this easier to spot

**Comment by night-ghost** [comment]
So now I should remove this PR and open series of individual?

**Comment by night-ghost** [comment]
So now I should remove this PR and open series of individual?

**Comment by night-ghost** [comment]
Hi all, I don't understand what I should do now...

**Comment by kwikius** [comment]
@night-ghost ( I'm no expert but ... ) At minimum do nothing, but dont close it again :) The PR process can take a while since there are a lot of pull request to process. I hope to get a look at this port myself some time soon and provide some feedback

**Comment by night-ghost** [comment]
Sorry for closing - buttons placed so near...

**Comment by kwikius** [comment]
Pulled tridges version and built on my repo after a couple of mods

https://github.com/kwikius/ardupilot/tree/revo.
Not tried loading or running it yet though..
Not sure how to try to update this PR from there though or make a new PR?

**Comment by lucasdemarchi** [comment]
new PR in #3834 so I'm closing this.

@kwikius when doing this we just open a new PR as you did and append a version to the title.

**Comment by night-ghost** [comment]
new version https://github.com/ArduPilot/ardupilot/pull/3874

**Pull request closed without merging**
