### PR TITLE
Update hwdef.dat for Cube Purple

### PR DESCRIPTION
**Pull request by MallikarjunSE**
Missing compass probe for AK8963

### CODE REVIEW

**Comment by tridge** [comment]
I'll leave Sid to decide on this, noting that the compass in the 9250 can impact sample rate for fast sampling. Not necessarily a good idea to enable it.

**Comment by bugobliterator** [comment]
I think we can enable its detection and disable that compass by default via parameter mask. What do you think @tridge . That way if user really wants it, its just a param change rather than a build.

**Comment by MallikarjunSE** [comment]
@tridge How is it managed in Cube Black?

**Comment by bugobliterator** [comment]
We have it disabled in CubeBlack, CubeBlack only has Compasses used that are on the Isolated IMU board.

**Comment by MallikarjunSE** [comment]
Hey @bugobliterator 
What difference does it make between isolated and non-isolated IMU? I believe both are connected via SPI.

**Comment by bugobliterator** [comment]
@MallikarjunSE My bad, actually we use one compass that is isolated in LSM and one on the MPU that is on non-isolated board. We don't use compass with MPU that is on isolated board, and that MPU has fast sampling turned on. So basically we to minimise the load on SPI bus, it is recommended not to use MAG in MPU with fast sampling enabled.

**Comment by tridge** [comment]
> I think we can enable its detection and disable that compass by default via parameter mask. What do you think @tridge . That way if user really wants it, its just a param change rather than a build.

yes, that is fine. Just do some tests on achieved sensor rates in the IMU msg so you can tell users what the issues are.

**Comment by tridge** [comment]
> So basically we to minimise the load on SPI bus, it is recommended not to use MAG in MPU with fast sampling enabled.

It isn't really the SPI load we're concerned about, it is a bug in the sensor. When you ask for 8kHz sampling with the mag enabled you'll find you don't actually get samples at 8kHz. It also varies with individual sensors (not just sensor type, but per board). It seems that internally the sensor isn't keeping up with sampling the IMU at high rate and also sampling the mag.

**Comment by MallikarjunSE** [comment]
This is only during fast sampling if i'm right. Is there a way to automatically disable compass when fast sampling is enabled? Or provide instructions to mask compass during fast sampling.

**Comment by peterbarker** [comment]
@MallikarjunSE Are you still interested in pursuing this PR?

The way we choose compasses to use has changed a lot since this was created.

If we can probe for the compass but have it not used by default we could disable fast sampling when it *is* enabled, perhaps.  I have concerns about breaking people's existing setups - @bugobliterator was talking about changing the defaults, but some users may have set parameters which may enable the compass and thus disable their fast sampling (I might be wrong on this and I'm sure Sid will correct me...)

**Comment by MallikarjunSE** [comment]
Hey @peterbarker 
No, MPU9250 when used alone on flying platforms is very noisy! 
Does the rover use the fast sampling? If not, then having the compass and disabling it in default param would be nice. 
Also since not many are questioning about it, it seems the current situation of no compass should be fine. 
Thanks!

**Comment by peterbarker** [comment]
@MallikarjunSE OK, thanks for looking at this anyway.  We might leave this alone for the time being :-)

**Pull request closed without merging**
