### PR TITLE
SRV_Channel: fix servo output function documentation typo

### PR DESCRIPTION
**Pull request by holadepo**

### CODE REVIEW

**Review by amilcarlucas — APPROVED** [review]

**Review by khancyr — CHANGES_REQUESTED** [review]
Correction is good but the commit message should be SRV_Channel: not RC_Channel !

**Review by khancyr — APPROVED** [review]

**Comment by khancyr** [comment]
hello,

Could you rebase this on latest master, we will merge it after.

**Comment by holadepo** [comment]
> hello,
> 
> Could you rebase this on latest master, we will merge it after.

Done @khancyr

**Review by khancyr — APPROVED** [review]

**Review by tridge — CHANGES_REQUESTED** [review]
the resulting line is a lot shorter - I think you may have removed some of the functions when merging?

**Comment by holadepo** [comment]
> the resulting line is a lot shorter - I think you may have removed some of the functions when merging?

That is right, there were changes on line 68 I did not notice while merging. It has been corrected now.

**Pull request closed without merging**
