### PR TITLE
Cast enum to int to fix Qurt compiler warning

### PR DESCRIPTION
**Pull request by katzfey**
Cast enum to an int to get rid of Qurt compiler warning when max enum value is less than the constant it is being compared to. Here is the warning:

../../libraries/AP_GPS/AP_GPS.cpp:1622:14: warning: result of comparison of constant 8 with expression of type 'mavlink_channel_t' is always false [-Wtautological-constant-out-of-range-compare]
    if (chan >= MAVLINK_COMM_NUM_BUFFERS) {
        ~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~

### CODE REVIEW

**Comment by peterbarker** [comment]
We went the other way for a similar thing:
```
libraries/GCS_MAVLink/GCS_MAVLink.h:#pragma clang diagnostic ignored "-Wtautological-constant-out-of-range-compare"
```

**Comment by katzfey** [comment]
If that's what you guys prefer then I can certainly change it to that. Was the int cast discussed when that one was put in?

**Comment by katzfey** [comment]
Casting as an int certainly looks nicer than all that pragma gunk. C99 section 6.7.2.2 §2: "The expression that defines the value of an enumeration constant shall be an integer constant expression that has a value representable as an int."; compilers are free to use a different integer type to represent the enumeration, but conversion to int is always lossless

**Review by peterbarker — APPROVED** [review]
LGTM

**Comment by peterbarker** [comment]
Merged, thanks!

It would be nice to adjust our compiler flags so these don't creep back in - even in non-QURT code.

**Pull request merged**
