### PR TITLE
Update GIT_Success.txt

### PR DESCRIPTION
**Pull request by zakiehbayati**

### CODE REVIEW

**Comment by magicrub** [comment]
Please remove your email address

**Comment by rmackay9** [comment]
If possible prefix the commit with "Tools:". txs!

**Review by peterbarker — CHANGES_REQUESTED** [review]
Changes have been requested on this PR.

**Comment by peterbarker** [comment]
@zakiehbayati I'm going to close this now - feel free to re-open it once the requested changes have been made (or make a fresh PR!)

**Pull request closed without merging**
