### PR TITLE
Replace /* fall through */ with FALLTHROUGH;

### PR DESCRIPTION
**Pull request by amilcarlucas**

### CODE REVIEW

**Comment by WickedShell** [comment]
Does this suppress any warnings that were missed before? I'm not seeing any warnings from GCC 8.1 Otherwise seems like a style thing/not worth bothering with.

**Comment by amilcarlucas** [comment]
I did not see any warnings, but I am not using GCC 8.1.
I fixed it for consistency reasons, and because maybe the warnings have been unnoticed until now.

**Comment by WickedShell** [comment]
Ah, usage of the macro, that is better. (I was thinking it was just a comment change, but what's behind `FALLTHROUGH` is an improvement because it does some smarter stuff for various compilers)

**Comment by rmackay9** [comment]
Merged, thanks!

**Pull request merged**
