### PR TITLE
SITL python : add hexacopter and reoder frame type

### PR DESCRIPTION
**Pull request by khancyr**

### CODE REVIEW

**Comment by peterbarker** [comment]
Thanks.  I'm very confused at to why hexa was never covered in sim_vehicle....

The reorganisation is good, and I think it hints at breaking the _options_for_frame up into separate structures per vehicle.  So perhaps _options_for_vehicletype{'ArduCopter': { "_options_for_frame": { ... } } sort of thing.  Currently this:

```./Tools/autotest/sim_vehicle.py -f Gazebo -v ArduPlane```

doesn't throw an error, it just builds for bin/arducopter-quad!

@khancyr Should I put the reorganisation in as-is, or do you think we should add a bit more structure first?

**Comment by khancyr** [comment]
Some time ago ,sitl hexa wasn't working ... it started on his back ... but now it works, so I add it ! 

I think will should merge this one as-is, the idea was just to add hexa and make the read a little bit clearer.
But I totally agree with your idea !

**Comment by tridge** [comment]
looks good to me. 
Peter, merge when ready

**Comment by peterbarker** [comment]
Merged, thanks!

**Pull request closed without merging**
