### PR TITLE
Support Elfin-Wing F405 board

### PR DESCRIPTION
**Pull request by suiaiyun**
This is a cheap and self-made flight control board. Its appearance is similar to that of the f4v3 flight control board, but it supports more serial ports and pwm output. 
Which is completely different from the F4V3. It is essentially a different board.

### CODE REVIEW

**Comment by Hwurzburg** [comment]
board ID already assigned...needs a new one added to board list...needs a README.md file...where can this board be obtained?

**Comment by suiaiyun** [comment]
Sorry. There is an error in this submission. Close and resubmit.

**Comment by andyp1per** [comment]
@suiaiyun I have recently done a fairly comprehensive F405 based board - it might be worth using this as a starting point for your PR: https://github.com/ArduPilot/ardupilot/pull/22075

**Comment by suiaiyun** [comment]
> @suiaiyun我最近做了一个相当全面的基于 F405 的板 - 可能值得将它用作您 PR 的起点：#22075

This is great. I am referring to your PR now. I have already done so. Thank you for your feedback. I will resubmit my PR.

**Pull request closed without merging**
