### PR TITLE
Copter: GPS glitch pre-arm check and notification

### PR DESCRIPTION
**Pull request by rmackay9**
This PR adds the following change to improve user awareness of GPS glitches:

- RGB LED flashes blue and yellow during a glitch (for all vehicles)
- Copter pre-arm GPS checks gets additional check for glitches
- Copter: "GPS Glitch" and "GPS Glitch cleared" messages sent to ground station (which should appear on HUD)
- Copter dataflash logging of glitch as an error

I plan to follow this PR up with another to add a GPS glitch Failsafe but that is slightly trickier and will require more testing while this PR is relatively safe and could be added to an AC3.5 point release fairly easily.

### CODE REVIEW

**Comment by magicrub** [comment]
I don't see anything in here that is copter specific, why can't this be pulled out to be generic for all platforms?

**Comment by khancyr** [comment]
Agreed, it should profit to all ! 
But I think it is an implementation problem as Copter gps check isn't really gps, it is more like navigation/positionning check, but it should profit to all vehicle!

**Comment by rmackay9** [comment]
One issue with making it work for all vehicles is that Plane and Rover can still apparently be compiled with DCM only (i.e. AP_AHRS_NAVEKF_AVAILABLE == False).  If the shared AP_Arming class uses AHRS_NavEKF then that won't be possible anymore I think.

**Comment by magicrub** [comment]
Come on, Randy. You're not going to let a small thing like that stop you, are you?

I think if we're at a point where EKF is no longer on copter then it's safe enough to drop it from all platforms. Copter gets more flight time than all other platforms combined.

**Comment by rmackay9** [comment]
@magicrub, I don't think Plane will go for that because DCM's position estimate drifts much more slowly than the EKF's.  I don't think we should hold up this PR for this.

**Comment by rmackay9** [comment]
Merging 'cuz this is a pretty low impact change.  I think @WickedShell is planning some GPS related arming changes so don't want to hold him up.  Maybe i'm just making excuses but..

**Comment by WickedShell** [comment]
@rmackay9 I am but I apparently never posted my question on this... Couldn't this go in AP_Arming and only be dropped from the build with an `#if AP_AHRS_NAVEKF_AVAILABLE == false` ? Just curious on that part.

@magicrub I don't think DCM will be dropped soon, but that shouldn't really preclude plane from getting the check :)

**Comment by rmackay9** [comment]
@WickedShell, hi there.  I think the problem though is that the constructor of ap-arming would also need to change based on whether that's available or not.
Maybe I'm wrong but I think perhaps we should drop that ap-ahrs-navekf-available definition and make it always available.

**Pull request merged**
