### PR TITLE
Tools: autotest: add 2 locations in Japan

### PR DESCRIPTION
**Pull request by DaijiroYamazaki**

### CODE REVIEW

**Review by rmackay9 — APPROVED** [review]
LGTM assuming it passes the autotests.

**Comment by muramura** [comment]
@DaijiroYamazaki san.
SITL's BING satellite map and MP's Google satellite map seem to show different positions of the aircraft.
Which is the same position as the site?

Screenshot from 2021-07-10 00-17-04
Screenshot from 2021-07-10 00-16-38

**Comment by rmackay9** [comment]
Merged, thanks!

**Comment by DaijiroYamazaki** [comment]
Hi muramura san, thank you for your review.
I picked this location from Google Hybrid map of Mission Planner.
It seem too close from tree on BING map, so need to be carefully to use in SITL and real location.

**Pull request merged**
