### PR TITLE
sim_vehicle.py: create from sim_vehicle.sh

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by tridge** [comment]
thanks! please push in

**Comment by peterbarker** [comment]
Merged this in.  Comments welcome.

**Comment by WickedShell** [comment]
Just a note, does not seem to work on the windows cygwin environment, due
to failing to import psutil. There may be a cygwin package that provides it
but I didn't immediately find it. I ran into a problem when trying to
install via PIP that I was missing a visual studio batch script for which I
need either visual studio, or mingw. I haven't chased it any further then
that at this point.

**Comment by peterbarker** [comment]
@WickedShell I've pushed up a fresh branch (https://github.com/peterbarker/ardupilot-1/tree/sim_vehicle.py) which avoids the use of psutil.  If you could test at some stage it would be appreciated.

**Pull request closed without merging**
