### PR TITLE
Pr copter 3.6 yaw land from master

### PR DESCRIPTION
**Pull request by khancyr**
backport from https://github.com/ArduPilot/ardupilot/pull/8537 to copter 3.6
alternative at https://github.com/ArduPilot/ardupilot/pull/11528

### CODE REVIEW

**Comment by rmackay9** [comment]
This looks good to me and I agree we should backport what we have in master to Copter-3.6 instead of coming up with a new solution.

**Comment by rmackay9** [comment]
@khancyr, you've tested this change to 3.6 in SITL at least?

**Comment by khancyr** [comment]
@rmackay9 tested on SITL : 
takeoff in guided, land, send long CONDITION_YAW 42, it works.
Tested on flight at Azurdrones for a year ! ;-P

**Comment by rmackay9** [comment]
Merged now that Copter-3.6.10 is out.  This should be included in Copter-3.6.11.

**Pull request merged**
