### PR TITLE
Copter: unfriend everyone, make relevant methods public

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by rmackay9** [comment]
much better, thanks!  one other thing that might be nice is to move the AutoYaw stuff lower.. I think it would be best if at the top of the mode class definition we had all the public things that developers of flight modes should implement.. and then below that all the helper functions available to them.. and then finally these big classes (AutoYaw and takeoff) listed in alphabetical order..  I might have a go at making that change on top of this PR..

**Comment by magicrub** [comment]
This diff is hard to read. However, it looks like it's probably ok if it compiles.

**Comment by rmackay9** [comment]
I've got an additional commit to add which is at the end of this branch: https://github.com/rmackay9/rmackay9-ardupilot/commits/peterbarker-unfriendly

**Comment by magicrub** [comment]
@rmackay9 why not just push your commit to peter's branch?

**Comment by rmackay9** [comment]
@magicrub, I've never managed to get that working .. I don't see his branch from SourceTree..

**Comment by rmackay9** [comment]
Merged, txs!

**Pull request merged**
