### PR TITLE
Copter: correct compilation when AFS is enabled

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by WickedShell** [comment]
s/disabled/enabled?

I'm a bit curious why AFS is not a standard feature on copter (at least on builds other then hal minimize), the breakage of AFS on copter has happened a lot because it's not normally included.

**Comment by peterbarker** [comment]
On Fri, 6 Apr 2018, WickedShell wrote:

> s/disabled/enabled?

Yes, thanks, fixed.

> I'm a bit curious why AFS is not a standard feature on copter (at least on builds other then hal minimize), the breakage of AFS on copter has happened a
> lot because it's not normally included.

I ran ./Tools/autotest/build-with-disabled-features.py to find this 
problem after the precland thing popped up.  I'm going to modify it to 
also do the other vehicles.

**Comment by WickedShell** [comment]
I didn't know about that script. Opinions on if that should become a CI step? (I'm inclined to say yes on the principle of this stuff takes a long time to catch otherwise)

**Comment by peterbarker** [comment]
On Fri, 6 Apr 2018, WickedShell wrote:

> I didn't know about that script. Opinions on if that should become a CI
> step? (I'm inclined to say yes on the principle of this stuff takes a long
> time to catch otherwise)

Takes too long to run to put on CI.  There are a *lot* of things to 
enable/disable.

**Comment by rmackay9** [comment]
Merged, thanks!
I've objected to having AFS enabled in copter by default because at least the last time I looked at it, it wasn't not well integrated into the existing failsafes.

**Pull request merged**
