### PR TITLE
AP_MSP: fix compilation with MSP Telemetry but not OSD

### PR DESCRIPTION
**Pull request by khancyr**
see https://custom.ardupilot.org/view?token=copter:KakuteF7:dafdf26c74ebb40b512a74a361ef9ad6b96efd2d:c132a21a4a0d0d6fd2e4a6b4a3d0f33b

### CODE REVIEW

**Comment by yaapu** [comment]
@khancyr the fix makes sense but the use case it covers does not exist :-)
Why would you compile in the DJI backend without OSD support?
People would end up selecting MSP and would be unable to use the DJI OSD feature or the DisplayPort feature.
In the custom build server It's probably better to always select OSD along MSP just like regular builds do.

@tridge made a big cleanup when MSP went int to allow a minimal OSD to be always included unless excluded by minimal features

**Comment by khancyr** [comment]
@yaapu I got not idea ! It seems that we cannot acces the build log anymore, the only things that was selected was MSP Telemetry which imply then DJI telemetry.

I don't know much the usage of MSP, but I think it would be faire to be able to use its telemetry without DJI or Display port, like on AP_Periph boards for example.
I have look at Displayport and it is indeed protected for AP_Periph build and got its own HAL_WITH_MSP_DISPLAYPORT.
So next step would maybe to add HAL_WITH_MSP_DJI or link DISPLAYPORT and DJI. what do you think?

**Comment by khancyr** [comment]
seems that new build with MSP_telem are failing too : https://custom.ardupilot.org/view?token=copter:FlywooF745Nano:9aee98eeb885ab140d72f9b8bf4c2fd96926ccab:0c30583150be2bdf014a50d6ed1b2241 
Vehicle: Copter
Board: FlywooF745Nano
Selected Features:
Enable EKF3
Enable MSP Telemetry
Enable MSP GPS
Enable MSP Compass
Enable MSP Baro
Enable Beacon
Enable NMEA Output
Enable Baro Wind Compensation
Enable HighLatency2 Support


https://custom.ardupilot.org/view?token=copter:FlywooF745Nano:6c25a8e628750b51745763c03a655f6354c3743c:206aab57d655e594a363de4f4fd0e3c7
Vehicle: Copter
Board: FlywooF745Nano
Selected Features:
Enable EKF3
Enable MSP Telemetry
Enable MSP Sensors
Enable MSP GPS
Enable MSP Compass
Enable MSP Baro
Enable Mode SystemID
Enable Mode Follow
Enable Mode Turtle
Enable Mode Guided NoGPS
Enable Beacon
Enable NMEA Output
Enable Baro Wind Compensation
Enable Proximity
Enable HighLatency2 Support

**Comment by yaapu** [comment]
to recap: 
regular builds always enable (minimal) OSD support unless minimize features is set which btw also disables MSP so that's the reason why all boards build on regular server.
On the custom server right now is easy to break dependency by not selecting OSD so as you suggested we can make MSP OSD explicit by creating a HAL_WITH_MSP_OSD directive which would enable/disable generic and DJI MSP support and when selected on the custom build server would enable OSD as well, how's that?

**Comment by andyp1per** [comment]
Better to fix this on the build server by adding the right dependencies there

**Comment by yaapu** [comment]
@andyp1per this would be easy, would still be a bit ackward for MSP sensors to require OSD as a dependency but it would a least build, I'll do a PR to fix the custom server so we can discuss what to do with the dependencies without blocking users

image

**Comment by yaapu** [comment]
ok, done the PR https://github.com/ArduPilot/CustomBuild/pull/14

**Comment by tridge** [comment]
not needed any more with custom build server fix

**Pull request closed without merging**
