### PR TITLE
AP_VisualOdom: handle ModalAi VOXL resets

### PR DESCRIPTION
**Pull request by rmackay9**
This PR improves the AP_VisualOdometry library's handling of [ModalAI VOXL camera](https://ardupilot.org/copter/docs/common-modalai-voxl.html) resets which are different than the IntelT265 camera with which it shares a driver.

When the T265 "resets" it increments the reset_counter and the position jumps (often to a location many meters away).  The yaw normally does not jump.  Resets often occur many times in a row.  The camera continues providing position, velocity and yaw estimates although they unreliable for about 1sec.  These resets normally occur due to high vibration or sunlight hitting the camera.

When the ModalAI "resets" it stops providing position, velocity and yaw estimates for a few seconds.  When it recovers increments the reset_counter and resets the position and yaw back to zero.  From the user's point of view, this means the vehicle jumps back close to the EKF origin and the heading resets to North.  Note: the jump will not be exactly to the origin or North because the camera may have been "aligned" to the compass and/or GPS based position. These resets are much more rare than on the T265 and they occur when the camera's view is blocked or there are not enough features.

This PR improves the reset handling (for the VOXL camera) by "aligning" the position back to what it was before the reset occurred and "aligns" the yaw so it matches the current AHRS/EKF yaw.  The detailed changes are:

- renamed align_sensor_to_vehicle() to align_yaw_to_ahrs() which is more precise
- split align_yaw_to_ahrs() and align_position_to_ahrs() to create more general purpose align_yaw() and align_position() methods
- added record_voxl_position_and_reset_count() to record the last good position from the camera.  Note these are not raw positions from the camera but instead scaled and rotated positions that are fed into the EKF
- when a reset occurs, use align_position() to shift the position to the last good camera position.  align_yaw_to_ahrs() is used to rotate the yaw to the current AHRS/EKF yaw

This has been bench tested on a real vehicle and I've confirmed the position and yaw do not jump after a reset.  Below are some screenshots from those tests.  I've also looked in the VISP logs and confirmed that there are no jumps.
pr-before-screenshot
pr-after-screenshot

### CODE REVIEW

**Review by tridge — APPROVED** [review]

**Comment by shubham-shahh** [comment]
which Ardupilot release will contain this PR?

**Comment by rmackay9** [comment]
@shubham-shahh,

Most likely it will be included in Copter-4.4.0 which should start beta testing within a couple of weeks.  Until then you could use "latest" which can be loaded from MP's Firmware Install screen after pressing "Ctrl-Q".  Note that "latest" changes each day and hasn't gone through beta testing so it is more dangerous to use than the beta or stable releases.

By the way, the ModalAI cameras don't reset very often.  I've found that I really need to treat them badly to make them reset.  To be more specific I had to cover the camera with a cloth and then move it around to force it to reset.

**Comment by shubham-shahh** [comment]
hahaha, yes you are right,
I'll add a few things for reference for someone who later refers this PR
in this [link](https://developer.qualcomm.com/sites/default/files/docs/machine-vision-sdk/api/v1.2.13/structmv_v_i_s_l_a_m_pose.html) there are all possible cases mentioned which can cause a reset. ranging from issues related to IMU and camera

**Comment by rmackay9** [comment]
@shubham-shahh,

Thanks for that!  It would be really nice if there was a way for ArduPilot to get these error codes.  We could at least display them to the user.  I will suggest this to ModalAI that they send using SEND_TEXT.  Please tell me if you have any better ideas.

**Comment by shubham-shahh** [comment]
> @shubham-shahh,
> 
> Thanks for that! It would be really nice if there was a way for ArduPilot to get these error codes. We could at least display them to the user. I will suggest this to ModalAI that they send using SEND_TEXT or maybe some other mavlink message. Please tell me if you have any better ideas.

yes, that sounds awesome, as I can see in their source code [here](https://gitlab.com/voxl-public/voxl-sdk/services/voxl-vision-hub/-/blob/master/src/vio_manager.c#L313)
they do send some mavlink messages through UDP, I'm not entirely sure which mavlink message it's referring to, but I guess it should be possible from their end. 
as mentioned [here](https://gitlab.com/voxl-public/voxl-sdk/services/voxl-vision-hub/-/blob/master/src/vio_manager.c#L588)
the error code is fetched but not forwarded to ardupilot

**Pull request merged**
