### PR TITLE
AP_NavEKF3: Change the if statement to a switch statement.

### PR DESCRIPTION
**Pull request by muramura**
I think that the mode judgment of the first "PV_AidingMode" can be replaced with a switch statement.

I have PR newly closed the following PR.
AP_NavEKF3: Changed if statements to switch statement. #5439

### CODE REVIEW

**Comment by muramura** [comment]
@OXINARF san.  
I will commit one.

**Comment by muramura** [comment]
I changed the commit message to "Change the if statement to a switch statement."

**Comment by OXINARF** [comment]
@muramura Still shows the same message _AP_NavEKF3: Change indentation to 4 white spaces._: https://github.com/ArduPilot/ardupilot/pull/7546/commits

**Comment by muramura** [comment]
I closed it by mistake.

**Comment by OXINARF** [comment]
Merged, thanks!

**Pull request merged**
