### PR TITLE
FrSky: Adjusted offsets

### PR DESCRIPTION
**Pull request by lvale**
Following up on @yaapu comment https://github.com/ArduPilot/ardupilot/pull/10499#issuecomment-474625077

### CODE REVIEW

**Comment by lvale** [comment]
Sometimes I wonder about the marvels of CI...... @OXINARF

**Comment by IamPete1** [comment]
I restarted it for you, it's passed this time

**Comment by lvale** [comment]
thanks @Iampete1 

@peterbarker now it is a good time to merge it

**Comment by peterbarker** [comment]
Merged, thanks!

**Pull request merged**
