### PR TITLE
AP_ExternalAHRS: Change GPS to GNSS

### PR DESCRIPTION
**Pull request by muramura**
The element name in message_ofs is set to GNSS.
I will change the definition name to match the element name.

### CODE REVIEW

**Comment by peterbarker** [comment]
@muramura does this change it to match the datasheet?

@valbv your thoughts?

**Comment by valbv** [comment]
It looks better
Thanks for these cosmetic changes

**Comment by valbv** [comment]
I think naming in changes is more correct
But in device documentation used "GPS" in title

image
image

**Comment by peterbarker** [comment]
OK, so sadly I think that while this PR does rename the variables to be more accurate, we should stick with the documentation's nomenclature.  If anything I guess the entry in the union could be changed to reflect the datasheet.

Thanks anyway, @muramura , closing this one.

**Pull request closed without merging**
