### PR TITLE
AP_Baro: use int64_t for intermediate values

### PR DESCRIPTION
**Pull request by peterbarker**
pointless loss of precision otherwise

### CODE REVIEW

**Comment by peterbarker** [comment]
It's possible that someone here has checked the ranges very carefully... but we should either use these intermediate values or add casts to be clear.

**Comment by tridge** [comment]
needs testing on sub with ms5637
possibly should be float?

**Comment by jaxxzer** [comment]
I will test this

**Comment by jaxxzer** [comment]
Everything is working normally here with the ms5**8**37 + the patch. I'll note that int32 was probably used in the first place as that's what's done in the datasheets:
[5837](https://www.te.com/commerce/DocumentDelivery/DDEController?Action=showdoc&DocId=Data+Sheet%7FMS5837-30BA%7FB1%7Fpdf%7FEnglish%7FENG_DS_MS5837-30BA_B1.pdf%7FCAT-BLPS0017)
[5611](https://www.te.com/commerce/DocumentDelivery/DDEController?Action=showdoc&DocId=Data+Sheet%7FMS5611-01BA03%7FB3%7Fpdf%7FEnglish%7FENG_DS_MS5611-01BA03_B3.pdf%7FCAT-BLPS0036)

If this really is a bug/problem, perhaps we should notify MS about it for the benefit of all the other drivers in out there?

**Comment by rmackay9** [comment]
decided that really it should be a float to be more consistent with other drivers.  Not sure if anyone is motivated to actually change it to resolve the compiler warning because it's likely not really a problem.

**Comment by peterbarker** [comment]
On Mon, 22 Apr 2019, Randy Mackay wrote:

> decided that really it should be a float to be more consistent with other
> drivers. Not sure if anyone is motivated to actually change it to resolve
> the compiler warning because it's likely not really a problem.

Agreed.  Almost certainly not a problem.

The problem is that the compiler warnings here obscure *ACTUAL* problems 
raised by the same compiler warning.

**Pull request closed without merging**
