### PR TITLE
Tools: Git Success - Tom Pittenger

### PR DESCRIPTION
**Pull request by magicrub**
Adding Tom Pittenger to Git SUccess

### CODE REVIEW

**Comment by Jeffery-qiu** [comment]
HELLO TOM,I AM JAYE

**Comment by rmackay9** [comment]
Hi @Jeffery-qiu!

P.S. we are at the ardupilot conference in Shenzhen!

**Comment by magicrub** [comment]
Hi @Jeffery-qiu !

**Comment by Jeffery-qiu** [comment]
ME TOO ,I SAT IN THE BACK

**Comment by magicrub** [comment]
If anyone is interested, you can watch me create this PR :)
Skip to 6:20
https://photos.app.goo.gl/gvTdWJMC46q6yC8x5

**Pull request merged**
