### PR TITLE
AP_GPS: Remove unused blending math

### LINKED ISSUE #7510: GPS blend: filtered correction looks unused
#### Issue details
_Please describe the problem, or desired feature_
Recently I read the AP_GPS.cpp, In calc_blended_state() function.
```
    blended_alt_offset_cm = 0.0f;
    blended_NE_offset_m.zero();
    for (uint8_t i=0; i<GPS_MAX_RECEIVERS; i++) {
        if (_blend_weights[i] > 0.0f) {
            blended_NE_offset_m += location_diff(state[GPS_BLENDED_INSTANCE].location, corrected_location[i]) * _blend_weights[i];
            blended_alt_offset_cm += (float)(corrected_location[i].alt - state[GPS_BLENDED_INSTANCE].location.alt) * _blend_weights[i];
        }
    }
```
 the variable blended_alt_offset_cm is set, but when we use it next time, it will not used.
```
Vector2f blended_NE_offset_m;
    float blended_alt_offset_cm = 0.0f;
    blended_NE_offset_m.zero();
    for (uint8_t i=0; i<GPS_MAX_RECEIVERS; i++) {
        if (_blend_weights[i] > 0.0f && i != best_index) {
            blended_NE_offset_m += location_diff(state[GPS_BLENDED_INSTANCE].location, state[i].location) * _blend_weights[i];
            blended_alt_offset_cm += (float)(state[i].location.alt - state[GPS_BLENDED_INSTANCE].location.alt) * _blend_weights[i];
        }
    }
```
I don't think it works well. 

#### Version
3.5.4

#### Platform

[  ] Copter

### PR DESCRIPTION
**Pull request by WickedShell**
Thanks to @ender-chen for noticing, closes #7510

### CODE REVIEW

**Comment by magicrub** [comment]
looks good to me, merged!

**Comment by OXINARF** [comment]
This actually looks completely wrong! What is the use of `corrected_location`? If you look more widely all this was supposed to filter the position, but the code removed here (and above) ended up not being used because code is missing.

**Comment by magicrub** [comment]
@OXINARF it updates `state[GPS_BLENDED_INSTANCE].location` just below it.

**Comment by OXINARF** [comment]
@magicrub Where is that? Which line?

**Comment by magicrub** [comment]
up where the first instance of the copy/paste is. The lower one was a partial duplicate 
https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_GPS/AP_GPS.cpp#L1417

**Comment by OXINARF** [comment]
@magicrub Lines 1411-1412 are NOT the same as lines 1465-1466 removed here. First one uses direct position from GPS, second one uses a corrected (filtered) position.

**Comment by magicrub** [comment]
@OXINARF ahh, i see. Hence you question about corrected_location! @WickedShell please tripple check this code we just removed, it's not an exact match.

**Comment by WickedShell** [comment]
So the reason I nuked the whole function but tagged @priseborough for review is that the block I nuked is a nop, but I can see it was intended to do something. I'm unsure if it was a legacy calculation that isn't needed anymore, or if there was intended to be an additional bit of code.

**Pull request merged**
