### PR TITLE
Tools/LogAnalyzer: fix and update loganalyzer

### PR DESCRIPTION
**Pull request by mentonin**
This PR updates LogAnalyzer, removing deprecated code, fixing incompatibilities with Python 3. It also formats the files with black.

### CODE REVIEW

**Comment by peterbarker** [comment]
Do we really need to change every instance of `'` to `"`?!  What's the reasoning?

If this is flake8-clean afterwards we should label it as such so it stays that way with `AP_FLAKE8_CLEAN` in a comment near the top.

This script has to continue to work with Python2.

**Comment by rmackay9** [comment]
Nice to some the log analyser getting some love!

**Comment by timtuxworth** [comment]
> This script has to continue to work with Python2.

Why? Python2 subsetted more than 2 years ago? https://www.python.org/doc/sunset-python-2/

**Comment by mentonin** [comment]
> Do we really need to change every instance of `'` to `"`?! What's the reasoning?

I ran it through black, because `pyproject.toml` makes me think it is the standard formatter for the project. According to [The Black code style](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html):
> The main reason to standardize on a single form of quotes is aesthetics. Having one kind of quotes everywhere reduces reader distraction. It will also enable a future version of Black to merge consecutive string literals that ended up on the same line (see [#26](https://github.com/psf/black/issues/26) for details).



> If this is flake8-clean afterwards we should label it as such so it stays that way with `AP_FLAKE8_CLEAN` in a comment near the top.

I rechecked and there are only a few violations of line length on comments and docstrings (it looks like I had E501 disabled in a config file somewhere). Will fix. Should I label it in the file docstring or in a comment (existing code has examples of both styles).

> This script has to continue to work with Python2.
I can try to fix it, but is it really necessary? Python2 has been deprecated for a while now, and supporting both is going to be increasingly complex as time goes on.

**Comment by peterbarker** [comment]
Merged, thanks!

**Pull request merged**
