### PR TITLE
Copter: skip throttle high arm check when arming in AUTO

### LINKED ISSUE #21415: Copter: pre-arm check that throttle is high should be skipped if arming in Auto
AP_Arming_Copter::arm_checks() skips over the pilot's throttle position checks if arming in Guided mode from a GCS.  I think we can also skip these checks if the vehicle is arming in Auto mode.  [See code here](https://github.com/ArduPilot/ardupilot/blob/master/ArduCopter/AP_Arming.cpp#L633).

### PR DESCRIPTION
**Pull request by ak-ironix**
Fixes #21415 
Hi @rmackay9! I am a newbie and have tried to add the necessary conditions. Please let me know if this is what you were looking for.
Thanks in Advance.

### CODE REVIEW

**Review by peterbarker — APPROVED** [review]
Seems to do what was requested.

**Comment by peterbarker** [comment]
@ak-ironix please note in the comments here what testing you have done on this PR.  We're going to assume you've just been working in SITL, and that's OK for this PR, but we do need to know that the functionality works, for example!

**Comment by rmackay9** [comment]
Merged, thanks!  sorry for the delay

**Comment by ak-ironix** [comment]
Thanks for merging! Looking forward to making more contributions.

**Pull request merged**
