### PR TITLE
Use RC_Channel to populate IOMCU mappings

### PR DESCRIPTION
**Pull request by peterbarker**
Bench-tested using an OrangeRX and a CubeOrangePlus and a servo.  All seems right compared to master.

```
Board,plane
CubeOrangePlus,-32
```

### CODE REVIEW

**Comment by amilcarlucas** [comment]
How close are we to remove RC_MAP ?

**Comment by peterbarker** [comment]
> How close are we to remove RC_MAP ?

I think my `die-rcmap-die` branch shows most of that.  Parameter conversion, scripting binding changes and simulink changes.

The other big thing is GCS adjustment.  QGC is going to require some surgery to understand `RCn_OPTION` 201 means roll, that sort of thing, rather than looking at `RCMAP_ROLL`, likewise with MissionPlanner.  I'd imagine several closed-source GCSs would also need updating.  These GCSs will need to understand both mechanisms for several years, of course.

I'm wondering about some interim arrangement whereby we magically update the `RCMAP` parameters from the `RCn_OPTION` parameters and vice-versa, throwing a warning when we update `RCn_OPTION` from `RCMAP`.

**Comment by IamPete1** [comment]
> I'm wondering about some interim arrangement whereby we magically update the `RCMAP` parameters from the `RCn_OPTION` parameters and vice-versa, throwing a warning when we update `RCn_OPTION` from `RCMAP`.

We could make RCMAP read only, so legacy GCSs can still show the correct thing on there RC calibration screen. I'm not sure if any try and change them, Mission Planner doesn't as far as I know.

**Review by IamPete1 — APPROVED** [review]
LGTM

**Review by tridge — APPROVED** [review]

**Pull request merged**
