### PR TITLE
add support for mavlink in-progress message

### PR DESCRIPTION
**Pull request by peterbarker**
```
MANUAL> Got COMMAND_ACK: PREFLIGHT_CALIBRATION: IN_PROGRESS
Calibration response (5)
AP: Updating barometer calibration
AP: Barometer calibration complete
AP: Airspeed 1 calibration started
AP: GPS 1: detected as u-blox at 230400 baud
Got COMMAND_ACK: PREFLIGHT_CALIBRATION: IN_PROGRESS
Calibration response (5)
AP: EKF2 IMU0 MAG0 initial yaw alignment complete
AP: EKF2 IMU1 MAG0 initial yaw alignment complete
Got COMMAND_ACK: PREFLIGHT_CALIBRATION: IN_PROGRESS
Calibration response (5)
AP: EKF3 IMU0 initialised
AP: EKF3 IMU1 initialised
AP: Airspeed 1 calibrated
Got COMMAND_ACK: PREFLIGHT_CALIBRATION: ACCEPTED
Calibrated
AP: EKF3 IMU0 tilt alignment complete
AP: EKF3 IMU1 tilt alignment complete
AP: EKF3 IMU0 MAG0 initial yaw alignment complete
AP: EKF3 IMU1 MAG0 initial yaw alignment complete
```

### CODE REVIEW

**Comment by peterbarker** [comment]
https://github.com/ArduPilot/MAVProxy/pull/1127 makes MAVProxy ignore the in-progress messages

**Comment by peterbarker** [comment]
Now also works when formatting SD cards:
image

**Comment by peterbarker** [comment]
Not without its cost:
```
Board              AP_Periph  blimp  copter  heli  plane  rover  sub
Durandal                      448    480     472   520    520    496
Hitec-Airspeed     0                                             
KakuteH7-bdshot               384    416     440   472    432    488
MatekF405                     368    384     384   352    424    504
Pixhawk1-1M                   360    344     368   504    424    536
f103-QiotekPeriph  8                                             
f303-Universal     0                                             
revo-mini                     360    352     344   296    480    472
skyviper-v2450                       288                         
```

... but it looks like the incremental cost might be 70-bytes-per-progressy-thing, assuming SkyViper doesn't have sdcard-wiping and

**Comment by peterbarker** [comment]
> what happens with no airspeed?

It successfully calibrates zero sensors.  Test added.

**Comment by tridge** [comment]
we can test on Sunday at SV

**Comment by peterbarker** [comment]
This one's been flown a bit now

**Comment by tridge** [comment]
good to merge when passes CI

**Review by tridge — APPROVED** [review]

**Pull request merged**
