### PR TITLE
Plane: implement RTL_CLIMB_MIN parameter

### PR DESCRIPTION
**Pull request by tridge**
this allows for an initial climb on RTL where roll is limited to
LEVEL_ROLL_LIMIT

### CODE REVIEW

**Comment by Hwurzburg** [comment]
test flew today....set RTL_CLIMB_MIN to 30.....never appeared to be invoked....here is a log: https://www.dropbox.com/s/lwr7g632diuusdh/RTL_CLIMB_MIN_TEST.bin?dl=0
this was testing with Throttle failsafe, circles then RTLs....so maybe I had to eliiminate the FS_SHORT action? or maybe FS RTLs get initialized differently?

**Comment by Redshifft** [comment]
Excellent, thought this got forgotten about !
All that is required is a simple climb first option in RTL, say  0= essentially off  to say 10sec.
Default it to 0 and the people that do not understand will not even know it's there.
The Failsafe does not even need to be considered as the fix is for RTL which currently will crash the Aircraft if you engage it or FS calls it at very low level because current action is instant Hard turn to home before gaining any height.
Thanks Tridge

**Comment by Redshifft** [comment]
I would also say any reference to Altitude would cripple its effectiveness as even flat looking fields could have 20 mtr height change - Has to be a timed wings level climb and which will get you out of any situation that a half sensible pilot could have a Failsafe in.

**Comment by tridge** [comment]
> never appeared to be invoked....here is a log:

thanks, I've fixed it. It only worked on the first RTL, which you did on the ground. I had forgotten to reset the flag on each new RTL

**Comment by tridge** [comment]
> I would also say any reference to Altitude would cripple its effectiveness as even flat looking fields could have 20 mtr height change

ok, so why does this mean it has to be a time? Just set RTL_CLIMB_MIN=20 and it will guarantee to climb 20m from whatever alt you are at when you enter RTL before it turns.

**Comment by Hwurzburg** [comment]
@tridge Thanks...will test fly again Sunday...rain tomorrow....I think the way its currently defined is optimum myself in terms of complexity vs solving the tree surfing/canyon diving issues...

**Comment by Redshifft** [comment]
> > I would also say any reference to Altitude would cripple its effectiveness as even flat looking fields could have 20 mtr height change
> 
> ok, so why does this mean it has to be a time? Just set RTL_CLIMB_MIN=20 and it will guarantee to climb 20m from whatever alt you are at when you enter RTL before it turns.

Provided it max climbs from current Altitude it will make no difference if that is Timed or measured :)
Whatever is easier for you to implement.

I saw "RTL_CLIMB_MIN to 30" and assumed  that meant  30mtr  ALT, if it had said  RTL_CLIMB_MIN to +30 I would have understood what was happening.

**Comment by RMFPV** [comment]
ha-ha
https://github.com/ArduPilot/ardupilot/issues/11180

there was mine too

thx a lot!

still would be nice to allow at least 10sec forward flight before start turning

**Comment by tridge** [comment]
> there was mine too

yep, this will allow us to close a few issues :-)

**Comment by Hwurzburg** [comment]
test flew today...working now ....I dont have the terrain to try it with terrain following....I am going to ask  if someone on RCG would like to try it and I will send him code for his FC based on Stable+this PR....but I dont see why this cant be merged now

**Comment by tridge** [comment]
thanks for testing Henry!

**Pull request merged**
