### PR TITLE
Parameters G2 enumerator added

### PR DESCRIPTION
**Pull request by EShamaev**
Added enumeration type for uniformity with main group of parameters.
In CPP file magic numbers changed to names in enumerator.

### CODE REVIEW

**Comment by EShamaev** [comment]
Compiler error in linux navio2 bebop configuration.

E: Unable to locate package gcc-4.9
E: Couldn't find any package by regex 'gcc-4.9'
E: Unable to locate package g++-4.9
E: Couldn't find any package by regex 'g++-4.9'

**Comment by magicrub** [comment]
This is not necessary and is also not done anywhere in the many other libraries that instantiate a param

**Comment by OXINARF** [comment]
I agree with @magicrub, every library that has parameters just sets the numbers without having an enum.
Also, both Copter and Rover have G2 too and use numbers as well. I don't think that adding an enum at this point brings any benefit, it is easy to manage the numbers.

**Comment by rmackay9** [comment]
.. but we appreciate the attempt to make thing better!

**Pull request closed without merging**
