### PR TITLE
HAL_ChibiOS: Add suport for OmnibusF4Pro board

### PR DESCRIPTION
**Pull request by sh83**
Added support for OmnibusF4Pro.
Tested boot, uarts, imu, external compass, barometer. Seems to work well.
Should work rcoutput, board led, buzzer(alarm). 
RCInput does not work, because timer channel conflict. Sdcard via spi and OSD chip are not supported yet.

Also this PR fixes some error in F405 table and adds support for complementary timer channels for RCOutput.

### CODE REVIEW

**Comment by tridge** [comment]
looks good, thanks!

**Comment by auturgy** [comment]
Bench tested on Furibee DarkMax (betaflight OmnibusF4SD target, mpu6000, buzzer, no compass or baro).  Boots and connects.  Can confirm board LED and buzzer works.

**Comment by sh83** [comment]
@auturgy, thanks for testing. The most intresting part is the motor output 1 and 2. It use timer complementary channel, no other chibios target doesnt use it yet.

**Comment by auturgy** [comment]
No worries. It was only a quick firmware flash to see if my board was compatible, and test led & buzzer. I’ll try to find some time later in the week to look a bit deeper.

Regards,

James

**Pull request merged**
