### PR TITLE
Sub: GCS_MAVLink fallthrough

### PR DESCRIPTION
**Pull request by WickedShell**
Coverity CID 142270. I don't think there is any reason to be falling through here :)

### CODE REVIEW

**Comment by jaxxzer** [comment]
I had noticed system_time coming through more frequently than expected in the past. Thanks!

**Comment by jaxxzer** [comment]
@peterbarker I was waiting for ci to finish to merge..

**Comment by WickedShell** [comment]
Was not intending to open it as a branch on master :)

@jaxxzer I pinged you on gitter for a couple of other stuff that coverity found.

**Comment by WickedShell** [comment]
@jaxxzer I think peter deleted it cause I did it in the wrong place, (which is fine) you can recreate it directly if you want, otherwise I can recreate it once I'm not trying to use web tools (and stuffing things up with them).

**Comment by jaxxzer** [comment]
@WickedShell I see, I'll follow up on gitter.

**Comment by peterbarker** [comment]
On Wed, 5 Jul 2017, WickedShell wrote:

> @jaxxzer I think peter deleted it cause I did it in the wrong place, (which

Nope, I deleted it because you asked me to :-)  I just assumed you were 
hoping to slip the branch creation under the radar....

**Comment by WickedShell** [comment]
Whhhhhaatt? I didn't do anything... Totally haven't generated ~10 e-mails pointing it out to 565 people :)

On a more serious note I will recreate it (without making a branch on master) unless @jaxxzer beats me to just doing it, no need to wait on me redoing the pr.

**Comment by OXINARF** [comment]
I went ahead and pushed it, slightly changing the commit message. Thanks!

**Pull request closed without merging**
