### PR TITLE
Fix vehicle-specific parameter values in Wiki

### PR DESCRIPTION
**Pull request by peterbarker**
This appears to fix many bugs in our Wiki documentation:

tracker doesn't do RC options:
https://ardupilot.org/antennatracker/docs/parameters.html#rc10-parameters

Copter doesn't do `FENCE_AUTOENABLE`:
https://ardupilot.org/copter/docs/parameters.html#fence-autoenable-fence-auto-enable

This is a huge delta in Parameter.rst - but everything I've looked at so far seems to correct according to the metadata.

### CODE REVIEW

**Comment by peterbarker** [comment]
[parameters-delta.txt](https://github.com/ArduPilot/ardupilot/files/6469990/parameters-delta.txt)

**Review by khancyr — APPROVED** [review]
Good one. 
I have look at Plane and copter change and they seem ok ! I guess my previous fix on this wasn't good enough, I didn't notice that most value weren't the good ones ...

**Comment by Hwurzburg** [comment]
still seems to be broken badly....there are three differences between master Rover params and after this...see below...it appears that only the VALUES tables are being removed....the arming_Check change worked since it only involved removing a few value items...not the entire param like fence autoenable and dont know if rc_lateral should really be removed....seems to have issues still...
diff
diff1

**Comment by khancyr** [comment]
We only apply the removal on values And bitmask so that is expected that everything beside those are unchange.
Parameters removal for vehicle is another thing

**Comment by Hwurzburg** [comment]
but @peterbarker  specifically stated that this removes FENCE_AUTOENABLE for copter above....should for ROVER also....so its not doing what Peter expects...I would expect that if a parameter has an @Values{vehicle} tag that any other vehicle not listed with another @Values{vehicle} tag would expect to have the param not emitted

**Comment by peterbarker** [comment]
> but @peterbarker specifically stated that this removes FENCE_AUTOENABLE for copter above....should for ROVER also....so its not doing what Peter expects...I would expect that if a parameter has an @values{vehicle} tag that any other vehicle not listed with another @values{vehicle} tag would expect to have the param not emitted

Right.  So I removed some magic around this.  The magic "has an @values{vehicle}" was actually on both the bitmask *and* values fields.  So I guess I should put that back in.

**Comment by peterbarker** [comment]
@Hwurzburg @khancyr I've pushed up another patch which resinstantes that Valus/Bitmask magic.

Here's a file which gives the delta between what you've been looking at and and after-this-patch (i.e. this is not a cumulative patch for thie PR, just hte change I made today).


[param-additional-changes.txt](https://github.com/ArduPilot/ardupilot/files/6481666/param-additional-changes.txt)

**Review by Hwurzburg — APPROVED** [review]
have validated the changes from master...cant swear about omissions, but changes are right....

**Pull request merged**
