### PR TITLE
CI: Does size matter ?

### PR DESCRIPTION
**Pull request by khancyr**
Rework from https://github.com/ArduPilot/ardupilot/pull/15702

It compiles master branch back, get the binaries for some boards, rebase the PR on top of master, build the binaries, use Bloaty to compare the binaries

PS: Only the taste matter ;-P

### CODE REVIEW

**Comment by tridge** [comment]
> Bloaty to compare the binaries

why do we want bloaty? What we want is to change in size of the bin file, not the elf (so it handles things like changes in embedded ROMFS).
Comparing the size of two bin files is a couple of lines of shell script

**Comment by khancyr** [comment]
reworked without bloaty
example output

````
Tools/scripts/pretty_diff_size.py -m second -s build/sitl/bin
Extracting binaries size on second
Get binary size of second/arducopter-heli
Get binary size of second/ardusub
Get binary size of second/antennatracker
Get binary size of second/ardurover
Get binary size of second/arducopter
Get binary size of second/arduplane
Success !
Extracting binaries size on build/sitl/bin
Get binary size of build/sitl/bin/arducopter-heli
Get binary size of build/sitl/bin/ardusub
Get binary size of build/sitl/bin/antennatracker
Get binary size of build/sitl/bin/ardurover
Get binary size of build/sitl/bin/arducopter
Get binary size of build/sitl/bin/arduplane
Success !

Binary           text             data         bss          total
---------------  ---------------  -----------  -----------  ---------------
arducopter-heli  1624 (+0.0375%)  0 (0.0000%)  0 (0.0000%)  1624 (+0.0349%)
ardusub          1816 (+0.0470%)  0 (0.0000%)  0 (0.0000%)  1816 (+0.0438%)
antennatracker   1640 (+0.0486%)  0 (0.0000%)  0 (0.0000%)  1640 (+0.0451%)
ardurover        1752 (+0.0445%)  0 (0.0000%)  0 (0.0000%)  1752 (+0.0413%)
arducopter       792 (+0.0181%)   0 (0.0000%)  0 (0.0000%)  792 (+0.0169%)
arduplane        1768 (+0.0410%)  0 (0.0000%)  0 (0.0000%)  1768 (+0.0381%)
````

**Review by tridge — APPROVED** [review]
pending CI passing

**Comment by amilcarlucas** [comment]
CI pass. Can it be merged?

**Pull request merged**
