### PR TITLE
AP_Frsky_Telem: reworked _statustext_queue.empty() check

### PR DESCRIPTION
**Pull request by floaledm**
Followup of #4863
Revised get_next_msg_chunk() to check within that function whether the queue is empty (instead of outside of the function) before sending the data (when calling send_uint32()).

### CODE REVIEW

**Comment by floaledm** [comment]
There's not nearly as many changes as the "Files changed" shows...
All I did is have get_next_msg_chunk() return false if the queue is empty and true if not, and if it returns true, the next step is sending _msg_chunk.chunk which used to be what get_next_msg_chunk() returned...

**Comment by magicrub** [comment]
merged this a minor change here https://github.com/ArduPilot/ardupilot/commit/99d48d8bbda14f60428863ceea8e15de6f7ab73b?w=1

PROTIP: to remove white space from a commit/diff, add ?w=1 to the URL

**Comment by magicrub** [comment]
@floaledm have you run this on your system?
`git config --global core.autocrlf false`

**Comment by floaledm** [comment]
Thanks Tom for modifying and merging. I made note of the pro tip! Running `git config --global core.autocrlf` shows `false`, so I assume it's set correctly...

**Pull request closed without merging**
