### PR TITLE
Use core as instance number when logging EKF data

### PR DESCRIPTION
**Pull request by peterbarker**
Also renames methods to be more consistent.  The fact that the packet shape is dictated by a particular structure doesn't mean the methods should be called that.

### CODE REVIEW

**Comment by peterbarker** [comment]
image

**Comment by peterbarker** [comment]
image

**Comment by peterbarker** [comment]
```
MatekF405-Wing

master:
  bin/arducopter  973104  1352  129800  1104256
pr/ekf3-instance-logging:
  bin/arducopter  972220  1352  129804  1103376
```

!

**Comment by amilcarlucas** [comment]
Very nice one!!!

**Pull request merged**
