### PR TITLE
AP_Scripting: add send named float binding

### PR DESCRIPTION
**Pull request by IamPete1**
This allows scripts to send named floats, this is useful for streaming interesting numbers to the GCS

https://github.com/ArduPilot/MissionPlanner/issues/2346

### CODE REVIEW

**Comment by IamPete1** [comment]
rebased, I still think this is very useful and we don't have the direct MAVLink method yet

**Comment by WickedShell** [comment]
That's actually on my to be rebased and merge within the next month list...
If I get it rebased can you test it?

**Review by tridge — APPROVED** [review]

**Comment by IamPete1** [comment]
@WickedShell happy to test, I still think this method deserves its own binding, its very useful for debugging.

**Comment by WickedShell** [comment]
> @WickedShell happy to test, I still think this method deserves its own binding, its very useful for debugging.

I guess once the general MAVLink stuff is in I'd rather not, simply to try and minimize flash consumption, and reduce the general overhead we impose on every script. I can give a straight example of sending a named float though, which could be easily used in other scripts. (I know, obligatory include comments here)

**Review by tridge — APPROVED** [review]

**Pull request merged**
