### PR TITLE
AP_Periph: CubeOrange-periph to use same APJ_BOARD_ID as CubeOrange

### PR DESCRIPTION
**Pull request by magicrub**
CubeOrange-periph to use same APJ_BOARD_ID as CubeOrange. Since the bootloader is 128k, and the hardware is the same, it is a safe change. That is not the case for CubeBlack.

Downsides
- this was implemented so users could not accidently load an AP_Periph image into a "normal" aircraft. That security is being removed.

Upsides:
- The risk of loading in a different/wrong image is the same as someone loading copter into a plane on accident. Has not been an actual problem.
- Users have been wanting to test AP_Periph on their CubeOrange and this different ID has made it very difficult.
- It's the same hardware so it makes sense to use the same hardware ID
- Being able to load in a different vehicle type is a useful way to do a hard wipe on the params.

### CODE REVIEW

**Comment by magicrub** [comment]
I don't know how to fix the Semaphore error.

**Comment by bugobliterator** [comment]
I don't know about this change for me specifically, as I mostly have both CubeOrange and CubeOrange-periph connected over USB, while developing. It could get messy with firmwares swapping and loading on the wrong board.

**Review by bugobliterator — COMMENTED** [review]
<div class="js-discussion js-socket-channel ml-0 pl-0 ml-md-6 pl-md-3" data-channel="eyJjIjoibWFya2VkLWFzLXJlYWQ6NTY5NzI4OCIsInQiOjE2MjEzNDQzNDh9--cdf53a0684611fc7e34564b79257408385f4c5734ecea917f2fe9888c1a890fa" data-channel-target="MDExOlB1bGxSZXF1ZXN0NjM2MDk2ODQz" style="box-sizing: border-box; margin-left: 40px !important; padding-left: 16px !important; color: rgb(203, 198, 192); font-family: -apple-system, system-ui, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(10, 14, 18); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="js-timeline-item js-timeline-progressive-focus-container" data-gid="MDEyOklzc3VlQ29tbWVudDg0MzE5MDEzNQ==" style="box-sizing: border-box;"><div class="TimelineItem js-comment-container" data-gid="MDEyOklzc3VlQ29tbWVudDg0MzE5MDEzNQ==" data-url="/_render_node/MDEyOklzc3VlQ29tbWVudDg0MzE5MDEzNQ==/timeline/issue_comment?variables%5BdeferredCommentActions%5D=false" style="box-sizing: border-box; position: relative; display: flex; padding: 16px 0px; margin-left: 16px;"><div class=" timeline-comment-group js-minimizable-comment-group js-targetable-element TimelineItem-body my-0 " id="issuecomment-843190135" style="box-sizing: border-box; margin-top: 4px; margin-bottom: 0px !important; min-width: 0px; max-width: 100%; color: var(--darkreader-text--color-timeline-text); flex: 1 1 auto;"><div class="ml-n3 timeline-comment unminimized-comment comment previewable-edit js-task-list-container editable-comment js-comment timeline-comment--caret reorderable-task-lists current-user" data-body-version="3f32f0f211dfed2ecbd5129c32899eeea584d5d48da77e8f4c47007674bcc8d6" data-unfurl-hide-url="/content_reference_attachments/hide" style="box-sizing: border-box; margin-left: -16px !important; position: relative; color: var(--darkreader-text--color-text-primary); background-color: var(--darkreader-bg--color-bg-primary); border-color: var(--darkreader-border--color-box-border-info); border-top-style: ; border-top-width: ; border-right-style: ; border-right-width: ; border-bottom-style: ; border-bottom-width: ; border-left-style: ; border-left-width: ; border-image-source: ; border-image-slice: ; border-image-width: ; border-image-outset: ; border-image-repeat: ; border-radius: 6px;"><div class="edit-comment-hide" style="box-sizing: border-box;"><task-lists sortable="" style="box-sizing: border-box;">I don't know about this change for me specifically, as I mostly have both CubeOrange and CubeOrange-periph connected over USB, while developing. It could get messy with firmwares swapping and loading on the wrong board.</task-lists></div><form class="js-comment-update" id="issuecomment-843190135-edit-form" action="https://github.com/ArduPilot/ardupilot/issue_comments/843190135" accept-charset="UTF-8" method="post" style="box-sizing: border-box;"></form></div></div></div></div><div id="partial-timeline" class="js-timeline-marker js-socket-channel js-updatable-content" data-channel="eyJjIjoicHVsbF9yZXF1ZXN0OjYzNjA5Njg0MyIsInQiOjE2MjEzNDU4NTh9--57ae3eefb6833b67671831f6ca3adc2d3cf1e529edb9da347e4f16a14f782109" data-url="/_render_node/MDExOlB1bGxSZXF1ZXN0NjM2MDk2ODQz/pull_requests/unread_timeline?variables%5BdeferCommitBadges%5D=false&amp;variables%5BdeferStatusCheckRollups%5D=false&amp;variables%5BdeferredCommentActions%5D=true&amp;variables%5BhasFocusedReviewComment%5D=false&amp;variables%5BhasFocusedReviewThread%5D=false&amp;variables%5BtimelinePageSize%5D=30&amp;variables%5BtimelineSince%5D=2021-05-18T13%3A50%3A58Z" data-last-modified="Tue, 18 May 2021 13:50:58 GMT" data-gid="MDExOlB1bGxSZXF1ZXN0NjM2MDk2ODQz" style="box-sizing: border-box;"></div></div><div class="discussion-timeline-actions" style="box-sizing: border-box; background-color: var(--darkreader-bg--color-bg-canvas); border-top: 2px solid var(--darkreader-border--color-border-primary); color: rgb(203, 198, 192); font-family: -apple-system, system-ui, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div id="partial-pull-merging" class="pull-merging js-pull-merging js-socket-channel js-updatable-content js-pull-refresh-on-pjax " aria-live="polite" data-channel="eyJjIjoicmVwbzo0ODI2Nzk2MTpicmFuY2g6cHIvcGVyaXBoX29yYW5nZV9ibF9pZCIsInQiOjE2MjEzNDU4NTh9--eacd49c3aa63803b2278a684967fc0f7639a0b96ba11eade2d8517afa0f9d99f eyJjIjoicmVwbzo3NTEyNDg0OmJyYW5jaDptYXN0ZXIiLCJ0IjoxNjIxMzQ1ODU4fQ==--f86777a76b1b5da89e06d360d1f25b69acdb6fcd3572e56cc1646963a3520322 eyJjIjoicmVwbzo3NTEyNDg0OmNvbW1pdDplZjExMzYwNDE0ZmE2NTQwOGJlM2ZjZTg3YzZlNDQwYTMwYWIwZGU1IiwidCI6MTYyMTM0NTg1OH0=--e584ddd869e93ae956cda23494fe9b18d06b7a9370eb035a539fd98bebdc630b eyJjIjoiaXNzdWU6ODgyNTY5MzAwOnN0YXRlIiwidCI6MTYyMTM0NTg1OH0=--ea3371c4babc5c6c38d99dfb9deb4be10813426f5de422fc9c1de3be5dd1530e eyJjIjoicHVsbF9yZXF1ZXN0OjYzNjA5Njg0MzpyZXZpZXdfc3RhdGUiLCJ0IjoxNjIxMzQ1ODU4fQ==--1e7ad99c26df7191673a7694a0f645ae8213c6cccd04633fa20c2de9d3a67d0b eyJjIjoicHVsbF9yZXF1ZXN0OjYzNjA5Njg0Mzp3b3JrZmxvd19ydW4iLCJ0IjoxNjIxMzQ1ODU4fQ==--84a97482bfc514c3c7ffa9525efa73bce3181145ac9a17e1d4969f870d00e729" data-url="/ArduPilot/ardupilot/pull/17396/show_partial?merge_type=rebase&amp;partial=pull_requests%2Fmerging" style="box-sizing: border-box;"><br class="Apple-interchange-newline"></div></div>

**Comment by magicrub** [comment]
@bugobliterator here's two solutions to your developer corner case

Undefine this in your periph app
HAL_PERIPH_LISTEN_FOR_SERIAL_UART_REBOOT_CMD_PORT

And/or

Undefine USB in your periph bootloader.

And/or

Buy a USB hub that has power selectors like this
https://www.amazon.com/dp/B00JX1ZS5O/ref=cm_sw_r_cp_apa_glt_fabc_ZEQW84WHMRVMBYRY3NPJ

**Comment by bugobliterator** [comment]
> @bugobliterator here's two solutions to your developer corner case
> 
> Undefine this in your periph app
> HAL_PERIPH_LISTEN_FOR_SERIAL_UART_REBOOT_CMD_PORT
> 
> And/or
> 
> Undefine USB in your periph bootloader.
> 
> And/or
> 
> Buy a USB hub that has power selectors like this
> https://www.amazon.com/dp/B00JX1ZS5O/ref=cm_sw_r_cp_apa_glt_fabc_ZEQW84WHMRVMBYRY3NPJ

Except that i actually use the USB to do firmware updates on both using --upload. Even with power selector, Its going to add an extra step, which if I forget is going to cause issue.

**Comment by magicrub** [comment]
Can you propose another solution to getting people who have CubeOranges onto AP_Periph? Lots of people ask about it...

**Comment by WickedShell** [comment]
> Can you propose another solution to getting people who have CubeOranges onto AP_Periph? Lots of people ask about it...

Force load it the first time, then update bootloader from the force loaded firmware?

**Comment by magicrub** [comment]
@WickedShell  There's a "force" option in the bootloader? Well crap, lets do that! I didn't even realize that!

**Comment by WickedShell** [comment]
The check of ID is in the computer side of the uploader. If you just add `--force` to the uploader.py script it ignores the ID's mismatching and happily uploads. I've done a ton of testing then swapping back to normal firmware with a cube orange this way.

**Comment by magicrub** [comment]
Closing, lets go with that route. Thanks @WickedShell !!!

**Pull request closed without merging**
