### PR TITLE
Plane: Quadplane: rework assistance check

### PR DESCRIPTION
**Pull request by IamPete1**
This reworks the assistance check into a new sub class. There are also a number of functional  changes:

- This more carefully resets the assistance state if not in a mode that checks assistance. Currently if you trigger alt assist and enter a VTOL mode and then re-enter FW at a later point while still under the set alt you will get no delay and no second warning message because the `in_alt_assist` and `alt_error_start_ms` are not cleared.
- Force flare no longer changes the assist state, instead assist checks for force flare. This means that the state is still where the user left it after the flare is done.
- All types of assist are checked at once. Currently we stop checking when the assistance should be triggered. This means in speed assist altitude is not checked. We have a delay for altitude assist and angle, so it is possible to come out of speed assist briefly before starting alt assist. 
- This adds a clear delay of double the set trigger delay (angle and alt only). This prevents a momentary clearing of the threshold from stopping assistance. We currently have a trigger delay and no clear delay, so if oscillating around the threshold we favor not assisting this change means we favor assisting.  

This will need a fair bit of testing, so far it has had none. I have opened the PR so we can get consensus on the desired behavior.

We might also want to re-work the messages, currently you can get a alt assisting message while still in speed assistance, we might want the messages to behave as before, so as soon as the speed is reached the alt assistance message is given. However it is quite nice to get the message early, it saves attempting the transition only to reach your set speed and find your too low.

We might also want to re-issue the angle and alt assistance warnings periodically. 

A followup PR could move all these functions into a new file, `quadplane.cpp` it is getting big....

### CODE REVIEW

**Comment by IamPete1** [comment]
Added logging of the various states to the QTUN message, the existing assist uint8 becomes a flags bitmask, so no increase in log size.

**Comment by IamPete1** [comment]
A normal transition, assist enabled and speed until speed reached, then just assist enabled:
image

Alt assist example changing the threshold to fake low alt with a 10 seconds assist delay to show the triggering and clearing timeouts:
image

A too low transition. First assistance + speed. Then assistance + speed + alt. Then speed is reached so assistance + alt. 
image

**Comment by IamPete1** [comment]
Rebased and updated assist autotest to check alt assist and transition fail action.

**Comment by IamPete1** [comment]
To see what it might look like the last commit moves the assist functionality into new files.

**Comment by tridge** [comment]
I like the concept, but needs a bunch of testing

**Comment by IamPete1** [comment]
Rebased.

**Comment by IamPete1** [comment]
Tested all types of assist with Alti Transition in realflight. All working as expected. Log here: https://drive.google.com/file/d/1sLEzbqd3NTciKZ3HMAg2rtyuZozzm02N/view?usp=sharing

**Review by tridge — APPROVED** [review]

**Pull request merged**
