### PR TITLE
Copter: correct namespacing of Copter modes

### PR DESCRIPTION
**Pull request by peterbarker**
This makes us look like Rover and Plane in terms of namespacing for the
Mode classes, and removes a wart where we #include mode.h in the middle
of the Mode class.

This was done mechanically for the most part.

I've had to remove the convenience reference for ap as part of this.

### CODE REVIEW

**Comment by rmackay9** [comment]
A fine change but it'll cause havoc for any open PRs and/or backports (although backports were already getting quite tough).

**Comment by peterbarker** [comment]
@rmackay9 I'm quite aware of the conflicts this will cause in my own PRs and WIPs.  OTOH, this really should be done...

**Comment by OXINARF** [comment]
I like the change because I hate the include, I hate the change because Mode shouldn't be a top citizen class 😄 If only C++ had namespaces 😜

Regarding delaying this, progress shouldn't be stopped by open PRs or we'll never move forward (312 open PRs at this moment...). Backporting is important, but I don't think this PR makes things particularly difficult for that.

**Comment by rmackay9** [comment]
Merged, thanks!  Sorry to those PRs that hit conflicts because of this! :-(

**Pull request merged**
