### PR TITLE
ArduPlane: Fix long failsafe never working if FS_SHORT_ACTN=3

### PR DESCRIPTION
**Pull request by Jaaaky**
This solves an issue when FS_SHORT_ACTN=3 aka Disabled, which caused to never trigger long_failsafe.

### CODE REVIEW

**Comment by Jaaaky** [comment]
I could not find the exact problem with the failed check. I do not know much about AutoTests. Error is ""ThrottleFailsafe (Fly throttle failsafe)": NotAchievedException('Receiver not healthy',)" , but I couldn't find what caused it.

**Comment by WickedShell** [comment]
Long failsafes are definitely triggerable with short failsafes disabled (intentionally tested this last week). Did you have a specific scenario I can test?

**Comment by Jaaaky** [comment]
> Long failsafes are definitely triggerable with short failsafes disabled (intentionally tested this last week). Did you have a specific scenario I can test?

You mean with "FS_SHORT_ACTN=3" ? Or some other way to disable it?

For me I've tested it and it never triggered RTL nor FAILSAFE was displayed on MissionPlanner.

After this patch it works. By the way, the fix is for ArduPlane; I've no idea about other vehicles.

**Comment by WickedShell** [comment]
I tested in plane, I've also tested this without the short and long timeouts being the same and had it work.

```
FS_GCS_ENABL     1.000000
FS_LONG_ACTN     1.000000
FS_LONG_TIMEOUT  15.000000
FS_SHORT_ACTN    3.000000
FS_SHORT_TIMEOUT 15.000000
```

**Comment by Jaaaky** [comment]
Could you please retest with all at default values except FS_SHORT_ACTN set to 3?

> FS_GCS_ENABL 0
> FS_SHORT_TIMEOUT 1.5
> FS_LONG_ACTN 0
> FS_LONG_TIMEOUT 5

**Comment by Jaaaky** [comment]
By the way, the PR fixes RC failsafe bug, not GCS. I didn't test GCS failsafe.

**Comment by WickedShell** [comment]
The behaviour here depends on what mode you are in. Manual/FBW/Cruise and friends would RTL, but Auto/RTL/Guided/Loiter wouldn't care. Quad modes would go QLAND, and QLAND/QRTL/RTL wouldn't change. What are you expecting to see that you aren't seeing?

I was testing no RC input.

**Comment by Jaaaky** [comment]
I've tested No RC with Manual/FBW/Cruise that should trigger RTL on long failsafe. It works when I set SHORT_FS_ACTN to default - circle - but not when set to 3 - disabled -.

**Comment by WickedShell** [comment]
Just simmed it, put the plane in manual, turned off the RC input and the plane went RTL.

```
FS_GCS_ENABL 1
FS_SHORT_ACTN 3
FS_SHORT_TIMEOUT 1.5
FS_LONG_ACTN 0
FS_LONG_TIMEOUT 5
```

**Comment by Jaaaky** [comment]
@WickedShell I've tested tens of times, with plane3.9 and master.
I confirm my initial finding and that my patch works.

```
FS_GCS_ENABL     1
FS_LONG_ACTN     0
FS_LONG_TIMEOUT  5
FS_SHORT_ACTN    3
FS_SHORT_TIMEOUT 1.5
```

RTL is never triggered. By the way, I'm afraid your RC receiver is the cause for this false negative result, some receiver can send some output on disconnection which causes flight mode change. I'd such issue before.

**Comment by tridge** [comment]
@Jaaaky I've just tested it and @WickedShell is correct that it works correctly already
I've got a log here:
http://uav.tridgell.net/tmp/short-fs-3.bin
Can you provide a log of master failing in SITL? Using SIM_RC_FAIL=1 to cause an R/C failure is the usual method
Or a log (tlog or bin) of real vehicle failing would be equally as good

**Comment by Jaaaky** [comment]
I've tested on real vehicles not in SITL. I'll retest and send a log as I didn't have sdcard during previous tests.

**Comment by Jaaaky** [comment]
I've tested on SITL. There is no bug there. I'll retest on real vehicle and send the logs.

**Comment by tridge** [comment]
@Jaaaky thanks. tlog should also be sufficient

**Comment by Jaaaky** [comment]
Attached is the tlog
At 1st I've tested with default params, you can see how it switched to CIRCLE then RTL. Then changed FS_SHORT_ACTN to 3 and tested many times and no RTL was triggered.
On messages you can see the Throttle Failsafe ON/OFF but no long failsafe action is triggered.
The test is done using master arduplane.
[2019-08-19 13-09-39.zip](https://github.com/ArduPilot/ardupilot/files/3515335/2019-08-19.13-09-39.zip)

**Comment by tridge** [comment]
@Jaaaky thanks! I'll take a look

**Comment by Jaaaky** [comment]
@tridge Have you reviewed the log?

**Comment by Jaaaky** [comment]
I've run the autotest in pr #12095 . It fails on master and works fine with my pr.

**Comment by tridge** [comment]
I've pushed an alternative fix for this issue to the same PR branch. This works for both low throttle and failsafe protocol flags

**Comment by Jaaaky** [comment]
Thanks, Closing this.

**Comment by peterbarker** [comment]
On Sun, 25 Aug 2019, Andrew Tridgell wrote:

> @tridge requested changes on this pull request.
> 
> sorry for doubting you previously, this is indeed a real bug. Unfortunately your fix seems to fix the failsafe trigger using low thr but breaks failsafe
> trigger using protocol flags.
> For example, if you test your patch with "param set SIM_RC_FAIL 1" in SITL you'll find it no longer triggers a failsafe. It does trigger with "rc 3 900"
> though.
> What we need to do is treat the two conditions equally
> @peterbarker we need the autotest to test both

The autotest already should be testing SIM_RC_FAIL=1 + FS_SHORT_ACTION=3 
here: 
https://github.com/ArduPilot/ardupilot/pull/12095/files#diff-0f046f609daafca0ffae999d20872ac5R887

I took @Jaaaky's comment to indicate all tests pass.

**Pull request closed without merging**
