### PR TITLE
Mavlink smart battery support

### PR DESCRIPTION
**Pull request by panky0**
this should provide support for sending battery data over mavlink to support this upcoming product: [www.betechnics.com ](https://betechnics.com/) homepage still work in progress....

### CODE REVIEW

**Review by magicrub — CHANGES_REQUESTED** [review]
- Please rename to "MAVLink" instead of "Mavlink_SMart_Battery". All batteries in this library are 'smart'
- your hijacking of the mavlink msgs to pipe them directly to the backend of the library is cheating/wrong, it makes many bad assuptions. Pass it through the front end AP_BattMonitor instance like how all the other drivers do it (UAVCAN?DroneCAN is an exception here for some crazy reasons). Take a look at AP_Mount library for how it handles mavlink msgs. It also allows a more graceful integration with AP_Periph that way too.

**Comment by magicrub** [comment]
Please also squash your WIP commits

**Comment by panky0** [comment]
> Please also squash your WIP commits

still learning how to use git; i think i messed some stuff up when trying to squash my WIP commits

**Comment by panky0** [comment]
-> https://github.com/ArduPilot/ardupilot/pull/21399

**Comment by ysfkg** [comment]
Hello

**Pull request closed without merging**
