### PR TITLE
SITL: Change barometer noise to 2cm for Sub

### PR DESCRIPTION
**Pull request by patrickelectric**
From MS5837-30BA Ultra Small Gel Filled Pressure Sensor datasheet
    The measurement depth system has a water depth resolution of 2 mm.

    A standard deviation of 1.951 cm was the best result in experimental conditions

### CODE REVIEW

**Comment by rmackay9** [comment]
@jaxxzer, you're happy with this?  If yes, we can push straight in.

**Comment by jaxxzer** [comment]
@patrickelectric The resolution is 2mm, the rms noise is larger, I would guess 1-2cm. Let's try 1cm?

**Comment by OXINARF** [comment]
Why isn't this change made in Tools/autotest/default_params/sub.parm?

**Comment by patrickelectric** [comment]
@jaxxzer With our logs, the best standard deviation was around 2cm. I'm updating to use this value.

**Comment by jaxxzer** [comment]
@patrickelectric I think we can just move this to the .param file and remove the patch from SITL.cpp.

**Comment by patrickelectric** [comment]
@jaxxzer done. 
The CI is failing, it appears that someone is merging things without waiting tests to finish..

**Comment by rmackay9** [comment]
@patrickelectric, the autotests are not very reliable sadly with false failures happening quite regularly.  If we kick off the jobs again, they often pass.  @peterbarker and @khancyr have taken over as maintainers of the copter and rover tests so that may help with reliability.  There are some issues with the semaphore machines not being cleaned which perhaps @tridge or @OXINARF may resolve..

**Pull request merged**
