### PR TITLE
Sub: Remove void as parameter

### PR DESCRIPTION
**Pull request by patrickelectric**
- Remove unnecessary void as parameter in C++ code

Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

### CODE REVIEW

**Comment by peterbarker** [comment]
On Thu, 28 Jun 2018, Patrick José Pereira wrote:

>  *  Remove unnecessary void as parameter in C++ code

tridge has a slight preference for keeping these.  Insanity, but there you 
go :-)

**Comment by tridge** [comment]
I do prefer to have them, I find it clearer

**Comment by rmackay9** [comment]
I prefer not to have the "void" but in any case, as @WickedShell says, it's a sub change so it's up to you guys.

**Comment by rmackay9** [comment]
@jaxxzer, shall I push the merge button?  (or you can of course).

**Comment by jaxxzer** [comment]
I prefer to have them also. But I am open to changing my preference if there is a good argument against taking them out.

**Comment by patrickelectric** [comment]
ArduSub, ArduCopter and Rover does have more function definition with `()` than `(void)`, between 3~5x, ArduPlane is a exception (`(void)` wins by ~3.5x).
I did a simple regex and this is the result with sub: http://ix.io/1fre

The idea behind this PR is to add more code consistency in the ArduSub project, I understand the ideas behind `(void)`, and if it's a consensus in the ArduPilot project to use it, this need to be added in [code style documentation](http://ardupilot.org/dev/docs/style-guide.html) and used in future patchs.

Besides the number of function definitions with `()`, `(void)` is unnecessary in C++ code (AFAIK) and it's more 4 chars to type and maintain :)

**Pull request merged**
