### PR TITLE
AC_AutoTune: allow save of completed axes

### PR DESCRIPTION
**Pull request by tridge**
this allows you to stop the tune by disarming part way through and
save the completed axes

### CODE REVIEW

**Comment by rmackay9** [comment]
LGTM

**Comment by rmackay9** [comment]
I think the "axes_completed = 0;" needs to be moved to "backup_gains_and_initialise()"...

**Comment by tridge** [comment]
@rmackay9 it doesn't change that behavior (ie. it continues from where it left off)

**Comment by tridge** [comment]
@rmackay9 I've moved axes_completed=0, as you suggested

**Comment by rmackay9** [comment]
Merged, thanks!

**Pull request merged**
