### PR TITLE
AP_Motors: example: add ability to dump all matrix motor layouts in JSON format

### PR DESCRIPTION
**Pull request by IamPete1**
This makes a json file such as this: 

[MotorsJSON.txt](https://github.com/ArduPilot/ardupilot/files/11511969/MotorsJSON.txt)

This allows tools to give extra info on motor test pages or frame selection, only matrix types currently but we could others manualy.

A example wiki page from @yuri-rage 
https://discuss.ardupilot.org/t/copter-wiki-motor-diagram-overhaul/101046/24?u=iampete

My Mission planner attempt:
https://github.com/ArduPilot/MissionPlanner/pull/3043

To get json just run example and dump to file, `./build/linux/examples/AP_Motors_test p > test.json`

This is a snippet:
```
{
	"Version": "AP_Motors library test ver 1.1",
	"layouts": [
		{
			"Class": 1,
			"ClassName": "QUAD",
			"Type": 0,
			"TypeName": "PLUS",
			"motors": [
				{
					"Number": 1,
					"TestOrder": 2,
					"Rotation": "CCW",
					"Roll": -0.5000,
					"Pitch": -0.0000
				},
				{
					"Number": 2,
					"TestOrder": 4,
					"Rotation": "CCW",
					"Roll": 0.5000,
					"Pitch": -0.0000
				},
				{
					"Number": 3,
					"TestOrder": 1,
					"Rotation": "CW",
					"Roll": -0.0000,
					"Pitch": 0.5000
				},
				{
					"Number": 4,
					"TestOrder": 3,
					"Rotation": "CW",
					"Roll": 0.0000,
					"Pitch": -0.5000
				}
			]
		},
         ]
}
```

### CODE REVIEW

**Comment by yuri-rage** [comment]
Excellent! I've made some more progress on the wiki page (mostly cosmetic). I should have at least a WIP PR later this week after cleaning up some ugliness in the JS and SVG structure.

**Comment by yuri-rage** [comment]
As I work through the motor diagramming, I've noticed a couple of things:
The Y6 frame class is the only one that supports a "default" type, which results in 17 of the same options. That becomes messy.
The NYT frame classes have no motor rotation direction defined. I'm sure there's good reason for that, and I'm inclined to skip diagrams for them.

**Comment by IamPete1** [comment]
@yuri-rage 

Yep, Y6 is odd. 

NYT stands for No Yaw Torque. There only available on plane where you might have tilts or control surfaces to use for yaw. There are no rotation directions because it doesn't matter to the mixer.  

For Deca the standard X layout is also the clock wise X layout. DECA X is the same as DECA CW X. The CW (clockwise) frames have the same motor ordering as test order (A = 1, B =2 ect) that makes it much easier to get the ordering right. (That is what they all should be really, but were locked into odd orderings from back before it was easy to re-assign the motor outputs)

**Comment by yuri-rage** [comment]
Ah! I'm misreading the DECA defs. There are two frames defined at once, essentially.

I'll make some customization to the diagram output to account for the odd cases, as expected. Just needed to understand.

**Review by tridge — APPROVED** [review]

**Review by rmackay9 — APPROVED** [review]

**Comment by amilcarlucas** [comment]
Thanks for this. I'm using it in the ArduPilot methodic configurator

**Pull request merged**
