### PR TITLE
Clean:remove the eclipse temple files.

### PR DESCRIPTION
**Pull request by Linjieqiang**

### CODE REVIEW

**Comment by amilcarlucas** [comment]
Sorry, I do not think this is a good idea. I think making them active is a better idea. What was the rationale behind hiding them in the first place ?

**Comment by rmackay9** [comment]
I probably support removing these files.  I don't use them because it's so easy to setup eclipse anyway..

**Comment by lucasdemarchi** [comment]
> Sorry, I do not think this is a good idea. I think making them active is a better idea. What was the rationale behind hiding them in the first place ?

If it's not working it gives the wrong impression for new people.

Unless it's actively used, maintained and makes life easier for devs, there's no point in keeping it in the tree. Otherwise we would add a config for each and every code editor in the tree. Btw, I'd much rather add a .editorconfig file (http://editorconfig.org/)  that is compatible with a bunch of editors.

**Comment by lucasdemarchi** [comment]
@Linjieqiang thanks, applied.

**Comment by Linjieqiang** [comment]
@lucasdemarchi I also want to remove some files in master branch.Such as "reformat.sh,uncrustify_cpp.cfg,uncrustify_headers.cfg".I think these files were unused.

**Comment by lucasdemarchi** [comment]
@Linjieqiang I don't know. I'm sure some of them are used by developers.  We actually need a one solution to fix formatting so we can simply call the script and have *parts* of the code fixed for good.

I use clang-format which comes very close to our coding style, but this and all the others you mentioned have strengths and weaknesses. If you can try these solutions and provide a feedback which one is better it would be good.  Ideally we should be able to reformat just the commit being submitted and not the entire file (as often this causes false positives)

**Comment by Evan1010** [comment]
Ah, so this is why the Eclipse instructions for setting up Ardupilot for Eclipse Build on Windows did not work as expected yesterday.

Any recommendations for alternative IDEs?

Currently Eclipse cannot get over the supposed typing errors, where every function is thought to have invalid argument types (maybe has to do with template?).

**Pull request merged**
