### PR TITLE
Fixed SITL tricopter model

### PR DESCRIPTION
**Pull request by tridge**
This fixes the SITL tricopter model, which was rotating the rear motor on the wrong axis.
Note that this also changes yaw tuning for all models. The yaw torque we were providing on all motors was an order of magnitude too high. We needed the rear motor tilted at 60 degrees just to hold steady, which is completely unrealistic.
We need to look at re-tuning yaw on all builting SITL models.

### CODE REVIEW

**Comment by peterbarker** [comment]
Should be removing from the blacklist of known-broken frames in the FlyEachFrame test here: https://github.com/ardupilot/ardupilot/blob/master/Tools/autotest/arducopter.py#L6621 so it doesn't get trivially broken again.

**Comment by tridge** [comment]
@peterbarker thanks, done

**Comment by tridge** [comment]
we might like to get @lthall or @priseborough to check the vector maths in SIM_Motor.cpp

**Comment by rmackay9** [comment]
Great! thanks for finding this.  I suspect we can simply revert this commit that I did last week which reduced all the gains by about a factor of 10.  https://github.com/ArduPilot/ardupilot/pull/17634

**Comment by tridge** [comment]
> I suspect we can simply revert this commit that I did last week which reduced all the gains by about a factor of 10

ahh, great!

**Comment by rmackay9** [comment]
@tridge,

Can you replace the "revert" commit with the last commit from this branch: https://github.com/rmackay9/rmackay9-ardupilot/commits/tridge-yaw-tune-fix

I've gone through and re-tested tri, quad, hexa, octa, octa-quad, dodeca-hexa and deca copters in SITL and they all fly better with just this commit instead of reverting the previous changes.

**Review by rmackay9 — DISMISSED** [review]
please pull in the last commit from this branch in place of the revert, thanks!

https://github.com/rmackay9/rmackay9-ardupilot/commits/tridge-yaw-tune-fix

**Comment by peterbarker** [comment]
Closes https://github.com/ArduPilot/ardupilot/issues/17645

**Comment by tridge** [comment]
> please pull in the last commit from this branch in place of the revert, thanks!

done, thanks for the tuning!

**Pull request merged**
