### PR TITLE
Tools: Added name(Gokul) to GIT_Success.txt   :)

### PR DESCRIPTION
**Pull request by thelowercaseguy**
Adding myself (Gokul) onto the list :)

### CODE REVIEW

**Comment by thelowercaseguy** [comment]
@rmackay9 Sure, I have done so. Could you check and let me know if there are any more issues
Thank you :)

**Comment by khancyr** [comment]
hello @thelowercaseguy,

you need to change the commit message not the pull request title !
you can use the `git commit --amend` cmd to update it and force push with `git push -f` !

**Comment by thelowercaseguy** [comment]
Hi @khancyr I had done it before, but I wasn't in sync with the master branch. Nevertheless, I have updated it. If there are any more issues please let me know.
Thank you once again!

**Comment by khancyr** [comment]
Good job on changing the commit message, but as you sync with master you made another mistake ! 

Sorry, we are quite pedantic on the commit, but that keeps the git flow clean.

We don't use the merge commit. You will need to rebase on master : `git rebase master` to get rid of the merge commit ! 
For further contribution, if there isn't any conflict with master you don't need to do the rebase as it can be done with github when we do the final merge.

**Comment by thelowercaseguy** [comment]
Sure sir will keep that in mind :)
I did: `git rebase master`
and then made my changes and then: `git push -f`

This should the job right? If not let me know. I will rectify my error.

**Comment by thelowercaseguy** [comment]
Thanks for all the help! @khancyr

**Comment by thelowercaseguy** [comment]
@khancyr I have removed the spaces as well. Hope it makes it easier for you!

**Comment by khancyr** [comment]
very nice ! I wasn't blocking for me, but now it is good to go

**Comment by rmackay9** [comment]
Merged, thanks!

**Pull request merged**
