### PR TITLE
Rename AP_Logger_DataFlash to AP_Logger_JEDEC

### PR DESCRIPTION
**Pull request by peterbarker**
The naming if this driver class is *really* confusing!

This is just one of the dataflash backends we support, the other being the W25N01GV.

Done as two commits, one to rename the files, the second to adjust for the renaming.

```
Board                    AP_Periph  blimp  bootloader  copter  heli  iofirmware  plane  rover  sub
CubeOrange-periph-heavy  *                                                                     
Durandal                            *      *           *       *                 *      *      *
Hitec-Airspeed           *                                                                     
KakuteH7-bdshot                     *      *           *       *                 *      *      *
MatekF405                           *      *           *       *                 *      *      *
Pixhawk1-1M-bdshot                  *                  *       *                 *      *      *
f103-QiotekPeriph        *                                                                     
f303-Universal           *                                                                     
iomcu                                                                *                         
revo-mini                           *      *           *       *                 *      *      *
skyviper-v2450                                         *                                       
```

### CODE REVIEW

**Review by andyp1per — CHANGES_REQUESTED** [review]
I don't agree with this naming change. JEDEC is an organization that controls many, many specs. Why is DataFlash confusing? I think you should pick a name that actually makes sense. I would, for instance, be ok with AP_Logger_Flash.

**Comment by peterbarker** [comment]
Rename to `AP_Logger_Flash_JEDEC` is here: https://github.com/ArduPilot/ardupilot/compare/master...peterbarker:ardupilot:pr/logger-rename-flasher-jedec-from-dataflash?expand=1

**Comment by magicrub** [comment]
How about black box?

**Comment by peterbarker** [comment]
> How about black box?

Rather too generic, I think?  This is a driver for hardware which speaks a specific set of opcodes, you could foresee other standards in use there.

**Comment by peterbarker** [comment]
So I spent a couple of hours trying to hunt down the standard these opcodes follow.

Couldn't find one.

I've seen them references as "Industry Standard Opcodes", frequently by the JEDEC name ("JEDEC READ ID"), and sometimes by one of the original implementers ("M25P80 opcodes").

I was fully expecting to be able to reference a JEDEC standard number, but I can't find one.

Linux has gone with "spinor" to describe them: https://github.com/torvalds/linux/blob/master/include/linux/mtd/spi-nor.h#L21

So we could make this `AP_Logger_Flash_SPINOR`....

**Review by tridge — APPROVED** [review]

**Review by andyp1per — APPROVED** [review]

**Pull request merged**
