### PR TITLE
AP_IOMCU: allow up to 16 channels of servo data to be sent to the iomcu

### PR DESCRIPTION
**Pull request by andyp1per**
Fixes https://github.com/ArduPilot/ardupilot/issues/26851

### CODE REVIEW

**Comment by andyp1per** [comment]
4.5.0beta3 using dshot without the whole SBUS change:

image

**Comment by rmackay9** [comment]
yay!  Thanks so much for this!

**Comment by tridge** [comment]
@rmackay9 will test

**Comment by tridge** [comment]
we need to work out where the duplicates on chan13 came from, maybe gdb on IOMCU looking in SBUS out function to see where it got the value from. Concern is this is a crash bug

**Comment by rmackay9** [comment]
I've confirmed that this fixes the most recent issue we've seen with the SBUS output.

So to re-iterate the testing procedure, I setup two CubeOrangePluses where the 1st autopilot's SBUS output was connected to the 2nd autopilot's RCIN.

Below is a screen shot of the 1st autopilot's servo output and we can see that it is copying RCIN 6 to four output channels.
image


Then on the 2nd autopilot we can see that the correct PWMs are appearing as SBUS input.
image

**Review by rmackay9 — APPROVED** [review]
This looks OK to me and I've tested this resolves the issue, thanks!

**Comment by rmackay9** [comment]
@andyp1per,

After this change there is just a single use of IOMCU_MAX_CHANNELS on line 1152 of iofirmware.cpp.  I'm just guess but should that line also be changed?

**Comment by andyp1per** [comment]
> After this change there is just a single use of IOMCU_MAX_CHANNELS on line 1152 of iofirmware.cpp. I'm just guessing but should that line also be changed?

No, that one is correct

**Review by tridge — APPROVED** [review]

**Pull request merged**
