### PR TITLE
AutoTest: break copter autotests into smaller "under 10 minute" chunk…

### PR DESCRIPTION
**Pull request by davidbuzz**
…s to speedup github actions CI

### CODE REVIEW

**Comment by davidbuzz** [comment]
CI is now passing for both github and travisCI, ready to merge.

**Comment by peterbarker** [comment]
Looks good from a general technical perspective.

I want to see this rebased on new commits in master just to make sure we're not introducing vast numbers of random failures.

I've rebased this on top of master.

**Comment by davidbuzz** [comment]
Has now been rebased twice , so tests run 3 times  on this PR, and all still passing.

**Comment by peterbarker** [comment]
I'm going to merge this.  I haven't seen it fail in 6 runs.

Thanks @davidbuzz and @khancyr !

**Pull request merged**
