### PR TITLE
Tools: First commit test: added name to GIT_Success.txt file

### PR DESCRIPTION
**Pull request by Theonewhomadethings**
Added my name to the GIT_Success file. Reason for this was because I was following an example doc on the ardupilot dev docs.

### CODE REVIEW

**Comment by rmackay9** [comment]
Hi @Theonewhomadethings,

thanks for this.. Could you update the commit title to start with "Tools: "?  If you peek at our commit history you'll see that we always prefix PRs with the subsystem or directory to make backporting to other branches earlier.  To be clear, I mean the commit title, not the PR title.  txs!

**Review by Ryanf55 — APPROVED** [review]

**Comment by rmackay9** [comment]
@Ryanf55, I've removed the MergeOnCIPass just so that we can get the commit title fixed.

**Comment by Theonewhomadethings** [comment]
Hi @rmackay9 I believe I have changed the commit message to have the format you specified of " Tools: ", could you verify that i have correctly done the changes you asked for?

**Comment by rmackay9** [comment]
Hi @Theonewhomadethings, yes, looking good now, thanks!

**Review by rmackay9 — APPROVED** [review]

**Comment by rmackay9** [comment]
Hi @Theonewhomadethings, I think you've perhaps closed this before we could merge it.

**Comment by Ryanf55** [comment]
> @Ryanf55, I've removed the MergeOnCIPass just so that we can get the commit title fixed.

Sorry, I got this approval mixed up with the other one. My apologies. 
LGTM now. Nice work!

**Comment by rmackay9** [comment]
Merged, thanks!

**Pull request merged**
