### PR TITLE
AP_NavEKF3: rearrange readGPSData to remove some nesting

### PR DESCRIPTION
**Pull request by peterbarker**
This leaves us with only a single mis-indented block.

We could remove 2 levels of indentation from this method, and probably should at some stage.

### CODE REVIEW

**Review by rmackay9 — CHANGES_REQUESTED** [review]
This looks good to me, I've checked each changed line and the logic seems correct.  Of course whenever you touch the EKF you need to re-test that it still works so you'll probably have to say what level of testing you've done.

If you're going to go this far then maybe add another commit to remove the two levels of indentation.

**Comment by peterbarker** [comment]
@rmackay9 I intend to fly this today on a quad.

I'll chat with tridge about the indenting.  At least with this patch its pretty clear what's going on with the indenting, and so far we haven't lost the history on these lines.

**Comment by peterbarker** [comment]
I've flown this and nothing untoward happened.

**Comment by rmackay9** [comment]
If you want to merge without fixing the indenting then I'm fine with that.  I think with github webpage you can always go back and figure out who changed stuff before your commit so I'm not personally so worried about formatting changes affecting "blame".

**Comment by peterbarker** [comment]
I've now run this through a new script and there's no change in output between this and master.

Thanks @rmackay9 , merging.

**Pull request merged**
