### PR TITLE
Plane: servos: update dspoiler auto trim

### PR DESCRIPTION
**Pull request by IamPete1**
This updates the dspoiler auto trim to reflect https://github.com/ArduPilot/ardupilot/pull/10614

### CODE REVIEW

**Comment by tridge** [comment]
needs SITL testing

**Comment by IamPete1** [comment]
update bitmask to ! = 0 to convert to bool

**Comment by IamPete1** [comment]
@tridge Have updated the bitmask and tested in realflight, couldn't find a suitable flying wing but have tested all configs with the DG-800. All seems to work as it should, no trim divergence anyway, ends up back to where it was within 10 or 20 eventually.

**Comment by IamPete1** [comment]
I have re-based this, @tridge I think I tested this pretty thoroughly in Real-flight in all configurations

**Comment by tridge** [comment]
thanks Pete!

**Pull request merged**
