### PR TITLE
Allow initialisation of AC_AttitudeControl pids with a structure

### PR DESCRIPTION
**Pull request by peterbarker**
Came up on the DevCall that the current constructor for AC_PID is a bit of a nightmare to work with.

Perhaps this structure might be better?

I've only converted one PID here, and if we do go down this path we'd remove the old constructor and move the content into the new constructor.

### CODE REVIEW

**Comment by peterbarker** [comment]
> I like this, much easier to follow. Costs a few bytes here, but I think it should not be so bad once we can remove the other constructor. Even if it is a net increase in flash I still think its worth it.

Weelll... moving the new constructor into the header does this:
```
Board,AP_Periph,blimp,bootloader,copter,heli,plane,rover,sub
Durandal,,*,*,*,*,*,*,*
Hitec-Airspeed,*,,,,,,,
KakuteH7-bdshot,,*,*,*,*,*,*,*
MatekF405,,*,*,*,*,*,*,*
f103-QiotekPeriph,*,,,,,,,
f303-Universal,*,,,,,,,
```

i.e. the compiler is sorting it all out so there's no change to the output of the compiler!

**Comment by peterbarker** [comment]
.... new formulation, moving the initialisation into the header file, out of the constructor implementation.

So this made it clear we're using the RP_FILT_HZ in the yaw constructor, which is a bit odd.

**Review by lthall — APPROVED** [review]
Love it

**Comment by peterbarker** [comment]
Leonard and Randy are happy, so we're merging ;-)

**Pull request merged**
