### PR TITLE
AP_Notify: Change arming time count check.

### PR DESCRIPTION
**Pull request by muramura**
1. Change the range check of arming time count from case statement to if statement.
2. Group the LED on / off check.
other
3. Change the indentation of the switch statement.
4. Insert the white space.

### CODE REVIEW

**Comment by magicrub** [comment]
I like everything except the switch to if change. The old way is part of a pattern

**Comment by OXINARF** [comment]
- I agree with @magicrub that the change to an if isn't great, leaving the switch maintains code consistency
- the white-space changes should be in a separate commit (we only allow it to be in the same commit if it is very very small).

**Comment by muramura** [comment]
@OXINARF Comments Thank you.
Divide Commit.
1 and 2, Commit.
3 and 4, Commit.

**Comment by muramura** [comment]
@OXINARF san
I divided the Commit.

**Comment by muramura** [comment]
@magicrub  Comment thank you.
For indentation of switch statement, it matched ardupilot manner.
For the case of the switch statement, the same groupings were grouped.
If you have any problems with the change, please let me know a bit more in detail.

**Comment by OXINARF** [comment]
@muramura Since both @magicrub and me didn't like the change from switch to ifs, I've merged just the grouping of on/off. Thanks!

**Pull request closed without merging**
