### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by okok125**
There is a PCB description in the OSD description. Please help me change it to SDH7V1, because it now says Kakute. Thanks.

### CODE REVIEW

**Comment by Hwurzburg** [comment]
@okok125 is this commercially available? if so please give a link to a webpage and I can add to the wiki

**Comment by okok125** [comment]
> @okok125這個可以商用嗎？如果是這樣，請提供一個網頁鏈接，我可以添加到維基

**Comment by okok125** [comment]
@Hwurzburg Thank you for your support. This is my own store. I often sell this SDH7V1 to some students and teachers in school. They are very grateful to your team for their open source services. This is the URL of my own store SDH7 V1: https://www.sdmodel.com.tw/content.php?cn=item&tid=1320&start=0

**Review by IamPete1 — CHANGES_REQUESTED** [review]
Commits need fixing up, but I think @Hwurzburg is on the case.

**Review by tridge — APPROVED** [review]

**Pull request merged**
