### PR TITLE
Remove BoardLED from NavIO2

### LINKED ISSUE #9435: AP_Notify misconfigures LED on Navio2
Hi,

I believe that a recent rewrite of AP_Notify ( 961e16dca96ef2188f198b5a22328c5610393f29 ) has introduced a bug that results in misconfiguring the LED when compiled for Navio2 boards.  I think there is an elif missing around lines 224-234 that is resulting in 'additional' backends being set for the Navio2.

https://github.com/ArduPilot/ardupilot/blob/0e0d847f7f8b1a3f79ca173ccccb919345b69190/libraries/AP_Notify/AP_Notify.cpp#L208-L234

When you compile after this commit (or download any build from after this commit) it appears to run fine but fills the console with

``GPIO_Sysfs: Unable to write pin 16 value.``
``GPIO_Sysfs: Unable to get value file descriptor for pin 4.``

I can fix the issue for myself by commenting out 224-234, but I'm lacking the mental acuity this morning to unpick the if statements to work out exactly whats going wrong.

### PR DESCRIPTION
**Pull request by WickedShell**
This resolves #9435, NavIO2 does not have any board led's, they are all controlled via Led_Sysfs. This also adds static asserts to the board leds to catch the obvious overlap of pins, which can't ever be a valid configuration.

@votingprawn would you be able to test that this resolves the issue you were seeing?

### CODE REVIEW

**Comment by votingprawn** [comment]
Hi @WickedShell sorry for the delay.  Yes this PR resolves the issue I was seeing.  Thanks for taking care of this!

**Comment by WickedShell** [comment]
@mirkix This PR as it stands breaks BBBlue builds because there are the AP_BoardLED is given the same defines for GPIO_B_LED and GPIO_C_LED. The problem with AP_BoardLED with identical pin defines is that the LED flashes are all screwed up and it becomes a race for what pattern they are flashed in. Would you have any objection if BBBlue moved to AP_BoardLED2? (We could alternatively define a -1 for the LED you don't want to use which on BBBlue looks to simply return from the driver safely without spamming any of the consoles).

**Comment by lucasdemarchi** [comment]
@WickedShell changing bbblue to use AP_BoardLED2 sounds good.

**Comment by WickedShell** [comment]
I've pushed up the changes to make BBBlue use AP_BoardLED2, but we should wait on getting a response from @mirkix before merging it since he is the maintainer.

**Comment by mirkix** [comment]
@WickedShell Hi, looks good but I will try AP_BoardLED2 with my BBBlue and come back with the result.

**Comment by mirkix** [comment]
I am fine with AP_BoardLED2 :+1:

**Comment by OXINARF** [comment]
Merged, thanks!

**Pull request merged**
