### PR TITLE
Linux signal handlers' clean-up.

### PR DESCRIPTION
**Pull request by staroselskii**
Some of our users have been complaining that they are not able to launch ArduPilot as a background process like this:

```./arducopter-quad &```

It'd used to hang until bringing this process to the foreground with ```fg```.

This is due to the default handling of ```TTIN``` signal.

While I was at it 
- I cleaned up the signal handling a bit in order to make a little more cross platform (as there're endeavours to se SITL on Mac OS X I reckon it might in theory be a right thing to do)
- Changed default handling of ```TTIN``` in ```ConsoleDevice``` to ignore the signal
- Removed FlightGear application, because it appears to be broken for quite sometime, so I doubt anybody uses this. I might be very wrong here.

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
@staroselskii signal handling should be centralized per application (or per thread in case it makes sense).   Spreading it across the codebase is no good.

**Comment by lucasdemarchi** [comment]
So... changes to Replay looks fine.  To FlightGear, I'd rather check with @tridge.  To RPI and ConsoleDevice, they should rather be moved to a common place in Linux boards.... probably HAL_Linux_Class.cpp

**Comment by staroselskii** [comment]
@lucasdemarchi 

I totally agree with you. I just haven't come up with a more proper fix just yet. I believe, it'd be a little easier to work with these changes applies, though.

What do you have in mind? I was thinking of some kind of SignalManager class with a method like ```register_handler(sighandler_t handler)```. Surprisingly, there's not enough information that I've found for handling this in C++ in an elegant way. Either way, I'm totally up to reimplementing this PR. Anywho, I suggest cherry-picking what you like right away.

**Comment by tridge** [comment]
its fine to remove the old flightgear code
Signal handling changes also look fine. I've also tested them with cygwin on windows8 and they build and run fine.
For replay we do need to do something about the waf build. The make build is broken (at least for me), and the waf build rebuilds everything. Replay is a tool where the developer is frequently doing very rapid build/test cycling, so the build needs to be fast.

**Comment by tridge** [comment]
I've pushed a change to make the Makefile in Tools/Replay call out to waf, in a way that existing replay docs will work. That solves the problem and this PR can go in I think.

**Comment by tridge** [comment]
applied, thanks!

**Pull request closed without merging**
