### PR TITLE
waf: fix build failure on cygwin due to bad path format

### PR DESCRIPTION
**Pull request by bugobliterator**

### CODE REVIEW

**Comment by rmackay9** [comment]
@bugobliterator unfortunately I'm still getting errors like this
```

[806/808] apj_tool build/CubeOrange/bin/arducopter
Loaded binary file of length 4076992
Setting defaults from /cygdrive/c/Users/rmack/Documents/GitHub/r9-ardupilot/libraries/AP_HAL_ChibiOS/hwdef/CubeOrange/defaults.parm
Saved binary of length 4076992
[807/808] Generating bin/arducopter.bin
C:\Program Files (x86)\GNU Tools ARM Embedded\6 2017-q2-update\bin\arm-none-eabi-objcopy.exe: '/cygdrive/c/Users/rmack/Documents/GitHub/r9-ardupilot/build/CubeOrange/bin/arducopter': No such file

Waf: Leaving directory `/cygdrive/c/Users/rmack/Documents/GitHub/r9-ardupilot/build/CubeOrange'
Build failed
-> missing file: '/cygdrive/c/Users/rmack/Documents/GitHub/r9-ardupilot/build/CubeOrange/bin/arducopter.bin'
"c:/cygwin64/bin/python3.6m waf copter" terminated with exit code 1. Build might be incomplete.
```

If I remove this commit then things seem to work.  I guess we can't just revert this change until it is sorted out?

- [waf: create separate image sections for internal and external flash ](https://github.com/ArduPilot/ardupilot/commit/f15f5e93340203496221e38fd1d19b3febbacb3e)

**Comment by bugobliterator** [comment]
@rmackay9 can you try again should be fixed

**Comment by tridge** [comment]
@rmackay9 @bugobliterator I was able to reproduce the issue and this PR fixes it for me

**Review by rmackay9 — APPROVED** [review]
Yes, works great, thanks!

**Pull request merged**
