### PR TITLE
WIP: ChibiOS: Plane: print thread statistics

### PR DESCRIPTION
**Pull request by kd0aij**
This is https://github.com/tridge/ardupilot/pull/12 rebased on master

### CODE REVIEW

**Comment by kd0aij** [comment]
Task SPI1 is using a lot of cpu:
```
        main  128        READY 0
        idle    1        READY 78364870
   ArduPlane  180        READY 30450793
    apm_uart   60        READY 4868630
    usb_pump    2        READY 100771
   apm_timer  178        READY 2259912
    apm_rcin  177        READY 482036
   toneAlarm   61        READY 67431
      apm_io   58        READY 1730291
 apm_storage   59        READY 212395
       SPI:2  179        READY 1370127
       I2C:1  176        READY 1257354
       SPI:1  179        READY 47042064
busy percent: 53.41, total_ticks: 168206674
```

**Comment by kd0aij** [comment]
changing effective sample rate of invensense driver to 500Hz decreases cpu load by 7%
with and without -O3 in LowPassFilter.cpp:
busy percent: 52.54, total_ticks: 839916164
time: 79.087 sec, busy: 52%
APM: PERF: 0/1500 max=3828 min=2838 F=3331 sd=18
busy percent: 52.39, total_ticks: 839915999
time: 84.086 sec, busy: 52%
APM: PERF: 0/1500 max=3352 min=3314 F=3331 sd=4

from the top of the while loop of AP_InertialSensor_Invensense::_read_fifo to 
osalThreadSuspendS in hal_spi.c: spiExchange is 20usec every 410usec (roughly)
for cpu load of ~5%

**Comment by kd0aij** [comment]
samples/sec/imu: 8KHz * 3 (gyro) + 4KHz * 3 (accel) = 36K samp/sec/imu
fpu speed: assuming 1 cycle multiply (best case pipelined; load takes 2 cycles) at 168MHz
if we spend 100 cycles per sample including IO and math:
100*36K/168M = 2%

Idle thread (yellow), accumulate section of poll_data (red), idle - accumulate (green)
and SPI thread using 30% of cpu cycles

**Comment by kd0aij** [comment]
SPIDevice::do_transfer no excessive cpu load involved with SPI transfers:

**Comment by kd0aij** [comment]
raising priority of SPI thread to 200 (highest in system) reduced worst case run time to 29758 (177 usec) and results in completion of most runs in less than 60usec. But the thread is running at intervals of approx. 135 msec (7400 Hz) and averaging 41 usec per run for 30% cpu usage.

```
        NAME PRIO        STATE   PCT        TOTAL      MIN      MAX     RUNS      AVG
        main  128        FINAL    0%            0      558   455405        0        0
        idle    1        READY   49%    414930448     1394  1686855    34248    12115
   ArduPlane  180      CURRENT   13%    109529040      723   152963     8642    12674
    apm_uart   60        READY    2%     23947267      688    28153     7024     3409
    usb_pump    2    SUSPENDED    0%       450279      550     5877      293     1536
   apm_timer  178        READY    1%     11041865      698     7486     5718     1931
    apm_rcin  177        READY    0%      2968007      705     5679     2393     1240
   toneAlarm   61     SLEEPING    0%       384913      749     4270      295     1304
      apm_io   58        READY    1%     10254733      696   164683     5604     1829
 apm_storage   59        READY    0%      1110572      741     6149      609     1823
       SPI:2  200     SLEEPING    0%      7121247     1097    10437     1753     4062
       I2C:1  176     SLEEPING    0%      6932262      773    10025     1998     3469
       SPI:1  200     SLEEPING   30%    253266838     1259    29758    36968     6850
busy: 50%, nirq: 4196446 tick rate: 168.009 MHz
```

**Comment by kd0aij** [comment]
with Sid's event based wait changes, and SPI priority still at 200:
```
        NAME PRIO        STATE   PCT        TOTAL      MIN      MAX     RUNS      AVG
        main  128        FINAL    0%            0      558   455405        0        0
        idle    1        READY   48%    408352301     1390  1683951    33728    12107
   ArduPlane  180      CURRENT   13%    110046403      611   122222     8805    12498
    apm_uart   60        READY    2%     23678901      676    17216     6764     3500
    usb_pump    2    SUSPENDED    0%       490663      550     6136      319     1538
   apm_timer  178        READY    1%     10849946      689     8129     5563     1950
    apm_rcin  177        READY    0%      2877049      690     6370     2323     1238
   toneAlarm   61     SLEEPING    0%       403299      752     5530      313     1288
      apm_io   58        READY    1%     10119048      688   164687     5491     1842
 apm_storage   59        READY    0%      1138068      632     7609      619     1838
       SPI:2  200     SLEEPING    0%      7160169     1097    10908     1758     4072
       I2C:1  176     SLEEPING    0%      7128020      758    10753     2110     3378
       SPI:1  200     SLEEPING   30%    259686731     1219    35230    36539     7107
busy: 51%, nirq: 23504121 tick rate: 168.013 MHz
```

**Comment by kd0aij** [comment]
fixed my version of the get_stats printout to print total/best/avg/worst times in usec:
```
time: 425.027
        NAME PRIO        STATE   PCT         RUNS TOTAL us     BEST      AVG    WORST
        main  128        FINAL    0%            0        0        0      0.0        0
        idle    1        READY   51%        28983  2591104        8     89.4      681
   ArduPlane  180     SLEEPING   11%         1538   579712       22    376.9     2625
    apm_uart   60      WTOREVT    3%         7677   157464        4     20.5       69
    usb_pump    2        READY    0%          289     2648        4      9.2       20
   apm_timer  178     SLEEPING    1%         7977    93520        4     11.7       37
    apm_rcin  177     SLEEPING    0%         2554    19367        4      7.6       28
   toneAlarm   61     SLEEPING    0%          324     2553        4      7.9       23
      apm_io   58      CURRENT    1%         5381    85494        4     15.9      433
 apm_storage   59     SLEEPING    0%          626     6841        4     10.9       23
       SPI:2  179     SLEEPING    0%         1764    43052        5     24.4       52
       I2C:1  176     SLEEPING    0%         1897    40305        5     21.2       58
       SPI:1  179    SUSPENDED   27%        29345  1377918        4     47.0      200
busy: 48%, nirq: 6544592 tick rate: 168 MHz, run interval: 5.000 sec
APM: PERF: 0/1500 max=3352 min=3312 F=3332 sd=4
```

**Comment by kd0aij** [comment]
thread stats on AUAVX2.1:
```
        NAME PRIO        STATE   PCT RUNS/sec TOTAL us     BEST      AVG    WORST
        main  128        FINAL    0%        0        0        0      0.0        0
        idle    1        READY   50%     7592  2511037        8     66.1      433
   ArduPlane  180     SLEEPING   13%     1671   654420        4     78.3      338
    apm_uart   60        WTSEM    3%     1567   175766        4     22.4       76
    usb_pump    2    SUSPENDED    0%       48     2292        4      9.6       22
   apm_timer  178     SLEEPING    1%     1162    76055        4     13.1       36
      noname  178     SLEEPING    0%      981    34042        4      6.9       29
    apm_rcin  177     SLEEPING    0%      462    23342        4     10.1       27
   toneAlarm   61     SLEEPING    0%       58     2313        5      8.0       18
      apm_io   58      CURRENT    1%     1152    89682        4     15.6      324
 apm_storage   59     SLEEPING    0%      128     7076        4     11.1       24
       IOMCU  180      WTOREVT    2%      914   114356        4     25.0      119
       SPI:1  181     SLEEPING   26%     8402  1311077        7     31.2      129
time: 385.008
busy: 49%, irq rate: 15.997 KHz tick rate: 168 MHz, run interval: 5.000 sec
```

**Comment by magicrub** [comment]
is this still valid? Should it get merged/cherrypicked into https://github.com/ArduPilot/ardupilot/pull/7851

**Comment by kd0aij** [comment]
@magicrub I think @bugobliterator implemented similar thread stats printout in parallel with this PR, but I don't know whether either was merged. Most of the stuff in this PR is just me wondering why thread priorities are set the way they are. I'm also not sure whether the ~50% aggregate cpu load is correct, since Tridge said it seemed too high.

**Comment by kd0aij** [comment]
stale

**Pull request closed without merging**
