### PR TITLE
AP_DDS: Switch to master instead of develop tag

### PR DESCRIPTION
**Pull request by Ryanf55**
* No new features added, just switching to the tag on master
* Develop tags expire

### CODE REVIEW

**Review by khancyr — APPROVED** [review]
Lgtm

**Review by peterbarker — DISMISSED** [review]
This commit message needs a prefix for the submodule name.

e.g. `XRCE-DDS-Client: Switch to master instead of develop tag`

**Comment by Ryanf55** [comment]
> This commit message needs a prefix for the submodule name.
> 
> e.g. `XRCE-DDS-Client: Switch to master instead of develop tag`

My bad, fixed

**Comment by tridge** [comment]
@Ryanf55 this still leaves .gitmodules pointing at develop. Was this intended?
I think a commit against .gitmodules should fix it.

**Comment by Ryanf55** [comment]
> @Ryanf55 this still leaves .gitmodules pointing at develop. Was this intended? I think a commit against .gitmodules should fix it.
> 
> ```
> [submodule "modules/Micro-XRCE-DDS-Client"]
>         path = modules/Micro-XRCE-DDS-Client
>         url = https://github.com/ardupilot/Micro-XRCE-DDS-Client.git
>         branch = develop
> [submodule "modules/Micro-CDR"]
>         path = modules/Micro-CDR
>         url = https://github.com/ardupilot/Micro-CDR.git
>         branch = develop
> ```

Updated and rebased.

**Pull request merged**
