### PR TITLE
Rover: push servo outputs

### PR DESCRIPTION
**Pull request by staroselskii**
In case something uses cork()/push() somewhere, PWM won't be issued.

It might be a wrong place to put the fix in but nevertheless it's an issue that should be resolved.
I tested it on Navio 2 and it did the trick. In order to reproduce the bug I changed Notify device to RCOutputRGBLed which implements cork() routine.

### CODE REVIEW

**Comment by khancyr** [comment]
I am specialist on this level of code, but after looking on the push/cork thing and how output are really send it seems the right thing to do

**Comment by OXINARF** [comment]
This doesn't look correct to me. There is no cork in this method, so it shouldn't be needed to do a push. If doing one corrects an issue, it looks like there is a cork somewhere that isn't doing the corresponding push.

I'll add though that doing a cork/push around the `output_ch_all` may be a good idea to output the servos all at the same time.

**Comment by staroselskii** [comment]
> If doing one corrects an issue, it looks like there is a cork somewhere that isn't doing the corresponding push.
> I'll add though that doing a cork/push around the output_ch_all may be a good idea to output the servos all at the same time.

If I got it right it's done intentianally and exactly for this [purpose](https://github.com/ArduPilot/ardupilot/blob/6a1c58b5a5fcc070dbb5655efafd222a9227f7cd/libraries/AP_Notify/RCOutputRGBLed.cpp#L73). So I guess the fix is in the right place, isn't it? Either way, I'll be happy to fix otherwise it if I'm proven wrong!

**Comment by khancyr** [comment]
@oxinarf the cork/push should always be done by pair ? in that case the bug found show that their is a place where it isn't done well

**Comment by OXINARF** [comment]
@khancyr Yes, it is supposed to be done in pairs.

@staroselskii I don't think that code makes sense. Why would you want to sync leds with motors output? It's also a complete hack as it depends on motor output being done after it and that guarantee obviously doesn't exist. In reality, until a few weeks ago, this wouldn't even work well in some HALs as we didn't support nested cork/push, meaning that two corks (that would certainly be happening) would be doing wrong things. We added support for nested, but it is far from perfect and, in any case, a pair of cork/push should always happen.

@lucasdemarchi @zehortigoza do you want to comment on the linked code?

**Comment by lucasdemarchi** [comment]
That code was actually relying on the fact that cork() + cork() + push() would send the output to the motors. The reasoning is that a call to set the output from the main thread doesn't have to wait a call from the AP_Notify to finish... Because we care more about jitter on motor output than on an rgb LED that's using the same physical device as rcoutput. Now that cork and push is not done by libraries and there's a nested cork/push, this should rather be moved to the vehicle logic.

**Comment by OXINARF** [comment]
@lucasdemarchi 

> That code was actually relying on the fact that cork() + cork() + push() would send the output to the motors. 

Cork + cork wasn't supported and would actually do bad things in some HALs. It won't do now, but a cork alone shouldn't exist.

> The reasoning is that a call to set the output from the main thread doesn't have to wait a call from the AP_Notify to finish

I'm missing something here. Since when does AP_Notify doesn't run in the main thread? And why would motor output be waiting for anything? I think the cork/push only says "write all these in-between at the same time". How not doing a push actually improves anything? It just makes any other RC write have to wait for someone to do push.

> Now that cork and push is not done by libraries and there's a nested cork/push, this should rather be moved to the vehicle logic.

I wouldn't say that. Indeed it was removed from some libraries and changed to the vehicle, but I don't think that's a rule. I think it actually makes sense to have a cork/push in that Notify backend, you don't want to update each color separately.

**Comment by khancyr** [comment]
The problem come from here https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Notify/RCOutputRGBLed.cpp#L73 ?

**Comment by OXINARF** [comment]
@khancyr Yes, that's linked above.

**Comment by lucasdemarchi** [comment]
> I'm missing something here. Since when does AP_Notify doesn't run in the main thread?

My bad. I thought I had moved this to another thread. So it's actually a bit worse since it will do a bus transaction from the main thread. Not the worst possible case as we run tasks from AP_Scheduler after motors are updated. I'm still not happy with any of the solutions though

**Comment by OXINARF** [comment]
> So it's actually a bit worse since it will do a bus transaction from the main thread.

@lucasdemarchi What do you mean with a bus transaction? Are you talking about PX4 RCOutput_TAP? Doing a write doesn't necessarily imply writing the output right away - with PX4 RCOutput it will output to motors only with the timer thread with normal PWM and output right away with Oneshot enabled. Putting cork/push around it does the writes together when push is called, but once again it depends on HAL implementation of when it actually gets to the motors.

**Comment by lucasdemarchi** [comment]
> @lucasdemarchi What do you mean with a bus transaction? Are you talking about PX4 RCOutput_TAP?

No, this is only used with PCA9685 and on Linux boards.

**Comment by OXINARF** [comment]
@lucasdemarchi Right. But then I'm not sure what your concern is, PCA9685 apparently will always write when pushed (and that probably always happens in the main thread). I would say that if that is a concern then the RCOutput_PCA9685 needs to be changed to only write in the timer thread.

**Comment by lucasdemarchi** [comment]
Writing to the motors is okish (I still want to change it, but it's not critical)... There's no point in continue the main loop if motors were not updated. Writing to LEDs and delay everything else is not ok though.

**Comment by OXINARF** [comment]
>  There's no point in continue the main loop if motors were not updated.

I think that's a little extremist, but I get your point. I only see two ways to go about fixing this:

- fix the RCOutput_9685 to do bus transfer either in I2C bus thread or in timer thread
- fix the RCOutputRGBLed to write to *rcout* in a different thread

I'm not a fan of the second choice because I'm not sure how safe it is to do that. Also, it feels to me that we would be fixing in the wrong place.

But here are the good news: I've just noticed that the notify driver actually uses SRV_Channels API and not *rcout* directly. The good news about this is that the output is only done when commanded by the vehicle.
So my final suggestion is:

- remove the cork from RCOutputRGBLed driver
- add cork/push around the `output_ch_all` call in Rover (this PR already adds the push)

**Comment by lucasdemarchi** [comment]
@oxinarf that seems good to me.

**Comment by OXINARF** [comment]
@staroselskii Do you want to change the PR to do what I wrote above?

**Comment by lucasdemarchi** [comment]
@gmorph have you read the comments?

**Comment by OXINARF** [comment]
@gmorph Like Lucas said, if you read the comments above, this isn't ready to be merged.

**Comment by staroselskii** [comment]
@lucasdemarchi @gmorph @OXINARF 

I force pushed the aforementioned changes.

**Comment by OXINARF** [comment]
@staroselskii Thanks!

@gmorph This looks good to me, if you can test this one on the weekend it would be great.

**Pull request merged**
