### PR TITLE
AP_NavEKF3: remove mag_state state

### PR DESCRIPTION
**Pull request by peterbarker**
```
we don't need to persist this across multiple calls as we now fuse all axes on the one step.

I've moved the defintion of these variables to where they are initialised to make it clear they're not used uninitialised.
```

Some of the initialisations could probably be tidied up to `const` the variables at definition, but that would have made this patch look pretty complicated.

Memory saved as expected on CubeBlack:
```
master:  RTL> 96: MEMINFO {brkval : 0, freemem : 59944, freemem32 : 59944}
   new: RTL> 163: MEMINFO {brkval : 0, freemem : 60224, freemem32 : 60224}
222
```
(delta is 280)

### CODE REVIEW

**Comment by peterbarker** [comment]
```
Board,AP_Periph,blimp,copter,heli,plane,rover,sub
Durandal,,-328,-328,-328,-328,-328,-336
Hitec-Airspeed,0,,,,,,
KakuteH7-bdshot,,-296,-296,-296,-296,-296,-296
MatekF405,,-264,-264,-264,-264,-264,-264
Pixhawk1-1M,,-256,-256,-256,-256,-256,-256
f103-QiotekPeriph,0,,,,,,
f303-Universal,0,,,,,,
revo-mini,,-264,-264,-264,-264,-264,-264
skyviper-v2450,,,-240,,,,
```

**Comment by peterbarker** [comment]
Durandal:

image

**Review by rmackay9 — APPROVED** [review]

**Comment by tridge** [comment]
we record a replay log on master, and run replay with this PR on the log, and we should see zero replay changes

**Comment by peterbarker** [comment]
> we record a replay log on master, and run replay with this PR on the log, and we should see zero replay changes

Done.  `Tools/Replay/check_replay_branch.py` *now* shows no changes.

The changes I brought to DevCall *did* lead to different EKF results, for reasons we probably need to get our head around (and might explain the rare Replay failures we get in CI).

The problem was the quaternion normalisation (now) on line 866.  We normalize the quaternion each time throough the for-each-axis loop.

**Comment by peterbarker** [comment]
@priseborough this doesn't change the output of the EKF.  The last patch is just to get us around `MATH_CHECK_INDEXES`, which is not the way we usually run things.

It does save some significant resources, as outlined above.

We've asked for your review because a previous version of this PR unexpectedly *did* change the output of the EKF.

The problem revolves around the normalisation of the quaternion, which we do each time we finish an axis.  This might have made sense when the MagFusion was split across three timing loops, but it does cause oddities now that we fuse all three in the one loop.

I believe the problems came about because q0..q3 are taken as copies of the quaternion as the first thing we do in the loop.  We then derive several values from them, and indeed use them in the for-each-axis loop.  These values are const and are not changed during the entire duration of `FuseMagnetometer`.  However, the quaternion *is* changed during the loop by being re-normalised.  That means we're doing calculations with out-dated values.  That might be OK - but I think we must also be mixing in calculations with the normalised quaternion since the output of the EKF changes if q0..q3 are made references to that quaternion.  (It's *possible* that the quaternion isn't normalized coming into the function; that would probably be a different bug).

So I guess what it comes to is - should we be normalizing that quaternion each time through the loop?  Should we be concerned that the quaternion is being normalized multiple times across the several loops and the intermediate values used on subsequent calculations?  Should the values q0...q3 be used in place of those intermediate values?

I can put together a minimal patch on top of this PR which illustrates the change if that would help.

**Review by tridge — APPROVED** [review]

**Pull request merged**
