### PR TITLE
AP_Scripting: modify example script of README.md

### PR DESCRIPTION
**Pull request by tatsuy**
change the two things:
- avoid to call set_output_pwm before setting origin
- make get_home() once

### CODE REVIEW

**Comment by rmackay9** [comment]
Txs for this.  I'm a little surprised that ahrs:get_location() returns a location before the origin is set.. I guess it does?

**Comment by tatsuy** [comment]
get_location() works. but home is (0, 0) before the origin is set.

This is the result with some debug messages.
```
AP: ArduCopter V4.2.0-dev (020262bf)
AP: 1e34f07c2e2336b6ffa84a3e61ad97e6
AP: Frame: QUAD/PLUS
AP: Barometer 1 calibration complete
Init Gyro**
AP: ArduPilot Ready

AP: get_location is none
AP: GPS 1: detected as u-blox at 230400 baud
AP: get_location: lat:-353632621, lng:1491652374
AP: get_home: lat:0, lng:0
AP: Home To Distance: 1.630288e+07                      // home_to_distance is quite big because home is (0, 0) 
AP: EKF3 IMU0 origin set                                // origin set
AP: get_location: lat:-353632621, lng:1491652374
AP: get_home: lat:-353632621, lng:1491652374
AP: Home To Distance: 0.0
```

**Comment by IamPete1** [comment]
I think its a bit odd having a example in the readme, why not link to a example in the examples folder?

**Comment by rmackay9** [comment]
So I think the issue may be then that get_home isn't failing properly in lua.  If it doesn't have a home then I think it should return false (which becomes null I think in lua)

**Comment by tatsuy** [comment]
@rmackay9 
OK, I removed origin check.

get_home is here.
https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_AHRS/AP_AHRS.h#L460
We may need to prepare a separate get_home for lua (return false if lat, lng, alt are 0) so that it does not affect other processes.

@IamPete1 
How about splitting it into "How to add a script" and "Examples" sections like in the Wiki?
https://ardupilot.org/copter/docs/common-lua-scripts.html#a-sample-script

**Comment by rmackay9** [comment]
@tatsuy,

Could you squash the commits?  I'll merge after that. txs

**Pull request merged**
