### PR TITLE
AP_BattMonitor: Adding driver for Rotoye Batmon equipped smart batteries

### PR DESCRIPTION
**Pull request by peterbarker**
Replaces #14284

### CODE REVIEW

**Comment by peterbarker** [comment]
@echoGee could you test this on hardware, please?

**Comment by nbelanger99** [comment]
> @echoGee could you test this on hardware, please?

Hi Peter. This updated branch has been tested as working with a Batmon smart-battery on a Pixhawk 4. Let us know if you have any other questions, and thanks for your help.

**Comment by rmackay9** [comment]
some comments from testing over here: https://github.com/ArduPilot/ardupilot/issues/15616

**Comment by echoGee** [comment]
@rmackay9 Know why the merging is blocked ?

**Comment by rmackay9** [comment]
@echoGee PRs often take several days to be merged.  I suspect PeterB is waiting on more testing feedback but I'm not sure.  After PeterB is ready he will likely add the "DevCall" topic and it will be discussed and merged in an upcoming weekly dev call.

**Comment by peterbarker** [comment]
@echoGee Yes, sorry for the delay here.  I was using your support here as test-case for some smartmon-based simulated battery stuff I was working on.

I wanted to get some feedback from both yourself and @WickedShell as to why this requires a custom driver rather than just using the "generic" support.

**Comment by echoGee** [comment]
> @echoGee Yes, sorry for the delay here. I was using your support here as test-case for some smartmon-based simulated battery stuff I was working on.
> 
> I wanted to get some feedback from both yourself and @WickedShell as to why this requires a custom driver rather than just using the "generic" support.

A single driver is ideal, and a good system to have. Unfortunately, the standard protocol for SMBUS is not **complete**. Having a single driver is possible, but it requires a organization/working-group to standardize SMBUS or SMBUS-like communication protocol and force it to be adopted by all smart battery.

**Comment by peterbarker** [comment]
Essentially I started to wonder if Rotoye here should inherit from Generic (as several other drivers do), then wondered whether things like the cell-count-auto-detection wouldn't work for Rotoye.

@echoGee could you be more specific about what the generic driver doesn't do that Rotoye needs, please?  It looks like we should be inheritting from Generic rather than AP_BattMonitor_SMBus to get the cell IDs at the very least.

**Comment by nbelanger99** [comment]
> Essentially I started to wonder if Rotoye here should inherit from Generic (as several other drivers do), then wondered whether things like the cell-count-auto-detection wouldn't work for Rotoye.
> 
> @echoGee could you be more specific about what the generic driver doesn't do that Rotoye needs, please? It looks like we should be inheritting from Generic rather than AP_BattMonitor_SMBus to get the cell IDs at the very least.

As of now, there doesn't seem to be any obvious reason that we couldn't use the generic SMBus base class. We'll look into making this change and see if there are any compatibility issues.

**Comment by nbelanger99** [comment]
> > Essentially I started to wonder if Rotoye here should inherit from Generic (as several other drivers do), then wondered whether things like the cell-count-auto-detection wouldn't work for Rotoye.
> > @echoGee could you be more specific about what the generic driver doesn't do that Rotoye needs, please? It looks like we should be inheritting from Generic rather than AP_BattMonitor_SMBus to get the cell IDs at the very least.
> 
> As of now, there doesn't seem to be any obvious reason that we couldn't use the generic SMBus base class. We'll look into making this change and see if there are any compatibility issues.

We've re-implemented the driver using the generic SMBus class, and it's tested-as-working on hardware. Should we push this to our public repo, create a new PR and close this one?

**Comment by nbelanger99** [comment]
I've gone ahead and opened a [new PR](https://github.com/ArduPilot/ardupilot/pull/15682). If there aren't any issues with it, we can close this one.

**Comment by peterbarker** [comment]
Closing this in favour of https://github.com/ArduPilot/ardupilot/pull/15682 (thanks @nbelanger99 )

**Pull request closed without merging**
