### PR TITLE
AP_RangeFinder:correct nooploop max dist

### PR DESCRIPTION
**Pull request by Hwurzburg**
correct max dist value   its 8m not 8000m

### CODE REVIEW

**Review by rishabsingh3003 — APPROVED** [review]
Thank you so much for catching this!!

**Comment by rmackay9** [comment]
I think @rishabsingh3003 is the maintainer so with his approval, let's merge on CI pass.

**Comment by peterbarker** [comment]
We have an entire suite of autotests dedicated to finding this sort of issue in our RangeFinder drivers.

Not creating a simulator for this was an oversight IMO.

**Comment by peterbarker** [comment]
> We have an entire suite of autotests dedicated to finding this sort of issue in our RangeFinder drivers.
> 
> Not creating a simulator for this was an oversight IMO.

.... except there *is* a driver.  This bug should have been caught by the test suite..

**Pull request merged**
