### PR TITLE
Refactor microstrain to common library

### PR DESCRIPTION
**Pull request by Ryanf55**
This refactors out out the common shared logic from microstrain series 5 and 7 (mainly, the parsing). This will allow creating the 7-series driver with far less code duplication. Logic was not impacted. On SITL, I just renamed the class to make it clear it's a simulator for the 5-series. The 7-series uses some different packets, and also has two GPS instances.

https://ardupilot.org/copter/docs/parameters.html#gps-type

https://ardupilot.org/copter/docs/common-external-ahrs.html
```
param set GPS_TYPE 21
param set AHRS_EKF_TYPE 11
param set EAHRS_TYPE 2
param set SERIAL4_PROTOCOL 36
param set SERIAL4_PROTOCOL 115
```

https://github.com/ardupilot/ardupilot/blob/master/libraries/SITL/SIM_MicroStrain.h#L3

Test: 
* `autotest.py build.Plane test.Plane.MicroStrainEAHRS  --debug`
* `sim_vehicle.py -v Plane -DG --console --map -A --uartE=sim:MicroStrain`
  * With GDB breakpoint: `sim_vehicle.py -v Plane -DG --console -A --uartE=sim:MicroStrain -B AP_ExternalAHRS_MicroStrain5.cpp:98`

### CODE REVIEW

**Review by tridge — COMMENTED** [review]
I'd prefer libraries/AP_ExternalAHRS/MicroStrain_common.{cpp,h}

**Comment by Ryanf55** [comment]
> I'd prefer libraries/AP_ExternalAHRS/MicroStrain_common.{cpp,h}

Done!

**Comment by Ryanf55** [comment]
I saw that SITL tests failed. After fixing my local dev environment, I was able to reproduce this failure locally and will be working on it. It's likely caused by the serial port not being set up. 
image

**Comment by Ryanf55** [comment]
`test.Rover.Rally` has failed 3x in a row in CI and is blocking merge.

**Review by tridge — APPROVED** [review]

**Pull request merged**
