### PR TITLE
autotest: Skip build_binaries.py if working directory has changes

### LINKED ISSUE #22725: Autotest script can blow away local changes
## Bug report

**Issue details**

Running the `autotest.py` script can blow away local code changes:
* If no test is specified, the `autotest.py` script will run all available tests.
* One of the tests is "Build Binaries", which calls the `build_binaries.py` script.
* The `build_binaries.py` script does a *forced checkout* of the `master` branch, blowing away any local changes.

**Version**
All

**Platform**
[ X ] All
[  ] AntennaTracker
[  ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

### PR DESCRIPTION
**Pull request by sypaq-nexton**
Fixes #22725.

### CODE REVIEW

**Comment by sypaq-nexton** [comment]
This is the simplest fix. Other options to address the issue:
* Update the `build_binaries.py` script to fail if the working directory is dirty.
* Remove the "build.Binaries" step from the Autotest.

**Comment by tridge** [comment]
build_binaries.py being part of autotest.py is a mistake I think. I'd prefer to break it out separately and not run it at all in autotest.py

**Comment by tridge** [comment]
@sypaq-nexton this can't happen in master, it gives this:
```
Steps must be supplied; try --list and/or --list-subtests or --help
```

**Comment by peterbarker** [comment]
@sypaq-nexton a couple of things.

This *was* a problem up until recently.

The work should not have been lost - `build_binaries.py` does a `stash`.  Easy to miss that, 'though.

**Comment by peterbarker** [comment]
... oh, also I added a bit warning to the Wiki a few years ago wheh nwriting up the instructions on how to use it day-to-day: https://ardupilot.org/dev/docs/the-ardupilot-autotest-framework.html#running-autotest

It was a big enough landmine I added a command-line option to put the script into "autotest server" mode, but it took me a while to push that through.

**Pull request closed without merging**
