### PR TITLE
Add SpeedyBee F4 hardware definition for ChiBios

### PR DESCRIPTION
**Pull request by s0up**
This hardware definition is a tested and working configuration for the SpeedyBee F4.  It does not have a built in barometer, so you need to add one to the I2C bus for APM to initialize properly.

The built-in BTLE chip is on SERIAL4.  You can configure it for wireless connections like this: 

param set SERIAL4_BAUD 19 (bluetooth support)
param set SERIAL4_PROTOCOL 1 (mavlink 1.0)

Thank you @tridge and @dbasch and others who helped immensely with getting this figured out and tested.

### CODE REVIEW

**Comment by tridge** [comment]
looks good! I've added the bootloader binaries, and changed commit msg to match our conventions.
just waiting for CI

**Comment by davidbitton** [comment]
Which barometer should be used?

**Comment by dbasch** [comment]
bmp180 is a good option

**Comment by davidbitton** [comment]
@dbasch I found [this](https://tro.pe/2DJ9n2x) combo which should fit the bill; BMP180, HMC5983 and MPU-6050.

RY836AI

**Comment by davidbitton** [comment]
I've evidenced an issue with compass discovery. I ordered the newer version of that gps/baro/compass/imu board which has a single MPU-9250. According to the code in `AP_Compass.cpp`, when `HAL_COMPASS_DEFAULT` is defined as `HAL_COMPASS_NONE` then `void Compass::_probe_external_i2c_compasses(void)` is called. Well, that routine doesn't look for the 9250. So, do we change the hwdef or AP_Compass? I can hack it either way however I'm thinking we need to do something in the hwdef file. Should I open this as an issue and track it there? Thanks.

**Comment by davidbitton** [comment]
OK, I just filed #9972 and commented on #5496. Ultimately, HAL_COMPASS_DEFAULT results in no 9250 probing.

**Pull request merged**
