### PR TITLE
autotest: add test for autorotation

### PR DESCRIPTION
**Pull request by peterbarker**
@Gone4Dirt - any clues on what I should do here to achieve a softer rather than harder landing?

Parts of the entry/exit matrix could be easily tested here - so being dumped into ALTHOLD, for example.

### CODE REVIEW

**Comment by Gone4Dirt** [comment]
What is it that you are looking to achieve?  Do you want to change a parameter and test if it changes the vertical velocity on impact?  Or is it that the vehicle is landing too quickly in the autotest so it looks like a crash?

Forgive me, im not very familiar with how the autotests work.  Do they use SITL to model the behaviour of vehicle?  Im not sure, but I dont think the rotor head is modelled correctly in SITL yet.  Tridge mentioned it a while back that SITL dosn't account for a relationship between descent speed and rotor rpm?  I had a quick look but couldn't find where this behaviour should be modelled.  That would be criticle for having some control over the impact speed.  Happy to write the model if you could point me in the right direction of where it needs to go.

**Comment by peterbarker** [comment]
@Gone4Dirt having the vehicle impact at a slower speed than without autorotate is what I was hoping to see.

You're right - I'd forgotten we don't model this well in SITL.

This is probably where more smarts need to go:
https://github.com/ardupilot/ardupilot/blob/master/libraries/SITL/SIM_Helicopter.cpp#L88

I think I might merge this.  It's not actually testing what it's supposed to - but the magic "28" constant can be reduced to something hopefully much smaller when we do simulate the physics better.  As it stands - at least we'll always be crossing more codepaths in autotest.

**Comment by peterbarker** [comment]
@Gone4Dirt Sorry, I also meant to say - yes, autotest is very much like SITL when you don't need to interact with the vehicle and can just run a pre-canned routine against the vehicle to work out if something is working or not.

**Comment by Gone4Dirt** [comment]
Thanks @peterbarker.  I will look at adding the RPM descent speed behavior to sitl then I may try adding to this autotest, as I would like to learn more about autotests.

**Pull request merged**
