### PR TITLE
Sub: sync MAVLink system id in 1hz loop

### PR DESCRIPTION
**Pull request by Williangalvani**
~needs testing~
tested

### CODE REVIEW

**Comment by rmackay9** [comment]
By the way, Copter seems to be missing this too.  @peterbarker do you think Copter needs this too?  I actually thought that copter was updating its system id in real time.

**Comment by patrickelectric** [comment]
Related to: https://github.com/ArduPilot/ardupilot/pull/26424

**Comment by amilcarlucas** [comment]
Can it be done in AP_Vehicle instead?

**Comment by peterbarker** [comment]
> Can it be done in AP_Vehicle instead?

Not nicely, but it can be done in GCS_Common if it's a good thing to do.

**Pull request merged**
