### PR TITLE
Copter/Plane/Rover:  Initialize a string array

### PR DESCRIPTION
**Pull request by muramura**
Initialize the message array of the AUTO variable.
Other methods initialize.
I want to match other methods.
I think AUTO variables are good, initialize and then use.

### CODE REVIEW

**Review by rmackay9 — APPROVED** [review]
I don't actually know if this is necessary or not but we do initialise the arrays in similar code within AP_Arming_Copter::mandatory_gps_checks() so this at least makes them consistent.

**Comment by amilcarlucas** [comment]
```
Binary Name      Text [B]       Data [B]     BSS (B)        Total Flash Change [B] (%)      Flash Free After PR (B)
---------------  -------------  -----------  -------------  ----------------------------  -------------------------
arducopter-heli  32 (+0.0018%)  0 (0.0000%)  0 (0.0000%)    32 (+0.0018%)                                    192592
ardurover        24 (+0.0015%)  0 (0.0000%)  0 (0.0000%)    24 (+0.0015%)                                    375440
arduplane        12 (+0.0007%)  0 (0.0000%)  4 (+0.0015%)   12 (+0.0007%)                                    218736
blimp            0 (0.0000%)    0 (0.0000%)  0 (0.0000%)    0 (0.0000%)                                      674236
arducopter       28 (+0.0016%)  0 (0.0000%)  -4 (-0.0015%)  28 (+0.0016%)                                    200256
antennatracker   0 (0.0000%)    0 (0.0000%)  0 (0.0000%)    0 (0.0000%)                                      614216
ardusub          0 (0.0000%)    0 (0.0000%)  0 (0.0000%)    0 (0.0000%)                                      413868
```

**Comment by amilcarlucas** [comment]
```
Binary Name      Text [B]       Data [B]     BSS (B)        Total Flash Change [B] (%)      Flash Free After PR (B)
---------------  -------------  -----------  -------------  ----------------------------  -------------------------
arducopter-heli  32 (+0.0018%)  0 (0.0000%)  0 (0.0000%)    32 (+0.0018%)                                    192592
ardurover        24 (+0.0015%)  0 (0.0000%)  0 (0.0000%)    24 (+0.0015%)                                    375440
arduplane        12 (+0.0007%)  0 (0.0000%)  4 (+0.0015%)   12 (+0.0007%)                                    218736
blimp            0 (0.0000%)    0 (0.0000%)  0 (0.0000%)    0 (0.0000%)                                      674236
arducopter       28 (+0.0016%)  0 (0.0000%)  -4 (-0.0015%)  28 (+0.0016%)                                    200256
antennatracker   0 (0.0000%)    0 (0.0000%)  0 (0.0000%)    0 (0.0000%)                                      614216
ardusub          0 (0.0000%)    0 (0.0000%)  0 (0.0000%)    0 (0.0000%)                                      413868
```

**Comment by amilcarlucas** [comment]
```
Binary Name      Text [B]       Data [B]     BSS (B)        Total Flash Change [B] (%)      Flash Free After PR (B)
---------------  -------------  -----------  -------------  ----------------------------  -------------------------
arducopter-heli  32 (+0.0018%)  0 (0.0000%)  0 (0.0000%)    32 (+0.0018%)                                    192592
ardurover        24 (+0.0015%)  0 (0.0000%)  0 (0.0000%)    24 (+0.0015%)                                    375440
arduplane        12 (+0.0007%)  0 (0.0000%)  4 (+0.0015%)   12 (+0.0007%)                                    218736
blimp            0 (0.0000%)    0 (0.0000%)  0 (0.0000%)    0 (0.0000%)                                      674236
arducopter       28 (+0.0016%)  0 (0.0000%)  -4 (-0.0015%)  28 (+0.0016%)                                    200256
antennatracker   0 (0.0000%)    0 (0.0000%)  0 (0.0000%)    0 (0.0000%)                                      614216
ardusub          0 (0.0000%)    0 (0.0000%)  0 (0.0000%)    0 (0.0000%)                                      413868
```

**Review by khancyr — CHANGES_REQUESTED** [review]
Well, in this case, we should remove the {}  as there are a waste, we copy the sting into the bugger and set the null-termination so we don't need the initialisation of the full bufffer.

**Pull request merged**
