### PR TITLE
SmartAudio v2 set the power level rather than power in dBm

### PR DESCRIPTION
**Pull request by andyp1per**

### CODE REVIEW

**Comment by andyp1per** [comment]
You can either set band and channel or frequency but not both. If you change the band or channel the frequency will be modified and vice versa.

VTX_MAX_POWER determines how high the selection for VTX_POWER will go if you select the "smart audio" function for your switch - could be 3-way, 6-way or a pot.

**Comment by Target0815** [comment]
>> if you select the "smart audio" function

Do you mean RCn_OPTIONS = 94 and then? Switch channel low/high to increase the transmit power, or how should that work exactly?

**Comment by andyp1per** [comment]
Yes option 94. The channel power will be distributed evenly from 0 to VTX_MAX_POWER and then divided into 6 increments.
So a two-pos switch will give you pitmode and max power - a 3 pos will give you pitmode max and middle and so on.

**Comment by Target0815** [comment]
Ok. 
Via 3-way switch here Pitmode (low) / 25 mW (middle) / 25 mW (high) are switched according to the display in the OSD. The Unifiy Pro32 HV I use can do 25 / 100 / 400 and 1000 mW. ArduPlane can't know the values, but the output only changes from pitmode to 25 mW when switching. Of course, it may be related to this bug. Can I verify this somehow (is there a changed target from you?).

**Comment by andyp1per** [comment]
You will need to set VTX_MAX_POWER to 1000 and make sure the VTX is unlocked. I've done all my testing on TBS kit.

**Review by tridge — APPROVED** [review]

**Pull request merged**
