### PR TITLE
Update readme.txt

### PR DESCRIPTION
**Pull request by bys1123**
update to new wiki site

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
I'd rather remove it since the info is already in the README.md file. @rmackay9 what do you think?

**Comment by rmackay9** [comment]
sure. i'm happy to remove it.  Looks like the Antenna Tracker has one as well.  Plane and Rover directories don't have their own readme file.

**Comment by lucasdemarchi** [comment]
Files removed.

@bys1123 thanks for pointing this out.

**Comment by bys1123** [comment]
My pleasure.

**Pull request closed without merging**
