### PR TITLE
Global: use c++ header instead of c one's

### PR DESCRIPTION
**Pull request by khancyr**

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
You need to explain why and make sure this works with the missing/ directory in AP_HAL

**Comment by khancyr** [comment]
We are using C++, and static analyser complain about usage of C headers. Moreover, there are already mixed usage of C and C++ version, so going to C++ version was making sense to me. 
I compile on SITL and px4-v2 and see no difference is size, nor warning.

**Comment by khancyr** [comment]
closed for now

**Comment by OXINARF** [comment]
@khancyr I agree that using C++ headers is much better, but this kind of global changes are dangerous.

**Comment by khancyr** [comment]
@OXINARF yep that why I closed it for now, and I will try to do it step be step !

**Pull request closed without merging**
