### PR TITLE
AP_Math: judge isnan judgment before operation

### PR DESCRIPTION
**Pull request by muramura**
I think it is better to make isnan judgment before delta operation.
Also, I think that it is better to perform isnan judgment before the zero judgment of variable a.

### CODE REVIEW

**Comment by peterbarker** [comment]
For https://github.com/ArduPilot/ardupilot/issues/13773

I don't think that is_zero comment is wrong, either.

**Comment by rmackay9** [comment]
.. and as with other PRs, please provide testing evidence, thanks!

**Comment by peterbarker** [comment]
I've added a unit test which tests the NaN path; I walked through the code with gdb to verify it was the relevant block returning false.

I've also consolidated the is-zero check.

I intend to merge this once CI passes.

**Comment by peterbarker** [comment]
Merged, thanks!

**Pull request merged**
