### PR TITLE
AP_Scripting: added an example of OOP programming

### PR DESCRIPTION
**Pull request by tridge**
very useful pattern for more complex scripts

### CODE REVIEW

**Comment by tridge** [comment]
@WickedShell wants to redo this with metatables

**Comment by davidbuzz** [comment]
I think this should go in till @WickedShell has a chance to do something better.  lgtm.

**Comment by WickedShell** [comment]
Real metatables work nicely, #15653 add's support, and this should be easy to rework on top of that, but I don't have the time before the call to get that done.

**Comment by davidbuzz** [comment]
As best as i can tell this PR includes a script that does not use 'metatables' but should still work as-is..?   Its beyond my knowledge to even know what a metatable is ... or how using them might change this PR, so i'm just trying to move this pr forward.....  do we merge it, or close it.? :-)

**Comment by tridge** [comment]
@WickedShell i've changed the example to include both closure and metatable style of objects

**Pull request merged**
