### PR TITLE
Fix BLHeli passthru for BLHeli_S ESC's

### PR DESCRIPTION
**Pull request by andyp1per**

### CODE REVIEW

**Review by tridge — APPROVED** [review]
well found! This is going to help a lot of people

**Comment by andyp1per** [comment]
@rmackay9 you might want to consider this for 4.0.x

**Comment by peterbarker** [comment]
That would actually be @bnsgeyer and @amilcarlucas

**Comment by amilcarlucas** [comment]
I do not have BLHeli HW to test this on :(

**Comment by Givy** [comment]
I'll test it.  Were do I download it?

**Comment by bnsgeyer** [comment]
@Givy it was backported to 4.0.6 so you can test it by loading 4.0.6-rc2 which is a beta version. Here is the release post. https://discuss.ardupilot.org/t/copter-4-0-6-rc2-available-for-beta-testing/66367

**Comment by Givy** [comment]
Thank you very much.

Givi


________________________________

**Comment by Hwurzburg** [comment]
@andyp1per currently the wiki says passthru only works for BLHeli32 escs....does this mean that BLHeli-S can also be programmed via passthru?

**Comment by andyp1per** [comment]
@Hwurzburg yes - I have a wiki change in development that addresses this

**Pull request merged**
