### PR TITLE
 AP_HAL_ChibiOS: Update luminousbee5 hwdefs, Add new bootloaders

### PR DESCRIPTION
**Pull request by DavideLentini**
Hello everyone , with this PR we would like to update the hwdefs of the luminousbee5 board , since the hwdefs that are currently in the master branch are obsolete .
Also we would like to add a secondary board "luminousbee5_4" which has a different imu : the 42688.
There will probably be more updates on these hwdefs in the future but in the meantime I think it is useful to have the updated hwdefs . And if possible do a backport of these hwdefs for the branch : _Copter-4.2_ and especially _Copter-4.3_ 
Thanks to all

### CODE REVIEW

**Comment by Hwurzburg** [comment]
since this is only for use in your products and not a stand alone autopilot, no need for a README.md, but do need the bootloaders placed in Tools or firmware build will not have a bootloader included or option...

if the major difference is just IMUs, then the original hwdef could accommodate all of them.....at the very least the new board name should adhere to pattern,....ie luminousbee5v4...

**Comment by DavideLentini** [comment]
> since this is only for use in your products and not a stand alone autopilot, no need for a README.md, but do need the bootloaders placed in Tools or firmware build will not have a bootloader included or option...
> 
> if the major difference is just IMUs, then the original hwdef could accommodate all of them.....at the very least the new board name should adhere to pattern,....ie luminousbee5v4...

 Ehi , thanks !

Got it about the name , In our case we will prefer to have 2 boards with 2 different IMU , exactly as the board already exists :
"luminousbee4" 
"luminousbee5"
"luminousbee5v4"

Otherwise do you know a method to insert and use 2 IMUs in the same hwdef ? We had already tried this without success though...

**Comment by Hwurzburg** [comment]
it done all the time...
if two imus could be on the same spibus, but not at the same time, just define them as you would individually...they can have the same CS pin or different ones...they can have the same DEVID...

look at the MatekH743 which has three different sets of sensors across production changes, but one hwdef (and firmware) for all

**Comment by DavideLentini** [comment]
> it done all the time... if two imus could be on the same spibus, but not at the same time, just define them as you would individually...they can have the same CS pin or different ones...they can have the same DEVID...
> 
> look at the MatekH743 which has three different sets of sensors across production changes, but one hwdef (and firmware) for all

Yes thank you , you are right ,
We have viewed the hwdef you recommended and realized how it is possible to define 2 IMUs in the same hwdef . Soon make a modification to this PR , after testing the hwdef .

**Comment by rmackay9** [comment]
@DavideLentini,

thanks for this.  Can you squash the commits down to a single commit and prefix the commit with "AP_HAL: "?

**Comment by Hwurzburg** [comment]
and put the new bootloader in the Tools/bootloader directory

**Comment by DavideLentini** [comment]
Hey , sorry for the late response . This is the first PR , so I am getting the hang of it :)
Anyway I did a squash of the last commits + a commit in which I put a new luminousbee5 bootloader (bin and hex) and named it :
`AP_HAL_ChibiOS: Update luminousbee5 hwdefs, Add new bootloaders`
I checked the commit and everything seems to be in order .
What do you guys think about it ?

**Pull request closed without merging**
