### PR TITLE
.github: use older cygwin installer

### PR DESCRIPTION
**Pull request by peterbarker**
Try to fix this:
image

### CODE REVIEW

**Review by andyp1per — APPROVED** [review]

**Comment by davidbuzz** [comment]
i think there's a pretty good chance that changing from :
- uses: cygwin/cygwin-install-action@master
to:
- uses: cygwin/cygwin-install-action@v2

might fix it, as https://github.com/cygwin/cygwin-install-action/releases shows that '@master' is getting us @v3 , and they've dropped support for x86

**Comment by davidbuzz** [comment]
:-(

**Comment by davidbuzz** [comment]
https://cygwin.com/pipermail/cygwin-announce/2022-November/010810.html   ?

**Comment by davidbuzz** [comment]
To install the last cygwin version for x86, run setup using the options 
'--allow-unsupported-windows option --site circa_URL', where circa_URL 
can be one of:

* The URL for any sourceware mirror[1], followed by cygwin-archive/20221123

* 
http://ctm.crouchingtigerhiddenfruitbat.org/pub/cygwin/circa/2022/11/23/063457

**Comment by peterbarker** [comment]
> Quote from above site: To install the last cygwin version for x86, run setup using the options '--allow-unsupported-windows option --site circa_URL', where circa_URL can be one of:
> 
>     * The URL for any sourceware mirror[1], followed by cygwin-archive/20221123
> 
> 
> http://ctm.crouchingtigerhiddenfruitbat.org/pub/cygwin/circa/2022/11/23/063457

No mirror I've found has  cygwin32-gcc-g++

We might actually have to do as tridge suggested on the call and move to 64-bit builds?!

@meee1 for visibility

**Comment by timtuxworth** [comment]
> ok so the reason for 32, was to support windows 7
> 
> 64 bit sitl binary's are fine, but will break on windows 7

https://www.microsoft.com/en-us/windows/end-of-support

**Comment by davidbuzz** [comment]
superceeded by #22356

**Pull request closed without merging**
