### PR TITLE
Airspeed: remove support for probe list in favor of AP_AIRSPEED_BACKEND_DEFAULT_ENABLED

### PR DESCRIPTION
**Pull request by IamPete1**
Airspeed probe list was added before we had per back end enable defines. Hitec Airspeed was the only user, this updates its HWDEF with the equivalent defines. This simplifys the airspeed code and saves a bit of flash.

### CODE REVIEW

**Comment by IamPete1** [comment]
Saves a little flash:
```
Binary Name    Text [B]        Data [B]     BSS (B)      Total Flash Change [B] (%)      Flash Free After PR (B)
-------------  --------------  -----------  -----------  ----------------------------  -------------------------
ap_periph      -96 (-0.1014%)  0 (0.0000%)  0 (0.0000%)  -96 (-0.1009%)                                     9368
```

**Comment by IamPete1** [comment]
We can also remove the DLVR probe method as it is now unused.

**Comment by tridge** [comment]
@IamPete1 I have this on one of my planes, can test this weekend

**Comment by peterbarker** [comment]
@IamPete1 correct me if I'm wrong, but this is less flexible than the probe list.  The probe list allows specification of a a bus and address, but just enabling the backend doesn't give that flexibility (esp. considering `defined(AP_PERIPH)` is used to gate the existence of the BUS parameter!)

**Comment by IamPete1** [comment]
@peterbarker You are right that the bus default won't work as its not in the table on periph, I will fix that. Your also right that we loose the ability to set an address, but we were using the the standard address anyway. If we did want to support addresses more fully they would probably warrant a dedicated param in anycase.

**Comment by tridge** [comment]
if you have both a baro and an airspeed sensor then you would need probe list as you can't distinguish a ms4525 from a ms5611

**Comment by IamPete1** [comment]
@tridge Probe list does not have any additional capability above the parameters. DLVR is the only airspeed that currently supports probe in any-case so probing does not help with ms4525.

**Pull request closed without merging**
