### PR TITLE
Fix segfault and build on bebop

### PR DESCRIPTION
**Pull request by jberaud**
Segfault was introduced by @tridge recent commit https://github.com/ArduPilot/ardupilot/commit/6e2fbf1988c6cb38bf80703217492a0c3ed03b64
Current bebop build also fails with static linking if lttng-ust is installed on the machine.

### CODE REVIEW

**Comment by jberaud** [comment]
Wrong culprit, not https://github.com/ArduPilot/ardupilot/commit/76b2759317102dc9a649df585152a4f041e48a51  but 6e2fbf1988c6cb38bf80703217492a0c3ed03b64

**Comment by tridge** [comment]
Hi Julien, I think the issue is this code:
https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_OpticalFlow/OpticalFlow.cpp#L71
that is allocating a backend from the frontend constructor, which means it can be allocated before hal is initialised.
Can we just move that code to the init() call, where the other backends are allocated?

**Comment by jberaud** [comment]
@tridge 
I could do that too. But since _sem is only used by the AP_OpticalFlow_Linux backend, then why not putting it inside this class ?
Regarding the need to allocate so early, there is none. It is just that is has been done this way from the beginning and it worked fine untill we had to add a dependancy toward hal.
I think it would be best to move the allocation in the init() function and also to have _sem inside AP_OpticalFlow_Linux class. I could amend the PR to add the allocation in init()

**Comment by tridge** [comment]
the reason for _sem in the backend parent class is that is a new pattern we're adopting. Many drivers don't properly protect the shared data between backend and frontend. Having the semaphore always available to do that makes it more likely driver authors will think about that detail.
We will also need it when we move the PX4 driver to be in-tree with direct I2C on the per-bus thread. It isn't needed in PX4 at the moment as it is all in one thread.

**Comment by lucasdemarchi** [comment]
I cherry-picked the first commit.

**Comment by jberaud** [comment]
@tridge: Ok then. I will push a version without moving the sem in Linux implementation, but it is equivalent to taking the last commit.

**Comment by jberaud** [comment]
Done

**Comment by tridge** [comment]
applied, thanks!

**Pull request closed without merging**
