### PR TITLE
Stick mixing freeze integrator

### PR DESCRIPTION
**Pull request by magicrub**
Stick mixing freeze integrator

### CODE REVIEW

**Comment by rmackay9** [comment]
I don't think we need the changes to AC_PID because the underlying issue that we're trying to resolve here is caused by the pilot's input (during stick mixing) being blended directly into the outputs which can lead to a tug-of-war between the turn rate controller and the pilot.

**Comment by magicrub** [comment]
This greatly improves the current implementation. However, after talking to @rmackay9 we won't merge because:
- the PID controller is getting reworked by Lenard and this may conflict
- the stick mixing must be totally reworked to be completely different than on plane by being a rate controller mixer
- stick mixing input can be acro vs manual style and we must giving the pilot more params knobs to fiddle with to make that choice

**Comment by magicrub** [comment]
See Issue https://github.com/ArduPilot/ardupilot/issues/11262

**Comment by rmackay9** [comment]
@magicrub, great, thanks

**Comment by magicrub** [comment]
I'm reopening this in favor of calling one mode for STICK_MIXING be "[DirectMixing](http://ardupilot.org/plane/docs/parameters.html#stick-mixing-stick-mixing)" like what Plane has, and another option be a higher level one as Randy suggested in issue https://github.com/ArduPilot/ardupilot/issues/11262

**Comment by magicrub** [comment]
in the dev call it was determined that the DIRECT option in plane is bad and shoudl be removed, so adding it to rover is the wrong decision.

**Pull request closed without merging**
