### PR TITLE
Sub: Add slew_rate functionality in RC

### PR DESCRIPTION
**Pull request by patrickelectric**

### CODE REVIEW

**Comment by rmackay9** [comment]
I'm definitely not a fan of this change.

- if slewing is required in only manual mode then it should be implemented in control_manual.cpp. Having the mode check and slewing in the fifty_hz_loop() is not the right place to do this.
- if there is an issue with high current then it is likely coming from the outputs changing too quickly.  Why limit the inputs?  The inputs could actually lead to the current reducing.
- pretty sure this method will greatly reduce the performance of the vehicle

I think there are better ways to achieve the current limiting.  Perhaps it should probably be done inside the motors library and then limit flags should be set to ensure the attitude controllers don't then suffer from I-term build up.  Rover has some motor level throttle slewing that could be a decent reference perhaps.

For input smoothing to the attitude controllers, in Copter we have an ATC_INPUT_TC (attitude control input time constant) parameter so that might be a useful reference.

**Comment by khancyr** [comment]
I agree with Randy. If the slew need to be apply because of the battery or mecanical constraint, it must be apply on the outputs and not inputs. This has cause to much problem on rover in the past...

**Comment by jaxxzer** [comment]
> if slewing is required in only manual mode then it should be implemented in control_manual.cpp. Having the mode check and slewing in the fifty_hz_loop() is not the right place to do this.

This code has to run synchronously with the RC_Channels pwm update. As far as I can see, it has to be here. As far as the mode conditional, it doesn't bother me, and I'm not convinced that it should. This sort of conditional is done all over the place in ardupilot, why is it now a problem here?

> if there is an issue with high current then it is likely coming from the outputs changing too quickly. Why limit the inputs? The inputs could actually lead to the current reducing.

The outputs match the inputs exactly in manual mode (which brings us down to semantics). There is no stabilization/controller involved in manual mode, only the motor mixing. The attitude controllers effectively limit the rate of change on the outputs in the other modes. I'm not sure if there is a good argument either way for putting this limiting on the input or the output, but a putting slew rate in the motors library seemed like the poorer choice.

> pretty sure this method will greatly reduce the performance of the vehicle

The effect of this patch will be negligible to zero in normal operating circumstances. It is for protection against exceptional circumstances.

> I think there are better ways to achieve the current limiting. Perhaps it should probably be done inside the motors library and then limit flags should be set to ensure the attitude controllers don't then suffer from I-term build up. Rover has some motor level throttle slewing that could be a decent reference perhaps.

This is *kind of* like current limiting, but for a specific situation (very short, very large current transients caused by the user screwing around). In manual mode, the user can bash the sticks around and have all of the motors repeatedly go -100 to 100 instantaneously. It makes a lot of noise and splashing, and it is quite entertaining. Unfortunately, it wreaks havoc on the system and has led to an increasingly high frequency of system failures (melted power modules, broken pixhawks, and broken thrusters). We already have current limiting in the motors library. That code _will not help_ in this situation. This particular problem is exacerbated by the fact that our motors are reversible, and blheli is so dang responsive. Again, manual mode has no stabilization/control applied to the outputs. This is what defines manual mode for Sub.

> Rover has some motor level throttle slewing that could be a decent reference perhaps.

This patch provides to Sub exactly the same sort of logic used in throttle limiting for rover and plane, and this patch could actually be useful in the goal of unifying vehicle code.

> For input smoothing to the attitude controllers, in Copter we have an ATC_INPUT_TC (attitude control input time constant) parameter so that might be a useful reference.

The ATC_INPUT_TC won't work for us because AttitudeControl is not involved in manual mode. This might be the same idea, but it's a different context. What we've done here will work for us (while leaving everyone else unaffected). I've got a branch with an LPF, we chose rate limiting to eliminate input lag for fine control. 


We are facing issues in Sub right now, this patch is a response to address those. It is a working patch with very minimal (and I would deem reasonable) changes to the libraries, and only functionally affects Sub. I'm sure that there are more elegant solutions to address the problem. I hope that some day someone can do a patch that improves upon this, but this is a start. It would be great to have this in the code for our users to test, and have available and play with and provide insight on what that better solution might look like. 

@rmackay9, does any of this change your opinion of the PR? I'm not a control expert, further inputs and reviews are welcome.

**Comment by jaxxzer** [comment]
Two reasons to put this on the output instead:
Logging
Mode change from auto->manual while input is applied

Move the limiting to motors/output side. Slew either the demand going into the mixer (rpy etc), or the servo output.

**Comment by jaxxzer** [comment]
Closing in favor of #8228

**Pull request closed without merging**
