### PR TITLE
AC_PrecLand: add target velocity estimation

### PR DESCRIPTION
**Pull request by jschall**
These changes:
- Largely decouple precision landing performance from GPS accuracy.
- Disable precision landing without a rangefinder (for the time being - until an estimator capable of depth-from-motion is introduced)
- Are a step towards precision landing with no GPS (just need some logic to switch AC_PosControl over to a different position input)
- Correct for distortion in the IR-LOCK lens (PX4Firmware patch)

### CODE REVIEW

**Comment by jschall** [comment]
Incorporated PR #4547

**Comment by jschall** [comment]
Changed that to PR #4550

**Comment by OXINARF** [comment]
@jschall This is intermittently failing SITL quadplane testing.

**Comment by jschall** [comment]
@OXINARF good catch and not surprising. I'll address it.

**Comment by jschall** [comment]
@OXINARF made a fix for that. We'll see how it does.

**Comment by OXINARF** [comment]
@jschall It has now run the SITL testing three times and passed all of them, so I guess it is fixed.

**Comment by jschall** [comment]
Known issues:
- Having EK2_MAG_CAL enabled (default) can cause a bad landing if the target is on a magnetic surface
- Having EK2_IMU_MASK set to 3 (default) can cause a bad landing if the EKF decides to use an IMU that is not the primary IMU.

**Comment by UaviaDrones** [comment]
Could you explain a bit more about the horizontal control strategy ? How is the code using both the position controller & the velocity controller ? Thanks for that beautiful work !

**Comment by rmackay9** [comment]
I'm going to test this now.

**Comment by rmackay9** [comment]
I tested this and it worked very well.  I didn't do as rigorous a test as with the previous PRs (that greatly improved things) so I can't give exact numbers of distance from the target but anecdotally, it seemed better.  It seemed to slow better just before touchdown.

**Comment by jschall** [comment]
The main advantage of this is that it decouples the precision landing performance from GPS performance. AC_PrecLand is capable of doing precision landings indoors, there just needs to be some AC_PosControl work.

**Comment by jschall** [comment]
Also, for the best possible precision landings, EK2_MAG_CAL should be set to turn mag field fusion off.

**Comment by rmackay9** [comment]
I've asked Tridge and Paul to have a peek at the AHRS and EKF changes.
@tridge mentioned that you might want to push a branch on ardupilot with the px4firmware fix in order to fix travis instead of changing the submodule URL.

**Comment by magicrub** [comment]
status?

**Comment by rmackay9** [comment]
@tridge merged the AHRS changes to master today so that clears the way for this to go into master.  I've rebased it on master and I'll do a quick test tomorrow to ensure that it's still working ok.

**Comment by jschall** [comment]
Rebased and pushed.

**Comment by rmackay9** [comment]
Merged, thanks so much!
I did another test this morning and I manually applied yaw as it descended (not super fast but perhaps 45deg per second) and it still landed right on the target.  nicely done!

**Pull request closed without merging**
