### PR TITLE
AP_GPS: add AP_GPS_FEMTO driver for Femtomes GPS

### PR DESCRIPTION
**Pull request by Femtomes**
1.Add AP_GPS_FEMTO driver for Femtomes gps device
2.Add femtomes driver in AP_GPS class

### CODE REVIEW

**Comment by WickedShell** [comment]
I don't see how this has made any effort on the issues raised in #17582. Please push changes to the same branch, which allows you to continue to use the same PR, rather then opening new ones repeatedly. It makes it very hard to track what has been addressed, and what review comments are still pending.

**Comment by Femtomes** [comment]
> I don't see how this has made any effort on the issues raised in #17582. Please push changes to the same branch, which allows you to continue to use the same PR, rather then opening new ones repeatedly. It makes it very hard to track what has been addressed, and what review comments are still pending.

You mean, I should close this PR, then reopen #17582, submit the changes?

**Comment by Femtomes** [comment]
Dear WickedShell,
    I have done the common parser class for Nova and Femto, [AP_GPS: add binary CRC message parser abstract class #18012](https://github.com/ArduPilot/ardupilot/pull/18012),  does it meet your requirements?

**Comment by Femtomes** [comment]
Reorganized code at #18690

**Pull request closed without merging**
