### PR TITLE
Add autotest to weed out default-values in default files

### PR DESCRIPTION
**Pull request by peterbarker**
A lot of fames are specifying EKF2 in their files where that's the default.

When we move to EKF3 by default that's a problem.

This tool does run on the other vehicle types, but the changes to their defaults are extensive so I've chosen to do a separate PR for those.

This new test is disabled at the moment but can be run with: `./Tools/autotest/autotest.py --gdb --debug build.Copter test.Copter.FrameDefaults`

### CODE REVIEW

**Comment by peterbarker** [comment]
Most of the Copter frames are spitting the equivalent of this out:

```
Loaded 70 parameters from /home/pbarker/rc/ardupilot/Tools/autotest/default_params/copter.parm
Loaded 1 parameters from /home/pbarker/rc/ardupilot/Tools/autotest/default_params/copter-dodecahexa.parm
AT-0112.2: Frame (dodeca-hexa) failed:
AT-0112.2:         /home/pbarker/rc/ardupilot/Tools/autotest/default_params/copter.parm has same value (1.000000) in (FS_THR_ENABLE) and in firmware
AT-0112.2:         /home/pbarker/rc/ardupilot/Tools/autotest/default_params/copter.parm has same value (5.000000) in (COMPASS_OFS_X) and in firmware
AT-0112.2:         /home/pbarker/rc/ardupilot/Tools/autotest/default_params/copter.parm has same value (13.000000) in (COMPASS_OFS_Y) and in firmware
AT-0112.2:         /home/pbarker/rc/ardupilot/Tools/autotest/default_params/copter.parm has same value (-18.000000) in (COMPASS_OFS_Z) and in firmware
AT-0112.2:         /home/pbarker/rc/ardupilot/Tools/autotest/default_params/copter.parm has same value (5.000000) in (COMPASS_OFS2_X) and in firmware
AT-0112.2:         /home/pbarker/rc/ardupilot/Tools/autotest/default_params/copter.parm has same value (13.000000) in (COMPASS_OFS2_Y) and in firmware
AT-0112.2:         /home/pbarker/rc/ardupilot/Tools/autotest/default_params/copter.parm has same value (-18.000000) in (COMPASS_OFS2_Z) and in firmware
AT-0112.2:         /home/pbarker/rc/ardupilot/Tools/autotest/default_params/copter.parm has same value (5.000000) in (COMPASS_OFS3_X) and in firmware
AT-0112.2:         /home/pbarker/rc/ardupilot/Tools/autotest/default_params/copter.parm has same value (13.000000) in (COMPASS_OFS3_Y) and in firmware
AT-0112.2:         /home/pbarker/rc/ardupilot/Tools/autotest/default_params/copter.parm has same value (-18.000000) in (COMPASS_OFS3_Z) and in firmware
AT-0112.2:         /home/pbarker/rc/ardupilot/Tools/autotest/default_params/copter.parm has same value (1500.000000) in (RC1_TRIM) and in firmware
AT-0112.2:         /home/pbarker/rc/ardupilot/Tools/autotest/default_params/copter.parm has same value (1500.000000) in (RC2_TRIM) and in firmware
AT-0112.2:         /home/pbarker/rc/ardupilot/Tools/autotest/default_params/copter.parm has same value (1500.000000) in (RC3_TRIM) and in firmware
AT-0112.2:         /home/pbarker/rc/ardupilot/Tools/autotest/default_params/copter.parm has same value (1500.000000) in (RC4_TRIM) and in firmware
AT-0112.2:         /home/pbarker/rc/ardupilot/Tools/autotest/default_params/copter.parm has same value (1500.000000) in (RC5_TRIM) and in firmware
AT-0112.2:         /home/pbarker/rc/ardupilot/Tools/autotest/default_params/copter.parm has same value (1500.000000) in (RC6_TRIM) and in firmware
AT-0112.2:         /home/pbarker/rc/ardupilot/Tools/autotest/default_params/copter.parm has same value (1500.000000) in (RC7_TRIM) and in firmware
AT-0112.2:         /home/pbarker/rc/ardupilot/Tools/autotest/default_params/copter.parm has same value (1500.000000) in (RC8_TRIM) and in firmware
AT-0112.2:         /home/pbarker/rc/ardupilot/Tools/autotest/default_params/copter.parm has same value (0.000000) in (FLTMODE6) and in firmware
AT-0112.2:         /home/pbarker/rc/ardupilot/Tools/autotest/default_params/copter.parm has same value (0.000000) in (INS_ACC3OFFS_X) and in firmware
AT-0112.2:         /home/pbarker/rc/ardupilot/Tools/autotest/default_params/copter.parm has same value (0.000000) in (INS_ACC3OFFS_Y) and in firmware
AT-0112.2:         /home/pbarker/rc/ardupilot/Tools/autotest/default_params/copter.parm has same value (0.000000) in (INS_ACC3OFFS_Z) and in firmware
```

**Comment by tridge** [comment]
we really need to add proper support for downloading defaults, preferably via ftp. The key would be to handle the ones where we do set_default()

**Comment by tridge** [comment]
this is only for sitl params, right? For non-SITL we have a problem that SITL and non-SITL may have different defaults

**Comment by peterbarker** [comment]
@tridge yes, this is for the SITL parameters represented in `vehicleinfo.py`.

I've *considered* augmenting this to look at all of the files in `Tools/Frame_params` - but we don't even know what *vehicle* they're for, which would slow that down somewhat :-)

**Review by tridge — APPROVED** [review]

**Pull request merged**
