### PR TITLE
AP_GPS: Do not set the bit decision.

### PR DESCRIPTION
**Pull request by muramura**
0 is set to 1 by using the exclusive OR.
This value to the condition of the if statement.

### CODE REVIEW

**Comment by OXINARF** [comment]
I understand your thinking but, to me, this is way more unreadable - and the advantage is small.

**Comment by muramura** [comment]
@OXINARF Comment Thanks.
To change the bit field.
To change from multiple ignore bit to multiple have bit.
Using this have bit on the condition of the if statement.
It becomes even more simple.

**Comment by magicrub** [comment]
Woah. I think you pushed to the wrong branch, these chins are waaaaay out of scope. I'm closing. Please open a new pr for whatever this was intended for

**Comment by magicrub** [comment]
Ahh, actually I think it just needed a rebase. Reopen after you've fixed
the branch and think it's worth submitting again.

**Comment by muramura** [comment]
@magicrub Comments Thanks.
I think.
Re New PR.

**Pull request closed without merging**
