### PR TITLE
AP_GPS: fixed TMODE config issue on non-F9 GPS

### PR DESCRIPTION
**Pull request by tridge**
thanks to Michel Pastor for reporting this

### CODE REVIEW

**Comment by shellixyz** [comment]
I tested the fix and the issue is gone. Thanks @tridge

**Comment by rmackay9** [comment]
Ah, I was seeing a new "GPS Failed configuration" error yesterday and couldn't get it to go away.. I wonder if this was the issue.

**Comment by rmackay9** [comment]
I ping'd @WickedShell and he asked that we hold off until tomorrow before merging

**Comment by tridge** [comment]
The bug was my fault, I didn't consider the effect on non-F9 when adding the TMODE fix

**Comment by WickedShell** [comment]
#12831 contains 2 fixup patches, the first one is definetly needed, couldn't push to tridges PR apparently.

**Comment by Naterater** [comment]
I also ran into this bug that causes warnings in Mission Planner when trying to arm with all checks enabled. Really looking forward to this being fixed as this comes up when running "latest"/master.

**Comment by tridge** [comment]
closing as replaced by #12831

**Comment by rmackay9** [comment]
I've removed the backports tags and instead added them to the replacement PR.

**Pull request closed without merging**
