### PR TITLE
Rover: fix stick mixing in auto mode

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by rmackay9** [comment]
From a review back through the versions it looks to me like Rover's stick mixing has never worked in any stable release.

The feature has a slightly checkered past because its implementation was not correct ([see issue here](https://github.com/ArduPilot/ardupilot/issues/11262)) and [it was merged without proper review](https://github.com/ArduPilot/ardupilot/pull/11244).

Putting that aside I'd like to be sure it's been tested.  I don't think we should rush it into 4.2 because it has been broken for so long that it doesn't seem to be a critical bug fix.

**Comment by peterbarker** [comment]
> From a review back through the versions it looks to me like Rover's stick mixing has never worked in any stable release.
> 
> The feature has a slightly checkered past because its implementation was not correct ([see issue here](https://github.com/ArduPilot/ardupilot/issues/11262)) and [it was merged without proper review](https://github.com/ArduPilot/ardupilot/pull/11244).
> 
> Putting that aside I'd like to be sure it's been tested. I don't think we should rush it into 4.2 because it has been broken for so long that it doesn't seem to be a critical bug fix.

That new autotest I wrote doesn't work before this PR but does work afterwards.

Playing around with this in SITL you can clearly see the feature fighting integrators, but enough shoving and the vehicle goes where you want it to.

I did *not* go looking for more instances of the same problem - for example, in guided mode - but they may be present.

I wouldn't suggest this for a backport.

**Comment by rmackay9** [comment]
@peterbarker thanks for that and the confirmation re the fight between autopilot and pilot.  @TunaLobster has also tested it apparently so I've held my nose again on the implementation and merged it in the hopes that some users will find it useful.

**Comment by geofrancis** [comment]
Thank you for this, I have been looking at using mavlink Rc override commands via stick mixing to do fine corrections using rangefinders in order for it to follow a corridor.

**Pull request merged**
