### PR TITLE
Rover: limit speed so rovers stays within lane between waypoints

### PR DESCRIPTION
**Pull request by rmackay9**
This PR replaces the formula used to calculate how much the desired speed should be reduced in order that the vehicle stay close to the line between waypoints.

The current method (before these changes are applied) uses the SPEED_TURN_GAIN parameter to specify how much the desired speed should be **scaled** down as the heading error to waypoint increases (i.e. by default a 90 degree heading error leads to 50% reduction is speed).  The problem with this approach is that as WP_SPEED (or CRUISE_SPEED) is increased the vehicle will make wider and wider turns.  The user can counteract this by changing the SPEED_TURN_GAIN but it is difficult to get right and doesn't work when the mission has legs with different speeds (i.e. DO_CHANGE_SPEED commands are in the mission).

The new approach essentially creates a virtual lane which is WP_OVERSHOOT meters on either side of the line between the origin and destination.  Within the "calc_reduced_speed_for_turn_or_distance" function we calculate the vehicle's distance to the edge of the lane, We then calculate the vehicle's maximum speed in order for it to make the turn.  This calculation relies on the maximum lateral acceleration of the vehicle (TURN_MAX_G) being set appropriately.  A simplified version of this same calculation is already used to calculate the _desired_speed_final which is used to reduce the vehicle's speed as it approaches a waypoint.

In SITL this method seems to work well.  The WP_SPEED can be set extremely high and the vehicle will simply drive at the maximum speed it can but still properly slow down for corners.

rover-speed-within-lane

There are some known issues:

- as brought up by @tridge on the dev call, this method relies on the vehicle moving in the direction it is heading.  It **may** not perform well in boats in a very strong current (it may be fine, we just need to test).  Note that the current SPEED_TURN_GAIN method has a similar weakness.
- a vehicle with a poorly tuned steering control may bounce back and forth against the outsides of the lane.  Slowing as it goes outside the lane, over steering back into the lane, hitting the other side of the lane, etc.  With the old method, the vehicle would get to the next waypoint faster but would veer far off the path.  It is a bit of a judgement call as to whether it is more important that the vehicle get to its target or that it stays within the lane.

### CODE REVIEW

**Comment by OXINARF** [comment]
The math is over my head, but logic looks good.

**Comment by rmackay9** [comment]
@OXINARF, thanks, merged!

**Comment by whiani** [comment]
https://github.com/ArduPilot/ardupilot/blob/Rover-4.0/libraries/AR_WPNav/AR_WPNav.cpp#L400
How does the formula come from?

**Comment by whiani** [comment]
@rmackay9

**Comment by rmackay9** [comment]
@whiani, I have a spreadsheet where I struggled and came up with this.  I can hardly make sense of it but in case you're interested I've put it here: https://www.dropbox.com/s/7mqlbissz54ylr2/cornering-thoughts.xlsx?dl=0

**Comment by whiani** [comment]
My understanding is shown in the figure below:
https://drive.google.com/file/d/183m54PNoluvIu9BnFsmXhkF3u063I3kd/view?usp=sharing
So I think the calculation of turn_angle_rad is incorrect, what do you think.

**Comment by whiani** [comment]
@rmackay9

**Pull request merged**
