### PR TITLE
AP_Scripting: allow scripts to control the gimbal mount

### PR DESCRIPTION
**Pull request by githubtd01**
These changes allow lua scripting to control the gimbal mount, which is important for vehicles which use serial communication with the gimbal (e.g. Basecam gimbals):

Add lua scripting bindings for the method 
`      void set_angle_targets(uint8_t instance, float roll, float tilt, float pan);`
in line 121 in /libraries/AP_Mount/AP_Mount.h

To control the mount in lua use:
`       mount:set_angle_targets(roll, pitch, yaw)`

Prepared with the help of Peter Hall. https://discuss.ardupilot.org/t/is-it-possible-to-change-waypoint-speed-and-camera-mount-pitch/62101/5

### CODE REVIEW

**Comment by IamPete1** [comment]
Would be great to have a example and demo of this to go with the binding

**Comment by githubtd01** [comment]
I have no idea how to get a compiled version of arducopter with this code. If I get one and can test it I'm very happy to contribute a (simple) example.
I think this is useful for mapping to orientate the camera in auto modus and it is also useful during take off and landing to orientate the camera into a safer position.

**Comment by IamPete1** [comment]
The build environment is quite straight forward to setup, https://ardupilot.org/dev/docs/building-setup-windows10.html#building-setup-windows10

Or I could build you a test firmware, what flight controller?

**Comment by rmackay9** [comment]
This is really great to see.  I definitely support this enhancement!

**Comment by WickedShell** [comment]
My main questions are: the angle limits seem tighter then necessary, does that reflect any internal limitations in the code here? Just seems like we might want to allow a roll of more then 90 degrees?

The other question is all the rest of the scripting attitude inputs (IE AHRS.roll etc) are all in radians, do we want to make the gimbal control also be in radians for consistency?

**Comment by githubtd01** [comment]
> My main questions are: the angle limits seem tighter then necessary, does that reflect any internal limitations in the code here? Just seems like we might want to allow a roll of more then 90 degrees?

You are right, the at least the pitch angle should go beyond 90 degrees. I'm not sure with the roll, that would probably cause problems with many gimbals?

> The other question is all the rest of the scripting attitude inputs (IE AHRS.roll etc) are all in radians, do we want to make the gimbal control also be in radians for consistency?

I think all gimbal related settings are in degrees.

**Comment by davidbuzz** [comment]
can this go in?

**Comment by githubtd01** [comment]
> can this go in?

Would be great. Unfortunately I'm not able to test it. I'm sorry, but I'm simple overloaded with work.

**Comment by peterbarker** [comment]
Thanks @githubtd01 for tackling this.  You were definitely on the right track with this work.

We now have extensive support for controlling the gimbal in our LUA bindings.

Thanks anyway!

**Pull request closed without merging**
