### PR TITLE
AP_Mission: only continue after land if next waypoint is a takeoff

### LINKED ISSUE #7929: Copter: ensure missions with land/rtl in the middle require takeoff afterwards
Copter missions support having a Land or RTL in the middle of the mission.

Although we require the first command in a mission to be a takeoff command (if auto is initiated while the vehicle is landed) we do not require a takeoff command if the mission includes a Land or RTL in the middle.

We should require a takeoff or else the vehicle will likely flip when it starts executing the following waypoint of spline command.

### PR DESCRIPTION
**Pull request by IamPete1**
Fixes #7929

### CODE REVIEW

**Comment by rmackay9** [comment]
This look pretty good to me.  I'd immediately give it an approval but I'm just holding off to hear what testing has been done.

**Comment by IamPete1** [comment]
@rmackay9 tested in SITL on copter. 

I notice were missing `MAV_CMD_NAV_VTOL_TAKEOFF` as a takeoff command for plane, so we should fix that too.

**Comment by IamPete1** [comment]
added `MAV_CMD_NAV_VTOL_TAKEOFF` as a takeoff command

**Comment by rmackay9** [comment]
I think this is a good idea.  It is an extension of our existing check to require-a-takeoff command to get the vehicle into the air.

**Comment by IamPete1** [comment]
This is now copter only.

**Comment by tridge** [comment]
> I think this is a good idea. It is an extension of our existing check to require-a-takeoff command to get the vehicle into the air.

it is much more than that. It assumes that the only valid NAV command after a LAND is takeoff. Here are some things this will prevent from working:
 - any ability to have a "wait for takeoff permission" NAV command, which is what you would want for package delivery
 - a lua script that implements any mission item with a verify method
 - a balloon lift command, NAV_WAIT_ALTITUDE

it means we will need to keep adding new exceptions to the list of what commands can come next.

**Comment by IamPete1** [comment]
@tridge I don't really see any issue with adding exceptions with those new commands are added. 

Lua scripts still work, you just set a very long delay before the takeoff then jump past the remaining delay. 

Why would `NAV_WAIT_ALTITUDE` ever come after a landing?

**Comment by IamPete1** [comment]
This is now copter only

**Comment by rmackay9** [comment]
Merged, thanks!

**Pull request merged**
