### PR TITLE
Update AP_NavEKF2_Control.cpp

### PR DESCRIPTION
**Pull request by jfint**
Add check for a valid frontend origin to prevent subsequent instances of ekf2 from compounding the inflight offset.

### CODE REVIEW

**Comment by rmackay9** [comment]
@jfint, thanks for this.  Could you change the commit description to start with "AP_NavEKF2:"?  To be clear, I'm talking about the commit description, not the PR description.

**Comment by jfint** [comment]
@rmackay9 I believe I have changed the commit comment.  I have to pull a Me-a Culpa on the data, as it was just pointed out that I have been looking at the NED values as adding 0 based number the second time and not ground based, so I will try to re-prove again tomorrow, unfortunately I have not discovered a way to try this particular thing on the sim.

**Comment by rmackay9** [comment]
@jfint, thanks the commit description looks better now.

**Comment by jfint** [comment]
This is my first time making a pull request in ardupilot, I don't want to be time consuming, but can I get some feedback on the sub test that failed?

**Comment by peterbarker** [comment]
@jfint I had a good look at the Sub tests.

Definitely not your fault.  I've never seen our connection to mavproxy explode so thoroughly, but that it did.

I've restarted the failing tests.

**Comment by jfint** [comment]
Tests today, show that this did not fix what we are seeing, so I am closing this request and then opening a bug for track again.

image

**Comment by jfint** [comment]
Bug is here:
https://github.com/ArduPilot/ardupilot/issues/16450

**Pull request closed without merging**
