### PR TITLE
PX4NuttX: setup I2C digital filter

### PR DESCRIPTION
**Pull request by tridge**
This may reduce the impact of I2C bus noise, which could help with compasses and with airspeed sensors

### CODE REVIEW

**Comment by OXINARF** [comment]
From a logic perspective looks good, but I can't say much more. I'll only ask if this was tested in all PX4 boards (and maybe Aero)?

**Comment by tridge** [comment]
only tested on FMUv2 so far

**Comment by WickedShell** [comment]
The comment for the table number should be annotated with the datasheet version you are using, because the RM0090 I used it was a very different table number.

**Comment by WickedShell** [comment]
The digital noise filter makes a significant improvement to the readings of the data off the bus. Far fewer bit flips on sensor data. (It doesn't entirely eliminate them, you can see a single temperature spike on the log with the noise filter, but compared to the other log file it's a massive improvement.

This data is collected from an extremely noisy system, that has large grounding problem on the I2C signal lines, crosstalk, and is generally quite a horrible RF enviorment. There remains a bug where the MS4525DO driver can accept data that is invalid, but @tridge and I think we can manage this by double reading the sensor, and rejecting any min/max sensor output values (the most common failure remaining).

With the filter:
figure_1-7
Without the filter:
figure_1-8

**Comment by WickedShell** [comment]
With:
figure_1-9
Without:
figure_1-10

**Comment by tridge** [comment]
excellent results Michael!
@lucasdemarchi, can you test on aero-fc?
@rmackay9 can you do a flight test on a copter?

**Comment by tridge** [comment]
@rmackay9 randy did a successful test flight, so I will push now

**Comment by WickedShell** [comment]
Flight tested this as well at this point, no issue, cleaned up a noisy system quite nicely.

**Pull request closed without merging**
