### PR TITLE
Copter: add ARMING_OPTION to hide prearm messages

### PR DESCRIPTION
**Pull request by tatsuy**
There are two changes.
~~1. move disarm_switch_checks from pre_arm_checks to arm_checks
it's affected for all vehicle types~~
1. add ARMING_OPTION to hide prearm messages
pre arm checks display the message every 30 seconds but that was unnecessary.
image

2. check disarm switch even arming checks are disabled
it's affected for only copter
In current master, the user can arm when arming checks are disabled and disarm switch is High.
but, Estop does not allow users to arm even if arming check is disabled.
I felt that it should be the same as EStop, or it makes users confusing.

3. turn the LED yellow when the vehicle can't be armed

note: disarm switch is like EStop+Disarm immediately #14244

I tested the followings in SITL:
```
param set RC9_OPTION 81
param set ARMING_CHECK 1
rc 9 2000      // LED is yellow
arm throttle // cannot arm
rc 9 1000      // LED is green
arm throttle // arming
rc 9 2000 // disarm by Disarm Switch

param set ARMING_CHECK 0    // LED is yellow (in master, it was green)
arm throttle // cannot arm in this branch (in master, the vehicle can arm)
rc 9 1000      // LED is green
arm throttle // arming
rc 9 2000 // disarm by Disarm Switch
```

### CODE REVIEW

**Comment by muramura** [comment]
I was in DISARMED state, and the DISARM SW was turned on.
I see the message "PreArm: Disarm Switch on" every 30 seconds.
I don't think it's necessary to check the status of this SW in the pre-arm check.
I would like to see a change to check this SW during arm operation.

Screenshot from 2022-01-22 21-41-28

**Comment by tatsuy** [comment]
That's what I fixed.

your version (bd4aed80) is master branch.
Please check this PR branch.

**Comment by peterbarker** [comment]
I can see that this makes things a bit more sensible, in that this is now treated like eSTOP is.

However, I'd prefer that we run both checks in prearm rather than both checks in arm.  I doubt that's going to be a common sentiment - marking for discussion at DevCall.

**Comment by WickedShell** [comment]
> However, I'd prefer that we run both checks in prearm rather than both checks in arm. I doubt that's going to be a common sentiment - marking for discussion at DevCall.

I'd agree with this position, it's really a prearm check and something we should do early. Personally I just don't think we should be spamming the status text messages out at all, but that's a separate conversation.

**Comment by rmackay9** [comment]
We discussed this on the dev call and thought that maybe the real underlying problem is that our pre-arm checks are too noisy.  IS the purpose of this change really to make the pre-arm checks quieter?  If "yes" then we think we should add an ARMING_OPTIONS bit to allow enabling/disabling the 30sec check and instead only display pre-arm check failures when the user tries to arm.

**Comment by peterbarker** [comment]
> We discussed this on the dev call and thought that maybe the real underlying problem is that our pre-arm checks are too noisy. IS the purpose of this change really to make the pre-arm checks quieter? If "yes" then we think we should add an ARMING_OPTIONS bit to allow enabling/disabling the 30sec check and instead only display pre-arm check failures when the user tries to arm.

To clarify, we'd continue to run the checks (so we update the SYS_STATUS prearm bit - just do so in a non-noisy manner.

**Comment by tatsuy** [comment]
Thank you for your comments!
OK, I will add ARMING_OPTIONS bit not to display the message for every 30 seconds.

In my opinion, errors related to AP internal status, such as EKF-related errors, cannot be known by the user, so it is useful to display them every 30 seconds.
But, the user is able to know the switch position error by looking at the transmitter, so I thought it should be checked only during arming.

I just wrote it becacuse I want to leave my point of view.

By the way, this pr includes two things:
1. move disarm_switch_checks from pre_arm_checks to arm_checks
2. check disarm switch even arming checks are disabled

But, it's discussed about only 1st one.
I'll separate it and make another PR of 2nd one.

**Comment by muramura** [comment]
@tatsuy san

> But, the user is able to know the switch position error by looking at the transmitter, so I thought it should be checked only during arming.

Is it true that all operators check the status of all switches on the radio before arming?
I sometimes correct the switches by listening to the vehicle buzzer sound during arm operation.
The radio has a lot of switches, volumes, sliders, etc.
I will check the important switches.
But do you check that the DISARM switch is off every time?
I don't think I do every time.

**Comment by peterbarker** [comment]
On Tue, 25 Jan 2022, murata,katsutoshi wrote:

> I will check the important switches.
> But do you check that the DISARM switch is off every time?

I wouldn't consider this switch "important".  I would consider this switch 
*critical*.

**Comment by tatsuy** [comment]
I've reworked it based on your advice.
I made it keep the prearm check and add ARMING_OPTIONS to hide the message.
I am happy with this specification.

> I wouldn't consider this switch "important".  I would consider this switch
*critical*.

Yes, I agree with Peter. This is critical.
I think critical means it should be checked even if arming check is disabled.
I added it to the same place as EStop (arm_checks) in this PR.

I tested in SITL

In Copter
// pattern1 (default)
ARMING_CHECK 1
ARMING_OPTIONS 0
enable prearm message

// pattern2
ARMING_CHECK 1
ARMING_OPTIONS 1
disable prearm message

// pattern3
ARMING_CHECK 0
ARMING_OPTIONS 0
disable prearm message

// pattern4
ARMING_CHECK 0
ARMING_OPTIONS 1
disable prearm message

In all patterns, if Disarm Switch is on, arming is prevented.

In Plane/Rover
This is the same behavior as the current master.

**Comment by rmackay9** [comment]
Hi, I tested this and I have two questions/concerns:

1. the new ARM_OPTIONS seems to be a duplicate of the existing ARM_RUDDER.  I think I must be missing something though
2. with the change to the Disarm aux switch position, the status LEDs don't match the arming checks.  So the vehicle cannot be armed but the LEDs are green.  This could be quite annoying for users because they would think they could arm but then they couldn't.

**Comment by tatsuy** [comment]
@rmackay9 Thank you for the review.
> with the change to the Disarm aux switch position, the status LEDs don't match the arming checks. So the vehicle cannot be armed but the LEDs are green. This could be quite annoying for users because they would think they could arm but then they couldn't.

This is the same problem with EStop and Interlock.
I will see if I can fix all of those with this PR.

**Comment by rmackay9** [comment]
@tatsuy, oh really?  that's not good.  Thanks for trying to resolve this.

**Comment by tatsuy** [comment]
@rmackay9 
I've fixed two things that you found.
Could you review these again?

**Comment by rmackay9** [comment]
@tatsuy,

Txs for this.  I've retested and it all seems to work as expected.  So in particular:

- the "Disable" switch must now be in the off position to arm the vehicle.  This is consistent with "Motor Emergency Stop" and "Interlock"
- the LEDs flash yellow indicating the vehicle cannot be armed for all three of the above mentioned switches if they are in the "wrong" position.
- the new ARMING_OPTIONS allows pre-arm check messages to be silenced

One small thing though is the ARMING_OPTIONS parameter is visible for all vehicles but only Copter uses it right?  I think we should only make it visible to Copter by using the "AP_GROUPINFO_FRAME" definition ([see here for a random example from another library that uses this](https://github.com/ArduPilot/ardupilot/blob/master/libraries/AC_Avoidance/AC_Avoid.cpp#L91))

@bnsgeyer, have you ever noticed that when the vehicle can't be armed because of the interlock switch position, the vehicle's LEDs are still green?  From my point of view, this is annoying to the user because they will think they can arm but then when they actually try to arm, it will fail with the sad tone.  I think this is annoying and can even be embarrassing if you've got people watching but what do you think?

**Comment by bnsgeyer** [comment]
@rmackay9 yes, I would agree with you. If for some reason the interlock switch was enabled before arming, I would expect a yellow light and some message to indicate that I couldn’t arm.

**Comment by tatsuy** [comment]
Thank you!
yes, I added AP_PARAM_FRAME_COPTER here.
https://github.com/ArduPilot/ardupilot/pull/19829/files#diff-19590cf17b8265289b1ac103bbaf4f4e8ce4f3541a036524326a368a7c3702b7R136

And I checked ARMING_OPTION isn't displayed in plane and rover.

**Comment by WickedShell** [comment]
I fell I'm missing something here, I'm on Plane so the ARMING_OPTION parameter is hidden, but plane now spams the prearm checks at me, which it didn't used to do, which is not what I want it to do. Is there any reason we shouldn't be sharing this parameter for all vehicles?

**Pull request merged**
