### PR TITLE
GCS_MAVLink: abort in SITL if unknown message sent

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by WickedShell** [comment]
Maybe panic rather then abort? (Assuming panic leaves the binray open/printfs I imagine this might be clearer why SITL quit?)

**Comment by OXINARF** [comment]
@WickedShell Interesting comment, I never noticed that, contrary to PX4 and Linux HALs, the SITL HAL actually stays in a for loop in case of a panic. I'm not sure that is very useful here, but I'm sure it can be in other places.

**Comment by peterbarker** [comment]
@OXINARF I guess staying in the infinite loop would allow you to attach a debugger to the process to inspect locals and the like, something `abort()` won't do.

I've changed this to a panic and pushed it up.

**Comment by OXINARF** [comment]
I changed the commit message to say *panic* instead of *abort* and merged. Thanks!

**Pull request closed without merging**
