### PR TITLE
AP_HAL_ESP32: Add GPIO driver for ESP32

### PR DESCRIPTION
**Pull request by sblaksono**
Add GPIO driver for ESP32

### CODE REVIEW

**Comment by sblaksono** [comment]
Done merging, tested on my esp32 board. No issue...

**Comment by tpwrules** [comment]
Please rebase on master and squash to one commit, the project does not permit merge commits.

**Comment by sblaksono** [comment]
@tpwrules done

**Comment by peterbarker** [comment]
> @tpwrules done

Well... what @tpwrules really meant was  *two* commits - one per logical subsystem.   Sorry, we're not making this stuff up, it's in here: https://ardupilot.org/dev/docs/submitting-patches-back-to-master.html#preparing-commits :-)

I've made that split for you and tweaked a commit message and marked this one as "merge on CI pass".

Thanks!

**Comment by sblaksono** [comment]
Thank you, newbie here :)

**Review by tpwrules — APPROVED** [review]
Tested and "sounds" good to me :)

**Pull request merged**
