### PR TITLE
Stop including un-needed headers in other headers

### PR DESCRIPTION
**Pull request by peterbarker**
Unnecessary includes lead to a rebuild cascade as everything depends on everything else.

This was focussing on the HAL includes, but lots of other things in here.

### CODE REVIEW

**Comment by amilcarlucas** [comment]
Strange results for an NFC change:
```
Binary Name      Text [B]           Data [B]     BSS (B)        Total Flash Change [B] (%)      Flash Free After PR (B)
---------------  -----------------  -----------  -------------  ----------------------------  -------------------------
antennatracker   -46164 (-3.4227%)  0 (0.0000%)  4 (+0.0015%)   -46164 (-3.4181%)                                661648
arducopter       -46168 (-2.6218%)  0 (0.0000%)  0 (0.0000%)    -46168 (-2.6171%)                                248172
ardusub          -46172 (-2.9764%)  0 (0.0000%)  -4 (-0.0015%)  -46172 (-2.9728%)                                459120
arducopter-heli  -46168 (-2.6096%)  0 (0.0000%)  0 (0.0000%)    -46168 (-2.6049%)                                239908
ardurover        -46164 (-2.9055%)  0 (0.0000%)  4 (+0.0015%)   -46164 (-2.9022%)                                421568
blimp            -46164 (-3.5781%)  0 (0.0000%)  -4 (-0.0015%)  -46164 (-3.5731%)                                720256
arduplane        -46164 (-2.6495%)  0 (0.0000%)  -4 (-0.0015%)  -46164 (-2.6448%)                                266760
```

**Comment by peterbarker** [comment]
> Strange results for an NFC change:
> 
> ```
> Binary Name      Text [B]           Data [B]     BSS (B)        Total Flash Change [B] (%)      Flash Free After PR (B)
> ---------------  -----------------  -----------  -------------  ----------------------------  -------------------------
> antennatracker   -46164 (-3.4227%)  0 (0.0000%)  4 (+0.0015%)   -46164 (-3.4181%)                                661648
> arducopter       -46168 (-2.6218%)  0 (0.0000%)  0 (0.0000%)    -46168 (-2.6171%)                                248172
> ardusub          -46172 (-2.9764%)  0 (0.0000%)  -4 (-0.0015%)  -46172 (-2.9728%)                                459120
> arducopter-heli  -46168 (-2.6096%)  0 (0.0000%)  0 (0.0000%)    -46168 (-2.6049%)                                239908
> ardurover        -46164 (-2.9055%)  0 (0.0000%)  4 (+0.0015%)   -46164 (-2.9022%)                                421568
> blimp            -46164 (-3.5781%)  0 (0.0000%)  -4 (-0.0015%)  -46164 (-3.5731%)                                720256
> arduplane        -46164 (-2.6495%)  0 (0.0000%)  -4 (-0.0015%)  -46164 (-2.6448%)                                266760
> ```

It will be NFC by the time it is done with any luck - give or take optimisations.

But our use of `#indef FOO` means that you can end up with this sort of thing.

**Review by khancyr — APPROVED** [review]
Nice one.
Removed a lot of git clone #include <AP_HAL/AP_HAL.h> that are unused, so that is nice.
Probably more improvements can be made, but this is good enought as it. 
Let's merge it before it rots ... 

As it is just include and safe one's, it should be compile time verified, if any error appears after this , then they are big errors that need to be addressed and not with some includes.

Any tools used for this ? 
iwyu report some other improvements, so I doubt it was the one used there

**Comment by peterbarker** [comment]
> Nice one. Removed a lot of git clone #include <AP_HAL/AP_HAL.h> that are unused, so that is nice. Probably more improvements can be made, but this is good enought as it. Let's merge it before it rots ...

Thanks :-)

> As it is just include and safe one's, it should be compile time verified, if any error appears after this , then they are big errors that need to be addressed and not with some includes.

Sadly, this isn't the case because of our use of `#infdef`.  If you remove a header making a define you can cause a compilation change and not even realise you've done.  Pretty sure we've committed to stop using them (except for defaulting) where we can.

> Any tools used for this ? iwyu report some other improvements, so I doubt it was the one used there

No, this was just inspection.

**Review by tridge — APPROVED** [review]

**Pull request merged**
