### PR TITLE
Dither heater pin to reduce impact on internal compasses

### PR DESCRIPTION
**Pull request by tridge**
This prevents a 1Hz change in magnetic field on the internal compasses:
image
Thanks to @WickedShell for noticing this

### CODE REVIEW

**Comment by rmackay9** [comment]
Very nice.. who could have even imagined this was happening?  I guess MichaelDB..

**Comment by jschall** [comment]
I don't think this is the right approach. It will still reduce heading accuracy as there will still be a bias proportional to the duty cycle. This just hides the symptom (visible square wave) and doesn't actually solve any issues caused by the effect.

Possible actions:
(1) Just ignore it. "Fixing" the visible square wave is likely pretty pointless.
(2) Add parameters COMPASS_HTR_(X|Y|Z) and subtract them when the heater is on.
(3) Same as (2) but set the PWM frequency high enough that it is well outside the bandwidth of the sensor, test that this doesn't cause significant aliasing products to appear, and always apply the correction, proportional to the duty cycle.

**Comment by tridge** [comment]
the EKF can learn a slowly changing offset in flight, which is what we get if we dither. It can't learn these 1Hz pulses, so it will add mag noise.
if you want to add compensation for the change we'd still want the dithering as timing between the heater pin change and the compass read is hard to control across the iomcu interface (especially as the compass has an internal accumulation buffer). Much easier to add a compensation proportional to the average than try to get that timing right.
If you want to add compensation in, then if we could show the effect is the same on all boards of the same type we could do it with defines in the hwdef.dat that target specific compasses for that board instead of exposing 9 more parameters

**Comment by jschall** [comment]
Why not just increase the frequency as in suggestion (3) and verify that it doesn't introduce aliasing effects? What's the point of the randomization?

**Comment by jschall** [comment]
The EKF would effectively interpret the square wave as a slowly changing bias anyway as its amplitude is small enough relative to the observation noise that it won't cause the magnetometer measurements to be rejected.

**Comment by tridge** [comment]
@jschall if you want to dive into this more and implement and test a different solution then please do so. Meanwhile I'll apply this, as I've tested it and at the very least it removes an annoying oscillation in logs that leaves users wondering what is going on. That is why this was noticed

**Pull request merged**
