### PR TITLE
modules: restore COLCON_IGNORE

### PR DESCRIPTION
**Pull request by srmainwaring**
Accidentally removed in 82adf42bd6

### CODE REVIEW

**Review by Ryanf55 — APPROVED** [review]

**Review by peterbarker — CHANGES_REQUESTED** [review]
This commit is not in the tools directory.

I guess we can't do anything about it, but having a named `COLCON_IGNORE` just sitting around in our directories like this is kind of garbage - a dotfile would have been far preferable.  Imagine what our tree would look like if all of our tools controlled their behaviour with such files?!

**Comment by Ryanf55** [comment]
> This commit is not in the tools directory.
> 
> I guess we can't do anything about it, but having a named `COLCON_IGNORE` just sitting around in our directories like this is kind of garbage - a dotfile would have been far preferable. Imagine what our tree would look like if all of our tools controlled their behaviour with such files?!

If only it was that easy. We need to fix all the dependent package issues. Otherwise, if you try building from top level, there's problems. 
```
ryan@ryan-B650:~/Development/ardu_ws/src/ardupilot$ colcon build
Starting >>> microcdr
Starting >>> Canard
Starting >>> ardupilot
Starting >>> benchmark
Starting >>> dronecan
Starting >>> googletest-distribution
Starting >>> mavlink
Starting >>> minimal
--- stderr: Canard                                                                                                                                                                                                    
python3: can't open file '/home/ryan/Development/ardu_ws/src/ardupilot/build/Canard/dronecan_dsdlc/dronecan_dsdlc.py': [Errno 2] No such file or directory
CMake Error at CMakeLists.txt:38 (add_subdirectory):
  add_subdirectory given source "googletest" which is not an existing
  directory.


---
Failed   <<< Canard [0.13s, exited with code 1]
--- stderr: benchmark
CMake Error at CMakeLists.txt:34 (message):
  Did not find Google Test sources! Either pass correct path in
  GOOGLETEST_PATH, or enable BENCHMARK_DOWNLOAD_DEPENDENCIES, or disable
  BENCHMARK_USE_BUNDLED_GTEST, or disable BENCHMARK_ENABLE_GTEST_TESTS /
  BENCHMARK_ENABLE_TESTING.


CMake Error at cmake/GoogleTest.cmake:13 (message):
  CMake step for googletest failed: 1
Call Stack (most recent call first):
  CMakeLists.txt:340 (include)


---
Failed   <<< benchmark [0.13s, exited with code 1]
--- stderr: ardupilot
CMake Error at /usr/share/cmake-3.22/Modules/CMakeDetermineSystem.cmake:130 (message):
  Could not find toolchain file: /tools/cmake/toolchain-esp32.cmake
Call Stack (most recent call first):
  CMakeLists.txt:5 (project)


CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
---
Failed   <<< ardupilot [0.13s, exited with code 1]
Aborted  <<< dronecan [0.36s]                                                                                                                                                               
Aborted  <<< minimal [0.38s]
Aborted  <<< mavlink [0.46s]                                                                                                                    
Aborted  <<< microcdr [0.48s]
Aborted  <<< googletest-distribution [2.61s]                                

Summary: 0 packages finished [3.45s]
  3 packages failed: Canard ardupilot benchmark
  5 packages aborted: dronecan googletest-distribution mavlink microcdr minimal
  3 packages had stderr output: Canard ardupilot benchmark
  1 package not processed
ryan@ryan-B650:~/Development/ardu_ws/src/ardupilo
```

This is a temporary fix until we can get around to doing so.

**Comment by srmainwaring** [comment]
@peterbarker, @Ryanf55 - I've looked through the `colcon` documentation to see if there another mechanism to configure the tool's search path. There isn't, and from discussions I've read on ROS answers by the devs there does not appear to be much interest in changing that behaviour.

The alternative to using `COLCON_IGNORE` is to have the ardupilot repo provide a single ROS 2 package. This requires a `CMakeLists.txt` and `package.xml` be present at the top level. The remainder of the ROS 2 specific files can be located in `./Tools/ros2/ardupilot` as before. As only a single package is now possible, the test code that was previously in a separate package must been moved.

I have made these changes in https://github.com/srmainwaring/ardupilot/tree/wips/wip-consolidate-ros2-pkgs. 
I have named the single project `ardupilot` as it will eventually contain launch files for real vehicles as well as simulated ones.

Please take a look. If you are happy with the structure I'll submit a PR and cancel this.

**Comment by Ryanf55** [comment]
After some updates, the next blocker for COLCON_IGNORE is this error:
```
ryan@ryan-sp3:~/Development/ardu_ws/src/ardupilot$ colcon build
[1.255s] ERROR:colcon:colcon build: Duplicate package names not supported:
- ardupilot:
  - libraries/AP_HAL_ESP32/targets/esp32/esp-idf
  - libraries/AP_HAL_ESP32/targets/esp32s3/esp-idf
```

**Pull request merged**
