### PR TITLE
Allow individual rangefinder backends to be compiled in/out

### PR DESCRIPTION
**Pull request by peterbarker**
Flew this on a SkyViper without issue.

### CODE REVIEW

**Comment by tridge** [comment]
looks good, just needs to be tested on at least one CAN and one serial rangefinder
probably analog too

**Comment by timtuxworth** [comment]
How do I use this? I'd love to build my own FW for my PixHawk 1-1M with only the equipment I'm using, is there a wiki page that explains how I would do that?

**Comment by rmackay9** [comment]
@timtuxworth

Here's a [link to the custom build server](https://custom.ardupilot.org/).  It's still a bit new but feel free to give it a try and report back..

**Comment by timtuxworth** [comment]
> @timtuxworth
> 
> Here's a [link to the custom build server](https://custom.ardupilot.org/). It's still a bit new but feel free to give it a try and report back..

Thanks @rmackay9 I know about that, but I'm more interested in how I do this when I'm doing my own builds.

**Comment by peterbarker** [comment]
I've tested this on a Benewake TFMiniPlus without issues.  So serial is done.

**Comment by peterbarker** [comment]
> > @timtuxworth
> > Here's a [link to the custom build server](https://custom.ardupilot.org/). It's still a bit new but feel free to give it a try and report back..
> 
> Thanks @rmackay9 I know about that, but I'm more interested in how I do this when I'm doing my own builds.

Create an extra.hwdef and pass it to the configure command-line:

```
pbarker@fx:~/rc/ardupilot(pr/skyviper-thinning)$ cat exta.hwdef
define AP_RANGEFINDER_BACKEND_DEFAULT_ENABLED 0
define AP_RANGEFINDER_BENEWAKE_TFMINI_ENABLED 1

pbarker@fx:~/rc/ardupilot(pr/skyviper-thinning)$ ./waf configure --board=PixRacer --extra-hwdef=exta.hwdef
```

For longer-term projects you can create a subdirectory in `libraries/AP_HAL_ChibiOS/hwdef` which includes the board you're using but also includes other bits-and-pieces to customise your build.

**Comment by peterbarker** [comment]
I've now tested this on a HereFlow can-attached rangefinder without issue.  So CAN is done

**Comment by peterbarker** [comment]
... and I've not tested analog.  Well, watched random numbers pop up due to a floating pin, anyway....

**Comment by timtuxworth** [comment]
> > > @timtuxworth
> > > Here's a [link to the custom build server](https://custom.ardupilot.org/). It's still a bit new but feel free to give it a try and report back..
> > 
> > 
> > Thanks @rmackay9 I know about that, but I'm more interested in how I do this when I'm doing my own builds.
> 
> Create an extra.hwdef and pass it to the configure command-line:
> 
> ```
> pbarker@fx:~/rc/ardupilot(pr/skyviper-thinning)$ cat exta.hwdef
> define AP_RANGEFINDER_BACKEND_DEFAULT_ENABLED 0
> define AP_RANGEFINDER_BENEWAKE_TFMINI_ENABLED 1
> 
> pbarker@fx:~/rc/ardupilot(pr/skyviper-thinning)$ ./waf configure --board=PixRacer --extra-hwdef=exta.hwdef
> ```
> 
> For longer-term projects you can create a subdirectory in `libraries/AP_HAL_ChibiOS/hwdef` which includes the board you're using but also includes other bits-and-pieces to customise your build.

Thanks mate, that's what I was looking for.

**Review by tridge — APPROVED** [review]

**Pull request merged**
