### PR TITLE
Plane: obey Q_RTL_ALT when in POS1 and POS2 states

### PR DESCRIPTION
**Pull request by tridge**
this fixes the alt target for when user has disabled the quadplane
approach code

### CODE REVIEW

**Comment by Hwurzburg** [comment]
tested in SITL for Convergence in all the cases I could think of...works great....
fails in all QRTL phases for tailsitter, target alt is 0 and flies into ground in all cases on returns....

**Comment by tridge** [comment]
>  fails in all QRTL phases for tailsitter, target alt is 0 and flies into ground in all cases on returns....

thanks! fixed, can you re-test?

**Comment by Hwurzburg** [comment]
unfotunately, the change you made to mode_qrtl.cpp breaks it again..first test flight with convergence fails if switching to QRTL at some distance....heads to Q_RTL_ALT okay, but when close, descends to ground well before home...no GSC postiton change notice..reverting to only the change in quadplane that I suggested still works though....did not test further
descent

**Comment by Hwurzburg** [comment]
Duh, first one ran out of battery! forgot that long VTOLs will drain the battery in the sim.....will resume testing....

btw, suggest changing to this in quadplane.cpp:
void QuadPlane::poscontrol_init_approach(void)
{
const float dist = plane.current_loc.get_distance(plane.next_WP_loc);
    if ((options & OPTION_DISABLE_APPROACH) != 0) {
        // go straight to QPOS_POSITION1
        poscontrol.set_state(QPOS_POSITION1);
        gcs().send_text(MAV_SEVERITY_INFO,"VTOL Position1 d=%.1f", dist);
    } else if (poscontrol.get_state() != QPOS_APPROACH) {
        gcs().send_text(MAV_SEVERITY_INFO,"VTOL approach d=%.1f", dist);
        poscontrol.set_state(QPOS_APPROACH);
        poscontrol.thrust_loss_start_ms = 0;
    }
}

**Comment by tridge** [comment]
> Duh, first one ran out of battery! forgot that long VTOLs will drain the battery in the sim.....will resume testing....

ahh! I normally set infinite battery in RealFlight to avoid this unless I'm specifically testing for endurance. Thanks for following up on this.

**Comment by tridge** [comment]
> btw, suggest changing to this in quadplane.cpp:

ok, just adding the message? Sounds good. Do you want to do the PR?

**Comment by Hwurzburg** [comment]
yep..will do..should be finished testing tomorrow, but dont expect any issues on TVBS..

**Pull request merged**
