### PR TITLE
Pkill shellout

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by OXINARF** [comment]
LGTM

**Comment by peterbarker** [comment]
@OXINARF Thanks!  This has been pushed in to master

**Comment by WickedShell** [comment]
Was this intended to fix the windows cygwin issues? (If so it has not resolved it).

**Comment by peterbarker** [comment]
@WickedShell I'm just installing Windows here to work through these issues.  I don't think pkill will do any better than the existing "ps -ea" stuff (which is why I didn't change the existing cygwin behaviour, and that behaviour has worked for some users) - but I'm going to test things here.

**Comment by lucasdemarchi** [comment]
I don't see this applied to master, reopening

**Comment by lucasdemarchi** [comment]
Ok... applying this myself.

**Pull request closed without merging**
