### PR TITLE
Remove POSITION_TARGET_TYPEMASK_FORCE_SET from messages

### PR DESCRIPTION
**Pull request by hendjoshsr71**
We shouldn't be setting `POSITION_TARGET_TYPEMASK_FORCE_SET` when sending accelerations as they are in m/s^2 not N. 

Found while adding in non static type masks for all relevant modes & vehicles into position_target_global_int for this https://github.com/ArduPilot/ardupilot/pull/17344.

Affects this PR that moves some of these functions up similar to the above PR: https://github.com/ArduPilot/ardupilot/pull/17963

### CODE REVIEW

**Review by peterbarker — APPROVED** [review]
Great!

I noticed this the other day when reviewing some of Leonard's work but was too lazy to chase it down.

**Comment by hendjoshsr71** [comment]
Added updates to the autotests to no longer use FORCE_SET and compute the bit masks from the definitions in common.py

**Review by khancyr — APPROVED** [review]
LGTM,
I am pretty sure it was settled for convenience (to have one everywhere). But now, we have the mavlink enum so that is better.

**Comment by hendjoshsr71** [comment]
> LGTM,
> I am pretty sure it was settled for convenience (to have one everywhere). But now, we have the mavlink enum so that is better.

Yeah it only really needed to be removed for consistency sake for most of these.  (A little unfortunate it means that the 10th bit is always 0.)

I'm adding acceleration outputs to position_target_global so I hit this.

**Comment by rmackay9** [comment]
I'm happy with the Copter and Rover changes.  I'll leave @peterbarker to say he's happy with the autotest changes (they happened after he gave his approval).

**Pull request merged**
