### PR TITLE
libraries: AP_HAL_ESP32: README: Add info about ESPPORT

### PR DESCRIPTION
**Pull request by patrickelectric**

### CODE REVIEW

**Comment by tpwrules** [comment]
This is usually automatically determined but it's good to know it can be manually specified. Perhaps it should be a separate aside? I've also found that ESPBAUD is not necessary on ESP32-S3.

**Comment by patrickelectric** [comment]
> This is usually automatically determined but it's good to know it can be manually specified. Perhaps it should be a separate aside? I've also found that ESPBAUD is not necessary on ESP32-S3.

I got a weird problem on my setup where it was necessary to setup the board device. I can break in a different example.

**Review by davidbuzz — APPROVED** [review]

**Comment by tpwrules** [comment]
I changed the example because the given port won't work with ESP32S3 (it's usually `/dev/ttyACM0`).

**Comment by peterbarker** [comment]
Note that we wouldn't ordinarily include "libraries: " in the commit message here.

**Pull request merged**
