### PR TITLE
EKF3: Fix bug causing too frequent resets if bad IMU data detected

### PR DESCRIPTION
**Pull request by priseborough**
Resets due to to bad IMU data is not supposed to be repeated sooner than 1000 msec as set by BAD_IMU_DATA_TIMEOUT_MS. 

Replay of log https://cdn.discordapp.com/attachments/708104439231152191/888550156696449034/00000216.BIN was used to find and fix this defect. The reset flag bitmask for the original log without the change XKF4[0].TS  and the replayed log XKF4[100].TS with the change is shown below. The repeated reset every 100msec which caused rapid switching in the timeout status has been fixed.

Screen Shot 2021-09-19 at 1 20 38 pm

### CODE REVIEW

**Comment by peterbarker** [comment]
Re-ran the failing test here.  It is a vibration failsafe check, so is related.

**Review by tridge — APPROVED** [review]

**Comment by tridge** [comment]
@priseborough thanks Paul!

**Comment by peterbarker** [comment]
@rmackay9 your Vibration failsafe seems to be reliably failing on this bugfix-PR.

**Comment by tridge** [comment]
here is master (without this PR) doing that test:
http://uav.tridgell.net/tmp/vibe-failsafe-master.bin
its odd, a replay on this log does change PD, but not by much:
image
only a small change in solution status too:
image
yet the test reliably fails.
ahh, the difference is the vertical velocity, that totally changes:
image

**Comment by tridge** [comment]
VD is bad with both master and this PR, but to different extents
image

**Comment by priseborough** [comment]
The behaviour during the vibration failsafe autotest is improved. The EKF's internal vertical velocity state is now reset to the GPS velocity each time a GPS measurement is processed when the bad IMU data status is active. Note that this does not mean the output state XKF1.VD will follow the GPS due to the affected IMU data that is used to predict forward from the EKF's internal time horizon to current time. I will now look at what can be done within the output observer to reduce the effect of the accelerometer error when bad IMU data has been detected.

image

image

**Comment by priseborough** [comment]
The output observer has been modified with additoin of a vertical velocity error integral that reduces the steady state offset between the delayed EKF state  and current time output observer state when bad IMU data is detected. When the protection is active, the offset has now been reduced to a third of what it was before. No changes to the vertical controller should be required due to the way that this has been implemented which has little effect on the delay.

image

**Review by andyp1per — APPROVED** [review]

**Comment by tridge** [comment]
looks like this does track VD better than master:
image

**Review by tridge — APPROVED** [review]

**Pull request merged**
