### PR TITLE
AP_Airspeed: fixed handling of unhealthy airspeed

### PR DESCRIPTION
**Pull request by tridge**
this fixes a bug introduced in
https://github.com/ArduPilot/ardupilot/pull/22416 which results in using bad airspeed data on timeout. The prev_health variable is updated by the get_pressure call
This defeated the IIR bad data protections:
image

### CODE REVIEW

**Review by peterbarker — APPROVED** [review]

**Comment by magicrub** [comment]
CI failed 3 times so I restarted them. One could be legitimate

```>>>> FAILED STEP: test.CopterTests1e at Thu Aug 10 10:06:27 2023
Failure Summary:
  test.CopterTests1e:
    SurfaceTracking (Test Surface Tracking) (Did not get home and disarm) (see /tmp/buildlogs/ArduCopter-SurfaceTracking.txt)
    RangeFinderDrivers (Test rangefinder drivers) (Failed to attain Altitude want 4.0, reached 2.522) (see /tmp/buildlogs/ArduCopter-RangeFinderDrivers.txt)
    RangeFinderDriversMaxAlt (test max-height behaviour) (Did not get home and disarm) (see /tmp/buildlogs/ArduCopter-RangeFinderDriversMaxAlt.txt)```

**Comment by IamPete1** [comment]
Oops. We should remove this stray set of healthy too, seems like it won't do anything. 

https://github.com/ArduPilot/ardupilot/blob/8ff37bc79c1dced549fbc0464d98c5e5a70264e1/libraries/AP_Airspeed/AP_Airspeed_Health.cpp#L100

Would be nice to refactor into using the filter class at some point too.

**Review by IamPete1 — COMMENTED** [review]
Do we need to increase the DroneCAN temperature timeout too?

https://github.com/ArduPilot/ardupilot/blob/8ff37bc79c1dced549fbc0464d98c5e5a70264e1/libraries/AP_Airspeed/AP_Airspeed_DroneCAN.cpp#L167

**Comment by tridge** [comment]
> Do we need to increase the DroneCAN temperature timeout too?

we could, but it is not critical and leaving it at 100ms allows us to easily detect loss of packets in logs

**Pull request merged**
