### PR TITLE
Copter-GCS Notice for cancelled landing

### PR DESCRIPTION
**Pull request by lvale**
Adding a GCS Notice when landing cancelled by high throttle

### CODE REVIEW

**Comment by magicrub** [comment]
These code segments are very repetitive. May make sense to refactor.

**Comment by lvale** [comment]
LoL, Just added to @rmackay9 code :)

**Comment by magicrub** [comment]
Hi-5!

**Comment by magicrub** [comment]
this looks good to me but needs a rebase.

**Comment by OXINARF** [comment]
@lvale Why did you close? Do you just don't have time to do the rebase or do you think this isn't needed anymore?

**Comment by lvale** [comment]
I'll re-submit after rebase :)

**Comment by OXINARF** [comment]
Ok, good!

**Pull request closed without merging**
