### PR TITLE
SRV_Channel: Add function names for trad heli functions and tricopter

### PR DESCRIPTION
**Pull request by Hwurzburg**
I used CollectiveX as the second function instead of SwashX because they are used a pure collective servos on heli-quad....and even though they are swash servos, they are also collective servos....

### CODE REVIEW

**Comment by bnsgeyer** [comment]
@Hwurzburg  I don't agree with this change.  In some cases a motor could have three different heli functions.  For example, Motor 4 could be tail rotor for a single heli, swash 1 for a dual heli, and collective 4 for a heli quad.  I don't believe this is the right way to go about this.  I think this should be left as is until it is done properly.  I think the proper way is to define all of the heli specific functions and properly map them to each of the frames.  I could probably put in an issue that a newcomer could take on.  

Unless someone has a better idea, that I'm not aware of.  

Regards,
Bill

**Comment by Hwurzburg** [comment]
I forgot about the tail servos....

**Comment by bnsgeyer** [comment]
@Hwurzburg  Ok. I'm still not convinced that I want to do it this way.   I will say that I am NOT onboard with using collective for labeling instead of swash when 99% of my users are single/dual heli users.   That is very confusing.  They are swashplate servos not collective servos.  Collective is just one movement of the swashplate.  Tailrotors and heliquads have swashplates but they only provide one movement and thus only require one servo.

**Comment by Hwurzburg** [comment]
SwashX instead of CollectiveX ?

**Comment by bnsgeyer** [comment]
@Hwurzburg What in this PR is tricopter specific? I will look at this and get you the changes tonight.

**Comment by Hwurzburg** [comment]
> @Hwurzburg What in this PR is tricopter specific? I will look at this and get you the changes tonight.

Motor7 is tail tilt servo in Tricopter quad plane and multicopters

**Comment by bnsgeyer** [comment]
@Hwurzburg  So is your intention to add that to the functions for Motor 7.

This gets very complicated.  So ideally this is what they should be

Function #     Single heli                dual heli                  heliquad
33                  Swash1_servo1     Swash1_servo1          Swash1_servo
34                  Swash1_servo2     Swash1_servo2          Swash2_servo
35                  Swash1_servo3     Swash1_servo3          Swash3_servo
36                  Tail_servo/motor  Swash2_servo1          Swash4_servo
37                  Swash1_servo4     Swash2_servo2   
38                                               Swash2_servo3   
39                                               Swash1_servo4   
40                                               Swash2_servo4   

The reason for 36 being tail_servo/motor is that with Direct Drive Fixed Pitch tail rotors, the motor for the tail rotor is directly connected to function number 36.  So that adds a bit more complexity.  

I suppose we could keep the naming as SwashX where X is 1 to 8 but I'm not sure that is any different from calling them motor 1 to 8.  

I'll be interested in your thoughts on this.

**Comment by bnsgeyer** [comment]
@Hwurzburg I think for motor4 instead of tailservoA it should read tailrotor. And for motor7 instead of tailservoB it should read tailtilt. I think that would be pretty clear between the two configurations they serve.

**Comment by Hwurzburg** [comment]
that would work....just so that they are different....will change...

**Comment by bnsgeyer** [comment]
Merged!  Thanks!

**Pull request merged**
