### PR TITLE
AP_Logger: constraints time spend in header writing

### LINKED ISSUE #11304: EKF Vertical Position and Velocity Errors on Arming Events
### Bug report

**Issue details**

On first arming event after pixhawk reboot, there is a relatively large error in EKF vertical position and velocity estimates. I have found the issue in the Copter-3.6 branch but not in the Copter-3.5 branch. This issue has been discussed pretty extensively on the forum over the past few days and more than 1 person has verified this issue. See forum post here:
https://discuss.ardupilot.org/t/copter-ekf-altitude-estimation-error-due-to-heavy-uart-communication-load/41625

This issue cannot be replicated in sitl, so the prevailing theory is that it has something to do with datalogging and uart load. This issue is independent of RTOS version (present in both chibios and nuttx).

I have a theory that this is somehow related to a delay just after resetting the ekf reference height (most likely due to log file creation or the start of a log). If I add an additional delay in the Copter::init_motors_arm() function, just before the function returns, the errors become significantly larger. 

Also if I enable log while disarmed, the errors are smaller. So the magnitude of this error seems to be related to log creation. 

Below is a typical signature of what happens on arming. This image comes from a log where I just armed the vehicle on the ground but did not fly. Additional log images can be seen on the forum post as well as a log file.
ekf_errors

These ekf errors show up in fused altitude and climb rate while armed and sitting on the ground. This issue is independent of EKF type, since I have been able to replicate this on every arming using both EKF2 and EKF3.

It is also worth noting that all successive arming events, after the first, will exhibit smaller ekf errors in vertical position and velocity. These errors seem to increase in magnitude based on uart load. If UART load is minimal, these errors are very small or nonexistent.

And finally I have found that when retrieving logs, the EKF seems to go into an unrecoverable state when using EKF3. You see vertical pos variance errors and compass variance errors that are not resolved until the pixhawk is rebooted. I never noticed this issue when running Copter 3.5. The ekf seemed to be unaffected by log downloads on older versions.

More details can be found in the forum posts, and this may be just one symptom of a larger issue since the user that created the post experienced a different but seemingly related issue with the EKF's vertical estimates.

**Version**
Copter-3.6

**Platform**
[  ] All
[  ] AntennaTracker
[ x ] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
Hexacopter, Octacopter, and should affect other frame types as well

**Hardware type**
Pixhawk 2.1

**Logs**
_Please provide a link to any relevant logs that show the issue_

### LINKED ISSUE #13882: EKF2: altitude climbing in first arm without takeoff
## Bug report

**Issue details**
PosHold mode, tested indoor using att_pos_mocap
use RC to arm and then disarm (copter did not take off)
Log Browser - 23 2020-3-25 上午 11-34-56 bin 2020_3_25 下午 01_47_00
[log_disarm0.zip](https://github.com/ArduPilot/ardupilot/files/4379249/log_disarm0.zip)
ctun.alt climbing after first armed (throttle min). If you take copter off at this moment, it will rocketing into sky. But this behavior did not happen in following arm

It is strange that it is not happened if log_disarm = 1
[log_disarm1.zip](https://github.com/ArduPilot/ardupilot/files/4379251/log_disarm1.zip)

**Version**
4.0.4-dev

**Platform**
[  ] All
[  ] AntennaTracker
[X] Copter
[  ] Plane
[  ] Rover
[  ] Submarine

**Airframe type**
quadcopter

**Hardware type**
kakute f7

### PR DESCRIPTION
**Pull request by chobitsfan**
fix #11304 and #13882

Start logging in first arm (log_disarm=0) seems make EKF altitude incorrectly climbing for a few seconds while copter still on the ground. It is not happened if you disarm and then arm again. 
[ekf_alt_climbing_high_1st_arm.zip](https://github.com/ArduPilot/ardupilot/files/4453727/ekf_alt_climbing_high_1st_arm.zip)

@JamesMegariotis also report 

> Seems to definitely be related to dataflash logging since arming using log while disarmed feature leads to much smaller errors

related [discussion](https://discuss.ardupilot.org/t/copter-ekf-altitude-estimation-error-due-to-heavy-uart-communication-load/41625)

Thanks @peterbarker very much for very useful [suggestions](https://discuss.ardupilot.org/t/copter-ekf-altitude-estimation-error-due-to-heavy-uart-communication-load/41625/41?u=chobitsfan)

flight tests log
[sd_log_fix.zip](https://github.com/ArduPilot/ardupilot/files/4453757/sd_log_fix.zip)

### CODE REVIEW

**Comment by peterbarker** [comment]
Wow.  That's pretty straight-forward :-)

AFAICS, this will only ever stop a really bad loop from getting worse.

If we take more than 200us to do the rest of "process()" then we'll still cause an overrun.  200us is not a lot of time :-)

If this does solve the problem you were seeing - and esp. if @JamesMegariotis can confirm it fixes the problems he's seen - then we should merge it.

But a more complete fix would have us check after writing each message to the log - so:
```
            if (!_logger_backend->Write_Format(_logger_backend->structure(next_format_to_send))) {
                return; // call me again!
            }
```

becomes
```
            if (AP::scheduler().time_available_usec() < MIN_LOOP_TIME_REMAINING_FOR_MESSAGE_WRITE_US) {
               return; // call me again!
            }
            if (!_logger_backend->Write_Format(_logger_backend->structure(next_format_to_send))) {
                return; // call me again!
            }
```

... and many other places too.

As I said, 'though - if this solves the problem I'd merge it.

**Comment by chobitsfan** [comment]
Thank you very much @peterbarker 

> a more complete fix would have us check after writing each message to the log 

I have updated the code. 
Test result, arm and disarm twice, copter do not take-off
[pr2_arm_disarm.zip](https://github.com/ArduPilot/ardupilot/files/4454790/pr2_arm_disarm.zip)
Compare to current master
[cur_arm_disarm.zip](https://github.com/ArduPilot/ardupilot/files/4454793/cur_arm_disarm.zip)
EKF vertical position and velocity errors still exists and significantly reduced.

test flight log
[pr2_flight.zip](https://github.com/ArduPilot/ardupilot/files/4454800/pr2_flight.zip)

**Comment by guglie** [comment]
Thanks, very useful! I'll test it as soon as possible

**Comment by chobitsfan** [comment]
Hi @peterbarker 

My colleague purposes another approach:
1. When log_disarm=0, open the log file in temp/ and write headers after boot
2. When vehicle armed, move the log file to normal location (move file only involve directory change, its cost should be very small)

Would you be able to leave some comments? Thank you very much

**Pull request merged**
