### PR TITLE
AP_InertialSensor: Change board type judgment to switch statement.

### PR DESCRIPTION
**Pull request by muramura**
Board type judgment is done by if statement.
This determination method takes time.
Therefore,
Change to switch statement.

### CODE REVIEW

**Comment by OXINARF** [comment]
@tridge I've assigned this to you since it conflicts with your PR #5379.

**Comment by OXINARF** [comment]
@muramura Can you fix the conflicts?

**Comment by muramura** [comment]
@OXINARF san. Comment thank you.
i  will  merge.

**Comment by muramura** [comment]
Multiple merging failures will fail.
Therefore,
Another PR was uploaded.

**Pull request closed without merging**
