### PR TITLE
Tools: Reserve board IDs for Sierra

### PR DESCRIPTION
**Pull request by MallikarjunSE**
Reserve range of Board IDs for Sierra.

### CODE REVIEW

**Review by magicrub — APPROVED** [review]

**Comment by magicrub** [comment]
@andyp1per why the devcall tag?

**Comment by andyp1per** [comment]
@magicrub I wasn't sure we had had the discussion about allocating that range

**Comment by andyp1per** [comment]
@magicrub also I don't have merge access, so its all I can do!

**Comment by magicrub** [comment]
They got here first, they win! :) Merged.

**Pull request merged**
