### PR TITLE
Tools: autotest: Web: Tools: Add WIP javascript magfit

### PR DESCRIPTION
**Pull request by IamPete1**
This is a very WIP (it doesn't work yet) online MAGFit tool using javascript, same idea as filter tool. So far it can import log data and calculate the expected earth field. 

image

Plot the error along with interference sources, I still need to add battery. 

image

Grab and show compass configuration.

image

It still needs to:

- Remove calibration from logged values to get back to raw.
- Actually do a MAGFit. I intend to just fit all compass for all sources of interference then we pick the one with the lowest error. Probably some sort of bar graph to compare and buttons to cycle through the different fits on the main graphs. 
- Have a option to save a param file

Many thanks to @Williangalvani who's data-flash log parser this uses. https://github.com/Williangalvani/JsDataflashParser

### CODE REVIEW

**Comment by IamPete1** [comment]
Added displaying of battery current to the interference graph and option to show raw or calibrated values. 

image

**Comment by rbeall** [comment]
This is Fire!

**Comment by Williangalvani** [comment]
NICE!

what was preventing me from working on it was finding a good js alternative for an optmizer

**Comment by IamPete1** [comment]
I have not got as far as the optimizer yet.... the filter tool uses some stuff from this library, https://github.com/mljs/ml they might have something we could use (although not at first glance).

**Comment by IamPete1** [comment]
Moved to https://github.com/ArduPilot/WebTools/pull/61

**Pull request closed without merging**
