### PR TITLE
DataFlash: log parameter changes while disarmed even if MASK_LOG_WHEN…

### LINKED ISSUE #3778: Param changes not logged when vehicle is disarmed
Currently, parameter changes on the disarmed vehicle are only logged if MASK_LOG_WHEN_DISARMED is set, otherwise they are suppressed. I think the intention of the MASK_LOG_WHEN_DISARMED flag is to suppress useless data streaming in from sensors and flight control, while the vehicle is sitting on the ground and waiting for action. However, the current implementation also suppresses logging of param changes that happen while the vehicle is landed (disarmed). 

This behavior is very nasty when tuning a vehicle and doing multiple flights battery, as parameter changes are impossible to trace after the flight.

### PR DESCRIPTION
**Pull request by hsteinhaus**
…_DISARMED is not set

Fixes #3778

### CODE REVIEW

**Comment by WickedShell** [comment]
I'm of mixed opinions on this, as I can see the point, however it is at odds of what people want out of disabling log when disarmed. The expectation is that if they never arm they won't have created any log files, which is a reasonable expectation, however this would be opposed to that behavior.

It's also at odds with #3067 as it's not clear which file you would save the parameters to.

**Comment by peterbarker** [comment]
On Tue, 22 Mar 2016, WickedShell wrote:

> I'm of mixed opinions on this, as I can see the point, however it is at odds
> of what people want out of disabling log when disarmed. The expectation is
> that if they never arm they won't have created any log files, which is a
> reasonable expectation, however this would be opposed to that behavior.

I like the intent of the patch.

> It's also at odds with #3067 as it's not clear which file you would save the
> parameters to.

With my suggestion of, "rotate to new file on disarm", this becomes clear 
:-)

Additionally, I have a tree around which has a LOG_RATE_ARMED / 
LOG_RATE_DISARMED in place of LOG_BITMASK.  This would also solve this 
problem, but I've received negative feedback on a simplistic log-rate 
system.

**Comment by hsteinhaus** [comment]
The rotation on disarm sounds very promising. It has the additional advantage of being able to log ERRs and EVs one day (with MASK_LOG_WHEN_DISARMED off).

**Comment by amilcarlucas** [comment]
Hasn't this functionality been added in a recent commit

**Comment by peterbarker** [comment]
On Mon, 13 Nov 2017, Amilcar Lucas wrote:

> Hasn't this functionality been added in a recent commit

On master, and Plane 3.8, yes!

Well spotte.d

**Comment by OXINARF** [comment]
@peterbarker So we can close this, right?

**Comment by peterbarker** [comment]
@OXINARF Yes, closed.

**Pull request closed without merging**
