### PR TITLE
travis: add python-numpy to install

### PR DESCRIPTION
**Pull request by khancyr**

### CODE REVIEW

**Comment by OXINARF** [comment]
@khancyr I guess you created two PRs because you used the edit button in GitHub? For the future, please don't create branches in this repo, make them in your fork and then do a PR.

**Comment by khancyr** [comment]
@OXINARF ... I am really sorry, I didn't see that ... it used to create a branch on my fork... surely because tridge add me ...

**Comment by OXINARF** [comment]
@khancyr Yeah, I guessed that was it. No problem, it has happened before :+1:

**Comment by khancyr** [comment]
close in favor of https://github.com/ArduPilot/ardupilot/pull/4979

**Pull request closed without merging**
