### PR TITLE
Convert drivers to use I2CDevice interface V2

### PR DESCRIPTION
**Pull request by lgywata**
Changes from v1:

- Split commits
- Improve commit messages
- Refactor a few methods

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
@lgywata please rebase and resubmit to fix CI. But I'm not sure it will be sufficient, in which case the build failure must be fixed.

**Comment by lgywata** [comment]
@lucasdemarchi travis failed due to sparse-endian header. As we talked in person, it seems that it shouldn't be a problem. Please, advise.

**Comment by lucasdemarchi** [comment]
@lgywata humn... I guess for now you can just ifdef out the part of the code to build only on linux

**Comment by OXINARF** [comment]
@lucasdemarchi Or add `HAVE_BYTESWAP_H=0` to PX4 builds.

**Comment by lucasdemarchi** [comment]
I thought so, but it is not that simple. We currently depend on it to implement the swap functions. While coming home I thought on a better alternative which would be doing a simple implementation of the byte swap functions. I'll do it later today or tomorrow

**Comment by OXINARF** [comment]
@lucasdemarchi Since it was already removed from QURT I though it wasn't needed on systems without that header. If you have a solution that's great.

**Comment by lucasdemarchi** [comment]
See #4465

**Pull request closed without merging**
