### PR TITLE
Copter: add change altitude with MP in loiter mode

### PR DESCRIPTION
**Pull request by ejngnng**
This feature for Copter, can change altitude in loiter mode using Mission Planner -> Actions -> Change Alt
Copter must in loiter mode.
Mission Planner 1.3.74

### CODE REVIEW

**Comment by rmackay9** [comment]
Thanks for this but I'm really not sure that we want mixed controls like this.  Loiter is meant to be a pilot controlled flight mode.  If the user wants to vehicle to climb higher then they could use Guided mode.

My concern if just what do we do when the pilot and GCS commands are not compatible... and the extra complexity.

**Comment by ejngnng** [comment]
@rmackay9  thanks for your reply.  if in the condition, Copter with a power tether system,  copter need to hover  stable,  maybe the telemetry link and radio link are wired connection,  only telemetry link is wired connection most of time, RC maybe   for emergency condition, in other words for backup.  some times we need to control copter to a  precise altitude using GCS, some times we need to control copter using RC.  I'm not sure if loiter mode is best for copter with power tether, but this mode do good.

**Comment by EosBandi** [comment]
@ejngnng  Guided mode is the way to go with tether. If you have to use RC link, either the pilot must switch to Loiter, or you can write a script which switch to Loiter if needed (based on tether status or pilot input).

**Comment by rmackay9** [comment]
Thanks again for this.  It's an interesting feature but after a discussion with @lthall we've found a few problems:

1. both the target altitude and the pilot's input are sent into the position controller.  This means that there will essentially be a fight between the two.  There's no way for the pilot to stop the attempted climb to the higher altitude.  It would be a good idea (and probably relatively simple) to disable the climb to the higher alt if the pilot inputs a significant negative climb rate.
2. as mentioned above it adds complexity to an already complex flight mode and at this point we don't want to mix pilot controlled and autonomous control.

So I'm going to close this PR but again, it's interesting and generally well done.

**Comment by ejngnng** [comment]
@rmackay9 yes I also found the problem.  The pilot can not control th copter untill finished the GCS change alt command， and to fix this problem, I think monitor the RC channel, when pilot need to change the mode or attidude, just reset the change alt flag and set the GCS target altitude to current altitude.  add I agree with you, this mixed control is complexity, maybe we need a new flight mode for tethered drones. just like ZigZag mode for crop spraying. : )

**Comment by ejngnng** [comment]
@EosBandi Thank you. As you said, Guide mode is the way,  I have a try with Guided mode before this PR.  I think Guided mode is not flexible for RC, and a script or pilot move the switch can work, but I think it is better to use one flight mode for tethered drones, it can reduce learning or using costs for normal users or people even without any flight experience. Maybe we need a new flight mode called _Tethere Mode_ for tethered drones.  : )

**Pull request closed without merging**
