### PR TITLE
Disalllow param bitmask and values at same time

### PR DESCRIPTION
**Pull request by peterbarker**
We do seem to be losing a bit of information by doing this.

I suggested on the DevCall that `@Values` should be considered "presets" by the GCSs when `@Bitmask` is present - so `@Bitmask` dictates the interface (checkboxes), but a drop-down box might be present to magically set bits in those boxes according to some useful rule.  The GNSS options suitable for Japan shows where that might be useful IMO.

### CODE REVIEW

**Comment by Hwurzburg** [comment]
I suggest any important information be moved to the Description...eg
in Heli_options change to:
// @Description: Bitmask of heli options.  Bit 0 changes how the pitch, roll, and yaw axis integrator term is managed for low speed and takeoff/landing. Setting this bit uses a leaky integrator for ground speeds less than 5 m/s and won't let the steady state integrator build above ILMI. The integrator is allowed to build to the ILMI value when it is landed.  This should be used for firmware versions prior to 4.1. Clearing this bit in 4.1 and later versions uses a different integrator management scheme bases integrator limiting on takeoff and landing.  Whenever the aircraft is landed the integrator is set to zero.  When the aicraft is airborne, the integrator is only limited by IMAX. 

and for the GNSS params add "51:GPS+IMES+QZSS+SBAS (for Japan Only)" at the end of each description

**Review by Hwurzburg — CHANGES_REQUESTED** [review]
approved with the move of info into descriptions

**Comment by WickedShell** [comment]
I'm incredibly in favor of this. A GCS already has to make this decision, and personally I've been of the opinion in my GCS that the bitmask offers the most value to the user so if that's present in the documentation that's the only thing I show.

I don't think moving things into the descriptions is a good idea though. It makes the description's a lot wordier and more confusing. The descriptions should be describing what an individual bit means, not offering random pairings.

**Comment by rmackay9** [comment]
As discussed on the dev call I have no objection to removing the values in cases where we have bitmasks..

**Review by tridge — APPROVED** [review]

**Pull request merged**
