### PR TITLE
ChibiOS: fixed some F4 clock varients and support no crystal

### PR DESCRIPTION
**Pull request by tridge**
This fixes some errors in F4 builds that were using the wrong sysclock. It also ensures that all MCU files have an EXPECTED_CLOCK, and allows for F4 builds without a crystal (for prototyping or very small boards)
This also removes the need for the PLL overrides in various boards

### CODE REVIEW

**Comment by MallikarjunSE** [comment]
Hey @tridge 
Is it fine if I remove this custom clock tree now?
https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_HAL_ChibiOS/hwdef/Sierra-F405/hwdef.dat#L123
It was not building without this on my F405 nodes. 
Thanks!

**Comment by tridge** [comment]
> Is it fine if I remove this custom clock tree now?

yes, I've added removal of all those custom clock trees to this PR
please test!

**Comment by MallikarjunSE** [comment]
> > Is it fine if I remove this custom clock tree now?
> 
> yes, I've added removal of all those custom clock trees to this PR please test!

Thanks! Will try this PR.

**Comment by MallikarjunSE** [comment]
> > Is it fine if I remove this custom clock tree now?
> 
> yes, I've added removal of all those custom clock trees to this PR please test!

Hey @tridge 
Working without any issues! 
Thank you!

**Comment by bugobliterator** [comment]
@tridge also need to update the STM32Cube files.

**Comment by tridge** [comment]
> @tridge also need to update the STM32Cube files.

done

**Review by bugobliterator — APPROVED** [review]

**Pull request merged**
