### PR TITLE
Using SI units: Change to using radians as angular units for copter control

### PR DESCRIPTION
**Pull request by bugobliterator**
This PR is first in series of unit conversion patches I'll be doing. The focus of this PR is to convert all of the control related code to use radians. Be aware that libraries touched in this patch is as follows:
- ArduCopter: this is the primary focus of this patch and tries to convert as much of the code to use radians as possible.
- libraries/AC_AttitudeControl: much of the code was already converted to use radians, but hasn't been percolated to other libraries and vehicles it touches.
- libraries/AC_WPNav: this library is now converted to mostly use radians, but changes made to parameter names still to be done, which could come in next cycle of patches.
- ArduPlane: this part of the patches are primarily quick fixes to have quadplane part of the code to receive data in previous form i.e. in centidegrees/degrees.

Side Notes:
- I propose that in the patches that happen in the future, devs must add the physical quantity's unit at the end of the parameter name especially if using non SI unit.
- if a function takes physical quantities as parameters or returns the function name should include the unit of zeroth order of that physical quantity(PQ) e.g. if a function returns angular acceleration and takes in angular velocity the function name should have _<unit of zeroeth order PQ i.e angle e.g. rad> at the end of the function name.
- I've tried to follow the above rule in this patch to change a lot of variable name for angular data.

Testing:
- the following branch has been tested in sitl autotest for quadcopter, plane, helicopter and quadplane and successfully passed all those tests.
- remaining untested bits are PosHold mode and Autotune mode. @lthall can you review the control_autotune changes to see if everything is in order.
- I've reviewed the patches myself couple of time, but seeing the scope of changes I would love to have more sets of eyes go through it, so @OXINARF, @rmackay9 if you can find time it would be great if you can skim through this pr.

### CODE REVIEW

**Comment by OXINARF** [comment]
Before I thoroughly review this quite big patch I want to say that:

- I don't agree with adding *_rad* everywhere. If a variable or function doesn't use SI units then it should have the unit added to its name. But when it uses SI units I don't see a need to have it, documentation should be enough to clear any doubt.
- I've seen that you use both radians()/degrees() and DEG_TO_RAD/RAD_TO_DEG, why is that?

As a final note I think this is great to have. In my opinion, the only place to use degrees is in the parameters and logs, all other code should use radians.

**Comment by bugobliterator** [comment]
@OXINARF you case of not using _rad everywhere makes sense if in current scenario the rule of non SI unit parameters had relevant unit attached to them, which is not the case, so at least until having SI unit becomes an Ardupilot wide thing I don't agree with not mentioning the units even if they are SI as that could lead to confusion especially when someone tries to rebase older work done with variable that was non SI unit earlier and rebases it, with _rad added such a work rebase will give compile time error and developer could very easily trace the issue.
For the second point I chose to use  DEG_TO_RAD/RAD_TO_DEG mostly for preprocessors and calculations, radians/degrees are used mostly in code for standalone values/variables. There might be exceptions but very rare, one or two at most.
Third point yes, I agree, and that is the case especially taken care of in this patch, parameters and patches are still denoted in degrees/centidegrees or atleast representation is done in a way that user only has to change degree values.

**Comment by OXINARF** [comment]
> you case of not using _rad everywhere makes sense if in current scenario the rule of non SI unit parameters had relevant unit attached to them, which is not the case, so at least until having SI unit becomes an Ardupilot wide thing I don't agree with not mentioning the units even if they are SI as that could lead to confusion especially when someone tries to rebase older work done with variable that was non SI unit earlier and rebases it, with _rad added such a work rebase will give compile time error and developer could very easily trace the issue.

You mean that there are places that use non-SI values and don't have it in their names? I don't see how changing the name of the ones using SI units would improve the situation. If anything, what should be done is changing those places where non-SI is used to have it in the name.
Regarding rebasing old work: that's something that can happen, that is why we have code review and tests running for every PR.

Regarding radians/degrees, those are inline functions from AP_Math that do the same as using DEG_TO_RAD/RAD_TO_DEG directly. So I think all places should use radians/degrees.

**Comment by magicrub** [comment]
This may want to wait for 3.4 to get released.

**Comment by bugobliterator** [comment]
@OXINARF first of all having unit attached to var name is not going to be a regression. I believe that we have a very awesome code review system in place, but again having an extra level of security is only going to help not hurt. Another point I missed is this also helps keeping track of which variables and functions are converted to use radians/or any other unit, and this process of conversion could be continued without going through everything again. In a nutshell I only see a lot pros and only one con i.e. variable name length is increased by 2-4 characters, which is still not that much considering the benefits.
BTW I agree on the point raised raised against using DEG_TO_RAD/RAD_TO_DEG. I will make this change, and should be an easy fix.
@magicrub I got @rmackay9 thoughts before starting on this, I got the feeling he is interested in getting this in now. But I would let @rmackay9 share what he thinks is best.

**Comment by magicrub** [comment]
... just something else to delay 3.4 release...

**Comment by OXINARF** [comment]
@bugobliterator I never liked that variables and functions have units in their names, that's what documentation is for. But if you talked about this with Randy, then it's fine, he has the final word.

**Comment by bugobliterator** [comment]
@OXINARF can you elaborate on the reason of your dislike? 
The documentation is there to explain the details of the parameter/function among other things and so is the purpose of parameter name, except it needs to be concise, and that is clearly not going to be lost with addition of 2-3 letters, and pros of that as I mentioned already are abundant.

**Comment by OXINARF** [comment]
@bugobliterator It gives longer names and many times I don't need it to know the unit it is in. Then you have a function with variables that "all" end with *_rad*, it makes it harder for me to see the different variables. This is a personal preference, not a technical one. Since you have talked about it with Randy, that's settled.
Once you have changed the RAD_TO_DEG/DEG_TO_RAD to degrees/radians, please ping me and I'll review this.

**Comment by rmackay9** [comment]
I agree with @magicrub that the impact on Copter-3.4 isn't good.  So we should discuss the timing in the dev meeting maybe.  The options are put it in for Copter-3.5 and suffer with merge conflicts between 3.4 and 3.5 or delay the copter-3.4 release so this change can be tested.

Ideally the _rad extension on variables names should be required if we consider that the default.  So normally the idea has been that SI units don't have an extension on them, all non-SI units do have an extension.

**Comment by proficnc** [comment]
please no more delays to 3.4... 3.5 would be better.

**Comment by R-Lefebvre** [comment]
+1.  I believe it's going to be a year since AC3.3 was released.

**Comment by kwikius** [comment]
Great idea to uniformly use a unit suffix. 
Strongly Disagree that you should not do this and  just use external documentation. In practise anything you can document in code itself is much superior since external documentation often fails to keep up. For evidence look to the Wiki.
Documenting in code itself is also faster, since you don't need to track down where the documentation is. Would also do this for functions that return physical quantities. Why not?
As for using SI units only everywhere, I think that it is best not to be dogmatic. Radians are not as intuitive as degrees or even revolutions.  So for example, try thinking what  90 degrees is in radians, or 1/3rd revolution in radians.  See for example the compass orientations. Try converting those to radians and see users complain :)
However SI units are good for code speed ( no conversion constants), so make sense where user understanding is not a great issue

**Comment by OXINARF** [comment]
> Why not?

Because it is ugly and takes space. If everything without suffix is SI and non-SI variables are suffixed, you don't need to look at documentation.
And documentation only doesn't keep up if we don't enforce it. And if we didn't enforce things, then a suffix also won't work.

> As for using SI units only everywhere, I think that it is best not to be dogmatic.

That wasn't even up for discussion, everything that is user-facing needs to be in degrees.

**Comment by kwikius** [comment]
@OXINARF  Sorry but your arguments don't stack up.

I'm not going to argue forever about whether code is ugly or not. That is subjective and frankly a waste of breath arguing in that way.

Code should be self documenting. If you disagree with that ... I'm Out :)

A particular quantity can be expressed in SI units using prefixes so just saying a quantity is in SI units isnt exact. So for example:

https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_Common/AP_Common.h#L130

That is in SI units, but is going to cause a lot of problems unless you go read the header again again again, which is slower than typing alt_cm isnt it?  Now would you want to change that to meters? No because it is the best unit for the situation.

In my experience, being explicit about every the units of every physical quantity With No Exceptions saves a huge amount of time.

**Comment by OXINARF** [comment]
> This is a personal preference, not a technical one.

Humm... who said that? Oh wait, it was me!...

> A particular quantity can be expressed in SI units using prefixes

Oh you are right, I should have said coherent SI units.

> Since you have talked about it with Randy, that's settled.

Not sure why after 5 days I said it was settled you came to argue about it but alright.

**Comment by kwikius** [comment]
The PR is actually concerned with standardising a code convention when creating symbols with units, a subject which comes up quite often, so how about deciding on this formally once and for all and making it a part of the Ardupilot Style Guide?

E.g in the Names section

http://ardupilot.org/dev/docs/style-guide.html#names

In new PR's after Release X/ Date X, every symbol that represents/returns a physical quantity must use a standard suffix which describes the units that its numeric value represents. 
Example symbols are variables, functions that return a physical quantity, formal arguments (parameters) and function arguments.

NOTE: We welcome PR's that convert symbols in existing code to use this convention!

The suffixes are (TBD)

_ms          milliseconds
_us          microseconds
_ns          nanoseconds
_m           meters (metres)  // disambigation most used
_minutes     minutes          // time
_minutes_of_arc               // angle
_mm          millimeters
_Pa          pascals
_hPa         hectopascals

etc  ( add all known suffixes used)

Q: Why require this?

A: It makes code self documenting and so helps to expose and prevent errors involving unit conversions and saves time consulting external documentation
---
Q: Why require it on function names?

A: It makes functions self-documenting at the call site.
---
Q: Why require a suffix on symbols representing base units?

A: It makes the unit explicit. On symbols without suffixes, you will need to consult external documentation as to the unit the numeric value of a physical quantity is expressed in. It may be in SI base units but you can't be sure.

**Comment by bugobliterator** [comment]
I like the idea of adding info on naming guidelines for variables denoting physical quantities to be a point in style guide. And should be strictly followed for any and all PR that follow this PR's merge. The discussion on "what those guidelines should be?" is perfect to be taken up during dev call, @CraigElder FYI.

**Comment by lvale** [comment]
I really like the approach @kwikius proposed, and should go as soon as possible. Only issue would be to keep track of what has changed on the existing code to the new units convention.

**Comment by bugobliterator** [comment]
Stale PR, closing

**Pull request closed without merging**
