### PR TITLE
Silt: Make flightgear view optional, rename some parameters for readability

### PR DESCRIPTION
**Pull request by khancyr**

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
I like consistency. We use rcin and rcout in the HAL layer. I think it should use it here as well.

**Comment by khancyr** [comment]
@lucasdemarchi rework done !

**Comment by OXINARF** [comment]
@khancyr This changes the default of always using FlightGear to only use with the flag, right? I think that's the correct way to do it, but we might want to get more opinions in that.

**Comment by tridge** [comment]
I like having the fg viewer by default, though I'd be quite happy to disable it with a flag

**Comment by khancyr** [comment]
@OXINARF @tridge Ok I revert to let the port open by default, I also make the port variable with instance number, otherwise in multisitl it won't work !

**Comment by OXINARF** [comment]
@khancyr LGTM, but I'd like to get @tridge's certificate of approval :smile:

**Comment by tridge** [comment]
applied, thanks!

**Pull request merged**
